In [141]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as sch
import seaborn as sns

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm
from sklearn.utils.class_weight import compute_class_weight

In [142]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [143]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722870  43.075001  42.314999  102223600
1  2018-01-03  40.715771  43.637501  42.990002  118071600
2  2018-01-04  40.904903  43.367500  43.020000   89738400
3  2018-01-05  41.370628  43.842499  43.262501   94640000
4  2018-01-08  41.216957  43.902500  43.482498   82271200
5  2018-01-09  41.212227  43.764999  43.352501   86336000
6  2018-01-10  41.202774  43.575001  43.250000   95839600
7  2018-01-11  41.436813  43.872501  43.622501   74670800
8  2018-01-12  41.864700  44.340000  43.912498  101672400
9  2018-01-16  41.651936  44.847500  44.035000  118263600
10 2018-01-17  42.339882  44.812500  43.767502  137547200
11 2018-01-18  42.377697  45.025002  44.562500  124773600
12 2018-01-19  42.188580  44.895000  44.352501  129700400
13 2018-01-22  41.843433  44.445000  44.150002  108434400
14 2018-01-23  41.852890  44.860001  44.205002  130756400
15 2018-01-24  41.186226  44.325001  43.299999  204420400
16 2018-01-25  40.451008  43.737499  42.632500  166116000
17 2018-01-26  40.545567  43.000000  42.514999  156572000
18 2018-01-29  39.706337  42.540001  41.767502  202561600
19 2018-01-30  39.472301  41.842499  41.174999  184192800
20 2018-01-31  39.581047  42.110001  41.625000  129915600
21 2018-02-01  39.663792  42.154999  41.689999  188923200
22 2018-02-02  37.942776  41.700001  40.025002  346375200
23 2018-02-05  36.994793  40.970001  39.000000  290954000
24 2018-02-06  38.540871  40.930000  38.500000  272975200
25 2018-02-07  37.715820  40.849998  39.767502  206434400
26 2018-02-08  36.678009  40.250000  38.757500  217562000
27 2018-02-09  37.126633  39.472500  37.560001  282690400
28 2018-02-12  38.622044  40.972500  39.377499  243278000
29 2018-02-13  39.008957  41.187500  40.412498  130196800
30 2018-02-14  39.728180  41.884998  40.720001  162579600
31 2018-02-15  41.062187  43.272499  42.250000  204588800
32 2018-02-16  40.929253  43.705002  42.942501  160704400
33 2018-02-20  40.791588  43.564999  42.855000  135722000
34 2018-02-21  40.606445  43.529999  42.752499  149886400
35 2018-02-22  40.945881  43.487499  42.927502  123967600
36 2018-02-23  41.657978  43.912498  43.384998  135249600
37 2018-02-26  42.481647  44.847500  44.052502  152648800
38 2018-02-27  42.343971  45.119999  44.540001  155712400
39 2018-02-28  42.279884  45.154999  44.512501  151128400
40 2018-03-01  41.539303  44.945000  43.165001  195208000
41 2018-03-02  41.826504  44.075001  43.112499  153816000
42 2018-03-05  41.971310  44.435001  43.630001  113605600
43 2018-03-06  41.935703  44.562500  44.032501   95154000
44 2018-03-07  41.546410  43.962502  43.567501  126814000

In [144]:
time_step = 44

In [145]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [146]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [147]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma_s = talib.SMA(data["Adj Close"], timeperiod=20)
    sma_l = talib.SMA(data["Adj Close"], timeperiod=50)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA_SHORT': sma_s,
        'SMA_LONG': sma_l,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [148]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724167,117105600.0
15,NaN,NaN,55.580742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706163,-87314800.0
16,NaN,NaN,45.152446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695099,-253430800.0
17,NaN,NaN,46.541677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034595,-73.817842,2.684663,-96858800.0
18,NaN,NaN,37.470383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639400,-81.393345,2.635361,-299420400.0
19,NaN,NaN,35.398354,NaN,NaN,42.761513,41.213175,39.664837,41.213175,NaN,NaN,-61.987909,-75.553968,2.599704,-483613200.0
20,NaN,NaN,37.137803,NaN,NaN,42.849896,41.156084,39.462271,41.156084,NaN,NaN,-49.633888,-63.087066,2.602418,-353697600.0
21,NaN,NaN,38.494843,NaN,NaN,42.910290,41.103485,39.296679,41.103485,NaN,NaN,-41.626447,-51.082748,2.600384,-164774400.0
22,NaN,NaN,25.947954,NaN,NaN,43.228468,40.955379,38.682289,40.955379,NaN,NaN,-40.765989,-44.008775,2.560086,-511149600.0
23,NaN,NaN,21.743877,NaN,NaN,43.578807,40.736587,37.894367,40.736587,NaN,NaN,-38.059358,-40.150598,2.593453,-802103600.0
24,NaN,NaN,39.079722,NaN,NaN,43.590203,40.602782,37.615361,40.602782,NaN,NaN,-24.766527,-34.530625,2.689293,-529128400.0
25,NaN,NaN,34.666367,NaN,NaN,43.652099,40.427962,37.203825,40.427962,NaN,NaN,-14.972484,-25.932790,2.662138,-735562800.0
26,NaN,NaN,30.066706,NaN,NaN,43.790970,40.201724,36.612478,40.201724,NaN,NaN,-13.427890,-17.722301,2.652998,-953124800.0
27,NaN,NaN,34.135074,NaN,NaN,43.765508,39.986215,36.206921,39.986215,NaN,NaN,-15.615533,-14.671969,2.663105,-670434400.0
28,NaN,NaN,45.513629,NaN,NaN,43.544883,39.824082,36.103281,39.824082,NaN,NaN,-6.295046,-11.779490,2.747588,-427156400.0
29,NaN,NaN,48.015938,NaN,NaN,43.330502,39.691933,36.053364,39.691933,NaN,NaN,11.072632,-3.612649,2.734579,-296959600.0
30,NaN,NaN,52.392777,NaN,NaN,42.991933,39.561348,36.130763,39.561348,NaN,NaN,26.336895,10.371494,2.744683,-134380000.0
31,NaN,NaN,59.246607,NaN,NaN,42.753754,39.495572,36.237391,39.495572,NaN,NaN,41.539683,26.316403,2.801800,70208800.0
32,NaN,NaN,58.345182,NaN,NaN,42.524615,39.432606,36.340598,39.432606,NaN,NaN,51.997605,39.958061,2.790444,-90495600.0
33,-0.373864,-0.940885,57.371687,NaN,NaN,42.339136,39.380014,36.420892,39.380014,NaN,NaN,56.241818,49.926368,2.779394,-226217600.0
34,-0.274209,-0.807550,56.017981,NaN,NaN,42.113880,39.317692,36.521503,39.317692,NaN,NaN,52.331331,53.523585,2.776467,-376104000.0
35,-0.165929,-0.679226,57.975754,NaN,NaN,42.071539,39.305674,36.539810,39.305674,NaN,NaN,52.421531,53.664893,2.783937,-252136400.0
36,-0.022398,-0.547860,61.815808,NaN,NaN,42.278024,39.366023,36.454022,39.366023,NaN,NaN,56.395139,53.716000,2.796986,-116886800.0
37,0.156016,-0.407085,65.717946,NaN,NaN,42.641730,39.462827,36.283924,39.462827,NaN,NaN,62.381636,57.066102,2.825024,35762000.0
38,0.283038,-0.269060,64.530874,NaN,NaN,43.012923,39.594709,36.176494,39.594709,NaN,NaN,65.108403,61.295060,2.811690,-119950400.0
39,0.374219,-0.140404,63.951790,NaN,NaN,43.346791,39.735088,36.123384,39.735088,NaN,NaN,64.320047,63.936696,2.811643,-271078800.0
40,0.382315,-0.035861,57.527340,NaN,NaN,43.527909,39.833001,36.138092,39.833001,NaN,NaN,59.272797,62.900416,2.801177,-466286800.0
41,0.407212,0.052754,59.237519,NaN,NaN,43.735166,39.941136,36.147107,39.941136,NaN,NaN,52.309003,58.633949,2.782214,-312470800.0
42,0.433629,0.128929,60.109656,NaN,NaN,43.918540,40.142563,36.366586,40.142563,NaN,NaN,42.550452,51.377417,2.769806,-198865200.0
43,0.446543,0.192452,59.771014,NaN,NaN,43.949841,40.389608,36.829376,40.389608,NaN,40.596320,34.223066,43.027507,2.757047,-294019200.0
44,0.420518,0.238065,56.052847,4.051359,0.82354,44.028294,40.539885,37.051477,40.539885,NaN,40.638546,12.020182,29.597900,2.704887,-420833200.0

In [149]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722870
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715771
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904903
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370628
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216957
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212227
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202774
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436813
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864700
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651936
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339882
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377697
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188580
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843433
14,NaN,NaN,68.998425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724167,117105600.0,41.852890
15,NaN,NaN,55.580742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706163,-87314800.0,41.186226
16,NaN,NaN,45.152446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695099,-253430800.0,40.451008
17,NaN,NaN,46.541677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034595,-73.817842,2.684663,-96858800.0,40.545567
18,NaN,NaN,37.470383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639400,-81.393345,2.635361,-299420400.0,39.706337
19,NaN,NaN,35.398354,NaN,NaN,42.761513,41.213175,39.664837,41.213175,NaN,NaN,-61.987909,-75.553968,2.599704,-483613200.0,39.472301
20,NaN,NaN,37.137803,NaN,NaN,42.849896,41.156084,39.462271,41.156084,NaN,NaN,-49.633888,-63.087066,2.602418,-353697600.0,39.581047
21,NaN,NaN,38.494843,NaN,NaN,42.910290,41.103485,39.296679,41.103485,NaN,NaN,-41.626447,-51.082748,2.600384,-164774400.0,39.663792
22,NaN,NaN,25.947954,NaN,NaN,43.228468,40.955379,38.682289,40.955379,NaN,NaN,-40.765989,-44.008775,2.560086,-511149600.0,37.942776
23,NaN,NaN,21.743877,NaN,NaN,43.578807,40.736587,37.894367,40.736587,NaN,NaN,-38.059358,-40.150598,2.593453,-802103600.0,36.994793
24,NaN,NaN,39.079722,NaN,NaN,43.590203,40.602782,37.615361,40.602782,NaN,NaN,-24.766527,-34.530625,2.689293,-529128400.0,38.540871
25,NaN,NaN,34.666367,NaN,NaN,43.652099,40.427962,37.203825,40.427962,NaN,NaN,-14.972484,-25.932790,2.662138,-735562800.0,37.715820
26,NaN,NaN,30.066706,NaN,NaN,43.790970,40.201724,36.612478,40.201724,NaN,NaN,-13.427890,-17.722301,2.652998,-953124800.0,36.678009
27,NaN,NaN,34.135074,NaN,NaN,43.765508,39.986215,36.206921,39.986215,NaN,NaN,-15.615533,-14.671969,2.663105,-670434400.0,37.126633
28,NaN,NaN,45.513629,NaN,NaN,43.544883,39.824082,36.103281,39.824082,NaN,NaN,-6.295046,-11.779490,2.747588,-427156400.0,38.622044
29,NaN,NaN,48.015938,NaN,NaN,43.330502,39.691933,36.053364,39.691933,NaN,NaN,11.072632,-3.612649,2.734579,-296959600.0,39.008957
30,NaN,NaN,52.392777,NaN,NaN,42.991933,39.561348,36.130763,39.561348,NaN,NaN,26.336895,10.371494,2.744683,-134380000.0,39.728180
31,NaN,NaN,59.246607,NaN,NaN,42.753754,39.495572,36.237391,39.495572,NaN,NaN,41.539683,26.316403,2.801800,70208800.0,41.062187
32,NaN,NaN,58.345182,NaN,NaN,42.524615,39.432606,36.340598,39.432606,NaN,NaN,51.997605,39.958061,2.790444,-90495600.0,40.929253
33,-0.373864,-0.940885,57.371687,NaN,NaN,42.339136,39.380014,36.420892,39.380014,NaN,NaN,56.241818,49.926368,2.779394,-226217600.0,40.791588
34,-0.274209,-0.807550,56.017981,NaN,NaN,42.113880,39.317692,36.521503,39.317692,NaN,NaN,52.331331,53.523585,2.776467,-376104000.0,40.606445
35,-0.165929,-0.679226,57.975754,NaN,NaN,42.071539,39.305674,36.539810,39.305674,NaN,NaN,52.421531,53.664893,2.783937,-252136400.0,40.945881
36,-0.022398,-0.547860,61.815808,NaN,NaN,42.278024,39.366023,36.454022,39.366023,NaN,NaN,56.395139,53.716000,2.796986,-116886800.0,41.657978
37,0.156016,-0.407085,65.717946,NaN,NaN,42.641730,39.462827,36.283924,39.462827,NaN,NaN,62.381636,57.066102,2.825024,35762000.0,42.481647
38,0.283038,-0.269060,64.530874,NaN,NaN,43.012923,39.594709,36.176494,39.594709,NaN,NaN,65.108403,61.295060,2.811690,-119950400.0,42.343971
39,0.374219,-0.140404,63.951790,NaN,NaN,43.346791,39.735088,36.123384,39.735088,NaN,NaN,64.320047,63.936696,2.811643,-271078800.0,42.279884
40,0.382315,-0.035861,57.527340,NaN,NaN,43.527909,39.833001,36.138092,39.833001,NaN,NaN,59.272797,62.900416,2.801177,-466286800.0,41.539303
41,0.407212,0.052754,59.237519,NaN,NaN,43.735166,39.941136,36.147107,39.941136,NaN,NaN,52.309003,58.633949,2.782214,-312470800.0,41.826504
42,0.433629,0.128929,60.109656,NaN,NaN,43.918540,40.142563,36.366586,40.142563,NaN,NaN,42.550452,51.377417,2.769806,-198865200.0,41.971310
43,0.446543,0.192452,59.771014,NaN,NaN,43.949841,40.389608,36.829376,40.389608,NaN,40.596320,34.223066,43.027507,2.757047,-294019200.0,41.935703
44,0.420518,0.238065,56.052847,4.051359,0.82354,44.028294,40.539885,37.051477,40.539885,NaN,40.638546,12.020182,29.597900,2.704887,-420833200.0,41.546410

In [150]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.567013,0.443929,58.241498,7.100809,1.143604,43.382885,41.728833,40.074780,41.728833,40.814298,41.035720,-7.013507,-3.909741,2.715223,-3.124152e+08,42.355831
1,0.548493,0.464842,58.592091,7.332835,1.202904,43.261029,41.862708,40.464387,41.862708,40.847954,41.096607,-20.016838,-8.448483,2.714433,-2.214400e+08,42.405678
2,0.515805,0.475034,57.044886,6.516228,0.819336,43.280286,41.922406,40.564526,41.922406,40.878762,41.148142,-27.992022,-18.340789,2.690139,-3.790588e+08,42.256149
3,0.432812,0.466590,50.806365,3.052116,-0.254196,43.245415,41.956468,40.667522,41.956468,40.892874,41.168691,-36.985407,-28.331423,2.648797,-5.128460e+08,41.610504
4,0.361720,0.445616,50.674731,2.976533,-0.055672,43.183913,41.996702,40.809492,41.996702,40.897386,41.187695,-46.752088,-37.243173,2.644562,-5.914436e+08,41.596264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [151]:
indicators_with_price['Prev_Adj_Close'] = indicators_with_price['Adj Close'].shift(1)
indicators_with_price['Return'] = ((indicators_with_price['Adj Close'] - indicators_with_price['Prev_Adj_Close'])/indicators_with_price['Prev_Adj_Close'])*100
indicators_with_price['Signal'] = np.where(indicators_with_price['Return'] > 1, 1,
                                           np.where(indicators_with_price['Return'] < -1, 2, 0))
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
0,0.567013,0.443929,58.241498,7.100809,1.143604,43.382885,41.728833,40.074780,41.728833,40.814298,41.035720,-7.013507,-3.909741,2.715223,-3.124152e+08,42.355831,NaN,NaN,0
1,0.548493,0.464842,58.592091,7.332835,1.202904,43.261029,41.862708,40.464387,41.862708,40.847954,41.096607,-20.016838,-8.448483,2.714433,-2.214400e+08,42.405678,42.355831,0.117685,0
2,0.515805,0.475034,57.044886,6.516228,0.819336,43.280286,41.922406,40.564526,41.922406,40.878762,41.148142,-27.992022,-18.340789,2.690139,-3.790588e+08,42.256149,42.405678,-0.352614,0
3,0.432812,0.466590,50.806365,3.052116,-0.254196,43.245415,41.956468,40.667522,41.956468,40.892874,41.168691,-36.985407,-28.331423,2.648797,-5.128460e+08,41.610504,42.256149,-1.527932,2
4,0.361720,0.445616,50.674731,2.976533,-0.055672,43.183913,41.996702,40.809492,41.996702,40.897386,41.187695,-46.752088,-37.243173,2.644562,-5.914436e+08,41.596264,41.610504,-0.034223,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [152]:
indicators_with_price["Signal"].value_counts()

Signal
0    737
1    414
2    324
Name: count, dtype: int64

In [153]:
indicators_with_price.dropna(inplace=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
1,0.548493,0.464842,58.592091,7.332835,1.202904,43.261029,41.862708,40.464387,41.862708,40.847954,41.096607,-20.016838,-8.448483,2.714433,-2.214400e+08,42.405678,42.355831,0.117685,0
2,0.515805,0.475034,57.044886,6.516228,0.819336,43.280286,41.922406,40.564526,41.922406,40.878762,41.148142,-27.992022,-18.340789,2.690139,-3.790588e+08,42.256149,42.405678,-0.352614,0
3,0.432812,0.466590,50.806365,3.052116,-0.254196,43.245415,41.956468,40.667522,41.956468,40.892874,41.168691,-36.985407,-28.331423,2.648797,-5.128460e+08,41.610504,42.256149,-1.527932,2
4,0.361720,0.445616,50.674731,2.976533,-0.055672,43.183913,41.996702,40.809492,41.996702,40.897386,41.187695,-46.752088,-37.243173,2.644562,-5.914436e+08,41.596264,41.610504,-0.034223,0
5,0.226727,0.401838,42.776544,-1.895700,-1.685959,43.175296,41.999076,40.822856,41.999076,40.886126,41.163971,-59.960178,-47.899224,2.611110,-7.396632e+08,40.653923,41.596264,-2.265446,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [154]:
indicators_with_price.columns

Index(['MACD', 'MACD_signal', 'RSI', 'CMO', 'MOM', 'Upper_BB', 'Middle_BB',
       'Lower_BB', 'SMA_SHORT', 'SMA_LONG', 'EMA', 'SLOWK', 'SLOWD', 'ATR',
       'OBV', 'Adj Close', 'Prev_Adj_Close', 'Return', 'Signal'],
      dtype='object')

In [155]:
# indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close', 'Return'])
# indicators_with_price

In [156]:
indicators_with_price.drop(columns=['Prev_Adj_Close', "Signal"], inplace=True)
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Return
1,0.548493,0.464842,58.592091,7.332835,1.202904,43.261029,41.862708,40.464387,41.862708,40.847954,41.096607,-20.016838,-8.448483,2.714433,-2.214400e+08,42.405678,0.117685
2,0.515805,0.475034,57.044886,6.516228,0.819336,43.280286,41.922406,40.564526,41.922406,40.878762,41.148142,-27.992022,-18.340789,2.690139,-3.790588e+08,42.256149,-0.352614
3,0.432812,0.466590,50.806365,3.052116,-0.254196,43.245415,41.956468,40.667522,41.956468,40.892874,41.168691,-36.985407,-28.331423,2.648797,-5.128460e+08,41.610504,-1.527932
4,0.361720,0.445616,50.674731,2.976533,-0.055672,43.183913,41.996702,40.809492,41.996702,40.897386,41.187695,-46.752088,-37.243173,2.644562,-5.914436e+08,41.596264,-0.034223
5,0.226727,0.401838,42.776544,-1.895700,-1.685959,43.175296,41.999076,40.822856,41.999076,40.886126,41.163971,-59.960178,-47.899224,2.611110,-7.396632e+08,40.653923,-2.265446
6,0.072556,0.335982,38.806020,-4.707979,-2.298203,43.330930,41.955757,40.580583,41.955757,40.863471,41.115772,-60.364597,-55.692288,2.604322,-9.056264e+08,40.079494,-1.412972
7,-0.123098,0.244166,33.410025,-9.019884,-3.037205,43.669842,41.830427,39.991011,41.830427,40.822443,41.028466,-57.037731,-59.120835,2.589763,-1.069742e+09,39.151375,-2.315697
8,-0.126721,0.169988,48.771940,0.230796,-0.833466,43.603895,41.756843,39.909790,41.756843,40.813906,41.027644,-35.113228,-50.838519,2.699325,-9.195768e+08,41.009968,4.747197
9,-0.212000,0.093591,42.761384,-4.462394,-1.894463,43.620647,41.637565,39.654484,41.637565,40.775781,40.980123,-25.755979,-39.302313,2.704911,-1.083267e+09,39.958427,-2.564109
10,-0.311617,0.012549,40.504336,-6.346415,-1.669304,43.661172,41.499417,39.337663,41.499417,40.733080,40.915092,-23.129921,-27.999709,2.693601,-1.249941e+09,39.516922,-1.104912
11,-0.361498,-0.062260,42.777699,-4.867424,-0.625507,43.694931,41.413727,39.132523,41.413727,40.682793,40.866666,-31.639027,-26.841642,2.745528,-1.096347e+09,39.825500,0.780877
12,-0.417287,-0.133266,41.338337,-5.999321,-0.981171,43.709491,41.300622,38.891753,41.300622,40.626527,40.808787,-33.350038,-29.372995,2.721526,-1.246694e+09,39.564396,-0.655622
13,-0.423862,-0.191385,44.466544,-4.030411,0.263958,43.655484,41.200571,38.745658,41.200571,40.582161,40.771521,-30.537778,-31.842281,2.714496,-1.125582e+09,39.970295,1.025920
14,-0.363211,-0.225750,49.885921,-0.435740,1.262325,43.579269,41.140517,38.701766,41.140517,40.559985,40.769881,-23.649204,-29.179007,2.737189,-9.871604e+08,40.734627,1.912250
15,-0.289021,-0.238404,51.759447,0.859653,1.436035,43.546088,41.114051,38.682014,41.114051,40.543269,40.780868,-13.681337,-22.622773,2.743310,-8.794276e+08,41.017082,0.693404
16,-0.311294,-0.252982,45.026012,-3.853583,0.304138,43.457725,41.012458,38.567191,41.012458,40.518903,40.744737,-15.941543,-17.757361,2.697567,-1.019449e+09,39.967930,-2.557843
17,-0.293575,-0.261101,47.789717,-2.010542,2.421562,43.223491,40.894606,38.565720,40.894606,40.517169,40.727830,-20.848893,-16.823924,2.740925,-9.033780e+08,40.364338,0.991815
18,-0.215755,-0.252032,52.696858,1.419565,4.129105,42.889424,40.794081,38.698738,40.794081,40.528736,40.745433,-19.855097,-18.881844,2.769120,-7.897436e+08,41.123898,1.881759
19,-0.167664,-0.235158,51.380444,0.543896,2.390762,42.607664,40.704712,38.801759,40.704712,40.553242,40.753709,-10.385073,-17.029687,2.739619,-8.794700e+08,40.931633,-0.467525
20,-0.095885,-0.207303,53.978914,2.354499,3.619335,42.427111,40.653678,38.880245,40.653678,40.590499,40.779551,0.476718,-9.921150,2.745244,-7.879128e+08,41.335155,0.985845
21,-0.027382,-0.171319,54.880265,2.981784,4.797203,42.237335,40.607155,38.976974,40.607155,40.628382,40.810469,4.591657,-1.772232,2.736644,-6.874156e+08,41.475212,0.338832
22,0.047239,-0.127608,56.572371,4.145772,4.607307,42.118853,40.581044,39.043236,40.581044,40.669785,40.851512,13.925066,6.331147,2.724904,-6.011020e+08,41.733940,0.623814
23,0.150987,-0.071889,60.145963,6.689077,3.686317,42.272666,40.615937,38.959208,40.615937,40.757097,40.916261,22.180917,13.565880,2.744629,-4.946804e+08,42.308361,1.376388
24,0.222977,-0.012916,59.277664,6.212425,3.204456,42.395829,40.646795,38.897760,40.646795,40.861469,40.973912,28.084365,21.396782,2.719773,-5.776984e+08,42.213413,-0.224419
25,0.181404,0.025948,49.567793,0.427663,1.288902,42.421430,40.664952,38.908475,40.664952,40.910994,40.975831,20.146099,23.470460,2.642224,-7.169336e+08,41.017082,-2.834007
26,0.012704,0.023300,39.724028,-6.863786,-1.725658,42.461948,40.627804,38.793660,40.627804,40.943408,40.902973,-8.290914,13.313183,2.581202,-9.788980e+08,39.336529,-4.097204
27,-0.128702,-0.007101,39.156272,-7.330548,-1.706661,42.454272,40.631365,38.808458,40.631365,40.994300,40.828290,-34.549947,-7.564921,2.567793,-1.124960e+09,39.222591,-0.289648
28,-0.281575,-0.061996,36.466732,-9.553054,-2.114948,42.515715,40.514699,38.513682,40.514699,41.025300,40.732661,-45.877174,-29.572678,2.552944,-1.259728e+09,38.676640,-1.391932
29,-0.384694,-0.126535,37.885162,-8.729317,-1.761265,42.577348,40.459036,38.340724,40.459036,41.029762,40.648773,-39.397653,-39.941591,2.561902,-1.146200e+09,38.845181,0.435769
30,-0.450308,-0.191290,39.061346,-8.061878,-1.965401,42.610304,40.432214,38.254124,40.432214,41.029193,40.574626,-33.203163,-39.492663,2.563718,-1.034348e+09,38.980480,0.348305
31,-0.532560,-0.259544,36.575174,-9.947375,-3.128498,42.686408,40.367413,38.048418,40.367413,41.005219,40.483731,-32.805882,-35.135566,2.530739,-1.176971e+09,38.529480,-1.156990
32,-0.535265,-0.314688,42.657060,-6.489488,-3.254311,42.697386,40.350560,38.003734,40.350560,40.968522,40.427891,-28.594988,-31.534678,2.584652,-1.007261e+09,39.227337,1.811228
33,-0.458572,-0.343465,49.472275,-2.193913,-2.205143,42.701497,40.358987,38.016477,40.358987,40.952713,40.415044,-18.764674,-26.721848,2.619510,-7.929836e+08,40.138828,2.323613
34,-0.251813,-0.325134,59.544947,5.401813,-0.367928,42.852522,40.417853,37.983184,40.417853,40.975121,40.481573,5.866509,-13.831051,2.739450,-5.268260e+08,41.911957,4.417489
35,-0.080893,-0.276286,59.913611,5.709021,0.448612,42.984210,40.466395,37.948580,40.466395,41.002750,40.548522,25.969029,4.356955,2.719707,-3.905532e+08,41.987915,0.181233
36,0.185352,-0.183959,66.948302,12.047580,1.808750,43.506952,40.649761,37.792570,40.649761,41.056538,40.685710,45.736693,25.857410,2.816484,-1.657480e+08,43.635254,3.923364
37,0.417020,-0.063763,68.103517,13.191912,1.979641,44.022551,40.829092,37.635633,40.829092,41.102397,40.830832,51.666130,41.123951,2.849752,4.057600e+06,43.950951,0.723490
38,0.610626,0.071115,68.887205,13.958474,2.226509,44.489629,40.981008,37.472387,40.981008,41.136008,40.978893,58.084165,51.828996,2.832202,1.176688e+08,44.162212,0.480676
39,0.780159,0.212924,70.053472,15.087769,2.926750,44.982157,41.158084,37.334011,41.158084,41.178592,41.134194,59.732851,56.494382,2.821887,2.105136e+08,44.473160,0.704103
40,0.954838,0.361307,72.337966,17.358392,3.109501,45.541697,41.346791,37.151885,41.346791,41.235180,41.310865,63.227857,60.348291,2.843133,3.224708e+08,45.109295,1.430380
41,1.067129,0.502471,70.769988,16.498700,2.216362,45.997978,41.519917,37.041857,41.519917,41.303149,41.472059,64.911990,62.624232,2.811889,2.176220e+08,44.937737,-0.380317
42,1.134580,0.628893,69.774584,15.967458,1.698486,46.380498,41.674865,36.969231,41.674865,41.363277,41.621430,64.592791,64.244213,2.785665,1.345068e+08,44.832890,-0.233316
43,1.141994,0.731513,65.895584,13.902004,1.706421,46.631597,41.780718,36.929839,41.780718,41.412359,41.746052,61.526820,63.677200,2.724876,3.972600e+07,44.425430,-0.908840
44,1.167862,0.818783,67.853943,15.469600,2.484211,46.941610,41.912049,36.882489,41.912049,41.470446,41.883563,61.088827,62.402813,2.722354,1.164584e+08,44.840042,0.933276
45,1.152201,0.885466,65.100690,14.016858,2.150810,47.228049,42.089020,36.949990,42.089020,41.530648,42.002359,59.272362,60.629336,2.698433,4.728240e+07,44.556488,-0.632368
46,1.113874,0.931148,63.514709,13.184215,2.138306,47.411587,42.341916,37.272245,42.341916,41.578541,42.108675,56.482997,58.948062,2.676831,-2.590840e+07,44.394455,-0.363658
47,1.096243,0.964167,65.282779,14.425512,3.098480,47.573566,42.616236,37.658905,42.616236,41.618293,42.224244,45.620387,53.791915,2.694418,4.769480e+07,44.708984,0.708488
48,1.061003,0.983534,64.091787,13.832495,3.000725,47.592554,42.912253,38.231953,42.912253,41.647545,42.329699,34.736724,45.613369,2.681318,-1.326800e+07,44.596989,-0.250499
49,1.044112,0.995650,65.806987,14.983597,4.229012,47.574091,43.214141,38.854190,43.214141,41.690823,42.443176,22.112280,34.156464,2.670368,6.696560e+07,44.882935,0.641178
50,1.014988,0.999518,65.219820,14.709169,4.753395,47.457199,43.506761,39.556324,43.506761,41.740364,42.549386,-9.602639,15.748788,2.645846,-2.597040e+07,44.832890,-0.111501

In [157]:
y = indicators_with_price["Return"]
y_2 = indicators_with_price["SMA_SHORT"]
y_3 = indicators_with_price["EMA"]
y_4 = indicators_with_price["Upper_BB"]
y_5 = indicators_with_price["Middle_BB"]
y_6 = indicators_with_price["Lower_BB"]
X = np.array(date)

trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



layout = go.Layout(
    title='Stock Price and Volume',
    xaxis=dict(title='Date'),
    yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
    yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
    height=600,
)

fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# Show plot
pyo.iplot(fig)

In [158]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        # Extract a window of data from X
        X_window = self.X[idx : idx + self.window_size]
        
        # Assuming you're predicting the value right after the window
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [159]:
X = indicators_with_price.iloc[:,:-1]
y = indicators_with_price.iloc[:,-2]

signal_true = indicators_with_price.iloc[:,-1]
y

1        42.405678
2        42.256149
3        41.610504
4        41.596264
5        40.653923
           ...
1470    182.679993
1471    188.630005
1472    191.559998
1473    193.889999
1474    195.179993
Name: Adj Close, Length: 1474, dtype: float64

In [160]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1180    1.297126
1181    0.378196
1182   -2.168029
1183    1.466111
1184    0.592655
          ...
1470   -0.517351
1471    3.257068
1472    1.553301
1473    1.216330
1474    0.665322
Name: Return, Length: 295, dtype: float64

In [161]:
correlation_matrix = X.corr()

# Perform hierarchical clustering to find the order of features
linked = sch.linkage(sch.distance.pdist(correlation_matrix), method='ward')
cluster_order = sch.dendrogram(linked, no_plot=True)['leaves']

# Reorder the correlation matrix
correlation_matrix_ordered = correlation_matrix.iloc[cluster_order, cluster_order]

fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix_ordered,
                    x=correlation_matrix_ordered.columns,
                    y=correlation_matrix_ordered.columns,
                    colorscale='Viridis',
                    text=correlation_matrix_ordered.round(2).values, 
                    texttemplate="%{text}",
                    textfont={"size":9}  
                    ))

fig.update_layout(
    title='Ordered Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  
    height=1000,  
)

pyo.iplot(fig)

In [162]:
X= X.iloc[:, cluster_order]

In [163]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

y_test.head(44)

1180    149.882217
1181    150.449066
1182    147.187286
1183    149.345215
1184    150.230316
1185    147.286728
1186    143.418350
1187    140.385315
1188    147.207184
1189    147.485626
1190    146.988403
1191    145.814972
1192    142.115646
1193    140.156586
1194    141.857086
1195    141.369812
1196    143.686859
1197    144.661423
1198    142.413971
1199    135.741272
1200    133.762329
1201    131.634216
1202    131.564621
1203    134.697113
1204    131.494995
1205    131.127060
1206    129.307236
1207    125.339409
1208    128.889572
1209    129.207794
1210    124.374794
1211    125.657639
1212    124.325073
1213    128.899506
1214    129.426559
1215    130.003342
1216    132.748016
1217    132.668457
1218    134.010941
1219    135.184372
1220    134.458435
1221    134.518112
1222    137.103653
1223    140.325653
Name: Adj Close, dtype: float64

In [164]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

X_train_df = X_train
X_test_df = X_test

for column in X_train.columns:

    if column not in ["Adj Close", "Return"]:
        scaler = MinMaxScaler()

        X_train_scaled = scaler.fit_transform(X_train[[column]].values)
        X_train_df[column] = X_train_scaled
            
        X_test_scaled = scaler.transform(X_test[[column]].values)
        X_test_df[column] = X_test_scaled

        scaler_dict[column] = scaler


X_train_df.head(24)

features = X_train_df.columns
X_train_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1,0.177936,0.261686,42.405678,0.048691,0.032213,0.037797,0.037797,0.016755,0.014072,0.483866,0.507174,0.508804,0.493383,0.498960,0.567548,0.468235
2,0.172548,0.234481,42.256149,0.049438,0.032346,0.038231,0.038231,0.016988,0.014472,0.447235,0.458579,0.506461,0.494198,0.494287,0.542888,0.458079
3,0.163380,0.211390,41.610504,0.050206,0.032106,0.038478,0.038478,0.017095,0.014632,0.405928,0.409500,0.500513,0.493523,0.481206,0.443455,0.414999
4,0.162440,0.197825,41.596264,0.051265,0.031682,0.038770,0.038770,0.017129,0.014780,0.361069,0.365721,0.495417,0.491846,0.483625,0.441357,0.414059
5,0.155021,0.172243,40.653923,0.051365,0.031623,0.038787,0.038787,0.017044,0.014595,0.300403,0.313374,0.485741,0.488346,0.463760,0.315471,0.353467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,0.850805,0.753803,146.053619,0.738088,0.800862,0.778358,0.778358,0.818604,0.829435,0.680159,0.631199,0.340107,0.343542,0.360230,0.463732,0.349552
1176,0.849088,0.770024,148.867889,0.744000,0.803314,0.782527,0.782527,0.817400,0.830427,0.747328,0.665570,0.388138,0.347930,0.321213,0.506323,0.377027
1177,0.803297,0.757360,147.455780,0.746416,0.805266,0.784731,0.784731,0.816305,0.830887,0.835637,0.739664,0.418622,0.358241,0.420018,0.480797,0.363377
1178,0.812803,0.772871,149.206009,0.747900,0.808367,0.787087,0.787087,0.815668,0.831932,0.856512,0.802536,0.453092,0.374178,0.423562,0.508857,0.380639
1179,0.765326,0.761787,147.962952,0.749683,0.810260,0.788953,0.788953,0.814627,0.832500,0.850520,0.839325,0.473178,0.391410,0.443981,0.484406,0.368317

In [165]:
scaler_adj = MinMaxScaler()
scaler_adj.fit(X_train[["Adj Close"]].values)

X_train_df['Adj Close'] = scaler_adj.transform(X_train[['Adj Close']].values).flatten()
X_test_df['Adj Close'] = scaler_adj.transform(X_test[['Adj Close']].values).flatten()

y_train = scaler_adj.transform(y_train.values.reshape(-1,1)).flatten()
y_test = scaler_adj.transform(y_test.values.reshape(-1,1)).flatten()



X_test_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1180,0.764804,0.775662,0.793797,0.751875,0.813419,0.791684,0.791684,0.814103,0.833706,0.876576,0.853920,0.499847,0.411144,0.487570,0.517394,0.387564
1181,0.724522,0.788577,0.797684,0.752021,0.816204,0.793223,0.793223,0.813227,0.835055,0.895161,0.867699,0.523637,0.432238,0.448749,0.527281,0.393264
1182,0.685712,0.778442,0.775317,0.751879,0.815519,0.792793,0.792793,0.810946,0.835217,0.907286,0.887937,0.523008,0.448973,0.379730,0.456307,0.359879
1183,0.661729,0.787383,0.790114,0.752318,0.813808,0.792104,0.792104,0.810434,0.836117,0.913913,0.901248,0.534244,0.464868,0.444493,0.497611,0.382098
1184,0.623617,0.797445,0.796184,0.752139,0.815320,0.792815,0.792815,0.809834,0.837282,0.923476,0.911343,0.547370,0.480511,0.467133,0.514480,0.391192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,0.263755,0.912203,1.018693,1.078159,1.105702,1.104494,1.104494,1.140327,1.152418,0.696649,0.699736,0.331987,0.360467,0.438975,0.219194,0.330143
1471,0.316961,0.925666,1.059493,1.079371,1.099583,1.101858,1.101858,1.142176,1.152792,0.728273,0.697239,0.358007,0.354748,0.530972,0.456178,0.434230
1472,0.316624,0.937531,1.079584,1.082407,1.093074,1.099905,1.099905,1.144078,1.154161,0.814261,0.731129,0.396416,0.358741,0.534505,0.541662,0.480565
1473,0.323439,0.947909,1.095561,1.083019,1.091863,1.099564,1.099564,1.145941,1.156274,0.926300,0.813002,0.440664,0.371807,0.555951,0.601115,0.515680
1474,0.300461,0.955220,1.104406,1.082644,1.092553,1.099746,1.099746,1.147838,1.158738,0.984412,0.904318,0.483036,0.391711,0.550955,0.631898,0.534630

In [168]:
correlation_matrix = X_train_df.corr()

fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values, 
                    texttemplate="%{text}",
                    textfont={"size":9}  
                    ))

fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  
    height=1000,  
)

# Show the figure
pyo.iplot(fig)

In [169]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train, dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test, dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(1)[0])

tensor(0.7379, device='cuda:0')
tensor([[0.7245, 0.7886, 0.7977, 0.7520, 0.8162, 0.7932, 0.7932, 0.8132, 0.8351,
         0.8952, 0.8677, 0.5236, 0.4322, 0.4487, 0.5273, 0.3933],
        [0.6857, 0.7784, 0.7753, 0.7519, 0.8155, 0.7928, 0.7928, 0.8109, 0.8352,
         0.9073, 0.8879, 0.5230, 0.4490, 0.3797, 0.4563, 0.3599],
        [0.6617, 0.7874, 0.7901, 0.7523, 0.8138, 0.7921, 0.7921, 0.8104, 0.8361,
         0.9139, 0.9012, 0.5342, 0.4649, 0.4445, 0.4976, 0.3821],
        [0.6236, 0.7974, 0.7962, 0.7521, 0.8153, 0.7928, 0.7928, 0.8098, 0.8373,
         0.9235, 0.9113, 0.5474, 0.4805, 0.4671, 0.5145, 0.3912],
        [0.5981, 0.7914, 0.7760, 0.7537, 0.8163, 0.7941, 0.7941, 0.8092, 0.8374,
         0.9237, 0.9172, 0.5399, 0.4914, 0.4592, 0.4471, 0.3605],
        [0.5869, 0.7794, 0.7495, 0.7546, 0.8078, 0.7900, 0.7900, 0.8083, 0.8361,
         0.8756, 0.9035, 0.5112, 0.4936, 0.4080, 0.3677, 0.3216],
        [0.5854, 0.7650, 0.7287, 0.7521, 0.8019, 0.7857, 0.7857, 0.8063, 0.8339,
         0.7960, 0.8581, 0.4709, 0.4865, 0.3590, 0.3118, 0.2921],
        [0.6453, 0.7842, 0.7755, 0.7524, 0.8000, 0.7849, 0.7849, 0.8050, 0.8341,
         0.7774, 0.8059, 0.4782, 0.4824, 0.4654, 0.4544, 0.3639],
        [0.6088, 0.7965, 0.7774, 0.7533, 0.8016, 0.7861, 0.7861, 0.8043, 0.8344,
         0.7888, 0.7750, 0.4855, 0.4807, 0.5578, 0.4597, 0.3667],
        [0.5723, 0.7852, 0.7740, 0.7605, 0.8012, 0.7895, 0.7895, 0.8036, 0.8345,
         0.8188, 0.7831, 0.4882, 0.4800, 0.6035, 0.4490, 0.3617],
        [0.5827, 0.7733, 0.7659, 0.7687, 0.7993, 0.7924, 0.7924, 0.8030, 0.8343,
         0.7983, 0.7906, 0.4834, 0.4783, 0.5378, 0.4231, 0.3496],
        [0.5960, 0.7621, 0.7405, 0.7742, 0.7969, 0.7939, 0.7939, 0.8019, 0.8327,
         0.7377, 0.7723, 0.4583, 0.4714, 0.4486, 0.3463, 0.3124],
        [0.5765, 0.7501, 0.7271, 0.7765, 0.7958, 0.7944, 0.7944, 0.8003, 0.8305,
         0.6628, 0.7167, 0.4275, 0.4590, 0.4211, 0.3088, 0.2931],
        [0.5583, 0.7608, 0.7388, 0.7927, 0.7862, 0.7972, 0.7972, 0.7992, 0.8291,
         0.6220, 0.6538, 0.4137, 0.4460, 0.4535, 0.3519, 0.3121],
        [0.5622, 0.7477, 0.7354, 0.7881, 0.7872, 0.7955, 0.7955, 0.7992, 0.8275,
         0.6178, 0.6111, 0.4007, 0.4327, 0.5122, 0.3416, 0.3072],
        [0.5462, 0.7599, 0.7513, 0.7864, 0.7852, 0.7936, 0.7936, 0.8002, 0.8268,
         0.6636, 0.6114, 0.4045, 0.4229, 0.5364, 0.4019, 0.3333],
        [0.5764, 0.7761, 0.7580, 0.7854, 0.7842, 0.7926, 0.7926, 0.8007, 0.8264,
         0.7016, 0.6398, 0.4138, 0.4171, 0.5657, 0.4266, 0.3443],
        [0.5921, 0.7619, 0.7426, 0.7831, 0.7816, 0.7901, 0.7901, 0.8003, 0.8253,
         0.7177, 0.6754, 0.4089, 0.4114, 0.5461, 0.3718, 0.3205],
        [0.6206, 0.7448, 0.6968, 0.7701, 0.7853, 0.7857, 0.7857, 0.7988, 0.8220,
         0.6670, 0.6766, 0.3676, 0.3977, 0.4085, 0.2382, 0.2535],
        [0.6081, 0.7171, 0.6833, 0.7563, 0.7869, 0.7798, 0.7798, 0.7972, 0.8181,
         0.6070, 0.6429, 0.3250, 0.3771, 0.4402, 0.2052, 0.2347],
        [0.5959, 0.7034, 0.6687, 0.7415, 0.7876, 0.7730, 0.7730, 0.7961, 0.8136,
         0.5756, 0.5922, 0.2812, 0.3510, 0.3655, 0.1712, 0.2147],
        [0.5762, 0.6900, 0.6682, 0.7281, 0.7892, 0.7673, 0.7673, 0.7949, 0.8093,
         0.5907, 0.5650, 0.2486, 0.3227, 0.3484, 0.1700, 0.2140],
        [0.5879, 0.7049, 0.6897, 0.7227, 0.7841, 0.7620, 0.7620, 0.7944, 0.8063,
         0.6254, 0.5716, 0.2435, 0.2990, 0.3853, 0.2674, 0.2523],
        [0.5853, 0.6914, 0.6677, 0.7149, 0.7784, 0.7552, 0.7552, 0.7935, 0.8023,
         0.6347, 0.5927, 0.2238, 0.2756, 0.3520, 0.2091, 0.2214],
        [0.5572, 0.6804, 0.6652, 0.7066, 0.7750, 0.7494, 0.7494, 0.7919, 0.7984,
         0.6337, 0.6080, 0.2090, 0.2536, 0.3005, 0.2026, 0.2178],
        [0.5297, 0.6685, 0.6527, 0.6956, 0.7754, 0.7442, 0.7442, 0.7907, 0.7940,
         0.6029, 0.6000, 0.1900, 0.2318, 0.2520, 0.1704, 0.2003],
        [0.5433, 0.6538, 0.6255, 0.6795, 0.7799, 0.7388, 0.7388, 0.7882, 0.7885,
         0.5879, 0.5833, 0.1556, 0.2067, 0.1687, 0.1075, 0.1632],
        [0.5557, 0.6668, 0.6498, 0.6728, 0.7734, 0.7321, 0.7321, 0.7862, 0.7844,
         0.5958, 0.5698, 0.1525, 0.1859, 0.2481, 0.2212, 0.2082],
        [0.5256, 0.6801, 0.6520, 0.6687, 0.7647, 0.7255, 0.7255, 0.7841, 0.7806,
         0.6128, 0.5733, 0.1555, 0.1699, 0.3070, 0.2309, 0.2122],
        [0.5644, 0.6608, 0.6189, 0.6593, 0.7577, 0.7173, 0.7173, 0.7814, 0.7753,
         0.6174, 0.5839, 0.1339, 0.1523, 0.1158, 0.1491, 0.1668],
        [0.5617, 0.6761, 0.6277, 0.6536, 0.7491, 0.7100, 0.7100, 0.7783, 0.7707,
         0.6084, 0.5883, 0.1280, 0.1369, 0.1605, 0.1898, 0.1832],
        [0.5389, 0.6622, 0.6185, 0.6454, 0.7445, 0.7035, 0.7035, 0.7746, 0.7658,
         0.5885, 0.5796, 0.1197, 0.1227, 0.1768, 0.1673, 0.1708],
        [0.5646, 0.6773, 0.6499, 0.6428, 0.7391, 0.6994, 0.6994, 0.7712, 0.7627,
         0.6410, 0.5880, 0.1434, 0.1167, 0.3005, 0.3052, 0.2288],
        [0.5655, 0.6895, 0.6535, 0.6425, 0.7308, 0.6949, 0.6949, 0.7684, 0.7599,
         0.6945, 0.6188, 0.1686, 0.1175, 0.3813, 0.3198, 0.2353],
        [0.5445, 0.7006, 0.6575, 0.6433, 0.7222, 0.6908, 0.6908, 0.7663, 0.7575,
         0.7638, 0.6813, 0.1951, 0.1240, 0.3916, 0.3365, 0.2425],
        [0.5309, 0.7126, 0.6763, 0.6492, 0.7093, 0.6868, 0.6868, 0.7630, 0.7561,
         0.8140, 0.7430, 0.2347, 0.1381, 0.4185, 0.4132, 0.2767],
        [0.5074, 0.7002, 0.6758, 0.6595, 0.6915, 0.6825, 0.6825, 0.7600, 0.7548,
         0.8756, 0.8075, 0.2680, 0.1568, 0.4105, 0.4111, 0.2759],
        [0.4925, 0.7102, 0.6850, 0.6695, 0.6765, 0.6794, 0.6794, 0.7577, 0.7540,
         0.9451, 0.8721, 0.3040, 0.1797, 0.4830, 0.4490, 0.2927],
        [0.4790, 0.7212, 0.6930, 0.6699, 0.6757, 0.6792, 0.6792, 0.7563, 0.7536,
         0.9697, 0.9276, 0.3408, 0.2063, 0.3519, 0.4816, 0.3075],
        [0.4712, 0.7092, 0.6880, 0.6696, 0.6765, 0.6795, 0.6795, 0.7558, 0.7530,
         0.9536, 0.9554, 0.3670, 0.2334, 0.3087, 0.4586, 0.2993],
        [0.4465, 0.7192, 0.6884, 0.6689, 0.6791, 0.6805, 0.6805, 0.7554, 0.7524,
         0.9231, 0.9476, 0.3890, 0.2600, 0.3267, 0.4604, 0.3001],
        [0.4445, 0.7331, 0.7062, 0.6665, 0.6851, 0.6825, 0.6825, 0.7552, 0.7528,
         0.9317, 0.9341, 0.4219, 0.2886, 0.3368, 0.5376, 0.3335],
        [0.4810, 0.7472, 0.7283, 0.6614, 0.6937, 0.6846, 0.6846, 0.7554, 0.7542,
         0.9518, 0.9335, 0.4667, 0.3215, 0.3912, 0.6197, 0.3738],
        [0.4616, 0.7587, 0.7379, 0.6561, 0.7057, 0.6883, 0.6883, 0.7566, 0.7561,
         0.9821, 0.9545, 0.5099, 0.3575, 0.3851, 0.6520, 0.3910]],
       device='cuda:0')

# 1D CNN-LSTM

<img src="/home/arda/Turkcell/RNN/LSTM/images/Screenshot from 2024-01-30 10-39-06.png" alt="Alt text">

In [174]:
class OneDimCNNLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, conv_channels, kernel_size, pool_size, stride):
        super(OneDimCNNLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # Convolutional Layer
        self.conv1 = nn.Conv1d(in_channels=input_dim, out_channels=conv_channels, kernel_size=kernel_size)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool1d(kernel_size=pool_size, stride=stride)

        self.lstm = nn.LSTM(input_size = conv_channels, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # CNN in_dim: (batch_size, in_channels, length)
        x = x.transpose(1, 2)

        # Conv layer forward propagate
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.maxpool1(x)

        # LSTM in_dim: (batch_size, seq_len, input_size)
        x = x.transpose(1, 2)

        assert x.size(-1) == self.lstm.input_size, f"Mismatch in LSTM input size. Expected: {self.lstm.input_size}, Got: {x.size(-1)}"

        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

# 2D CNN - LSTM

In [175]:
import torch
import torch.nn as nn

class TwoDimCNNLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, conv_channels, kernel_size, pool_size, stride):
        super(TwoDimCNNLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # 2D Convolutional Layer
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=conv_channels, kernel_size=kernel_size)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool2d(kernel_size=pool_size, stride=stride)

        dummy_x = torch.zeros(1, 1, 44, 16)
        dummy_x = self.conv1(dummy_x)
        dummy_x = self.relu1(dummy_x)
        dummy_x = self.maxpool1(dummy_x)
        _, C, H, W = dummy_x.shape
        lstm_input_size = C * H * W

        self.lstm = nn.LSTM(input_size=lstm_input_size, hidden_size=hidden_size, num_layers=layer_size, dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        #[110, 44, 16
        batch_size, seq_len, numOfFeatures = x.shape
        x = x.view(-1, 1, seq_len, numOfFeatures)

        # CNN in_dim: (batch_size, in_channels, height, width)
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.maxpool1(x)

        # Flatten the output for LSTM
        batch_size, channels, height, width = x.size()
        x = x.view(batch_size, 1, channels * height * width)

        assert x.size(-1) == self.lstm.input_size, f"Mismatch in LSTM input size. Expected: {self.lstm.input_size}, Got: {x.size(-1)}"


        # Forward propagate LSTM
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(x.device)
        out, (hn, cn) = self.lstm(x, (h0, c0))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

In [176]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device, model_type):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model_type = model_type
        self.model = None
        self.optimizer = None
        self.criterion = nn.MSELoss()

    
    def train_validate(self, config, trial):

        if self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        elif self.model_type == "2D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = TwoDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)


        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.view(-1,1)


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.view(-1,1)

                        preds = self.model(data)
                        loss = self.criterion(preds, target)
                        #loss = loss.mean()

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
        
        if self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        elif self.model_type == "2D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = TwoDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)


        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)  

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                all_preds.extend(preds.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [177]:
model_type = "1D CNN-LSTM"

def objective(trial):

    if model_type == "1D CNN-LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "conv_channels": trial.suggest_int("conv_channels", 16, 128),
            "kernel_size": trial.suggest_int("kernel_size", 2, 6),
            "num_layers": trial.suggest_int("num_layers", 1, 5),
            "pool_size": trial.suggest_int("pool_size", 2, 5),
            "stride": trial.suggest_int("stride", 1, 4)
        }

    elif model_type == "2D CNN-LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "conv_channels": trial.suggest_int("conv_channels", 16, 128),
            "kernel_size": trial.suggest_int("kernel_size", 2, 6),
            "num_layers": trial.suggest_int("num_layers", 1, 5),
            "pool_size": trial.suggest_int("pool_size", 2, 5),
            "stride": trial.suggest_int("stride", 1, 4)
        }

    trainer = ModelActioner(train_data, test_data, device, model_type)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [178]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=10, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=10, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-29 04:18:18,994] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/10 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0026161916811313283, val_loss: 0.0034543058770910772
epochs 2/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0020525244064629076, val_loss: 0.0028085403517627765
epochs 3/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.001555456760290422, val_loss: 0.0024165173083366383
epochs 4/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.001645517607807721, val_loss: 0.002183085050626052
epochs 5/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.001654312804978537, val_loss: 0.0020578803171812697
epochs 6/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0018939558097994641, val_loss: 0.002014853972473512
epochs 7/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0017190762869033374, val_loss: 0.002011585924601941
epochs 8/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0015744111488426203, val_loss: 0.0020385448908354477
epochs 9/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0016080046562772048, val_loss: 0.0020894315494125876
epochs 10/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.002001522368702449, val_loss: 0.002149002475013572
epochs 11/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0015809125285350572, val_loss: 0.002211291504969633
epochs 12/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0014890872076839994, val_loss: 0.002259300030625016
epochs 13/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0015609459400078968, val_loss: 0.002283528631937409
epochs 14/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0016159224936640577, val_loss: 0.0022870369493301033
epochs 15/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0014850043716203225, val_loss: 0.002279739303972631
epochs 16/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0014201289631034198, val_loss: 0.0022626272279512947
epochs 17/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0017048920517003065, val_loss: 0.0022321206920351538
epochs 18/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.001350963431238932, val_loss: 0.002194563965387051
epochs 19/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0017079524561076573, val_loss: 0.002143741050666129
epochs 20/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0015548652221791838, val_loss: 0.00211429842760067
epochs 21/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0016377819824571673, val_loss: 0.00209576135843736
epochs 22/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.001468063457746451, val_loss: 0.0020890238105994528
epochs 23/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.001343703483795061, val_loss: 0.002084429929570034
epochs 24/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.001396818252549948, val_loss: 0.0020660567263673458
epochs 25/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0014001899754236403, val_loss: 0.0020427405285998864
epochs 26/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0012172220924280975, val_loss: 0.0020305614101715267
epochs 27/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0012818548423973353, val_loss: 0.001996106660318753
epochs 28/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0012818498487927412, val_loss: 0.001966118717088152
epochs 29/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0012915961487267754, val_loss: 0.0019315227104853543
epochs 30/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0012358008338579614, val_loss: 0.0019131050717391114
epochs 31/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0012791653935748497, val_loss: 0.0018992095347370695
epochs 32/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0013058211250034603, val_loss: 0.00188141607460147
epochs 33/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00109169257032734, val_loss: 0.001848008738961268
epochs 34/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0011257164045482089, val_loss: 0.0017987077685550999
epochs 35/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00110537971210617, val_loss: 0.0017525684941564958
epochs 36/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0011178340775107867, val_loss: 0.001720063338147368
epochs 37/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0008884226437658072, val_loss: 0.001697815607595085
epochs 38/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0009237181995750258, val_loss: 0.0016611636571324966
epochs 39/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0008731871659524346, val_loss: 0.001599762734412536
epochs 40/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0009443210468529479, val_loss: 0.0015274989012155741
epochs 41/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0008254361522727106, val_loss: 0.0014610792305098758
epochs 42/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.000807686302639348, val_loss: 0.0014211233737927778
epochs 43/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.000724389842760406, val_loss: 0.0014219829358687753
epochs 44/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006502024155404223, val_loss: 0.0014522948041164054
epochs 45/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006311337779104513, val_loss: 0.0014876959457064648
epochs 46/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006006173489272202, val_loss: 0.001455405857765101
epochs 47/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006082383952544708, val_loss: 0.001364635019353714
epochs 48/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005810876468833732, val_loss: 0.0012326785775946167
epochs 49/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004384176407352482, val_loss: 0.0011515871547137894
epochs 50/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004756511161471472, val_loss: 0.0011680647142591181
epochs 51/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005355380074194584, val_loss: 0.0012674378072559617
epochs 52/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005430997827237374, val_loss: 0.0012923990314390274
epochs 53/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004446084056613281, val_loss: 0.0013116189046447515
epochs 54/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004188634522602354, val_loss: 0.001213100168603921
epochs 55/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00045753262453026287, val_loss: 0.001079354467543049
epochs 56/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00040456377625416374, val_loss: 0.0010270034542021456
epochs 57/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.000459827919870517, val_loss: 0.0010848022247763184
epochs 58/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004600318972830121, val_loss: 0.0011580940764077086
epochs 59/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00041464021165953265, val_loss: 0.001193164774800636
epochs 60/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004317376777946361, val_loss: 0.001160500131494479
epochs 61/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00040661450873717274, val_loss: 0.0011247039728529416
epochs 62/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00044762263515670046, val_loss: 0.0011332783276441867
epochs 63/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00040245917595089657, val_loss: 0.0011164286442128103
epochs 64/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003720518740776338, val_loss: 0.001144616402810065
epochs 65/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00043775225977266304, val_loss: 0.0011311060075756536
epochs 66/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004051173053755376, val_loss: 0.001066655329417526
epochs 67/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003584936578255637, val_loss: 0.0010325779162702105
epochs 68/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00036398397305196053, val_loss: 0.0010780552163456502
epochs 69/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00037225629141750304, val_loss: 0.0011416141475949968
epochs 70/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003522623255297444, val_loss: 0.0011586912158659843
epochs 71/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003934200068837718, val_loss: 0.0010965186018477042
epochs 72/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003845290648505876, val_loss: 0.00098974932854867
epochs 73/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00033698990316081203, val_loss: 0.0009847848150120288
epochs 74/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00034844322684588597, val_loss: 0.0010391255107981758
epochs 75/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003267915515033038, val_loss: 0.0010758326718430947
epochs 76/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002767960102861061, val_loss: 0.0010549052618135989
epochs 77/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00030490014607111287, val_loss: 0.0010157916685640221
epochs 78/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003011198778710279, val_loss: 0.0009801825366805865
epochs 79/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003160342212619358, val_loss: 0.0009971445727546418
Starting fold 2:
epochs 1/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006357384437085731, val_loss: 0.01654874748259625
epochs 2/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0007684569397946147, val_loss: 0.015434440254928574
epochs 3/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0007974654153520168, val_loss: 0.018190249909089986
epochs 4/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006649319804642143, val_loss: 0.017834705216859384
epochs 5/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006243207287362784, val_loss: 0.01513370081151604
epochs 6/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006492976215975188, val_loss: 0.013780990295190976
epochs 7/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0007104165615553238, val_loss: 0.013972353195111272
epochs 8/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006307296231905082, val_loss: 0.014126669275500471
epochs 9/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005819989267876741, val_loss: 0.013547862298471271
epochs 10/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006033679549361144, val_loss: 0.01248827609652407
epochs 11/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006043474474985713, val_loss: 0.012477559012868417
epochs 12/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005868336088748988, val_loss: 0.012625198072147749
epochs 13/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005284860328707284, val_loss: 0.012251570549788614
epochs 14/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005376411701422333, val_loss: 0.011609213323228888
epochs 15/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005492411356045813, val_loss: 0.011033170703778822
epochs 16/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0006064764466038402, val_loss: 0.010733524155088518
epochs 17/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.000513482541380337, val_loss: 0.01010812322791449
epochs 18/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00055974252161995, val_loss: 0.010150377818496613
epochs 19/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005422752846025009, val_loss: 0.010039277239234517
epochs 20/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004990767843598662, val_loss: 0.009476817498801561
epochs 21/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004980130029576868, val_loss: 0.009330813713844806
epochs 22/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005877264187115891, val_loss: 0.010104671918920108
epochs 23/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004924218005090362, val_loss: 0.009470398678252149
epochs 24/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004962937384819253, val_loss: 0.008675263174587772
epochs 25/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0005578955040758078, val_loss: 0.009202050907468354
epochs 26/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004640407328884606, val_loss: 0.00905271369727358
epochs 27/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004683216580061984, val_loss: 0.008414316210383303
epochs 28/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00048599123498940924, val_loss: 0.00802857020534772
epochs 29/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00045182946934254156, val_loss: 0.008403810211728332
epochs 30/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004715042951760081, val_loss: 0.008556125720066053
epochs 31/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00037822176795698564, val_loss: 0.007824763887261272
epochs 32/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004354486792375356, val_loss: 0.007530225892970092
epochs 33/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004132628202190166, val_loss: 0.007704087661175185
epochs 34/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00044122138315575853, val_loss: 0.007722674060869154
epochs 35/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004573184016988782, val_loss: 0.007278443789651627
epochs 36/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0004302419586620714, val_loss: 0.007201031482379351
epochs 37/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00038317650864343097, val_loss: 0.0073632374270351
epochs 38/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00040758491768980875, val_loss: 0.007205295550178677
epochs 39/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00037262566362465866, val_loss: 0.006728029637425034
epochs 40/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00042943850511041197, val_loss: 0.006673969934502292
epochs 41/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00040773868528231586, val_loss: 0.006704787189071929
epochs 42/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003749148999734003, val_loss: 0.006531414476090244
epochs 43/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00040584295606584656, val_loss: 0.00624982252342518
epochs 44/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003421031991277863, val_loss: 0.006269553233992565
epochs 45/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00035248761938265613, val_loss: 0.005946443073707756
epochs 46/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00036793389040632737, val_loss: 0.005944973008125705
epochs 47/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00036954799790480877, val_loss: 0.006005742699252786
epochs 48/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00033892288212455555, val_loss: 0.0057083881144761725
epochs 49/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00033171414406871853, val_loss: 0.005596921700373213
epochs 50/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00035176111021543554, val_loss: 0.005111930591901814
epochs 51/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00036083713790038136, val_loss: 0.005059092840864742
epochs 52/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00034545613317639814, val_loss: 0.004929950962178212
epochs 53/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00035187777080806587, val_loss: 0.004913772323917815
epochs 54/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003154618893799158, val_loss: 0.004765515592042849
epochs 55/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00030269327580850167, val_loss: 0.004670870987447126
epochs 56/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.000337505849486212, val_loss: 0.0043884755577892065
epochs 57/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00035477442083890135, val_loss: 0.004416461050308374
epochs 58/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0003221046311920877, val_loss: 0.004201577461100425
epochs 59/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002993832686043647, val_loss: 0.004145590995288104
epochs 60/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00032841153952752614, val_loss: 0.004166612295044596
epochs 61/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00030644179802845014, val_loss: 0.004132815520895064
epochs 62/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002937573267793219, val_loss: 0.0040824835280464005
epochs 63/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00029525164629045215, val_loss: 0.003973280049789027
epochs 64/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002790710276470699, val_loss: 0.003918140642800758
epochs 65/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002928268839236555, val_loss: 0.0041428089040829235
epochs 66/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00028804950689464455, val_loss: 0.003950128428793202
epochs 67/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00028481821242061327, val_loss: 0.003692177352224472
epochs 68/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00029104061452069844, val_loss: 0.003614641907415476
epochs 69/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002645184689859975, val_loss: 0.0035953914885847736
epochs 70/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002746272439445494, val_loss: 0.0036738087230968096
epochs 71/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00028259339889801427, val_loss: 0.0035224446938151403
epochs 72/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002847491877336586, val_loss: 0.003485160867779678
epochs 73/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00028964641848321034, val_loss: 0.003438839570633949
epochs 74/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002757481441865024, val_loss: 0.0033894916867009467
epochs 75/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002821611954970654, val_loss: 0.0032975100271561476
epochs 76/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00027145715766723974, val_loss: 0.0031835376414366895
epochs 77/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00028135107002665824, val_loss: 0.003082168345812649
epochs 78/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0002404549493150918, val_loss: 0.0030029515166663462
epochs 79/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00025779510956346047, val_loss: 0.0031972741086045823
Starting fold 3:
epochs 1/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0016047413213732718, val_loss: 0.020148678224474664
epochs 2/79

[I 2024-01-29 04:18:54,936] Trial 0 finished with value: 0.005891822827857746 and parameters: {'batch_size': 68, 'epochs': 79, 'hidden_size': 44, 'learning_rate': 0.00022078935295972353, 'dropout_prob': 0.11862455537099377, 'weight_decay': 7.078889213386802e-06, 'lr_step_size': 28, 'gamma': 0.12912968019210905, 'num_layers': 3}. Best is trial 0 with value: 0.005891822827857746.

Current Learning Rate: 0.00022078935295972353
train_loss: 0.0023399045066730796, val_loss: 0.0018779130230002382
epochs 79/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0021931124746752215, val_loss: 0.0017927354170876758
Mean validation loss: 0.005891822827857746
Starting fold 1:
epochs 1/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.006205625158097399, val_loss: 0.010650315767932664
epochs 2/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.006241620811143596, val_loss: 0.010445666011600267
epochs 3/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.006189192996948565, val_loss: 0.010247287044804248
epochs 4/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.005963212421384493, val_loss: 0.01005401004539438
epochs 5/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.005831708690445674, val_loss: 0.009865964011402516
epochs 6/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0056446706006107366, val_loss: 0.009682846679376862
epochs 7/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0056270188921572345, val_loss: 0.009503917652798234
epochs 8/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0056985865389977235, val_loss: 0.009328060369524691
epochs 9/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.005223278584277355, val_loss: 0.009157243359676272
epochs 10/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.00518850597896074, val_loss: 0.008990341993344446
epochs 11/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.005155801083770041, val_loss: 0.00882727542039618
epochs 12/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.005010334067169185, val_loss: 0.008668476321473323
epochs 13/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.004771872294306951, val_loss: 0.008514286575730515
epochs 14/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.004871542779361143, val_loss: 0.008363444949426348
epochs 15/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.004564238204865864, val_loss: 0.008216899902209956
epochs 16/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.004554357746689532, val_loss: 0.0080742005951131
epochs 17/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0044855063226637674, val_loss: 0.00793481323616727
epochs 18/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.004268839081602269, val_loss: 0.007799519426756041
epochs 19/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0042099955528484365, val_loss: 0.007669126070424835
epochs 20/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.004176717929811658, val_loss: 0.007542732663245665
epochs 21/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.004104634708920984, val_loss: 0.007419935880948312
epochs 22/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0041109002991824555, val_loss: 0.007299662393976062
epochs 23/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0040412187790743225, val_loss: 0.007182564903001384
epochs 24/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0038756802083777363, val_loss: 0.007069152204576072
epochs 25/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.00394422467920537, val_loss: 0.006958188932566415
epochs 26/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.003916323941053921, val_loss: 0.006849760490238036
epochs 27/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0036101148953955426, val_loss: 0.006745518845501085
epochs 28/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0036764722115262168, val_loss: 0.006643945544652602
epochs 29/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.003529217447717919, val_loss: 0.00654472025830752
epochs 30/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.003600998177487207, val_loss: 0.006447988053507827
epochs 31/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.003448428653523718, val_loss: 0.006354015586631638
epochs 32/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0034537029728342436, val_loss: 0.006261793671116706
epochs 33/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0033118215475329443, val_loss: 0.006172924675786543
epochs 34/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.003147245873697102, val_loss: 0.006087039652768345
epochs 35/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0033006273369353854, val_loss: 0.0060035910348964746
epochs 36/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0031738363623030875, val_loss: 0.005922395272165655
epochs 37/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0031922287951027485, val_loss: 0.005843358690894786
epochs 38/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0031300046977489012, val_loss: 0.00576644042868995
epochs 39/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0030180574357999783, val_loss: 0.005692146683392662
epochs 40/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0030822815159090647, val_loss: 0.005619295960829332
epochs 41/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002945541581874223, val_loss: 0.0055480438288271665
epochs 42/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.003054624375593113, val_loss: 0.005478664406048006
epochs 43/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0028482951879452325, val_loss: 0.005411598458147001
epochs 44/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0029327669033878726, val_loss: 0.005345585563210228
epochs 45/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002748294798412213, val_loss: 0.005281098606434488
epochs 46/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0026939083111325378, val_loss: 0.005218664156494751
epochs 47/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.00283236535829737, val_loss: 0.00515769344567267
epochs 48/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0025567672025461337, val_loss: 0.0050999982406942064
epochs 49/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0026793609042406867, val_loss: 0.005044632676308827
epochs 50/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0025636719257913923, val_loss: 0.004990888606737215
epochs 51/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0026413969088982985, val_loss: 0.004938245478711983
epochs 52/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0025571282046209826, val_loss: 0.004886683921093151
epochs 53/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0025043043792002686, val_loss: 0.004836842885226129
epochs 54/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002427190460117632, val_loss: 0.0047886168236829455
epochs 55/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0024959000679174144, val_loss: 0.004742098299579488
epochs 56/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0023637495591844384, val_loss: 0.004697178817531537
epochs 57/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0023406052208309503, val_loss: 0.004652828766555383
epochs 58/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0024605113749490365, val_loss: 0.0046089692417009874
epochs 59/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0023888138784585815, val_loss: 0.00456626694366119
epochs 60/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002450498115075262, val_loss: 0.004524823099562021
epochs 61/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002419546756917905, val_loss: 0.00448432117737534
epochs 62/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002397190849909461, val_loss: 0.0044446923608630505
epochs 63/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0022702229748431005, val_loss: 0.004406006215263414
epochs 64/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0022819145319150076, val_loss: 0.004368705068907094
epochs 65/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002311757847201079, val_loss: 0.0043322622015944156
epochs 66/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0022221203158168416, val_loss: 0.00429710304418766
epochs 67/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0023424593664362636, val_loss: 0.004262727651395219
epochs 68/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0022771227057091894, val_loss: 0.004229001790191486
epochs 69/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002230108453965697, val_loss: 0.0041961773257411855
epochs 70/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0022379569482597473, val_loss: 0.004164265264527843
epochs 71/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0021513547546132225, val_loss: 0.004133262233586893
epochs 72/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0020679890747966343, val_loss: 0.0041033429978784945
epochs 73/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0021460203576440873, val_loss: 0.004073915438586107
epochs 74/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002162648758262788, val_loss: 0.004046110596776344
epochs 75/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002147152771756641, val_loss: 0.004018727452223184
epochs 76/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0020466426938870234, val_loss: 0.003991960252206477
epochs 77/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0020977006649206343, val_loss: 0.003966168629525417
epochs 78/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019487434955264785, val_loss: 0.003941637361619286
epochs 79/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002059625897335967, val_loss: 0.003917096478669909
epochs 80/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002153587111541511, val_loss: 0.0038928004177582877
epochs 81/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002200961760612891, val_loss: 0.003868916645096664
epochs 82/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0020020449687236626, val_loss: 0.0038459938282526477
epochs 83/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0020699081029497872, val_loss: 0.0038238470858362105
epochs 84/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0020981983005951502, val_loss: 0.0038026457584078703
epochs 85/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019925446365959944, val_loss: 0.0037828210076667054
epochs 86/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0021398207926387456, val_loss: 0.003763327489005865
epochs 87/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019318743241264632, val_loss: 0.0037446470198802964
epochs 88/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019760733225235813, val_loss: 0.0037260183795951502
epochs 89/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019116891701215584, val_loss: 0.0037076343118863566
epochs 90/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019745392939320913, val_loss: 0.003690111622394176
epochs 91/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019365671219451256, val_loss: 0.003672950600813483
epochs 92/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018973322554589494, val_loss: 0.0036556601401778166
epochs 93/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001994509284237498, val_loss: 0.0036389538605584117
epochs 94/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019954911120677074, val_loss: 0.0036229322560959393
epochs 95/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018594812467008044, val_loss: 0.003607731852705083
epochs 96/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019520569764273732, val_loss: 0.0035930334047719874
epochs 97/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019961158738863705, val_loss: 0.0035786528421181533
epochs 98/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019695342463245127, val_loss: 0.0035650659624792674
epochs 99/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018998825940989743, val_loss: 0.003551956109096488
epochs 100/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019437131196211436, val_loss: 0.0035383879048774443
epochs 101/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019396807220274288, val_loss: 0.00352442361354069
epochs 102/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018592687519757372, val_loss: 0.003510674213800855
epochs 103/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019442965509369969, val_loss: 0.0034970288006613455
epochs 104/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018679860519784453, val_loss: 0.0034841316349917737
epochs 105/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018657217647782282, val_loss: 0.0034714091637556162
epochs 106/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018465711131667424, val_loss: 0.0034594436150867116
epochs 107/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001844821539462397, val_loss: 0.003447942512735685
epochs 108/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018728913246090278, val_loss: 0.003437132703660243
epochs 109/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018182340911344478, val_loss: 0.0034265168154089852
epochs 110/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001820544427334282, val_loss: 0.0034156760611083535
epochs 111/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018579686192280957, val_loss: 0.0034046483992367354
epochs 112/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.00185102546115798, val_loss: 0.003394182083423609
epochs 113/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001915560021543091, val_loss: 0.003384412171457101
epochs 114/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019180694671568313, val_loss: 0.0033746443494227984
epochs 115/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018431465849157815, val_loss: 0.0033655391593966338
epochs 116/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017411802062078526, val_loss: 0.0033571114394045066
epochs 117/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.00185835136860413, val_loss: 0.003348662923262627
epochs 118/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017573169858415465, val_loss: 0.0033411911298230133
epochs 119/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001779860573036498, val_loss: 0.0033333250657142824
epochs 120/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018932627388398703, val_loss: 0.003324580516804148
epochs 121/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018819206486161994, val_loss: 0.0033158233731728857
epochs 122/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018949629359045312, val_loss: 0.00330752878426451
epochs 123/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017988386453668538, val_loss: 0.0032992661091691207
epochs 124/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018696988853135782, val_loss: 0.0032909343563631258
epochs 125/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001814287576493562, val_loss: 0.003282646070820866
epochs 126/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018746022113574374, val_loss: 0.0032745443380600404
epochs 127/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001828431988772201, val_loss: 0.003267038094308523
epochs 128/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001836569602049789, val_loss: 0.0032601864422085107
epochs 129/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018459958676861502, val_loss: 0.0032528766939692475
epochs 130/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017671920726762007, val_loss: 0.0032452163883982593
epochs 131/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017613989763623594, val_loss: 0.0032378093770054715
epochs 132/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018209426253298787, val_loss: 0.003230636852556869
epochs 133/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001671234184361406, val_loss: 0.0032236008996035528
epochs 134/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017931622593957736, val_loss: 0.0032163739670068026
epochs 135/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.001746924459554353, val_loss: 0.0032100778857797937
epochs 136/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017372063330472693, val_loss: 0.0032039288694418414
epochs 137/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018549389797140306, val_loss: 0.0031982432079511306
epochs 138/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017325170188039346, val_loss: 0.0031928827769921292
epochs 139/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018640249085269476, val_loss: 0.0031877448511304996
epochs 140/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017289385677462345, val_loss: 0.003183175753321617
Starting fold 2:
epochs 1/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.00253962119058325, val_loss: 0.06013141832654438
epochs 2/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0024906291090699014, val_loss: 0.05945723584641224
epochs 3/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002336429408536413, val_loss: 0.05878330404480929
epochs 4/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.002240993552331353, val_loss: 0.05813193536072812
epochs 5/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0021711253548178594, val_loss: 0.057503579864426266
epochs 6/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0021840116352526014, val_loss: 0.056903316072686005
epochs 7/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0020550054766478552, val_loss: 0.056326857812347864
epochs 8/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0020314730938197183, val_loss: 0.05577731408454754
epochs 9/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019930265128175117, val_loss: 0.055255585049510635
epochs 10/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018807527342550752, val_loss: 0.05475718323042784
epochs 11/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019144054765949433, val_loss: 0.054276116231761914
epochs 12/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019315480894874781, val_loss: 0.053819184935597515
epochs 13/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0019242709965167424, val_loss: 0.05337546095646248
epochs 14/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017940241921481758, val_loss: 0.05295388808562642
epochs 15/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018023105822306982, val_loss: 0.052554768682629975
epochs 16/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018231603955096837, val_loss: 0.05217455883347799
epochs 17/140
Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0018058081836646084, val_loss: 0.051814536706953455
epochs 18/140
Current Learning Rate: 1.754139832399197e-05

[I 2024-01-29 04:19:20,166] Trial 1 pruned.

Current Learning Rate: 1.754139832399197e-05
train_loss: 0.0017719820678869316, val_loss: 0.04436374763174662
epochs 132/140
Starting fold 1:
epochs 1/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.014682276978304511, val_loss: 0.008193094034342922
epochs 2/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.013177522271871567, val_loss: 0.007622682644675176
epochs 3/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.013184082802189023, val_loss: 0.007081037173823764
epochs 4/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.012423711083829402, val_loss: 0.006571617772957931
epochs 5/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.012037000118901854, val_loss: 0.0060898577287810405
epochs 6/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.011224203488152278, val_loss: 0.005636133974702615
epochs 7/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.010049829161480853, val_loss: 0.005218080939138653
epochs 8/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0100852891312618, val_loss: 0.004829467664455512
epochs 9/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.008934079287083525, val_loss: 0.004472884069265866
epochs 10/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.008742025019110818, val_loss: 0.004144942743651982
epochs 11/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.008155647229011121, val_loss: 0.003846306496092843
epochs 12/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0078080764285435806, val_loss: 0.0035720727734129738
epochs 13/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.007001336428679918, val_loss: 0.0033197278907108638
epochs 14/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.006795367493147128, val_loss: 0.003091180990277617
epochs 15/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.006538088663824295, val_loss: 0.002880960629597582
epochs 16/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.006564168342830319, val_loss: 0.0026895681879034747
epochs 17/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.005889012019983248, val_loss: 0.002516828132448373
epochs 18/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.005131100353441741, val_loss: 0.0023636570700478776
epochs 19/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0054164312020140255, val_loss: 0.002225705991602606
epochs 20/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.005084415209038478, val_loss: 0.002102247094390569
epochs 21/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.004703347343265226, val_loss: 0.001992358808854112
epochs 22/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0046385068372872314, val_loss: 0.0018942345416656247
epochs 23/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.00457818498099713, val_loss: 0.001806431536183313
epochs 24/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.00427488441284942, val_loss: 0.001729799193088655
epochs 25/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0041258370650834155, val_loss: 0.001663563057297358
epochs 26/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.003657070557145696, val_loss: 0.0016066542723112637
epochs 27/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0035778541166923547, val_loss: 0.0015585718297020153
epochs 28/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.00339532411216121, val_loss: 0.0015183568638921887
epochs 29/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.003230667170627337, val_loss: 0.0014847014099359512
epochs 30/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0035061728797460856, val_loss: 0.0014573794841352436
epochs 31/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0031230955188603776, val_loss: 0.0014354119215298582
epochs 32/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0032580639799370576, val_loss: 0.0014187596841818756
epochs 33/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.003021268737747481, val_loss: 0.001406300812959671
epochs 34/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002932926627660268, val_loss: 0.0013979825501640637
epochs 35/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0027546462749964314, val_loss: 0.0013932718171013726
epochs 36/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0026244975234332836, val_loss: 0.0013916560586679865
epochs 37/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0025930082155881744, val_loss: 0.0013924950250872859
epochs 38/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002346856727902042, val_loss: 0.0013953678275424022
epochs 39/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0025375286754416794, val_loss: 0.001400041480169252
epochs 40/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0024364482954536614, val_loss: 0.0014063655226318925
epochs 41/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0023108892730976404, val_loss: 0.0014138540804938034
epochs 42/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002284963686313284, val_loss: 0.0014227543164182592
epochs 43/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002497307470950641, val_loss: 0.0014326117794822763
epochs 44/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002724151479962625, val_loss: 0.001443489816867643
epochs 45/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0022848791981998243, val_loss: 0.0014549791209261726
epochs 46/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0022820241308133854, val_loss: 0.0014663498969403682
epochs 47/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0021211668407838595, val_loss: 0.00147838377462769
epochs 48/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002023863473809079, val_loss: 0.0014899693929624777
epochs 49/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.00216599803564972, val_loss: 0.0015016003787793495
epochs 50/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0023439444822112195, val_loss: 0.0015135698572353081
epochs 51/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002111866131522938, val_loss: 0.0015261916236744986
epochs 52/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020131857183418775, val_loss: 0.001539586482707549
epochs 53/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0024106814673072415, val_loss: 0.0015531791356840619
epochs 54/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0021609425079077483, val_loss: 0.001566836541449582
epochs 55/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.00223575659145258, val_loss: 0.0015803514721079005
epochs 56/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002009590957803946, val_loss: 0.0015936586747152938
epochs 57/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019962615921701255, val_loss: 0.0016071100771013233
epochs 58/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0024063100597183956, val_loss: 0.0016205086010611719
epochs 59/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001925821004337386, val_loss: 0.0016347679688974662
epochs 60/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020527690796083528, val_loss: 0.001648334105050674
epochs 61/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.00204981269658004, val_loss: 0.0016623706884544205
epochs 62/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.00213083149130015, val_loss: 0.0016753862491222444
epochs 63/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001893307702419789, val_loss: 0.0016880398529961153
epochs 64/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018038337388517041, val_loss: 0.001699305777610452
epochs 65/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002001284374120204, val_loss: 0.0017096388274458823
epochs 66/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018952879711593453, val_loss: 0.0017188410102217287
epochs 67/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002273970935493708, val_loss: 0.0017282246456791956
epochs 68/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019869252279596894, val_loss: 0.0017367110984330928
epochs 69/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002126256361799805, val_loss: 0.0017457577330922639
epochs 70/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001990821587510015, val_loss: 0.0017558954293943113
epochs 71/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018907978150405381, val_loss: 0.0017663978850813928
epochs 72/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001953283611587004, val_loss: 0.0017774600311423893
epochs 73/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019710922515706014, val_loss: 0.001788086171641394
epochs 74/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019715277502607357, val_loss: 0.0017988338756064575
epochs 75/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0021672629604214118, val_loss: 0.0018096254897062426
epochs 76/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001819810633988757, val_loss: 0.0018210238949568182
epochs 77/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002057996208436395, val_loss: 0.0018312289138083106
epochs 78/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019415950182041055, val_loss: 0.001840715486280344
epochs 79/89
Epoch 00079: reducing learning rate of group 0 to 3.0154e-05.
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.0020342094774701094, val_loss: 0.001848853719248264
epochs 80/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.0017126329855895355, val_loss: 0.001851566368713975
epochs 81/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.0016625232381844207, val_loss: 0.0018540015702860223
epochs 82/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.002038068240998607, val_loss: 0.001856473360762552
epochs 83/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.001873535079587447, val_loss: 0.0018597623264348065
epochs 84/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.0018589779661086045, val_loss: 0.0018630753081567862
epochs 85/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.002178365639165828, val_loss: 0.0018658616700796065
epochs 86/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.0019241944666167623, val_loss: 0.0018689917676426747
epochs 87/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.0021243650319152756, val_loss: 0.0018718058277887326
epochs 88/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.002017239292495345, val_loss: 0.001874079686348085
epochs 89/89
Current Learning Rate: 3.015376609798625e-05
train_loss: 0.0021186397778556534, val_loss: 0.0018756661598605137
Starting fold 2:
epochs 1/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020981500291395784, val_loss: 0.051663285604229676
epochs 2/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001978900018184984, val_loss: 0.05102708163084807
epochs 3/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002108156257173867, val_loss: 0.050359613365597196
epochs 4/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0021586554434573114, val_loss: 0.04977960387865702
epochs 5/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002033184138728714, val_loss: 0.04929112560219235
epochs 6/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.00201331471685212, val_loss: 0.048856348351196004
epochs 7/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019158896557632883, val_loss: 0.048488040213231685
epochs 8/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0021466054845512856, val_loss: 0.04827930364343855
epochs 9/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002016422171686287, val_loss: 0.048082919584380254
epochs 10/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018874095767579166, val_loss: 0.047894765381459835
epochs 11/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001961924907282034, val_loss: 0.04777540432082282
epochs 12/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020060241935003086, val_loss: 0.04771422346433004
epochs 13/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019305795074826338, val_loss: 0.04762135390882139
epochs 14/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020194678975264282, val_loss: 0.04753335703302313
epochs 15/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019158253429020144, val_loss: 0.04744577738973829
epochs 16/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002080070358605215, val_loss: 0.047365746564335294
epochs 17/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019693778358439184, val_loss: 0.04728845920827654
epochs 18/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002079164393069247, val_loss: 0.04722304311063555
epochs 19/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020319282096911387, val_loss: 0.04718368141739457
epochs 20/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020533327386766122, val_loss: 0.04713427358203464
epochs 21/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020257743403541617, val_loss: 0.04707317937303473
epochs 22/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002030014834492062, val_loss: 0.04705789078164984
epochs 23/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0021197837851155243, val_loss: 0.047066696264125685
epochs 24/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018650169231213807, val_loss: 0.047047951707133544
epochs 25/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002034457020785925, val_loss: 0.04703681170940399
epochs 26/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001978776782583986, val_loss: 0.04699151383505927
epochs 27/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020997120389385556, val_loss: 0.046925558536141006
epochs 28/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018813556826877405, val_loss: 0.04686570388299448
epochs 29/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020579125776415135, val_loss: 0.046827779323966416
epochs 30/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002029823504221235, val_loss: 0.04680013435858267
epochs 31/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020786364093462206, val_loss: 0.046785733214131105
epochs 32/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019820834188120032, val_loss: 0.04678962076151812
epochs 33/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0021483313321752724, val_loss: 0.04678523209359911
epochs 34/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018578202606210766, val_loss: 0.046742675481019194
epochs 35/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020627071073470457, val_loss: 0.04672187345999258
epochs 36/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019539342775429774, val_loss: 0.04673175403365382
epochs 37/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001858518709549017, val_loss: 0.04673498592994831
epochs 38/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002072508910076206, val_loss: 0.04672262569268545
epochs 39/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001963073646988828, val_loss: 0.04667707008344156
epochs 40/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001957038251589738, val_loss: 0.046642150040026066
epochs 41/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019368853980287085, val_loss: 0.04660433972323382
epochs 42/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.002077617710775703, val_loss: 0.04657540829093368
epochs 43/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019113320616469533, val_loss: 0.046558385645901715
epochs 44/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019612111075041636, val_loss: 0.0465393982551716
epochs 45/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018424545961498507, val_loss: 0.04652136012359902
epochs 46/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019766803619532913, val_loss: 0.046500641438696116
epochs 47/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020181284087039237, val_loss: 0.046492024704262065
epochs 48/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019766565333648846, val_loss: 0.04650482700930701
epochs 49/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001824130947974395, val_loss: 0.046542357515405725
epochs 50/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018351267652197847, val_loss: 0.04656344045091559
epochs 51/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0021385319118134892, val_loss: 0.04656235542562273
epochs 52/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019387973750152657, val_loss: 0.04653217174388744
epochs 53/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018504664798249984, val_loss: 0.04647946523295508
epochs 54/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019474170971809244, val_loss: 0.046470184017110755
epochs 55/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001959887422906299, val_loss: 0.04648193661813383
epochs 56/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019742642408900335, val_loss: 0.046489575394877684
epochs 57/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019895498177631313, val_loss: 0.046518346225773846
epochs 58/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020267584909117314, val_loss: 0.04654828155482257
epochs 59/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0021105194562618525, val_loss: 0.04654904979246634
epochs 60/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0017901552438067572, val_loss: 0.04654064719323759
epochs 61/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019451363397993168, val_loss: 0.04655765052194948
epochs 62/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001881399378671967, val_loss: 0.046559918809820106
epochs 63/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019114332158108656, val_loss: 0.046565554208225675
epochs 64/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020051118377153823, val_loss: 0.04657438673354961
epochs 65/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001977595193483584, val_loss: 0.046593337699219035
epochs 66/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001789983787075039, val_loss: 0.04658016672840825
epochs 67/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.001837261288370298, val_loss: 0.04656666020552317
epochs 68/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018829932156213041, val_loss: 0.046535433994399175
epochs 69/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0020395138775217187, val_loss: 0.04652588235007392
epochs 70/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0019478578873637247, val_loss: 0.046514009987866436
epochs 71/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.0018711619829822892, val_loss: 0.04650755116233119
epochs 72/89

[I 2024-01-29 04:19:58,900] Trial 2 finished with value: 0.15594028760565462 and parameters: {'batch_size': 56, 'epochs': 89, 'hidden_size': 22, 'learning_rate': 9.277165112055194e-05, 'dropout_prob': 0.14714628733455787, 'weight_decay': 0.007889990286014474, 'lr_step_size': 42, 'gamma': 0.32503211631754836, 'num_layers': 5}. Best is trial 0 with value: 0.005891822827857746.

Current Learning Rate: 9.277165112055194e-05
train_loss: 0.084236808597695, val_loss: 0.20619739260938433
epochs 89/89
Current Learning Rate: 9.277165112055194e-05
train_loss: 0.08540876525952372, val_loss: 0.20621175953635462
Mean validation loss: 0.15594028760565462
Starting fold 1:
epochs 1/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.002858067097411932, val_loss: 0.005265633113652704
epochs 2/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.002811963771665959, val_loss: 0.005139069738871758
epochs 3/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.00265501069860827, val_loss: 0.0050214457026283655
epochs 4/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0025928464246374604, val_loss: 0.004909644784804966
epochs 5/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0025140384236644756, val_loss: 0.004802999631797392
epochs 6/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0025659927908380175, val_loss: 0.004701610484589187
epochs 7/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0023978927956992075, val_loss: 0.004604726870884261
epochs 8/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.002340125304793841, val_loss: 0.004512092216856896
epochs 9/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.002324220358614663, val_loss: 0.004422972405639787
epochs 10/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0023560176333902697, val_loss: 0.00433723734773045
epochs 11/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0022195351916659426, val_loss: 0.0042556028938778336
epochs 12/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0022628564485593847, val_loss: 0.004177956196982118
epochs 13/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0022539095818310192, val_loss: 0.004103598516574869
epochs 14/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.002069847065783841, val_loss: 0.0040324807872936606
epochs 15/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.002115894722335629, val_loss: 0.003963560981136407
epochs 16/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.002031754505649013, val_loss: 0.003898616668598224
epochs 17/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0020704591674362556, val_loss: 0.003836269789774503
epochs 18/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0020088784139309273, val_loss: 0.0037764078431156657
epochs 19/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001963324969217769, val_loss: 0.003719335959647738
epochs 20/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0019748611538058245, val_loss: 0.0036646365659267063
epochs 21/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0019286953494884074, val_loss: 0.0036122799215335694
epochs 22/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0018413592427111182, val_loss: 0.0035634153912449994
epochs 23/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001898818554993915, val_loss: 0.0035168781233507963
epochs 24/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0018288749423319179, val_loss: 0.0034729267806849545
epochs 25/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017250755470932314, val_loss: 0.003432073088968912
epochs 26/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0018172761462138672, val_loss: 0.0033930952213556756
epochs 27/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0018832758896199888, val_loss: 0.003355599665415606
epochs 28/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017857803439255803, val_loss: 0.0033189503204387925
epochs 29/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017339810180649357, val_loss: 0.003283681994717982
epochs 30/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001726555456346097, val_loss: 0.0032500516612171417
epochs 31/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017875476703537922, val_loss: 0.003217372100888973
epochs 32/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017689721827321735, val_loss: 0.0031864672718155715
epochs 33/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017650775911629592, val_loss: 0.0031572905598237873
epochs 34/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017370202180341278, val_loss: 0.003129580757573306
epochs 35/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.00172160566710916, val_loss: 0.003103101254618239
epochs 36/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017288282826101703, val_loss: 0.003077823690892685
epochs 37/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016435755021551525, val_loss: 0.0030540620135734715
epochs 38/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001714780198189577, val_loss: 0.0030306234987201317
epochs 39/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016709879399154728, val_loss: 0.0030077022882843657
epochs 40/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001682689551288556, val_loss: 0.0029856762959666197
epochs 41/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017038946949852337, val_loss: 0.002964940576237582
epochs 42/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016490466705842042, val_loss: 0.00294571038841876
epochs 43/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017225154050576844, val_loss: 0.0029269964665189266
epochs 44/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017045308069914187, val_loss: 0.0029089862165699106
epochs 45/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016982195347449497, val_loss: 0.0028919677258402643
epochs 46/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016146322712302208, val_loss: 0.0028759083486095604
epochs 47/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015757353697584844, val_loss: 0.002860420989611792
epochs 48/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001715814675461795, val_loss: 0.0028457632140507774
epochs 49/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001634534477182713, val_loss: 0.0028323986681200388
epochs 50/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016675297131051162, val_loss: 0.0028196339646080833
epochs 51/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015864868440028084, val_loss: 0.0028067537544605634
epochs 52/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016406543650909473, val_loss: 0.0027939503336147893
epochs 53/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016997824721712324, val_loss: 0.0027819812068686127
epochs 54/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015135869512481518, val_loss: 0.002771012588507599
epochs 55/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016171069334775798, val_loss: 0.002760330710323557
epochs 56/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016726229473102935, val_loss: 0.0027504932636114223
epochs 57/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016258845456544996, val_loss: 0.0027415320565480563
epochs 58/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016273512080691656, val_loss: 0.002732605186923008
epochs 59/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015317115664641421, val_loss: 0.00272407348402628
epochs 60/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016414053284710176, val_loss: 0.002715635096787342
epochs 61/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001687255843027838, val_loss: 0.002707224454276175
epochs 62/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015462701234929754, val_loss: 0.0026988059865303395
epochs 63/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016252794952474926, val_loss: 0.0026904374438648424
epochs 64/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016137711469414889, val_loss: 0.0026828662168035017
epochs 65/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016048983361351451, val_loss: 0.002675862132390547
epochs 66/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015832519589151304, val_loss: 0.0026685514520587666
epochs 67/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015623216792990111, val_loss: 0.0026612050580932566
epochs 68/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015650945672716356, val_loss: 0.0026538418772231254
epochs 69/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015879985444419281, val_loss: 0.0026463461903086494
epochs 70/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016081786791083256, val_loss: 0.0026391582339004216
epochs 71/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015754214232162524, val_loss: 0.002632562266958375
epochs 72/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016284779383568093, val_loss: 0.002626694697287998
epochs 73/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015457703990825011, val_loss: 0.0026213525958906207
epochs 74/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015152490449652663, val_loss: 0.0026167043963343734
epochs 75/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016080714389988173, val_loss: 0.002611751026946992
epochs 76/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015915589359601174, val_loss: 0.0026071317524405287
epochs 77/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016260438165198521, val_loss: 0.002601957985288685
epochs 78/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015854884242320335, val_loss: 0.002596842604116463
epochs 79/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016291605792694579, val_loss: 0.0025919686004127716
epochs 80/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001647401027730666, val_loss: 0.002587579348723271
epochs 81/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015615809454558123, val_loss: 0.002583615569626942
epochs 82/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016189682289749678, val_loss: 0.0025798586309917033
epochs 83/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015395846836710055, val_loss: 0.0025760299814421507
epochs 84/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001548177024845867, val_loss: 0.0025718387069424524
epochs 85/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015295636058956581, val_loss: 0.0025679405306517663
epochs 86/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.00161649640894642, val_loss: 0.0025636824984325186
epochs 87/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015373044659530645, val_loss: 0.0025601250827238554
epochs 88/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016145465039268234, val_loss: 0.002556763797266675
epochs 89/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015808070142826949, val_loss: 0.0025540386956732068
epochs 90/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016498232903694244, val_loss: 0.002551144945697622
epochs 91/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001559722886151193, val_loss: 0.0025485095531967957
epochs 92/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0014689755313539584, val_loss: 0.0025461510850286616
epochs 93/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001604563336801029, val_loss: 0.0025434357027286692
epochs 94/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015737220640355525, val_loss: 0.0025405104508593917
epochs 95/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015828906157127533, val_loss: 0.0025382067140613104
epochs 96/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016412121403080067, val_loss: 0.0025358838602043098
epochs 97/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0015548109427694918, val_loss: 0.0025343031526380588
Starting fold 2:
epochs 1/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0020647990479076275, val_loss: 0.05632955314857619
epochs 2/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0020004581806088964, val_loss: 0.05572272278368473
epochs 3/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0019633633446742077, val_loss: 0.055127603460162405
epochs 4/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0018792134018689836, val_loss: 0.05455094753276734
epochs 5/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0018791080431614592, val_loss: 0.05399838592561464
epochs 6/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0018123664495739151, val_loss: 0.05348103466842856
epochs 7/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017985183350762751, val_loss: 0.05299571768513748
epochs 8/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017282099364445812, val_loss: 0.05254353071370768
epochs 9/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017123129702600747, val_loss: 0.05211821837084634
epochs 10/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016908217066380449, val_loss: 0.05171618341571755
epochs 11/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017702538738338066, val_loss: 0.05134166833308954
epochs 12/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016908245544363363, val_loss: 0.05099369381510076
epochs 13/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017273141842029528, val_loss: 0.05067439454178962
epochs 14/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017059139516800495, val_loss: 0.0503798004476324
epochs 15/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001698248471086722, val_loss: 0.05010320030389324
epochs 16/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017493510775306166, val_loss: 0.049850929321514234
epochs 17/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016596056749008468, val_loss: 0.04961773797514893
epochs 18/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001698445305360314, val_loss: 0.04940123649107085
epochs 19/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001644900789709226, val_loss: 0.049198100077254434
epochs 20/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016165747323981425, val_loss: 0.049009344082266565
epochs 21/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016640643897130939, val_loss: 0.04883519196439357
epochs 22/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016869197722916346, val_loss: 0.04866957425006798
epochs 23/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017283772730261166, val_loss: 0.04851678433635878
epochs 24/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017210154387624417, val_loss: 0.04837061358349664
epochs 25/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016715062923003284, val_loss: 0.04823872716062599
epochs 26/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016706304136745996, val_loss: 0.04812015114086015
epochs 27/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016681794012653442, val_loss: 0.048006822340308675
epochs 28/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016747562868685258, val_loss: 0.047900800874072405
epochs 29/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001677736093454176, val_loss: 0.04780045015707848
epochs 30/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017282724114642343, val_loss: 0.04770933171468122
epochs 31/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001660269986110737, val_loss: 0.047623864301140344
epochs 32/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.00165304641569854, val_loss: 0.04754394316484058
epochs 33/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001695620676789477, val_loss: 0.047474581836944536
epochs 34/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.00168536104992005, val_loss: 0.04740783962465468
epochs 35/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001771263393409437, val_loss: 0.047350584810215327
epochs 36/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016915149516628755, val_loss: 0.04729590242699025
epochs 37/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017446611182718712, val_loss: 0.04724459447676227
epochs 38/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001658267390700475, val_loss: 0.047189462249950756
epochs 39/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001615503597248955, val_loss: 0.04714267071159113
epochs 40/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016317561395972535, val_loss: 0.04709858332006704
epochs 41/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.00168023470667557, val_loss: 0.04705562028619978
epochs 42/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017086488684230192, val_loss: 0.04701402960788636
epochs 43/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017329448684165376, val_loss: 0.046975560604579865
epochs 44/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016757364205599549, val_loss: 0.04693715652776143
epochs 45/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016389673739784743, val_loss: 0.04690248693620402
epochs 46/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016956763873570955, val_loss: 0.0468761045190077
epochs 47/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016986107839041668, val_loss: 0.04684817143494174
epochs 48/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001691377439289194, val_loss: 0.04682973160275391
epochs 49/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016690534932691221, val_loss: 0.04680747828549809
epochs 50/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001699942601985964, val_loss: 0.04678452360842909
epochs 51/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016838122498812915, val_loss: 0.04676184531242129
epochs 52/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.00170928937508012, val_loss: 0.04673685151196662
epochs 53/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001732867825893061, val_loss: 0.046718034006300424
epochs 54/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016838323794419589, val_loss: 0.04669234227566492
epochs 55/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017218542249786046, val_loss: 0.04666791874028388
epochs 56/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001713450726534493, val_loss: 0.046652883025152345
epochs 57/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016938224648331884, val_loss: 0.04664274251886776
epochs 58/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.001746081241445203, val_loss: 0.04663419723510742
epochs 59/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016757491506829041, val_loss: 0.04662797360547951
epochs 60/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0017530876422997585, val_loss: 0.046629255253171166
epochs 61/97
Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.0016625615641275681, val_loss: 0.04662371604215531

[I 2024-01-29 04:20:21,196] Trial 3 pruned.

Current Learning Rate: 2.5681569114434612e-05
train_loss: 0.013280512949305875, val_loss: 0.18008509656739613
epochs 78/97
Starting fold 1:
epochs 1/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.033596228023892956, val_loss: 0.03749635951623084
epochs 2/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.03064643150489581, val_loss: 0.03489707175780226
epochs 3/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.028950930229927365, val_loss: 0.03242593000411356
epochs 4/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.02658052634643881, val_loss: 0.030077224764874372
epochs 5/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.024707563417522532, val_loss: 0.027850166850146792
epochs 6/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.022827790657940664, val_loss: 0.025741308030706865
epochs 7/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.02130846306681633, val_loss: 0.023749683752025245
epochs 8/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.019424860610773687, val_loss: 0.02187122459764834
epochs 9/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.01815510903926272, val_loss: 0.02010068974442898
epochs 10/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.016240794211626053, val_loss: 0.018440828663568016
epochs 11/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.015118726480164026, val_loss: 0.016884780612099106
epochs 12/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.013969701028576023, val_loss: 0.015422981222549443
epochs 13/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.0131609298680958, val_loss: 0.014049812466418617
epochs 14/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.012084827023117166, val_loss: 0.012763712974018836
epochs 15/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.01070323302165458, val_loss: 0.011569455936156884
epochs 16/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.009607349571428801, val_loss: 0.010461650601533985
epochs 17/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.008916581735799187, val_loss: 0.009435301121797354
epochs 18/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.008430017942660734, val_loss: 0.008481851554717179
epochs 19/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.007082149018778613, val_loss: 0.007606859272099519
epochs 20/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.00695392337480658, val_loss: 0.0068032025561603916
epochs 21/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.006389909693481107, val_loss: 0.0060593355570244724
epochs 22/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.005576108153419275, val_loss: 0.005380906571175844
epochs 23/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.004842336681720458, val_loss: 0.004765229208503293
epochs 24/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.004266274615043872, val_loss: 0.004215782610502429
epochs 25/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.0036195398332845223, val_loss: 0.0037265771207838226
epochs 26/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.003501168458330396, val_loss: 0.003289473257840626
epochs 27/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.003364884809247757, val_loss: 0.002900297113998532
epochs 28/140

[I 2024-01-29 04:20:22,662] Trial 4 pruned.

Current Learning Rate: 7.165562617427442e-05
train_loss: 0.0030503599953494573, val_loss: 0.0025577102040948356
epochs 29/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.0024787157124496603, val_loss: 0.0022589619746973748
epochs 30/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.002310360463238076, val_loss: 0.0020033212170890587
epochs 31/140
Current Learning Rate: 7.165562617427442e-05
train_loss: 0.0022385645424947143, val_loss: 0.001781884492692173
epochs 32/140
Starting fold 1:
epochs 1/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.008817530909896289, val_loss: 0.0019870404919077244
epochs 2/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.002908972028250757, val_loss: 0.0014818902127444744
epochs 3/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0031929525056559787, val_loss: 0.0013270622751276409
epochs 4/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001884402643497053, val_loss: 0.0018688946729525924
epochs 5/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001312641978361889, val_loss: 0.003179966738181455
epochs 6/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016733937676211722, val_loss: 0.004124687119786229
epochs 7/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0022229662937063134, val_loss: 0.0041528878334377494
epochs 8/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0023083782999923355, val_loss: 0.003523340049598898
epochs 9/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0019892772757693343, val_loss: 0.0027379941062203477
epochs 10/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016012819496130472, val_loss: 0.0021623417103130904
epochs 11/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016434119132004287, val_loss: 0.0018626002295474922
epochs 12/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016489861067384482, val_loss: 0.0017932770341368659
epochs 13/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001581521005075621, val_loss: 0.001880508049258164
epochs 14/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015392281629733348, val_loss: 0.0021013164992577265
epochs 15/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001538499407960396, val_loss: 0.0023999427378709826
epochs 16/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015542248337480583, val_loss: 0.002680497077692832
epochs 17/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015545886009931565, val_loss: 0.002853668727246778
epochs 18/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.00159815941496115, val_loss: 0.0028612290708614247
epochs 19/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016722833884781913, val_loss: 0.002727391930030925
epochs 20/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015690209295012448, val_loss: 0.002532408755671765
epochs 21/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016074990008124396, val_loss: 0.002358418407051691
epochs 22/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016181913743677893, val_loss: 0.0022450245284874526
epochs 23/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016313236745956698, val_loss: 0.0021984831962202278
epochs 24/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015384483984426447, val_loss: 0.00221807967006628
epochs 25/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001585335691312426, val_loss: 0.002276456682011485
epochs 26/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001456069198780154, val_loss: 0.0023574228564809474
epochs 27/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001499865224928056, val_loss: 0.002425246772223285
epochs 28/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016319381894151631, val_loss: 0.0024709292255075915
epochs 29/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015228335476039272, val_loss: 0.0025103100508983645
epochs 30/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015645674969020642, val_loss: 0.0025341356439249857
epochs 31/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001494056373638542, val_loss: 0.0025382886274850796
epochs 32/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015389225041297706, val_loss: 0.002520568635580795
epochs 33/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015335737543768788, val_loss: 0.002488071830677135
epochs 34/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015550128490615048, val_loss: 0.002443875651806593
epochs 35/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015758800246801815, val_loss: 0.0023927572183310986
epochs 36/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0014934707874138104, val_loss: 0.00236459615241204
epochs 37/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015520584083309299, val_loss: 0.002357629393892629
epochs 38/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015930846480554657, val_loss: 0.00236340836688344
epochs 39/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015355601171521765, val_loss: 0.002376517280936241
epochs 40/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015024160672175257, val_loss: 0.0023957964232457535
epochs 41/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0014978992814002068, val_loss: 0.002413824882491359
epochs 42/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001560107182319227, val_loss: 0.002422812378167042
epochs 43/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001472081628775126, val_loss: 0.0024218441020431264
epochs 44/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015088386355752224, val_loss: 0.002413197753152677
epochs 45/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015008966499743493, val_loss: 0.0024032987088763286
epochs 46/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016059088030535924, val_loss: 0.002392509386741689
epochs 47/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015182308987469265, val_loss: 0.002387088490650058
epochs 48/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015469060549022336, val_loss: 0.002387705924255507
epochs 49/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015577175311352078, val_loss: 0.0023899179816778216
epochs 50/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001501599378197601, val_loss: 0.00239483019270535
epochs 51/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001547501960426177, val_loss: 0.0024034391223852125
epochs 52/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001590445451438427, val_loss: 0.002406007078077112
epochs 53/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015924436898019753, val_loss: 0.002399857704793768
epochs 54/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0015755504443261184, val_loss: 0.0023917509409199867
epochs 55/81
Epoch 00055: reducing learning rate of group 0 to 2.2470e-03.
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015168250452629046, val_loss: 0.002390545127647264
epochs 56/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015429422332856216, val_loss: 0.0023914242130038993
epochs 57/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015295637342588682, val_loss: 0.002392213259424482
epochs 58/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015439676905148907, val_loss: 0.002393581023040627
epochs 59/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0014853034719922826, val_loss: 0.0023952291646440116
epochs 60/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015145821141471204, val_loss: 0.0023949218281943884
epochs 61/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015250106121560462, val_loss: 0.002392603633260088
epochs 62/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015525725376056997, val_loss: 0.002389503260409193
epochs 63/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015391324242380888, val_loss: 0.0023856935024793658
epochs 64/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015203605234426888, val_loss: 0.0023842838293473634
epochs 65/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015072772377415708, val_loss: 0.002385300933383405
epochs 66/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015260917771803704, val_loss: 0.002387660738479878
epochs 67/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015167176355852892, val_loss: 0.0023916730424389243
epochs 68/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015467998890304252, val_loss: 0.002393810294701585
epochs 69/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015380973057625325, val_loss: 0.002394448150880635
epochs 70/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015036257694622404, val_loss: 0.002392928282331143
epochs 71/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015387537251961858, val_loss: 0.002390741220941501
epochs 72/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0014987397166949354, val_loss: 0.0023876861835430774
epochs 73/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015416194966651107, val_loss: 0.0023831752727606465
epochs 74/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015248142097047284, val_loss: 0.002377275044896773
epochs 75/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0014734848279898103, val_loss: 0.002371747262908944
epochs 76/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0014555421302487191, val_loss: 0.002367342755730663
epochs 77/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015384998564657412, val_loss: 0.00236309040337801
epochs 78/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0014962812248421342, val_loss: 0.0023615883297419976
epochs 79/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015085423745116904, val_loss: 0.0023597384403858867
epochs 80/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.0015703677126255474, val_loss: 0.0023578727185460074
epochs 81/81
Current Learning Rate: 0.0022469622531271286
train_loss: 0.001528875260172706, val_loss: 0.002359496013793562
Starting fold 2:
epochs 1/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0020016892155814217, val_loss: 0.0494816569345338
epochs 2/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016816620509776637, val_loss: 0.04518395555870874
epochs 3/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0018094882487606917, val_loss: 0.04402919752257211
epochs 4/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0018192831473547897, val_loss: 0.044573536940983365
epochs 5/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001811493435717313, val_loss: 0.04557910455124719
epochs 6/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001725604636336635, val_loss: 0.04635931019272123
epochs 7/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.001740701812058982, val_loss: 0.04659016536814826
epochs 8/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0017169122022053223, val_loss: 0.046408013573714664
epochs 9/81
Current Learning Rate: 0.004190074605625635
train_loss: 0.0016936824191975995, val_loss: 0.04599193057843617
epochs 10/81

[I 2024-01-29 04:20:26,469] Trial 5 pruned.

Current Learning Rate: 0.004190074605625635
train_loss: 0.001676895651698486, val_loss: 0.045641006103583744
epochs 11/81
Starting fold 1:
epochs 1/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.02871799082740357, val_loss: 0.037170650802119065
epochs 2/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.028506335223975936, val_loss: 0.036673118670781456
epochs 3/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.02817850073701457, val_loss: 0.036180349589182585
epochs 4/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.027527040301969178, val_loss: 0.03569248214206368
epochs 5/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.02714151855754225, val_loss: 0.03520933000577821
epochs 6/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.026848770501582245, val_loss: 0.03473059145152253
epochs 7/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.026349168584534996, val_loss: 0.034256701884919374
epochs 8/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.026300891724072004, val_loss: 0.03378664229124311
epochs 9/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.025702406466007233, val_loss: 0.03332145685556705
epochs 10/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.025290971964989837, val_loss: 0.03286097587022201
epochs 11/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.024915592833177038, val_loss: 0.03240534292642402
epochs 12/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.024698333216733055, val_loss: 0.0319546782584102
epochs 13/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.024395848683228617, val_loss: 0.03150844266490331
epochs 14/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.023747162354227743, val_loss: 0.031067823252034565
epochs 15/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.02353588843620137, val_loss: 0.030631776110678122
epochs 16/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.0230259413781919, val_loss: 0.030199724293890454
epochs 17/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.022952974117115926, val_loss: 0.02977203964083283
epochs 18/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.022703225302853083, val_loss: 0.029347458391120195
epochs 19/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.02233483012961714, val_loss: 0.02892751039730178
epochs 20/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.021842156419236407, val_loss: 0.028512018796785797
epochs 21/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.02165981102734804, val_loss: 0.02810028794581297
epochs 22/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.021014118939638136, val_loss: 0.027693416430521263
epochs 23/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.02079769982711265, val_loss: 0.027290977655895172
epochs 24/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.020635113982777845, val_loss: 0.026892721298195067
epochs 25/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.020546973790777356, val_loss: 0.026497681600549234
epochs 26/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.020097896682196543, val_loss: 0.026106524443815626
epochs 27/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.019920605528903634, val_loss: 0.02571924445687463
epochs 28/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.019540882571355292, val_loss: 0.0253348635539176
epochs 29/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.018759944182085365, val_loss: 0.024955829014144247
epochs 30/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01879279223319731, val_loss: 0.02458129732539414
epochs 31/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01852485845355611, val_loss: 0.024211176331081087
epochs 32/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.018155759053402824, val_loss: 0.023844844094975285
epochs 33/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.017941164088092352, val_loss: 0.023482204626792322
epochs 34/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01796113542820278, val_loss: 0.023122364073676408
epochs 35/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.017446184246555755, val_loss: 0.022766311845136066
epochs 36/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01701088764361645, val_loss: 0.02241444753275977
epochs 37/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.016867964616731592, val_loss: 0.02206647323158683
epochs 38/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01663389298084535, val_loss: 0.021721734778669777
epochs 39/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.016386257876691065, val_loss: 0.021380839406182527
epochs 40/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01594334895673551, val_loss: 0.02104347537237185
epochs 41/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.015970752613717006, val_loss: 0.020709696378578585
epochs 42/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.015648938999756386, val_loss: 0.020379259748749
epochs 43/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.015240156248603996, val_loss: 0.02005298354874843
epochs 44/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.015070689195080807, val_loss: 0.019730376434468087
epochs 45/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.014711585484052958, val_loss: 0.019411809387661162
epochs 46/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.014479598863736579, val_loss: 0.019097008412240674
epochs 47/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.014371260902599284, val_loss: 0.018784844183496067
epochs 48/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.013987528513136662, val_loss: 0.018476849175477154
epochs 49/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01360477170857944, val_loss: 0.018172525480468438
epochs 50/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01362484266099177, val_loss: 0.01787128524174766
epochs 51/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01326409627340342, val_loss: 0.017573269902082977
epochs 52/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.012974720340418189, val_loss: 0.017278233405064652
epochs 53/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.012701440190798358, val_loss: 0.016986568847661296
epochs 54/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.012634988442847604, val_loss: 0.01669846209032195
epochs 55/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.012355641976587083, val_loss: 0.016413984632996655
epochs 56/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.012150401372070374, val_loss: 0.016132903635186494
epochs 57/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.011998385656625032, val_loss: 0.01585481602639433
epochs 58/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01176184134949979, val_loss: 0.015579469058485259
epochs 59/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.011560443970129678, val_loss: 0.015307395418406164
epochs 60/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.011519751786009261, val_loss: 0.015038237833077945
epochs 61/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01110113545467979, val_loss: 0.01477254813330041
epochs 62/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01093937013494341, val_loss: 0.014510179234165994
Starting fold 2:
epochs 1/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.012506459955135876, val_loss: 0.0747575179609672
epochs 2/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.011858503235931604, val_loss: 0.07304086291758471
epochs 3/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.011388249260356212, val_loss: 0.07136635841042907
epochs 4/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.010734086730922904, val_loss: 0.06973144833846066
epochs 5/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.01021099024474385, val_loss: 0.06813858134090585
epochs 6/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.00969778963101728, val_loss: 0.06658668997426512
epochs 7/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.009272369776058716, val_loss: 0.06507060688639445
epochs 8/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.008875940239553322, val_loss: 0.06358822533693263
epochs 9/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.008424530867339753, val_loss: 0.0621318729229705
epochs 10/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.008056809313565807, val_loss: 0.06070326063683424
epochs 11/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.007591487699751018, val_loss: 0.05930734654425313
epochs 12/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.007252323693082248, val_loss: 0.057940049087086685
epochs 13/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.0069170442721892475, val_loss: 0.05659833343492614
epochs 14/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.006483796418160397, val_loss: 0.055293459267843334
epochs 15/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.0061661779608990315, val_loss: 0.05402130613882075
epochs 16/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.005839146318597262, val_loss: 0.05277655924123431
epochs 17/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.00549681478863125, val_loss: 0.05156218889292586
epochs 18/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.005200777982427962, val_loss: 0.050379172381427556
epochs 19/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.004910535026725018, val_loss: 0.04922464712665825
epochs 20/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.00465692321605253, val_loss: 0.04809426476873418
epochs 21/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.004418045284206878, val_loss: 0.04699581039566842
epochs 22/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.004108377586433413, val_loss: 0.045924463915446447
epochs 23/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.003863518726508229, val_loss: 0.044884918247738846
epochs 24/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.00371989667124427, val_loss: 0.04386650088918272
epochs 25/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.003434680765193683, val_loss: 0.04287526971369824
epochs 26/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.0032631718854009514, val_loss: 0.04191339092831763
epochs 27/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.003100145418666264, val_loss: 0.040967611093369743
epochs 28/62

[I 2024-01-29 04:20:31,834] Trial 6 pruned.

Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.002859239099734023, val_loss: 0.040046418617878644
epochs 29/62
Current Learning Rate: 5.7213404355968186e-06
train_loss: 0.0026969382195981676, val_loss: 0.03915399170071675
epochs 30/62
Starting fold 1:
epochs 1/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.40772789114914637, val_loss: 0.4291385413793029
epochs 2/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.16810197420418263, val_loss: 0.12942317467202585
epochs 3/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.05833530324070077, val_loss: 0.008027517786816197
epochs 4/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.018620185769702258, val_loss: 0.005867174589882048
epochs 5/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.005728817965198112, val_loss: 0.0021815918787584576
epochs 6/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.0028032748439153167, val_loss: 0.00753171617539708
epochs 7/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.005192107445021209, val_loss: 0.006598359917502397
epochs 8/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.00421849290203107, val_loss: 0.0026339101340257065
epochs 9/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.002498308688671769, val_loss: 0.0014435945804940448
epochs 10/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.0025583454297463362, val_loss: 0.0014216756942760811
epochs 11/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.0022339775043196584, val_loss: 0.0020021140056775597
epochs 12/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.0016673844770258783, val_loss: 0.0032490906225537105
epochs 13/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.0020708226751977284, val_loss: 0.0033823811638824365
epochs 14/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.0022925273392741616, val_loss: 0.0025705957622636877
epochs 15/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.002178678499828828, val_loss: 0.00206020351366273
epochs 16/72
Current Learning Rate: 0.04467051356102407
train_loss: 0.001797394656061538, val_loss: 0.0020539478963073443
epochs 17/72
Epoch 00017: reducing learning rate of group 0 to 1.0513e-02.
Current Learning Rate: 0.0105133422284972
train_loss: 0.0018549713358209517, val_loss: 0.0024121703090954315
epochs 18/72
Current Learning Rate: 0.0105133422284972
train_loss: 0.0019316583645137908, val_loss: 0.0025094569132234606
epochs 19/72
Current Learning Rate: 0.0105133422284972
train_loss: 0.0017143378944111693, val_loss: 0.002580447257348588
epochs 20/72
Current Learning Rate: 0.0105133422284972
train_loss: 0.0019447461129043643, val_loss: 0.0025520552748631905
epochs 21/72
Current Learning Rate: 0.0105133422284972
train_loss: 0.0019739811639546564, val_loss: 0.002495423916828321
epochs 22/72
Current Learning Rate: 0.0105133422284972
train_loss: 0.0015077077158677735, val_loss: 0.002437287065072389
epochs 23/72
Current Learning Rate: 0.0105133422284972
train_loss: 0.0018040790204203834, val_loss: 0.002383147318608487
epochs 24/72
Epoch 00024: reducing learning rate of group 0 to 2.4743e-03.
Current Learning Rate: 0.002474347304346697
train_loss: 0.001714598532079866, val_loss: 0.0023629282121965414
epochs 25/72
Current Learning Rate: 0.002474347304346697
train_loss: 0.001566680264659226, val_loss: 0.002366008377441811
epochs 26/72
Current Learning Rate: 0.002474347304346697
train_loss: 0.0017457419620385687, val_loss: 0.0023686346513583823
epochs 27/72
Current Learning Rate: 0.002474347304346697
train_loss: 0.001741223565094467, val_loss: 0.002378595346170995
epochs 28/72
Current Learning Rate: 0.002474347304346697
train_loss: 0.0017581544441207754, val_loss: 0.0023869674889341235
epochs 29/72
Current Learning Rate: 0.002474347304346697
train_loss: 0.0016717801143194696, val_loss: 0.0023937771766983644
epochs 30/72
Current Learning Rate: 0.002474347304346697
train_loss: 0.0015241580083966255, val_loss: 0.0024082982880630033
epochs 31/72
Epoch 00031: reducing learning rate of group 0 to 5.8235e-04.
Current Learning Rate: 0.0005823452190049095
train_loss: 0.0017504949808905, val_loss: 0.002419850564495261
epochs 32/72

[I 2024-01-29 04:20:33,775] Trial 7 pruned.

Starting fold 1:
epochs 1/96
Current Learning Rate: 0.07348093836819382
train_loss: 5.4268953912438045, val_loss: 0.1747014688120948
epochs 2/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.5211750932429966, val_loss: 0.3286741144127316
epochs 3/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.14582087121334075, val_loss: 0.0036921592351670065
epochs 4/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.05521590068544212, val_loss: 0.039555086857742734
epochs 5/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.02158716135217171, val_loss: 0.009119624065028297
epochs 6/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.01638491070878349, val_loss: 0.022928492062621646
epochs 7/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.014083310798741876, val_loss: 0.0037819306728326613
epochs 8/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.008678056350847903, val_loss: 0.001764104756552519
epochs 9/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.011225512947298979, val_loss: 0.0013984681346401987
epochs 10/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.0044236019872570115, val_loss: 0.0038763125064886278
epochs 11/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.00653271955977145, val_loss: 0.0062288991175591946
epochs 12/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.007331922135658954, val_loss: 0.0033121700721999835
epochs 13/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.004271376690533208, val_loss: 0.0017613961891685096
epochs 14/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.0034237855971839867, val_loss: 0.002028033861683475
epochs 15/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.003735841617086216, val_loss: 0.003445768179113252
epochs 16/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.0055148610034896255, val_loss: 0.00379884513353722
epochs 17/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.002411659028822262, val_loss: 0.0028138403948913845
epochs 18/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.003341926645340496, val_loss: 0.0024019626370217237
epochs 19/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.004670348881106627, val_loss: 0.0026007422452999484
epochs 20/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.004511542414854232, val_loss: 0.0029808254847820434
epochs 21/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.005024055031275279, val_loss: 0.002898338328426083
epochs 22/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.0042417215330428195, val_loss: 0.0025947023467678162
epochs 23/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.00229374192728612, val_loss: 0.0027206371693561473
epochs 24/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.002661499835697836, val_loss: 0.002915796888474789
epochs 25/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.0027625655769186685, val_loss: 0.0027830642195314998
epochs 26/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.003690155572257936, val_loss: 0.002484107215423137
epochs 27/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.0036401069772086644, val_loss: 0.002400608112414678
epochs 28/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.003261904617753125, val_loss: 0.002807996533293691
epochs 29/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.0033347218554761063, val_loss: 0.002768695671370046
epochs 30/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.0022643147332066867, val_loss: 0.002582020384983884
epochs 31/96
Current Learning Rate: 0.07348093836819382
train_loss: 0.0035635015473848113, val_loss: 0.0024023758596740663
epochs 32/96

[I 2024-01-29 04:20:36,108] Trial 8 pruned.

Starting fold 1:
epochs 1/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.003222161060885379, val_loss: 0.0016725286176162107
epochs 2/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0017889143703015227, val_loss: 0.0016978461117971512
epochs 3/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.001600801944732666, val_loss: 0.0022973022571513577
epochs 4/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0016506012161507419, val_loss: 0.002816744799178744
epochs 5/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0018162067869286003, val_loss: 0.0027967007786390326
epochs 6/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0017717965756003794, val_loss: 0.0025004399053397634
epochs 7/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0017087638745770643, val_loss: 0.0022500214344334034
epochs 8/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.001643491404033021, val_loss: 0.0021568003539291637
epochs 9/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.001639646447361692, val_loss: 0.002200560895578256
epochs 10/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0016034670811342566, val_loss: 0.0022905592156189773
epochs 11/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0016038514882032024, val_loss: 0.002365824899503163
epochs 12/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015748694324620852, val_loss: 0.0023739400452801158
epochs 13/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015686044653289413, val_loss: 0.0023461695139606795
epochs 14/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015604612429773337, val_loss: 0.0023003844470377006
epochs 15/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0016535546636748078, val_loss: 0.0022632143061075893
epochs 16/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015563808209998044, val_loss: 0.002251546127751233
epochs 17/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.001583572294514038, val_loss: 0.0022646578782725903
epochs 18/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.001530814977166684, val_loss: 0.00229896709234232
epochs 19/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015936091670913524, val_loss: 0.0023325607697996828
epochs 20/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015828174465384922, val_loss: 0.002352245802444125
epochs 21/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.001548714514233564, val_loss: 0.0023530272781730646
epochs 22/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015954869762553195, val_loss: 0.002337587494698782
epochs 23/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015002407501206586, val_loss: 0.002338816263964252
epochs 24/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0014748202979956802, val_loss: 0.0023353991379577014
epochs 25/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015997390556884439, val_loss: 0.0023284703271374816
epochs 26/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.001526078466007388, val_loss: 0.002335295628105837
epochs 27/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.001487169923309825, val_loss: 0.002343017341835158
epochs 28/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015343279994436, val_loss: 0.0023481600016118987
epochs 29/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.001494455317917623, val_loss: 0.0023533355311623643
epochs 30/62
Current Learning Rate: 0.0011869893573671234
train_loss: 0.0015345593938898099, val_loss: 0.002349927563161131
epochs 31/62

[I 2024-01-29 04:20:38,355] Trial 9 pruned.

Current Learning Rate: 0.0011869893573671234
train_loss: 0.001510191931830425, val_loss: 0.002346564121248703
epochs 32/62
Number of finished trials: 10
Best trial:
Value: 0.005891822827857746
Params:
batch_size: 68
epochs: 79
hidden_size: 44
learning_rate: 0.00022078935295972353
dropout_prob: 0.11862455537099377
weight_decay: 7.078889213386802e-06
lr_step_size: 28
gamma: 0.12912968019210905
num_layers: 3

In [179]:
trainer = ModelActioner(train_data, test_data, device, model_type)
model = trainer.train(trial.params)

epochs 1/79

Current Learning Rate: 0.00022078935295972353
train_loss: 0.42712533657771373
epochs 2/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.3398248373805689
epochs 3/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.23089723345548702
epochs 4/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.07332626369531525
epochs 5/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.07636017390744276
epochs 6/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.05740143414668837
epochs 7/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.03519123312709484
epochs 8/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.022575530587871956
epochs 9/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.012931673994312465
epochs 10/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0075616575059550715
epochs 11/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.007493208540759423
epochs 12/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006598943400520848
epochs 13/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0065511049066838455
epochs 14/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006808368317241317
epochs 15/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006151008422564436
epochs 16/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006518086873093365
epochs 17/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005963322841090515
epochs 18/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005801536664694942
epochs 19/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005900396936314616
epochs 20/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005933429457920107
epochs 21/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005832487656755397
epochs 22/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006089632586054996
epochs 23/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005597768408874058
epochs 24/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005688919146270348
epochs 25/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005610412602735445
epochs 26/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0054901960593061565
epochs 27/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005685053858700893
epochs 28/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005556699224965163
epochs 29/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0052570857706639735
epochs 30/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005119805763545343
epochs 31/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005579564736803198
epochs 32/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00522636233045338
epochs 33/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005953478804145353
epochs 34/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005921007672095023
epochs 35/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005709554559227063
epochs 36/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005447982252874958
epochs 37/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.007055010963723654
epochs 38/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005473930816502528
epochs 39/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00529940725501118
epochs 40/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005362264869431042
epochs 41/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005345638763233363
epochs 42/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004738838226013378
epochs 43/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004826552458599801
epochs 44/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0047200813715136914
epochs 45/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005108330166787894
epochs 46/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0046174542674803
epochs 47/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004648141056249977
epochs 48/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005248996516533754
epochs 49/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005266730245900246
epochs 50/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0049603048180709985
epochs 51/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004315629417060296
epochs 52/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005204918489089884
epochs 53/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004872833285070464
epochs 54/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.00490208308659658
epochs 55/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0053712015823842675
epochs 56/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005509660719988236
epochs 57/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005553080757981421
epochs 58/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0050178782495419755
epochs 59/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0052773590107337625
epochs 60/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005501614485576027
epochs 61/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0050934451154232155
epochs 62/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004904136323936218
epochs 63/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005850167727376856
epochs 64/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005719756424459855
epochs 65/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.006609382697418004
epochs 66/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005246741663857408
epochs 67/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005227128663284925
epochs 68/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.005370037526811272
epochs 69/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0042065985950062845
epochs 70/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004135298536011399
epochs 71/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004343874537948076
epochs 72/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004219933823653648
epochs 73/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0038714786478634185
epochs 74/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0038384543953356763
epochs 75/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0038255339158116326
epochs 76/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004367548434088409
epochs 77/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.003851193078846921
epochs 78/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.004403466994911104
epochs 79/79
Current Learning Rate: 0.00022078935295972353
train_loss: 0.0040497595308931125

In [180]:
preds = trainer.test(trial.params)
preds = np.array(preds)

y_true = y_test[time_step:]
y_true = scaler_adj.inverse_transform(y_true.reshape(-1, 1)).flatten()
preds = scaler_adj.inverse_transform(preds.reshape(-1, 1)).flatten()


mse = mean_squared_error(y_true, preds)
print(f'Mean Squared Error: {mse:.4f}')

rmse = mean_squared_error(y_true, preds, squared=False)
print(f'Root Mean Squared Error: {rmse:.4f}')

r2 = r2_score(y_true, preds)
print(f'R² Score: {r2:.4f}')

mape = mean_absolute_percentage_error(y_true, preds)*100
print(f'mape Score: % {mape:.4f}')

test_loss: 0.0018684213240797896
Mean Squared Error: 39.7373
Root Mean Squared Error: 6.3038
R² Score: 0.8153
mape Score: % 3.0146

In [181]:
y_true

array([141.73774719, 141.07147217, 143.1598053 , 145.11885071,
       142.20515442, 143.48796082, 144.62162781, 149.98167419,
       153.64122009, 150.88661194, 153.79037476, 151.07556152,
       150.03138733, 150.39990234, 153.22843933, 152.58105469,
       154.70243835, 153.08900452, 151.9336853 , 147.88012695,
       148.30839539, 148.79641724, 146.11729431, 147.32237244,
       146.81443787, 144.72291565, 145.32051086, 150.41981506,
       153.20851135, 150.98753357, 152.25239563, 149.9815979 ,
       147.90003967, 149.86207581, 151.973526  , 152.37190247,
       155.22035217, 154.3737793 , 156.76408386, 158.63648987,
       157.19235229, 158.28790283, 159.60256958, 157.64053345,
       157.01307678, 160.1204834 , 161.70404053, 164.23377991,
       165.49867249, 164.96083069, 163.09838867, 163.99476624,
       161.37539673, 160.15036011, 159.45318604, 164.89111328,
       164.5425415 , 164.56245422, 165.79743958, 166.95277405,
       165.97669983, 164.353302  , 164.66204834, 163.10835266,
       163.09838867, 167.72961426, 168.99446106, 168.90483093,
       167.85906982, 166.77348328, 165.12017822, 172.86877441,
       172.79905701, 171.07603455, 172.85879517, 173.04803467,
       172.11054993, 171.61187744, 171.61187744, 172.23022461,
       174.5839386 , 174.69364929, 173.7361908 , 171.10322571,
       171.38247681, 172.52941895, 174.96290588, 176.82794189,
       176.77806091, 179.61050415, 180.46821594, 179.10186768,
       178.73284912, 177.34655762, 180.0892334 , 180.47819519,
       183.30064392, 182.82194519, 183.4602356 , 185.51473999,
       184.42764282, 184.51741028, 183.47021484, 186.50212097,
       186.18295288, 184.7767334 , 187.5592804 , 188.74612427,
       189.08520508, 193.4535675 , 191.94758606, 190.82058716,
       191.29930115, 190.17230225, 188.10783386, 187.57925415,
       189.26473999, 190.03266907, 190.18228149, 193.47351074,
       193.21418762, 194.58055115, 192.61579895, 191.42897034,
       192.23680115, 193.10449219, 193.98214722, 192.70555115,
       195.30860901, 195.92695618, 195.08918762, 192.06724548,
       190.66101074, 181.50546265, 178.37380981, 179.3212738 ,
       177.71556091, 177.49615479, 177.55607605, 179.22389221,
       177.21652222, 176.33769226, 173.77107239, 174.26042175,
       175.60864258, 176.99681091, 180.88169861, 176.14793396,
       178.375     , 179.95292664, 183.87774658, 187.40310669,
       187.62281799, 189.21073914, 189.45040894, 182.66934204,
       177.3263855 , 177.94555664, 179.12400818, 176.06803894,
       173.98078918, 175.50878906, 174.77972412, 177.73583984,
       178.83439636, 175.2591095 , 173.70115662, 174.56001282,
       175.84832764, 171.73374939, 170.20574951, 170.46542358,
       170.98474121, 173.52139282, 172.173172  , 173.43151855,
       174.67987061, 177.25648499, 178.75450134, 178.1552887 ,
       179.56343079, 180.47224426, 178.61468506, 178.48486328,
       176.91691589, 175.60864258, 175.22915649, 172.65254211,
       172.77238464, 173.21180725, 170.87489319, 166.67042542,
       167.99867249, 170.06593323, 170.5453186 , 173.74110413,
       177.33638   , 176.41757202, 178.9941864 , 181.58078003,
       182.64936829, 182.16999817, 186.3999939 , 184.80000305,
       187.44000244, 188.00999451, 189.71000671, 189.69000244,
       191.44999695, 190.63999939, 191.30999756, 189.97000122,
       189.78999329, 190.3999939 , 189.36999512, 189.94999695,
       191.24000549, 189.42999268, 193.41999817, 192.32000732,
       194.27000427, 195.71000671, 193.17999268, 194.71000671,
       197.96000671, 198.11000061, 197.57000732, 195.88999939,
       196.94000244, 194.83000183, 194.67999268, 193.6000061 ,
       193.05000305, 193.1499939 , 193.58000183, 192.52999878,
       185.63999939, 184.25      , 181.91000366, 181.17999268,
       185.55999756, 185.13999939, 186.19000244, 185.58999634,
       185.91999817, 183.63000488, 182.67999268, 188.63000488,
       191.55999756, 193.88999939, 195.17999268])

In [182]:
preds

array([140.88153, 142.02545, 143.21538, 144.47716, 145.80974, 147.05548,
       148.21104, 149.31726, 150.51859, 151.86479, 153.2011 , 154.53159,
       155.7423 , 156.79031, 157.67992, 158.48843, 159.21672, 159.93481,
       160.59639, 161.17113, 161.54651, 161.7084 , 161.66832, 161.36406,
       160.8838 , 160.28766, 159.57819, 158.83385, 158.28058, 158.04747,
       158.06564, 158.32262, 158.6586 , 158.93352, 159.14696, 159.35487,
       159.59505, 159.95728, 160.40158, 160.96846, 161.66122, 162.37941,
       163.09576, 163.79315, 164.38994, 164.86159, 165.31377, 165.80933,
       166.41371, 167.13818, 167.90746, 168.60611, 169.21521, 169.63322,
       169.8375 , 169.81413, 169.79402, 169.83214, 169.96973, 170.21536,
       170.57298, 170.95792, 171.27574, 171.51129, 171.61037, 171.58102,
       171.60162, 171.75478, 172.03944, 172.37364, 172.66513, 172.79843,
       172.9751 , 173.21092, 173.4844 , 173.82672, 174.23137, 174.64845,
       175.0228 , 175.32907, 175.58763, 175.86761, 176.18417, 176.4839 ,
       176.65286, 176.67688, 176.58612, 176.48288, 176.48431, 176.60799,
       176.90027, 177.34201, 177.82469, 178.2638 , 178.57317, 178.83536,
       179.07509, 179.39049, 179.76201, 180.19743, 180.69838, 181.18773,
       181.6394 , 181.99005, 182.32745, 182.65619, 182.94049, 183.24231,
       183.5843 , 183.96239, 184.42383, 184.88097, 185.26605, 185.5865 ,
       185.81094, 185.89082, 185.81018, 185.65874, 185.4976 , 185.34978,
       185.31972, 185.40245, 185.61742, 185.83977, 185.9797 , 186.04427,
       186.07103, 186.11108, 186.14182, 186.23628, 186.3925 , 186.55785,
       186.60326, 186.45976, 185.94533, 185.09471, 184.07503, 182.95477,
       181.80016, 180.64986, 179.59209, 178.5826 , 177.60802, 176.62238,
       175.66739, 174.82307, 174.14713, 173.7697 , 173.52716, 173.46121,
       173.58237, 173.95122, 174.5791 , 175.37505, 176.26974, 177.2105 ,
       177.98186, 178.43863, 178.60675, 178.57007, 178.31665, 177.84702,
       177.26007, 176.59116, 175.97803, 175.49088, 175.04707, 174.59877,
       174.16806, 173.7917 , 173.37369, 172.89386, 172.40096, 171.93321,
       171.593  , 171.34149, 171.22263, 171.25066, 171.51622, 172.01881,
       172.66039, 173.41805, 174.24556, 175.02275, 175.68745, 176.18727,
       176.48778, 176.60191, 176.47574, 176.16388, 175.73512, 175.1669 ,
       174.44127, 173.65417, 172.93036, 172.3089 , 171.90233, 171.82259,
       172.00551, 172.46808, 173.20705, 174.1501 , 175.15187, 176.22067,
       177.25125, 178.26434, 179.23027, 180.16133, 181.02266, 181.83955,
       182.59001, 183.28815, 183.88313, 184.36627, 184.77574, 185.09258,
       185.34232, 185.56944, 185.71007, 185.88667, 186.0514 , 186.26503,
       186.54285, 186.79745, 187.05238, 187.35965, 187.71468, 188.06798,
       188.34288, 188.55986, 188.66132, 188.6649 , 188.55188, 188.31013,
       187.9614 , 187.55946, 187.11531, 186.50403, 185.73596, 184.82867,
       183.8206 , 182.91403, 182.13289, 181.51054, 181.00394, 180.60281,
       180.22743, 179.82317, 179.59193, 179.59804, 179.87605],
      dtype=float32)

In [183]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [184]:
signals = pd.DataFrame(preds, columns=['pred'])
signals["next_day"] = pd.DataFrame(y_true)
signals["today"] = stock_price
signals["Signal_Pred"] = (signals["today"] < signals["pred"]).astype(int)
signals["Signal_True"] = (signals["today"] < signals["next_day"]).astype(int)

signals.head(50)

          pred    next_day       today  Signal_Pred  Signal_True
0   140.881531  141.737747  140.325653            1            1
1   142.025452  141.071472  141.737747            1            0
2   143.215378  143.159805  141.071472            1            1
3   144.477158  145.118851  143.159805            1            1
4   145.809738  142.205154  145.118851            1            0
5   147.055481  143.487961  142.205154            1            1
6   148.211044  144.621628  143.487961            1            1
7   149.317261  149.981674  144.621628            1            1
8   150.518585  153.641220  149.981674            1            1
9   151.864792  150.886612  153.641220            0            0
10  153.201096  153.790375  150.886612            1            1
11  154.531586  151.075562  153.790375            1            0
12  155.742294  150.031387  151.075562            1            0
13  156.790314  150.399902  150.031387            1            1
14  157.679916  153.228439  150.399902            1            1
15  158.488434  152.581055  153.228439            1            0
16  159.216721  154.702438  152.581055            1            1
17  159.934814  153.089005  154.702438            1            0
18  160.596390  151.933685  153.089005            1            0
19  161.171127  147.880127  151.933685            1            0
20  161.546509  148.308395  147.880127            1            1
21  161.708405  148.796417  148.308395            1            1
22  161.668320  146.117294  148.796417            1            0
23  161.364059  147.322372  146.117294            1            1
24  160.883804  146.814438  147.322372            1            0
25  160.287659  144.722916  146.814438            1            0
26  159.578186  145.320511  144.722916            1            1
27  158.833847  150.419815  145.320511            1            1
28  158.280579  153.208511  150.419815            1            1
29  158.047470  150.987534  153.208511            1            0
30  158.065643  152.252396  150.987534            1            1
31  158.322617  149.981598  152.252396            1            0
32  158.658600  147.900040  149.981598            1            0
33  158.933517  149.862076  147.900040            1            1
34  159.146957  151.973526  149.862076            1            1
35  159.354874  152.371902  151.973526            1            1
36  159.595047  155.220352  152.371902            1            1
37  159.957275  154.373779  155.220352            1            0
38  160.401581  156.764084  154.373779            1            1
39  160.968460  158.636490  156.764084            1            1
40  161.661224  157.192352  158.636490            1            0
41  162.379410  158.287903  157.192352            1            1
42  163.095764  159.602570  158.287903            1            1
43  163.793152  157.640533  159.602570            1            0
44  164.389938  157.013077  157.640533            1            0
45  164.861588  160.120483  157.013077            1            1
46  165.313766  161.704041  160.120483            1            1
47  165.809326  164.233780  161.704041            1            1
48  166.413712  165.498672  164.233780            1            1
49  167.138184  164.960831  165.498672            1            0

In [185]:
signals["Signal_Pred"].value_counts()

Signal_Pred
0    127
1    124
Name: count, dtype: int64

In [186]:
signals["Date"] = date_test
signals

           pred    next_day       today  Signal_Pred  Signal_True       Date
0    140.881531  141.737747  140.325653            1            1 2023-01-23
1    142.025452  141.071472  141.737747            1            0 2023-01-24
2    143.215378  143.159805  141.071472            1            1 2023-01-25
3    144.477158  145.118851  143.159805            1            1 2023-01-26
4    145.809738  142.205154  145.118851            1            0 2023-01-27
..          ...         ...         ...          ...          ...        ...
246  180.227432  182.679993  183.630005            0            0 2024-01-16
247  179.823166  188.630005  182.679993            0            1 2024-01-17
248  179.591934  191.559998  188.630005            0            1 2024-01-18
249  179.598038  193.889999  191.559998            0            1 2024-01-19
250  179.876053  195.179993  193.889999            0            1 2024-01-22

[251 rows x 6 columns]

In [187]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [188]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [189]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
buy_signals = signals[signals['Signal_Pred'] == 1]
sell_signals = signals[signals['Signal_Pred'] == 0]

# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]


# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))


# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))


# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [190]:
trace_pred = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['pred'],
    mode='lines+markers',
    name='Predicted'
)

trace_true = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['next_day'],
    mode='lines+markers',
    name='Actual Next Day'
)

# Define the layout
layout = go.Layout(
    title='Predicted vs Actual Next Day Values',
    xaxis=dict(title='Index'),
    yaxis=dict(title='Value'),
    height=700
)

# Create the figure and add traces
fig = go.Figure(data=[trace_pred, trace_true], layout=layout)

# Show the figure
fig.show()