In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as sch
import seaborn as sns

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm
from sklearn.utils.class_weight import compute_class_weight

In [2]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [3]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722878  43.075001  42.314999  102223600
1  2018-01-03  40.715790  43.637501  42.990002  118071600
2  2018-01-04  40.904915  43.367500  43.020000   89738400
3  2018-01-05  41.370625  43.842499  43.262501   94640000
4  2018-01-08  41.216957  43.902500  43.482498   82271200
5  2018-01-09  41.212227  43.764999  43.352501   86336000
6  2018-01-10  41.202774  43.575001  43.250000   95839600
7  2018-01-11  41.436813  43.872501  43.622501   74670800
8  2018-01-12  41.864712  44.340000  43.912498  101672400
9  2018-01-16  41.651943  44.847500  44.035000  118263600
10 2018-01-17  42.339878  44.812500  43.767502  137547200
11 2018-01-18  42.377689  45.025002  44.562500  124773600
12 2018-01-19  42.188583  44.895000  44.352501  129700400
13 2018-01-22  41.843430  44.445000  44.150002  108434400
14 2018-01-23  41.852886  44.860001  44.205002  130756400
15 2018-01-24  41.186230  44.325001  43.299999  204420400
16 2018-01-25  40.451012  43.737499  42.632500  166116000
17 2018-01-26  40.545567  43.000000  42.514999  156572000
18 2018-01-29  39.706337  42.540001  41.767502  202561600
19 2018-01-30  39.472305  41.842499  41.174999  184192800
20 2018-01-31  39.581047  42.110001  41.625000  129915600
21 2018-02-01  39.663784  42.154999  41.689999  188923200
22 2018-02-02  37.942764  41.700001  40.025002  346375200
23 2018-02-05  36.994785  40.970001  39.000000  290954000
24 2018-02-06  38.540874  40.930000  38.500000  272975200
25 2018-02-07  37.715813  40.849998  39.767502  206434400
26 2018-02-08  36.678001  40.250000  38.757500  217562000
27 2018-02-09  37.126637  39.472500  37.560001  282690400
28 2018-02-12  38.622047  40.972500  39.377499  243278000
29 2018-02-13  39.008949  41.187500  40.412498  130196800
30 2018-02-14  39.728180  41.884998  40.720001  162579600
31 2018-02-15  41.062180  43.272499  42.250000  204588800
32 2018-02-16  40.929264  43.705002  42.942501  160704400
33 2018-02-20  40.791584  43.564999  42.855000  135722000
34 2018-02-21  40.606441  43.529999  42.752499  149886400
35 2018-02-22  40.945869  43.487499  42.927502  123967600
36 2018-02-23  41.657982  43.912498  43.384998  135249600
37 2018-02-26  42.481647  44.847500  44.052502  152648800
38 2018-02-27  42.343967  45.119999  44.540001  155712400
39 2018-02-28  42.279884  45.154999  44.512501  151128400
40 2018-03-01  41.539295  44.945000  43.165001  195208000
41 2018-03-02  41.826511  44.075001  43.112499  153816000
42 2018-03-05  41.971306  44.435001  43.630001  113605600
43 2018-03-06  41.935696  44.562500  44.032501   95154000
44 2018-03-07  41.546413  43.962502  43.567501  126814000

In [4]:
time_step = 44

In [5]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [6]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [7]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma_s = talib.SMA(data["Adj Close"], timeperiod=20)
    sma_l = talib.SMA(data["Adj Close"], timeperiod=50)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA_SHORT': sma_s,
        'SMA_LONG': sma_l,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [8]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724164,117105600.0
15,NaN,NaN,55.580774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706160,-87314800.0
16,NaN,NaN,45.152357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695096,-253430800.0
17,NaN,NaN,46.541550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034478,-73.817800,2.684660,-96858800.0
18,NaN,NaN,37.470195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639347,-81.393270,2.635358,-299420400.0
19,NaN,NaN,35.398190,NaN,NaN,42.761511,41.213177,39.664844,41.213177,NaN,NaN,-61.987876,-75.553900,2.599701,-483613200.0
20,NaN,NaN,37.137601,NaN,NaN,42.849896,41.156086,39.462276,41.156086,NaN,NaN,-49.633855,-63.087026,2.602415,-353697600.0
21,NaN,NaN,38.494537,NaN,NaN,42.910291,41.103486,39.296681,41.103486,NaN,NaN,-41.626480,-51.082737,2.600382,-164774400.0
22,NaN,NaN,25.947625,NaN,NaN,43.228470,40.955378,38.682286,40.955378,NaN,NaN,-40.766132,-44.008822,2.560085,-511149600.0
23,NaN,NaN,21.743588,NaN,NaN,43.578811,40.736586,37.894362,40.736586,NaN,NaN,-38.059543,-40.150718,2.593453,-802103600.0
24,NaN,NaN,39.079692,NaN,NaN,43.590207,40.602782,37.615358,40.602782,NaN,NaN,-24.766626,-34.530767,2.689293,-529128400.0
25,NaN,NaN,34.666271,NaN,NaN,43.652103,40.427961,37.203820,40.427961,NaN,NaN,-14.972547,-25.932905,2.662138,-735562800.0
26,NaN,NaN,30.066616,NaN,NaN,43.790974,40.201723,36.612471,40.201723,NaN,NaN,-13.427950,-17.722375,2.652999,-953124800.0
27,NaN,NaN,34.135092,NaN,NaN,43.765512,39.986214,36.206916,39.986214,NaN,NaN,-15.615595,-14.672031,2.663106,-670434400.0
28,NaN,NaN,45.513645,NaN,NaN,43.544885,39.824081,36.103277,39.824081,NaN,NaN,-6.295050,-11.779532,2.747588,-427156400.0
29,NaN,NaN,48.015882,NaN,NaN,43.330502,39.691931,36.053360,39.691931,NaN,NaN,11.072627,-3.612673,2.734579,-296959600.0
30,NaN,NaN,52.392773,NaN,NaN,42.991933,39.561346,36.130759,39.561346,NaN,NaN,26.336873,10.371483,2.744684,-134380000.0
31,NaN,NaN,59.246573,NaN,NaN,42.753755,39.495571,36.237386,39.495571,NaN,NaN,41.539597,26.316365,2.801801,70208800.0
32,NaN,NaN,58.345274,NaN,NaN,42.524617,39.432605,36.340593,39.432605,NaN,NaN,51.997622,39.958031,2.790445,-90495600.0
33,-0.373865,-0.940887,57.371668,NaN,NaN,42.339138,39.380012,36.420887,39.380012,NaN,NaN,56.241815,49.926345,2.779394,-226217600.0
34,-0.274210,-0.807551,56.017962,NaN,NaN,42.113883,39.317690,36.521498,39.317690,NaN,NaN,52.331352,53.523596,2.776467,-376104000.0
35,-0.165931,-0.679227,57.975696,NaN,NaN,42.071539,39.305672,36.539805,39.305672,NaN,NaN,52.421427,53.664865,2.783938,-252136400.0
36,-0.022400,-0.547862,61.815838,NaN,NaN,42.278024,39.366021,36.454017,39.366021,NaN,NaN,56.395076,53.715952,2.796987,-116886800.0
37,0.156015,-0.407086,65.717957,NaN,NaN,42.641730,39.462825,36.283919,39.462825,NaN,NaN,62.381594,57.066033,2.825025,35762000.0
38,0.283037,-0.269062,64.530851,NaN,NaN,43.012923,39.594706,36.176489,39.594706,NaN,NaN,65.108407,61.295026,2.811691,-119950400.0
39,0.374218,-0.140406,63.951802,NaN,NaN,43.346791,39.735085,36.123379,39.735085,NaN,NaN,64.320030,63.936677,2.811644,-271078800.0
40,0.382314,-0.035862,57.527288,NaN,NaN,43.527908,39.832998,36.138087,39.832998,NaN,NaN,59.272747,62.900395,2.801178,-466286800.0
41,0.407211,0.052753,59.237555,NaN,NaN,43.735166,39.941134,36.147101,39.941134,NaN,NaN,52.309014,58.633930,2.782216,-312470800.0
42,0.433628,0.128928,60.109622,NaN,NaN,43.918540,40.142561,36.366582,40.142561,NaN,NaN,42.550435,51.377399,2.769807,-198865200.0
43,0.446542,0.192451,59.770944,NaN,NaN,43.949839,40.389606,36.829374,40.389606,NaN,40.596320,34.223026,43.027492,2.757049,-294019200.0
44,0.420518,0.238064,56.052889,4.051349,0.823536,44.028293,40.539883,37.051474,40.539883,NaN,40.638546,12.020141,29.597868,2.704888,-420833200.0

In [9]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722878
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715790
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904915
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370625
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216957
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212227
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202774
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436813
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864712
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651943
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339878
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377689
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188583
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843430
14,NaN,NaN,68.998501,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724164,117105600.0,41.852886
15,NaN,NaN,55.580774,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706160,-87314800.0,41.186230
16,NaN,NaN,45.152357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695096,-253430800.0,40.451012
17,NaN,NaN,46.541550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034478,-73.817800,2.684660,-96858800.0,40.545567
18,NaN,NaN,37.470195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639347,-81.393270,2.635358,-299420400.0,39.706337
19,NaN,NaN,35.398190,NaN,NaN,42.761511,41.213177,39.664844,41.213177,NaN,NaN,-61.987876,-75.553900,2.599701,-483613200.0,39.472305
20,NaN,NaN,37.137601,NaN,NaN,42.849896,41.156086,39.462276,41.156086,NaN,NaN,-49.633855,-63.087026,2.602415,-353697600.0,39.581047
21,NaN,NaN,38.494537,NaN,NaN,42.910291,41.103486,39.296681,41.103486,NaN,NaN,-41.626480,-51.082737,2.600382,-164774400.0,39.663784
22,NaN,NaN,25.947625,NaN,NaN,43.228470,40.955378,38.682286,40.955378,NaN,NaN,-40.766132,-44.008822,2.560085,-511149600.0,37.942764
23,NaN,NaN,21.743588,NaN,NaN,43.578811,40.736586,37.894362,40.736586,NaN,NaN,-38.059543,-40.150718,2.593453,-802103600.0,36.994785
24,NaN,NaN,39.079692,NaN,NaN,43.590207,40.602782,37.615358,40.602782,NaN,NaN,-24.766626,-34.530767,2.689293,-529128400.0,38.540874
25,NaN,NaN,34.666271,NaN,NaN,43.652103,40.427961,37.203820,40.427961,NaN,NaN,-14.972547,-25.932905,2.662138,-735562800.0,37.715813
26,NaN,NaN,30.066616,NaN,NaN,43.790974,40.201723,36.612471,40.201723,NaN,NaN,-13.427950,-17.722375,2.652999,-953124800.0,36.678001
27,NaN,NaN,34.135092,NaN,NaN,43.765512,39.986214,36.206916,39.986214,NaN,NaN,-15.615595,-14.672031,2.663106,-670434400.0,37.126637
28,NaN,NaN,45.513645,NaN,NaN,43.544885,39.824081,36.103277,39.824081,NaN,NaN,-6.295050,-11.779532,2.747588,-427156400.0,38.622047
29,NaN,NaN,48.015882,NaN,NaN,43.330502,39.691931,36.053360,39.691931,NaN,NaN,11.072627,-3.612673,2.734579,-296959600.0,39.008949
30,NaN,NaN,52.392773,NaN,NaN,42.991933,39.561346,36.130759,39.561346,NaN,NaN,26.336873,10.371483,2.744684,-134380000.0,39.728180
31,NaN,NaN,59.246573,NaN,NaN,42.753755,39.495571,36.237386,39.495571,NaN,NaN,41.539597,26.316365,2.801801,70208800.0,41.062180
32,NaN,NaN,58.345274,NaN,NaN,42.524617,39.432605,36.340593,39.432605,NaN,NaN,51.997622,39.958031,2.790445,-90495600.0,40.929264
33,-0.373865,-0.940887,57.371668,NaN,NaN,42.339138,39.380012,36.420887,39.380012,NaN,NaN,56.241815,49.926345,2.779394,-226217600.0,40.791584
34,-0.274210,-0.807551,56.017962,NaN,NaN,42.113883,39.317690,36.521498,39.317690,NaN,NaN,52.331352,53.523596,2.776467,-376104000.0,40.606441
35,-0.165931,-0.679227,57.975696,NaN,NaN,42.071539,39.305672,36.539805,39.305672,NaN,NaN,52.421427,53.664865,2.783938,-252136400.0,40.945869
36,-0.022400,-0.547862,61.815838,NaN,NaN,42.278024,39.366021,36.454017,39.366021,NaN,NaN,56.395076,53.715952,2.796987,-116886800.0,41.657982
37,0.156015,-0.407086,65.717957,NaN,NaN,42.641730,39.462825,36.283919,39.462825,NaN,NaN,62.381594,57.066033,2.825025,35762000.0,42.481647
38,0.283037,-0.269062,64.530851,NaN,NaN,43.012923,39.594706,36.176489,39.594706,NaN,NaN,65.108407,61.295026,2.811691,-119950400.0,42.343967
39,0.374218,-0.140406,63.951802,NaN,NaN,43.346791,39.735085,36.123379,39.735085,NaN,NaN,64.320030,63.936677,2.811644,-271078800.0,42.279884
40,0.382314,-0.035862,57.527288,NaN,NaN,43.527908,39.832998,36.138087,39.832998,NaN,NaN,59.272747,62.900395,2.801178,-466286800.0,41.539295
41,0.407211,0.052753,59.237555,NaN,NaN,43.735166,39.941134,36.147101,39.941134,NaN,NaN,52.309014,58.633930,2.782216,-312470800.0,41.826511
42,0.433628,0.128928,60.109622,NaN,NaN,43.918540,40.142561,36.366582,40.142561,NaN,NaN,42.550435,51.377399,2.769807,-198865200.0,41.971306
43,0.446542,0.192451,59.770944,NaN,NaN,43.949839,40.389606,36.829374,40.389606,NaN,40.596320,34.223026,43.027492,2.757049,-294019200.0,41.935696
44,0.420518,0.238064,56.052889,4.051349,0.823536,44.028293,40.539883,37.051474,40.539883,NaN,40.638546,12.020141,29.597868,2.704888,-420833200.0,41.546413

In [10]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.567014,0.443929,58.241593,7.100844,1.143616,43.382889,41.728832,40.074776,41.728832,40.814298,41.035720,-7.013279,-3.909588,2.715223,-3.124152e+08,42.355843
1,0.548495,0.464842,58.592132,7.332835,1.202908,43.261033,41.862708,40.464382,41.862708,40.847954,41.096607,-20.016654,-8.448281,2.714433,-2.214400e+08,42.405682
2,0.515806,0.475035,57.044847,6.516185,0.819332,43.280290,41.922406,40.564522,41.922406,40.878761,41.148142,-27.991884,-18.340606,2.690139,-3.790588e+08,42.256145
3,0.432812,0.466590,50.806328,3.052068,-0.254211,43.245420,41.956468,40.667515,41.956468,40.892873,41.168692,-36.985453,-28.331331,2.648797,-5.128460e+08,41.610500
4,0.361721,0.445616,50.674730,2.976506,-0.055679,43.183918,41.996702,40.809485,41.996702,40.897386,41.187695,-46.752180,-37.243173,2.644562,-5.914436e+08,41.596264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [11]:
indicators_with_price['Prev_Adj_Close'] = indicators_with_price['Adj Close'].shift(1)
indicators_with_price['Return'] = ((indicators_with_price['Adj Close'] - indicators_with_price['Prev_Adj_Close'])/indicators_with_price['Prev_Adj_Close'])*100
indicators_with_price['Signal'] = np.where(indicators_with_price['Return'] > 1, 1,
                                           np.where(indicators_with_price['Return'] < -1, 2, 0))
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
0,0.567014,0.443929,58.241593,7.100844,1.143616,43.382889,41.728832,40.074776,41.728832,40.814298,41.035720,-7.013279,-3.909588,2.715223,-3.124152e+08,42.355843,NaN,NaN,0
1,0.548495,0.464842,58.592132,7.332835,1.202908,43.261033,41.862708,40.464382,41.862708,40.847954,41.096607,-20.016654,-8.448281,2.714433,-2.214400e+08,42.405682,42.355843,0.117667,0
2,0.515806,0.475035,57.044847,6.516185,0.819332,43.280290,41.922406,40.564522,41.922406,40.878761,41.148142,-27.991884,-18.340606,2.690139,-3.790588e+08,42.256145,42.405682,-0.352632,0
3,0.432812,0.466590,50.806328,3.052068,-0.254211,43.245420,41.956468,40.667515,41.956468,40.892873,41.168692,-36.985453,-28.331331,2.648797,-5.128460e+08,41.610500,42.256145,-1.527932,2
4,0.361721,0.445616,50.674730,2.976506,-0.055679,43.183918,41.996702,40.809485,41.996702,40.897386,41.187695,-46.752180,-37.243173,2.644562,-5.914436e+08,41.596264,41.610500,-0.034214,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [12]:
indicators_with_price["Signal"].value_counts()

Signal
0    737
1    414
2    324
Name: count, dtype: int64

In [13]:
indicators_with_price.dropna(inplace=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
1,0.548495,0.464842,58.592132,7.332835,1.202908,43.261033,41.862708,40.464382,41.862708,40.847954,41.096607,-20.016654,-8.448281,2.714433,-2.214400e+08,42.405682,42.355843,0.117667,0
2,0.515806,0.475035,57.044847,6.516185,0.819332,43.280290,41.922406,40.564522,41.922406,40.878761,41.148142,-27.991884,-18.340606,2.690139,-3.790588e+08,42.256145,42.405682,-0.352632,0
3,0.432812,0.466590,50.806328,3.052068,-0.254211,43.245420,41.956468,40.667515,41.956468,40.892873,41.168692,-36.985453,-28.331331,2.648797,-5.128460e+08,41.610500,42.256145,-1.527932,2
4,0.361721,0.445616,50.674730,2.976506,-0.055679,43.183918,41.996702,40.809485,41.996702,40.897386,41.187695,-46.752180,-37.243173,2.644562,-5.914436e+08,41.596264,41.610500,-0.034214,0
5,0.226728,0.401839,42.776537,-1.895735,-1.685955,43.175301,41.999076,40.822850,41.999076,40.886125,41.163972,-59.960224,-47.899286,2.611110,-7.396632e+08,40.653923,41.596264,-2.265446,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [14]:
indicators_with_price.columns

Index(['MACD', 'MACD_signal', 'RSI', 'CMO', 'MOM', 'Upper_BB', 'Middle_BB',
       'Lower_BB', 'SMA_SHORT', 'SMA_LONG', 'EMA', 'SLOWK', 'SLOWD', 'ATR',
       'OBV', 'Adj Close', 'Prev_Adj_Close', 'Return', 'Signal'],
      dtype='object')

In [15]:
# indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close', 'Return'])
# indicators_with_price

In [16]:
indicators_with_price.drop(columns=['Prev_Adj_Close', "Signal"], inplace=True)
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Return
1,0.548495,0.464842,58.592132,7.332835,1.202908,43.261033,41.862708,40.464382,41.862708,40.847954,41.096607,-20.016654,-8.448281,2.714433,-2.214400e+08,42.405682,0.117667
2,0.515806,0.475035,57.044847,6.516185,0.819332,43.280290,41.922406,40.564522,41.922406,40.878761,41.148142,-27.991884,-18.340606,2.690139,-3.790588e+08,42.256145,-0.352632
3,0.432812,0.466590,50.806328,3.052068,-0.254211,43.245420,41.956468,40.667515,41.956468,40.892873,41.168692,-36.985453,-28.331331,2.648797,-5.128460e+08,41.610500,-1.527932
4,0.361721,0.445616,50.674730,2.976506,-0.055679,43.183918,41.996702,40.809485,41.996702,40.897386,41.187695,-46.752180,-37.243173,2.644562,-5.914436e+08,41.596264,-0.034214
5,0.226728,0.401839,42.776537,-1.895735,-1.685955,43.175301,41.999076,40.822850,41.999076,40.886125,41.163972,-59.960224,-47.899286,2.611110,-7.396632e+08,40.653923,-2.265446
6,0.072556,0.335982,38.805987,-4.708037,-2.298199,43.330934,41.955757,40.580579,41.955757,40.863470,41.115772,-60.364631,-55.692345,2.604322,-9.056264e+08,40.079491,-1.412981
7,-0.123097,0.244166,33.410034,-9.019912,-3.037205,43.669844,41.830427,39.991009,41.830427,40.822442,41.028466,-57.037738,-59.120864,2.589764,-1.069742e+09,39.151379,-2.315678
8,-0.126721,0.169989,48.771985,0.230804,-0.833454,43.603897,41.756843,39.909789,41.756843,40.813906,41.027644,-35.113180,-50.838516,2.699325,-9.195768e+08,41.009975,4.747207
9,-0.211999,0.093591,42.761365,-4.462443,-1.894463,43.620649,41.637566,39.654483,41.637566,40.775780,40.980123,-25.755924,-39.302281,2.704911,-1.083267e+09,39.958424,-2.564137
10,-0.311617,0.012550,40.504319,-6.346464,-1.669312,43.661175,41.499417,39.337660,41.499417,40.733079,40.915092,-23.129921,-27.999675,2.693601,-1.249941e+09,39.516918,-1.104912
11,-0.361498,-0.062260,42.777708,-4.867452,-0.625511,43.694935,41.413728,39.132521,41.413728,40.682792,40.866666,-31.639081,-26.841642,2.745528,-1.096347e+09,39.825500,0.780887
12,-0.417288,-0.133265,41.338348,-5.999350,-0.981171,43.709493,41.300622,38.891751,41.300622,40.626526,40.808787,-33.350066,-29.373023,2.721526,-1.246694e+09,39.564396,-0.655622
13,-0.423862,-0.191385,44.466606,-4.030402,0.263966,43.655487,41.200572,38.745657,41.200572,40.582160,40.771521,-30.537715,-31.842287,2.714496,-1.125582e+09,39.970303,1.025939
14,-0.363212,-0.225750,49.885820,-0.435834,1.262306,43.579272,41.140518,38.701763,41.140518,40.559984,40.769881,-23.649269,-29.179017,2.737189,-9.871604e+08,40.734612,1.912192
15,-0.289022,-0.238404,51.759448,0.859631,1.436035,43.546091,41.114051,38.682011,41.114051,40.543268,40.780867,-13.681403,-22.622796,2.743310,-8.794276e+08,41.017082,0.693442
16,-0.311295,-0.252983,45.025977,-3.853639,0.304138,43.457729,41.012458,38.567187,41.012458,40.518902,40.744736,-15.941750,-17.757474,2.697568,-1.019449e+09,39.967922,-2.557861
17,-0.293576,-0.261101,47.789704,-2.010580,2.421570,43.223495,40.894606,38.565717,40.894606,40.517168,40.727830,-20.849013,-16.824055,2.740926,-9.033780e+08,40.364334,0.991825
18,-0.215754,-0.252032,52.696970,1.419629,4.129131,42.889427,40.794081,38.698735,40.794081,40.528735,40.745434,-19.854978,-18.881914,2.769121,-7.897436e+08,41.123917,1.881816
19,-0.167663,-0.235158,51.380458,0.543892,2.390762,42.607668,40.704712,38.801756,40.704712,40.553241,40.753709,-10.384828,-17.029606,2.739619,-8.794700e+08,40.931637,-0.467562
20,-0.095884,-0.207303,53.978887,2.354475,3.619343,42.427112,40.653678,38.880244,40.653678,40.590498,40.779551,0.477004,-9.920934,2.745243,-7.879128e+08,41.335155,0.985836
21,-0.027383,-0.171319,54.880161,2.981709,4.797199,42.237334,40.607154,38.976974,40.607154,40.628381,40.810469,4.591570,-1.772085,2.736643,-6.874156e+08,41.475201,0.338804
22,0.047238,-0.127608,56.572313,4.145730,4.607300,42.118852,40.581043,39.043235,40.581043,40.669784,40.851512,13.924888,6.331154,2.724904,-6.011020e+08,41.733936,0.623832
23,0.150987,-0.071889,60.145914,6.689050,3.686314,42.272666,40.615936,38.959207,40.615936,40.757096,40.916261,22.180739,13.565733,2.744630,-4.946804e+08,42.308361,1.376397
24,0.222977,-0.012916,59.277723,6.212456,3.204475,42.395831,40.646795,38.897758,40.646795,40.861469,40.973913,28.084427,21.396685,2.719774,-5.776984e+08,42.213425,-0.224392
25,0.181404,0.025948,49.567794,0.427644,1.288902,42.421433,40.664952,38.908472,40.664952,40.910993,40.975831,20.146205,23.470457,2.642224,-7.169336e+08,41.017082,-2.834033
26,0.012705,0.023300,39.724081,-6.863780,-1.725647,42.461950,40.627805,38.793659,40.627805,40.943408,40.902974,-8.290773,13.313286,2.581202,-9.788980e+08,39.336533,-4.097194
27,-0.128701,-0.007100,39.156307,-7.330557,-1.706673,42.454274,40.631365,38.808456,40.631365,40.994299,40.828290,-34.549911,-7.564827,2.567792,-1.124960e+09,39.222591,-0.289657
28,-0.281575,-0.061995,36.466774,-9.553060,-2.114944,42.515717,40.514698,38.513680,40.514698,41.025299,40.732661,-45.877138,-29.572607,2.552944,-1.259728e+09,38.676640,-1.391932
29,-0.384694,-0.126535,37.885167,-8.729343,-1.761265,42.577350,40.459036,38.340722,40.459036,41.029762,40.648773,-39.397682,-39.941577,2.561902,-1.146200e+09,38.845177,0.435760
30,-0.450308,-0.191290,39.061316,-8.061923,-1.965397,42.610306,40.432214,38.254121,40.432214,41.029193,40.574626,-33.203249,-39.492690,2.563718,-1.034348e+09,38.980473,0.348295
31,-0.532561,-0.259544,36.575151,-9.947417,-3.128510,42.686411,40.367412,38.048414,40.367412,41.005218,40.483730,-32.806024,-35.135651,2.530740,-1.176971e+09,38.529472,-1.156990
32,-0.535266,-0.314688,42.656997,-6.489550,-3.254322,42.697389,40.350559,38.003729,40.350559,40.968521,40.427890,-28.595185,-31.534819,2.584653,-1.007261e+09,39.227325,1.811219
33,-0.458573,-0.343465,49.472287,-2.193923,-2.205139,42.701500,40.358985,38.016470,40.358985,40.952713,40.415043,-18.764813,-26.722007,2.619512,-7.929836e+08,40.138828,2.323643
34,-0.251814,-0.325135,59.544953,5.401811,-0.367924,42.852527,40.417853,37.983178,40.417853,40.975120,40.481573,5.866454,-13.831181,2.739452,-5.268260e+08,41.911961,4.417499
35,-0.080893,-0.276287,59.913635,5.709035,0.448627,42.984216,40.466395,37.948573,40.466395,41.002750,40.548522,25.969112,4.356918,2.719708,-3.905532e+08,41.987923,0.181242
36,0.185351,-0.183959,66.948250,12.047531,1.808735,43.506955,40.649761,37.792566,40.649761,41.056537,40.685709,45.736733,25.857433,2.816484,-1.657480e+08,43.635246,3.923327
37,0.417020,-0.063763,68.103506,13.191903,1.979649,44.022555,40.829092,37.635629,40.829092,41.102397,40.830831,51.666162,41.124002,2.849754,4.057600e+06,43.950954,0.723516
38,0.610626,0.071114,68.887152,13.958423,2.226509,44.489629,40.981006,37.472383,40.981006,41.136008,40.978892,58.084103,51.828999,2.832203,1.176688e+08,44.162205,0.480650
39,0.780157,0.212923,70.053378,15.087678,2.926727,44.982154,41.158081,37.334009,41.158081,41.178591,41.134192,59.732738,56.494334,2.821888,2.105136e+08,44.473141,0.704077
40,0.954837,0.361306,72.337932,17.358356,3.109509,45.541693,41.346788,37.151883,41.346788,41.235179,41.310863,63.227708,60.348183,2.843136,3.224708e+08,45.109291,1.430415
41,1.067128,0.502470,70.770059,16.498722,2.216362,45.997976,41.519915,37.041854,41.519915,41.303148,41.472058,64.911913,62.624120,2.811891,2.176220e+08,44.937744,-0.380292
42,1.134580,0.628892,69.774546,15.967422,1.698475,46.380497,41.674863,36.969229,41.674863,41.363276,41.621428,64.592791,64.244137,2.785667,1.345068e+08,44.832886,-0.233341
43,1.141993,0.731512,65.895553,13.901970,1.706417,46.631595,41.780716,36.929837,41.780716,41.412358,41.746050,61.526820,63.677175,2.724878,3.972600e+07,44.425426,-0.908840
44,1.167861,0.818782,67.853895,15.469551,2.484192,46.941607,41.912047,36.882487,41.912047,41.470445,41.883561,61.088758,62.402790,2.722356,1.164584e+08,44.840034,0.933267
45,1.152200,0.885466,65.100645,14.016811,2.150799,47.228045,42.089017,36.949988,42.089017,41.530646,42.002357,59.272275,60.629284,2.698435,4.728240e+07,44.556480,-0.632368
46,1.113872,0.931147,63.514593,13.184130,2.138294,47.411582,42.341912,37.272242,42.341912,41.578540,42.108672,56.482846,58.947960,2.676834,-2.590840e+07,44.394440,-0.363675
47,1.096242,0.964166,65.282728,14.425472,3.098480,47.573561,42.616231,37.658902,42.616231,41.618292,42.224241,45.620240,53.791787,2.694422,4.769480e+07,44.708981,0.708514
48,1.061003,0.983533,64.091860,13.832515,3.000732,47.592550,42.912249,38.231948,42.912249,41.647543,42.329697,34.736676,45.613254,2.681322,-1.326800e+07,44.596996,-0.250474
49,1.044112,0.995649,65.806989,14.983572,4.229008,47.574088,43.214137,38.854185,43.214137,41.690822,42.443174,22.112272,34.156396,2.670371,6.696560e+07,44.882931,0.641152
50,1.014988,0.999517,65.219821,14.709143,4.753395,47.457195,43.506758,39.556320,43.506758,41.740363,42.549383,-9.602693,15.748752,2.645849,-2.597040e+07,44.832886,-0.111501

In [17]:
y = indicators_with_price["Return"]
y_2 = indicators_with_price["SMA_SHORT"]
y_3 = indicators_with_price["EMA"]
y_4 = indicators_with_price["Upper_BB"]
y_5 = indicators_with_price["Middle_BB"]
y_6 = indicators_with_price["Lower_BB"]
X = np.array(date)

trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



layout = go.Layout(
    title='Stock Price and Volume',
    xaxis=dict(title='Date'),
    yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
    yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
    height=600,
)

fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# Show plot
pyo.iplot(fig)

In [18]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        X_window = self.X[idx : idx + self.window_size]
        
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [19]:
X = indicators_with_price.iloc[:,:-1]
y = indicators_with_price.iloc[:,-2]

signal_true = indicators_with_price.iloc[:,-1]
y

1        42.405682
2        42.256145
3        41.610500
4        41.596264
5        40.653923
           ...
1470    182.679993
1471    188.630005
1472    191.559998
1473    193.889999
1474    195.179993
Name: Adj Close, Length: 1474, dtype: float64

In [20]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1180    1.297126
1181    0.378196
1182   -2.168029
1183    1.466111
1184    0.592655
          ...
1470   -0.517351
1471    3.257068
1472    1.553301
1473    1.216330
1474    0.665322
Name: Return, Length: 295, dtype: float64

In [21]:
correlation_matrix = X.corr()

# Perform hierarchical clustering to find the order of features
linked = sch.linkage(sch.distance.pdist(correlation_matrix), method='ward')
cluster_order = sch.dendrogram(linked, no_plot=True)['leaves']

# Reorder the correlation matrix
correlation_matrix_ordered = correlation_matrix.iloc[cluster_order, cluster_order]

fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix_ordered,
                    x=correlation_matrix_ordered.columns,
                    y=correlation_matrix_ordered.columns,
                    colorscale='Viridis',
                    text=correlation_matrix_ordered.round(2).values,  
                    texttemplate="%{text}",
                    textfont={"size":9}  
                    ))

# Update the layout
fig.update_layout(
    title='Ordered Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  
    height=1000,  
)

# Show the figure
pyo.iplot(fig)

In [22]:
X= X.iloc[:, cluster_order]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

y_test.head(44)

1180    149.882217
1181    150.449066
1182    147.187286
1183    149.345215
1184    150.230316
1185    147.286728
1186    143.418350
1187    140.385315
1188    147.207184
1189    147.485626
1190    146.988403
1191    145.814972
1192    142.115646
1193    140.156586
1194    141.857086
1195    141.369812
1196    143.686859
1197    144.661423
1198    142.413971
1199    135.741272
1200    133.762329
1201    131.634216
1202    131.564621
1203    134.697113
1204    131.494995
1205    131.127060
1206    129.307236
1207    125.339409
1208    128.889572
1209    129.207794
1210    124.374794
1211    125.657639
1212    124.325073
1213    128.899506
1214    129.426559
1215    130.003342
1216    132.748016
1217    132.668457
1218    134.010941
1219    135.184372
1220    134.458435
1221    134.518112
1222    137.103653
1223    140.325653
Name: Adj Close, dtype: float64

In [24]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

X_train_df = X_train
X_test_df = X_test

for column in X_train.columns:

    if column not in ["Adj Close", "Return"]:
        scaler = MinMaxScaler()

        X_train_scaled = scaler.fit_transform(X_train[[column]].values)
        X_train_df[column] = X_train_scaled
            
        X_test_scaled = scaler.transform(X_test[[column]].values)
        X_test_df[column] = X_test_scaled

        scaler_dict[column] = scaler


X_train_df.head(24)

features = X_train_df.columns
X_train_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1,0.177936,0.261686,42.405682,0.048691,0.032213,0.037797,0.037797,0.016755,0.014072,0.483867,0.507175,0.508804,0.493383,0.498960,0.567548,0.468234
2,0.172548,0.234481,42.256145,0.049438,0.032346,0.038231,0.038231,0.016988,0.014472,0.447236,0.458580,0.506461,0.494198,0.494286,0.542886,0.458078
3,0.163379,0.211390,41.610500,0.050206,0.032106,0.038478,0.038478,0.017095,0.014632,0.405928,0.409501,0.500513,0.493523,0.481205,0.443453,0.414997
4,0.162440,0.197825,41.596264,0.051265,0.031682,0.038770,0.038770,0.017129,0.014780,0.361069,0.365722,0.495417,0.491846,0.483624,0.441356,0.414058
5,0.155021,0.172243,40.653923,0.051365,0.031623,0.038787,0.038787,0.017044,0.014595,0.300403,0.313374,0.485742,0.488346,0.463760,0.315470,0.353465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,0.850805,0.753803,146.053619,0.738088,0.800862,0.778358,0.778358,0.818604,0.829435,0.680159,0.631199,0.340107,0.343542,0.360230,0.463731,0.349551
1176,0.849089,0.770024,148.867889,0.744000,0.803314,0.782527,0.782527,0.817400,0.830427,0.747329,0.665570,0.388138,0.347930,0.321213,0.506322,0.377026
1177,0.803297,0.757360,147.455780,0.746416,0.805266,0.784731,0.784731,0.816305,0.830887,0.835637,0.739664,0.418622,0.358240,0.420018,0.480797,0.363376
1178,0.812803,0.772871,149.206009,0.747900,0.808367,0.787087,0.787087,0.815668,0.831932,0.856512,0.802536,0.453092,0.374178,0.423562,0.508856,0.380638
1179,0.765326,0.761787,147.962952,0.749683,0.810260,0.788953,0.788953,0.814627,0.832500,0.850520,0.839325,0.473178,0.391410,0.443981,0.484405,0.368317

In [25]:
scaler_adj = MinMaxScaler()
scaler_adj.fit(X_train[["Adj Close"]].values)

X_train_df['Adj Close'] = scaler_adj.transform(X_train[['Adj Close']].values).flatten()
X_test_df['Adj Close'] = scaler_adj.transform(X_test[['Adj Close']].values).flatten()

y_train = scaler_adj.transform(y_train.values.reshape(-1,1)).flatten()
y_test = scaler_adj.transform(y_test.values.reshape(-1,1)).flatten()

X_test_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1180,0.764804,0.775662,0.793797,0.751875,0.813419,0.791684,0.791684,0.814103,0.833706,0.876576,0.853920,0.499847,0.411144,0.487569,0.517393,0.387563
1181,0.724522,0.788577,0.797684,0.752021,0.816204,0.793223,0.793223,0.813227,0.835055,0.895161,0.867699,0.523637,0.432238,0.448749,0.527280,0.393263
1182,0.685712,0.778442,0.775317,0.751879,0.815519,0.792793,0.792793,0.810946,0.835217,0.907287,0.887937,0.523008,0.448973,0.379729,0.456306,0.359879
1183,0.661729,0.787383,0.790114,0.752318,0.813808,0.792104,0.792104,0.810434,0.836117,0.913913,0.901248,0.534244,0.464868,0.444492,0.497611,0.382097
1184,0.623617,0.797445,0.796184,0.752139,0.815320,0.792815,0.792815,0.809834,0.837282,0.923476,0.911343,0.547371,0.480511,0.467133,0.514479,0.391191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,0.263755,0.912203,1.018693,1.078159,1.105702,1.104494,1.104494,1.140327,1.152418,0.696649,0.699736,0.331987,0.360467,0.438975,0.219193,0.330142
1471,0.316961,0.925666,1.059493,1.079371,1.099583,1.101858,1.101858,1.142176,1.152792,0.728273,0.697239,0.358007,0.354748,0.530971,0.456177,0.434229
1472,0.316624,0.937531,1.079584,1.082407,1.093074,1.099905,1.099905,1.144078,1.154161,0.814261,0.731129,0.396416,0.358741,0.534505,0.541661,0.480564
1473,0.323439,0.947909,1.095561,1.083019,1.091863,1.099564,1.099564,1.145941,1.156274,0.926300,0.813002,0.440664,0.371807,0.555951,0.601114,0.515679
1474,0.300461,0.955220,1.104406,1.082644,1.092553,1.099746,1.099746,1.147838,1.158738,0.984412,0.904319,0.483036,0.391711,0.550955,0.631898,0.534629

In [26]:
correlation_matrix = X_train_df.corr()

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values,  # Rounded values for display
                    texttemplate="%{text}",
                    textfont={"size":9}  # Adjust text size if necessary
                    ))

# Update the layout
fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  # or any width you desire
    height=1000,  # or any height you desire
)

# Show the figure
pyo.iplot(fig)

In [27]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train, dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test, dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(1)[0])

tensor(0.7379, device='cuda:0')
tensor([[0.7245, 0.7886, 0.7977, 0.7520, 0.8162, 0.7932, 0.7932, 0.8132, 0.8351,
         0.8952, 0.8677, 0.5236, 0.4322, 0.4487, 0.5273, 0.3933],
        [0.6857, 0.7784, 0.7753, 0.7519, 0.8155, 0.7928, 0.7928, 0.8109, 0.8352,
         0.9073, 0.8879, 0.5230, 0.4490, 0.3797, 0.4563, 0.3599],
        [0.6617, 0.7874, 0.7901, 0.7523, 0.8138, 0.7921, 0.7921, 0.8104, 0.8361,
         0.9139, 0.9012, 0.5342, 0.4649, 0.4445, 0.4976, 0.3821],
        [0.6236, 0.7974, 0.7962, 0.7521, 0.8153, 0.7928, 0.7928, 0.8098, 0.8373,
         0.9235, 0.9113, 0.5474, 0.4805, 0.4671, 0.5145, 0.3912],
        [0.5981, 0.7914, 0.7760, 0.7537, 0.8163, 0.7941, 0.7941, 0.8092, 0.8374,
         0.9237, 0.9172, 0.5399, 0.4914, 0.4592, 0.4471, 0.3605],
        [0.5869, 0.7794, 0.7495, 0.7546, 0.8078, 0.7900, 0.7900, 0.8083, 0.8361,
         0.8756, 0.9035, 0.5112, 0.4936, 0.4080, 0.3677, 0.3216],
        [0.5854, 0.7650, 0.7287, 0.7521, 0.8019, 0.7857, 0.7857, 0.8063, 0.8339,
         0.7960, 0.8581, 0.4709, 0.4865, 0.3590, 0.3118, 0.2921],
        [0.6453, 0.7842, 0.7755, 0.7524, 0.8000, 0.7849, 0.7849, 0.8050, 0.8341,
         0.7774, 0.8059, 0.4782, 0.4824, 0.4654, 0.4544, 0.3639],
        [0.6088, 0.7965, 0.7774, 0.7533, 0.8016, 0.7861, 0.7861, 0.8043, 0.8344,
         0.7888, 0.7750, 0.4855, 0.4807, 0.5578, 0.4597, 0.3667],
        [0.5723, 0.7852, 0.7740, 0.7605, 0.8012, 0.7895, 0.7895, 0.8036, 0.8345,
         0.8188, 0.7831, 0.4882, 0.4800, 0.6035, 0.4490, 0.3617],
        [0.5827, 0.7733, 0.7659, 0.7687, 0.7993, 0.7924, 0.7924, 0.8030, 0.8343,
         0.7983, 0.7906, 0.4834, 0.4783, 0.5378, 0.4231, 0.3496],
        [0.5960, 0.7621, 0.7405, 0.7742, 0.7969, 0.7939, 0.7939, 0.8019, 0.8327,
         0.7377, 0.7723, 0.4583, 0.4714, 0.4486, 0.3463, 0.3124],
        [0.5765, 0.7501, 0.7271, 0.7765, 0.7958, 0.7944, 0.7944, 0.8003, 0.8305,
         0.6628, 0.7167, 0.4275, 0.4590, 0.4211, 0.3088, 0.2931],
        [0.5583, 0.7608, 0.7388, 0.7927, 0.7862, 0.7972, 0.7972, 0.7992, 0.8291,
         0.6220, 0.6538, 0.4137, 0.4460, 0.4535, 0.3519, 0.3121],
        [0.5622, 0.7477, 0.7354, 0.7881, 0.7872, 0.7955, 0.7955, 0.7992, 0.8275,
         0.6178, 0.6111, 0.4007, 0.4327, 0.5122, 0.3416, 0.3072],
        [0.5462, 0.7599, 0.7513, 0.7864, 0.7852, 0.7936, 0.7936, 0.8002, 0.8268,
         0.6636, 0.6114, 0.4045, 0.4229, 0.5364, 0.4019, 0.3333],
        [0.5764, 0.7761, 0.7580, 0.7854, 0.7842, 0.7926, 0.7926, 0.8007, 0.8264,
         0.7016, 0.6398, 0.4138, 0.4171, 0.5657, 0.4266, 0.3443],
        [0.5921, 0.7619, 0.7426, 0.7831, 0.7816, 0.7901, 0.7901, 0.8003, 0.8253,
         0.7177, 0.6754, 0.4089, 0.4114, 0.5461, 0.3718, 0.3205],
        [0.6206, 0.7448, 0.6968, 0.7701, 0.7853, 0.7857, 0.7857, 0.7988, 0.8220,
         0.6670, 0.6766, 0.3676, 0.3977, 0.4085, 0.2382, 0.2535],
        [0.6081, 0.7171, 0.6833, 0.7563, 0.7869, 0.7798, 0.7798, 0.7972, 0.8181,
         0.6070, 0.6429, 0.3250, 0.3771, 0.4402, 0.2052, 0.2347],
        [0.5959, 0.7034, 0.6687, 0.7415, 0.7876, 0.7730, 0.7730, 0.7961, 0.8136,
         0.5756, 0.5922, 0.2812, 0.3510, 0.3655, 0.1712, 0.2147],
        [0.5762, 0.6900, 0.6682, 0.7281, 0.7892, 0.7673, 0.7673, 0.7949, 0.8093,
         0.5907, 0.5650, 0.2486, 0.3227, 0.3484, 0.1700, 0.2140],
        [0.5879, 0.7049, 0.6897, 0.7227, 0.7841, 0.7620, 0.7620, 0.7944, 0.8063,
         0.6254, 0.5716, 0.2435, 0.2990, 0.3853, 0.2674, 0.2523],
        [0.5853, 0.6914, 0.6677, 0.7149, 0.7784, 0.7552, 0.7552, 0.7935, 0.8023,
         0.6347, 0.5927, 0.2238, 0.2756, 0.3520, 0.2091, 0.2214],
        [0.5572, 0.6804, 0.6652, 0.7066, 0.7750, 0.7494, 0.7494, 0.7919, 0.7984,
         0.6337, 0.6080, 0.2090, 0.2536, 0.3005, 0.2026, 0.2178],
        [0.5297, 0.6685, 0.6527, 0.6956, 0.7754, 0.7442, 0.7442, 0.7907, 0.7940,
         0.6029, 0.6000, 0.1900, 0.2318, 0.2520, 0.1704, 0.2003],
        [0.5433, 0.6538, 0.6255, 0.6795, 0.7799, 0.7388, 0.7388, 0.7882, 0.7885,
         0.5879, 0.5833, 0.1556, 0.2067, 0.1687, 0.1075, 0.1632],
        [0.5557, 0.6668, 0.6498, 0.6728, 0.7734, 0.7321, 0.7321, 0.7862, 0.7844,
         0.5958, 0.5698, 0.1525, 0.1859, 0.2481, 0.2212, 0.2082],
        [0.5256, 0.6801, 0.6520, 0.6687, 0.7647, 0.7255, 0.7255, 0.7841, 0.7806,
         0.6128, 0.5733, 0.1555, 0.1699, 0.3070, 0.2309, 0.2122],
        [0.5644, 0.6608, 0.6189, 0.6593, 0.7577, 0.7173, 0.7173, 0.7814, 0.7753,
         0.6174, 0.5839, 0.1339, 0.1523, 0.1158, 0.1491, 0.1668],
        [0.5617, 0.6761, 0.6277, 0.6536, 0.7491, 0.7100, 0.7100, 0.7783, 0.7707,
         0.6084, 0.5883, 0.1280, 0.1369, 0.1605, 0.1898, 0.1832],
        [0.5389, 0.6622, 0.6185, 0.6454, 0.7445, 0.7035, 0.7035, 0.7746, 0.7658,
         0.5885, 0.5796, 0.1197, 0.1227, 0.1768, 0.1673, 0.1708],
        [0.5646, 0.6773, 0.6499, 0.6428, 0.7391, 0.6994, 0.6994, 0.7712, 0.7627,
         0.6410, 0.5880, 0.1434, 0.1167, 0.3005, 0.3052, 0.2288],
        [0.5655, 0.6895, 0.6535, 0.6425, 0.7308, 0.6949, 0.6949, 0.7684, 0.7599,
         0.6945, 0.6188, 0.1686, 0.1175, 0.3813, 0.3198, 0.2353],
        [0.5445, 0.7006, 0.6575, 0.6433, 0.7222, 0.6908, 0.6908, 0.7663, 0.7575,
         0.7638, 0.6813, 0.1951, 0.1240, 0.3916, 0.3365, 0.2425],
        [0.5309, 0.7126, 0.6763, 0.6492, 0.7093, 0.6868, 0.6868, 0.7630, 0.7561,
         0.8140, 0.7430, 0.2347, 0.1381, 0.4185, 0.4132, 0.2767],
        [0.5074, 0.7002, 0.6758, 0.6595, 0.6915, 0.6825, 0.6825, 0.7600, 0.7548,
         0.8756, 0.8075, 0.2680, 0.1568, 0.4105, 0.4111, 0.2759],
        [0.4925, 0.7102, 0.6850, 0.6695, 0.6765, 0.6794, 0.6794, 0.7577, 0.7540,
         0.9451, 0.8721, 0.3040, 0.1797, 0.4830, 0.4490, 0.2927],
        [0.4790, 0.7212, 0.6930, 0.6699, 0.6757, 0.6792, 0.6792, 0.7563, 0.7536,
         0.9697, 0.9276, 0.3408, 0.2063, 0.3519, 0.4816, 0.3075],
        [0.4712, 0.7092, 0.6880, 0.6696, 0.6765, 0.6795, 0.6795, 0.7558, 0.7530,
         0.9536, 0.9554, 0.3670, 0.2334, 0.3087, 0.4586, 0.2993],
        [0.4465, 0.7192, 0.6884, 0.6689, 0.6791, 0.6805, 0.6805, 0.7554, 0.7524,
         0.9231, 0.9476, 0.3890, 0.2600, 0.3267, 0.4604, 0.3001],
        [0.4445, 0.7331, 0.7062, 0.6665, 0.6851, 0.6825, 0.6825, 0.7552, 0.7528,
         0.9317, 0.9341, 0.4219, 0.2886, 0.3368, 0.5376, 0.3335],
        [0.4810, 0.7472, 0.7283, 0.6614, 0.6937, 0.6846, 0.6846, 0.7554, 0.7542,
         0.9518, 0.9335, 0.4667, 0.3215, 0.3912, 0.6197, 0.3738],
        [0.4616, 0.7587, 0.7379, 0.6561, 0.7057, 0.6883, 0.6883, 0.7566, 0.7561,
         0.9821, 0.9545, 0.5099, 0.3575, 0.3851, 0.6520, 0.3910]],
       device='cuda:0')

# Gated Recurrent Unit (GRU)

<img src="/home/arda/Turkcell/RNN/LSTM/Screenshot from 2024-01-30 09-47-19.png" alt="Alt text">

- Update Gate: The update gate decides how much of the past information needs to be passed along to the future. It's similar to the combination of the forget and input gates in an LSTM.

- Reset Gate: The reset gate decides how much of the past information to forget. It's useful for the model to forget irrelevant parts of the past and to capture short-term dependencies.

- Current Memory Content: The current memory content combines the new input with the past memory (modulated by the reset gate) to create a candidate for the new hidden state.

In [28]:
class StackedGRUModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob):
        super(StackedGRUModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # GRU Layer
        self.gru = nn.GRU(input_size=input_dim, hidden_size=hidden_size, num_layers=layer_size, dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
        
        # Dropout layer
        self.dropout = nn.Dropout(dropout_prob)

        # Fully connected layer
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # Forward propagate GRU
        out, _ = self.gru(x)  # Output shape: (batch, seq_len, hidden_size)

        # Apply dropout
        out = self.dropout(out[:, -1, :])  # Get the last time step output

        # Fully connected layer
        out = self.fc(out)

        return out

In [29]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model = None
        self.optimizer = None
        self.criterion = nn.MSELoss()

    
    def train_validate(self, config, trial):
 
        batch_size = config["batch_size"]
        epochs = config["epochs"]
        hidden_size = config["hidden_size"]
        num_layers = config["num_layers"]
        learning_rate = config["learning_rate"]
        dropout_prob = config["dropout_prob"]
        weight_decay = config["weight_decay"]
        lr_step_size = config["lr_step_size"]
        gamma = config["gamma"]
        
        self.model = StackedGRUModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.view(-1,1)


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    #loss = loss.mean()
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.view(-1,1)

                        preds = self.model(data)
                        loss = self.criterion(preds, target)
                        #loss = loss.mean()

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
        
        batch_size = config["batch_size"]
        epochs = config["epochs"]
        hidden_size = config["hidden_size"]
        num_layers = config["num_layers"]
        learning_rate = config["learning_rate"]
        dropout_prob = config["dropout_prob"]
        weight_decay = config["weight_decay"]
        lr_step_size = config["lr_step_size"]
        gamma = config["gamma"]
        
        self.model = StackedGRUModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)  

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                #loss = loss.mean()
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                all_preds.extend(preds.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [30]:
def objective(trial):

    config = {
        "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
        "epochs": trial.suggest_int("epochs", 50, 150),
        "hidden_size": trial.suggest_int("hidden_size", 10, 100),
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
        "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
        "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
        "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
        "gamma": trial.suggest_float("gamma", 0.1, 0.9),
        "num_layers": trial.suggest_int("num_layers", 1, 5)
    }

    trainer = ModelActioner(train_data, test_data, device)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [31]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=20, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    # Optionally, you can include additional information in the progress bar
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=20, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-30 14:38:36,450] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/20 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.004025713680312038, val_loss: 0.002922618756731036
epochs 2/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.004253323376178742, val_loss: 0.0028112999005883775
epochs 3/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003960169292986393, val_loss: 0.002723682529499961
epochs 4/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0035525753162801267, val_loss: 0.002650068928401365
epochs 5/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0039710090961307285, val_loss: 0.0026039393272536695
epochs 6/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003495074436068535, val_loss: 0.002570155461961847
epochs 7/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003892160626128316, val_loss: 0.002518478364291941
epochs 8/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.004398588091135025, val_loss: 0.0024847791929946098
epochs 9/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.004160105157643557, val_loss: 0.0024459935126027892
epochs 10/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0035394265782088042, val_loss: 0.002419925708429661
epochs 11/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0036163375712931155, val_loss: 0.002410869321369482
epochs 12/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003294018050655723, val_loss: 0.0024174981764098877
epochs 13/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003350276546552777, val_loss: 0.00241471856380394
epochs 14/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.004162956541404128, val_loss: 0.0023854891865060877
epochs 15/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0029874252388253806, val_loss: 0.0023753392253263246
epochs 16/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0037782314233481885, val_loss: 0.0023704046619410515
epochs 17/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003574476344510913, val_loss: 0.0023521983924582996
epochs 18/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0033392850309610367, val_loss: 0.002349548930026315
epochs 19/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.00365296364761889, val_loss: 0.0023205660908142962
epochs 20/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0032279420644044875, val_loss: 0.0023050881154150285
epochs 21/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002901558205485344, val_loss: 0.0023089683267889082
epochs 22/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0033773656468838453, val_loss: 0.002309874636700091
epochs 23/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003582263458520174, val_loss: 0.002299143490812707
epochs 24/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003338137036189437, val_loss: 0.0022902215243361538
epochs 25/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0034979306627064945, val_loss: 0.002299140357146306
epochs 26/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003140751365572214, val_loss: 0.00230860729608192
epochs 27/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002859823266044259, val_loss: 0.0023338040940601517
epochs 28/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003212386881932616, val_loss: 0.0023473793571129956
epochs 29/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0027695616241544484, val_loss: 0.002343517257252994
epochs 30/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0030452159699052572, val_loss: 0.00230910054164096
epochs 31/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002947928849607706, val_loss: 0.0023021321474554794
epochs 32/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0028770900797098877, val_loss: 0.0023105607602730512
epochs 33/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.003080332465469837, val_loss: 0.0023113170363964937
epochs 34/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0026506666559726, val_loss: 0.00231175882699924
epochs 35/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.00250276408623904, val_loss: 0.0023107461726154994
epochs 36/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002746260608546436, val_loss: 0.002295690564014924
epochs 37/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.00281075828243047, val_loss: 0.0022399251188506327
epochs 38/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002922577131539583, val_loss: 0.002204384613491437
epochs 39/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0027964341919869185, val_loss: 0.0021743948704430033
epochs 40/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0025657203514128923, val_loss: 0.0021672340894669847
epochs 41/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0032506147865206, val_loss: 0.002175549285427209
epochs 42/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.00278399963863194, val_loss: 0.0021844260304027963
epochs 43/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.00293760453350842, val_loss: 0.0021696905075774464
epochs 44/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0029790057335048912, val_loss: 0.0021514401785911077
epochs 45/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0027434158604592086, val_loss: 0.002146489953341347
epochs 46/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002564636478200555, val_loss: 0.0021286394065812664
epochs 47/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002856927691027522, val_loss: 0.0021065352687848703
epochs 48/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0027080052066594364, val_loss: 0.0020992107779925894
epochs 49/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002447226527146995, val_loss: 0.002087840245280257
epochs 50/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0020555027993395926, val_loss: 0.0020778388617727806
epochs 51/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0020781339379027488, val_loss: 0.0020628245008454003
epochs 52/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0025854203617200256, val_loss: 0.0020481452756073502
epochs 53/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0028530767653137446, val_loss: 0.002024111166108577
epochs 54/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0021335929166525604, val_loss: 0.0020111487952317233
epochs 55/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0020206338493153455, val_loss: 0.0020085648385926133
epochs 56/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002770051802508533, val_loss: 0.0020067854852184024
epochs 57/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002374037471599877, val_loss: 0.0019893183960534985
epochs 58/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002299790596589446, val_loss: 0.0019824481141142466
epochs 59/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002808712632395327, val_loss: 0.001964727904778171
epochs 60/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0024610809748992326, val_loss: 0.0019360494660706352
epochs 61/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0023586466209962963, val_loss: 0.0019056277411802617
epochs 62/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0021802995586767794, val_loss: 0.0018883991294180748
epochs 63/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002459638472646475, val_loss: 0.0018847633822126285
epochs 64/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0023976653115823864, val_loss: 0.001872821289075233
epochs 65/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0022947519551962613, val_loss: 0.0018759373847700696
epochs 66/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016195034608244897, val_loss: 0.0018766713799864409
epochs 67/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019778267247602343, val_loss: 0.0018967827292351378
epochs 68/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0020669235847890375, val_loss: 0.0019260957654166435
epochs 69/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0022239995421841742, val_loss: 0.0019496279428639109
epochs 70/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002133685466833413, val_loss: 0.0019180470022432032
epochs 71/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019853113451972606, val_loss: 0.0018923003352789218
epochs 72/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002203298453241587, val_loss: 0.0018867916792813472
epochs 73/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019439362920820713, val_loss: 0.001892047364476615
epochs 74/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002214369177818298, val_loss: 0.001878804820417254
epochs 75/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002483654813840985, val_loss: 0.0018779850865482653
epochs 76/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002258744393475354, val_loss: 0.0018958590749808878
epochs 77/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002177839516662061, val_loss: 0.001888413085705704
epochs 78/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002257893793284893, val_loss: 0.001867227578750028
epochs 79/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0020432751160115005, val_loss: 0.0018477407296400065
epochs 80/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0017304084612987936, val_loss: 0.0018311245912050326
epochs 81/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0018921430921182037, val_loss: 0.00180975439010937
epochs 82/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0020042025949805974, val_loss: 0.0017961364919467577
epochs 83/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0017679656390100717, val_loss: 0.0017831244074158056
epochs 84/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0020535871386528014, val_loss: 0.0017794398082760236
epochs 85/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0021587411174550653, val_loss: 0.0017691448684436855
epochs 86/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015985310077667237, val_loss: 0.0017619078221888572
epochs 87/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019284536829218268, val_loss: 0.0017609226655352999
epochs 88/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0017507648677565157, val_loss: 0.0017683182017035073
epochs 89/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019800446927547453, val_loss: 0.0017777199936395008
epochs 90/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0018729845760390162, val_loss: 0.0017754283204561385
epochs 91/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001657392759807408, val_loss: 0.0017685842439754023
epochs 92/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001806185324676335, val_loss: 0.0017556950647664804
epochs 93/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0017201444832608103, val_loss: 0.0017416936064523364
epochs 94/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001950670499354601, val_loss: 0.0017244537045597716
epochs 95/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016377015039324761, val_loss: 0.0016996506644688823
epochs 96/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001853752345778048, val_loss: 0.0016850702316443579
epochs 97/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0017226930474862456, val_loss: 0.0016839226822383583
epochs 98/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001697118952870369, val_loss: 0.0016722373255385608
epochs 99/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019113033777102828, val_loss: 0.0016633268641603608
epochs 100/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019072226947173475, val_loss: 0.0016536786887430088
epochs 101/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0020025019766762853, val_loss: 0.0016546067332099906
epochs 102/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001820279797539115, val_loss: 0.0016520741953398718
epochs 103/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0017116573406383395, val_loss: 0.0016415317107987388
epochs 104/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016901926370337605, val_loss: 0.0016425754306727044
epochs 105/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015299268066883086, val_loss: 0.0016357370017209736
epochs 106/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016273484099656344, val_loss: 0.0016372849753313753
epochs 107/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0017409559106454254, val_loss: 0.0016187038922450805
epochs 108/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002355205127969384, val_loss: 0.0015849410847295076
epochs 109/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001585315086413175, val_loss: 0.0015653793984302196
epochs 110/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.00176105669233948, val_loss: 0.0015609189287436604
epochs 111/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016275948146358132, val_loss: 0.0015595462476580882
epochs 112/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016916226595640182, val_loss: 0.0015620159656031145
epochs 113/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0018271918641403317, val_loss: 0.0015669755552028103
epochs 114/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015244555659592151, val_loss: 0.0015669870321212641
epochs 115/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.00160183091647923, val_loss: 0.001586920553270146
epochs 116/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0014525710721500218, val_loss: 0.001611259009993374
Starting fold 2:
epochs 1/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0024362130208545434, val_loss: 0.03646898445077043
epochs 2/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002142632636303048, val_loss: 0.03497345407527906
epochs 3/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.002087214461584283, val_loss: 0.03385673555984068
epochs 4/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019250300830834617, val_loss: 0.03296776773240516
epochs 5/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016188995137388048, val_loss: 0.03258944501873677
epochs 6/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001722633998993401, val_loss: 0.03238471630940992
epochs 7/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0021516536086021204, val_loss: 0.03221652950480502
epochs 8/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019935493370994805, val_loss: 0.031993262134689504
epochs 9/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0018527752828555756, val_loss: 0.031635503289560794
epochs 10/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001959634828688405, val_loss: 0.03143460021684409
epochs 11/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019680685922749204, val_loss: 0.031136386401990734
epochs 12/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0018356116408713183, val_loss: 0.030915843983175893
epochs 13/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001795442382950031, val_loss: 0.030926768387120867
epochs 14/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001711384674637409, val_loss: 0.030618100688255653
epochs 15/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0019171583173811279, val_loss: 0.03042235694549702
epochs 16/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0018609364082088256, val_loss: 0.03039329823244501
epochs 17/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0018144520128632363, val_loss: 0.030141367986009866
epochs 18/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016603945228602923, val_loss: 0.029994653833527413
epochs 19/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0018025538057830962, val_loss: 0.030183046642276976
epochs 20/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015861037313830019, val_loss: 0.030358939416824826
epochs 21/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015952062361817168, val_loss: 0.030386456736811885
epochs 22/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016841745703778473, val_loss: 0.030025430201064972
epochs 23/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015679242207341899, val_loss: 0.029774973336508664
epochs 24/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016641884048206432, val_loss: 0.029436289781221637
epochs 25/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0014869752177221597, val_loss: 0.028974622882232463
epochs 26/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016331876398341873, val_loss: 0.028902635953965642
epochs 27/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0017393569165280477, val_loss: 0.028695243859180698
epochs 28/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001592491227533855, val_loss: 0.028477034772987717
epochs 29/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0016707928668791157, val_loss: 0.028259434416968987
epochs 30/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0013411583948393885, val_loss: 0.028117602513659568
epochs 31/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015091263909644808, val_loss: 0.02795777447206318
epochs 32/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015211720750630295, val_loss: 0.027764695474789255
epochs 33/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015373053170475214, val_loss: 0.0281563527468178
epochs 34/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.001404047219665097, val_loss: 0.02801892300328565
epochs 35/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015642454142443896, val_loss: 0.027919406199423725
epochs 36/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015177320600499578, val_loss: 0.02759932899088771
epochs 37/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0014291233361617595, val_loss: 0.02757311272360976
epochs 38/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0015650205292657882, val_loss: 0.02775557021851893
epochs 39/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0013098975334508163, val_loss: 0.02756066747482807
epochs 40/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0013388581543246722, val_loss: 0.027187108569753864
epochs 41/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0014097810705071979, val_loss: 0.026880470252344534
epochs 42/116
Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.0014884328705536344, val_loss: 0.026593867566180294
epochs 43/116
Current Learning Rate: 5.8373498480289535e-05

[I 2024-01-30 14:40:37,563] Trial 0 finished with value: 0.011147735436951134 and parameters: {'batch_size': 38, 'epochs': 116, 'hidden_size': 22, 'learning_rate': 5.8373498480289535e-05, 'dropout_prob': 0.17486793373326623, 'weight_decay': 2.16848429675218e-05, 'lr_step_size': 36, 'gamma': 0.8737917389841742, 'num_layers': 2}. Best is trial 0 with value: 0.011147735436951134.

Current Learning Rate: 5.8373498480289535e-05
train_loss: 0.00284528904655396, val_loss: 0.001958468556280923
Mean validation loss: 0.011147735436951134
Starting fold 1:
epochs 1/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.038362462818622586, val_loss: 0.06018538741522996
epochs 2/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.03710276162938068, val_loss: 0.05826966078193099
epochs 3/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.03590819596459991, val_loss: 0.05639731852465837
epochs 4/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.03421320468187332, val_loss: 0.054569114492368447
epochs 5/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.032926277110451145, val_loss: 0.0527851792081954
epochs 6/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0314315304356186, val_loss: 0.05104812100608513
epochs 7/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.030856122880389816, val_loss: 0.04935749888262421
epochs 8/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.02932937853038311, val_loss: 0.047712068236063394
epochs 9/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.02817504468717073, val_loss: 0.04611540723730017
epochs 10/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.027752195984909408, val_loss: 0.04456163974350722
epochs 11/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.02632601922868114, val_loss: 0.04305213256172402
epochs 12/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.025258076700725055, val_loss: 0.04158882307943213
epochs 13/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.024122902770575723, val_loss: 0.040168426576114837
epochs 14/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.023191890875367743, val_loss: 0.03879374362252377
epochs 15/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.02218537670805266, val_loss: 0.03746023054712664
epochs 16/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.021322661226517277, val_loss: 0.03616881932294558
epochs 17/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.020722348419459243, val_loss: 0.034917386849878954
epochs 18/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.01937308715362298, val_loss: 0.03370385794412522
epochs 19/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.018679047797463443, val_loss: 0.032530441348041804
epochs 20/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.017884094454348087, val_loss: 0.03139677968999696
epochs 21/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.017168305333899823, val_loss: 0.030299469592079284
epochs 22/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.016230288589079128, val_loss: 0.029237733296458682
epochs 23/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.01550210979031889, val_loss: 0.028212119899098834
epochs 24/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.015151074332626243, val_loss: 0.027217184425031068
epochs 25/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.014363179228415615, val_loss: 0.026253249870721626
epochs 26/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.013585638362718255, val_loss: 0.02532336401639792
epochs 27/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.013162804370451914, val_loss: 0.024423737019773514
epochs 28/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.012523359854362513, val_loss: 0.023554235716503134
epochs 29/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.012355940779180903, val_loss: 0.02271180532912098
epochs 30/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.011785798696310896, val_loss: 0.021894265035236324
epochs 31/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.011113556435233669, val_loss: 0.02110408234690863
epochs 32/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.010512445063183181, val_loss: 0.02034285141243821
epochs 33/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.01002471477381493, val_loss: 0.01960648356803826
epochs 34/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.009738468873853746, val_loss: 0.018898438189237837
epochs 35/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.009421482790065439, val_loss: 0.018212827858786102
epochs 36/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.008842788401402926, val_loss: 0.01754790596742794
epochs 37/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.00828874437628608, val_loss: 0.01690762226898519
epochs 38/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.007916770926921776, val_loss: 0.016291786418863075
epochs 39/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.007566869886297929, val_loss: 0.015699255610348056
epochs 40/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.007112554995048987, val_loss: 0.015129092095232515
epochs 41/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.006980833805803405, val_loss: 0.014578466150889952
epochs 42/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0064579027239233255, val_loss: 0.014048969205567446
epochs 43/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0060360237147266925, val_loss: 0.013540042022233287
epochs 44/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.005924379046222097, val_loss: 0.01305325631367624
epochs 45/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.005746611484669541, val_loss: 0.012584112150959236
epochs 46/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0053023739962985645, val_loss: 0.012134728958169935
epochs 47/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0052347156709354175, val_loss: 0.011700887893321653
epochs 48/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.005036052147318658, val_loss: 0.011280289585036891
epochs 49/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.004536020150408149, val_loss: 0.010876204670658187
epochs 50/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.004435567752654223, val_loss: 0.0104877815074312
epochs 51/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.004324822355748007, val_loss: 0.010114269124137031
epochs 52/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0039734652278160575, val_loss: 0.009756457504062425
epochs 53/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.003675438267619986, val_loss: 0.009416121417883212
epochs 54/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0037376752037456946, val_loss: 0.009087470653294414
epochs 55/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0034647762591607477, val_loss: 0.008773398437788562
epochs 56/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.003247415078313727, val_loss: 0.008473098494861492
epochs 57/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0030677842368420803, val_loss: 0.008186688585078749
epochs 58/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0028154544066637754, val_loss: 0.007913030627326517
epochs 59/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0027531630751725877, val_loss: 0.007653249417820936
epochs 60/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.002737127215062317, val_loss: 0.007403073785580182
epochs 61/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.002711833079688643, val_loss: 0.007160855506463026
epochs 62/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.002491581799021285, val_loss: 0.006927701371115824
epochs 63/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0023266076018396567, val_loss: 0.006703631558194362
epochs 64/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0021743681661686616, val_loss: 0.006489077713537626
epochs 65/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.002173511280776247, val_loss: 0.006284225330486027
epochs 66/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0019212640705518424, val_loss: 0.006088595112992657
epochs 67/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0019936751537515144, val_loss: 0.005902902989416684
epochs 68/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0018335094252650284, val_loss: 0.005725033286830814
epochs 69/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0017267072787753453, val_loss: 0.005555913336427202
epochs 70/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0016695646103471518, val_loss: 0.005393489178950115
epochs 71/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.001671677482878103, val_loss: 0.0052381873736897155
epochs 72/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.001564323574022733, val_loss: 0.005091360453565522
epochs 73/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.001598102547914574, val_loss: 0.004948923064927969
epochs 74/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0013953108432408618, val_loss: 0.004814295313769468
epochs 75/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.001517355541919211, val_loss: 0.004684319645757713
epochs 76/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.001372788895816101, val_loss: 0.004558619563886649
epochs 77/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0012678752864686478, val_loss: 0.004438872396127966
Starting fold 2:
epochs 1/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0026831602113134667, val_loss: 0.05385932586495838
epochs 2/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0023149432172743225, val_loss: 0.05110309479965104
epochs 3/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.002001881162331275, val_loss: 0.04856512001740239
epochs 4/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0016730176171258406, val_loss: 0.04625818626117454
epochs 5/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.001518683140209107, val_loss: 0.04420007810627342
epochs 6/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.00146412655713017, val_loss: 0.04237110262352323
epochs 7/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0012523201515401731, val_loss: 0.040780782896690265
epochs 8/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0012426486932721706, val_loss: 0.03942433937832161
epochs 9/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0011258227680011168, val_loss: 0.03826021170490002
epochs 10/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0010868626367792212, val_loss: 0.03728380755930351
epochs 11/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0011356427562472197, val_loss: 0.03646257265456139
epochs 12/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0011072662397285328, val_loss: 0.03576030651176417
epochs 13/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0010727203585020706, val_loss: 0.03515008054476566
epochs 14/77
Current Learning Rate: 2.4100774717026936e-05
train_loss: 0.0010493941581132269, val_loss: 0.03462012023443267
epochs 15/77

[I 2024-01-30 14:40:47,468] Trial 1 pruned.

Starting fold 1:
epochs 1/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008402749715299394, val_loss: 0.0013586440646870643
epochs 2/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000713061851963989, val_loss: 0.0013577550307480452
epochs 3/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000950031702737569, val_loss: 0.0013591260829430428
epochs 4/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009138557038233174, val_loss: 0.0013536945305377857
epochs 5/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009172212372313401, val_loss: 0.0013471978182828044
epochs 6/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007075642048699879, val_loss: 0.0013397457286753697
epochs 7/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009252685168145323, val_loss: 0.0013327447187202297
epochs 8/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007584789921039421, val_loss: 0.001326864190222868
epochs 9/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008807454665657133, val_loss: 0.0013225315916031678
epochs 10/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006842300199327598, val_loss: 0.0013189009331793786
epochs 11/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008785138608226063, val_loss: 0.0013167647155655903
epochs 12/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008478657186251917, val_loss: 0.0013124300263207356
epochs 13/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007353265509376989, val_loss: 0.0013076280306522099
epochs 14/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007525459376139272, val_loss: 0.00130276468426307
epochs 15/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007745297365258203, val_loss: 0.0012988583736057596
epochs 16/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000711136118441477, val_loss: 0.0012949405446070832
epochs 17/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009622873487196078, val_loss: 0.0012914792944217672
epochs 18/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006330915311608757, val_loss: 0.0012869635891297427
epochs 19/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007240503141043806, val_loss: 0.0012826333883422963
epochs 20/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007551151845530655, val_loss: 0.0012792723592760032
epochs 21/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0005102485770629229, val_loss: 0.0012761676705118378
epochs 22/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008449696641611425, val_loss: 0.001273832405026061
epochs 23/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006866002787750116, val_loss: 0.0012716908080542765
epochs 24/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007435897352958196, val_loss: 0.0012693198961507598
epochs 25/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006730499213230551, val_loss: 0.0012672804148187713
epochs 26/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007068778904412235, val_loss: 0.0012622612877132952
epochs 27/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008638959145173431, val_loss: 0.0012571493755944723
epochs 28/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007833584956212067, val_loss: 0.0012530665870086985
epochs 29/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.001019677718317038, val_loss: 0.0012498404542735664
epochs 30/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0004919987541047464, val_loss: 0.0012479341803266414
epochs 31/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007379555390032597, val_loss: 0.0012454598638994088
epochs 32/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007442061774016015, val_loss: 0.0012412753692833047
epochs 33/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008211362711766637, val_loss: 0.0012380314357061353
epochs 34/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007341375651058594, val_loss: 0.001236485158356286
epochs 35/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006532567594580254, val_loss: 0.0012340989267507756
epochs 36/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008841639225322165, val_loss: 0.001230106131135481
epochs 37/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008374011419762514, val_loss: 0.0012253975252702182
epochs 38/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007178202825966046, val_loss: 0.0012221667984415525
epochs 39/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007643375835246651, val_loss: 0.0012181812958765982
epochs 40/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006632291808369031, val_loss: 0.0012139014561109924
epochs 41/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007276020748050589, val_loss: 0.0012108564963373332
epochs 42/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006375828727246507, val_loss: 0.001208806008752805
epochs 43/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0005272300054601051, val_loss: 0.0012062244087540194
epochs 44/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006433581496821716, val_loss: 0.001203142719407364
epochs 45/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008088783253793066, val_loss: 0.0011997014712529976
epochs 46/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008100384106479683, val_loss: 0.0011970460789540547
epochs 47/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007156201361029065, val_loss: 0.0011954722830855716
epochs 48/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007525061848450845, val_loss: 0.0011951168447027042
epochs 49/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008606193737298447, val_loss: 0.001192994243908851
epochs 50/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0004623487184289843, val_loss: 0.0011885560318770961
epochs 51/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006497514651671641, val_loss: 0.0011846133718444478
epochs 52/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007633603303570692, val_loss: 0.001181148907687717
epochs 53/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006496365238777607, val_loss: 0.001178473559169409
epochs 54/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006383588159224018, val_loss: 0.0011759057971180748
epochs 55/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0005311162747124112, val_loss: 0.0011731807710559762
epochs 56/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007531980424813043, val_loss: 0.0011709438308595468
epochs 57/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000722128135997704, val_loss: 0.0011688003506851456
epochs 58/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008052253032617859, val_loss: 0.0011657518795112434
epochs 59/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006351614052331761, val_loss: 0.0011631371500370926
epochs 60/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006278391811065376, val_loss: 0.0011617917808945531
epochs 61/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008489377940637305, val_loss: 0.0011606462656384181
epochs 62/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008037299836838715, val_loss: 0.0011590916208603183
epochs 63/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006496820593479482, val_loss: 0.0011563105802033244
epochs 64/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006654522841257093, val_loss: 0.0011529433840892535
epochs 65/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007292999559707057, val_loss: 0.0011498366549386884
epochs 66/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008104646480397174, val_loss: 0.0011469023794960724
epochs 67/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006999259906526851, val_loss: 0.0011449332628337538
epochs 68/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007268958498331669, val_loss: 0.0011443104594945908
epochs 69/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006270240955544929, val_loss: 0.0011430378680218445
epochs 70/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007289932599585308, val_loss: 0.0011403201198422167
epochs 71/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0005464892417780663, val_loss: 0.0011375622862947504
epochs 72/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000512355526351664, val_loss: 0.001135309310734676
epochs 73/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009699654385545536, val_loss: 0.001133579232224273
epochs 74/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006846980658960284, val_loss: 0.0011314319735565394
epochs 75/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006582589654595052, val_loss: 0.0011314180764774963
epochs 76/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006017925821269225, val_loss: 0.0011296408077998816
epochs 77/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006317075418528954, val_loss: 0.0011263693299879956
epochs 78/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.00048755611014233806, val_loss: 0.001124131914429002
epochs 79/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006476818511912011, val_loss: 0.0011223561095662672
epochs 80/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006337774606531878, val_loss: 0.0011203580143431537
epochs 81/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007376812537825716, val_loss: 0.0011186421053174874
epochs 82/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007933627403537302, val_loss: 0.0011171267118284026
epochs 83/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006745637377638272, val_loss: 0.0011148010381336062
epochs 84/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0007200630024798508, val_loss: 0.0011124276668024273
epochs 85/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008025835597532262, val_loss: 0.0011101613745460454
epochs 86/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0005635647592594308, val_loss: 0.0011079626416734534
epochs 87/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0005982740302753977, val_loss: 0.001105378232077109
epochs 88/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006288938340730966, val_loss: 0.0011042064447239258
epochs 89/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000657722159858646, val_loss: 0.0011040035959532751
epochs 90/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0005601743340345198, val_loss: 0.001103790198352986
epochs 91/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009686042266701789, val_loss: 0.0010995301737147629
epochs 92/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0005645761663081909, val_loss: 0.0010969767537308
epochs 93/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006714004252755426, val_loss: 0.0010971956605014082
epochs 94/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0006181450468782139, val_loss: 0.0010974347196727567
Starting fold 2:
epochs 1/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0011010978782966016, val_loss: 0.029839121270924807
epochs 2/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000975925449326777, val_loss: 0.028404880167236402
epochs 3/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.00122299416785959, val_loss: 0.02719399220157395
epochs 4/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010878651675191957, val_loss: 0.02628377908298736
epochs 5/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0012363442704345696, val_loss: 0.025942322430964657
epochs 6/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0011676889940995556, val_loss: 0.0258357204329321
epochs 7/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0011009511312544788, val_loss: 0.02577110602416926
epochs 8/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0012470451210494003, val_loss: 0.025819081130619877
epochs 9/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009473621097146373, val_loss: 0.025616965061989884
epochs 10/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0011238261343454229, val_loss: 0.025347562179107358
epochs 11/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009432231475529077, val_loss: 0.02488930414741238
epochs 12/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010923018783765863, val_loss: 0.024584567105328595
epochs 13/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.001048441517405153, val_loss: 0.024580105560186204
epochs 14/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010438071002727275, val_loss: 0.024657528211791364
epochs 15/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.001052299630981784, val_loss: 0.024669922112176817
epochs 16/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009696519027352283, val_loss: 0.024566069821871463
epochs 17/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010587162068506856, val_loss: 0.024234921102308564
epochs 18/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009952681133736142, val_loss: 0.023893372695301732
epochs 19/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0012081114186396661, val_loss: 0.023640905563576668
epochs 20/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009520079623103033, val_loss: 0.023459898428646504
epochs 21/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009457152554922612, val_loss: 0.023238686319913656
epochs 22/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0011535336765384494, val_loss: 0.023017204760834967
epochs 23/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010481427234289111, val_loss: 0.022969836921051697
epochs 24/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0011341022691532163, val_loss: 0.023142045708718122
epochs 25/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009186420951985895, val_loss: 0.023133893117860512
epochs 26/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0011530597641232294, val_loss: 0.023192334843789617
epochs 27/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009997284177618254, val_loss: 0.02313170526620178
epochs 28/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010013818263357609, val_loss: 0.023044046741373166
epochs 29/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.001073482658315971, val_loss: 0.022796496808055847
epochs 30/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010860687580038265, val_loss: 0.022612809481976366
epochs 31/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009772243792738515, val_loss: 0.02237228500760264
epochs 32/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010345099529722645, val_loss: 0.022163722467012505
epochs 33/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.00105258356449612, val_loss: 0.021965346178384842
epochs 34/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0011103773849898346, val_loss: 0.021872770267898443
epochs 35/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0011230014240931926, val_loss: 0.02179925410057265
epochs 36/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010750433590569063, val_loss: 0.021980436474439643
epochs 37/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010371661666224129, val_loss: 0.021882895397505275
epochs 38/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000943690338979861, val_loss: 0.021707464773306456
epochs 39/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010691636205419877, val_loss: 0.021600219736457187
epochs 40/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008707283000832812, val_loss: 0.02138344343830511
epochs 41/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.001002802309889769, val_loss: 0.021003555617339555
epochs 42/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000911891788854276, val_loss: 0.020833847298971798
epochs 43/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008576057963736728, val_loss: 0.020737887203703245
epochs 44/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009389540663119258, val_loss: 0.020688761450675507
epochs 45/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.001024505783669223, val_loss: 0.020645825767633384
epochs 46/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009753061536027458, val_loss: 0.02023964166941821
epochs 47/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008843881162534662, val_loss: 0.020172661834361928
epochs 48/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008974455763576036, val_loss: 0.02009669013035597
epochs 49/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009126238845747043, val_loss: 0.020058546141381303
epochs 50/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009050393041830244, val_loss: 0.02004773575669677
epochs 51/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.00099480348231583, val_loss: 0.0198975176348415
epochs 52/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008872994984282638, val_loss: 0.019836559076177537
epochs 53/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000958241799451278, val_loss: 0.019637033542884246
epochs 54/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009134109484463056, val_loss: 0.01950193180027541
epochs 55/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008988476607618033, val_loss: 0.019419937823263424
epochs 56/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008247474327193214, val_loss: 0.01938517390326572
epochs 57/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009130718227811306, val_loss: 0.019256497711120618
epochs 58/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009561321329685435, val_loss: 0.019166387809765716
epochs 59/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008543367524653438, val_loss: 0.01889665306437386
epochs 60/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009004832669296413, val_loss: 0.018745012417504633
epochs 61/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.000806270085295446, val_loss: 0.01861808382014118
epochs 62/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008815181332408133, val_loss: 0.018398578368649676
epochs 63/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008789967535288469, val_loss: 0.01833734050560644
epochs 64/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009064028998081251, val_loss: 0.01848360098573187
epochs 65/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008362607399522668, val_loss: 0.018379089475496026
epochs 66/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.001025356237065799, val_loss: 0.018090550788978813
epochs 67/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0010315583080285546, val_loss: 0.017928954897566685
epochs 68/94
Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0008735803080634226, val_loss: 0.017939760693393293
epochs 69/94

[I 2024-01-30 14:42:06,269] Trial 2 finished with value: 0.010334756432686018 and parameters: {'batch_size': 41, 'epochs': 94, 'hidden_size': 20, 'learning_rate': 7.59200897001826e-05, 'dropout_prob': 0.03039996337816533, 'weight_decay': 1.1101645002899062e-05, 'lr_step_size': 66, 'gamma': 0.12370692519362719, 'num_layers': 1}. Best is trial 2 with value: 0.010334756432686018.

Current Learning Rate: 7.59200897001826e-05
train_loss: 0.0009584952414917649, val_loss: 0.0010475044760227244
Mean validation loss: 0.010334756432686018
Starting fold 1:
epochs 1/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0026087213803915993, val_loss: 0.0020324989967602527
epochs 2/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0024344366632009806, val_loss: 0.002716567659277528
epochs 3/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.002283523200496443, val_loss: 0.003262640405741949
epochs 4/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0027750320536525626, val_loss: 0.003425586793113441
epochs 5/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.002431974253666244, val_loss: 0.0033248436271346043
epochs 6/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.002362358937726209, val_loss: 0.0030582006119879053
epochs 7/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.002530609430304091, val_loss: 0.002737240448209738
epochs 8/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0022726335752706384, val_loss: 0.002527686090962518
epochs 9/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0022416349285968432, val_loss: 0.002433866674971161
epochs 10/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0022995063734829032, val_loss: 0.0024245691810002817
epochs 11/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0020488321915955138, val_loss: 0.002530115710142704
epochs 12/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.002314697291800066, val_loss: 0.0025810392870057727
epochs 13/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0020811318278949904, val_loss: 0.002555132525259747
epochs 14/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0016906020047731305, val_loss: 0.002493674124476485
epochs 15/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0019626438715740252, val_loss: 0.0024477257453356057
epochs 16/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.001812569978401849, val_loss: 0.0024691668167222468
epochs 17/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0017630245628472614, val_loss: 0.0025132644102938235
epochs 18/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.00179307364711636, val_loss: 0.0025116931060366037
epochs 19/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0016634387870956408, val_loss: 0.002468396810212335
epochs 20/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0017133164654583915, val_loss: 0.0023902925031651402
epochs 21/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0017218576535876645, val_loss: 0.0023525328830897156
epochs 22/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0017487076772867065, val_loss: 0.002297775453096995
epochs 23/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0016668643465412682, val_loss: 0.0022599401339585524
epochs 24/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0016898063348459178, val_loss: 0.0022796834394010522
epochs 25/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0015530541778149966, val_loss: 0.0022747905704096727
epochs 26/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0013638925891810733, val_loss: 0.0022179805858445075
epochs 27/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0014805028380482997, val_loss: 0.002109519482473843
epochs 28/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0016360654777504112, val_loss: 0.002003400277721489
epochs 29/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0014086227226806315, val_loss: 0.0019546117597085883
epochs 30/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0015022547070035026, val_loss: 0.001993237938944413
epochs 31/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0014359680696782705, val_loss: 0.0020707061171017973
epochs 32/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0013685519451667604, val_loss: 0.0020954898370999014
epochs 33/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0012818031754393718, val_loss: 0.002136517922894748
epochs 34/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.001123861577300551, val_loss: 0.002148393690327389
epochs 35/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0013062930328918523, val_loss: 0.0021157205716470285
epochs 36/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0010943601676875628, val_loss: 0.0020498823903922344
epochs 37/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0010973215666844657, val_loss: 0.0019423618398991132
epochs 38/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0011334382224288818, val_loss: 0.0018482709507687046
epochs 39/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000993559068975676, val_loss: 0.0017831560980994254
epochs 40/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0010790529345333772, val_loss: 0.001796959489371465
epochs 41/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0009509387980582879, val_loss: 0.0018347989999234588
epochs 42/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.001098020439109716, val_loss: 0.001800609898285955
epochs 43/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008506694928081216, val_loss: 0.001796620144482909
epochs 44/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000886293470026239, val_loss: 0.00180809708457211
epochs 45/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0009757164409261589, val_loss: 0.0017902057713529626
epochs 46/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.001010699693946854, val_loss: 0.00173635434360236
epochs 47/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0010166047588235846, val_loss: 0.0016293695997095681
epochs 48/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008193559068451194, val_loss: 0.0015397482909195656
epochs 49/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0009512376031029577, val_loss: 0.0015437472803381434
epochs 50/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008077104983385652, val_loss: 0.0016033947770391398
epochs 51/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0010043470997755464, val_loss: 0.0016709791624822492
epochs 52/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008300466150486548, val_loss: 0.0017255525661831988
epochs 53/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.00076581467966255, val_loss: 0.0017455551017534047
epochs 54/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007886739885802136, val_loss: 0.0017980107772422747
epochs 55/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008733692232788981, val_loss: 0.0018133639345510996
epochs 56/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.001010151290775914, val_loss: 0.0017032291925427252
epochs 57/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0009165360727102349, val_loss: 0.0016113324197090512
epochs 58/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008015466621145606, val_loss: 0.0015850195493493672
epochs 59/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000744339196305526, val_loss: 0.0015914372112121552
epochs 60/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008042808404608973, val_loss: 0.0015647411482715388
epochs 61/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006913507923998527, val_loss: 0.0014948156830440792
epochs 62/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006687042073616268, val_loss: 0.001473595006419124
epochs 63/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006994682603123549, val_loss: 0.001557226659820622
epochs 64/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006380733298627954, val_loss: 0.0016774309666029044
epochs 65/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006829244752512559, val_loss: 0.0017393931911866521
epochs 66/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007656934033883245, val_loss: 0.0016642693937885472
epochs 67/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006106878201918382, val_loss: 0.0015409061863523213
epochs 68/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006235579062424797, val_loss: 0.0014776599042335644
epochs 69/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007037928493350352, val_loss: 0.0014657275758162584
epochs 70/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006068069460238085, val_loss: 0.0015042531860729915
epochs 71/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007457743450925735, val_loss: 0.0015669717970359627
epochs 72/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006011296443543152, val_loss: 0.0015538155728588915
epochs 73/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006141642292373274, val_loss: 0.001476394951977353
epochs 74/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007276147885836269, val_loss: 0.001410354867749404
epochs 75/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006280075259335143, val_loss: 0.0013393225050845464
epochs 76/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005915737579160027, val_loss: 0.0013633403085848493
epochs 77/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006559421614694752, val_loss: 0.001374992311217024
epochs 78/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006234279187322643, val_loss: 0.0013511359711484393
epochs 79/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005993402278124306, val_loss: 0.0012935612254613448
epochs 80/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000517277597253652, val_loss: 0.0012837311919105963
epochs 81/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005666798682221652, val_loss: 0.001280041557962134
epochs 82/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005871748404675408, val_loss: 0.001310714086728348
epochs 83/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005281513909147562, val_loss: 0.0012955849737091552
epochs 84/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006474966419198992, val_loss: 0.0012536075738598666
epochs 85/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004794797867744867, val_loss: 0.001204033804473482
epochs 86/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006233418412433055, val_loss: 0.0012449538261289634
epochs 87/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006519840362383739, val_loss: 0.0013535843934819457
epochs 88/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000565550698114461, val_loss: 0.0014767392930234709
epochs 89/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005993486336113787, val_loss: 0.0015250540454871953
epochs 90/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006821640249415252, val_loss: 0.0014654738012708664
epochs 91/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005628761882881487, val_loss: 0.0013651158676819047
epochs 92/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005961383408009025, val_loss: 0.001284609053751439
epochs 93/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004794490350545139, val_loss: 0.0012317684461503097
epochs 94/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005159954984647859, val_loss: 0.0012457376310882706
epochs 95/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005664277417389185, val_loss: 0.001314657957418748
epochs 96/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.00045609655238589957, val_loss: 0.0013792099413140455
epochs 97/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005500936966487452, val_loss: 0.0013927271758716199
epochs 98/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005758207778470885, val_loss: 0.0013386620012747626
epochs 99/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.00048042646621500974, val_loss: 0.0012832245390330041
epochs 100/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004901129642109338, val_loss: 0.0012725087301713222
epochs 101/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004679068310284301, val_loss: 0.0012956182952852003
epochs 102/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005644920931540822, val_loss: 0.0013351889086022442
epochs 103/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005191924059641008, val_loss: 0.0013527008372225932
epochs 104/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005004128683235888, val_loss: 0.0013526094782199444
epochs 105/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005312267531591811, val_loss: 0.0013177789831330764
epochs 106/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004925539700228623, val_loss: 0.0012775772433203188
epochs 107/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005598496664070377, val_loss: 0.0012393484706528456
epochs 108/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004153107345030692, val_loss: 0.0012282105499974614
epochs 109/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004455703476100768, val_loss: 0.00125975399818604
epochs 110/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004771786271655736, val_loss: 0.0013188678167930375
epochs 111/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005811176654931746, val_loss: 0.001344525446285612
epochs 112/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000488832499985093, val_loss: 0.001360343883991138
epochs 113/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005259779807314963, val_loss: 0.0013581456326406509
epochs 114/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.00047606918731042626, val_loss: 0.0013003887898299755
epochs 115/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004935440464913355, val_loss: 0.0012072435111760917
epochs 116/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0004292812452676069, val_loss: 0.0011232633601933244
epochs 117/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.00050695109928615, val_loss: 0.0010994888466989829
epochs 118/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0005266456910727644, val_loss: 0.0011657728441244375
Starting fold 2:
epochs 1/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0009228754980614935, val_loss: 0.03284975626165905
epochs 2/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000839845713081777, val_loss: 0.028263103113406234
epochs 3/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.001015259706219265, val_loss: 0.026427120709466557
epochs 4/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0010790587175578507, val_loss: 0.026534252075685397
epochs 5/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0010764957419449174, val_loss: 0.027367807333431547
epochs 6/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008207939196277242, val_loss: 0.027839009945709554
epochs 7/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000936598865094774, val_loss: 0.02777798305309954
epochs 8/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008466826743534754, val_loss: 0.027255604930576823
epochs 9/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0009207005396308402, val_loss: 0.026913125378390152
epochs 10/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008102169794541609, val_loss: 0.026613688776417385
epochs 11/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008659411851736892, val_loss: 0.02628739420620222
epochs 12/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008153608465065939, val_loss: 0.02600581905553265
epochs 13/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008151542245149907, val_loss: 0.02577174197705019
epochs 14/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0009169177476889245, val_loss: 0.025431509780150557
epochs 15/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007958194511385984, val_loss: 0.02505074722308015
epochs 16/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007266621152983393, val_loss: 0.02472974957218246
epochs 17/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0008373168751868938, val_loss: 0.024532922351407627
epochs 18/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007863366452818565, val_loss: 0.024537943214887663
epochs 19/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007060201331637652, val_loss: 0.02420955528283403
epochs 20/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007823596758083601, val_loss: 0.024085971467669994
epochs 21/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007119791237127507, val_loss: 0.024063805088637365
epochs 22/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000760164809807039, val_loss: 0.02411495598535689
epochs 23/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006961292563569007, val_loss: 0.023910725711002237
epochs 24/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007390837200596624, val_loss: 0.02360673545164958
epochs 25/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007867815302737735, val_loss: 0.02344176813309628
epochs 26/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000687429939668827, val_loss: 0.023181244723557953
epochs 27/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007521641565244743, val_loss: 0.02292331577914338
epochs 28/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007510092580171258, val_loss: 0.022386811023193693
epochs 29/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007213621813740021, val_loss: 0.022015806198829695
epochs 30/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006987917752866449, val_loss: 0.022405015334250437
epochs 31/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.000713665230555391, val_loss: 0.02274631354070845
epochs 32/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007109482022245614, val_loss: 0.02260055418850647
epochs 33/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007158486788575157, val_loss: 0.022055860993171496
epochs 34/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007554711849246872, val_loss: 0.021795407366303223
epochs 35/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007929277343990031, val_loss: 0.021746539503395085
epochs 36/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.00070034750395683, val_loss: 0.021600737258614527
epochs 37/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007695844942933602, val_loss: 0.02184020077425336
epochs 38/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0006708182607369503, val_loss: 0.021962363228556655
epochs 39/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007957179878904707, val_loss: 0.021858388728033456
epochs 40/118
Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0007457394892531681, val_loss: 0.02153798681314266
epochs 41/118

[I 2024-01-30 14:44:05,586] Trial 3 finished with value: 0.008323717569181186 and parameters: {'batch_size': 87, 'epochs': 118, 'hidden_size': 71, 'learning_rate': 8.205865104498625e-05, 'dropout_prob': 0.19473390238669874, 'weight_decay': 0.000591327449312974, 'lr_step_size': 51, 'gamma': 0.21371863072679062, 'num_layers': 4}. Best is trial 3 with value: 0.008323717569181186.

Current Learning Rate: 8.205865104498625e-05
train_loss: 0.0019157374982294345, val_loss: 0.0026318341464040772
Mean validation loss: 0.008323717569181186
Starting fold 1:
epochs 1/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.15546643350665507, val_loss: 0.028951933903117028
epochs 2/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.01147473719473438, val_loss: 0.03820847542512985
epochs 3/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.016106045684826216, val_loss: 0.003624212166797074
epochs 4/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.008094520641392784, val_loss: 0.0018578911928223475
epochs 5/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.001907209394573185, val_loss: 0.010092000225706705
epochs 6/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.005205890496175638, val_loss: 0.003264492164210727
epochs 7/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0014638786103061744, val_loss: 0.0013376414897807297
epochs 8/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.002090369128487318, val_loss: 0.0009849955510747219
epochs 9/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0007365127477035122, val_loss: 0.0031570918093036327
epochs 10/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0012618797442165057, val_loss: 0.003196087800749829
epochs 11/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0005830662802940136, val_loss: 0.0007888742363161688
epochs 12/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0005040418044173796, val_loss: 0.0006409825185232515
epochs 13/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0005173920803109036, val_loss: 0.0012809679410854607
epochs 14/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0004181508173994524, val_loss: 0.0019432707880956254
epochs 15/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0003203263990335951, val_loss: 0.000796989699001498
epochs 16/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.00022007090837608924, val_loss: 0.0005759369433646844
epochs 17/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.00027317044931758, val_loss: 0.0009176172535508014
epochs 18/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.00021610404870252273, val_loss: 0.0013288073298301445
epochs 19/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.00018853937853188988, val_loss: 0.0008903656040303527
epochs 20/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0001288016822256491, val_loss: 0.0006186316553909804
epochs 21/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.00016106283016453841, val_loss: 0.0007525076750122631
epochs 22/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0001429071003497627, val_loss: 0.000990379742962966
epochs 23/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.00012996505400607067, val_loss: 0.0007946556475612202
epochs 24/90
Current Learning Rate: 0.011098994293113963
train_loss: 9.785879810806364e-05, val_loss: 0.000583631388421747
epochs 25/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.00010687709593759409, val_loss: 0.000669233530523285
epochs 26/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.00011357834423267233, val_loss: 0.0008141592367633527
epochs 27/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.0001041216495459115, val_loss: 0.0006543376408184745
epochs 28/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.959754180212162e-05, val_loss: 0.0005851439729292271
epochs 29/90
Current Learning Rate: 0.011098994293113963
train_loss: 9.910694344925056e-05, val_loss: 0.000709608080681406
epochs 30/90
Current Learning Rate: 0.011098994293113963
train_loss: 9.478254697138542e-05, val_loss: 0.0006696183009475972
epochs 31/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.241570612881333e-05, val_loss: 0.0005682493852902322
epochs 32/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.793857276415159e-05, val_loss: 0.0006289003622008576
epochs 33/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.751610353711601e-05, val_loss: 0.0006707153463919115
epochs 34/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.750130517383743e-05, val_loss: 0.0005713819954839964
epochs 35/90
Current Learning Rate: 0.011098994293113963
train_loss: 9.252670478369844e-05, val_loss: 0.000530378624384794
epochs 36/90
Current Learning Rate: 0.011098994293113963
train_loss: 9.120334863454398e-05, val_loss: 0.0006370209786894968
epochs 37/90
Current Learning Rate: 0.011098994293113963
train_loss: 9.725992299775642e-05, val_loss: 0.0005699119580048506
epochs 38/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.315086000182323e-05, val_loss: 0.0005577645890067317
epochs 39/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.609555753585147e-05, val_loss: 0.0005661976017383119
epochs 40/90
Current Learning Rate: 0.011098994293113963
train_loss: 9.42511039044659e-05, val_loss: 0.0005656711790444595
epochs 41/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.197766498932125e-05, val_loss: 0.0005335468856159538
epochs 42/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.218592166055093e-05, val_loss: 0.0006245573628499793
epochs 43/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.480237815284024e-05, val_loss: 0.0005422824005585252
epochs 44/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.011150189914348e-05, val_loss: 0.0005416936589412332
epochs 45/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.788623900667421e-05, val_loss: 0.0005465786314397562
epochs 46/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.291418652656782e-05, val_loss: 0.0005457249439103411
epochs 47/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.276001216316792e-05, val_loss: 0.0005524914348146893
epochs 48/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.684145373212615e-05, val_loss: 0.0005381451384949735
epochs 49/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.064647722915795e-05, val_loss: 0.0005338502387675117
epochs 50/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.395052196347694e-05, val_loss: 0.0005725184067462882
epochs 51/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.461690524666522e-05, val_loss: 0.0005639843212621701
epochs 52/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.101492827623396e-05, val_loss: 0.0004934716887960565
epochs 53/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.729789672578734e-05, val_loss: 0.0005620597291872689
epochs 54/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.231736139817115e-05, val_loss: 0.0005469300974962405
epochs 55/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.096205756852501e-05, val_loss: 0.0005101983233111067
epochs 56/90
Current Learning Rate: 0.011098994293113963
train_loss: 8.284328298606468e-05, val_loss: 0.0005853035461133538
epochs 57/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.451881036487113e-05, val_loss: 0.0004995980728251327
epochs 58/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.651960729976724e-05, val_loss: 0.000548205300075342
epochs 59/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.82387583106021e-05, val_loss: 0.0005085813959123611
epochs 60/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.898833083393248e-05, val_loss: 0.00048641784607233215
epochs 61/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.359323449475739e-05, val_loss: 0.0005683982256284383
epochs 62/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.89686521257911e-05, val_loss: 0.0004958621724480985
epochs 63/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.541452344555996e-05, val_loss: 0.0005869468743820483
epochs 64/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.243866329142627e-05, val_loss: 0.0004918709542142183
epochs 65/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.251225102472266e-05, val_loss: 0.0005351736985002866
epochs 66/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.104689292119522e-05, val_loss: 0.0005175329939765294
epochs 67/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.123154129275415e-05, val_loss: 0.0004770535631992278
epochs 68/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.49348746504218e-05, val_loss: 0.0005442884453620377
epochs 69/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.710574686478236e-05, val_loss: 0.0004735483244220386
epochs 70/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.120590568152501e-05, val_loss: 0.0005626253070428022
epochs 71/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.45040709214089e-05, val_loss: 0.0004561530067659323
epochs 72/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.615897890278384e-05, val_loss: 0.0006039836815842944
epochs 73/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.93527356060957e-05, val_loss: 0.0004717831593191635
epochs 74/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.570844263095702e-05, val_loss: 0.0005066410476935008
epochs 75/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.287680091765269e-05, val_loss: 0.0005531715966450671
epochs 76/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.782821472274679e-05, val_loss: 0.00044926817529827417
epochs 77/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.914535406394861e-05, val_loss: 0.0005447010962165049
epochs 78/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.43530450180467e-05, val_loss: 0.0004640260675740946
epochs 79/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.833934392871973e-05, val_loss: 0.0005392781084602964
epochs 80/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.52114421092464e-05, val_loss: 0.0004382191095612056
epochs 81/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.600804129113002e-05, val_loss: 0.0005399955197289172
epochs 82/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.74029323195818e-05, val_loss: 0.0004479734976369415
epochs 83/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.301590843493805e-05, val_loss: 0.0005348801185766841
epochs 84/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.487193521994509e-05, val_loss: 0.00047631943062509575
epochs 85/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.182854020165426e-05, val_loss: 0.0005535594508050024
epochs 86/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.757790008326993e-05, val_loss: 0.00041915684322168725
epochs 87/90
Current Learning Rate: 0.011098994293113963
train_loss: 7.223078573588282e-05, val_loss: 0.0005178749892770106
epochs 88/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.190070412948875e-05, val_loss: 0.0004661725134134204
epochs 89/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.874168293985636e-05, val_loss: 0.00048018015421269136
epochs 90/90
Current Learning Rate: 0.011098994293113963
train_loss: 6.239004996084413e-05, val_loss: 0.000518167188154563
Starting fold 2:
epochs 1/90
Current Learning Rate: 0.011098994293113963
train_loss: 0.013495334922971105, val_loss: 0.017146193407594212
epochs 2/90

[I 2024-01-30 14:44:13,884] Trial 4 pruned.

Starting fold 1:
epochs 1/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.013609757524375854, val_loss: 0.007456400688391465
epochs 2/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.012947873707468572, val_loss: 0.007275926064245314
epochs 3/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.01337605457703926, val_loss: 0.007098334486024681
epochs 4/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.01370024351697219, val_loss: 0.00692331781268992
epochs 5/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.012783514612697456, val_loss: 0.006752336643686735
epochs 6/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.012721800027219088, val_loss: 0.006585203734517256
epochs 7/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.012296691541805078, val_loss: 0.006422642126886381
epochs 8/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.012131723837534848, val_loss: 0.00626397926530372
epochs 9/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.011913360998426614, val_loss: 0.0061091307443492705
epochs 10/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.012382130341996488, val_loss: 0.005956943111159105
epochs 11/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.01172714970123611, val_loss: 0.005807215928422809
epochs 12/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.011388513019406481, val_loss: 0.0056616444671625105
epochs 13/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0113838884905961, val_loss: 0.005519544711908099
epochs 14/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.01066031265195067, val_loss: 0.005381291777772641
epochs 15/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.010720318330353812, val_loss: 0.0052457840856972825
epochs 16/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.01015187504235655, val_loss: 0.005114614075941659
epochs 17/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.010571615394253872, val_loss: 0.004985527573991074
epochs 18/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.00990743616130203, val_loss: 0.004860511361916978
epochs 19/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.009797666055199347, val_loss: 0.004739448421994451
epochs 20/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.009298101138617646, val_loss: 0.00462193901295818
epochs 21/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.009827899176774449, val_loss: 0.004506885623510079
epochs 22/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.008974066913422, val_loss: 0.004394385303375582
epochs 23/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.009042997486693294, val_loss: 0.0042849616292326975
epochs 24/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.009031801423253981, val_loss: 0.00417827502128338
epochs 25/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.009365064849292762, val_loss: 0.004072410307046046
epochs 26/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.008727290155366062, val_loss: 0.003969434772251006
epochs 27/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.008224776578380874, val_loss: 0.003870489114585022
epochs 28/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.008448893950614883, val_loss: 0.0037742635116927207
epochs 29/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.008659629939785717, val_loss: 0.0036802291109413895
epochs 30/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.008093638100514286, val_loss: 0.003588327176181511
epochs 31/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.008414580137468874, val_loss: 0.0034989652294103823
epochs 32/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.007941199143686774, val_loss: 0.0034130960105420655
epochs 33/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.007242515901299684, val_loss: 0.00332973117012501
epochs 34/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.007031654236274526, val_loss: 0.003249386457908682
epochs 35/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.007621074243644743, val_loss: 0.0031720460645075907
epochs 36/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.006865217771356631, val_loss: 0.003097194749720286
epochs 37/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.007842408137788115, val_loss: 0.0030233830442373696
epochs 38/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.006987995768921744, val_loss: 0.0029515797652984186
epochs 39/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.007322807721548566, val_loss: 0.0028817414581127684
epochs 40/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0067065388773028785, val_loss: 0.002814291039834085
epochs 41/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.00612596600671838, val_loss: 0.0027502004373461384
epochs 42/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.006681500139376639, val_loss: 0.0026888675410571515
epochs 43/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.006461075889436822, val_loss: 0.0026290877355711053
epochs 44/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.006636970545974021, val_loss: 0.0025712064925948325
epochs 45/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.006472302211056415, val_loss: 0.002515101455005438
epochs 46/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.006658837357290873, val_loss: 0.002460516708510036
epochs 47/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0060368122600362095, val_loss: 0.00240834656207842
epochs 48/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.006033702129130496, val_loss: 0.002358129588491653
epochs 49/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.005828835527829238, val_loss: 0.0023104614133468617
epochs 50/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.005915292960248495, val_loss: 0.0022643782075546267
epochs 51/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.005594321546806513, val_loss: 0.0022205792585506087
epochs 52/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.005498692618781015, val_loss: 0.002178579471696158
epochs 53/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.00536225010781843, val_loss: 0.002138546422997332
epochs 54/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.005422167567609761, val_loss: 0.0021005359505396827
epochs 55/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.00457991723424608, val_loss: 0.002064727772940098
epochs 56/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0050101551870619385, val_loss: 0.0020308219344187628
epochs 57/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.00508705009890132, val_loss: 0.001998484016718865
epochs 58/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.005073110835847298, val_loss: 0.001967414957348001
epochs 59/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.00481123429122626, val_loss: 0.0019378200307040027
epochs 60/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004712949746202579, val_loss: 0.0019093385272999368
epochs 61/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004814929514510655, val_loss: 0.0018826258575442745
epochs 62/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004430167177250903, val_loss: 0.001857634709233901
epochs 63/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004736698036523242, val_loss: 0.0018341620485039635
epochs 64/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004885113439032513, val_loss: 0.0018117358412522153
epochs 65/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004535794263325729, val_loss: 0.0017906863030807544
epochs 66/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004464690374994748, val_loss: 0.001771218933210654
epochs 67/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0042047636405760916, val_loss: 0.001753042864572582
epochs 68/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004246563251792012, val_loss: 0.0017364819458052614
epochs 69/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004172965179589626, val_loss: 0.0017212474723001597
epochs 70/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004069359854206835, val_loss: 0.0017074150464155037
epochs 71/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.003978263327582298, val_loss: 0.0016950753288159995
epochs 72/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0040225014776775715, val_loss: 0.0016839268493987177
epochs 73/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.004322289976315867, val_loss: 0.0016738679548743965
epochs 74/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.003995208036902017, val_loss: 0.0016648449154913168
epochs 75/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0035417000202486587, val_loss: 0.0016569652665922635
epochs 76/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.003961932478705421, val_loss: 0.0016501500979915912
epochs 77/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0039157065437297875, val_loss: 0.0016442995593746355
epochs 78/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0035553265742859557, val_loss: 0.0016394766142222878
epochs 79/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0035732945843942854, val_loss: 0.001635664166536468
epochs 80/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0039405940333381295, val_loss: 0.0016327142987551818
epochs 81/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.003483986363770734, val_loss: 0.0016306744982819837
epochs 82/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.003468018209586214, val_loss: 0.0016295226090174985
epochs 83/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0032796859477744683, val_loss: 0.0016292170582187643
epochs 84/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0034027338842861354, val_loss: 0.0016297306636395795
epochs 85/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.003406700899971551, val_loss: 0.0016310774665692373
epochs 86/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.003018621357133318, val_loss: 0.0016332270048060404
epochs 87/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0034740496040812055, val_loss: 0.0016360534097883536
epochs 88/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.0032498027418593044, val_loss: 0.0016395427473451481
epochs 89/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.003261512634957111, val_loss: 0.0016437665828138407
epochs 90/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.003239784023945073, val_loss: 0.0016487086903277375
epochs 91/141
Current Learning Rate: 2.996244060242214e-06
train_loss: 0.00343743435683121, val_loss: 0.001654446516411592
epochs 92/141

[I 2024-01-30 14:44:23,021] Trial 5 pruned.

Starting fold 1:
epochs 1/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.05473988930645742, val_loss: 0.06983510881820053
epochs 2/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.04995158336272365, val_loss: 0.06427910579023538
epochs 3/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.045148883907026365, val_loss: 0.05899390666967347
epochs 4/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.041708490752467985, val_loss: 0.053972497543014544
epochs 5/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.03820422695655572, val_loss: 0.04921098057397459
epochs 6/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.03456244637307368, val_loss: 0.044715612574859905
epochs 7/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.030981140172010972, val_loss: 0.04048477573487809
epochs 8/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0278922843648807, val_loss: 0.03651938727371907
epochs 9/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.02531980442275342, val_loss: 0.03281394692837561
epochs 10/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.02309347139181275, val_loss: 0.029360830300935992
epochs 11/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.019865796254261544, val_loss: 0.026162082743313577
epochs 12/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.01778423733715164, val_loss: 0.023209391280062615
epochs 13/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.01602663616159637, val_loss: 0.02049779433205172
epochs 14/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.01337840112024232, val_loss: 0.01802230569676905
epochs 15/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.011264249545178915, val_loss: 0.015776562332003204
epochs 16/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.010614708374793592, val_loss: 0.01374365508595787
epochs 17/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.00851888387022834, val_loss: 0.011921023476928
epochs 18/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.007657446233114522, val_loss: 0.010294726327869786
epochs 19/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.00672417205366257, val_loss: 0.008851099054688814
epochs 20/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.005934990332829521, val_loss: 0.0075778121254332954
epochs 21/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.004720646939485481, val_loss: 0.006470159916995615
epochs 22/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.004266469187323789, val_loss: 0.005511211353309807
epochs 23/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.003267974489809651, val_loss: 0.004692549221636481
epochs 24/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.002815240673647311, val_loss: 0.003998118905454046
epochs 25/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0025440460824603705, val_loss: 0.0034129270839026917
epochs 26/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0021639856969398494, val_loss: 0.0029254006763930044
epochs 27/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0018954211352760657, val_loss: 0.002522035915202525
epochs 28/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0016744873737671265, val_loss: 0.002192842355552351
epochs 29/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0016337707228223353, val_loss: 0.001923628651417506
epochs 30/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0016960961768697751, val_loss: 0.0017069940290182198
epochs 31/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0016181843165357253, val_loss: 0.0015350208322396847
epochs 32/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0015169498185921265, val_loss: 0.0013991709764388995
epochs 33/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0012085645018439545, val_loss: 0.0012928899506934816
epochs 34/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0013929606421458486, val_loss: 0.0012105435845023267
epochs 35/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0013906024126826148, val_loss: 0.001145322989301618
epochs 36/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0013292013116082862, val_loss: 0.0010941962186566175
epochs 37/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0011773955637564588, val_loss: 0.0010562391291685383
epochs 38/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0013369307504035532, val_loss: 0.0010280786832072648
epochs 39/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.001241555825598832, val_loss: 0.0010087594536820515
epochs 40/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0011515114505432154, val_loss: 0.000996732264024171
epochs 41/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0013000500878613246, val_loss: 0.0009884815470613637
epochs 42/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0012680950960585553, val_loss: 0.000985727825469372
epochs 43/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0013941918671327201, val_loss: 0.0009851567026796853
epochs 44/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0012451004500402825, val_loss: 0.0009854401827656797
epochs 45/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0011098421874186513, val_loss: 0.000988363282183412
epochs 46/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.001247316429170927, val_loss: 0.0009922788858169778
epochs 47/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0010450364145646361, val_loss: 0.000999498619296386
epochs 48/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0009858475275043594, val_loss: 0.0010071549304051413
epochs 49/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.001123037278701208, val_loss: 0.0010147831463852464
epochs 50/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0012479222217256106, val_loss: 0.0010222192981807644
epochs 51/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.001096896962017605, val_loss: 0.0010301095309418443
epochs 52/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.001170806144364178, val_loss: 0.0010371436996301686
epochs 53/96
Epoch 00053: reducing learning rate of group 0 to 5.9300e-05.
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.0012928532405854449, val_loss: 0.001044986435478903
epochs 54/96
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.0011203013562695369, val_loss: 0.0010486310028388515
epochs 55/96
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.001091944889814936, val_loss: 0.001052560453428197
epochs 56/96
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.001069127153421409, val_loss: 0.0010561963198207585
epochs 57/96
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.0011255527665765073, val_loss: 0.0010593854645901562
epochs 58/96
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.001030774416990186, val_loss: 0.0010619353893811681
epochs 59/96
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.0011120935356685598, val_loss: 0.001064542233180156
epochs 60/96
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.0009897396550513804, val_loss: 0.001067926517592881
epochs 61/96
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.0012731159743117658, val_loss: 0.0010711477494123516
epochs 62/96
Current Learning Rate: 5.930001232332744e-05
train_loss: 0.0010984664225313617, val_loss: 0.001076107409307807
epochs 63/96
Epoch 00063: reducing learning rate of group 0 to 2.7527e-05.
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.0010458491813072836, val_loss: 0.0010799163892106325
epochs 64/96
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.0011366231550805662, val_loss: 0.0010815082447758566
epochs 65/96
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.001140059188841597, val_loss: 0.0010827096876233728
epochs 66/96
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.0010502617996137002, val_loss: 0.001083083857862875
epochs 67/96
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.0009998591028546032, val_loss: 0.0010830955833188017
epochs 68/96
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.0012227861051398673, val_loss: 0.0010835017556067132
epochs 69/96
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.001102671673594925, val_loss: 0.0010835737602541311
epochs 70/96
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.0010355934813177506, val_loss: 0.0010832350069894727
epochs 71/96
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.0010096487635133885, val_loss: 0.001083474226924837
epochs 72/96
Current Learning Rate: 2.7526930841392675e-05
train_loss: 0.0011386351083944504, val_loss: 0.001084041318757011
epochs 73/96
Epoch 00073: reducing learning rate of group 0 to 1.2778e-05.
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.001097621494217923, val_loss: 0.001084742490935174
epochs 74/96
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.0011282714966096377, val_loss: 0.0010849130439243117
epochs 75/96
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.0010609266770954587, val_loss: 0.001085099364106085
epochs 76/96
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.0010927761426979773, val_loss: 0.0010852761189059092
epochs 77/96
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.00117573338058336, val_loss: 0.0010852179886242277
epochs 78/96
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.0011876286319947164, val_loss: 0.0010851321190043731
epochs 79/96
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.0010339547248900329, val_loss: 0.001085496584810292
epochs 80/96
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.0009807109302767602, val_loss: 0.0010856353103740031
epochs 81/96
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.0011496773406275008, val_loss: 0.001085678089540033
epochs 82/96
Current Learning Rate: 1.2777938686004937e-05
train_loss: 0.0009619859849887066, val_loss: 0.0010858214039616682
epochs 83/96
Epoch 00083: reducing learning rate of group 0 to 5.9315e-06.
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.0011576512696736148, val_loss: 0.0010857647679075994
epochs 84/96
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.0009740713793833397, val_loss: 0.0010857711170853001
epochs 85/96
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.001187260107651941, val_loss: 0.0010857208235104316
epochs 86/96
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.0009430274643052957, val_loss: 0.0010857033073161753
epochs 87/96
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.0012623867553070579, val_loss: 0.0010855300559861852
epochs 88/96
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.0011088436273367782, val_loss: 0.0010853053922007334
epochs 89/96
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.0011618221785235955, val_loss: 0.0010851664636801514
epochs 90/96
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.001126788380727368, val_loss: 0.001085020800009641
epochs 91/96
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.0010496889786353629, val_loss: 0.0010849882158846225
epochs 92/96
Current Learning Rate: 5.931490074359519e-06
train_loss: 0.0010503362992925471, val_loss: 0.0010849802046318207
epochs 93/96
Epoch 00093: reducing learning rate of group 0 to 2.7534e-06.
Current Learning Rate: 2.7533842012216943e-06
train_loss: 0.0009755064264601586, val_loss: 0.0010849726404076954
epochs 94/96
Current Learning Rate: 2.7533842012216943e-06
train_loss: 0.0009572107063018178, val_loss: 0.0010849714577758547
epochs 95/96
Current Learning Rate: 2.7533842012216943e-06
train_loss: 0.0010503896616252237, val_loss: 0.0010849968801257472
epochs 96/96
Current Learning Rate: 2.7533842012216943e-06
train_loss: 0.0010855274881530358, val_loss: 0.0010849669578463015
Starting fold 2:
epochs 1/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0014366912981126664, val_loss: 0.026581210020200287
epochs 2/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.001177345901988152, val_loss: 0.02388222444625128
epochs 3/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0013233569067028059, val_loss: 0.022424632215271235
epochs 4/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0013551194808079732, val_loss: 0.021923067900672475
epochs 5/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.001239880893501087, val_loss: 0.02205895870510075
epochs 6/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0012170817859048185, val_loss: 0.022209252240678306
epochs 7/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0011368986682371682, val_loss: 0.02204134425631276
epochs 8/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0010221208262043491, val_loss: 0.021804250136175485
epochs 9/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0010833178496659098, val_loss: 0.021489213472084392
epochs 10/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0011023792562917818, val_loss: 0.021161338590361452
epochs 11/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0010091675049809636, val_loss: 0.02061706272116493
epochs 12/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0011609800591190053, val_loss: 0.019970302568581053
epochs 13/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0009629126692849327, val_loss: 0.019157135684200854
epochs 14/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.001032187411282703, val_loss: 0.01863700180023751
epochs 15/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0009092452146769022, val_loss: 0.018320549826418595
epochs 16/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0010088879802745906, val_loss: 0.018227586650816852
epochs 17/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0008658981678692874, val_loss: 0.0182986325490727
epochs 18/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0008954677691174509, val_loss: 0.01826154073040006
epochs 19/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007521951524110752, val_loss: 0.01810803090434068
epochs 20/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0008482195593301196, val_loss: 0.01815426929375876
epochs 21/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0009029608840026984, val_loss: 0.01813509070595342
epochs 22/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0008287808802875747, val_loss: 0.017649891362500884
epochs 23/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0009558697250772435, val_loss: 0.016971142984749304
epochs 24/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0008846897933519099, val_loss: 0.01631975575552258
epochs 25/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.000922195388847043, val_loss: 0.015827909851121525
epochs 26/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0008679836172006022, val_loss: 0.015576005913317204
epochs 27/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0008135451357762543, val_loss: 0.015521583381409526
epochs 28/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007357923165000582, val_loss: 0.015700817374246463
epochs 29/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0008453620357517556, val_loss: 0.015517554305020779
epochs 30/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007227361596946292, val_loss: 0.015122652460362703
epochs 31/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007303504360530103, val_loss: 0.014778165912955369
epochs 32/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007637810729330991, val_loss: 0.014660038852265902
epochs 33/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0008404325809953906, val_loss: 0.014468864752127537
epochs 34/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007358412367370383, val_loss: 0.014180123153088427
epochs 35/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006950038434086137, val_loss: 0.014061339061569285
epochs 36/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006653846800265868, val_loss: 0.013971437079211077
epochs 37/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007889765718064731, val_loss: 0.013936111489163032
epochs 38/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007645645059674664, val_loss: 0.013792224383602539
epochs 39/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007608841638090605, val_loss: 0.013654327172805708
epochs 40/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0005927213687587303, val_loss: 0.013320769089712668
epochs 41/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006389472007599111, val_loss: 0.012889786877191414
epochs 42/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006213302341336507, val_loss: 0.012520710367305333
epochs 43/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006180534261066251, val_loss: 0.012306864919121224
epochs 44/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007353805551995919, val_loss: 0.011988883706243344
epochs 45/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006504686600602377, val_loss: 0.011782483482319448
epochs 46/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006602829744416414, val_loss: 0.011683653070586462
epochs 47/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006179419655007578, val_loss: 0.011784858426335391
epochs 48/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006807127942596525, val_loss: 0.0119210838244134
epochs 49/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006413906565400474, val_loss: 0.011903567736101135
epochs 50/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006627726309784101, val_loss: 0.011730011394888004
epochs 51/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0005993908039284354, val_loss: 0.011500590223395241
epochs 52/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006576191401569846, val_loss: 0.011464657153559741
epochs 53/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007029182793963258, val_loss: 0.011271185586573902
epochs 54/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006239404153148828, val_loss: 0.010849155486861944
epochs 55/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006302558466187607, val_loss: 0.010363374860149132
epochs 56/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007219591024724919, val_loss: 0.010140028641751361
epochs 57/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0007180830133258117, val_loss: 0.010129390283187151
epochs 58/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006067281760002602, val_loss: 0.01010677766143566
epochs 59/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006163699803830893, val_loss: 0.010103314965914087
epochs 60/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006367395177979936, val_loss: 0.010217712370422545
epochs 61/96
Current Learning Rate: 0.00012774731341494067
train_loss: 0.0006448336327718792, val_loss: 0.010227300066540324
epochs 62/96
Current Learning Rate: 0.00012774731341494067

[I 2024-01-30 14:45:25,155] Trial 6 finished with value: 0.005435122813030339 and parameters: {'batch_size': 107, 'epochs': 96, 'hidden_size': 54, 'learning_rate': 0.00012774731341494067, 'dropout_prob': 0.0780852120548357, 'weight_decay': 4.230067116377507e-06, 'lr_step_size': 9, 'gamma': 0.46419772547946214, 'num_layers': 1}. Best is trial 6 with value: 0.005435122813030339.

Starting fold 1:
epochs 1/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.023977631310883322, val_loss: 0.02624332686028783
epochs 2/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.020369679446479206, val_loss: 0.021234494944413502
epochs 3/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.015854397457779237, val_loss: 0.016888227905072863
epochs 4/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.012657421138627748, val_loss: 0.013193212419984833
epochs 5/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.010267310307091592, val_loss: 0.010099858016012207
epochs 6/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.007798492173223119, val_loss: 0.0076124028021854065
epochs 7/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.005831671017451873, val_loss: 0.005656609858667094
epochs 8/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.004249296552428093, val_loss: 0.004170511043556626
epochs 9/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0033280976809022065, val_loss: 0.003094394998033605
epochs 10/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.002753689780978388, val_loss: 0.002341268124014494
epochs 11/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0021725179455978306, val_loss: 0.001830298931241804
epochs 12/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.002092633935573854, val_loss: 0.0014990001089043086
epochs 13/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.00181257691675503, val_loss: 0.0012913028255016321
epochs 14/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.001691923783111729, val_loss: 0.0011623729175577562
epochs 15/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.001465395387066038, val_loss: 0.0010809926075919989
epochs 16/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0013827174950979259, val_loss: 0.0010346027445935068
epochs 17/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0013976297218744691, val_loss: 0.0010133784112801392
epochs 18/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0012793200225324223, val_loss: 0.0010043087707359403
epochs 19/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.001248396118171513, val_loss: 0.0009974127372963325
epochs 20/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0012809700075242865, val_loss: 0.0009992799115559412
epochs 21/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.001326231169514358, val_loss: 0.0010126235096582345
epochs 22/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0013529533263001788, val_loss: 0.001029313789562337
epochs 23/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0012614924742497112, val_loss: 0.0010586169027235535
epochs 24/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0013483824686294323, val_loss: 0.0010886265127550041
epochs 25/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0012886876632508479, val_loss: 0.0011041643308653008
epochs 26/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.001394176255225351, val_loss: 0.0011089995359292342
epochs 27/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0010857717746770696, val_loss: 0.0011183045017311261
epochs 28/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0011279927750461195, val_loss: 0.0011287529875213902
epochs 29/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.001115512715554551, val_loss: 0.0011310234466301544
epochs 30/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.0010968398388573213, val_loss: 0.001131659469729851
epochs 31/53
Current Learning Rate: 4.966772580472261e-05
train_loss: 0.001188999501449105, val_loss: 0.0011332939177500232
epochs 32/53

[I 2024-01-30 14:45:28,037] Trial 7 pruned.

Starting fold 1:
epochs 1/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.06891588335366626, val_loss: 0.0796269638434289
epochs 2/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.0602975615545323, val_loss: 0.07177135513888465
epochs 3/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.05791446411688077, val_loss: 0.06442141044076788
epochs 4/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.05109337042821081, val_loss: 0.05757000821608084
epochs 5/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.04632353880687764, val_loss: 0.05119899506606753
epochs 6/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.03964176491687172, val_loss: 0.045320861278072236
epochs 7/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.03615474746023354, val_loss: 0.039920340691293986
epochs 8/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.031508869795422806, val_loss: 0.034984442232935516
epochs 9/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.029316250528944165, val_loss: 0.0304720216090717
epochs 10/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.024841815992993743, val_loss: 0.02638936777988439
epochs 11/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.02206214016891624, val_loss: 0.022717692943477127
epochs 12/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.01805648712539359, val_loss: 0.019451488775235636
epochs 13/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.017690090080232996, val_loss: 0.016540467078802447
epochs 14/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.014346072543412447, val_loss: 0.013968530313047782
epochs 15/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.011094592166084207, val_loss: 0.011749566655862268
epochs 16/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.010789337342506962, val_loss: 0.009831308027502721
epochs 17/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.009917018334626368, val_loss: 0.00817069134344815
epochs 18/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.008116871421225368, val_loss: 0.006752276847326251
epochs 19/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.007511424372511867, val_loss: 0.005566459829135547
epochs 20/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.006089661774029465, val_loss: 0.004584052925190282
epochs 21/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.004821474516862317, val_loss: 0.0037811645380561314
epochs 22/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.0038083476798706933, val_loss: 0.00315854175351363
epochs 23/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.004904718486298072, val_loss: 0.0026621022532698968
epochs 24/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.0040750008713650076, val_loss: 0.0022644131178302424
epochs 25/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.0036097175123071985, val_loss: 0.001962953996130083
epochs 26/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.0036279515093682628, val_loss: 0.001739911897669709
epochs 27/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.0034800798779255466, val_loss: 0.001576137594711134
epochs 28/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.003348246523130097, val_loss: 0.0014569252303175669
epochs 29/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.0029992447357232634, val_loss: 0.0013753436444199118
epochs 30/113

[I 2024-01-30 14:45:30,674] Trial 8 pruned.

Current Learning Rate: 0.00010184762613922115
train_loss: 0.003409604941445746, val_loss: 0.0013175881800374814
epochs 31/113
Current Learning Rate: 0.00010184762613922115
train_loss: 0.0029737789061312614, val_loss: 0.0012761120346902067
epochs 32/113
Starting fold 1:
epochs 1/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0019150351186429985, val_loss: 0.001953025421783052
epochs 2/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.002048742666987604, val_loss: 0.001931385764489985
epochs 3/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0021054188769898917, val_loss: 0.0019096601581959814
epochs 4/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.002259067876117402, val_loss: 0.001887660533948629
epochs 5/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0019624691971234587, val_loss: 0.0018656380621164485
epochs 6/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0021131809261676513, val_loss: 0.0018433278374787834
epochs 7/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0017026729685695548, val_loss: 0.0018225069938193042
epochs 8/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.002103087010695354, val_loss: 0.0018028898436265688
epochs 9/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0018173378071208533, val_loss: 0.00178379688144627
epochs 10/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.002094135558428733, val_loss: 0.0017651875192920368
epochs 11/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0020140177717334344, val_loss: 0.0017472791153489164
epochs 12/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.002167350247404293, val_loss: 0.0017291233762753782
epochs 13/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0022616287264482756, val_loss: 0.0017109822430130509
epochs 14/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0018264208969316984, val_loss: 0.0016938831971923787
epochs 15/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.002091569802723825, val_loss: 0.0016774592222645879
epochs 16/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.001798431079001411, val_loss: 0.0016611535145245769
epochs 17/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.002015362795148241, val_loss: 0.001645169439682461
epochs 18/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0019704590882419757, val_loss: 0.0016298778193433667
epochs 19/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.002101671379549723, val_loss: 0.0016146727139130235
epochs 20/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.00250982143180935, val_loss: 0.0015990738476695562
epochs 21/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0019458442411728596, val_loss: 0.0015833810493522495
epochs 22/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0021634917044521945, val_loss: 0.0015676317949934553
epochs 23/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0019011860456023561, val_loss: 0.0015517969883081537
epochs 24/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0020476000873666063, val_loss: 0.0015357510807613532
epochs 25/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.002094798579223846, val_loss: 0.0015194072329904884
epochs 26/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.001742041515382497, val_loss: 0.0015038515719222939
epochs 27/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0015578918845245713, val_loss: 0.0014888024058934577
epochs 28/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0016632369866496639, val_loss: 0.0014752814906252617
epochs 29/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.00152213501278311, val_loss: 0.001462866446537966
epochs 30/69

[I 2024-01-30 14:45:33,573] Trial 9 pruned.

Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0018234225394400327, val_loss: 0.0014509907373899801
epochs 31/69
Current Learning Rate: 3.043346949685802e-06
train_loss: 0.0017345969148568417, val_loss: 0.001440535388947292
epochs 32/69
Starting fold 1:
epochs 1/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.020057395482925993, val_loss: 0.004041672820994068
epochs 2/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0031101045201802134, val_loss: 0.013667001862019773
epochs 3/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.009687348815465444, val_loss: 0.013352038190951423
epochs 4/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.007631753624024752, val_loss: 0.003502919530821225
epochs 5/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0019764233539861283, val_loss: 0.0013176951453917557
epochs 6/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0026067211016963577, val_loss: 0.0016362189707006254
epochs 7/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.002283634556040756, val_loss: 0.0013114919572780352
epochs 8/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0007158758081985932, val_loss: 0.0032906460710653354
epochs 9/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0013434856552569392, val_loss: 0.004812796315592196
epochs 10/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.002188730049927376, val_loss: 0.004147808257830403
epochs 11/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0019062786235927458, val_loss: 0.0023299550835324066
epochs 12/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0009143467689251625, val_loss: 0.0011403519144680882
epochs 13/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0006920992314055759, val_loss: 0.000887742473943425
epochs 14/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0007366091129370033, val_loss: 0.000868547584913257
epochs 15/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0005758360196762767, val_loss: 0.0011864663829328492
epochs 16/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0003851709621621443, val_loss: 0.0018522264015498674
epochs 17/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0005614880585007516, val_loss: 0.002044415635441149
epochs 18/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0005296639692173095, val_loss: 0.0015576208418693453
epochs 19/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.00035425478509798844, val_loss: 0.0009369572586682994
epochs 20/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0003386319336162782, val_loss: 0.0007175576045281357
epochs 21/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0004448355939147357, val_loss: 0.0007750618249355327
epochs 22/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0003303495717486122, val_loss: 0.0010856149264515216
epochs 23/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.00024120440020372993, val_loss: 0.0013562395687340685
epochs 24/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0003323975444226036, val_loss: 0.0012079342088240775
epochs 25/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0002654419802159904, val_loss: 0.0009142097174873694
epochs 26/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.00024027158735981702, val_loss: 0.0007651555873934062
epochs 27/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0002846295465899043, val_loss: 0.0007823609445791041
epochs 28/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.00022697373565997144, val_loss: 0.0009579545259752887
epochs 29/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0002503539441692594, val_loss: 0.0010819119922835232
epochs 30/148
Epoch 00030: reducing learning rate of group 0 to 1.4168e-03.
Current Learning Rate: 0.0014167775767202242
train_loss: 0.00023832115793514898, val_loss: 0.0010497511446749465
epochs 31/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0002436805011759708, val_loss: 0.000937228913359817
epochs 32/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.00018478920553063386, val_loss: 0.0008663482897515808
epochs 33/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0002105875172051846, val_loss: 0.0008329465763092721
epochs 34/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.00020065628463941578, val_loss: 0.0008594296253119994
epochs 35/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.00022269644193185836, val_loss: 0.000905449955358303
epochs 36/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.00024122201491416872, val_loss: 0.0009052994181050933
epochs 37/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.00019914136803555793, val_loss: 0.000865458315635647
epochs 38/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.00022668199442130955, val_loss: 0.0007963549488479094
epochs 39/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.00016326250877586734, val_loss: 0.0007450461723945207
epochs 40/148
Epoch 00040: reducing learning rate of group 0 to 1.0402e-03.
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0001867977756774053, val_loss: 0.0007762508981931393
epochs 41/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.00021302938923901436, val_loss: 0.0007916205696159206
epochs 42/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0001843955196627097, val_loss: 0.0008155539881766937
epochs 43/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.00015506837141736853, val_loss: 0.0007989392248592118
epochs 44/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.00017039012998697886, val_loss: 0.0007703921834786704
epochs 45/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.00016783094937349426, val_loss: 0.000726549971168713
epochs 46/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.00018248132519626156, val_loss: 0.000727792765477687
epochs 47/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.00019489473580554324, val_loss: 0.0007501388798349551
epochs 48/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.00015639519616869572, val_loss: 0.0007946298636462805
epochs 49/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0001763904752136257, val_loss: 0.000791698530462334
epochs 50/148
Epoch 00050: reducing learning rate of group 0 to 7.6368e-04.
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0001646597839058622, val_loss: 0.0007867890965407862
epochs 51/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.00014372119671622241, val_loss: 0.0007957394529570131
epochs 52/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0001755950539709853, val_loss: 0.000786372524869096
epochs 53/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.000198391717429714, val_loss: 0.0007819279216207741
epochs 54/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.00019908369898698048, val_loss: 0.000738942958248247
epochs 55/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.00016515756050418867, val_loss: 0.0007247809565068031
epochs 56/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.00017308993678613518, val_loss: 0.0007342338302849038
epochs 57/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.00021325442373237917, val_loss: 0.0007471476232499949
epochs 58/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.00018473239554288355, val_loss: 0.0007588197793608294
epochs 59/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.00018453066165277147, val_loss: 0.0007633492974231818
epochs 60/148
Epoch 00060: reducing learning rate of group 0 to 5.6068e-04.
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00017365268217154633, val_loss: 0.0007582620993840494
epochs 61/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00017029589695371933, val_loss: 0.0007366040626370777
epochs 62/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00016759254373793835, val_loss: 0.0007156157170400201
epochs 63/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00017570521120337379, val_loss: 0.0007047466866742257
epochs 64/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00020868341012637278, val_loss: 0.0007173272447072945
epochs 65/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0001711345997663509, val_loss: 0.0007136808299470605
epochs 66/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00017360737577914017, val_loss: 0.0007161815604102606
epochs 67/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00018406549750484135, val_loss: 0.0007280731390762542
epochs 68/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0002158423248482378, val_loss: 0.0007300656258834466
epochs 69/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00018456831496319195, val_loss: 0.0007348690952991121
epochs 70/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00015742156542010457, val_loss: 0.0007329793433965523
epochs 71/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0001670220781785534, val_loss: 0.0007347971256840826
epochs 72/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00019645421416498722, val_loss: 0.0007220660867576029
epochs 73/148
Epoch 00073: reducing learning rate of group 0 to 4.1164e-04.
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00014892377305506289, val_loss: 0.0007161228626038849
epochs 74/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00016879562807796327, val_loss: 0.0007285792951098835
epochs 75/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00019687609976819275, val_loss: 0.0007370633566530333
epochs 76/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00016796182026155294, val_loss: 0.0007507535264021643
epochs 77/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.0001704967504912546, val_loss: 0.0007559966556044177
epochs 78/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00017515014869308, val_loss: 0.0007423780905175215
epochs 79/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00016498729375215542, val_loss: 0.0007101112171926255
epochs 80/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00016973795929133256, val_loss: 0.0006787057267039985
epochs 81/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00017558808789257648, val_loss: 0.000671998617084076
epochs 82/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00015561164454036197, val_loss: 0.0006945076757036741
epochs 83/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00017347882393024567, val_loss: 0.0007196383972075724
epochs 84/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00016787171855532122, val_loss: 0.0007441079496712763
epochs 85/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00015400839325402078, val_loss: 0.0007381111562218783
epochs 86/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00016663276569727859, val_loss: 0.0007178159384426498
epochs 87/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.0001556087161206003, val_loss: 0.000695608168912475
epochs 88/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00017537611910436107, val_loss: 0.0006875598716313049
epochs 89/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.00015655420563569735, val_loss: 0.0006942400701403145
epochs 90/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.0001610949520622135, val_loss: 0.0007229686646799868
epochs 91/148
Epoch 00091: reducing learning rate of group 0 to 3.0222e-04.
Current Learning Rate: 0.0003022227472596694
train_loss: 0.00018739762339177297, val_loss: 0.000722140111888404
epochs 92/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0001506753643058657, val_loss: 0.0007084535493973702
epochs 93/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0001581768946428048, val_loss: 0.0006993601802230206
epochs 94/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.00017089074382582975, val_loss: 0.0006982679164687556
epochs 95/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.00016169633772254824, val_loss: 0.0006844138577377187
epochs 96/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.00014984929584898054, val_loss: 0.0006782171008775809
epochs 97/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.00016251765260485147, val_loss: 0.0006812189325472222
epochs 98/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.00018615469652056497, val_loss: 0.0006917418356770502
epochs 99/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.00016498458655979975, val_loss: 0.0006977879926876446
epochs 100/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.00015570775281766575, val_loss: 0.0007118567455253224
epochs 101/148
Epoch 00101: reducing learning rate of group 0 to 2.2189e-04.
Current Learning Rate: 0.0002218871970022357
train_loss: 0.00020502480643029374, val_loss: 0.0007299759461256187
epochs 102/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0001982403762093255, val_loss: 0.0007294709948981773
epochs 103/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.00014359028443179436, val_loss: 0.0007177899087620307
epochs 104/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0001642378174246436, val_loss: 0.00070570348664963
epochs 105/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.00015550592001282464, val_loss: 0.0007008698986961492
epochs 106/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0001824509359338615, val_loss: 0.0007046499360714935
epochs 107/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.00020675661454381617, val_loss: 0.0007082281143604112
epochs 108/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.00014570110851261567, val_loss: 0.0007077432484717094
epochs 109/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.00018415292426269796, val_loss: 0.0006978338550118404
epochs 110/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.00016049443166641714, val_loss: 0.0006910548626264143
epochs 111/148
Epoch 00111: reducing learning rate of group 0 to 1.6291e-04.
Current Learning Rate: 0.00016290609704241494
train_loss: 0.0001511260122673488, val_loss: 0.0006908363337436366
epochs 112/148
Current Learning Rate: 0.00016290609704241494
train_loss: 0.0001652697389210133, val_loss: 0.0006904679774177364
epochs 113/148
Current Learning Rate: 0.00016290609704241494
train_loss: 0.0001812960361253078, val_loss: 0.0006921528702295046
epochs 114/148
Current Learning Rate: 0.00016290609704241494
train_loss: 0.00015682581724831834, val_loss: 0.0006982956690499411
epochs 115/148
Current Learning Rate: 0.00016290609704241494
train_loss: 0.00017076625969677576, val_loss: 0.0007019780251929271
epochs 116/148
Current Learning Rate: 0.00016290609704241494
train_loss: 0.00015977504379789982, val_loss: 0.0006957788058253567
epochs 117/148
Current Learning Rate: 0.00016290609704241494
train_loss: 0.00014547902330952256, val_loss: 0.0006991762987574533
epochs 118/148
Current Learning Rate: 0.00016290609704241494
train_loss: 0.0001644565292640197, val_loss: 0.0007053694587537191
epochs 119/148
Current Learning Rate: 0.00016290609704241494
train_loss: 0.00015213325532386078, val_loss: 0.0007090822438753786
epochs 120/148
Current Learning Rate: 0.00016290609704241494
train_loss: 0.0001571171742781237, val_loss: 0.0007126957542144708
epochs 121/148
Epoch 00121: reducing learning rate of group 0 to 1.1960e-04.
Current Learning Rate: 0.000119603099287091
train_loss: 0.00017521461976636936, val_loss: 0.0007071104284102422
epochs 122/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00017945157451322303, val_loss: 0.0006953346395647035
epochs 123/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00015604682220758773, val_loss: 0.0006853473522434277
epochs 124/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.0001877659656824299, val_loss: 0.0006771267198639671
epochs 125/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00016925127703488167, val_loss: 0.0006729111381222508
epochs 126/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00017074703286389673, val_loss: 0.0006710904017959293
epochs 127/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00015882402964818634, val_loss: 0.0006760628796958675
epochs 128/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00017149307463305854, val_loss: 0.0006796514563676384
epochs 129/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00014965142089701992, val_loss: 0.0006863725108800396
epochs 130/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00016602544109398302, val_loss: 0.0006965419401355561
epochs 131/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.000151121033597615, val_loss: 0.0007050263158152885
epochs 132/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00015370965327172982, val_loss: 0.0007119842916764024
epochs 133/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00015865372632489246, val_loss: 0.0007139999017078755
epochs 134/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.00016000927598246276, val_loss: 0.0007125506020938268
epochs 135/148
Current Learning Rate: 0.000119603099287091
train_loss: 0.0001657783760732089, val_loss: 0.0007058829771325229
epochs 136/148
Epoch 00136: reducing learning rate of group 0 to 8.7811e-05.
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.00016185908209177127, val_loss: 0.0007009383654572987
epochs 137/148
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.00016274278482581537, val_loss: 0.00069925060753511
epochs 138/148
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.0001643229257560482, val_loss: 0.000698997180618804
epochs 139/148
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.00017027772984491956, val_loss: 0.000694679518115692
epochs 140/148
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.00015264372701303248, val_loss: 0.0006907260791945552
epochs 141/148
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.00016060397231883959, val_loss: 0.0006863775465356571
epochs 142/148
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.00016406351339690828, val_loss: 0.0006847494978934438
epochs 143/148
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.00014939921399529434, val_loss: 0.0006834699318186188
epochs 144/148
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.00017343768160667662, val_loss: 0.0006834948446974898
epochs 145/148
Current Learning Rate: 8.781071806878573e-05
train_loss: 0.0001562062109434536, val_loss: 0.0006821645931470104
epochs 146/148
Epoch 00146: reducing learning rate of group 0 to 6.4469e-05.
Current Learning Rate: 6.446925082808458e-05
train_loss: 0.00017268679473904502, val_loss: 0.0006814306176411698
epochs 147/148
Current Learning Rate: 6.446925082808458e-05
train_loss: 0.00017093459908593153, val_loss: 0.0006795915999516312
epochs 148/148
Current Learning Rate: 6.446925082808458e-05
train_loss: 0.0001464299692184125, val_loss: 0.0006818914797992282
Starting fold 2:
epochs 1/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.005153443747669112, val_loss: 0.03725711986540802
epochs 2/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0008560937598481587, val_loss: 0.0075829791086208485
epochs 3/148

[I 2024-01-30 14:48:06,281] Trial 10 finished with value: 0.0032413798090183757 and parameters: {'batch_size': 123, 'epochs': 148, 'hidden_size': 99, 'learning_rate': 0.0019297301389046295, 'dropout_prob': 0.07570182866427809, 'weight_decay': 9.161691434506323e-05, 'lr_step_size': 9, 'gamma': 0.7341843028499456, 'num_layers': 3}. Best is trial 10 with value: 0.0032413798090183757.

Current Learning Rate: 6.446925082808458e-05
train_loss: 0.0009035663593715021, val_loss: 0.001476918894147116
Mean validation loss: 0.0032413798090183757
Starting fold 1:
epochs 1/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.04217313573156532, val_loss: 0.0021706110583470453
epochs 2/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0016517615677960414, val_loss: 0.014797751057557958
epochs 3/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.008775253495274993, val_loss: 0.0073962241088449164
epochs 4/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.004352523295797016, val_loss: 0.00148835773462745
epochs 5/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0022421328406045703, val_loss: 0.0012382228055564815
epochs 6/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0020670109600024788, val_loss: 0.0016058651395031206
epochs 7/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0010078527204888431, val_loss: 0.003960681752740312
epochs 8/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.001777597938933851, val_loss: 0.005060226671279423
epochs 9/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.002679798810277134, val_loss: 0.0033462954181241534
epochs 10/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0015688285148874122, val_loss: 0.0014883383465487334
epochs 11/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0009802621467602684, val_loss: 0.0009150708307667325
epochs 12/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0008481921058295196, val_loss: 0.0008850609517173359
epochs 13/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0005122149121138806, val_loss: 0.0012522988930213999
epochs 14/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0004346894845519656, val_loss: 0.0018821722669551573
epochs 15/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.000569313200876901, val_loss: 0.0016176395283620214
epochs 16/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.00047230055803849707, val_loss: 0.00082327796838606
epochs 17/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.00030303676382908106, val_loss: 0.0006359915534544381
epochs 18/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.00041765314381336793, val_loss: 0.0007345674152328342
epochs 19/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0003614974212771478, val_loss: 0.0010154038215260557
epochs 20/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0003209279583595497, val_loss: 0.0008596640735280714
epochs 21/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0003246585738930949, val_loss: 0.0006947170988602377
epochs 22/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0002858246233173352, val_loss: 0.0007272262268492745
epochs 23/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0002887952593339019, val_loss: 0.0009616957650958466
epochs 24/147
Current Learning Rate: 0.0026788492203108976
train_loss: 0.0003685169695496657, val_loss: 0.0010830468591179442
epochs 25/147
Epoch 00025: reducing learning rate of group 0 to 1.9265e-03.
Current Learning Rate: 0.0019265027893348029
train_loss: 0.00028127837944530735, val_loss: 0.0010728732479191704
epochs 26/147
Current Learning Rate: 0.0019265027893348029
train_loss: 0.0002895098403218742, val_loss: 0.000980305163899348
epochs 27/147
Current Learning Rate: 0.0019265027893348029
train_loss: 0.00029862286579660386, val_loss: 0.0008991059853181628
epochs 28/147
Current Learning Rate: 0.0019265027893348029
train_loss: 0.00026640302377544636, val_loss: 0.0008584344911262167
epochs 29/147
Current Learning Rate: 0.0019265027893348029
train_loss: 0.00024414787836385106, val_loss: 0.000913808116425696
epochs 30/147
Current Learning Rate: 0.0019265027893348029
train_loss: 0.00023374510055873543, val_loss: 0.0009761728652323
epochs 31/147
Current Learning Rate: 0.0019265027893348029
train_loss: 0.00023520195176579843, val_loss: 0.0010416895658068516
epochs 32/147

[I 2024-01-30 14:48:09,852] Trial 11 pruned.

Starting fold 1:
epochs 1/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.031033035597494363, val_loss: 0.004028554703971302
epochs 2/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.007768039188445791, val_loss: 0.0038392670032514073
epochs 3/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.003636119776944581, val_loss: 0.002943920181009662
epochs 4/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0016614016366044157, val_loss: 0.009011220374198818
epochs 5/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.005279411648179551, val_loss: 0.008224415484441337
epochs 6/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.004434056796966807, val_loss: 0.004034340008970094
epochs 7/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0018633015158181815, val_loss: 0.0014197913450607785
epochs 8/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0011166196037696577, val_loss: 0.001088915546744983
epochs 9/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0014984830310200586, val_loss: 0.0011418772271277492
epochs 10/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0012232086489491754, val_loss: 0.0010153969664190693
epochs 11/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0006767424151276876, val_loss: 0.0015407363094497846
epochs 12/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0007213592740682591, val_loss: 0.0024130076918967816
epochs 13/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0010719125433273516, val_loss: 0.0026028162310708057
epochs 14/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0012041485453281847, val_loss: 0.0019621094011223663
epochs 15/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0008286035979644542, val_loss: 0.0011959347902260051
epochs 16/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0005183793353161921, val_loss: 0.0009007248734912427
epochs 17/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0006111132795922458, val_loss: 0.0008688987979281043
epochs 18/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0005276153096929193, val_loss: 0.0009098683392121482
epochs 19/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003447896175968804, val_loss: 0.0010986908758736694
epochs 20/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00040331745694857093, val_loss: 0.0012863516558402725
epochs 21/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00047422479164149414, val_loss: 0.0012348565060790707
epochs 22/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00043276572633706227, val_loss: 0.0010107587043580318
epochs 23/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00028094164820351196, val_loss: 0.0008645149706382422
epochs 24/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003820598436409215, val_loss: 0.0008181877196803394
epochs 25/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003827373095861587, val_loss: 0.0008407228593357281
epochs 26/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00035093833468731884, val_loss: 0.000927956133930594
epochs 27/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002466685517758474, val_loss: 0.0010286303125900862
epochs 28/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003685743204857174, val_loss: 0.0010097986860225401
epochs 29/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002929590325373666, val_loss: 0.0009199093107045407
epochs 30/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00031770305167332194, val_loss: 0.0008702253813180264
epochs 31/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00030477564486270574, val_loss: 0.0009145642340949505
epochs 32/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002921799245278204, val_loss: 0.0010302516292391354
epochs 33/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00025992169991552244, val_loss: 0.0011278995380197311
epochs 34/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003646838651835232, val_loss: 0.001022768896301006
epochs 35/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00031324327788560797, val_loss: 0.0008437269311533778
epochs 36/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00027083879057930685, val_loss: 0.0007578015588310167
epochs 37/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002822571276307204, val_loss: 0.0007734329362089435
epochs 38/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002754469893835975, val_loss: 0.0008713363116377935
epochs 39/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002748600358149576, val_loss: 0.0009845825906648305
epochs 40/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002831578777036875, val_loss: 0.0009983349254258746
epochs 41/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00025916504405598206, val_loss: 0.0008847178963983737
epochs 42/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.000253203577640785, val_loss: 0.000801515260097822
epochs 43/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00021718607313232497, val_loss: 0.0007902838740308114
epochs 44/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00027460049336935444, val_loss: 0.0008917527501816275
epochs 45/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00026687240660019023, val_loss: 0.0009612107429857903
epochs 46/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002956323162499374, val_loss: 0.000854258939701443
epochs 47/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002508496398437082, val_loss: 0.0007538539135739917
epochs 48/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002694122656401688, val_loss: 0.0007512928755084181
epochs 49/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002507802378539437, val_loss: 0.0008799803331457374
epochs 50/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00021959971023821517, val_loss: 0.000971374309975309
epochs 51/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019484865325993222, val_loss: 0.0009223631955498445
epochs 52/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00026905196473786704, val_loss: 0.0007761195605366968
epochs 53/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00022896438213616707, val_loss: 0.0007345390579387269
epochs 54/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002105883599142544, val_loss: 0.0007893707313409775
epochs 55/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00021235115326769454, val_loss: 0.0008679556722873477
epochs 56/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00023230544450741848, val_loss: 0.0008583237873926197
epochs 57/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00023544726404667782, val_loss: 0.0008182817764848805
epochs 58/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002215698404286645, val_loss: 0.0008188841730342666
epochs 59/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00021606426399605545, val_loss: 0.000828576271829353
epochs 60/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00021225435622526626, val_loss: 0.0008201835966988087
epochs 61/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00023436061624364045, val_loss: 0.0007947893662651676
epochs 62/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002459806816707561, val_loss: 0.0008287442625264967
epochs 63/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00023546619746699242, val_loss: 0.0008409749901306534
epochs 64/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018750083997330972, val_loss: 0.0008264608037837894
epochs 65/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019754639659750912, val_loss: 0.0007628773411621325
epochs 66/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00020988135197273406, val_loss: 0.0007562063307631958
epochs 67/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00023221961286923798, val_loss: 0.0008239519344113038
epochs 68/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019925728617971273, val_loss: 0.0008600487340045797
epochs 69/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017818357250928927, val_loss: 0.0008645754189091296
epochs 70/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017018783531200728, val_loss: 0.0007739247492127731
epochs 71/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002064847015916664, val_loss: 0.0007354248709768481
epochs 72/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00022558880675780147, val_loss: 0.0007916171342090127
epochs 73/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00021085677152242216, val_loss: 0.0008228338120576665
epochs 74/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002117752060018431, val_loss: 0.0008263234741260204
epochs 75/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002222902137681989, val_loss: 0.0007783590379249915
epochs 76/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002187471358889812, val_loss: 0.0007419272845028284
epochs 77/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002455099724772337, val_loss: 0.000806184450060341
epochs 78/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018845078662515764, val_loss: 0.0008402660031120475
epochs 79/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017681726622916023, val_loss: 0.0008095454437092745
epochs 80/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019884190601021003, val_loss: 0.00072784687065342
epochs 81/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001950463575715395, val_loss: 0.0007402280291817126
epochs 82/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019713120931747223, val_loss: 0.0008798852455420371
epochs 83/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00025129068710253035, val_loss: 0.0008286971048508628
epochs 84/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00020249347128954373, val_loss: 0.0007708231618544136
epochs 85/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018774388721028932, val_loss: 0.0007876247122468644
epochs 86/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017692992328911236, val_loss: 0.0007800743761152108
epochs 87/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019327366347792315, val_loss: 0.0007662515878331202
epochs 88/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017812536274217756, val_loss: 0.0007348625073622094
epochs 89/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017382148025238788, val_loss: 0.0007701312075831026
epochs 90/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017775050689938085, val_loss: 0.0008204751959835578
epochs 91/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018795326621712824, val_loss: 0.0008023934781141136
epochs 92/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018463026989545478, val_loss: 0.0007991912051303578
epochs 93/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00022239699304152868, val_loss: 0.0007826926553327462
epochs 94/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018313393865307596, val_loss: 0.0007841675239707535
epochs 95/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018033751058330955, val_loss: 0.0008288187844242664
epochs 96/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019980191274570594, val_loss: 0.0008775848399006353
epochs 97/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00020130422375299722, val_loss: 0.0007708279962470341
epochs 98/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00016867187698249166, val_loss: 0.0007429924749192738
epochs 99/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018605421340142035, val_loss: 0.0008224653329259209
epochs 100/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001976967266512618, val_loss: 0.0008553660969944701
epochs 101/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00020565650844027436, val_loss: 0.0008063059561656758
epochs 102/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018324184761456166, val_loss: 0.0007538264744364405
epochs 103/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018109521027470595, val_loss: 0.000759026134450102
epochs 104/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00016692363500815668, val_loss: 0.000761919815130852
epochs 105/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019142944143631641, val_loss: 0.0007795678783810534
epochs 106/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001865568844215503, val_loss: 0.0007721365689855592
epochs 107/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00016227044459236296, val_loss: 0.0007359802605283678
epochs 108/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017310381862396178, val_loss: 0.0007917701719278253
epochs 109/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017189900896291395, val_loss: 0.0008491412898163415
epochs 110/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001656258333241567, val_loss: 0.000798154938762771
epochs 111/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00016403884901113711, val_loss: 0.0007324176530967215
epochs 112/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019841354032426974, val_loss: 0.0007408405076675412
epochs 113/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001904123452780033, val_loss: 0.0008240705088061827
epochs 114/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017812252098290052, val_loss: 0.0008322072714147103
epochs 115/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019646113540052045, val_loss: 0.000682906149584731
epochs 116/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00018172955246164316, val_loss: 0.0006914173439822637
epochs 117/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001574009139164302, val_loss: 0.0009172069918667335
epochs 118/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001791569950383794, val_loss: 0.0008901195560899814
epochs 119/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00023378208241315167, val_loss: 0.000703044154015419
epochs 120/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00019550382636034078, val_loss: 0.0006979317969467648
epochs 121/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001773786372627671, val_loss: 0.0008861272445376026
epochs 122/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00020617461858292747, val_loss: 0.0008252120625921254
epochs 123/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017855993493484627, val_loss: 0.0006983441594192295
epochs 124/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001766820555770353, val_loss: 0.0007237152739430448
epochs 125/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00015771812468301505, val_loss: 0.0008500250382533682
epochs 126/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00020543174219997846, val_loss: 0.0008085831456507245
epochs 127/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.000213108513516521, val_loss: 0.0007227440707283292
epochs 128/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017625391728391774, val_loss: 0.0007247317379257992
epochs 129/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00016843234380327262, val_loss: 0.0007221609640129837
epochs 130/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001525709912560782, val_loss: 0.0007400283799075556
epochs 131/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00017799633523712767, val_loss: 0.0007316377224886011
epochs 132/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0001707975372770115, val_loss: 0.0007775782167242603
Starting fold 2:
epochs 1/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00259769563140049, val_loss: 0.035399960827023264
epochs 2/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0015890715933419607, val_loss: 0.021610252721796907
epochs 3/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0006676454229957957, val_loss: 0.013701247167157591
epochs 4/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0011068531745150293, val_loss: 0.025741859038592017
epochs 5/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0008707238365040593, val_loss: 0.02715498694864215
epochs 6/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00046306210798874873, val_loss: 0.01734103644316001
epochs 7/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0006053964115954484, val_loss: 0.015392464496904896
epochs 8/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0006554036847829308, val_loss: 0.020756669298169158
epochs 9/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0005368860393159318, val_loss: 0.0195548682123738
epochs 10/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003253602218355905, val_loss: 0.013755593591778682
epochs 11/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0004389134654498814, val_loss: 0.013341214409265568
epochs 12/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0004700526326653943, val_loss: 0.01655260651130919
epochs 13/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0004291731292043387, val_loss: 0.013935079684766828
epochs 14/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003194073285006901, val_loss: 0.011145133830646359
epochs 15/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0004628624531009178, val_loss: 0.013870293311479072
epochs 16/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.000341201603735458, val_loss: 0.013703429874367816
epochs 17/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.000307213129859054, val_loss: 0.01119543672120445
epochs 18/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003708613642348876, val_loss: 0.012092097807754443
epochs 19/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00039739669806669196, val_loss: 0.012481013381922687
epochs 20/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0002985997676098655, val_loss: 0.010564867907238228
epochs 21/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00036871189146799017, val_loss: 0.01141787526350488
epochs 22/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003173221490901249, val_loss: 0.011411736536987875
epochs 23/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00028784085888480695, val_loss: 0.009911301983126179
epochs 24/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003406514080688554, val_loss: 0.01032252878532129
epochs 25/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.00034192705752406674, val_loss: 0.010766404932216993
epochs 26/132
Current Learning Rate: 0.0011428573811287886
train_loss: 0.0003242522827042439, val_loss: 0.009500586162887948
epochs 27/132

[I 2024-01-30 14:48:46,396] Trial 12 pruned.

Starting fold 1:
epochs 1/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.11341047997120768, val_loss: 0.7914802551900268
epochs 2/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.6505929827690125, val_loss: 7.650864848384151
epochs 3/106
Current Learning Rate: 0.07596027857602791
train_loss: 4.5358394384384155, val_loss: 0.03422608476861444
epochs 4/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.03513307683169842, val_loss: 0.015682605026220833
epochs 5/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.021201190538704395, val_loss: 0.0065466477289283405
epochs 6/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.019542154856026173, val_loss: 0.0015018108168742546
epochs 7/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.02400822751224041, val_loss: 0.018317863261376424
epochs 8/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.048631103709340096, val_loss: 0.004983024486271596
epochs 9/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.03328466787934303, val_loss: 0.0021409377292175556
epochs 10/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.043463973328471184, val_loss: 0.005255734333004704
epochs 11/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.04203278198838234, val_loss: 0.006399548036001977
epochs 12/106
Current Learning Rate: 0.07596027857602791
train_loss: 0.04848012886941433, val_loss: 0.003470397174910263
epochs 13/106
Epoch 00013: reducing learning rate of group 0 to 2.9046e-02.
Current Learning Rate: 0.02904585803038609
train_loss: 0.05760258436203003, val_loss: 0.008476919331957423
epochs 14/106
Current Learning Rate: 0.02904585803038609
train_loss: 0.05223029851913452, val_loss: 0.003514561897313725
epochs 15/106
Current Learning Rate: 0.02904585803038609
train_loss: 0.04544435255229473, val_loss: 0.0016510416507208474
epochs 16/106
Current Learning Rate: 0.02904585803038609
train_loss: 0.05181142874062061, val_loss: 0.0037505777217644864
epochs 17/106
Current Learning Rate: 0.02904585803038609
train_loss: 0.050267286598682404, val_loss: 0.0015732209344773932
epochs 18/106
Current Learning Rate: 0.02904585803038609
train_loss: 0.04288213141262531, val_loss: 0.002651032480311447
epochs 19/106
Current Learning Rate: 0.02904585803038609
train_loss: 0.041902437806129456, val_loss: 0.004926591414327501
epochs 20/106
Epoch 00020: reducing learning rate of group 0 to 1.1107e-02.
Current Learning Rate: 0.011106618940015222
train_loss: 0.04995922930538654, val_loss: 0.003931255272599479
epochs 21/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.04365408234298229, val_loss: 0.0026446004344579128
epochs 22/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.051208678632974625, val_loss: 0.0016911371440747407
epochs 23/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.03989921323955059, val_loss: 0.0014081524309909178
epochs 24/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.04880436696112156, val_loss: 0.001418842620551389
epochs 25/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.051414189860224724, val_loss: 0.001486384696647446
epochs 26/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.04207738861441612, val_loss: 0.001486521531463103
epochs 27/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.045015692710876465, val_loss: 0.0014033887957878135
epochs 28/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.046977629885077477, val_loss: 0.0017007529763591097
epochs 29/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.0462355837225914, val_loss: 0.002441958819482742
epochs 30/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.043228620663285255, val_loss: 0.002957683894598472
epochs 31/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.046152688562870026, val_loss: 0.002620422741750541
epochs 32/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.04396052099764347, val_loss: 0.0020627449759375795
epochs 33/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.03946910426020622, val_loss: 0.0015738330410039495
epochs 34/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.04440349154174328, val_loss: 0.001399345404010207
epochs 35/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.03799486346542835, val_loss: 0.0014388282301653393
epochs 36/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.0430737379938364, val_loss: 0.0014930126403837844
epochs 37/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.04731649346649647, val_loss: 0.0014263663998997165
epochs 38/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.048724401742219925, val_loss: 0.0014690209300843653
epochs 39/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.041505374014377594, val_loss: 0.002145316077441854
epochs 40/106
Current Learning Rate: 0.011106618940015222
train_loss: 0.03879706189036369, val_loss: 0.002973107167115563
epochs 41/106
Epoch 00041: reducing learning rate of group 0 to 4.2470e-03.
Current Learning Rate: 0.004246973325754603
train_loss: 0.054885009303689, val_loss: 0.00302540132450679
epochs 42/106
Current Learning Rate: 0.004246973325754603
train_loss: 0.03864777088165283, val_loss: 0.0028617694738651157
epochs 43/106
Current Learning Rate: 0.004246973325754603
train_loss: 0.040644342079758644, val_loss: 0.0024775656044271296
epochs 44/106
Current Learning Rate: 0.004246973325754603
train_loss: 0.04418563283979893, val_loss: 0.0021109414393471544
epochs 45/106
Current Learning Rate: 0.004246973325754603
train_loss: 0.035902123898267746, val_loss: 0.001822387161030232
epochs 46/106
Current Learning Rate: 0.004246973325754603
train_loss: 0.03195363562554121, val_loss: 0.0016584456950628134
epochs 47/106
Current Learning Rate: 0.004246973325754603
train_loss: 0.04302171804010868, val_loss: 0.0015808768641565824
epochs 48/106
Epoch 00048: reducing learning rate of group 0 to 1.6240e-03.
Current Learning Rate: 0.001623966981048365
train_loss: 0.029306070879101753, val_loss: 0.0016052980773907312
epochs 49/106
Current Learning Rate: 0.001623966981048365
train_loss: 0.03675290383398533, val_loss: 0.0016083597823381226
epochs 50/106
Current Learning Rate: 0.001623966981048365
train_loss: 0.045752132311463356, val_loss: 0.0016078526927490852
epochs 51/106
Current Learning Rate: 0.001623966981048365
train_loss: 0.037063224241137505, val_loss: 0.0016290795088193758
epochs 52/106
Current Learning Rate: 0.001623966981048365
train_loss: 0.03158371150493622, val_loss: 0.0017095318158950519
epochs 53/106
Current Learning Rate: 0.001623966981048365
train_loss: 0.037761783227324486, val_loss: 0.0018022318488287508
epochs 54/106
Current Learning Rate: 0.001623966981048365
train_loss: 0.03898295760154724, val_loss: 0.0018574913380674958
epochs 55/106
Epoch 00055: reducing learning rate of group 0 to 6.2098e-04.
Current Learning Rate: 0.0006209760583007078
train_loss: 0.03980359248816967, val_loss: 0.0019288629058763266
epochs 56/106
Current Learning Rate: 0.0006209760583007078
train_loss: 0.03819588012993336, val_loss: 0.0019430427860700225
epochs 57/106
Current Learning Rate: 0.0006209760583007078
train_loss: 0.037495093420147896, val_loss: 0.0019494027537466198
epochs 58/106
Current Learning Rate: 0.0006209760583007078
train_loss: 0.037538764998316765, val_loss: 0.0019460807536869117
epochs 59/106
Current Learning Rate: 0.0006209760583007078
train_loss: 0.04215044155716896, val_loss: 0.0019348447596674006
epochs 60/106
Current Learning Rate: 0.0006209760583007078
train_loss: 0.039269233122467995, val_loss: 0.0019160278902817813
epochs 61/106
Current Learning Rate: 0.0006209760583007078
train_loss: 0.041256070137023926, val_loss: 0.0018899281630563554
epochs 62/106
Epoch 00062: reducing learning rate of group 0 to 2.3745e-04.
Current Learning Rate: 0.00023745018801659963
train_loss: 0.038040872663259506, val_loss: 0.0018648934121263366
epochs 63/106
Current Learning Rate: 0.00023745018801659963
train_loss: 0.039034636691212654, val_loss: 0.0018578256813318976
epochs 64/106
Current Learning Rate: 0.00023745018801659963
train_loss: 0.03471661824733019, val_loss: 0.0018477720606064414
epochs 65/106
Current Learning Rate: 0.00023745018801659963
train_loss: 0.04172211792320013, val_loss: 0.0018437979347134138
epochs 66/106
Current Learning Rate: 0.00023745018801659963
train_loss: 0.036553531885147095, val_loss: 0.001845189817397604
epochs 67/106
Current Learning Rate: 0.00023745018801659963
train_loss: 0.03946182131767273, val_loss: 0.0018455188277315487
epochs 68/106
Current Learning Rate: 0.00023745018801659963
train_loss: 0.03419058956205845, val_loss: 0.0018455990552889903
epochs 69/106
Epoch 00069: reducing learning rate of group 0 to 9.0797e-05.
Current Learning Rate: 9.079672402090458e-05
train_loss: 0.03992261551320553, val_loss: 0.0018420305579504067
epochs 70/106
Current Learning Rate: 9.079672402090458e-05
train_loss: 0.043920714408159256, val_loss: 0.0018398322031966277
epochs 71/106
Current Learning Rate: 9.079672402090458e-05
train_loss: 0.03370683081448078, val_loss: 0.0018364556325308821
epochs 72/106
Current Learning Rate: 9.079672402090458e-05
train_loss: 0.041014447808265686, val_loss: 0.001831246916298316
epochs 73/106
Current Learning Rate: 9.079672402090458e-05
train_loss: 0.04083957150578499, val_loss: 0.0018296668594875545
epochs 74/106
Current Learning Rate: 9.079672402090458e-05
train_loss: 0.03990566544234753, val_loss: 0.0018282899036806413
epochs 75/106
Current Learning Rate: 9.079672402090458e-05
train_loss: 0.035390716046094894, val_loss: 0.0018252025094442563
epochs 76/106
Epoch 00076: reducing learning rate of group 0 to 3.4719e-05.
Current Learning Rate: 3.471905060084428e-05
train_loss: 0.03762149251997471, val_loss: 0.0018205628493214371
epochs 77/106
Current Learning Rate: 3.471905060084428e-05
train_loss: 0.032110294327139854, val_loss: 0.001819162990801805
epochs 78/106
Current Learning Rate: 3.471905060084428e-05
train_loss: 0.03793901950120926, val_loss: 0.0018181092247167335
epochs 79/106
Current Learning Rate: 3.471905060084428e-05
train_loss: 0.040939949452877045, val_loss: 0.0018170318178519626
epochs 80/106
Current Learning Rate: 3.471905060084428e-05
train_loss: 0.03505384549498558, val_loss: 0.0018165775082904412
epochs 81/106
Current Learning Rate: 3.471905060084428e-05
train_loss: 0.039110805839300156, val_loss: 0.0018159652873504138
epochs 82/106
Current Learning Rate: 3.471905060084428e-05
train_loss: 0.036591824144124985, val_loss: 0.0018151648928997693
epochs 83/106
Epoch 00083: reducing learning rate of group 0 to 1.3276e-05.
Current Learning Rate: 1.3275946765947827e-05
train_loss: 0.039990052580833435, val_loss: 0.0018137238122690371
epochs 84/106
Current Learning Rate: 1.3275946765947827e-05
train_loss: 0.04149790294468403, val_loss: 0.0018133321689520643
epochs 85/106
Current Learning Rate: 1.3275946765947827e-05
train_loss: 0.03295751381665468, val_loss: 0.001812793106726425
epochs 86/106
Current Learning Rate: 1.3275946765947827e-05
train_loss: 0.034378630109131336, val_loss: 0.0018126801918716558
epochs 87/106
Current Learning Rate: 1.3275946765947827e-05
train_loss: 0.03754524514079094, val_loss: 0.0018127284831337867
epochs 88/106
Current Learning Rate: 1.3275946765947827e-05
train_loss: 0.02824963629245758, val_loss: 0.0018128361529855441
epochs 89/106
Current Learning Rate: 1.3275946765947827e-05
train_loss: 0.03551278542727232, val_loss: 0.0018126462303193177
epochs 90/106
Epoch 00090: reducing learning rate of group 0 to 5.0765e-06.
Current Learning Rate: 5.076485660814544e-06
train_loss: 0.03486470691859722, val_loss: 0.0018127432943656843
epochs 91/106
Current Learning Rate: 5.076485660814544e-06
train_loss: 0.03777852561324835, val_loss: 0.0018127565355306225
epochs 92/106

[I 2024-01-30 14:48:54,199] Trial 13 pruned.

Starting fold 1:
epochs 1/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.011973645849349467, val_loss: 0.007135379571645032
epochs 2/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.005119603701965197, val_loss: 0.0021175397892615627
epochs 3/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.003131325748798094, val_loss: 0.0012039857976281494
epochs 4/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0035676113918031516, val_loss: 0.0012630900711796823
epochs 5/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0036335862082380213, val_loss: 0.0012075789953414448
epochs 6/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0028363057326427415, val_loss: 0.0013723062748944377
epochs 7/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0026384201881132626, val_loss: 0.0019845826421659835
epochs 8/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.002466440312319288, val_loss: 0.002808195516336512
epochs 9/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.002305121141436853, val_loss: 0.003503740642271522
epochs 10/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0029831045105023998, val_loss: 0.0037604565695223825
epochs 11/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0031482337630893056, val_loss: 0.003518983492906151
epochs 12/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0030191340214131696, val_loss: 0.0030022041832722685
epochs 13/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0025113005031782544, val_loss: 0.0024176322295769025
epochs 14/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0025878061209560223, val_loss: 0.0020318836942019446
epochs 15/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0020115816242698777, val_loss: 0.0018202488795082976
epochs 16/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.002104706537762755, val_loss: 0.001731977268786135
epochs 17/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0021342206292932755, val_loss: 0.00176484382415077
epochs 18/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.002563493996613512, val_loss: 0.0018603325132822627
epochs 19/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0020356548729499706, val_loss: 0.002007637236380664
epochs 20/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0023534383532885267, val_loss: 0.002143589816537868
epochs 21/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0022971650046345435, val_loss: 0.0022666397145407265
epochs 22/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0021167183760553597, val_loss: 0.0023477797248036103
epochs 23/128
Current Learning Rate: 0.0005717372517781901
train_loss: 0.0020244207698851824, val_loss: 0.0024075439352561874
epochs 24/128
Epoch 00024: reducing learning rate of group 0 to 4.0815e-04.
Current Learning Rate: 0.0004081456369850728
train_loss: 0.0022253905882519717, val_loss: 0.0023683860524441732
epochs 25/128
Current Learning Rate: 0.0004081456369850728
train_loss: 0.0021373489019951147, val_loss: 0.0023086444552058954
epochs 26/128
Current Learning Rate: 0.0004081456369850728
train_loss: 0.002066949466978641, val_loss: 0.0022168246653145327
epochs 27/128
Current Learning Rate: 0.0004081456369850728
train_loss: 0.002251131103472098, val_loss: 0.0021439535913202992
epochs 28/128
Current Learning Rate: 0.0004081456369850728
train_loss: 0.00198857487534712, val_loss: 0.0021350031674571
epochs 29/128
Current Learning Rate: 0.0004081456369850728
train_loss: 0.0017622000948329898, val_loss: 0.002151163461680953
epochs 30/128
Current Learning Rate: 0.0004081456369850728
train_loss: 0.0023314657351492267, val_loss: 0.0021549593530984586
epochs 31/128

[I 2024-01-30 14:48:57,347] Trial 14 pruned.

Current Learning Rate: 0.0004081456369850728
train_loss: 0.002145533509380919, val_loss: 0.002161597366144181
epochs 32/128
Starting fold 1:
epochs 1/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.12180568232985312, val_loss: 0.0013957680372407946
epochs 2/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0024078616296480363, val_loss: 0.00705850958484151
epochs 3/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.004267894266491854, val_loss: 0.0012030551048665843
epochs 4/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.001599486644600371, val_loss: 0.004607545168794415
epochs 5/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0019511328320827726, val_loss: 0.0012498162192521645
epochs 6/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0011920488261813788, val_loss: 0.0038869064067189813
epochs 7/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0013074037857892873, val_loss: 0.0009343232063295704
epochs 8/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0010492777709211957, val_loss: 0.0010611072846961813
epochs 9/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0006170238562749307, val_loss: 0.00198834263200677
epochs 10/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0005360135116222266, val_loss: 0.0006011751333033548
epochs 11/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00047388362091671873, val_loss: 0.0007434947231092131
epochs 12/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.000319754608177678, val_loss: 0.0010888036672705315
epochs 13/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00033879528453230464, val_loss: 0.000502205091401092
epochs 14/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00035302839938882054, val_loss: 0.0006189050324441047
epochs 15/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0002699051936169302, val_loss: 0.0009690371542419406
epochs 16/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00022942473480821047, val_loss: 0.0005195608719654884
epochs 17/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0003049572442633737, val_loss: 0.000627658686849471
epochs 18/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0002723128127399832, val_loss: 0.0009298670929012742
epochs 19/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0002281814900925383, val_loss: 0.0004661214756120302
epochs 20/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00022654591172651732, val_loss: 0.0005779033002447307
epochs 21/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00022178214911898402, val_loss: 0.0007650781142671356
epochs 22/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00017917137409217263, val_loss: 0.0004938559604515494
epochs 23/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00019944018307509588, val_loss: 0.0006931523276045155
epochs 24/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.000188122699450775, val_loss: 0.000552072547386627
epochs 25/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001881586844989981, val_loss: 0.0005510279915859755
epochs 26/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00017472832152730245, val_loss: 0.000538349185565797
epochs 27/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00017840824485143746, val_loss: 0.0004622343105785105
epochs 28/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00018010216414327977, val_loss: 0.0005935325937729979
epochs 29/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00019243150041132283, val_loss: 0.0004560996251822592
epochs 30/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00015890719935812643, val_loss: 0.0005977093667117139
epochs 31/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00017188228107682478, val_loss: 0.0006460629145429401
epochs 32/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00016638008612636967, val_loss: 0.0004720347329066258
epochs 33/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00019719656457278976, val_loss: 0.00047059570024622773
epochs 34/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001511983667641241, val_loss: 0.0005645269791967674
epochs 35/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00015966208869174712, val_loss: 0.00055389784108022
epochs 36/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00017097030450761514, val_loss: 0.0005765806482587424
epochs 37/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00018692051801879548, val_loss: 0.0006028598889113507
epochs 38/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001604732058599199, val_loss: 0.00041002630476012
epochs 39/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001598811976452309, val_loss: 0.0005797230241350244
epochs 40/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001560065188402261, val_loss: 0.000443344704561039
epochs 41/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00016394865080273074, val_loss: 0.0006795311551069885
epochs 42/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001647964253941992, val_loss: 0.00048776576580373794
epochs 43/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014058572813059744, val_loss: 0.0006593627573459695
epochs 44/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00015848302297710785, val_loss: 0.00044558667956614894
epochs 45/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001562333299692622, val_loss: 0.0006653708219081631
epochs 46/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014702742329590317, val_loss: 0.0004882870947883006
epochs 47/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001493358202998551, val_loss: 0.0005609363286845909
epochs 48/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014760289080808625, val_loss: 0.0004970304439738688
epochs 49/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014457295405200535, val_loss: 0.0005161560132234756
epochs 50/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001596229256201217, val_loss: 0.0006334986880704362
epochs 51/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00013494489838577513, val_loss: 0.0006087105017892706
epochs 52/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00015438092002449067, val_loss: 0.0004292634306857412
epochs 53/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00016145112519887718, val_loss: 0.0004543443856404838
epochs 54/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014566220695422472, val_loss: 0.0006970898025356869
epochs 55/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00017541635223958444, val_loss: 0.00046469130368210945
epochs 56/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014755159251140674, val_loss: 0.00057566462983328
epochs 57/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00011660046262764617, val_loss: 0.0004758397976513065
epochs 58/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00012721165759629863, val_loss: 0.0005419005276592172
epochs 59/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00011308469520851137, val_loss: 0.0004990473760737885
epochs 60/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014586226507641472, val_loss: 0.0006245688288737453
epochs 61/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00013277304755511546, val_loss: 0.00048650973956913704
epochs 62/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014971460684472205, val_loss: 0.0005324496201605403
epochs 63/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014099001686860758, val_loss: 0.00047519107404036853
epochs 64/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.000140862384585872, val_loss: 0.0005735899647420627
epochs 65/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00013304640191276313, val_loss: 0.0005160676418291158
epochs 66/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014457255885262337, val_loss: 0.00048279828452332704
epochs 67/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001347057142227545, val_loss: 0.0005958746420296534
epochs 68/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00012386213650308108, val_loss: 0.0005506639480165812
epochs 69/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00013045132716223108, val_loss: 0.0004920039268052846
epochs 70/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00012008417750047029, val_loss: 0.0006201601349785629
epochs 71/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00013443338003095337, val_loss: 0.00039438361161272655
epochs 72/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00017181866638374662, val_loss: 0.000635060980033977
epochs 73/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014753720055236236, val_loss: 0.0005547697501098145
epochs 74/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001368636443849506, val_loss: 0.00045867980194214
epochs 75/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001367560765509935, val_loss: 0.0006153271282932514
epochs 76/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00014859992734272964, val_loss: 0.00048219585463542627
epochs 77/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00012456811470512645, val_loss: 0.00044882461513643936
epochs 78/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00013496493882389347, val_loss: 0.0006556789025097036
epochs 79/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00012230959056116838, val_loss: 0.0004676552498639221
epochs 80/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0001342837939247195, val_loss: 0.0005371061049151683
epochs 81/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00011348669431754388, val_loss: 0.00044729724288031106
epochs 82/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00013481554059054408, val_loss: 0.0005384725036540576
epochs 83/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.00011699694809258769, val_loss: 0.000656622981377902
Starting fold 2:
epochs 1/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.027948135452109727, val_loss: 0.04047375020605547
epochs 2/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0036104053624728717, val_loss: 0.04742602882758966
epochs 3/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0017904812374243163, val_loss: 0.03440826591202822
epochs 4/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.001512167215688857, val_loss: 0.036134189714199655
epochs 5/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0009768045614341441, val_loss: 0.020831137486590594
epochs 6/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.000887807268427567, val_loss: 0.01456490936122401
epochs 7/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.000687855027375207, val_loss: 0.01309513820522519
epochs 8/83
Current Learning Rate: 0.006024096099506999
train_loss: 0.0002792594678460996, val_loss: 0.007636770746478486
epochs 9/83

[I 2024-01-30 14:49:08,186] Trial 15 pruned.

Starting fold 1:
epochs 1/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.14320826004014203, val_loss: 0.09274254006052775
epochs 2/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.06517513080647117, val_loss: 0.026243792048522403
epochs 3/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.013309170173995785, val_loss: 0.0017005281849941682
epochs 4/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0026758163174810377, val_loss: 0.0011373399147054269
epochs 5/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0020872456327963034, val_loss: 0.0038701643102935384
epochs 6/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.003131840086395019, val_loss: 0.0036732007745682955
epochs 7/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0026198443380723658, val_loss: 0.0013076756528342171
epochs 8/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0023037930288793227, val_loss: 0.0018585354971167231
epochs 9/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.001819860641109316, val_loss: 0.0029859456505315998
epochs 10/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0020577748048756467, val_loss: 0.0021673368122835184
epochs 11/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0015070019749385353, val_loss: 0.001559282897413516
epochs 12/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0014220152711985927, val_loss: 0.002318706641080863
epochs 13/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.001423958440213219, val_loss: 0.002252148682369836
epochs 14/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0013590552556132407, val_loss: 0.0013278421145745567
epochs 15/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0009085157788113544, val_loss: 0.001810181938621792
epochs 16/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0010948204380264016, val_loss: 0.002301045498507659
epochs 17/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0010305733848853331, val_loss: 0.001238246358254747
epochs 18/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0006667285544895812, val_loss: 0.0016041720029158844
epochs 19/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0006811905106970746, val_loss: 0.0017373174822072513
epochs 20/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.000599752430264887, val_loss: 0.0015167174659880055
epochs 21/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0005837509399402494, val_loss: 0.001561324677794122
epochs 22/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0006042679428662124, val_loss: 0.0012756982288833353
epochs 23/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00048668012022972106, val_loss: 0.0013824022919704606
epochs 24/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004744863658408193, val_loss: 0.0017042120124974717
epochs 25/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0005950196157515932, val_loss: 0.0014085492115959318
epochs 26/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00046989586553536355, val_loss: 0.001395226561322084
epochs 27/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0005105827794116187, val_loss: 0.001469701368247144
epochs 28/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0005159961372172754, val_loss: 0.0014528788601709825
epochs 29/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0005268993827293774, val_loss: 0.0014825783762803656
epochs 30/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0006146443021287652, val_loss: 0.001520348092844148
epochs 31/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0005927180329117139, val_loss: 0.001217307132070086
epochs 32/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.000521245270991992, val_loss: 0.001440465272892089
epochs 33/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.000591955341300682, val_loss: 0.0016255063263030487
epochs 34/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0005290060518554559, val_loss: 0.0012603844649949304
epochs 35/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0003915614607792936, val_loss: 0.0014665704955058615
epochs 36/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004679466490511243, val_loss: 0.001305694262670826
epochs 37/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.000510326906499502, val_loss: 0.0014043803682961013
epochs 38/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004914136456423685, val_loss: 0.0013912192191041651
epochs 39/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.000431490084156394, val_loss: 0.0012586547259522218
epochs 40/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0003933818569700969, val_loss: 0.0015644797637674307
epochs 41/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004569948712167771, val_loss: 0.0011556445850088957
epochs 42/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004682653430408161, val_loss: 0.0014500058147989745
epochs 43/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0005040877944434453, val_loss: 0.0014000647107235318
epochs 44/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00042182641581779245, val_loss: 0.0012331024913619908
epochs 45/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004205422221658457, val_loss: 0.0014135877150000028
epochs 46/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0003911573885584642, val_loss: 0.0012540316790349722
epochs 47/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00046144766169355105, val_loss: 0.0012123163171400804
epochs 48/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004566072250446795, val_loss: 0.0014681419395076642
epochs 49/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00048745112021845815, val_loss: 0.001260992223655598
epochs 50/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00046691935184705805, val_loss: 0.0012255651111315405
epochs 51/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00042938085833539894, val_loss: 0.001504586693564696
epochs 52/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004584102006016397, val_loss: 0.0011703582311470416
epochs 53/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00034627621797354597, val_loss: 0.001400294903543822
epochs 54/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0005079975039208014, val_loss: 0.0012293796610301508
epochs 55/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00037707667491447766, val_loss: 0.0012095417039254533
epochs 56/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0003913770803544474, val_loss: 0.0013541431623115574
epochs 57/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00038669760994564155, val_loss: 0.0012029964363180277
epochs 58/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004240973829598117, val_loss: 0.0013796922407530632
epochs 59/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0003927869235140909, val_loss: 0.0012736515135556045
epochs 60/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00034075447612466587, val_loss: 0.0013059714787347716
epochs 61/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00035044003950468705, val_loss: 0.0013139244822216118
epochs 62/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00032229009574573294, val_loss: 0.00122477267665552
epochs 63/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00041253036179114135, val_loss: 0.0013516417853275521
epochs 64/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0003598472901534191, val_loss: 0.001194016326547763
epochs 65/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004035307825114088, val_loss: 0.001244458426963464
epochs 66/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.00036018061463868146, val_loss: 0.0012131152080468064
epochs 67/101
Current Learning Rate: 0.03552479216297926
train_loss: 0.0004091565223030844, val_loss: 0.0012747921998472146
epochs 68/101
Epoch 00068: reducing learning rate of group 0 to 1.7405e-02.
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003547083260185134, val_loss: 0.0013284933619803587
epochs 69/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003362041542698678, val_loss: 0.001254875954824485
epochs 70/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00039471785498072245, val_loss: 0.0013723663940918558
epochs 71/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00036815196845533426, val_loss: 0.0013321003509825834
epochs 72/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0004109366243937984, val_loss: 0.0012088838335503603
epochs 73/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003486233797095912, val_loss: 0.0013034229165881813
epochs 74/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00034518148719431144, val_loss: 0.0014029601140738658
epochs 75/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003619103265105207, val_loss: 0.001212708177118902
epochs 76/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00032459184371155537, val_loss: 0.0012408877221224386
epochs 77/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00038394110168538695, val_loss: 0.0014128472525737294
epochs 78/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00039702288907535963, val_loss: 0.0011668089021455556
epochs 79/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003063073899523404, val_loss: 0.0011856198049379541
epochs 80/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003151888969832247, val_loss: 0.0014208799358808421
epochs 81/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003358930225275751, val_loss: 0.0012298667168666032
epochs 82/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00037704880554596646, val_loss: 0.0012285428196524403
epochs 83/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00037140687406798337, val_loss: 0.001340687372638578
epochs 84/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003441722182814326, val_loss: 0.0011898791546829874
epochs 85/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00035709439406146935, val_loss: 0.001233377893518154
epochs 86/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00032051063056937176, val_loss: 0.0013292146976464354
epochs 87/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00035064689903887674, val_loss: 0.0012312808338763369
epochs 88/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00027066975476612386, val_loss: 0.0012292895645793854
epochs 89/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003742741921757299, val_loss: 0.0012867470490857073
epochs 90/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.00034275580439594035, val_loss: 0.0011702197717524889
epochs 91/101
Current Learning Rate: 0.017405095552839745
train_loss: 0.0003155457493113844, val_loss: 0.0013189551061100608
epochs 92/101

[I 2024-01-30 14:49:17,691] Trial 16 pruned.

Starting fold 1:
epochs 1/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.009777791719687613, val_loss: 0.011783230694986525
epochs 2/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.005643239946986892, val_loss: 0.006724067433939251
epochs 3/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.002960136387264356, val_loss: 0.003484705382361811
epochs 4/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.001577231931304069, val_loss: 0.0017579998143470634
epochs 5/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0011826030655739536, val_loss: 0.0010763639878301767
epochs 6/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0012739532587339023, val_loss: 0.0009218757733747008
epochs 7/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.00147681954748757, val_loss: 0.0009115184081358609
epochs 8/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0015441051267675663, val_loss: 0.0008937062728883964
epochs 9/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0013848987420236594, val_loss: 0.000891220346881599
epochs 10/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0010853734424974965, val_loss: 0.0009851328480099304
epochs 11/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0008342197918529181, val_loss: 0.0012225742041005227
epochs 12/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0006928986526633564, val_loss: 0.0015813771859501248
epochs 13/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0006692841180330633, val_loss: 0.001977932620325456
epochs 14/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0007017673658035499, val_loss: 0.0023102389676890596
epochs 15/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0008061831136920342, val_loss: 0.002491969361755918
epochs 16/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0008539540374553517, val_loss: 0.002493601139923114
epochs 17/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0008327758209289689, val_loss: 0.002334784530657565
epochs 18/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0007660992201540227, val_loss: 0.002075380017111206
epochs 19/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0006650306570870606, val_loss: 0.0017865856562152248
epochs 20/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.000581440007265069, val_loss: 0.001521857728086481
epochs 21/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0005127779511416233, val_loss: 0.0013109101546144792
epochs 22/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.00046823580893320276, val_loss: 0.001163739262015692
epochs 23/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.00042721630322232253, val_loss: 0.001077634228976128
epochs 24/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.0004238335035839363, val_loss: 0.0010400865222056392
epochs 25/63
Current Learning Rate: 0.00030407576717697717
train_loss: 0.00038886418256688077, val_loss: 0.0010441560333621781
epochs 26/63
Epoch 00026: reducing learning rate of group 0 to 2.4016e-04.
Current Learning Rate: 0.00024016277332752502
train_loss: 0.0003649197802204933, val_loss: 0.0010808064710415368
epochs 27/63
Current Learning Rate: 0.00024016277332752502
train_loss: 0.00034049301420485505, val_loss: 0.0011276170125085782
epochs 28/63
Current Learning Rate: 0.00024016277332752502
train_loss: 0.0003261032224767596, val_loss: 0.0011825921252941486
epochs 29/63
Current Learning Rate: 0.00024016277332752502
train_loss: 0.00031746879011686696, val_loss: 0.0012335268421487873
epochs 30/63
Current Learning Rate: 0.00024016277332752502
train_loss: 0.0003165257278229355, val_loss: 0.001268472131674311
epochs 31/63

[I 2024-01-30 14:49:20,410] Trial 17 pruned.

Current Learning Rate: 0.00024016277332752502
train_loss: 0.0003045122901216689, val_loss: 0.0012817004291776804
epochs 32/63
Starting fold 1:
epochs 1/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.003331455604271277, val_loss: 0.00480544420757464
epochs 2/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.00311314351979251, val_loss: 0.004430307252776055
epochs 3/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0024812225080830487, val_loss: 0.004119805267287625
epochs 4/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0026567717033781505, val_loss: 0.0038377802865826108
epochs 5/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.002761445936477302, val_loss: 0.0035775214102286746
epochs 6/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.002399610190064107, val_loss: 0.0033463000180692505
epochs 7/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0021175693193646638, val_loss: 0.0031460226912583622
epochs 8/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0020235564504554006, val_loss: 0.0029740564435198113
epochs 9/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0020987021056690105, val_loss: 0.002825247153403267
epochs 10/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0021544300528292203, val_loss: 0.0026943094337915892
epochs 11/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0020107097500984216, val_loss: 0.002584705353781049
epochs 12/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0022343426152426553, val_loss: 0.0024899852279790494
epochs 13/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0020612568125790475, val_loss: 0.002406983935057368
epochs 14/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.001957630802950773, val_loss: 0.0023308263136266123
epochs 15/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0018084034228721929, val_loss: 0.002269866407563092
epochs 16/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016371231713013625, val_loss: 0.0022212726103447416
epochs 17/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0019434643648932443, val_loss: 0.0021752763909741093
epochs 18/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0019431608226640445, val_loss: 0.00213270250919753
epochs 19/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0018098040738167536, val_loss: 0.002092939441796964
epochs 20/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016062256013116751, val_loss: 0.0020569782490378846
epochs 21/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015911826906774781, val_loss: 0.002026507534547438
epochs 22/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0018675957245776725, val_loss: 0.001999205575514309
epochs 23/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015826871355162247, val_loss: 0.0019777779114462197
epochs 24/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0018498199703907104, val_loss: 0.0019587549087147983
epochs 25/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016081924090701107, val_loss: 0.0019489842905569329
epochs 26/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016184994770140435, val_loss: 0.0019433515706276964
epochs 27/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016914370169519987, val_loss: 0.0019397147809199634
epochs 28/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014769918940912344, val_loss: 0.001934893566329111
epochs 29/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014644751116927516, val_loss: 0.0019276067626874441
epochs 30/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015988853747809404, val_loss: 0.001921299250584549
epochs 31/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016533924713975896, val_loss: 0.0019138277386359516
epochs 32/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014598631211188867, val_loss: 0.0019026893888915539
epochs 33/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.001608460697369944, val_loss: 0.0018930470801288724
epochs 34/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016984995944719565, val_loss: 0.0018859539558573888
epochs 35/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015303981230030523, val_loss: 0.001882502190441031
epochs 36/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014918317626181402, val_loss: 0.001878996631290724
epochs 37/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015671757160146769, val_loss: 0.0018768990381556766
epochs 38/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016830182530132955, val_loss: 0.001874989284530144
epochs 39/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016534329747389023, val_loss: 0.0018725916438381233
epochs 40/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014459765669399577, val_loss: 0.0018701175121201212
epochs 41/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015614653974281329, val_loss: 0.001870742898616723
epochs 42/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016306940294606121, val_loss: 0.0018694306586415719
epochs 43/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015261371521965454, val_loss: 0.0018618441459097009
epochs 44/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0016864034512668457, val_loss: 0.0018522522890220875
epochs 45/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015276338718218827, val_loss: 0.0018497169921396388
epochs 46/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014329579609789346, val_loss: 0.001853771721784065
epochs 47/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013734450851763157, val_loss: 0.0018545878153644188
epochs 48/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.001646471776582889, val_loss: 0.0018461331523087605
epochs 49/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014894715982097153, val_loss: 0.0018368003478461
epochs 50/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015012993030004988, val_loss: 0.0018225939492892138
epochs 51/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014986839271027986, val_loss: 0.0018100781559022686
epochs 52/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014758502059665165, val_loss: 0.0017995089606662829
epochs 53/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013663711326539908, val_loss: 0.0017889867485599426
epochs 54/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0017687381324848455, val_loss: 0.0017746050935115408
epochs 55/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0011088790120802035, val_loss: 0.0017667773044815966
epochs 56/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014430116479113501, val_loss: 0.001760185540656229
epochs 57/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015219585467620117, val_loss: 0.001753255707968184
epochs 58/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.00146606629775641, val_loss: 0.001747437249548812
epochs 59/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014115609871958824, val_loss: 0.0017472830325089119
epochs 60/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015348873046030732, val_loss: 0.001748138370371803
epochs 61/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0014952041061693116, val_loss: 0.0017531299975912565
epochs 62/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0015085164096059376, val_loss: 0.0017621831949332129
epochs 63/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.001348361757424611, val_loss: 0.0017630673911688583
epochs 64/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013060825233543781, val_loss: 0.0017551141932715105
epochs 65/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.001314485488508485, val_loss: 0.001750092230929387
epochs 66/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013577049830928445, val_loss: 0.0017421192054700835
epochs 67/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013820965327077399, val_loss: 0.0017352394572404956
epochs 68/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0012734991645342426, val_loss: 0.001728390977919969
epochs 69/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.001462198582502376, val_loss: 0.0017205037451632538
epochs 70/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0012460375161792495, val_loss: 0.001709526503137091
epochs 71/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013021038321312517, val_loss: 0.0016975190346350982
epochs 72/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0012726935000452948, val_loss: 0.0016898813621429283
epochs 73/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0011379776130381384, val_loss: 0.0016862331780545887
epochs 74/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013724088846509786, val_loss: 0.0016847606371070637
epochs 75/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013941507878419209, val_loss: 0.0016835396530392465
epochs 76/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013280843099652741, val_loss: 0.0016836870599368085
epochs 77/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0013039403006826576, val_loss: 0.0016868132794529652
epochs 78/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0012504424636350258, val_loss: 0.0016977197389616064
epochs 79/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0011635925896514795, val_loss: 0.0017148649046522758
epochs 80/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0011591819929890335, val_loss: 0.0017182008211165864
epochs 81/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.00153495626536345, val_loss: 0.0017132813244301669
epochs 82/127
Current Learning Rate: 8.608351142177036e-06
train_loss: 0.0012705115460496593, val_loss: 0.0017092353770590668
epochs 83/127
Epoch 00083: reducing learning rate of group 0 to 2.8503e-06.
Current Learning Rate: 2.850325650446959e-06
train_loss: 0.001302283278690945, val_loss: 0.0017034563637232634
epochs 84/127
Current Learning Rate: 2.850325650446959e-06
train_loss: 0.0010459578219237493, val_loss: 0.0017019539576260344
epochs 85/127
Current Learning Rate: 2.850325650446959e-06
train_loss: 0.0012544659211447364, val_loss: 0.0016992773564111086
epochs 86/127
Current Learning Rate: 2.850325650446959e-06
train_loss: 0.0011923305022432224, val_loss: 0.001696499726715345
epochs 87/127
Current Learning Rate: 2.850325650446959e-06
train_loss: 0.0012059171046865614, val_loss: 0.0016941377885698798
epochs 88/127
Current Learning Rate: 2.850325650446959e-06
train_loss: 0.0011502653145917545, val_loss: 0.001691009784788731
epochs 89/127
Current Learning Rate: 2.850325650446959e-06
train_loss: 0.001239419530305129, val_loss: 0.0016863153429416123
epochs 90/127
Current Learning Rate: 2.850325650446959e-06
train_loss: 0.0013511203027232305, val_loss: 0.001682013977120665
epochs 91/127
Current Learning Rate: 2.850325650446959e-06
train_loss: 0.001384781120577827, val_loss: 0.0016778897495309591
epochs 92/127

[I 2024-01-30 14:49:31,178] Trial 18 pruned.

Starting fold 1:
epochs 1/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.017563580760830328, val_loss: 0.011512739593705173
epochs 2/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.008825778024957369, val_loss: 0.004414464167205903
epochs 3/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.003896699230627794, val_loss: 0.0011277983854241452
epochs 4/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0017919118356841959, val_loss: 0.0008109718745650733
epochs 5/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.00228043432273951, val_loss: 0.0018187809589863436
epochs 6/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0025981508232162972, val_loss: 0.0025441031801396066
epochs 7/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0035924260431018317, val_loss: 0.002314610830532811
epochs 8/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0028133529973657506, val_loss: 0.0015524775431942314
epochs 9/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0022649072662093922, val_loss: 0.0008964514719856972
epochs 10/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0014815831863272347, val_loss: 0.0006326408317637822
epochs 11/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0012193649039162616, val_loss: 0.0007733708355642323
epochs 12/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.001191420419337718, val_loss: 0.0011322876007638615
epochs 13/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0014149331548986466, val_loss: 0.0014649759705496273
epochs 14/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0015925311311883361, val_loss: 0.0015779910347345604
epochs 15/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.001699522124162238, val_loss: 0.001463303452717367
epochs 16/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0017273456703773454, val_loss: 0.0011837184435328242
epochs 17/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0012059467072647653, val_loss: 0.0009024583509132739
epochs 18/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0011024443285637781, val_loss: 0.0006919961463334778
epochs 19/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0009856794133635337, val_loss: 0.0005827648170962536
epochs 20/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0009292738512158393, val_loss: 0.0005521022529272294
epochs 21/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0011884223547224935, val_loss: 0.0005514512239541444
epochs 22/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0009247377239118673, val_loss: 0.0005454653104097045
epochs 23/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0008733318187296391, val_loss: 0.0005320372163421578
epochs 24/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0008314839264034833, val_loss: 0.0005260074958353052
epochs 25/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0008510843679112824, val_loss: 0.0005398804830663182
epochs 26/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0008894191521808113, val_loss: 0.000574774814402517
epochs 27/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.000938185560517013, val_loss: 0.000609027763992479
epochs 28/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0008848489421468816, val_loss: 0.0006369479379688129
epochs 29/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0008494637324474752, val_loss: 0.0006393161924154295
epochs 30/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0008740474139095137, val_loss: 0.0006174384237503603
epochs 31/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0008398300367652585, val_loss: 0.0005922183162217379
epochs 32/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0007019401595339571, val_loss: 0.0005549713077637116
epochs 33/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0007577657344211874, val_loss: 0.0005299019000231825
epochs 34/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006613703285294928, val_loss: 0.000522764092594602
epochs 35/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0007220431451538676, val_loss: 0.0005283287175679727
epochs 36/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006472885712834173, val_loss: 0.0005333319051676582
epochs 37/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005641241545641893, val_loss: 0.0005344884684457192
epochs 38/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0007353719844678907, val_loss: 0.0005321863813266631
epochs 39/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006334830265443184, val_loss: 0.0005243211304313114
epochs 40/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006477537552679056, val_loss: 0.0005145360572169973
epochs 41/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006003034901560137, val_loss: 0.0005095994782759734
epochs 42/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006961200429175638, val_loss: 0.0005059635812396962
epochs 43/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006537332315929234, val_loss: 0.000508058122322259
epochs 44/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006666831592539031, val_loss: 0.0005202371283389983
epochs 45/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006647550396768279, val_loss: 0.0005354811215684528
epochs 46/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006042481786081274, val_loss: 0.0005345895200248354
epochs 47/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.000543881065555309, val_loss: 0.0005243518917942074
epochs 48/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006037487832241152, val_loss: 0.0005248118393374459
epochs 49/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005864527070355651, val_loss: 0.0005194333441390425
epochs 50/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0007003780901677123, val_loss: 0.0005109239775852531
epochs 51/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006089483890192289, val_loss: 0.0005212126168232687
epochs 52/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0007172756472994623, val_loss: 0.0005203710413764591
epochs 53/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006314858175372999, val_loss: 0.0005162552988622338
epochs 54/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005765975060823716, val_loss: 0.0005205797401710201
epochs 55/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006049530617402572, val_loss: 0.0005371741411244132
epochs 56/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005209342411131059, val_loss: 0.0005512039688977576
epochs 57/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0006042748818321055, val_loss: 0.0005579191539067007
epochs 58/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005482128821313381, val_loss: 0.0005624204331691126
epochs 59/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.00046233378693853554, val_loss: 0.0005591118704557182
epochs 60/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0004669968476886616, val_loss: 0.0005603248959348079
epochs 61/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0004895136324002554, val_loss: 0.0005450782799728648
epochs 62/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005439866003335306, val_loss: 0.0005422594046057571
epochs 63/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005323154275844756, val_loss: 0.0005509126447904954
epochs 64/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005319665461827658, val_loss: 0.0005587165751469829
epochs 65/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.00047658792218977685, val_loss: 0.0005590925013175894
epochs 66/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005167219028072922, val_loss: 0.0005742467038404867
epochs 67/85
Epoch 00067: reducing learning rate of group 0 to 2.2931e-04.
Current Learning Rate: 0.0002293145816394801
train_loss: 0.00041161741859181537, val_loss: 0.0005842850998748665
epochs 68/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0004211609460119354, val_loss: 0.0005845438835898502
epochs 69/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.00048164399585833674, val_loss: 0.000572671654120472
epochs 70/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.00046311043735936674, val_loss: 0.0005718392979664108
epochs 71/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0003972395543793314, val_loss: 0.0005741191711634023
epochs 72/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0005091200294708343, val_loss: 0.0005752864304841275
epochs 73/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0005309955321105295, val_loss: 0.0005770035380024522
epochs 74/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0004729028221366829, val_loss: 0.0005761255374949465
epochs 75/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0005102445432720215, val_loss: 0.0005829675722418835
epochs 76/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0004585382476522538, val_loss: 0.0005922667489993194
epochs 77/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.00048070443475520925, val_loss: 0.0006023769392558034
epochs 78/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0004930864302686563, val_loss: 0.0006041673660985436
epochs 79/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0004728391919726212, val_loss: 0.0006027405349495846
epochs 80/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0003779912915840549, val_loss: 0.0006113782372305949
epochs 81/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0005171297926847872, val_loss: 0.000617435762366753
epochs 82/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0004649328827661903, val_loss: 0.0006162172502766624
epochs 83/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0005007815914914797, val_loss: 0.0006031822391647707
epochs 84/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.0004372602907671152, val_loss: 0.0005911031133364688
epochs 85/85
Current Learning Rate: 0.0002293145816394801
train_loss: 0.00042180284140876643, val_loss: 0.00057631513355152
Starting fold 2:
epochs 1/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0008907085734586622, val_loss: 0.018435480536291838
epochs 2/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005645574436653258, val_loss: 0.012558334489801416
epochs 3/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0007902522578142524, val_loss: 0.01443976771441244
epochs 4/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.0007542870107283791, val_loss: 0.016661460880958844
epochs 5/85
Current Learning Rate: 0.00042674418565050973
train_loss: 0.000511075895264902, val_loss: 0.014696433455264443
epochs 6/85

[I 2024-01-30 14:49:38,668] Trial 19 pruned.

Current Learning Rate: 0.00042674418565050973
train_loss: 0.0005867673167995716, val_loss: 0.013029759991224165
epochs 7/85
Number of finished trials: 20
Best trial:
Value: 0.0032413798090183757
Params:
batch_size: 123
epochs: 148
hidden_size: 99
learning_rate: 0.0019297301389046295
dropout_prob: 0.07570182866427809
weight_decay: 9.161691434506323e-05
lr_step_size: 9
gamma: 0.7341843028499456
num_layers: 3

In [32]:
trainer = ModelActioner(train_data, test_data, device)
model = trainer.train(trial.params)

epochs 1/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.0657042062074143
epochs 2/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.19959346815730375
epochs 3/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.03741984476585614
epochs 4/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.011496071154477346
epochs 5/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.012208082143315792
epochs 6/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.024112468134480557
epochs 7/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.02385016929949039
epochs 8/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.026170690437278297
epochs 9/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.014125866720674453
epochs 10/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.012216907045250094
epochs 11/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.01658734359905649
epochs 12/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.03733334337004218
epochs 13/148
Current Learning Rate: 0.0019297301389046295
train_loss: 0.031952895807709526
epochs 14/148
Epoch 00014: reducing learning rate of group 0 to 1.4168e-03.
Current Learning Rate: 0.0014167775767202242
train_loss: 0.05783017535574964
epochs 15/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.01581797245623224
epochs 16/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.025913518754712057
epochs 17/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.013254449976041978
epochs 18/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.012842238269744252
epochs 19/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.004847372413945224
epochs 20/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.004169009577909624
epochs 21/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0032880588142829023
epochs 22/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0034783050229173925
epochs 23/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0031924660115026857
epochs 24/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.002939170780401915
epochs 25/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0027492685819666273
epochs 26/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.003035676961181078
epochs 27/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.002636128807202441
epochs 28/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0024650158569071083
epochs 29/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0024825954623622945
epochs 30/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0028941312726096778
epochs 31/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0025746295523228708
epochs 32/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.0030782145666500087
epochs 33/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.003557155737120018
epochs 34/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.00430491678919315
epochs 35/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.004836665481710519
epochs 36/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.006513172795889399
epochs 37/148
Current Learning Rate: 0.0014167775767202242
train_loss: 0.009183162262884794
epochs 38/148
Epoch 00038: reducing learning rate of group 0 to 1.0402e-03.
Current Learning Rate: 0.0010401758574577731
train_loss: 0.011836655581234605
epochs 39/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.019356847009549764
epochs 40/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.008261702386487997
epochs 41/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.007227003023552499
epochs 42/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0029493388188807992
epochs 43/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0028064257916604633
epochs 44/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0023757070420404266
epochs 45/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0022969456146715314
epochs 46/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0022275451599083848
epochs 47/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0021715149795482683
epochs 48/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0023280975551422407
epochs 49/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.002171500433889722
epochs 50/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0022290436478407585
epochs 51/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.002584661480405015
epochs 52/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.0035116273578510737
epochs 53/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.003889525151172538
epochs 54/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.005481130502490318
epochs 55/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.00686657551264735
epochs 56/148
Current Learning Rate: 0.0010401758574577731
train_loss: 0.01040035159366066
epochs 57/148
Epoch 00057: reducing learning rate of group 0 to 7.6368e-04.
Current Learning Rate: 0.0007636807867489796
train_loss: 0.009551687127118725
epochs 58/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.010458930304142163
epochs 59/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.003383910633717963
epochs 60/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.002637268172854984
epochs 61/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0021737470267707737
epochs 62/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0021997278449171743
epochs 63/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.002116932710253178
epochs 64/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0019106208738467825
epochs 65/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0018907837733566875
epochs 66/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0019613618042426686
epochs 67/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0017648679794054396
epochs 68/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0017384205106594538
epochs 69/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0017621468016821358
epochs 70/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0019075395587225556
epochs 71/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0015564467688193669
epochs 72/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0016884453076072292
epochs 73/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.001805715690049474
epochs 74/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0017592546469167834
epochs 75/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0021333275078093254
epochs 76/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.002248841367501946
epochs 77/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0026307162225896715
epochs 78/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.0037044997455753254
epochs 79/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.00427412255151743
epochs 80/148
Current Learning Rate: 0.0007636807867489796
train_loss: 0.007002509194441624
epochs 81/148
Epoch 00081: reducing learning rate of group 0 to 5.6068e-04.
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00668136730614746
epochs 82/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.007905621452914501
epochs 83/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0028059271125005975
epochs 84/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0021591320623374965
epochs 85/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0017186586316090308
epochs 86/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.001723604525825612
epochs 87/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.001792499612830169
epochs 88/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0015524076546223357
epochs 89/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.001563857024815549
epochs 90/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0014595010581591459
epochs 91/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0016204020154989623
epochs 92/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0015981325792125119
epochs 93/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0016158680296795328
epochs 94/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0014685256445897325
epochs 95/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0013539354994355614
epochs 96/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0015001789044633935
epochs 97/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0013581812393155138
epochs 98/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0013867920763341358
epochs 99/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0014174285851339995
epochs 100/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0014372535117866988
epochs 101/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0013650263215790582
epochs 102/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0013281424887814776
epochs 103/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0013240688852504273
epochs 104/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0012964688889843326
epochs 105/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0014002171503010694
epochs 106/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0014999770266409052
epochs 107/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.001403377996296068
epochs 108/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0012755444813376121
epochs 109/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0012191356753234008
epochs 110/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.001409540558015899
epochs 111/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0014797371592027
epochs 112/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0014359398350239595
epochs 113/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.001567751678560208
epochs 114/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.0018459608467446542
epochs 115/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.002695512541904143
epochs 116/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.00437992912927942
epochs 117/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.005486888104346109
epochs 118/148
Current Learning Rate: 0.0005606824460191977
train_loss: 0.009666968641047763
epochs 119/148
Epoch 00119: reducing learning rate of group 0 to 4.1164e-04.
Current Learning Rate: 0.0004116442507508069
train_loss: 0.008229683491987041
epochs 120/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.009368724063321402
epochs 121/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.0024229268149174297
epochs 122/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.0019288840354676666
epochs 123/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.0018187542664685127
epochs 124/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.001656622868769757
epochs 125/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.0016542482379714174
epochs 126/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.0015856458071238744
epochs 127/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.001598494984981366
epochs 128/148
Current Learning Rate: 0.0004116442507508069
train_loss: 0.0014205566912044315
epochs 129/148
Epoch 00129: reducing learning rate of group 0 to 3.0222e-04.
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0014256620101911726
epochs 130/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0014064658127288182
epochs 131/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0014788578609173854
epochs 132/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0013788948570981228
epochs 133/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.001376372363583989
epochs 134/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0014584658703857022
epochs 135/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0012785406029087775
epochs 136/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0013524143293495844
epochs 137/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0013723754961097957
epochs 138/148
Current Learning Rate: 0.0003022227472596694
train_loss: 0.0014236433462020304
epochs 139/148
Epoch 00139: reducing learning rate of group 0 to 2.2189e-04.
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0013353806561872462
epochs 140/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0013930653882318583
epochs 141/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0013203100246835771
epochs 142/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0012627494482206599
epochs 143/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0014197590355484414
epochs 144/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0013110712452408025
epochs 145/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0011960492170767628
epochs 146/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0012937607197629469
epochs 147/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0013544093322066287
epochs 148/148
Current Learning Rate: 0.0002218871970022357
train_loss: 0.0014303551691287866

In [33]:
preds = trainer.test(trial.params)
preds = np.array(preds)

y_true = y_test[time_step:]
y_true = scaler_adj.inverse_transform(y_true.reshape(-1, 1)).flatten()
preds = scaler_adj.inverse_transform(preds.reshape(-1, 1)).flatten()


mse = mean_squared_error(y_true, preds)
print(f'Mean Squared Error: {mse:.4f}')

rmse = mean_squared_error(y_true, preds, squared=False)
print(f'Root Mean Squared Error: {rmse:.4f}')

r2 = r2_score(y_true, preds)
print(f'R² Score: {r2:.4f}')

mape = mean_absolute_percentage_error(y_true, preds)*100
print(f'mape Score: % {mape:.4f}')

test_loss: 0.0012888773328223937
Mean Squared Error: 27.4116
Root Mean Squared Error: 5.2356
R² Score: 0.8726
mape Score: % 2.4734

In [34]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [35]:
signals = pd.DataFrame(preds, columns=['pred'])
signals["next_day"] = pd.DataFrame(y_true)
signals["today"] = stock_price
signals["Signal_Pred"] = (signals["today"] < signals["pred"]).astype(int)
signals["Signal_True"] = (signals["today"] < signals["next_day"]).astype(int)

signals.head(50)

          pred    next_day       today  Signal_Pred  Signal_True
0   135.690048  141.737747  140.325653            0            1
1   137.220428  141.071472  141.737747            0            0
2   138.451996  143.159805  141.071472            0            1
3   139.714645  145.118851  143.159805            0            1
4   141.099136  142.205154  145.118851            0            0
5   141.745697  143.487961  142.205154            0            1
6   142.217682  144.621628  143.487961            0            1
7   142.866837  149.981674  144.621628            0            1
8   144.308228  153.641220  149.981674            0            1
9   146.243393  150.886612  153.641220            0            0
10  147.559204  153.790375  150.886612            0            1
11  148.761520  151.075562  153.790375            0            0
12  149.366714  150.031387  151.075562            0            0
13  149.538513  150.399902  150.031387            0            1
14  149.675049  153.228439  150.399902            0            1
15  150.224533  152.581055  153.228439            0            0
16  150.838852  154.702438  152.581055            0            1
17  151.675919  153.089005  154.702438            0            0
18  152.234573  151.933685  153.089005            0            0
19  152.436798  147.880127  151.933685            1            0
20  151.856705  148.308395  147.880127            1            1
21  151.114243  148.796417  148.308395            1            1
22  150.580643  146.117294  148.796417            1            0
23  149.755524  147.322372  146.117294            1            1
24  149.071426  146.814438  147.322372            1            0
25  148.590668  144.722916  146.814438            1            0
26  147.936996  145.320511  144.722916            1            1
27  147.443222  150.419815  145.320511            1            1
28  148.035370  153.208511  150.419815            0            1
29  149.355957  150.987534  153.208511            0            0
30  150.299118  152.252396  150.987534            0            1
31  151.091660  149.981598  152.252396            0            0
32  151.247498  147.900040  149.981598            1            0
33  150.727493  149.862076  147.900040            1            1
34  150.269058  151.973526  149.862076            1            1
35  150.314362  152.371902  151.973526            0            1
36  150.664169  155.220352  152.371902            0            1
37  151.469086  154.373779  155.220352            0            0
38  152.211487  156.764084  154.373779            0            1
39  153.131256  158.636490  156.764084            0            1
40  154.282745  157.192352  158.636490            0            0
41  155.097702  158.287903  157.192352            0            1
42  155.778000  159.602570  158.287903            0            1
43  156.506378  157.640533  159.602570            0            0
44  156.766205  157.013077  157.640533            0            0
45  156.701523  160.120483  157.013077            0            1
46  157.111481  161.704041  160.120483            0            1
47  157.992310  164.233780  161.704041            0            1
48  159.297119  165.498672  164.233780            0            1
49  160.807037  164.960831  165.498672            0            0

In [36]:
signals["Signal_Pred"].value_counts()

Signal_Pred
0    224
1     27
Name: count, dtype: int64

In [37]:
signals["Date"] = date_test
signals

           pred    next_day       today  Signal_Pred  Signal_True       Date
0    135.690048  141.737747  140.325653            0            1 2023-01-23
1    137.220428  141.071472  141.737747            0            0 2023-01-24
2    138.451996  143.159805  141.071472            0            1 2023-01-25
3    139.714645  145.118851  143.159805            0            1 2023-01-26
4    141.099136  142.205154  145.118851            0            0 2023-01-27
..          ...         ...         ...          ...          ...        ...
246  179.676727  182.679993  183.630005            0            0 2024-01-16
247  178.975479  188.630005  182.679993            0            1 2024-01-17
248  179.351898  191.559998  188.630005            0            1 2024-01-18
249  180.592804  193.889999  191.559998            0            1 2024-01-19
250  182.262268  195.179993  193.889999            0            1 2024-01-22

[251 rows x 6 columns]

In [38]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [39]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [40]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
buy_signals = signals[signals['Signal_Pred'] == 1]
sell_signals = signals[signals['Signal_Pred'] == 0]

# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]


# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))


# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))


# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [41]:
trace_pred = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['pred'],
    mode='lines+markers',
    name='Predicted'
)

trace_true = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['next_day'],
    mode='lines+markers',
    name='Actual Next Day'
)

# Define the layout
layout = go.Layout(
    title='Predicted vs Actual Next Day Values',
    xaxis=dict(title='Index'),
    yaxis=dict(title='Value'),
    height=700
)

# Create the figure and add traces
fig = go.Figure(data=[trace_pred, trace_true], layout=layout)

# Show the figure
fig.show()