In [104]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm

In [105]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [106]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722874  43.075001  42.314999  102223600
1  2018-01-03  40.715771  43.637501  42.990002  118071600
2  2018-01-04  40.904900  43.367500  43.020000   89738400
3  2018-01-05  41.370628  43.842499  43.262501   94640000
4  2018-01-08  41.216972  43.902500  43.482498   82271200
5  2018-01-09  41.212234  43.764999  43.352501   86336000
6  2018-01-10  41.202774  43.575001  43.250000   95839600
7  2018-01-11  41.436817  43.872501  43.622501   74670800
8  2018-01-12  41.864704  44.340000  43.912498  101672400
9  2018-01-16  41.651939  44.847500  44.035000  118263600
10 2018-01-17  42.339878  44.812500  43.767502  137547200
11 2018-01-18  42.377701  45.025002  44.562500  124773600
12 2018-01-19  42.188580  44.895000  44.352501  129700400
13 2018-01-22  41.843426  44.445000  44.150002  108434400
14 2018-01-23  41.852882  44.860001  44.205002  130756400
15 2018-01-24  41.186226  44.325001  43.299999  204420400
16 2018-01-25  40.451004  43.737499  42.632500  166116000
17 2018-01-26  40.545567  43.000000  42.514999  156572000
18 2018-01-29  39.706341  42.540001  41.767502  202561600
19 2018-01-30  39.472294  41.842499  41.174999  184192800
20 2018-01-31  39.581043  42.110001  41.625000  129915600
21 2018-02-01  39.663784  42.154999  41.689999  188923200
22 2018-02-02  37.942764  41.700001  40.025002  346375200
23 2018-02-05  36.994793  40.970001  39.000000  290954000
24 2018-02-06  38.540863  40.930000  38.500000  272975200
25 2018-02-07  37.715828  40.849998  39.767502  206434400
26 2018-02-08  36.678013  40.250000  38.757500  217562000
27 2018-02-09  37.126633  39.472500  37.560001  282690400
28 2018-02-12  38.622051  40.972500  39.377499  243278000
29 2018-02-13  39.008965  41.187500  40.412498  130196800
30 2018-02-14  39.728184  41.884998  40.720001  162579600
31 2018-02-15  41.062187  43.272499  42.250000  204588800
32 2018-02-16  40.929249  43.705002  42.942501  160704400
33 2018-02-20  40.791595  43.564999  42.855000  135722000
34 2018-02-21  40.606434  43.529999  42.752499  149886400
35 2018-02-22  40.945873  43.487499  42.927502  123967600
36 2018-02-23  41.657978  43.912498  43.384998  135249600
37 2018-02-26  42.481644  44.847500  44.052502  152648800
38 2018-02-27  42.343967  45.119999  44.540001  155712400
39 2018-02-28  42.279884  45.154999  44.512501  151128400
40 2018-03-01  41.539303  44.945000  43.165001  195208000
41 2018-03-02  41.826511  44.075001  43.112499  153816000
42 2018-03-05  41.971298  44.435001  43.630001  113605600
43 2018-03-06  41.935692  44.562500  44.032501   95154000
44 2018-03-07  41.546413  43.962502  43.567501  126814000

In [107]:
time_step = 44

In [108]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [109]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [110]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma = talib.SMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA': sma,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [111]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724165,117105600.0
15,NaN,NaN,55.580682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0
16,NaN,NaN,45.152378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695098,-253430800.0
17,NaN,NaN,46.541660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034648,-73.817992,2.684662,-96858800.0
18,NaN,NaN,37.470435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639414,-81.393427,2.635360,-299420400.0
19,NaN,NaN,35.398312,NaN,NaN,42.761514,41.213176,39.664837,NaN,NaN,-61.987936,-75.553999,2.599703,-483613200.0
20,NaN,NaN,37.137813,NaN,NaN,42.849898,41.156084,39.462270,NaN,NaN,-49.633948,-63.087100,2.602417,-353697600.0
21,NaN,NaN,38.494784,NaN,NaN,42.910293,41.103485,39.296676,NaN,NaN,-41.626612,-51.082832,2.600384,-164774400.0
22,NaN,NaN,25.947936,NaN,NaN,43.228472,40.955378,38.682284,NaN,NaN,-40.766165,-44.008909,2.560087,-511149600.0
23,NaN,NaN,21.743918,NaN,NaN,43.578810,40.736586,37.894362,NaN,NaN,-38.059500,-40.150759,2.593455,-802103600.0
24,NaN,NaN,39.079669,NaN,NaN,43.590206,40.602781,37.615356,NaN,NaN,-24.766643,-34.530769,2.689294,-529128400.0
25,NaN,NaN,34.666393,NaN,NaN,43.652099,40.427960,37.203821,NaN,NaN,-14.972484,-25.932876,2.662140,-735562800.0
26,NaN,NaN,30.066705,NaN,NaN,43.790969,40.201722,36.612476,NaN,NaN,-13.427869,-17.722332,2.652999,-953124800.0
27,NaN,NaN,34.135045,NaN,NaN,43.765506,39.986213,36.206920,NaN,NaN,-15.615473,-14.671942,2.663106,-670434400.0
28,NaN,NaN,45.513671,NaN,NaN,43.544880,39.824080,36.103281,NaN,NaN,-6.294988,-11.779444,2.747589,-427156400.0
29,NaN,NaN,48.015979,NaN,NaN,43.330498,39.691932,36.053365,NaN,NaN,11.072710,-3.612584,2.734579,-296959600.0
30,NaN,NaN,52.392795,NaN,NaN,42.991930,39.561347,36.130764,NaN,NaN,26.336998,10.371573,2.744683,-134380000.0
31,NaN,NaN,59.246612,NaN,NaN,42.753750,39.495571,36.237393,NaN,NaN,41.539747,26.316485,2.801799,70208800.0
32,NaN,NaN,58.345159,NaN,NaN,42.524610,39.432605,36.340600,NaN,NaN,51.997607,39.958117,2.790443,-90495600.0
33,-0.373864,-0.940886,57.371744,NaN,NaN,42.339133,39.380013,36.420893,NaN,NaN,56.241838,49.926398,2.779394,-226217600.0
34,-0.274210,-0.807550,56.017898,NaN,NaN,42.113877,39.317691,36.521504,NaN,NaN,52.331290,53.523579,2.776466,-376104000.0
35,-0.165931,-0.679226,57.975695,NaN,NaN,42.071535,39.305673,36.539811,NaN,NaN,52.421469,53.664866,2.783937,-252136400.0
36,-0.022399,-0.547861,61.815789,NaN,NaN,42.278021,39.366022,36.454023,NaN,NaN,56.395036,53.715931,2.796986,-116886800.0
37,0.156014,-0.407086,65.717907,NaN,NaN,42.641726,39.462826,36.283926,NaN,NaN,62.381577,57.066027,2.825025,35762000.0
38,0.283037,-0.269061,64.530836,NaN,NaN,43.012919,39.594707,36.176495,NaN,NaN,65.108369,61.294994,2.811691,-119950400.0
39,0.374218,-0.140405,63.951788,NaN,NaN,43.346788,39.735087,36.123386,NaN,NaN,64.320013,63.936653,2.811644,-271078800.0
40,0.382314,-0.035862,57.527340,NaN,NaN,43.527906,39.833000,36.138094,NaN,NaN,59.272780,62.900387,2.801178,-466286800.0
41,0.407212,0.052753,59.237562,NaN,NaN,43.735164,39.941136,36.147108,NaN,NaN,52.309047,58.633947,2.782215,-312470800.0
42,0.433628,0.128928,60.109585,NaN,NaN,43.918535,40.142563,36.366590,NaN,NaN,42.550415,51.377414,2.769806,-198865200.0
43,0.446542,0.192451,59.770943,NaN,NaN,43.949835,40.389608,36.829381,40.596319,40.596319,34.222944,43.027469,2.757048,-294019200.0
44,0.420517,0.238064,56.052912,4.051362,0.82354,44.028288,40.539885,37.051483,40.615036,40.638546,12.020059,29.597806,2.704888,-420833200.0

In [112]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722874
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715771
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904900
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370628
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216972
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212234
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202774
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436817
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864704
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651939
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339878
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377701
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188580
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843426
14,NaN,NaN,68.998111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724165,117105600.0,41.852882
15,NaN,NaN,55.580682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0,41.186226
16,NaN,NaN,45.152378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695098,-253430800.0,40.451004
17,NaN,NaN,46.541660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034648,-73.817992,2.684662,-96858800.0,40.545567
18,NaN,NaN,37.470435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639414,-81.393427,2.635360,-299420400.0,39.706341
19,NaN,NaN,35.398312,NaN,NaN,42.761514,41.213176,39.664837,NaN,NaN,-61.987936,-75.553999,2.599703,-483613200.0,39.472294
20,NaN,NaN,37.137813,NaN,NaN,42.849898,41.156084,39.462270,NaN,NaN,-49.633948,-63.087100,2.602417,-353697600.0,39.581043
21,NaN,NaN,38.494784,NaN,NaN,42.910293,41.103485,39.296676,NaN,NaN,-41.626612,-51.082832,2.600384,-164774400.0,39.663784
22,NaN,NaN,25.947936,NaN,NaN,43.228472,40.955378,38.682284,NaN,NaN,-40.766165,-44.008909,2.560087,-511149600.0,37.942764
23,NaN,NaN,21.743918,NaN,NaN,43.578810,40.736586,37.894362,NaN,NaN,-38.059500,-40.150759,2.593455,-802103600.0,36.994793
24,NaN,NaN,39.079669,NaN,NaN,43.590206,40.602781,37.615356,NaN,NaN,-24.766643,-34.530769,2.689294,-529128400.0,38.540863
25,NaN,NaN,34.666393,NaN,NaN,43.652099,40.427960,37.203821,NaN,NaN,-14.972484,-25.932876,2.662140,-735562800.0,37.715828
26,NaN,NaN,30.066705,NaN,NaN,43.790969,40.201722,36.612476,NaN,NaN,-13.427869,-17.722332,2.652999,-953124800.0,36.678013
27,NaN,NaN,34.135045,NaN,NaN,43.765506,39.986213,36.206920,NaN,NaN,-15.615473,-14.671942,2.663106,-670434400.0,37.126633
28,NaN,NaN,45.513671,NaN,NaN,43.544880,39.824080,36.103281,NaN,NaN,-6.294988,-11.779444,2.747589,-427156400.0,38.622051
29,NaN,NaN,48.015979,NaN,NaN,43.330498,39.691932,36.053365,NaN,NaN,11.072710,-3.612584,2.734579,-296959600.0,39.008965
30,NaN,NaN,52.392795,NaN,NaN,42.991930,39.561347,36.130764,NaN,NaN,26.336998,10.371573,2.744683,-134380000.0,39.728184
31,NaN,NaN,59.246612,NaN,NaN,42.753750,39.495571,36.237393,NaN,NaN,41.539747,26.316485,2.801799,70208800.0,41.062187
32,NaN,NaN,58.345159,NaN,NaN,42.524610,39.432605,36.340600,NaN,NaN,51.997607,39.958117,2.790443,-90495600.0,40.929249
33,-0.373864,-0.940886,57.371744,NaN,NaN,42.339133,39.380013,36.420893,NaN,NaN,56.241838,49.926398,2.779394,-226217600.0,40.791595
34,-0.274210,-0.807550,56.017898,NaN,NaN,42.113877,39.317691,36.521504,NaN,NaN,52.331290,53.523579,2.776466,-376104000.0,40.606434
35,-0.165931,-0.679226,57.975695,NaN,NaN,42.071535,39.305673,36.539811,NaN,NaN,52.421469,53.664866,2.783937,-252136400.0,40.945873
36,-0.022399,-0.547861,61.815789,NaN,NaN,42.278021,39.366022,36.454023,NaN,NaN,56.395036,53.715931,2.796986,-116886800.0,41.657978
37,0.156014,-0.407086,65.717907,NaN,NaN,42.641726,39.462826,36.283926,NaN,NaN,62.381577,57.066027,2.825025,35762000.0,42.481644
38,0.283037,-0.269061,64.530836,NaN,NaN,43.012919,39.594707,36.176495,NaN,NaN,65.108369,61.294994,2.811691,-119950400.0,42.343967
39,0.374218,-0.140405,63.951788,NaN,NaN,43.346788,39.735087,36.123386,NaN,NaN,64.320013,63.936653,2.811644,-271078800.0,42.279884
40,0.382314,-0.035862,57.527340,NaN,NaN,43.527906,39.833000,36.138094,NaN,NaN,59.272780,62.900387,2.801178,-466286800.0,41.539303
41,0.407212,0.052753,59.237562,NaN,NaN,43.735164,39.941136,36.147108,NaN,NaN,52.309047,58.633947,2.782215,-312470800.0,41.826511
42,0.433628,0.128928,60.109585,NaN,NaN,43.918535,40.142563,36.366590,NaN,NaN,42.550415,51.377414,2.769806,-198865200.0,41.971298
43,0.446542,0.192451,59.770943,NaN,NaN,43.949835,40.389608,36.829381,40.596319,40.596319,34.222944,43.027469,2.757048,-294019200.0,41.935692
44,0.420517,0.238064,56.052912,4.051362,0.82354,44.028288,40.539885,37.051483,40.615036,40.638546,12.020059,29.597806,2.704888,-420833200.0,41.546413

In [113]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.420517,0.238064,56.052912,4.051362,0.823540,44.028288,40.539885,37.051483,40.615036,40.638546,12.020059,29.597806,2.704888,-4.208332e+08,41.546413
1,0.431503,0.276752,59.233517,6.192273,1.284019,44.042948,40.754083,37.465218,40.644218,40.699045,-9.379590,12.287804,2.706938,-3.257368e+08,41.999790
2,0.492754,0.319952,63.732478,9.481629,1.816479,43.867406,41.056252,38.245097,40.685502,40.788927,-18.948467,-5.435999,2.727886,-1.969960e+08,42.721378
3,0.568075,0.369577,66.042461,11.303189,1.763767,43.662505,41.356640,39.050774,40.725588,40.893170,-6.400702,-11.576253,2.738474,-6.816760e+07,43.134396
4,0.587478,0.413157,61.780488,9.044897,1.502037,43.567673,41.561488,39.555302,40.759725,40.974318,1.684858,-7.888104,2.738627,-1.949416e+08,42.719009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [114]:
indicators_with_price['Next_Adj_Close'] = indicators_with_price['Adj Close'].shift(-1)
indicators_with_price['Signal'] = (indicators_with_price['Next_Adj_Close'] > indicators_with_price['Adj Close']).astype(int)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Next_Adj_Close,Signal
0,0.420517,0.238064,56.052912,4.051362,0.823540,44.028288,40.539885,37.051483,40.615036,40.638546,12.020059,29.597806,2.704888,-4.208332e+08,41.546413,41.999790,1
1,0.431503,0.276752,59.233517,6.192273,1.284019,44.042948,40.754083,37.465218,40.644218,40.699045,-9.379590,12.287804,2.706938,-3.257368e+08,41.999790,42.721378,1
2,0.492754,0.319952,63.732478,9.481629,1.816479,43.867406,41.056252,38.245097,40.685502,40.788927,-18.948467,-5.435999,2.727886,-1.969960e+08,42.721378,43.134396,1
3,0.568075,0.369577,66.042461,11.303189,1.763767,43.662505,41.356640,39.050774,40.725588,40.893170,-6.400702,-11.576253,2.738474,-6.816760e+07,43.134396,42.719009,0
4,0.587478,0.413157,61.780488,9.044897,1.502037,43.567673,41.561488,39.555302,40.759725,40.974318,1.684858,-7.888104,2.738627,-1.949416e+08,42.719009,42.355846,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,188.630005,1
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,191.559998,1
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,193.889999,1
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,195.179993,1
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,NaN,0

In [115]:
indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close'])
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Signal
0,0.420517,0.238064,56.052912,4.051362,0.823540,44.028288,40.539885,37.051483,40.615036,40.638546,12.020059,29.597806,2.704888,-4.208332e+08,41.546413,1
1,0.431503,0.276752,59.233517,6.192273,1.284019,44.042948,40.754083,37.465218,40.644218,40.699045,-9.379590,12.287804,2.706938,-3.257368e+08,41.999790,1
2,0.492754,0.319952,63.732478,9.481629,1.816479,43.867406,41.056252,38.245097,40.685502,40.788927,-18.948467,-5.435999,2.727886,-1.969960e+08,42.721378,1
3,0.568075,0.369577,66.042461,11.303189,1.763767,43.662505,41.356640,39.050774,40.725588,40.893170,-6.400702,-11.576253,2.738474,-6.816760e+07,43.134396,0
4,0.587478,0.413157,61.780488,9.044897,1.502037,43.567673,41.561488,39.555302,40.759725,40.974318,1.684858,-7.888104,2.738627,-1.949416e+08,42.719009,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,1
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,1
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,1
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,1
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,0

In [116]:
y = indicators_with_price["Adj Close"]
y_2 = indicators_with_price["SMA"]
y_3 = indicators_with_price["EMA"]
y_4 = indicators_with_price["Upper_BB"]
y_5 = indicators_with_price["Middle_BB"]
y_6 = indicators_with_price["Lower_BB"]
X = np.array(date)

trace = go.Scatter(x=X, y=y, mode="lines+markers", name="Adj Close")
trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



layout = go.Layout(
    title='Stock Price and Volume',
    xaxis=dict(title='Date'),
    yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
    yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
    height=600,
)

fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# Show plot
pyo.iplot(fig)

In [117]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        # Extract a window of data from X
        X_window = self.X[idx : idx + self.window_size]
        
        # Assuming you're predicting the value right after the window
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [118]:
X = indicators_with_price.iloc[:, :-1]
y = indicators_with_price.iloc[:,-2]

signal_true = indicators_with_price.iloc[:,-1]
y

0        41.546413
1        41.999790
2        42.721378
3        43.134396
4        42.719009
           ...
1475    182.679993
1476    188.630005
1477    191.559998
1478    193.889999
1479    195.179993
Name: Adj Close, Length: 1480, dtype: float64

In [119]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1184    1
1185    1
1186    0
1187    1
1188    1
       ..
1475    1
1476    1
1477    1
1478    1
1479    0
Name: Signal, Length: 296, dtype: int64

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
# X_train = X_train.to_numpy()
# y_train = y_train.to_numpy()
len(y_test)

296

In [121]:
# # Get the count of each unique value in the series
# category_counts = y_train.value_counts()
# print(category_counts.index)
# print(category_counts.values)

# # Create bar plot
# plt.bar(["1","0"], category_counts.values)

# # Adding labels and title
# plt.xlabel('Category')
# plt.ylabel('Frequency')
# plt.title('Distribution of Categories')

# # Show plot
# plt.show()

In [122]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

for column in X_train.columns:
    # Initialize a scaler
    scaler = MinMaxScaler()
    
    # Fit on the training data and transform it
    X_train_scaled = scaler.fit_transform(X_train[column].to_numpy().reshape(-1, 1))
    X_train_df[column] = X_train_scaled.flatten()
    
    # Transform the test data using the same scaler
    X_test_scaled = scaler.transform(X_test[column].to_numpy().reshape(-1, 1))
    X_test_df[column] = X_test_scaled.flatten()

    scaler_dict[column] = scaler

    

X_train_df.head(24)

y_train_df = X_train_df["Adj Close"]
y_test_df = X_test_df["Adj Close"]
features = X_train_df.columns
X_test_df

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.473178,0.391409,0.484407,0.368317,0.443981,0.810260,0.788953,0.749683,0.804887,0.832500,0.850519,0.839325,0.765326,0.761787,0.780636
1,0.499847,0.411144,0.517395,0.387564,0.487570,0.813419,0.791684,0.751875,0.804933,0.833706,0.876575,0.853920,0.764804,0.775662,0.793797
2,0.523637,0.432238,0.527282,0.393264,0.448749,0.816205,0.793223,0.752021,0.804433,0.835055,0.895160,0.867699,0.724522,0.788577,0.797684
3,0.523008,0.448973,0.456308,0.359880,0.379729,0.815520,0.792793,0.751879,0.802963,0.835217,0.907286,0.887937,0.685712,0.778442,0.775317
4,0.534244,0.464868,0.497612,0.382098,0.444493,0.813808,0.792104,0.752318,0.802403,0.836117,0.913913,0.901248,0.661728,0.787383,0.790115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,0.331987,0.360467,0.219195,0.330143,0.438975,1.105702,1.104494,1.078159,1.146372,1.152418,0.696649,0.699736,0.263755,0.912203,1.018693
292,0.358007,0.354748,0.456178,0.434230,0.530971,1.099583,1.101858,1.079371,1.147028,1.152792,0.728273,0.697238,0.316961,0.925666,1.059493
293,0.396416,0.358741,0.541663,0.480565,0.534505,1.093074,1.099905,1.082407,1.147734,1.154161,0.814261,0.731129,0.316623,0.937531,1.079584
294,0.440664,0.371807,0.601115,0.515680,0.555951,1.091863,1.099564,1.083018,1.148741,1.156274,0.926300,0.813002,0.323439,0.947909,1.095561
295,0.483036,0.391711,0.631899,0.534630,0.550955,1.092553,1.099746,1.082644,1.149678,1.158738,0.984412,0.904318,0.300461,0.955220,1.104407

In [123]:
scaler_dict

{'MACD': MinMaxScaler(),
 'MACD_signal': MinMaxScaler(),
 'RSI': MinMaxScaler(),
 'CMO': MinMaxScaler(),
 'MOM': MinMaxScaler(),
 'Upper_BB': MinMaxScaler(),
 'Middle_BB': MinMaxScaler(),
 'Lower_BB': MinMaxScaler(),
 'SMA': MinMaxScaler(),
 'EMA': MinMaxScaler(),
 'SLOWK': MinMaxScaler(),
 'SLOWD': MinMaxScaler(),
 'ATR': MinMaxScaler(),
 'OBV': MinMaxScaler(),
 'Adj Close': MinMaxScaler()}

In [124]:
correlation_matrix = X_train_df.corr()

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values,  # Rounded values for display
                    texttemplate="%{text}",
                    textfont={"size":9}  # Adjust text size if necessary
                    ))

# Update the layout
fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  # or any width you desire
    height=1000,  # or any height you desire
)

# Show the figure
pyo.iplot(fig)

In [125]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train_df.to_numpy(), dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test_df.to_numpy(), dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(1)[0])

tensor(0.7283, device='cuda:0')
tensor([[0.4998, 0.4111, 0.5174, 0.3876, 0.4876, 0.8134, 0.7917, 0.7519, 0.8049,
         0.8337, 0.8766, 0.8539, 0.7648, 0.7757, 0.7938],
        [0.5236, 0.4322, 0.5273, 0.3933, 0.4487, 0.8162, 0.7932, 0.7520, 0.8044,
         0.8351, 0.8952, 0.8677, 0.7245, 0.7886, 0.7977],
        [0.5230, 0.4490, 0.4563, 0.3599, 0.3797, 0.8155, 0.7928, 0.7519, 0.8030,
         0.8352, 0.9073, 0.8879, 0.6857, 0.7784, 0.7753],
        [0.5342, 0.4649, 0.4976, 0.3821, 0.4445, 0.8138, 0.7921, 0.7523, 0.8024,
         0.8361, 0.9139, 0.9012, 0.6617, 0.7874, 0.7901],
        [0.5474, 0.4805, 0.5145, 0.3912, 0.4671, 0.8153, 0.7928, 0.7521, 0.8022,
         0.8373, 0.9235, 0.9113, 0.6236, 0.7974, 0.7962],
        [0.5399, 0.4914, 0.4472, 0.3605, 0.4592, 0.8163, 0.7941, 0.7537, 0.8018,
         0.8374, 0.9237, 0.9172, 0.5981, 0.7914, 0.7760],
        [0.5112, 0.4936, 0.3677, 0.3216, 0.4080, 0.8078, 0.7900, 0.7546, 0.8007,
         0.8361, 0.8756, 0.9035, 0.5869, 0.7794, 0.7495],
        [0.4709, 0.4865, 0.3118, 0.2921, 0.3590, 0.8019, 0.7857, 0.7521, 0.7990,
         0.8339, 0.7960, 0.8581, 0.5854, 0.7650, 0.7287],
        [0.4782, 0.4824, 0.4544, 0.3639, 0.4654, 0.8000, 0.7849, 0.7524, 0.7987,
         0.8341, 0.7774, 0.8059, 0.6453, 0.7842, 0.7755],
        [0.4855, 0.4807, 0.4597, 0.3667, 0.5578, 0.8016, 0.7861, 0.7533, 0.7997,
         0.8344, 0.7888, 0.7750, 0.6088, 0.7965, 0.7774],
        [0.4882, 0.4800, 0.4490, 0.3617, 0.6035, 0.8012, 0.7895, 0.7605, 0.8014,
         0.8345, 0.8188, 0.7831, 0.5723, 0.7852, 0.7740],
        [0.4834, 0.4783, 0.4231, 0.3496, 0.5378, 0.7993, 0.7924, 0.7687, 0.8022,
         0.8343, 0.7983, 0.7906, 0.5827, 0.7733, 0.7659],
        [0.4583, 0.4714, 0.3463, 0.3124, 0.4486, 0.7969, 0.7939, 0.7742, 0.8017,
         0.8327, 0.7377, 0.7723, 0.5960, 0.7621, 0.7405],
        [0.4275, 0.4590, 0.3088, 0.2931, 0.4211, 0.7958, 0.7944, 0.7765, 0.8008,
         0.8305, 0.6628, 0.7167, 0.5765, 0.7501, 0.7271],
        [0.4137, 0.4460, 0.3519, 0.3121, 0.4535, 0.7862, 0.7972, 0.7927, 0.8003,
         0.8291, 0.6220, 0.6538, 0.5583, 0.7608, 0.7388],
        [0.4007, 0.4327, 0.3416, 0.3072, 0.5122, 0.7872, 0.7955, 0.7881, 0.8007,
         0.8275, 0.6178, 0.6111, 0.5622, 0.7477, 0.7354],
        [0.4045, 0.4229, 0.4019, 0.3333, 0.5364, 0.7852, 0.7936, 0.7864, 0.8015,
         0.8268, 0.6636, 0.6114, 0.5462, 0.7599, 0.7513],
        [0.4138, 0.4171, 0.4266, 0.3443, 0.5657, 0.7842, 0.7926, 0.7854, 0.8026,
         0.8264, 0.7016, 0.6398, 0.5764, 0.7761, 0.7580],
        [0.4089, 0.4114, 0.3718, 0.3205, 0.5461, 0.7816, 0.7901, 0.7831, 0.8035,
         0.8253, 0.7177, 0.6754, 0.5921, 0.7619, 0.7426],
        [0.3676, 0.3977, 0.2382, 0.2535, 0.4085, 0.7853, 0.7857, 0.7701, 0.8024,
         0.8220, 0.6670, 0.6766, 0.6206, 0.7448, 0.6968],
        [0.3250, 0.3771, 0.2052, 0.2347, 0.4402, 0.7869, 0.7798, 0.7563, 0.8018,
         0.8181, 0.6070, 0.6429, 0.6081, 0.7171, 0.6833],
        [0.2812, 0.3510, 0.1712, 0.2147, 0.3655, 0.7876, 0.7730, 0.7415, 0.8001,
         0.8136, 0.5756, 0.5922, 0.5959, 0.7034, 0.6687],
        [0.2486, 0.3227, 0.1700, 0.2140, 0.3484, 0.7892, 0.7673, 0.7281, 0.7982,
         0.8093, 0.5907, 0.5650, 0.5762, 0.6900, 0.6682],
        [0.2435, 0.2990, 0.2674, 0.2523, 0.3853, 0.7841, 0.7620, 0.7227, 0.7968,
         0.8063, 0.6254, 0.5716, 0.5879, 0.7049, 0.6897],
        [0.2238, 0.2756, 0.2091, 0.2214, 0.3520, 0.7784, 0.7552, 0.7149, 0.7950,
         0.8023, 0.6347, 0.5927, 0.5853, 0.6914, 0.6677],
        [0.2090, 0.2536, 0.2026, 0.2178, 0.3005, 0.7750, 0.7494, 0.7066, 0.7924,
         0.7984, 0.6337, 0.6080, 0.5572, 0.6804, 0.6652],
        [0.1900, 0.2318, 0.1704, 0.2003, 0.2520, 0.7754, 0.7442, 0.6956, 0.7891,
         0.7940, 0.6029, 0.6000, 0.5297, 0.6685, 0.6527],
        [0.1556, 0.2067, 0.1075, 0.1632, 0.1687, 0.7799, 0.7388, 0.6795, 0.7847,
         0.7885, 0.5879, 0.5833, 0.5433, 0.6538, 0.6255],
        [0.1525, 0.1859, 0.2212, 0.2082, 0.2481, 0.7734, 0.7321, 0.6728, 0.7814,
         0.7844, 0.5958, 0.5698, 0.5557, 0.6668, 0.6498],
        [0.1555, 0.1699, 0.2309, 0.2122, 0.3070, 0.7647, 0.7255, 0.6687, 0.7789,
         0.7806, 0.6128, 0.5733, 0.5256, 0.6801, 0.6520],
        [0.1339, 0.1523, 0.1491, 0.1668, 0.1158, 0.7577, 0.7173, 0.6593, 0.7737,
         0.7753, 0.6174, 0.5839, 0.5644, 0.6608, 0.6189],
        [0.1280, 0.1369, 0.1898, 0.1832, 0.1605, 0.7491, 0.7100, 0.6536, 0.7691,
         0.7707, 0.6084, 0.5883, 0.5617, 0.6761, 0.6277],
        [0.1197, 0.1227, 0.1673, 0.1708, 0.1768, 0.7445, 0.7035, 0.6454, 0.7648,
         0.7658, 0.5885, 0.5796, 0.5389, 0.6622, 0.6185],
        [0.1434, 0.1167, 0.3052, 0.2288, 0.3005, 0.7391, 0.6994, 0.6428, 0.7622,
         0.7627, 0.6410, 0.5880, 0.5646, 0.6773, 0.6499],
        [0.1686, 0.1175, 0.3198, 0.2353, 0.3813, 0.7308, 0.6949, 0.6425, 0.7608,
         0.7599, 0.6945, 0.6188, 0.5655, 0.6895, 0.6535],
        [0.1951, 0.1240, 0.3365, 0.2425, 0.3916, 0.7222, 0.6908, 0.6433, 0.7595,
         0.7575, 0.7638, 0.6813, 0.5445, 0.7006, 0.6575],
        [0.2347, 0.1381, 0.4132, 0.2767, 0.4185, 0.7093, 0.6868, 0.6492, 0.7585,
         0.7561, 0.8140, 0.7430, 0.5309, 0.7126, 0.6763],
        [0.2680, 0.1568, 0.4111, 0.2759, 0.4105, 0.6915, 0.6825, 0.6595, 0.7575,
         0.7548, 0.8756, 0.8075, 0.5074, 0.7002, 0.6758],
        [0.3040, 0.1797, 0.4490, 0.2927, 0.4830, 0.6765, 0.6794, 0.6695, 0.7575,
         0.7540, 0.9451, 0.8721, 0.4925, 0.7102, 0.6850],
        [0.3408, 0.2063, 0.4816, 0.3075, 0.3519, 0.6757, 0.6792, 0.6699, 0.7556,
         0.7536, 0.9697, 0.9276, 0.4790, 0.7212, 0.6930],
        [0.3670, 0.2334, 0.4586, 0.2993, 0.3087, 0.6765, 0.6795, 0.6696, 0.7532,
         0.7530, 0.9536, 0.9554, 0.4712, 0.7092, 0.6880],
        [0.3890, 0.2600, 0.4604, 0.3001, 0.3267, 0.6791, 0.6805, 0.6689, 0.7509,
         0.7524, 0.9231, 0.9476, 0.4465, 0.7192, 0.6884],
        [0.4219, 0.2886, 0.5376, 0.3335, 0.3368, 0.6851, 0.6825, 0.6665, 0.7489,
         0.7528, 0.9317, 0.9341, 0.4445, 0.7331, 0.7062],
        [0.4667, 0.3215, 0.6197, 0.3738, 0.3912, 0.6937, 0.6846, 0.6614, 0.7476,
         0.7542, 0.9518, 0.9335, 0.4810, 0.7472, 0.7283]], device='cuda:0')

# Vanilla LSTM

In [126]:
class VanillaLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob):
        super(VanillaLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

# Stacked LSTM

In [127]:
class StackedLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, stateful):
        super(StackedLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size
        self.stateful = stateful

        self.hn = None
        self.cn = None

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def reset_hidden_state(self):
        self.hn = None
        self.cn = None

    def forward(self, x):
        # If the model is not stateful or it's the first batch (states are None), initialize h0 and c0
        if not self.stateful or self.hn is None:
            h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(x.device)
            c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(x.device)
        else:
            # If the model is stateful and it's not the first batch, use the stored states
            h0, c0 = self.hn, self.cn

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        if self.stateful:
            self.hn, self.cn = hn.detach(), cn.detach()

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

# Bidirectional LSTM

# 1D CNN-LSTM

In [128]:
class OneDimCNNLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, conv_channels, kernel_size, pool_size, stride):
        super(OneDimCNNLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # Convolutional Layer
        self.conv1 = nn.Conv1d(in_channels=input_dim, out_channels=conv_channels, kernel_size=kernel_size)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool1d(kernel_size=pool_size, stride=pool_size)

        self.conv2 = nn.Conv1d(in_channels=conv_channels, out_channels=conv_channels*2, kernel_size=kernel_size)
        self.relu2 = nn.ReLU()
        self.maxpool2 = nn.MaxPool1d(kernel_size=2, stride=2)


        self.lstm = nn.LSTM(input_size = conv_channels*2, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # CNN in_dim: (batch_size, in_channels, length)
        x = x.transpose(1, 2)

        # Conv layer forward propagate
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.maxpool1(x)

        x = self.conv2(x)
        x = self.relu2(x)
        x = self.maxpool2(x)

        # LSTM in_dim: (batch_size, seq_len, input_size)
        x = x.transpose(1, 2)

        assert x.size(-1) == self.lstm.input_size, f"Mismatch in LSTM input size. Expected: {self.lstm.input_size}, Got: {x.size(-1)}"

        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

In [129]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device, model_type):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model_type = model_type
        self.model = None
        self.optimizer = None
        self.criterion = nn.MSELoss()

    
    def train_validate(self, config, trial):

        if self.model_type == "Vanilla LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):

                    data, target = data.to(self.device), target.to(self.device)
                    target = target.view(-1, 1)  # Reshape target to have an extra dimension


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.view(-1, 1)

                        preds = self.model(data)
                        loss = self.criterion(preds, target)

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
        if self.model_type == "Vanilla LSTM":

            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1, 1)  # Reshape target to have an extra dimension

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1, 1)
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                all_preds.extend(preds.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [130]:
model_type = "Stacked LSTM"

def objective(trial):
    if model_type == "Vanilla LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.15),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 10, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9)
        }

    elif model_type == "Stacked LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "num_layers": trial.suggest_int("num_layers", 1, 5)
        }

    elif model_type == "1D CNN-LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "conv_channels": trial.suggest_int("conv_channels", 16, 128),
            "kernel_size": trial.suggest_int("kernel_size", 2, 6),
            "num_layers": trial.suggest_int("num_layers", 1, 5),
            "pool_size": trial.suggest_int("pool_size", 2, 5),
            "stride": trial.suggest_int("stride", 1, 4)
        }

    trainer = ModelActioner(train_data, test_data, device, model_type)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [131]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=40, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    # Optionally, you can include additional information in the progress bar
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=40, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-26 13:12:03,229] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/40 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.015491704922169447, val_loss: 0.021475601941347122
epochs 2/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.015188372693955898, val_loss: 0.02109705563634634
epochs 3/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.015601668041199446, val_loss: 0.02072245953604579
epochs 4/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.014754651580005884, val_loss: 0.02035200409591198
epochs 5/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.014167014043778181, val_loss: 0.019986337050795555
epochs 6/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.013959396630525589, val_loss: 0.019624963402748108
epochs 7/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.013510598801076412, val_loss: 0.019268137402832508
epochs 8/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.013261628337204456, val_loss: 0.018915643449872732
epochs 9/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.01325550302863121, val_loss: 0.018567099701613188
epochs 10/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.012984333094209433, val_loss: 0.018222562037408352
epochs 11/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.01262318529188633, val_loss: 0.017882474698126316
epochs 12/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.012565005104988813, val_loss: 0.017546314280480146
epochs 13/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.011654096655547619, val_loss: 0.01721546147018671
epochs 14/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.011766328476369381, val_loss: 0.016889539547264576
epochs 15/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.011930101085454226, val_loss: 0.016567650251090527
epochs 16/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.01155770430341363, val_loss: 0.016250003594905138
epochs 17/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.011136988177895546, val_loss: 0.015936799813061953
epochs 18/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.011104785837233067, val_loss: 0.01562781073153019
epochs 19/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.010396730154752731, val_loss: 0.015323797706514597
epochs 20/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.010561947245150805, val_loss: 0.015024163760244846
epochs 21/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.01018856093287468, val_loss: 0.01472918875515461
epochs 22/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.009512885706499219, val_loss: 0.014439747203141451
epochs 23/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.009992151521146297, val_loss: 0.014154389034956694
epochs 24/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.009364660596475005, val_loss: 0.013873415999114513
epochs 25/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.009533698204904795, val_loss: 0.01359628839418292
epochs 26/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.009398359106853604, val_loss: 0.013322876766324043
epochs 27/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.008904399815946817, val_loss: 0.013053917326033115
epochs 28/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.008840292459353805, val_loss: 0.01278921402990818
epochs 29/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.007959251292049885, val_loss: 0.01252991915680468
epochs 30/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.008448289707303047, val_loss: 0.012274080887436867
epochs 31/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.008296424988657236, val_loss: 0.012022225884720683
epochs 32/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.007763825124129653, val_loss: 0.011774585582315922
epochs 33/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00774394441395998, val_loss: 0.011531147407367826
epochs 34/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.007705065421760082, val_loss: 0.01129135093651712
epochs 35/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0077449672389775515, val_loss: 0.011055059498175979
epochs 36/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00736864167265594, val_loss: 0.01082228752784431
epochs 37/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.007512213196605444, val_loss: 0.01059250277467072
epochs 38/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.007158280815929174, val_loss: 0.01036665984429419
epochs 39/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00681159202940762, val_loss: 0.010144756874069571
epochs 40/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.006651878589764237, val_loss: 0.00992671656422317
epochs 41/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.006939252372831106, val_loss: 0.009711737977340817
epochs 42/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.006703137187287211, val_loss: 0.009499813430011272
epochs 43/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.006209588143974543, val_loss: 0.00929196341894567
epochs 44/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0059009091928601265, val_loss: 0.009088634746149182
epochs 45/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.006083709187805653, val_loss: 0.008888782234862447
epochs 46/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.005726169794797897, val_loss: 0.008692814270034432
epochs 47/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.005731482291594148, val_loss: 0.008500647731125355
epochs 48/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.005608989158645272, val_loss: 0.008311965502798557
epochs 49/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.005526782711967826, val_loss: 0.008126860484480858
epochs 50/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.005456333747133613, val_loss: 0.007944918237626553
epochs 51/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0053754388354718685, val_loss: 0.0077657748479396105
epochs 52/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0051102410070598125, val_loss: 0.007589829037897289
epochs 53/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0051940560806542635, val_loss: 0.007416988257318735
epochs 54/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.004999362863600254, val_loss: 0.007246932364068925
epochs 55/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.004801233997568488, val_loss: 0.007080151583068073
epochs 56/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.004512324696406722, val_loss: 0.006917103077284992
epochs 57/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.004577461862936616, val_loss: 0.006757327122613788
epochs 58/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.004627990652807057, val_loss: 0.006600193213671446
epochs 59/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0041556020732969046, val_loss: 0.006446958403103054
epochs 60/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0040987590327858925, val_loss: 0.006297338288277388
epochs 61/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.004126382642425597, val_loss: 0.006150312139652669
epochs 62/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.003944103140383959, val_loss: 0.00600664340890944
epochs 63/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.003868440166115761, val_loss: 0.005866453517228365
epochs 64/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.003881548414938152, val_loss: 0.005728900199756026
epochs 65/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.003935529966838658, val_loss: 0.005593455862253904
epochs 66/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0035726313944905996, val_loss: 0.005460921674966812
epochs 67/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0032778094755485654, val_loss: 0.0053322582971304655
epochs 68/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0037175380857661366, val_loss: 0.005205704597756267
epochs 69/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.003333635744638741, val_loss: 0.005082030431367457
epochs 70/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0034959045005962253, val_loss: 0.004960782243870199
epochs 71/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0031493729911744595, val_loss: 0.00484248751308769
epochs 72/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.002940724487416446, val_loss: 0.004727002640720457
epochs 73/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0030388106824830174, val_loss: 0.004614449688233435
epochs 74/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.002785322838462889, val_loss: 0.004504861950408667
epochs 75/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0027917540865018964, val_loss: 0.004398082091938704
epochs 76/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0029841673094779253, val_loss: 0.004293693404179066
epochs 77/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0026778519386425614, val_loss: 0.00419177149888128
epochs 78/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.002770376275293529, val_loss: 0.004092039191164076
epochs 79/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0025602598907426, val_loss: 0.0039947518380358815
epochs 80/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.002611967851407826, val_loss: 0.0038996204384602606
epochs 81/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.002696133335120976, val_loss: 0.003806509485002607
epochs 82/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.002537504071369767, val_loss: 0.003715474216733128
epochs 83/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0023455576738342643, val_loss: 0.00362716504605487
epochs 84/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0022681865375488997, val_loss: 0.003541402576956898
epochs 85/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00230408925563097, val_loss: 0.0034578657941892743
epochs 86/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0022034109570086002, val_loss: 0.003377112268935889
epochs 87/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.002093226299621165, val_loss: 0.003298613883089274
epochs 88/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00227188877761364, val_loss: 0.0032215281389653683
epochs 89/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.002075464348308742, val_loss: 0.0031469616224057972
epochs 90/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0020547910826280713, val_loss: 0.003074615524383262
epochs 91/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0018975340644828975, val_loss: 0.0030046402534935623
epochs 92/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.002173982677049935, val_loss: 0.0029355633596424013
epochs 93/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0019858451560139656, val_loss: 0.0028678528615273535
epochs 94/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0018252632580697536, val_loss: 0.0028022076876368374
epochs 95/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.001859439304098487, val_loss: 0.0027382889529690146
epochs 96/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0018763739499263465, val_loss: 0.0026762102206703275
epochs 97/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0017399622593075037, val_loss: 0.002615924982819706
epochs 98/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0018420816049911082, val_loss: 0.0025575390900485218
epochs 99/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0017703110352158546, val_loss: 0.002500805101590231
epochs 100/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0017760078189894557, val_loss: 0.002445427526254207
epochs 101/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0016692879144102335, val_loss: 0.0023917171347420663
epochs 102/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0015517593128606677, val_loss: 0.002339962578844279
epochs 103/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0016088333795778453, val_loss: 0.0022900149633642286
epochs 104/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.001754157361574471, val_loss: 0.002240952366264537
epochs 105/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0015666247345507145, val_loss: 0.002193215215811506
epochs 106/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0014932228368707001, val_loss: 0.0021470629144459963
epochs 107/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00144351419294253, val_loss: 0.0021026610193075612
epochs 108/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.001523433078546077, val_loss: 0.0020597139809979126
epochs 109/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0014363850350491703, val_loss: 0.00201800097420346
epochs 110/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.001397128391545266, val_loss: 0.0019781030277954414
epochs 111/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00141044775955379, val_loss: 0.0019395925337448716
epochs 112/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0012903453898616135, val_loss: 0.001902471631183289
epochs 113/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0013549485593102872, val_loss: 0.0018664586532395333
epochs 114/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.001431486860383302, val_loss: 0.001831429690355435
epochs 115/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0011946907034143806, val_loss: 0.001797754579456523
epochs 116/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.001257325115147978, val_loss: 0.001765563793014735
Starting fold 2:
epochs 1/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0016247926105279475, val_loss: 0.03745564818382263
epochs 2/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0014983348228270188, val_loss: 0.03635398671030998
epochs 3/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0013530413998523727, val_loss: 0.035313885658979416
epochs 4/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0012944523259648122, val_loss: 0.034340073354542255
epochs 5/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.001174577177152969, val_loss: 0.033430387265980244
epochs 6/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0011953854191233404, val_loss: 0.032582471147179604
epochs 7/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0011012446921085939, val_loss: 0.0318053076043725
epochs 8/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0010721944636316039, val_loss: 0.03110313229262829
epochs 9/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.001117419102229178, val_loss: 0.030451804399490356
epochs 10/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009606169405742548, val_loss: 0.029876750893890858
epochs 11/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00098858756973641, val_loss: 0.029371024575084448
epochs 12/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.001021906005917117, val_loss: 0.028951828368008137
epochs 13/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0010126988490810618, val_loss: 0.028603406623005867
epochs 14/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009961527830455452, val_loss: 0.028292341623455286
epochs 15/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009543503256281838, val_loss: 0.02803724491968751
epochs 16/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009685097247711383, val_loss: 0.027840716764330864
epochs 17/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009960199822671711, val_loss: 0.027654768899083138
epochs 18/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009708154684631154, val_loss: 0.027510142419487238
epochs 19/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009038883945322596, val_loss: 0.027388510294258595
epochs 20/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009522756517981179, val_loss: 0.02727118832990527
epochs 21/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009511706593912095, val_loss: 0.02716331509873271
epochs 22/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.000985492930340115, val_loss: 0.02708789287135005
epochs 23/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0008859824374667369, val_loss: 0.0270169866271317
epochs 24/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00089443133038003, val_loss: 0.026944225654006004
epochs 25/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009694381878944114, val_loss: 0.026865510269999504
epochs 26/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009023611637530848, val_loss: 0.026777118910104036
epochs 27/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0010126300330739468, val_loss: 0.02670302288606763
epochs 28/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009430379359400831, val_loss: 0.02663026424124837
epochs 29/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009834948577918112, val_loss: 0.02656365418806672
epochs 30/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009108887970796786, val_loss: 0.026498878840357065
epochs 31/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009279033838538453, val_loss: 0.02643988374620676
epochs 32/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.000916268938453868, val_loss: 0.026357391849160194
epochs 33/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.000872191296366509, val_loss: 0.026248336769640446
epochs 34/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0008843000396154821, val_loss: 0.026172641199082136
epochs 35/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009152425773208961, val_loss: 0.026121543254703283
epochs 36/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0008873770129866898, val_loss: 0.026083956938236952
epochs 37/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009653226443333551, val_loss: 0.026042852085083723
epochs 38/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0008570642385166138, val_loss: 0.026030330918729305
epochs 39/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009493999241385609, val_loss: 0.02602431271225214
epochs 40/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0009220984356943518, val_loss: 0.026026529725641012
epochs 41/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0008796322072157636, val_loss: 0.026024211663752794
epochs 42/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.00088160639279522, val_loss: 0.02601301483809948
epochs 43/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0008609548094682395, val_loss: 0.026011239737272263
epochs 44/116
Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0008813789900159463, val_loss: 0.026006587781012058
epochs 45/116
Current Learning Rate: 1.579787598700664e-05

[I 2024-01-26 13:13:00,026] Trial 0 finished with value: 0.026604424174478607 and parameters: {'batch_size': 95, 'epochs': 116, 'hidden_size': 91, 'learning_rate': 1.579787598700664e-05, 'dropout_prob': 0.08742803388397978, 'weight_decay': 4.62898458132716e-06, 'lr_step_size': 29, 'gamma': 0.5327445559368696, 'num_layers': 1}. Best is trial 0 with value: 0.026604424174478607.

Current Learning Rate: 1.579787598700664e-05
train_loss: 0.0011590053647523746, val_loss: 0.0015053260140120983
Mean validation loss: 0.026604424174478607
Starting fold 1:
epochs 1/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.008939117036367718, val_loss: 0.012349283283478335
epochs 2/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.008125652600766012, val_loss: 0.011657222242731797
epochs 3/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.007814860565122216, val_loss: 0.011012230617435354
epochs 4/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.006982155866602338, val_loss: 0.010410580235092264
epochs 5/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.00691282464816284, val_loss: 0.009845203984724847
epochs 6/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.006275974516756833, val_loss: 0.009314828836604169
epochs 7/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0062062069448936535, val_loss: 0.008816359113705785
epochs 8/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0056358279660344126, val_loss: 0.008351540506670349
epochs 9/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0051448609499187255, val_loss: 0.007920133812647117
epochs 10/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.005074183114399938, val_loss: 0.007520731048364388
epochs 11/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.004723633787484447, val_loss: 0.007149744886708887
epochs 12/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.004558305993467864, val_loss: 0.006805354611654031
epochs 13/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.004315652502823229, val_loss: 0.006486403451938378
epochs 14/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.00402191251908478, val_loss: 0.006193887903109977
epochs 15/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.00377838331562663, val_loss: 0.005925509990438034
epochs 16/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.003723928267381301, val_loss: 0.005680641433910319
epochs 17/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.003441652030328681, val_loss: 0.005455692965341242
epochs 18/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0032236673633298397, val_loss: 0.005250063837554894
epochs 19/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0031365144853847788, val_loss: 0.005061389584290354
epochs 20/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0030606941393527547, val_loss: 0.004887144787139014
epochs 21/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.003081950890267954, val_loss: 0.004725614062657482
epochs 22/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002899662514315232, val_loss: 0.004576971269163646
epochs 23/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0025921683525666596, val_loss: 0.004441360320503775
epochs 24/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0027035671065708524, val_loss: 0.004316645380305617
epochs 25/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002666196606955246, val_loss: 0.004200709885672519
epochs 26/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002596783383112205, val_loss: 0.004094158117904475
epochs 27/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0024410754270655544, val_loss: 0.003997142715869766
epochs 28/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0025067714055215843, val_loss: 0.003907334363382114
epochs 29/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0023656134493649007, val_loss: 0.0038229413183504027
epochs 30/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0023582363213216395, val_loss: 0.003745742303956496
epochs 31/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0024314510868862272, val_loss: 0.0036741871631851323
epochs 32/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002262356185574869, val_loss: 0.0036072674624033664
epochs 33/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002221487794610623, val_loss: 0.0035450611091954144
epochs 34/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002229483515073202, val_loss: 0.003487293042340561
epochs 35/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002110729832202196, val_loss: 0.0034333265214962394
epochs 36/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002065352367629346, val_loss: 0.003382995937901892
epochs 37/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002176302599132453, val_loss: 0.0033354316936119606
epochs 38/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.00204101149850574, val_loss: 0.0032922121156987393
epochs 39/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002078015842524014, val_loss: 0.003252513040053217
epochs 40/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001997860076249038, val_loss: 0.00321629057932449
epochs 41/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0020766933681443333, val_loss: 0.0031812028224138837
epochs 42/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0019990481742608703, val_loss: 0.0031480199191719293
epochs 43/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0019916112436667867, val_loss: 0.00311677667410358
epochs 44/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001986064442041281, val_loss: 0.0030887572290865997
epochs 45/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001990239425121169, val_loss: 0.0030613032659809842
epochs 46/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018792766832599515, val_loss: 0.0030357847063753165
epochs 47/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018992610692389702, val_loss: 0.0030123931453808358
epochs 48/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0019787447036881197, val_loss: 0.0029908928064335334
epochs 49/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0019250687787701424, val_loss: 0.0029710541209696153
epochs 50/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0019404016030756266, val_loss: 0.0029524368258487237
epochs 51/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001844315642589017, val_loss: 0.002935371895957934
epochs 52/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001887652127219266, val_loss: 0.002919939530425166
epochs 53/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0019016288588509748, val_loss: 0.002903798536250466
epochs 54/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018767076887582477, val_loss: 0.0028873846988732876
epochs 55/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.00187190070037583, val_loss: 0.0028725983403427038
epochs 56/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001835715329568637, val_loss: 0.0028580726369431143
epochs 57/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018739375212278805, val_loss: 0.0028443840528397184
epochs 58/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017944659253484325, val_loss: 0.00283044879814904
epochs 59/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0019081357069999764, val_loss: 0.002816609481937791
epochs 60/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017671221781424002, val_loss: 0.002802732861355731
epochs 61/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018444216258725837, val_loss: 0.0027894754575467423
epochs 62/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018458967011323886, val_loss: 0.002775798968382572
epochs 63/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017165876888228875, val_loss: 0.0027631507010052077
epochs 64/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018611923178755924, val_loss: 0.0027502080597179503
epochs 65/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001767005686844258, val_loss: 0.0027394286626459736
epochs 66/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017990263730385586, val_loss: 0.0027297522039397767
epochs 67/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016931081288739254, val_loss: 0.0027212147233321477
epochs 68/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001775045563025694, val_loss: 0.0027136533349556356
epochs 69/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001791563021068118, val_loss: 0.0027070770505815745
epochs 70/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016859978707017083, val_loss: 0.0027019091171065442
epochs 71/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017523613966707336, val_loss: 0.002695577608813581
epochs 72/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018477925172957935, val_loss: 0.002688670700023833
epochs 73/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017695323453823988, val_loss: 0.0026830581065855528
epochs 74/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001771386772835333, val_loss: 0.0026774084955257806
epochs 75/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017647887298249101, val_loss: 0.0026704853817232344
epochs 76/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001719300349635121, val_loss: 0.0026639812650453105
epochs 77/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018024233831582886, val_loss: 0.0026569535980295192
epochs 78/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016898252388560459, val_loss: 0.0026513323432912953
epochs 79/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001758507834012179, val_loss: 0.0026456817126783885
epochs 80/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017944476640734234, val_loss: 0.0026386628760711145
epochs 81/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017497161905722397, val_loss: 0.00263172925057772
epochs 82/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017036472655538666, val_loss: 0.0026256999025415432
epochs 83/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016664516425838596, val_loss: 0.0026204088531238466
epochs 84/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016673322325866473, val_loss: 0.0026156325603982336
epochs 85/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001757031505143172, val_loss: 0.002612933991967063
epochs 86/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017185674649418184, val_loss: 0.002609903007549675
epochs 87/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016485783577847638, val_loss: 0.0026063700500679643
epochs 88/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017349538589386563, val_loss: 0.0026031393778363342
epochs 89/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016775704466884859, val_loss: 0.002600229458001099
epochs 90/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001805855792113825, val_loss: 0.0025954096700604025
epochs 91/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001686058525535229, val_loss: 0.002590367624438123
epochs 92/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017643123767093608, val_loss: 0.0025849727766686366
epochs 93/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017306046450118486, val_loss: 0.0025801336662353656
epochs 94/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001755430016323532, val_loss: 0.002576033469583643
epochs 95/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016207402535273056, val_loss: 0.002571849765158013
epochs 96/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017555059779337362, val_loss: 0.0025662592024003205
epochs 97/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016871346038227018, val_loss: 0.0025603431791655328
epochs 98/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016311230334012132, val_loss: 0.002555486025582803
epochs 99/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017134756266482566, val_loss: 0.002549305658689455
epochs 100/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017077969178851498, val_loss: 0.0025426980181548157
epochs 101/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016636972818033476, val_loss: 0.002536676902520029
epochs 102/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016714079930496058, val_loss: 0.0025302432501982703
epochs 103/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016266622445791174, val_loss: 0.0025241381415214976
epochs 104/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015701961470767855, val_loss: 0.0025196298981379523
epochs 105/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016532538042060639, val_loss: 0.0025154536589980124
epochs 106/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016362119331269672, val_loss: 0.0025114565597553003
epochs 107/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001707327758011065, val_loss: 0.0025072435676855476
epochs 108/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017545267510669011, val_loss: 0.0025028481123674858
epochs 109/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016924190175670543, val_loss: 0.0024991380933083985
epochs 110/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001680739917547295, val_loss: 0.0024945726520136783
epochs 111/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001692173380012575, val_loss: 0.0024901524235151316
epochs 112/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016449523231896915, val_loss: 0.002485538085334395
epochs 113/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016716101317127284, val_loss: 0.0024810349250114277
epochs 114/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016365762934774945, val_loss: 0.002476343517436793
epochs 115/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015947363486415462, val_loss: 0.0024725336140315785
epochs 116/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016376750641747524, val_loss: 0.002469648308071651
epochs 117/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016133925754969057, val_loss: 0.0024672421626746655
epochs 118/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016445023951267726, val_loss: 0.0024644609638734866
epochs 119/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001659930574609653, val_loss: 0.0024621785471313877
epochs 120/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017088918579056074, val_loss: 0.0024602881240609444
epochs 121/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001667512556243884, val_loss: 0.00245867956331686
epochs 122/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016155065453954433, val_loss: 0.0024558525483467076
epochs 123/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016478905160176127, val_loss: 0.0024543551532061475
epochs 124/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017029153955120005, val_loss: 0.0024533247134011045
epochs 125/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017040962782247286, val_loss: 0.002451720863188568
epochs 126/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001671043717253365, val_loss: 0.0024488847114537892
epochs 127/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016673155386294973, val_loss: 0.0024461345845147183
epochs 128/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016600916443980838, val_loss: 0.0024431664227066857
epochs 129/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016862183944077085, val_loss: 0.0024401339310172357
epochs 130/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016952175512223652, val_loss: 0.002437380174370973
epochs 131/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016582469713236942, val_loss: 0.0024352989453626304
epochs 132/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016455749441918574, val_loss: 0.0024348649147309756
epochs 133/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016707106456650715, val_loss: 0.0024349662867423735
epochs 134/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016234032160259391, val_loss: 0.0024338039152912404
epochs 135/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001693133493934415, val_loss: 0.0024318522234496316
epochs 136/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016521407511869543, val_loss: 0.002427884453515473
epochs 137/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015772690494103652, val_loss: 0.002423973293288758
epochs 138/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001589085994974563, val_loss: 0.0024195859894940728
epochs 139/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016675725763075446, val_loss: 0.002416868113275421
epochs 140/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016239898904275736, val_loss: 0.002414563724673108
epochs 141/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016001041721258509, val_loss: 0.0024121365411893317
epochs 142/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017215831303282788, val_loss: 0.0024099816494670355
epochs 143/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015911949528871398, val_loss: 0.0024081836699655183
epochs 144/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016036453509801314, val_loss: 0.0024058691029878038
epochs 145/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016204131742645251, val_loss: 0.002403566040294735
epochs 146/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015979128326044272, val_loss: 0.0024020659639255
epochs 147/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015717033615433855, val_loss: 0.0024004828724029817
epochs 148/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.001550886282501252, val_loss: 0.0023991179554478117
Starting fold 2:
epochs 1/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.002021126369455535, val_loss: 0.053347687893792205
epochs 2/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0018407168510173888, val_loss: 0.052067971856970534
epochs 3/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017405578400939703, val_loss: 0.050840585169039276
epochs 4/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016933709726129707, val_loss: 0.049730583319538516
epochs 5/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016076940733718832, val_loss: 0.04873657720653634
epochs 6/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015487757869873588, val_loss: 0.04788453186813154
epochs 7/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0016018879918479605, val_loss: 0.04715781690258729
epochs 8/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015454082118690406, val_loss: 0.046521920436307006
epochs 9/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015513837496799073, val_loss: 0.04597800624997992
epochs 10/148
Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0015092376362238276, val_loss: 0.045518328171027335
epochs 11/148

[I 2024-01-26 13:15:56,344] Trial 1 finished with value: 0.07702999179473394 and parameters: {'batch_size': 72, 'epochs': 148, 'hidden_size': 99, 'learning_rate': 4.877021798443148e-05, 'dropout_prob': 0.09395232882541973, 'weight_decay': 0.005161199759558092, 'lr_step_size': 87, 'gamma': 0.1637444516440712, 'num_layers': 3}. Best is trial 0 with value: 0.026604424174478607.

Current Learning Rate: 4.877021798443148e-05
train_loss: 0.0017336219741570715, val_loss: 0.0031307127106150515
Mean validation loss: 0.07702999179473394
Starting fold 1:
epochs 1/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029714719529606793, val_loss: 0.037760711226024125
epochs 2/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029873427611432576, val_loss: 0.037714348772638726
epochs 3/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02989459135814717, val_loss: 0.03766809248022343
epochs 4/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029877056357891937, val_loss: 0.0376218931945531
epochs 5/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029733573253217495, val_loss: 0.037575851263184294
epochs 6/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029874882415721293, val_loss: 0.03752988930791616
epochs 7/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029723842157737206, val_loss: 0.037483914647447436
epochs 8/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02933182278157849, val_loss: 0.037437981474948555
epochs 9/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029587451594048426, val_loss: 0.037392040822458894
epochs 10/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02973409608790749, val_loss: 0.03734614771643752
epochs 11/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029096166250344953, val_loss: 0.037300311401486395
epochs 12/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.0294941274939399, val_loss: 0.037254454715079384
epochs 13/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029329538502191242, val_loss: 0.03720862158623181
epochs 14/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02922410742428742, val_loss: 0.037162915793688675
epochs 15/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02971506754034444, val_loss: 0.037117250685236955
epochs 16/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02906601947585219, val_loss: 0.03707159281169113
epochs 17/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029345614355253544, val_loss: 0.037025967769716915
epochs 18/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029190639778971673, val_loss: 0.03698041444938434
epochs 19/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029113344897172953, val_loss: 0.03693490682267829
epochs 20/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02903174934418578, val_loss: 0.036889381667501046
epochs 21/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028924294247439034, val_loss: 0.03684390848012347
epochs 22/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029308912295259927, val_loss: 0.03679848262353947
epochs 23/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028690049013024882, val_loss: 0.0367531659571748
epochs 24/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02873001918196678, val_loss: 0.0367079367174914
epochs 25/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028826314269712095, val_loss: 0.03666279453196024
epochs 26/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02890557604596803, val_loss: 0.03661771881345071
epochs 27/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028910476773193007, val_loss: 0.03657266241743377
epochs 28/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02879442881400648, val_loss: 0.03652762172645644
epochs 29/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028545627997894035, val_loss: 0.03648270212702061
epochs 30/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028994275247187992, val_loss: 0.03643767992524724
epochs 31/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028522074624503915, val_loss: 0.03639279090260204
epochs 32/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02852727547287941, val_loss: 0.036347879096865654
epochs 33/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028648443696530242, val_loss: 0.03630299165256714
epochs 34/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028631287489674594, val_loss: 0.03625815497025063
epochs 35/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028158171906283027, val_loss: 0.03621337347124752
epochs 36/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02833563992263455, val_loss: 0.036168680634153516
epochs 37/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028729287221243505, val_loss: 0.03612392408479201
epochs 38/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02867721716236127, val_loss: 0.036079061746989424
epochs 39/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02849412973185903, val_loss: 0.036034287826011056
epochs 40/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028499831327874408, val_loss: 0.03598958664622746
epochs 41/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.0279830537442314, val_loss: 0.03594517278435983
epochs 42/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028221135527679794, val_loss: 0.03590081048835265
epochs 43/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028289399148994372, val_loss: 0.035856518306230246
epochs 44/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028308963971702676, val_loss: 0.03581221845785254
epochs 45/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028335672254232985, val_loss: 0.03576785066214047
epochs 46/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02830400711023494, val_loss: 0.0357234828664284
epochs 47/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.027939781977942117, val_loss: 0.03567915513719383
epochs 48/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.027914111492665192, val_loss: 0.03563486425892303
epochs 49/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.027758451188473324, val_loss: 0.03559074606746435
epochs 50/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028248474541071215, val_loss: 0.0355465925739784
epochs 51/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02787626497447491, val_loss: 0.035502496704851325
epochs 52/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02758903496555592, val_loss: 0.035458539857676157
epochs 53/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.027945527855895068, val_loss: 0.03541448909397188
epochs 54/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02789868132064217, val_loss: 0.035370401018544245
epochs 55/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.027613786353092445, val_loss: 0.0353264009874118
epochs 56/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.027945714522349206, val_loss: 0.035282338077300475
Starting fold 2:
epochs 1/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.03174435314967444, val_loss: 0.14232685483599963
epochs 2/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.031045332612273723, val_loss: 0.14214479323280485
epochs 3/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.031041388792034826, val_loss: 0.14196329983441452
epochs 4/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.03138725967636626, val_loss: 0.1417818981958063
epochs 5/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.031310137437264386, val_loss: 0.14160105029219075
epochs 6/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.03125814149450315, val_loss: 0.14142066585390192
epochs 7/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.03095016230731026, val_loss: 0.14124121242447904
epochs 8/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.030829669905238246, val_loss: 0.14106174997593227
epochs 9/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.03098862695899841, val_loss: 0.1408827711484934
epochs 10/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.03077164150186275, val_loss: 0.14070448875427247
epochs 11/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.030903608222050887, val_loss: 0.14052655767453345
epochs 12/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.030731450415853605, val_loss: 0.1403486822388674
epochs 13/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.030476915598601887, val_loss: 0.14017112584490526
epochs 14/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.03065302933958408, val_loss: 0.13999335899164803
epochs 15/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.03049955563619733, val_loss: 0.13981574115000273
epochs 16/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.030174392682353134, val_loss: 0.1396392953238989
epochs 17/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02999923847321617, val_loss: 0.13946349844336509
epochs 18/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.030373727848851367, val_loss: 0.13928758051050336
epochs 19/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.030161593920600256, val_loss: 0.1391109046967406
epochs 20/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.030024934988959057, val_loss: 0.13893483096831724
epochs 21/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029845258919522166, val_loss: 0.13875921180373743
epochs 22/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02962808197511262, val_loss: 0.1385838061963257
epochs 23/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029659142484888434, val_loss: 0.13840863504692127
epochs 24/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02976323885009869, val_loss: 0.1382334509178212
epochs 25/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029699339472541685, val_loss: 0.13805839489949376
epochs 26/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029396233879225818, val_loss: 0.1378839877090956
epochs 27/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02946306551120391, val_loss: 0.13770971184498385
epochs 28/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02934409731655921, val_loss: 0.13753554468092166
epochs 29/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029164484030518092, val_loss: 0.13736177729932886
epochs 30/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.029181123953802804, val_loss: 0.13718778412593038
epochs 31/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02900383894968974, val_loss: 0.1370148637969243
epochs 32/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028999907886119267, val_loss: 0.13684224815745102
epochs 33/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02886652462429514, val_loss: 0.13666965416387508
epochs 34/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02874827911636155, val_loss: 0.13649690449237822
epochs 35/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028718314998734153, val_loss: 0.13632478831630004
epochs 36/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028690747480447355, val_loss: 0.13615274782243528
epochs 37/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02869909515261258, val_loss: 0.13598088786790247
epochs 38/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028581557180242318, val_loss: 0.13580893023233664
epochs 39/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028263861320814803, val_loss: 0.13563810441839066
epochs 40/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028155064318133027, val_loss: 0.13546741067578918
epochs 41/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028170714380317614, val_loss: 0.13529662246766844
epochs 42/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02837769419543053, val_loss: 0.13512543757495127
epochs 43/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.028285612798246897, val_loss: 0.13495433405041696
epochs 44/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.027841453192951646, val_loss: 0.13478414620223797
epochs 45/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02798982558919019, val_loss: 0.13461417104852827
epochs 46/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02779784609171513, val_loss: 0.13444454571918438
epochs 47/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02824947111014473, val_loss: 0.13427456797737825
epochs 48/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02745812990653672, val_loss: 0.13410463439006554
epochs 49/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.027662587859422754, val_loss: 0.13393460570981627
epochs 50/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02740583721009132, val_loss: 0.1337650114376294
epochs 51/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.027415761726565267, val_loss: 0.13359536301148564
epochs 52/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02749495336442794, val_loss: 0.1334264964649552
epochs 53/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02745082768317508, val_loss: 0.1332580143683835
epochs 54/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.02701964672703884, val_loss: 0.13308982162883407
epochs 55/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.026999405788649854, val_loss: 0.1329226485600597
epochs 56/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.026971986487899956, val_loss: 0.13275545447280532
Starting fold 3:
epochs 1/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06205039725132417, val_loss: 0.4480517260338131
epochs 2/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.0619631185294374, val_loss: 0.4475992215307135
epochs 3/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06174100361470329, val_loss: 0.44715354207314945
epochs 4/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06189591886737106, val_loss: 0.44671243335071364
epochs 5/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06169064311604751, val_loss: 0.4462736608166444
epochs 6/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.061640427400472396, val_loss: 0.44583720517785924
epochs 7/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.061231623178249914, val_loss: 0.4454022267931386
epochs 8/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06141457437096458, val_loss: 0.4449685859052758
epochs 9/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06090536235848017, val_loss: 0.4445362288700907
epochs 10/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06099081212295252, val_loss: 0.44410564883759146
epochs 11/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.060738810882168384, val_loss: 0.4436759341704218
epochs 12/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06049687028290671, val_loss: 0.443247745225304
epochs 13/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.060235541353100226, val_loss: 0.4428202505174436
epochs 14/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06038647179344767, val_loss: 0.4423927172234184
epochs 15/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.060038861985269344, val_loss: 0.4419663567292063
epochs 16/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.060106823443059336, val_loss: 0.4415400172534742
epochs 17/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.060312400895513985, val_loss: 0.4411142399436549
epochs 18/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.06018123021676091, val_loss: 0.4406877666711807
epochs 19/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05930343405098507, val_loss: 0.44026332168202653
epochs 20/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.059702696123470865, val_loss: 0.4398385868260735
epochs 21/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.0595566495452403, val_loss: 0.43941465726024226
epochs 22/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05934307347460274, val_loss: 0.43899168654492027
epochs 23/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05903277229190918, val_loss: 0.43856915878622155
epochs 24/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05893568867621453, val_loss: 0.4381467695298948
epochs 25/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.058826926598946255, val_loss: 0.43772472503938176
epochs 26/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05873365129360504, val_loss: 0.4373039678523415
epochs 27/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.0586759528259567, val_loss: 0.43688223424710726
epochs 28/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.058234408082799956, val_loss: 0.4364608582697417
epochs 29/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05791671065482915, val_loss: 0.4360413819551468
epochs 30/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05817348537476439, val_loss: 0.4356218910530994
epochs 31/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.057844003670636496, val_loss: 0.4352024112877093
epochs 32/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05806669187323566, val_loss: 0.43478347612054724
epochs 33/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.057790827723383384, val_loss: 0.4343655366646616
epochs 34/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05758117872960212, val_loss: 0.43394792738713717
epochs 35/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05726418207285174, val_loss: 0.4335296350090127
epochs 36/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.057374729260214065, val_loss: 0.43311188722911637
epochs 37/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.0569044224166295, val_loss: 0.43269487399803963
epochs 38/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.057020496193058136, val_loss: 0.4322779203716077
epochs 39/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05669436662604934, val_loss: 0.4318614517387591
epochs 40/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.056371107960544654, val_loss: 0.4314456089546806
epochs 41/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05658775906062179, val_loss: 0.43102895570428745
epochs 42/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05680482590146232, val_loss: 0.4306129235970347
epochs 43/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05631011489353943, val_loss: 0.43019766807556153
epochs 44/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05625117914914562, val_loss: 0.42978283213941676
epochs 45/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05601039100438356, val_loss: 0.4293681966631036
epochs 46/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05600202962135275, val_loss: 0.4289533478649039
epochs 47/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.0555683499757658, val_loss: 0.42853994416563135
epochs 48/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.055331449579905, val_loss: 0.4281257445874967
epochs 49/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.0555846585532683, val_loss: 0.42771219422942713
epochs 50/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.055556596567233406, val_loss: 0.42729865265519995
epochs 51/56
Current Learning Rate: 1.218957125448378e-06
train_loss: 0.05535925991849549, val_loss: 0.42688558556531603
epochs 52/56

[I 2024-01-26 13:16:30,564] Trial 2 finished with value: 0.39801784333884993 and parameters: {'batch_size': 41, 'epochs': 56, 'hidden_size': 43, 'learning_rate': 1.218957125448378e-06, 'dropout_prob': 0.05049794558578487, 'weight_decay': 0.0007641282995872579, 'lr_step_size': 70, 'gamma': 0.5410869924993871, 'num_layers': 4}. Best is trial 0 with value: 0.026604424174478607.

Current Learning Rate: 1.218957125448378e-06
train_loss: 0.21700302615492165, val_loss: 0.658880865573883
Mean validation loss: 0.39801784333884993
Starting fold 1:
epochs 1/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.003154146444898001, val_loss: 0.0013503294828727743
epochs 2/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0018423945639944193, val_loss: 0.004323775279580762
epochs 3/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0030392971998815864, val_loss: 0.0024794329870737306
epochs 4/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0021068757387662403, val_loss: 0.0015307647297097566
epochs 5/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001968513232484264, val_loss: 0.0014635016115406823
epochs 6/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015755268006806115, val_loss: 0.0017410055168990144
epochs 7/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001566409403427602, val_loss: 0.002166006366391421
epochs 8/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016616481462015623, val_loss: 0.00234675796068347
epochs 9/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0017027212674484442, val_loss: 0.002201833171727087
epochs 10/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001676977604419287, val_loss: 0.0019752508381651224
epochs 11/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016303721358877068, val_loss: 0.0018273339943813258
epochs 12/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016422352742857154, val_loss: 0.001799620511959993
epochs 13/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015058389314952748, val_loss: 0.0018805245044763738
epochs 14/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016182224966254772, val_loss: 0.001984339646419118
epochs 15/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001541198492907968, val_loss: 0.002054017173788069
epochs 16/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015028323860238552, val_loss: 0.002079153238293274
epochs 17/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015859841790332116, val_loss: 0.0020562982557365966
epochs 18/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001609761768945885, val_loss: 0.0020231816257460433
epochs 19/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016354887556333682, val_loss: 0.0019829283914173414
epochs 20/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015761323294626844, val_loss: 0.0019472794938146284
epochs 21/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0014899330138608716, val_loss: 0.0019424405043920207
epochs 22/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015047685181918114, val_loss: 0.001952420456004084
epochs 23/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015546380566727174, val_loss: 0.0019739722716622054
epochs 24/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015677823610052368, val_loss: 0.001997737268041084
epochs 25/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015278110332713512, val_loss: 0.002018085523894498
epochs 26/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001538512202463799, val_loss: 0.0020264572607917026
epochs 27/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001444249931802532, val_loss: 0.0020341999450465666
epochs 28/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015603736753722554, val_loss: 0.0020349248102559756
epochs 29/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015044046716004805, val_loss: 0.0020259386081689676
epochs 30/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001521766764926724, val_loss: 0.0020195619840370983
epochs 31/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001502125498097341, val_loss: 0.0020174701636853187
epochs 32/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015028516757363258, val_loss: 0.002022185450493309
epochs 33/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015086196303232817, val_loss: 0.0020246475283975567
epochs 34/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0014403516703934752, val_loss: 0.0020373750576063204
epochs 35/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015201305668788815, val_loss: 0.002048018562307238
epochs 36/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0014850565380919235, val_loss: 0.0020574348379772058
epochs 37/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0014934465904891687, val_loss: 0.002063443430233747
epochs 38/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0014861683681374415, val_loss: 0.0020663274902433747
epochs 39/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015079204745186297, val_loss: 0.0020652878496452776
epochs 40/134
Epoch 00040: reducing learning rate of group 0 to 4.1952e-03.
Current Learning Rate: 0.004195215058662896
train_loss: 0.001512862750525145, val_loss: 0.0020629451873614207
epochs 41/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.001485592183675372, val_loss: 0.0020624284738196843
epochs 42/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014865715566740715, val_loss: 0.002062132879387048
epochs 43/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014945174924306276, val_loss: 0.0020611781746418655
epochs 44/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014842823048208007, val_loss: 0.002060199357526328
epochs 45/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014742821680173571, val_loss: 0.0020605202073439664
epochs 46/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0015006587566427985, val_loss: 0.002060723960503789
epochs 47/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014849007676514846, val_loss: 0.002061749325673047
epochs 48/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014815421790301212, val_loss: 0.002063155215613446
epochs 49/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014839984360150993, val_loss: 0.0020658174376493614
epochs 50/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014889480823369109, val_loss: 0.0020682160341254385
epochs 51/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014813736891435263, val_loss: 0.0020708384150087736
epochs 52/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014902883547811621, val_loss: 0.0020730683262962357
epochs 53/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014966968057897726, val_loss: 0.0020741428184249486
epochs 54/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014958765037590637, val_loss: 0.002074575393865081
epochs 55/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.001495555864101717, val_loss: 0.002075319391166742
epochs 56/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014865483325832572, val_loss: 0.0020766393047156988
epochs 57/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014986935067051825, val_loss: 0.002078022343860204
epochs 58/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014865590147612813, val_loss: 0.0020795936495568114
epochs 59/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.001495872602314002, val_loss: 0.0020805278943091827
epochs 60/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014905716300219003, val_loss: 0.0020811043960030045
epochs 61/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.001498150104185027, val_loss: 0.0020811347730494544
epochs 62/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014859347441846407, val_loss: 0.002081525886100472
epochs 63/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014957057384124613, val_loss: 0.0020821228801076743
epochs 64/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.001487583630583494, val_loss: 0.0020832603274979385
epochs 65/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014907432634285406, val_loss: 0.00208471235497487
epochs 66/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014906725924351792, val_loss: 0.0020862236899311507
epochs 67/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.001488732653026665, val_loss: 0.0020879197009459234
epochs 68/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.001492502918087044, val_loss: 0.0020896244783407862
epochs 69/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014914388952188586, val_loss: 0.0020911693061383342
epochs 70/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014952351005233235, val_loss: 0.0020926496216194016
epochs 71/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.001492908255711786, val_loss: 0.0020938255404440785
epochs 72/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014919175429416722, val_loss: 0.002094665608877365
epochs 73/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014894053243456017, val_loss: 0.0020956838362556148
epochs 74/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.001494298556415168, val_loss: 0.0020968068104641707
epochs 75/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014946184312544862, val_loss: 0.00209755219402723
epochs 76/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014932691147183314, val_loss: 0.0020983502449541305
epochs 77/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014950334220070784, val_loss: 0.0020988761542340448
epochs 78/134
Current Learning Rate: 0.004195215058662896
train_loss: 0.0014946268511458153, val_loss: 0.0020992927581047344
epochs 79/134
Epoch 00079: reducing learning rate of group 0 to 2.1504e-03.
Current Learning Rate: 0.0021503847556920176
train_loss: 0.001496646632930558, val_loss: 0.0020996567617035714
epochs 80/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014937113713178979, val_loss: 0.0020997139844295912
epochs 81/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014913659787883884, val_loss: 0.0020996511008553698
epochs 82/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014924182697493387, val_loss: 0.0020994892766650177
epochs 83/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014916871227078925, val_loss: 0.002099290071055293
epochs 84/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014902903883730208, val_loss: 0.0020992106067225045
epochs 85/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014902584043355953, val_loss: 0.002099293260528755
epochs 86/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014894056555165567, val_loss: 0.0020994774749085897
epochs 87/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.001491396267910635, val_loss: 0.002099647889017912
epochs 88/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014916754338436906, val_loss: 0.0020998053176107963
epochs 89/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.001489574951426077, val_loss: 0.00210012514710941
epochs 90/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014895569173141235, val_loss: 0.002100596979174665
epochs 91/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014883327271826075, val_loss: 0.002101189029360141
epochs 92/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014919064182322473, val_loss: 0.002101721017204813
epochs 93/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014912676374048092, val_loss: 0.0021021631272129812
epochs 94/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.001490687952517826, val_loss: 0.0021026752705342678
epochs 95/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014924309654528961, val_loss: 0.002103091428656817
epochs 96/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.001488939629971834, val_loss: 0.002103491891849492
epochs 97/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014908501922802412, val_loss: 0.002103866455083909
epochs 98/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014909117173182926, val_loss: 0.00210416080954019
epochs 99/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014918120527382646, val_loss: 0.002104319206218382
epochs 100/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014895328078541512, val_loss: 0.002104496762867233
epochs 101/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014907394212633862, val_loss: 0.0021047166700315614
epochs 102/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014920879689988827, val_loss: 0.00210489176648767
epochs 103/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014920191635610536, val_loss: 0.0021050593226008413
epochs 104/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014904567129346298, val_loss: 0.0021053014490079428
epochs 105/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.001490189098005526, val_loss: 0.0021056012861663475
epochs 106/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014919723710351575, val_loss: 0.002105810087308974
epochs 107/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.001490614196365258, val_loss: 0.0021060783373142936
epochs 108/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014920076246581677, val_loss: 0.0021063003028853255
epochs 109/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014928434149815554, val_loss: 0.0021064105468164935
epochs 110/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014907776603266891, val_loss: 0.002106494931534766
epochs 111/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014917883423071258, val_loss: 0.002106648523630084
epochs 112/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014913511301672675, val_loss: 0.002106833620621872
epochs 113/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014919079193771866, val_loss: 0.0021070246803758077
epochs 114/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014903968195492205, val_loss: 0.0021072929455457547
epochs 115/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014915577181933545, val_loss: 0.002107545590077184
epochs 116/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014924106523578398, val_loss: 0.002107782725790074
epochs 117/134
Current Learning Rate: 0.0021503847556920176
train_loss: 0.0014911954767548626, val_loss: 0.002107973119372649
epochs 118/134
Epoch 00118: reducing learning rate of group 0 to 1.1022e-03.
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014911390562223172, val_loss: 0.002108260291309929
epochs 119/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014895158490521442, val_loss: 0.0021084269432130416
epochs 120/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014900089393210549, val_loss: 0.002108540053105619
epochs 121/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.001490764520100416, val_loss: 0.002108584253552468
epochs 122/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014894822669080704, val_loss: 0.0021086008902210253
epochs 123/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014906771170085688, val_loss: 0.002108588232199269
epochs 124/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014897880444646274, val_loss: 0.00210856711445989
epochs 125/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014896709785956006, val_loss: 0.0021085609064596753
epochs 126/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014898146076838632, val_loss: 0.0021085479361078654
epochs 127/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014901942400396557, val_loss: 0.0021085267960044896
epochs 128/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014893409993658822, val_loss: 0.002108515310560745
epochs 129/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014892671324655807, val_loss: 0.0021085511703093193
epochs 130/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014907884218509455, val_loss: 0.002108563604691115
epochs 131/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014906453405274078, val_loss: 0.0021085581746822417
epochs 132/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014890665140946543, val_loss: 0.00210856924715795
epochs 133/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.0014909792375922399, val_loss: 0.0021085696936719808
epochs 134/134
Current Learning Rate: 0.001102244946409597
train_loss: 0.001489991062676142, val_loss: 0.002108564732541134
Starting fold 2:
epochs 1/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016226494497172288, val_loss: 0.044925249564020255
epochs 2/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015043628333890075, val_loss: 0.04114879565803628
epochs 3/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016580559832570878, val_loss: 0.03885532457773623
epochs 4/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001801073602492627, val_loss: 0.03884466967888569
epochs 5/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0017755426166236009, val_loss: 0.039785963296890256
epochs 6/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016898982465806368, val_loss: 0.04067281501269654
epochs 7/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001627103949124974, val_loss: 0.041189623957401826
epochs 8/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015964869124122504, val_loss: 0.04125409489007373
epochs 9/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0015939926946119062, val_loss: 0.041011377335771135
epochs 10/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016091472531307343, val_loss: 0.0407359235870995
epochs 11/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016262624391330113, val_loss: 0.04057745522770442
epochs 12/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016357665527673242, val_loss: 0.04055832249945716
epochs 13/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016362193802610578, val_loss: 0.04062478613892668
epochs 14/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016314344899575717, val_loss: 0.04070298623685774
epochs 15/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.001626387824331974, val_loss: 0.04074796377436111
epochs 16/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016236938393711553, val_loss: 0.04075311303726937
epochs 17/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016235546796355936, val_loss: 0.040734311693200936
epochs 18/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016248494205156978, val_loss: 0.040712059436267926
epochs 19/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016262723348183115, val_loss: 0.04069889671120205
epochs 20/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016270626474196386, val_loss: 0.04069708896506774
epochs 21/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016271225012085204, val_loss: 0.04070213241012473
epochs 22/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016267703667644559, val_loss: 0.04070823559243428
epochs 23/134
Current Learning Rate: 0.008184502490470877
train_loss: 0.0016263865793007426, val_loss: 0.04071184851621327
epochs 24/134
Current Learning Rate: 0.008184502490470877

[I 2024-01-26 13:16:45,296] Trial 3 pruned.

Current Learning Rate: 0.008184502490470877
train_loss: 0.012062642262562324, val_loss: 0.19159578555508663
epochs 4/134
Starting fold 1:
epochs 1/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0017833416325677381, val_loss: 0.0018603569313295578
epochs 2/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0015306739626746429, val_loss: 0.0018171361935521034
epochs 3/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0014209171683576547, val_loss: 0.00187572793128263
epochs 4/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0014328014693762126, val_loss: 0.0019636097860424536
epochs 5/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0014379142820344943, val_loss: 0.00204693196022785
epochs 6/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0015168404096345368, val_loss: 0.002113076548190101
epochs 7/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0014137878597370887, val_loss: 0.002158425868439831
epochs 8/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0015055161998852303, val_loss: 0.00218080584768598
epochs 9/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0014331602638489322, val_loss: 0.0021878888953085008
epochs 10/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0014667454236922295, val_loss: 0.0021776091724045967
epochs 11/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0014738307432516624, val_loss: 0.0021565327629152883
epochs 12/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0014422876294702292, val_loss: 0.0021279011301598267
epochs 13/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001450761585300298, val_loss: 0.0020967125292181183
epochs 14/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0014448009627430062, val_loss: 0.0020691135579622108
epochs 15/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0013911569454266052, val_loss: 0.002050910187934182
epochs 16/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001418168102636149, val_loss: 0.0020330092067045993
epochs 17/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001360575950361396, val_loss: 0.0020175965852104127
epochs 18/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001371327059735593, val_loss: 0.002007517199595704
epochs 19/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0013899214774076092, val_loss: 0.0020026231270381493
epochs 20/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001335228762687429, val_loss: 0.0020000804025728843
epochs 21/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0013006841837379494, val_loss: 0.0020007029635292525
epochs 22/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001352817582358655, val_loss: 0.0019964943076238822
epochs 23/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0013885989221499155, val_loss: 0.001990673265812036
epochs 24/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001347087095736673, val_loss: 0.0019864412888541427
epochs 25/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0012831554355982103, val_loss: 0.001979823127437971
epochs 26/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001303111668676138, val_loss: 0.0019770790841185343
epochs 27/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001324945140482956, val_loss: 0.001971606636959079
epochs 28/141
Epoch 00028: reducing learning rate of group 0 to 1.9819e-04.
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012820503049481072, val_loss: 0.0019621646191042507
epochs 29/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0013021080092968124, val_loss: 0.0019539544279196935
epochs 30/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012776092883493555, val_loss: 0.0019461312484437305
epochs 31/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012900216566202672, val_loss: 0.001938591139562624
epochs 32/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.001230412877262815, val_loss: 0.001932599552367863
epochs 33/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012542299840501265, val_loss: 0.001925103008551033
epochs 34/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012179342649975106, val_loss: 0.001917692890856415
epochs 35/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012161588296294213, val_loss: 0.0019110710580686205
epochs 36/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012462514857026308, val_loss: 0.0019036097004764567
epochs 37/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012297363486140967, val_loss: 0.0018944193633567345
epochs 38/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012104934179469158, val_loss: 0.0018842878561515948
epochs 39/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0012439070931194644, val_loss: 0.0018737036863488979
epochs 40/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0011667912360280753, val_loss: 0.0018663533540491603
epochs 41/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0011945398083250773, val_loss: 0.0018588359038786669
epochs 42/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.001212927612083915, val_loss: 0.0018528833697353932
epochs 43/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0011663377799681926, val_loss: 0.0018469358880170866
epochs 44/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0011986759001095045, val_loss: 0.0018405972710369449
epochs 45/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0011802688044937034, val_loss: 0.001834257893680938
epochs 46/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0011691523911921602, val_loss: 0.0018264267140215165
epochs 47/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0011485401295909755, val_loss: 0.0018178159168823376
epochs 48/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.001147348791556923, val_loss: 0.0018106579498730993
epochs 49/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.001128765359815014, val_loss: 0.0018036752063045767
epochs 50/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.001134631000949364, val_loss: 0.0017954935050128321
epochs 51/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0011062936698037543, val_loss: 0.001785235296885826
epochs 52/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.001113479370006213, val_loss: 0.0017722906526423205
epochs 53/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0010908613925015456, val_loss: 0.0017572642898334091
epochs 54/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0010587295603105113, val_loss: 0.001742818738382898
epochs 55/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0010559946862294485, val_loss: 0.0017281053269183949
epochs 56/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0011056556305112806, val_loss: 0.001712134824820647
epochs 57/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0010225061511032676, val_loss: 0.0016979696896956547
epochs 58/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0010626753301996934, val_loss: 0.001683141321777121
epochs 59/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.001008095350851746, val_loss: 0.0016705353180632779
epochs 60/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.001015775553931139, val_loss: 0.001661998978325803
epochs 61/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0010146646172200379, val_loss: 0.0016562788398005069
epochs 62/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0009851855538344305, val_loss: 0.001651450258826739
epochs 63/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0009588071255405482, val_loss: 0.0016440394518308734
epochs 64/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0009606821922046181, val_loss: 0.0016344311518447572
epochs 65/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0009300635134997337, val_loss: 0.001624903563826688
epochs 66/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0009153820568156477, val_loss: 0.0016145371513343171
epochs 67/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0009119110800767024, val_loss: 0.0016020853593210248
epochs 68/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0008888817955984881, val_loss: 0.0015890678550165734
epochs 69/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0008984093425648384, val_loss: 0.0015749179120910794
epochs 70/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0008896223220386003, val_loss: 0.0015572907893281235
epochs 71/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0008764496201796359, val_loss: 0.001537850771197363
epochs 72/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.000844109651485556, val_loss: 0.0015190435303865295
epochs 73/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0007733026384621074, val_loss: 0.0015001100665693612
epochs 74/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0008336332516352597, val_loss: 0.001480283604101523
epochs 75/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0007601745922951714, val_loss: 0.00146011918489086
epochs 76/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0007761511633074598, val_loss: 0.0014395078631902211
epochs 77/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0007359061672009135, val_loss: 0.0014194073952048232
epochs 78/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0007561380062007198, val_loss: 0.0014027016029055967
epochs 79/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0007263401811207203, val_loss: 0.0013898363018310384
epochs 80/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0006817234667802327, val_loss: 0.0013792614489303607
epochs 81/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0006886395233634271, val_loss: 0.0013668546600169257
epochs 82/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0006536258329441281, val_loss: 0.0013510545066214707
epochs 83/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0006472215295377138, val_loss: 0.0013312371355775547
epochs 84/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.000607859076147801, val_loss: 0.0013115801413445488
epochs 85/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0005998830984983789, val_loss: 0.0012906143619482848
epochs 86/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.000574789444401272, val_loss: 0.001264739825733398
epochs 87/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0005437892671723507, val_loss: 0.0012379096134712822
epochs 88/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0005507729353236132, val_loss: 0.0012146164093313641
epochs 89/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0005312955778974452, val_loss: 0.0011952144602362655
epochs 90/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.000537064260999231, val_loss: 0.0011761335536567984
epochs 91/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0004703837385597198, val_loss: 0.0011655053558857426
epochs 92/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00046902745686422446, val_loss: 0.0011602015592966622
epochs 93/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0004588874292829515, val_loss: 0.001152826309829068
epochs 94/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00042643487288028395, val_loss: 0.0011425854886367329
epochs 95/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00042703010503349726, val_loss: 0.0011288296633498057
epochs 96/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0004276530284091438, val_loss: 0.0011076315814678214
epochs 97/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0003988368605190006, val_loss: 0.0010856677134717374
epochs 98/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00040140355152911263, val_loss: 0.0010660761437305299
epochs 99/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00037921517811666586, val_loss: 0.0010497756069526077
epochs 100/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00038439870542405466, val_loss: 0.0010371357174957857
epochs 101/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00036363356936673977, val_loss: 0.0010269098568977298
epochs 102/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00035864547856985344, val_loss: 0.0010170542619705788
epochs 103/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00034580464278788944, val_loss: 0.001004658434478762
epochs 104/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00031688162738359286, val_loss: 0.0009949407592342284
epochs 105/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0003158038693455685, val_loss: 0.0009869971735353925
epochs 106/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.000299090662922122, val_loss: 0.0009768178686499595
epochs 107/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00028444512603240774, val_loss: 0.0009688375900671082
epochs 108/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0003335125839313198, val_loss: 0.0009629189906837909
epochs 109/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002944104298397801, val_loss: 0.0009577746086410786
epochs 110/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0003005198002363996, val_loss: 0.0009500975248795983
epochs 111/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00029787876961850804, val_loss: 0.0009429803017012186
epochs 112/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00029497149899773494, val_loss: 0.0009383432361861004
epochs 113/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00030120396281984685, val_loss: 0.0009364083185669427
epochs 114/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002751262918249459, val_loss: 0.00093398548687171
epochs 115/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002897815860035878, val_loss: 0.0009287586444866304
epochs 116/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002770708175376058, val_loss: 0.0009209088359248678
epochs 117/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002563262575820677, val_loss: 0.0009144812077896572
epochs 118/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00029976804768299, val_loss: 0.0009116211287236135
epochs 119/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00027024398885642815, val_loss: 0.0009129104032916458
epochs 120/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00026855968968256526, val_loss: 0.0009201600243901148
epochs 121/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00026903795292846077, val_loss: 0.0009290519948607605
epochs 122/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00029701254802363877, val_loss: 0.0009312490733511942
epochs 123/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00027988882609765583, val_loss: 0.0009298880431359927
epochs 124/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00028084534569643437, val_loss: 0.0009253619888209199
epochs 125/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002612238111109228, val_loss: 0.0009195224911979351
epochs 126/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.000258994143376568, val_loss: 0.0009127809718177703
epochs 127/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00024896859494650636, val_loss: 0.0009147757777674614
epochs 128/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002759134939160982, val_loss: 0.0009173452121965391
epochs 129/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00025772526339431736, val_loss: 0.0009133164354256894
epochs 130/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0003037467442673484, val_loss: 0.000908246549998263
epochs 131/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00024596893237781173, val_loss: 0.0009088201668897742
epochs 132/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002554585723708825, val_loss: 0.000910475071960766
epochs 133/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002628484089846576, val_loss: 0.0009166283526849982
epochs 134/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00025079799846647994, val_loss: 0.0009201863566168437
epochs 135/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00025259048714743634, val_loss: 0.0009210397207521294
epochs 136/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002593415427805954, val_loss: 0.0009262847312799606
epochs 137/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00027458542271664266, val_loss: 0.0009271346875098779
epochs 138/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002728803827745938, val_loss: 0.0009244434443596555
epochs 139/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002504865240648781, val_loss: 0.0009168234512847113
epochs 140/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.00028116530922584626, val_loss: 0.000910327859271906
epochs 141/141
Current Learning Rate: 0.00019818656157385563
train_loss: 0.0002661835224563746, val_loss: 0.0009055747374843218
Starting fold 2:
epochs 1/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0006674643952129899, val_loss: 0.02785682705672164
epochs 2/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0005891101128470741, val_loss: 0.02159785898892503
epochs 3/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0010988112153044265, val_loss: 0.020180816379816908
epochs 4/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.001113510264181777, val_loss: 0.021854480650079878
epochs 5/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.000792885735925091, val_loss: 0.023614135306132468
epochs 6/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0005690969765725497, val_loss: 0.023759456037690765
epochs 7/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0005536752832612316, val_loss: 0.022254402288480808
epochs 8/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0005952216531640213, val_loss: 0.020229606134326835
epochs 9/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0006860943811357414, val_loss: 0.01918198385913121
epochs 10/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0007130090971354787, val_loss: 0.019339296849150405
epochs 11/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0006469647455225257, val_loss: 0.01968517660310394
epochs 12/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0005911875436523635, val_loss: 0.01946540178829118
epochs 13/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0005568464675697645, val_loss: 0.018701299574030075
epochs 14/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0005832069847536715, val_loss: 0.018167919489113907
epochs 15/141
Current Learning Rate: 0.0002878195559618446
train_loss: 0.0006065357032256495, val_loss: 0.01811155621942721
epochs 16/141

[I 2024-01-26 13:18:33,334] Trial 4 finished with value: 0.006206227117267181 and parameters: {'batch_size': 124, 'epochs': 141, 'hidden_size': 90, 'learning_rate': 0.0002878195559618446, 'dropout_prob': 0.04000453554923736, 'weight_decay': 0.0004368912780687088, 'lr_step_size': 25, 'gamma': 0.6885792068977017, 'num_layers': 3}. Best is trial 4 with value: 0.006206227117267181.

Current Learning Rate: 0.0002878195559618446
train_loss: 0.0010626260123191107, val_loss: 0.002369890308105632
Mean validation loss: 0.006206227117267181
Starting fold 1:
epochs 1/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.002190828985706168, val_loss: 0.001235254389374811
epochs 2/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015282908426965342, val_loss: 0.0021262473972073117
epochs 3/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016831507839685257, val_loss: 0.0029293159837834536
epochs 4/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001927845300738945, val_loss: 0.002618755930330065
epochs 5/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0017796858162527267, val_loss: 0.002050405379237705
epochs 6/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016596880307540567, val_loss: 0.0017460751419237472
epochs 7/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015490968462759875, val_loss: 0.0017453071126702095
epochs 8/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015991387251951413, val_loss: 0.0018447474942628393
epochs 9/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016008457515119133, val_loss: 0.002003596190632762
epochs 10/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015704563197734961, val_loss: 0.0021480785048640285
epochs 11/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016566226891116362, val_loss: 0.0022023184194327576
epochs 12/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016180367340367459, val_loss: 0.0021513643158342396
epochs 13/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016297760350234489, val_loss: 0.0020243513668997603
epochs 14/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015384750229713972, val_loss: 0.001944585826928041
epochs 15/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015861220312408956, val_loss: 0.0019396432621808918
epochs 16/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001603013413229124, val_loss: 0.0019785140628779405
epochs 17/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015407046640527704, val_loss: 0.002038741109304522
epochs 18/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015820669495855996, val_loss: 0.0020739824915500847
epochs 19/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015397418171280725, val_loss: 0.0020466418224570682
epochs 20/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016540300500070626, val_loss: 0.0019875525650078136
epochs 21/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015484133799250949, val_loss: 0.001956866713743167
epochs 22/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015305166815156362, val_loss: 0.001941077010001448
epochs 23/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0014998406791020993, val_loss: 0.001979783526621759
epochs 24/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001637797918336123, val_loss: 0.0020309949362662767
epochs 25/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016153324364016667, val_loss: 0.0020576791237353494
epochs 26/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015956868170561441, val_loss: 0.002054763678308135
epochs 27/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016239123124059437, val_loss: 0.0020566671106376144
epochs 28/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016252637629421722, val_loss: 0.0020591409631857747
epochs 29/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0017107649303445788, val_loss: 0.002040805200445711
epochs 30/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015811379062238542, val_loss: 0.0020332072389704224
epochs 31/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001655078576579016, val_loss: 0.002065868431849307
epochs 32/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016090956849726162, val_loss: 0.0020711268785434138
epochs 33/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015514940131795714, val_loss: 0.002053826589498816
epochs 34/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015535176405568276, val_loss: 0.0020332491187697375
epochs 35/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001531052273754827, val_loss: 0.002026914212834335
epochs 36/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001605923965153603, val_loss: 0.002009148931277818
epochs 37/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015527860272222345, val_loss: 0.002023662023374958
epochs 38/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015434260610307224, val_loss: 0.0020628293075500743
epochs 39/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015764545224986872, val_loss: 0.0020791473706546974
epochs 40/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016150282432423218, val_loss: 0.002085287267446371
epochs 41/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001602976141217177, val_loss: 0.0020859367541944313
epochs 42/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001508854767636972, val_loss: 0.002090819036330734
epochs 43/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016452661885858488, val_loss: 0.0020494573006688273
epochs 44/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016527622271065698, val_loss: 0.002020349473949816
epochs 45/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016037660930075953, val_loss: 0.002028184905066155
epochs 46/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015560666084638796, val_loss: 0.002052405831483683
epochs 47/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015792309190912515, val_loss: 0.0020591351146944555
epochs 48/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001541365768667004, val_loss: 0.002054940320637175
epochs 49/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016027988281597286, val_loss: 0.0020629612016675406
epochs 50/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001563960964727142, val_loss: 0.002057845183145745
epochs 51/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016356102823920082, val_loss: 0.002039026997303345
epochs 52/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015281606414454902, val_loss: 0.00201643538403962
epochs 53/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015846530095395314, val_loss: 0.0019970584345221716
epochs 54/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015434937561574196, val_loss: 0.001993124464551281
epochs 55/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001551841293487661, val_loss: 0.0020136906555547427
epochs 56/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016060155291358425, val_loss: 0.002034051143288563
epochs 57/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001538930742619988, val_loss: 0.0020288002747723736
epochs 58/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016261571249311887, val_loss: 0.0020224820079563772
epochs 59/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015556153238943998, val_loss: 0.002037398775236828
epochs 60/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016002812142879089, val_loss: 0.0020621219723436393
epochs 61/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015289699686323538, val_loss: 0.002062088338731739
epochs 62/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015519967468112315, val_loss: 0.002051189106944213
epochs 63/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001562601821627284, val_loss: 0.00202044444419076
epochs 64/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015679218103622063, val_loss: 0.001986923323956465
epochs 65/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015591607071799348, val_loss: 0.001974096840651902
epochs 66/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001562745579231935, val_loss: 0.0019851873883070716
epochs 67/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001523004326928027, val_loss: 0.0020095082882203553
epochs 68/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001514739427052279, val_loss: 0.002039974093694534
epochs 69/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0014675283404358198, val_loss: 0.002050999927910437
epochs 70/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016077696719500971, val_loss: 0.0020527741481170154
epochs 71/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015215933773632922, val_loss: 0.0020545364680736766
epochs 72/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015514143615100214, val_loss: 0.002046807730833902
epochs 73/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015259924286127851, val_loss: 0.002037979034081984
epochs 74/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015603210439861103, val_loss: 0.0020313273007846683
epochs 75/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015851869811166054, val_loss: 0.002015461539849639
epochs 76/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015918519060314313, val_loss: 0.0020105995804586105
epochs 77/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015693357334959346, val_loss: 0.0020184447938319003
epochs 78/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001590630059256096, val_loss: 0.002028908659275131
Starting fold 2:
epochs 1/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016830946211963524, val_loss: 0.04292632260016705
epochs 2/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0017824694043252077, val_loss: 0.03842383260397535
epochs 3/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0019382220181317902, val_loss: 0.041387748286912315
epochs 4/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016526213217538928, val_loss: 0.04305771476540126
epochs 5/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0015804015898825846, val_loss: 0.04205720679540383
epochs 6/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001631706516031715, val_loss: 0.041195933775682196
epochs 7/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016728874718338423, val_loss: 0.0413095051814851
epochs 8/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0017161616597532931, val_loss: 0.041869015658372324
epochs 9/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016785195144429484, val_loss: 0.0418583552598169
epochs 10/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016315513534017985, val_loss: 0.0414790724845309
epochs 11/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.001618387312919367, val_loss: 0.04121346964843963
epochs 12/78
Current Learning Rate: 0.000700745027353472
train_loss: 0.0016849309513896802, val_loss: 0.041511042288651594
epochs 13/78

[I 2024-01-26 13:18:41,461] Trial 5 pruned.

Current Learning Rate: 0.000700745027353472
train_loss: 0.0016721264862816928, val_loss: 0.041782026581074064
epochs 14/78
Starting fold 1:
epochs 1/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.003163706593975229, val_loss: 0.00526434131499723
epochs 2/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.003165308461910555, val_loss: 0.005178715549654474
epochs 3/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0030964267708967733, val_loss: 0.005096164558046057
epochs 4/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0030022261857275702, val_loss: 0.005016259251677088
epochs 5/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0030770794562015092, val_loss: 0.004938710243502436
epochs 6/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0029449961669007806, val_loss: 0.004863263504567409
epochs 7/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002945156781750388, val_loss: 0.004790355947701947
epochs 8/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002905459713043743, val_loss: 0.004718917541475476
epochs 9/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002805227829651956, val_loss: 0.00465032249753437
epochs 10/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0027728878339985386, val_loss: 0.004583233398366964
epochs 11/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002722507780019537, val_loss: 0.004517825744666257
epochs 12/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0026233100859252246, val_loss: 0.004455724671348243
epochs 13/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002670211510696007, val_loss: 0.004395422484345832
epochs 14/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002589147949995669, val_loss: 0.004336725955669719
epochs 15/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002555361062006437, val_loss: 0.004278734901546207
epochs 16/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002520751260147479, val_loss: 0.004221938442481731
epochs 17/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0025993460194991998, val_loss: 0.004165916348268327
epochs 18/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002421413182195178, val_loss: 0.00411221657046362
epochs 19/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0026136294886543367, val_loss: 0.004058837666985039
epochs 20/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0023444257822120562, val_loss: 0.004006880929840631
epochs 21/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002434731902260529, val_loss: 0.00395727559991524
epochs 22/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002423824330387441, val_loss: 0.0039083282294756685
epochs 23/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002267583080346843, val_loss: 0.0038603986176894978
epochs 24/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0023657248055219257, val_loss: 0.0038139850351542825
epochs 25/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002371923700832811, val_loss: 0.0037695166010005203
epochs 26/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002321503043946761, val_loss: 0.003727026068908775
epochs 27/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0022493576321530304, val_loss: 0.0036861435655737296
epochs 28/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0022193284760425357, val_loss: 0.003645824142088378
epochs 29/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.00213424413844845, val_loss: 0.0036070238719204148
epochs 30/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0021812536088921326, val_loss: 0.0035681775705980775
epochs 31/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0021753739259254778, val_loss: 0.0035305347107504005
epochs 32/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0022030817727729875, val_loss: 0.0034939887715920216
epochs 33/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.00208628705724167, val_loss: 0.0034587470026484594
epochs 34/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.00217978473550542, val_loss: 0.003423768227788203
epochs 35/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002188890135393625, val_loss: 0.003390053993299309
epochs 36/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0022193849144969136, val_loss: 0.0033567016883017985
epochs 37/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0020902395105957495, val_loss: 0.00332477746805556
epochs 38/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.001996037044782976, val_loss: 0.003293666714805448
epochs 39/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0020857415618497485, val_loss: 0.0032639383506121752
epochs 40/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002007613136236997, val_loss: 0.003236481075107708
epochs 41/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0020036854065868907, val_loss: 0.0032089790819506895
epochs 42/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0019307816493030834, val_loss: 0.003181728474661022
epochs 43/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002000862801459765, val_loss: 0.0031543798709447544
epochs 44/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0019153491770052106, val_loss: 0.003127472079588762
epochs 45/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0020812846969898886, val_loss: 0.003101170447112772
epochs 46/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.002037604819633998, val_loss: 0.0030762458168043707
epochs 47/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.001990855936463432, val_loss: 0.0030517309879590023
epochs 48/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0019278416420045112, val_loss: 0.003028604147594275
epochs 49/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.001906068051252269, val_loss: 0.0030061140527035796
epochs 50/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0018960739452220303, val_loss: 0.0029838887325910803
epochs 51/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0019347347226453405, val_loss: 0.0029617709002004154
epochs 52/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0020034237076240395, val_loss: 0.0029398269340928985
epochs 53/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0018528823183212233, val_loss: 0.002918645564549431
epochs 54/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0018728753834454295, val_loss: 0.0028986781820238227
epochs 55/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0019320360557972698, val_loss: 0.002878910581976494
epochs 56/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0018409469458243908, val_loss: 0.002859408690327607
epochs 57/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0018896245183943968, val_loss: 0.002839834534633586
epochs 58/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0019644389777615863, val_loss: 0.0028208686133822133
epochs 59/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.001757912713832124, val_loss: 0.0028036222057907204
epochs 60/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0018473630016638996, val_loss: 0.0027870468253049217
epochs 61/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017730619897759568, val_loss: 0.0027712416619914094
epochs 62/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0018351058357726096, val_loss: 0.0027548040195956433
epochs 63/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017610757119990396, val_loss: 0.0027385246174066865
epochs 64/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017034155592371366, val_loss: 0.002722938642699247
epochs 65/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017472875869747153, val_loss: 0.0027081262573789757
epochs 66/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017928928010453667, val_loss: 0.0026942152938940317
epochs 67/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0016501218225656838, val_loss: 0.002681357519912509
epochs 68/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.001778010051087844, val_loss: 0.0026678551232754743
epochs 69/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017893355849848472, val_loss: 0.002653921747543408
epochs 70/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0018037819739363744, val_loss: 0.0026405031197722756
epochs 71/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017163041545580583, val_loss: 0.002627747183157082
epochs 72/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017517765931858633, val_loss: 0.0026154909593108307
epochs 73/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017705636959075683, val_loss: 0.0026032921802987786
epochs 74/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0016163615643898467, val_loss: 0.002592314304676716
epochs 75/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.001726821388920622, val_loss: 0.002581205621122775
epochs 76/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.001727151955013764, val_loss: 0.002569879119906354
epochs 77/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0016435193744990485, val_loss: 0.0025589542603579743
epochs 78/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017138973836201906, val_loss: 0.002548694327216301
epochs 79/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017031100436916428, val_loss: 0.0025394245726362754
epochs 80/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0016485313468652557, val_loss: 0.002530260585971471
epochs 81/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0016745070560749522, val_loss: 0.0025207943460707994
epochs 82/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0016787889165387146, val_loss: 0.002510919286195483
epochs 83/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.001661985621275993, val_loss: 0.0025013962876982987
epochs 84/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017210113414636765, val_loss: 0.0024931035429625282
epochs 85/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0017235945197171532, val_loss: 0.002484761171217542
epochs 86/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0015954246248982504, val_loss: 0.002476477167587482
epochs 87/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.001713229026407996, val_loss: 0.002468354948704425
epochs 88/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0016084375468045963, val_loss: 0.0024607626336020125
epochs 89/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0016156845246625476, val_loss: 0.0024530734180619844
epochs 90/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0015752567878256454, val_loss: 0.0024451262870570645
epochs 91/122
Current Learning Rate: 6.161403149372306e-06
train_loss: 0.0016323159606575868, val_loss: 0.0024376246334500856
epochs 92/122

[I 2024-01-26 13:18:50,240] Trial 6 pruned.

Starting fold 1:
epochs 1/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.03189941362575873, val_loss: 0.0081923056455133
epochs 2/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.010989817763115034, val_loss: 0.02294606998758881
epochs 3/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.013875143756587549, val_loss: 0.0035721021526689202
epochs 4/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.002983239972596302, val_loss: 0.0011466495297530568
epochs 5/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0015318299677394526, val_loss: 0.004108485688553437
epochs 6/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0024887464220611083, val_loss: 0.002000757351695364
epochs 7/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.001498706665810651, val_loss: 0.0012564263473522211
epochs 8/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0013112164453272462, val_loss: 0.0021441547658086115
epochs 9/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016383373560720908, val_loss: 0.0027806370418004102
epochs 10/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0019380710435430765, val_loss: 0.0019128188398960782
epochs 11/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0014557820344251874, val_loss: 0.0017380849931597415
epochs 12/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0014559585557052694, val_loss: 0.0023051383575779924
epochs 13/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016965828557180143, val_loss: 0.00240338664030117
epochs 14/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016257713797370487, val_loss: 0.0018948764961494722
epochs 15/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0014859816611677065, val_loss: 0.0020852371143471253
epochs 16/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.001588217312018969, val_loss: 0.0023611483004826466
epochs 17/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0017336664659715576, val_loss: 0.0021177679360047667
epochs 18/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0015917833471145346, val_loss: 0.0021004868164278667
epochs 19/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016436516768551788, val_loss: 0.0024301089358663088
epochs 20/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0018059867634100987, val_loss: 0.0023358993458953733
epochs 21/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0017065959370436185, val_loss: 0.0021443921210256554
epochs 22/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016162905769114763, val_loss: 0.002264649195192186
epochs 23/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016835962904128553, val_loss: 0.002361859035016479
epochs 24/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.00167687495511353, val_loss: 0.0022668260600001208
epochs 25/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016888319446527595, val_loss: 0.002218075729845288
epochs 26/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.00166253639407315, val_loss: 0.002301413416678674
epochs 27/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016606239659411489, val_loss: 0.0024080019266540676
epochs 28/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016814990199667305, val_loss: 0.0023409686048245547
epochs 29/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0017127734601863746, val_loss: 0.0022482468878335664
epochs 30/52

[I 2024-01-26 13:18:52,509] Trial 7 pruned.

Current Learning Rate: 0.023834273282698583
train_loss: 0.001640681182164515, val_loss: 0.0022776532568968832
epochs 31/52
Current Learning Rate: 0.023834273282698583
train_loss: 0.0016418617511494392, val_loss: 0.002325263098004813
epochs 32/52
Starting fold 1:
epochs 1/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.003933808859437704, val_loss: 0.003198845568113029
epochs 2/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0025344012305140496, val_loss: 0.001719719055108726
epochs 3/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0018294463865458966, val_loss: 0.001757804153021425
epochs 4/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.001493951992597431, val_loss: 0.0024795955279842017
epochs 5/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0019247669959440827, val_loss: 0.0027039931388571858
epochs 6/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0019143319223076105, val_loss: 0.002272375684697181
epochs 7/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0018248571315780282, val_loss: 0.0019808597047813238
epochs 8/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.001669315982144326, val_loss: 0.001986904302611947
epochs 9/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0016764662927016617, val_loss: 0.002122638234868646
epochs 10/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0016317329951561987, val_loss: 0.002155458170454949
epochs 11/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0016704001231119038, val_loss: 0.0020882915472611786
epochs 12/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0018971507204696536, val_loss: 0.0020869885571300983
epochs 13/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0017957067117094993, val_loss: 0.00218599810032174
epochs 14/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.001595701347105205, val_loss: 0.002311758603900671
epochs 15/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0017536449246108531, val_loss: 0.0022975837578997015
epochs 16/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0017752056242898106, val_loss: 0.0022518618730828165
epochs 17/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.001669095130637288, val_loss: 0.002153785526752472
epochs 18/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0016766609740443527, val_loss: 0.0021219310583546758
epochs 19/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0016544294310733676, val_loss: 0.0021615995676256715
epochs 20/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.001635635329876095, val_loss: 0.002218551642727107
epochs 21/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0017031275550834835, val_loss: 0.0022770453710108996
epochs 22/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0017091857967898249, val_loss: 0.0022900748648680747
epochs 23/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.001745138899423182, val_loss: 0.002197266183793545
epochs 24/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0016426046728156506, val_loss: 0.0021093241521157324
epochs 25/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0016699160216376186, val_loss: 0.0021051536314189434
epochs 26/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0016293777502141894, val_loss: 0.0021538074710406364
epochs 27/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.00173426135443151, val_loss: 0.0021962749189697204
epochs 28/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0017334942473098635, val_loss: 0.002217496430967003
epochs 29/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0016978274914436042, val_loss: 0.0022164239315316083
epochs 30/131

[I 2024-01-26 13:18:54,933] Trial 8 pruned.

Current Learning Rate: 0.00595600910459178
train_loss: 0.0015852291020564736, val_loss: 0.0022089760517701507
epochs 31/131
Current Learning Rate: 0.00595600910459178
train_loss: 0.0015784507850185037, val_loss: 0.002198469825088978
epochs 32/131
Starting fold 1:
epochs 1/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04340109434959136, val_loss: 0.04964792522552766
epochs 2/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.043161221632831974, val_loss: 0.04944804291191854
epochs 3/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.042971655334296976, val_loss: 0.04924865429730792
epochs 4/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.042814884138734716, val_loss: 0.049049573705384604
epochs 5/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04262482669008406, val_loss: 0.04885072427752771
epochs 6/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04247984545011269, val_loss: 0.04865207983867118
epochs 7/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.042322529087725436, val_loss: 0.04845368881758891
epochs 8/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04211077525427467, val_loss: 0.048255497785775286
epochs 9/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04203992934995576, val_loss: 0.04805749507718965
epochs 10/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04178929574003345, val_loss: 0.047859722062161096
epochs 11/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.0415726843241014, val_loss: 0.0476622083469441
epochs 12/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04146272355788633, val_loss: 0.047464920992129726
epochs 13/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04120555235759208, val_loss: 0.04726790205428475
epochs 14/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04109836369752884, val_loss: 0.047071152415714766
epochs 15/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.040861889425861206, val_loss: 0.04687461678526903
epochs 16/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04078855081216285, val_loss: 0.04667829251603076
epochs 17/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.0405728282701028, val_loss: 0.04648217735321898
epochs 18/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.040368481098037014, val_loss: 0.04628625874848742
epochs 19/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.04019438926326601, val_loss: 0.04609057395473907
epochs 20/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.040029883482738546, val_loss: 0.04589512699136609
epochs 21/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.03988041199351612, val_loss: 0.04569990805497295
epochs 22/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.03968752361834049, val_loss: 0.04550493439953578
epochs 23/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.03956387858641775, val_loss: 0.045310191221927344
epochs 24/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.03934769067717226, val_loss: 0.04511566117013756
epochs 25/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.039195455610752106, val_loss: 0.04492136738017986
epochs 26/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.0390682203793212, val_loss: 0.04472729906831917
epochs 27/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.03882345635639994, val_loss: 0.04453347437083721
epochs 28/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.038674813646234964, val_loss: 0.044339919756901894
epochs 29/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.038497818829981906, val_loss: 0.04414660062052702
epochs 30/56

[I 2024-01-26 13:18:56,730] Trial 9 pruned.

Current Learning Rate: 9.787544845600567e-06
train_loss: 0.038313530777630056, val_loss: 0.04395352509853087
epochs 31/56
Current Learning Rate: 9.787544845600567e-06
train_loss: 0.03816495316201135, val_loss: 0.04376068417178957
epochs 32/56
Starting fold 1:
epochs 1/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0028751697881441367, val_loss: 0.0024622417594257155
epochs 2/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0018997193743033628, val_loss: 0.0015568772600473542
epochs 3/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0015362216649871124, val_loss: 0.0011861644195098626
epochs 4/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0014524722128714386, val_loss: 0.0010606949425939667
epochs 5/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0013464040515062056, val_loss: 0.0010232262178569247
epochs 6/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0012873607172973847, val_loss: 0.0010291374055668712
epochs 7/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0011335725258839757, val_loss: 0.001082771394009653
epochs 8/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0010348036909770026, val_loss: 0.0011822566169461138
epochs 9/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0009514645967436464, val_loss: 0.001307502707564517
epochs 10/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0009093364026691569, val_loss: 0.001411416339933088
epochs 11/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0008980765411826341, val_loss: 0.001450995186735925
epochs 12/99
Epoch 00012: reducing learning rate of group 0 to 3.2339e-04.
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0008557332753154792, val_loss: 0.001414534932394561
epochs 13/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0008035217663028131, val_loss: 0.0013393231618561243
epochs 14/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0007444041505406954, val_loss: 0.0012385763914177293
epochs 15/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0006766974809579551, val_loss: 0.0011316293997592048
epochs 16/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0006212479343000603, val_loss: 0.001036558208349896
epochs 17/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0005698209793895091, val_loss: 0.0009619383839890361
epochs 18/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0005265601003836644, val_loss: 0.0009108156333432386
epochs 19/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0004828081055740385, val_loss: 0.0008798592797431506
epochs 20/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0004457251456762223, val_loss: 0.0008652433569199945
epochs 21/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0003954341138811096, val_loss: 0.0008656303275768694
epochs 22/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00037111208320742375, val_loss: 0.000874318579505933
epochs 23/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00035055832428808667, val_loss: 0.0008837734912767222
epochs 24/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00032887766658524543, val_loss: 0.0008866377297396722
epochs 25/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00029946942476702756, val_loss: 0.0008730420095257853
epochs 26/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00027269853101308017, val_loss: 0.0008476094575598836
epochs 27/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00026239512004203313, val_loss: 0.0008136462518259099
epochs 28/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0002530660418989627, val_loss: 0.0007789336488043007
epochs 29/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00022809800483580484, val_loss: 0.0007475123752986914
epochs 30/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0002059005608316511, val_loss: 0.0007210180616790526
epochs 31/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00017608649995006425, val_loss: 0.0006989363495162443
epochs 32/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00017442627500522097, val_loss: 0.0006836093226937871
epochs 33/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0001647180445663827, val_loss: 0.000673197670594642
epochs 34/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00015474887285994268, val_loss: 0.0006658153179542799
epochs 35/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00014734958140730955, val_loss: 0.0006574662990475956
epochs 36/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00014146018810080071, val_loss: 0.0006479854401397078
epochs 37/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00013832842523697764, val_loss: 0.000633877611375953
epochs 38/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00013884125862540186, val_loss: 0.0006199243564256712
epochs 39/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00012851567183756025, val_loss: 0.0006076845965397201
epochs 40/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00012359721004031598, val_loss: 0.0005987650285916109
epochs 41/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00012257803058386536, val_loss: 0.0005927668663820154
epochs 42/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00013441506077805043, val_loss: 0.0005849051178972188
epochs 43/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00011419353694164831, val_loss: 0.0005789913077789702
epochs 44/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00011730543697730786, val_loss: 0.0005733826271209278
epochs 45/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00011727745127006385, val_loss: 0.0005671482361657054
epochs 46/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00011267262843351713, val_loss: 0.0005619605819351579
epochs 47/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00010804042302831812, val_loss: 0.0005552658039194189
epochs 48/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00011290288568584641, val_loss: 0.0005478294860375555
epochs 49/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00011713681106860014, val_loss: 0.0005483019202457447
epochs 50/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00010888419737487934, val_loss: 0.0005465373936060228
epochs 51/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00010213731423535042, val_loss: 0.0005478419130668044
epochs 52/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0001013465730418255, val_loss: 0.0005493999520120652
epochs 53/99
Current Learning Rate: 0.00032339234663865895
train_loss: 9.982833618874123e-05, val_loss: 0.0005502632586285472
epochs 54/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00011171585394645502, val_loss: 0.000544131325410777
epochs 55/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00010333528181562494, val_loss: 0.0005319453199933234
epochs 56/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.0001051607812865098, val_loss: 0.0005193401422155531
epochs 57/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00010608377365554732, val_loss: 0.0005065914084154524
epochs 58/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00010187499130169224, val_loss: 0.0005052557466306576
epochs 59/99
Current Learning Rate: 0.00032339234663865895
train_loss: 0.00010279624050446345, val_loss: 0.0005073107631975098
epochs 60/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.488625646446292e-05, val_loss: 0.0005080252542699639
epochs 61/99
Current Learning Rate: 0.00032339234663865895
train_loss: 9.244886651255288e-05, val_loss: 0.0005110704977261392
epochs 62/99
Current Learning Rate: 0.00032339234663865895
train_loss: 9.758950143709386e-05, val_loss: 0.0005146744979643508
epochs 63/99
Current Learning Rate: 0.00032339234663865895
train_loss: 9.176834497147386e-05, val_loss: 0.0005078892713706744
epochs 64/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.756099330065281e-05, val_loss: 0.0004956394403339609
epochs 65/99
Current Learning Rate: 0.00032339234663865895
train_loss: 9.221664360283236e-05, val_loss: 0.0004836146002880445
epochs 66/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.968267326341256e-05, val_loss: 0.000479793992800344
epochs 67/99
Current Learning Rate: 0.00032339234663865895
train_loss: 9.236515348005157e-05, val_loss: 0.0004826972346850916
epochs 68/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.695443324732447e-05, val_loss: 0.0004877992360362489
epochs 69/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.891373037936558e-05, val_loss: 0.00048721370679375374
epochs 70/99
Current Learning Rate: 0.00032339234663865895
train_loss: 9.134455176535994e-05, val_loss: 0.0004795529775468535
epochs 71/99
Current Learning Rate: 0.00032339234663865895
train_loss: 9.132921006407981e-05, val_loss: 0.00047558347179897523
epochs 72/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.647547089678579e-05, val_loss: 0.00047248609020913903
epochs 73/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.540669100751218e-05, val_loss: 0.0004693252690087416
epochs 74/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.839618040885972e-05, val_loss: 0.00046941779651924186
epochs 75/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.007461575815748e-05, val_loss: 0.0004683453816381332
epochs 76/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.28777926998507e-05, val_loss: 0.00046430937762029077
epochs 77/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.867027453992418e-05, val_loss: 0.0004628857499674747
epochs 78/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.639590179020734e-05, val_loss: 0.00045950425862285654
epochs 79/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.020496078595323e-05, val_loss: 0.00045352992846777563
epochs 80/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.161916745226144e-05, val_loss: 0.0004534612728380843
epochs 81/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.125448634688694e-05, val_loss: 0.0004539619175423133
epochs 82/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.534353278503802e-05, val_loss: 0.00045164593029767275
epochs 83/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.353809718851392e-05, val_loss: 0.00044829082724295166
epochs 84/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.22701754115865e-05, val_loss: 0.0004429502032795235
epochs 85/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.431554589677896e-05, val_loss: 0.0004450925141818037
epochs 86/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.787405799682203e-05, val_loss: 0.0004473250285771332
epochs 87/99
Current Learning Rate: 0.00032339234663865895
train_loss: 7.993040045747827e-05, val_loss: 0.000451345174377294
epochs 88/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.209980235398306e-05, val_loss: 0.0004562659654766321
epochs 89/99
Current Learning Rate: 0.00032339234663865895
train_loss: 7.990984618357431e-05, val_loss: 0.00045315138873104984
epochs 90/99
Current Learning Rate: 0.00032339234663865895
train_loss: 7.973784423053362e-05, val_loss: 0.0004412264005575133
epochs 91/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.552732914196033e-05, val_loss: 0.00043006582173371784
epochs 92/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.117206154182848e-05, val_loss: 0.00042667696803906245
epochs 93/99
Current Learning Rate: 0.00032339234663865895
train_loss: 7.249161135405302e-05, val_loss: 0.00043118269440080775
epochs 94/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.056628690897732e-05, val_loss: 0.0004379855799733808
epochs 95/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.777586527254531e-05, val_loss: 0.00043791368983587934
epochs 96/99
Current Learning Rate: 0.00032339234663865895
train_loss: 7.637353103889741e-05, val_loss: 0.0004357622623884756
epochs 97/99
Current Learning Rate: 0.00032339234663865895
train_loss: 8.140245405038035e-05, val_loss: 0.0004318203201125327
epochs 98/99
Current Learning Rate: 0.00032339234663865895
train_loss: 7.956140126273232e-05, val_loss: 0.00042862281521880314
epochs 99/99
Epoch 00099: reducing learning rate of group 0 to 2.4597e-04.
Current Learning Rate: 0.0002459738863540634
train_loss: 8.448663031326999e-05, val_loss: 0.00042906284736665457
Starting fold 2:
epochs 1/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00022821550067563199, val_loss: 0.00855768564108171
epochs 2/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0005668135972595529, val_loss: 0.009196435895405317
epochs 3/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00036821249002394707, val_loss: 0.012038332733668779
epochs 4/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00022452549923113302, val_loss: 0.011235647079975982
epochs 5/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.000187977449355745, val_loss: 0.008950558618495339
epochs 6/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00026965238840172165, val_loss: 0.008035307926566978
epochs 7/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00027947656038266266, val_loss: 0.0084654907843
epochs 8/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00021734652905970028, val_loss: 0.008674985248791544
epochs 9/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001836602324864974, val_loss: 0.0077955199601618865
epochs 10/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001906737041855721, val_loss: 0.006843763472218263
epochs 11/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00020279215930617953, val_loss: 0.006577138406665702
epochs 12/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00019282143881642504, val_loss: 0.006758501106186917
epochs 13/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00017349313374755807, val_loss: 0.006525447572532453
epochs 14/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001631246178141354, val_loss: 0.005872813386744575
epochs 15/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001787990032952573, val_loss: 0.005513947604126052
epochs 16/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001809134007137465, val_loss: 0.005483873766895971
epochs 17/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00016186277314677442, val_loss: 0.005460854590331253
epochs 18/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00015071934858018433, val_loss: 0.0051877029828335105
epochs 19/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00015993498259616134, val_loss: 0.00491874462091609
epochs 20/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001590185124721182, val_loss: 0.004764484045536895
epochs 21/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00015985788210711786, val_loss: 0.004693053829434671
epochs 22/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00014319160208718754, val_loss: 0.004534538335313923
epochs 23/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00015453566493785106, val_loss: 0.004376572880305742
epochs 24/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00013887676928118852, val_loss: 0.0042330679826830565
epochs 25/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001455636451474244, val_loss: 0.004114296551989882
epochs 26/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00013998769649525025, val_loss: 0.003993697297808371
epochs 27/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00014633592034346963, val_loss: 0.00393367349905403
epochs 28/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001361303976553149, val_loss: 0.00385959346435572
epochs 29/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001347424485414338, val_loss: 0.003701692402951027
epochs 30/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00014005407804353653, val_loss: 0.0036156146591039082
epochs 31/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001268819748044112, val_loss: 0.0035138874265708423
epochs 32/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00012257295158250552, val_loss: 0.003412888189287562
epochs 33/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00012311112912261467, val_loss: 0.0033284516171797327
epochs 34/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00012797019903940197, val_loss: 0.0032836651086415114
epochs 35/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00012108090802365423, val_loss: 0.003163835896473182
epochs 36/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00012181815001991039, val_loss: 0.003088951576501131
epochs 37/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00011486105680600495, val_loss: 0.003089580983903847
epochs 38/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.0001189535335135205, val_loss: 0.0030097669088526777
epochs 39/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00011155577100764371, val_loss: 0.002923574627033974
epochs 40/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00011355803343528686, val_loss: 0.0029308454231604148
epochs 41/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00010950072166068773, val_loss: 0.0028670542432289374
epochs 42/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00010694136887506925, val_loss: 0.0027425771432095453
epochs 43/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00011604850710443173, val_loss: 0.0027442090752485553
epochs 44/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00010902499680493125, val_loss: 0.0027110802450854526
epochs 45/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00010755599199144757, val_loss: 0.0026140246834409865
epochs 46/99
Current Learning Rate: 0.00042517769432613136
train_loss: 9.938141508763165e-05, val_loss: 0.0025454794840985224
epochs 47/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.000100438039762115, val_loss: 0.002525617000891974
epochs 48/99
Current Learning Rate: 0.00042517769432613136
train_loss: 9.340819141423133e-05, val_loss: 0.002494064424383013
epochs 49/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00010063809918631848, val_loss: 0.002418905579926152
epochs 50/99
Current Learning Rate: 0.00042517769432613136
train_loss: 9.64992621447891e-05, val_loss: 0.0024346598522051385
epochs 51/99
Current Learning Rate: 0.00042517769432613136
train_loss: 9.46332171320376e-05, val_loss: 0.0023541972629333796
epochs 52/99
Current Learning Rate: 0.00042517769432613136
train_loss: 9.038392607563812e-05, val_loss: 0.0022508975559551465
epochs 53/99
Current Learning Rate: 0.00042517769432613136
train_loss: 0.00010499476116628533, val_loss: 0.0023017687674023605
epochs 54/99
Current Learning Rate: 0.00042517769432613136
train_loss: 9.183332501714559e-05, val_loss: 0.002260954168282057
epochs 55/99
Current Learning Rate: 0.00042517769432613136
train_loss: 9.297194479394851e-05, val_loss: 0.002131947223097086
epochs 56/99
Current Learning Rate: 0.00042517769432613136
train_loss: 9.116544204420949e-05, val_loss: 0.0021632200744199125
epochs 57/99
Current Learning Rate: 0.00042517769432613136

[I 2024-01-26 13:19:46,321] Trial 10 finished with value: 0.0015551751845140963 and parameters: {'batch_size': 112, 'epochs': 99, 'hidden_size': 72, 'learning_rate': 0.00042517769432613136, 'dropout_prob': 0.005823123556620957, 'weight_decay': 2.9938580103995673e-05, 'lr_step_size': 6, 'gamma': 0.7606051562775581, 'num_layers': 1}. Best is trial 10 with value: 0.0015551751845140963.

Current Learning Rate: 0.0001870890062705307
train_loss: 0.0002726906198567074, val_loss: 0.0008162963675874236
epochs 99/99
Current Learning Rate: 0.0001870890062705307
train_loss: 0.0002841800371013386, val_loss: 0.0008173047068626865
Mean validation loss: 0.0015551751845140963
Starting fold 1:
epochs 1/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.010063565736881604, val_loss: 0.007013789333991314
epochs 2/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.005836393111875575, val_loss: 0.00343130014126042
epochs 3/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0029518104210422423, val_loss: 0.0014546713653927374
epochs 4/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00155292098030546, val_loss: 0.0007446500737722473
epochs 5/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0010601564662800613, val_loss: 0.0007857436537865157
epochs 6/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0011383555798889383, val_loss: 0.0010138575588107893
epochs 7/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0012943597004969457, val_loss: 0.001076183791768639
epochs 8/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0012328695159675063, val_loss: 0.0009398675424132594
epochs 9/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0010594812863641172, val_loss: 0.0007464908813984183
epochs 10/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0008104674320508677, val_loss: 0.0006356225952530574
epochs 11/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0006457540100918298, val_loss: 0.0006634805668574317
epochs 12/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0005878933049787424, val_loss: 0.0007995236332614073
epochs 13/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0006725538901886657, val_loss: 0.0009652450795616268
epochs 14/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0007767681985186707, val_loss: 0.0010833405567896798
epochs 15/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0007982454711485557, val_loss: 0.0011119366484069217
epochs 16/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.000800259766554901, val_loss: 0.0010497705572848454
epochs 17/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0007460515619880569, val_loss: 0.0009232078134357978
epochs 18/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0006428305819434555, val_loss: 0.0007793287306221349
epochs 19/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0005476379756337816, val_loss: 0.0006532713374135232
epochs 20/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0004540859980471922, val_loss: 0.0005622232171222812
epochs 21/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0003764262093586455, val_loss: 0.0005075726031607606
epochs 22/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0003347273093439933, val_loss: 0.00047738904862566604
epochs 23/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0003195090810645764, val_loss: 0.00046065900211320505
epochs 24/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00030187471006923403, val_loss: 0.0004511089203572881
epochs 25/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.000253545657324139, val_loss: 0.00044972174823909117
epochs 26/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00025416020369831176, val_loss: 0.00045870721599050357
epochs 27/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0002027101921205605, val_loss: 0.0004763843445720053
epochs 28/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00020785972332018182, val_loss: 0.0004948942811767522
epochs 29/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00019795173269047058, val_loss: 0.0005046309897136923
epochs 30/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001924026866235133, val_loss: 0.0004998461602218939
epochs 31/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00019052930116518645, val_loss: 0.00048040728257834226
epochs 32/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00018900614170553652, val_loss: 0.00045125367032596844
epochs 33/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00014326803939184173, val_loss: 0.00042130900814969975
epochs 34/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.000140521646512513, val_loss: 0.00039468244542245216
epochs 35/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00014195095255241827, val_loss: 0.0003758196346002239
epochs 36/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001236815604467043, val_loss: 0.00036536502317942093
epochs 37/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001124391588841957, val_loss: 0.000362613685367825
epochs 38/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00011295805402608638, val_loss: 0.00036341801536955725
epochs 39/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00010394006289731663, val_loss: 0.00036959123512803527
epochs 40/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.727910391551344e-05, val_loss: 0.00037899851779098085
epochs 41/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00011201299501791302, val_loss: 0.000385206169525382
epochs 42/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.71711597230751e-05, val_loss: 0.00038428589445845175
epochs 43/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.92184109667218e-05, val_loss: 0.00037652570792584143
epochs 44/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.990884768500875e-05, val_loss: 0.0003681497200312534
epochs 45/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00011357016563507434, val_loss: 0.000358506795677577
epochs 46/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.581247945071051e-05, val_loss: 0.00035314330146464176
epochs 47/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.403200992413699e-05, val_loss: 0.00035144817620197215
epochs 48/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.786947327819163e-05, val_loss: 0.00035330212826681275
epochs 49/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001020840770491448, val_loss: 0.0003581860310269373
epochs 50/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.55396451325597e-05, val_loss: 0.00036751024653265056
epochs 51/95
Current Learning Rate: 0.00046993838704028316
train_loss: 8.916517510538381e-05, val_loss: 0.00037689363969931083
epochs 52/95
Current Learning Rate: 0.00046993838704028316
train_loss: 8.82870224718078e-05, val_loss: 0.0003827207511149984
epochs 53/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.624304220778868e-05, val_loss: 0.0003843682585284114
epochs 54/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00010458889427306866, val_loss: 0.00038067221750296944
epochs 55/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.444239874842184e-05, val_loss: 0.0003747677415192715
epochs 56/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.015924714683359e-05, val_loss: 0.000371584840391542
epochs 57/95
Epoch 00057: reducing learning rate of group 0 to 3.6039e-04.
Current Learning Rate: 0.00036038958461923596
train_loss: 8.847801015546889e-05, val_loss: 0.00037148627697637204
epochs 58/95
Current Learning Rate: 0.00036038958461923596
train_loss: 8.934755621196114e-05, val_loss: 0.0003732689049732136
epochs 59/95
Current Learning Rate: 0.00036038958461923596
train_loss: 7.765881907145836e-05, val_loss: 0.0003788582070755135
epochs 60/95
Current Learning Rate: 0.00036038958461923596
train_loss: 9.139872586513919e-05, val_loss: 0.0003861166548296368
epochs 61/95
Current Learning Rate: 0.00036038958461923596
train_loss: 8.915502349784794e-05, val_loss: 0.0003922062746776072
epochs 62/95
Current Learning Rate: 0.00036038958461923596
train_loss: 0.00010016330408306156, val_loss: 0.00039320187367449856
epochs 63/95
Current Learning Rate: 0.00036038958461923596
train_loss: 9.996670380228591e-05, val_loss: 0.00038924497448054976
epochs 64/95
Current Learning Rate: 0.00036038958461923596
train_loss: 9.223770010928427e-05, val_loss: 0.0003842784462521147
epochs 65/95
Current Learning Rate: 0.00036038958461923596
train_loss: 9.560097973199415e-05, val_loss: 0.00037980873656986086
epochs 66/95
Current Learning Rate: 0.00036038958461923596
train_loss: 8.435964302502965e-05, val_loss: 0.000379028521848867
epochs 67/95
Epoch 00067: reducing learning rate of group 0 to 2.7638e-04.
Current Learning Rate: 0.00027637804504549243
train_loss: 8.738091070738032e-05, val_loss: 0.0003817622720625399
epochs 68/95
Current Learning Rate: 0.00027637804504549243
train_loss: 8.853648897983428e-05, val_loss: 0.0003841850820830778
epochs 69/95
Current Learning Rate: 0.00027637804504549243
train_loss: 8.340259155374952e-05, val_loss: 0.00038816592124548104
epochs 70/95
Current Learning Rate: 0.00027637804504549243
train_loss: 7.839440356627547e-05, val_loss: 0.0003918014528799655
epochs 71/95
Current Learning Rate: 0.00027637804504549243
train_loss: 8.314172917284611e-05, val_loss: 0.0003942748952172942
epochs 72/95
Current Learning Rate: 0.00027637804504549243
train_loss: 9.138114535170117e-05, val_loss: 0.0003968796007316805
epochs 73/95
Current Learning Rate: 0.00027637804504549243
train_loss: 8.618550882123313e-05, val_loss: 0.00039646494704739826
epochs 74/95
Current Learning Rate: 0.00027637804504549243
train_loss: 9.28361942274741e-05, val_loss: 0.0003948065425471501
epochs 75/95
Current Learning Rate: 0.00027637804504549243
train_loss: 8.614264385725715e-05, val_loss: 0.00039114561177005895
epochs 76/95
Current Learning Rate: 0.00027637804504549243
train_loss: 9.575887884956932e-05, val_loss: 0.0003889597286041336
epochs 77/95
Epoch 00077: reducing learning rate of group 0 to 2.1195e-04.
Current Learning Rate: 0.00021195069736510685
train_loss: 8.31722033724777e-05, val_loss: 0.00038879016133968865
epochs 78/95
Current Learning Rate: 0.00021195069736510685
train_loss: 8.595603407899801e-05, val_loss: 0.0003877583999143864
epochs 79/95
Current Learning Rate: 0.00021195069736510685
train_loss: 9.180014910127379e-05, val_loss: 0.0003863460015916069
epochs 80/95
Current Learning Rate: 0.00021195069736510685
train_loss: 8.785346703677389e-05, val_loss: 0.00038622120880877205
epochs 81/95
Current Learning Rate: 0.00021195069736510685
train_loss: 9.141753727913295e-05, val_loss: 0.00038704763696602496
epochs 82/95
Current Learning Rate: 0.00021195069736510685
train_loss: 8.267371204534643e-05, val_loss: 0.000389640746748467
epochs 83/95
Current Learning Rate: 0.00021195069736510685
train_loss: 8.335920069121609e-05, val_loss: 0.000393050256657022
epochs 84/95
Current Learning Rate: 0.00021195069736510685
train_loss: 8.358144466336326e-05, val_loss: 0.0003959960692507019
epochs 85/95
Current Learning Rate: 0.00021195069736510685
train_loss: 9.332551191236187e-05, val_loss: 0.00039825126487381854
epochs 86/95
Current Learning Rate: 0.00021195069736510685
train_loss: 0.00011676146900036226, val_loss: 0.00039811698064257046
epochs 87/95
Epoch 00087: reducing learning rate of group 0 to 1.6254e-04.
Current Learning Rate: 0.00016254220955271852
train_loss: 0.00011438358315468863, val_loss: 0.0003968181127627184
epochs 88/95
Current Learning Rate: 0.00016254220955271852
train_loss: 8.284189844791973e-05, val_loss: 0.0003973377058221223
epochs 89/95
Current Learning Rate: 0.00016254220955271852
train_loss: 9.828353680572228e-05, val_loss: 0.0003960991805989148
epochs 90/95
Current Learning Rate: 0.00016254220955271852
train_loss: 8.676137103496953e-05, val_loss: 0.0003955586919083113
epochs 91/95
Current Learning Rate: 0.00016254220955271852
train_loss: 9.219992747315892e-05, val_loss: 0.00039478227944958857
epochs 92/95
Current Learning Rate: 0.00016254220955271852
train_loss: 9.246114901830687e-05, val_loss: 0.0003933801525578785
epochs 93/95
Current Learning Rate: 0.00016254220955271852
train_loss: 0.00012048041451060654, val_loss: 0.0003920047804345622
epochs 94/95
Current Learning Rate: 0.00016254220955271852
train_loss: 9.23677364067101e-05, val_loss: 0.00039065644661221945
epochs 95/95
Current Learning Rate: 0.00016254220955271852
train_loss: 8.632321317379952e-05, val_loss: 0.00038904265499073323
Starting fold 2:
epochs 1/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00033843865909913897, val_loss: 0.013288493116239183
epochs 2/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00021288298207525116, val_loss: 0.010880266772092957
epochs 3/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0002469841992837916, val_loss: 0.010997363241193325
epochs 4/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00025066836223183937, val_loss: 0.01182017047203293
epochs 5/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0002195328895858869, val_loss: 0.011378640811400194
epochs 6/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001921544406190821, val_loss: 0.010350089003086874
epochs 7/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00022318296423212526, val_loss: 0.009965710991405342
epochs 8/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00021196988366826094, val_loss: 0.01011760346101303
epochs 9/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00020108541162028957, val_loss: 0.01001527137613218
epochs 10/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00019008737246239385, val_loss: 0.009476483120632016
epochs 11/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00018484548228642732, val_loss: 0.008904518231161332
epochs 12/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00019256675234493358, val_loss: 0.008844690676778556
epochs 13/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00017972004620548287, val_loss: 0.008936949199261635
epochs 14/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00017798832783515344, val_loss: 0.00864808676813386
epochs 15/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001763774967816732, val_loss: 0.008116955998794813
epochs 16/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001690515293280202, val_loss: 0.007975236276213668
epochs 17/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00018964001938002185, val_loss: 0.007975452830769905
epochs 18/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00016922499853535555, val_loss: 0.00789714843819016
epochs 19/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00016344164495852678, val_loss: 0.007656051538345453
epochs 20/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00016904360923753733, val_loss: 0.007373181431505241
epochs 21/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00017053015535087692, val_loss: 0.007342388654911988
epochs 22/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001594785198616783, val_loss: 0.007172115361563077
epochs 23/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00016027254463743271, val_loss: 0.007044451196040762
epochs 24/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001534056128500532, val_loss: 0.006916743595349161
epochs 25/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00014766640185706292, val_loss: 0.006650148242663004
epochs 26/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00015188386887051534, val_loss: 0.006529506303271965
epochs 27/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00014740339865966235, val_loss: 0.006537032794011266
epochs 28/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00014766109506078798, val_loss: 0.006424031325762993
epochs 29/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00013232417119357515, val_loss: 0.006209889135176414
epochs 30/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00013066195864858425, val_loss: 0.006036328594200313
epochs 31/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00013001448224761255, val_loss: 0.006012685838351516
epochs 32/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001395915149930117, val_loss: 0.0059345477236140715
epochs 33/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001290194843214091, val_loss: 0.0056308186392446885
epochs 34/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00013175181470854257, val_loss: 0.005496584015016101
epochs 35/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00012543258714063803, val_loss: 0.00563554820286012
epochs 36/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00011488812827002747, val_loss: 0.005428783491400904
epochs 37/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00011668099455403678, val_loss: 0.005135639133176913
epochs 38/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00012248550969831597, val_loss: 0.00501460969619649
epochs 39/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00011108523182261515, val_loss: 0.0050135008708917
epochs 40/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00011493148974152159, val_loss: 0.004837804499670471
epochs 41/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00011640073379997998, val_loss: 0.0046642282499784705
epochs 42/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001092069514446561, val_loss: 0.004509369972603101
epochs 43/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00011340190224138113, val_loss: 0.004478373264550771
epochs 44/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.0001064803542057665, val_loss: 0.004405457259302861
epochs 45/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00010837778938462419, val_loss: 0.004168536582054865
epochs 46/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00010072392896721507, val_loss: 0.004070339059628742
epochs 47/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.89313171885442e-05, val_loss: 0.004083961293738531
epochs 48/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.745083055014747e-05, val_loss: 0.004015341773629189
epochs 49/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.856497121003676e-05, val_loss: 0.003774980120483394
epochs 50/95
Current Learning Rate: 0.00046993838704028316
train_loss: 0.00010483931741634335, val_loss: 0.003699151495177495
epochs 51/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.757667842342543e-05, val_loss: 0.003641218549302338
epochs 52/95
Current Learning Rate: 0.00046993838704028316
train_loss: 8.732068004304126e-05, val_loss: 0.003483376373830987
epochs 53/95
Current Learning Rate: 0.00046993838704028316
train_loss: 8.574836101615801e-05, val_loss: 0.0033566386812660647
epochs 54/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.407737883233685e-05, val_loss: 0.0033164179834880327
epochs 55/95
Current Learning Rate: 0.00046993838704028316
train_loss: 8.536008729271616e-05, val_loss: 0.00306049495580067
epochs 56/95
Current Learning Rate: 0.00046993838704028316
train_loss: 8.971651391460143e-05, val_loss: 0.003046716995978434
epochs 57/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.26045896784145e-05, val_loss: 0.002896190353816277
epochs 58/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.311848441843482e-05, val_loss: 0.0026932160854094517
epochs 59/95
Current Learning Rate: 0.00046993838704028316
train_loss: 9.296942495750141e-05, val_loss: 0.002622785164337409
epochs 60/95

[I 2024-01-26 13:20:32,163] Trial 11 finished with value: 0.0016396158199197513 and parameters: {'batch_size': 127, 'epochs': 95, 'hidden_size': 69, 'learning_rate': 0.00046993838704028316, 'dropout_prob': 0.005546344352455934, 'weight_decay': 3.51204391965916e-05, 'lr_step_size': 9, 'gamma': 0.7668868825315676, 'num_layers': 1}. Best is trial 10 with value: 0.0015551751845140963.

Current Learning Rate: 0.00027637804504549243
train_loss: 0.00028766550682408513, val_loss: 0.0007778933078761359
epochs 95/95
Current Learning Rate: 0.00027637804504549243
train_loss: 0.00030845243828815384, val_loss: 0.0007925808739137689
Mean validation loss: 0.0016396158199197513
Starting fold 1:
epochs 1/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.007100229262141511, val_loss: 0.007627647772039238
epochs 2/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.00475996610873967, val_loss: 0.005129112626769041
epochs 3/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.00324028971310901, val_loss: 0.0034065863626126787
epochs 4/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.0023078749134009214, val_loss: 0.0023039948510765835
epochs 5/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.001762375516179753, val_loss: 0.001662881402788978
epochs 6/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.0014982532679201348, val_loss: 0.0013274620346859784
epochs 7/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.001385633338328549, val_loss: 0.0011676247352672936
epochs 8/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.001308806565296101, val_loss: 0.0010982572312442291
epochs 9/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.0012379736081991148, val_loss: 0.0010783102579329064
epochs 10/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.001136181848797653, val_loss: 0.0010956913162341439
epochs 11/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.0010750810422714015, val_loss: 0.0011506224855302686
epochs 12/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.0009839905536194382, val_loss: 0.0012416136706872893
epochs 13/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.0009251714132628158, val_loss: 0.0013585816094602802
epochs 14/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.0008932566941152082, val_loss: 0.0014847489691180128
epochs 15/95
Epoch 00015: reducing learning rate of group 0 to 2.8037e-04.
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0008999723953341968, val_loss: 0.0015979935513123085
epochs 16/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.000886117414828684, val_loss: 0.0016664481557917927
epochs 17/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0008801463259212476, val_loss: 0.0016978447699282123
epochs 18/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0008640973105732548, val_loss: 0.0016893978345538735
epochs 19/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0008498197853393656, val_loss: 0.0016461318029446135
epochs 20/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0008003489175615342, val_loss: 0.0015759334537984902
epochs 21/95
Epoch 00021: reducing learning rate of group 0 to 2.3545e-04.
Current Learning Rate: 0.00023544566017400935
train_loss: 0.0007527629510916181, val_loss: 0.0014870039792425048
epochs 22/95
Current Learning Rate: 0.00023544566017400935
train_loss: 0.000679023130061595, val_loss: 0.0014058198219189715
epochs 23/95
Current Learning Rate: 0.00023544566017400935
train_loss: 0.0006530051416790996, val_loss: 0.001324792253466225
epochs 24/95
Current Learning Rate: 0.00023544566017400935
train_loss: 0.0005954322095739803, val_loss: 0.0012497270945459604
epochs 25/95
Current Learning Rate: 0.00023544566017400935
train_loss: 0.0005484476192290649, val_loss: 0.0011825576835115881
epochs 26/95
Current Learning Rate: 0.00023544566017400935
train_loss: 0.0005080114005403103, val_loss: 0.0011259803813453274
epochs 27/95
Epoch 00027: reducing learning rate of group 0 to 1.9772e-04.
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0004902855134691651, val_loss: 0.0010801209812358905
epochs 28/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00047314892091028586, val_loss: 0.0010508207477151268
epochs 29/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0004290494458186195, val_loss: 0.001029461855834693
epochs 30/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00041195937220963013, val_loss: 0.0010148979267748809
epochs 31/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0003897303738324952, val_loss: 0.0010054229431644718
epochs 32/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.000368419096890935, val_loss: 0.0010002867097347534
epochs 33/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00036008193963329847, val_loss: 0.0009989672543413593
epochs 34/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0003459383699871404, val_loss: 0.0009991987069952301
epochs 35/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00033104068103344427, val_loss: 0.000999629516751922
epochs 36/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00030581735527927155, val_loss: 0.0009999969997902794
epochs 37/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0003030218403038912, val_loss: 0.0009977889553594746
epochs 38/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0002884804269629776, val_loss: 0.0009935315278677367
epochs 39/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0002761708206411353, val_loss: 0.0009859906622870383
epochs 40/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0002633568406484923, val_loss: 0.0009753162533008052
epochs 41/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0002533974997564464, val_loss: 0.0009623686233872401
epochs 42/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0002476711952017228, val_loss: 0.0009465150887416185
epochs 43/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00023209088187860815, val_loss: 0.0009298166762547273
epochs 44/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0002212012973215774, val_loss: 0.0009123309391342397
epochs 45/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00020739345705614572, val_loss: 0.000895581724992218
epochs 46/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00020121331763220952, val_loss: 0.0008800461254156145
epochs 47/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00019362872500144142, val_loss: 0.0008664290263703534
epochs 48/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00018451458469682716, val_loss: 0.0008551111968699843
epochs 49/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0001805606203944128, val_loss: 0.0008452479719907339
epochs 50/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00017591306241229176, val_loss: 0.0008376737827539296
epochs 51/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0001683152900353123, val_loss: 0.0008319220717806418
epochs 52/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0001526176228684275, val_loss: 0.0008271387343196884
epochs 53/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00015826723216665222, val_loss: 0.0008218760105113401
epochs 54/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00016501306925324332, val_loss: 0.0008160097446402927
epochs 55/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00014713637275762218, val_loss: 0.0008099300446031664
epochs 56/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00015590590069462594, val_loss: 0.0008029531309914187
epochs 57/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00014890029652681397, val_loss: 0.0007972343356078981
epochs 58/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0001316102101746334, val_loss: 0.0007920430098525493
epochs 59/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0001338393290337224, val_loss: 0.0007880258392297516
epochs 60/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0001287016025009124, val_loss: 0.0007851402034774717
epochs 61/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00012585337753989734, val_loss: 0.0007834307433528776
epochs 62/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00012642115145449918, val_loss: 0.0007811528736247534
epochs 63/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00013422573438698525, val_loss: 0.0007782616904526213
epochs 64/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0001232324644086858, val_loss: 0.0007758754240440842
epochs 65/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00012097619393515694, val_loss: 0.0007726123941737521
epochs 66/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00012182168670972858, val_loss: 0.0007687229195940553
epochs 67/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00012131025199012488, val_loss: 0.0007643787592410503
epochs 68/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00012375399674056098, val_loss: 0.000760228299891184
epochs 69/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00011949496938062734, val_loss: 0.0007582235833979212
epochs 70/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00011336604450326903, val_loss: 0.0007561534487697492
epochs 71/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00010885957453865558, val_loss: 0.000754611139602371
epochs 72/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00012057859777613837, val_loss: 0.0007509842684253511
epochs 73/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00011154543945418768, val_loss: 0.0007469168974478778
epochs 74/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00011797600324682303, val_loss: 0.000743585530864565
epochs 75/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00011290443948574217, val_loss: 0.0007415150257752669
epochs 76/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00010674518834045892, val_loss: 0.0007397800164701613
epochs 77/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0001170887426460946, val_loss: 0.000739887374450183
epochs 78/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.0001222054170380273, val_loss: 0.0007424772799008918
epochs 79/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00011135154479569265, val_loss: 0.0007466547652208982
epochs 80/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00011939273401941663, val_loss: 0.0007500280903370462
epochs 81/95
Current Learning Rate: 0.00019772126927044545
train_loss: 0.00010991123448260815, val_loss: 0.0007503502990737999
epochs 82/95
Epoch 00082: reducing learning rate of group 0 to 1.6604e-04.
Current Learning Rate: 0.00016604128652455627
train_loss: 0.00010963394199375455, val_loss: 0.0007477424564728464
epochs 83/95
Current Learning Rate: 0.00016604128652455627
train_loss: 0.00010582734145205713, val_loss: 0.000745382833625435
epochs 84/95
Current Learning Rate: 0.00016604128652455627
train_loss: 0.00010473993514958573, val_loss: 0.0007444439239885756
epochs 85/95
Current Learning Rate: 0.00016604128652455627
train_loss: 0.00010436822807318286, val_loss: 0.0007454697452454926
epochs 86/95
Current Learning Rate: 0.00016604128652455627
train_loss: 0.00011023579251119181, val_loss: 0.0007463870425310329
epochs 87/95
Current Learning Rate: 0.00016604128652455627
train_loss: 0.00010509809956267035, val_loss: 0.0007478942810465876
epochs 88/95
Epoch 00088: reducing learning rate of group 0 to 1.3944e-04.
Current Learning Rate: 0.00013943724381528032
train_loss: 0.00010302220597575223, val_loss: 0.0007495337884297202
epochs 89/95
Current Learning Rate: 0.00013943724381528032
train_loss: 0.00010560097484573673, val_loss: 0.0007491626205400711
epochs 90/95
Current Learning Rate: 0.00013943724381528032
train_loss: 0.00010537609234329705, val_loss: 0.0007491767713585624
epochs 91/95
Current Learning Rate: 0.00013943724381528032
train_loss: 0.0001026010393520425, val_loss: 0.000748678068339359
epochs 92/95
Current Learning Rate: 0.00013943724381528032
train_loss: 0.00010461136660428326, val_loss: 0.0007485865459066669
epochs 93/95
Current Learning Rate: 0.00013943724381528032
train_loss: 0.00010559702373269063, val_loss: 0.0007476598665418446
epochs 94/95
Epoch 00094: reducing learning rate of group 0 to 1.1710e-04.
Current Learning Rate: 0.00011709584627872954
train_loss: 0.00010341769356225421, val_loss: 0.0007453888590374079
epochs 95/95
Current Learning Rate: 0.00011709584627872954
train_loss: 0.00010879402934254981, val_loss: 0.0007432378476981907
Starting fold 2:
epochs 1/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.00044897355479693753, val_loss: 0.015864429142522184
epochs 2/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.000317998324010803, val_loss: 0.013130119099820915
epochs 3/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.00043651976647149577, val_loss: 0.014079168985450738
epochs 4/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.00038974371924077307, val_loss: 0.015738369936221526
epochs 5/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.00036207203849794736, val_loss: 0.016252596612627568
epochs 6/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.00032928083337059144, val_loss: 0.015387694432253116
epochs 7/95
Current Learning Rate: 0.00033386069245239626
train_loss: 0.00029856051202698024, val_loss: 0.01405397340361225
epochs 8/95
Epoch 00008: reducing learning rate of group 0 to 2.8037e-04.
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00030531164329180394, val_loss: 0.013219372075247137
epochs 9/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00031643152320420516, val_loss: 0.013161456109465737
epochs 10/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00030962944660323526, val_loss: 0.013438448978980121
epochs 11/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002974066008678883, val_loss: 0.013668803784898237
epochs 12/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002882304262081896, val_loss: 0.013572400315713726
epochs 13/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00028932494820573516, val_loss: 0.013153694704861232
epochs 14/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00027958557605559597, val_loss: 0.012627189871119826
epochs 15/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00027406460572628453, val_loss: 0.012235372131200213
epochs 16/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002720481328938867, val_loss: 0.012057525693978133
epochs 17/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00027114934664017424, val_loss: 0.012035236338545618
epochs 18/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002619497865548749, val_loss: 0.011996270725993734
epochs 19/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00026022449298914965, val_loss: 0.011857191360506572
epochs 20/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002594697977704192, val_loss: 0.011584029042799222
epochs 21/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00026199894288622184, val_loss: 0.01130057679195153
epochs 22/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00025174343620739433, val_loss: 0.011053467537031361
epochs 23/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002516273806625242, val_loss: 0.010896516167313644
epochs 24/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00024412121109842127, val_loss: 0.010786360818402547
epochs 25/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002442125825358457, val_loss: 0.010664881412920199
epochs 26/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00022967141611795677, val_loss: 0.010494075896904657
epochs 27/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00023196857693715412, val_loss: 0.010298085492104292
epochs 28/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.000236813409183493, val_loss: 0.010078584718959113
epochs 29/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00022551718115880104, val_loss: 0.009888811105568157
epochs 30/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00022360364007334665, val_loss: 0.009748816953383779
epochs 31/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002276906020262303, val_loss: 0.009613533582734434
epochs 32/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.000228582091107168, val_loss: 0.009501408175320218
epochs 33/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00021985665034184135, val_loss: 0.009374099295880449
epochs 34/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002111668441916424, val_loss: 0.00922395979593459
epochs 35/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00021758541621047219, val_loss: 0.009072126766764804
epochs 36/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002047019518182711, val_loss: 0.008906942647636721
epochs 37/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00020228326535097471, val_loss: 0.008759195769303724
epochs 38/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00020128066358953027, val_loss: 0.008621033143840337
epochs 39/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0002036095192076908, val_loss: 0.008458378955133652
epochs 40/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0001973673495261832, val_loss: 0.008289605844765902
epochs 41/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0001918952577206686, val_loss: 0.00815217542265983
epochs 42/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0001901117001053583, val_loss: 0.008068552228475087
epochs 43/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00019391513933920864, val_loss: 0.007977205545543448
epochs 44/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00018517532675775184, val_loss: 0.007831102305729138
epochs 45/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0001859400314730776, val_loss: 0.007658718126875005
epochs 46/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0001804638210160192, val_loss: 0.007514220973672835
epochs 47/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00017302487180323193, val_loss: 0.007384143079827098
epochs 48/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00017040447279501487, val_loss: 0.00729541652958448
epochs 49/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00017428988264184324, val_loss: 0.007214912346956369
epochs 50/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00016984115942537563, val_loss: 0.007089303551535858
epochs 51/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00016811253249455292, val_loss: 0.006939056487508902
epochs 52/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00016679652226708928, val_loss: 0.006797898422289444
epochs 53/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00016491235652019417, val_loss: 0.006671186546353918
epochs 54/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00016229254958345432, val_loss: 0.006576338232690959
epochs 55/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.0001632622336106387, val_loss: 0.00650385082576816
epochs 56/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00016880334794558093, val_loss: 0.006372214391778566
epochs 57/95
Current Learning Rate: 0.00028036770702170096
train_loss: 0.00016331410243813145, val_loss: 0.0061963882897735426
epochs 58/95
Current Learning Rate: 0.00028036770702170096

[I 2024-01-26 13:21:18,135] Trial 12 finished with value: 0.002409991604707158 and parameters: {'batch_size': 127, 'epochs': 95, 'hidden_size': 67, 'learning_rate': 0.00033386069245239626, 'dropout_prob': 0.0021563309034467125, 'weight_decay': 3.1493521360338275e-05, 'lr_step_size': 5, 'gamma': 0.8397745327916294, 'num_layers': 1}. Best is trial 10 with value: 0.0015551751845140963.

Current Learning Rate: 0.00016604128652455627
train_loss: 0.0002897527852588897, val_loss: 0.0008124994362189778
Mean validation loss: 0.002409991604707158
Starting fold 1:
epochs 1/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.003139251707072713, val_loss: 0.0011796578005152313
epochs 2/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0012509899238418592, val_loss: 0.0013724820678410316
epochs 3/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0009472151835277481, val_loss: 0.0020468702121625507
epochs 4/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0011156586188773969, val_loss: 0.0011373446605591054
epochs 5/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0006557310360030418, val_loss: 0.0007208140566945076
epochs 6/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0007067969110242924, val_loss: 0.0006490531490846096
epochs 7/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00044294230312133504, val_loss: 0.0008737562233459596
epochs 8/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00038584288267884403, val_loss: 0.0010515711936597272
epochs 9/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0003253923292504624, val_loss: 0.00048668179431268457
epochs 10/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00018222853916660442, val_loss: 0.00048561739049067623
epochs 11/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0003842233351621728, val_loss: 0.0005657252074390846
epochs 12/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0002570116922326729, val_loss: 0.0008127993411586717
epochs 13/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00020901196610219287, val_loss: 0.0004441364168949229
epochs 14/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0001440254389308393, val_loss: 0.0003919244742351829
epochs 15/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00019888160738781535, val_loss: 0.0005491627264602453
epochs 16/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0001541170251010427, val_loss: 0.0007793160647117091
epochs 17/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00013636562733537223, val_loss: 0.0006037339665406188
epochs 18/98
Current Learning Rate: 0.0019845077540416012
train_loss: 9.84312031313924e-05, val_loss: 0.0004534155671870777
epochs 19/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0001337290427871171, val_loss: 0.0005446791318000148
epochs 20/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00010218099533200363, val_loss: 0.0007699649473100802
epochs 21/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00011238865493061511, val_loss: 0.0007004426878043696
epochs 22/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.000109633982202994, val_loss: 0.0005125432776893783
epochs 23/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00011469371950768522, val_loss: 0.0005634913175048209
epochs 24/98
Current Learning Rate: 0.0019845077540416012
train_loss: 9.202358250101832e-05, val_loss: 0.0007531937655202407
epochs 25/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00011214611517253185, val_loss: 0.000670383327662038
epochs 26/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00010456662900028995, val_loss: 0.0005181109986886823
epochs 27/98
Current Learning Rate: 0.0019845077540416012
train_loss: 9.547344594274795e-05, val_loss: 0.0005610403372740716
epochs 28/98
Current Learning Rate: 0.0019845077540416012
train_loss: 9.235685283783823e-05, val_loss: 0.000657086418313587
epochs 29/98
Epoch 00029: reducing learning rate of group 0 to 1.4835e-03.
Current Learning Rate: 0.0014835335863596095
train_loss: 9.864932887323544e-05, val_loss: 0.0006098010838430032
epochs 30/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.679857351951987e-05, val_loss: 0.0005497291846519434
epochs 31/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.55203945799363e-05, val_loss: 0.000539575370356416
epochs 32/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.676038962317091e-05, val_loss: 0.000566989772701881
epochs 33/98
Current Learning Rate: 0.0014835335863596095
train_loss: 7.857732248100403e-05, val_loss: 0.0005766549793311003
epochs 34/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.303027266134067e-05, val_loss: 0.0005467547122909883
epochs 35/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.854259683989528e-05, val_loss: 0.0005321704329904413
epochs 36/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.224255970593443e-05, val_loss: 0.0005296960692871117
epochs 37/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.499294610577635e-05, val_loss: 0.00054045132664645
epochs 38/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.554268332725195e-05, val_loss: 0.000515506952682412
epochs 39/98
Current Learning Rate: 0.0014835335863596095
train_loss: 7.739380740340014e-05, val_loss: 0.0004965145461794332
epochs 40/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.414534135047641e-05, val_loss: 0.0005288848475749164
epochs 41/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.462959725109517e-05, val_loss: 0.0005360305747384892
epochs 42/98
Current Learning Rate: 0.0014835335863596095
train_loss: 7.691837216905122e-05, val_loss: 0.0005316371821161163
epochs 43/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.704768088615598e-05, val_loss: 0.0005135536842556719
epochs 44/98
Epoch 00044: reducing learning rate of group 0 to 1.1090e-03.
Current Learning Rate: 0.001109026607416757
train_loss: 9.403910191490707e-05, val_loss: 0.0004939994229827885
epochs 45/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.840288528039023e-05, val_loss: 0.0005319193726264577
epochs 46/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.460101472385424e-05, val_loss: 0.0005406352319129693
epochs 47/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.275496852308462e-05, val_loss: 0.0005005973416126308
epochs 48/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.7667243458686e-05, val_loss: 0.00047818683761809215
epochs 49/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.25419445295426e-05, val_loss: 0.0005077436979550648
epochs 50/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.240043868059537e-05, val_loss: 0.0005424222821985543
epochs 51/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.140727199803988e-05, val_loss: 0.0005366432205559441
epochs 52/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.785912968481792e-05, val_loss: 0.0004927903943002764
epochs 53/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.013114477906033e-05, val_loss: 0.0004994765587310356
epochs 54/98
Current Learning Rate: 0.001109026607416757
train_loss: 7.050717042722299e-05, val_loss: 0.0005413416577012915
epochs 55/98
Current Learning Rate: 0.001109026607416757
train_loss: 9.170420472448888e-05, val_loss: 0.0005147514145248447
epochs 56/98
Current Learning Rate: 0.001109026607416757
train_loss: 9.095196789865823e-05, val_loss: 0.0004940530499688496
epochs 57/98
Current Learning Rate: 0.001109026607416757
train_loss: 9.312302898156065e-05, val_loss: 0.0005229511132806932
epochs 58/98
Current Learning Rate: 0.001109026607416757
train_loss: 8.064137337465868e-05, val_loss: 0.0005298424538571118
epochs 59/98
Epoch 00059: reducing learning rate of group 0 to 8.2906e-04.
Current Learning Rate: 0.0008290611195237095
train_loss: 7.993240731976633e-05, val_loss: 0.0005284522709476541
epochs 60/98
Current Learning Rate: 0.0008290611195237095
train_loss: 8.589876183817212e-05, val_loss: 0.0005030746680093121
epochs 61/98
Current Learning Rate: 0.0008290611195237095
train_loss: 8.416377811380172e-05, val_loss: 0.0005003393030308776
epochs 62/98
Current Learning Rate: 0.0008290611195237095
train_loss: 8.454805168807261e-05, val_loss: 0.000535104198742805
epochs 63/98
Current Learning Rate: 0.0008290611195237095
train_loss: 8.164697344335237e-05, val_loss: 0.0005378585168632286
epochs 64/98
Current Learning Rate: 0.0008290611195237095
train_loss: 7.620346847321152e-05, val_loss: 0.0005150241657821951
epochs 65/98
Current Learning Rate: 0.0008290611195237095
train_loss: 7.910220734438075e-05, val_loss: 0.0004944091080687941
epochs 66/98
Current Learning Rate: 0.0008290611195237095
train_loss: 8.30256868778777e-05, val_loss: 0.0005004654499843079
epochs 67/98
Current Learning Rate: 0.0008290611195237095
train_loss: 7.773127504869511e-05, val_loss: 0.000535781199716056
epochs 68/98
Current Learning Rate: 0.0008290611195237095
train_loss: 7.783021849861957e-05, val_loss: 0.0005201160183979051
epochs 69/98
Current Learning Rate: 0.0008290611195237095
train_loss: 8.28649209564135e-05, val_loss: 0.0004992513803651826
epochs 70/98
Current Learning Rate: 0.0008290611195237095
train_loss: 7.824995378828853e-05, val_loss: 0.000505961777525954
epochs 71/98
Current Learning Rate: 0.0008290611195237095
train_loss: 8.910721103587237e-05, val_loss: 0.0005368777843327016
epochs 72/98
Current Learning Rate: 0.0008290611195237095
train_loss: 7.614760378553336e-05, val_loss: 0.0005480309694049586
epochs 73/98
Current Learning Rate: 0.0008290611195237095
train_loss: 7.144739011939811e-05, val_loss: 0.0005165009991814211
epochs 74/98
Epoch 00074: reducing learning rate of group 0 to 6.1977e-04.
Current Learning Rate: 0.0006197708290398236
train_loss: 8.009448517297738e-05, val_loss: 0.0005035897109911801
epochs 75/98
Current Learning Rate: 0.0006197708290398236
train_loss: 7.169584534590525e-05, val_loss: 0.0005162507508908962
epochs 76/98
Current Learning Rate: 0.0006197708290398236
train_loss: 8.26186197580108e-05, val_loss: 0.0005080443296863354
epochs 77/98
Current Learning Rate: 0.0006197708290398236
train_loss: 8.09993343289917e-05, val_loss: 0.0005130341035271015
epochs 78/98
Current Learning Rate: 0.0006197708290398236
train_loss: 7.814776943537015e-05, val_loss: 0.0005225585564882127
epochs 79/98
Current Learning Rate: 0.0006197708290398236
train_loss: 8.040298114218259e-05, val_loss: 0.0005224556696990284
epochs 80/98
Current Learning Rate: 0.0006197708290398236
train_loss: 7.627421207297104e-05, val_loss: 0.000519037336925976
epochs 81/98
Current Learning Rate: 0.0006197708290398236
train_loss: 8.90455880404548e-05, val_loss: 0.0005066815080920749
epochs 82/98
Current Learning Rate: 0.0006197708290398236
train_loss: 7.925418237726646e-05, val_loss: 0.0004952470626832158
epochs 83/98
Current Learning Rate: 0.0006197708290398236
train_loss: 7.765588640100568e-05, val_loss: 0.0005077500798506662
epochs 84/98
Current Learning Rate: 0.0006197708290398236
train_loss: 7.466714799336746e-05, val_loss: 0.0005163974526160593
epochs 85/98
Current Learning Rate: 0.0006197708290398236
train_loss: 8.045059171548162e-05, val_loss: 0.0005159698583348042
epochs 86/98
Current Learning Rate: 0.0006197708290398236
train_loss: 7.30785851039017e-05, val_loss: 0.0005146583573246301
epochs 87/98
Current Learning Rate: 0.0006197708290398236
train_loss: 7.984710747749839e-05, val_loss: 0.0005108923606856384
epochs 88/98
Current Learning Rate: 0.0006197708290398236
train_loss: 7.533010606206709e-05, val_loss: 0.0005010591578626957
epochs 89/98
Epoch 00089: reducing learning rate of group 0 to 4.6331e-04.
Current Learning Rate: 0.0004633143099864368
train_loss: 7.88995456547893e-05, val_loss: 0.0004904013814475068
epochs 90/98
Current Learning Rate: 0.0004633143099864368
train_loss: 7.410205984534083e-05, val_loss: 0.0004879272210880452
epochs 91/98
Current Learning Rate: 0.0004633143099864368
train_loss: 8.538496082397422e-05, val_loss: 0.0004883886820799059
epochs 92/98
Current Learning Rate: 0.0004633143099864368
train_loss: 7.777669483115651e-05, val_loss: 0.0004913637545924805
epochs 93/98
Current Learning Rate: 0.0004633143099864368
train_loss: 8.016288131904347e-05, val_loss: 0.0005088537393021398
epochs 94/98
Current Learning Rate: 0.0004633143099864368
train_loss: 7.979291635580777e-05, val_loss: 0.0005229406305404968
epochs 95/98
Current Learning Rate: 0.0004633143099864368
train_loss: 7.123423588621479e-05, val_loss: 0.000495773204142767
epochs 96/98
Current Learning Rate: 0.0004633143099864368
train_loss: 7.355637154480638e-05, val_loss: 0.00047313208484219536
epochs 97/98
Current Learning Rate: 0.0004633143099864368
train_loss: 7.9105785928397e-05, val_loss: 0.00047284253485390526
epochs 98/98
Current Learning Rate: 0.0004633143099864368
train_loss: 7.653956272406504e-05, val_loss: 0.0004956108084067972
Starting fold 2:
epochs 1/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0009269002754559838, val_loss: 0.002155039211012129
epochs 2/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.002113270893192078, val_loss: 0.0294010597232141
epochs 3/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0010454522281897402, val_loss: 0.026323065847942705
epochs 4/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00040738957185040863, val_loss: 0.014868925144209674
epochs 5/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0009461148197787176, val_loss: 0.0176041867829075
epochs 6/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0005835202575039339, val_loss: 0.022357157343312315
epochs 7/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00040887517220414196, val_loss: 0.016460620825129904
epochs 8/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0002705966878765091, val_loss: 0.009543053115914135
epochs 9/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0003911500312633028, val_loss: 0.009964288538321852
epochs 10/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00023776648020812949, val_loss: 0.008140134288145131
epochs 11/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00015898298588581383, val_loss: 0.003866638359001004
epochs 12/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.0002435638473942067, val_loss: 0.00406643485889378
epochs 13/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00019565828483073826, val_loss: 0.003653794153912091
epochs 14/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00016945458425509155, val_loss: 0.002796828863057798
epochs 15/98
Current Learning Rate: 0.0019845077540416012
train_loss: 0.00019307332992244292, val_loss: 0.003770986424550708
epochs 16/98
Epoch 00016: reducing learning rate of group 0 to 1.4835e-03.
Current Learning Rate: 0.0014835335863596095
train_loss: 0.0001476814593556092, val_loss: 0.003438499214826152
epochs 17/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00014694399021544468, val_loss: 0.0031086403511979273
epochs 18/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00015874146968264158, val_loss: 0.0033467273230934026
epochs 19/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00013233205356396195, val_loss: 0.0028599665857128504
epochs 20/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00013436691444535667, val_loss: 0.002432668156689033
epochs 21/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.0001357511097586738, val_loss: 0.0022740048602970906
epochs 22/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00011946250805952954, val_loss: 0.0018862621420626775
epochs 23/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00011893125994997957, val_loss: 0.0017874776243268953
epochs 24/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00012416272561255792, val_loss: 0.0015861254655694784
epochs 25/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00012007581346168942, val_loss: 0.0014432326308451593
epochs 26/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00010871850095817967, val_loss: 0.0014171128819917183
epochs 27/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00010875021222378373, val_loss: 0.0012453608769359753
epochs 28/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00010528270468057599, val_loss: 0.0012060521357374167
epochs 29/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00010385990349995585, val_loss: 0.0011735435602818862
epochs 30/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.56045797609381e-05, val_loss: 0.0011951459142820616
epochs 31/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.323255222912657e-05, val_loss: 0.0012499368443202815
epochs 32/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.777946602908502e-05, val_loss: 0.0014095869013353397
epochs 33/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.564775612045962e-05, val_loss: 0.0014389518482953703
epochs 34/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.46348590704637e-05, val_loss: 0.0017388651796959732
epochs 35/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.143364240439902e-05, val_loss: 0.0020292130439836338
epochs 36/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.696932121235142e-05, val_loss: 0.0020859086236573363
epochs 37/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.159855960433274e-05, val_loss: 0.0023414423591212223
epochs 38/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.894129653778356e-05, val_loss: 0.0020542186709414973
epochs 39/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.17402332082642e-05, val_loss: 0.0020061089540831744
epochs 40/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00011467439813522536, val_loss: 0.0017326486701341836
epochs 41/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00011891659511380376, val_loss: 0.001300552565187804
epochs 42/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.0001453795937681877, val_loss: 0.0012781356700303915
epochs 43/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00015280066585738065, val_loss: 0.00115684545690831
epochs 44/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00013331857027974603, val_loss: 0.001135862906659512
epochs 45/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00014572316902462934, val_loss: 0.0013835237643338347
epochs 46/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.737877649297986e-05, val_loss: 0.0011404599161132386
epochs 47/98
Current Learning Rate: 0.0014835335863596095
train_loss: 0.00012116067168550982, val_loss: 0.0012460498657004026
epochs 48/98
Current Learning Rate: 0.0014835335863596095
train_loss: 7.264465792487547e-05, val_loss: 0.001262884021516105
epochs 49/98
Current Learning Rate: 0.0014835335863596095
train_loss: 7.938646859225915e-05, val_loss: 0.001190572244874937
epochs 50/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.091115137894552e-05, val_loss: 0.0015135338407401976
epochs 51/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.562552623181163e-05, val_loss: 0.0015437430726658358
epochs 52/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.08725912448656e-05, val_loss: 0.0013400588785053083
epochs 53/98
Current Learning Rate: 0.0014835335863596095
train_loss: 8.328564755701288e-05, val_loss: 0.0014678967467166091
epochs 54/98
Current Learning Rate: 0.0014835335863596095
train_loss: 7.453279279281177e-05, val_loss: 0.001225072785133594
epochs 55/98
Current Learning Rate: 0.0014835335863596095
train_loss: 7.76343407491559e-05, val_loss: 0.0015127913971235485
epochs 56/98
Current Learning Rate: 0.0014835335863596095
train_loss: 7.778236165330256e-05, val_loss: 0.0013782392366250094
epochs 57/98
Current Learning Rate: 0.0014835335863596095
train_loss: 9.596013562833449e-05, val_loss: 0.0015656492366504513
epochs 58/98
Current Learning Rate: 0.0014835335863596095

[I 2024-01-26 13:21:41,909] Trial 13 pruned.

Epoch 00075: reducing learning rate of group 0 to 6.1977e-04.
Current Learning Rate: 0.0006197708290398236
train_loss: 0.0001768999971669441, val_loss: 0.0016812479362430933
epochs 76/98
Starting fold 1:
epochs 1/82
Current Learning Rate: 8.252166386310128e-05
train_loss: 0.001766459722267954, val_loss: 0.0013995568439560502
epochs 2/82
Current Learning Rate: 8.252166386310128e-05
train_loss: 0.0016126766482270078, val_loss: 0.0015431596606504173
epochs 3/82
Current Learning Rate: 8.252166386310128e-05
train_loss: 0.001494559709374842, val_loss: 0.0016866675826206214
epochs 4/82
Current Learning Rate: 8.252166386310128e-05
train_loss: 0.001578173842771273, val_loss: 0.0018161457038092378
epochs 5/82
Current Learning Rate: 8.252166386310128e-05
train_loss: 0.001412509610925458, val_loss: 0.0019134632945918527
epochs 6/82
Current Learning Rate: 8.252166386310128e-05
train_loss: 0.001342954975552857, val_loss: 0.001988307728530153
epochs 7/82
Current Learning Rate: 8.252166386310128e-05
train_loss: 0.0013256903639749476, val_loss: 0.0020254884583042246
epochs 8/82
Epoch 00008: reducing learning rate of group 0 to 2.8548e-05.
Current Learning Rate: 2.8548456329477276e-05
train_loss: 0.0013210270774403686, val_loss: 0.0020423421002066645
epochs 9/82
Current Learning Rate: 2.8548456329477276e-05
train_loss: 0.0013801334781180087, val_loss: 0.002041261221625303
epochs 10/82
Current Learning Rate: 2.8548456329477276e-05
train_loss: 0.0013191202030468144, val_loss: 0.002033571638840888
epochs 11/82
Current Learning Rate: 2.8548456329477276e-05
train_loss: 0.0012575270853152402, val_loss: 0.0020207602846264642
epochs 12/82
Current Learning Rate: 2.8548456329477276e-05
train_loss: 0.001391153955390971, val_loss: 0.0020025606787959604
epochs 13/82
Current Learning Rate: 2.8548456329477276e-05
train_loss: 0.0013011803262327846, val_loss: 0.001982178643811494
epochs 14/82
Current Learning Rate: 2.8548456329477276e-05
train_loss: 0.0013839662001517259, val_loss: 0.001958492769565629
epochs 15/82
Epoch 00015: reducing learning rate of group 0 to 9.8764e-06.
Current Learning Rate: 9.876368466686922e-06
train_loss: 0.0011903410544618965, val_loss: 0.0019341525863733535
epochs 16/82
Current Learning Rate: 9.876368466686922e-06
train_loss: 0.0011834506313071439, val_loss: 0.0019257280678414788
epochs 17/82
Current Learning Rate: 9.876368466686922e-06
train_loss: 0.0012551060136358598, val_loss: 0.0019166001611952916
epochs 18/82
Current Learning Rate: 9.876368466686922e-06
train_loss: 0.0013577918595585384, val_loss: 0.0019075659799119948
epochs 19/82
Current Learning Rate: 9.876368466686922e-06
train_loss: 0.0012882184494580878, val_loss: 0.0018991683285046173
epochs 20/82
Current Learning Rate: 9.876368466686922e-06
train_loss: 0.0011721700043907683, val_loss: 0.0018911926400553632
epochs 21/82
Current Learning Rate: 9.876368466686922e-06
train_loss: 0.0013259223123130044, val_loss: 0.001883458160783017
epochs 22/82
Epoch 00022: reducing learning rate of group 0 to 3.4167e-06.
Current Learning Rate: 3.416740049410363e-06
train_loss: 0.0013075666134490778, val_loss: 0.001875790926983188
epochs 23/82
Current Learning Rate: 3.416740049410363e-06
train_loss: 0.001326475077994952, val_loss: 0.001873214798060393
epochs 24/82
Current Learning Rate: 3.416740049410363e-06
train_loss: 0.0012897036148627338, val_loss: 0.0018706175566062723
epochs 25/82
Current Learning Rate: 3.416740049410363e-06
train_loss: 0.0011733024650694508, val_loss: 0.0018682981825948349
epochs 26/82
Current Learning Rate: 3.416740049410363e-06
train_loss: 0.0011714718034981112, val_loss: 0.0018660150330489208
epochs 27/82
Current Learning Rate: 3.416740049410363e-06
train_loss: 0.0013399077162734772, val_loss: 0.0018638951982690118
epochs 28/82
Current Learning Rate: 3.416740049410363e-06
train_loss: 0.0012833478633853558, val_loss: 0.001862093239507981
epochs 29/82
Epoch 00029: reducing learning rate of group 0 to 1.1820e-06.
Current Learning Rate: 1.1820248104980707e-06
train_loss: 0.001085960002321946, val_loss: 0.0018603662549714116
epochs 30/82

[I 2024-01-26 13:21:43,788] Trial 14 pruned.

Current Learning Rate: 1.1820248104980707e-06
train_loss: 0.0011961199428984208, val_loss: 0.001859817229591212
epochs 31/82
Current Learning Rate: 1.1820248104980707e-06
train_loss: 0.0012088312007682888, val_loss: 0.0018593145764163254
epochs 32/82
Starting fold 1:
epochs 1/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.002035699532318272, val_loss: 0.007913234555407574
epochs 2/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.004498448662802969, val_loss: 0.003575353995945893
epochs 3/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0022312683972383015, val_loss: 0.001242514609016086
epochs 4/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0015718015768614254, val_loss: 0.0010525519959628583
epochs 5/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0016063424415494265, val_loss: 0.0010161653234574356
epochs 6/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0011714576743543149, val_loss: 0.0013085606900092802
epochs 7/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0008718205493335661, val_loss: 0.0020323858008180792
epochs 8/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0010629463585485753, val_loss: 0.002309711233369614
epochs 9/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0010472539671402621, val_loss: 0.0017410029314066234
epochs 10/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0007904356829576978, val_loss: 0.000988304612569903
epochs 11/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0005234705480305772, val_loss: 0.000685962670678763
epochs 12/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0005353103459224498, val_loss: 0.0006173022728609411
epochs 13/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0003839608088846465, val_loss: 0.0007265073958000071
epochs 14/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.000237780626201512, val_loss: 0.0010540654123025505
epochs 15/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00030407117845147457, val_loss: 0.0007741195505092803
epochs 16/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00018961503243956126, val_loss: 0.00045013068317386663
epochs 17/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00028164486299685546, val_loss: 0.0004337973298357898
epochs 18/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00027946356812639064, val_loss: 0.0005710683628230502
epochs 19/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00020752200737325966, val_loss: 0.000770472677571601
epochs 20/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00018593522867089824, val_loss: 0.0007440247144059915
epochs 21/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00015611456995094685, val_loss: 0.0006233229706259935
epochs 22/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0001537170302502713, val_loss: 0.0005678756174778468
epochs 23/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00015897415823450215, val_loss: 0.000596549170777986
epochs 24/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0001517484526725878, val_loss: 0.0006677943171541158
epochs 25/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00014346624727630498, val_loss: 0.0006784884712511772
epochs 26/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00012962795169043698, val_loss: 0.0005835324917968951
epochs 27/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0001341463178457496, val_loss: 0.0005028302462673501
epochs 28/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0001213610925141869, val_loss: 0.0005194523138925434
epochs 29/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00012904075326667608, val_loss: 0.0006015207802288627
epochs 30/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00012335314577763997, val_loss: 0.0005713591437884851
epochs 31/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00011371923625885852, val_loss: 0.0005018262756302168
epochs 32/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00012054609764355087, val_loss: 0.0004918712185156581
epochs 33/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00013560092277322455, val_loss: 0.0005549125765499316
epochs 34/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00010560359759868955, val_loss: 0.000591881078128752
epochs 35/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0001130742374746325, val_loss: 0.0005462997139578587
epochs 36/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00012837039401730228, val_loss: 0.0004873644983346917
epochs 37/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00010448985075957975, val_loss: 0.0005078655716619993
epochs 38/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00013205836095087425, val_loss: 0.0005463118885496729
epochs 39/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0001066592767816282, val_loss: 0.000499106580881696
epochs 40/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00010936694115547365, val_loss: 0.00045846145305978626
epochs 41/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.0001170938846802241, val_loss: 0.0004732969474341524
epochs 42/111
Current Learning Rate: 0.0018636070131033211
train_loss: 0.00012007796383266778, val_loss: 0.0004948100810380358
epochs 43/111
Epoch 00043: reducing learning rate of group 0 to 1.4147e-03.
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010092004016960824, val_loss: 0.0004719248188561515
epochs 44/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010330851984786261, val_loss: 0.00048092590203802836
epochs 45/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.0001071445020467141, val_loss: 0.0004890580869917023
epochs 46/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.48156173475773e-05, val_loss: 0.0004913521526185306
epochs 47/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00011662897488445435, val_loss: 0.0005129221312113498
epochs 48/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00011459635463420694, val_loss: 0.00048665654919061223
epochs 49/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.92723174644389e-05, val_loss: 0.00045171802569376796
epochs 50/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.0001011831003492453, val_loss: 0.0004637461345593788
epochs 51/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.0001123212423408404, val_loss: 0.00046606607992496146
epochs 52/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.0001044939979788308, val_loss: 0.0004546855423158329
epochs 53/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010542249342267352, val_loss: 0.00044260431620243347
epochs 54/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.948456388787906e-05, val_loss: 0.00047213376659017644
epochs 55/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010673601079217502, val_loss: 0.00048673403890509356
epochs 56/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010170460307946134, val_loss: 0.00045363590684964467
epochs 57/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.963017571288602e-05, val_loss: 0.0004295516826555525
epochs 58/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010043045224033688, val_loss: 0.0004379186528048625
epochs 59/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.529766393825411e-05, val_loss: 0.0004699503310563925
epochs 60/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010215036730331026, val_loss: 0.00048270151386723705
epochs 61/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00011278993149876203, val_loss: 0.0004646401754335353
epochs 62/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.378457800362651e-05, val_loss: 0.00042109406357140915
epochs 63/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.0001049745362251997, val_loss: 0.0004236384778969774
epochs 64/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.873232553026786e-05, val_loss: 0.0004744540630398612
epochs 65/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.358594849656679e-05, val_loss: 0.0004699182966233868
epochs 66/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.350299997573816e-05, val_loss: 0.00047046534631303266
epochs 67/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.994796685568106e-05, val_loss: 0.0004645118722692132
epochs 68/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010476870260103361, val_loss: 0.0004595255957132107
epochs 69/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.163828347625799e-05, val_loss: 0.00045766918491081974
epochs 70/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010335009620145062, val_loss: 0.0004286431989289428
epochs 71/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.082400930837091e-05, val_loss: 0.0004288977661513184
epochs 72/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.522734677075948e-05, val_loss: 0.00045958799984011995
epochs 73/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.867598020814752e-05, val_loss: 0.0004529053663932963
epochs 74/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.368937261892777e-05, val_loss: 0.0004492943579527108
epochs 75/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.063677295527764e-05, val_loss: 0.00044480762015538
epochs 76/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.465525807555471e-05, val_loss: 0.0004134759717424841
epochs 77/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.969518783391993e-05, val_loss: 0.0004137468034107434
epochs 78/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.943661209502209e-05, val_loss: 0.00044323391844763567
epochs 79/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.44690801062327e-05, val_loss: 0.0005024518805408949
epochs 80/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.900457982427294e-05, val_loss: 0.0004543730137428563
epochs 81/111
Current Learning Rate: 0.001414698776839114
train_loss: 0.00010062798277144075, val_loss: 0.00040363402498003686
epochs 82/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.901619707773391e-05, val_loss: 0.0004242398065367812
epochs 83/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.497071817014856e-05, val_loss: 0.0004702446436950643
epochs 84/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.148150075864242e-05, val_loss: 0.00046639727232487577
epochs 85/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.425577206684179e-05, val_loss: 0.00044067585411922713
epochs 86/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.897232060247149e-05, val_loss: 0.0004193882721378223
epochs 87/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.286745158820658e-05, val_loss: 0.00042702830641677507
epochs 88/111
Current Learning Rate: 0.001414698776839114
train_loss: 9.061067493779486e-05, val_loss: 0.0004321858403272927
epochs 89/111

[I 2024-01-26 13:21:48,626] Trial 15 pruned.

Current Learning Rate: 0.001414698776839114
train_loss: 8.917298592247167e-05, val_loss: 0.0004360308858418935
epochs 90/111
Current Learning Rate: 0.001414698776839114
train_loss: 8.336471088880085e-05, val_loss: 0.0004359116924828605
epochs 91/111
Current Learning Rate: 0.001414698776839114
train_loss: 7.867006689163023e-05, val_loss: 0.0004533601502005599
epochs 92/111
Starting fold 1:
epochs 1/85
Current Learning Rate: 0.09442705798670074
train_loss: 20.2924540616817, val_loss: 1.4922306888981869
epochs 2/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.9783616172639947, val_loss: 2.0080585053092554
epochs 3/85
Current Learning Rate: 0.09442705798670074
train_loss: 1.2053969123253696, val_loss: 0.34282737437047456
epochs 4/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.4446961515828183, val_loss: 0.013446811831703312
epochs 5/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.12093594576183118, val_loss: 0.2428402354842738
epochs 6/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.23411762086968674, val_loss: 0.018793968795293232
epochs 7/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.1398211839951967, val_loss: 0.01456432276846547
epochs 8/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.11671683411849172, val_loss: 0.14713350816776877
epochs 9/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.227591566976748, val_loss: 0.006525261366837903
epochs 10/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.1311261241373263, val_loss: 0.040053853062655485
epochs 11/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.14003683501168301, val_loss: 0.036524849894799684
epochs 12/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.14178891197631233, val_loss: 0.031159774802233045
epochs 13/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.12095726524528704, val_loss: 0.029929265855370382
epochs 14/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.12057193125549116, val_loss: 0.03190228719460337
epochs 15/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.12970227159951864, val_loss: 0.042104082789860275
epochs 16/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0991502602633677, val_loss: 0.026968665028873243
epochs 17/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.11941332660223308, val_loss: 0.021108731666677878
epochs 18/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.1056166167321958, val_loss: 0.020592679397055978
epochs 19/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.10263894153268714, val_loss: 0.013667480667170726
epochs 20/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0658994480379318, val_loss: 0.08132137789538033
epochs 21/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.12434209247953014, val_loss: 0.0066703735556649536
epochs 22/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.08559209673028244, val_loss: 0.004941246898746804
epochs 23/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.07112079803880893, val_loss: 0.035527858569433815
epochs 24/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.05701806615842016, val_loss: 0.010722958639656242
epochs 25/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.055289202850115925, val_loss: 0.033366439766005465
epochs 26/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.059735260982262464, val_loss: 0.01061169607564807
epochs 27/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.03538278941261141, val_loss: 0.02853336942284123
epochs 28/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.05419641542003343, val_loss: 0.046685267945653516
epochs 29/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.07256333537791905, val_loss: 0.005458260180526658
epochs 30/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.030970985716895053, val_loss: 0.006708045102851955
epochs 31/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.027979139669945367, val_loss: 0.05476766118877813
epochs 32/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.054700197455914396, val_loss: 0.012013558425793523
epochs 33/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.04495180478613628, val_loss: 0.010385513898769492
epochs 34/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.02716385322181802, val_loss: 0.006157172821756257
epochs 35/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.025288120657205582, val_loss: 0.005050279190273661
epochs 36/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.020377262799363388, val_loss: 0.05363187546792783
epochs 37/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.04485565596505215, val_loss: 0.004210954380074614
epochs 38/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.01942447994492556, val_loss: 0.011876243441120574
epochs 39/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.01622950777313427, val_loss: 0.011965765617787838
epochs 40/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.014900186089308638, val_loss: 0.0049988816271683105
epochs 41/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.010914912476743522, val_loss: 0.014337759837508202
epochs 42/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.01502672482870127, val_loss: 0.006005228440718431
epochs 43/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.00902777471162967, val_loss: 0.0038512447799899075
epochs 44/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.011192207430538378, val_loss: 0.010890306689237293
epochs 45/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.00956764029044854, val_loss: 0.00427784844252624
epochs 46/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.007893212668989834, val_loss: 0.004061474758935602
epochs 47/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.00830988498698724, val_loss: 0.012199931817227288
epochs 48/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.009680209774523973, val_loss: 0.005880916917598561
epochs 49/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.008747564932625544, val_loss: 0.005661331362238056
epochs 50/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.006576405210714591, val_loss: 0.007634176882474046
epochs 51/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.008197463695940219, val_loss: 0.007163896911630505
epochs 52/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0062144021185016945, val_loss: 0.010406550657200185
epochs 53/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.009284974095460616, val_loss: 0.003603237534039899
epochs 54/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.004439718208863939, val_loss: 0.009711054619401693
epochs 55/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.006209355220198632, val_loss: 0.004759369538116612
epochs 56/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.004254217717894598, val_loss: 0.008689840059531363
epochs 57/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.006161228976653594, val_loss: 0.003666574103561671
epochs 58/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.004182680554099773, val_loss: 0.008418086264282466
epochs 59/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.005233367743264688, val_loss: 0.0038544500761322287
epochs 60/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.004859274914978366, val_loss: 0.008689268884298048
epochs 61/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0058662571472507955, val_loss: 0.0033477428871648094
epochs 62/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.004837062910787369, val_loss: 0.005920830660646683
epochs 63/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0040111784774221875, val_loss: 0.004172926116734743
epochs 64/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.004372961333903827, val_loss: 0.007569497269823363
epochs 65/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.005340284845595689, val_loss: 0.005527241116291598
epochs 66/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.003955100976714963, val_loss: 0.003927243237481698
epochs 67/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.002884935081544283, val_loss: 0.007628265327136768
epochs 68/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.004441476973557943, val_loss: 0.0028677226240305526
epochs 69/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0025791190000937175, val_loss: 0.007309695622442584
epochs 70/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0040189400927996945, val_loss: 0.0032196217853772014
epochs 71/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0027180892831989026, val_loss: 0.008836019034252355
epochs 72/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.004947953926105249, val_loss: 0.0039104551738618236
epochs 73/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.002688268496115741, val_loss: 0.005422825655458789
epochs 74/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.00331543419804228, val_loss: 0.0038410357775558765
epochs 75/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0026434805048139473, val_loss: 0.006572842745012359
epochs 76/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0033882580476960068, val_loss: 0.0034049826833468517
epochs 77/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.00244463602522094, val_loss: 0.004286194646632985
epochs 78/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.002676405345923022, val_loss: 0.00398984999199839
epochs 79/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0024886851713649535, val_loss: 0.004637597937529024
epochs 80/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0026532142919390217, val_loss: 0.0043641294842880025
epochs 81/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.002670593351419819, val_loss: 0.003845716289881813
epochs 82/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0022975939699742746, val_loss: 0.00472038474277054
epochs 83/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.002534047530130728, val_loss: 0.0032978467385921823
epochs 84/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.0020395221488893425, val_loss: 0.005287353204269158
epochs 85/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.002821181960845072, val_loss: 0.0027633690998252287
Starting fold 2:
epochs 1/85
Current Learning Rate: 0.09442705798670074
train_loss: 1.479415753303635, val_loss: 0.34516451358795164
epochs 2/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.18008099725090065, val_loss: 0.07787173555085533
epochs 3/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.017946873026850975, val_loss: 0.03909279394306635
epochs 4/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.16288314399946677, val_loss: 0.11948577871448116
epochs 5/85

[I 2024-01-26 13:21:54,135] Trial 16 pruned.

Current Learning Rate: 0.09442705798670074
train_loss: 0.12242939864334307, val_loss: 0.04192632148930754
epochs 6/85
Current Learning Rate: 0.09442705798670074
train_loss: 0.05594939244420905, val_loss: 0.20860285696230438
epochs 7/85
Starting fold 1:
epochs 1/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.022334109386429192, val_loss: 0.025074818436252443
epochs 2/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.017468971344887427, val_loss: 0.019546694700655183
epochs 3/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.013163771199699687, val_loss: 0.014795569989732221
epochs 4/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.009640777720089413, val_loss: 0.01080489662524901
epochs 5/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.006665260513239589, val_loss: 0.007567393282232316
epochs 6/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.004423576721379312, val_loss: 0.005059192011034802
epochs 7/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.002776733832969943, val_loss: 0.0032452496404355197
epochs 8/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.00165439137980636, val_loss: 0.00205515354403025
epochs 9/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0011376095963274374, val_loss: 0.0013750321718122762
epochs 10/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0008891652419391137, val_loss: 0.001057144664427094
epochs 11/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0008759010030189529, val_loss: 0.0009429798310616446
epochs 12/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0008193532291395394, val_loss: 0.0009131022872966959
epochs 13/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.000921580265122956, val_loss: 0.0009075553439049001
epochs 14/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.000851954592738031, val_loss: 0.0009147243859172848
epochs 15/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0008801409783221684, val_loss: 0.000938742099931819
epochs 16/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.000754496686185073, val_loss: 0.0009804983562054603
epochs 17/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0007755442974341445, val_loss: 0.0010300527433221424
epochs 18/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0007526673851412182, val_loss: 0.0010775157389473048
epochs 19/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0007095517319516818, val_loss: 0.0011112413093398669
epochs 20/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0007390210802489157, val_loss: 0.001124627814102783
epochs 21/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0007048841164520893, val_loss: 0.0011236806326594792
epochs 22/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0007635896556741116, val_loss: 0.0011099264405569748
epochs 23/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0007528058457721367, val_loss: 0.0010860704540391452
epochs 24/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0006532677374228738, val_loss: 0.0010584282303553712
epochs 25/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0006386271030733999, val_loss: 0.0010325434770110358
epochs 26/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0006502688589726428, val_loss: 0.0010164229041133934
epochs 27/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0006359075267315156, val_loss: 0.0010035825186749112
epochs 28/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0006283502464372616, val_loss: 0.0009947227883171045
epochs 29/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0005951440487957657, val_loss: 0.000992355070124368
epochs 30/72
Current Learning Rate: 0.00011457526042508523
train_loss: 0.0005999841615496399, val_loss: 0.0009948342873509605
epochs 31/72

[I 2024-01-26 13:21:56,579] Trial 17 pruned.

Current Learning Rate: 0.00011457526042508523
train_loss: 0.0005958660806706911, val_loss: 0.0009971078859770817
epochs 32/72
Starting fold 1:
epochs 1/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.006409653658537488, val_loss: 0.0015200287278275936
epochs 2/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0028009542607163127, val_loss: 0.0009887898788101188
epochs 3/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0022696860784076544, val_loss: 0.000966299098524216
epochs 4/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0018727148503163143, val_loss: 0.0008386104128715632
epochs 5/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0014827143891077293, val_loss: 0.0008828552899343011
epochs 6/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0012850289269791622, val_loss: 0.0010824029183774992
epochs 7/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0012724357534592088, val_loss: 0.0012190467953730963
epochs 8/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0014746221051992554, val_loss: 0.0010795814959381363
epochs 9/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0013383214668321766, val_loss: 0.0007536255901581363
epochs 10/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0008677558520024545, val_loss: 0.0005226316723948051
epochs 11/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0007233541189251762, val_loss: 0.0004921744847180028
epochs 12/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.000746331057560287, val_loss: 0.0005194140867771287
epochs 13/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0005802299643523599, val_loss: 0.00046665620328368326
epochs 14/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0005977090086640888, val_loss: 0.0004182620157830809
epochs 15/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0005887624452282724, val_loss: 0.00044866483781094615
epochs 16/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0005969865768412618, val_loss: 0.000463955965211713
epochs 17/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0006203261847411724, val_loss: 0.0004226264886950192
epochs 18/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00052486701292525, val_loss: 0.00039530824410336976
epochs 19/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0004831724132313148, val_loss: 0.0003985622628150802
epochs 20/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0005859311161513784, val_loss: 0.0003896074145909791
epochs 21/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00045881295319352494, val_loss: 0.00039311938882364254
epochs 22/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00045107456634899503, val_loss: 0.0004116620712202827
epochs 23/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0004800079807050918, val_loss: 0.00041927161157792923
epochs 24/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0004390095262543151, val_loss: 0.00043059959165188237
epochs 25/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00034836330205986375, val_loss: 0.00044183218131748665
epochs 26/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00032474208610916606, val_loss: 0.0004533371373422836
epochs 27/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0004112904848481872, val_loss: 0.00045647813929367416
epochs 28/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0003746755880695817, val_loss: 0.000438252077774929
epochs 29/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00037312225812408876, val_loss: 0.0004262001936838619
epochs 30/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00037430035023901026, val_loss: 0.00042859912531352355
epochs 31/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00034443007653432066, val_loss: 0.00044443662949274047
epochs 32/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0003231224867417232, val_loss: 0.0004896850219474322
epochs 33/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00032142946637529686, val_loss: 0.0005078427204065711
epochs 34/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0004186312677216177, val_loss: 0.0004933944788430572
epochs 35/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00032833525482074997, val_loss: 0.0004442085210221673
epochs 36/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00031481320069073453, val_loss: 0.00040962673788032445
epochs 37/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00034631149457326453, val_loss: 0.0004160974831871786
epochs 38/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00032595106994880266, val_loss: 0.00043188816481760066
epochs 39/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0002724841460708137, val_loss: 0.00043425216725537257
epochs 40/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00037501087645068764, val_loss: 0.0004282200623205618
epochs 41/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0003259451312356089, val_loss: 0.0004251684653450196
epochs 42/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.000328298154176752, val_loss: 0.00045756268648945383
epochs 43/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.000235895152620383, val_loss: 0.0004890059868461992
epochs 44/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00029409530658372924, val_loss: 0.0004618141188984737
epochs 45/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00024621159506128413, val_loss: 0.00044540957590614104
epochs 46/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0003558700386508319, val_loss: 0.0004579028719729793
epochs 47/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0002735746157429132, val_loss: 0.0004623080004852167
epochs 48/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00029562296082363707, val_loss: 0.0004662903580250905
epochs 49/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00027255977834819966, val_loss: 0.0004777814102310099
epochs 50/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0002777473320939431, val_loss: 0.0005093168304914511
epochs 51/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00027228337804492757, val_loss: 0.0005117036198498681
epochs 52/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0002669968044899992, val_loss: 0.0005141917295986787
epochs 53/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00025861345409219596, val_loss: 0.00046882496681064365
epochs 54/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00021101969744593494, val_loss: 0.00043591136759220573
epochs 55/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00028214570790480235, val_loss: 0.00042781976088391324
epochs 56/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0002684211496288251, val_loss: 0.00045181004143638636
epochs 57/108
Epoch 00057: reducing learning rate of group 0 to 7.5508e-04.
Current Learning Rate: 0.0007550827630055572
train_loss: 0.0002641249772798466, val_loss: 0.0005059347282727494
epochs 58/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.0003118644097795416, val_loss: 0.0005246902670478448
epochs 59/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00020605351693168478, val_loss: 0.0005284758229543896
epochs 60/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00025415346945488926, val_loss: 0.00048404301250181894
epochs 61/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.0002597113642351408, val_loss: 0.0004433817603919459
epochs 62/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00022487647488321128, val_loss: 0.0004323625065521092
epochs 63/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00030876413986429967, val_loss: 0.00043816892491457495
epochs 64/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00023045888581117125, val_loss: 0.00046275353831190026
epochs 65/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.000227566477444366, val_loss: 0.00048261479854485705
epochs 66/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00025618757507273634, val_loss: 0.0005006966587021261
epochs 67/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00022288664538217218, val_loss: 0.000506505023191781
epochs 68/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.000200364307200193, val_loss: 0.0004894292262370551
epochs 69/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00019098043435645338, val_loss: 0.00046166219690348955
epochs 70/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00024931532986413097, val_loss: 0.0004444107568001767
epochs 71/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00021210167247581442, val_loss: 0.0004359984715273114
epochs 72/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00018478642833590704, val_loss: 0.00043530723211772154
epochs 73/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.0002589398924579942, val_loss: 0.0004537130715202932
epochs 74/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00022353584277688674, val_loss: 0.0004772445586767342
epochs 75/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00021602059484729052, val_loss: 0.00048282877603349715
epochs 76/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00022533142274417178, val_loss: 0.0004715566482015052
epochs 77/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00021564506138307287, val_loss: 0.0004555696388706565
epochs 78/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00022202822820920694, val_loss: 0.0004404453758309644
epochs 79/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00018705419298432964, val_loss: 0.000436146509386354
epochs 80/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00019942404837102482, val_loss: 0.00044432016898338734
epochs 81/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.0002277471619891003, val_loss: 0.0004527022637806735
epochs 82/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.0002195271857903878, val_loss: 0.00046517528075798367
epochs 83/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00020958596754721122, val_loss: 0.000482178176906401
epochs 84/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00021993299581625156, val_loss: 0.0004955082093242948
epochs 85/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00024754107611155824, val_loss: 0.0004925766339415293
epochs 86/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00024652347017667793, val_loss: 0.00046733244686804126
epochs 87/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00023557744816092677, val_loss: 0.0004468022917679168
epochs 88/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00020593187992313974, val_loss: 0.00043005125296890345
epochs 89/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00023644102651527838, val_loss: 0.0004350572712658169
epochs 90/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00022336678475288576, val_loss: 0.0004394942577499406
epochs 91/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00022535747756544303, val_loss: 0.00044220931702415996
epochs 92/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00023222529163927232, val_loss: 0.0004597908939774099
epochs 93/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.00019350236199036438, val_loss: 0.00046833301296972325
epochs 94/108
Epoch 00094: reducing learning rate of group 0 to 4.8435e-04.
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00022098010277228527, val_loss: 0.00045579033367654405
epochs 95/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.0001930204466732807, val_loss: 0.00044666548538340356
epochs 96/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00018339293203194085, val_loss: 0.00043535638818100684
epochs 97/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00019380209054552802, val_loss: 0.0004427573283656353
epochs 98/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00023075800242000505, val_loss: 0.00044477771719501013
epochs 99/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.0001731550903059542, val_loss: 0.00045983184413910894
epochs 100/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.0001984349929874665, val_loss: 0.0004717549845257676
epochs 101/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00017798251003688692, val_loss: 0.0004824557914521153
epochs 102/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00016712309535298693, val_loss: 0.0004813227084109952
epochs 103/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00023455655839490263, val_loss: 0.00046534534684676483
epochs 104/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00017334730333746655, val_loss: 0.00044228810522901386
epochs 105/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00019697460244826384, val_loss: 0.00042505065303933073
epochs 106/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.0001959092383530285, val_loss: 0.00041232465484522675
epochs 107/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.00018910432991106063, val_loss: 0.00041439643996694177
epochs 108/108
Current Learning Rate: 0.00048435280524830674
train_loss: 0.0002101896186726854, val_loss: 0.0004220894308099033
Starting fold 2:
epochs 1/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00048807687263960315, val_loss: 0.00473066586388373
epochs 2/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0016847322626027132, val_loss: 0.008241298601129337
epochs 3/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0005367432607607425, val_loss: 0.012019855352608782
epochs 4/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0003119552321119332, val_loss: 0.007001087366064128
epochs 5/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00042722581466047194, val_loss: 0.003691825137081507
epochs 6/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0007574962221521051, val_loss: 0.004154067855377338
epochs 7/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00044484548025617475, val_loss: 0.006594574544578791
epochs 8/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00037346170636163537, val_loss: 0.004443477143190409
epochs 9/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00031321618421076747, val_loss: 0.0025017047190646594
epochs 10/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0004511495969429808, val_loss: 0.0034790084488984002
epochs 11/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00030601604680429627, val_loss: 0.004076008444749995
epochs 12/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00030750333466322014, val_loss: 0.003412653384485135
epochs 13/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00027342455612022987, val_loss: 0.002546990279255337
epochs 14/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0003230578870371621, val_loss: 0.0025501714345361843
epochs 15/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0003216850241427126, val_loss: 0.002053033153673536
epochs 16/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0002948732767675354, val_loss: 0.003040134010983533
epochs 17/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00032352497387603906, val_loss: 0.003018990261970382
epochs 18/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00023719452920455583, val_loss: 0.001731933147254351
epochs 19/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00029537455515023074, val_loss: 0.0020227841873604216
epochs 20/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00027250888815615325, val_loss: 0.0019784818636253477
epochs 21/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00024343373439286983, val_loss: 0.0016152357376229606
epochs 22/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00022130009601823987, val_loss: 0.002621543158679024
epochs 23/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00024001725553381747, val_loss: 0.002092606515476578
epochs 24/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00022592082731487034, val_loss: 0.0021937631242173283
epochs 25/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00021264035420149173, val_loss: 0.003369285377036584
epochs 26/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0001811459885701831, val_loss: 0.002479748816327437
epochs 27/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00022196414437004072, val_loss: 0.0018189998331332676
epochs 28/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.000278094145745088, val_loss: 0.001918947412387321
epochs 29/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00020542755458001537, val_loss: 0.001733938037221761
epochs 30/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00018692954189119566, val_loss: 0.0013499636705474633
epochs 31/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00020048235325559387, val_loss: 0.0014193459242386253
epochs 32/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00017573743274337366, val_loss: 0.0017719419280949392
epochs 33/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00019646430335246566, val_loss: 0.0018471093100838755
epochs 34/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0001710158965005049, val_loss: 0.0014761866548245674
epochs 35/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00019646513698573569, val_loss: 0.0018411609062336778
epochs 36/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0001588175105816366, val_loss: 0.0017014972767547558
epochs 37/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00015127554728870134, val_loss: 0.001526489568335053
epochs 38/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00015992180880474685, val_loss: 0.001709592303163127
epochs 39/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00015392825796305644, val_loss: 0.001538555540977732
epochs 40/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00015533587916012804, val_loss: 0.0017012542321983922
epochs 41/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0001621077583159173, val_loss: 0.001234254941932465
epochs 42/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0002102217047266956, val_loss: 0.0015629006500699019
epochs 43/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0002268894408572171, val_loss: 0.0029265156922567833
epochs 44/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00017933065851378303, val_loss: 0.0012064805401391105
epochs 45/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.000406294952048675, val_loss: 0.0016412169782836971
epochs 46/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00022967949392439454, val_loss: 0.004513993388728091
epochs 47/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00025508672661089804, val_loss: 0.0024006364327904426
epochs 48/108
Current Learning Rate: 0.0011771377657156651

[I 2024-01-26 13:22:43,970] Trial 18 finished with value: 0.0011512266347036932 and parameters: {'batch_size': 126, 'epochs': 108, 'hidden_size': 55, 'learning_rate': 0.0011771377657156651, 'dropout_prob': 0.127914833127579, 'weight_decay': 1.1312951163760579e-05, 'lr_step_size': 36, 'gamma': 0.6414565779787799, 'num_layers': 1}. Best is trial 18 with value: 0.0011512266347036932.

Current Learning Rate: 0.0007550827630055572
train_loss: 0.0007344037574703658, val_loss: 0.0007656941803074196
epochs 108/108
Current Learning Rate: 0.0007550827630055572
train_loss: 0.0007034872863502977, val_loss: 0.0007094502283603345
Mean validation loss: 0.0011512266347036932
Starting fold 1:
epochs 1/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0050891139054376824, val_loss: 0.0010978848563115064
epochs 2/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0018211645196731154, val_loss: 0.0010869102981431705
epochs 3/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0010100163038403384, val_loss: 0.0027825870875906396
epochs 4/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0016407038944491528, val_loss: 0.003159620918603124
epochs 5/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0015884643546183054, val_loss: 0.0018367367661803176
epochs 6/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0009327077300679919, val_loss: 0.0008442735339294335
epochs 7/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0006206597639615403, val_loss: 0.0006658975708935605
epochs 8/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0006688458655078552, val_loss: 0.0009088022282077489
epochs 9/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00042015267918989256, val_loss: 0.0016299803912835685
epochs 10/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0005549159342128979, val_loss: 0.0012649192442615075
epochs 11/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0003110785619355738, val_loss: 0.00047590039780755574
epochs 12/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00035134449947355807, val_loss: 0.00040404319511971583
epochs 13/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0005915810370903561, val_loss: 0.0006707759641454016
epochs 14/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00029905520741043513, val_loss: 0.0010296296179723484
epochs 15/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00031920984436414743, val_loss: 0.0007609618631632705
epochs 16/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00024855484202577685, val_loss: 0.0005685665367453016
epochs 17/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0003482249824293448, val_loss: 0.0006117046914847666
epochs 18/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0003390402095024719, val_loss: 0.000834442605417663
epochs 19/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0002749581717101759, val_loss: 0.000869824234733211
epochs 20/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00027301201311944937, val_loss: 0.0005856861106095542
epochs 21/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00025743318952950895, val_loss: 0.00047278784576950495
epochs 22/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00027987908642420446, val_loss: 0.0005813816556167838
epochs 23/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00022632024545026454, val_loss: 0.0006795657605643532
epochs 24/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00022196105917253974, val_loss: 0.0006259578738919165
epochs 25/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00020475297424127348, val_loss: 0.0005715051110631688
epochs 26/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0001905068966152612, val_loss: 0.0005899586027034706
epochs 27/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00018704823359209848, val_loss: 0.0005657575158310417
epochs 28/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0001996583182756838, val_loss: 0.0005568920666854339
epochs 29/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00018383645663944711, val_loss: 0.0006529435643307423
epochs 30/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00019388256815115087, val_loss: 0.0006884616071290925
epochs 31/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.0001701858828279288, val_loss: 0.00055472435403652
epochs 32/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00018613199829001372, val_loss: 0.00044916518871966556
epochs 33/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00025137255119931837, val_loss: 0.0005907778663401443
epochs 34/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00019103221711702645, val_loss: 0.0006309082412994222
epochs 35/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00019610531346284245, val_loss: 0.0004899185127885032
epochs 36/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00018176594657186223, val_loss: 0.00043271073005407264
epochs 37/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00020617116809405975, val_loss: 0.0006081574898225403
epochs 38/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00020316093555026638, val_loss: 0.0006221469210638469
epochs 39/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00018105205603397305, val_loss: 0.0004907821118984813
epochs 40/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00017980146329041178, val_loss: 0.0005019287047233727
epochs 41/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00014983399734391192, val_loss: 0.0005363551398132634
epochs 42/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00016078445830652, val_loss: 0.0005106826279906704
epochs 43/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00016298187524386632, val_loss: 0.00047736091456547573
epochs 44/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00016452597571371466, val_loss: 0.0005070871212458434
epochs 45/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00013844185703323762, val_loss: 0.0005994872170910975
epochs 46/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00017793341248761863, val_loss: 0.0004954486296475423
epochs 47/109
Current Learning Rate: 0.0016169040041149512
train_loss: 0.00013820594674478727, val_loss: 0.0004599101437059672
epochs 48/109
Epoch 00048: reducing learning rate of group 0 to 1.0416e-03.
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00016740692080929875, val_loss: 0.0004655706185363478
epochs 49/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.0001585258038463316, val_loss: 0.0005439703531201781
epochs 50/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00015874340935720523, val_loss: 0.0005289415482701244
epochs 51/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014226877178053225, val_loss: 0.0004741427087298545
epochs 52/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00015394519639238226, val_loss: 0.00046843540775099476
epochs 53/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.0001621836678455829, val_loss: 0.0005086328000240764
epochs 54/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.000149282602682146, val_loss: 0.0005399689704829239
epochs 55/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014872008001762688, val_loss: 0.000517909500845953
epochs 56/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00013834564532245216, val_loss: 0.0004884338410001396
epochs 57/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.0001675982003737437, val_loss: 0.0004925949726480452
epochs 58/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.0001413294705439751, val_loss: 0.0004768887677193178
epochs 59/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.000158558369117887, val_loss: 0.00044565060594131385
epochs 60/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014090866591830395, val_loss: 0.00048356526301512003
epochs 61/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014673541820804146, val_loss: 0.0005566232035849488
epochs 62/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.0001412495441495833, val_loss: 0.0005174146239082084
epochs 63/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00013316461397488112, val_loss: 0.0004486956501128397
epochs 64/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00013724220709838462, val_loss: 0.0005079237790165567
epochs 65/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014711132864345258, val_loss: 0.0005011434048738968
epochs 66/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014157751368321968, val_loss: 0.00042459126799306094
epochs 67/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00016238067741812157, val_loss: 0.00046954839222292463
epochs 68/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014498446896476182, val_loss: 0.00048024810453889107
epochs 69/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014635509681906305, val_loss: 0.0004373685178028322
epochs 70/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00013977696232215844, val_loss: 0.00044645823838532363
epochs 71/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014765605106061374, val_loss: 0.0004716573446210915
epochs 72/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00013392174820948735, val_loss: 0.0004990589709211092
epochs 73/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.000118103608799988, val_loss: 0.00048562511380480016
epochs 74/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00010791571950999481, val_loss: 0.00046138888865243644
epochs 75/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00013608741114455226, val_loss: 0.00041796970349662984
epochs 76/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00013573738435393592, val_loss: 0.00044294664181315487
epochs 77/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014008293414678375, val_loss: 0.0005572869041842703
epochs 78/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00013675610534846783, val_loss: 0.00047523735549092586
epochs 79/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00012372108674179273, val_loss: 0.00042999372664397875
epochs 80/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00011650398856114694, val_loss: 0.0004796437849443847
epochs 81/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00011067704594767604, val_loss: 0.0004191029733383881
epochs 82/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00013805814753715438, val_loss: 0.00037439267524812177
epochs 83/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.0001384680994976263, val_loss: 0.0004674757763400282
epochs 84/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.0001407178343039337, val_loss: 0.0005612641199197816
epochs 85/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00012907439668197185, val_loss: 0.0004092050328740458
epochs 86/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00015348073831869682, val_loss: 0.00040932049810898637
epochs 87/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00012467883099912127, val_loss: 0.0004836466273685035
epochs 88/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00012902244711049686, val_loss: 0.0004945982088285842
epochs 89/109

[I 2024-01-26 13:22:49,007] Trial 19 pruned.

Current Learning Rate: 0.0010415823731765804
train_loss: 0.0001222143201678256, val_loss: 0.0004261966310686579
epochs 90/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.00014083598398428876, val_loss: 0.0004179399658919704
epochs 91/109
Current Learning Rate: 0.0010415823731765804
train_loss: 0.0001255914084092518, val_loss: 0.0005466253569466062
epochs 92/109
Starting fold 1:
epochs 1/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.015699464065561955, val_loss: 0.008247189370817259
epochs 2/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.007915788805602413, val_loss: 0.000965422345784885
epochs 3/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0009355647618098087, val_loss: 0.005231741623413798
epochs 4/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0031487711080300964, val_loss: 0.005191549871999182
epochs 5/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00266257651873227, val_loss: 0.002274664366728087
epochs 6/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.001099808183866308, val_loss: 0.0007831951981643215
epochs 7/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0008861123991664499, val_loss: 0.0009707792744800253
epochs 8/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0013650872401501004, val_loss: 0.0008005508086889198
epochs 9/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0008459754426056813, val_loss: 0.000881256266668635
epochs 10/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0004844728509564639, val_loss: 0.00151152571840947
epochs 11/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0006557584390975534, val_loss: 0.0019583704199727723
epochs 12/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0008381909078085109, val_loss: 0.0017733453238370682
epochs 13/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0006226954819315946, val_loss: 0.0012331409909070077
epochs 14/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0004196886964277119, val_loss: 0.0008061569545565076
epochs 15/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00037765537394749885, val_loss: 0.0006475940512150134
epochs 16/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0004070788352309089, val_loss: 0.0006204640955394625
epochs 17/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.000387649336603078, val_loss: 0.0006973776362045962
epochs 18/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0002716924615302368, val_loss: 0.0009035995030181335
epochs 19/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00025048941576020107, val_loss: 0.0010584580370433334
epochs 20/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0003299131116364151, val_loss: 0.0009642532761637611
epochs 21/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00022076587253985435, val_loss: 0.0007687733331725834
epochs 22/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00023097951358833692, val_loss: 0.0005964251148581847
epochs 23/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00023874761199725695, val_loss: 0.0005466284766474641
epochs 24/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0002356741190612267, val_loss: 0.0005801931133885917
epochs 25/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001879661231405886, val_loss: 0.0006710310875572951
epochs 26/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001883077985870554, val_loss: 0.0007154551097253142
epochs 27/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001553255987298479, val_loss: 0.0006997523322321572
epochs 28/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0002101602466274543, val_loss: 0.0006098209822850644
epochs 29/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00016529829667170386, val_loss: 0.0005279575699732002
epochs 30/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001514368408702706, val_loss: 0.0005114582835966231
epochs 31/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001770307788224033, val_loss: 0.0005514245262020267
epochs 32/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00017630389369227678, val_loss: 0.00060366920362484
epochs 33/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00014643695467384533, val_loss: 0.000601718456815242
epochs 34/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00018219519728231, val_loss: 0.0005622160755784103
epochs 35/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00015508130791682848, val_loss: 0.0005516416497381502
epochs 36/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00013933797454228624, val_loss: 0.0005365845772566421
epochs 37/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00015390789784233724, val_loss: 0.000559720740880278
epochs 38/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00016853459704802126, val_loss: 0.0006245906864167314
epochs 39/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00016709931836598308, val_loss: 0.0006258710202114583
epochs 40/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00015174231015599186, val_loss: 0.0005608784550292368
epochs 41/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00015391988900343055, val_loss: 0.0005158892526340328
epochs 42/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00014887701216043513, val_loss: 0.000529396577085687
epochs 43/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00012442682001212807, val_loss: 0.0005503064489427121
epochs 44/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00014318006188228824, val_loss: 0.0005502562064257769
epochs 45/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00013488919419040414, val_loss: 0.0005244521777249726
epochs 46/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00013995290906965047, val_loss: 0.00046492893284027413
epochs 47/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00014602864945405407, val_loss: 0.0004784548773099423
epochs 48/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00015256344501578592, val_loss: 0.0005183626875039312
epochs 49/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011702496899248983, val_loss: 0.000524407969389454
epochs 50/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001230721893845935, val_loss: 0.0004947691193496882
epochs 51/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011752717990403701, val_loss: 0.0004970135287102925
epochs 52/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001468356599951604, val_loss: 0.0005098529369110781
epochs 53/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00014630747602112885, val_loss: 0.000518869026296
epochs 54/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00013297975513667457, val_loss: 0.0005187989548032515
epochs 55/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00014759617172929116, val_loss: 0.0004584025046297986
epochs 56/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00013893398519078466, val_loss: 0.000490322536145533
epochs 57/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00013723522780836853, val_loss: 0.0005816227683681063
epochs 58/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00013456442255502273, val_loss: 0.0006049042848309526
epochs 59/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.000124337663491085, val_loss: 0.0004981120799416921
epochs 60/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011859617117902656, val_loss: 0.000436152273553154
epochs 61/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001218084301064281, val_loss: 0.0005005290531507375
epochs 62/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001420995501623685, val_loss: 0.0005526286965744618
epochs 63/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001380001220815374, val_loss: 0.0005130564143703515
epochs 64/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00010957090968364163, val_loss: 0.0004731208645113695
epochs 65/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011679139777123438, val_loss: 0.000471583706415626
epochs 66/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001358637569386414, val_loss: 0.0005062262773112467
epochs 67/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011583016239455902, val_loss: 0.0005624063541242657
epochs 68/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011785899673429269, val_loss: 0.0005942443906142695
epochs 69/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00013642317261608122, val_loss: 0.0005284993844964591
epochs 70/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00013375281582978603, val_loss: 0.0004668406439840941
epochs 71/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00012721142426782631, val_loss: 0.0005389441660602307
epochs 72/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00010628541655789472, val_loss: 0.0006279580425670199
epochs 73/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00012201675792886434, val_loss: 0.00048583435587045787
epochs 74/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00010712692252893344, val_loss: 0.00047449204522356586
epochs 75/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00012375991259192998, val_loss: 0.0006027581774871673
epochs 76/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001095290535120416, val_loss: 0.0005895418455015475
epochs 77/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00010459548763097509, val_loss: 0.00045206045454649843
epochs 78/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011836397783267066, val_loss: 0.0005193223688126493
epochs 79/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00010662288025885478, val_loss: 0.0006165375841144276
epochs 80/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011454648533560287, val_loss: 0.0004760772376596977
epochs 81/104
Current Learning Rate: 0.00873603239210866
train_loss: 9.555504450537755e-05, val_loss: 0.00044683168617714393
epochs 82/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00012120809317964717, val_loss: 0.0006393407294557332
epochs 83/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00012585211481660064, val_loss: 0.0005532312492601034
epochs 84/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011882541117589234, val_loss: 0.00046512327719124425
epochs 85/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.0001074079692587379, val_loss: 0.0005618853390363879
epochs 86/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00010092014643688392, val_loss: 0.0005391378843341954
epochs 87/104
Current Learning Rate: 0.00873603239210866
train_loss: 9.810526692155308e-05, val_loss: 0.0005252606370241234
epochs 88/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011537570401407337, val_loss: 0.0005080075849515483
epochs 89/104
Current Learning Rate: 0.00873603239210866
train_loss: 0.00011132187210023403, val_loss: 0.0005076924087724795
epochs 90/104

[I 2024-01-26 13:22:53,452] Trial 20 pruned.

Current Learning Rate: 0.00873603239210866
train_loss: 0.0001087174239249802, val_loss: 0.00048484245214096614
epochs 91/104
Current Learning Rate: 0.00873603239210866
train_loss: 9.745143006990762e-05, val_loss: 0.0005625073694605626
epochs 92/104
Starting fold 1:
epochs 1/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.017091399941005204, val_loss: 0.007063393326672284
epochs 2/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.01523622448899244, val_loss: 0.005733875807766852
epochs 3/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.012613844891127787, val_loss: 0.00460098673908138
epochs 4/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.0115583570183892, val_loss: 0.003662435152249313
epochs 5/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.009254917110267439, val_loss: 0.0029151181567852436
epochs 6/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.00835956232132096, val_loss: 0.002348579365858122
epochs 7/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.007182682158523484, val_loss: 0.001957587810772422
epochs 8/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.006638682457177263, val_loss: 0.0017270398350726617
epochs 9/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.005492567908214895, val_loss: 0.0016399856362687914
epochs 10/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.004973343642134416, val_loss: 0.001678696750222068
epochs 11/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.004371441322329798, val_loss: 0.0018236478055386168
epochs 12/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.004629436929367091, val_loss: 0.0020565562783495376
epochs 13/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.0044065087102353575, val_loss: 0.002362547069787979
epochs 14/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.0040887553440897085, val_loss: 0.00270859775084414
epochs 15/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.0038350255571697888, val_loss: 0.003074667936092929
epochs 16/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.00386868088849281, val_loss: 0.003444947135683737
epochs 17/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.00429854141548276, val_loss: 0.003813341583468412
epochs 18/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.004306837784028367, val_loss: 0.004133748939554942
epochs 19/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.0037393159429101566, val_loss: 0.004400231885282617
epochs 20/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.003985290665571627, val_loss: 0.0046151276481778995
epochs 21/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.0044055614963566005, val_loss: 0.004775489582435081
epochs 22/87
Epoch 00022: reducing learning rate of group 0 to 2.6929e-04.
Current Learning Rate: 0.0002692928224978136
train_loss: 0.00437715346189706, val_loss: 0.004887390822956437
epochs 23/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.004275449850645504, val_loss: 0.004918442176360833
epochs 24/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.00428333753523858, val_loss: 0.0049084417031783805
epochs 25/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.004023442728641002, val_loss: 0.004875792955097399
epochs 26/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.004108847425270237, val_loss: 0.00482775416029127
epochs 27/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.003888920773016779, val_loss: 0.00475955456495285
epochs 28/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.0036394934464049965, val_loss: 0.004684109417231459
epochs 29/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.003999362236477042, val_loss: 0.0046016514203266095
epochs 30/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.0038919749620713686, val_loss: 0.004510223355732466
epochs 31/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.004097340251074026, val_loss: 0.004413149662707981
epochs 32/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.003737868863697115, val_loss: 0.004321256299552164
epochs 33/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.003652341906471472, val_loss: 0.004229262667266946
epochs 34/87
Current Learning Rate: 0.0002692928224978136
train_loss: 0.003349600585275575, val_loss: 0.0041443370184616034
epochs 35/87
Epoch 00035: reducing learning rate of group 0 to 1.8744e-04.
Current Learning Rate: 0.00018743703495840777
train_loss: 0.0037210493201487943, val_loss: 0.004061972085190446
epochs 36/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.0035719787799998333, val_loss: 0.004006630211676422
epochs 37/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.003245574951564011, val_loss: 0.003951335217999784
epochs 38/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.0033753510834159035, val_loss: 0.0039002786733602223
epochs 39/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.00314876276901678, val_loss: 0.0038482374952811945
epochs 40/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.0037427977144129966, val_loss: 0.0038050294216526183
epochs 41/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.0032675510738044977, val_loss: 0.0037622360610648207
epochs 42/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.0035751296648461567, val_loss: 0.0037255048751831054
epochs 43/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.003098214113790738, val_loss: 0.0036983497342781015
epochs 44/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.0036073701407172178, val_loss: 0.0036749065020366717
epochs 45/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.003587487991899252, val_loss: 0.0036544245030534894
epochs 46/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.0032494702229374332, val_loss: 0.0036370180351169485
epochs 47/87
Current Learning Rate: 0.00018743703495840777
train_loss: 0.0034750627353787424, val_loss: 0.0036204205041653233
epochs 48/87
Epoch 00048: reducing learning rate of group 0 to 1.3046e-04.
Current Learning Rate: 0.00013046260107539486
train_loss: 0.0031121875355510334, val_loss: 0.0036000033350367293
epochs 49/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.003248733184055278, val_loss: 0.003585447959209743
epochs 50/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.00375869920673339, val_loss: 0.0035705497586413434
epochs 51/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.002802039268671682, val_loss: 0.0035542803865514306
epochs 52/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.0027320905784635166, val_loss: 0.003536365053763515
epochs 53/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.0026998071318590326, val_loss: 0.0035142106641280024
epochs 54/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.0028313991564669107, val_loss: 0.003492721611339795
epochs 55/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.0030326312726461574, val_loss: 0.0034655893025429627
epochs 56/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.0033080263700532284, val_loss: 0.003440857139465056
epochs 57/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.0027291937755714907, val_loss: 0.0034172565039051208
epochs 58/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.003392680891250309, val_loss: 0.0033976772505986065
epochs 59/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.002623035070045214, val_loss: 0.0033791795863132726
epochs 60/87
Current Learning Rate: 0.00013046260107539486
train_loss: 0.003236669860780239, val_loss: 0.0033567062922214208
epochs 61/87
Epoch 00061: reducing learning rate of group 0 to 9.0806e-05.
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.00324400808956278, val_loss: 0.003338018794985194
epochs 62/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.0029936880927140777, val_loss: 0.0033285468130519517
epochs 63/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.003003682485340457, val_loss: 0.0033170376267088087
epochs 64/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.0031005082529430325, val_loss: 0.0033082570292447743
epochs 65/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.0028704276014315457, val_loss: 0.0033013185192095605
epochs 66/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.0031070504631651075, val_loss: 0.0032948022708296776
epochs 67/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.003171416617145664, val_loss: 0.003288229848993452
epochs 68/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.003073340325959419, val_loss: 0.0032836153613109336
epochs 69/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.0029545960335158987, val_loss: 0.0032784337766076387
epochs 70/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.00308535782081124, val_loss: 0.003272079088185963
epochs 71/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.0024762247321440983, val_loss: 0.003263964023637144
epochs 72/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.0030578128846460266, val_loss: 0.003255714289844036
epochs 73/87
Current Learning Rate: 9.080644219075736e-05
train_loss: 0.0028686479028118285, val_loss: 0.0032468985766172407
epochs 74/87
Epoch 00074: reducing learning rate of group 0 to 6.3204e-05.
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.002685276762043175, val_loss: 0.0032358497479244284
epochs 75/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.0026555230375379323, val_loss: 0.0032288594073370883
epochs 76/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.002959342837627781, val_loss: 0.003220443849108721
epochs 77/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.0027760629934307775, val_loss: 0.0032130343055254535
epochs 78/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.003409942876743643, val_loss: 0.0032043079698556346
epochs 79/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.002273348145382969, val_loss: 0.0031949341591251523
epochs 80/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.002872393704264572, val_loss: 0.0031882091278308314
epochs 81/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.002794144025660659, val_loss: 0.003183374504901861
epochs 82/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.0029398317546828795, val_loss: 0.003181015504033942
epochs 83/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.002432502730210361, val_loss: 0.003179792883364778
epochs 84/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.0023324773009670407, val_loss: 0.003174776064330026
epochs 85/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.002547768846546349, val_loss: 0.0031716287822315566
epochs 86/87
Current Learning Rate: 6.320439632027627e-05
train_loss: 0.0031735716436646485, val_loss: 0.0031686437071153993
epochs 87/87
Epoch 00087: reducing learning rate of group 0 to 4.3992e-05.
Current Learning Rate: 4.399242628423514e-05
train_loss: 0.002883118131247006, val_loss: 0.0031658448965141647
Starting fold 2:
epochs 1/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.0031490205296952475, val_loss: 0.06768036531774621
epochs 2/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.0028291296606001103, val_loss: 0.062093074541342885
epochs 3/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.002963432735812507, val_loss: 0.057428767179187976
epochs 4/87
Current Learning Rate: 0.00038689592088847756
train_loss: 0.0028894332482626564, val_loss: 0.0543951887049173
epochs 5/87

[I 2024-01-26 13:22:58,807] Trial 21 pruned.

Starting fold 1:
epochs 1/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.007441709547205583, val_loss: 0.004420604758993967
epochs 2/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0028906337224486236, val_loss: 0.00134045141749084
epochs 3/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0017548340654588844, val_loss: 0.001029372201484971
epochs 4/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0018921876234296513, val_loss: 0.0011721591535637057
epochs 5/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.002320788037889686, val_loss: 0.0009788642331075511
epochs 6/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0015161696110705012, val_loss: 0.0009122345823255417
epochs 7/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0013499182103642899, val_loss: 0.001204517139213797
epochs 8/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0011904282299311536, val_loss: 0.0016581574347678963
epochs 9/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0011516625098393935, val_loss: 0.00202278153339744
epochs 10/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.001464379710868295, val_loss: 0.002014518180849815
epochs 11/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0012858485600813047, val_loss: 0.0017184016553648306
epochs 12/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0009718756022936615, val_loss: 0.0013222596998706362
epochs 13/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0009556137236742009, val_loss: 0.0009741569837818755
epochs 14/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0009546038927510381, val_loss: 0.0007908210437132144
epochs 15/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0006246561977987815, val_loss: 0.0007101144974034181
epochs 16/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0008205466009186287, val_loss: 0.0006901268467405124
epochs 17/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0007577082433272153, val_loss: 0.0007153680206484799
epochs 18/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0006127613734478425, val_loss: 0.0008040930904251965
epochs 19/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0006332889759888578, val_loss: 0.0009205515575319479
epochs 20/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0006218192582692657, val_loss: 0.0010123686105974852
epochs 21/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0005984259263832906, val_loss: 0.0010063608129521047
epochs 22/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0005568035810842718, val_loss: 0.0009327389416284859
epochs 23/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0005008421867387369, val_loss: 0.0008234058293869326
epochs 24/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.00047094357892331714, val_loss: 0.0006945077632400697
epochs 25/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0005626534264975865, val_loss: 0.0006139646383847943
epochs 26/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.000622678031887565, val_loss: 0.0005936590697322236
epochs 27/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.00047113746098291715, val_loss: 0.0006062248675765371
epochs 28/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0004413189132097422, val_loss: 0.0006675042390461864
epochs 29/93

[I 2024-01-26 13:23:02,386] Trial 22 pruned.

Current Learning Rate: 0.0008445389913867653
train_loss: 0.0004566215923803515, val_loss: 0.0007782892667149243
epochs 30/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.0004644358337636253, val_loss: 0.0008723627516270714
epochs 31/93
Current Learning Rate: 0.0008445389913867653
train_loss: 0.00048321567699435706, val_loss: 0.0008712262554725289
epochs 32/93
Starting fold 1:
epochs 1/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.04377838282992965, val_loss: 0.04722552085785489
epochs 2/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.03743246038885493, val_loss: 0.040241360340855625
epochs 3/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.03103181943297386, val_loss: 0.033843456708679075
epochs 4/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.026163690527410882, val_loss: 0.0279715816833471
epochs 5/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.021376074252552106, val_loss: 0.022593868195422386
epochs 6/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.017066656043262858, val_loss: 0.017717605559645515
epochs 7/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.01311752236889381, val_loss: 0.013366399202985983
epochs 8/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.009396153791366438, val_loss: 0.009586589538345212
epochs 9/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.006427089796450577, val_loss: 0.006443340455083863
epochs 10/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.004204827799817155, val_loss: 0.0039996748024254646
epochs 11/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0025251136283929413, val_loss: 0.0023031151514978296
epochs 12/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0015287320515582044, val_loss: 0.00131960612611453
epochs 13/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.001066478912865645, val_loss: 0.0009192079877002949
epochs 14/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0008691531468158294, val_loss: 0.0008508345809164702
epochs 15/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0009212123009523279, val_loss: 0.0008675030399708225
epochs 16/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0009817146245806822, val_loss: 0.0008559974051374746
epochs 17/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0009212946433475928, val_loss: 0.000835702763747816
epochs 18/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0009289083253334914, val_loss: 0.0008624103404336462
epochs 19/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0007490759654166667, val_loss: 0.0009568388803592442
epochs 20/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0007740839428917848, val_loss: 0.0010964848119520436
epochs 21/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0008377888541680908, val_loss: 0.0012345172888384886
epochs 22/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0009202589434081394, val_loss: 0.0013311551320887367
epochs 23/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0009136984002237257, val_loss: 0.001376558175558641
epochs 24/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0008987398971313316, val_loss: 0.0013665845293680352
epochs 25/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0008353960884146784, val_loss: 0.0013104078556735706
epochs 26/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0008757543175689582, val_loss: 0.0012303951130505945
epochs 27/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0008096740859879279, val_loss: 0.001142425147975844
epochs 28/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0007612602866414052, val_loss: 0.0010608652810333297
epochs 29/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0007294798637495229, val_loss: 0.0009969233167602828
epochs 30/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0007094735723895658, val_loss: 0.000947772509320394
epochs 31/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005695823045435215, val_loss: 0.0009133539717080758
epochs 32/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0006007400794739001, val_loss: 0.0008954258755119027
epochs 33/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0006065261398601394, val_loss: 0.0008929902836251513
epochs 34/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0006479320712203748, val_loss: 0.0008991153034577636
epochs 35/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.000554266301332973, val_loss: 0.0009063665666249825
epochs 36/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.000580975770380495, val_loss: 0.0009122384303114622
epochs 37/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.000616859310723253, val_loss: 0.000914892985479367
epochs 38/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005352984875667301, val_loss: 0.0009110789494834056
epochs 39/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005563340738023582, val_loss: 0.0009071007867245689
epochs 40/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005532648291830954, val_loss: 0.0008990525359925079
epochs 41/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005698253945937674, val_loss: 0.0008844873952176912
epochs 42/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0006046078059099321, val_loss: 0.0008531527045354443
epochs 43/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005237866554556317, val_loss: 0.0008242386555617773
epochs 44/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00046316621975213483, val_loss: 0.0008064014120272507
epochs 45/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00044552288906599737, val_loss: 0.0007939529770642126
epochs 46/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00047802951448829847, val_loss: 0.0007840853250328158
epochs 47/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0004266897791622844, val_loss: 0.0007716830887243544
epochs 48/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0004330614118340523, val_loss: 0.0007586061514877273
epochs 49/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0003778951933399137, val_loss: 0.0007498564644361307
epochs 50/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00041645919432324407, val_loss: 0.0007410542832650734
epochs 51/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00038711731865891797, val_loss: 0.0007338042812127816
epochs 52/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00036816496484741375, val_loss: 0.0007310192877316455
epochs 53/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0003474367455438417, val_loss: 0.000726898357817462
epochs 54/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00037823085984104853, val_loss: 0.0007195602987562061
epochs 55/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00036504312822791305, val_loss: 0.0007104940908519846
epochs 56/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00033155712973032345, val_loss: 0.000702252897501335
epochs 57/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00038050928223559537, val_loss: 0.0006980999538331832
epochs 58/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00033571714248912605, val_loss: 0.0006900110323361955
epochs 59/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0003074884014112238, val_loss: 0.0006771258251606732
epochs 60/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0003484777669655159, val_loss: 0.0006675239895948356
epochs 61/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0003111670996938636, val_loss: 0.0006532958710235298
epochs 62/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0002956072061543206, val_loss: 0.000643794830294179
epochs 63/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.000355141550780421, val_loss: 0.0006393126962632921
epochs 64/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00033101470494569326, val_loss: 0.0006383507981234671
epochs 65/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00027353781502154707, val_loss: 0.0006433573889999503
epochs 66/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00033406632995281957, val_loss: 0.0006462104810021916
epochs 67/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00030068610993973715, val_loss: 0.0006315823184865478
epochs 68/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0002711010711592328, val_loss: 0.0006121444623108561
epochs 69/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0002604303004581628, val_loss: 0.0006018343972850984
epochs 70/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0002596101559710836, val_loss: 0.0006036759542583145
Starting fold 2:
epochs 1/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005843843940774126, val_loss: 0.019989357173050705
epochs 2/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005002911368041838, val_loss: 0.016197427269071342
epochs 3/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005711923333460857, val_loss: 0.01797582809078066
epochs 4/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0005110513256544149, val_loss: 0.01969560657039677
epochs 5/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0004878294559220146, val_loss: 0.018898851745516847
epochs 6/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00044203860222631576, val_loss: 0.01694723827225205
epochs 7/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0004926443730303283, val_loss: 0.016495546845621184
epochs 8/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00045617598799780305, val_loss: 0.01684981961734593
epochs 9/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0004322943250467927, val_loss: 0.01648119128995428
epochs 10/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00044814906907145326, val_loss: 0.015867825129412507
epochs 11/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0004228952069656531, val_loss: 0.015187275091088132
epochs 12/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00047849856177651273, val_loss: 0.015197218084511788
epochs 13/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00043462296261599187, val_loss: 0.015009206182960618
epochs 14/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00044339347307533513, val_loss: 0.014626001312985625
epochs 15/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00043186284911873944, val_loss: 0.01421157393457466
epochs 16/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00040797061757123293, val_loss: 0.013790815203499637
epochs 17/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.0003996753063754448, val_loss: 0.01355637944009351
epochs 18/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00039267773601367435, val_loss: 0.01316163751639818
epochs 19/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.000411892300747384, val_loss: 0.012964537587801092
epochs 20/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00040049208282174443, val_loss: 0.012411345927485901
epochs 21/70
Current Learning Rate: 0.0001574220992910159
train_loss: 0.00037888300170092596, val_loss: 0.011847884405257279
epochs 22/70

[I 2024-01-26 13:23:08,900] Trial 23 pruned.

Starting fold 1:
epochs 1/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.022345930230068534, val_loss: 0.02908543849265889
epochs 2/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.02205701238034587, val_loss: 0.028663104409842113
epochs 3/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.022096756296722513, val_loss: 0.028243936568890748
epochs 4/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.021344464409508202, val_loss: 0.0278288884186431
epochs 5/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.021145270402102095, val_loss: 0.02741751546334279
epochs 6/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.020384202750497744, val_loss: 0.027009769980060428
epochs 7/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.020865891315042972, val_loss: 0.026605159887357763
epochs 8/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.02015160941763928, val_loss: 0.0262040326371789
epochs 9/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.01945305945057618, val_loss: 0.025807089309551213
epochs 10/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.019536862492953475, val_loss: 0.02541402074459352
epochs 11/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.0197397930645629, val_loss: 0.02502423767000437
epochs 12/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.019046661306760814, val_loss: 0.02463837156170293
epochs 13/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.018542388287421906, val_loss: 0.024256526306271554
epochs 14/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.01861471440643072, val_loss: 0.023878560244644943
epochs 15/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.01771104589692856, val_loss: 0.023504975408707794
epochs 16/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.017427548236752813, val_loss: 0.02313574199613772
epochs 17/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.017119860453040977, val_loss: 0.022771023664819565
epochs 18/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.016986372655159548, val_loss: 0.02240996940159484
epochs 19/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.01710423121326848, val_loss: 0.022052030088870148
epochs 20/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.01635471739267048, val_loss: 0.021698160297972592
epochs 21/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.01690085186181884, val_loss: 0.021347494844935443
epochs 22/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.01606133772354377, val_loss: 0.021000308180718047
epochs 23/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.015311855675750658, val_loss: 0.020657452029225074
epochs 24/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.015246193449159987, val_loss: 0.020319183607046543
epochs 25/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.015110921266635782, val_loss: 0.01998551607033924
epochs 26/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.015075061984948422, val_loss: 0.01965567515182652
epochs 27/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.014576822200692013, val_loss: 0.019329446760055265
epochs 28/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.0143189759532872, val_loss: 0.019006904601854713
epochs 29/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.014475410637494765, val_loss: 0.018687747864934958
epochs 30/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.014284748422276032, val_loss: 0.018372392757354597
epochs 31/121
Current Learning Rate: 2.864738368399816e-05
train_loss: 0.014077340522290845, val_loss: 0.01806025597217836
epochs 32/121

[I 2024-01-26 13:23:12,497] Trial 24 pruned.

Starting fold 1:
epochs 1/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.008176811541871805, val_loss: 0.003832101239822805
epochs 2/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.002662057890311668, val_loss: 0.0010041330916512954
epochs 3/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0017605292944752268, val_loss: 0.001488136005048689
epochs 4/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.002333949764234651, val_loss: 0.001335858275476647
epochs 5/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0017622391460463405, val_loss: 0.0009243728357097624
epochs 6/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0010680267725164366, val_loss: 0.0011319753240585622
epochs 7/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0008502173387617068, val_loss: 0.0017380424488740239
epochs 8/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.001138847796123867, val_loss: 0.002173819252914798
epochs 9/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0013815901720112091, val_loss: 0.0021427799748428363
epochs 10/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0013019486796110868, val_loss: 0.00173034641269815
epochs 11/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0010234135322542371, val_loss: 0.0012260437602220151
epochs 12/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0007621140638979053, val_loss: 0.0008761570528517232
epochs 13/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0006832322902291229, val_loss: 0.0007488383945249217
epochs 14/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0007300185128482745, val_loss: 0.0007293260714504868
epochs 15/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0006538477096718884, val_loss: 0.0007011562334618679
epochs 16/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0005813589553949178, val_loss: 0.0006988434271127181
epochs 17/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0004365793536539729, val_loss: 0.0007825146255383611
epochs 18/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0004055861959626016, val_loss: 0.0008846476534687865
epochs 19/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0004507349857656089, val_loss: 0.0008853689551439235
epochs 20/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00038246671810108975, val_loss: 0.0007548418185538857
epochs 21/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0003436552314700461, val_loss: 0.0006064430835019601
epochs 22/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0002692868223867232, val_loss: 0.0005377458154199351
epochs 23/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00033783896115461464, val_loss: 0.0005212695503264273
epochs 24/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00031909458323896517, val_loss: 0.0005033326604844708
epochs 25/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0003344978352910594, val_loss: 0.0005301995605757264
epochs 26/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00023349381119355952, val_loss: 0.0005786017465748285
epochs 27/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00026038971440070063, val_loss: 0.0005739252102150777
epochs 28/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00019978828066469809, val_loss: 0.0005025366155773794
epochs 29/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00022398542894638682, val_loss: 0.00045127333693304345
epochs 30/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.000246470632861785, val_loss: 0.0004388999046855851
epochs 31/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00022456925331712946, val_loss: 0.0004445462438621019
epochs 32/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0002165811203763281, val_loss: 0.0004822654909252091
epochs 33/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00020746304155756277, val_loss: 0.0005316977713894295
epochs 34/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00016072692999028062, val_loss: 0.000521658727513185
epochs 35/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001828267509393443, val_loss: 0.00047368201347509106
epochs 36/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00017069616411677808, val_loss: 0.00043927298515642946
epochs 37/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00018008848067103443, val_loss: 0.00043260918908727994
epochs 38/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00015792555036329615, val_loss: 0.0004615031648427248
epochs 39/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00015411602400586401, val_loss: 0.0004899905305999136
epochs 40/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00013126580999692363, val_loss: 0.0004980591455885013
epochs 41/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012809699738251142, val_loss: 0.0004622668099105603
epochs 42/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00015129469753255283, val_loss: 0.0004440781435972129
epochs 43/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012560728091078714, val_loss: 0.0004286836081423405
epochs 44/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00014650809010306962, val_loss: 0.00043158451904003555
epochs 45/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001344242654771446, val_loss: 0.0004494424207031874
epochs 46/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012145273591924801, val_loss: 0.0004819072794481671
epochs 47/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00015109061687804855, val_loss: 0.00045977140651207025
epochs 48/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012998063635007528, val_loss: 0.00042005356456349164
epochs 49/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00013504721458670437, val_loss: 0.00039128645814918474
epochs 50/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.000132752984523234, val_loss: 0.0004094890893228646
epochs 51/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012200459566788355, val_loss: 0.00047449011043155273
epochs 52/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001312967353059273, val_loss: 0.0004902333488357009
epochs 53/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011324575385323872, val_loss: 0.0004499105573478645
epochs 54/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012024872615400359, val_loss: 0.00040822868092953667
epochs 55/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00014516249020265319, val_loss: 0.00038554311743753617
epochs 56/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00013691209441228574, val_loss: 0.0004052074808370028
epochs 57/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012317033025809857, val_loss: 0.0004453305775409956
epochs 58/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001262049560242112, val_loss: 0.0004513061315887363
epochs 59/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011892227121279575, val_loss: 0.0004162936173471328
epochs 60/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001470314510745658, val_loss: 0.0003766892696148716
epochs 61/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001408156477784934, val_loss: 0.0003749394190411917
epochs 62/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011947693909812522, val_loss: 0.00041976746127291237
epochs 63/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012106204207827289, val_loss: 0.0004815099891857244
epochs 64/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012135839949080132, val_loss: 0.0004456039084624009
epochs 65/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012450122046988996, val_loss: 0.0003729459797461076
epochs 66/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00014817280661143166, val_loss: 0.0003621169039673221
epochs 67/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012740173463642255, val_loss: 0.00041754062878776734
epochs 68/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001454305161850674, val_loss: 0.0004858170118256423
epochs 69/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.000123353716365895, val_loss: 0.0004352491531263743
epochs 70/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010932131102124818, val_loss: 0.0003764673165278509
epochs 71/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011884336900517443, val_loss: 0.0003842652685738071
epochs 72/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.000142386478010418, val_loss: 0.00042904402500042985
epochs 73/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001270956961793433, val_loss: 0.00043014514583199724
epochs 74/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011043084477454326, val_loss: 0.0004037850004878189
epochs 75/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012773177915828695, val_loss: 0.0003892333157924249
epochs 76/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011006893213274644, val_loss: 0.0004018873013065834
epochs 77/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001268283062688026, val_loss: 0.0004050323707480474
epochs 78/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011112066031752252, val_loss: 0.0003968434757553041
epochs 79/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010040404288845725, val_loss: 0.0004088619393051455
epochs 80/104
Current Learning Rate: 0.000851398577386171
train_loss: 9.930264633639079e-05, val_loss: 0.00042653777200030163
epochs 81/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011002202116191926, val_loss: 0.00040196462941821665
epochs 82/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011014139626671462, val_loss: 0.00038635707843288973
epochs 83/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011398433477887393, val_loss: 0.00041871639634911463
epochs 84/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011456717172557929, val_loss: 0.0004241401310489317
epochs 85/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010652942919956618, val_loss: 0.00040459682081985334
epochs 86/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012029646007393144, val_loss: 0.0003883777884000569
epochs 87/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00013134068094108157, val_loss: 0.0003918986093546999
epochs 88/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010361836834099929, val_loss: 0.0004067792822177963
epochs 89/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012363384341465702, val_loss: 0.00038606153516172384
epochs 90/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010933318040578773, val_loss: 0.0003678795018411045
epochs 91/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011764987797696928, val_loss: 0.00037669468024672056
epochs 92/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012111463174254535, val_loss: 0.0003845927487035576
epochs 93/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012001196859943632, val_loss: 0.00038476164359292994
epochs 94/104
Current Learning Rate: 0.000851398577386171
train_loss: 8.925951164871406e-05, val_loss: 0.000365099572503057
epochs 95/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010230872086188021, val_loss: 0.00035914770973919844
epochs 96/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012756110587169563, val_loss: 0.000373995098159771
epochs 97/104
Current Learning Rate: 0.000851398577386171
train_loss: 9.817317722512311e-05, val_loss: 0.00041893056339559784
epochs 98/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012205752806805417, val_loss: 0.00039901051710139175
epochs 99/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010278953509680975, val_loss: 0.00035590782040105154
epochs 100/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011222449163477377, val_loss: 0.00035146088722333506
epochs 101/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011471624307695923, val_loss: 0.0003941913681429517
epochs 102/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010684897106808708, val_loss: 0.00039308872778507834
epochs 103/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011389126474999725, val_loss: 0.00037521725378036007
epochs 104/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001088069057962122, val_loss: 0.00037619300335216775
Starting fold 2:
epochs 1/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0003764732500712853, val_loss: 0.0039125715419159905
epochs 2/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0016822604390510701, val_loss: 0.013601292549681506
epochs 3/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0005129846422756888, val_loss: 0.016645442265527027
epochs 4/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0002490901202499548, val_loss: 0.008992033593944813
epochs 5/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0005346310909341188, val_loss: 0.006746443714578881
epochs 6/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0004948109467238139, val_loss: 0.00955697469486806
epochs 7/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00024389232069217158, val_loss: 0.008865300032898392
epochs 8/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00017448114991374926, val_loss: 0.005110360816807339
epochs 9/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00031439669194361687, val_loss: 0.004417736285464152
epochs 10/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0002788137096917796, val_loss: 0.005367787236249761
epochs 11/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00019869051577284393, val_loss: 0.003960929538343886
epochs 12/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0002275879098880595, val_loss: 0.003485193822263299
epochs 13/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00022470405651562797, val_loss: 0.004097906716388503
epochs 14/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00019337831231256897, val_loss: 0.003635935917325122
epochs 15/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00018931108982207277, val_loss: 0.003515194470405971
epochs 16/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00018506047758580136, val_loss: 0.003616980316828152
epochs 17/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00018202733745535, val_loss: 0.003196624107658863
epochs 18/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00018235117118150046, val_loss: 0.0029124763922912904
epochs 19/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00016578683244006243, val_loss: 0.0028522355102100654
epochs 20/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00015355509850977747, val_loss: 0.0026129536992429117
epochs 21/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00015915764417609592, val_loss: 0.0022993153420669075
epochs 22/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001845607024925381, val_loss: 0.0023532593775981744
epochs 23/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00013956927595197493, val_loss: 0.002245961614933453
epochs 24/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001632675579649482, val_loss: 0.0020637061587828946
epochs 25/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001477618886718502, val_loss: 0.0021755664492957294
epochs 26/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00015284187649836225, val_loss: 0.0018884247432364837
epochs 27/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001343321710967422, val_loss: 0.0018303858539040544
epochs 28/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001359943158412965, val_loss: 0.0018000751090432076
epochs 29/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001343239877506245, val_loss: 0.0017415899477016769
epochs 30/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001391434140570805, val_loss: 0.0017424321957055088
epochs 31/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001326847615066646, val_loss: 0.001678627644555251
epochs 32/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012613846679175223, val_loss: 0.0016299300906738561
epochs 33/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00013080992079937315, val_loss: 0.0014840050379892713
epochs 34/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011819033361940743, val_loss: 0.0015237715438400443
epochs 35/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011366158153242922, val_loss: 0.0014168126723042836
epochs 36/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00011223573164897971, val_loss: 0.0014332529344277358
epochs 37/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010792877028028383, val_loss: 0.0013689874153657768
epochs 38/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001059767812541012, val_loss: 0.001362261730001161
epochs 39/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.000103403364750863, val_loss: 0.0013111215314558266
epochs 40/104
Current Learning Rate: 0.000851398577386171
train_loss: 9.840269960573336e-05, val_loss: 0.0013592732904822026
epochs 41/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010278746240625256, val_loss: 0.0014046001857710316
epochs 42/104
Current Learning Rate: 0.000851398577386171
train_loss: 9.494316145719495e-05, val_loss: 0.0013688049052449826
epochs 43/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010266574501752314, val_loss: 0.0013016624878601807
epochs 44/104
Current Learning Rate: 0.000851398577386171
train_loss: 8.525010554493699e-05, val_loss: 0.001222860539871219
epochs 45/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012227360160690486, val_loss: 0.001291602588025853
epochs 46/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00012183175472034093, val_loss: 0.0012951838404038235
epochs 47/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001533507172433402, val_loss: 0.0015514864629183553
epochs 48/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010206170803652832, val_loss: 0.0014063435435099038
epochs 49/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.000115994658029338, val_loss: 0.0015828472847045447
epochs 50/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00010555638255027588, val_loss: 0.0014147677253564133
epochs 51/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00013943823432782665, val_loss: 0.0015936115585071476
epochs 52/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001135928861530326, val_loss: 0.001426243806858302
epochs 53/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00016828703634306103, val_loss: 0.0017012412289133
epochs 54/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.00013469530830135276, val_loss: 0.001594524580899528
epochs 55/104
Current Learning Rate: 0.000851398577386171
train_loss: 0.0001740728642433073, val_loss: 0.001657992881710494
epochs 56/104

[I 2024-01-26 13:23:37,672] Trial 25 pruned.

Starting fold 1:
epochs 1/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.018698691201739406, val_loss: 0.013138909574205939
epochs 2/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.010412309029580732, val_loss: 0.001049560481241267
epochs 3/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0010024416113370343, val_loss: 0.004013625708849807
epochs 4/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.002842779479626762, val_loss: 0.005081110212363695
epochs 5/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0022496474171547513, val_loss: 0.0022582040805565686
epochs 6/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.000645088619019493, val_loss: 0.0007235032714609253
epochs 7/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.000555809105648414, val_loss: 0.000872946300507082
epochs 8/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0009673066596549593, val_loss: 0.0008010081119688326
epochs 9/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0007040206630910305, val_loss: 0.000680813193321228
epochs 10/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.00035632324717497745, val_loss: 0.0010704290660980501
epochs 11/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.00042354950212603927, val_loss: 0.0014084880411820977
epochs 12/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0004915522178635002, val_loss: 0.0012461576316701738
epochs 13/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0003590705629903823, val_loss: 0.0008510258857552942
epochs 14/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0002534594236701531, val_loss: 0.0006262560865204585
epochs 15/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.00026695788531613194, val_loss: 0.0005804516840726137
epochs 16/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.00028361726389879264, val_loss: 0.0006084098186539976
epochs 17/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0002287081116504085, val_loss: 0.0007362157437264135
epochs 18/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.00021709006036153846, val_loss: 0.0008468089625239372
epochs 19/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.00020781571748605194, val_loss: 0.0008065215091368086
epochs 20/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.00018323410477023573, val_loss: 0.0006695764923566266
epochs 21/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0001514752701807179, val_loss: 0.0005875979881047418
epochs 22/90
Epoch 00022: reducing learning rate of group 0 to 2.6608e-03.
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00015295166874574007, val_loss: 0.0005837217169372659
epochs 23/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00015270565467960151, val_loss: 0.0006150596015351384
epochs 24/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00013942820292676947, val_loss: 0.0006591721768736055
epochs 25/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.0001435720981374432, val_loss: 0.0006805193990370945
epochs 26/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00013218926821872103, val_loss: 0.0006549849101391277
epochs 27/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00013546099707079855, val_loss: 0.0006163042614628609
epochs 28/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00013375342815906104, val_loss: 0.0005817322011448835
epochs 29/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00013455905228559125, val_loss: 0.0005741044486823834
epochs 30/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00012829044740340722, val_loss: 0.0005843175575137138
epochs 31/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00011780727501517455, val_loss: 0.0006104768560218968
epochs 32/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00011360579151905289, val_loss: 0.0006259221056672303
epochs 33/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.0001247393626008967, val_loss: 0.0006130561036498923
epochs 34/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.0001350080519363186, val_loss: 0.0005828373281187133
epochs 35/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.663585614792904e-05, val_loss: 0.0005645407376026637
epochs 36/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010499710946245806, val_loss: 0.0005702597726332514
epochs 37/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010620587479359911, val_loss: 0.0005948326121525544
epochs 38/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010859539730805218, val_loss: 0.0006015374398741283
epochs 39/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00011477334651556846, val_loss: 0.0005872004677688605
epochs 40/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00012036720053354082, val_loss: 0.000563325185181671
epochs 41/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010675559912526392, val_loss: 0.0005529455718045171
epochs 42/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010762740995759438, val_loss: 0.0005582460864005904
epochs 43/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.0001075381065387965, val_loss: 0.0005620728651257722
epochs 44/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.75925667597422e-05, val_loss: 0.0005571231858706788
epochs 45/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.540275495965034e-05, val_loss: 0.0005542175084548561
epochs 46/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.340901926502977e-05, val_loss: 0.0005604451093332548
epochs 47/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.892702196099747e-05, val_loss: 0.0005596799310296774
epochs 48/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010488930538964556, val_loss: 0.0005435597041229668
epochs 49/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010451846564568482, val_loss: 0.0005327806268867693
epochs 50/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.58012793010934e-05, val_loss: 0.0005423861641534849
epochs 51/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.598603945433799e-05, val_loss: 0.0005541848974596513
epochs 52/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010444299236711997, val_loss: 0.0005501995537135946
epochs 53/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.572442366717089e-05, val_loss: 0.000540239490127485
epochs 54/90
Current Learning Rate: 0.0026608319570838716
train_loss: 8.90158319012507e-05, val_loss: 0.0005466235740306346
epochs 55/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010982047051105551, val_loss: 0.0005328141581757289
epochs 56/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.349462228496314e-05, val_loss: 0.0005139093429438377
epochs 57/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00010582556715235114, val_loss: 0.0005067514010558003
epochs 58/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.637196666230202e-05, val_loss: 0.0005200459560575454
epochs 59/90
Current Learning Rate: 0.0026608319570838716
train_loss: 8.717814252074612e-05, val_loss: 0.0005423512456840591
epochs 60/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.798002054020272e-05, val_loss: 0.0005360096607259229
epochs 61/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.0001092053167093055, val_loss: 0.0004979682681885989
epochs 62/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.0001065361511121553, val_loss: 0.00047478358212270236
epochs 63/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.881401684220979e-05, val_loss: 0.0005039167811015719
epochs 64/90
Current Learning Rate: 0.0026608319570838716
train_loss: 8.697356304190563e-05, val_loss: 0.0005552292078439342
epochs 65/90
Current Learning Rate: 0.0026608319570838716
train_loss: 8.913499508420692e-05, val_loss: 0.0005494378739967943
epochs 66/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.419214375635707e-05, val_loss: 0.0005010547716856787
epochs 67/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.821434574213957e-05, val_loss: 0.0004714946752708209
epochs 68/90
Current Learning Rate: 0.0026608319570838716
train_loss: 9.595156589057297e-05, val_loss: 0.0004988734647141475
epochs 69/90
Current Learning Rate: 0.0026608319570838716
train_loss: 0.00011849071398548978, val_loss: 0.0005235138349235057
epochs 70/90
Current Learning Rate: 0.0026608319570838716
train_loss: 8.768649560423862e-05, val_loss: 0.0005291474394892392
epochs 71/90
Current Learning Rate: 0.0026608319570838716
train_loss: 8.719460931484048e-05, val_loss: 0.0005143358543711273
epochs 72/90
Current Learning Rate: 0.0026608319570838716
train_loss: 8.622989093725521e-05, val_loss: 0.0004995169289606183
epochs 73/90
Current Learning Rate: 0.0026608319570838716
train_loss: 8.54561017676085e-05, val_loss: 0.0005024933893429606
epochs 74/90
Epoch 00074: reducing learning rate of group 0 to 1.6257e-03.
Current Learning Rate: 0.0016257467683919136
train_loss: 8.72406879544111e-05, val_loss: 0.0005233318569432748
epochs 75/90
Current Learning Rate: 0.0016257467683919136
train_loss: 8.786096027745914e-05, val_loss: 0.0005303648202434967
epochs 76/90
Current Learning Rate: 0.0016257467683919136
train_loss: 8.050231400901746e-05, val_loss: 0.0005158842271684032
epochs 77/90
Current Learning Rate: 0.0016257467683919136
train_loss: 8.039290237081189e-05, val_loss: 0.0005052989557091343
epochs 78/90
Current Learning Rate: 0.0016257467683919136
train_loss: 9.111391983950805e-05, val_loss: 0.0004910562530552086
epochs 79/90
Current Learning Rate: 0.0016257467683919136
train_loss: 8.606141108382298e-05, val_loss: 0.0004985929687360399
epochs 80/90
Current Learning Rate: 0.0016257467683919136
train_loss: 8.40646329666733e-05, val_loss: 0.0005169429215847661
epochs 81/90
Epoch 00081: reducing learning rate of group 0 to 9.9332e-04.
Current Learning Rate: 0.000993318104099063
train_loss: 8.983548483995133e-05, val_loss: 0.000523822440912849
epochs 82/90
Current Learning Rate: 0.000993318104099063
train_loss: 7.536955052177961e-05, val_loss: 0.000525313629278619
epochs 83/90
Current Learning Rate: 0.000993318104099063
train_loss: 8.654173633610634e-05, val_loss: 0.0005193737899198344
epochs 84/90
Current Learning Rate: 0.000993318104099063
train_loss: 9.168602233617812e-05, val_loss: 0.0005103108546647586
epochs 85/90
Current Learning Rate: 0.000993318104099063
train_loss: 7.740135111625453e-05, val_loss: 0.0005114121595397592
epochs 86/90
Current Learning Rate: 0.000993318104099063
train_loss: 8.896029321476817e-05, val_loss: 0.0005138628589185445
epochs 87/90
Current Learning Rate: 0.000993318104099063
train_loss: 8.219420445752085e-05, val_loss: 0.0005162252493104652
epochs 88/90
Epoch 00088: reducing learning rate of group 0 to 6.0691e-04.
Current Learning Rate: 0.0006069093139929285
train_loss: 8.884299390238563e-05, val_loss: 0.0005143070581222051
epochs 89/90

[I 2024-01-26 13:23:42,505] Trial 26 pruned.

Current Learning Rate: 0.0006069093139929285
train_loss: 9.99047803864079e-05, val_loss: 0.0005097917207565746
epochs 90/90
Current Learning Rate: 0.0006069093139929285
train_loss: 8.77536492465113e-05, val_loss: 0.0005033002308520831
Starting fold 2:
epochs 1/90
Current Learning Rate: 0.0043549381991648695
train_loss: 0.0017722804296921057, val_loss: 0.013189970172549548
epochs 2/90
Starting fold 1:
epochs 1/102
Current Learning Rate: 0.02319615712735748
train_loss: 1.1548947760933324, val_loss: 0.046791845481646686
epochs 2/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.03218646941118335, val_loss: 0.02498387808078214
epochs 3/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.20742661200071635, val_loss: 0.016242138982603425
epochs 4/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.031657260460288904, val_loss: 0.07792517625187573
epochs 5/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.08891164911420722, val_loss: 0.021739329456498747
epochs 6/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.018482892357401158, val_loss: 0.016725873633434897
epochs 7/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.017631506645365766, val_loss: 0.03917286603858596
epochs 8/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.031406165394735966, val_loss: 0.006540425376672493
epochs 9/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.007550875014184337, val_loss: 0.003576420231011549
epochs 10/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.010965139595301527, val_loss: 0.005451941792853176
epochs 11/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.009396216420358733, val_loss: 0.001233863815861313
epochs 12/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.002566247965258203, val_loss: 0.007922728967509772
epochs 13/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.006515057894744371, val_loss: 0.014833059181508266
epochs 14/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.011016220952335157, val_loss: 0.008357355253476846
epochs 15/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.00654966367996837, val_loss: 0.001681534622452761
epochs 16/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.0038550703100075846, val_loss: 0.001670938863811132
epochs 17/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.004990970196300432, val_loss: 0.001443919622780461
epochs 18/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.0035409285490842243, val_loss: 0.0023229847220998063
epochs 19/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.0028815820004398887, val_loss: 0.0072483643987461144
epochs 20/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.005101111134220111, val_loss: 0.008198187294367113
epochs 21/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.006186027643515875, val_loss: 0.004103937156890568
epochs 22/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.0035333509152559073, val_loss: 0.001422399659886172
epochs 23/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.003711819560512116, val_loss: 0.0012296734353233324
epochs 24/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.003003524126190888, val_loss: 0.0016402352699323704
epochs 25/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.0016843329159248817, val_loss: 0.003866306810002578
epochs 26/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.0028220710026002245, val_loss: 0.0056890943822892085
epochs 27/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.004049623497810803, val_loss: 0.004320356171382101
epochs 28/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.0029523891592888457, val_loss: 0.002290534732961341
epochs 29/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.0026497024797687407, val_loss: 0.0015450063602704752
epochs 30/102
Current Learning Rate: 0.02319615712735748
train_loss: 0.0023651459695477233, val_loss: 0.0017225733566048897
epochs 31/102

[I 2024-01-26 13:23:44,766] Trial 27 pruned.

Current Learning Rate: 0.02319615712735748
train_loss: 0.0018755980252631401, val_loss: 0.002682204382788194
epochs 32/102
Starting fold 1:
epochs 1/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.03868830733393368, val_loss: 0.043705690652132034
epochs 2/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.03385665953943604, val_loss: 0.0387966172083428
epochs 3/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0296270244411732, val_loss: 0.03416121162866291
epochs 4/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.02525101396206178, val_loss: 0.029784079837171656
epochs 5/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.021920972454704736, val_loss: 0.025645853265335684
epochs 6/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.01939899444972214, val_loss: 0.02174188343710021
epochs 7/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0157105221266025, val_loss: 0.0180769732319995
epochs 8/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.013009196000271723, val_loss: 0.01466376932435914
epochs 9/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.010133217284946065, val_loss: 0.011529461529694106
epochs 10/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.007701010933439983, val_loss: 0.00870686945946593
epochs 11/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.005485176035252057, val_loss: 0.006252154046179433
epochs 12/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.004092574315635781, val_loss: 0.004221346462145448
epochs 13/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0031486738130058114, val_loss: 0.002672256013427518
epochs 14/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0020560601811954065, val_loss: 0.0016561906821535605
epochs 15/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0016881451500873816, val_loss: 0.0011642998280493838
epochs 16/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0019423001151728002, val_loss: 0.0010680821295337456
epochs 17/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0021477902651225265, val_loss: 0.001146096880180075
epochs 18/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0022544623107502333, val_loss: 0.001199083362926582
epochs 19/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0026360215300596074, val_loss: 0.0011673034720220848
epochs 20/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0022799431615950247, val_loss: 0.0010941858146045554
epochs 21/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.001923188628432782, val_loss: 0.0010565686113152065
epochs 22/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.001681632025314397, val_loss: 0.0010901984672895388
epochs 23/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0016401823928677722, val_loss: 0.0011917972097810555
epochs 24/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0013311309127235099, val_loss: 0.001339064298295661
epochs 25/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0017454388649447968, val_loss: 0.0014994939004904346
epochs 26/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.001617025050922836, val_loss: 0.0016408237034307891
epochs 27/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.001478872384483877, val_loss: 0.0017488716403022408
epochs 28/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0015777056779418337, val_loss: 0.0018133832184646867
epochs 29/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0012802771954356057, val_loss: 0.001824900146426731
epochs 30/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0017328086358151939, val_loss: 0.0017847890726682778
epochs 31/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0013444235940512858, val_loss: 0.0017187634642284952
epochs 32/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0015943558077867095, val_loss: 0.0016323711300317786
epochs 33/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0014288512205607013, val_loss: 0.001544140882814597
epochs 34/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0014742267269052956, val_loss: 0.0014654182442954105
epochs 35/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0013649472292806756, val_loss: 0.0013935645876795445
epochs 36/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.001374645679453878, val_loss: 0.0013349549569140532
epochs 37/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0013478226579823776, val_loss: 0.0012853789069738827
epochs 38/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.001422673770177521, val_loss: 0.0012478521583895934
epochs 39/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0012608928434354695, val_loss: 0.0012204181096565566
epochs 40/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0013101393675529643, val_loss: 0.001207051513790104
epochs 41/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0013979230701041065, val_loss: 0.0012041937933597517
epochs 42/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0014213486268234096, val_loss: 0.001211071518666454
epochs 43/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0014250884384014889, val_loss: 0.0012223563144767755
epochs 44/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0012149247340857983, val_loss: 0.0012325455134391393
epochs 45/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0011201240551216823, val_loss: 0.0012341787468789047
epochs 46/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0012984496026643012, val_loss: 0.0012290220321646255
epochs 47/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0013346185625873897, val_loss: 0.0012285490060764317
epochs 48/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0011382326177370391, val_loss: 0.0012241842127160023
epochs 49/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0012193323345854878, val_loss: 0.001214665547625995
epochs 50/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0013550140490559371, val_loss: 0.0012008201600493568
epochs 51/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0011998338771885947, val_loss: 0.0011857193894684315
epochs 52/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0011468002033468924, val_loss: 0.001164560049992839
epochs 53/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0010197002097572152, val_loss: 0.001139025234519259
epochs 54/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0011603964223085266, val_loss: 0.0011109221162960718
epochs 55/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0011356739008701162, val_loss: 0.0011053509293369164
epochs 56/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0009723187203666097, val_loss: 0.0010979257456615176
epochs 57/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0010279276359238122, val_loss: 0.0010898627469463176
epochs 58/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007804820626532953, val_loss: 0.0010884494312401664
epochs 59/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.001114711722996282, val_loss: 0.0010834529775341874
epochs 60/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.000954839523489538, val_loss: 0.0010568377007362678
epochs 61/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0008829831096686815, val_loss: 0.0010219674012133557
epochs 62/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.000824091147239271, val_loss: 0.0009790454458102193
epochs 63/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0008056153065377945, val_loss: 0.0009351309425638695
epochs 64/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0008030393234405079, val_loss: 0.0009076137089562652
epochs 65/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0008510504879890696, val_loss: 0.0008895183502892522
epochs 66/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007716061970169999, val_loss: 0.0008928833428255626
epochs 67/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.00067312005098517, val_loss: 0.0008893494638246729
epochs 68/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006621223476127182, val_loss: 0.000880315385170673
epochs 69/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005764476679216482, val_loss: 0.0008628996009448249
epochs 70/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0008047038664747225, val_loss: 0.0008464765744161253
epochs 71/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006887090949978875, val_loss: 0.000835457577762243
epochs 72/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006240317230357936, val_loss: 0.0008519746862523453
epochs 73/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006383956367100932, val_loss: 0.0008647817686371701
epochs 74/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007331765311966209, val_loss: 0.0008393692290778027
epochs 75/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005263114550248965, val_loss: 0.0008252276793906564
epochs 76/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006787572025419458, val_loss: 0.0008137813113678835
epochs 77/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006203153354458903, val_loss: 0.000812864102619259
epochs 78/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006134764132040896, val_loss: 0.0008013198875184907
epochs 79/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006206718818774741, val_loss: 0.0007781893854323579
epochs 80/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005503908737170461, val_loss: 0.0007837776762531384
epochs 81/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005559966298996618, val_loss: 0.0008430380778583256
epochs 82/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005248353792060362, val_loss: 0.000893893985592417
epochs 83/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005847165532606212, val_loss: 0.0009018358265932061
epochs 84/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.000575747120341188, val_loss: 0.0009170625738701538
epochs 85/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006732921771656134, val_loss: 0.0009349437191543219
epochs 86/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.000494465636285512, val_loss: 0.0009367723710295793
epochs 87/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006517810244603377, val_loss: 0.0009278817420923396
epochs 88/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0004819574900657723, val_loss: 0.0008678325715376751
epochs 89/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006072384697434149, val_loss: 0.0008236488639867227
epochs 90/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0004897164977400711, val_loss: 0.0007834921278500635
epochs 91/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005462770105192536, val_loss: 0.0008432612460302679
epochs 92/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005256005112498411, val_loss: 0.000930272796387343
epochs 93/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005021238175686449, val_loss: 0.0010537593502943452
epochs 94/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005693573100296291, val_loss: 0.0011328353123788379
epochs 95/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0004572890726481809, val_loss: 0.0010671212344038252
epochs 96/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005856515735534853, val_loss: 0.0009068456496798286
epochs 97/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005006891810090134, val_loss: 0.0007610729570794655
epochs 98/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005019980599172413, val_loss: 0.0007311675795599034
epochs 99/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006313583856497548, val_loss: 0.000819593006254811
epochs 100/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0004838431640037973, val_loss: 0.0009424227050897715
epochs 101/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006038680715535424, val_loss: 0.0010032493063542795
epochs 102/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.000558731118584738, val_loss: 0.0009812604893293035
epochs 103/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005017772231152968, val_loss: 0.0009085808660050756
epochs 104/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006116803851909935, val_loss: 0.0008504826661297365
epochs 105/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.00047942873023107255, val_loss: 0.0008172966159978195
epochs 106/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005584285092098932, val_loss: 0.0008112361078689757
epochs 107/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005242807674221694, val_loss: 0.0008029583964104715
epochs 108/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0004795406451816426, val_loss: 0.00081949152579335
epochs 109/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006084154899183073, val_loss: 0.0008120102238057083
epochs 110/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005231786788882394, val_loss: 0.0009024651984586136
epochs 111/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0004943447573551614, val_loss: 0.0009894751128740609
epochs 112/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005350654552641668, val_loss: 0.0010116810077115109
epochs 113/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005280243640299886, val_loss: 0.0009696124593335155
epochs 114/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0004362092310513713, val_loss: 0.0009555867260420008
Starting fold 2:
epochs 1/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0008167019604068054, val_loss: 0.012219696893895926
epochs 2/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.001005332632063839, val_loss: 0.012197349588141629
epochs 3/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0009696948783178078, val_loss: 0.01571555009209796
epochs 4/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0008916149626633054, val_loss: 0.016042784983782393
epochs 5/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007576610537638006, val_loss: 0.014889062553840248
epochs 6/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007735617109574378, val_loss: 0.014005503886820455
epochs 7/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0008130300250884734, val_loss: 0.014369454725008262
epochs 8/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006896180719578345, val_loss: 0.015261465928664333
epochs 9/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007852166477517274, val_loss: 0.015232085838521781
epochs 10/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007235869109679602, val_loss: 0.013984416390916235
epochs 11/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007214791993120391, val_loss: 0.013173006131852927
epochs 12/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0008382622648863808, val_loss: 0.014045378291293195
epochs 13/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006736653342254852, val_loss: 0.014921642374247313
epochs 14/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006994487040700685, val_loss: 0.014585723830877166
epochs 15/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007169351692458516, val_loss: 0.014031502075101199
epochs 16/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006454392921449127, val_loss: 0.01368362231082038
epochs 17/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007033416600040111, val_loss: 0.013644784247796787
epochs 18/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007548445443573751, val_loss: 0.013469859810644075
epochs 19/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006960860551580003, val_loss: 0.01358918250097256
epochs 20/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.000630891004172889, val_loss: 0.013643449834106784
epochs 21/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006315395523990063, val_loss: 0.013702836279806337
epochs 22/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006976469533248363, val_loss: 0.013941541608226927
epochs 23/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005887217488826105, val_loss: 0.013615113462468511
epochs 24/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006468373696981488, val_loss: 0.013709764069828548
epochs 25/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006194919467241945, val_loss: 0.013496742730862215
epochs 26/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006793756068586127, val_loss: 0.013260544547320981
epochs 27/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0007043432300346659, val_loss: 0.013495599091249076
epochs 28/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006988070090301335, val_loss: 0.013941082417180664
epochs 29/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006721077967851766, val_loss: 0.013352011796087027
epochs 30/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006588085303328148, val_loss: 0.0130486567504704
epochs 31/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006679923742347839, val_loss: 0.013229069765657187
epochs 32/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.000539196100649669, val_loss: 0.013280787652260378
epochs 33/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006948796186694189, val_loss: 0.013566507051061643
epochs 34/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.000609599366342943, val_loss: 0.01330841114548476
epochs 35/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005522081750984254, val_loss: 0.013087333032959387
epochs 36/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005901935295888075, val_loss: 0.012788491127522368
epochs 37/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005206717867526765, val_loss: 0.013113119369862895
epochs 38/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0004945968378849916, val_loss: 0.013182842932445439
epochs 39/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006087720133731828, val_loss: 0.012825288099089735
epochs 40/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0005987971135733748, val_loss: 0.012426361368086777
epochs 41/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.00062320455541148, val_loss: 0.012607676001559747
epochs 42/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006244965786065318, val_loss: 0.013082246957836966
epochs 43/114
Current Learning Rate: 0.00018977787478707624
train_loss: 0.0006032652148094616, val_loss: 0.012718871284864451
epochs 44/114

[I 2024-01-26 13:24:11,769] Trial 28 pruned.

Starting fold 1:
epochs 1/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00472545565571636, val_loss: 0.0016096304752863944
epochs 2/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0022390790400095284, val_loss: 0.005173849523998797
epochs 3/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0025605204282328486, val_loss: 0.004050913208629936
epochs 4/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0012725561391562223, val_loss: 0.000983936435659416
epochs 5/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0008603968599345535, val_loss: 0.0009402571886312217
epochs 6/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0013072474102955312, val_loss: 0.0007592888723593205
epochs 7/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0008261594630312175, val_loss: 0.001330286089796573
epochs 8/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0006342639389913529, val_loss: 0.0022693687642458826
epochs 9/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0007457099854946136, val_loss: 0.0020124798465985805
epochs 10/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.000491711383801885, val_loss: 0.0011307883833069354
epochs 11/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00025961156643461436, val_loss: 0.0006602638168260455
epochs 12/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0003808074980042875, val_loss: 0.0005884456768399104
epochs 13/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0004495430621318519, val_loss: 0.000694166541507002
epochs 14/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0003090023237746209, val_loss: 0.001069220837962348
epochs 15/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00027521057199919596, val_loss: 0.0013659165415447205
epochs 16/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0002796351764118299, val_loss: 0.00126844323676778
epochs 17/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00024007334286579862, val_loss: 0.0008772440487518907
epochs 18/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001853049616329372, val_loss: 0.000634889533102978
epochs 19/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00023889353178674355, val_loss: 0.0005990255376673304
epochs 20/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0002374804753344506, val_loss: 0.0007669753540540114
epochs 21/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00017856563499663025, val_loss: 0.0009844185697147623
epochs 22/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00019734031957341358, val_loss: 0.0009911360175465234
epochs 23/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00015431627980433404, val_loss: 0.0007924099991214462
epochs 24/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00012859454727731645, val_loss: 0.0006662821979261935
epochs 25/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00013887096065445803, val_loss: 0.0006471216947829816
epochs 26/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00013553535245591775, val_loss: 0.000741540476155933
epochs 27/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00015134247951209545, val_loss: 0.0008454118215013295
epochs 28/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00013417126319836825, val_loss: 0.0008237425754487049
epochs 29/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00013622960250359029, val_loss: 0.0006685283842671197
epochs 30/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00013767145355814137, val_loss: 0.0006033034514985047
epochs 31/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00012033624807372689, val_loss: 0.0006526872421090957
epochs 32/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00013694546214537695, val_loss: 0.0007165453607740346
epochs 33/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00012099722516722977, val_loss: 0.0007247975627251435
epochs 34/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00011329067638143897, val_loss: 0.000635103464446729
epochs 35/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001269653112103697, val_loss: 0.0006189569867274258
epochs 36/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00012500814409577288, val_loss: 0.0006327289884211496
epochs 37/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00010569350706646219, val_loss: 0.000631842794973636
epochs 38/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00011221781824133359, val_loss: 0.0006277287757257
epochs 39/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.607175161363557e-05, val_loss: 0.0005906098376726732
epochs 40/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00010059539272333495, val_loss: 0.0005568541964748874
epochs 41/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001100693698390387, val_loss: 0.0006067526628612541
epochs 42/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00011564297528821044, val_loss: 0.0006359825492836535
epochs 43/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00010378543083788827, val_loss: 0.0006044018045940902
epochs 44/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00011416927009122446, val_loss: 0.0005924915785726625
epochs 45/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00010883107461268082, val_loss: 0.0005989254168525804
epochs 46/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00010586239295662381, val_loss: 0.0006239640024432447
epochs 47/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.810316623770632e-05, val_loss: 0.00062199542298913
epochs 48/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00010677547106752172, val_loss: 0.0005789015376649331
epochs 49/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00011706351506290957, val_loss: 0.0005856831739947665
epochs 50/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.768838935997337e-05, val_loss: 0.0006594415026484057
epochs 51/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.538377707940526e-05, val_loss: 0.0006548512646986637
epochs 52/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.255389886675403e-05, val_loss: 0.0006204973251442425
epochs 53/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.88650247361511e-05, val_loss: 0.0005811228038510308
epochs 54/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00010540822404436767, val_loss: 0.000570370251807617
epochs 55/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.014182796818204e-05, val_loss: 0.0006237355482880957
epochs 56/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00010221580669167452, val_loss: 0.0006215568537299987
epochs 57/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.434422852587886e-05, val_loss: 0.0005957412431598641
epochs 58/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.854215386440046e-05, val_loss: 0.0005482377091539092
epochs 59/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.518640945316292e-05, val_loss: 0.0005789672686660197
epochs 60/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.418924310011789e-05, val_loss: 0.0006456230730691459
epochs 61/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.855367195792496e-05, val_loss: 0.0006371350573317613
epochs 62/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.22965191421099e-05, val_loss: 0.000580547875870252
epochs 63/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.288212822866626e-05, val_loss: 0.0005562777478189673
epochs 64/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.887375927064568e-05, val_loss: 0.0006021109438734129
epochs 65/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.756550571182743e-05, val_loss: 0.0006035048354533501
epochs 66/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.888857701094821e-05, val_loss: 0.0005587172199739143
epochs 67/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.267566227004863e-05, val_loss: 0.0005654886008414906
epochs 68/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.878544394974597e-05, val_loss: 0.0006301551511569414
epochs 69/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.328851228929125e-05, val_loss: 0.000581219184823567
epochs 70/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.67808485054411e-05, val_loss: 0.0005741585591749754
epochs 71/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.443421367905103e-05, val_loss: 0.0006213359229150228
epochs 72/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.686089859111235e-05, val_loss: 0.0006489927145594265
epochs 73/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.561039430787787e-05, val_loss: 0.0005697184751625173
epochs 74/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.050855467445217e-05, val_loss: 0.0005100919115648139
epochs 75/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.84032306203153e-05, val_loss: 0.0005737176761613227
epochs 76/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.26526372495573e-05, val_loss: 0.0006541900293086655
epochs 77/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.902428817236796e-05, val_loss: 0.0006101078033680096
epochs 78/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.956941408338025e-05, val_loss: 0.0005257770899333991
epochs 79/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.171768033411354e-05, val_loss: 0.0005490535841090605
epochs 80/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.969438204076141e-05, val_loss: 0.0006194191009853967
epochs 81/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.191668894141912e-05, val_loss: 0.0006387740904756356
epochs 82/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.56104634294752e-05, val_loss: 0.0005512510178959928
epochs 83/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.055401824298315e-05, val_loss: 0.0005295450464473106
epochs 84/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.499822070007212e-05, val_loss: 0.0006184760095493402
epochs 85/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.729139881324954e-05, val_loss: 0.0006553423118020874
epochs 86/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.827142326277681e-05, val_loss: 0.0005296922208799515
epochs 87/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.576041025458835e-05, val_loss: 0.000525510582519928
epochs 88/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.393272921442986e-05, val_loss: 0.0006401979335350916
epochs 89/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.182459012256004e-05, val_loss: 0.000622992345597595
epochs 90/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.749544602120295e-05, val_loss: 0.0005327245708031114
epochs 91/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.531293860869482e-05, val_loss: 0.0005927170386712532
epochs 92/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.519253242411651e-05, val_loss: 0.0006091452269174624
epochs 93/120
Current Learning Rate: 0.0031759398793721545
train_loss: 9.22785111470148e-05, val_loss: 0.0005814222349727061
epochs 94/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.717712989891879e-05, val_loss: 0.0005493295830092393
epochs 95/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.46397599868942e-05, val_loss: 0.0005718806642107666
epochs 96/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.260679533123039e-05, val_loss: 0.0006172818393679336
epochs 97/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.698302033531945e-05, val_loss: 0.0005908754719712306
epochs 98/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.579230780014768e-05, val_loss: 0.0005709950128220953
epochs 99/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.759607251500711e-05, val_loss: 0.0005947141762590036
epochs 100/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.273682396975346e-05, val_loss: 0.0005864997874596156
epochs 101/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.32647931727115e-05, val_loss: 0.0005639876544591971
epochs 102/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.228577669593506e-05, val_loss: 0.0005832137358083855
epochs 103/120
Current Learning Rate: 0.0031759398793721545
train_loss: 8.733788490644656e-05, val_loss: 0.000584906003496144
epochs 104/120
Current Learning Rate: 0.0031759398793721545
train_loss: 7.218722566904034e-05, val_loss: 0.0005435418461274821
epochs 105/120
Epoch 00105: reducing learning rate of group 0 to 1.4251e-03.
Current Learning Rate: 0.0014250651259657525
train_loss: 7.855396324885078e-05, val_loss: 0.0006069703449611552
epochs 106/120
Current Learning Rate: 0.0014250651259657525
train_loss: 8.918454113882035e-05, val_loss: 0.0006130569527158514
epochs 107/120
Current Learning Rate: 0.0014250651259657525
train_loss: 7.417707456625067e-05, val_loss: 0.0005862857142346911
epochs 108/120
Current Learning Rate: 0.0014250651259657525
train_loss: 8.116005483316258e-05, val_loss: 0.0005675130523741245
epochs 109/120
Current Learning Rate: 0.0014250651259657525
train_loss: 7.840487160137855e-05, val_loss: 0.0005590504915744532
epochs 110/120
Current Learning Rate: 0.0014250651259657525
train_loss: 7.148139411583543e-05, val_loss: 0.0005739417938457336
epochs 111/120
Current Learning Rate: 0.0014250651259657525
train_loss: 8.136015821946785e-05, val_loss: 0.0006022278794262093
epochs 112/120
Current Learning Rate: 0.0014250651259657525
train_loss: 8.600497676525265e-05, val_loss: 0.0006038789870217443
epochs 113/120
Current Learning Rate: 0.0014250651259657525
train_loss: 7.537376222899184e-05, val_loss: 0.0005780711690022144
epochs 114/120
Current Learning Rate: 0.0014250651259657525
train_loss: 6.961885810596868e-05, val_loss: 0.0005402101705840323
epochs 115/120
Current Learning Rate: 0.0014250651259657525
train_loss: 7.489557538065128e-05, val_loss: 0.0005444557100418024
epochs 116/120
Current Learning Rate: 0.0014250651259657525
train_loss: 8.876187348505482e-05, val_loss: 0.0005858913937117904
epochs 117/120
Current Learning Rate: 0.0014250651259657525
train_loss: 7.774878031341359e-05, val_loss: 0.0006241430455702357
epochs 118/120
Current Learning Rate: 0.0014250651259657525
train_loss: 7.518962593167089e-05, val_loss: 0.0006154965085443109
epochs 119/120
Current Learning Rate: 0.0014250651259657525
train_loss: 7.420437032124028e-05, val_loss: 0.0005693651037290692
epochs 120/120
Current Learning Rate: 0.0014250651259657525
train_loss: 7.497155456803739e-05, val_loss: 0.0005646284407703206
Starting fold 2:
epochs 1/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0009371871237817686, val_loss: 0.00519898597849533
epochs 2/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0022046266531106085, val_loss: 0.024786040652543306
epochs 3/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0011005260312231258, val_loss: 0.03214008267968893
epochs 4/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0006290846122283256, val_loss: 0.021486622747033834
epochs 5/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0004379348574730102, val_loss: 0.014810542576014996
epochs 6/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0006259301226236857, val_loss: 0.01719783549197018
epochs 7/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0004521605806075968, val_loss: 0.020047097466886044
epochs 8/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0003440719865466235, val_loss: 0.015459808055311441
epochs 9/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0002028905728366226, val_loss: 0.009967189864255488
epochs 10/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00028883396225865, val_loss: 0.010371023905463517
epochs 11/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0002621898165671155, val_loss: 0.01088211394380778
epochs 12/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00018101114437740762, val_loss: 0.008125524851493537
epochs 13/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00020235041483829264, val_loss: 0.007896108902059495
epochs 14/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00022671817896480206, val_loss: 0.009010582114569843
epochs 15/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00016894976943149231, val_loss: 0.007875004957895726
epochs 16/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00017639390534895938, val_loss: 0.00779728009365499
epochs 17/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001947320342878811, val_loss: 0.008235941641032696
epochs 18/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00015615864867868368, val_loss: 0.007339272880926728
epochs 19/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001714589961920865, val_loss: 0.007165459159296006
epochs 20/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001667236447246978, val_loss: 0.006957000005058944
epochs 21/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00015156531117099803, val_loss: 0.0065217456431128085
epochs 22/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00015628905021003447, val_loss: 0.006491487205494195
epochs 23/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00015039197387523018, val_loss: 0.006327714363578707
epochs 24/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001441180666006403, val_loss: 0.006082878680899739
epochs 25/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001497050434409175, val_loss: 0.006189300038386136
epochs 26/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001473742177040549, val_loss: 0.00605809863191098
epochs 27/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001357512992399279, val_loss: 0.005844767089001834
epochs 28/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.0001287445156776812, val_loss: 0.00569090450881049
epochs 29/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00012991764197067823, val_loss: 0.005795670964289457
epochs 30/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00013070298155071214, val_loss: 0.005655489745549858
epochs 31/120
Current Learning Rate: 0.0031759398793721545
train_loss: 0.00014082889720157254, val_loss: 0.00541567977052182
epochs 32/120
Epoch 00032: reducing learning rate of group 0 to 1.4251e-03.
Current Learning Rate: 0.0014250651259657525
train_loss: 0.0001342965115327388, val_loss: 0.005298269301420078
epochs 33/120
Current Learning Rate: 0.0014250651259657525
train_loss: 0.00011705520046234597, val_loss: 0.005272365553537384
epochs 34/120
Current Learning Rate: 0.0014250651259657525
train_loss: 0.00011560528764675837, val_loss: 0.00537617685040459
epochs 35/120
Current Learning Rate: 0.0014250651259657525
train_loss: 0.0001127567720686784, val_loss: 0.005277012882288545
epochs 36/120
Current Learning Rate: 0.0014250651259657525
train_loss: 0.00011439938316470943, val_loss: 0.005286715779220685
epochs 37/120
Current Learning Rate: 0.0014250651259657525
train_loss: 0.00010975683653668966, val_loss: 0.005513939657248557
epochs 38/120
Current Learning Rate: 0.0014250651259657525

[I 2024-01-26 13:25:14,004] Trial 29 finished with value: 0.0025633805252194483 and parameters: {'batch_size': 95, 'epochs': 120, 'hidden_size': 77, 'learning_rate': 0.0031759398793721545, 'dropout_prob': 0.07927237133353969, 'weight_decay': 0.0001582727096128703, 'lr_step_size': 30, 'gamma': 0.44870658138763975, 'num_layers': 1}. Best is trial 18 with value: 0.0011512266347036932.

Current Learning Rate: 0.000639436100926839
train_loss: 0.00054788473789813, val_loss: 0.0007966204721014947
epochs 120/120
Current Learning Rate: 0.000639436100926839
train_loss: 0.0005327789527655114, val_loss: 0.0008205464400816709
Mean validation loss: 0.0025633805252194483
Starting fold 1:
epochs 1/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003923562324703916, val_loss: 0.0016528592671659825
epochs 2/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003622243403898258, val_loss: 0.001656849728897214
epochs 3/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003818956499698719, val_loss: 0.0016626669032695262
epochs 4/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0038498415005099222, val_loss: 0.0016704402208377264
epochs 5/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0037910514370244194, val_loss: 0.0016799402349677525
epochs 6/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0034222599376287116, val_loss: 0.001691230240670082
epochs 7/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003463748601681896, val_loss: 0.0017043374344020298
epochs 8/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003472923907132721, val_loss: 0.0017191903288843796
epochs 9/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0034289501368460294, val_loss: 0.001735172530109259
epochs 10/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003441155596489185, val_loss: 0.0017523837324820066
epochs 11/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003408974622327246, val_loss: 0.0017704585282205555
epochs 12/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003524984077452437, val_loss: 0.0017894366520187375
epochs 13/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0033522451559914964, val_loss: 0.0018091511257041833
epochs 14/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0033040822287531274, val_loss: 0.0018291511465672796
epochs 15/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003366690372288423, val_loss: 0.0018496950524614045
epochs 16/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003304109770780135, val_loss: 0.0018708795532706732
epochs 17/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003414276287596869, val_loss: 0.0018917360781128274
epochs 18/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0031937616154257406, val_loss: 0.0019128912422609957
epochs 19/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003280094521438801, val_loss: 0.001933657701163994
epochs 20/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0030222981831205913, val_loss: 0.0019539088433559396
epochs 21/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003246576146614787, val_loss: 0.0019744332800129133
epochs 22/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.003133929901952414, val_loss: 0.0019951142284921125
epochs 23/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0032766676507890225, val_loss: 0.002015612776832361
epochs 24/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0031920539809537954, val_loss: 0.0020362803445957405
epochs 25/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0031154933177228823, val_loss: 0.002056612486730477
epochs 26/128
Current Learning Rate: 2.8370001910078596e-05
train_loss: 0.0031665057985504207, val_loss: 0.002076361309982052
epochs 27/128
Epoch 00027: reducing learning rate of group 0 to 1.9463e-05.
Current Learning Rate: 1.9463429572926445e-05
train_loss: 0.00298634328278958, val_loss: 0.002095998582234116
epochs 28/128
Current Learning Rate: 1.9463429572926445e-05
train_loss: 0.0029601002841158526, val_loss: 0.0021092966002853293
epochs 29/128
Current Learning Rate: 1.9463429572926445e-05
train_loss: 0.003026331179946857, val_loss: 0.0021220990931492692
epochs 30/128
Current Learning Rate: 1.9463429572926445e-05
train_loss: 0.003153282376373873, val_loss: 0.0021344511530754207
epochs 31/128

[I 2024-01-26 13:25:15,355] Trial 30 pruned.

Current Learning Rate: 1.9463429572926445e-05
train_loss: 0.0030130827370540877, val_loss: 0.0021468371428598307
epochs 32/128
Starting fold 1:
epochs 1/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0015277377648377105, val_loss: 0.0010079677143183194
epochs 2/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0011226273828039044, val_loss: 0.001277683817438389
epochs 3/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00118000701829595, val_loss: 0.0015244078822433949
epochs 4/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0012741837907876623, val_loss: 0.001582589343582329
epochs 5/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0012845197741530444, val_loss: 0.0014851402283008945
epochs 6/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0011949450708925724, val_loss: 0.0013150654083706047
epochs 7/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0010733726544697817, val_loss: 0.0011427174812476885
epochs 8/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0009490067298573099, val_loss: 0.0010051558860332559
epochs 9/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0008541315941042022, val_loss: 0.0009119175374507904
epochs 10/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0007916017754101439, val_loss: 0.0008546197603113557
epochs 11/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0007228194490859383, val_loss: 0.0008213920151128581
epochs 12/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0006692323490585151, val_loss: 0.000804042517158546
epochs 13/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0006145338625892213, val_loss: 0.0007990657253877112
epochs 14/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0005702345209245227, val_loss: 0.000803076043283861
epochs 15/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0005332799536470128, val_loss: 0.0008103714238754229
epochs 16/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0005024660372567412, val_loss: 0.0008136450564243683
epochs 17/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0004802142104477082, val_loss: 0.0008046675877841679
epochs 18/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0004508055066444764, val_loss: 0.0007807402228201298
epochs 19/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00041220214456859, val_loss: 0.0007457864887424206
epochs 20/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0003777243745341701, val_loss: 0.0007053525462795637
epochs 21/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00034722667126181096, val_loss: 0.0006662969214008435
epochs 22/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0003131278407588405, val_loss: 0.0006333268063731099
epochs 23/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0002768604807849777, val_loss: 0.0006078813825488874
epochs 24/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00025546825552163154, val_loss: 0.0005894578123269113
epochs 25/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00022828634399430533, val_loss: 0.0005768329199207457
epochs 26/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00020918033949687685, val_loss: 0.0005681863189429828
epochs 27/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00019266159966048834, val_loss: 0.0005616144871486253
epochs 28/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00017649315429336734, val_loss: 0.0005544609616902706
epochs 29/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0001650162686066898, val_loss: 0.0005443272622008072
epochs 30/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0001516016391657391, val_loss: 0.0005309675716010755
epochs 31/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00013889327697382358, val_loss: 0.0005158721438707097
epochs 32/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.0001329885394385967, val_loss: 0.0005011274938863751
epochs 33/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00012093096914835961, val_loss: 0.0004891643306779626
epochs 34/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00011337959432766136, val_loss: 0.00048077654546910996
epochs 35/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00011168827347175561, val_loss: 0.0004754847889815114
epochs 36/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00010195419484884234, val_loss: 0.0004726152707773604
epochs 37/91
Current Learning Rate: 0.0003489475933468397
train_loss: 0.00010456001511652415, val_loss: 0.00047061700790532326
epochs 38/91
Current Learning Rate: 0.0003489475933468397
train_loss: 9.405065219126347e-05, val_loss: 0.0004684954949066435
epochs 39/91
Current Learning Rate: 0.0003489475933468397
train_loss: 9.42952951606314e-05, val_loss: 0.00046520231071075325
epochs 40/91
Current Learning Rate: 0.0003489475933468397
train_loss: 9.259896116992949e-05, val_loss: 0.0004606669658402863
epochs 41/91
Current Learning Rate: 0.0003489475933468397
train_loss: 8.700530452188104e-05, val_loss: 0.00045604847898510724
epochs 42/91
Current Learning Rate: 0.0003489475933468397
train_loss: 8.692956256900768e-05, val_loss: 0.00045276413622655367
epochs 43/91
Current Learning Rate: 0.0003489475933468397
train_loss: 8.47791008326519e-05, val_loss: 0.00045158845789142345
epochs 44/91
Current Learning Rate: 0.0003489475933468397
train_loss: 8.405370968639066e-05, val_loss: 0.0004519866993895879
epochs 45/91
Current Learning Rate: 0.0003489475933468397
train_loss: 8.193481143711037e-05, val_loss: 0.00045348073686718156
epochs 46/91
Current Learning Rate: 0.0003489475933468397
train_loss: 7.94304448247299e-05, val_loss: 0.0004548842430506882
epochs 47/91
Current Learning Rate: 0.0003489475933468397
train_loss: 8.101185697964148e-05, val_loss: 0.00045575064570201854
epochs 48/91
Current Learning Rate: 0.0003489475933468397
train_loss: 7.827285183961259e-05, val_loss: 0.0004556684993746641
epochs 49/91
Current Learning Rate: 0.0003489475933468397
train_loss: 8.081668630965348e-05, val_loss: 0.000454730433902066
epochs 50/91
Current Learning Rate: 0.0003489475933468397
train_loss: 7.895085888632916e-05, val_loss: 0.0004532712903854094
epochs 51/91
Epoch 00051: reducing learning rate of group 0 to 2.9123e-04.
Current Learning Rate: 0.0002912340564123175
train_loss: 7.58041933295317e-05, val_loss: 0.00045323819167127733
epochs 52/91
Current Learning Rate: 0.0002912340564123175
train_loss: 7.73454341565651e-05, val_loss: 0.00045431068926853567
epochs 53/91
Current Learning Rate: 0.0002912340564123175
train_loss: 7.825013898055706e-05, val_loss: 0.00045597965914854094
epochs 54/91
Current Learning Rate: 0.0002912340564123175
train_loss: 7.620482249062901e-05, val_loss: 0.00045782047642492935
epochs 55/91
Current Learning Rate: 0.0002912340564123175
train_loss: 7.496471784849603e-05, val_loss: 0.0004585033503213995
epochs 56/91
Current Learning Rate: 0.0002912340564123175
train_loss: 7.866801522476108e-05, val_loss: 0.00045816228712761874
epochs 57/91
Current Learning Rate: 0.0002912340564123175
train_loss: 7.606176146318351e-05, val_loss: 0.0004573326686544246
epochs 58/91
Current Learning Rate: 0.0002912340564123175
train_loss: 7.501554500777274e-05, val_loss: 0.0004559366007972705
epochs 59/91
Epoch 00059: reducing learning rate of group 0 to 2.4307e-04.
Current Learning Rate: 0.00024306594236936895
train_loss: 7.53534983040912e-05, val_loss: 0.0004555019427483019
epochs 60/91
Current Learning Rate: 0.00024306594236936895
train_loss: 7.730357059412391e-05, val_loss: 0.00045562922758491417
epochs 61/91
Current Learning Rate: 0.00024306594236936895
train_loss: 7.499293937335576e-05, val_loss: 0.0004560383355343028
epochs 62/91
Current Learning Rate: 0.00024306594236936895
train_loss: 7.365792484243254e-05, val_loss: 0.0004557726328800383
epochs 63/91
Current Learning Rate: 0.00024306594236936895
train_loss: 7.364604282070344e-05, val_loss: 0.00045535201513159434
epochs 64/91
Current Learning Rate: 0.00024306594236936895
train_loss: 7.369057168130224e-05, val_loss: 0.00045444542468574484
epochs 65/91
Current Learning Rate: 0.00024306594236936895
train_loss: 7.337365164666583e-05, val_loss: 0.0004535641668266372
epochs 66/91
Current Learning Rate: 0.00024306594236936895
train_loss: 7.483873157884533e-05, val_loss: 0.00045290201485745216
epochs 67/91
Epoch 00067: reducing learning rate of group 0 to 2.0286e-04.
Current Learning Rate: 0.00020286450378682636
train_loss: 7.587146070651023e-05, val_loss: 0.00045239971644294103
epochs 68/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.379869777268093e-05, val_loss: 0.00045188550383930926
epochs 69/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.261485925961384e-05, val_loss: 0.0004511619427878606
epochs 70/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.20295586353658e-05, val_loss: 0.00045046424125566294
epochs 71/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.343014026685666e-05, val_loss: 0.00044941218986519073
epochs 72/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.420608246895044e-05, val_loss: 0.0004480742438892393
epochs 73/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.318313452598982e-05, val_loss: 0.0004473814287369973
epochs 74/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.742592884154107e-05, val_loss: 0.00044648582115769386
epochs 75/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.42503042075489e-05, val_loss: 0.00044564257902828485
epochs 76/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.224992632951686e-05, val_loss: 0.00044560841113132864
epochs 77/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.24933082605467e-05, val_loss: 0.00044633627035900166
epochs 78/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.221957562969213e-05, val_loss: 0.0004470743128637734
epochs 79/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.175294587413143e-05, val_loss: 0.00044712889939546585
epochs 80/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.282417056175243e-05, val_loss: 0.0004462207986139937
epochs 81/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.179163826788824e-05, val_loss: 0.0004450232035627491
epochs 82/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.16268408914881e-05, val_loss: 0.00044347883790339296
epochs 83/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.108500683802719e-05, val_loss: 0.00044244859294083555
epochs 84/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.050472394391698e-05, val_loss: 0.00044148500494070744
epochs 85/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.281455672407327e-05, val_loss: 0.0004413017856055184
epochs 86/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.130504634819532e-05, val_loss: 0.00044095222715680534
epochs 87/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.137097916136937e-05, val_loss: 0.0004410155417740737
epochs 88/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.074178421661552e-05, val_loss: 0.0004410441033542156
epochs 89/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.2856224218604e-05, val_loss: 0.00044093581872355
epochs 90/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.121604913232946e-05, val_loss: 0.0004410017281770706
epochs 91/91
Current Learning Rate: 0.00020286450378682636
train_loss: 7.224420589505156e-05, val_loss: 0.00044062493773373336
Starting fold 2:
epochs 1/91

[I 2024-01-26 13:25:19,353] Trial 31 pruned.

Starting fold 1:
epochs 1/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.013633958230677404, val_loss: 0.009595512618359767
epochs 2/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.006137879591704787, val_loss: 0.003533893539325187
epochs 3/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.002195246165348707, val_loss: 0.0011023154335194512
epochs 4/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0012548030305065607, val_loss: 0.0009624808891921451
epochs 5/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0016549421180235711, val_loss: 0.0012061566739392123
epochs 6/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0018180660388775562, val_loss: 0.001046339220269338
epochs 7/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.00146199098396066, val_loss: 0.0008194960715053113
epochs 8/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0009072283809808524, val_loss: 0.0008868232737050245
epochs 9/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0006457470369672305, val_loss: 0.0012687661219388247
epochs 10/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0006842602234284737, val_loss: 0.0017644721769580715
epochs 11/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0008716915357294248, val_loss: 0.0021503770233769165
epochs 12/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0010738810380357072, val_loss: 0.0022880412540153454
epochs 13/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0011272461934774918, val_loss: 0.0021591688555322197
epochs 14/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0010256665525957942, val_loss: 0.0018453094667117847
epochs 15/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.000850259224381788, val_loss: 0.0014663739889664085
epochs 16/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.000675955646683609, val_loss: 0.00112904630797474
epochs 17/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.000510575563499802, val_loss: 0.0008895731702643005
epochs 18/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0004139321366030919, val_loss: 0.0007536401506513357
epochs 19/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.00039373570685519984, val_loss: 0.0006908754217683485
epochs 20/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0003404796037724928, val_loss: 0.000675597446235387
epochs 21/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.00033295603995946675, val_loss: 0.0006989667792559454
epochs 22/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.00030863951848770837, val_loss: 0.0007609038209346565
epochs 23/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0002586588061316625, val_loss: 0.0008498635608702898
epochs 24/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.00026443983369972557, val_loss: 0.0009368794627095524
epochs 25/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.000261987410914643, val_loss: 0.0009864826735697294
epochs 26/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.00026547447854873577, val_loss: 0.00097441094388303
epochs 27/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0002501774413854276, val_loss: 0.0008975511147199493
epochs 28/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.0002115558544143201, val_loss: 0.0007946701279204143
epochs 29/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.00018149124700453525, val_loss: 0.0007004833326822049
epochs 30/97
Current Learning Rate: 0.0006712958137413195
train_loss: 0.00015316940376865922, val_loss: 0.0006338321946953473
epochs 31/97

[I 2024-01-26 13:25:21,195] Trial 32 pruned.

Current Learning Rate: 0.0006712958137413195
train_loss: 0.00015039813465830918, val_loss: 0.0006022336586427532
epochs 32/97
Starting fold 1:
epochs 1/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0024033478363172005, val_loss: 0.0025179891160836344
epochs 2/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0022397866546127357, val_loss: 0.002402617954526489
epochs 3/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0022048448966080813, val_loss: 0.0023101307874496438
epochs 4/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.002098651749915198, val_loss: 0.0022289927675094652
epochs 5/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0021065630196397634, val_loss: 0.002154553132928222
epochs 6/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0019639033033806634, val_loss: 0.0020874988459246725
epochs 7/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.001988304873903919, val_loss: 0.002029044749399059
epochs 8/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0019458017655109103, val_loss: 0.001977175537276229
epochs 9/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.001970608207691265, val_loss: 0.0019313342685468103
epochs 10/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.001977421519787688, val_loss: 0.0018905489200015406
epochs 11/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0019100242796795148, val_loss: 0.001855240745077792
epochs 12/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0019160730004506676, val_loss: 0.0018249402021817667
epochs 13/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0019268655616446937, val_loss: 0.0017982987955053288
epochs 14/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0018207757151685656, val_loss: 0.0017742538867567322
epochs 15/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0017581239532630303, val_loss: 0.001753417882106365
epochs 16/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0017742847276263332, val_loss: 0.0017352968984357033
epochs 17/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0018263269656975019, val_loss: 0.001718824514720932
epochs 18/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.001691282129429869, val_loss: 0.0017046380392888463
epochs 19/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.001753602098477514, val_loss: 0.00169218924742094
epochs 20/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0016068342993477065, val_loss: 0.0016801596032516835
epochs 21/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0016843321671905487, val_loss: 0.001668387639342415
epochs 22/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0016697415138447755, val_loss: 0.0016573909558294537
epochs 23/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.001638317364880717, val_loss: 0.0016471194743644447
epochs 24/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0016327918311090845, val_loss: 0.0016372399449066603
epochs 25/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0015621982879422017, val_loss: 0.0016282041887997797
epochs 26/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0016075947560909155, val_loss: 0.001619618273750683
epochs 27/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0015331290938009165, val_loss: 0.0016122108343743571
epochs 28/108

[I 2024-01-26 13:25:22,576] Trial 33 pruned.

Current Learning Rate: 6.488156166012874e-05
train_loss: 0.001508687717815567, val_loss: 0.001604720015280978
epochs 29/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.001550639777346269, val_loss: 0.0015973443833277806
epochs 30/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0015564771313955517, val_loss: 0.0015897456288497013
epochs 31/108
Current Learning Rate: 6.488156166012874e-05
train_loss: 0.0015024211328158058, val_loss: 0.001581768562257486
epochs 32/108
Starting fold 1:
epochs 1/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.006413558371193511, val_loss: 0.006849004365013618
epochs 2/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.003864215144054278, val_loss: 0.004074048942665717
epochs 3/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.002453600642835035, val_loss: 0.0025059462119028657
epochs 4/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0016578656841853732, val_loss: 0.0017586225426241167
epochs 5/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.001302487080101855, val_loss: 0.0014558472927953853
epochs 6/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0013525837945053353, val_loss: 0.001359956638311575
epochs 7/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.001227209181371635, val_loss: 0.0013785607959633987
epochs 8/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0011922250357824132, val_loss: 0.0014755594942375625
epochs 9/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0010988135855816501, val_loss: 0.0016273236721692803
epochs 10/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0011456511942302121, val_loss: 0.0018010654184955025
epochs 11/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0010244712536835944, val_loss: 0.0019538076188550086
epochs 12/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0010480795015801528, val_loss: 0.002050549420374936
epochs 13/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0011249415953275992, val_loss: 0.002061825404004929
epochs 14/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.001032403468362693, val_loss: 0.001984122755330693
epochs 15/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0010288720763607048, val_loss: 0.0018405448414820344
epochs 16/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0009131308539317137, val_loss: 0.001678862320917879
epochs 17/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0008554367475689536, val_loss: 0.0015409717313320326
epochs 18/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0007934414395621341, val_loss: 0.0014184967039526735
epochs 19/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0006533431990599064, val_loss: 0.0013441701404333702
epochs 20/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0006031886332876687, val_loss: 0.0013127030834623025
epochs 21/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.000568050576839596, val_loss: 0.0012948891048405417
epochs 22/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0005457046455519863, val_loss: 0.001289279936157216
epochs 23/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0005149652032598264, val_loss: 0.0012788180052762312
epochs 24/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0005136867997383601, val_loss: 0.0012543910271855757
epochs 25/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0004587122303507242, val_loss: 0.0012243275839290092
epochs 26/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00042873223114599425, val_loss: 0.001164064879872297
epochs 27/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00043778068601999333, val_loss: 0.0011052092956991767
epochs 28/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0003698695245762601, val_loss: 0.0010558009095563503
epochs 29/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0003380430634072247, val_loss: 0.0010107219831154094
epochs 30/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0003749373002823344, val_loss: 0.0009697352434925147
epochs 31/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00030642897694825046, val_loss: 0.0009340066797449253
epochs 32/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0003486055370702065, val_loss: 0.0009148954148067308
epochs 33/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00029803790124500855, val_loss: 0.0009168167670539237
epochs 34/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002872299464223416, val_loss: 0.0009192805752574809
epochs 35/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00028938050902644664, val_loss: 0.0008981016398664858
epochs 36/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00027952542693942395, val_loss: 0.0008749475809102143
epochs 37/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002811864798882437, val_loss: 0.0008481714566618106
epochs 38/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00024016857036928598, val_loss: 0.0008241342446509455
epochs 39/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00025760385829734766, val_loss: 0.0008157000837902735
epochs 40/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.000289767503272742, val_loss: 0.0008164776499861067
epochs 41/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002591343219759629, val_loss: 0.0008191422125061141
epochs 42/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002784762283370487, val_loss: 0.0008200295764254406
epochs 43/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002471780000058444, val_loss: 0.0008086651728310819
epochs 44/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002494056303188891, val_loss: 0.0008092599527643821
epochs 45/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00026081674640361023, val_loss: 0.0008048615543214653
epochs 46/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00027110076901551926, val_loss: 0.0007909880628224193
epochs 47/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002343909032979833, val_loss: 0.0007672938132600393
epochs 48/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00023353652213700115, val_loss: 0.0007276513079934949
epochs 49/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002753132964962309, val_loss: 0.0007134515592999952
epochs 50/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00021246585521638686, val_loss: 0.0007271604465801686
epochs 51/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00022738945622940694, val_loss: 0.0007489171779429613
epochs 52/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00022991154822337098, val_loss: 0.0007718295877183616
epochs 53/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002439344879301069, val_loss: 0.0007736150649036159
epochs 54/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00022246003752929698, val_loss: 0.0007561561780580392
epochs 55/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00026857480008498226, val_loss: 0.0007438005967598751
epochs 56/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00021350077785379988, val_loss: 0.0007392756416505252
epochs 57/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002097816536613544, val_loss: 0.0007262393948239103
epochs 58/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016658931946087824, val_loss: 0.0007453983404526585
epochs 59/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017901623780888163, val_loss: 0.0007770396981581335
epochs 60/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00021724365873715694, val_loss: 0.000781652883903773
epochs 61/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002172179900011734, val_loss: 0.0007647927376781713
epochs 62/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001803723608119119, val_loss: 0.0007275757335025303
epochs 63/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00020044532828155512, val_loss: 0.0006814932501583825
epochs 64/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00021360249083954841, val_loss: 0.0006679250824642
epochs 65/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002004369068584454, val_loss: 0.0006956214848813895
epochs 66/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00022058015747461468, val_loss: 0.000723402351133317
epochs 67/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00020981340685945102, val_loss: 0.0007328680179948845
epochs 68/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00021216648494469393, val_loss: 0.0007306361672434784
epochs 69/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00019152990946742264, val_loss: 0.0007231349906329629
epochs 70/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00021988822393866845, val_loss: 0.0006993202214959494
epochs 71/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017276475876937375, val_loss: 0.0006911381538405916
epochs 72/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017437640566832238, val_loss: 0.0006820239065028114
epochs 73/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017812024506335883, val_loss: 0.0006700027783824082
epochs 74/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00020308864270765826, val_loss: 0.0006616906566992647
epochs 75/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.000189243276958893, val_loss: 0.0006586233898384595
epochs 76/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001385609453121249, val_loss: 0.0006671481609565058
epochs 77/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016964814896805604, val_loss: 0.0006899296994991968
epochs 78/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00021516870619961992, val_loss: 0.0007207781854958739
epochs 79/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001795608054779127, val_loss: 0.0007366643285326733
epochs 80/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00018242977852136582, val_loss: 0.0006872045658574759
epochs 81/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017305467619352336, val_loss: 0.0006452535541412592
epochs 82/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016501615157865575, val_loss: 0.0006279245990107915
epochs 83/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001609927782402864, val_loss: 0.0006204365279700141
epochs 84/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016599791009579541, val_loss: 0.000642706497149591
epochs 85/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00018760817604886957, val_loss: 0.0006651415300056167
epochs 86/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017850522356303898, val_loss: 0.0006493999480689557
epochs 87/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017419030857701345, val_loss: 0.0006238806016642085
epochs 88/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001532762726511512, val_loss: 0.0005993572279725126
epochs 89/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001643198031448073, val_loss: 0.0006182287802068075
epochs 90/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017378646505102026, val_loss: 0.0006500135435520574
epochs 91/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016500787582787637, val_loss: 0.0006709218706849865
epochs 92/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00014738473278396813, val_loss: 0.0006812480977188036
epochs 93/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001464659773965219, val_loss: 0.0006584461427050165
epochs 94/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00014669962325378468, val_loss: 0.0006374398063742679
epochs 95/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016718278639018535, val_loss: 0.000616463173010791
epochs 96/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016653565812463822, val_loss: 0.0005917977749241369
epochs 97/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00014981371342927513, val_loss: 0.0005720406728965156
Starting fold 2:
epochs 1/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00033005330698965973, val_loss: 0.00971677572417416
epochs 2/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0005199982009607514, val_loss: 0.009745544306688794
epochs 3/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00043602144570812875, val_loss: 0.01134205795334358
epochs 4/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0003808927115307214, val_loss: 0.010592052905428175
epochs 5/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00032608110938637863, val_loss: 0.00907279905299411
epochs 6/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002943160857141361, val_loss: 0.008437530858148086
epochs 7/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00033139561652971775, val_loss: 0.008775054227168623
epochs 8/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0003287774935750732, val_loss: 0.008789680950882795
epochs 9/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002733727996344801, val_loss: 0.008036521262195158
epochs 10/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00028427434946551284, val_loss: 0.007374707282839441
epochs 11/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002505092622366072, val_loss: 0.007054911697847083
epochs 12/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00030373480978213545, val_loss: 0.0071173324029108415
epochs 13/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002915954553540551, val_loss: 0.007100067575045518
epochs 14/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00024016701415683584, val_loss: 0.006640783702881125
epochs 15/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002469629145803322, val_loss: 0.00624835755320658
epochs 16/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.000284114636566588, val_loss: 0.006255577940885958
epochs 17/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00029127335388023457, val_loss: 0.006118905698071773
epochs 18/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002464494837974933, val_loss: 0.005759355223026911
epochs 19/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002493249717333942, val_loss: 0.005655563797336072
epochs 20/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00026871536120827503, val_loss: 0.005472437762287691
epochs 21/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002346479817596877, val_loss: 0.0051632685237564145
epochs 22/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00023595114720305184, val_loss: 0.005075779533638668
epochs 23/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00023622793956555574, val_loss: 0.00503831478969292
epochs 24/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00020158247025392484, val_loss: 0.004678471161873619
epochs 25/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00021979568995639535, val_loss: 0.004553379472283843
epochs 26/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00021502517449430581, val_loss: 0.004721510396522813
epochs 27/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001954802422245082, val_loss: 0.004560115805055063
epochs 28/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00020674293141622146, val_loss: 0.004512344403376215
epochs 29/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00019706415491543196, val_loss: 0.0044486176063257615
epochs 30/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00020289897656766698, val_loss: 0.004302405485711796
epochs 31/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0002226258279207334, val_loss: 0.004017441412801609
epochs 32/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00022951538523652984, val_loss: 0.004098187142211061
epochs 33/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00018941832573833188, val_loss: 0.004070688841717416
epochs 34/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001898137483007495, val_loss: 0.0037978854011989347
epochs 35/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00018619994799863842, val_loss: 0.0036275724734878166
epochs 36/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001772904884427063, val_loss: 0.003717961027532032
epochs 37/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001743833245678903, val_loss: 0.0036209432736014654
epochs 38/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00020905787517365657, val_loss: 0.0033970975484025026
epochs 39/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017290313867545737, val_loss: 0.003158194875026024
epochs 40/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00017673378514652876, val_loss: 0.0033633140896103886
epochs 41/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016235108355191954, val_loss: 0.0031162451258799255
epochs 42/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00018025159485037683, val_loss: 0.0029768552213729556
epochs 43/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00015986000718456986, val_loss: 0.0028946310274094635
epochs 44/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001609171756028541, val_loss: 0.002731358822922247
epochs 45/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016068372244358454, val_loss: 0.002775613915123119
epochs 46/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016831571219403198, val_loss: 0.0026464369723199575
epochs 47/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00015878943861600037, val_loss: 0.0025310745527875904
epochs 48/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00013364812649869188, val_loss: 0.0024576450583194136
epochs 49/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00015862701134449853, val_loss: 0.002623762826184056
epochs 50/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00014387281227850747, val_loss: 0.0023115298349263244
epochs 51/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00016923464882941181, val_loss: 0.0023337986235243365
epochs 52/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00014015453422249073, val_loss: 0.0024766427596516318
epochs 53/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00014511035499852274, val_loss: 0.002313998018661024
epochs 54/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00013605148535708922, val_loss: 0.002252882095528644
epochs 55/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.00013467584350636524, val_loss: 0.0022667654960011867
epochs 56/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001235673657088467, val_loss: 0.0020071987354496838
epochs 57/97
Current Learning Rate: 0.00024336271617796497
train_loss: 0.0001279089947370506, val_loss: 0.002025184638286622
epochs 58/97
Current Learning Rate: 0.00024336271617796497

[I 2024-01-26 13:26:05,196] Trial 34 finished with value: 0.0014333708475238347 and parameters: {'batch_size': 81, 'epochs': 97, 'hidden_size': 87, 'learning_rate': 0.00024336271617796497, 'dropout_prob': 0.05355603480168346, 'weight_decay': 1.7594380069047365e-05, 'lr_step_size': 17, 'gamma': 0.7400233221387637, 'num_layers': 1}. Best is trial 18 with value: 0.0011512266347036932.

Current Learning Rate: 0.00013327382360519814
train_loss: 0.0004568108655803371, val_loss: 0.000824403086995804
epochs 97/97
Current Learning Rate: 0.00013327382360519814
train_loss: 0.000427552166327491, val_loss: 0.0007538101274373108
Mean validation loss: 0.0014333708475238347
Starting fold 1:
epochs 1/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.013061169677070881, val_loss: 0.017747381157977016
epochs 2/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.012380286178698666, val_loss: 0.016567317215039543
epochs 3/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.011307514507911707, val_loss: 0.015443242341279983
epochs 4/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.010402331501245499, val_loss: 0.01437134408441029
epochs 5/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.009757876092273939, val_loss: 0.013349796929641774
epochs 6/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.009031931972621303, val_loss: 0.012379991679795479
epochs 7/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.008332741397776101, val_loss: 0.011460137112360252
epochs 8/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.007463164615297788, val_loss: 0.010591358946342217
epochs 9/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.006882710139708299, val_loss: 0.009771302964930471
epochs 10/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.006306402441604357, val_loss: 0.008998563657759836
epochs 11/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.00584902665332744, val_loss: 0.008272041797049736
epochs 12/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.005267582402417534, val_loss: 0.007591045069459237
epochs 13/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.004850627632664615, val_loss: 0.0069552729923376124
epochs 14/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0042127609841133415, val_loss: 0.006365249553499253
epochs 15/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0038960558975017386, val_loss: 0.005818784795701503
epochs 16/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0035172859464134825, val_loss: 0.005315294087937984
epochs 17/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0031240966416111117, val_loss: 0.0048527263074280005
epochs 18/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0029370584647710387, val_loss: 0.004429401188329058
epochs 19/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0026554280260920916, val_loss: 0.004043073183244193
epochs 20/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0023712235000474674, val_loss: 0.0036937435375109903
epochs 21/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.002217882967210914, val_loss: 0.0033794528660732077
epochs 22/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0021263004001842714, val_loss: 0.0030965351707939255
epochs 23/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.001851488654746821, val_loss: 0.0028429899643493913
epochs 24/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0017801211604627928, val_loss: 0.0026170465243539136
epochs 25/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0015449653805454115, val_loss: 0.002417455088671934
epochs 26/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0014094572586289265, val_loss: 0.0022439091492407514
epochs 27/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.001377681322628632, val_loss: 0.0020925111397733227
epochs 28/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0012679390590883007, val_loss: 0.0019611136074864158
epochs 29/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.001252113109129775, val_loss: 0.0018467197032326734
epochs 30/77

[I 2024-01-26 13:26:07,364] Trial 35 pruned.

Current Learning Rate: 3.94838586297792e-05
train_loss: 0.0011777666345312212, val_loss: 0.001749878875623261
epochs 31/77
Current Learning Rate: 3.94838586297792e-05
train_loss: 0.001153956834566902, val_loss: 0.001668301060501682
epochs 32/77
Starting fold 1:
epochs 1/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.005006869017195545, val_loss: 0.006008678652640236
epochs 2/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00315752639802859, val_loss: 0.004018068894449818
epochs 3/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0019569505355320873, val_loss: 0.002618478392067022
epochs 4/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0012859605219043596, val_loss: 0.0017261607027888347
epochs 5/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.000929761853216118, val_loss: 0.001228167658662546
epochs 6/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.000704253292305542, val_loss: 0.0009887742626137638
epochs 7/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0006908985724868743, val_loss: 0.0008919528901491216
epochs 8/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0006361665377258569, val_loss: 0.0008584132497689049
epochs 9/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0006636786280739072, val_loss: 0.0008586117288551146
epochs 10/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0005977913855244161, val_loss: 0.0008894136458892669
epochs 11/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0006107858408205702, val_loss: 0.0009538344490513401
epochs 12/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00047394534087384513, val_loss: 0.0010507321339039328
epochs 13/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00044302571339741053, val_loss: 0.0011564349693607685
epochs 14/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0005593137243474637, val_loss: 0.0012395649746299328
epochs 15/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0005352887050800124, val_loss: 0.0012822225794432024
epochs 16/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0005152024324879197, val_loss: 0.0012745335724168017
epochs 17/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0005653071309145736, val_loss: 0.0012239746478275935
epochs 18/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0004033261741585049, val_loss: 0.0011606612308241893
epochs 19/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.000482719668836676, val_loss: 0.0010840673754788249
epochs 20/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003616406981324728, val_loss: 0.0010181187464791276
epochs 21/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003982425959915609, val_loss: 0.00096405107990569
epochs 22/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003340482059253478, val_loss: 0.0009268135290384586
epochs 23/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003184499003844777, val_loss: 0.0009079251426890934
epochs 24/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.000328056722815075, val_loss: 0.0009029460790579354
epochs 25/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00033522452010258444, val_loss: 0.0009073850562057678
epochs 26/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002932225247557079, val_loss: 0.0009058380487610855
epochs 27/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002796996966169804, val_loss: 0.0009122707540978139
epochs 28/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00027007342241153025, val_loss: 0.0009118354304901962
epochs 29/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002886153617414254, val_loss: 0.0009190927500496496
epochs 30/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.000304033363538206, val_loss: 0.0009209396798963242
epochs 31/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00024401705296967473, val_loss: 0.0009116705740636557
epochs 32/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00025393775446757086, val_loss: 0.0008927819897699489
epochs 33/103
Epoch 00033: reducing learning rate of group 0 to 1.1963e-04.
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00023516443677516164, val_loss: 0.0008686302865451006
epochs 34/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00022091236958084138, val_loss: 0.0008586888480318809
epochs 35/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0002562151198569489, val_loss: 0.0008494525104699853
epochs 36/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00023424591835416656, val_loss: 0.0008399237662639567
epochs 37/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0002579346649949194, val_loss: 0.0008298538667747236
epochs 38/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00024005352262113438, val_loss: 0.0008253505758291699
epochs 39/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00024098209442423754, val_loss: 0.0008236388246204067
epochs 40/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00024687823361570113, val_loss: 0.0008175152307988978
epochs 41/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00023165241222350712, val_loss: 0.0008066630602881655
epochs 42/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00024202870293888018, val_loss: 0.0007957688226030625
epochs 43/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021050900563989816, val_loss: 0.0007842089199249657
epochs 44/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00020517753934990124, val_loss: 0.0007748253141088706
epochs 45/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00016710660856915637, val_loss: 0.0007690732939456786
epochs 46/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00020996989677721437, val_loss: 0.0007653587997131246
epochs 47/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00019027773799423715, val_loss: 0.0007693335293688027
epochs 48/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00018930773137406886, val_loss: 0.0007670018314935365
epochs 49/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00022890559867894472, val_loss: 0.000754582825481377
epochs 50/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021797882049883667, val_loss: 0.0007421602366345101
epochs 51/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00020157467025503712, val_loss: 0.0007371579626985629
epochs 52/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.000232130687647058, val_loss: 0.0007423713673089974
epochs 53/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021700653267448376, val_loss: 0.0007553077128250151
epochs 54/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021671388377925675, val_loss: 0.000769873462214539
epochs 55/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00022408380709269918, val_loss: 0.0007776193723609475
epochs 56/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00020496554375552621, val_loss: 0.0007700055102376561
epochs 57/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00023189628026509462, val_loss: 0.0007649777917801035
epochs 58/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00022765156249270627, val_loss: 0.0007666011986561658
epochs 59/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00020785916184602109, val_loss: 0.000760393893984943
epochs 60/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00020236656258164562, val_loss: 0.0007498767848071446
epochs 61/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021773313607187256, val_loss: 0.0007460544702266098
epochs 62/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00023255576065582174, val_loss: 0.0007471132853472802
epochs 63/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021309733381617423, val_loss: 0.0007492156947448261
epochs 64/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00018886137978896793, val_loss: 0.0007464641050319188
epochs 65/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00022675545777402524, val_loss: 0.0007337194172003748
epochs 66/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021031094733380565, val_loss: 0.000722231275377501
epochs 67/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.000198312002038093, val_loss: 0.0007206284536024262
epochs 68/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021673567121309277, val_loss: 0.0007324411106789117
epochs 69/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00016215985562762638, val_loss: 0.0007416420886951719
epochs 70/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00018214364421223044, val_loss: 0.0007408586070692093
epochs 71/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00019370648584108015, val_loss: 0.0007431988844473381
epochs 72/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00019121825515819516, val_loss: 0.0007475102170581905
epochs 73/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0002302676521235538, val_loss: 0.0007444422478377084
epochs 74/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00020758311997939784, val_loss: 0.0007470456315403633
epochs 75/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00019654470785386173, val_loss: 0.0007405062082781163
epochs 76/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00019982213056401202, val_loss: 0.0007368595570656716
epochs 77/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021223612359455346, val_loss: 0.0007287849609718634
epochs 78/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021320036007397758, val_loss: 0.0007226378411455938
epochs 79/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0002028238558283958, val_loss: 0.0007119790692645199
epochs 80/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0001642651351989786, val_loss: 0.0007043378193645224
epochs 81/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0002112070320627505, val_loss: 0.0006914524055900984
epochs 82/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00021579428706134326, val_loss: 0.0006875742228370847
epochs 83/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0001986232298230262, val_loss: 0.0006756346582398308
epochs 84/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0001889803396280561, val_loss: 0.0006726993368111404
epochs 85/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0001968736035786079, val_loss: 0.0006804926507787681
epochs 86/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00017918116262942356, val_loss: 0.0006930703387632475
epochs 87/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00018730624050428894, val_loss: 0.0007041575873077626
epochs 88/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.000154505786409381, val_loss: 0.0007122947719165639
epochs 89/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0001640386338725588, val_loss: 0.0007103923134165693
epochs 90/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0001642164172249307, val_loss: 0.0007073332934707746
epochs 91/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00019308309083020217, val_loss: 0.0006973232759934801
epochs 92/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00018680149032182893, val_loss: 0.0007001358609781355
epochs 93/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00017345802732865866, val_loss: 0.0006998915514390989
epochs 94/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00017147483656452478, val_loss: 0.0006955211603781209
epochs 95/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.0001892470777659726, val_loss: 0.0006963282045035158
epochs 96/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00017670529127108717, val_loss: 0.0006927480212317804
epochs 97/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00015862648625012584, val_loss: 0.0006871384512985395
epochs 98/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00017866532787018898, val_loss: 0.0006840680030444147
epochs 99/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00019530529856350958, val_loss: 0.0006825032288983685
epochs 100/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00019416283566418938, val_loss: 0.0006730464156517931
epochs 101/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00017237144049048718, val_loss: 0.0006641595121963244
epochs 102/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00016685119557414987, val_loss: 0.0006610207159323373
epochs 103/103
Current Learning Rate: 0.00011962823590957567
train_loss: 0.00018009554593223392, val_loss: 0.0006697627503997769
Starting fold 2:
epochs 1/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0004957366009062082, val_loss: 0.019579474287303656
epochs 2/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00035927968067545936, val_loss: 0.01604243227966914
epochs 3/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00043487245773002017, val_loss: 0.015299183091050701
epochs 4/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00046751907211728394, val_loss: 0.016007075473470123
epochs 5/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0004480116545700615, val_loss: 0.016593826454328862
epochs 6/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003880891464512771, val_loss: 0.016397001662928807
epochs 7/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003710173513115335, val_loss: 0.0157165339069539
epochs 8/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0004124934250476623, val_loss: 0.015037118371478036
epochs 9/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003606552636100739, val_loss: 0.014593463565075867
epochs 10/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00039076531860413716, val_loss: 0.01427279544847184
epochs 11/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00033187456271997165, val_loss: 0.014067376708905947
epochs 12/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00033792551927801565, val_loss: 0.013902432986192013
epochs 13/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003351571190777529, val_loss: 0.013623144641812695
epochs 14/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003522127905422454, val_loss: 0.013478586869314312
epochs 15/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00032936256971688156, val_loss: 0.013134009116574337
epochs 16/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003199239596525379, val_loss: 0.012642399078284048
epochs 17/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003075475681965288, val_loss: 0.012311300244427434
epochs 18/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00027820659471265236, val_loss: 0.01227493078178285
epochs 19/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00030532473714342095, val_loss: 0.012036716830181447
epochs 20/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00031071066673336504, val_loss: 0.011565970184624587
epochs 21/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00030866927301854285, val_loss: 0.011264158936070376
epochs 22/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00028595886990507625, val_loss: 0.010947741974929445
epochs 23/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002722149561266537, val_loss: 0.010736930976915908
epochs 24/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002960677892827478, val_loss: 0.010929700234708817
epochs 25/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00028323947128803027, val_loss: 0.010738042428305275
epochs 26/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00027068753142406136, val_loss: 0.010206620302051305
epochs 27/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002592006589111406, val_loss: 0.009638598308849491
epochs 28/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003010722904659097, val_loss: 0.009372658277616689
epochs 29/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00025230252695588494, val_loss: 0.00928437823895365
epochs 30/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002793982336649941, val_loss: 0.009332949888745421
epochs 31/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0003024671708867812, val_loss: 0.009071505461868487
epochs 32/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002506261051932693, val_loss: 0.008595756623330281
epochs 33/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00025601855346681795, val_loss: 0.008343728716901847
epochs 34/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002405580314715687, val_loss: 0.008052765613568848
epochs 35/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002694696603851442, val_loss: 0.007809372798319122
epochs 36/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002563422746070979, val_loss: 0.007572644996138192
epochs 37/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002321378860582818, val_loss: 0.007360351806825125
epochs 38/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00022973933492290884, val_loss: 0.007182865336806955
epochs 39/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002665988438055042, val_loss: 0.0069751271683918805
epochs 40/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00023761349308953965, val_loss: 0.006722940883819798
epochs 41/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00022321931078055825, val_loss: 0.006453136580162926
epochs 42/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00022268261726774078, val_loss: 0.0063387159104949155
epochs 43/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002328199480344713, val_loss: 0.00619975070799946
epochs 44/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00019220844576346664, val_loss: 0.005897599852362059
epochs 45/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002506349562042344, val_loss: 0.005584254132975873
epochs 46/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00020888446114871554, val_loss: 0.005380773351919887
epochs 47/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00019604660339705572, val_loss: 0.005304278607639533
epochs 48/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0002158893589359267, val_loss: 0.005180463774779223
epochs 49/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00020580973518678403, val_loss: 0.004980040311592778
epochs 50/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00020382484339949626, val_loss: 0.004765681517739339
epochs 51/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.00024392661534396835, val_loss: 0.004608683385824981
epochs 52/103
Current Learning Rate: 0.0001776211215729719
train_loss: 0.0001943391350658586, val_loss: 0.004534808112504451
epochs 53/103
Current Learning Rate: 0.0001776211215729719

[I 2024-01-26 13:26:28,024] Trial 36 pruned.

Current Learning Rate: 0.0001776211215729719
train_loss: 0.00026326930427897246, val_loss: 0.0018332809148552387
epochs 66/103
Starting fold 1:
epochs 1/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0016638561087586965, val_loss: 0.0015491892393727444
epochs 2/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0014520944823743775, val_loss: 0.00174231090472619
epochs 3/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0014179633037297446, val_loss: 0.001897302960155924
epochs 4/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.001426570239250156, val_loss: 0.001955048522703644
epochs 5/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0014251659097346036, val_loss: 0.0019376538816447322
epochs 6/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0013760979552324372, val_loss: 0.0018855556248270563
epochs 7/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0013340859157707247, val_loss: 0.001818143281669013
epochs 8/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0013367854836887044, val_loss: 0.0017568499529979338
epochs 9/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0012721387664848742, val_loss: 0.0017114290676545352
epochs 10/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0012319321525099344, val_loss: 0.0016880872472507978
epochs 11/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0012129850648833734, val_loss: 0.0016921261573627003
epochs 12/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011880229048026529, val_loss: 0.0017106419499644911
epochs 13/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011842525878149133, val_loss: 0.0017287621387942253
epochs 14/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011816272293033666, val_loss: 0.0017369405694281387
epochs 15/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011822018614590266, val_loss: 0.0017325947487016062
epochs 16/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011731077775996375, val_loss: 0.0017239785979894038
epochs 17/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011685493518598378, val_loss: 0.0017158390071831252
epochs 18/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011381517550417858, val_loss: 0.0017104537921688078
epochs 19/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011496475413686742, val_loss: 0.0017002481924320914
epochs 20/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011247246714590705, val_loss: 0.001688121657169081
epochs 21/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011354218402534332, val_loss: 0.0016810861262983006
epochs 22/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011147543218133873, val_loss: 0.0016758679213173884
epochs 23/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011130635263582103, val_loss: 0.0016741805961110483
epochs 24/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011272591578553577, val_loss: 0.0016784341331865442
epochs 25/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011457181803722818, val_loss: 0.0016839937659250083
epochs 26/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.001137751110179938, val_loss: 0.0016878805962685299
epochs 27/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011203925065561443, val_loss: 0.0016885031042252912
epochs 28/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.001118414803242654, val_loss: 0.0016855264257173985
epochs 29/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011052322730201443, val_loss: 0.001680815358045756
epochs 30/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.001109112089340526, val_loss: 0.001673000737546796
epochs 31/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0010890923570657737, val_loss: 0.0016690885577669466
epochs 32/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0010863866107109444, val_loss: 0.0016682407157005447
epochs 33/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0010877906897803769, val_loss: 0.001667161119832216
epochs 34/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.001097596503984134, val_loss: 0.001666906429148328
epochs 35/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0010867624277077419, val_loss: 0.0016695522461209055
epochs 36/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0010850395958282445, val_loss: 0.0016729710868706828
epochs 37/117
Current Learning Rate: 0.0005493501274163368
train_loss: 0.0011034473588408314, val_loss: 0.0016757922360403953
epochs 38/117
Epoch 00038: reducing learning rate of group 0 to 3.0542e-04.
Current Learning Rate: 0.0003054249532957617
train_loss: 0.001105563961716957, val_loss: 0.0016765623463709887
epochs 39/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010919092846482894, val_loss: 0.00167553922265621
epochs 40/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010664939495894175, val_loss: 0.0016759970059961472
epochs 41/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010732081343456613, val_loss: 0.0016785059844168198
epochs 42/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0011011377753579598, val_loss: 0.0016796814054128174
epochs 43/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010883118941963307, val_loss: 0.0016823753141675536
epochs 44/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010747337686265574, val_loss: 0.0016836703993919257
epochs 45/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010829209373026203, val_loss: 0.001684161482109247
epochs 46/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010536307312768738, val_loss: 0.0016832373297993879
epochs 47/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010837390612945647, val_loss: 0.0016811643436085433
epochs 48/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.001103012770487878, val_loss: 0.0016785035213136947
epochs 49/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0011007685473151995, val_loss: 0.0016756871712124465
epochs 50/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010812984286243782, val_loss: 0.0016749832261427258
epochs 51/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0011085610757091719, val_loss: 0.0016738791616118856
epochs 52/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010821195786487998, val_loss: 0.0016737029884672282
epochs 53/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010901904399935646, val_loss: 0.0016721299815751415
epochs 54/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010842978395215284, val_loss: 0.0016722553777263353
epochs 55/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.001079108145572, val_loss: 0.0016740858692700338
epochs 56/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.00110381235227626, val_loss: 0.0016777527022273525
epochs 57/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010781517446862142, val_loss: 0.001680754910921678
epochs 58/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010730794463980648, val_loss: 0.0016829941305331886
epochs 59/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010812276511722686, val_loss: 0.0016837764767268183
epochs 60/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010727844576314581, val_loss: 0.0016848107410815398
epochs 61/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010899012551434633, val_loss: 0.0016835635071497802
epochs 62/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0011065706976775178, val_loss: 0.0016814211113868576
epochs 63/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010697064181409875, val_loss: 0.0016804778669642186
epochs 64/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010825067783068669, val_loss: 0.0016801385117057514
epochs 65/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0011020826235548348, val_loss: 0.0016798524593468755
epochs 66/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010899215588946582, val_loss: 0.0016794720906641726
epochs 67/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.001093903304488202, val_loss: 0.0016776951363824896
epochs 68/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010864329263935552, val_loss: 0.0016750985937266562
epochs 69/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010870745961591112, val_loss: 0.0016752327991477948
epochs 70/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010827169102604354, val_loss: 0.001675153209362179
epochs 71/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0011210607312693213, val_loss: 0.0016758813872002065
epochs 72/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.001092623910823788, val_loss: 0.0016756411779696417
epochs 73/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010795741224061011, val_loss: 0.0016748853101346054
epochs 74/117
Current Learning Rate: 0.0003054249532957617
train_loss: 0.0010911216285373819, val_loss: 0.0016733135531754478
epochs 75/117
Epoch 00075: reducing learning rate of group 0 to 1.6981e-04.
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010990940392826144, val_loss: 0.0016705606938462313
epochs 76/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.001070760051094878, val_loss: 0.0016690382586890145
epochs 77/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010688724088188458, val_loss: 0.0016677942506870941
epochs 78/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010804116372080323, val_loss: 0.0016676120285410434
epochs 79/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010757092708158062, val_loss: 0.0016677899019621116
epochs 80/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.001084343316554288, val_loss: 0.0016675045925168025
epochs 81/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0011164177137145184, val_loss: 0.001667794019388231
epochs 82/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010895782615989447, val_loss: 0.0016679878080092174
epochs 83/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010869919841704693, val_loss: 0.0016689894469699969
epochs 84/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010970725875507157, val_loss: 0.0016700162714665854
epochs 85/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.00109846698576707, val_loss: 0.001670744029596742
epochs 86/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010726225591497496, val_loss: 0.0016716829804384983
epochs 87/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010756963395244, val_loss: 0.0016722564423138177
epochs 88/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.001078621391666514, val_loss: 0.0016721695872930515
epochs 89/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010948128512705136, val_loss: 0.0016724822589343315
epochs 90/117
Current Learning Rate: 0.00016980864741844437
train_loss: 0.0010770840775589214, val_loss: 0.0016728602196580094
epochs 91/117

[I 2024-01-26 13:26:33,852] Trial 37 pruned.

Current Learning Rate: 0.00016980864741844437
train_loss: 0.001086160689929353, val_loss: 0.0016730188493200235
epochs 92/117
Starting fold 1:
epochs 1/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0024249984539653126, val_loss: 0.0027643673054530823
epochs 2/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002040190965329346, val_loss: 0.0027631790006508758
epochs 3/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0021916057847097123, val_loss: 0.00276262892906456
epochs 4/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0019851628917661544, val_loss: 0.0027620590821913395
epochs 5/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0020803430693616207, val_loss: 0.0027615004648013333
epochs 6/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002073521480748528, val_loss: 0.0027609759479099395
epochs 7/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002013303308845743, val_loss: 0.002760415029785547
epochs 8/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0021353469591734835, val_loss: 0.002759712832477434
epochs 9/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0021656956247936344, val_loss: 0.0027589356100897453
epochs 10/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.001911287808692769, val_loss: 0.002758060321579442
epochs 11/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0019181119308708922, val_loss: 0.0027571718934555783
epochs 12/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002160375515048049, val_loss: 0.002756290824005478
epochs 13/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002159831304054119, val_loss: 0.002755413234760789
epochs 14/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002145870233346757, val_loss: 0.0027545446922120297
epochs 15/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0020351098623665933, val_loss: 0.002753716149048782
epochs 16/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0020756032348512427, val_loss: 0.002752930048461023
epochs 17/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0020225151491008305, val_loss: 0.0027521544681420843
epochs 18/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002019136497677353, val_loss: 0.002751424061563356
epochs 19/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002178851827537935, val_loss: 0.0027506112390638967
epochs 20/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.001981119609952561, val_loss: 0.002749896142631769
epochs 21/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0021632650658782375, val_loss: 0.0027492568141927846
epochs 22/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0019379080285465246, val_loss: 0.002748727055548347
epochs 23/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0021073695878792357, val_loss: 0.002748173480779913
epochs 24/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002037489731600018, val_loss: 0.0027475920030969733
epochs 25/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0020399893554368695, val_loss: 0.002746906666097378
epochs 26/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002073277906196094, val_loss: 0.002746182847706797
epochs 27/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.001986178152851368, val_loss: 0.0027454450809225243
epochs 28/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.002030610842140097, val_loss: 0.002744743481008826
epochs 29/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0019208071324484128, val_loss: 0.002744042702129503
epochs 30/99
Current Learning Rate: 1.283341718268883e-06
train_loss: 0.001931825226883551, val_loss: 0.002743301154910832
epochs 31/99

[I 2024-01-26 13:26:36,000] Trial 38 pruned.

Current Learning Rate: 1.283341718268883e-06
train_loss: 0.0020355177540822248, val_loss: 0.002742416640486274
epochs 32/99
Starting fold 1:
epochs 1/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.09345318987279345, val_loss: 0.0021580456033054936
epochs 2/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0016132292803376913, val_loss: 0.0012191601073075283
epochs 3/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0012836639193425838, val_loss: 0.002096406689624449
epochs 4/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0011944876505846256, val_loss: 0.0007683285512030125
epochs 5/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0005393405444920063, val_loss: 0.004452039938003413
epochs 6/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.011486023076270757, val_loss: 0.01354057488864974
epochs 7/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.007576091067963525, val_loss: 0.002954696170299461
epochs 8/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0026194983603138673, val_loss: 0.002379703197603751
epochs 9/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.004639120135260255, val_loss: 0.0022361965568147993
epochs 10/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0037583404367691592, val_loss: 0.0010740736646479682
epochs 11/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0013544191728885237, val_loss: 0.0022542301081366054
epochs 12/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.002123694634065032, val_loss: 0.0036992956148950676
epochs 13/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0021787230415563834, val_loss: 0.003465489404717166
epochs 14/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0020103485102912315, val_loss: 0.001997745166973848
epochs 15/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0012942803472182469, val_loss: 0.0009282605483588812
epochs 16/146
Epoch 00016: reducing learning rate of group 0 to 8.4326e-03.
Current Learning Rate: 0.00843258894780005
train_loss: 0.0010147974305590125, val_loss: 0.0007976483489313212
epochs 17/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.0011921848452306893, val_loss: 0.000810865297496907
epochs 18/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.001070992567723519, val_loss: 0.0007151554485684947
epochs 19/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.0007895465762550501, val_loss: 0.0008282222368411327
epochs 20/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.0007805148856469282, val_loss: 0.0009863503908395376
epochs 21/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.0006605674524938589, val_loss: 0.0008631889956488617
epochs 22/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.0004792493051163068, val_loss: 0.000481506778956636
epochs 23/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00036566530960906103, val_loss: 0.0006009718957724736
epochs 24/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.0004029350514572702, val_loss: 0.00044903522479887073
epochs 25/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00035503510949446966, val_loss: 0.0007264662402265362
epochs 26/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.000335823435115775, val_loss: 0.0004832296093043528
epochs 27/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00032984904522125264, val_loss: 0.0004946215975858075
epochs 28/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.0003134806006289038, val_loss: 0.00044610281781244437
epochs 29/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00030052420793493325, val_loss: 0.00048766809969062085
epochs 30/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.0003096940054092556, val_loss: 0.0004533318523930288
epochs 31/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.0002950474797551961, val_loss: 0.0004609880806559599
epochs 32/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00027970883897260616, val_loss: 0.0004632506017132025
epochs 33/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00024913316194311177, val_loss: 0.00046804030487117797
epochs 34/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00026014111905456767, val_loss: 0.00046338485615131885
epochs 35/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00026377846600218237, val_loss: 0.00046465600424103046
epochs 36/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00022326641039016018, val_loss: 0.0004839927423745394
epochs 37/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00022924745510528353, val_loss: 0.000490915924800854
epochs 38/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00019423607323245195, val_loss: 0.00046547145374413386
epochs 39/146
Current Learning Rate: 0.00843258894780005
train_loss: 0.00020601233010989075, val_loss: 0.00047974713073161085
epochs 40/146
Epoch 00040: reducing learning rate of group 0 to 4.8637e-03.
Current Learning Rate: 0.004863708219998459
train_loss: 0.00021014775158714895, val_loss: 0.0005186753696762025
epochs 41/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.00020142023277003318, val_loss: 0.0005086140774533545
epochs 42/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.0002182712487410754, val_loss: 0.000483287290032757
epochs 43/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.00020927481435999078, val_loss: 0.0004877414413433718
epochs 44/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.00019440712333705865, val_loss: 0.000515903545371992
epochs 45/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.000173457502234286, val_loss: 0.0005018485611990878
epochs 46/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.00018424641702471204, val_loss: 0.0004894057668647484
epochs 47/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.00016931220536781964, val_loss: 0.0005095740504513838
epochs 48/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.00017553949682654716, val_loss: 0.0005421403697446772
epochs 49/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.00018173418893160202, val_loss: 0.0005132939213102585
epochs 50/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.00017832549622797065, val_loss: 0.0004934335593134165
epochs 51/146
Current Learning Rate: 0.004863708219998459
train_loss: 0.00017846650275475296, val_loss: 0.0005351688228792658
epochs 52/146
Epoch 00052: reducing learning rate of group 0 to 2.8053e-03.
Current Learning Rate: 0.002805266306197935
train_loss: 0.00019347203105050874, val_loss: 0.0005682637427909006
epochs 53/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.00019232914124394913, val_loss: 0.0005233366636706418
epochs 54/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.00017036313089958735, val_loss: 0.0005054091146264813
epochs 55/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.0001589330081754413, val_loss: 0.0005318770080951875
epochs 56/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.0001502047104479157, val_loss: 0.0005362598703389889
epochs 57/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.00017216730338986963, val_loss: 0.0005352917911582871
epochs 58/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.00016720471658596866, val_loss: 0.000526477015993901
epochs 59/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.00015384837062906866, val_loss: 0.0005201533939199228
epochs 60/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.00016741701294545477, val_loss: 0.0005530217006851576
epochs 61/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.00015165822926639137, val_loss: 0.0005349754723475167
epochs 62/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.00015213263012762917, val_loss: 0.0005272498176629213
epochs 63/146
Current Learning Rate: 0.002805266306197935
train_loss: 0.00016631550495635326, val_loss: 0.0005368357922538723
epochs 64/146
Epoch 00064: reducing learning rate of group 0 to 1.6180e-03.
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00017488346968189274, val_loss: 0.0005520322501022173
epochs 65/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00014100094727166978, val_loss: 0.000555970169922435
epochs 66/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00014181653233735184, val_loss: 0.0005431964007010194
epochs 67/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00013171036047615896, val_loss: 0.0005296696663687104
epochs 68/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00015649289937420306, val_loss: 0.0005352324867424997
epochs 69/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00014054734952208636, val_loss: 0.0005298251819208657
epochs 70/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00014639685334833828, val_loss: 0.0005328862431557163
epochs 71/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00015298428632760127, val_loss: 0.0005565509138824908
epochs 72/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00017289805691689253, val_loss: 0.0005747409947951766
epochs 73/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00016162542191236034, val_loss: 0.0005673906340043208
epochs 74/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.0001368876041133741, val_loss: 0.000552553640629508
epochs 75/146
Current Learning Rate: 0.0016180080491530594
train_loss: 0.00014013074810224536, val_loss: 0.0005557880213018507
epochs 76/146
Epoch 00076: reducing learning rate of group 0 to 9.3323e-04.
Current Learning Rate: 0.000933226924424255
train_loss: 0.00014794438366631143, val_loss: 0.0005670847803182704
epochs 77/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.00015747424913570285, val_loss: 0.0005686298536602408
epochs 78/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.0001530378519275569, val_loss: 0.0005573420187973074
epochs 79/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.0001529756761891277, val_loss: 0.0005724882373071619
epochs 80/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.00013463600311967495, val_loss: 0.0005889097213328473
epochs 81/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.0001451291111726804, val_loss: 0.0006087988103421307
epochs 82/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.000142160655262782, val_loss: 0.0005977223320913158
epochs 83/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.00013008124063306145, val_loss: 0.0005720619657567065
epochs 84/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.00013831317329803775, val_loss: 0.000553367953551443
epochs 85/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.0001522562777513246, val_loss: 0.0005608882929664105
epochs 86/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.0001384208597683985, val_loss: 0.0005829704750794917
epochs 87/146
Current Learning Rate: 0.000933226924424255
train_loss: 0.0001370452051847487, val_loss: 0.0005941656847043257
epochs 88/146
Epoch 00088: reducing learning rate of group 0 to 5.3826e-04.
Current Learning Rate: 0.0005382621507514936
train_loss: 0.00014368826937003943, val_loss: 0.0005833711000281925
epochs 89/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.0001452700196655075, val_loss: 0.0005852505641278663
epochs 90/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.00014314266292402814, val_loss: 0.0005897078693746344
epochs 91/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.00015739284572191536, val_loss: 0.0005822463013158229
epochs 92/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.0001573879202815557, val_loss: 0.0005851258297058704
epochs 93/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.00014368417109117697, val_loss: 0.0005897609762063152
epochs 94/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.000128480268023467, val_loss: 0.0005812679883092642
epochs 95/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.00013913462661500824, val_loss: 0.0005904680231316505
epochs 96/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.0001429571926373204, val_loss: 0.0005947995799176983
epochs 97/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.0001417559603731589, val_loss: 0.000588522070565408
epochs 98/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.00013378037118328442, val_loss: 0.0005876816561028949
epochs 99/146
Current Learning Rate: 0.0005382621507514936
train_loss: 0.00014193129410207468, val_loss: 0.0006045727426872441
epochs 100/146
Epoch 00100: reducing learning rate of group 0 to 3.1046e-04.
Current Learning Rate: 0.00031045626240409566
train_loss: 0.0001385942132880078, val_loss: 0.0006292192250073544
epochs 101/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.00014438730048775477, val_loss: 0.000636277273052225
epochs 102/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.00014190324873197824, val_loss: 0.00063328374955362
epochs 103/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.0001484126359604201, val_loss: 0.0006236804413339613
epochs 104/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.00015470708603970706, val_loss: 0.0006056604769056369
epochs 105/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.0001352371764369309, val_loss: 0.0005885645499036304
epochs 106/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.00014116255777863493, val_loss: 0.0005776599067949542
epochs 107/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.000147799046030023, val_loss: 0.000570753068467112
epochs 108/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.00012252119440266766, val_loss: 0.0005677187858198426
epochs 109/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.00014690395083131365, val_loss: 0.0005689810694955094
epochs 110/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.00014860137659860286, val_loss: 0.0005833702652077926
epochs 111/146
Current Learning Rate: 0.00031045626240409566
train_loss: 0.00014770647899958452, val_loss: 0.0005910755732513376
epochs 112/146
Epoch 00112: reducing learning rate of group 0 to 1.7906e-04.
Current Learning Rate: 0.0001790634744266444
train_loss: 0.0001438975845016294, val_loss: 0.0005995741858465695
epochs 113/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.00013712079319367674, val_loss: 0.0006068719820560593
epochs 114/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.00014352015032751582, val_loss: 0.0006104338007341875
epochs 115/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.00013789532347704823, val_loss: 0.0006118808692247656
epochs 116/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.00013940606119209215, val_loss: 0.0006131026434319976
epochs 117/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.00013124021873074142, val_loss: 0.0006121973963576908
epochs 118/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.0001387356261195811, val_loss: 0.000601505796351519
epochs 119/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.0001508747173877629, val_loss: 0.0005926916216451087
epochs 120/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.00012715985940303653, val_loss: 0.0005848819380748625
epochs 121/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.00013938680364701308, val_loss: 0.0005765974990361812
epochs 122/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.00014231625812642865, val_loss: 0.000573570431075304
epochs 123/146
Current Learning Rate: 0.0001790634744266444
train_loss: 0.00013885972025730697, val_loss: 0.0005770269444359368
epochs 124/146
Epoch 00124: reducing learning rate of group 0 to 1.0328e-04.
Current Learning Rate: 0.0001032793721906205
train_loss: 0.00012045983404325518, val_loss: 0.0005771151841863206
epochs 125/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.0001440525336779262, val_loss: 0.0005782251108413268
epochs 126/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.00016766853284360352, val_loss: 0.0005757193399691268
epochs 127/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.00013265900902057948, val_loss: 0.0005738427893160598
epochs 128/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.00012355821021820272, val_loss: 0.0005756026719035091
epochs 129/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.0001453772565582767, val_loss: 0.0005795218335391071
epochs 130/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.00014155056468505216, val_loss: 0.00058437726999584
epochs 131/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.00014660961000787976, val_loss: 0.0005885114093727775
epochs 132/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.00014531097181852122, val_loss: 0.0005899413004762641
epochs 133/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.0001325235245626812, val_loss: 0.0005923959098780822
epochs 134/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.00013920262848076068, val_loss: 0.0005971260941709931
epochs 135/146
Current Learning Rate: 0.0001032793721906205
train_loss: 0.00013281313371599505, val_loss: 0.0006019148583474912
epochs 136/146
Epoch 00136: reducing learning rate of group 0 to 5.9569e-05.
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.00013413680273132692, val_loss: 0.0006082374817005506
epochs 137/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.00014354407750560264, val_loss: 0.000610440039676369
epochs 138/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.00015680491081806585, val_loss: 0.0006107699760162321
epochs 139/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.00012305665433431337, val_loss: 0.0006096368765850601
epochs 140/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.00013482862758744312, val_loss: 0.0006081687032220591
epochs 141/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.00013241147864487415, val_loss: 0.0006062947152378527
epochs 142/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.0001626171242127097, val_loss: 0.0006029398048811249
epochs 143/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.00012756700284386935, val_loss: 0.000599237407042988
epochs 144/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.00013870973213526763, val_loss: 0.0005957577270333116
epochs 145/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.0001283407442602574, val_loss: 0.0005937809994640319
epochs 146/146
Current Learning Rate: 5.9568981079155994e-05
train_loss: 0.00014803664127707874, val_loss: 0.0005925748984353911
Starting fold 2:
epochs 1/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.002907848653481587, val_loss: 0.05210838329635168
epochs 2/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0015025534513896626, val_loss: 0.012164751263825517
epochs 3/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.003953111192554627, val_loss: 0.05884377305444918
epochs 4/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0014463066472671926, val_loss: 0.032093707177984085
epochs 5/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0025504434107508707, val_loss: 0.047826674423719705
epochs 6/146
Current Learning Rate: 0.014620234838549195
train_loss: 0.0015665213638720544, val_loss: 0.0463900073970619
epochs 7/146
Current Learning Rate: 0.014620234838549195

[I 2024-01-26 13:26:59,082] Trial 39 pruned.

Number of finished trials: 40
Best trial:
Value: 0.0011512266347036932
Params:
batch_size: 126
epochs: 108
hidden_size: 55
learning_rate: 0.0011771377657156651
dropout_prob: 0.127914833127579
weight_decay: 1.1312951163760579e-05
lr_step_size: 36
gamma: 0.6414565779787799
num_layers: 1

In [132]:
trainer = ModelActioner(train_data, test_data, device, model_type)
model = trainer.train(trial.params)

epochs 1/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.22239974339149501
epochs 2/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.039227310180860134
epochs 3/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.07507393879962987
epochs 4/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.045202181346126295
epochs 5/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.023447028561005074
epochs 6/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.016177093433706383
epochs 7/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.009941333281121364
epochs 8/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.006076831294615802
epochs 9/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.009177255476702397
epochs 10/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.007298129611942721
epochs 11/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.01469885814983986
epochs 12/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00754801322166857
epochs 13/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.009231265292404906
epochs 14/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005183542856799537
epochs 15/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.006420809250190168
epochs 16/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00418747096279587
epochs 17/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.004209945981366266
epochs 18/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00325546947975741
epochs 19/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00365826444835157
epochs 20/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0029997659295699316
epochs 21/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.003155442711737889
epochs 22/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0028013032730852595
epochs 23/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0031545250766947374
epochs 24/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.003053776732964539
epochs 25/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0025984056156104136
epochs 26/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0024430735850106237
epochs 27/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.003315197217345581
epochs 28/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.004269788882045663
epochs 29/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0042816827632793176
epochs 30/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0046585823035504865
epochs 31/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005341261430447431
epochs 32/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005534989363207531
epochs 33/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005296878786726953
epochs 34/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005497061667387913
epochs 35/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0049981566520536464
epochs 36/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.006714137367548813
epochs 37/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.007956460386585125
epochs 38/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.006946436248070217
epochs 39/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.007423356597734567
epochs 40/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005536939739556003
epochs 41/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.004858732515161759
epochs 42/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.003344522847175157
epochs 43/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002870823858967541
epochs 44/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002194382677369408
epochs 45/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0020808407183626277
epochs 46/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0019412568742776975
epochs 47/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002036348713322935
epochs 48/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.001910479627335199
epochs 49/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0021234948394856855
epochs 50/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00210301927750391
epochs 51/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0021375647718454467
epochs 52/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002208473673703051
epochs 53/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0019077076449512357
epochs 54/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.001969161594292688
epochs 55/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0018188546553382797
epochs 56/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002419334661681205
epochs 57/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002584012042988386
epochs 58/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0032549419884545434
epochs 59/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.003390006401413733
epochs 60/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0045440474999946
epochs 61/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.007080865935820743
epochs 62/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.006212608978814004
epochs 63/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.006643235380225202
epochs 64/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.006114090685916476
epochs 65/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005628603372085644
epochs 66/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.004097745198401084
epochs 67/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0035750862869654634
epochs 68/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.003057495545975766
epochs 69/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0029309973662939707
epochs 70/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002336846838941136
epochs 71/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0019513208751480928
epochs 72/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002024701055013697
epochs 73/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002246800058147576
epochs 74/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002106101645882805
epochs 75/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0019126277626798438
epochs 76/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0019013558790902606
epochs 77/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0017617895474694178
epochs 78/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0018516915707885728
epochs 79/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0016683350936785388
epochs 80/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.001992114855353353
epochs 81/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002124708715755811
epochs 82/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0019823392522276234
epochs 83/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.002011678196140565
epochs 84/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0015541272793167368
epochs 85/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.001820988597357523
epochs 86/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0025059725061414373
epochs 87/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0027045717848906
epochs 88/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.003716327094987623
epochs 89/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005140793010650668
epochs 90/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0053281891876586565
epochs 91/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005719544394646379
epochs 92/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.005237790417404061
epochs 93/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0051772828119666025
epochs 94/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0039523567871104824
epochs 95/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.003580830375568966
epochs 96/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0031862471392071854
epochs 97/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.00236619098769121
epochs 98/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.001922617146307235
epochs 99/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0018889759192365762
epochs 100/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0023154209775384516
epochs 101/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0015759026199750799
epochs 102/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0014627087911082382
epochs 103/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0014348477149676337
epochs 104/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0015485204882631815
epochs 105/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0012942180172295162
epochs 106/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.001476049647853391
epochs 107/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0013700383519263644
epochs 108/108
Current Learning Rate: 0.0011771377657156651
train_loss: 0.0014108738364915266

In [133]:
y_true = y_test_df[time_step:]
preds = trainer.test(trial.params)

# Mean Absolute Error
mae = mean_absolute_error(y_true, preds)
print(f'Mean Absolute Error: {mae}')

# Mean Squared Error
mse = mean_squared_error(y_true, preds)
print(f'Mean Squared Error: {mse}')

# Root Mean Squared Error
rmse = np.sqrt(mse)
print(f'Root Mean Squared Error: {rmse}')

# R-squared Score
r2 = r2_score(y_true, preds)
print(f'R-squared Score: {r2}')

mape = mean_absolute_percentage_error(y_true, preds)*100
print(f"MAPE: {mape}")

test_loss: 0.001196102937683463
Mean Absolute Error: 0.029745363273016752
Mean Squared Error: 0.001196102764509944
Root Mean Squared Error: 0.03458471865593161
R-squared Score: 0.8839130177836735
MAPE: 3.011679615510095

In [134]:
y_true

44     0.728267
45     0.737950
46     0.733381
47     0.747701
48     0.761134
         ...
291    1.018693
292    1.059493
293    1.079584
294    1.095561
295    1.104407
Name: Adj Close, Length: 252, dtype: float64

In [162]:
y_true = y_true.reset_index(drop=True)
#y_true = y_true.drop(columns=["index","level_0"])
X_value = X_test_df.iloc[43:,-1]
X_value = X_value.reset_index()
preds_values = [x[0] for x in preds]
X_value["Preds"] = pd.Series(preds_values)
X_value["Next Day"] = y_true
X_value = X_value.drop(columns=["index"])
X_value["Diff Preds"] = (X_value["Preds"] - X_value["Adj Close"])
X_value["Diff Next Day"] = (X_value["Next Day"] - X_value["Adj Close"])
X_value = X_value.dropna()
X_value

     Adj Close     Preds  Next Day  Diff Preds  Diff Next Day
0     0.706173  0.693062  0.728267   -0.013111       0.022093
1     0.728267  0.705377  0.737950   -0.022890       0.009683
2     0.737950  0.715592  0.733381   -0.022357      -0.004569
3     0.733381  0.719320  0.747701   -0.014061       0.014320
4     0.747701  0.726739  0.761134   -0.020962       0.013433
..         ...       ...       ...         ...            ...
247   1.025208  0.993976  1.018693   -0.031231      -0.006514
248   1.018693  0.985355  1.059493   -0.033338       0.040800
249   1.059493  1.001208  1.079584   -0.058285       0.020091
250   1.079584  1.018027  1.095561   -0.061557       0.015977
251   1.095561  1.035326  1.104407   -0.060236       0.008846

[252 rows x 5 columns]

In [163]:
def assign_label(diff):
    if diff > 0.001:
        return 1  # Buy
    elif diff < -0.05:
        return 0  # Sell
    else:
        return 2  # Hold/Other

In [164]:
# Apply the function to assign labels
X_value['Signal Preds'] = X_value['Diff Preds'].apply(assign_label)
X_value['Signal True'] = X_value['Diff Next Day'].apply(assign_label)

# Dropping the intermediate difference columns if they are no longer needed
X_value = X_value.drop(columns=['Diff Preds', 'Diff Next Day'])

X_value

     Adj Close     Preds  Next Day  Signal Preds  Signal True
0     0.706173  0.693062  0.728267             2            1
1     0.728267  0.705377  0.737950             2            1
2     0.737950  0.715592  0.733381             2            2
3     0.733381  0.719320  0.747701             2            1
4     0.747701  0.726739  0.761134             2            1
..         ...       ...       ...           ...          ...
247   1.025208  0.993976  1.018693             2            2
248   1.018693  0.985355  1.059493             2            1
249   1.059493  1.001208  1.079584             0            1
250   1.079584  1.018027  1.095561             0            1
251   1.095561  1.035326  1.104407             0            1

[252 rows x 5 columns]

In [165]:
accuracy = accuracy_score(X_value["Signal True"], X_value["Signal Preds"])
print(f'Accuracy: {accuracy * 100:.2f}%')

# Precision
precision = precision_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'Precision: {precision:.4f}')

# Recall
recall = recall_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'Recall: {recall:.4f}')

# F1 Score
f1 = f1_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'F1 Score: {f1:.4f}')

Accuracy: 47.62%
Precision: 0.6666
Recall: 0.4762
F1 Score: 0.3439

In [166]:
y_true

0      0.728267
1      0.737950
2      0.733381
3      0.747701
4      0.761134
         ...
247    1.018693
248    1.059493
249    1.079584
250    1.095561
251    1.104407
Name: Adj Close, Length: 252, dtype: float64

In [167]:
X_value["Signal Preds"]

0      2
1      2
2      2
3      2
4      2
      ..
247    2
248    2
249    0
250    0
251    0
Name: Signal Preds, Length: 252, dtype: int64

In [168]:
signals = pd.DataFrame(X_value["Signal Preds"].values, columns=['Signal'])
signals

     Signal
0         2
1         2
2         2
3         2
4         2
..      ...
247       2
248       2
249       0
250       0
251       0

[252 rows x 1 columns]

In [169]:
signals["Signal"].value_counts()

Signal
2    236
0     10
1      6
Name: count, dtype: int64

In [170]:
signals["Date"] = date_test
signals

     Signal        Date
0         2  2023-01-23
1         2  2023-01-24
2         2  2023-01-25
3         2  2023-01-26
4         2  2023-01-27
..      ...         ...
247       2  2024-01-17
248       2  2024-01-18
249       0  2024-01-19
250       0  2024-01-22
251       0  2024-01-23

[252 rows x 2 columns]

In [171]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737762
2    141.071487
3    143.159821
4    145.118835
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [172]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

AttributeError: Can only use .dt accessor with datetimelike values

In [173]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
buy_signals = signals[signals['Signal'] == 1]
sell_signals = signals[signals['Signal'] == 0]

# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]

# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))

# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))

# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

In [174]:
price_signal = stock_data[stock_data['Date'].isin(signals['Date'])]["Adj Close"]
price_signal = price_signal.reset_index()
price_signal = price_signal.drop(columns=["index"])
result = pd.concat([price_signal,signals], axis=1)
result

      Adj Close  Signal        Date
0    140.325653       2  2023-01-23
1    141.737762       2  2023-01-24
2    141.071487       2  2023-01-25
3    143.159821       2  2023-01-26
4    145.118835       2  2023-01-27
..          ...     ...         ...
247  182.679993       2  2024-01-17
248  188.630005       2  2024-01-18
249  191.559998       0  2024-01-19
250  193.889999       0  2024-01-22
251  195.179993       0  2024-01-23

[252 rows x 3 columns]

In [175]:
price_signal

      Adj Close
0    140.325653
1    141.737762
2    141.071487
3    143.159821
4    145.118835
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [149]:
sell_signals

     Signal       Date
148       0 2023-08-24
152       0 2023-08-30
153       0 2023-08-31
154       0 2023-09-01
155       0 2023-09-05
156       0 2023-09-06
210       0 2023-11-21
249       0 2024-01-19
250       0 2024-01-22
251       0 2024-01-23

In [150]:
buy_prices

Series([], Name: Adj Close, dtype: float64)