In [26]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm

In [27]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [28]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722874  43.075001  42.314999  102223600
1  2018-01-03  40.715782  43.637501  42.990002  118071600
2  2018-01-04  40.904903  43.367500  43.020000   89738400
3  2018-01-05  41.370617  43.842499  43.262501   94640000
4  2018-01-08  41.216972  43.902500  43.482498   82271200
5  2018-01-09  41.212234  43.764999  43.352501   86336000
6  2018-01-10  41.202774  43.575001  43.250000   95839600
7  2018-01-11  41.436810  43.872501  43.622501   74670800
8  2018-01-12  41.864704  44.340000  43.912498  101672400
9  2018-01-16  41.651939  44.847500  44.035000  118263600
10 2018-01-17  42.339878  44.812500  43.767502  137547200
11 2018-01-18  42.377705  45.025002  44.562500  124773600
12 2018-01-19  42.188572  44.895000  44.352501  129700400
13 2018-01-22  41.843422  44.445000  44.150002  108434400
14 2018-01-23  41.852871  44.860001  44.205002  130756400
15 2018-01-24  41.186222  44.325001  43.299999  204420400
16 2018-01-25  40.451012  43.737499  42.632500  166116000
17 2018-01-26  40.545570  43.000000  42.514999  156572000
18 2018-01-29  39.706329  42.540001  41.767502  202561600
19 2018-01-30  39.472305  41.842499  41.174999  184192800
20 2018-01-31  39.581043  42.110001  41.625000  129915600
21 2018-02-01  39.663780  42.154999  41.689999  188923200
22 2018-02-02  37.942764  41.700001  40.025002  346375200
23 2018-02-05  36.994797  40.970001  39.000000  290954000
24 2018-02-06  38.540874  40.930000  38.500000  272975200
25 2018-02-07  37.715828  40.849998  39.767502  206434400
26 2018-02-08  36.678020  40.250000  38.757500  217562000
27 2018-02-09  37.126640  39.472500  37.560001  282690400
28 2018-02-12  38.622055  40.972500  39.377499  243278000
29 2018-02-13  39.008949  41.187500  40.412498  130196800
30 2018-02-14  39.728172  41.884998  40.720001  162579600
31 2018-02-15  41.062195  43.272499  42.250000  204588800
32 2018-02-16  40.929237  43.705002  42.942501  160704400
33 2018-02-20  40.791584  43.564999  42.855000  135722000
34 2018-02-21  40.606430  43.529999  42.752499  149886400
35 2018-02-22  40.945873  43.487499  42.927502  123967600
36 2018-02-23  41.657978  43.912498  43.384998  135249600
37 2018-02-26  42.481640  44.847500  44.052502  152648800
38 2018-02-27  42.343960  45.119999  44.540001  155712400
39 2018-02-28  42.279888  45.154999  44.512501  151128400
40 2018-03-01  41.539291  44.945000  43.165001  195208000
41 2018-03-02  41.826511  44.075001  43.112499  153816000
42 2018-03-05  41.971302  44.435001  43.630001  113605600
43 2018-03-06  41.935692  44.562500  44.032501   95154000
44 2018-03-07  41.546417  43.962502  43.567501  126814000

In [29]:
time_step = 44

In [30]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [31]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [32]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma = talib.SMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA': sma,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [33]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724166,117105600.0
15,NaN,NaN,55.580714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706163,-87314800.0
16,NaN,NaN,45.152421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695100,-253430800.0
17,NaN,NaN,46.541666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.818108,2.684663,-96858800.0
18,NaN,NaN,37.470200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639374,-81.393431,2.635361,-299420400.0
19,NaN,NaN,35.398265,NaN,NaN,42.761509,41.213175,39.664841,NaN,NaN,-61.987903,-75.553944,2.599704,-483613200.0
20,NaN,NaN,37.137612,NaN,NaN,42.849893,41.156083,39.462273,NaN,NaN,-49.633966,-63.087081,2.602418,-353697600.0
21,NaN,NaN,38.494546,NaN,NaN,42.910289,41.103483,39.296678,NaN,NaN,-41.626546,-51.082805,2.600385,-164774400.0
22,NaN,NaN,25.947657,NaN,NaN,43.228468,40.955376,38.682285,NaN,NaN,-40.766198,-44.008904,2.560087,-511149600.0
23,NaN,NaN,21.743657,NaN,NaN,43.578806,40.736585,37.894364,NaN,NaN,-38.059512,-40.150752,2.593455,-802103600.0
24,NaN,NaN,39.079674,NaN,NaN,43.590201,40.602780,37.615360,NaN,NaN,-24.766563,-34.530758,2.689294,-529128400.0
25,NaN,NaN,34.666315,NaN,NaN,43.652095,40.427960,37.203826,NaN,NaN,-14.972404,-25.932826,2.662139,-735562800.0
26,NaN,NaN,30.066648,NaN,NaN,43.790963,40.201722,36.612481,NaN,NaN,-13.427771,-17.722246,2.652999,-953124800.0
27,NaN,NaN,34.135011,NaN,NaN,43.765501,39.986214,36.206926,NaN,NaN,-15.615398,-14.671858,2.663105,-670434400.0
28,NaN,NaN,45.513663,NaN,NaN,43.544875,39.824081,36.103288,NaN,NaN,-6.294895,-11.779355,2.747587,-427156400.0
29,NaN,NaN,48.015865,NaN,NaN,43.330493,39.691932,36.053371,NaN,NaN,11.072682,-3.612537,2.734577,-296959600.0
30,NaN,NaN,52.392737,NaN,NaN,42.991923,39.561347,36.130770,NaN,NaN,26.336864,10.371550,2.744682,-134380000.0
31,NaN,NaN,59.246678,NaN,NaN,42.753743,39.495571,36.237399,NaN,NaN,41.539639,26.316395,2.801800,70208800.0
32,NaN,NaN,58.345095,NaN,NaN,42.524603,39.432604,36.340606,NaN,NaN,51.997520,39.958008,2.790443,-90495600.0
33,-0.373865,-0.940885,57.371680,NaN,NaN,42.339125,39.380013,36.420900,NaN,NaN,56.241759,49.926306,2.779394,-226217600.0
34,-0.274211,-0.807551,56.017890,NaN,NaN,42.113871,39.317690,36.521510,NaN,NaN,52.331145,53.523475,2.776467,-376104000.0
35,-0.165932,-0.679227,57.975711,NaN,NaN,42.071530,39.305673,36.539816,NaN,NaN,52.421386,53.664763,2.783939,-252136400.0
36,-0.022400,-0.547861,61.815806,NaN,NaN,42.278014,39.366021,36.454028,NaN,NaN,56.395015,53.715849,2.796988,-116886800.0
37,0.156014,-0.407086,65.717908,NaN,NaN,42.641719,39.462825,36.283931,NaN,NaN,62.381560,57.065987,2.825026,35762000.0
38,0.283036,-0.269062,64.530804,NaN,NaN,43.012911,39.594706,36.176501,NaN,NaN,65.108318,61.294964,2.811693,-119950400.0
39,0.374218,-0.140406,63.951858,NaN,NaN,43.346781,39.735085,36.123390,NaN,NaN,64.319978,63.936619,2.811646,-271078800.0
40,0.382313,-0.035862,57.527272,NaN,NaN,43.527897,39.832998,36.138098,NaN,NaN,59.272713,62.900337,2.801179,-466286800.0
41,0.407211,0.052752,59.237562,NaN,NaN,43.735156,39.941134,36.147113,NaN,NaN,52.309014,58.633902,2.782217,-312470800.0
42,0.433627,0.128927,60.109606,NaN,NaN,43.918529,40.142561,36.366594,NaN,NaN,42.550392,51.377373,2.769808,-198865200.0
43,0.446542,0.192450,59.770928,NaN,NaN,43.949829,40.389606,36.829384,40.596318,40.596318,34.222971,43.027459,2.757050,-294019200.0
44,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-420833200.0

In [34]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722874
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715782
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904903
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370617
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216972
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212234
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202774
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436810
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864704
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651939
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339878
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377705
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188572
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843422
14,NaN,NaN,68.998186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724166,117105600.0,41.852871
15,NaN,NaN,55.580714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706163,-87314800.0,41.186222
16,NaN,NaN,45.152421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695100,-253430800.0,40.451012
17,NaN,NaN,46.541666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.818108,2.684663,-96858800.0,40.545570
18,NaN,NaN,37.470200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639374,-81.393431,2.635361,-299420400.0,39.706329
19,NaN,NaN,35.398265,NaN,NaN,42.761509,41.213175,39.664841,NaN,NaN,-61.987903,-75.553944,2.599704,-483613200.0,39.472305
20,NaN,NaN,37.137612,NaN,NaN,42.849893,41.156083,39.462273,NaN,NaN,-49.633966,-63.087081,2.602418,-353697600.0,39.581043
21,NaN,NaN,38.494546,NaN,NaN,42.910289,41.103483,39.296678,NaN,NaN,-41.626546,-51.082805,2.600385,-164774400.0,39.663780
22,NaN,NaN,25.947657,NaN,NaN,43.228468,40.955376,38.682285,NaN,NaN,-40.766198,-44.008904,2.560087,-511149600.0,37.942764
23,NaN,NaN,21.743657,NaN,NaN,43.578806,40.736585,37.894364,NaN,NaN,-38.059512,-40.150752,2.593455,-802103600.0,36.994797
24,NaN,NaN,39.079674,NaN,NaN,43.590201,40.602780,37.615360,NaN,NaN,-24.766563,-34.530758,2.689294,-529128400.0,38.540874
25,NaN,NaN,34.666315,NaN,NaN,43.652095,40.427960,37.203826,NaN,NaN,-14.972404,-25.932826,2.662139,-735562800.0,37.715828
26,NaN,NaN,30.066648,NaN,NaN,43.790963,40.201722,36.612481,NaN,NaN,-13.427771,-17.722246,2.652999,-953124800.0,36.678020
27,NaN,NaN,34.135011,NaN,NaN,43.765501,39.986214,36.206926,NaN,NaN,-15.615398,-14.671858,2.663105,-670434400.0,37.126640
28,NaN,NaN,45.513663,NaN,NaN,43.544875,39.824081,36.103288,NaN,NaN,-6.294895,-11.779355,2.747587,-427156400.0,38.622055
29,NaN,NaN,48.015865,NaN,NaN,43.330493,39.691932,36.053371,NaN,NaN,11.072682,-3.612537,2.734577,-296959600.0,39.008949
30,NaN,NaN,52.392737,NaN,NaN,42.991923,39.561347,36.130770,NaN,NaN,26.336864,10.371550,2.744682,-134380000.0,39.728172
31,NaN,NaN,59.246678,NaN,NaN,42.753743,39.495571,36.237399,NaN,NaN,41.539639,26.316395,2.801800,70208800.0,41.062195
32,NaN,NaN,58.345095,NaN,NaN,42.524603,39.432604,36.340606,NaN,NaN,51.997520,39.958008,2.790443,-90495600.0,40.929237
33,-0.373865,-0.940885,57.371680,NaN,NaN,42.339125,39.380013,36.420900,NaN,NaN,56.241759,49.926306,2.779394,-226217600.0,40.791584
34,-0.274211,-0.807551,56.017890,NaN,NaN,42.113871,39.317690,36.521510,NaN,NaN,52.331145,53.523475,2.776467,-376104000.0,40.606430
35,-0.165932,-0.679227,57.975711,NaN,NaN,42.071530,39.305673,36.539816,NaN,NaN,52.421386,53.664763,2.783939,-252136400.0,40.945873
36,-0.022400,-0.547861,61.815806,NaN,NaN,42.278014,39.366021,36.454028,NaN,NaN,56.395015,53.715849,2.796988,-116886800.0,41.657978
37,0.156014,-0.407086,65.717908,NaN,NaN,42.641719,39.462825,36.283931,NaN,NaN,62.381560,57.065987,2.825026,35762000.0,42.481640
38,0.283036,-0.269062,64.530804,NaN,NaN,43.012911,39.594706,36.176501,NaN,NaN,65.108318,61.294964,2.811693,-119950400.0,42.343960
39,0.374218,-0.140406,63.951858,NaN,NaN,43.346781,39.735085,36.123390,NaN,NaN,64.319978,63.936619,2.811646,-271078800.0,42.279888
40,0.382313,-0.035862,57.527272,NaN,NaN,43.527897,39.832998,36.138098,NaN,NaN,59.272713,62.900337,2.801179,-466286800.0,41.539291
41,0.407211,0.052752,59.237562,NaN,NaN,43.735156,39.941134,36.147113,NaN,NaN,52.309014,58.633902,2.782217,-312470800.0,41.826511
42,0.433627,0.128927,60.109606,NaN,NaN,43.918529,40.142561,36.366594,NaN,NaN,42.550392,51.377373,2.769808,-198865200.0,41.971302
43,0.446542,0.192450,59.770928,NaN,NaN,43.949829,40.389606,36.829384,40.596318,40.596318,34.222971,43.027459,2.757050,-294019200.0,41.935692
44,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-420833200.0,41.546417

In [35]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [36]:
indicators_with_price['Next_Adj_Close'] = indicators_with_price['Adj Close'].shift(-1)
indicators_with_price['Signal'] = (indicators_with_price['Next_Adj_Close'] > indicators_with_price['Adj Close']).astype(int)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Next_Adj_Close,Signal
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417,41.999790,1
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790,42.721375,1
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375,43.134396,1
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396,42.719009,0
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009,42.355839,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,188.630005,1
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,191.559998,1
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,193.889999,1
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,195.179993,1
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,NaN,0

In [37]:
indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close'])
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Signal
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417,1
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790,1
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375,1
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396,0
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,1
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,1
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,1
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,1
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,0

In [38]:
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Signal
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417,1
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790,1
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375,1
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396,0
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009,0
5,0.567013,0.443928,58.241621,7.100861,1.143604,43.382885,41.728829,40.074773,40.785715,41.035718,-7.013504,-3.909818,2.715225,-3.124152e+08,42.355839,1
6,0.548495,0.464842,58.592215,7.332888,1.202911,43.261029,41.862705,40.464380,40.813054,41.096606,-20.016654,-8.448451,2.714435,-2.214400e+08,42.405685,0
7,0.515805,0.475034,57.044806,6.516173,0.819328,43.280287,41.922402,40.564517,40.831675,41.148141,-27.991976,-18.340711,2.690141,-3.790588e+08,42.256138,0
8,0.432812,0.466590,50.806350,3.052092,-0.254204,43.245415,41.956465,40.667515,40.825897,41.168690,-36.985499,-28.331377,2.648799,-5.128460e+08,41.610500,0
9,0.361721,0.445616,50.674822,2.976570,-0.055668,43.183913,41.996699,40.809486,40.824632,41.187694,-46.752180,-37.243219,2.644564,-5.914436e+08,41.596272,0
10,0.226728,0.401838,42.776479,-1.895759,-1.685963,43.175295,41.999074,40.822852,40.786315,41.163970,-59.960215,-47.899298,2.611111,-7.396632e+08,40.653915,0
11,0.072555,0.335982,38.805883,-4.708101,-2.298229,43.330932,41.955754,40.580575,40.734082,41.115770,-60.364759,-55.692385,2.604323,-9.056264e+08,40.079475,0
12,-0.123099,0.244166,33.409966,-9.019960,-3.037205,43.669843,41.830423,39.991003,40.665055,41.028464,-57.038039,-59.121004,2.589766,-1.069742e+09,39.151367,1
13,-0.126722,0.169988,48.771960,0.230787,-0.833454,43.603897,41.756840,39.909782,40.646113,41.027642,-35.113454,-50.838751,2.699328,-9.195768e+08,41.009968,0
14,-0.212000,0.093590,42.761440,-4.462381,-1.894436,43.620648,41.637563,39.654479,40.603057,40.980121,-25.755979,-39.302491,2.704914,-1.083267e+09,39.958435,0
15,-0.311617,0.012549,40.504349,-6.346439,-1.669300,43.661172,41.499415,39.337658,40.565119,40.915090,-23.129866,-27.999766,2.693604,-1.249941e+09,39.516922,1
16,-0.361498,-0.062260,42.777711,-4.867444,-0.625511,43.694932,41.413725,39.132519,40.550903,40.866664,-31.638972,-26.841606,2.745530,-1.096347e+09,39.825500,0
17,-0.417287,-0.133266,41.338349,-5.999343,-0.981174,43.709490,41.300620,38.891750,40.528603,40.808785,-33.350038,-29.372959,2.721528,-1.246694e+09,39.564396,1
18,-0.423861,-0.191385,44.466611,-4.030393,0.263973,43.655483,41.200570,38.745656,40.534603,40.771519,-30.537715,-31.842242,2.714498,-1.125582e+09,39.970303,1
19,-0.363211,-0.225750,49.885880,-0.435786,1.262314,43.579269,41.140516,38.701763,40.563292,40.769879,-23.649205,-29.178986,2.737191,-9.871604e+08,40.734619,1
20,-0.289020,-0.238404,51.759458,0.859645,1.436039,43.546088,41.114049,38.682011,40.595929,40.780866,-13.681338,-22.622753,2.743311,-8.794276e+08,41.017082,0
21,-0.311294,-0.252982,45.026021,-3.853599,0.304150,43.457724,41.012456,38.567188,40.602841,40.744736,-15.941607,-17.757384,2.697569,-1.019449e+09,39.967930,1
22,-0.293575,-0.261101,47.789675,-2.010589,2.421566,43.223491,40.894604,38.565718,40.657877,40.727829,-20.848976,-16.823974,2.740926,-9.033780e+08,40.364330,1
23,-0.215755,-0.252031,52.696869,1.419560,4.129101,42.889425,40.794079,38.698733,40.751720,40.745432,-19.855179,-18.881921,2.769122,-7.897436e+08,41.123898,0
24,-0.167663,-0.235158,51.380455,0.543890,2.390759,42.607666,40.704710,38.801755,40.806056,40.753707,-10.385155,-17.029770,2.739621,-8.794700e+08,40.931633,1
25,-0.095884,-0.207303,53.978925,2.354496,3.619328,42.427110,40.653676,38.880242,40.888313,40.779550,0.476718,-9.921205,2.745245,-7.879128e+08,41.335155,1
26,-0.027382,-0.171319,54.880251,2.981765,4.797188,42.237332,40.607152,38.976972,40.997340,40.810468,4.591612,-1.772275,2.736645,-6.874156e+08,41.475208,1
27,0.047239,-0.127607,56.572359,4.145755,4.607296,42.118852,40.581042,39.043233,41.102051,40.851511,13.924978,6.331103,2.724906,-6.011020e+08,41.733936,1
28,0.150988,-0.071888,60.146018,6.689115,3.686314,42.272668,40.615936,38.959203,41.185831,40.916260,22.180899,13.565830,2.744631,-4.946804e+08,42.308369,0
29,0.222977,-0.012915,59.277650,6.212424,3.204464,42.395829,40.646793,38.897756,41.258660,40.973911,28.084392,21.396756,2.719774,-5.776984e+08,42.213413,0
30,0.181405,0.025949,49.567801,0.427657,1.288910,42.421431,40.664951,38.908471,41.287953,40.975830,20.146169,23.470487,2.642225,-7.169336e+08,41.017082,0
31,0.012703,0.023300,39.723960,-6.863875,-1.725685,42.461950,40.627803,38.793655,41.248733,40.902971,-8.291094,13.313156,2.581203,-9.788980e+08,39.336510,0
32,-0.128702,-0.007101,39.156301,-7.330558,-1.706646,42.454273,40.631364,38.808455,41.209946,40.828288,-34.550127,-7.565017,2.567795,-1.124960e+09,39.222591,0
33,-0.281575,-0.061996,36.466798,-9.553036,-2.114937,42.515715,40.514698,38.513681,41.161879,40.732659,-45.877296,-29.572839,2.552946,-1.259728e+09,38.676647,1
34,-0.384693,-0.126535,37.885194,-8.729317,-1.761246,42.577347,40.459035,38.340723,41.121851,40.648772,-39.397567,-39.941663,2.561904,-1.146200e+09,38.845184,1
35,-0.450307,-0.191289,39.061346,-8.061895,-1.965393,42.610304,40.432213,38.254123,41.077183,40.574625,-33.203077,-39.492646,2.563719,-1.034348e+09,38.980480,0
36,-0.532560,-0.259544,36.575172,-9.947394,-3.128498,42.686408,40.367412,38.048417,41.006080,40.483730,-32.805853,-35.135499,2.530740,-1.176971e+09,38.529480,1
37,-0.535264,-0.314688,42.657091,-6.489484,-3.254299,42.697385,40.350560,38.003734,40.932119,40.427890,-28.594961,-31.534630,2.584653,-1.007261e+09,39.227341,1
38,-0.458571,-0.343464,49.472278,-2.193921,-2.205132,42.701496,40.358986,38.016476,40.882002,40.415043,-18.764646,-26.721820,2.619511,-7.929836e+08,40.138828,1
39,-0.251812,-0.325134,59.544954,5.401815,-0.367931,42.852522,40.417853,37.983183,40.873640,40.481573,5.866537,-13.831023,2.739451,-5.268260e+08,41.911957,1
40,-0.080893,-0.276286,59.913619,5.709024,0.448624,42.984210,40.466394,37.948579,40.883836,40.548521,25.969029,4.356973,2.719707,-3.905532e+08,41.987915,1
41,0.185352,-0.183958,66.948284,12.047562,1.808735,43.506950,40.649760,37.792571,40.924944,40.685709,45.736650,25.857405,2.816484,-1.657480e+08,43.635246,1
42,0.417019,-0.063763,68.103514,13.191910,1.979645,44.022548,40.829091,37.635634,40.969936,40.830831,51.666068,41.123916,2.849753,4.057600e+06,43.950947,1
43,0.610626,0.071115,68.887189,13.958459,2.226513,44.489624,40.981006,37.472388,41.020538,40.978892,58.084066,51.828928,2.832203,1.176688e+08,44.162205,1
44,0.780158,0.212924,70.053471,15.087770,2.926739,44.982153,41.158083,37.334013,41.087055,41.134192,59.732775,56.494303,2.821888,2.105136e+08,44.473156,1
45,0.954837,0.361306,72.337954,17.358382,3.109497,45.541691,41.346789,37.151887,41.157726,41.310863,63.227766,60.348202,2.843135,3.224708e+08,45.109287,0
46,1.067127,0.502470,70.769975,16.498689,2.216354,45.997971,41.519915,37.041859,41.208097,41.472057,64.911903,62.624148,2.811891,2.176220e+08,44.937729,0
47,1.134580,0.628892,69.774677,15.967504,1.698498,46.380493,41.674863,36.969233,41.246700,41.621428,64.592740,64.244136,2.785668,1.345068e+08,44.832893,0
48,1.141993,0.731513,65.895629,13.902027,1.706421,46.631591,41.780716,36.929841,41.285482,41.746050,61.526803,63.677148,2.724878,3.972600e+07,44.425430,1
49,1.167862,0.818782,67.853972,15.469610,2.484200,46.941604,41.912047,36.882490,41.341941,41.883561,61.088827,62.402790,2.722356,1.164584e+08,44.840038,0

In [39]:
y = indicators_with_price["Adj Close"]
y_2 = indicators_with_price["SMA"]
y_3 = indicators_with_price["EMA"]
y_4 = indicators_with_price["Upper_BB"]
y_5 = indicators_with_price["Middle_BB"]
y_6 = indicators_with_price["Lower_BB"]
X = np.array(date)

trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



layout = go.Layout(
    title='Stock Price and Volume',
    xaxis=dict(title='Date'),
    yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
    yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
    height=600,
)

fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# Show plot
pyo.iplot(fig)

In [40]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        # Extract a window of data from X
        X_window = self.X[idx : idx + self.window_size]
        
        # Assuming you're predicting the value right after the window
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [41]:
X = indicators_with_price.iloc[:, :-1]
y = indicators_with_price.iloc[:,-2]

signal_true = indicators_with_price.iloc[:,-1]
y

0        41.546417
1        41.999790
2        42.721375
3        43.134396
4        42.719009
           ...
1475    182.679993
1476    188.630005
1477    191.559998
1478    193.889999
1479    195.179993
Name: Adj Close, Length: 1480, dtype: float64

In [42]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1184    1
1185    1
1186    0
1187    1
1188    1
       ..
1475    1
1476    1
1477    1
1478    1
1479    0
Name: Signal, Length: 296, dtype: int64

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
# X_train = X_train.to_numpy()
# y_train = y_train.to_numpy()
len(y_test)

296

In [44]:
# # Get the count of each unique value in the series
# category_counts = y_train.value_counts()
# print(category_counts.index)
# print(category_counts.values)

# # Create bar plot
# plt.bar(["1","0"], category_counts.values)

# # Adding labels and title
# plt.xlabel('Category')
# plt.ylabel('Frequency')
# plt.title('Distribution of Categories')

# # Show plot
# plt.show()

In [45]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

for column in X_train.columns:
    # Initialize a scaler
    scaler = MinMaxScaler()
    
    # Fit on the training data and transform it
    X_train_scaled = scaler.fit_transform(X_train[column].to_numpy().reshape(-1, 1))
    X_train_df[column] = X_train_scaled.flatten()
    
    # Transform the test data using the same scaler
    X_test_scaled = scaler.transform(X_test[column].to_numpy().reshape(-1, 1))
    X_test_df[column] = X_test_scaled.flatten()

    scaler_dict[column] = scaler

    

X_train_df.head(24)

y_train_df = X_train_df["Adj Close"]
y_test_df = X_test_df["Adj Close"]
features = X_train_df.columns
X_test_df

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.473178,0.391410,0.484405,0.368317,0.443981,0.810260,0.788953,0.749683,0.804887,0.832500,0.850519,0.839325,0.765326,0.761787,0.780636
1,0.499847,0.411144,0.517394,0.387563,0.487569,0.813419,0.791684,0.751875,0.804933,0.833706,0.876575,0.853920,0.764804,0.775662,0.793797
2,0.523637,0.432238,0.527280,0.393264,0.448749,0.816205,0.793223,0.752021,0.804433,0.835055,0.895160,0.867699,0.724522,0.788577,0.797684
3,0.523008,0.448973,0.456306,0.359879,0.379729,0.815520,0.792793,0.751879,0.802963,0.835217,0.907286,0.887937,0.685712,0.778442,0.775317
4,0.534244,0.464868,0.497611,0.382098,0.444492,0.813808,0.792104,0.752318,0.802403,0.836117,0.913913,0.901248,0.661728,0.787383,0.790114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,0.331987,0.360467,0.219193,0.330143,0.438975,1.105702,1.104494,1.078159,1.146372,1.152418,0.696648,0.699736,0.263755,0.912203,1.018693
292,0.358007,0.354748,0.456177,0.434230,0.530971,1.099583,1.101858,1.079371,1.147028,1.152792,0.728273,0.697238,0.316961,0.925666,1.059493
293,0.396417,0.358741,0.541661,0.480564,0.534505,1.093074,1.099905,1.082407,1.147733,1.154161,0.814260,0.731128,0.316624,0.937531,1.079584
294,0.440665,0.371807,0.601114,0.515679,0.555950,1.091863,1.099564,1.083019,1.148741,1.156274,0.926300,0.813002,0.323439,0.947909,1.095561
295,0.483036,0.391711,0.631898,0.534629,0.550954,1.092553,1.099746,1.082644,1.149678,1.158738,0.984412,0.904318,0.300461,0.955220,1.104406

In [46]:
scaler_dict

{'MACD': MinMaxScaler(),
 'MACD_signal': MinMaxScaler(),
 'RSI': MinMaxScaler(),
 'CMO': MinMaxScaler(),
 'MOM': MinMaxScaler(),
 'Upper_BB': MinMaxScaler(),
 'Middle_BB': MinMaxScaler(),
 'Lower_BB': MinMaxScaler(),
 'SMA': MinMaxScaler(),
 'EMA': MinMaxScaler(),
 'SLOWK': MinMaxScaler(),
 'SLOWD': MinMaxScaler(),
 'ATR': MinMaxScaler(),
 'OBV': MinMaxScaler(),
 'Adj Close': MinMaxScaler()}

In [47]:
correlation_matrix = X_train_df.corr()

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values,  # Rounded values for display
                    texttemplate="%{text}",
                    textfont={"size":9}  # Adjust text size if necessary
                    ))

# Update the layout
fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  # or any width you desire
    height=1000,  # or any height you desire
)

# Show the figure
pyo.iplot(fig)

In [48]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train_df.to_numpy(), dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test_df.to_numpy(), dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(1)[0])

tensor(0.7283, device='cuda:0')
tensor([[0.4998, 0.4111, 0.5174, 0.3876, 0.4876, 0.8134, 0.7917, 0.7519, 0.8049,
         0.8337, 0.8766, 0.8539, 0.7648, 0.7757, 0.7938],
        [0.5236, 0.4322, 0.5273, 0.3933, 0.4487, 0.8162, 0.7932, 0.7520, 0.8044,
         0.8351, 0.8952, 0.8677, 0.7245, 0.7886, 0.7977],
        [0.5230, 0.4490, 0.4563, 0.3599, 0.3797, 0.8155, 0.7928, 0.7519, 0.8030,
         0.8352, 0.9073, 0.8879, 0.6857, 0.7784, 0.7753],
        [0.5342, 0.4649, 0.4976, 0.3821, 0.4445, 0.8138, 0.7921, 0.7523, 0.8024,
         0.8361, 0.9139, 0.9012, 0.6617, 0.7874, 0.7901],
        [0.5474, 0.4805, 0.5145, 0.3912, 0.4671, 0.8153, 0.7928, 0.7521, 0.8022,
         0.8373, 0.9235, 0.9113, 0.6236, 0.7974, 0.7962],
        [0.5399, 0.4914, 0.4471, 0.3605, 0.4592, 0.8163, 0.7941, 0.7537, 0.8018,
         0.8374, 0.9237, 0.9172, 0.5981, 0.7914, 0.7760],
        [0.5112, 0.4936, 0.3677, 0.3216, 0.4080, 0.8078, 0.7900, 0.7546, 0.8007,
         0.8361, 0.8756, 0.9035, 0.5869, 0.7794, 0.7495],
        [0.4709, 0.4865, 0.3118, 0.2921, 0.3590, 0.8019, 0.7857, 0.7521, 0.7990,
         0.8339, 0.7960, 0.8581, 0.5854, 0.7650, 0.7287],
        [0.4782, 0.4824, 0.4544, 0.3639, 0.4654, 0.8000, 0.7849, 0.7524, 0.7987,
         0.8341, 0.7774, 0.8059, 0.6453, 0.7842, 0.7755],
        [0.4855, 0.4807, 0.4597, 0.3667, 0.5578, 0.8016, 0.7861, 0.7533, 0.7997,
         0.8344, 0.7888, 0.7750, 0.6088, 0.7965, 0.7774],
        [0.4882, 0.4800, 0.4490, 0.3617, 0.6035, 0.8012, 0.7895, 0.7605, 0.8014,
         0.8345, 0.8188, 0.7831, 0.5723, 0.7852, 0.7740],
        [0.4834, 0.4783, 0.4231, 0.3496, 0.5378, 0.7993, 0.7924, 0.7687, 0.8022,
         0.8343, 0.7983, 0.7906, 0.5827, 0.7733, 0.7659],
        [0.4583, 0.4714, 0.3463, 0.3124, 0.4486, 0.7969, 0.7939, 0.7742, 0.8017,
         0.8327, 0.7377, 0.7723, 0.5960, 0.7621, 0.7405],
        [0.4275, 0.4590, 0.3088, 0.2931, 0.4211, 0.7958, 0.7944, 0.7765, 0.8008,
         0.8305, 0.6628, 0.7167, 0.5765, 0.7501, 0.7271],
        [0.4137, 0.4460, 0.3519, 0.3121, 0.4535, 0.7862, 0.7972, 0.7927, 0.8003,
         0.8291, 0.6220, 0.6538, 0.5583, 0.7608, 0.7388],
        [0.4007, 0.4327, 0.3416, 0.3072, 0.5122, 0.7872, 0.7955, 0.7881, 0.8007,
         0.8275, 0.6178, 0.6111, 0.5622, 0.7477, 0.7354],
        [0.4045, 0.4229, 0.4019, 0.3333, 0.5364, 0.7852, 0.7936, 0.7864, 0.8015,
         0.8268, 0.6636, 0.6114, 0.5462, 0.7599, 0.7513],
        [0.4138, 0.4171, 0.4266, 0.3443, 0.5657, 0.7842, 0.7926, 0.7854, 0.8026,
         0.8264, 0.7016, 0.6398, 0.5764, 0.7761, 0.7580],
        [0.4089, 0.4114, 0.3718, 0.3205, 0.5461, 0.7816, 0.7901, 0.7831, 0.8035,
         0.8253, 0.7177, 0.6754, 0.5921, 0.7619, 0.7426],
        [0.3676, 0.3977, 0.2382, 0.2535, 0.4085, 0.7853, 0.7857, 0.7701, 0.8024,
         0.8220, 0.6670, 0.6766, 0.6206, 0.7448, 0.6968],
        [0.3250, 0.3771, 0.2052, 0.2347, 0.4402, 0.7869, 0.7798, 0.7563, 0.8018,
         0.8181, 0.6070, 0.6429, 0.6081, 0.7171, 0.6833],
        [0.2812, 0.3510, 0.1712, 0.2147, 0.3655, 0.7876, 0.7730, 0.7415, 0.8001,
         0.8136, 0.5756, 0.5922, 0.5959, 0.7034, 0.6687],
        [0.2486, 0.3227, 0.1700, 0.2140, 0.3484, 0.7892, 0.7673, 0.7281, 0.7982,
         0.8093, 0.5907, 0.5650, 0.5762, 0.6900, 0.6682],
        [0.2435, 0.2990, 0.2674, 0.2523, 0.3853, 0.7841, 0.7620, 0.7227, 0.7968,
         0.8063, 0.6254, 0.5716, 0.5879, 0.7049, 0.6897],
        [0.2238, 0.2756, 0.2091, 0.2214, 0.3520, 0.7784, 0.7552, 0.7149, 0.7950,
         0.8023, 0.6347, 0.5927, 0.5853, 0.6914, 0.6677],
        [0.2090, 0.2536, 0.2026, 0.2178, 0.3005, 0.7750, 0.7494, 0.7066, 0.7924,
         0.7984, 0.6337, 0.6080, 0.5572, 0.6804, 0.6652],
        [0.1900, 0.2318, 0.1704, 0.2003, 0.2520, 0.7754, 0.7442, 0.6956, 0.7891,
         0.7940, 0.6029, 0.6000, 0.5297, 0.6685, 0.6527],
        [0.1556, 0.2067, 0.1075, 0.1632, 0.1687, 0.7799, 0.7388, 0.6795, 0.7847,
         0.7885, 0.5879, 0.5833, 0.5433, 0.6538, 0.6255],
        [0.1525, 0.1859, 0.2212, 0.2082, 0.2481, 0.7734, 0.7321, 0.6728, 0.7814,
         0.7844, 0.5958, 0.5698, 0.5557, 0.6668, 0.6498],
        [0.1555, 0.1699, 0.2309, 0.2122, 0.3070, 0.7647, 0.7255, 0.6687, 0.7789,
         0.7806, 0.6128, 0.5733, 0.5256, 0.6801, 0.6520],
        [0.1339, 0.1523, 0.1491, 0.1668, 0.1158, 0.7577, 0.7173, 0.6593, 0.7737,
         0.7753, 0.6174, 0.5838, 0.5644, 0.6608, 0.6189],
        [0.1280, 0.1369, 0.1898, 0.1832, 0.1605, 0.7491, 0.7100, 0.6536, 0.7691,
         0.7707, 0.6084, 0.5883, 0.5617, 0.6761, 0.6277],
        [0.1197, 0.1227, 0.1673, 0.1708, 0.1768, 0.7445, 0.7035, 0.6454, 0.7648,
         0.7658, 0.5885, 0.5796, 0.5389, 0.6622, 0.6185],
        [0.1434, 0.1167, 0.3052, 0.2288, 0.3005, 0.7391, 0.6994, 0.6428, 0.7622,
         0.7627, 0.6410, 0.5880, 0.5646, 0.6773, 0.6499],
        [0.1686, 0.1175, 0.3198, 0.2353, 0.3813, 0.7308, 0.6949, 0.6425, 0.7608,
         0.7599, 0.6945, 0.6188, 0.5655, 0.6895, 0.6535],
        [0.1951, 0.1240, 0.3365, 0.2425, 0.3916, 0.7222, 0.6908, 0.6433, 0.7595,
         0.7575, 0.7638, 0.6813, 0.5445, 0.7006, 0.6575],
        [0.2347, 0.1381, 0.4132, 0.2767, 0.4185, 0.7093, 0.6868, 0.6492, 0.7585,
         0.7561, 0.8140, 0.7430, 0.5309, 0.7126, 0.6763],
        [0.2680, 0.1568, 0.4111, 0.2759, 0.4105, 0.6915, 0.6825, 0.6595, 0.7575,
         0.7548, 0.8756, 0.8075, 0.5074, 0.7002, 0.6758],
        [0.3040, 0.1797, 0.4490, 0.2927, 0.4830, 0.6765, 0.6794, 0.6695, 0.7575,
         0.7540, 0.9451, 0.8721, 0.4925, 0.7102, 0.6850],
        [0.3408, 0.2063, 0.4816, 0.3075, 0.3519, 0.6757, 0.6792, 0.6699, 0.7556,
         0.7536, 0.9697, 0.9276, 0.4790, 0.7212, 0.6930],
        [0.3670, 0.2334, 0.4586, 0.2993, 0.3087, 0.6765, 0.6795, 0.6696, 0.7532,
         0.7530, 0.9536, 0.9554, 0.4712, 0.7092, 0.6880],
        [0.3890, 0.2600, 0.4604, 0.3001, 0.3267, 0.6791, 0.6805, 0.6689, 0.7509,
         0.7524, 0.9231, 0.9476, 0.4465, 0.7192, 0.6884],
        [0.4219, 0.2886, 0.5376, 0.3335, 0.3368, 0.6851, 0.6825, 0.6665, 0.7489,
         0.7528, 0.9317, 0.9341, 0.4445, 0.7331, 0.7062],
        [0.4667, 0.3215, 0.6197, 0.3738, 0.3912, 0.6937, 0.6846, 0.6614, 0.7476,
         0.7542, 0.9518, 0.9335, 0.4810, 0.7472, 0.7283]], device='cuda:0')

# Vanilla LSTM

In [49]:
class VanillaLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob):
        super(VanillaLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

# Stacked LSTM

In [50]:
class StackedLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, stateful):
        super(StackedLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size
        self.stateful = stateful
        
        self.hn = None
        self.cn = None

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=self.layer_size,
                            dropout=(dropout_prob if self.layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def reset_hidden_state(self, batch_size=None):
        if batch_size is None or not self.stateful:
            # Reset hidden and cell states to None if batch_size is not provided or if the model is not stateful
            self.hn = None
            self.cn = None
        else:
            # Resize hidden and cell states to match current batch size, preserving the state as much as possible
            self.hn = self._resize_state(self.hn, batch_size)
            self.cn = self._resize_state(self.cn, batch_size)


    def _resize_state(self, state, batch_size):
        if state is None:
            # If state is not initialized, initialize with zeros
            return torch.zeros(self.layer_size, batch_size, self.hidden_size).to(device)
        elif batch_size < state.size(1):
            # If batch size is smaller, truncate the state
            return state[:, :batch_size, :].contiguous()
        elif batch_size > state.size(1):
            # If batch size is larger, pad the state with zeros
            padding_size = batch_size - state.size(1)
            padding = torch.zeros(self.layer_size, padding_size, self.hidden_size).to(device)
            return torch.cat([state, padding], dim=1)
        

    def forward(self, x):
        current_batch_size = x.size(0)

        # Check and adjust the hidden and cell states
        if not self.stateful or self.hn is None or self.hn.size(1) != current_batch_size:
            self.reset_hidden_state(current_batch_size)
        else:
            # Detach the hidden states from the graph to avoid backpropagating through the entire sequence history
            self.hn = self.hn.detach()
            self.cn = self.cn.detach()

        # Ensure that hn and cn are not None and have the correct shape
        h0 = self.hn if self.hn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)
        c0 = self.cn if self.cn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0, c0))

        # Update hidden states if stateful
        if self.stateful:
            self.hn, self.cn = hn.detach(), cn.detach()

        # Process the output of the last time step
        out = self.dropout(out[:, -1, :])  # Add dropout
        out = self.fc(out)  # Fully connected layer

        return out

# Bidirectional LSTM

# 1D CNN-LSTM

In [51]:
class OneDimCNNLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, conv_channels, kernel_size, pool_size, stride):
        super(OneDimCNNLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # Convolutional Layer
        self.conv1 = nn.Conv1d(in_channels=input_dim, out_channels=conv_channels, kernel_size=kernel_size)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool1d(kernel_size=pool_size, stride=pool_size)

        self.conv2 = nn.Conv1d(in_channels=conv_channels, out_channels=conv_channels*2, kernel_size=kernel_size)
        self.relu2 = nn.ReLU()
        self.maxpool2 = nn.MaxPool1d(kernel_size=2, stride=2)


        self.lstm = nn.LSTM(input_size = conv_channels*2, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # CNN in_dim: (batch_size, in_channels, length)
        x = x.transpose(1, 2)

        # Conv layer forward propagate
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.maxpool1(x)

        # x = self.conv2(x)
        # x = self.relu2(x)
        # x = self.maxpool2(x)

        # LSTM in_dim: (batch_size, seq_len, input_size)
        x = x.transpose(1, 2)

        assert x.size(-1) == self.lstm.input_size, f"Mismatch in LSTM input size. Expected: {self.lstm.input_size}, Got: {x.size(-1)}"

        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

In [52]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device, model_type):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model_type = model_type
        self.model = None
        self.optimizer = None
        self.criterion = nn.MSELoss()

    
    def train_validate(self, config, trial):

        if self.model_type == "Vanilla LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=1).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.view(-1, 1)  # Reshape target to have an extra dimension


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    loss = loss.mean()
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.view(-1, 1)

                        preds = self.model(data)
                        loss = self.criterion(preds, target)
                        loss = loss.mean()

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
        if self.model_type == "Vanilla LSTM":

            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=1).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1, 1)  # Reshape target to have an extra dimension

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                loss = loss.mean()
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1, 1)
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                all_preds.extend(preds.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [53]:
model_type = "1D CNN-LSTM"

def objective(trial):
    if model_type == "Vanilla LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.15),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 10, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9)
        }

    elif model_type == "Stacked LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "num_layers": trial.suggest_int("num_layers", 1, 5)
        }

    elif model_type == "1D CNN-LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "conv_channels": trial.suggest_int("conv_channels", 16, 128),
            "kernel_size": trial.suggest_int("kernel_size", 2, 6),
            "num_layers": trial.suggest_int("num_layers", 1, 5),
            "pool_size": trial.suggest_int("pool_size", 2, 5),
            "stride": trial.suggest_int("stride", 1, 4)
        }

    trainer = ModelActioner(train_data, test_data, device, model_type)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [54]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=25, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    # Optionally, you can include additional information in the progress bar
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=25, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-26 23:14:11,986] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/25 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.013532064964161499, val_loss: 0.003291820022767704
epochs 2/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.003468603718609206, val_loss: 0.0026245382975933975
epochs 3/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0018059582841631614, val_loss: 0.0012419183671131338
epochs 4/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0019040302630808008, val_loss: 0.002709260008812539
epochs 5/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0019181415408016428, val_loss: 0.0018479339374033244
epochs 6/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0016153031996892471, val_loss: 0.0014252280228232083
epochs 7/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001671807416469643, val_loss: 0.002134815424582676
epochs 8/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0019040402637696579, val_loss: 0.0024573790528321345
epochs 9/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0016698528798051962, val_loss: 0.0015875098163776688
epochs 10/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015459076979344613, val_loss: 0.001396564232479585
epochs 11/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001694715700700487, val_loss: 0.0017536267806702343
epochs 12/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015487640293462104, val_loss: 0.0017066926107202705
epochs 13/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015891226798933195, val_loss: 0.0014404105702660193
epochs 14/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0016080061028907566, val_loss: 0.001998309528847274
epochs 15/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0017061856691725553, val_loss: 0.0024986676222301628
epochs 16/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001551498547135117, val_loss: 0.0013031925398727731
epochs 17/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0018379122288407464, val_loss: 0.001586594449595156
epochs 18/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001628208929354227, val_loss: 0.0026361276968504843
epochs 19/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001681452332138035, val_loss: 0.0015337029286648
epochs 20/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001601032348423216, val_loss: 0.0015877517666300072
epochs 21/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015699333223318191, val_loss: 0.002390290564538813
epochs 22/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015701119144643217, val_loss: 0.0016877606137361573
epochs 23/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015025581698864699, val_loss: 0.0016815332573299345
epochs 24/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015268234529924628, val_loss: 0.001681878759011038
epochs 25/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001492963341603938, val_loss: 0.00175506572643491
epochs 26/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015499172333971057, val_loss: 0.0019822241309540053
epochs 27/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0014438497129288551, val_loss: 0.0015816112618746334
epochs 28/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0014961058231021621, val_loss: 0.0017201963468993966
epochs 29/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0016272078758399738, val_loss: 0.0018243741697484726
epochs 30/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015392531463141112, val_loss: 0.0014046178874866056
epochs 31/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0016738091203335084, val_loss: 0.0015432764806686656
epochs 32/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001667328883501652, val_loss: 0.0018952768256177048
epochs 33/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015944168247331522, val_loss: 0.0016945702097329654
epochs 34/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001485842025814284, val_loss: 0.0017880342232896702
epochs 35/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0014787889410447525, val_loss: 0.0016643343597503477
epochs 36/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015478175256009165, val_loss: 0.001901164074354854
epochs 37/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015287622859958853, val_loss: 0.0020033866877814657
epochs 38/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015694358202285672, val_loss: 0.0018577020878805534
epochs 39/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015059508757028534, val_loss: 0.001697226896220328
epochs 40/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015062742487842978, val_loss: 0.0018748032076186256
epochs 41/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015692051830946616, val_loss: 0.0017383881593368163
epochs 42/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015738197455280707, val_loss: 0.0015589522818213722
epochs 43/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015274078223707253, val_loss: 0.0022218069490535478
epochs 44/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015508725087305434, val_loss: 0.001345604307042729
epochs 45/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001587908630455403, val_loss: 0.0016857070710485508
epochs 46/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0014919590584835723, val_loss: 0.0020763336539905714
epochs 47/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0014705646158147015, val_loss: 0.0020932137659799895
epochs 48/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015322513596497868, val_loss: 0.0015026589824916109
epochs 49/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015670788014846805, val_loss: 0.0014599056301736518
epochs 50/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015757024882508343, val_loss: 0.002282390111787735
epochs 51/145
Epoch 00051: reducing learning rate of group 0 to 8.6387e-04.
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015886941716369046, val_loss: 0.0017463236845000401
epochs 52/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015630660241616793, val_loss: 0.0016711688098056535
epochs 53/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015352083651937153, val_loss: 0.0016274843450733705
epochs 54/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015223695259345205, val_loss: 0.001654441297470935
epochs 55/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001493902573680603, val_loss: 0.0017205659373614349
epochs 56/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014430921016211965, val_loss: 0.0017876639815145418
epochs 57/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001538827509839872, val_loss: 0.001800758693073141
epochs 58/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001480296282342782, val_loss: 0.0018328759102395882
epochs 59/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015435268397835133, val_loss: 0.0018436654795598434
epochs 60/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014275527847195533, val_loss: 0.0018237672476588112
epochs 61/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015273564029484987, val_loss: 0.0018157558295091515
epochs 62/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014401482798061089, val_loss: 0.0017273197722572245
epochs 63/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014794948798800378, val_loss: 0.0016673509454305628
epochs 64/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014868859511089365, val_loss: 0.001657425552778142
epochs 65/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014617616414876753, val_loss: 0.0017110239224214304
epochs 66/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001527189925362013, val_loss: 0.001824278276609747
epochs 67/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014680888231132965, val_loss: 0.001897362035417341
epochs 68/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001470501923713049, val_loss: 0.0019094123645979715
epochs 69/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014936186226182863, val_loss: 0.0018381035672255645
epochs 70/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.00146683561922002, val_loss: 0.0017329249883340182
epochs 71/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001506287099082807, val_loss: 0.001661432642753138
epochs 72/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014888707462600186, val_loss: 0.001628993887233695
epochs 73/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015197851756391556, val_loss: 0.0015832030101017537
epochs 74/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001505101178650205, val_loss: 0.001609700837932331
epochs 75/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001495750166941434, val_loss: 0.0017027756107333852
epochs 76/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014291134460731165, val_loss: 0.0017445282943203654
epochs 77/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014062138433617196, val_loss: 0.0017102447811722461
epochs 78/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014862108770390286, val_loss: 0.0016657373282788811
epochs 79/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014492773861428233, val_loss: 0.0016573805435511626
epochs 80/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015178872633872455, val_loss: 0.0016822548400868024
epochs 81/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014407003420944277, val_loss: 0.0017591004308901335
epochs 82/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001463304263368053, val_loss: 0.0017729166625557761
epochs 83/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014735337941123076, val_loss: 0.0017278813420010632
epochs 84/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014458436996823078, val_loss: 0.0017294116731806609
epochs 85/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014693150125247867, val_loss: 0.0017069571317590185
epochs 86/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014851269011973943, val_loss: 0.001672889980315966
epochs 87/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015564424966118837, val_loss: 0.001697975368312511
epochs 88/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001463829448422123, val_loss: 0.0016784350614455577
epochs 89/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015229508734161132, val_loss: 0.0016501402853081298
epochs 90/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001492419971251174, val_loss: 0.0016877003130503
epochs 91/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014652647788783437, val_loss: 0.0017337435936114114
epochs 92/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015655742149407927, val_loss: 0.0017067945755307415
epochs 93/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015410753979506952, val_loss: 0.00172219600798072
epochs 94/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015196756729365963, val_loss: 0.0017820052165342004
epochs 95/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014967916404681379, val_loss: 0.0019161091682403104
epochs 96/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0014903109251080376, val_loss: 0.0019631631721399334
epochs 97/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.0015055841502831563, val_loss: 0.0018387964320074964
epochs 98/145
Current Learning Rate: 0.0008638713093116579
train_loss: 0.001439421810209751, val_loss: 0.0016623976631212588
epochs 99/145
Epoch 00099: reducing learning rate of group 0 to 8.6875e-05.
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001523284327030476, val_loss: 0.001564270257949829
epochs 100/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001488457574190474, val_loss: 0.00156119434395805
epochs 101/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001510484906305608, val_loss: 0.0015670260867888205
epochs 102/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015273699169292261, val_loss: 0.00158095981276251
epochs 103/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014505480054618888, val_loss: 0.0016064988859733076
epochs 104/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001490479781243362, val_loss: 0.0016290893091967231
epochs 105/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015654157142547009, val_loss: 0.0016493017828140995
epochs 106/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015039972213440036, val_loss: 0.0016800143958167419
epochs 107/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014721685634484808, val_loss: 0.001709917007553342
epochs 108/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014623726564949673, val_loss: 0.0017300746789643247
epochs 109/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014611363643780352, val_loss: 0.0017452213380142654
epochs 110/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001529147452674806, val_loss: 0.001760387910824073
epochs 111/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014860870267607664, val_loss: 0.0017692800295710759
epochs 112/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015005976133244602, val_loss: 0.0017799785100291237
epochs 113/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014564282077021505, val_loss: 0.0017871313716137879
epochs 114/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015206197442143763, val_loss: 0.001789627854687799
epochs 115/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014929495099319243, val_loss: 0.0017878763708531072
epochs 116/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001443213890429194, val_loss: 0.0017825497222427084
epochs 117/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014108117884270063, val_loss: 0.0017689756436371489
epochs 118/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001501190984670661, val_loss: 0.0017553630474905827
epochs 119/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014643777560099567, val_loss: 0.0017430386457004045
epochs 120/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001421670317282214, val_loss: 0.0017345324759126494
epochs 121/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015317908990638035, val_loss: 0.0017304118410193998
epochs 122/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014382159711155845, val_loss: 0.0017201931344492263
epochs 123/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015060580782837382, val_loss: 0.0017070974578688803
epochs 124/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014581662189141896, val_loss: 0.0016984322647515097
epochs 125/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.00145577584319797, val_loss: 0.0017024660084739719
epochs 126/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001469150536669124, val_loss: 0.0017119098699798709
epochs 127/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014640344129140048, val_loss: 0.0017203888960035615
epochs 128/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015246551391962719, val_loss: 0.0017297886618364013
epochs 129/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015387162915430964, val_loss: 0.0017395247135458417
epochs 130/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014690132260224537, val_loss: 0.00174507437776284
epochs 131/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015005757082498779, val_loss: 0.0017488463616341745
epochs 132/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014521080387854262, val_loss: 0.0017503121622691028
epochs 133/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014830403091189892, val_loss: 0.0017491215656168368
epochs 134/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015270752936454588, val_loss: 0.001748042067169751
epochs 135/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014688187986489777, val_loss: 0.0017486161374683051
epochs 136/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014950687108610413, val_loss: 0.0017469660342229825
epochs 137/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014415370677230194, val_loss: 0.0017520670408358503
epochs 138/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014597825871437396, val_loss: 0.001756633963975075
epochs 139/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014809925556427946, val_loss: 0.0017699732071425963
epochs 140/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015033748178546757, val_loss: 0.0017810676326534074
epochs 141/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0015293043566328521, val_loss: 0.0017863671865167195
epochs 142/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014239752346551732, val_loss: 0.001786296420706142
epochs 143/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014574762948445584, val_loss: 0.0017869106408110575
epochs 144/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.0014692943543195725, val_loss: 0.0017855362684809065
epochs 145/145
Current Learning Rate: 8.687492630029715e-05
train_loss: 0.001431065817412577, val_loss: 0.0017947919942487619
Starting fold 2:
epochs 1/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.002593599961715211, val_loss: 0.04222688133779325
epochs 2/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015199056183184056, val_loss: 0.0460745667744624
epochs 3/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015770383004564791, val_loss: 0.04892265837835638
epochs 4/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0016062497703579108, val_loss: 0.04478744880149239
epochs 5/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015117507112384037, val_loss: 0.04486234491985095
epochs 6/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015240723870719147, val_loss: 0.0439697911472697
epochs 7/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001580727215868568, val_loss: 0.046531169351778534
epochs 8/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015490820649766215, val_loss: 0.047536330689725126
epochs 9/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015572443812791454, val_loss: 0.04421917192245785
epochs 10/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0014899838250130415, val_loss: 0.04366007496259714
epochs 11/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0014579473048031918, val_loss: 0.04751042333480559
epochs 12/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.0015345622865042012, val_loss: 0.048171520252761085
epochs 13/145
Current Learning Rate: 0.008590207449180714
train_loss: 0.001501570460018947, val_loss: 0.042438078867761714
epochs 14/145
Current Learning Rate: 0.008590207449180714

[I 2024-01-26 23:15:26,143] Trial 0 finished with value: 0.14683456295664468 and parameters: {'batch_size': 61, 'epochs': 145, 'hidden_size': 66, 'learning_rate': 0.008590207449180714, 'dropout_prob': 0.15103820415417538, 'weight_decay': 7.470201259818449e-05, 'lr_step_size': 47, 'gamma': 0.1005646620785682, 'conv_channels': 22, 'kernel_size': 5, 'num_layers': 5, 'pool_size': 4, 'stride': 4}. Best is trial 0 with value: 0.14683456295664468.

Current Learning Rate: 8.687492630029715e-05
train_loss: 0.08310969182143085, val_loss: 0.20294268719459835
Mean validation loss: 0.14683456295664468
Starting fold 1:
epochs 1/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0015155393336164324, val_loss: 0.0015949612924535024
epochs 2/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0013538135399453735, val_loss: 0.001618422370551056
epochs 3/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0013844019451521728, val_loss: 0.0016480455291457475
epochs 4/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00135016363285678, val_loss: 0.0016792476508080175
epochs 5/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0012082627876416634, val_loss: 0.0015383518325459017
epochs 6/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0012280011537337773, val_loss: 0.0016219987331791536
epochs 7/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0011784691988539538, val_loss: 0.0015481306546318689
epochs 8/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.001095113588962704, val_loss: 0.0016009654188038488
epochs 9/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0010368009624806675, val_loss: 0.0014391396298857504
epochs 10/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0009481963854724247, val_loss: 0.0014653326594270765
epochs 11/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0008757359274712049, val_loss: 0.001494966664253489
epochs 12/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007836612394863838, val_loss: 0.0013799301250592658
epochs 13/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006581189919655261, val_loss: 0.0014824321812116786
epochs 14/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0005659654062535417, val_loss: 0.0014534405236573595
epochs 15/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0004957507502312135, val_loss: 0.001482640999663425
epochs 16/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0004800478789930869, val_loss: 0.00159110194255941
epochs 17/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00039594079778333636, val_loss: 0.0014460011042262378
epochs 18/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003732504356824058, val_loss: 0.0016201510473987774
epochs 19/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00037764184127904866, val_loss: 0.0014312106503271743
epochs 20/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00040166492475882955, val_loss: 0.0016404959532481274
epochs 21/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000387120820232667, val_loss: 0.0013978575846474422
epochs 22/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003396706643367284, val_loss: 0.0016538825854168911
epochs 23/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003928740628333272, val_loss: 0.0014998637066271745
epochs 24/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003290232565057905, val_loss: 0.0014844170673505256
epochs 25/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00037294954128906524, val_loss: 0.0014989004231450197
epochs 26/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00038881115768545944, val_loss: 0.0014221048779099396
epochs 27/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00035087934229522945, val_loss: 0.0016231366482220197
epochs 28/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003872955512059362, val_loss: 0.0013936269403386273
epochs 29/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000329906022249672, val_loss: 0.0014995638354632415
epochs 30/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00034450836614460535, val_loss: 0.0016039146441280058
epochs 31/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00031342153287321136, val_loss: 0.0015109944475912734
epochs 32/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00031889348051902886, val_loss: 0.0014250634875344604
epochs 33/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000344946472844305, val_loss: 0.0015743075771943518
epochs 34/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00035707056216013276, val_loss: 0.0014107871187948866
epochs 35/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000330555858396876, val_loss: 0.0015179205207938426
epochs 36/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003358311451799971, val_loss: 0.0014943876744885193
epochs 37/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003420945318219693, val_loss: 0.0014922807924449444
epochs 38/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0002993704331426048, val_loss: 0.0014343668290070796
epochs 39/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003580584445061456, val_loss: 0.0016267463711923675
epochs 40/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00035731759363491283, val_loss: 0.001329833342644729
epochs 41/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000350834608482393, val_loss: 0.0016617929317841403
epochs 42/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00036043090849967774, val_loss: 0.0013482311127805395
epochs 43/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003209836168312713, val_loss: 0.0015594075029519829
epochs 44/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003062524324233987, val_loss: 0.0014369305174209569
epochs 45/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000326842157243702, val_loss: 0.0013799919293409116
epochs 46/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00034188640818588045, val_loss: 0.001572555477583879
epochs 47/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00031975335594707806, val_loss: 0.001347546757345921
epochs 48/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00033294326092704737, val_loss: 0.0015377067299069543
epochs 49/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00031925905342703977, val_loss: 0.0015053746596861042
epochs 50/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00034306981251575053, val_loss: 0.0014525773922765726
epochs 51/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00033607519795431903, val_loss: 0.0014302019103381194
epochs 52/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00030787683085930584, val_loss: 0.0014700830448418855
epochs 53/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003114609957648147, val_loss: 0.0014414218744557155
epochs 54/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003515030386073417, val_loss: 0.001465450854677903
epochs 55/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00030197039289449, val_loss: 0.0013627506094053387
epochs 56/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003281264624092728, val_loss: 0.0015246435901836346
epochs 57/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00033396969558548574, val_loss: 0.0014228582345439415
epochs 58/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0002994903115139, val_loss: 0.0014930504067849956
epochs 59/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003164944033702149, val_loss: 0.0014827462574957234
epochs 60/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003167071961797774, val_loss: 0.0014466311022835342
epochs 61/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00035282843439888797, val_loss: 0.001428220543618265
epochs 62/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00032616051152887707, val_loss: 0.001464890539155979
epochs 63/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003084987968721084, val_loss: 0.0014612259355520731
epochs 64/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00030360404542941404, val_loss: 0.001417832750532972
epochs 65/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00031876117695662143, val_loss: 0.001421863990100591
epochs 66/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00030404874675073906, val_loss: 0.0014882157850814493
epochs 67/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003409045950607642, val_loss: 0.0014241530351634872
epochs 68/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000341314599714487, val_loss: 0.0014078628823259158
epochs 69/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00032714925565462756, val_loss: 0.001480720295129638
epochs 70/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003273502148467263, val_loss: 0.0014155420928115123
epochs 71/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00033505946262984683, val_loss: 0.0014620893916703368
epochs 72/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00034632419548487586, val_loss: 0.0013537497700829254
epochs 73/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003227144470560904, val_loss: 0.0015204973445322953
epochs 74/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000314723984583428, val_loss: 0.001329022101861866
epochs 75/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003332122994929944, val_loss: 0.0014767604610441546
epochs 76/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0002979580763310782, val_loss: 0.001372381826666625
epochs 77/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003025609425477389, val_loss: 0.0014607874027110243
epochs 78/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003159316688604457, val_loss: 0.0014146124110802224
epochs 79/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00031552596820371326, val_loss: 0.0014143456128965083
epochs 80/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0002680467129194815, val_loss: 0.0015052113228624588
epochs 81/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00030144875054247675, val_loss: 0.001368389591133516
epochs 82/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003258785134867618, val_loss: 0.0014854549418056482
epochs 83/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003060994050955694, val_loss: 0.0013988129230902383
epochs 84/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000297248357674107, val_loss: 0.0014081099646558104
epochs 85/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003082499957312585, val_loss: 0.0014865691430474583
epochs 86/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003162893972139021, val_loss: 0.001348270780995096
epochs 87/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003001569231089793, val_loss: 0.0014844605674673068
epochs 88/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00028930847888420286, val_loss: 0.001365237649971325
epochs 89/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00029504553715110215, val_loss: 0.0014693737667250005
epochs 90/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00030224054935388265, val_loss: 0.001389058573955768
epochs 91/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00029784132830651573, val_loss: 0.0014127542289268029
epochs 92/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0002869739065461449, val_loss: 0.00144888764786485
epochs 93/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00029758639039324694, val_loss: 0.0013659418266462652
epochs 94/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00029702919725279665, val_loss: 0.0014374275642790293
epochs 95/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00030871234638126275, val_loss: 0.001429741496318265
epochs 96/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0002903249485442709, val_loss: 0.0013916093071824627
epochs 97/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003107498715460104, val_loss: 0.0013619935336081606
epochs 98/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0002875002278750272, val_loss: 0.0014937826162694317
epochs 99/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00029285901753035816, val_loss: 0.0012994361790142168
epochs 100/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00029510261956602337, val_loss: 0.0015246574932366217
epochs 101/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00031974308597120015, val_loss: 0.0013597347957425212
epochs 102/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00032636048502019164, val_loss: 0.0013362767493450328
epochs 103/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0003419162677968607, val_loss: 0.0015414740436857468
epochs 104/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00033332868969362033, val_loss: 0.0012826862169037525
Starting fold 2:
epochs 1/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0008442628944880868, val_loss: 0.037382165224928605
epochs 2/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007583507048701377, val_loss: 0.035290244986352165
epochs 3/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007590788918988486, val_loss: 0.035425651151882974
epochs 4/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007692764978855848, val_loss: 0.034507632373194944
epochs 5/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007443161583260486, val_loss: 0.034938813902829824
epochs 6/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007359302137047053, val_loss: 0.03431338563953575
epochs 7/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007426406073040868, val_loss: 0.0326773779956918
epochs 8/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007353503734951741, val_loss: 0.0337705827073047
epochs 9/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007018304289024519, val_loss: 0.0345933836149542
epochs 10/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007158343073617863, val_loss: 0.033712180821519146
epochs 11/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0007036935202593572, val_loss: 0.03148109426623896
epochs 12/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006820611747618961, val_loss: 0.03144185339149676
epochs 13/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006867616774367266, val_loss: 0.03137552255862638
epochs 14/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006792854444172821, val_loss: 0.029721010692025485
epochs 15/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006758365412487796, val_loss: 0.031625455813972574
epochs 16/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006768866662720316, val_loss: 0.03093150779604912
epochs 17/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006877121858690914, val_loss: 0.031780120142196354
epochs 18/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006873687582188531, val_loss: 0.02994036623521855
epochs 19/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006745562128918736, val_loss: 0.0286800510201015
epochs 20/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006567295487528961, val_loss: 0.030636309557839445
epochs 21/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006502791405900529, val_loss: 0.03094822662441354
epochs 22/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006651664762390091, val_loss: 0.031300457919898786
epochs 23/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006764118492260183, val_loss: 0.03099519808433558
epochs 24/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006561099095147495, val_loss: 0.02889676395999758
epochs 25/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006319123969756459, val_loss: 0.027925779141093555
epochs 26/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006301002301226713, val_loss: 0.02937132676965312
epochs 27/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006161673766511836, val_loss: 0.029258267699103606
epochs 28/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006480337996771069, val_loss: 0.029451341927051546
epochs 29/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006237724710157828, val_loss: 0.02901678491187723
epochs 30/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006329011472285186, val_loss: 0.025246257531015497
epochs 31/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006556080090568254, val_loss: 0.027688538439963994
epochs 32/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006381264042207285, val_loss: 0.026530169676008977
epochs 33/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006402358486268081, val_loss: 0.028290361362068278
epochs 34/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000616732984168553, val_loss: 0.0288796014691654
epochs 35/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006148761564154962, val_loss: 0.0267080871682418
epochs 36/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006276980324305202, val_loss: 0.026590777561068535
epochs 37/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006323137253179754, val_loss: 0.02694229646340797
epochs 38/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006261781274684166, val_loss: 0.03082422594490804
epochs 39/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006177026006442152, val_loss: 0.027048609817498608
epochs 40/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006330528982767933, val_loss: 0.0257379195996021
epochs 41/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006095994184234817, val_loss: 0.028266253243935734
epochs 42/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0005914418418940745, val_loss: 0.027441690705324474
epochs 43/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000581104022842881, val_loss: 0.027625996776317295
epochs 44/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000570151959178283, val_loss: 0.02756898056127523
epochs 45/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006131786295506907, val_loss: 0.024712217501119564
epochs 46/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006240798399391535, val_loss: 0.029222158970017183
epochs 47/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006208521289456832, val_loss: 0.030015804344101955
epochs 48/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00060273724191479, val_loss: 0.025847879914860976
epochs 49/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0005896494190796818, val_loss: 0.026284202070612658
epochs 50/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.000592052666347866, val_loss: 0.025376462916794577
epochs 51/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0006157615693825248, val_loss: 0.028461669895209766
epochs 52/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0005890853678513514, val_loss: 0.028107788394156254
epochs 53/104
Current Learning Rate: 0.00021816996161030182

[I 2024-01-26 23:16:19,728] Trial 1 finished with value: 0.010049154356568352 and parameters: {'batch_size': 32, 'epochs': 104, 'hidden_size': 89, 'learning_rate': 0.00021816996161030182, 'dropout_prob': 0.1272723440657144, 'weight_decay': 0.0005261517371819727, 'lr_step_size': 34, 'gamma': 0.6936855452706332, 'conv_channels': 56, 'kernel_size': 5, 'num_layers': 2, 'pool_size': 3, 'stride': 2}. Best is trial 1 with value: 0.010049154356568352.

Current Learning Rate: 0.00010498330605135981
train_loss: 0.001596660795376489, val_loss: 0.01001184545457363
Mean validation loss: 0.010049154356568352
Starting fold 1:
epochs 1/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.01769996691299112, val_loss: 0.008575488656367126
epochs 2/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0026853622353978845, val_loss: 0.0015756669870920872
epochs 3/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0036929918208012456, val_loss: 0.001284179755633599
epochs 4/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.002065889887805832, val_loss: 0.002604678415350224
epochs 5/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0021332421879235067, val_loss: 0.003120950979523753
epochs 6/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0018304885267034958, val_loss: 0.002016813283492076
epochs 7/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0017016016853679168, val_loss: 0.0014345025962316676
epochs 8/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0017553795631484765, val_loss: 0.0014818105809880715
epochs 9/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015550648499476282, val_loss: 0.0019853688727476094
epochs 10/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0017607540897044696, val_loss: 0.002186293947191811
epochs 11/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016870175108411594, val_loss: 0.002012222284745229
epochs 12/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016454683678028615, val_loss: 0.0016804657227016593
epochs 13/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015024489931468117, val_loss: 0.0017373441926840888
epochs 14/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016152143257817156, val_loss: 0.0018843835072689934
epochs 15/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0017440730350484189, val_loss: 0.0019235185494548396
epochs 16/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015544309182778785, val_loss: 0.0016358650424272607
epochs 17/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001725430912828367, val_loss: 0.0016304525583492298
epochs 18/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015988394005322143, val_loss: 0.0019168995063457833
epochs 19/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0017311141133847597, val_loss: 0.0018752226924621746
epochs 20/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001624616584740579, val_loss: 0.0017687455567188168
epochs 21/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016771339799130434, val_loss: 0.0017226753352013859
epochs 22/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015352450801353705, val_loss: 0.0020099629991148647
epochs 23/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001563707286933143, val_loss: 0.0017520361016259381
epochs 24/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015699683222919702, val_loss: 0.0017335015974056563
epochs 25/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001640664857175005, val_loss: 0.0017774205348503433
epochs 26/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015788172261397306, val_loss: 0.0016877220330857917
epochs 27/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016550608469467413, val_loss: 0.0016450360405111783
epochs 28/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016545104929000924, val_loss: 0.00201075296530402
epochs 29/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015183055123902465, val_loss: 0.0018126517828357847
epochs 30/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0017236258111600028, val_loss: 0.0015301973470119073
epochs 31/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016032267692743947, val_loss: 0.001825913075529235
epochs 32/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0017196585399735914, val_loss: 0.0019246158759893947
epochs 33/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015911080090231016, val_loss: 0.0017898364960657138
epochs 34/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001619953479568817, val_loss: 0.001582165736410963
epochs 35/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001614259301047576, val_loss: 0.0016523961725301648
epochs 36/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015545990550890564, val_loss: 0.0020015388469848978
epochs 37/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016309363583691026, val_loss: 0.0015987224631795758
epochs 38/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015861958976050741, val_loss: 0.001789240193504252
epochs 39/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001552708111213226, val_loss: 0.0017414624018496588
epochs 40/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016063506935576075, val_loss: 0.0018068648133377889
epochs 41/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001473936062967895, val_loss: 0.0017314427434221694
epochs 42/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0014765903892877854, val_loss: 0.001758758424732246
epochs 43/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016022083116695284, val_loss: 0.0018925930005743315
epochs 44/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015932142942849743, val_loss: 0.0016601987440433158
epochs 45/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015132507542148232, val_loss: 0.001672134507986668
epochs 46/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0014272368280217052, val_loss: 0.0017518506630470878
epochs 47/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015815637650360402, val_loss: 0.0017710104578566787
epochs 48/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015800174141890908, val_loss: 0.0018139654770493508
epochs 49/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015802688596427048, val_loss: 0.0017715132133545059
epochs 50/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015025997166766931, val_loss: 0.0015973290673604137
epochs 51/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001571162975099134, val_loss: 0.0016817628847141015
epochs 52/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015702179265453626, val_loss: 0.0018010234435726154
epochs 53/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0014746769012785271, val_loss: 0.0019256249094676031
epochs 54/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001510565306403135, val_loss: 0.0017446051927675543
epochs 55/104
Epoch 00055: reducing learning rate of group 0 to 1.4889e-04.
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0016269880886140623, val_loss: 0.0020767649292553728
epochs 56/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0017386379320860693, val_loss: 0.0020007580524849656
epochs 57/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015206295335175176, val_loss: 0.001861962423610844
epochs 58/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015230250030167792, val_loss: 0.0017254471631818697
epochs 59/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015353311919362137, val_loss: 0.0017105243913216614
epochs 60/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0017220421014108548, val_loss: 0.0017212995058415751
epochs 61/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0014937113026941293, val_loss: 0.0017372310449565319
epochs 62/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.001596947547391449, val_loss: 0.001710854941292813
epochs 63/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015042825356910102, val_loss: 0.0017276656587216022
epochs 64/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0014667678477340623, val_loss: 0.0017655276809819044
epochs 65/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0014560080243666705, val_loss: 0.0017878567312819588
epochs 66/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.001552490696409031, val_loss: 0.0017664193665902865
epochs 67/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.001495705612346922, val_loss: 0.0018333938340411374
epochs 68/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015917104203253985, val_loss: 0.0018500087586672683
epochs 69/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015612825236626362, val_loss: 0.0017706140679748434
epochs 70/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015866566008250964, val_loss: 0.0017617763142640653
epochs 71/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0016655352113670425, val_loss: 0.0017421684093087127
epochs 72/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015837793410020439, val_loss: 0.0017409318892628346
epochs 73/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.001552344875802335, val_loss: 0.0017555948984073965
epochs 74/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015529907333027375, val_loss: 0.0017644719588325213
epochs 75/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.001537402259725097, val_loss: 0.0017662001234528266
epochs 76/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0016794954555256194, val_loss: 0.0017946383364400582
epochs 77/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015165293576980107, val_loss: 0.001767660760761876
epochs 78/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0014339870283086049, val_loss: 0.0017635590776703075
epochs 79/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.001546697142092805, val_loss: 0.0017604782981307883
epochs 80/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.001621134049798313, val_loss: 0.0017087564681117471
epochs 81/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015824169533229188, val_loss: 0.0016359541399747525
epochs 82/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015274578962769163, val_loss: 0.001726003532837096
epochs 83/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015059546506228415, val_loss: 0.00182824308653117
epochs 84/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015858353973415337, val_loss: 0.001983287099650816
epochs 85/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015574381362009598, val_loss: 0.0019742918200790884
epochs 86/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015898718584426924, val_loss: 0.0018947847187519074
epochs 87/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0016267404621957164, val_loss: 0.001760060365900005
epochs 88/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.001604262026222913, val_loss: 0.0017398996634016696
epochs 89/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0016110862200883658, val_loss: 0.0017747786447503849
epochs 90/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0016181459809702478, val_loss: 0.0018016668404207418
epochs 91/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015889163937811788, val_loss: 0.0018617881167876094
epochs 92/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015057507743078628, val_loss: 0.0018170234134518787
epochs 93/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0014566335251162711, val_loss: 0.001808087868419917
epochs 94/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015009047157180152, val_loss: 0.0017641530874626416
epochs 95/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015681124880517784, val_loss: 0.0017133078461292347
epochs 96/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.001490842156406296, val_loss: 0.0017088954949653463
epochs 97/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0016615430481339757, val_loss: 0.001778062485084918
epochs 98/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.00155657680067969, val_loss: 0.001825003694791935
epochs 99/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0016601408292588435, val_loss: 0.001780924274537124
epochs 100/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015317380367042986, val_loss: 0.0017837952467073736
epochs 101/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015865642614172478, val_loss: 0.001732262473945555
epochs 102/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015768767383537794, val_loss: 0.0017081790640460033
epochs 103/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015091530451747147, val_loss: 0.001728215641771002
epochs 104/104
Current Learning Rate: 0.00014888517215081145
train_loss: 0.0015656227834130588, val_loss: 0.001701721811274949
Starting fold 2:
epochs 1/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001920215458315062, val_loss: 0.04856687309710603
epochs 2/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016457435148032873, val_loss: 0.0457782272837664
epochs 3/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001537640329058233, val_loss: 0.043856603103248695
epochs 4/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001556090141744598, val_loss: 0.04515753980529936
epochs 5/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001570173531256028, val_loss: 0.04407095846376921
epochs 6/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015746166941856868, val_loss: 0.0460469247087052
epochs 7/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016053992911781135, val_loss: 0.045791778164474585
epochs 8/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015513735388307586, val_loss: 0.044832322040670794
epochs 9/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001650453993658486, val_loss: 0.045808568008636176
epochs 10/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015631499651231264, val_loss: 0.0453637313881987
epochs 11/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015966971282308038, val_loss: 0.044434438292917454
epochs 12/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016616135320969318, val_loss: 0.04656035551115086
epochs 13/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015928845607528562, val_loss: 0.046756788539259055
epochs 14/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016156160652539447, val_loss: 0.040644085642538574
epochs 15/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0017113636431627369, val_loss: 0.043459834354488476
epochs 16/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001545384894492791, val_loss: 0.045361754474671265
epochs 17/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016215026586953746, val_loss: 0.04593703538963669
epochs 18/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001638504867687037, val_loss: 0.04321931792717231
epochs 19/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015305166353324527, val_loss: 0.04756359293272621
epochs 20/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001537541873557003, val_loss: 0.047083561632194015
epochs 21/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015865068539584939, val_loss: 0.04413233297435861
epochs 22/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001527407985964888, val_loss: 0.047803546880420884
epochs 23/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0014875533635188875, val_loss: 0.044324255617041335
epochs 24/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015720593608229568, val_loss: 0.043382103329426366
epochs 25/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015788256202971464, val_loss: 0.04663788468429917
epochs 26/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015462148726280583, val_loss: 0.0421973411974154
epochs 27/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015913893578966198, val_loss: 0.0466289898674739
epochs 28/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001546304896596427, val_loss: 0.045110286811464714
epochs 29/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016161635322006125, val_loss: 0.042729784352214716
epochs 30/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015254363405371183, val_loss: 0.04647820854657575
epochs 31/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001602284154413562, val_loss: 0.048117530345916745
epochs 32/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015610285887592717, val_loss: 0.04527805278960027
epochs 33/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015522700207504002, val_loss: 0.044876988467417264
epochs 34/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016029534328385795, val_loss: 0.043738067738319696
epochs 35/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016601096299525939, val_loss: 0.04556690121167584
epochs 36/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015549112344160677, val_loss: 0.046982606578814354
epochs 37/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015048510652329577, val_loss: 0.04323207300744559
epochs 38/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015726375056577748, val_loss: 0.04403507638918726
epochs 39/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016079556809640244, val_loss: 0.048762531147191396
epochs 40/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001556632182511844, val_loss: 0.0429710989719943
epochs 41/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015225125151980472, val_loss: 0.04460934949548621
epochs 42/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015527467794814393, val_loss: 0.04745073467493057
epochs 43/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015681716662488486, val_loss: 0.04220571984585963
epochs 44/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015487529527346948, val_loss: 0.04587368137742344
epochs 45/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015584576825954412, val_loss: 0.047122227400541304
epochs 46/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015489939195839199, val_loss: 0.04235534001337855
epochs 47/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0016032493955112602, val_loss: 0.04621212788318333
epochs 48/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015522646754489917, val_loss: 0.045921979295580014
epochs 49/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001537788952210624, val_loss: 0.04261989773888337
epochs 50/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015414948587452895, val_loss: 0.04609055730857347
epochs 51/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001502447746890156, val_loss: 0.045108730443998386
epochs 52/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015919219677973735, val_loss: 0.04423631237525689
epochs 53/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.001521157458620636, val_loss: 0.04616667251837881
epochs 54/104
Current Learning Rate: 0.001031435095793296
train_loss: 0.0015527847382289014, val_loss: 0.044185858925706464
epochs 55/104
Current Learning Rate: 0.001031435095793296

[I 2024-01-26 23:17:16,475] Trial 2 finished with value: 0.14751121193609285 and parameters: {'batch_size': 36, 'epochs': 104, 'hidden_size': 93, 'learning_rate': 0.001031435095793296, 'dropout_prob': 0.19866174084503035, 'weight_decay': 1.371664275592657e-05, 'lr_step_size': 51, 'gamma': 0.14434759177580736, 'conv_channels': 55, 'kernel_size': 4, 'num_layers': 5, 'pool_size': 5, 'stride': 2}. Best is trial 1 with value: 0.010049154356568352.

Current Learning Rate: 0.00014888517215081145
train_loss: 0.08344255185440967, val_loss: 0.20382561181720935
Mean validation loss: 0.14751121193609285
Starting fold 1:
epochs 1/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.021371193004674032, val_loss: 0.02237161868496945
epochs 2/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.01578069031238556, val_loss: 0.01715272123876371
epochs 3/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.011887124406271859, val_loss: 0.012770218769774626
epochs 4/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.008586624240208613, val_loss: 0.00913065381740269
epochs 5/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.005667590443044901, val_loss: 0.006272319334216024
epochs 6/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.004126120758193888, val_loss: 0.004205551101384979
epochs 7/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.002699062630142036, val_loss: 0.0028276954789793023
epochs 8/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0023430527580019676, val_loss: 0.0019990664821020084
epochs 9/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017067364325109673, val_loss: 0.0015593444174890848
epochs 10/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016606467641203811, val_loss: 0.0013667038605107288
epochs 11/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017179085922084357, val_loss: 0.0013121210308255334
epochs 12/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001940634359581102, val_loss: 0.0013415676290414443
epochs 13/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0015783333734266068, val_loss: 0.0014309484474851113
epochs 14/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016054869470137514, val_loss: 0.001575712325958241
epochs 15/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018750727973192145, val_loss: 0.0017337290882623118
epochs 16/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018392124966914323, val_loss: 0.0018408047586777492
epochs 17/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001993248912530314, val_loss: 0.001901396863334077
epochs 18/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016389928329245825, val_loss: 0.0019505604917771722
epochs 19/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017415169785779557, val_loss: 0.0019729222030084774
epochs 20/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017738541140907298, val_loss: 0.0019510540259560865
epochs 21/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016629711976029764, val_loss: 0.0019165901626509271
epochs 22/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0019144101368606483, val_loss: 0.0019011097592546752
epochs 23/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0015233696585423067, val_loss: 0.0018740544224304981
epochs 24/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0015556994182253747, val_loss: 0.0018679025043782434
epochs 25/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0015203535513903358, val_loss: 0.0018818793585523963
epochs 26/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0019844566851756292, val_loss: 0.001872472917219918
epochs 27/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018741951146359114, val_loss: 0.0018471493073248942
epochs 28/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017463460748427008, val_loss: 0.0018375775415303284
epochs 29/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017683626030032572, val_loss: 0.0018519655207024986
epochs 30/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0019335367735230217, val_loss: 0.0018416352655836626
epochs 31/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001538907561916858, val_loss: 0.0017908143106308814
epochs 32/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017862663457268162, val_loss: 0.0017282521652400885
epochs 33/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001761039909539058, val_loss: 0.0016898296025924778
epochs 34/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001713938063843862, val_loss: 0.001692570250873503
epochs 35/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0019156374674486486, val_loss: 0.001719038260757531
epochs 36/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001772935850251662, val_loss: 0.0017909623823422743
epochs 37/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016077527224919513, val_loss: 0.001863129815625909
epochs 38/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018088379972859433, val_loss: 0.0019138851582905963
epochs 39/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001734754362290627, val_loss: 0.0018987611775580597
epochs 40/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001653899771994666, val_loss: 0.0019213893708135738
epochs 41/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017618911126383433, val_loss: 0.0019416698236263503
epochs 42/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017999415016291956, val_loss: 0.0019446245051528278
epochs 43/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0019938064144777233, val_loss: 0.0019549133121281076
epochs 44/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001821094074311029, val_loss: 0.0019531961965472684
epochs 45/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001864375235929497, val_loss: 0.0019343494057753369
epochs 46/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0019522230067339382, val_loss: 0.001891790768499241
epochs 47/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018969942080347161, val_loss: 0.001885435955084272
epochs 48/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017109537380747496, val_loss: 0.0019052886888139735
epochs 49/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018475338197803419, val_loss: 0.0018730144684301004
epochs 50/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018003762325909185, val_loss: 0.0018359381062174706
epochs 51/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001670621933513566, val_loss: 0.001804489926067426
epochs 52/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016829090039735953, val_loss: 0.0018089884548987212
epochs 53/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0021497295899806836, val_loss: 0.0018500114251908503
epochs 54/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001936802857457415, val_loss: 0.0018923556499526298
epochs 55/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017063913474741736, val_loss: 0.0019663872393338305
epochs 56/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016518551690847074, val_loss: 0.0020500624386936817
epochs 57/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.00186301210809401, val_loss: 0.002116721663869133
epochs 58/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018984213165056548, val_loss: 0.002134599646945533
epochs 59/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017386955650229203, val_loss: 0.002147108160792605
epochs 60/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016948750732760681, val_loss: 0.002119341250018854
epochs 61/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001924148589176567, val_loss: 0.0021013681041566947
epochs 62/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016786039592453133, val_loss: 0.0020413978006935825
epochs 63/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018702042656705568, val_loss: 0.0019710318883880973
epochs 64/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017475680938284649, val_loss: 0.0019278107045561468
epochs 65/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0016419290877437514, val_loss: 0.0019040197495518154
epochs 66/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017156249696486875, val_loss: 0.0018856739576317762
epochs 67/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001684714891751738, val_loss: 0.001877451315522194
epochs 68/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018359430936949425, val_loss: 0.0018776272104955034
epochs 69/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0019027408010228292, val_loss: 0.0018874841245920643
epochs 70/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001615909616291327, val_loss: 0.0019134741270375487
epochs 71/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001756576901473301, val_loss: 0.001878113874332293
epochs 72/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018437237533936767, val_loss: 0.001838852605463839
epochs 73/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0018305882548080071, val_loss: 0.0018160394950475739
epochs 74/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.001774774035929065, val_loss: 0.001815664581341767
epochs 75/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0019370863208008047, val_loss: 0.0018205226356114604
epochs 76/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017931364458299388, val_loss: 0.0018455829293663173
epochs 77/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.00182324691957451, val_loss: 0.0019221284628943786
epochs 78/91
Current Learning Rate: 0.00029121838300435543
train_loss: 0.0017943875937673607, val_loss: 0.0019925717834236197
epochs 79/91
Epoch 00079: reducing learning rate of group 0 to 1.8569e-04.
Current Learning Rate: 0.00018568686600941046
train_loss: 0.001619057614037669, val_loss: 0.002033192467091507
epochs 80/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.0017914475670917647, val_loss: 0.0020454445902846363
epochs 81/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.0019423101893871239, val_loss: 0.0020438998079809704
epochs 82/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.0020209472706100265, val_loss: 0.002013156472974898
epochs 83/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.0019118539051544902, val_loss: 0.0019747251693747548
epochs 84/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.0019777009159473603, val_loss: 0.001919187705865816
epochs 85/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.0018483964248413318, val_loss: 0.0018826068182917018
epochs 86/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.00196899642346819, val_loss: 0.0018761684695307753
epochs 87/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.0021760415359351197, val_loss: 0.001883758064727054
epochs 88/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.0018422699999064208, val_loss: 0.0019042273290994529
epochs 89/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.001839314771840643, val_loss: 0.0019237112983031884
epochs 90/91

[I 2024-01-26 23:17:20,854] Trial 3 pruned.

Current Learning Rate: 0.00018568686600941046
train_loss: 0.0019395867828279733, val_loss: 0.0019446552394105023
epochs 91/91
Current Learning Rate: 0.00018568686600941046
train_loss: 0.0015968517296163268, val_loss: 0.0019586021019341914
Starting fold 2:
epochs 1/91
Starting fold 1:
epochs 1/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.024780015823872466, val_loss: 0.022222016790979786
epochs 2/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.014632922097256309, val_loss: 0.013422449286046781
epochs 3/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.007933502281574826, val_loss: 0.007037627540136639
epochs 4/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0044333099632671005, val_loss: 0.00297722111848232
epochs 5/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0027496698508529286, val_loss: 0.0013225200487986992
epochs 6/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.002884050586113804, val_loss: 0.0011322809714137724
epochs 7/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0031066699909340395, val_loss: 0.0011380601404724936
epochs 8/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.00268495000996872, val_loss: 0.0012613429105840623
epochs 9/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.002698707649190175, val_loss: 0.0015949333074355596
epochs 10/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.002800444442484724, val_loss: 0.0019260950888948221
epochs 11/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.002502694652464829, val_loss: 0.0021254713144643524
epochs 12/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0023262083751002423, val_loss: 0.0020923516247421505
epochs 13/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.002675708424986193, val_loss: 0.0019333041812244214
epochs 14/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0024479231110921033, val_loss: 0.0017090661573762956
epochs 15/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0022198581247051294, val_loss: 0.0015655724564567208
epochs 16/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.002135378413980729, val_loss: 0.0015167532795059837
epochs 17/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0017738639254515109, val_loss: 0.001533775285229479
epochs 18/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.002444837634500704, val_loss: 0.0014795122680401332
epochs 19/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.001900502381307122, val_loss: 0.0014938935710999527
epochs 20/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0017454837436640734, val_loss: 0.00158851491654978
epochs 21/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0018922971818890228, val_loss: 0.001481871165972399
epochs 22/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0021620358046340314, val_loss: 0.0014067020095688732
epochs 23/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0018813367712458497, val_loss: 0.0011765904516275777
epochs 24/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0013460188613910423, val_loss: 0.0015181339995347356
epochs 25/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0016286351742517008, val_loss: 0.0018810941641660113
epochs 26/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0014484572003742582, val_loss: 0.0012260324352322833
epochs 27/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0013599152235608352, val_loss: 0.0018783600633277705
epochs 28/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.001567840225700485, val_loss: 0.0015539868930844883
epochs 29/109

[I 2024-01-26 23:17:22,584] Trial 4 pruned.

Current Learning Rate: 0.0005075681278872791
train_loss: 0.001714143785648048, val_loss: 0.0011148390415320663
epochs 30/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0015401604928468402, val_loss: 0.002833545367282472
epochs 31/109
Current Learning Rate: 0.0005075681278872791
train_loss: 0.0014991080792816846, val_loss: 0.0019493039660645943
epochs 32/109
Starting fold 1:
epochs 1/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.03147450636484121, val_loss: 0.03826511408153333
epochs 2/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.030629727577692584, val_loss: 0.03775707173504327
epochs 3/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.030471600788204295, val_loss: 0.03725400621953764
epochs 4/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.029430848928658587, val_loss: 0.036757067669379084
epochs 5/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.02972434670909455, val_loss: 0.036264817965658086
epochs 6/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.028480397027574086, val_loss: 0.03577819478354956
epochs 7/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.028816747528157736, val_loss: 0.035297110519911114
epochs 8/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.027942337840795518, val_loss: 0.03482043092188082
epochs 9/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.027909877641420614, val_loss: 0.03434954207194479
epochs 10/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.027440253253045836, val_loss: 0.03388303620250602
epochs 11/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.027017022100718397, val_loss: 0.033423610110031934
epochs 12/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.02696903026417682, val_loss: 0.03296855241060257
epochs 13/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.0258498257712314, val_loss: 0.032519550190160146
epochs 14/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.026183517708590155, val_loss: 0.03207635679527333
epochs 15/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.02482240901965844, val_loss: 0.03164027611676015
epochs 16/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.025080432801654465, val_loss: 0.03121091331306257
epochs 17/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.024653118182169764, val_loss: 0.03078758704819177
epochs 18/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.023644949005622612, val_loss: 0.030370645558363513
epochs 19/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.023559669503255894, val_loss: 0.029958715936855267
epochs 20/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.02308244266008076, val_loss: 0.02954992220589989
epochs 21/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.02316080071032047, val_loss: 0.02914584433954013
epochs 22/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.021934708227452478, val_loss: 0.02874764480481022
epochs 23/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.022114311531186103, val_loss: 0.028353738176979518
epochs 24/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.02228215227001592, val_loss: 0.027963740064909582
epochs 25/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.022256263933683698, val_loss: 0.0275766613648126
epochs 26/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.021255854478007867, val_loss: 0.027194751406970776
epochs 27/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.021155796650993198, val_loss: 0.026817135846144275
epochs 28/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.020578860883650026, val_loss: 0.026444727966659948
epochs 29/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.020336231687351276, val_loss: 0.026077564746925706
epochs 30/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.019951526467737398, val_loss: 0.025715902114385052
epochs 31/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.019544931795251998, val_loss: 0.02535797220311667
epochs 32/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.019574904206552005, val_loss: 0.025004220538233455
epochs 33/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01940909128047918, val_loss: 0.024652748770619695
epochs 34/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01893082351276749, val_loss: 0.024303165587939716
epochs 35/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.018565070962435322, val_loss: 0.023956335335969924
epochs 36/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01829025751273883, val_loss: 0.023613713799338593
epochs 37/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01850848654775243, val_loss: 0.02327357022777984
epochs 38/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.017522346326395086, val_loss: 0.02293529588925211
epochs 39/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.017470063092677218, val_loss: 0.022599547787716515
epochs 40/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.017565767114099705, val_loss: 0.02226695247778767
epochs 41/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.016273030344592897, val_loss: 0.021939276413697945
epochs 42/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01670231278005399, val_loss: 0.021614993265584897
epochs 43/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.016045799871024332, val_loss: 0.021294216674409415
epochs 44/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.015648060644927776, val_loss: 0.0209763631812836
epochs 45/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01583370001692521, val_loss: 0.020661311616238794
epochs 46/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.015508787206521159, val_loss: 0.02034945768353186
epochs 47/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.015273143056976168, val_loss: 0.020041546617683613
epochs 48/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.014504890163478099, val_loss: 0.019737457523220463
epochs 49/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01424456407365046, val_loss: 0.01943652480840683
epochs 50/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01440030986345128, val_loss: 0.019136458184374008
epochs 51/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.013724640452940213, val_loss: 0.018840775697639114
epochs 52/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.013441544957458973, val_loss: 0.018548380407063584
epochs 53/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.013555075385068593, val_loss: 0.018258837551662795
epochs 54/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.013573241753405647, val_loss: 0.0179723226122166
epochs 55/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01344775081072983, val_loss: 0.017689052204552448
epochs 56/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.013047483906542, val_loss: 0.01740753519299783
epochs 57/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01239632581801791, val_loss: 0.01713004420070272
epochs 58/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.012590961785692918, val_loss: 0.01685604060951032
Starting fold 2:
epochs 1/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.014678223950690345, val_loss: 0.09949584532725184
epochs 2/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.013964615624986196, val_loss: 0.09782459265307376
epochs 3/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.013355501476479204, val_loss: 0.09614842902672918
epochs 4/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01300609334322967, val_loss: 0.09450986118693101
epochs 5/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.01242993580863664, val_loss: 0.09291705018595646
epochs 6/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.011703501808408059, val_loss: 0.09136523220099901
epochs 7/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.011131691854251058, val_loss: 0.08981640119301645
epochs 8/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.010629858154999582, val_loss: 0.08832073195984488
epochs 9/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.010152886778508362, val_loss: 0.08683801434542003
epochs 10/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.009854580158073651, val_loss: 0.08538496164899123
epochs 11/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.00933906085004932, val_loss: 0.08394270837306976
epochs 12/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.009145748370180005, val_loss: 0.0824643880913132
epochs 13/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.008780857803005922, val_loss: 0.08099508771770879
epochs 14/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.00819008117051501, val_loss: 0.07955981053804097
epochs 15/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.007740172680075231, val_loss: 0.07816121821340762
epochs 16/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.007178161915783819, val_loss: 0.0768589691111916
epochs 17/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.006897681735848126, val_loss: 0.07559444323966377
epochs 18/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.006696839846278492, val_loss: 0.0743481065097608
epochs 19/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.0061826612261172975, val_loss: 0.0731088651638282
epochs 20/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.006087472755461931, val_loss: 0.07197733631259516
epochs 21/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.005911647606837122, val_loss: 0.07094572468807822
epochs 22/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.005644791406628332, val_loss: 0.06987723770894502
epochs 23/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.005372508992686083, val_loss: 0.0688325224738372
epochs 24/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.005236538391756384, val_loss: 0.06784499687583823
epochs 25/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.004911066170193647, val_loss: 0.06682996843990527
epochs 26/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.004660203430409494, val_loss: 0.06584094778487556
epochs 27/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.004591697518174585, val_loss: 0.0649044773296306
epochs 28/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.004053877264653382, val_loss: 0.06398067458679801
epochs 29/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.004110542670088379, val_loss: 0.0630435266384953
epochs 30/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.004061166358817565, val_loss: 0.06222186343450295
epochs 31/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.0037496498467302635, val_loss: 0.06146916884340738
epochs 32/58

[I 2024-01-26 23:17:27,961] Trial 5 pruned.

Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.003595265378489306, val_loss: 0.0607261527917887
epochs 33/58
Current Learning Rate: 2.9423368938084218e-05
train_loss: 0.0035348594801402405, val_loss: 0.06002957824813692
epochs 34/58
Starting fold 1:
epochs 1/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.04193974309845975, val_loss: 0.05070797906894433
epochs 2/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.04129216027887244, val_loss: 0.05018083492391988
epochs 3/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.04098027783789133, val_loss: 0.049656614112226584
epochs 4/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.040341016375704815, val_loss: 0.04913580045104027
epochs 5/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.039827211358045275, val_loss: 0.04861923111112494
epochs 6/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03925542294194824, val_loss: 0.048106579011992404
epochs 7/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.039204895221873336, val_loss: 0.04759653512584536
epochs 8/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.038135639695744766, val_loss: 0.04709034856212767
epochs 9/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03787083304242084, val_loss: 0.046588996562518574
epochs 10/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03779852504008695, val_loss: 0.04608974041123139
epochs 11/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.037340020584432705, val_loss: 0.045594606195625505
epochs 12/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03688152048148607, val_loss: 0.04510288693402943
epochs 13/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03645148092978879, val_loss: 0.04461542673801121
epochs 14/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03565835533173461, val_loss: 0.044131629757191
epochs 15/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03575683989022908, val_loss: 0.04364994254551436
epochs 16/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.034965610621791134, val_loss: 0.043173585322342424
epochs 17/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.034792944475224144, val_loss: 0.042702456798992657
epochs 18/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03433228817425276, val_loss: 0.04223414690870988
epochs 19/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.034077700541207664, val_loss: 0.04176839029318408
epochs 20/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.0335546177076666, val_loss: 0.04130598208621929
epochs 21/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03301468664094021, val_loss: 0.04084898288312711
epochs 22/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03260699694878177, val_loss: 0.040396299213171005
epochs 23/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03199560187364879, val_loss: 0.039947659012518434
epochs 24/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03186126614087506, val_loss: 0.039502194053248355
epochs 25/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.031648059620669015, val_loss: 0.03906010612845421
epochs 26/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.031063603923508997, val_loss: 0.0386199725693778
epochs 27/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.03026392706914952, val_loss: 0.03818441935275731
epochs 28/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.030163575591225372, val_loss: 0.03775219372228572
epochs 29/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.029688754756199687, val_loss: 0.03732404355940066
epochs 30/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02940375765687541, val_loss: 0.036901247148451055
epochs 31/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.029565894152773053, val_loss: 0.0364784217194507
epochs 32/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02879466879132547, val_loss: 0.0360604390501976
epochs 33/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.028222978977780592, val_loss: 0.03564515905944925
epochs 34/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02806199524355562, val_loss: 0.035234013435087704
epochs 35/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02764986337799775, val_loss: 0.034825533981385985
epochs 36/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.027059106175836765, val_loss: 0.03442120077578645
epochs 37/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02734902195240322, val_loss: 0.034020359971021354
epochs 38/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02645832368809926, val_loss: 0.03362100481202728
epochs 39/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.026397387389289706, val_loss: 0.03322595930413196
epochs 40/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02558337491201727, val_loss: 0.032834839154230924
epochs 41/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.025417274217072287, val_loss: 0.03244680652492925
epochs 42/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02497648453634036, val_loss: 0.032063264870329906
epochs 43/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.024661522515510258, val_loss: 0.031683023234731274
epochs 44/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02425319803388495, val_loss: 0.03130633478101931
epochs 45/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.024187116834678148, val_loss: 0.03093291419117074
epochs 46/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.024139617207018953, val_loss: 0.030561660641902372
epochs 47/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02336186398016779, val_loss: 0.030194600906811263
epochs 48/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.023050962486549427, val_loss: 0.029829423756975875
epochs 49/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.022894369104975148, val_loss: 0.029468373209238053
epochs 50/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.022681037297374324, val_loss: 0.02911105544159287
epochs 51/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02228536852880528, val_loss: 0.02875753886213428
epochs 52/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.021980578001392515, val_loss: 0.028405575983618436
epochs 53/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.02211655660679466, val_loss: 0.028056672293888894
epochs 54/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.021398517371792544, val_loss: 0.02771195586966841
epochs 55/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.020968895523171677, val_loss: 0.02736983969807625
epochs 56/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.020960577224430284, val_loss: 0.027030922335229423
epochs 57/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.020245349956186195, val_loss: 0.026694738747257935
epochs 58/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.020059978060032194, val_loss: 0.02636197523066872
epochs 59/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.019994709327032692, val_loss: 0.026031511257353583
epochs 60/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.019538603330913343, val_loss: 0.025706720744308673
epochs 61/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.0191121433126299, val_loss: 0.025384838565399772
epochs 62/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.01903258681689438, val_loss: 0.025065881896175837
epochs 63/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.0189004390255401, val_loss: 0.024750030236808877
epochs 64/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.01857752047087017, val_loss: 0.02443535378889034
epochs 65/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.018133449103487166, val_loss: 0.024125381029750172
epochs 66/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.018308851064035767, val_loss: 0.023817273445035283
epochs 67/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.01775797354547601, val_loss: 0.02351411963371854
epochs 68/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.017709164105747875, val_loss: 0.02321125470886105
epochs 69/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.017179577464335842, val_loss: 0.02291304622041552
epochs 70/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.0170053471271929, val_loss: 0.022617803219901887
epochs 71/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.016663433278077528, val_loss: 0.02232588776632359
epochs 72/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.016373042732869325, val_loss: 0.022036069259047508
epochs 73/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.016248832074435133, val_loss: 0.021750775803076595
epochs 74/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.016265115945747022, val_loss: 0.021467489651159237
epochs 75/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.015668153664783427, val_loss: 0.02118775136768818
epochs 76/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.01590967665573484, val_loss: 0.020910695136377687
epochs 77/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.015257094408336438, val_loss: 0.02063669285884029
epochs 78/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.014864123161686095, val_loss: 0.020366679720188442
epochs 79/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.014915937165680685, val_loss: 0.020098477386330305
epochs 80/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.014679895704121966, val_loss: 0.019833557307720184
epochs 81/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.014471524591116528, val_loss: 0.019571333613834882
epochs 82/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.014187213160881871, val_loss: 0.019311795383691786
epochs 83/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.013863548763880604, val_loss: 0.019055632560660965
epochs 84/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.013907657504865998, val_loss: 0.01880269246666055
epochs 85/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.013729721954778621, val_loss: 0.01855136581549519
epochs 86/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.013398281886781516, val_loss: 0.01830248087644577
epochs 87/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.013194598679087665, val_loss: 0.018058668841656886
epochs 88/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.012915533339898836, val_loss: 0.017816658533717458
epochs 89/125

[I 2024-01-26 23:17:31,788] Trial 6 pruned.

Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.012749770136648103, val_loss: 0.017576708487774196
epochs 90/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.012648557391213743, val_loss: 0.017339632013126424
epochs 91/125
Current Learning Rate: 3.8965451946667574e-05
train_loss: 0.012176852526241228, val_loss: 0.017105635383019322
epochs 92/125
Starting fold 1:
epochs 1/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.007819370415649916, val_loss: 0.010489804327095809
epochs 2/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.006723509219131972, val_loss: 0.009145897087690077
epochs 3/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.005735631056718136, val_loss: 0.007924227014576134
epochs 4/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0048017088127763645, val_loss: 0.006817335757966105
epochs 5/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0040947141615968, val_loss: 0.005820799172904931
epochs 6/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.003397033814536898, val_loss: 0.004934869598793356
epochs 7/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.002837153203099182, val_loss: 0.004153716735737888
epochs 8/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0023676891394547725, val_loss: 0.003472929587587714
epochs 9/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.001986113764149578, val_loss: 0.002892067991687279
epochs 10/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0017446040016549983, val_loss: 0.0024079717646696064
epochs 11/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0015959113113288032, val_loss: 0.002023059107657326
epochs 12/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0014102557637287597, val_loss: 0.0017366260155349186
epochs 13/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013467157406634406, val_loss: 0.001531317879102732
epochs 14/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013834843877702952, val_loss: 0.0013966649109007497
epochs 15/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.001460736899293567, val_loss: 0.001317430783896462
epochs 16/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0014860333458177352, val_loss: 0.001280758071592764
epochs 17/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0015246581776361717, val_loss: 0.001270405840324728
epochs 18/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0015371223703320874, val_loss: 0.0012801896192525563
epochs 19/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0015193526093897067, val_loss: 0.0013054148624896218
epochs 20/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.001494223862200191, val_loss: 0.001348479940114837
epochs 21/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0014670689578021043, val_loss: 0.0014120419877336214
epochs 22/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.001405060296191981, val_loss: 0.0014805891747145276
epochs 23/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013626107884767023, val_loss: 0.0015521519952208587
epochs 24/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013716537517642505, val_loss: 0.0016209624045969624
epochs 25/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013970457115455677, val_loss: 0.001677835127338767
epochs 26/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0014025995507836342, val_loss: 0.0017207836364641002
epochs 27/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.001337050755606278, val_loss: 0.001743660196907034
epochs 28/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0012853520248379362, val_loss: 0.001746468961630997
epochs 29/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013621022189526182, val_loss: 0.001731945652710764
epochs 30/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013380279213092044, val_loss: 0.0017050036596820543
epochs 31/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013399931197789938, val_loss: 0.0016764835956947584
epochs 32/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013306717253535202, val_loss: 0.0016450080113779558
epochs 33/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0013314326171224055, val_loss: 0.0016146546254228605
epochs 34/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.001249572009730496, val_loss: 0.0015857617824191325
epochs 35/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0012755946023389696, val_loss: 0.0015569637982959027
epochs 36/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.001204285605222379, val_loss: 0.0015303315864385744
epochs 37/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.00118884614693295, val_loss: 0.0015025915369685544
epochs 38/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0012011890838804998, val_loss: 0.0014733218477646771
epochs 39/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0011618454989634063, val_loss: 0.0014525711806000847
epochs 40/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0011365553278377967, val_loss: 0.0014370003347530177
epochs 41/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0010646677404446037, val_loss: 0.0014361854458815957
epochs 42/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0010501402859134895, val_loss: 0.0014571915637995852
epochs 43/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0010014512992807124, val_loss: 0.0014622547639239775
epochs 44/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0010120398769351213, val_loss: 0.0014788916861442358
epochs 45/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0009112550717729487, val_loss: 0.0014937907800470528
epochs 46/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0008968388324750489, val_loss: 0.0014613039950889192
epochs 47/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0008382511705062107, val_loss: 0.0014601113483015643
epochs 48/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0007542046577375579, val_loss: 0.0014467573761449833
epochs 49/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0006458942349509973, val_loss: 0.0014393172606727794
epochs 50/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0006421450108877922, val_loss: 0.0014977100231733762
epochs 51/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0005801086681649873, val_loss: 0.0016526605125124518
epochs 52/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0005273141352900941, val_loss: 0.0018289374457182068
epochs 53/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.00046756633030446736, val_loss: 0.001863991202002293
epochs 54/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0004139483511129296, val_loss: 0.0017209460419651708
epochs 55/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.00041930724462298187, val_loss: 0.00177425881235027
epochs 56/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0003655722355592604, val_loss: 0.002204140023279347
epochs 57/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0003440200884238278, val_loss: 0.0024293766062902775
epochs 58/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.00035839672813093974, val_loss: 0.002276106578248896
epochs 59/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.00031276442674233726, val_loss: 0.0022606772517687395
epochs 60/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.0003146282345130059, val_loss: 0.002324695417069291
epochs 61/140
Current Learning Rate: 0.00018935161077310026
train_loss: 0.000309754174974698, val_loss: 0.0025656229179156454
epochs 62/140
Epoch 00062: reducing learning rate of group 0 to 6.1278e-05.
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00029006907777664694, val_loss: 0.0025395847734455998
epochs 63/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00029141399120960975, val_loss: 0.0024778864370953095
epochs 64/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00029758756128629965, val_loss: 0.0023961195403611976
epochs 65/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002676972050195266, val_loss: 0.002339036542137987
epochs 66/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002877379666499205, val_loss: 0.0023239354995128357
epochs 67/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002973322136217336, val_loss: 0.0023691087372993166
epochs 68/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002708277980625433, val_loss: 0.002419287014115406
epochs 69/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00026806077129501655, val_loss: 0.0024668901521516474
epochs 70/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00027726625864344994, val_loss: 0.002478334153267114
epochs 71/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00032038197754637193, val_loss: 0.0023948027703322864
epochs 72/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00028701728105692093, val_loss: 0.0023068522789368505
epochs 73/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002697546537475366, val_loss: 0.0022505787642378558
epochs 74/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002722308165271227, val_loss: 0.002279048471858627
epochs 75/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00027223019247972653, val_loss: 0.0023372096303654346
epochs 76/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00026564200126909113, val_loss: 0.0024216624687572845
epochs 77/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.000262652983349797, val_loss: 0.002466094265937021
epochs 78/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00026758303896425977, val_loss: 0.0024461374471062107
epochs 79/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002664630117483045, val_loss: 0.002361675680271889
epochs 80/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00029285112824781163, val_loss: 0.00226781797889424
epochs 81/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00026337268370154655, val_loss: 0.002172692301438043
epochs 82/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00027374968784371097, val_loss: 0.002128018696155203
epochs 83/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00029645592041656766, val_loss: 0.0021345039707069335
epochs 84/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002497870465863104, val_loss: 0.0022111225897740376
epochs 85/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.000288886469972663, val_loss: 0.00231276028544495
epochs 86/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00024975628659472263, val_loss: 0.002386469413575373
epochs 87/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00024394808386109379, val_loss: 0.002410266609666379
epochs 88/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002537911736381877, val_loss: 0.002366527451790477
epochs 89/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00027743086807037655, val_loss: 0.002312779387361125
epochs 90/140

[I 2024-01-26 23:17:36,151] Trial 7 pruned.

Current Learning Rate: 6.127785825783559e-05
train_loss: 0.00024281446301182243, val_loss: 0.0022914620692302524
epochs 91/140
Current Learning Rate: 6.127785825783559e-05
train_loss: 0.0002609961252586034, val_loss: 0.0023081703626207616
epochs 92/140
Starting fold 1:
epochs 1/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0022659327712302147, val_loss: 0.0023438831129552504
epochs 2/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0016401536823985607, val_loss: 0.001688621798530221
epochs 3/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0016149402645073438, val_loss: 0.0014464890045162878
epochs 4/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.001700716694865964, val_loss: 0.0013794990072615052
epochs 5/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0016734588719708354, val_loss: 0.0014278159893460964
epochs 6/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.001779146679971171, val_loss: 0.00155523613119792
epochs 7/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.00172789014483753, val_loss: 0.0017427897497423385
epochs 8/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.001607897654665928, val_loss: 0.001921138497020461
epochs 9/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0015549583850722564, val_loss: 0.002048372673360925
epochs 10/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0016859716331390174, val_loss: 0.0020639460460331878
epochs 11/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0017426675283595135, val_loss: 0.0019536989373400023
epochs 12/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0015810819220189985, val_loss: 0.0018092042447901086
epochs 13/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.001524463244468758, val_loss: 0.0016859152133723624
epochs 14/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0014970412441088182, val_loss: 0.001615753469645585
epochs 15/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0014768745382561495, val_loss: 0.0016076937428136406
epochs 16/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0016178035532663528, val_loss: 0.0016325296417466905
epochs 17/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0016325532103349503, val_loss: 0.0016662923643659604
epochs 18/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0014971438439955053, val_loss: 0.0017263879411314664
epochs 19/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0016074763561942076, val_loss: 0.0017942097087047602
epochs 20/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0015246784902716937, val_loss: 0.0018597803973151666
epochs 21/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0016065731031918212, val_loss: 0.001920949719160011
epochs 22/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0015470125050725122, val_loss: 0.0019224641072612843
epochs 23/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.001606215238816252, val_loss: 0.0019042190666751643
epochs 24/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0015928723126355754, val_loss: 0.0018671478120316017
epochs 25/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.001508741398145886, val_loss: 0.0017862316171981787
epochs 26/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0015181740243478041, val_loss: 0.0017275717330018157
epochs 27/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.00162616739858334, val_loss: 0.0017047490949105275
epochs 28/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0016058068906300161, val_loss: 0.001697377935297003
epochs 29/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0015704076124453232, val_loss: 0.001707484505727495
epochs 30/94

[I 2024-01-26 23:17:37,617] Trial 8 pruned.

Current Learning Rate: 0.000817379431673565
train_loss: 0.0015040058728405519, val_loss: 0.0017300240376866176
epochs 31/94
Current Learning Rate: 0.000817379431673565
train_loss: 0.0015540122924568621, val_loss: 0.0017578970028185531
epochs 32/94
Starting fold 1:
epochs 1/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.009525924271560814, val_loss: 0.007874260945735793
epochs 2/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0031449692887499142, val_loss: 0.002166331317398305
epochs 3/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.001439262929642083, val_loss: 0.0012472403704458358
epochs 4/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0023052856172925155, val_loss: 0.0012237467432370116
epochs 5/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.001834761869701508, val_loss: 0.0015012877546005735
epochs 6/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0015081413084101912, val_loss: 0.0021873329049221387
epochs 7/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0015822423836461415, val_loss: 0.0023574253562592754
epochs 8/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0015317191804857238, val_loss: 0.002071043892493962
epochs 9/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0014241028644487654, val_loss: 0.0016754752092406546
epochs 10/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0014088112162426113, val_loss: 0.0015190089605503568
epochs 11/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0014573817398693216, val_loss: 0.0015518056351299348
epochs 12/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0013644029956163936, val_loss: 0.0017044861745824547
epochs 13/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0013967340003306929, val_loss: 0.001751560516851513
epochs 14/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0013307810497568235, val_loss: 0.0017110060882068387
epochs 15/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.001253205499807863, val_loss: 0.0015341434946381733
epochs 16/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0011847729371909641, val_loss: 0.0014754286048149592
epochs 17/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0011451825076763174, val_loss: 0.0014270394602422848
epochs 18/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0009711195494195348, val_loss: 0.001345536036809024
epochs 19/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0007509811919207048, val_loss: 0.001493500291651703
epochs 20/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0005293332787818815, val_loss: 0.0014980545806649484
epochs 21/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0003747978263019927, val_loss: 0.0021317471664300874
epochs 22/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0003288808511570096, val_loss: 0.0031188861785554573
epochs 23/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.00042620057907984837, val_loss: 0.0018945909521885609
epochs 24/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0003414187635491161, val_loss: 0.0022463460238405356
epochs 25/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.00032525401927016085, val_loss: 0.0019164580704742356
epochs 26/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.00029132679000643913, val_loss: 0.0018906097638567811
epochs 27/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.00029543920138262606, val_loss: 0.0017195865897902925
epochs 28/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0003413527926711954, val_loss: 0.0017602316073240026
epochs 29/127

[I 2024-01-26 23:17:39,469] Trial 9 pruned.

Current Learning Rate: 0.00032205205564744436
train_loss: 0.0002993280337633271, val_loss: 0.001989779814979748
epochs 30/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0002662521508203721, val_loss: 0.0017547119421100145
epochs 31/127
Current Learning Rate: 0.00032205205564744436
train_loss: 0.0002768156085757686, val_loss: 0.002171156049313906
epochs 32/127
Starting fold 1:
epochs 1/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0022071460703093756, val_loss: 0.003772546257823706
epochs 2/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.002251881580358665, val_loss: 0.0037517512462248927
epochs 3/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.002261166455910394, val_loss: 0.003730489289093959
epochs 4/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.002176190157862086, val_loss: 0.003707906018060289
epochs 5/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0023262195142084046, val_loss: 0.0036843515295339256
epochs 6/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.002268134216826997, val_loss: 0.003661077587228072
epochs 7/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.002168076759890506, val_loss: 0.0036379546245658085
epochs 8/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0021761757652520347, val_loss: 0.00361524362264103
epochs 9/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.002124878853608511, val_loss: 0.003592499781792101
epochs 10/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0020921133385088885, val_loss: 0.003568790710874294
epochs 11/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0021389551142132596, val_loss: 0.003545670495613625
epochs 12/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0021708593850857335, val_loss: 0.0035220944543222065
epochs 13/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0020225771935656668, val_loss: 0.003499093757158047
epochs 14/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0020600692957247558, val_loss: 0.00347601012326777
epochs 15/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0020505385595912997, val_loss: 0.003453349410311172
epochs 16/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0021826993514734664, val_loss: 0.0034314591217001803
epochs 17/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0020972709845457423, val_loss: 0.003408715856800738
epochs 18/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.002055843605806953, val_loss: 0.0033859497034236003
epochs 19/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0020226136462664916, val_loss: 0.0033636349253356457
epochs 20/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.001991884682425543, val_loss: 0.003343096520065477
epochs 21/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.002078315842357513, val_loss: 0.003322666493783656
epochs 22/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.001975626576887934, val_loss: 0.003302137531634224
epochs 23/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0019326446810737253, val_loss: 0.0032814157734576024
epochs 24/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.001992144185044852, val_loss: 0.0032604475211548177
epochs 25/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0020180506447918323, val_loss: 0.0032402112785922853
epochs 26/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0018420131742268016, val_loss: 0.0032204790383969484
epochs 27/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.001937460842983503, val_loss: 0.0032007575672315922
epochs 28/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0018596379331460124, val_loss: 0.0031811629238195326
epochs 29/70

[I 2024-01-26 23:17:41,204] Trial 10 pruned.

Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0020325944961146697, val_loss: 0.0031625155800659405
epochs 30/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0019562399480491876, val_loss: 0.0031452794583808437
epochs 31/70
Current Learning Rate: 1.1106222781889914e-06
train_loss: 0.0019105154101883895, val_loss: 0.0031270929783778754
epochs 32/70
Starting fold 1:
epochs 1/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.038995864405296746, val_loss: 0.0017670244205203888
epochs 2/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.004798123193904757, val_loss: 0.0012121491360870239
epochs 3/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0035353841627702902, val_loss: 0.0020907680571422373
epochs 4/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.002305923466644201, val_loss: 0.0017276233393012693
epochs 5/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0017290841022163238, val_loss: 0.001167159346790102
epochs 6/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0017426577359928113, val_loss: 0.002260851565944521
epochs 7/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0016198558322350054, val_loss: 0.0012928822350467702
epochs 8/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0017563476668376672, val_loss: 0.0023206343004283938
epochs 9/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0015602391188670145, val_loss: 0.0015521239256486297
epochs 10/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0015248967389772205, val_loss: 0.0017130890015610739
epochs 11/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.002126677891264032, val_loss: 0.00312883738967541
epochs 12/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0017200143486996622, val_loss: 0.0012299139702104424
epochs 13/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0017441793798321956, val_loss: 0.0025077781186586146
epochs 14/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0016922808858860089, val_loss: 0.0016286360173437156
epochs 15/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0013315435976868398, val_loss: 0.0015903288847766816
epochs 16/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0014007959110466273, val_loss: 0.011817672824192988
epochs 17/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.002643648721277714, val_loss: 0.001247089390802246
epochs 18/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.001688880867349278, val_loss: 0.004556977016067034
epochs 19/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0025751385482420262, val_loss: 0.0012418403326974888
epochs 20/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0015941185300777617, val_loss: 0.0012113219972601846
epochs 21/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0011909958079310231, val_loss: 0.0026629174508056358
epochs 22/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0005713501278813438, val_loss: 0.003873933850493478
epochs 23/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0006473209557282787, val_loss: 0.004824335331489381
epochs 24/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0008024353521728986, val_loss: 0.002771270918463798
epochs 25/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0007879346710213117, val_loss: 0.0010735645865727413
epochs 26/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0004825401490578722, val_loss: 0.0015097160198676743
epochs 27/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0004524979334459395, val_loss: 0.0019012544500200373
epochs 28/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0003771778373782964, val_loss: 0.001512323932317821
epochs 29/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00036863892042004554, val_loss: 0.0023802884517384595
epochs 30/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0003892589265505146, val_loss: 0.0013044728211274272
epochs 31/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00027545639750314876, val_loss: 0.0013343268153747838
epochs 32/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00026567891710376564, val_loss: 0.0013439212276257183
epochs 33/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00025736899865717676, val_loss: 0.0012002709431965883
epochs 34/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00025281567811218434, val_loss: 0.0011500086396393416
epochs 35/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.000242535548443955, val_loss: 0.001164794086454142
epochs 36/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0002410155148122852, val_loss: 0.0011121238649234569
epochs 37/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00023376143278590846, val_loss: 0.0017235322953446915
epochs 38/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00034444918534350826, val_loss: 0.0018628030169853254
epochs 39/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00033785648487728875, val_loss: 0.0013647374010791905
epochs 40/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00020653328048004033, val_loss: 0.0011143522223727288
epochs 41/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00021880772929810184, val_loss: 0.0008880452350958398
epochs 42/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0002942716898886781, val_loss: 0.0009950037065305209
epochs 43/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00018099112884987047, val_loss: 0.0012220188031757348
epochs 44/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00021348812772071382, val_loss: 0.0014649815036376055
epochs 45/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0002133370838955192, val_loss: 0.0013212307429823437
epochs 46/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00020165419065099405, val_loss: 0.0009329577546419674
epochs 47/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0002666258960073863, val_loss: 0.001023966182133575
epochs 48/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0003149018809046155, val_loss: 0.0015060029654322487
epochs 49/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00024096349500867195, val_loss: 0.0033035998808612164
epochs 50/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0008018455942970161, val_loss: 0.002821651572900775
epochs 51/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0008304995337599202, val_loss: 0.0007586295342710065
epochs 52/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0005810448748218876, val_loss: 0.001847182385819523
epochs 53/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00046722666700493154, val_loss: 0.0021675928606112536
epochs 54/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0004038393961596548, val_loss: 0.0008806995762585614
epochs 55/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00027856958017525213, val_loss: 0.0009829161872499084
epochs 56/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00032256737666964334, val_loss: 0.0017736088913424236
epochs 57/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0002672311640038204, val_loss: 0.0014443022652382129
epochs 58/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0002219206174853944, val_loss: 0.0009195979096387562
epochs 59/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00022255574616505518, val_loss: 0.0010106004774570465
epochs 60/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00021420114276942943, val_loss: 0.0015356067396504315
epochs 61/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00020097639315185675, val_loss: 0.0012696473797979323
epochs 62/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00017692565567191003, val_loss: 0.0011797851530565438
epochs 63/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00017185939328843042, val_loss: 0.0015889535192400218
epochs 64/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0001831626333449477, val_loss: 0.0015531005209164792
epochs 65/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00020081046746590322, val_loss: 0.0015329746039290178
epochs 66/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00017517919684331373, val_loss: 0.0012886111094542827
epochs 67/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00018515972494098702, val_loss: 0.0016696124202816894
epochs 68/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00021198925318649824, val_loss: 0.002080826191109066
epochs 69/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00025485755345710604, val_loss: 0.002072294750005791
epochs 70/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.00025490602435495116, val_loss: 0.002379058008572381
epochs 71/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0003299327730354363, val_loss: 0.0015802049721395106
epochs 72/145
Epoch 00072: reducing learning rate of group 0 to 3.2147e-02.
Current Learning Rate: 0.032146911816641296
train_loss: 0.0003224321807226117, val_loss: 0.0010114548194810355
epochs 73/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.0002306891710950846, val_loss: 0.0007379461061454525
epochs 74/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00025767526776211236, val_loss: 0.0011058360733410442
epochs 75/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00021377366769899565, val_loss: 0.0014578266890327397
epochs 76/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00017569334365697087, val_loss: 0.001324502760421877
epochs 77/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00016382877381003805, val_loss: 0.0012357621557863526
epochs 78/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.000147460921480639, val_loss: 0.0011449402835416167
epochs 79/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00014979621842748633, val_loss: 0.0010522859327274522
epochs 80/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00017089747707359492, val_loss: 0.0011562390467397083
epochs 81/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00015283437219056252, val_loss: 0.0014832803152354532
epochs 82/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.0001622829685833207, val_loss: 0.001832614514339519
epochs 83/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00016103890896039573, val_loss: 0.0012846794598245699
epochs 84/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00014700221554927626, val_loss: 0.0013282606310799326
epochs 85/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00013540055975011598, val_loss: 0.001796060978238912
epochs 86/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.0001591158478971154, val_loss: 0.0012600132625697083
epochs 87/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00015212174276760045, val_loss: 0.0012900854136157585
epochs 88/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00014181523553193792, val_loss: 0.0009631135013861287
epochs 89/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00017633084307338944, val_loss: 0.0010614205476533818
epochs 90/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.0001604223706587953, val_loss: 0.0010861540979117546
epochs 91/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00013774401120731215, val_loss: 0.0013262084685266018
epochs 92/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00015874046443250815, val_loss: 0.0014036690791774738
epochs 93/145
Current Learning Rate: 0.032146911816641296
train_loss: 0.00016697905888768698, val_loss: 0.0018285229336470366
epochs 94/145
Epoch 00094: reducing learning rate of group 0 to 2.6478e-02.
Current Learning Rate: 0.02647754338284619
train_loss: 0.00021079923355596532, val_loss: 0.0026903424681605477
epochs 95/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00025601719236491543, val_loss: 0.0021684092408242196
epochs 96/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00017702682920284324, val_loss: 0.000829510757160422
epochs 97/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00023874469269158957, val_loss: 0.0007257175227431091
epochs 98/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00021486736245845495, val_loss: 0.001218495046487078
epochs 99/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00015160605505929868, val_loss: 0.0016624574880360773
epochs 100/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00015218757938495592, val_loss: 0.0025361409692681936
epochs 101/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00024297659026495622, val_loss: 0.002334926334994012
epochs 102/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00020803765092798705, val_loss: 0.0014750702778416637
epochs 103/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00024351479438145793, val_loss: 0.0011353418623146257
epochs 104/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00016205670985264557, val_loss: 0.0009754374822430117
epochs 105/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00015262457619476328, val_loss: 0.0016152155561078535
epochs 106/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00013636427806647445, val_loss: 0.0018899140413850546
epochs 107/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00014061931571249212, val_loss: 0.0023032611003145575
epochs 108/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00018953945679976115, val_loss: 0.0019338817795199392
epochs 109/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00015738004187465106, val_loss: 0.001336973734616645
epochs 110/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00014205922979224276, val_loss: 0.0009684076551102886
epochs 111/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00016194323420916734, val_loss: 0.0010699472843522305
epochs 112/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00015130961642410655, val_loss: 0.001246638317886544
epochs 113/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00011909416800910166, val_loss: 0.0013475889670907667
epochs 114/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00012104774715752635, val_loss: 0.0018366916246074986
epochs 115/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.00013369296016447295, val_loss: 0.001918559770810565
epochs 116/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.0001399701589482567, val_loss: 0.0026146610457401134
epochs 117/145
Current Learning Rate: 0.02647754338284619
train_loss: 0.0002165325070228918, val_loss: 0.0019897832743529425
epochs 118/145
Epoch 00118: reducing learning rate of group 0 to 2.1808e-02.
Current Learning Rate: 0.021808014019797338
train_loss: 0.0001278744390124063, val_loss: 0.0016193675263294655
epochs 119/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00011110107340133063, val_loss: 0.0018217834601129748
epochs 120/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.000122074312055606, val_loss: 0.0018631654546449059
epochs 121/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00011648949967868823, val_loss: 0.0017542615637036138
epochs 122/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00010862090371359189, val_loss: 0.0018265398053795491
epochs 123/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00010353091653853067, val_loss: 0.001344471202403503
epochs 124/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00012662583528588966, val_loss: 0.0010888932257474056
epochs 125/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00017911850552895645, val_loss: 0.0010464001854415983
epochs 126/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.000142590410465154, val_loss: 0.0017143300035968422
epochs 127/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.0001180330631062756, val_loss: 0.0017727198397838755
epochs 128/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00011060799014031594, val_loss: 0.002131295037504874
epochs 129/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.0001233281521356395, val_loss: 0.0017347017425651612
epochs 130/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.0001255293139317808, val_loss: 0.0015511930123657772
epochs 131/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00011943268607290903, val_loss: 0.0013730354417164467
epochs 132/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00012655144570376968, val_loss: 0.0010615869746911095
epochs 133/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00019046361110093514, val_loss: 0.0013157792211706308
epochs 134/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00015113904806448293, val_loss: 0.001273108774330467
epochs 135/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00014448545001582, val_loss: 0.0014303388607100045
epochs 136/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00012351806964081908, val_loss: 0.0012868382134719899
epochs 137/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00013741196775012406, val_loss: 0.0014828308528338217
epochs 138/145
Current Learning Rate: 0.021808014019797338
train_loss: 0.00013357459105655403, val_loss: 0.00113720291870107
epochs 139/145
Epoch 00139: reducing learning rate of group 0 to 1.7962e-02.
Current Learning Rate: 0.017961994004164067
train_loss: 0.0001757413430344681, val_loss: 0.0010626991193643527
epochs 140/145
Current Learning Rate: 0.017961994004164067
train_loss: 0.00019223500176418672, val_loss: 0.0020803045034163484
epochs 141/145
Current Learning Rate: 0.017961994004164067
train_loss: 0.00018076257141441793, val_loss: 0.0028340898160087434
epochs 142/145
Current Learning Rate: 0.017961994004164067
train_loss: 0.00019644488041338168, val_loss: 0.0022964759558243186
epochs 143/145
Current Learning Rate: 0.017961994004164067
train_loss: 0.00016842602742958421, val_loss: 0.0011663531933568025
epochs 144/145
Current Learning Rate: 0.017961994004164067
train_loss: 0.00016762810306605196, val_loss: 0.001211202047814272
epochs 145/145
Current Learning Rate: 0.017961994004164067
train_loss: 0.0001444654952042344, val_loss: 0.0020058569578012744
Starting fold 2:
epochs 1/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.005165872166827811, val_loss: 0.053159574478080396
epochs 2/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.001636104879741508, val_loss: 0.05170439401347386
epochs 3/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0020190758517281593, val_loss: 0.035979660551406834
epochs 4/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0017222527488085784, val_loss: 0.035239012519779955
epochs 5/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.002086268481492114, val_loss: 0.044843416857092006
epochs 6/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0015713463264738063, val_loss: 0.037631533883119885
epochs 7/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0014756446155891017, val_loss: 0.05079613035838855
epochs 8/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0022798502217292, val_loss: 0.03225988348651873
epochs 9/145
Current Learning Rate: 0.039030204743859605
train_loss: 0.0019437668557082744, val_loss: 0.04368744917998189
epochs 10/145
Current Learning Rate: 0.039030204743859605

[I 2024-01-26 23:18:39,196] Trial 11 finished with value: 0.044525780874623076 and parameters: {'batch_size': 53, 'epochs': 145, 'hidden_size': 64, 'learning_rate': 0.039030204743859605, 'dropout_prob': 0.12085581542533387, 'weight_decay': 3.535761691923612e-05, 'lr_step_size': 20, 'gamma': 0.8236418954911782, 'conv_channels': 16, 'kernel_size': 6, 'num_layers': 1, 'pool_size': 5, 'stride': 2}. Best is trial 1 with value: 0.010049154356568352.

Current Learning Rate: 0.017961994004164067
train_loss: 0.0019998844345345307, val_loss: 0.004534340316527768
Mean validation loss: 0.044525780874623076
Starting fold 1:
epochs 1/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.32186847226081516, val_loss: 0.003963943912745699
epochs 2/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.007586587976517254, val_loss: 0.0014010445092265543
epochs 3/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0024036179076095945, val_loss: 0.0011537152036142193
epochs 4/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0019621606928443436, val_loss: 0.0022137755564855116
epochs 5/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0014716155955715007, val_loss: 0.001776751677358621
epochs 6/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0012896914706001744, val_loss: 0.0018197796282995687
epochs 7/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0013020083443016598, val_loss: 0.0019850142333828107
epochs 8/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0011833832498125143, val_loss: 0.006132157548869911
epochs 9/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0014140466390496218, val_loss: 0.0020662779343853656
epochs 10/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0013332021560544442, val_loss: 0.009669029570527767
epochs 11/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0023020983790047467, val_loss: 0.0013523103509980596
epochs 12/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0011732459230667078, val_loss: 0.005463764122932365
epochs 13/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.02933131738957998, val_loss: 0.006110388753739627
epochs 14/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0029845076533475596, val_loss: 0.0017562187414640856
epochs 15/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0020933416567889876, val_loss: 0.0012960619774132378
epochs 16/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0018313774116043198, val_loss: 0.0014878840458358786
epochs 17/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0017731428532371002, val_loss: 0.0019206060660316756
epochs 18/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0016280249827296325, val_loss: 0.0013603225359570628
epochs 19/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0017904256642060844, val_loss: 0.0018008717372523326
epochs 20/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.001604101566083141, val_loss: 0.0017754483055078278
epochs 21/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0014867589214669638, val_loss: 0.0013210794827165572
epochs 22/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.001018499702484788, val_loss: 0.00138491850505632
epochs 23/78
Epoch 00023: reducing learning rate of group 0 to 3.2339e-02.
Current Learning Rate: 0.0323386689096436
train_loss: 0.0009765776202058124, val_loss: 0.001189292055603705
epochs 24/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0008812850920213877, val_loss: 0.0009966940521017502
epochs 25/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0006940970168216154, val_loss: 0.0012255157252136421
epochs 26/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0004928470481995886, val_loss: 0.0019289923433557545
epochs 27/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0005110732526334591, val_loss: 0.001872756762283021
epochs 28/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0004989879752668601, val_loss: 0.002017614076306161
epochs 29/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0005695232776863696, val_loss: 0.001881654336313276
epochs 30/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00038544117537400637, val_loss: 0.0008155158080626279
epochs 31/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0004053910754584266, val_loss: 0.0014851252131752278
epochs 32/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.000308593187257525, val_loss: 0.0014123413831265152
epochs 33/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.000292599811923298, val_loss: 0.0011188633393765868
epochs 34/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0002509300140541439, val_loss: 0.0015820931110187974
epochs 35/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00026071364792235393, val_loss: 0.0013504762141230075
epochs 36/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00024623891306538623, val_loss: 0.0007522328609698698
epochs 37/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0004342147413377748, val_loss: 0.0021840664650019455
epochs 38/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0002956260338051882, val_loss: 0.0011907119521454566
epochs 39/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0002487405776168759, val_loss: 0.0007117644195922798
epochs 40/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0003690269102471096, val_loss: 0.0010277663397382161
epochs 41/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00029478676695266344, val_loss: 0.0015456256511817246
epochs 42/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00028473746956718203, val_loss: 0.002139541217567105
epochs 43/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00026523936248850076, val_loss: 0.0014314230335386177
epochs 44/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00024962914888563225, val_loss: 0.001417044444181221
epochs 45/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00025851277015662117, val_loss: 0.000723906220120721
epochs 46/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00024062017626803075, val_loss: 0.0009862969393572328
epochs 47/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00023003710796872743, val_loss: 0.0018177292536404963
epochs 48/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0002346687176644704, val_loss: 0.0010521771079909645
epochs 49/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0003488620069172037, val_loss: 0.0007054505382639993
epochs 50/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0003554785268773374, val_loss: 0.0013478297709585412
epochs 51/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0006631814082012217, val_loss: 0.0007679771975074944
epochs 52/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0008333932003312696, val_loss: 0.0007153370284389606
epochs 53/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0007205776430629683, val_loss: 0.0011753948684169078
epochs 54/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00025598890581597135, val_loss: 0.0012875812679627224
epochs 55/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00022962991237076685, val_loss: 0.0014052984078022602
epochs 56/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00018826828569504678, val_loss: 0.0018447234472995133
epochs 57/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00020059384152869153, val_loss: 0.0012579532548491108
epochs 58/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00018154509330327672, val_loss: 0.0018083473624612549
epochs 59/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00019026234773551358, val_loss: 0.0016011647132568453
epochs 60/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0002005887385549661, val_loss: 0.0014154327788243168
epochs 61/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00017905915301525966, val_loss: 0.0016401824106364266
epochs 62/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.0001578592215082608, val_loss: 0.0013454134974285568
epochs 63/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00014993983836336013, val_loss: 0.0012808717799520021
epochs 64/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00015333861121785288, val_loss: 0.0017346770134999564
epochs 65/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00021570857811878483, val_loss: 0.001064930163863066
epochs 66/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00014128902031715321, val_loss: 0.0016076373781910853
epochs 67/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00013956649678508064, val_loss: 0.0015004066646246142
epochs 68/78
Current Learning Rate: 0.0323386689096436
train_loss: 0.00016838538626631674, val_loss: 0.0017492812745714267
epochs 69/78
Epoch 00069: reducing learning rate of group 0 to 2.8835e-02.
Current Learning Rate: 0.028835462718036043
train_loss: 0.00021797177438489406, val_loss: 0.0015512542884894892
epochs 70/78
Current Learning Rate: 0.028835462718036043
train_loss: 0.00014772456699191887, val_loss: 0.0018074956881862722
epochs 71/78
Current Learning Rate: 0.028835462718036043
train_loss: 0.000154795700808264, val_loss: 0.0010270423865509466
epochs 72/78
Current Learning Rate: 0.028835462718036043
train_loss: 0.0001673028211179802, val_loss: 0.002275179812415062
epochs 73/78
Current Learning Rate: 0.028835462718036043
train_loss: 0.00019660724359901475, val_loss: 0.0010198737139274416
epochs 74/78
Current Learning Rate: 0.028835462718036043
train_loss: 0.00015221944482427237, val_loss: 0.0016901281987022805
epochs 75/78
Current Learning Rate: 0.028835462718036043
train_loss: 0.00012404844766072194, val_loss: 0.0007622883403918853
epochs 76/78
Current Learning Rate: 0.028835462718036043
train_loss: 0.00027229350679063875, val_loss: 0.002464553446655995
epochs 77/78
Current Learning Rate: 0.028835462718036043
train_loss: 0.0002020582174162356, val_loss: 0.0013825372124924079
epochs 78/78
Current Learning Rate: 0.028835462718036043
train_loss: 0.0002278311611965029, val_loss: 0.000602988935210497
Starting fold 2:
epochs 1/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.007376287868828513, val_loss: 0.014339890252602728
epochs 2/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0028137707947998455, val_loss: 0.04533996854565645
epochs 3/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0026156105082727186, val_loss: 0.036586620590012324
epochs 4/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0016815537402994538, val_loss: 0.048799440754871616
epochs 5/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.001470993364407485, val_loss: 0.0390844503711713
epochs 6/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.001945059601903746, val_loss: 0.04044250026345253
epochs 7/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0014672349974525307, val_loss: 0.051789345121697375
epochs 8/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.001659487718777535, val_loss: 0.03627248929911538
epochs 9/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.001912350970087573, val_loss: 0.05075657038312209
epochs 10/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0017683468382241891, val_loss: 0.03694725320919564
epochs 11/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0016235066171870322, val_loss: 0.049277319661096525
epochs 12/78

[I 2024-01-26 23:18:44,152] Trial 12 pruned.

Current Learning Rate: 0.03626747789947646
train_loss: 0.0015607065040201538, val_loss: 0.03901775753811786
epochs 13/78
Current Learning Rate: 0.03626747789947646
train_loss: 0.0015334000435694563, val_loss: 0.04552387554002436
epochs 14/78
Starting fold 1:
epochs 1/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.8324689248785082, val_loss: 0.03517662596545721
epochs 2/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.017604143329356847, val_loss: 0.001963759049479114
epochs 3/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0025081791939507974, val_loss: 0.0018652822883603603
epochs 4/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.00264886400882939, val_loss: 0.002060054817334994
epochs 5/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002820407371281793, val_loss: 0.005224921696476246
epochs 6/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.017038851037719533, val_loss: 0.07338276301559649
epochs 7/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.04455775640978429, val_loss: 0.001413425819268205
epochs 8/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0015484179125020378, val_loss: 0.0012729733217336041
epochs 9/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0017123454091090122, val_loss: 0.0024064569397045203
epochs 10/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0016202128357499053, val_loss: 0.002764300296181127
epochs 11/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002445984858480331, val_loss: 0.0034204610341571663
epochs 12/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0026954339057403175, val_loss: 0.0027667656736938577
epochs 13/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.003004027273211824, val_loss: 0.003547354037628362
epochs 14/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0037704529694134467, val_loss: 0.001352344195995676
epochs 15/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0022322309938700574, val_loss: 0.0016538537401509913
epochs 16/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.004271002331944673, val_loss: 0.005140819969145875
epochs 17/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0019369318162238127, val_loss: 0.0015035822681200347
epochs 18/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.006118625360786131, val_loss: 0.00980689147193181
epochs 19/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.004463609511424836, val_loss: 0.001504086940794399
epochs 20/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002412001656270341, val_loss: 0.0012338456284181265
epochs 21/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0016627296670585086, val_loss: 0.0012209706890739893
epochs 22/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0017157210416993813, val_loss: 0.0026603952638412777
epochs 23/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.015765440110484825, val_loss: 0.001235084123541846
epochs 24/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0019213498018583969, val_loss: 0.002375152618869355
epochs 25/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0025826836531785756, val_loss: 0.001604214227317195
epochs 26/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.006792010277460673, val_loss: 0.0035209530216984844
epochs 27/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.001787692666326429, val_loss: 0.003532380299446614
epochs 28/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.010068725762692722, val_loss: 0.0020702198981062364
epochs 29/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.001814218771055733, val_loss: 0.0012581047295641742
epochs 30/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0030708058957794777, val_loss: 0.0012258243226250143
epochs 31/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0022752038779129324, val_loss: 0.0017170203255342418
epochs 32/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.003492205115770431, val_loss: 0.006116621068825847
epochs 33/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.004266533285599986, val_loss: 0.0026928002602959935
epochs 34/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002328694174311271, val_loss: 0.003644211607446012
epochs 35/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0020154178939073494, val_loss: 0.02566168731764743
epochs 36/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.009698795847055552, val_loss: 0.0013065703458299762
epochs 37/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0021328865231848076, val_loss: 0.0014268290833570063
epochs 38/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002002336028473158, val_loss: 0.0012503270537739522
epochs 39/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0021798732604733423, val_loss: 0.0036564686262097797
epochs 40/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002204679146311001, val_loss: 0.009409442387129131
epochs 41/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.021079296493706736, val_loss: 0.0038174763517944436
epochs 42/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0024993144625209663, val_loss: 0.0012505788564387906
epochs 43/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.001610277421576412, val_loss: 0.0025291076346643663
epochs 44/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0015715192782839661, val_loss: 0.0013255230861863023
epochs 45/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.00411464342920992, val_loss: 0.0038293593220020596
epochs 46/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0051716295628514335, val_loss: 0.0013753027691947002
epochs 47/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002262509023574622, val_loss: 0.007061880871065353
epochs 48/119
Epoch 00048: reducing learning rate of group 0 to 7.3149e-02.
Current Learning Rate: 0.07314945203557961
train_loss: 0.0025243587497817844, val_loss: 0.0035045118340732238
epochs 49/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0017495552286211596, val_loss: 0.029340592477666703
epochs 50/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.022039719962661988, val_loss: 0.0015959981755402526
epochs 51/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0017069122349647316, val_loss: 0.001270995796413014
epochs 52/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0018177051697612593, val_loss: 0.006749372542100517
epochs 53/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.005557998780798363, val_loss: 0.0021296110371813964
epochs 54/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0020422728701592666, val_loss: 0.0015062151770842702
epochs 55/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0023285469616224105, val_loss: 0.001322335835337933
epochs 56/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0026116312653022378, val_loss: 0.0014998710346653273
epochs 57/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.003361886305930583, val_loss: 0.010841826673008894
epochs 58/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.005112125896113483, val_loss: 0.008887259534707195
epochs 59/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.003803752134799173, val_loss: 0.001317851109381177
epochs 60/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0016811588362447526, val_loss: 0.0013244999155990387
epochs 61/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.001835004142240474, val_loss: 0.016152686174762877
epochs 62/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.006232781365121666, val_loss: 0.0012889661764922112
epochs 63/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0015941299792183073, val_loss: 0.0014259375435741325
epochs 64/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0015569451191511593, val_loss: 0.0011419817572459578
epochs 65/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.004854087404122478, val_loss: 0.003655868962309078
epochs 66/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.005078068485875663, val_loss: 0.001247725418866857
epochs 67/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0013225344040333049, val_loss: 0.002021156041882932
epochs 68/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0020412695949505034, val_loss: 0.0023058819535531497
epochs 69/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.003059698615566288, val_loss: 0.0026360701990166776
epochs 70/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0018299570432741587, val_loss: 0.0036589146395655057
epochs 71/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0018685194100008199, val_loss: 0.0033836910672681896
epochs 72/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0020882737063067525, val_loss: 0.0017228625579982211
epochs 73/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0011739172525458822, val_loss: 0.0013169486529046768
epochs 74/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.37075814846658, val_loss: 0.23120386396583759
epochs 75/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.1453612309047266, val_loss: 0.029048985007562134
epochs 76/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.03368309378918064, val_loss: 0.020070721581578254
epochs 77/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.020882459955387993, val_loss: 0.027715393136206426
epochs 78/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.027181922556146196, val_loss: 0.005041654956968207
epochs 79/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.015132779892730085, val_loss: 0.009595812788527263
epochs 80/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.011095272695743725, val_loss: 0.0020314207827476292
epochs 81/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.005517132609690491, val_loss: 0.0014473023472084223
epochs 82/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.009755243517850575, val_loss: 0.0026968521053755755
epochs 83/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0034959354903548955, val_loss: 0.0012384862081441833
epochs 84/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.002359166785486435, val_loss: 0.002604078316423846
epochs 85/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.00317837006387938, val_loss: 0.002422329609429366
epochs 86/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.005122483476359201, val_loss: 0.0078039967847105705
epochs 87/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0033474391975783203, val_loss: 0.0018052910289138948
epochs 88/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.002332603018485794, val_loss: 0.001257378177864379
epochs 89/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.001927336158941647, val_loss: 0.0012294655598356927
epochs 90/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.01014424156593649, val_loss: 0.008759414904603833
epochs 91/119
Epoch 00091: reducing learning rate of group 0 to 5.4969e-02.
Current Learning Rate: 0.0549694113299799
train_loss: 0.002505808833398317, val_loss: 0.0015756188095302174
epochs 92/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0023629375684418178, val_loss: 0.0027858226094394922
epochs 93/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0019784399786179786, val_loss: 0.001548321331287489
epochs 94/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0015877032076547805, val_loss: 0.002615253249869535
epochs 95/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0018017552394763027, val_loss: 0.002402364868229549
epochs 96/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.005217963971785809, val_loss: 0.001763662290269215
epochs 97/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.00148008225461174, val_loss: 0.002175921041788043
epochs 98/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.004298826858499333, val_loss: 0.002172213616339784
epochs 99/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0033006115252838322, val_loss: 0.006162125244736671
epochs 100/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0030319686709462026, val_loss: 0.002957602302347751
epochs 101/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0017967598555658601, val_loss: 0.0013714806630129093
epochs 102/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0025714380372511714, val_loss: 0.002101600113765974
epochs 103/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0019987966117792225, val_loss: 0.0031476126836710856
epochs 104/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0018560044038550634, val_loss: 0.0032651716929027125
epochs 105/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0015520238930261448, val_loss: 0.004481137901740639
epochs 106/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.00935828716151024, val_loss: 0.006662573586953314
epochs 107/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0026613360258603566, val_loss: 0.0012539065081479126
epochs 108/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.001834002301391018, val_loss: 0.002852781420867694
epochs 109/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0018429498849926811, val_loss: 0.0013373382297638607
epochs 110/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0015909212911011357, val_loss: 0.004687055717467478
epochs 111/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0025230792792219864, val_loss: 0.00128730023524871
epochs 112/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.001919087104646391, val_loss: 0.0014699788592559726
epochs 113/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.008450677487263946, val_loss: 0.007994457285263037
epochs 114/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.005252479839040653, val_loss: 0.004398254506093891
epochs 115/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0015676263658525912, val_loss: 0.0012663253377755417
epochs 116/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.001669577060659465, val_loss: 0.0030584486838626233
epochs 117/119
Current Learning Rate: 0.0549694113299799
train_loss: 0.0016206630456604455, val_loss: 0.0018746920628473162
epochs 118/119
Epoch 00118: reducing learning rate of group 0 to 4.1308e-02.
Current Learning Rate: 0.041307707684465095
train_loss: 0.0024268182840100246, val_loss: 0.0011457613228183043
epochs 119/119
Current Learning Rate: 0.041307707684465095
train_loss: 0.0012683363802927104, val_loss: 0.001122435225222848
Starting fold 2:
epochs 1/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.6263322036786887, val_loss: 0.04483009070942277
epochs 2/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.029582059981399463, val_loss: 0.15456451271709643
epochs 3/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.016467588372822656, val_loss: 0.022309888041529218
epochs 4/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.010035126396503887, val_loss: 0.019352884071045802
epochs 5/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.007420471952737946, val_loss: 0.03594187137327696
epochs 6/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.00664973518394522, val_loss: 0.04347779068507646
epochs 7/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.005488726606984672, val_loss: 0.03321715308059203
epochs 8/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0030617299808287307, val_loss: 0.06902102886846191
epochs 9/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.00277704529121126, val_loss: 0.0555727508115141
epochs 10/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.004219394875690341, val_loss: 0.04894296146537128
epochs 11/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002866766381224519, val_loss: 0.05896228767539326
epochs 12/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0024328907669864987, val_loss: 0.18790655371389892
epochs 13/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.015316788710065579, val_loss: 0.047303889417334606
epochs 14/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0016429311657128365, val_loss: 0.044374533781879826
epochs 15/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.018894193245490132, val_loss: 0.02421823322380844
epochs 16/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0023304640352235814, val_loss: 0.03855366820567532
epochs 17/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0025008370352320765, val_loss: 0.057724381708785105
epochs 18/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0026584493400725094, val_loss: 0.14441217325235667
epochs 19/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.006051484953710123, val_loss: 0.037273951482615975
epochs 20/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0023739450966547195, val_loss: 0.0417964334158521
epochs 21/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0035143086080145288, val_loss: 0.047995106875896455
epochs 22/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0025314098273060822, val_loss: 0.0456392937977063
epochs 23/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0022561383164046624, val_loss: 0.08420897545783143
epochs 24/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.005804974280640875, val_loss: 0.020339353578655343
epochs 25/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0027734353096763556, val_loss: 0.057171898766567836
epochs 26/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002470357467322365, val_loss: 0.11155970520094821
epochs 27/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.004373755453056411, val_loss: 0.04331097673428686
epochs 28/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.0019523411229448882, val_loss: 0.0643889527179693
epochs 29/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.003949264441861918, val_loss: 0.058367525276384856
epochs 30/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.002311340569959659, val_loss: 0.05583312154600495
epochs 31/119
Epoch 00031: reducing learning rate of group 0 to 7.3149e-02.
Current Learning Rate: 0.07314945203557961
train_loss: 0.0034841008925516354, val_loss: 0.04658266556890387
epochs 32/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0018157658338742821, val_loss: 0.049717886040085243
epochs 33/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.002331777648559134, val_loss: 0.065569327457955
epochs 34/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.002569939854162696, val_loss: 0.04306725957675984
epochs 35/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.002478135720900211, val_loss: 0.04773938895056122
epochs 36/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.002271110049179314, val_loss: 0.0567809239814156
epochs 37/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0024048398328503887, val_loss: 0.04739025066557683
epochs 38/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.0025950195212652415, val_loss: 0.04463604861184171
epochs 39/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.002229831269084427, val_loss: 0.053663291311577745
epochs 40/119
Current Learning Rate: 0.07314945203557961
train_loss: 0.002298558913293834, val_loss: 0.05563814973360614
epochs 41/119

[I 2024-01-26 23:19:00,813] Trial 13 pruned.

Current Learning Rate: 0.09734218001689338
train_loss: 0.018535777063746203, val_loss: 0.2731738510884737
epochs 33/119
Current Learning Rate: 0.09734218001689338
train_loss: 0.014181842576516302, val_loss: 0.23333332271952378
epochs 34/119
Starting fold 1:
epochs 1/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.007508828242211357, val_loss: 0.003057495045083526
epochs 2/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0015419821947273847, val_loss: 0.00204178803955744
epochs 3/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0009367287085440599, val_loss: 0.003403792753325481
epochs 4/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0005653327257421456, val_loss: 0.0035737519667140747
epochs 5/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0005827040664275716, val_loss: 0.0011915074446924815
epochs 6/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00041671082588819495, val_loss: 0.001451935559070032
epochs 7/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0003377932646942913, val_loss: 0.0021357173872131267
epochs 8/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0003107857693593312, val_loss: 0.001964724848757645
epochs 9/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00025111909980248464, val_loss: 0.0020414136068307256
epochs 10/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00025157268843797377, val_loss: 0.002151158394439048
epochs 11/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0002801496282029946, val_loss: 0.0027785420123683778
epochs 12/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00032748752189371244, val_loss: 0.0018164183625853376
epochs 13/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00028349310848984477, val_loss: 0.0020357565562191763
epochs 14/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00019925771630369127, val_loss: 0.0018213897434945561
epochs 15/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00022475451964725692, val_loss: 0.0011926517987280692
epochs 16/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00020252107527707458, val_loss: 0.001272115152402732
epochs 17/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00020709398790801827, val_loss: 0.001572743988301801
epochs 18/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00016514115750875422, val_loss: 0.001324589317664504
epochs 19/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0002846743713139164, val_loss: 0.0010452725379237612
epochs 20/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0002553803543713385, val_loss: 0.0009294413269105319
epochs 21/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0002763973738949158, val_loss: 0.000980580609144741
epochs 22/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00027535480974046024, val_loss: 0.0014894119892759543
epochs 23/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00024666481369518134, val_loss: 0.0016887848927198271
epochs 24/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00018676274508164312, val_loss: 0.0016697956818940217
epochs 25/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00013828342347742842, val_loss: 0.0017443337232658737
epochs 26/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0001201453344133609, val_loss: 0.0012498570140451193
epochs 27/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0001599151336306118, val_loss: 0.001206805214506427
epochs 28/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00018989823675885992, val_loss: 0.0012117382604628802
epochs 29/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00015265202432362314, val_loss: 0.0018598413199039274
epochs 30/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.0001759988610406014, val_loss: 0.0017022269336800827
epochs 31/135
Current Learning Rate: 0.006740545250936056
train_loss: 0.00011448132704811685, val_loss: 0.0020839906365022454
epochs 32/135

[I 2024-01-26 23:19:02,694] Trial 14 pruned.

Starting fold 1:
epochs 1/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.008037160770771535, val_loss: 0.011780734164150137
epochs 2/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.007804267409894812, val_loss: 0.011428674133984667
epochs 3/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.007601435727586872, val_loss: 0.011083644677541757
epochs 4/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.007254398506330816, val_loss: 0.010747919481639799
epochs 5/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.007103528234323388, val_loss: 0.010419461381082473
epochs 6/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.006869501823951539, val_loss: 0.010100322741230851
epochs 7/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.006592688425198981, val_loss: 0.009791856533602664
epochs 8/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.006349791789819536, val_loss: 0.009493160483084228
epochs 9/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.006084472958096548, val_loss: 0.009199588309581343
epochs 10/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0058988771352328755, val_loss: 0.008914020593817297
epochs 11/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.005688247513516169, val_loss: 0.008635592740029096
epochs 12/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.005304285523628718, val_loss: 0.00836656253882929
epochs 13/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.005284835050176633, val_loss: 0.00810434654306032
epochs 14/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0050912060407235435, val_loss: 0.007851074934986078
epochs 15/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0048988952154391694, val_loss: 0.007604288187270102
epochs 16/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.004644368304625938, val_loss: 0.007363350125715921
epochs 17/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.004402985562276291, val_loss: 0.007131265432230736
epochs 18/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.00427577845188544, val_loss: 0.00690449407128127
epochs 19/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0041360268712435895, val_loss: 0.006683718949850453
epochs 20/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0040304891679337936, val_loss: 0.006469503199485572
epochs 21/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.003895144666986246, val_loss: 0.00626168915952899
epochs 22/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0036976030880683346, val_loss: 0.006060558106554182
epochs 23/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.003562501762797566, val_loss: 0.005866287322714925
epochs 24/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0034476711034872815, val_loss: 0.005678560503905541
epochs 25/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0033432128851449017, val_loss: 0.005497181275859475
epochs 26/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0031725003102206087, val_loss: 0.0053211439964606574
epochs 27/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.00306813610153959, val_loss: 0.005148238492639441
epochs 28/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0030521091759989137, val_loss: 0.004980737002762524
epochs 29/150

[I 2024-01-26 23:19:04,522] Trial 15 pruned.

Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0028417885977480755, val_loss: 0.004817763532168771
epochs 30/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.0027972739361422625, val_loss: 0.004659390981358133
epochs 31/150
Current Learning Rate: 1.2949642736415988e-05
train_loss: 0.002692763720590033, val_loss: 0.00450867279432714
epochs 32/150
Starting fold 1:
epochs 1/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.006707326582583942, val_loss: 0.001117182255256921
epochs 2/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0017434294997273308, val_loss: 0.0035185818560421467
epochs 3/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0016468698955386092, val_loss: 0.0012972015875244612
epochs 4/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0014711622283548902, val_loss: 0.0013528846596416674
epochs 5/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0013539872291546903, val_loss: 0.002027130783780625
epochs 6/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0012633945903201636, val_loss: 0.001538501041451175
epochs 7/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0011289621102868726, val_loss: 0.0013548380903605568
epochs 8/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.000990257334993466, val_loss: 0.0014311985884744086
epochs 9/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0005045006339634327, val_loss: 0.0017401838160463069
epochs 10/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00041607796447351575, val_loss: 0.0023680354076388633
epochs 11/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0003335758305375317, val_loss: 0.0017870408727934486
epochs 12/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00027479599750796825, val_loss: 0.0010555828492598313
epochs 13/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0002079283011354212, val_loss: 0.001270735011387028
epochs 14/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00021808432249695455, val_loss: 0.0015327529981732368
epochs 15/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0002307651892279912, val_loss: 0.0013235141829538502
epochs 16/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0002029284828734633, val_loss: 0.0009872711717004055
epochs 17/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0001972416732889159, val_loss: 0.0010026133692774334
epochs 18/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00020823993422948805, val_loss: 0.0009691530691557809
epochs 19/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00015355354499709057, val_loss: 0.0010391931466170047
epochs 20/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0001691774071476079, val_loss: 0.0013380527533100623
epochs 21/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00014779652242156627, val_loss: 0.001613648277462313
epochs 22/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00017524222264335933, val_loss: 0.0013724629411866005
epochs 23/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0001720569631097054, val_loss: 0.0013113006042610657
epochs 24/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00011751453137932051, val_loss: 0.0009509408264420927
epochs 25/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00015373669616804508, val_loss: 0.0011282687835199269
epochs 26/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00012699247484928682, val_loss: 0.0015573321081894008
epochs 27/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0001422255231055284, val_loss: 0.0014016587336204555
epochs 28/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0001255411725172675, val_loss: 0.0016598091644578073
epochs 29/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.000131440840624763, val_loss: 0.0015558164235890696
epochs 30/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00014901025784447004, val_loss: 0.0014418534640418855
epochs 31/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00014003332226390116, val_loss: 0.001068077454539506
epochs 32/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0001109793420733982, val_loss: 0.0015976577261952978
epochs 33/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00013059370738981095, val_loss: 0.0022153983284768307
epochs 34/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00019503197683278764, val_loss: 0.00193683673799234
epochs 35/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00016116126559944334, val_loss: 0.0011807325002002088
epochs 36/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0001071088941228625, val_loss: 0.0011141370173151557
epochs 37/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00013523834671727136, val_loss: 0.0009896212661834923
epochs 38/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00010870339955497337, val_loss: 0.0010590767978053343
epochs 39/115
Current Learning Rate: 0.004521743797023824
train_loss: 9.245390499831716e-05, val_loss: 0.0013482911928899978
epochs 40/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00013878259970193826, val_loss: 0.0018813552420684381
epochs 41/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0001442901488381291, val_loss: 0.0018132173113132779
epochs 42/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.0001468698311854448, val_loss: 0.0012283503923467116
epochs 43/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00011131462585916252, val_loss: 0.0009779063004412148
epochs 44/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00011084211981046552, val_loss: 0.001013100744641729
epochs 45/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00012849790226410781, val_loss: 0.0012144474496476744
epochs 46/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00012716637444866233, val_loss: 0.0017999710919531552
epochs 47/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00012193521137018443, val_loss: 0.0016431685990506882
epochs 48/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00010335768992693997, val_loss: 0.001457020609737619
epochs 49/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00010334046179961756, val_loss: 0.001159278081582957
epochs 50/115
Current Learning Rate: 0.004521743797023824
train_loss: 8.941007591171288e-05, val_loss: 0.0011687730929177058
epochs 51/115
Current Learning Rate: 0.004521743797023824
train_loss: 9.707597890060003e-05, val_loss: 0.001146999843369581
epochs 52/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00010350914798388993, val_loss: 0.0012487980757692927
epochs 53/115
Current Learning Rate: 0.004521743797023824
train_loss: 8.679574851779954e-05, val_loss: 0.0013818086529346673
epochs 54/115
Current Learning Rate: 0.004521743797023824
train_loss: 9.30206067431228e-05, val_loss: 0.0011948911705985665
epochs 55/115
Current Learning Rate: 0.004521743797023824
train_loss: 0.00010016512035355462, val_loss: 0.0011582703752394178
epochs 56/115
Current Learning Rate: 0.004521743797023824
train_loss: 8.233458931116682e-05, val_loss: 0.0011508289700079906
epochs 57/115
Epoch 00057: reducing learning rate of group 0 to 3.4515e-03.
Current Learning Rate: 0.003451498177024384
train_loss: 8.38476668210014e-05, val_loss: 0.0012901079363042587
epochs 58/115
Current Learning Rate: 0.003451498177024384
train_loss: 8.990074275061488e-05, val_loss: 0.001002757276996578
epochs 59/115
Current Learning Rate: 0.003451498177024384
train_loss: 9.145928963430618e-05, val_loss: 0.0015463177788708556
epochs 60/115
Current Learning Rate: 0.003451498177024384
train_loss: 0.00010964157608166141, val_loss: 0.001733117951325288
epochs 61/115
Current Learning Rate: 0.003451498177024384
train_loss: 9.328453559550996e-05, val_loss: 0.0011380690511463112
epochs 62/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.230719041361131e-05, val_loss: 0.0013539169939528954
epochs 63/115
Current Learning Rate: 0.003451498177024384
train_loss: 8.116427833508504e-05, val_loss: 0.0016024522176992736
epochs 64/115
Current Learning Rate: 0.003451498177024384
train_loss: 9.053284118540193e-05, val_loss: 0.0013651488299824689
epochs 65/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.707324613492299e-05, val_loss: 0.0011864355704011885
epochs 66/115
Current Learning Rate: 0.003451498177024384
train_loss: 8.963680317576386e-05, val_loss: 0.0015517321145652157
epochs 67/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.564104951023565e-05, val_loss: 0.0015255652282288984
epochs 68/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.420554596281268e-05, val_loss: 0.0013828620094021684
epochs 69/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.627062893190764e-05, val_loss: 0.0013477519540557343
epochs 70/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.444177313836438e-05, val_loss: 0.0014460313954929773
epochs 71/115
Current Learning Rate: 0.003451498177024384
train_loss: 6.757206383075467e-05, val_loss: 0.0014362183987702195
epochs 72/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.610836320581209e-05, val_loss: 0.0014248121603343048
epochs 73/115
Current Learning Rate: 0.003451498177024384
train_loss: 6.371152611743463e-05, val_loss: 0.0014132162078136677
epochs 74/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.458652084766839e-05, val_loss: 0.0017186496468064817
epochs 75/115
Current Learning Rate: 0.003451498177024384
train_loss: 8.477427763864398e-05, val_loss: 0.0016499873508062017
epochs 76/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.607448921924898e-05, val_loss: 0.0011020292172600563
epochs 77/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.912514755796445e-05, val_loss: 0.0013003963058030134
epochs 78/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.37135916623581e-05, val_loss: 0.0014471198971334257
epochs 79/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.698351079230441e-05, val_loss: 0.0014476363706451497
epochs 80/115
Current Learning Rate: 0.003451498177024384
train_loss: 6.508385865201585e-05, val_loss: 0.0014116821724823431
epochs 81/115
Current Learning Rate: 0.003451498177024384
train_loss: 6.710571132747358e-05, val_loss: 0.001358567069186584
epochs 82/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.880670761407696e-05, val_loss: 0.0012020788302547054
epochs 83/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.895501307518173e-05, val_loss: 0.0010902791369804426
epochs 84/115
Current Learning Rate: 0.003451498177024384
train_loss: 8.68559325585681e-05, val_loss: 0.001238897963623075
epochs 85/115
Current Learning Rate: 0.003451498177024384
train_loss: 6.863177297514324e-05, val_loss: 0.0013415266477846
epochs 86/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.602197805872972e-05, val_loss: 0.0016567412469732134
epochs 87/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.07620975414389e-05, val_loss: 0.0017088141267825115
epochs 88/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.331123082334862e-05, val_loss: 0.0013495438340071
epochs 89/115
Current Learning Rate: 0.003451498177024384
train_loss: 7.14328249925625e-05, val_loss: 0.0012218012768579157
epochs 90/115

[I 2024-01-26 23:19:08,945] Trial 16 pruned.

Epoch 00090: reducing learning rate of group 0 to 2.6346e-03.
Current Learning Rate: 0.0026345675917869528
train_loss: 8.282461356812794e-05, val_loss: 0.0010610324036526052
epochs 91/115
Current Learning Rate: 0.0026345675917869528
train_loss: 7.916203168478157e-05, val_loss: 0.0018790432399040775
epochs 92/115
Starting fold 1:
epochs 1/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0038366571583442, val_loss: 0.006395476404577494
epochs 2/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0038785675074905156, val_loss: 0.006378235672845652
epochs 3/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003852992700903039, val_loss: 0.0063610393259870375
epochs 4/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003765571712957401, val_loss: 0.006343914583129318
epochs 5/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0039206931686126874, val_loss: 0.0063268798060323065
epochs 6/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0038334330568384183, val_loss: 0.0063100214704479045
epochs 7/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003804333613401181, val_loss: 0.00629334630150544
epochs 8/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003800062477392586, val_loss: 0.006276088203058431
epochs 9/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0038267810608407383, val_loss: 0.006259128167048881
epochs 10/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003839171474407378, val_loss: 0.006242471369669626
epochs 11/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0038308465412180675, val_loss: 0.006226030217581674
epochs 12/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003797378361617264, val_loss: 0.006209362366873967
epochs 13/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0038332672446574037, val_loss: 0.006193136600287337
epochs 14/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0036997202146602302, val_loss: 0.006176545858187111
epochs 15/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0037598806114769296, val_loss: 0.0061600877707333945
epochs 16/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0037358079081107128, val_loss: 0.006143834422293462
epochs 17/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003761822414143305, val_loss: 0.006127568706870079
epochs 18/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003740321869324697, val_loss: 0.006111373051412796
epochs 19/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003699282039643118, val_loss: 0.0060953059135691115
epochs 20/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003656765946040028, val_loss: 0.00607940645300244
epochs 21/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0036796627247608024, val_loss: 0.006063051972734301
epochs 22/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003661180363575879, val_loss: 0.006046921181443491
epochs 23/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003665073961019516, val_loss: 0.00603086180788906
epochs 24/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003763217824560247, val_loss: 0.006014905541547035
epochs 25/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003557862772753364, val_loss: 0.0059992863943702296
epochs 26/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0036890362536436635, val_loss: 0.005983532323060851
epochs 27/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003649110366639338, val_loss: 0.005967904985147088
epochs 28/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0035716495574697068, val_loss: 0.00595228402434211
epochs 29/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.003618564304748648, val_loss: 0.005937042405926868
epochs 30/81

[I 2024-01-26 23:19:10,695] Trial 17 pruned.

Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0036066519978799317, val_loss: 0.00592129595185581
epochs 31/81
Current Learning Rate: 3.0129270188629495e-06
train_loss: 0.0036331250994025093, val_loss: 0.00590557093781076
epochs 32/81
Starting fold 1:
epochs 1/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00427682507709649, val_loss: 0.005410301325058466
epochs 2/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.003028636815418538, val_loss: 0.0038553301110177446
epochs 3/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0021417984389699996, val_loss: 0.0027066481667325686
epochs 4/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0017203839667337506, val_loss: 0.0019507184882011069
epochs 5/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0013099413077150913, val_loss: 0.0015320719005294929
epochs 6/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0013134166518667418, val_loss: 0.001319131402200774
epochs 7/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0011947655768476818, val_loss: 0.001252287752791553
epochs 8/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0010788985065454126, val_loss: 0.0012585557467230644
epochs 9/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0010229582959589989, val_loss: 0.0012907756161630937
epochs 10/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.001075221284133333, val_loss: 0.0013582713090152922
epochs 11/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0010278795576213222, val_loss: 0.0014142679356920877
epochs 12/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0011057311031771333, val_loss: 0.001458093974935381
epochs 13/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0010311722167228397, val_loss: 0.0014811208496164335
epochs 14/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0008003927611035148, val_loss: 0.0014794391301141954
epochs 15/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0008058921865947349, val_loss: 0.0014512279459986052
epochs 16/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0008404239540380474, val_loss: 0.0014469502352815317
epochs 17/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0008907546365854183, val_loss: 0.0014511966538664541
epochs 18/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0007163204770461705, val_loss: 0.001471076355818169
epochs 19/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0006878041919614924, val_loss: 0.001521050553511534
epochs 20/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0006454305096811272, val_loss: 0.0014593294019026584
epochs 21/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0006734810184417782, val_loss: 0.0014719324425402048
epochs 22/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.000582364337261472, val_loss: 0.0014661587223312573
epochs 23/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005663284664287379, val_loss: 0.0015707684558277067
epochs 24/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005752144258861479, val_loss: 0.0015519448899124798
epochs 25/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.000493132044395775, val_loss: 0.0015596332506423718
epochs 26/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005357723816383728, val_loss: 0.0015853429832005579
epochs 27/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005045660835764321, val_loss: 0.0015668187762218479
epochs 28/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00048114881011363317, val_loss: 0.0015532049858991645
epochs 29/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00045400915443774705, val_loss: 0.0015164383913782475
epochs 30/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00047171518258676916, val_loss: 0.0014850812498480082
epochs 31/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00044914025730624993, val_loss: 0.0014939522609653834
epochs 32/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.000398941295325609, val_loss: 0.001595083774545377
epochs 33/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00043268344130697903, val_loss: 0.0016604264904009668
epochs 34/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0004496120402013491, val_loss: 0.001656337853790702
epochs 35/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0004174447888018269, val_loss: 0.0016183683526163038
epochs 36/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00040369857605056545, val_loss: 0.0015559567346874821
epochs 37/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00035762913972384446, val_loss: 0.0017021808822296168
epochs 38/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0004183352920288024, val_loss: 0.0017120431875810027
epochs 39/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003772780397220662, val_loss: 0.0015854562338637678
epochs 40/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00039019004386653633, val_loss: 0.0015635373925569614
epochs 41/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003902803898917658, val_loss: 0.0015711851650848986
epochs 42/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003518721857720888, val_loss: 0.0014811221332485347
epochs 43/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00043813759954278603, val_loss: 0.0015663103206622366
epochs 44/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00039524121645004734, val_loss: 0.0017006657558101181
epochs 45/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00031693383820024075, val_loss: 0.0015887871341730812
epochs 46/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003375998468407871, val_loss: 0.001398155925256249
epochs 47/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0002957887119631969, val_loss: 0.001523144315241983
epochs 48/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003377581270270687, val_loss: 0.0015315483299721227
epochs 49/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00031182990251660443, val_loss: 0.0016005304911615034
epochs 50/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00033509315245809325, val_loss: 0.001562838786967883
epochs 51/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003295734952093641, val_loss: 0.0014331109748270952
epochs 52/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00033071454320299, val_loss: 0.0014989478519725563
epochs 53/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00037391531069787514, val_loss: 0.001515350257365131
epochs 54/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003919036093927724, val_loss: 0.0013963520692318286
epochs 55/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003439481190932719, val_loss: 0.0014655231430783476
Starting fold 2:
epochs 1/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0008583981955828341, val_loss: 0.03538975810730144
epochs 2/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0007550630471852951, val_loss: 0.03634707740459003
epochs 3/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0007638642152749909, val_loss: 0.03539139438224466
epochs 4/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0006341985725540374, val_loss: 0.03459535696004566
epochs 5/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0007658731324083515, val_loss: 0.03329978196048423
epochs 6/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0006764316942855274, val_loss: 0.03441679313974945
epochs 7/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0006743433964163016, val_loss: 0.03209639520041253
epochs 8/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0006980839611251691, val_loss: 0.03348803809402805
epochs 9/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.000614852542792888, val_loss: 0.031722495459804406
epochs 10/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0006124697869190162, val_loss: 0.03191896920141421
epochs 11/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.000595624490693138, val_loss: 0.032089111395180225
epochs 12/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.000617391342223671, val_loss: 0.029571639981709027
epochs 13/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0006473339750204775, val_loss: 0.03134047639017042
epochs 14/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005842999496962875, val_loss: 0.028977857500706847
epochs 15/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005599506437551769, val_loss: 0.02966110147535801
epochs 16/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005425379906419518, val_loss: 0.028841277064853593
epochs 17/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005298313857852727, val_loss: 0.02889110262652761
epochs 18/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005051986313973382, val_loss: 0.029163052876921076
epochs 19/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0005169752995195602, val_loss: 0.02829408823071342
epochs 20/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00047023917137075364, val_loss: 0.027573872288983118
epochs 21/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0004899180716739992, val_loss: 0.026936700557799717
epochs 22/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0004941787987742206, val_loss: 0.027756460148252938
epochs 23/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00046052067405789307, val_loss: 0.026538835436497862
epochs 24/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.000460348272922841, val_loss: 0.02692361886760122
epochs 25/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0004368672627606429, val_loss: 0.026820123195648193
epochs 26/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00043485187465864183, val_loss: 0.025469327718019484
epochs 27/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0004497615782096737, val_loss: 0.025999814752293262
epochs 28/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.000416242966763859, val_loss: 0.024815921220732364
epochs 29/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003592252717154272, val_loss: 0.02603004791430737
epochs 30/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00036233056453056635, val_loss: 0.024324303453690126
epochs 31/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003827147645336625, val_loss: 0.02522696497801103
epochs 32/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003980447569598542, val_loss: 0.023593597084675965
epochs 33/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00037246291161098174, val_loss: 0.0241217105012191
epochs 34/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003580681666790042, val_loss: 0.023530885636022215
epochs 35/55
Current Learning Rate: 7.090449608573994e-05
train_loss: 0.00038635223260682417, val_loss: 0.023824582464600865
epochs 36/55

[I 2024-01-26 23:19:16,270] Trial 18 pruned.

Current Learning Rate: 7.090449608573994e-05
train_loss: 0.0003356921825845922, val_loss: 0.023101699813023995
epochs 37/55
Starting fold 1:
epochs 1/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.003418115800932834, val_loss: 0.0026781286088455665
epochs 2/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0014126644727136743, val_loss: 0.0011300162203904045
epochs 3/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0013908874733667624, val_loss: 0.001446517074088517
epochs 4/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0009311576171680109, val_loss: 0.0023853078754128595
epochs 5/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0007439041173232621, val_loss: 0.0009733314295054266
epochs 6/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.000495577512897159, val_loss: 0.0009121888678667968
epochs 7/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00029062730946431036, val_loss: 0.0019065791765522015
epochs 8/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00036385211799489826, val_loss: 0.0009071835911048478
epochs 9/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0003001429056319849, val_loss: 0.0013399776929107151
epochs 10/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00026287204328630313, val_loss: 0.0012781058551474033
epochs 11/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0002253541637114004, val_loss: 0.0008471198196179772
epochs 12/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00027559621958062053, val_loss: 0.0011623206389087596
epochs 13/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00022792458950885033, val_loss: 0.0011316837779687422
epochs 14/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001834174549194837, val_loss: 0.0009167577679219999
epochs 15/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00018803452564354397, val_loss: 0.00127987566673638
epochs 16/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00018442461786387292, val_loss: 0.0009907478356341783
epochs 17/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001630017964328688, val_loss: 0.0010731898150161694
epochs 18/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001605211697384029, val_loss: 0.0010255861286024906
epochs 19/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001522468082839623, val_loss: 0.0010727704441370932
epochs 20/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00015080050376893364, val_loss: 0.0010149382502085676
epochs 21/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00014840524435337437, val_loss: 0.0010104849995849164
epochs 22/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00013174737786788397, val_loss: 0.0008148565048989104
epochs 23/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00016755935250426104, val_loss: 0.001363685685455015
epochs 24/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00019321865846378436, val_loss: 0.0009825585163382225
epochs 25/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001433996811484624, val_loss: 0.001156008986168002
epochs 26/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00015076172329779518, val_loss: 0.001120344741809133
epochs 27/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00013219617348544203, val_loss: 0.0007897968446884892
epochs 28/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001344818631064539, val_loss: 0.0011282247540197875
epochs 29/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00012913161462117722, val_loss: 0.0008075935398473552
epochs 30/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00014452414057144014, val_loss: 0.001377716727897917
epochs 31/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001668093045736896, val_loss: 0.0009423577108751296
epochs 32/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00013796941685110427, val_loss: 0.0010468069108595188
epochs 33/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00013562991118401681, val_loss: 0.0008064843652965991
epochs 34/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00013754678289651086, val_loss: 0.001120636993283896
epochs 35/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001575435093591774, val_loss: 0.001064931174225517
epochs 36/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010794392935502784, val_loss: 0.0007791376586905436
epochs 37/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00011515829981745858, val_loss: 0.001211234172315974
epochs 38/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00011183860969092501, val_loss: 0.0009203466470353305
epochs 39/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010921085892110376, val_loss: 0.0011750632762222697
epochs 40/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001009659045896689, val_loss: 0.0010447636687834013
epochs 41/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010158136635589854, val_loss: 0.0008521626341940933
epochs 42/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00011932017629365681, val_loss: 0.0011450293915052164
epochs 43/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00011226657653950449, val_loss: 0.000830331838714253
epochs 44/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010632371011429074, val_loss: 0.0012740819886522857
epochs 45/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00012375147190667982, val_loss: 0.0008912400409922396
epochs 46/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010270129706967916, val_loss: 0.0009985483239257807
epochs 47/132
Current Learning Rate: 0.0017844565585771665
train_loss: 9.591940167746016e-05, val_loss: 0.0010004393805406596
epochs 48/132
Current Learning Rate: 0.0017844565585771665
train_loss: 9.389924994856731e-05, val_loss: 0.0011034912466512698
epochs 49/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010314883777602135, val_loss: 0.0007865084610928438
epochs 50/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00011567494565449459, val_loss: 0.0012240410279972774
epochs 51/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010844977996863523, val_loss: 0.001221905872961016
epochs 52/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010281455156234045, val_loss: 0.00076856651331151
epochs 53/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00011270786375174986, val_loss: 0.001114134082423621
epochs 54/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010063727753923128, val_loss: 0.0007327919501174046
epochs 55/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00011443271719862853, val_loss: 0.0009519524786523298
epochs 56/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010149247674761634, val_loss: 0.0008742538936387159
epochs 57/132
Current Learning Rate: 0.0017844565585771665
train_loss: 9.419686026184966e-05, val_loss: 0.0011111375397855514
epochs 58/132
Current Learning Rate: 0.0017844565585771665
train_loss: 9.339550850104148e-05, val_loss: 0.0009395932950275509
epochs 59/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.336171633441394e-05, val_loss: 0.0010585080354327434
epochs 60/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.910912890171044e-05, val_loss: 0.0008038795448986715
epochs 61/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.805089945733351e-05, val_loss: 0.0012081637733468884
epochs 62/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010429360822615165, val_loss: 0.00079038662002667
epochs 63/132
Current Learning Rate: 0.0017844565585771665
train_loss: 9.810080174295428e-05, val_loss: 0.0010206247128448204
epochs 64/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.762894063501765e-05, val_loss: 0.0011717435248245142
epochs 65/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010505132492031215, val_loss: 0.0011102710605451936
epochs 66/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.623730115543462e-05, val_loss: 0.0008386216834064965
epochs 67/132
Current Learning Rate: 0.0017844565585771665
train_loss: 9.820766909366572e-05, val_loss: 0.0012703378819615434
epochs 68/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00011876347018283253, val_loss: 0.0007204634633748547
epochs 69/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00012368550194782744, val_loss: 0.0010045152892799753
epochs 70/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.677330218855978e-05, val_loss: 0.000807350875172568
epochs 71/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.12489965219835e-05, val_loss: 0.0009613122735907765
epochs 72/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.529506158083677e-05, val_loss: 0.0009811120138405577
epochs 73/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.310100402970995e-05, val_loss: 0.0010678051070212142
epochs 74/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.509961863685596e-05, val_loss: 0.0012595417118925404
epochs 75/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00012355928476225878, val_loss: 0.000793539758122183
epochs 76/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001138250054760934, val_loss: 0.0011823342034691258
epochs 77/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.407052748799815e-05, val_loss: 0.0007489753280472206
epochs 78/132
Current Learning Rate: 0.0017844565585771665
train_loss: 9.489347308102112e-05, val_loss: 0.0008600702123275321
epochs 79/132
Current Learning Rate: 0.0017844565585771665
train_loss: 9.717619832372293e-05, val_loss: 0.0009258832617074644
epochs 80/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00010458847770534798, val_loss: 0.0009183010490807263
epochs 81/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.898687979365747e-05, val_loss: 0.0010251471846315422
epochs 82/132
Current Learning Rate: 0.0017844565585771665
train_loss: 8.364375313057711e-05, val_loss: 0.001138944779277632
epochs 83/132
Current Learning Rate: 0.0017844565585771665
train_loss: 9.505401440516212e-05, val_loss: 0.0009507767788722719
epochs 84/132
Current Learning Rate: 0.0017844565585771665
train_loss: 7.617979128171053e-05, val_loss: 0.0008816461685407711
epochs 85/132
Epoch 00085: reducing learning rate of group 0 to 1.4765e-03.
Current Learning Rate: 0.001476483800095458
train_loss: 7.700967111496108e-05, val_loss: 0.001004183088968459
epochs 86/132
Current Learning Rate: 0.001476483800095458
train_loss: 8.122673553819033e-05, val_loss: 0.000782439972298514
epochs 87/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.486717176537863e-05, val_loss: 0.000971138768363744
epochs 88/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.586918199146902e-05, val_loss: 0.0008040691211231445
epochs 89/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.852316277996196e-05, val_loss: 0.0009385090119107382
epochs 90/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.372837028110792e-05, val_loss: 0.000884769631451682
epochs 91/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.889241245912241e-05, val_loss: 0.000945318432059139
epochs 92/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.79556304271529e-05, val_loss: 0.0009937945839115663
epochs 93/132
Current Learning Rate: 0.001476483800095458
train_loss: 9.335128906011385e-05, val_loss: 0.0008093615025772076
epochs 94/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.64097061810868e-05, val_loss: 0.0009284063554859083
epochs 95/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.634467462929406e-05, val_loss: 0.0007970365205485569
epochs 96/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.885341160305727e-05, val_loss: 0.0009433032736476315
epochs 97/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.614094532695354e-05, val_loss: 0.0009481440616869613
epochs 98/132
Current Learning Rate: 0.001476483800095458
train_loss: 8.37814085044604e-05, val_loss: 0.0009924192655537474
epochs 99/132
Current Learning Rate: 0.001476483800095458
train_loss: 7.499643757718762e-05, val_loss: 0.0008412254238991361
epochs 100/132
Current Learning Rate: 0.001476483800095458
train_loss: 8.254995191236958e-05, val_loss: 0.001187135820816222
epochs 101/132
Current Learning Rate: 0.001476483800095458
train_loss: 0.0001088669129163272, val_loss: 0.0007809535722787443
epochs 102/132
Epoch 00102: reducing learning rate of group 0 to 1.2217e-03.
Current Learning Rate: 0.001221662921109465
train_loss: 7.084696967228267e-05, val_loss: 0.0010700903796149713
epochs 103/132
Current Learning Rate: 0.001221662921109465
train_loss: 9.80234240399257e-05, val_loss: 0.0007263131372287477
epochs 104/132
Current Learning Rate: 0.001221662921109465
train_loss: 8.655501733301207e-05, val_loss: 0.0009722207875089033
epochs 105/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.650589089424007e-05, val_loss: 0.0008331984465353583
epochs 106/132
Current Learning Rate: 0.001221662921109465
train_loss: 0.00010079609829086908, val_loss: 0.0010186225960129185
epochs 107/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.921279833872656e-05, val_loss: 0.0009395288805918474
epochs 108/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.510411351655708e-05, val_loss: 0.0009755593552989395
epochs 109/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.63973952608036e-05, val_loss: 0.000871400682770304
epochs 110/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.636929034273827e-05, val_loss: 0.0010720142102065055
epochs 111/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.748278968440565e-05, val_loss: 0.000849970803277469
epochs 112/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.3274715472699e-05, val_loss: 0.0008657596435544914
epochs 113/132
Current Learning Rate: 0.001221662921109465
train_loss: 6.850010379965074e-05, val_loss: 0.000949983187877622
epochs 114/132
Current Learning Rate: 0.001221662921109465
train_loss: 6.749960582390868e-05, val_loss: 0.0008861870247576581
epochs 115/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.432601222190944e-05, val_loss: 0.0008932991124885646
epochs 116/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.604671057044088e-05, val_loss: 0.0011453993655251044
epochs 117/132
Current Learning Rate: 0.001221662921109465
train_loss: 8.680767285496633e-05, val_loss: 0.0008125838817489383
epochs 118/132
Current Learning Rate: 0.001221662921109465
train_loss: 7.783556391491162e-05, val_loss: 0.0009171508718281984
epochs 119/132
Epoch 00119: reducing learning rate of group 0 to 1.0108e-03.
Current Learning Rate: 0.0010108206352939463
train_loss: 6.976880199784461e-05, val_loss: 0.0009497088674259814
epochs 120/132
Current Learning Rate: 0.0010108206352939463
train_loss: 7.278341160456061e-05, val_loss: 0.0008231475918651803
epochs 121/132
Current Learning Rate: 0.0010108206352939463
train_loss: 7.734294194960967e-05, val_loss: 0.0008988698062143827
epochs 122/132
Current Learning Rate: 0.0010108206352939463
train_loss: 7.110672518856039e-05, val_loss: 0.0008874487125706908
epochs 123/132
Current Learning Rate: 0.0010108206352939463
train_loss: 7.005735862644782e-05, val_loss: 0.0009881880649022367
epochs 124/132
Current Learning Rate: 0.0010108206352939463
train_loss: 6.503393811535237e-05, val_loss: 0.0008812755113467574
epochs 125/132
Current Learning Rate: 0.0010108206352939463
train_loss: 7.30144584897636e-05, val_loss: 0.0009534989244696733
epochs 126/132
Current Learning Rate: 0.0010108206352939463
train_loss: 7.19210136020066e-05, val_loss: 0.0009135246080787558
epochs 127/132
Current Learning Rate: 0.0010108206352939463
train_loss: 7.149785692730036e-05, val_loss: 0.0007822152815367046
epochs 128/132
Current Learning Rate: 0.0010108206352939463
train_loss: 7.366600460189052e-05, val_loss: 0.0008161195437423885
epochs 129/132
Current Learning Rate: 0.0010108206352939463
train_loss: 7.506436898103474e-05, val_loss: 0.0008772519925658248
epochs 130/132
Current Learning Rate: 0.0010108206352939463
train_loss: 6.83426361846566e-05, val_loss: 0.0009842216095421463
epochs 131/132
Current Learning Rate: 0.0010108206352939463
train_loss: 6.533996470113237e-05, val_loss: 0.0008057317004146937
epochs 132/132
Current Learning Rate: 0.0010108206352939463
train_loss: 8.370825679249767e-05, val_loss: 0.0008927465257185855
Starting fold 2:
epochs 1/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.001891718331056549, val_loss: 0.04175828671769092
epochs 2/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.000738531605365049, val_loss: 0.030164688090352637
epochs 3/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0009414970378489478, val_loss: 0.03868743894915832
epochs 4/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.000708389350237619, val_loss: 0.03774283875368143
epochs 5/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0004798127790165477, val_loss: 0.028668030312186794
epochs 6/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00040675962947333525, val_loss: 0.03067919837408944
epochs 7/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0003679370680689125, val_loss: 0.025833929545785252
epochs 8/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0002982920123031363, val_loss: 0.025124588000931238
epochs 9/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00028444904034442614, val_loss: 0.021873255309305693
epochs 10/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0002775301281393408, val_loss: 0.01756401021817797
epochs 11/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0002546629758925471, val_loss: 0.018296532136829274
epochs 12/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00023891769830554135, val_loss: 0.02094557567646629
epochs 13/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00023561643779669938, val_loss: 0.01593658190808798
epochs 14/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0002221516379473829, val_loss: 0.017330729549652653
epochs 15/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00019589355169476844, val_loss: 0.016036678497728548
epochs 16/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001692713478022549, val_loss: 0.014593408835169516
epochs 17/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00015776621455044828, val_loss: 0.013429145475751475
epochs 18/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00016055315906047136, val_loss: 0.014322599690211447
epochs 19/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.000146630766194951, val_loss: 0.01382299115587222
epochs 20/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00013796789349534695, val_loss: 0.013400684502956114
epochs 21/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00012777120240283884, val_loss: 0.011493677714545476
epochs 22/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.0001247769174178278, val_loss: 0.010247574518679789
epochs 23/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00012940969616848682, val_loss: 0.01116730047291831
epochs 24/132
Current Learning Rate: 0.0017844565585771665
train_loss: 0.00011133621649749234, val_loss: 0.011287061497569084
epochs 25/132

[I 2024-01-26 23:19:32,009] Trial 19 pruned.

Starting fold 1:
epochs 1/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.258570770659533, val_loss: 0.008627713952017458
epochs 2/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.005012983088626673, val_loss: 0.012047084146424344
epochs 3/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.007018047997629956, val_loss: 0.0011846558252153428
epochs 4/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.004475223151721845, val_loss: 0.007165193214620415
epochs 5/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0033350424032266204, val_loss: 0.001171737982842483
epochs 6/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00173502638445873, val_loss: 0.0018398282792125094
epochs 7/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0009684560998146864, val_loss: 0.001475745517956583
epochs 8/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0014443778751516028, val_loss: 0.0011812518473322455
epochs 9/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0011353364312335064, val_loss: 0.0010993540483085734
epochs 10/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0007356947232773038, val_loss: 0.001777145840031536
epochs 11/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0004539064064278807, val_loss: 0.0016569109560039483
epochs 12/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0004908335670877836, val_loss: 0.0017342744272594388
epochs 13/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0014099646543495748, val_loss: 0.002010065719093147
epochs 14/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0007425814309451533, val_loss: 0.0016968205975564686
epochs 15/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0007541411369426274, val_loss: 0.0009785827286051291
epochs 16/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0007797110179365662, val_loss: 0.0010573365419220767
epochs 17/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0005372101042762791, val_loss: 0.0018889843792605557
epochs 18/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00046696251344033763, val_loss: 0.001276107057683954
epochs 19/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0004661623388528824, val_loss: 0.0012717542949279672
epochs 20/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00033721801944346607, val_loss: 0.0013359537728032784
epochs 21/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00038117751644581164, val_loss: 0.0010487109722912703
epochs 22/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0004922987795189807, val_loss: 0.0011287587756094964
epochs 23/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.000514408599548532, val_loss: 0.0010117709109755723
epochs 24/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00063697755563465, val_loss: 0.001024538871685141
epochs 25/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0005566892520475545, val_loss: 0.0013338001138579688
epochs 26/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00037225400630727803, val_loss: 0.001673956303612182
epochs 27/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00038929879175204977, val_loss: 0.0014910293853302534
epochs 28/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0002917610890060467, val_loss: 0.0012968943613630376
epochs 29/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0003289380126118072, val_loss: 0.0013356311736922514
epochs 30/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0003505204559156769, val_loss: 0.001018595593785377
epochs 31/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00036714961032358637, val_loss: 0.0012374436666600798
epochs 32/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0003792760253418237, val_loss: 0.0009982374980800639
epochs 33/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0004892030954483504, val_loss: 0.0012971441273724562
epochs 34/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0003036618551337405, val_loss: 0.0012841099799659691
epochs 35/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00030993319600575457, val_loss: 0.0010246236342936754
epochs 36/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00037398592011365846, val_loss: 0.0012317857043327469
epochs 37/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0003332219019189085, val_loss: 0.0010520369090188883
epochs 38/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00037181199877522886, val_loss: 0.0009985529989200203
epochs 39/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0004202876757756856, val_loss: 0.0010291405518441216
epochs 40/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00035197694179307863, val_loss: 0.001347353173370816
epochs 41/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0003151599146229656, val_loss: 0.0013828039304108212
epochs 42/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.000320907282385681, val_loss: 0.00232566298769885
epochs 43/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0005491241601320278, val_loss: 0.0019493465201537077
epochs 44/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0004136033454223683, val_loss: 0.0010217306369572487
epochs 45/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0005590386679518575, val_loss: 0.0010270873286859377
epochs 46/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0006280305265375462, val_loss: 0.0010305613579571638
epochs 47/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0006075665878597647, val_loss: 0.0013627447678070319
epochs 48/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0004169114070368539, val_loss: 0.002212356947558491
epochs 49/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.0005011483720552764, val_loss: 0.001585299339096405
epochs 50/98
Current Learning Rate: 0.0239104936531749
train_loss: 0.00035133196414742425, val_loss: 0.001027993634220605
epochs 51/98
Epoch 00051: reducing learning rate of group 0 to 1.3744e-02.
Current Learning Rate: 0.013744389661530009
train_loss: 0.00043306786162582666, val_loss: 0.001050289208682156
epochs 52/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0005381311118406685, val_loss: 0.0021961335043766
epochs 53/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00044934622526757027, val_loss: 0.0010496660129559274
epochs 54/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00033543066054239477, val_loss: 0.0017118544232002215
epochs 55/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00033107527384632513, val_loss: 0.0011172546747777808
epochs 56/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003044195488511928, val_loss: 0.0015525029923178647
epochs 57/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00036875582392033383, val_loss: 0.0017092663267823426
epochs 58/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003762207603645756, val_loss: 0.0010040600839267043
epochs 59/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003719861377153154, val_loss: 0.001833423647392345
epochs 60/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00034673869652722617, val_loss: 0.001034986981386809
epochs 61/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00036769482999500866, val_loss: 0.0013368418624036405
epochs 62/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00030159935857610484, val_loss: 0.0012659393679840785
epochs 63/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003523635279730354, val_loss: 0.0011055863854524336
epochs 64/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00035399417576723193, val_loss: 0.0016716433149811469
epochs 65/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00040149995689525415, val_loss: 0.001036761322450873
epochs 66/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003518708598628444, val_loss: 0.0015051002663217094
epochs 67/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0002957959766622241, val_loss: 0.0011954477246801712
epochs 68/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00028932399245126073, val_loss: 0.0012354565980403048
epochs 69/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00028139420043628077, val_loss: 0.001326427286441781
epochs 70/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00029374777468068426, val_loss: 0.0011350948786313989
epochs 71/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003012116082429298, val_loss: 0.0011576923639758637
epochs 72/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00030267604712494895, val_loss: 0.0012872058371278016
epochs 73/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003035041598578621, val_loss: 0.0013439535518716041
epochs 74/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00028178168194196925, val_loss: 0.0011593080861003774
epochs 75/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.000272299650149714, val_loss: 0.0016886368577711675
epochs 76/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003857301903496447, val_loss: 0.0010195421330679796
epochs 77/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003698725547445448, val_loss: 0.0013385323354190117
epochs 78/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00031305037095750635, val_loss: 0.0012608636293168132
epochs 79/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00028997953019202933, val_loss: 0.001152094453573227
epochs 80/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00031065712774809643, val_loss: 0.001484297699981222
epochs 81/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0002921955770273742, val_loss: 0.000999321217501634
epochs 82/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0003611801979499624, val_loss: 0.001688496877537354
epochs 83/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.0004081800855745218, val_loss: 0.001322964273736273
epochs 84/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00031995969383340135, val_loss: 0.0010661261866947538
epochs 85/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00031246800790540874, val_loss: 0.0014500393912098126
epochs 86/98
Current Learning Rate: 0.013744389661530009
train_loss: 0.00030570829403586686, val_loss: 0.00105991810989125
epochs 87/98
Epoch 00087: reducing learning rate of group 0 to 7.9006e-03.
Current Learning Rate: 0.007900641864953267
train_loss: 0.0002966819340240602, val_loss: 0.0013830658893934206
epochs 88/98
Current Learning Rate: 0.007900641864953267
train_loss: 0.0002778051390410646, val_loss: 0.0011145189943674364
epochs 89/98
Current Learning Rate: 0.007900641864953267
train_loss: 0.0002595673883517616, val_loss: 0.0013972950278242167
epochs 90/98
Current Learning Rate: 0.007900641864953267
train_loss: 0.00030238119775037234, val_loss: 0.0011191087419559296
epochs 91/98
Current Learning Rate: 0.007900641864953267
train_loss: 0.0003148612511148186, val_loss: 0.0013275919420840708
epochs 92/98

[I 2024-01-26 23:19:35,985] Trial 20 pruned.

Starting fold 1:
epochs 1/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.006493265624158084, val_loss: 0.0024259025696665047
epochs 2/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0019657061551697553, val_loss: 0.0018780897837132216
epochs 3/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0016111948061734438, val_loss: 0.0012579489906784148
epochs 4/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0016987996641546488, val_loss: 0.0023239351343363524
epochs 5/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0016275200061500073, val_loss: 0.0023580235429108143
epochs 6/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001593894953839481, val_loss: 0.0016264743986539542
epochs 7/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001600478298496455, val_loss: 0.0015898852550890296
epochs 8/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0015033217961899937, val_loss: 0.00189888778841123
epochs 9/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0016439944971352815, val_loss: 0.001998746348544955
epochs 10/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014915506355464459, val_loss: 0.0014071347948629409
epochs 11/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0015316261327825488, val_loss: 0.0018148093950003386
epochs 12/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014610772603191435, val_loss: 0.00211699593346566
epochs 13/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014959194930270314, val_loss: 0.0017175241722725333
epochs 14/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0015288230730220675, val_loss: 0.001409667101688683
epochs 15/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0015954582137055694, val_loss: 0.0020159925101324917
epochs 16/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0015070718945935369, val_loss: 0.001664147450355813
epochs 17/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014917136169970036, val_loss: 0.0016951436642557382
epochs 18/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014690877636894585, val_loss: 0.0018204214051365853
epochs 19/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014832264510914682, val_loss: 0.001697209826670587
epochs 20/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014967702212743462, val_loss: 0.0018121166853234173
epochs 21/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001534500950947404, val_loss: 0.002008524409029633
epochs 22/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014875177294015884, val_loss: 0.0016133738216012716
epochs 23/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0015217510284855963, val_loss: 0.0016233617905527353
epochs 24/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014923932612873614, val_loss: 0.0020465741981752217
epochs 25/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0015041830600239336, val_loss: 0.0017267460585571825
epochs 26/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014687786460854113, val_loss: 0.0017111947759985923
epochs 27/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014530272805131973, val_loss: 0.0017788307508453728
epochs 28/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001472583960276097, val_loss: 0.0018668776261620223
epochs 29/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001478616474196315, val_loss: 0.0018261663266457618
epochs 30/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014514406677335501, val_loss: 0.0016185692278668285
epochs 31/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001460941438563168, val_loss: 0.0017018597456626595
epochs 32/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014180951518937945, val_loss: 0.0017948753549717367
epochs 33/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001454383705276996, val_loss: 0.0017724790377542377
epochs 34/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014643415343016386, val_loss: 0.0017742473050020636
epochs 35/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014794813585467636, val_loss: 0.0015823277994059027
epochs 36/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014761816710233688, val_loss: 0.0018382023321464659
epochs 37/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014468897599726916, val_loss: 0.0016947544179856777
epochs 38/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014846190577372908, val_loss: 0.0016266024205833674
epochs 39/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014621567563153804, val_loss: 0.0019101491197943687
epochs 40/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001523878565058112, val_loss: 0.002033155004028231
epochs 41/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014873900217935443, val_loss: 0.0015597777091898024
epochs 42/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001500971522182226, val_loss: 0.0015555838937871159
epochs 43/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014574325177818537, val_loss: 0.0018382530310191215
epochs 44/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014383037807419897, val_loss: 0.0017387412139214576
epochs 45/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014338446198962629, val_loss: 0.0017378136282786727
epochs 46/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014609516481868922, val_loss: 0.001779218192677945
epochs 47/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014774928800761699, val_loss: 0.0018255723174661399
epochs 48/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014437738223932683, val_loss: 0.0015544649679213763
epochs 49/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014681731117889285, val_loss: 0.0016997434315271676
epochs 50/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014554784866049886, val_loss: 0.002061717922333628
epochs 51/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001466950448229909, val_loss: 0.0016340408124960958
epochs 52/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014991577831096948, val_loss: 0.0015337251708842814
epochs 53/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014631978585384787, val_loss: 0.0020014353096485136
epochs 54/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014606958080548792, val_loss: 0.0017552237375639379
epochs 55/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.001418226957321167, val_loss: 0.0015191913465969265
epochs 56/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014877702458761632, val_loss: 0.001734913612017408
epochs 57/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014244699152186513, val_loss: 0.0019126812461763621
epochs 58/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014836824615485967, val_loss: 0.0019389510271139443
epochs 59/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014861953735817225, val_loss: 0.0016416770406067372
epochs 60/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014347574557177722, val_loss: 0.0017549250740557909
epochs 61/146
Current Learning Rate: 0.008475267250367484
train_loss: 0.0014684732537716626, val_loss: 0.0019441119278781117
epochs 62/146
Epoch 00062: reducing learning rate of group 0 to 3.0617e-03.
Current Learning Rate: 0.0030616502747850935
train_loss: 0.00145352320978418, val_loss: 0.0016776853008195758
epochs 63/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014336177380755543, val_loss: 0.0016532098641619086
epochs 64/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014453983749262989, val_loss: 0.001674523379188031
epochs 65/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.001428160339128226, val_loss: 0.0017986837774515152
epochs 66/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014438875718042255, val_loss: 0.0018003604956902564
epochs 67/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014432121184654533, val_loss: 0.0016649760655127466
epochs 68/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014650862198323012, val_loss: 0.0016317238565534352
epochs 69/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014524402911774814, val_loss: 0.00169475763104856
epochs 70/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014481869409792125, val_loss: 0.0017007977468892932
epochs 71/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014376482809893786, val_loss: 0.0016661176225170494
epochs 72/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.001459426584187895, val_loss: 0.00163844283670187
epochs 73/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014419686864130198, val_loss: 0.0016952259349636734
epochs 74/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.001445688062813133, val_loss: 0.0018321282579563559
epochs 75/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014373536920174955, val_loss: 0.0017554659978486597
epochs 76/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014523400575853884, val_loss: 0.0017360850586555898
epochs 77/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014669397147372364, val_loss: 0.0017699407297186553
epochs 78/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014434439595788716, val_loss: 0.0017468331614509224
epochs 79/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014411093783564866, val_loss: 0.0017378179822117091
epochs 80/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014414562261663376, val_loss: 0.0017787528573535382
epochs 81/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014335420681163668, val_loss: 0.001729840668849647
epochs 82/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.00146254263818264, val_loss: 0.0016437171143479645
epochs 83/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.001460446009878069, val_loss: 0.0017796360538341106
epochs 84/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014215038623660802, val_loss: 0.0017528024851344525
epochs 85/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014357281965203584, val_loss: 0.0016944760689511895
epochs 86/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014344222261570394, val_loss: 0.0017264068243093788
epochs 87/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014482860220596193, val_loss: 0.0017556376522406935
epochs 88/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014378777821548283, val_loss: 0.001699638180434704
epochs 89/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.001440047996584326, val_loss: 0.0017344067222438754
epochs 90/146

[I 2024-01-26 23:19:40,570] Trial 21 pruned.

Current Learning Rate: 0.0030616502747850935
train_loss: 0.001431046857032925, val_loss: 0.001797167060431093
epochs 91/146
Current Learning Rate: 0.0030616502747850935
train_loss: 0.0014337141066789628, val_loss: 0.0019000475760549307
epochs 92/146
Starting fold 1:
epochs 1/145
Current Learning Rate: 0.09699963620602928
train_loss: 7.953397155096019, val_loss: 4.916390519393118
epochs 2/145
Current Learning Rate: 0.09699963620602928
train_loss: 1.8818703701621609, val_loss: 0.006943798158317804
epochs 3/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.1483111829545937, val_loss: 4.86643543996309
epochs 4/145
Current Learning Rate: 0.09699963620602928
train_loss: 1.5508645847439766, val_loss: 0.240419124694247
epochs 5/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.15124908834695816, val_loss: 0.003722303883956843
epochs 6/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.048372681301675345, val_loss: 0.01846886288962866
epochs 7/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.05987914092838764, val_loss: 0.01129062111048322
epochs 8/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.049908414973240146, val_loss: 0.0022620782685024957
epochs 9/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.039293312516651656, val_loss: 0.011868453609119905
epochs 10/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.03685831739322135, val_loss: 0.007224737666547298
epochs 11/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.024517312743946126, val_loss: 0.002926088636741042
epochs 12/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.029650383138735043, val_loss: 0.0012688381738323522
epochs 13/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.026852566993942385, val_loss: 0.0016544991675274151
epochs 14/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.019709560873084946, val_loss: 0.003525819476252716
epochs 15/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.015041038859635592, val_loss: 0.005225435095398049
epochs 16/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.01733511326050288, val_loss: 0.0055186058345593906
epochs 17/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.015015522434719299, val_loss: 0.003097235237395293
epochs 18/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.015329167810513786, val_loss: 0.0013531525956319743
epochs 19/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.009303014382327857, val_loss: 0.0017834355821833014
epochs 20/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.009794973792802347, val_loss: 0.003322584199179944
epochs 21/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.006930184844685228, val_loss: 0.00512980365831601
epochs 22/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.007695276657805631, val_loss: 0.003697213655533759
epochs 23/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.007085809030717141, val_loss: 0.002087222286622579
epochs 24/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.005869929592958407, val_loss: 0.0017439442852168884
epochs 25/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.006941796010850291, val_loss: 0.002055292330241125
epochs 26/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.005132114208352409, val_loss: 0.002913588020754488
epochs 27/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.00541101288246481, val_loss: 0.002958691201025718
epochs 28/145

[I 2024-01-26 23:19:42,175] Trial 22 pruned.

Current Learning Rate: 0.09699963620602928
train_loss: 0.005330876949684401, val_loss: 0.0018133292599630199
epochs 29/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.004128222770400737, val_loss: 0.0018291540358117537
epochs 30/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.005461026853146522, val_loss: 0.0035138906984540975
epochs 31/145
Current Learning Rate: 0.09699963620602928
train_loss: 0.00432984832380163, val_loss: 0.0038991865187295175
epochs 32/145
Starting fold 1:
epochs 1/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.03378041611592236, val_loss: 0.009571235700461426
epochs 2/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.007211925186167814, val_loss: 0.004927339344775598
epochs 3/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.002344805499122135, val_loss: 0.0012744967911490484
epochs 4/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0019829345174672964, val_loss: 0.002359939614727505
epochs 5/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.00167183444504381, val_loss: 0.0014831045421918757
epochs 6/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015535552146550464, val_loss: 0.001984013230417316
epochs 7/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015299929214004232, val_loss: 0.001401990742153047
epochs 8/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0017330459993038522, val_loss: 0.0018103157672540921
epochs 9/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014578258949577024, val_loss: 0.0016625109030620048
epochs 10/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014903642286203409, val_loss: 0.001691681416215081
epochs 11/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015806370610861402, val_loss: 0.002024037530645728
epochs 12/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0016150689052760994, val_loss: 0.0015130221151354673
epochs 13/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.001559196760583865, val_loss: 0.002086436515673995
epochs 14/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015703442365568327, val_loss: 0.001597046672587136
epochs 15/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015037671393273693, val_loss: 0.0016570968289957627
epochs 16/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015428720746728543, val_loss: 0.0019335310483400367
epochs 17/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015310622714950065, val_loss: 0.0014592316320264026
epochs 18/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015101613948660855, val_loss: 0.0018614819383640823
epochs 19/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015211223238637964, val_loss: 0.001736224010758298
epochs 20/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.001467273916166864, val_loss: 0.0018998762899029413
epochs 21/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014695293306814213, val_loss: 0.0018027386842540613
epochs 22/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015196271222329845, val_loss: 0.0017045030266193576
epochs 23/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014607585464163047, val_loss: 0.0016800358336982563
epochs 24/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014993922080305455, val_loss: 0.001665225449802452
epochs 25/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014968039737524171, val_loss: 0.001818593433371892
epochs 26/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014264143966628534, val_loss: 0.001686830413037617
epochs 27/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015549719682894647, val_loss: 0.0018529913345302798
epochs 28/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.001483541148052992, val_loss: 0.0017656923014376508
epochs 29/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015019984774928736, val_loss: 0.0016619053338409254
epochs 30/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.001504581905043635, val_loss: 0.0017780921716046962
epochs 31/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015293001736465253, val_loss: 0.0017014047124815222
epochs 32/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0016632365326299087, val_loss: 0.0021861591603067753
epochs 33/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015438096034095475, val_loss: 0.0013897627628849526
epochs 34/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015784385509936042, val_loss: 0.0022099678324976643
epochs 35/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015010674318641816, val_loss: 0.0014438466885813364
epochs 36/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015001134064636732, val_loss: 0.0019011707725248446
epochs 37/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015118032277218606, val_loss: 0.0016166628975617257
epochs 38/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014794078931261443, val_loss: 0.0017361055502030803
epochs 39/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014737397334293315, val_loss: 0.0018010191270150244
epochs 40/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014909782508192094, val_loss: 0.0017075772544271068
epochs 41/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014892670760960564, val_loss: 0.0017218393874109577
epochs 42/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014905520818980509, val_loss: 0.00171053971739878
epochs 43/139
Epoch 00043: reducing learning rate of group 0 to 1.9464e-03.
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014488085215960285, val_loss: 0.0017273010686039924
epochs 44/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014827621635049582, val_loss: 0.001746802986599505
epochs 45/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014326683153692437, val_loss: 0.0017261998170349552
epochs 46/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014396864351032203, val_loss: 0.0017484291576118649
epochs 47/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.001453845675936655, val_loss: 0.0017517407841392255
epochs 48/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014725055374009044, val_loss: 0.0017742496958051465
epochs 49/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014385273787315544, val_loss: 0.0017423320923147625
epochs 50/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014671427185500138, val_loss: 0.0017144484194240679
epochs 51/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014532971698300618, val_loss: 0.0017086473906314686
epochs 52/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.001446874723402097, val_loss: 0.0016974816319385642
epochs 53/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014277330955098334, val_loss: 0.0017230970399013084
epochs 54/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014319016708453235, val_loss: 0.001743254884709849
epochs 55/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014356587743876797, val_loss: 0.0017171736432876634
epochs 56/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0015031880907420264, val_loss: 0.0017453568448361598
epochs 57/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014534957982648752, val_loss: 0.0017798464138698029
epochs 58/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014144497139281348, val_loss: 0.0017571101510456125
epochs 59/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014523883246032423, val_loss: 0.0017070227523187274
epochs 60/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014404612231852586, val_loss: 0.001720247640715618
epochs 61/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014663833646888012, val_loss: 0.0016978008611323802
epochs 62/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014584707132981795, val_loss: 0.0016861261989872315
epochs 63/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014571742307835896, val_loss: 0.0016952944784670283
epochs 64/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014605026477702747, val_loss: 0.001738757694654755
epochs 65/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014527874863951614, val_loss: 0.0018171526957303286
epochs 66/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0015066526468696172, val_loss: 0.0018498822041836224
epochs 67/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014445814781969316, val_loss: 0.0017538214175912895
epochs 68/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.001443763582133933, val_loss: 0.0016731226645213993
epochs 69/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014261563277901395, val_loss: 0.001694117421529403
epochs 70/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.001499042846262455, val_loss: 0.0017415960386738573
epochs 71/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014468217617832125, val_loss: 0.0018159411100082492
epochs 72/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.001463469489183473, val_loss: 0.0017910218215547503
epochs 73/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014592057161376272, val_loss: 0.0017928085626887256
epochs 74/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014326254549240204, val_loss: 0.001768423052578184
epochs 75/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014692099611765068, val_loss: 0.001779094574311258
epochs 76/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0015110507282722545, val_loss: 0.0018329074594045157
epochs 77/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014847366801021915, val_loss: 0.0018399037843521097
epochs 78/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014325384473379114, val_loss: 0.0018114962425131939
epochs 79/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014506245693682055, val_loss: 0.0017514220487914588
epochs 80/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014447996337702007, val_loss: 0.0017248132529570476
epochs 81/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014750176354458458, val_loss: 0.0017136297905572544
epochs 82/139
Current Learning Rate: 0.0019464156703977802
train_loss: 0.0014702543941032338, val_loss: 0.0016481298983930365
epochs 83/139
Epoch 00083: reducing learning rate of group 0 to 1.9686e-04.
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014552605614115142, val_loss: 0.0016779163564359279
epochs 84/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014522399272353045, val_loss: 0.0016896948193837152
epochs 85/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014500569000742154, val_loss: 0.0016957945178115838
epochs 86/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014506017176532432, val_loss: 0.0017083564283032165
epochs 87/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014494260154223363, val_loss: 0.0017221397775421408
epochs 88/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014546392436482404, val_loss: 0.0017274662968702614
epochs 89/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014103112965944762, val_loss: 0.00173071125877629
epochs 90/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001453665036732625, val_loss: 0.0017252552096339825
epochs 91/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001469181783766927, val_loss: 0.0017239126793451999
epochs 92/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001463274440826162, val_loss: 0.0017153377565065104
epochs 93/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014782616016945165, val_loss: 0.0017158523722747832
epochs 94/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014476489526905904, val_loss: 0.0017154290402112038
epochs 95/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014744523373481475, val_loss: 0.0017156248446553945
epochs 96/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014944809832071002, val_loss: 0.0017141865572499993
epochs 97/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001443813087443184, val_loss: 0.0017103325103801723
epochs 98/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014341965826277277, val_loss: 0.0017154396413580368
epochs 99/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014869829872623086, val_loss: 0.0017194362994479506
epochs 100/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001415760956680108, val_loss: 0.0017218837416485737
epochs 101/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001428398592275028, val_loss: 0.0017204742002496986
epochs 102/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001458016246875846, val_loss: 0.0017255802203803077
epochs 103/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014431129755011123, val_loss: 0.0017337199999019504
epochs 104/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001438794117175827, val_loss: 0.001738174589914515
epochs 105/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001433710266811479, val_loss: 0.0017449221647295513
epochs 106/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001438373182655165, val_loss: 0.0017473496570202865
epochs 107/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014126914118318572, val_loss: 0.0017493140087217877
epochs 108/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014361973551690187, val_loss: 0.0017467281248077359
epochs 109/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001428176200409469, val_loss: 0.0017491016034527046
epochs 110/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014377700305837943, val_loss: 0.0017406315340562479
epochs 111/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014814349118080971, val_loss: 0.001736644792100905
epochs 112/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014485513227746674, val_loss: 0.0017399658399977183
epochs 113/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014933617007428486, val_loss: 0.0017352270035955466
epochs 114/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001466746624608181, val_loss: 0.0017292236566151444
epochs 115/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014559173552123339, val_loss: 0.0017298139313137845
epochs 116/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014201001490858432, val_loss: 0.0017277281565934812
epochs 117/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001454673521220684, val_loss: 0.001728126006568537
epochs 118/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.001386369046706118, val_loss: 0.0017293442978131535
epochs 119/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014507951073985744, val_loss: 0.0017312789985321855
epochs 120/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014221848405309415, val_loss: 0.001734769458294307
epochs 121/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014454335709543605, val_loss: 0.0017378589285439567
epochs 122/139
Current Learning Rate: 0.00019686145120758914
train_loss: 0.0014477285721927488, val_loss: 0.0017390227735679792
epochs 123/139
Epoch 00123: reducing learning rate of group 0 to 1.9911e-05.
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014295576268954105, val_loss: 0.0017400150922568221
epochs 124/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014410336593803214, val_loss: 0.0017407751752455767
epochs 125/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014488408819919355, val_loss: 0.0017412693546104588
epochs 126/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014479931137573562, val_loss: 0.0017414481011464407
epochs 127/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014357768035934944, val_loss: 0.0017414028884990044
epochs 128/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014603101997636258, val_loss: 0.0017420833305406727
epochs 129/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014551756921910533, val_loss: 0.0017415293737461693
epochs 130/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014585841649309976, val_loss: 0.0017407245621526319
epochs 131/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014634932060480902, val_loss: 0.0017406244486521342
epochs 132/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.001443049875945833, val_loss: 0.0017399436573645002
epochs 133/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014846056424032308, val_loss: 0.001739317798178251
epochs 134/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.001459480610087906, val_loss: 0.0017383631533256878
epochs 135/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014676862341155739, val_loss: 0.001737695298231158
epochs 136/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014401905306026732, val_loss: 0.001737224284289895
epochs 137/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.001476288501687936, val_loss: 0.0017365273296538937
epochs 138/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014497169164793663, val_loss: 0.0017359294548728748
epochs 139/139
Current Learning Rate: 1.991066531212109e-05
train_loss: 0.0014501598682009468, val_loss: 0.0017347903260471005
Starting fold 2:
epochs 1/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.00847610680839831, val_loss: 0.04052968851633762
epochs 2/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0016498017483268326, val_loss: 0.040950370874059824
epochs 3/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015441205603756794, val_loss: 0.04173571161533657
epochs 4/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.001754267208621298, val_loss: 0.04230415115230962
epochs 5/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.001621927895068534, val_loss: 0.040891559284768605
epochs 6/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015540015130107731, val_loss: 0.040315455041433634
epochs 7/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015406705374755945, val_loss: 0.043379768062579004
epochs 8/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014856523017729877, val_loss: 0.04394316534070592
epochs 9/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0014825148501825568, val_loss: 0.046310883858486224
epochs 10/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015223302437286628, val_loss: 0.04705740097714098
epochs 11/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015029882522005784, val_loss: 0.039695282417692636
epochs 12/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.001486634857658493, val_loss: 0.04367971702625877
epochs 13/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015406579085576692, val_loss: 0.04339614508575515
epochs 14/139
Current Learning Rate: 0.019244671512530176
train_loss: 0.0015071982039922946, val_loss: 0.047372532537893246
epochs 15/139
Current Learning Rate: 0.019244671512530176

[I 2024-01-26 23:19:58,800] Trial 23 pruned.

Starting fold 1:
epochs 1/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.02076458955477727, val_loss: 0.013164167723765498
epochs 2/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.004670859106179131, val_loss: 0.0015565539256816633
epochs 3/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0038617086155634177, val_loss: 0.0011964563629589975
epochs 4/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.001673413481024143, val_loss: 0.002266834763270852
epochs 5/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.001806343575988553, val_loss: 0.0027450400723242445
epochs 6/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.001795067734967329, val_loss: 0.002199819963425398
epochs 7/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0015945005132571646, val_loss: 0.0016356051997526695
epochs 8/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.001549739196994587, val_loss: 0.0014670862081019502
epochs 9/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0016146011221663732, val_loss: 0.0015304243020517261
epochs 10/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0016723741703715763, val_loss: 0.0016854400391151246
epochs 11/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0015384331529371832, val_loss: 0.0018234744741532363
epochs 12/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0015925314350935973, val_loss: 0.0017083124821319392
epochs 13/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0014563802960573843, val_loss: 0.0015171125041026818
epochs 14/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.001535874616207653, val_loss: 0.0014412167849705408
epochs 15/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0012225081641717176, val_loss: 0.0017119240236321562
epochs 16/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0008992327677429115, val_loss: 0.0012281186033138319
epochs 17/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0008389635869350873, val_loss: 0.00151567678702505
epochs 18/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0005544300577113111, val_loss: 0.002143493427061721
epochs 19/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0004186729557420078, val_loss: 0.0030057632437858143
epochs 20/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0004645223315731671, val_loss: 0.002135023501652636
epochs 21/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0003610120589942916, val_loss: 0.0017611890565603972
epochs 22/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0003161981848901824, val_loss: 0.001599050872027874
epochs 23/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0003021339009712009, val_loss: 0.0023575078548961565
epochs 24/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.00034812438243534414, val_loss: 0.0022288185911939332
epochs 25/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.00027721422114777134, val_loss: 0.0020504316817478913
epochs 26/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.00036221487129009083, val_loss: 0.0012545769703329393
epochs 27/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.00030390934261959046, val_loss: 0.0013811574268497919
epochs 28/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0003354118502772364, val_loss: 0.002321546055425547
epochs 29/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0003220327587577661, val_loss: 0.001348986983985493
epochs 30/121

[I 2024-01-26 23:20:00,493] Trial 24 pruned.

Current Learning Rate: 0.0030290973733271627
train_loss: 0.0002772529857649811, val_loss: 0.002056406437125253
epochs 31/121
Current Learning Rate: 0.0030290973733271627
train_loss: 0.0002470189255147584, val_loss: 0.00216713780904875
epochs 32/121
Number of finished trials: 25
Best trial:
Value: 0.010049154356568352
Params:
batch_size: 32
epochs: 104
hidden_size: 89
learning_rate: 0.00021816996161030182
dropout_prob: 0.1272723440657144
weight_decay: 0.0005261517371819727
lr_step_size: 34
gamma: 0.6936855452706332
conv_channels: 56
kernel_size: 5
num_layers: 2
pool_size: 3
stride: 2

In [55]:
trainer = ModelActioner(train_data, test_data, device, model_type)
model = trainer.train(trial.params)

epochs 1/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.12864866507680792
epochs 2/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.018284875386508935
epochs 3/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0070425965937606074
epochs 4/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.005469782491982506
epochs 5/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.004887046573454874
epochs 6/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.004262852471877347
epochs 7/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.003939015366006316
epochs 8/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0035841805893078184
epochs 9/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0034122886895937353
epochs 10/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.003528795901914699
epochs 11/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0032935253998035924
epochs 12/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.003278269086098462
epochs 13/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.003893653411222132
epochs 14/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.003327093044655365
epochs 15/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.003011110570412456
epochs 16/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.003274124604241367
epochs 17/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0030860705333843564
epochs 18/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00314924086100961
epochs 19/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0028194458019641933
epochs 20/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0027050779928175506
epochs 21/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0030491688256070277
epochs 22/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002909067673853746
epochs 23/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0030331086302012727
epochs 24/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0030560595489907685
epochs 25/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0030807679588497994
epochs 26/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002793803133005113
epochs 27/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0030376571867811054
epochs 28/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0029105059786193204
epochs 29/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0027548228308819887
epochs 30/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002920588016052518
epochs 31/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0027894340390176102
epochs 32/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00289287847107309
epochs 33/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0025713774796346563
epochs 34/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0030822366557753922
epochs 35/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002474377812458235
epochs 36/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0027525304228459536
epochs 37/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0027293941978234473
epochs 38/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0025736840245755097
epochs 39/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002432279024077089
epochs 40/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002872320178798155
epochs 41/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0025901031059523422
epochs 42/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0023932259770829164
epochs 43/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002567274049087836
epochs 44/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002623725431693489
epochs 45/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002445561370175136
epochs 46/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0027041938441821883
epochs 47/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0023727534510391323
epochs 48/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002645959176547956
epochs 49/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0025192640084577235
epochs 50/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002542903881699762
epochs 51/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0024412147774312055
epochs 52/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002764197743677518
epochs 53/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0025240469920007804
epochs 54/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00263824153144174
epochs 55/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002776490296482256
epochs 56/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0025709164669949626
epochs 57/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0029393008187119114
epochs 58/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0023184703638483035
epochs 59/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0027146228147964728
epochs 60/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002567983085796106
epochs 61/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002884373382518166
epochs 62/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0023548557807021495
epochs 63/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0024088922116023144
epochs 64/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0024116356064679853
epochs 65/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0024158770900644493
epochs 66/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0024692188474562085
epochs 67/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0024502120879397057
epochs 68/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0022578424014347166
epochs 69/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0022853066973192128
epochs 70/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002591546755610851
epochs 71/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0023037134236737825
epochs 72/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0021439933499909545
epochs 73/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002545177315672239
epochs 74/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002171346721272066
epochs 75/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0023549607068528993
epochs 76/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002945094173692428
epochs 77/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0021641246529230684
epochs 78/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0024290061237192467
epochs 79/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002335931908894788
epochs 80/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0023247067800216507
epochs 81/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0022839035352757364
epochs 82/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002258505450006117
epochs 83/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0030825406427315454
epochs 84/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002468938644354542
epochs 85/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.00249772448207072
epochs 86/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002325384782039021
epochs 87/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002208391376444253
epochs 88/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0021888027796848563
epochs 89/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0023993632065851178
epochs 90/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0022147641492713437
epochs 91/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002264705698185584
epochs 92/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002216816767886804
epochs 93/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002246502623484846
epochs 94/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0024314507891080883
epochs 95/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0022762132710532137
epochs 96/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002627073121338821
epochs 97/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0023613132797835165
epochs 98/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002290686802415733
epochs 99/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002266766833909379
epochs 100/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002417651066360505
epochs 101/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002149824814037665
epochs 102/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.002597824161823251
epochs 103/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0022811824235280877
epochs 104/104
Current Learning Rate: 0.00021816996161030182
train_loss: 0.0021589482043820776

In [56]:
y_true = y_test_df[time_step:]
preds = trainer.test(trial.params)

# Mean Absolute Error
mae = mean_absolute_error(y_true, preds)
print(f'Mean Absolute Error: {mae}')

# Mean Squared Error
mse = mean_squared_error(y_true, preds)
print(f'Mean Squared Error: {mse}')

# Root Mean Squared Error
rmse = np.sqrt(mse)
print(f'Root Mean Squared Error: {rmse}')

# R-squared Score
r2 = r2_score(y_true, preds)
print(f'R-squared Score: {r2}')

mape = mean_absolute_percentage_error(y_true, preds)*100
print(f"MAPE: {mape}")

test_loss: 0.0048392148363211795
Mean Absolute Error: 0.060968709291134904
Mean Squared Error: 0.004839215382113116
Root Mean Squared Error: 0.06956446925056725
R-squared Score: 0.5303328280629049
MAPE: 6.209330008777527

In [57]:
y_true

44     0.728267
45     0.737950
46     0.733381
47     0.747701
48     0.761134
         ...
291    1.018693
292    1.059493
293    1.079584
294    1.095561
295    1.104406
Name: Adj Close, Length: 252, dtype: float64

In [58]:
y_true = y_true.reset_index(drop=True)
#y_true = y_true.drop(columns=["index","level_0"])
X_value = X_test_df.iloc[43:,-1]
X_value = X_value.reset_index()
preds_values = [x[0] for x in preds]
X_value["Preds"] = pd.Series(preds_values)
X_value["Next Day"] = y_true
X_value = X_value.drop(columns=["index"])
X_value["Diff Preds"] = (X_value["Preds"] - X_value["Adj Close"])
X_value["Diff Next Day"] = (X_value["Next Day"] - X_value["Adj Close"])
X_value = X_value.dropna()
X_value

     Adj Close     Preds  Next Day  Diff Preds  Diff Next Day
0     0.706173  0.677229  0.728267   -0.028944       0.022094
1     0.728267  0.678025  0.737950   -0.050242       0.009683
2     0.737950  0.680013  0.733381   -0.057937      -0.004569
3     0.733381  0.680416  0.747701   -0.052964       0.014320
4     0.747701  0.685097  0.761134   -0.062603       0.013433
..         ...       ...       ...         ...            ...
247   1.025207  1.011437  1.018693   -0.013771      -0.006514
248   1.018693  1.006030  1.059493   -0.012663       0.040800
249   1.059493  0.998969  1.079584   -0.060523       0.020091
250   1.079584  0.991106  1.095561   -0.088478       0.015977
251   1.095561  0.986842  1.104406   -0.108719       0.008846

[252 rows x 5 columns]

In [59]:
def assign_label(diff):
    if diff > 0.0:
        return 1  # Buy
    elif diff < -0.01:
        return 0  # Sell
    else:
        return 2  # Hold/Other

In [60]:
# Apply the function to assign labels
X_value['Signal Preds'] = X_value['Diff Preds'].apply(assign_label)
X_value['Signal True'] = X_value['Diff Next Day'].apply(assign_label)

# Dropping the intermediate difference columns if they are no longer needed
X_value = X_value.drop(columns=['Diff Preds', 'Diff Next Day'])

X_value

     Adj Close     Preds  Next Day  Signal Preds  Signal True
0     0.706173  0.677229  0.728267             0            1
1     0.728267  0.678025  0.737950             0            1
2     0.737950  0.680013  0.733381             0            2
3     0.733381  0.680416  0.747701             0            1
4     0.747701  0.685097  0.761134             0            1
..         ...       ...       ...           ...          ...
247   1.025207  1.011437  1.018693             0            2
248   1.018693  1.006030  1.059493             0            1
249   1.059493  0.998969  1.079584             0            1
250   1.079584  0.991106  1.095561             0            1
251   1.095561  0.986842  1.104406             0            1

[252 rows x 5 columns]

In [61]:
accuracy = accuracy_score(X_value["Signal True"], X_value["Signal Preds"])
print(f'Accuracy: {accuracy * 100:.2f}%')

# Precision
precision = precision_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'Precision: {precision:.4f}')

# Recall
recall = recall_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'Recall: {recall:.4f}')

# F1 Score
f1 = f1_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'F1 Score: {f1:.4f}')

Accuracy: 23.81%
Precision: 0.4232
Recall: 0.2381
F1 Score: 0.1952

In [62]:
y_true

0      0.728267
1      0.737950
2      0.733381
3      0.747701
4      0.761134
         ...
247    1.018693
248    1.059493
249    1.079584
250    1.095561
251    1.104406
Name: Adj Close, Length: 252, dtype: float64

In [63]:
X_value["Signal Preds"]

0      0
1      0
2      0
3      0
4      0
      ..
247    0
248    0
249    0
250    0
251    0
Name: Signal Preds, Length: 252, dtype: int64

In [64]:
signals = pd.DataFrame(X_value["Signal Preds"].values, columns=['Signal'])
signals

     Signal
0         0
1         0
2         0
3         0
4         0
..      ...
247       0
248       0
249       0
250       0
251       0

[252 rows x 1 columns]

In [65]:
signals["Signal"].value_counts()

Signal
0    211
1     31
2     10
Name: count, dtype: int64

In [66]:
signals["Date"] = date_test
signals

     Signal       Date
0         0 2023-01-23
1         0 2023-01-24
2         0 2023-01-25
3         0 2023-01-26
4         0 2023-01-27
..      ...        ...
247       0 2024-01-17
248       0 2024-01-18
249       0 2024-01-19
250       0 2024-01-22
251       0 2024-01-23

[252 rows x 2 columns]

In [67]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325668
1    141.737762
2    141.071487
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [68]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [69]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
buy_signals = signals[signals['Signal'] == 1]
sell_signals = signals[signals['Signal'] == 0]

# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]

# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))

# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))

# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [70]:
price_signal = stock_data[stock_data['Date'].isin(signals['Date'])]["Adj Close"]
price_signal = price_signal.reset_index()
price_signal = price_signal.drop(columns=["index"])
result = pd.concat([price_signal,signals], axis=1)
result

      Adj Close  Signal       Date
0    140.325668       0 2023-01-23
1    141.737762       0 2023-01-24
2    141.071487       0 2023-01-25
3    143.159805       0 2023-01-26
4    145.118851       0 2023-01-27
..          ...     ...        ...
247  182.679993       0 2024-01-17
248  188.630005       0 2024-01-18
249  191.559998       0 2024-01-19
250  193.889999       0 2024-01-22
251  195.179993       0 2024-01-23

[252 rows x 3 columns]

In [71]:
price_signal

      Adj Close
0    140.325668
1    141.737762
2    141.071487
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [72]:
sell_signals

     Signal       Date
0         0 2023-01-23
1         0 2023-01-24
2         0 2023-01-25
3         0 2023-01-26
4         0 2023-01-27
..      ...        ...
247       0 2024-01-17
248       0 2024-01-18
249       0 2024-01-19
250       0 2024-01-22
251       0 2024-01-23

[211 rows x 2 columns]

In [73]:
buy_prices

1293    148.308380
1294    148.796402
1295    146.117294
1296    147.322388
1297    146.814438
1298    144.722931
1299    145.320526
1300    150.419830
1301    153.208527
1303    152.252396
1305    147.900055
1306    149.862091
1407    178.373810
1408    179.321274
1409    177.715576
1410    177.496155
1411    177.556076
1412    179.223892
1413    177.216522
1414    176.337692
1415    173.771072
1416    174.260422
1417    175.608643
1418    176.996811
1419    180.881699
1444    170.465424
1465    167.998672
1466    170.065933
1511    181.910004
1512    181.179993
1513    185.559998
Name: Adj Close, dtype: float64