In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm
from sklearn.utils.class_weight import compute_class_weight

In [2]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [3]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722870  43.075001  42.314999  102223600
1  2018-01-03  40.715790  43.637501  42.990002  118071600
2  2018-01-04  40.904903  43.367500  43.020000   89738400
3  2018-01-05  41.370632  43.842499  43.262501   94640000
4  2018-01-08  41.216965  43.902500  43.482498   82271200
5  2018-01-09  41.212242  43.764999  43.352501   86336000
6  2018-01-10  41.202770  43.575001  43.250000   95839600
7  2018-01-11  41.436817  43.872501  43.622501   74670800
8  2018-01-12  41.864700  44.340000  43.912498  101672400
9  2018-01-16  41.651939  44.847500  44.035000  118263600
10 2018-01-17  42.339882  44.812500  43.767502  137547200
11 2018-01-18  42.377701  45.025002  44.562500  124773600
12 2018-01-19  42.188583  44.895000  44.352501  129700400
13 2018-01-22  41.843430  44.445000  44.150002  108434400
14 2018-01-23  41.852886  44.860001  44.205002  130756400
15 2018-01-24  41.186226  44.325001  43.299999  204420400
16 2018-01-25  40.451015  43.737499  42.632500  166116000
17 2018-01-26  40.545578  43.000000  42.514999  156572000
18 2018-01-29  39.706348  42.540001  41.767502  202561600
19 2018-01-30  39.472309  41.842499  41.174999  184192800
20 2018-01-31  39.581039  42.110001  41.625000  129915600
21 2018-02-01  39.663788  42.154999  41.689999  188923200
22 2018-02-02  37.942764  41.700001  40.025002  346375200
23 2018-02-05  36.994793  40.970001  39.000000  290954000
24 2018-02-06  38.540871  40.930000  38.500000  272975200
25 2018-02-07  37.715828  40.849998  39.767502  206434400
26 2018-02-08  36.678009  40.250000  38.757500  217562000
27 2018-02-09  37.126644  39.472500  37.560001  282690400
28 2018-02-12  38.622059  40.972500  39.377499  243278000
29 2018-02-13  39.008957  41.187500  40.412498  130196800
30 2018-02-14  39.728180  41.884998  40.720001  162579600
31 2018-02-15  41.062191  43.272499  42.250000  204588800
32 2018-02-16  40.929260  43.705002  42.942501  160704400
33 2018-02-20  40.791584  43.564999  42.855000  135722000
34 2018-02-21  40.606438  43.529999  42.752499  149886400
35 2018-02-22  40.945877  43.487499  42.927502  123967600
36 2018-02-23  41.657982  43.912498  43.384998  135249600
37 2018-02-26  42.481647  44.847500  44.052502  152648800
38 2018-02-27  42.343979  45.119999  44.540001  155712400
39 2018-02-28  42.279873  45.154999  44.512501  151128400
40 2018-03-01  41.539299  44.945000  43.165001  195208000
41 2018-03-02  41.826511  44.075001  43.112499  153816000
42 2018-03-05  41.971302  44.435001  43.630001  113605600
43 2018-03-06  41.935699  44.562500  44.032501   95154000
44 2018-03-07  41.546417  43.962502  43.567501  126814000

In [4]:
time_step = 44

In [5]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [6]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [7]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma_s = talib.SMA(data["Adj Close"], timeperiod=20)
    sma_l = talib.SMA(data["Adj Close"], timeperiod=50)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA_SHORT': sma_s,
        'SMA_LONG': sma_l,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [8]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724163,117105600.0
15,NaN,NaN,55.580781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706159,-87314800.0
16,NaN,NaN,45.152512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695096,-253430800.0
17,NaN,NaN,46.541805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034337,-73.817777,2.684660,-96858800.0
18,NaN,NaN,37.470444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639025,-81.393119,2.635357,-299420400.0
19,NaN,NaN,35.398370,NaN,NaN,42.761511,41.213179,39.664848,41.213179,NaN,NaN,-61.987574,-75.553645,2.599699,-483613200.0
20,NaN,NaN,37.137588,NaN,NaN,42.849897,41.156088,39.462279,41.156088,NaN,NaN,-49.633771,-63.086790,2.602413,-353697600.0
21,NaN,NaN,38.494703,NaN,NaN,42.910292,41.103488,39.296684,41.103488,NaN,NaN,-41.626480,-51.082608,2.600381,-164774400.0
22,NaN,NaN,25.947771,NaN,NaN,43.228473,40.955381,38.682289,40.955381,NaN,NaN,-40.766165,-44.008805,2.560083,-511149600.0
23,NaN,NaN,21.743757,NaN,NaN,43.578812,40.736589,37.894366,40.736589,NaN,NaN,-38.059467,-40.150704,2.593451,-802103600.0
24,NaN,NaN,39.079685,NaN,NaN,43.590208,40.602784,37.615361,40.602784,NaN,NaN,-24.766604,-34.530745,2.689291,-529128400.0
25,NaN,NaN,34.666358,NaN,NaN,43.652101,40.427963,37.203825,40.427963,NaN,NaN,-14.972445,-25.932839,2.662136,-735562800.0
26,NaN,NaN,30.066653,NaN,NaN,43.790973,40.201725,36.612478,40.201725,NaN,NaN,-13.427850,-17.722300,2.652996,-953124800.0
27,NaN,NaN,34.135131,NaN,NaN,43.765510,39.986217,36.206924,39.986217,NaN,NaN,-15.615441,-14.671912,2.663103,-670434400.0
28,NaN,NaN,45.513708,NaN,NaN,43.544885,39.824085,36.103284,39.824085,NaN,NaN,-6.294919,-11.779403,2.747585,-427156400.0
29,NaN,NaN,48.015920,NaN,NaN,43.330503,39.691936,36.053368,39.691936,NaN,NaN,11.072759,-3.612533,2.734575,-296959600.0
30,NaN,NaN,52.392768,NaN,NaN,42.991934,39.561350,36.130767,39.561350,NaN,NaN,26.336971,10.371604,2.744680,-134380000.0
31,NaN,NaN,59.246627,NaN,NaN,42.753755,39.495575,36.237395,39.495575,NaN,NaN,41.539705,26.316478,2.801797,70208800.0
32,NaN,NaN,58.345226,NaN,NaN,42.524616,39.432609,36.340601,39.432609,NaN,NaN,51.997668,39.958115,2.790441,-90495600.0
33,-0.373864,-0.940885,57.371649,NaN,NaN,42.339138,39.380017,36.420895,39.380017,NaN,NaN,56.241861,49.926411,2.779390,-226217600.0
34,-0.274210,-0.807550,56.017917,NaN,NaN,42.113882,39.317694,36.521506,39.317694,NaN,NaN,52.331311,53.523613,2.776464,-376104000.0
35,-0.165931,-0.679226,57.975713,NaN,NaN,42.071541,39.305677,36.539813,39.305677,NaN,NaN,52.421448,53.664873,2.783935,-252136400.0
36,-0.022400,-0.547861,61.815806,NaN,NaN,42.278025,39.366025,36.454025,39.366025,NaN,NaN,56.395097,53.715952,2.796984,-116886800.0
37,0.156015,-0.407086,65.717922,NaN,NaN,42.641729,39.462828,36.283927,39.462828,NaN,NaN,62.381636,57.066060,2.825022,35762000.0
38,0.283038,-0.269061,64.530915,NaN,NaN,43.012924,39.594710,36.176496,39.594710,NaN,NaN,65.108457,61.295063,2.811688,-119950400.0
39,0.374218,-0.140405,63.951661,NaN,NaN,43.346789,39.735088,36.123387,39.735088,NaN,NaN,64.320030,63.936708,2.811641,-271078800.0
40,0.382313,-0.035862,57.527298,NaN,NaN,43.527907,39.833001,36.138096,39.833001,NaN,NaN,59.272764,62.900417,2.801175,-466286800.0
41,0.407211,0.052753,59.237542,NaN,NaN,43.735165,39.941137,36.147110,39.941137,NaN,NaN,52.308980,58.633925,2.782213,-312470800.0
42,0.433627,0.128928,60.109587,NaN,NaN,43.918536,40.142564,36.366592,40.142564,NaN,NaN,42.550425,51.377390,2.769804,-198865200.0
43,0.446542,0.192451,59.770981,NaN,NaN,43.949836,40.389610,36.829383,40.389610,NaN,40.596322,34.223028,43.027478,2.757047,-294019200.0
44,0.420518,0.238064,56.052919,4.051403,0.823547,44.028290,40.539887,37.051484,40.539887,NaN,40.638548,12.020187,29.597880,2.704886,-420833200.0

In [9]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722870
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715790
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904903
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370632
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216965
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212242
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202770
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436817
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864700
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651939
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339882
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377701
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188583
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843430
14,NaN,NaN,68.998483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724163,117105600.0,41.852886
15,NaN,NaN,55.580781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706159,-87314800.0,41.186226
16,NaN,NaN,45.152512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695096,-253430800.0,40.451015
17,NaN,NaN,46.541805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034337,-73.817777,2.684660,-96858800.0,40.545578
18,NaN,NaN,37.470444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639025,-81.393119,2.635357,-299420400.0,39.706348
19,NaN,NaN,35.398370,NaN,NaN,42.761511,41.213179,39.664848,41.213179,NaN,NaN,-61.987574,-75.553645,2.599699,-483613200.0,39.472309
20,NaN,NaN,37.137588,NaN,NaN,42.849897,41.156088,39.462279,41.156088,NaN,NaN,-49.633771,-63.086790,2.602413,-353697600.0,39.581039
21,NaN,NaN,38.494703,NaN,NaN,42.910292,41.103488,39.296684,41.103488,NaN,NaN,-41.626480,-51.082608,2.600381,-164774400.0,39.663788
22,NaN,NaN,25.947771,NaN,NaN,43.228473,40.955381,38.682289,40.955381,NaN,NaN,-40.766165,-44.008805,2.560083,-511149600.0,37.942764
23,NaN,NaN,21.743757,NaN,NaN,43.578812,40.736589,37.894366,40.736589,NaN,NaN,-38.059467,-40.150704,2.593451,-802103600.0,36.994793
24,NaN,NaN,39.079685,NaN,NaN,43.590208,40.602784,37.615361,40.602784,NaN,NaN,-24.766604,-34.530745,2.689291,-529128400.0,38.540871
25,NaN,NaN,34.666358,NaN,NaN,43.652101,40.427963,37.203825,40.427963,NaN,NaN,-14.972445,-25.932839,2.662136,-735562800.0,37.715828
26,NaN,NaN,30.066653,NaN,NaN,43.790973,40.201725,36.612478,40.201725,NaN,NaN,-13.427850,-17.722300,2.652996,-953124800.0,36.678009
27,NaN,NaN,34.135131,NaN,NaN,43.765510,39.986217,36.206924,39.986217,NaN,NaN,-15.615441,-14.671912,2.663103,-670434400.0,37.126644
28,NaN,NaN,45.513708,NaN,NaN,43.544885,39.824085,36.103284,39.824085,NaN,NaN,-6.294919,-11.779403,2.747585,-427156400.0,38.622059
29,NaN,NaN,48.015920,NaN,NaN,43.330503,39.691936,36.053368,39.691936,NaN,NaN,11.072759,-3.612533,2.734575,-296959600.0,39.008957
30,NaN,NaN,52.392768,NaN,NaN,42.991934,39.561350,36.130767,39.561350,NaN,NaN,26.336971,10.371604,2.744680,-134380000.0,39.728180
31,NaN,NaN,59.246627,NaN,NaN,42.753755,39.495575,36.237395,39.495575,NaN,NaN,41.539705,26.316478,2.801797,70208800.0,41.062191
32,NaN,NaN,58.345226,NaN,NaN,42.524616,39.432609,36.340601,39.432609,NaN,NaN,51.997668,39.958115,2.790441,-90495600.0,40.929260
33,-0.373864,-0.940885,57.371649,NaN,NaN,42.339138,39.380017,36.420895,39.380017,NaN,NaN,56.241861,49.926411,2.779390,-226217600.0,40.791584
34,-0.274210,-0.807550,56.017917,NaN,NaN,42.113882,39.317694,36.521506,39.317694,NaN,NaN,52.331311,53.523613,2.776464,-376104000.0,40.606438
35,-0.165931,-0.679226,57.975713,NaN,NaN,42.071541,39.305677,36.539813,39.305677,NaN,NaN,52.421448,53.664873,2.783935,-252136400.0,40.945877
36,-0.022400,-0.547861,61.815806,NaN,NaN,42.278025,39.366025,36.454025,39.366025,NaN,NaN,56.395097,53.715952,2.796984,-116886800.0,41.657982
37,0.156015,-0.407086,65.717922,NaN,NaN,42.641729,39.462828,36.283927,39.462828,NaN,NaN,62.381636,57.066060,2.825022,35762000.0,42.481647
38,0.283038,-0.269061,64.530915,NaN,NaN,43.012924,39.594710,36.176496,39.594710,NaN,NaN,65.108457,61.295063,2.811688,-119950400.0,42.343979
39,0.374218,-0.140405,63.951661,NaN,NaN,43.346789,39.735088,36.123387,39.735088,NaN,NaN,64.320030,63.936708,2.811641,-271078800.0,42.279873
40,0.382313,-0.035862,57.527298,NaN,NaN,43.527907,39.833001,36.138096,39.833001,NaN,NaN,59.272764,62.900417,2.801175,-466286800.0,41.539299
41,0.407211,0.052753,59.237542,NaN,NaN,43.735165,39.941137,36.147110,39.941137,NaN,NaN,52.308980,58.633925,2.782213,-312470800.0,41.826511
42,0.433627,0.128928,60.109587,NaN,NaN,43.918536,40.142564,36.366592,40.142564,NaN,NaN,42.550425,51.377390,2.769804,-198865200.0,41.971302
43,0.446542,0.192451,59.770981,NaN,NaN,43.949836,40.389610,36.829383,40.389610,NaN,40.596322,34.223028,43.027478,2.757047,-294019200.0,41.935699
44,0.420518,0.238064,56.052919,4.051403,0.823547,44.028290,40.539887,37.051484,40.539887,NaN,40.638548,12.020187,29.597880,2.704886,-420833200.0,41.546417

In [10]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.567013,0.443928,58.241572,7.100857,1.143597,43.382887,41.728833,40.074779,41.728833,40.814300,41.035722,-7.013413,-3.909660,2.715222,-3.124152e+08,42.355839
1,0.548493,0.464841,58.592059,7.332813,1.202900,43.261030,41.862708,40.464386,41.862708,40.847956,41.096608,-20.016882,-8.448448,2.714432,-2.214400e+08,42.405670
2,0.515804,0.475034,57.044886,6.516224,0.819328,43.280287,41.922405,40.564524,41.922405,40.878763,41.148143,-27.992068,-18.340788,2.690139,-3.790588e+08,42.256145
3,0.432811,0.466589,50.806400,3.052144,-0.254192,43.245417,41.956468,40.667519,41.956468,40.892875,41.168693,-36.985499,-28.331483,2.648797,-5.128460e+08,41.610508
4,0.361720,0.445615,50.674766,2.976561,-0.055672,43.183914,41.996702,40.809490,41.996702,40.897388,41.187696,-46.752042,-37.243203,2.644561,-5.914436e+08,41.596268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [11]:
# Define the conditions
conditions = [
    (indicators_with_price['RSI'] < 30), # al sinyali
    (indicators_with_price['RSI'] > 70) # sat sinyali
]

# Define the choices corresponding to each condition
choices = [2, 1] # 1 sat demek 2 al

# Use np.select to apply the conditions and choices
# The default value is 0 (for when the RSI is between 30 and 70)
indicators_with_price['RSI_SIGNAL'] = np.select(conditions, choices, default=0)

conditions = [
    (indicators_with_price['SMA_SHORT'] > indicators_with_price['SMA_LONG']), # al sinyali
    (indicators_with_price['SMA_LONG'] > indicators_with_price['SMA_SHORT']) # sat sinyali
]
# Define the choices corresponding to each condition
choices = [2, 1] # 1 sat demek 2 al

indicators_with_price['SMA_SIGNAL'] = np.select(conditions, choices, default=0)

# Display the dataframe to verify the results

# Create a column 'MACD_Signal' to hold the trading signal
indicators_with_price['MACD_Signal'] = 0

# Generate buy/sell signals
indicators_with_price['MACD_Signal'][indicators_with_price['MACD'] > indicators_with_price['MACD_signal']] = 2  # Buy signal
indicators_with_price['MACD_Signal'][indicators_with_price['MACD'] < indicators_with_price['MACD_signal']] = 1  # Sell signal

# Create a column 'BB_Signal' to hold the trading signal
indicators_with_price['BB_Signal'] = 0

# Generate buy/sell signals
indicators_with_price['BB_Signal'][indicators_with_price['Adj Close'] < indicators_with_price['Lower_BB']] = 2  # Buy signal
indicators_with_price['BB_Signal'][indicators_with_price['Adj Close'] > indicators_with_price['Upper_BB']] = 1  # Sell signal



indicators_with_price.head(50)

/tmp/ipykernel_43979/840148971.py:29: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_43979/840148971.py:30: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_43979/840148971.py:36: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_43979/840148971.py:37: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,RSI_SIGNAL,SMA_SIGNAL,MACD_Signal,BB_Signal
0,0.567013,0.443928,58.241572,7.100857,1.143597,43.382887,41.728833,40.074779,41.728833,40.814300,41.035722,-7.013413,-3.909660,2.715222,-3.124152e+08,42.355839,0,2,2,0
1,0.548493,0.464841,58.592059,7.332813,1.202900,43.261030,41.862708,40.464386,41.862708,40.847956,41.096608,-20.016882,-8.448448,2.714432,-2.214400e+08,42.405670,0,2,2,0
2,0.515804,0.475034,57.044886,6.516224,0.819328,43.280287,41.922405,40.564524,41.922405,40.878763,41.148143,-27.992068,-18.340788,2.690139,-3.790588e+08,42.256145,0,2,2,0
3,0.432811,0.466589,50.806400,3.052144,-0.254192,43.245417,41.956468,40.667519,41.956468,40.892875,41.168693,-36.985499,-28.331483,2.648797,-5.128460e+08,41.610508,0,2,1,0
4,0.361720,0.445615,50.674766,2.976561,-0.055672,43.183914,41.996702,40.809490,41.996702,40.897388,41.187696,-46.752042,-37.243203,2.644561,-5.914436e+08,41.596268,0,2,1,0
5,0.226726,0.401838,42.776424,-1.895762,-1.685970,43.175299,41.999076,40.822853,41.999076,40.886127,41.163973,-59.960211,-47.899251,2.611109,-7.396632e+08,40.653912,0,2,1,2
6,0.072555,0.335981,38.805926,-4.708028,-2.298214,43.330934,41.955756,40.580579,41.955756,40.863472,41.115773,-60.364744,-55.692332,2.604322,-9.056264e+08,40.079487,0,2,1,2
7,-0.123098,0.244165,33.410026,-9.019855,-3.037197,43.669841,41.830426,39.991012,41.830426,40.822444,41.028467,-57.037842,-59.120932,2.589764,-1.069742e+09,39.151386,0,2,1,2
8,-0.126721,0.169988,48.771956,0.230814,-0.833458,43.603894,41.756843,39.909791,41.756843,40.813907,41.027645,-35.113187,-50.838591,2.699325,-9.195768e+08,41.009972,0,2,1,0
9,-0.212000,0.093590,42.761333,-4.462424,-1.894463,43.620645,41.637565,39.654485,41.637565,40.775782,40.980124,-25.755897,-39.302308,2.704910,-1.083267e+09,39.958424,0,2,1,0
10,-0.311617,0.012549,40.504317,-6.346417,-1.669300,43.661171,41.499417,39.337664,41.499417,40.733081,40.915093,-23.129894,-27.999659,2.693601,-1.249941e+09,39.516926,0,2,1,0
11,-0.361498,-0.062261,42.777690,-4.867421,-0.625511,43.694931,41.413728,39.132525,41.413728,40.682794,40.866667,-31.638999,-26.841597,2.745528,-1.096347e+09,39.825504,0,2,1,0
12,-0.417288,-0.133266,41.338282,-5.999354,-0.981186,43.709490,41.300622,38.891754,41.300622,40.626528,40.808788,-33.350010,-29.372968,2.721525,-1.246694e+09,39.564392,0,2,1,0
13,-0.423862,-0.191385,44.466584,-4.030385,0.263954,43.655484,41.200572,38.745660,41.200572,40.582162,40.771522,-30.537714,-31.842241,2.714496,-1.125582e+09,39.970303,0,2,1,0
14,-0.363211,-0.225750,49.885867,-0.435777,1.262310,43.579269,41.140518,38.701767,41.140518,40.559986,40.769882,-23.649232,-29.178985,2.737188,-9.871604e+08,40.734619,0,2,1,0
15,-0.289021,-0.238405,51.759449,0.859654,1.436043,43.546087,41.114051,38.682015,41.114051,40.543270,40.780869,-13.681338,-22.622761,2.743309,-8.794276e+08,41.017082,0,2,1,0
16,-0.311294,-0.252983,45.026001,-3.853591,0.304142,43.457724,41.012458,38.567192,41.012458,40.518904,40.744738,-15.941607,-17.757392,2.697567,-1.019449e+09,39.967930,0,2,1,0
17,-0.293576,-0.261101,47.789636,-2.010599,2.421562,43.223490,40.894605,38.565721,40.894605,40.517170,40.727831,-20.849017,-16.823988,2.740924,-9.033780e+08,40.364326,0,2,1,0
18,-0.215755,-0.252032,52.696933,1.419618,4.129116,42.889422,40.794080,38.698739,40.794080,40.528737,40.745434,-19.855077,-18.881901,2.769121,-7.897436e+08,41.123909,0,2,2,0
19,-0.167664,-0.235158,51.380441,0.543896,2.390762,42.607664,40.704712,38.801760,40.704712,40.553242,40.753710,-10.385054,-17.029716,2.739618,-8.794700e+08,40.931633,0,2,2,0
20,-0.095885,-0.207304,53.978907,2.354500,3.619328,42.427108,40.653678,38.880247,40.653678,40.590499,40.779552,0.476861,-9.921090,2.745243,-7.879128e+08,41.335155,0,2,2,0
21,-0.027383,-0.171320,54.880209,2.981752,4.797195,42.237333,40.607154,38.976975,40.607154,40.628383,40.810470,4.591568,-1.772208,2.736643,-6.874156e+08,41.475204,0,1,2,0
22,0.047238,-0.127608,56.572317,4.145741,4.607288,42.118850,40.581044,39.043237,40.581044,40.669786,40.851512,13.924890,6.331106,2.724904,-6.011020e+08,41.733932,0,1,2,0
23,0.150986,-0.071889,60.145955,6.689083,3.686302,42.272663,40.615936,38.959210,40.615936,40.757097,40.916261,22.180740,13.565733,2.744630,-4.946804e+08,42.308361,0,1,2,1
24,0.222976,-0.012916,59.277692,6.212450,3.204460,42.395826,40.646794,38.897761,40.646794,40.861470,40.973913,28.084313,21.396648,2.719774,-5.776984e+08,42.213417,0,1,2,0
25,0.181404,0.025948,49.567797,0.427664,1.288902,42.421428,40.664952,38.908476,40.664952,40.910994,40.975831,20.146134,23.470396,2.642225,-7.169336e+08,41.017082,0,1,2,0
26,0.012704,0.023299,39.724022,-6.863806,-1.725666,42.461946,40.627804,38.793662,40.627804,40.943408,40.902973,-8.290915,13.313177,2.581203,-9.788980e+08,39.336525,0,1,1,0
27,-0.128703,-0.007101,39.156267,-7.330568,-1.706673,42.454272,40.631364,38.808457,40.631364,40.994300,40.828289,-34.550017,-7.564933,2.567793,-1.124960e+09,39.222588,0,1,1,0
28,-0.281576,-0.061996,36.466749,-9.553060,-2.114944,42.515714,40.514698,38.513681,40.514698,41.025300,40.732661,-45.877244,-29.572725,2.552945,-1.259728e+09,38.676640,0,1,1,0
29,-0.384695,-0.126536,37.885051,-8.729396,-1.761272,42.577349,40.459035,38.340721,40.459035,41.029762,40.648772,-39.397802,-39.941688,2.561903,-1.146200e+09,38.845165,0,1,1,0
30,-0.450309,-0.191291,39.061369,-8.061881,-1.965397,42.610305,40.432212,38.254120,40.432212,41.029192,40.574626,-33.203278,-39.492775,2.563720,-1.034348e+09,38.980480,0,1,1,0
31,-0.532561,-0.259545,36.575178,-9.947394,-3.128506,42.686409,40.367411,38.048413,40.367411,41.005218,40.483730,-32.806025,-35.135701,2.530741,-1.176971e+09,38.529476,0,1,1,0
32,-0.535266,-0.314689,42.657026,-6.489524,-3.254318,42.697387,40.350558,38.003729,40.350558,40.968521,40.427890,-28.595072,-31.534791,2.584654,-1.007261e+09,39.227329,0,1,1,0
33,-0.458573,-0.343466,49.472291,-2.193910,-2.205151,42.701498,40.358984,38.016471,40.358984,40.952712,40.415043,-18.764757,-26.721951,2.619512,-7.929836e+08,40.138828,0,1,1,0
34,-0.251813,-0.325135,59.544981,5.401848,-0.367908,42.852525,40.417851,37.983178,40.417851,40.975120,40.481573,5.866509,-13.831107,2.739452,-5.268260e+08,41.911964,0,1,2,0
35,-0.080893,-0.276287,59.913626,5.709041,0.448620,42.984213,40.466393,37.948573,40.466393,41.002749,40.548521,25.969112,4.356955,2.719708,-3.905532e+08,41.987919,0,1,2,0
36,0.185351,-0.183959,66.948264,12.047558,1.808735,43.506953,40.649759,37.792565,40.649759,41.056537,40.685709,45.736733,25.857452,2.816485,-1.657480e+08,43.635246,0,1,2,1
37,0.417020,-0.063763,68.103507,13.191918,1.979649,44.022552,40.829090,37.635628,40.829090,41.102396,40.830831,51.666115,41.123987,2.849754,4.057600e+06,43.950951,0,1,2,0
38,0.610626,0.071115,68.887195,13.958480,2.226513,44.489630,40.981005,37.472381,40.981005,41.136008,40.978892,58.084122,51.828990,2.832204,1.176688e+08,44.162212,0,1,2,0
39,0.780158,0.212923,70.053447,15.087762,2.926739,44.982157,41.158082,37.334006,41.158082,41.178591,41.134193,59.732832,56.494356,2.821888,2.105136e+08,44.473156,1,1,2,0
40,0.954839,0.361307,72.337992,17.358438,3.109512,45.541700,41.346789,37.151878,41.346789,41.235180,41.310865,63.227889,60.348281,2.843135,3.224708e+08,45.109306,1,2,2,0
41,1.067128,0.502471,70.769813,16.498633,2.216347,45.997979,41.519915,37.041852,41.519915,41.303148,41.472059,64.911971,62.624231,2.811889,2.176220e+08,44.937725,1,2,2,0
42,1.134581,0.628893,69.774559,15.967469,1.698486,46.380500,41.674863,36.969226,41.674863,41.363276,41.621429,64.592808,64.244223,2.785667,1.345068e+08,44.832893,0,2,2,0
43,1.141994,0.731513,65.895503,13.901978,1.706421,46.631599,41.780717,36.929834,41.780717,41.412358,41.746051,61.526769,63.677183,2.724877,3.972600e+07,44.425426,0,2,2,0
44,1.167862,0.818783,67.853843,15.469558,2.484196,46.941610,41.912047,36.882484,41.912047,41.470445,41.883561,61.088792,62.402790,2.722355,1.164584e+08,44.840034,0,2,2,0
45,1.152200,0.885466,65.100637,14.016837,2.150814,47.228049,42.089017,36.949986,42.089017,41.530646,42.002358,59.272293,60.629285,2.698435,4.728240e+07,44.556484,0,2,2,0
46,1.113873,0.931148,63.514589,13.184156,2.138298,47.411586,42.341913,37.272241,42.341913,41.578539,42.108673,56.482884,58.947990,2.676833,-2.590840e+07,44.394444,0,2,2,0
47,1.096243,0.964167,65.282781,14.425542,3.098488,47.573567,42.616234,37.658901,42.616234,41.618292,42.224243,45.620400,53.791859,2.694421,4.769480e+07,44.708996,0,2,2,0
48,1.061004,0.983534,64.091718,13.832485,3.000725,47.592555,42.912251,38.231948,42.912251,41.647543,42.329698,34.736788,45.613357,2.681320,-1.326800e+07,44.596992,0,2,2,0
49,1.044113,0.995650,65.806886,14.983571,4.229023,47.574091,43.214140,38.854189,43.214140,41.690822,42.443176,22.112404,34.156531,2.670369,6.696560e+07,44.882935,0,2,2,0

In [12]:
# Sum the signals for each row
indicators_with_price['Sum_Buy_Signals'] = (indicators_with_price[['RSI_SIGNAL', 'SMA_SIGNAL', 'MACD_Signal', 'BB_Signal']] == 2).sum(axis=1)
indicators_with_price['Sum_Sell_Signals'] = (indicators_with_price[['RSI_SIGNAL', 'SMA_SIGNAL', 'MACD_Signal', 'BB_Signal']] == 1).sum(axis=1)

# Define the conditions
conditions = [
    (indicators_with_price['Sum_Buy_Signals'] >= 3), # At least three buy signals - Strong Buy
    (indicators_with_price['Sum_Buy_Signals'] >= 2), # At least two buy signals - Buy
    (indicators_with_price['Sum_Sell_Signals'] >= 3), # At least three sell signals - Strong Sell
    (indicators_with_price['Sum_Sell_Signals'] >= 2), # At least two sell signals - Sell
]

# Define the choices corresponding to each condition
choices = [4, 3, 1, 2] # Strong Buy, Buy, Strong Sell, Sell

# Use np.select to apply the conditions and choices
# The default value is 0 (Neutral)
indicators_with_price['Signal'] = np.select(conditions, choices, default=0)

# Remove the sum columns if they are no longer needed
indicators_with_price = indicators_with_price.drop(columns=['Sum_Buy_Signals', 'Sum_Sell_Signals'])

# Display the dataframe to verify the results
indicators_with_price[['RSI_SIGNAL', 'SMA_SIGNAL', 'MACD_Signal', 'BB_Signal', 'Signal']].head(50)

    RSI_SIGNAL  SMA_SIGNAL  MACD_Signal  BB_Signal  Signal
0            0           2            2          0       3
1            0           2            2          0       3
2            0           2            2          0       3
3            0           2            1          0       0
4            0           2            1          0       0
5            0           2            1          2       3
6            0           2            1          2       3
7            0           2            1          2       3
8            0           2            1          0       0
9            0           2            1          0       0
10           0           2            1          0       0
11           0           2            1          0       0
12           0           2            1          0       0
13           0           2            1          0       0
14           0           2            1          0       0
15           0           2            1          0       0
16           0           2            1          0       0
17           0           2            1          0       0
18           0           2            2          0       3
19           0           2            2          0       3
20           0           2            2          0       3
21           0           1            2          0       0
22           0           1            2          0       0
23           0           1            2          1       2
24           0           1            2          0       0
25           0           1            2          0       0
26           0           1            1          0       2
27           0           1            1          0       2
28           0           1            1          0       2
29           0           1            1          0       2
30           0           1            1          0       2
31           0           1            1          0       2
32           0           1            1          0       2
33           0           1            1          0       2
34           0           1            2          0       0
35           0           1            2          0       0
36           0           1            2          1       2
37           0           1            2          0       0
38           0           1            2          0       0
39           1           1            2          0       2
40           1           2            2          0       3
41           1           2            2          0       3
42           0           2            2          0       3
43           0           2            2          0       3
44           0           2            2          0       3
45           0           2            2          0       3
46           0           2            2          0       3
47           0           2            2          0       3
48           0           2            2          0       3
49           0           2            2          0       3

In [13]:
signal_distribution = indicators_with_price['Signal'].value_counts().sort_index()
signal_distribution

Signal
0    697
1      4
2    263
3    504
4      7
Name: count, dtype: int64

In [14]:
# indicators_with_price['Next_Adj_Close'] = indicators_with_price['Adj Close'].shift(-1)
# indicators_with_price['Return'] = ((indicators_with_price['Next_Adj_Close'] - indicators_with_price['Adj Close'])/indicators_with_price['Adj Close'])*100
# indicators_with_price['Signal'] = np.where(indicators_with_price['Return'] > 1, 1,
#                                            np.where(indicators_with_price['Return'] < -1, 2, 0))
# indicators_with_price

In [15]:
indicators_with_price["Signal"].value_counts()

Signal
0    697
3    504
2    263
4      7
1      4
Name: count, dtype: int64

In [16]:
# indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close', 'Return'])
# indicators_with_price

In [17]:
indicators_with_price.drop(columns=['RSI_SIGNAL', 'SMA_SIGNAL', 'MACD_Signal', 'BB_Signal'], inplace=True)
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Signal
0,0.567013,0.443928,58.241572,7.100857,1.143597,43.382887,41.728833,40.074779,41.728833,40.814300,41.035722,-7.013413,-3.909660,2.715222,-3.124152e+08,42.355839,3
1,0.548493,0.464841,58.592059,7.332813,1.202900,43.261030,41.862708,40.464386,41.862708,40.847956,41.096608,-20.016882,-8.448448,2.714432,-2.214400e+08,42.405670,3
2,0.515804,0.475034,57.044886,6.516224,0.819328,43.280287,41.922405,40.564524,41.922405,40.878763,41.148143,-27.992068,-18.340788,2.690139,-3.790588e+08,42.256145,3
3,0.432811,0.466589,50.806400,3.052144,-0.254192,43.245417,41.956468,40.667519,41.956468,40.892875,41.168693,-36.985499,-28.331483,2.648797,-5.128460e+08,41.610508,0
4,0.361720,0.445615,50.674766,2.976561,-0.055672,43.183914,41.996702,40.809490,41.996702,40.897388,41.187696,-46.752042,-37.243203,2.644561,-5.914436e+08,41.596268,0
5,0.226726,0.401838,42.776424,-1.895762,-1.685970,43.175299,41.999076,40.822853,41.999076,40.886127,41.163973,-59.960211,-47.899251,2.611109,-7.396632e+08,40.653912,3
6,0.072555,0.335981,38.805926,-4.708028,-2.298214,43.330934,41.955756,40.580579,41.955756,40.863472,41.115773,-60.364744,-55.692332,2.604322,-9.056264e+08,40.079487,3
7,-0.123098,0.244165,33.410026,-9.019855,-3.037197,43.669841,41.830426,39.991012,41.830426,40.822444,41.028467,-57.037842,-59.120932,2.589764,-1.069742e+09,39.151386,3
8,-0.126721,0.169988,48.771956,0.230814,-0.833458,43.603894,41.756843,39.909791,41.756843,40.813907,41.027645,-35.113187,-50.838591,2.699325,-9.195768e+08,41.009972,0
9,-0.212000,0.093590,42.761333,-4.462424,-1.894463,43.620645,41.637565,39.654485,41.637565,40.775782,40.980124,-25.755897,-39.302308,2.704910,-1.083267e+09,39.958424,0
10,-0.311617,0.012549,40.504317,-6.346417,-1.669300,43.661171,41.499417,39.337664,41.499417,40.733081,40.915093,-23.129894,-27.999659,2.693601,-1.249941e+09,39.516926,0
11,-0.361498,-0.062261,42.777690,-4.867421,-0.625511,43.694931,41.413728,39.132525,41.413728,40.682794,40.866667,-31.638999,-26.841597,2.745528,-1.096347e+09,39.825504,0
12,-0.417288,-0.133266,41.338282,-5.999354,-0.981186,43.709490,41.300622,38.891754,41.300622,40.626528,40.808788,-33.350010,-29.372968,2.721525,-1.246694e+09,39.564392,0
13,-0.423862,-0.191385,44.466584,-4.030385,0.263954,43.655484,41.200572,38.745660,41.200572,40.582162,40.771522,-30.537714,-31.842241,2.714496,-1.125582e+09,39.970303,0
14,-0.363211,-0.225750,49.885867,-0.435777,1.262310,43.579269,41.140518,38.701767,41.140518,40.559986,40.769882,-23.649232,-29.178985,2.737188,-9.871604e+08,40.734619,0
15,-0.289021,-0.238405,51.759449,0.859654,1.436043,43.546087,41.114051,38.682015,41.114051,40.543270,40.780869,-13.681338,-22.622761,2.743309,-8.794276e+08,41.017082,0
16,-0.311294,-0.252983,45.026001,-3.853591,0.304142,43.457724,41.012458,38.567192,41.012458,40.518904,40.744738,-15.941607,-17.757392,2.697567,-1.019449e+09,39.967930,0
17,-0.293576,-0.261101,47.789636,-2.010599,2.421562,43.223490,40.894605,38.565721,40.894605,40.517170,40.727831,-20.849017,-16.823988,2.740924,-9.033780e+08,40.364326,0
18,-0.215755,-0.252032,52.696933,1.419618,4.129116,42.889422,40.794080,38.698739,40.794080,40.528737,40.745434,-19.855077,-18.881901,2.769121,-7.897436e+08,41.123909,3
19,-0.167664,-0.235158,51.380441,0.543896,2.390762,42.607664,40.704712,38.801760,40.704712,40.553242,40.753710,-10.385054,-17.029716,2.739618,-8.794700e+08,40.931633,3
20,-0.095885,-0.207304,53.978907,2.354500,3.619328,42.427108,40.653678,38.880247,40.653678,40.590499,40.779552,0.476861,-9.921090,2.745243,-7.879128e+08,41.335155,3
21,-0.027383,-0.171320,54.880209,2.981752,4.797195,42.237333,40.607154,38.976975,40.607154,40.628383,40.810470,4.591568,-1.772208,2.736643,-6.874156e+08,41.475204,0
22,0.047238,-0.127608,56.572317,4.145741,4.607288,42.118850,40.581044,39.043237,40.581044,40.669786,40.851512,13.924890,6.331106,2.724904,-6.011020e+08,41.733932,0
23,0.150986,-0.071889,60.145955,6.689083,3.686302,42.272663,40.615936,38.959210,40.615936,40.757097,40.916261,22.180740,13.565733,2.744630,-4.946804e+08,42.308361,2
24,0.222976,-0.012916,59.277692,6.212450,3.204460,42.395826,40.646794,38.897761,40.646794,40.861470,40.973913,28.084313,21.396648,2.719774,-5.776984e+08,42.213417,0
25,0.181404,0.025948,49.567797,0.427664,1.288902,42.421428,40.664952,38.908476,40.664952,40.910994,40.975831,20.146134,23.470396,2.642225,-7.169336e+08,41.017082,0
26,0.012704,0.023299,39.724022,-6.863806,-1.725666,42.461946,40.627804,38.793662,40.627804,40.943408,40.902973,-8.290915,13.313177,2.581203,-9.788980e+08,39.336525,2
27,-0.128703,-0.007101,39.156267,-7.330568,-1.706673,42.454272,40.631364,38.808457,40.631364,40.994300,40.828289,-34.550017,-7.564933,2.567793,-1.124960e+09,39.222588,2
28,-0.281576,-0.061996,36.466749,-9.553060,-2.114944,42.515714,40.514698,38.513681,40.514698,41.025300,40.732661,-45.877244,-29.572725,2.552945,-1.259728e+09,38.676640,2
29,-0.384695,-0.126536,37.885051,-8.729396,-1.761272,42.577349,40.459035,38.340721,40.459035,41.029762,40.648772,-39.397802,-39.941688,2.561903,-1.146200e+09,38.845165,2
30,-0.450309,-0.191291,39.061369,-8.061881,-1.965397,42.610305,40.432212,38.254120,40.432212,41.029192,40.574626,-33.203278,-39.492775,2.563720,-1.034348e+09,38.980480,2
31,-0.532561,-0.259545,36.575178,-9.947394,-3.128506,42.686409,40.367411,38.048413,40.367411,41.005218,40.483730,-32.806025,-35.135701,2.530741,-1.176971e+09,38.529476,2
32,-0.535266,-0.314689,42.657026,-6.489524,-3.254318,42.697387,40.350558,38.003729,40.350558,40.968521,40.427890,-28.595072,-31.534791,2.584654,-1.007261e+09,39.227329,2
33,-0.458573,-0.343466,49.472291,-2.193910,-2.205151,42.701498,40.358984,38.016471,40.358984,40.952712,40.415043,-18.764757,-26.721951,2.619512,-7.929836e+08,40.138828,2
34,-0.251813,-0.325135,59.544981,5.401848,-0.367908,42.852525,40.417851,37.983178,40.417851,40.975120,40.481573,5.866509,-13.831107,2.739452,-5.268260e+08,41.911964,0
35,-0.080893,-0.276287,59.913626,5.709041,0.448620,42.984213,40.466393,37.948573,40.466393,41.002749,40.548521,25.969112,4.356955,2.719708,-3.905532e+08,41.987919,0
36,0.185351,-0.183959,66.948264,12.047558,1.808735,43.506953,40.649759,37.792565,40.649759,41.056537,40.685709,45.736733,25.857452,2.816485,-1.657480e+08,43.635246,2
37,0.417020,-0.063763,68.103507,13.191918,1.979649,44.022552,40.829090,37.635628,40.829090,41.102396,40.830831,51.666115,41.123987,2.849754,4.057600e+06,43.950951,0
38,0.610626,0.071115,68.887195,13.958480,2.226513,44.489630,40.981005,37.472381,40.981005,41.136008,40.978892,58.084122,51.828990,2.832204,1.176688e+08,44.162212,0
39,0.780158,0.212923,70.053447,15.087762,2.926739,44.982157,41.158082,37.334006,41.158082,41.178591,41.134193,59.732832,56.494356,2.821888,2.105136e+08,44.473156,2
40,0.954839,0.361307,72.337992,17.358438,3.109512,45.541700,41.346789,37.151878,41.346789,41.235180,41.310865,63.227889,60.348281,2.843135,3.224708e+08,45.109306,3
41,1.067128,0.502471,70.769813,16.498633,2.216347,45.997979,41.519915,37.041852,41.519915,41.303148,41.472059,64.911971,62.624231,2.811889,2.176220e+08,44.937725,3
42,1.134581,0.628893,69.774559,15.967469,1.698486,46.380500,41.674863,36.969226,41.674863,41.363276,41.621429,64.592808,64.244223,2.785667,1.345068e+08,44.832893,3
43,1.141994,0.731513,65.895503,13.901978,1.706421,46.631599,41.780717,36.929834,41.780717,41.412358,41.746051,61.526769,63.677183,2.724877,3.972600e+07,44.425426,3
44,1.167862,0.818783,67.853843,15.469558,2.484196,46.941610,41.912047,36.882484,41.912047,41.470445,41.883561,61.088792,62.402790,2.722355,1.164584e+08,44.840034,3
45,1.152200,0.885466,65.100637,14.016837,2.150814,47.228049,42.089017,36.949986,42.089017,41.530646,42.002358,59.272293,60.629285,2.698435,4.728240e+07,44.556484,3
46,1.113873,0.931148,63.514589,13.184156,2.138298,47.411586,42.341913,37.272241,42.341913,41.578539,42.108673,56.482884,58.947990,2.676833,-2.590840e+07,44.394444,3
47,1.096243,0.964167,65.282781,14.425542,3.098488,47.573567,42.616234,37.658901,42.616234,41.618292,42.224243,45.620400,53.791859,2.694421,4.769480e+07,44.708996,3
48,1.061004,0.983534,64.091718,13.832485,3.000725,47.592555,42.912251,38.231948,42.912251,41.647543,42.329698,34.736788,45.613357,2.681320,-1.326800e+07,44.596992,3
49,1.044113,0.995650,65.806886,14.983571,4.229023,47.574091,43.214140,38.854189,43.214140,41.690822,42.443176,22.112404,34.156531,2.670369,6.696560e+07,44.882935,3

In [18]:
# y = indicators_with_price["Adj Close"]
# y_2 = indicators_with_price["SMA"]
# y_3 = indicators_with_price["EMA"]
# y_4 = indicators_with_price["Upper_BB"]
# y_5 = indicators_with_price["Middle_BB"]
# y_6 = indicators_with_price["Lower_BB"]
# X = np.array(date)

# trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
# trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
# trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
# trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
# trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
# trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



# layout = go.Layout(
#     title='Stock Price and Volume',
#     xaxis=dict(title='Date'),
#     yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
#     yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
#     yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
#     yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
#     yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
#     yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
#     height=600,
# )

# fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# # Show plot
# pyo.iplot(fig)

In [19]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        # Extract a window of data from X
        X_window = self.X[idx : idx + self.window_size]
        
        # Assuming you're predicting the value right after the window
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [20]:
X = indicators_with_price.iloc[:, :-1]
y = indicators_with_price.iloc[:,-1]

signal_true = indicators_with_price.iloc[:,-1]
y

0       3
1       3
2       3
3       0
4       0
       ..
1470    2
1471    2
1472    0
1473    0
1474    0
Name: Signal, Length: 1475, dtype: int64

In [21]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1180    0
1181    0
1182    3
1183    3
1184    3
       ..
1470    2
1471    2
1472    0
1473    0
1474    0
Name: Signal, Length: 295, dtype: int64

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
# X_train = X_train.to_numpy()
# y_train = y_train.to_numpy()
y_test.head(44)

1180    0
1181    0
1182    3
1183    3
1184    3
1185    3
1186    3
1187    2
1188    2
1189    0
1190    0
1191    0
1192    0
1193    0
1194    0
1195    0
1196    0
1197    0
1198    0
1199    3
1200    3
1201    2
1202    2
1203    2
1204    2
1205    2
1206    2
1207    2
1208    2
1209    2
1210    2
1211    2
1212    2
1213    2
1214    0
1215    0
1216    0
1217    0
1218    0
1219    0
1220    0
1221    0
1222    0
1223    2
Name: Signal, dtype: int64

In [23]:
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train), y=y_train)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)
class_weights

array([ 0.42369838, 59.        ,  1.15686275,  0.57420925, 59.        ])

In [24]:
# # Get the count of each unique value in the series
# category_counts = y_train.value_counts()
# print(category_counts.index)
# print(category_counts.values)

# # Create bar plot
# plt.bar(["1","0"], category_counts.values)

# # Adding labels and title
# plt.xlabel('Category')
# plt.ylabel('Frequency')
# plt.title('Distribution of Categories')

# # Show plot
# plt.show()

In [25]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

for column in X_train.columns:
    # Initialize a scaler
    scaler = MinMaxScaler()
    
    # Fit on the training data and transform it
    X_train_scaled = scaler.fit_transform(X_train[column].to_numpy().reshape(-1, 1))
    X_train_df[column] = X_train_scaled.flatten()
    
    # Transform the test data using the same scaler
    X_test_scaled = scaler.transform(X_test[column].to_numpy().reshape(-1, 1))
    X_test_df[column] = X_test_scaled.flatten()

    scaler_dict[column] = scaler

    

X_train_df.head(24)

features = X_train_df.columns
X_test_df

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.499847,0.411144,0.517394,0.387563,0.487569,0.813419,0.791684,0.751875,0.791684,0.814103,0.833706,0.876576,0.853920,0.764804,0.775662,0.793797
1,0.523637,0.432238,0.527281,0.393263,0.448749,0.816205,0.793223,0.752021,0.793223,0.813227,0.835055,0.895160,0.867699,0.724522,0.788577,0.797684
2,0.523008,0.448973,0.456307,0.359879,0.379729,0.815520,0.792793,0.751879,0.792793,0.810946,0.835217,0.907286,0.887937,0.685712,0.778442,0.775317
3,0.534244,0.464868,0.497611,0.382097,0.444493,0.813808,0.792104,0.752318,0.792104,0.810434,0.836117,0.913913,0.901248,0.661728,0.787383,0.790115
4,0.547370,0.480511,0.514479,0.391191,0.467133,0.815320,0.792814,0.752139,0.792814,0.809834,0.837282,0.923475,0.911343,0.623616,0.797445,0.796184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,0.331987,0.360467,0.219194,0.330142,0.438975,1.105702,1.104494,1.078159,1.104494,1.140327,1.152418,0.696649,0.699736,0.263755,0.912203,1.018693
291,0.358007,0.354748,0.456177,0.434229,0.530971,1.099583,1.101858,1.079371,1.101858,1.142176,1.152792,0.728273,0.697238,0.316961,0.925666,1.059493
292,0.396416,0.358741,0.541662,0.480564,0.534505,1.093074,1.099905,1.082407,1.099905,1.144078,1.154161,0.814261,0.731129,0.316623,0.937531,1.079584
293,0.440664,0.371807,0.601114,0.515679,0.555951,1.091863,1.099564,1.083019,1.099564,1.145941,1.156274,0.926300,0.813002,0.323439,0.947909,1.095561
294,0.483036,0.391711,0.631898,0.534629,0.550955,1.092553,1.099746,1.082644,1.099746,1.147838,1.158738,0.984412,0.904319,0.300461,0.955220,1.104406

In [26]:
scaler_dict

{'MACD': MinMaxScaler(),
 'MACD_signal': MinMaxScaler(),
 'RSI': MinMaxScaler(),
 'CMO': MinMaxScaler(),
 'MOM': MinMaxScaler(),
 'Upper_BB': MinMaxScaler(),
 'Middle_BB': MinMaxScaler(),
 'Lower_BB': MinMaxScaler(),
 'SMA_SHORT': MinMaxScaler(),
 'SMA_LONG': MinMaxScaler(),
 'EMA': MinMaxScaler(),
 'SLOWK': MinMaxScaler(),
 'SLOWD': MinMaxScaler(),
 'ATR': MinMaxScaler(),
 'OBV': MinMaxScaler(),
 'Adj Close': MinMaxScaler()}

In [27]:
correlation_matrix = X_train_df.corr()

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values,  # Rounded values for display
                    texttemplate="%{text}",
                    textfont={"size":9}  # Adjust text size if necessary
                    ))

# Update the layout
fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  # or any width you desire
    height=1000,  # or any height you desire
)

# Show the figure
pyo.iplot(fig)

In [28]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train.to_numpy(), dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test.to_numpy(), dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(0)[0])

tensor(2., device='cuda:0')
tensor([[0.4998, 0.4111, 0.5174, 0.3876, 0.4876, 0.8134, 0.7917, 0.7519, 0.7917,
         0.8141, 0.8337, 0.8766, 0.8539, 0.7648, 0.7757, 0.7938],
        [0.5236, 0.4322, 0.5273, 0.3933, 0.4487, 0.8162, 0.7932, 0.7520, 0.7932,
         0.8132, 0.8351, 0.8952, 0.8677, 0.7245, 0.7886, 0.7977],
        [0.5230, 0.4490, 0.4563, 0.3599, 0.3797, 0.8155, 0.7928, 0.7519, 0.7928,
         0.8109, 0.8352, 0.9073, 0.8879, 0.6857, 0.7784, 0.7753],
        [0.5342, 0.4649, 0.4976, 0.3821, 0.4445, 0.8138, 0.7921, 0.7523, 0.7921,
         0.8104, 0.8361, 0.9139, 0.9012, 0.6617, 0.7874, 0.7901],
        [0.5474, 0.4805, 0.5145, 0.3912, 0.4671, 0.8153, 0.7928, 0.7521, 0.7928,
         0.8098, 0.8373, 0.9235, 0.9113, 0.6236, 0.7974, 0.7962],
        [0.5399, 0.4914, 0.4471, 0.3605, 0.4592, 0.8163, 0.7941, 0.7537, 0.7941,
         0.8092, 0.8374, 0.9237, 0.9172, 0.5981, 0.7914, 0.7760],
        [0.5112, 0.4936, 0.3677, 0.3216, 0.4080, 0.8078, 0.7900, 0.7546, 0.7900,
         0.8083, 0.8361, 0.8756, 0.9035, 0.5869, 0.7794, 0.7495],
        [0.4709, 0.4865, 0.3118, 0.2921, 0.3590, 0.8019, 0.7857, 0.7521, 0.7857,
         0.8063, 0.8339, 0.7960, 0.8581, 0.5854, 0.7650, 0.7287],
        [0.4782, 0.4824, 0.4544, 0.3639, 0.4654, 0.8000, 0.7849, 0.7524, 0.7849,
         0.8050, 0.8341, 0.7774, 0.8059, 0.6453, 0.7842, 0.7755],
        [0.4855, 0.4807, 0.4597, 0.3667, 0.5578, 0.8016, 0.7861, 0.7533, 0.7861,
         0.8043, 0.8344, 0.7888, 0.7750, 0.6088, 0.7965, 0.7774],
        [0.4882, 0.4800, 0.4490, 0.3617, 0.6035, 0.8012, 0.7895, 0.7605, 0.7895,
         0.8036, 0.8345, 0.8188, 0.7831, 0.5723, 0.7852, 0.7740],
        [0.4834, 0.4783, 0.4231, 0.3496, 0.5378, 0.7993, 0.7924, 0.7687, 0.7924,
         0.8030, 0.8343, 0.7983, 0.7906, 0.5827, 0.7733, 0.7659],
        [0.4583, 0.4714, 0.3463, 0.3124, 0.4486, 0.7969, 0.7939, 0.7742, 0.7939,
         0.8019, 0.8327, 0.7377, 0.7723, 0.5960, 0.7621, 0.7405],
        [0.4275, 0.4590, 0.3088, 0.2931, 0.4211, 0.7958, 0.7944, 0.7765, 0.7944,
         0.8003, 0.8305, 0.6628, 0.7167, 0.5765, 0.7501, 0.7271],
        [0.4137, 0.4460, 0.3519, 0.3121, 0.4535, 0.7862, 0.7972, 0.7927, 0.7972,
         0.7992, 0.8291, 0.6220, 0.6538, 0.5583, 0.7608, 0.7388],
        [0.4007, 0.4327, 0.3416, 0.3072, 0.5122, 0.7872, 0.7955, 0.7881, 0.7955,
         0.7992, 0.8275, 0.6178, 0.6111, 0.5622, 0.7477, 0.7354],
        [0.4045, 0.4229, 0.4019, 0.3333, 0.5364, 0.7852, 0.7936, 0.7864, 0.7936,
         0.8002, 0.8268, 0.6636, 0.6114, 0.5462, 0.7599, 0.7513],
        [0.4138, 0.4171, 0.4266, 0.3443, 0.5657, 0.7842, 0.7926, 0.7854, 0.7926,
         0.8007, 0.8264, 0.7016, 0.6398, 0.5764, 0.7761, 0.7580],
        [0.4089, 0.4114, 0.3718, 0.3205, 0.5461, 0.7816, 0.7901, 0.7831, 0.7901,
         0.8003, 0.8253, 0.7177, 0.6754, 0.5921, 0.7619, 0.7426],
        [0.3676, 0.3977, 0.2382, 0.2535, 0.4085, 0.7853, 0.7857, 0.7701, 0.7857,
         0.7988, 0.8220, 0.6670, 0.6766, 0.6206, 0.7448, 0.6968],
        [0.3250, 0.3771, 0.2052, 0.2347, 0.4402, 0.7869, 0.7798, 0.7563, 0.7798,
         0.7972, 0.8181, 0.6070, 0.6429, 0.6081, 0.7171, 0.6833],
        [0.2812, 0.3510, 0.1712, 0.2147, 0.3655, 0.7876, 0.7730, 0.7415, 0.7730,
         0.7961, 0.8136, 0.5756, 0.5922, 0.5959, 0.7034, 0.6687],
        [0.2486, 0.3227, 0.1700, 0.2140, 0.3484, 0.7892, 0.7673, 0.7281, 0.7673,
         0.7949, 0.8093, 0.5907, 0.5650, 0.5762, 0.6900, 0.6682],
        [0.2435, 0.2990, 0.2674, 0.2523, 0.3853, 0.7841, 0.7620, 0.7227, 0.7620,
         0.7944, 0.8063, 0.6254, 0.5716, 0.5879, 0.7049, 0.6897],
        [0.2238, 0.2756, 0.2091, 0.2214, 0.3520, 0.7784, 0.7552, 0.7149, 0.7552,
         0.7935, 0.8023, 0.6347, 0.5927, 0.5853, 0.6914, 0.6677],
        [0.2090, 0.2536, 0.2026, 0.2178, 0.3005, 0.7750, 0.7494, 0.7066, 0.7494,
         0.7919, 0.7984, 0.6337, 0.6080, 0.5572, 0.6804, 0.6652],
        [0.1900, 0.2318, 0.1704, 0.2003, 0.2520, 0.7754, 0.7442, 0.6956, 0.7442,
         0.7907, 0.7940, 0.6029, 0.6000, 0.5297, 0.6685, 0.6527],
        [0.1556, 0.2067, 0.1075, 0.1632, 0.1687, 0.7799, 0.7388, 0.6795, 0.7388,
         0.7882, 0.7885, 0.5879, 0.5833, 0.5433, 0.6538, 0.6255],
        [0.1525, 0.1859, 0.2212, 0.2082, 0.2481, 0.7734, 0.7321, 0.6728, 0.7321,
         0.7862, 0.7844, 0.5958, 0.5698, 0.5557, 0.6668, 0.6498],
        [0.1555, 0.1699, 0.2309, 0.2122, 0.3070, 0.7647, 0.7255, 0.6687, 0.7255,
         0.7841, 0.7806, 0.6128, 0.5733, 0.5256, 0.6801, 0.6520],
        [0.1339, 0.1523, 0.1491, 0.1668, 0.1158, 0.7577, 0.7173, 0.6593, 0.7173,
         0.7814, 0.7753, 0.6174, 0.5839, 0.5644, 0.6608, 0.6189],
        [0.1280, 0.1369, 0.1898, 0.1832, 0.1605, 0.7491, 0.7100, 0.6536, 0.7100,
         0.7783, 0.7707, 0.6084, 0.5883, 0.5617, 0.6761, 0.6277],
        [0.1197, 0.1227, 0.1673, 0.1708, 0.1768, 0.7445, 0.7035, 0.6454, 0.7035,
         0.7746, 0.7658, 0.5885, 0.5796, 0.5389, 0.6622, 0.6185],
        [0.1434, 0.1167, 0.3052, 0.2288, 0.3005, 0.7391, 0.6994, 0.6428, 0.6994,
         0.7712, 0.7627, 0.6410, 0.5880, 0.5646, 0.6773, 0.6499],
        [0.1686, 0.1175, 0.3198, 0.2353, 0.3813, 0.7308, 0.6949, 0.6425, 0.6949,
         0.7684, 0.7599, 0.6945, 0.6188, 0.5655, 0.6895, 0.6535],
        [0.1951, 0.1240, 0.3365, 0.2425, 0.3916, 0.7222, 0.6908, 0.6433, 0.6908,
         0.7663, 0.7575, 0.7638, 0.6813, 0.5445, 0.7006, 0.6575],
        [0.2347, 0.1381, 0.4132, 0.2767, 0.4185, 0.7093, 0.6868, 0.6492, 0.6868,
         0.7630, 0.7561, 0.8140, 0.7430, 0.5309, 0.7126, 0.6763],
        [0.2680, 0.1568, 0.4111, 0.2759, 0.4105, 0.6915, 0.6825, 0.6595, 0.6825,
         0.7600, 0.7548, 0.8756, 0.8075, 0.5074, 0.7002, 0.6758],
        [0.3040, 0.1797, 0.4490, 0.2927, 0.4830, 0.6765, 0.6794, 0.6695, 0.6794,
         0.7577, 0.7540, 0.9451, 0.8721, 0.4925, 0.7102, 0.6850],
        [0.3408, 0.2063, 0.4816, 0.3075, 0.3519, 0.6757, 0.6792, 0.6699, 0.6792,
         0.7563, 0.7536, 0.9697, 0.9276, 0.4790, 0.7212, 0.6930],
        [0.3670, 0.2334, 0.4586, 0.2993, 0.3087, 0.6765, 0.6795, 0.6696, 0.6795,
         0.7558, 0.7530, 0.9536, 0.9554, 0.4712, 0.7092, 0.6880],
        [0.3890, 0.2600, 0.4604, 0.3001, 0.3267, 0.6791, 0.6805, 0.6689, 0.6805,
         0.7554, 0.7524, 0.9231, 0.9476, 0.4465, 0.7192, 0.6884],
        [0.4219, 0.2886, 0.5376, 0.3335, 0.3368, 0.6851, 0.6825, 0.6665, 0.6825,
         0.7552, 0.7528, 0.9317, 0.9341, 0.4445, 0.7331, 0.7062],
        [0.4667, 0.3215, 0.6197, 0.3738, 0.3912, 0.6937, 0.6846, 0.6614, 0.6846,
         0.7554, 0.7542, 0.9518, 0.9335, 0.4810, 0.7472, 0.7283]],
       device='cuda:0')

# Vanilla LSTM

In [29]:
class VanillaLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob):
        super(VanillaLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

# Stacked LSTM

In [30]:
class StackedLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, stateful):
        super(StackedLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size
        self.stateful = stateful
        
        self.hn = None
        self.cn = None

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=self.layer_size,
                            dropout=(dropout_prob if self.layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def reset_hidden_state(self, batch_size=None):
        if batch_size is None or not self.stateful:
            # Reset hidden and cell states to None if batch_size is not provided or if the model is not stateful
            self.hn = None
            self.cn = None
        else:
            # Resize hidden and cell states to match current batch size, preserving the state as much as possible
            self.hn = self._resize_state(self.hn, batch_size)
            self.cn = self._resize_state(self.cn, batch_size)


    def _resize_state(self, state, batch_size):
        if state is None:
            # If state is not initialized, initialize with zeros
            return torch.zeros(self.layer_size, batch_size, self.hidden_size).to(device)
        elif batch_size < state.size(1):
            # If batch size is smaller, truncate the state
            return state[:, :batch_size, :].contiguous()
        elif batch_size > state.size(1):
            # If batch size is larger, pad the state with zeros
            padding_size = batch_size - state.size(1)
            padding = torch.zeros(self.layer_size, padding_size, self.hidden_size).to(device)
            return torch.cat([state, padding], dim=1)
        

    def forward(self, x):
        current_batch_size = x.size(0)

        # Check and adjust the hidden and cell states
        if not self.stateful or self.hn is None or self.hn.size(1) != current_batch_size:
            self.reset_hidden_state(current_batch_size)
        else:
            # Detach the hidden states from the graph to avoid backpropagating through the entire sequence history
            self.hn = self.hn.detach()
            self.cn = self.cn.detach()

        # Ensure that hn and cn are not None and have the correct shape
        h0 = self.hn if self.hn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)
        c0 = self.cn if self.cn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0, c0))

        # Update hidden states if stateful
        if self.stateful:
            self.hn, self.cn = hn.detach(), cn.detach()

        # Process the output of the last time step
        out = self.dropout(out[:, -1, :])  # Add dropout
        out = self.fc(out)  # Fully connected layer

        return out

# Bidirectional LSTM

# 1D CNN-LSTM

In [31]:
class OneDimCNNLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, conv_channels, kernel_size, pool_size, stride):
        super(OneDimCNNLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # Convolutional Layer
        self.conv1 = nn.Conv1d(in_channels=input_dim, out_channels=conv_channels, kernel_size=kernel_size)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool1d(kernel_size=pool_size, stride=pool_size)

        # self.conv2 = nn.Conv1d(in_channels=conv_channels, out_channels=conv_channels*2, kernel_size=kernel_size)
        # self.relu2 = nn.ReLU()
        # self.maxpool2 = nn.MaxPool1d(kernel_size=2, stride=2)


        self.lstm = nn.LSTM(input_size = conv_channels, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # CNN in_dim: (batch_size, in_channels, length)
        x = x.transpose(1, 2)

        # Conv layer forward propagate
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.maxpool1(x)

        # x = self.conv2(x)
        # x = self.relu2(x)
        # x = self.maxpool2(x)

        # LSTM in_dim: (batch_size, seq_len, input_size)
        x = x.transpose(1, 2)

        assert x.size(-1) == self.lstm.input_size, f"Mismatch in LSTM input size. Expected: {self.lstm.input_size}, Got: {x.size(-1)}"

        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

In [32]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device, model_type):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model_type = model_type
        self.model = None
        self.optimizer = None
        self.criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)

    
    def train_validate(self, config, trial):

        if self.model_type == "Vanilla LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=5).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=5).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=5, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.long()


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    loss = loss.mean()
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.long()

                        preds = self.model(data)
                        loss = self.criterion(preds, target)
                        loss = loss.mean()

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
        if self.model_type == "Vanilla LSTM":

            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=5).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=5).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=5, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.long()  

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                loss = loss.mean()
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.long()
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                _, predicted_classes = torch.max(preds, 1)
                all_preds.extend(predicted_classes.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [33]:
model_type = "1D CNN-LSTM"

def objective(trial):
    if model_type == "Vanilla LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.15),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 10, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9)
        }

    elif model_type == "Stacked LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "num_layers": trial.suggest_int("num_layers", 1, 5)
        }

    elif model_type == "1D CNN-LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "conv_channels": trial.suggest_int("conv_channels", 16, 128),
            "kernel_size": trial.suggest_int("kernel_size", 2, 6),
            "num_layers": trial.suggest_int("num_layers", 1, 5),
            "pool_size": trial.suggest_int("pool_size", 2, 5),
            "stride": trial.suggest_int("stride", 1, 4)
        }

    trainer = ModelActioner(train_data, test_data, device, model_type)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [34]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=25, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    # Optionally, you can include additional information in the progress bar
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=25, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-27 01:50:51,617] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/25 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.570634452460324, val_loss: 1.5423387509805184
epochs 2/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.2768523849117819, val_loss: 1.3679035946174904
epochs 3/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.2785435184758371, val_loss: 1.474496637071882
epochs 4/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.197447239416432, val_loss: 1.1755895999373582
epochs 5/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.1269651832380845, val_loss: 1.0454602159520305
epochs 6/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0816962831307455, val_loss: 1.1379783632894043
epochs 7/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.1054922223715258, val_loss: 1.1801792067825478
epochs 8/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0778300643591356, val_loss: 1.2143524412124875
epochs 9/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0770809456940096, val_loss: 1.1740930162409626
epochs 10/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0867917007176664, val_loss: 1.1359137202066087
epochs 11/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0706010351630406, val_loss: 1.1237026938685664
epochs 12/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0781324259273668, val_loss: 1.1269566880332098
epochs 13/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0825782078098876, val_loss: 1.1398906657304713
epochs 14/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0669707334478489, val_loss: 1.144506955272937
epochs 15/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.072876193136445, val_loss: 1.1407231086145633
epochs 16/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0666257523741398, val_loss: 1.135333394247388
epochs 17/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0708253321223233, val_loss: 1.132611322655249
epochs 18/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0738249742547878, val_loss: 1.1334249266871699
epochs 19/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0593134308360634, val_loss: 1.1371586341706534
epochs 20/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.08139723820212, val_loss: 1.1364802185189786
epochs 21/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.073118430781739, val_loss: 1.132518797324448
epochs 22/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0718885853652556, val_loss: 1.1314131910838778
epochs 23/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0675753548507292, val_loss: 1.1370941797892253
epochs 24/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0728885796681749, val_loss: 1.1411341081851374
epochs 25/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0638544247412556, val_loss: 1.1445520289991267
epochs 26/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0694960505550444, val_loss: 1.1388586778489371
epochs 27/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.066023070150645, val_loss: 1.1335045092951053
epochs 28/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0762914250658444, val_loss: 1.1247504754041238
epochs 29/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.078816822061988, val_loss: 1.1210423808879952
epochs 30/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.068808528765334, val_loss: 1.1264898146271074
epochs 31/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.072036301278319, val_loss: 1.1355631774064725
epochs 32/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0690062901112423, val_loss: 1.144321391822169
epochs 33/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.069562687923771, val_loss: 1.1462421808293257
epochs 34/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0669935192737279, val_loss: 1.1427537038843467
epochs 35/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0676369941671482, val_loss: 1.1397444186387238
epochs 36/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.072010862265582, val_loss: 1.1308732152615906
epochs 37/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.069004667991119, val_loss: 1.1269162344554113
epochs 38/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.069954928303264, val_loss: 1.1311756000316964
epochs 39/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0664853094760036, val_loss: 1.1399876484795222
epochs 40/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0718429687759639, val_loss: 1.1470231139470661
epochs 41/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0822051376572455, val_loss: 1.1466970046361287
epochs 42/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0766614070113416, val_loss: 1.1425617453913208
epochs 43/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.078457957162907, val_loss: 1.137634583881923
epochs 44/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.071545864899121, val_loss: 1.1346987624647755
epochs 45/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0775946759428654, val_loss: 1.1392075523497567
epochs 46/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0709985338580545, val_loss: 1.1433065322341112
epochs 47/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.074006534995833, val_loss: 1.1444549661464791
epochs 48/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0712897552869707, val_loss: 1.1382274760140314
epochs 49/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0746663677754826, val_loss: 1.1324624882804022
epochs 50/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.078922864030169, val_loss: 1.1307897845273296
epochs 51/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.073686217762413, val_loss: 1.1326988348885187
epochs 52/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0745484548089392, val_loss: 1.1340048988029439
epochs 53/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0720656130326356, val_loss: 1.138546729844714
epochs 54/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0714957907561857, val_loss: 1.1414739814384904
epochs 55/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.071144564613622, val_loss: 1.1383262702396937
epochs 56/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.071422566294046, val_loss: 1.138294916935068
epochs 57/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0653592004825931, val_loss: 1.1424360041895871
epochs 58/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.066328245931895, val_loss: 1.1432536468304024
epochs 59/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0710246625371005, val_loss: 1.1426254826248008
epochs 60/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.06859041570993, val_loss: 1.148609897447011
epochs 61/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0713553796888022, val_loss: 1.1443767358386328
epochs 62/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.075173933468564, val_loss: 1.125132614342624
epochs 63/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.06886787938822, val_loss: 1.1211104247935866
epochs 64/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0719899731780846, val_loss: 1.1253294433866228
epochs 65/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0862861235104306, val_loss: 1.1448526666277932
epochs 66/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0799227921750534, val_loss: 1.1426430713562739
epochs 67/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0687911722672547, val_loss: 1.1383274781010138
epochs 68/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0741335615437693, val_loss: 1.1192850252938649
epochs 69/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0775956002829588, val_loss: 1.1364325026355724
epochs 70/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0722335252462256, val_loss: 1.1510678592813077
epochs 71/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0672225296809412, val_loss: 1.1403728162170088
epochs 72/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0705855585517683, val_loss: 1.133490940250417
epochs 73/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0663221543996122, val_loss: 1.1354006106260592
epochs 74/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.071650332805374, val_loss: 1.1412001198561734
epochs 75/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0725667507860672, val_loss: 1.1325395290183011
epochs 76/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.068449157070739, val_loss: 1.1366940478168468
epochs 77/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.069620930087504, val_loss: 1.1440652375498777
epochs 78/84
Epoch 00078: reducing learning rate of group 0 to 8.5517e-03.
Current Learning Rate: 0.00855171348252926
train_loss: 1.0676169894752703, val_loss: 1.1393231014726024
epochs 79/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.0623243809994602, val_loss: 1.1388638524151353
epochs 80/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.0653788968530624, val_loss: 1.1376592822806546
epochs 81/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.0620967505489969, val_loss: 1.1358962702372717
epochs 82/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.071181710477899, val_loss: 1.1338784953273793
epochs 83/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.065221636707246, val_loss: 1.1319498202157399
epochs 84/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.0656280168063978, val_loss: 1.1319533025146162
Starting fold 2:
epochs 1/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.1435355035882246, val_loss: 1.1138813533480205
epochs 2/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.2601004424848055, val_loss: 1.0720938942419789
epochs 3/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0486063514885149, val_loss: 1.0617480766836298
epochs 4/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0510487449796577, val_loss: 1.0592365252277838
epochs 5/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.060322663344835, val_loss: 1.0590927301260529
epochs 6/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.061681112803911, val_loss: 1.0569014170813182
epochs 7/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.052072317662992, val_loss: 1.0563772254519992
epochs 8/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0502652823925018, val_loss: 1.056589062882479
epochs 9/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0481829138178573, val_loss: 1.0578072824806133
epochs 10/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0466374814510346, val_loss: 1.0584083653631664
epochs 11/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0464183151721955, val_loss: 1.0582588671376465
epochs 12/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.048682263964101, val_loss: 1.0582927301447227
epochs 13/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.047346886208183, val_loss: 1.058404798860903
epochs 14/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0515409777038975, val_loss: 1.058125701215532
epochs 15/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0471103953687768, val_loss: 1.0581956499468081
epochs 16/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.050788779007761, val_loss: 1.0581940806731975
epochs 17/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0479710202468069, val_loss: 1.0577176796696173
epochs 18/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0425024879606146, val_loss: 1.0579053974025463
epochs 19/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0461813173796002, val_loss: 1.058310549725931
epochs 20/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0550226694659184, val_loss: 1.056967228808731
epochs 21/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.044182422914003, val_loss: 1.0573676061377955
epochs 22/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.051081593413102, val_loss: 1.0579253523438066
epochs 23/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0496863242826964, val_loss: 1.0582451697379824
epochs 24/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.051760343815151, val_loss: 1.0584256049817202
epochs 25/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0445618513383363, val_loss: 1.058555132812924
epochs 26/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0525205703158127, val_loss: 1.05841313341938
epochs 27/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0503553418736709, val_loss: 1.057870811570889
epochs 28/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0464270513308676, val_loss: 1.0578155492348646
epochs 29/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0495761300388136, val_loss: 1.05766369268377
epochs 30/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0504364951660758, val_loss: 1.0572201855598935
epochs 31/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.047581453386106, val_loss: 1.0572918237201752
epochs 32/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0478934604870647, val_loss: 1.0578544180859963
epochs 33/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0448925815130534, val_loss: 1.058540131995287
epochs 34/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.048424687197334, val_loss: 1.05866290589489
epochs 35/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0502805502791153, val_loss: 1.058187001596683
epochs 36/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0476319457355299, val_loss: 1.05758212577729
epochs 37/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0456837650976682, val_loss: 1.0575412193303386
epochs 38/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.045956068603616, val_loss: 1.057935667416406
epochs 39/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0488589638157895, val_loss: 1.0578271579490137
epochs 40/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0464269528263495, val_loss: 1.057600925523768
epochs 41/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0487376696185062, val_loss: 1.0573318745724107
epochs 42/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0473117075468366, val_loss: 1.057424581240094
epochs 43/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0477330527807538, val_loss: 1.0576909812039168
epochs 44/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0459859374322389, val_loss: 1.0580512874971622
epochs 45/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0475505991985923, val_loss: 1.0581442511901653
epochs 46/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.046173743511501, val_loss: 1.0582873881178558
epochs 47/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0479685689273635, val_loss: 1.0582717836849274
epochs 48/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0412809240190606, val_loss: 1.0589600826697374
epochs 49/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0433281923595228, val_loss: 1.0594945852718656
epochs 50/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0475335867781388, val_loss: 1.0591155656431086
epochs 51/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0489707918543565, val_loss: 1.0583448816859533
epochs 52/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0491273161612058, val_loss: 1.0578824218618808
epochs 53/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.048230191594676, val_loss: 1.0575946960499678
epochs 54/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0453353684199485, val_loss: 1.0578578076665364
epochs 55/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0459679951793268, val_loss: 1.057910460959036
epochs 56/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.048183957840267, val_loss: 1.0579617193767004
epochs 57/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0494336234895807, val_loss: 1.0578491019193457
epochs 58/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0429142961376592, val_loss: 1.0584197485888447
epochs 59/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0488789916038512, val_loss: 1.0584403251214003
epochs 60/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0492133755432933, val_loss: 1.0578430383293718
epochs 61/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0465870054144608, val_loss: 1.0574270177770544
epochs 62/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0445973763340397, val_loss: 1.0575782637747506
epochs 63/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.044844274771841, val_loss: 1.0581263720043121
epochs 64/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.045454309174889, val_loss: 1.058326416545444
epochs 65/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0491893991043693, val_loss: 1.057951119210985
epochs 66/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0496388485557155, val_loss: 1.0575502637832883
epochs 67/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0460346717583506, val_loss: 1.0574954861686343
epochs 68/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0443725162430813, val_loss: 1.0577888277472642
epochs 69/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0464773981194748, val_loss: 1.0578383721371807
epochs 70/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0470508064094344, val_loss: 1.0577100184228685
epochs 71/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0478612661361695, val_loss: 1.0576395389264224
epochs 72/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0438811841763949, val_loss: 1.0576704936052757
epochs 73/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0462480717583706, val_loss: 1.057624742782936
epochs 74/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0432087377498025, val_loss: 1.057822759189303
epochs 75/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.047616758472041, val_loss: 1.0576694005380862
epochs 76/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0452331844129061, val_loss: 1.0577190010635942
epochs 77/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0446040674259789, val_loss: 1.0577354579375535
epochs 78/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0480384776466771, val_loss: 1.0572819845386283
epochs 79/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0438250601291656, val_loss: 1.057407870179131
epochs 80/84
Epoch 00080: reducing learning rate of group 0 to 8.5517e-03.
Current Learning Rate: 0.00855171348252926
train_loss: 1.0459068354807401, val_loss: 1.057825240508589
epochs 81/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.0425632771692779, val_loss: 1.0579816588649043
epochs 82/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.041182103282527, val_loss: 1.0582212099322565
epochs 83/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.0446376154297277, val_loss: 1.058305301363506
epochs 84/84
Current Learning Rate: 0.00855171348252926
train_loss: 1.0447256025515104, val_loss: 1.0583474118873555
Starting fold 3:
epochs 1/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.1241586878764818, val_loss: 1.0773605319557997
epochs 2/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.105088392020529, val_loss: 1.0807336912584053
epochs 3/84

[I 2024-01-27 01:51:26,578] Trial 0 finished with value: 1.1064366340404437 and parameters: {'batch_size': 86, 'epochs': 84, 'hidden_size': 51, 'learning_rate': 0.04471910604647985, 'dropout_prob': 0.11405534453545046, 'weight_decay': 8.740781938907536e-05, 'lr_step_size': 72, 'gamma': 0.19123176285413301, 'conv_channels': 84, 'kernel_size': 5, 'num_layers': 5, 'pool_size': 4, 'stride': 1}. Best is trial 0 with value: 1.1064366340404437.

Current Learning Rate: 0.04471910604647985
train_loss: 1.0364899819101174, val_loss: 1.2841643681601873
epochs 84/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.035973895628324, val_loss: 1.2831430182885872
Mean validation loss: 1.1064366340404437
Starting fold 1:
epochs 1/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.6194562924469953, val_loss: 1.6391602111241175
epochs 2/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.6162133191892614, val_loss: 1.6370395718428192
epochs 3/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.6136898526346497, val_loss: 1.6349482826454929
epochs 4/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.6113840528807715, val_loss: 1.6328630781678295
epochs 5/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.6093816994372463, val_loss: 1.6307771445582153
epochs 6/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.6077674096791532, val_loss: 1.6286813910045321
epochs 7/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.6061145497866327, val_loss: 1.6265774618380915
epochs 8/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.6026776180217404, val_loss: 1.6244570325922083
epochs 9/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.6003640134921249, val_loss: 1.6223194435159995
epochs 10/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5981996178002882, val_loss: 1.6201554694503704
epochs 11/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5956706894629913, val_loss: 1.6179614760888317
epochs 12/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5937358384357072, val_loss: 1.6157385098240362
epochs 13/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5909902419095263, val_loss: 1.6134795757828566
epochs 14/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5888688314647574, val_loss: 1.611181927736474
epochs 15/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5868268374997283, val_loss: 1.6088341998044775
epochs 16/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5830511553749365, val_loss: 1.6064318828481845
epochs 17/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5816898807805246, val_loss: 1.6039739247983096
epochs 18/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5764128887216458, val_loss: 1.6014424007405679
epochs 19/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.574624228227825, val_loss: 1.5988336751069971
epochs 20/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5730202996918043, val_loss: 1.5961435900794134
epochs 21/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5698559309175502, val_loss: 1.593366675275974
epochs 22/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5660742839593538, val_loss: 1.5904906880918634
epochs 23/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5615689604694307, val_loss: 1.587501741590954
epochs 24/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5587220304299398, val_loss: 1.584394756448332
epochs 25/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5546731118756438, val_loss: 1.5811671920554349
epochs 26/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5523747149562337, val_loss: 1.5778036086016862
epochs 27/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5487434870285512, val_loss: 1.5742942138954445
epochs 28/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5443110241315752, val_loss: 1.5706308190784757
epochs 29/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.538622356834212, val_loss: 1.5667935571973286
epochs 30/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5350532737701976, val_loss: 1.5627785832793624
epochs 31/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5296506401131915, val_loss: 1.5585656430986192
epochs 32/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5245909391273378, val_loss: 1.5541293621063232
epochs 33/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5204666235059967, val_loss: 1.549474250702631
epochs 34/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5157029522651153, val_loss: 1.5445702429170962
epochs 35/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5091415462693618, val_loss: 1.539416376245085
epochs 36/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.5021837350585698, val_loss: 1.5339774133036377
epochs 37/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4974407481897565, val_loss: 1.528245661624525
epochs 38/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4887881622264523, val_loss: 1.5222071409225464
epochs 39/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4849170733496782, val_loss: 1.5158322563877813
epochs 40/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4777644229809026, val_loss: 1.509128795729743
epochs 41/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4672093478796995, val_loss: 1.502066940226883
epochs 42/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4597041045183912, val_loss: 1.4946205212325645
epochs 43/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.450215471352582, val_loss: 1.4867812622161138
epochs 44/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4423881219943782, val_loss: 1.4785353103012004
epochs 45/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4323096381432099, val_loss: 1.4698798013111902
epochs 46/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4193664183791395, val_loss: 1.4607981399253562
epochs 47/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.4068257053485091, val_loss: 1.4512888590494792
epochs 48/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.39713563719345, val_loss: 1.4413836248337277
epochs 49/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.3838669117832683, val_loss: 1.4311052283282002
epochs 50/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.3697899386520784, val_loss: 1.4204852032282995
epochs 51/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.3599963181930064, val_loss: 1.4095636076397366
epochs 52/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.3444374175595988, val_loss: 1.3984425881552318
epochs 53/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.3325126851416382, val_loss: 1.3871971677850794
epochs 54/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.3175203531824482, val_loss: 1.3759316824100636
epochs 55/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.3018609010736355, val_loss: 1.36470900704621
epochs 56/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.2878522354894908, val_loss: 1.3536926747629883
epochs 57/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.2679763589229884, val_loss: 1.3430292732501157
epochs 58/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.2609159415929105, val_loss: 1.3328643923714047
epochs 59/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.2459049705435468, val_loss: 1.3233362133540805
epochs 60/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.2279109830007504, val_loss: 1.3144985670765872
epochs 61/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.217998188203542, val_loss: 1.306398734844551
epochs 62/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.206970340918496, val_loss: 1.2990705203757715
epochs 63/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1922947723828061, val_loss: 1.2925569746229384
epochs 64/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1825093143273397, val_loss: 1.2866610408460022
epochs 65/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1795823112208181, val_loss: 1.2812773954300654
epochs 66/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.165298991178343, val_loss: 1.2762129981681782
epochs 67/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1626492601414626, val_loss: 1.2714731283288785
epochs 68/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1438272130426936, val_loss: 1.2669071665516607
epochs 69/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.146529191451547, val_loss: 1.2622542734499331
epochs 70/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1429048664282755, val_loss: 1.2576718752977079
epochs 71/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1363187235687415, val_loss: 1.253128936051061
epochs 72/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1326422972204797, val_loss: 1.2485248619917209
epochs 73/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.133695757201829, val_loss: 1.243592797133027
epochs 74/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1237276636493143, val_loss: 1.2385071219590607
epochs 75/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.119204287129547, val_loss: 1.2333456164314633
epochs 76/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1201044033959273, val_loss: 1.2281258490981248
epochs 77/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1144484025645631, val_loss: 1.2229115048413555
epochs 78/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1174183696976507, val_loss: 1.2177365860611042
epochs 79/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1122788602769063, val_loss: 1.2126095843693567
epochs 80/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1143637914308078, val_loss: 1.2077367993258925
epochs 81/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1078315761076842, val_loss: 1.2030548696164731
epochs 82/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.104173672136836, val_loss: 1.1985876156539512
epochs 83/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.0996458486736758, val_loss: 1.194346863125998
epochs 84/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.100594084300296, val_loss: 1.1903270861459156
epochs 85/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1003949885593034, val_loss: 1.1864431743268613
epochs 86/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.1005083590901958, val_loss: 1.1826784446756675
epochs 87/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.0852642209117949, val_loss: 1.1790811712779696
epochs 88/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.0889844813271967, val_loss: 1.1756346616795454
epochs 89/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.0942515371981716, val_loss: 1.1725002413704282
epochs 90/129

[I 2024-01-27 01:51:30,540] Trial 1 pruned.

Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.098478309147021, val_loss: 1.169537380258873
epochs 91/129
Current Learning Rate: 4.1591821424223354e-05
train_loss: 1.0889153505495082, val_loss: 1.1667650767735072
epochs 92/129
Starting fold 1:
epochs 1/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6263663063498692, val_loss: 1.6835835736895364
epochs 2/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6254553645069063, val_loss: 1.6822803379997375
epochs 3/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6243225036491273, val_loss: 1.681018664723351
epochs 4/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6228914884996664, val_loss: 1.6797766420576308
epochs 5/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6221584000512568, val_loss: 1.6785493389008537
epochs 6/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6212033988293553, val_loss: 1.677332495886182
epochs 7/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6201128198214227, val_loss: 1.676123991845146
epochs 8/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6188778739949172, val_loss: 1.6749227538941398
epochs 9/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6183681338245333, val_loss: 1.6737274726231892
epochs 10/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6176106467921072, val_loss: 1.6725401821590604
epochs 11/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6164005720178494, val_loss: 1.6713561879263983
epochs 12/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6155615083834263, val_loss: 1.6701765192879572
epochs 13/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6142915175223225, val_loss: 1.6689995981398082
epochs 14/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.613523673636751, val_loss: 1.6678237441986326
epochs 15/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6122089730507416, val_loss: 1.666650270658826
epochs 16/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6111281829354651, val_loss: 1.6654772493574355
epochs 17/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6100934325712513, val_loss: 1.6643022355579196
epochs 18/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.609362942386048, val_loss: 1.6631219595197648
epochs 19/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6084655042718219, val_loss: 1.6619388111053952
epochs 20/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6075208386825641, val_loss: 1.6607540732338315
epochs 21/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6064850865858387, val_loss: 1.6595681754369584
epochs 22/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6053397898898698, val_loss: 1.6583799521128337
epochs 23/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6041619721507527, val_loss: 1.6571857948151847
epochs 24/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6033000103466173, val_loss: 1.6559852172457983
epochs 25/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6024067851261319, val_loss: 1.6547767075281294
epochs 26/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6016623930157168, val_loss: 1.653559440658206
epochs 27/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.6001084618543455, val_loss: 1.652334975817847
epochs 28/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5991638168614573, val_loss: 1.6511006128220331
epochs 29/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.598125935849095, val_loss: 1.649857619452098
epochs 30/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5972505757945994, val_loss: 1.6486051347520616
epochs 31/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5957790881551372, val_loss: 1.6473421066526384
epochs 32/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5941148359738095, val_loss: 1.646065630610027
epochs 33/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5934064107415564, val_loss: 1.6447767605857244
epochs 34/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5923069128815417, val_loss: 1.64347243309021
epochs 35/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.590847969679308, val_loss: 1.6421561203305683
epochs 36/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5898341065301944, val_loss: 1.6408231807133509
epochs 37/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.588126567645847, val_loss: 1.6394743786917791
epochs 38/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5871772466529726, val_loss: 1.6381041587345184
epochs 39/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5860270473969544, val_loss: 1.6367113249642509
epochs 40/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.585143684716749, val_loss: 1.635301705390688
epochs 41/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5833989974715947, val_loss: 1.6338716802142916
epochs 42/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5818225313855716, val_loss: 1.6324220138882835
epochs 43/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5804090524843226, val_loss: 1.630949270157587
epochs 44/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5795351547720544, val_loss: 1.6294537063628909
epochs 45/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5782707492718522, val_loss: 1.6279356063358368
epochs 46/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5764315109602445, val_loss: 1.6263950457648626
epochs 47/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5748948227048545, val_loss: 1.624831994374593
epochs 48/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5738268410348144, val_loss: 1.623244599690513
epochs 49/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5721783843964183, val_loss: 1.621634604438903
epochs 50/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5707275112261947, val_loss: 1.619998782400101
epochs 51/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5690565390112512, val_loss: 1.6183384259541829
epochs 52/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5676768550073914, val_loss: 1.6166526836062234
epochs 53/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.566309337216522, val_loss: 1.6149411788062444
epochs 54/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5641762080616977, val_loss: 1.6132006683046856
epochs 55/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5626854490859345, val_loss: 1.6114302438402932
epochs 56/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5615335234796814, val_loss: 1.6096312829426356
epochs 57/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.55966656432726, val_loss: 1.6078010892111159
epochs 58/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5582653383934062, val_loss: 1.60594137698885
epochs 59/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.556022273932452, val_loss: 1.6040472511261228
epochs 60/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5547153656395318, val_loss: 1.6021205376064966
epochs 61/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.552191846657798, val_loss: 1.600157716917613
epochs 62/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.551090832780169, val_loss: 1.5981632527850924
epochs 63/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5487443676793762, val_loss: 1.5961317978208027
epochs 64/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5474581930649842, val_loss: 1.594068139318436
epochs 65/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.544962135284983, val_loss: 1.5919675486428397
epochs 66/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.542632461842442, val_loss: 1.589831032450237
epochs 67/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5404144868800778, val_loss: 1.587660585130964
epochs 68/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5385470633731462, val_loss: 1.5854532907879542
epochs 69/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5375006517190584, val_loss: 1.583211073799739
epochs 70/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5353528429700443, val_loss: 1.5809337146698483
epochs 71/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.532629181577273, val_loss: 1.5786215161520338
epochs 72/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5305522386940362, val_loss: 1.5762747261259291
epochs 73/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5287993734419658, val_loss: 1.5738938025065832
Starting fold 2:
epochs 1/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5484920683660006, val_loss: 1.5382886860105727
epochs 2/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5447594002673501, val_loss: 1.533631404240926
epochs 3/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.540604012890866, val_loss: 1.5289532646300301
epochs 4/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5358798503875732, val_loss: 1.5242641237046983
epochs 5/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5328086438931916, val_loss: 1.5195654933414762
epochs 6/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5285922746909293, val_loss: 1.514852415947687
epochs 7/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5246603557938023, val_loss: 1.5101269559254722
epochs 8/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5197373107859964, val_loss: 1.5053845114178128
epochs 9/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5155997985287717, val_loss: 1.5006251940651545
epochs 10/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5116581439971923, val_loss: 1.4958499310508606
epochs 11/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5070144766255429, val_loss: 1.4910566012064617
epochs 12/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.5026157002700002, val_loss: 1.4862485291465881
epochs 13/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.49817329143223, val_loss: 1.4814256997335524
epochs 14/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4938220657800374, val_loss: 1.4765942872516693
epochs 15/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.489343984503495, val_loss: 1.4717548158433702
epochs 16/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4845568004407381, val_loss: 1.4669065115943787
epochs 17/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4800345025564494, val_loss: 1.462052761562287
epochs 18/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4764956223337273, val_loss: 1.4571986501179044
epochs 19/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4714675413934808, val_loss: 1.4523433371195718
epochs 20/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.467583335700788, val_loss: 1.4474871120755635
epochs 21/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4621676501474883, val_loss: 1.442632932511587
epochs 22/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.456769970216249, val_loss: 1.4377757197334653
epochs 23/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.451641897778762, val_loss: 1.4329136591109017
epochs 24/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4470653094743426, val_loss: 1.4280503496291146
epochs 25/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.443841162480806, val_loss: 1.4231946298054285
epochs 26/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4382832985175282, val_loss: 1.4183461666107178
epochs 27/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4333705136650488, val_loss: 1.41350623728737
epochs 28/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4288013621380455, val_loss: 1.4086727963553534
epochs 29/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4247688556972302, val_loss: 1.4038511684962682
epochs 30/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4194118512304206, val_loss: 1.3990400972820463
epochs 31/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4142196429403204, val_loss: 1.3942371758203658
epochs 32/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.4096520298405697, val_loss: 1.389442935822502
epochs 33/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.405372807226683, val_loss: 1.3846633358607217
epochs 34/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3996167559372752, val_loss: 1.379895876324366
epochs 35/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.395221095336111, val_loss: 1.3751401749868242
epochs 36/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.390352565991251, val_loss: 1.370400319023738
epochs 37/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3873212902169478, val_loss: 1.3656796330497378
epochs 38/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3813992337176675, val_loss: 1.3609771747437736
epochs 39/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.376943542455372, val_loss: 1.3562975232563321
epochs 40/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3714416478809557, val_loss: 1.3516379405581762
epochs 41/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3672561645507812, val_loss: 1.3469989034864638
epochs 42/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.363448863280447, val_loss: 1.3423792237327212
epochs 43/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.358423964600814, val_loss: 1.3377847349832928
epochs 44/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3538597408093904, val_loss: 1.3332142678518144
epochs 45/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.348466179872814, val_loss: 1.3286705452298362
epochs 46/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3450805689159193, val_loss: 1.3241598303355868
epochs 47/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.339814814140922, val_loss: 1.3196801155332536
epochs 48/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.335144073084781, val_loss: 1.3152322958386133
epochs 49/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3315655915360702, val_loss: 1.3108192663344125
epochs 50/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3274635766681873, val_loss: 1.3064474132325914
epochs 51/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3230089557798286, val_loss: 1.3021210734806363
epochs 52/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3178332498199061, val_loss: 1.2978346518107824
epochs 53/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3144833376533107, val_loss: 1.2935950112721277
epochs 54/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3091598159388491, val_loss: 1.2894043335838923
epochs 55/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3067581935932762, val_loss: 1.285268297271123
epochs 56/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.3007200573620044, val_loss: 1.2811880263071211
epochs 57/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.296941864490509, val_loss: 1.277165106364659
epochs 58/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2926276715178238, val_loss: 1.2732026652684287
epochs 59/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2897642229732713, val_loss: 1.269304455272735
epochs 60/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.286204859457518, val_loss: 1.265476872050573
epochs 61/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.282038404439625, val_loss: 1.2617181804445055
epochs 62/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.277950432426051, val_loss: 1.2580339132793366
epochs 63/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2736963102692052, val_loss: 1.2544233155628992
epochs 64/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2706828537740205, val_loss: 1.2508841715161763
epochs 65/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2670558797685723, val_loss: 1.2474193913596017
epochs 66/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.263422373721474, val_loss: 1.2440296600735377
epochs 67/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2606113345999466, val_loss: 1.2407179616746449
epochs 68/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.257655266084169, val_loss: 1.2374851703643799
epochs 69/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2533150120785361, val_loss: 1.2343293579797896
epochs 70/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2497328137096606, val_loss: 1.2312461459447468
epochs 71/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2463903050673635, val_loss: 1.2282319958247836
epochs 72/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2431854185305145, val_loss: 1.2252803624622406
epochs 73/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2400046963440745, val_loss: 1.2223925193150837
Starting fold 3:
epochs 1/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2323187015597137, val_loss: 1.2253618808019728
epochs 2/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2270530252758354, val_loss: 1.2228390754215301
epochs 3/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2245172096681511, val_loss: 1.2204228582836332
epochs 4/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2212925619316437, val_loss: 1.2181027124798487
epochs 5/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2168196923703427, val_loss: 1.2158719263379536
epochs 6/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2142539998558997, val_loss: 1.2137240133588276
epochs 7/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2100602463804355, val_loss: 1.211652610037062
epochs 8/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2067615522860642, val_loss: 1.2096566510578943
epochs 9/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2041723667423, val_loss: 1.2077291711928353
epochs 10/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.2002461626994798, val_loss: 1.2058659053984142
epochs 11/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.1985654818362217, val_loss: 1.204062090979682
epochs 12/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.1952976103616724, val_loss: 1.2023145868664695
epochs 13/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.1917565711143776, val_loss: 1.2006228443176028
epochs 14/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.1901980831250156, val_loss: 1.1989724844221086
epochs 15/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.1875959706013148, val_loss: 1.1973655318456984
epochs 16/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.1849254795034239, val_loss: 1.1957963686140756
epochs 17/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.1833179390912316, val_loss: 1.1942661376226515
epochs 18/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.180251439552106, val_loss: 1.1927634761447
epochs 19/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.1789332014395608, val_loss: 1.1912984734489804
epochs 20/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 1.175475220060097, val_loss: 1.1898693319350955
epochs 21/73
Current Learning Rate: 3.456698721144436e-05

[I 2024-01-27 01:51:54,922] Trial 2 finished with value: 1.2966244378201883 and parameters: {'batch_size': 102, 'epochs': 73, 'hidden_size': 31, 'learning_rate': 3.456698721144436e-05, 'dropout_prob': 0.005976321377478566, 'weight_decay': 0.00022898650753771027, 'lr_step_size': 22, 'gamma': 0.27624126770258145, 'conv_channels': 118, 'kernel_size': 6, 'num_layers': 2, 'pool_size': 3, 'stride': 3}. Best is trial 0 with value: 1.1064366340404437.

Current Learning Rate: 3.456698721144436e-05
train_loss: 0.9729157467830017, val_loss: 1.2128204428960407
epochs 73/73
Current Learning Rate: 3.456698721144436e-05
train_loss: 0.9708517854669404, val_loss: 1.2117718874462067
Mean validation loss: 1.2966244378201883
Starting fold 1:
epochs 1/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.5628479519439618, val_loss: 1.4510772430076802
epochs 2/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.4746315373176055, val_loss: 1.34626090905023
epochs 3/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.3401547526813926, val_loss: 1.2064460761963376
epochs 4/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.1790566924978925, val_loss: 1.1544148020012668
epochs 5/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.1250142077500906, val_loss: 1.1548964251916876
epochs 6/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.086362120368718, val_loss: 1.1179503240282573
epochs 7/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0633376237609624, val_loss: 1.0900396474454768
epochs 8/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0565162628733051, val_loss: 1.0949574595405942
epochs 9/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0658047199249268, val_loss: 1.1161838839293787
epochs 10/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.071719814969607, val_loss: 1.1338765608570562
epochs 11/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0583101404899078, val_loss: 1.1431733174298806
epochs 12/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0671413444099627, val_loss: 1.1357236741081116
epochs 13/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.081406133961303, val_loss: 1.1177560009022869
epochs 14/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0590494852415555, val_loss: 1.1033807564034033
epochs 15/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0757239757408021, val_loss: 1.0981167340404774
epochs 16/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0630966318839508, val_loss: 1.0993729899169276
epochs 17/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0684186457339382, val_loss: 1.104259700371475
epochs 18/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0547685685582187, val_loss: 1.1119002974222576
epochs 19/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.061871231538463, val_loss: 1.1184720059551259
epochs 20/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0675865567791525, val_loss: 1.1209485644385928
epochs 21/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0622065622769101, val_loss: 1.1184594479818193
epochs 22/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0575823109811513, val_loss: 1.1127036179184282
epochs 23/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.055454300960321, val_loss: 1.1072653557257677
epochs 24/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.067654205866509, val_loss: 1.1036831317124542
epochs 25/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0686445623168146, val_loss: 1.1048232342200304
epochs 26/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.061080295378001, val_loss: 1.1069499828197338
epochs 27/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0439879401191992, val_loss: 1.1109943787256877
epochs 28/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.05789063301386, val_loss: 1.1152564489021504
epochs 29/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0608217479046727, val_loss: 1.1144756867141319
epochs 30/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0532249905051985, val_loss: 1.1108866576795224
epochs 31/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.051223220625473, val_loss: 1.1045918716955436
epochs 32/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0448987240566634, val_loss: 1.1057286994167106
epochs 33/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.037076537521722, val_loss: 1.1241415266006711
epochs 34/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0233883439558338, val_loss: 1.1402049890901678
epochs 35/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0008493836637566, val_loss: 1.1530929362332378
epochs 36/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9793520048650771, val_loss: 1.1634333613057617
epochs 37/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9464259884120282, val_loss: 1.3109598090408972
epochs 38/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9102340605870591, val_loss: 1.0194315087227594
epochs 39/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9563230238659843, val_loss: 1.4741487017384283
epochs 40/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9023212634456095, val_loss: 1.077498422413276
epochs 41/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9824248652183573, val_loss: 1.1300549898198042
epochs 42/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8500037673880293, val_loss: 1.5297009780924156
epochs 43/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8839972899222249, val_loss: 1.4530462531185655
epochs 44/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.872598452717846, val_loss: 1.2366833213775876
epochs 45/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8545219058765791, val_loss: 1.4993694598081881
epochs 46/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8583483895706256, val_loss: 1.5959896448428037
epochs 47/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8413604912957596, val_loss: 1.3825439662529677
epochs 48/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8665087082623187, val_loss: 1.4744594860329199
epochs 49/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8518879220123691, val_loss: 1.6316840572962685
epochs 50/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8357473655520934, val_loss: 1.4727311222641557
epochs 51/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8408867648134681, val_loss: 1.4507760181628837
epochs 52/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8372797669540525, val_loss: 1.6118052850955378
epochs 53/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8302360220729369, val_loss: 1.5182609797785522
epochs 54/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8241059961119247, val_loss: 1.4117089219824979
Starting fold 2:
epochs 1/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.3147984605086478, val_loss: 1.7663811754297327
epochs 2/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.4542719376714606, val_loss: 1.3045988953302776
epochs 3/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0782721933565642, val_loss: 1.069279260105557
epochs 4/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.022688002335398, val_loss: 1.0552844938147006
epochs 5/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.065194142492194, val_loss: 1.052414651901003
epochs 6/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0445977449417114, val_loss: 1.0531279583456654
epochs 7/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0354714023439509, val_loss: 1.070230971568476
epochs 8/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.01871242836902, val_loss: 1.0842273153325237
epochs 9/54
Current Learning Rate: 0.0021898022824337945
train_loss: 1.0026823552031265, val_loss: 1.097065286030845
epochs 10/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9893017812779076, val_loss: 1.1466924090864796
epochs 11/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.984639268799832, val_loss: 1.2298057470372115
epochs 12/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9651003900327181, val_loss: 1.2910123968881273
epochs 13/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.96291743516922, val_loss: 1.3794195153725841
epochs 14/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9473559743479678, val_loss: 1.4059253035399017
epochs 15/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.937382740096042, val_loss: 1.446080489764138
epochs 16/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9288131205659164, val_loss: 1.4593307751196403
epochs 17/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9196805778302645, val_loss: 1.5083974984587816
epochs 18/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.896278851283224, val_loss: 1.5323329810742978
epochs 19/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8951035405460157, val_loss: 1.5661150103523618
epochs 20/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8664480391301607, val_loss: 1.597880382386465
epochs 21/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8362945983284398, val_loss: 1.621847836428849
epochs 22/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8183219225783097, val_loss: 1.6680964035962624
epochs 23/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.7930230906135157, val_loss: 1.6702699371115872
epochs 24/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.7813162998149269, val_loss: 1.7007905326823078
epochs 25/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8169868977446305, val_loss: 1.72767799493497
epochs 26/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9880528588044016, val_loss: 1.7939628482495666
epochs 27/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9987513134354039, val_loss: 1.535289309012196
epochs 28/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.957419951338517, val_loss: 1.710442476171665
epochs 29/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9101562707047713, val_loss: 1.6544066333266163
epochs 30/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.9099063289792915, val_loss: 1.535114850947466
epochs 31/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.880826811414016, val_loss: 1.6087838373486958
epochs 32/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8479569730005766, val_loss: 1.6750360165954268
epochs 33/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8280567558188188, val_loss: 1.697366199796162
epochs 34/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.8052334910944888, val_loss: 1.7499968664986747
epochs 35/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.7714342895307039, val_loss: 1.7175319661539068
epochs 36/54
Current Learning Rate: 0.0021898022824337945
train_loss: 0.7652820718915839, val_loss: 1.801175803734512
epochs 37/54

[I 2024-01-27 01:51:59,464] Trial 3 pruned.

Current Learning Rate: 0.0021898022824337945
train_loss: 0.7470577309006139, val_loss: 1.7200811111107075
epochs 38/54
Starting fold 1:
epochs 1/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.528406027099849, val_loss: 1.611688359704598
epochs 2/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.5090157717310322, val_loss: 1.5909768147443337
epochs 3/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.493658978277476, val_loss: 1.5713976747775205
epochs 4/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.4771638060115395, val_loss: 1.5516054592435322
epochs 5/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.4624061846608267, val_loss: 1.531064996643672
epochs 6/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.4443884788383363, val_loss: 1.5090362230936687
epochs 7/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.428444378663108, val_loss: 1.4854525807042602
epochs 8/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.4097318412121678, val_loss: 1.459911719201103
epochs 9/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.3898210706511094, val_loss: 1.4316996323368536
epochs 10/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.3617150952054569, val_loss: 1.399941359878217
epochs 11/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.3354398261814218, val_loss: 1.3655882531372958
epochs 12/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.3032283876578845, val_loss: 1.330406665171265
epochs 13/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.2701796287017344, val_loss: 1.2967819221436032
epochs 14/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.2303941705464068, val_loss: 1.2669271098242865
epochs 15/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.2014645681331295, val_loss: 1.2430718102783123
epochs 16/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.1721770083092895, val_loss: 1.2258151082134752
epochs 17/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.151680385879197, val_loss: 1.214263159761984
epochs 18/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.122688842069416, val_loss: 1.205820978633941
epochs 19/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.119148209456998, val_loss: 1.1982601836875633
epochs 20/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.1048856174758592, val_loss: 1.191217061073061
epochs 21/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0842877164561087, val_loss: 1.1832389289109164
epochs 22/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0857249286162292, val_loss: 1.174717665349365
epochs 23/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.08449329443627, val_loss: 1.1664178667875824
epochs 24/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0887087302682288, val_loss: 1.158430120932362
epochs 25/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0874765243829858, val_loss: 1.1517744114790014
epochs 26/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0782075252832544, val_loss: 1.1477256187055476
epochs 27/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0785598149474378, val_loss: 1.1467225980506373
epochs 28/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0750377752393951, val_loss: 1.1473216398683175
epochs 29/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0857663585253412, val_loss: 1.1491049212753457
epochs 30/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0727524713695986, val_loss: 1.1523757302571858
epochs 31/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0789399040931182, val_loss: 1.1560740382583052
epochs 32/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.076597407226163, val_loss: 1.1600926660356068
epochs 33/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0696820594877472, val_loss: 1.1638803570358842
epochs 34/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.061299158640557, val_loss: 1.1674642197038763
epochs 35/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0725372848710464, val_loss: 1.1698011065286302
epochs 36/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0779976039656793, val_loss: 1.1716226370877059
epochs 37/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0720657066524966, val_loss: 1.1731004923109025
epochs 38/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0701830980041265, val_loss: 1.1737874639097345
epochs 39/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0810461793270412, val_loss: 1.1740605238253476
epochs 40/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.079069882787335, val_loss: 1.1738168354387637
epochs 41/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0805769821736202, val_loss: 1.173650374488225
epochs 42/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0765741308322128, val_loss: 1.1734906643156022
epochs 43/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0637056914923704, val_loss: 1.1736064329349174
epochs 44/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0690285223316771, val_loss: 1.173310878415587
epochs 45/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0701409584564687, val_loss: 1.1725297901365492
epochs 46/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0676073004437991, val_loss: 1.1713404144559587
epochs 47/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.071139034176372, val_loss: 1.1695087466921126
epochs 48/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0676870339828013, val_loss: 1.167388984765956
epochs 49/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0786946419021846, val_loss: 1.165893590008771
epochs 50/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0806795021626339, val_loss: 1.16517177586833
epochs 51/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.074812152622882, val_loss: 1.1644135814495187
epochs 52/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.064439955806233, val_loss: 1.1637627296346835
epochs 53/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0695844364415912, val_loss: 1.1635915009433
epochs 54/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0629202714141126, val_loss: 1.1639804461645702
epochs 55/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0743560884635486, val_loss: 1.1646022960622475
epochs 56/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0805642398864186, val_loss: 1.165500006347737
epochs 57/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0781542867890204, val_loss: 1.1662397807237332
epochs 58/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.077737042417077, val_loss: 1.1670232166058172
epochs 59/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0685304359615786, val_loss: 1.1675512248246127
epochs 60/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0699260053834365, val_loss: 1.1680646825719763
epochs 61/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0847903040691196, val_loss: 1.168922749145952
epochs 62/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0744929806724268, val_loss: 1.1697157224019368
epochs 63/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0644255377235212, val_loss: 1.1704029740479889
epochs 64/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0593025291153273, val_loss: 1.1704113489736325
epochs 65/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0770377987966488, val_loss: 1.1699431390358657
epochs 66/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0730992942580377, val_loss: 1.1698343028467169
epochs 67/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.080100576915042, val_loss: 1.1712721718682184
epochs 68/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0695521731651265, val_loss: 1.173851974426754
epochs 69/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0688405661058675, val_loss: 1.1771353022762077
epochs 70/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0607706838877413, val_loss: 1.1785012149306202
epochs 71/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0678527742156183, val_loss: 1.1753944543303636
epochs 72/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.072540687640924, val_loss: 1.168030028620725
epochs 73/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0595359739832853, val_loss: 1.159667693117939
epochs 74/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0531106488242823, val_loss: 1.1531045235023296
epochs 75/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0442782072496664, val_loss: 1.14925622624695
epochs 76/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0495061250257243, val_loss: 1.1491883501173958
epochs 77/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.046237737096417, val_loss: 1.1319312519497342
epochs 78/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0392141573092075, val_loss: 1.1318311968808452
epochs 79/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0278558475184816, val_loss: 1.1348098220017853
epochs 80/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0241988984702146, val_loss: 1.1504372276326336
epochs 81/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0225523516769808, val_loss: 1.141728889374506
epochs 82/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0026669964116282, val_loss: 1.1759252724824127
epochs 83/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9973699029203484, val_loss: 1.214257766330053
epochs 84/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9918364342594645, val_loss: 1.1467372374559837
epochs 85/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9697585723787078, val_loss: 1.2487109445390248
epochs 86/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9608980773007059, val_loss: 1.2181790417464322
epochs 87/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9609077301324974, val_loss: 1.3120230682312497
epochs 88/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9525595784811449, val_loss: 1.3517211341353321
epochs 89/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9738019754749319, val_loss: 1.0279589490915733
epochs 90/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0141132882752344, val_loss: 1.0328136140076571
epochs 91/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9285947190529389, val_loss: 1.369116466512125
epochs 92/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9330961485807808, val_loss: 1.4021329066110035
epochs 93/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.975044262346797, val_loss: 1.043993698226081
epochs 94/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9610477929339983, val_loss: 1.0036175181626013
epochs 95/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9546155636223199, val_loss: 1.0180954882707545
epochs 96/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9196219038588839, val_loss: 1.2903328358180939
epochs 97/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8991793434657351, val_loss: 1.4160526953046284
epochs 98/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.896920424481337, val_loss: 1.4709462558150923
epochs 99/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9084412012424768, val_loss: 1.4741016847115975
epochs 100/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9036654755083054, val_loss: 1.4492643648985202
epochs 101/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8864758230004636, val_loss: 1.4056433924922236
Starting fold 2:
epochs 1/101
Current Learning Rate: 0.002295793695679908
train_loss: 1.0017803882297716, val_loss: 1.4034874672612185
epochs 2/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9649694047476116, val_loss: 1.300728202496887
epochs 3/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9647293994301244, val_loss: 1.3281425483643063
epochs 4/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9458613646657843, val_loss: 1.3908597703963992
epochs 5/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.935646883437508, val_loss: 1.4493278769588975
epochs 6/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9274300863868312, val_loss: 1.4602737054622994
epochs 7/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9239336678856298, val_loss: 1.4321522977617052
epochs 8/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9383540134680899, val_loss: 1.475863396806061
epochs 9/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9220692270680477, val_loss: 1.4909334327808763
epochs 10/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9151576111191198, val_loss: 1.4719471616089028
epochs 11/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9160858417812147, val_loss: 1.499596772370515
epochs 12/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9116731957385414, val_loss: 1.5144860820164756
epochs 13/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9010284379908913, val_loss: 1.5802225719684015
epochs 14/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8901322942031057, val_loss: 1.5641831922783422
epochs 15/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9301183104515076, val_loss: 1.3228635106767928
epochs 16/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.929174081902755, val_loss: 1.467810309753216
epochs 17/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.9448994184795179, val_loss: 1.5218181868709584
epochs 18/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8880711216675607, val_loss: 1.552978792518535
epochs 19/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.899383008480072, val_loss: 1.6434069146554937
epochs 20/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8788857729811418, val_loss: 1.6610106280241064
epochs 21/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8886571281834652, val_loss: 1.587391663480688
epochs 22/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8673000247854935, val_loss: 1.6149551433230203
epochs 23/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8618869944622642, val_loss: 1.567602481160845
epochs 24/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8443456881924679, val_loss: 1.5253862123640756
epochs 25/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.858373120583986, val_loss: 1.6087584577540242
epochs 26/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8514576560572574, val_loss: 1.5762889429374978
epochs 27/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8457303360888833, val_loss: 1.6777964546566917
epochs 28/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8389348456734105, val_loss: 1.621202313080036
epochs 29/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8471941809905202, val_loss: 1.58069580320328
epochs 30/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8325082465222008, val_loss: 1.561289870549762
epochs 31/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8325549897394682, val_loss: 1.6458495577807148
epochs 32/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8345618806387248, val_loss: 1.6224976355436618
epochs 33/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8311293570618881, val_loss: 1.610937857754016
epochs 34/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8236557515043962, val_loss: 1.6132821336625114
epochs 35/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8202288075497276, val_loss: 1.5619179004083865
epochs 36/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8219055420474002, val_loss: 1.6535816041250078
epochs 37/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8194745653554013, val_loss: 1.5758638205351654
epochs 38/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8182456211039895, val_loss: 1.637732393527157
epochs 39/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.821503872620432, val_loss: 1.4948299259105056
epochs 40/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8231339981681423, val_loss: 1.7007944255909593
epochs 41/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8090022476095903, val_loss: 1.5743646571245142
epochs 42/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8510176627259506, val_loss: 1.7557124410356795
epochs 43/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8107819657576711, val_loss: 1.7528818410540383
epochs 44/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8512782554877432, val_loss: 1.7859954430312706
epochs 45/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8031279149808381, val_loss: 1.6594033985541612
epochs 46/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8037629052212364, val_loss: 1.5322831156392578
epochs 47/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7955533266067505, val_loss: 1.5808141849659108
epochs 48/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7886853374932942, val_loss: 1.4985704951816134
epochs 49/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8062771050553573, val_loss: 1.6515207555558946
epochs 50/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.790666789757578, val_loss: 1.5828370732605141
epochs 51/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8239165513139022, val_loss: 1.5858900900240298
epochs 52/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.8072697244192425, val_loss: 1.5384788891625782
epochs 53/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7916666087351347, val_loss: 1.4987850555036433
epochs 54/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7827839744718451, val_loss: 1.5200802434689153
epochs 55/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7734479132451509, val_loss: 1.6200472097548226
epochs 56/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.786292070464084, val_loss: 1.5981748280701813
epochs 57/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7820550448016117, val_loss: 1.6448165310753717
epochs 58/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7925994672273334, val_loss: 1.538367543901716
epochs 59/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7692558119171544, val_loss: 1.6220094261976776
epochs 60/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7785529833090933, val_loss: 1.6340995743161155
epochs 61/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7645313946824325, val_loss: 1.562883557465972
epochs 62/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7663620779388829, val_loss: 1.639348966104013
epochs 63/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.784506618976593, val_loss: 1.5553971825453339
epochs 64/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.762495241667095, val_loss: 1.6532677973388994
epochs 65/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7762089371681213, val_loss: 1.62733440298252
epochs 66/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.7674310966541893, val_loss: 1.6057829503659848
epochs 67/101
Current Learning Rate: 0.002295793695679908

[I 2024-01-27 01:52:12,913] Trial 4 pruned.

Current Learning Rate: 0.002295793695679908
train_loss: 0.6557667600040067, val_loss: 1.4393657004391704
epochs 69/101
Current Learning Rate: 0.002295793695679908
train_loss: 0.669988322237045, val_loss: 1.4510798347059382
epochs 70/101
Starting fold 1:
epochs 1/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.6484782776907476, val_loss: 1.2302497833494157
epochs 2/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.2134852571637218, val_loss: 1.0791180228430128
epochs 3/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.090794412877547, val_loss: 1.1302765456456987
epochs 4/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0702260027381139, val_loss: 1.1054546284297155
epochs 5/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0854713286404833, val_loss: 1.0741187125917464
epochs 6/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.096555535705926, val_loss: 1.078059298651559
epochs 7/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0778338010398505, val_loss: 1.091781425097632
epochs 8/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0880252790700702, val_loss: 1.0958510921114968
epochs 9/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0806917463921752, val_loss: 1.0852858547180417
epochs 10/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.067811658869239, val_loss: 1.0799567737276592
epochs 11/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0758685897158078, val_loss: 1.0769040565642098
epochs 12/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0763604341377138, val_loss: 1.0726907366798037
epochs 13/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0893968506009166, val_loss: 1.0755426448488992
epochs 14/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0667181870076046, val_loss: 1.0850043750944591
epochs 15/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0815106093571447, val_loss: 1.0893083451286194
epochs 16/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.081727970957132, val_loss: 1.0774602644027225
epochs 17/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.081212741542237, val_loss: 1.0744953571803986
epochs 18/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0820157708921982, val_loss: 1.0789130926132202
epochs 19/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0694784493970622, val_loss: 1.0847979064971682
epochs 20/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0901498644763887, val_loss: 1.0834084900598677
epochs 21/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0681393889232456, val_loss: 1.0816797718169198
epochs 22/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0693059760238488, val_loss: 1.076830262229556
epochs 23/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0879922381246276, val_loss: 1.0685963763131037
epochs 24/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0755096212107473, val_loss: 1.071294729671781
epochs 25/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0695824804106309, val_loss: 1.0854500532150269
epochs 26/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0719206077266115, val_loss: 1.0879558495112829
epochs 27/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0712218003747351, val_loss: 1.08211616675059
epochs 28/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0731318708489703, val_loss: 1.0810753334136236
epochs 29/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0807085224471167, val_loss: 1.0829923361066789
epochs 30/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0687892724082109, val_loss: 1.0892866055170696
epochs 31/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0723710840285137, val_loss: 1.0902326844987416
epochs 32/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0805827073401806, val_loss: 1.085638892082941
epochs 33/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.084290880183275, val_loss: 1.088105222535512
epochs 34/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0757146911471303, val_loss: 1.088240277199518
epochs 35/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.075992626045387, val_loss: 1.078910780331445
epochs 36/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0677383888454337, val_loss: 1.0794203527390012
epochs 37/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0753759944626173, val_loss: 1.0806773333322435
epochs 38/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0716926396205164, val_loss: 1.079836270165822
epochs 39/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0803481540130695, val_loss: 1.0836750647378346
epochs 40/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.067814339517923, val_loss: 1.08594686833639
epochs 41/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0695914229797443, val_loss: 1.0845784895003787
epochs 42/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0690077805394278, val_loss: 1.085886011047969
epochs 43/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.079072528484604, val_loss: 1.0869393518992834
epochs 44/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0710866794536251, val_loss: 1.088779644360618
epochs 45/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0797820946308956, val_loss: 1.0890932329117307
epochs 46/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.071974283737662, val_loss: 1.0870970903881012
epochs 47/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0785269131835218, val_loss: 1.087545869842408
epochs 48/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0727162074044112, val_loss: 1.0878006749682956
epochs 49/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0753432568455241, val_loss: 1.0809734416386438
epochs 50/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0815274821526093, val_loss: 1.079579135728261
epochs 51/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.075200186974091, val_loss: 1.085549583510747
epochs 52/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0822605156773673, val_loss: 1.100971363839649
epochs 53/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0790863249314393, val_loss: 1.0830281045701768
epochs 54/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0725093118807407, val_loss: 1.0778165639392914
epochs 55/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.079392237813061, val_loss: 1.0770949541576325
epochs 56/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0729301780930365, val_loss: 1.0794376607925174
epochs 57/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.069065721871341, val_loss: 1.0868620361600603
epochs 58/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0657447414248402, val_loss: 1.0928764116196406
epochs 59/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0783030425066724, val_loss: 1.0847503703738015
epochs 60/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0745538161063068, val_loss: 1.0811836284304421
epochs 61/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.067745028365969, val_loss: 1.0823637776904635
epochs 62/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0766626534037564, val_loss: 1.0818999135305012
epochs 63/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0723826067609936, val_loss: 1.0752288973520672
epochs 64/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0680297694281133, val_loss: 1.0814460024001107
epochs 65/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0741109598369498, val_loss: 1.0885368282832797
epochs 66/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0728422896400172, val_loss: 1.0880149148759388
epochs 67/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0781586232609774, val_loss: 1.0794204549183921
epochs 68/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.083517717441339, val_loss: 1.0762253280669924
epochs 69/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.078747057165775, val_loss: 1.0789317252143982
epochs 70/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0757306439714283, val_loss: 1.0790873993010748
epochs 71/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0794227154467118, val_loss: 1.0746213651838756
epochs 72/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0720482502932325, val_loss: 1.075647547131493
epochs 73/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0744608827910498, val_loss: 1.0786841748252747
epochs 74/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0737559271108417, val_loss: 1.0825816090144809
epochs 75/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0710054767069392, val_loss: 1.091353622693864
epochs 76/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0785031231286013, val_loss: 1.0875339678355627
epochs 77/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0730842682703627, val_loss: 1.0829062537541465
epochs 78/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0730235770110685, val_loss: 1.0742849906285603
epochs 79/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0786020268944545, val_loss: 1.0744684821083432
epochs 80/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0780027000067747, val_loss: 1.0781189089729672
epochs 81/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0695018225315354, val_loss: 1.083020289738973
epochs 82/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0690310313439495, val_loss: 1.0908020053591048
epochs 83/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0763847391018693, val_loss: 1.08389185156141
Starting fold 2:
epochs 1/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.1738743876156055, val_loss: 1.0738299195728604
epochs 2/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.1045221215800236, val_loss: 1.0562213015934778
epochs 3/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.1222379333094548, val_loss: 1.0692376115965465
epochs 4/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0694016500523216, val_loss: 1.0592570825228615
epochs 5/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0563764383918361, val_loss: 1.0581976932192605
epochs 6/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0506514561803717, val_loss: 1.0599649444458976
epochs 7/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0589562309415717, val_loss: 1.0587607924900357
epochs 8/83
Current Learning Rate: 0.024305686505905113
train_loss: 1.0549207643458718, val_loss: 1.0575876718475705
epochs 9/83

[I 2024-01-27 01:52:17,974] Trial 5 pruned.

Starting fold 1:
epochs 1/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5989239640260866, val_loss: 1.587611851868806
epochs 2/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.599056461718694, val_loss: 1.5869945685068767
epochs 3/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5992922957655022, val_loss: 1.5863740532486528
epochs 4/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5970330356927442, val_loss: 1.5857525445796825
epochs 5/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5963893879146476, val_loss: 1.585128082169427
epochs 6/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5954095874157252, val_loss: 1.5845002863142226
epochs 7/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5963455569681697, val_loss: 1.583868636025323
epochs 8/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5932973929100636, val_loss: 1.5832372815520674
epochs 9/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5920099001280301, val_loss: 1.5826076445756134
epochs 10/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5934874973996147, val_loss: 1.5819819900724623
epochs 11/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5933130923366048, val_loss: 1.5813546313179865
epochs 12/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5914788938941755, val_loss: 1.5807237934183191
epochs 13/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5890978399995734, val_loss: 1.58008783393436
epochs 14/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5897030374766645, val_loss: 1.5794482275291726
epochs 15/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5903725262087678, val_loss: 1.5788077689983226
epochs 16/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5893447586379126, val_loss: 1.578166334717362
epochs 17/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5885375956590262, val_loss: 1.5775275009649772
epochs 18/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5874133734178792, val_loss: 1.576885744377419
epochs 19/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.586634271431968, val_loss: 1.5762452637707745
epochs 20/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5870639641247495, val_loss: 1.5756023415812739
epochs 21/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.58526750884131, val_loss: 1.5749575473644115
epochs 22/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5841224486915229, val_loss: 1.5743130489631936
epochs 23/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5833961932446945, val_loss: 1.5736649786984478
epochs 24/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5858401222378795, val_loss: 1.5730136235555012
epochs 25/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.583755947532454, val_loss: 1.5723589217221294
epochs 26/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5821763014918222, val_loss: 1.5717031160990398
epochs 27/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5814081218230163, val_loss: 1.5710493237883956
epochs 28/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5824412993735668, val_loss: 1.570389398822078
epochs 29/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5792258534756007, val_loss: 1.56972603003184
epochs 30/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5796637210546363, val_loss: 1.5690577339243006
epochs 31/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5782704702846666, val_loss: 1.5683880073052865
epochs 32/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5778831199825747, val_loss: 1.5677158302730985
epochs 33/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.576601871021131, val_loss: 1.567041074788129
epochs 34/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5764566585031479, val_loss: 1.566361661310549
epochs 35/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5752883949829022, val_loss: 1.5656774353097986
epochs 36/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5752314572558976, val_loss: 1.5649914829819291
epochs 37/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5749252466631185, val_loss: 1.5643028065010354
epochs 38/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.574980456791623, val_loss: 1.56360752052731
epochs 39/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.573550299200088, val_loss: 1.5629082918167114
epochs 40/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5715489537303984, val_loss: 1.562205676679258
epochs 41/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.57168851348118, val_loss: 1.5614987523467452
epochs 42/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5699143884069633, val_loss: 1.5607857660011009
epochs 43/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5698313763004323, val_loss: 1.5600692519435175
epochs 44/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5695686377779976, val_loss: 1.5593524464854487
epochs 45/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5694587311819586, val_loss: 1.5586327226073653
epochs 46/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5673904587461063, val_loss: 1.5579088882163719
epochs 47/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.567157785305802, val_loss: 1.5571793538552743
epochs 48/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5647468573135854, val_loss: 1.5564426316155329
epochs 49/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5651432244565475, val_loss: 1.5557002712179113
epochs 50/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5651388455435868, val_loss: 1.554953893025716
epochs 51/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5625764986607418, val_loss: 1.5542011305137917
epochs 52/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5632579794728942, val_loss: 1.5534441382796675
epochs 53/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.561249910848927, val_loss: 1.552687026836254
epochs 54/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5614233597410911, val_loss: 1.5519234471850925
epochs 55/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5588966501944976, val_loss: 1.551152926904184
epochs 56/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5603587546273676, val_loss: 1.5503716027295147
epochs 57/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.559980120958458, val_loss: 1.5495749049716525
epochs 58/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5590975665297184, val_loss: 1.5487713151507907
epochs 59/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5583390303307179, val_loss: 1.5479582724747833
epochs 60/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5564571525413953, val_loss: 1.547132792296233
epochs 61/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5551442862805271, val_loss: 1.546301453201859
epochs 62/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5555884738243062, val_loss: 1.545468639444422
epochs 63/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5534361157741847, val_loss: 1.5446192644260548
epochs 64/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.552867742109049, val_loss: 1.5437565909491644
epochs 65/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5516124639211524, val_loss: 1.542884769263091
epochs 66/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5522229477997225, val_loss: 1.5420029869786016
epochs 67/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5496120665085877, val_loss: 1.541102546232718
epochs 68/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.550639299197971, val_loss: 1.5401926967832777
epochs 69/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.549201405485263, val_loss: 1.5392721582342077
epochs 70/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5477945879491837, val_loss: 1.5383355308462072
epochs 71/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5461542400390065, val_loss: 1.5373865410133645
epochs 72/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5456665024083323, val_loss: 1.536423299047682
epochs 73/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5445434522878436, val_loss: 1.535447080930074
epochs 74/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5436466401784208, val_loss: 1.5344647213264748
epochs 75/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.542572211844759, val_loss: 1.5334707277792472
epochs 76/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5410828771391465, val_loss: 1.5324622216048065
epochs 77/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5397230087150453, val_loss: 1.5314423199053164
epochs 78/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5393718312548093, val_loss: 1.5304024837635182
epochs 79/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5389823183339304, val_loss: 1.5293428500493367
epochs 80/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5381023091171424, val_loss: 1.5282663725040577
epochs 81/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5369451570261212, val_loss: 1.5271629845654522
epochs 82/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5328923145513884, val_loss: 1.5260445718412046
epochs 83/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5335337079632345, val_loss: 1.5249020037827667
epochs 84/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.53335851836579, val_loss: 1.5237383003588076
epochs 85/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5315106813820245, val_loss: 1.5225543004495126
epochs 86/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.530769011113032, val_loss: 1.5213538938098483
epochs 87/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5292072708069966, val_loss: 1.5201398973111753
epochs 88/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5278167949297041, val_loss: 1.5189125935236614
epochs 89/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5269584212627711, val_loss: 1.5176708300908406
epochs 90/119
Current Learning Rate: 4.998044994915679e-05
train_loss: 1.5235497577028125, val_loss: 1.5163975380085133
epochs 91/119

[I 2024-01-27 01:52:21,601] Trial 6 pruned.

Current Learning Rate: 4.998044994915679e-05
train_loss: 1.525017421283023, val_loss: 1.515089547192609
epochs 92/119
Starting fold 1:
epochs 1/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.5888720906841818, val_loss: 1.5933680534362793
epochs 2/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.5609027627875043, val_loss: 1.5589784383773804
epochs 3/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.530607450694938, val_loss: 1.5232075055440266
epochs 4/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.5023610604371076, val_loss: 1.4832553068796794
epochs 5/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.471474804803339, val_loss: 1.4359501600265503
epochs 6/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.4332198547443171, val_loss: 1.377041498819987
epochs 7/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.3896000054494249, val_loss: 1.304143746693929
epochs 8/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.3354141581120915, val_loss: 1.2180840969085693
epochs 9/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.2670597218718205, val_loss: 1.1277793248494465
epochs 10/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.2154367587953339, val_loss: 1.0522158741950989
epochs 11/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1810007101578237, val_loss: 1.0040129621823628
epochs 12/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1513989758117036, val_loss: 0.9766490658124288
epochs 13/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1454041971586137, val_loss: 0.9608545899391174
epochs 14/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1466260471269099, val_loss: 0.9523947238922119
epochs 15/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1397161733417611, val_loss: 0.9489861329396566
epochs 16/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1352583850241456, val_loss: 0.949031670888265
epochs 17/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1278451493897363, val_loss: 0.9496939778327942
epochs 18/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1186972329129723, val_loss: 0.9503261844317118
epochs 19/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1025110080604155, val_loss: 0.9508795340855917
epochs 20/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.109257564182681, val_loss: 0.9519705971082052
epochs 21/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0945487705824888, val_loss: 0.95374862353007
epochs 22/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1102127545167013, val_loss: 0.9550277392069498
epochs 23/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1024569413424787, val_loss: 0.951852043469747
epochs 24/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0982668268742986, val_loss: 0.9469899535179138
epochs 25/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.090391238634499, val_loss: 0.9441724419593811
epochs 26/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.082787273441934, val_loss: 0.945897122224172
epochs 27/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0815802057376083, val_loss: 0.9495635430018107
epochs 28/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.076858195334829, val_loss: 0.9539742867151896
epochs 29/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0719506874758535, val_loss: 0.9519808491071066
epochs 30/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.062510281957257, val_loss: 0.9450019001960754
epochs 31/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0717738951063904, val_loss: 0.9439340035120646
epochs 32/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0596031808728323, val_loss: 0.9560413956642151
epochs 33/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0583208921068001, val_loss: 0.9687724113464355
epochs 34/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0361299673924271, val_loss: 0.966664175192515
epochs 35/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0473776203799623, val_loss: 0.9760246078173319
epochs 36/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0470486021166696, val_loss: 0.9785080949465433
epochs 37/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0247375525105062, val_loss: 0.9703211784362793
epochs 38/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0122412390109756, val_loss: 0.9807995359102885
epochs 39/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9778009777917912, val_loss: 0.9982808033625284
epochs 40/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9827629780270042, val_loss: 0.9932917157808939
epochs 41/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9510561146661249, val_loss: 1.0077767968177795
epochs 42/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9626589866832913, val_loss: 1.020837167898814
epochs 43/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9706643354830318, val_loss: 1.034950892130534
epochs 44/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9409657247091463, val_loss: 1.0461522539456685
epochs 45/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9514608425307648, val_loss: 1.0191918015480042
epochs 46/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9145905798330357, val_loss: 1.0528860886891682
epochs 47/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9244975255734009, val_loss: 1.096902112166087
epochs 48/150
Epoch 00048: reducing learning rate of group 0 to 2.1348e-04.
Current Learning Rate: 0.0002134782267569435
train_loss: 0.924216322795883, val_loss: 1.060261646906535
epochs 49/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.8975387914642614, val_loss: 1.0656300981839497
epochs 50/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.9185537733332649, val_loss: 1.0960940718650818
epochs 51/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.914921549914395, val_loss: 1.1162448128064473
epochs 52/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.9080044755136779, val_loss: 1.0987854997316997
epochs 53/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.9211320419898208, val_loss: 1.1046272714932759
epochs 54/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.8763860389200181, val_loss: 1.1509719888369243
epochs 55/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.9043099263107589, val_loss: 1.1844021876653035
epochs 56/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.897339042412673, val_loss: 1.1775524814923604
epochs 57/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.8733812560429748, val_loss: 1.1700677275657654
epochs 58/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.8640474157495649, val_loss: 1.2061046759287517
epochs 59/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.8808331864822597, val_loss: 1.2397989829381306
epochs 60/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.8715472574789487, val_loss: 1.26213800907135
epochs 61/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.8491681606669701, val_loss: 1.2426576614379883
epochs 62/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.856393551015105, val_loss: 1.231155276298523
epochs 63/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.8574848724285346, val_loss: 1.267121394475301
epochs 64/150
Current Learning Rate: 0.0002134782267569435
train_loss: 0.8568540334857572, val_loss: 1.2997660636901855
epochs 65/150
Epoch 00065: reducing learning rate of group 0 to 1.1878e-04.
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8285132191724178, val_loss: 1.2974425554275513
epochs 66/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8332207880095037, val_loss: 1.2945385376612346
epochs 67/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8230057482007911, val_loss: 1.3043155670166016
epochs 68/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8351809524428782, val_loss: 1.3087400197982788
epochs 69/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8184049179416677, val_loss: 1.3106667200724285
epochs 70/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.817078147805174, val_loss: 1.304928183555603
epochs 71/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8168966489312537, val_loss: 1.314039985338847
epochs 72/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8135240156769128, val_loss: 1.318518877029419
epochs 73/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.829990572720298, val_loss: 1.33738108476003
epochs 74/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8106703439152053, val_loss: 1.348810354868571
epochs 75/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8148824631075584, val_loss: 1.3391040563583374
epochs 76/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8059059157577485, val_loss: 1.3289735714594524
epochs 77/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8121497294041499, val_loss: 1.3259910742441814
epochs 78/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8153401702174341, val_loss: 1.3425195217132568
epochs 79/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8037564735762112, val_loss: 1.3557554086049397
epochs 80/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.7839276634585794, val_loss: 1.350072701772054
epochs 81/150
Current Learning Rate: 0.00011877572954042662
train_loss: 0.8145254323775856, val_loss: 1.357664942741394
epochs 82/150
Epoch 00082: reducing learning rate of group 0 to 6.6085e-05.
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.8053674736104086, val_loss: 1.358543038368225
epochs 83/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.8175737833633473, val_loss: 1.3538754781087239
epochs 84/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7894940812394257, val_loss: 1.348741928736369
epochs 85/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7906752549384901, val_loss: 1.3517629305521648
epochs 86/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7900733955555561, val_loss: 1.3567372957865398
epochs 87/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7866258220600832, val_loss: 1.362829049428304
epochs 88/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7917402395247165, val_loss: 1.3701086044311523
epochs 89/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7865340004026578, val_loss: 1.3658474286397297
epochs 90/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.786253390355884, val_loss: 1.3548509279886882
epochs 91/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7781860547540076, val_loss: 1.3501277764638264
epochs 92/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.774164343379555, val_loss: 1.351427475611369
epochs 93/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7976576294262372, val_loss: 1.358949065208435
epochs 94/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7810796413434113, val_loss: 1.3594997326533
epochs 95/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7759363870502143, val_loss: 1.3599071502685547
epochs 96/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7774846612314903, val_loss: 1.359547734260559
epochs 97/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7754413947775102, val_loss: 1.3613752921422322
epochs 98/150
Current Learning Rate: 6.608483751330256e-05
train_loss: 0.7722575626292154, val_loss: 1.3648372491200764
epochs 99/150
Epoch 00099: reducing learning rate of group 0 to 3.6769e-05.
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7665386064982539, val_loss: 1.3674854437510173
epochs 100/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7717921683145443, val_loss: 1.3669524987538655
epochs 101/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7713038382651918, val_loss: 1.3637149731318157
epochs 102/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7567055359950865, val_loss: 1.364882270495097
epochs 103/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7623574625681208, val_loss: 1.366840124130249
epochs 104/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7663197341077614, val_loss: 1.36843736966451
epochs 105/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7566750438113488, val_loss: 1.3663080930709839
epochs 106/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7649804799968659, val_loss: 1.3630305528640747
epochs 107/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7696332198162977, val_loss: 1.3631387948989868
epochs 108/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7655853850289165, val_loss: 1.3671318689982097
epochs 109/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7628971383326653, val_loss: 1.3710413376490276
epochs 110/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7625539188141598, val_loss: 1.3739699125289917
epochs 111/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7513717017794779, val_loss: 1.3727205991744995
epochs 112/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7612830244433817, val_loss: 1.3729308048884075
epochs 113/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.747151622909526, val_loss: 1.3704605897267659
epochs 114/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7546379372321498, val_loss: 1.3666555484135945
epochs 115/150
Current Learning Rate: 3.676850284193099e-05
train_loss: 0.7320511594648761, val_loss: 1.3621114492416382
epochs 116/150
Epoch 00116: reducing learning rate of group 0 to 2.0457e-05.
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7480364089626916, val_loss: 1.359702507654826
epochs 117/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7369281713563111, val_loss: 1.3583410580952961
epochs 118/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7525762280946626, val_loss: 1.361225922902425
epochs 119/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7690983065135816, val_loss: 1.3658414681752522
epochs 120/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7421314435869611, val_loss: 1.3701698382695515
epochs 121/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7798757548419593, val_loss: 1.3734492858250935
epochs 122/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7491480431943663, val_loss: 1.3766972223917644
epochs 123/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7493880503464744, val_loss: 1.3775872389475505
epochs 124/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7386607334251803, val_loss: 1.377460281054179
epochs 125/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7440090717757559, val_loss: 1.37499996026357
epochs 126/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7402348802351827, val_loss: 1.3735645214716594
epochs 127/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7422425197681207, val_loss: 1.3704888025919597
epochs 128/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7411694097581334, val_loss: 1.369920055071513
epochs 129/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7452069979687636, val_loss: 1.3700795968373616
epochs 130/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7354243924714507, val_loss: 1.3713029225667317
epochs 131/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7563803266558348, val_loss: 1.371071497599284
epochs 132/150
Current Learning Rate: 2.0457382542023372e-05
train_loss: 0.7560276877505617, val_loss: 1.3721260229746501
epochs 133/150
Epoch 00133: reducing learning rate of group 0 to 1.1382e-05.
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7442969093147996, val_loss: 1.3744267622629802
epochs 134/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7311919087358795, val_loss: 1.3731118043263753
epochs 135/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7534260000077841, val_loss: 1.3716293573379517
epochs 136/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7449112414377522, val_loss: 1.3699718713760376
epochs 137/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7339495729791556, val_loss: 1.3694181839625041
epochs 138/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.749264290195485, val_loss: 1.3698322375615437
epochs 139/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7314890990355564, val_loss: 1.3708076079686482
epochs 140/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7417636798860515, val_loss: 1.3730977376302083
epochs 141/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7540551187051217, val_loss: 1.3751075665156047
epochs 142/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7406325912912478, val_loss: 1.3767032623291016
epochs 143/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7459207063258007, val_loss: 1.375900387763977
epochs 144/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7555465585118188, val_loss: 1.3736678759257
epochs 145/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7727755014418931, val_loss: 1.3711134195327759
epochs 146/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7483062741800128, val_loss: 1.3686671257019043
epochs 147/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7592183431873771, val_loss: 1.3685553471247356
epochs 148/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7393038921955368, val_loss: 1.3677686055501301
epochs 149/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.7353064557878759, val_loss: 1.3665512800216675
epochs 150/150
Epoch 00150: reducing learning rate of group 0 to 6.3328e-06.
Current Learning Rate: 6.33283694442677e-06
train_loss: 0.7401429035588709, val_loss: 1.3674872716267903
Starting fold 2:
epochs 1/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0484189549559042, val_loss: 1.7652408281962078
epochs 2/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9841889420622274, val_loss: 1.4419086575508118
epochs 3/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1259980720909017, val_loss: 1.3422632217407227
epochs 4/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.1186642645221008, val_loss: 1.3818053404490154
epochs 5/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.0563610238464256, val_loss: 1.4665910800298054
epochs 6/150
Current Learning Rate: 0.0003836891044628586
train_loss: 1.011551497327654, val_loss: 1.5074252088864644
epochs 7/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.9726289879334601, val_loss: 1.5927608807881672
epochs 8/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.88846369338663, val_loss: 1.6910254955291748
epochs 9/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.8903403180210214, val_loss: 1.7239580949147542
epochs 10/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.8631491278347216, val_loss: 1.7049611806869507
epochs 11/150
Current Learning Rate: 0.0003836891044628586
train_loss: 0.8582966602162311, val_loss: 1.6794217030207317
epochs 12/150
Current Learning Rate: 0.0003836891044628586

[I 2024-01-27 01:52:35,202] Trial 7 pruned.

Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.6795187956016314, val_loss: 1.8582087755203247
epochs 120/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.6953296959400177, val_loss: 1.8583431641260784
epochs 121/150
Current Learning Rate: 1.1382146895397056e-05
train_loss: 0.6993767108376089, val_loss: 1.85862398147583
epochs 122/150
Starting fold 1:
epochs 1/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.6066820908591386, val_loss: 1.5834436416625977
epochs 2/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.5954363502132956, val_loss: 1.5754020422224015
epochs 3/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.585346316791954, val_loss: 1.5674012066825989
epochs 4/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.57552336772699, val_loss: 1.5591107663654147
epochs 5/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.5646983097985152, val_loss: 1.5502418960843767
epochs 6/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.5526688935244894, val_loss: 1.5404700797701638
epochs 7/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.5409512351320676, val_loss: 1.5293875156886994
epochs 8/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.5270049322338004, val_loss: 1.5164028254766313
epochs 9/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.509581607673805, val_loss: 1.5006897922546145
epochs 10/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.4898835639054862, val_loss: 1.4810280780943612
epochs 11/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.462821642765824, val_loss: 1.455743081985958
epochs 12/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.4308195457408566, val_loss: 1.4229452761392745
epochs 13/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.3842570026507552, val_loss: 1.3818587235042028
epochs 14/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.3291339705751828, val_loss: 1.3368570161244226
epochs 15/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.2604151876809084, val_loss: 1.3025721557556638
epochs 16/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.1998591110968464, val_loss: 1.2954517754297408
epochs 17/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.1512755536284123, val_loss: 1.3050629865555536
epochs 18/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.1366110696842533, val_loss: 1.3044148910613287
epochs 19/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.1232534528402758, val_loss: 1.2854431186403548
epochs 20/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.1096000209528738, val_loss: 1.2548743410715981
epochs 21/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.0933340625613148, val_loss: 1.221642463926285
epochs 22/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.081053039478382, val_loss: 1.1919774025205583
epochs 23/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.077463314483303, val_loss: 1.1692393450509935
epochs 24/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.078112353829189, val_loss: 1.1536898045312791
epochs 25/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.0753583065502306, val_loss: 1.1443989239041767
epochs 26/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.0790908118193063, val_loss: 1.1401721182323636
epochs 27/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.0716518213611623, val_loss: 1.139496269680205
epochs 28/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.081735976703504, val_loss: 1.1415250225672646
epochs 29/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.0726312598632892, val_loss: 1.1455835255365523
epochs 30/122

[I 2024-01-27 01:52:36,939] Trial 8 pruned.

Current Learning Rate: 0.0003302661243307012
train_loss: 1.0731618048632956, val_loss: 1.150733718796382
epochs 31/122
Current Learning Rate: 0.0003302661243307012
train_loss: 1.072267199061928, val_loss: 1.156387105820671
epochs 32/122
Starting fold 1:
epochs 1/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.8703966764879476, val_loss: 0.9910906250514682
epochs 2/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0462099638284814, val_loss: 1.4036815923357766
epochs 3/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.1782033175073994, val_loss: 1.2897187616459276
epochs 4/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.1321741067926296, val_loss: 1.085363986630919
epochs 5/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.1096027072187493, val_loss: 1.1276681757477856
epochs 6/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0790504242113124, val_loss: 1.2027710796033264
epochs 7/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.1061816121895276, val_loss: 1.1257659676213745
epochs 8/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.068566581965741, val_loss: 1.1443625133504312
epochs 9/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.076454618838445, val_loss: 1.1181858494168235
epochs 10/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0764265909244877, val_loss: 1.1530092185136502
epochs 11/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0548864465733474, val_loss: 1.0258370174301996
epochs 12/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.025794213979032, val_loss: 1.0934566347687333
epochs 13/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0090872398845812, val_loss: 1.0255687649918612
epochs 14/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9774214959269418, val_loss: 1.0566190058592135
epochs 15/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9949145529282655, val_loss: 0.9942549605848928
epochs 16/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9440530863107811, val_loss: 0.9557401695579448
epochs 17/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.060000926412213, val_loss: 0.8684437136170725
epochs 18/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0525671786662796, val_loss: 0.9323582176178221
epochs 19/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9711960273263343, val_loss: 1.2547832203920557
epochs 20/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0027391910552979, val_loss: 0.9688562571056305
epochs 21/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9247704051552018, val_loss: 0.9944312392719208
epochs 22/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9452070709298418, val_loss: 1.0040638762176353
epochs 23/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9201010097383828, val_loss: 0.9933507868221828
epochs 24/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0009684362960736, val_loss: 0.886122066192526
epochs 25/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0302402473869123, val_loss: 0.8385420987214992
epochs 26/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9251414162950365, val_loss: 0.8843791800201255
epochs 27/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9487417006367789, val_loss: 1.2003544808695557
epochs 28/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9096585955295263, val_loss: 0.9339146916828458
epochs 29/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8936176137774402, val_loss: 1.00547053006591
epochs 30/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8793743617871669, val_loss: 0.8842031671887353
epochs 31/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9603957355958629, val_loss: 0.9054861835071019
epochs 32/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9745251726729708, val_loss: 1.3891030076950315
epochs 33/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.00040242372383, val_loss: 0.9706067102296012
epochs 34/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9124580877613647, val_loss: 0.8666826262675896
epochs 35/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8882933349509514, val_loss: 1.0684345695707533
epochs 36/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8777837859398407, val_loss: 0.8518108356566656
epochs 37/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8803589855813231, val_loss: 1.2042208184640875
epochs 38/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.161894228445922, val_loss: 1.50813740712625
epochs 39/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9951734642707865, val_loss: 1.0305845513545646
epochs 40/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9405512254275576, val_loss: 0.8543679606977594
epochs 41/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.898332312469083, val_loss: 0.8791105012414316
epochs 42/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9083636169034149, val_loss: 1.0279091457841258
epochs 43/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8747981287421981, val_loss: 0.9908369584058327
epochs 44/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.847841802691914, val_loss: 0.9161007309716845
epochs 45/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8107073519242372, val_loss: 0.8525814959611843
epochs 46/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8475662413691976, val_loss: 1.2391669251931408
epochs 47/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.3399798982430502, val_loss: 1.1455528281983876
epochs 48/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.090746203642241, val_loss: 1.1320417608533586
epochs 49/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.1050047537419185, val_loss: 1.1167261291433264
epochs 50/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.109869694210472, val_loss: 1.150498905509868
epochs 51/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0804842311050256, val_loss: 1.120611759089919
epochs 52/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.085945725440979, val_loss: 1.1521598687247625
epochs 53/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0907764116506926, val_loss: 1.0543211301167805
epochs 54/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0396835448230124, val_loss: 1.2985914113029602
epochs 55/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.1158328212368551, val_loss: 0.9969989323111438
epochs 56/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.024347817710557, val_loss: 1.2704553862728138
epochs 57/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0484583977005244, val_loss: 1.0306624363339136
epochs 58/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9702607905053343, val_loss: 1.139454895226413
epochs 59/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9905455817726894, val_loss: 0.9907323216635083
epochs 60/125
Epoch 00060: reducing learning rate of group 0 to 2.4923e-02.
Current Learning Rate: 0.02492312007338692
train_loss: 0.9468824769813977, val_loss: 0.9362655389245855
epochs 61/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9481002048672181, val_loss: 1.0559980150253054
epochs 62/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9119900333943791, val_loss: 1.1383973583973275
epochs 63/125
Current Learning Rate: 0.02492312007338692
train_loss: 1.055513486812252, val_loss: 0.8745778057941054
epochs 64/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9729076954706801, val_loss: 1.0099058706293662
epochs 65/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9310993368088887, val_loss: 1.1115142271001504
epochs 66/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9137237583779539, val_loss: 0.8798847450781121
epochs 67/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.876391578719254, val_loss: 0.8655216842101364
epochs 68/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9122791221628639, val_loss: 1.186770512313439
epochs 69/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.899486534258458, val_loss: 0.8433403016398193
epochs 70/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8805323689395844, val_loss: 1.2199310474294833
epochs 71/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.876754916775289, val_loss: 0.8412502316570787
epochs 72/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9198535287567459, val_loss: 1.309015054551382
epochs 73/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9305623850897344, val_loss: 0.850167798302161
epochs 74/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8857882590818156, val_loss: 1.1498507179280437
epochs 75/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8701892885238088, val_loss: 0.8700341809363592
epochs 76/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8189045780616281, val_loss: 1.018371616721784
epochs 77/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7967502253217847, val_loss: 0.845513669429002
epochs 78/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8593056819825896, val_loss: 1.4624868561981847
epochs 79/125
Current Learning Rate: 0.02492312007338692
train_loss: 1.0288597994449875, val_loss: 0.8155724234366543
epochs 80/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9251430746148394, val_loss: 1.181346922955185
epochs 81/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8518574693440143, val_loss: 0.8482167342352489
epochs 82/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.844221493648609, val_loss: 0.9862177983793632
epochs 83/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8120037186208195, val_loss: 0.9595234226928187
epochs 84/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7744551728533201, val_loss: 0.9459105086705041
epochs 85/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8041655137276774, val_loss: 0.8490371404501497
epochs 86/125
Current Learning Rate: 0.02492312007338692
train_loss: 1.0362460319908502, val_loss: 1.174057627165759
epochs 87/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9564725073220218, val_loss: 1.0175199855572332
epochs 88/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8579339107293733, val_loss: 1.0620357794736428
epochs 89/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9080307842549229, val_loss: 0.8059996912088344
epochs 90/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8985842045064996, val_loss: 0.9026930376335427
epochs 91/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8096829278306811, val_loss: 1.0331769475230463
epochs 92/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7877135623187919, val_loss: 0.8961835159826531
epochs 93/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7709655206240908, val_loss: 0.9845957040156006
epochs 94/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7526276717011217, val_loss: 0.8622346816870271
epochs 95/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8092824632584736, val_loss: 1.0356939920672663
epochs 96/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8299015841558965, val_loss: 0.8449778481135293
epochs 97/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.823056129260837, val_loss: 1.1061748814961267
epochs 98/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8125300956646185, val_loss: 0.8847154429349949
epochs 99/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.9068205425252465, val_loss: 1.0935296618118489
epochs 100/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8103133674067352, val_loss: 0.8763732121735023
epochs 101/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8643765752228143, val_loss: 0.947946550354125
epochs 102/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7496394561847467, val_loss: 0.9250564704496393
epochs 103/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.741118685425264, val_loss: 0.982367096754609
epochs 104/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7217520765609142, val_loss: 0.8249197846682614
epochs 105/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8188967704772949, val_loss: 1.3119676340193975
epochs 106/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8106903614798141, val_loss: 0.8248337124075208
epochs 107/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8141640243729996, val_loss: 1.0038272237020827
epochs 108/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.6951504362191205, val_loss: 0.9225556913507048
epochs 109/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7073745608953905, val_loss: 1.0024386095622229
epochs 110/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7117187193550989, val_loss: 0.9193048625396042
epochs 111/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.730571763989813, val_loss: 0.9835812096242551
epochs 112/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7297628559367195, val_loss: 0.8567117548808849
epochs 113/125
Current Learning Rate: 0.02492312007338692
train_loss: 1.1085941070661496, val_loss: 0.9768636683938364
epochs 114/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7952157302676696, val_loss: 0.8866208280835833
epochs 115/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.8474431902326215, val_loss: 0.9150465036195422
epochs 116/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7488115907339525, val_loss: 0.860861548040279
epochs 117/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7338403163780093, val_loss: 0.9843702514966329
epochs 118/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7388895837424313, val_loss: 0.883908523768975
epochs 119/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7036071578869645, val_loss: 0.973116397857666
epochs 120/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.6859325672943555, val_loss: 0.902622665204699
epochs 121/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.6785519219817916, val_loss: 0.9943267132239367
epochs 122/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.6820769622063761, val_loss: 0.8749404413990243
epochs 123/125
Current Learning Rate: 0.02492312007338692
train_loss: 0.7057070307706663, val_loss: 1.087265911241057
epochs 124/125
Epoch 00124: reducing learning rate of group 0 to 1.3806e-02.
Current Learning Rate: 0.01380568541466868
train_loss: 0.717641297123195, val_loss: 0.8393151738025524
epochs 125/125
Current Learning Rate: 0.01380568541466868
train_loss: 0.708609352873258, val_loss: 0.9009937358596337
Starting fold 2:
epochs 1/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.332892225918017, val_loss: 1.0681872147100944
epochs 2/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0698769719977128, val_loss: 1.0567164805831102
epochs 3/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0503007211183246, val_loss: 1.0514630277951558
epochs 4/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0522998577670046, val_loss: 1.0429014093661435
epochs 5/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.057215680574116, val_loss: 1.0303517513804965
epochs 6/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0332772844716123, val_loss: 1.0248401262772777
epochs 7/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0065294234376205, val_loss: 0.9669846914432667
epochs 8/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9642377194605376, val_loss: 0.9291666998434319
epochs 9/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9445165734542044, val_loss: 1.0130795461160165
epochs 10/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0208504162336651, val_loss: 1.0136318708223009
epochs 11/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.038289209416038, val_loss: 0.9371531722406862
epochs 12/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.97257443227266, val_loss: 0.8969055776873593
epochs 13/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9257918389219987, val_loss: 0.8899298616187282
epochs 14/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8997467028467279, val_loss: 0.9129070712145043
epochs 15/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9221470782631322, val_loss: 1.0026615140614685
epochs 16/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.029264749978718, val_loss: 1.020831286276459
epochs 17/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.1484396965880144, val_loss: 1.0697800646383295
epochs 18/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0863273206510042, val_loss: 1.0566301266983074
epochs 19/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0622595410597953, val_loss: 1.0500766001050434
epochs 20/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0544418705137153, val_loss: 1.0549163338999268
epochs 21/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0676694129642688, val_loss: 1.0592903974195007
epochs 22/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.056046143958443, val_loss: 1.047509576908495
epochs 23/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0573396682739258, val_loss: 1.0348477477119082
epochs 24/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0399612489499543, val_loss: 1.0287553945546428
epochs 25/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.02729000355068, val_loss: 1.0197042286711395
epochs 26/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0240358239726017, val_loss: 0.980403273509293
epochs 27/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9683878810782182, val_loss: 0.9829183977747721
epochs 28/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9978191005556207, val_loss: 0.963400196776819
epochs 29/125
Current Learning Rate: 0.04499319631986336
train_loss: 1.0036340813887747, val_loss: 0.910120234918342
epochs 30/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9043244393248308, val_loss: 0.9733927240447392
epochs 31/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9177853201564989, val_loss: 0.9010573029518127
epochs 32/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9504443319220292, val_loss: 0.9315652147171989
epochs 33/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9032522577988474, val_loss: 1.011461131156437
epochs 34/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9160189816826269, val_loss: 0.8987822330817974
epochs 35/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9221005935417979, val_loss: 0.8958912576947894
epochs 36/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8695656174107602, val_loss: 0.8956677175703502
epochs 37/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9012557035998294, val_loss: 0.8932263504260431
epochs 38/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9421624171106439, val_loss: 0.9030138872287892
epochs 39/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.9210332519129703, val_loss: 0.8799536392171546
epochs 40/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8855559116915652, val_loss: 0.8778121635396644
epochs 41/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8756125839133012, val_loss: 0.9331001573138766
epochs 42/125
Current Learning Rate: 0.04499319631986336

[I 2024-01-27 01:52:53,942] Trial 9 pruned.

Current Learning Rate: 0.04499319631986336
train_loss: 0.8793037500239005, val_loss: 2.6043318743428223
epochs 21/125
Current Learning Rate: 0.04499319631986336
train_loss: 0.8969224507025131, val_loss: 1.0986100350107466
epochs 22/125
Starting fold 1:
epochs 1/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.600083739969743, val_loss: 1.5910595712207614
epochs 2/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.602890459654843, val_loss: 1.590969749859401
epochs 3/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.60014882886597, val_loss: 1.5908814838954382
epochs 4/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.599581166087645, val_loss: 1.5907929170699346
epochs 5/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5993537678144365, val_loss: 1.590704770315261
epochs 6/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.6022043858523145, val_loss: 1.5906167995362055
epochs 7/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5995444009441355, val_loss: 1.590528823080517
epochs 8/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5996470938178258, val_loss: 1.590441346168518
epochs 9/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5992833500757266, val_loss: 1.590354084968567
epochs 10/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.599755941885304, val_loss: 1.5902669373012723
epochs 11/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5999290119290976, val_loss: 1.5901796420415242
epochs 12/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5994307732706918, val_loss: 1.5900917564119612
epochs 13/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.6006320203161988, val_loss: 1.5900039843150549
epochs 14/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5995144825331205, val_loss: 1.589915843237014
epochs 15/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5990686734933504, val_loss: 1.5898275829496837
epochs 16/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5998972148795403, val_loss: 1.5897392488661266
epochs 17/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.597998030522731, val_loss: 1.5896506366275607
epochs 18/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5992471659994874, val_loss: 1.5895627112615676
epochs 19/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.600189258290835, val_loss: 1.589475398971921
epochs 20/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5975653663355642, val_loss: 1.5893890744163877
epochs 21/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.599184562398501, val_loss: 1.5893017394202096
epochs 22/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5974649496727589, val_loss: 1.5892148869378226
epochs 23/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5976734061515767, val_loss: 1.589128545352391
epochs 24/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5979398052105729, val_loss: 1.5890415339242845
epochs 25/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5990935682626295, val_loss: 1.5889536993844169
epochs 26/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5981797828724247, val_loss: 1.5888660919098627
epochs 27/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5992765170741456, val_loss: 1.5887788307099115
epochs 28/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.598245847911735, val_loss: 1.5886915297735305
epochs 29/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5978787700543229, val_loss: 1.5886042685735793
epochs 30/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.5976195803487487, val_loss: 1.5885173820313954
epochs 31/50
Current Learning Rate: 2.090480311670659e-06
train_loss: 1.598426724603663, val_loss: 1.5884301832744054
epochs 32/50

[I 2024-01-27 01:52:56,030] Trial 10 pruned.

Starting fold 1:
epochs 1/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6616634130477905, val_loss: 1.5974721731962982
epochs 2/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.661614565325033, val_loss: 1.5974002786414334
epochs 3/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6614727274909693, val_loss: 1.59732926774908
epochs 4/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.661433883986548, val_loss: 1.5972587690151558
epochs 5/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6613852116449965, val_loss: 1.597188634847207
epochs 6/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6611976249055713, val_loss: 1.5971185006792583
epochs 7/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.661161184310913, val_loss: 1.5970485771774614
epochs 8/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6610503302818818, val_loss: 1.5969784568857264
epochs 9/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6609322194653655, val_loss: 1.596908652593219
epochs 10/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6608405063289622, val_loss: 1.5968386937701513
epochs 11/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.660795136271971, val_loss: 1.5967687841445681
epochs 12/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6605632673383384, val_loss: 1.5966989514688965
epochs 13/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6606325585180552, val_loss: 1.5966292594475722
epochs 14/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6605233097575722, val_loss: 1.5965593498219888
epochs 15/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6604502956280534, val_loss: 1.5964897908861675
epochs 16/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6602572396163542, val_loss: 1.5964199796555534
epochs 17/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.660140725954665, val_loss: 1.5963503576460338
epochs 18/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6601344815099426, val_loss: 1.5962807848339988
epochs 19/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6599382605228123, val_loss: 1.5962111275032085
epochs 20/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6598907528123306, val_loss: 1.5961418631215576
epochs 21/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6597742996914848, val_loss: 1.5960723111238428
epochs 22/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6598033561756473, val_loss: 1.596002597657461
epochs 23/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.659587858859157, val_loss: 1.595933227942734
epochs 24/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6595997111335474, val_loss: 1.5958640266347814
epochs 25/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6594522442493138, val_loss: 1.5957946569200545
epochs 26/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6592671428051295, val_loss: 1.5957253994765106
epochs 27/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6592081747754082, val_loss: 1.5956562404279355
epochs 28/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6590696036503576, val_loss: 1.595586828453831
epochs 29/75

[I 2024-01-27 01:52:58,052] Trial 11 pruned.

Current Learning Rate: 4.005379474674045e-06
train_loss: 1.658917872693526, val_loss: 1.5955176132696647
epochs 30/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.6588888786226044, val_loss: 1.5954485803684861
epochs 31/75
Current Learning Rate: 4.005379474674045e-06
train_loss: 1.658739739687655, val_loss: 1.5953793368011555
epochs 32/75
Starting fold 1:
epochs 1/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6175610026763996, val_loss: 1.6850661739470467
epochs 2/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6191908052454445, val_loss: 1.6843914020629156
epochs 3/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6181675189452647, val_loss: 1.6837392616524267
epochs 4/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6141170831250895, val_loss: 1.6830958809171404
epochs 5/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.617126807492441, val_loss: 1.6824595442524664
epochs 6/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6137454247599496, val_loss: 1.6818303223009463
epochs 7/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6143866203218231, val_loss: 1.6812059412557612
epochs 8/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6140317448770813, val_loss: 1.6805800571643486
epochs 9/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6109303629211107, val_loss: 1.679959462433265
epochs 10/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6150308354362768, val_loss: 1.6793410374373985
epochs 11/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.613084658902353, val_loss: 1.6787164772629106
epochs 12/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.61295684719585, val_loss: 1.6780933103864155
epochs 13/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.61081219905334, val_loss: 1.6774784244557537
epochs 14/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.611130265665304, val_loss: 1.6768689843081923
epochs 15/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6123411674149997, val_loss: 1.676257605275149
epochs 16/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6103039199769185, val_loss: 1.675646220565473
epochs 17/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6113091001959996, val_loss: 1.6750327367631217
epochs 18/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.609786605335655, val_loss: 1.674420923783035
epochs 19/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6107980780576536, val_loss: 1.6738119081214622
epochs 20/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.606107198131022, val_loss: 1.673204635816907
epochs 21/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6057274728545343, val_loss: 1.6726025021265423
epochs 22/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.60621721082957, val_loss: 1.6720094220348136
epochs 23/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.608111149977639, val_loss: 1.6714168654547796
epochs 24/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6053466784392352, val_loss: 1.6708222842090343
epochs 25/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6054545547325574, val_loss: 1.6702271125934742
epochs 26/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6042226172242489, val_loss: 1.669626992215555
epochs 27/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6043242103766397, val_loss: 1.6690217817901933
epochs 28/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6032418605544805, val_loss: 1.66841807630327
epochs 29/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6019604068776077, val_loss: 1.6678104854765392
epochs 30/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.602443333071564, val_loss: 1.6671990988746521
epochs 31/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6011155725149584, val_loss: 1.666591344056306
epochs 32/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.603165101006393, val_loss: 1.6659875824337913
epochs 33/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5996986846025076, val_loss: 1.6653872122840276
epochs 34/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.602767831367972, val_loss: 1.6647859408111167
epochs 35/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6001537164468416, val_loss: 1.6641846542005185
epochs 36/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6002132680403625, val_loss: 1.6635827734356834
epochs 37/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5977742678207876, val_loss: 1.6629815927888982
epochs 38/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6003669887313043, val_loss: 1.6623796243516227
epochs 39/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5949320980391577, val_loss: 1.6617735693694422
epochs 40/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5960032565431446, val_loss: 1.6611646199352528
epochs 41/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5957678275582678, val_loss: 1.6605591439696217
epochs 42/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5935050498752694, val_loss: 1.6599476949247733
epochs 43/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5925232427906615, val_loss: 1.659333902692038
epochs 44/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5960200226119676, val_loss: 1.658718886829558
epochs 45/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5943621010056341, val_loss: 1.6581030030729909
epochs 46/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.592460151742266, val_loss: 1.6574858603654083
epochs 47/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5932743636725462, val_loss: 1.6568660281953358
epochs 48/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5904750867663877, val_loss: 1.656239013823252
epochs 49/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5911752085411113, val_loss: 1.655606467887838
epochs 50/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5891313090998465, val_loss: 1.6549706307668535
epochs 51/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.591348133162054, val_loss: 1.6543314595701832
epochs 52/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.589017043563084, val_loss: 1.6536922120543385
epochs 53/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5866565641932462, val_loss: 1.6530493415852703
epochs 54/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5877668177270141, val_loss: 1.6523919452435125
epochs 55/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5870550652449045, val_loss: 1.6517278195688965
epochs 56/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5899715841752697, val_loss: 1.651056521153324
epochs 57/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.587441797031782, val_loss: 1.6503751593292075
epochs 58/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5847326997687055, val_loss: 1.649690377649176
epochs 59/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5870742435854768, val_loss: 1.6489991252384488
epochs 60/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.585931997024576, val_loss: 1.6483030413824415
epochs 61/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5851964120465423, val_loss: 1.647603189503705
epochs 62/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5817429051973433, val_loss: 1.6468975506131611
epochs 63/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.583504546375175, val_loss: 1.6461892853338251
epochs 64/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.582336820857063, val_loss: 1.6454722717325523
epochs 65/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5810698033627415, val_loss: 1.6447501397006725
epochs 66/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5799932873061815, val_loss: 1.6440187806174869
epochs 67/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5812520400391823, val_loss: 1.6432848752491058
epochs 68/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.580176024536812, val_loss: 1.6425417295839422
epochs 69/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.576528043647087, val_loss: 1.6417969761702118
epochs 70/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.578722961910108, val_loss: 1.6410477003723225
epochs 71/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5787606345421357, val_loss: 1.640294216928028
epochs 72/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.576792434872133, val_loss: 1.6395419943269598
epochs 73/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5753310394536761, val_loss: 1.6387830701454607
epochs 74/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.574988234729667, val_loss: 1.6380116945852048
epochs 75/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5754295487678487, val_loss: 1.637233158898732
epochs 76/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5761208715239121, val_loss: 1.6364517842651045
Starting fold 2:
epochs 1/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.60352356998544, val_loss: 1.5996867758887154
epochs 2/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.6035284123922648, val_loss: 1.5982337225051153
epochs 3/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.601523885915154, val_loss: 1.5967750618697474
epochs 4/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.600826471102865, val_loss: 1.5953151927423226
epochs 5/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5982129504806117, val_loss: 1.593858448916642
epochs 6/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.599153686824598, val_loss: 1.5923993883940277
epochs 7/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5978208416386654, val_loss: 1.5909450640754095
epochs 8/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.593976449652722, val_loss: 1.5894910696322324
epochs 9/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.594348378557908, val_loss: 1.5880397980806058
epochs 10/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5930019457089273, val_loss: 1.5865909756806793
epochs 11/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5906691388079994, val_loss: 1.5851398807354073
epochs 12/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5923612142864028, val_loss: 1.5836857197776673
epochs 13/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.5874287680575723, val_loss: 1.5822306492971996
epochs 14/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.586518883077722, val_loss: 1.5807703821747392
epochs 15/76
Current Learning Rate: 3.0500048546067386e-05
train_loss: 1.586164013649288, val_loss: 1.579300120394066
epochs 16/76

[I 2024-01-27 01:53:02,090] Trial 12 pruned.

Starting fold 1:
epochs 1/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.5633890454057624, val_loss: 1.2949807013153398
epochs 2/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.3217975687606172, val_loss: 1.0214720913972803
epochs 3/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.2105418109768973, val_loss: 0.9501230565328447
epochs 4/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.218335949001512, val_loss: 0.9393948379647795
epochs 5/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.2454429633954434, val_loss: 0.9372106683317316
epochs 6/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.2326239397388479, val_loss: 0.9374439713185426
epochs 7/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.2068892127556325, val_loss: 0.9404777966479145
epochs 8/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.2011071858605789, val_loss: 0.9449941664145737
epochs 9/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.1559034426798995, val_loss: 0.9488989720268856
epochs 10/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.1646372345105516, val_loss: 0.9514580217618791
epochs 11/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.162393811173464, val_loss: 0.9525534059635545
epochs 12/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.1707896858609783, val_loss: 0.9525085693944699
epochs 13/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.1693873146441593, val_loss: 0.9515906748948274
epochs 14/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.1765393814491352, val_loss: 0.9502986086108697
epochs 15/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.1695630541022535, val_loss: 0.9486731375966754
epochs 16/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.189149761699257, val_loss: 0.9470088078231408
epochs 17/91
Epoch 00017: reducing learning rate of group 0 to 1.0762e-03.
Current Learning Rate: 0.0010761961873359523
train_loss: 1.1792473022226264, val_loss: 0.9461148024866821
epochs 18/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.181058055131223, val_loss: 0.9460763931274414
epochs 19/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.1684759134397458, val_loss: 0.946028541004847
epochs 20/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.1608103098669602, val_loss: 0.9459640084120332
epochs 21/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.1789180436683575, val_loss: 0.9459018401367955
epochs 22/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.1699494541627575, val_loss: 0.9458370596643478
epochs 23/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.171797458726074, val_loss: 0.945793507275758
epochs 24/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.1788599369413566, val_loss: 0.9457740386327108
epochs 25/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.1716419898402628, val_loss: 0.9457699505109636
epochs 26/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.1941161539542113, val_loss: 0.9457967647169002
epochs 27/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.1709969961206326, val_loss: 0.9458302719883187
epochs 28/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.177881487689093, val_loss: 0.9458613168625605
epochs 29/91
Epoch 00029: reducing learning rate of group 0 to 1.1073e-04.
Current Learning Rate: 0.00011073276418629384
train_loss: 1.1766552126220384, val_loss: 0.9458897359787471
epochs 30/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.177101482271524, val_loss: 0.945892698234982
epochs 31/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.1682032949013235, val_loss: 0.9458938256773368
epochs 32/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.179605888134522, val_loss: 0.9458953075938754
epochs 33/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.1748876556051964, val_loss: 0.9458954523480128
epochs 34/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.1721438484666236, val_loss: 0.9458887230151545
epochs 35/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.1598950764895735, val_loss: 0.9458791525275619
epochs 36/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.1846361044813825, val_loss: 0.9458749404659977
epochs 37/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.1831750236256584, val_loss: 0.9458764914482359
epochs 38/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.1681322680093855, val_loss: 0.9458763243029358
epochs 39/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.185532125815047, val_loss: 0.9458742047113086
epochs 40/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.1685023282834996, val_loss: 0.9458707179972734
epochs 41/91
Epoch 00041: reducing learning rate of group 0 to 1.1394e-05.
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.1712058614061764, val_loss: 0.9458683587255932
epochs 42/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.169982078499819, val_loss: 0.9458681641432344
epochs 43/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.1765678356455258, val_loss: 0.9458679594690838
epochs 44/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.1733958646265, val_loss: 0.9458677106433444
epochs 45/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.1837964036077728, val_loss: 0.9458673877060098
epochs 46/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.1800478796684306, val_loss: 0.9458672971952529
epochs 47/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.1716923535806347, val_loss: 0.9458676526155422
epochs 48/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.1744990364419228, val_loss: 0.9458681543668112
epochs 49/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.173153510268446, val_loss: 0.9458686917547195
epochs 50/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.1641997517091442, val_loss: 0.9458692540567388
epochs 51/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.188738314581167, val_loss: 0.9458702112001086
epochs 52/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.167083976780557, val_loss: 0.9458705700894512
epochs 53/91
Epoch 00053: reducing learning rate of group 0 to 1.1723e-06.
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.1816456707984364, val_loss: 0.9458712594849723
epochs 54/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.1855873743276946, val_loss: 0.9458711462676841
epochs 55/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.1744117103322014, val_loss: 0.9458713610336263
epochs 56/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.170545660076341, val_loss: 0.9458713701793126
epochs 57/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.1776849699270038, val_loss: 0.9458714386142751
epochs 58/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.1631912345661544, val_loss: 0.9458713853170001
epochs 59/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.1812478737681325, val_loss: 0.9458715379553497
epochs 60/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.185609991637824, val_loss: 0.9458714512290147
epochs 61/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.1890240661136766, val_loss: 0.9458714543826996
epochs 62/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.165278313359665, val_loss: 0.9458714537519627
epochs 63/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.1645899982976664, val_loss: 0.9458714225304821
epochs 64/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.1696653075867298, val_loss: 0.9458713354887786
epochs 65/91
Epoch 00065: reducing learning rate of group 0 to 1.2062e-07.
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1880897942013766, val_loss: 0.945871252862234
epochs 66/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.184986936796398, val_loss: 0.9458713134129842
epochs 67/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1617338960083368, val_loss: 0.9458713127822472
epochs 68/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1777082310297102, val_loss: 0.9458713134129842
epochs 69/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1917069367089197, val_loss: 0.9458713143590897
epochs 70/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1703580948694838, val_loss: 0.9458713446344648
epochs 71/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1821769697503894, val_loss: 0.9458713153051952
epochs 72/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1695649564578272, val_loss: 0.9458711973573796
epochs 73/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1891806687360034, val_loss: 0.9458713165666691
epochs 74/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1644802006127322, val_loss: 0.9458712588542353
epochs 75/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1763176527947032, val_loss: 0.9458712894449789
epochs 76/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.1664436834020764, val_loss: 0.9458713200357225
epochs 77/91
Epoch 00077: reducing learning rate of group 0 to 1.2411e-08.
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.1746295915224165, val_loss: 0.9458712620079202
epochs 78/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.1693125513835727, val_loss: 0.9458712620079202
epochs 79/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.1687677633699947, val_loss: 0.9458712623232887
epochs 80/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.164082810828823, val_loss: 0.9458712620079202
epochs 81/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.17957019493842, val_loss: 0.9458712623232887
epochs 82/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.169792744501723, val_loss: 0.9458712620079202
epochs 83/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.18403629701175, val_loss: 0.9458713212971965
epochs 84/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.1714226481802177, val_loss: 0.9458712620079202
epochs 85/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.1662057210637637, val_loss: 0.9458712620079202
epochs 86/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.170560109365673, val_loss: 0.9458712620079202
epochs 87/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.1890596853500885, val_loss: 0.9458713212971965
epochs 88/91
Current Learning Rate: 1.2411232447459584e-08
train_loss: 1.1748606949576532, val_loss: 0.9458712620079202
epochs 89/91
Epoch 00089: reducing learning rate of group 0 to 1.2770e-09.
Current Learning Rate: 1.2770255944391308e-09
train_loss: 1.1694022838357856, val_loss: 0.9458712620079202
epochs 90/91
Current Learning Rate: 1.2770255944391308e-09
train_loss: 1.1706180697336246, val_loss: 0.9458712620079202
epochs 91/91
Current Learning Rate: 1.2770255944391308e-09
train_loss: 1.1725237182297632, val_loss: 0.9458712620079202
Starting fold 2:
epochs 1/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.117147193456951, val_loss: 1.0589984731068687
epochs 2/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.0397787912895804, val_loss: 1.0768545840783095
epochs 3/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.081750996489274, val_loss: 1.1017511490160825
epochs 4/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.1102040990402824, val_loss: 1.0949840261822654
epochs 5/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.1012879600650385, val_loss: 1.0795005566228635
epochs 6/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.080484668204659, val_loss: 1.0707757394149822
epochs 7/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.0689108945821462, val_loss: 1.0677997725350517
epochs 8/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.0584402369825463, val_loss: 1.0683028909264418
epochs 9/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.063789059927589, val_loss: 1.071176305334404
epochs 10/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.065374354626003, val_loss: 1.07355804607351
epochs 11/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.0781973267856397, val_loss: 1.0737280315823026
epochs 12/91
Current Learning Rate: 0.010459399637923951
train_loss: 1.072987161184612, val_loss: 1.0724346880559568
epochs 13/91
Epoch 00013: reducing learning rate of group 0 to 1.0762e-03.
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0679139240791924, val_loss: 1.0717475401661383
epochs 14/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0741908954946617, val_loss: 1.0717149487248174
epochs 15/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0622440774189799, val_loss: 1.0717150020220922
epochs 16/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.069755171160949, val_loss: 1.071710379350753
epochs 17/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0621761839640769, val_loss: 1.0717779751177188
epochs 18/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0603315253006784, val_loss: 1.0719318657955796
epochs 19/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0726474275714473, val_loss: 1.0720457582877427
epochs 20/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.068205064535141, val_loss: 1.0721797974652083
epochs 21/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0732421379340322, val_loss: 1.0722376505533855
epochs 22/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0652210223047356, val_loss: 1.0721757534950498
epochs 23/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0681037049544484, val_loss: 1.0720556321598234
epochs 24/91
Current Learning Rate: 0.0010761961873359523
train_loss: 1.0618006608988109, val_loss: 1.072064030738104
epochs 25/91
Epoch 00025: reducing learning rate of group 0 to 1.1073e-04.
Current Learning Rate: 0.00011073276418629384
train_loss: 1.067854947165439, val_loss: 1.0720863446356759
epochs 26/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0659002940905722, val_loss: 1.072087303355888
epochs 27/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0508497498537366, val_loss: 1.0720898370263439
epochs 28/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0745195573882054, val_loss: 1.072085930241479
epochs 29/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0667109809423747, val_loss: 1.0720828566601668
epochs 30/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0686379715016014, val_loss: 1.072071411937633
epochs 31/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0640772552866684, val_loss: 1.0720671957762784
epochs 32/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0652458877939928, val_loss: 1.072072790728675
epochs 33/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0579264223575593, val_loss: 1.072081584148306
epochs 34/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0555867944893085, val_loss: 1.0720867413692374
epochs 35/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0595230623295433, val_loss: 1.0720842184213104
epochs 36/91
Current Learning Rate: 0.00011073276418629384
train_loss: 1.0627635472699215, val_loss: 1.0720828579216408
epochs 37/91
Epoch 00037: reducing learning rate of group 0 to 1.1394e-05.
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.0565402140742854, val_loss: 1.0720872494278761
epochs 38/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.0597630532164322, val_loss: 1.0720882668066276
epochs 39/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.063110389834956, val_loss: 1.0720899679042675
epochs 40/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.0648167879957902, val_loss: 1.0720915520001972
epochs 41/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.0638138573420675, val_loss: 1.0720921042104248
epochs 42/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.0621463581135397, val_loss: 1.0720931726788718
epochs 43/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.068471352050179, val_loss: 1.0720937185817294
epochs 44/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.069535928964615, val_loss: 1.0720942733149048
epochs 45/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.0662231009257468, val_loss: 1.0720936665459284
epochs 46/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.0614129292337517, val_loss: 1.0720938116154344
epochs 47/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.0598711070261504, val_loss: 1.0720935848654893
epochs 48/91
Current Learning Rate: 1.1393596454462866e-05
train_loss: 1.0638813084677645, val_loss: 1.0720932111538277
epochs 49/91
Epoch 00049: reducing learning rate of group 0 to 1.1723e-06.
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0607553381668895, val_loss: 1.0720927753145733
epochs 50/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0687205967150237, val_loss: 1.072092920384079
epochs 51/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0740461101657466, val_loss: 1.072092976835039
epochs 52/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0649705504116258, val_loss: 1.0720932105230907
epochs 53/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0644857315640701, val_loss: 1.0720931196969652
epochs 54/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.054231761317504, val_loss: 1.072093266027945
epochs 55/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0643731311747902, val_loss: 1.0720932940957408
epochs 56/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.060494998254274, val_loss: 1.0720934404267206
epochs 57/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0649832706702382, val_loss: 1.0720934997159968
epochs 58/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0703444101308521, val_loss: 1.0720934994006284
epochs 59/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0624674514720314, val_loss: 1.0720933524389116
epochs 60/91
Current Learning Rate: 1.172318248542528e-06
train_loss: 1.0603223860263824, val_loss: 1.072093323740379
epochs 61/91
Epoch 00061: reducing learning rate of group 0 to 1.2062e-07.
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.0577718430443814, val_loss: 1.072093353385017
epochs 62/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.0674718085088228, val_loss: 1.0720932944111092
epochs 63/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.0595144425567828, val_loss: 1.0720932940957408
epochs 64/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.0630239753346695, val_loss: 1.072093323740379
epochs 65/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.0560911865610825, val_loss: 1.0720933234250103
epochs 66/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.0553365456430535, val_loss: 1.0720933537003856
epochs 67/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.0649197001206248, val_loss: 1.072093353385017
epochs 68/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.0559796712900462, val_loss: 1.072093353385017
epochs 69/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.0670644687978845, val_loss: 1.0720932647664712
epochs 70/91
Current Learning Rate: 1.206230255177676e-07
train_loss: 1.071219045237491, val_loss: 1.0720932944111092
epochs 71/91
Current Learning Rate: 1.206230255177676e-07

[I 2024-01-27 01:53:19,061] Trial 13 pruned.

Starting fold 1:
epochs 1/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.608811558229137, val_loss: 1.6234990169131567
epochs 2/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6078288074563312, val_loss: 1.623127092760076
epochs 3/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6084458865420357, val_loss: 1.6227626693311823
epochs 4/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6081223600197836, val_loss: 1.6224032350318143
epochs 5/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.607571085710176, val_loss: 1.6220456525762246
epochs 6/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6075899288916462, val_loss: 1.6216893543011297
epochs 7/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6075347275009955, val_loss: 1.621333602874998
epochs 8/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6054431480887048, val_loss: 1.620978450018262
epochs 9/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6056808457948775, val_loss: 1.6206236093763322
epochs 10/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6055221133207151, val_loss: 1.6202704559558283
epochs 11/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6052157036296983, val_loss: 1.6199173763315513
epochs 12/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6044595965540223, val_loss: 1.619565417526891
epochs 13/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6036723246749158, val_loss: 1.6192148570661191
epochs 14/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.60456031217625, val_loss: 1.618864897697691
epochs 15/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6026768172598633, val_loss: 1.6185148424572415
epochs 16/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6026536357340389, val_loss: 1.6181652848682706
epochs 17/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6026543703378808, val_loss: 1.617816750965421
epochs 18/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6022682776625867, val_loss: 1.617468791033225
epochs 19/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6020745288639169, val_loss: 1.6171209244501024
epochs 20/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.6014592990825314, val_loss: 1.6167736797736436
epochs 21/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.600170400130187, val_loss: 1.6164271440455522
epochs 22/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.5999003186899954, val_loss: 1.6160809426080613
epochs 23/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.59998010215959, val_loss: 1.6157344560774545
epochs 24/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.599636854925705, val_loss: 1.6153880641573952
epochs 25/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.5988960902728335, val_loss: 1.6150423136968461
epochs 26/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.5992629141083563, val_loss: 1.6146965424219768
epochs 27/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.5987245711980689, val_loss: 1.6143502917870012
epochs 28/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.5973567375962023, val_loss: 1.6140055416753052
epochs 29/65

[I 2024-01-27 01:53:20,590] Trial 14 pruned.

Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.597450746291595, val_loss: 1.613660556929452
epochs 30/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.5973919992047454, val_loss: 1.6133150669632765
epochs 31/65
Current Learning Rate: 1.2184059769431392e-05
train_loss: 1.5963587192964803, val_loss: 1.6129696728691223
epochs 32/65
Starting fold 1:
epochs 1/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.6671801362362209, val_loss: 1.56307129632859
epochs 2/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.6305046487229033, val_loss: 1.524932139765018
epochs 3/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.5885318811027167, val_loss: 1.4703209160496948
epochs 4/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.5208320037232643, val_loss: 1.380953825970806
epochs 5/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.4085885504777518, val_loss: 1.268959020180677
epochs 6/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.2817870740491057, val_loss: 1.2128439649703011
epochs 7/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.197774859623135, val_loss: 1.2180462211528151
epochs 8/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.1638201637417858, val_loss: 1.218776094850409
epochs 9/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.1449020146075344, val_loss: 1.1925791306470437
epochs 10/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.1235392683463572, val_loss: 1.1544392960412162
epochs 11/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0861815613601844, val_loss: 1.1205528249185552
epochs 12/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.085661781395917, val_loss: 1.1001023987613658
epochs 13/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0853444172449762, val_loss: 1.0922835510243813
epochs 14/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0693075993922367, val_loss: 1.095855539437955
epochs 15/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0755596472954876, val_loss: 1.1058326663163605
epochs 16/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0539365495062623, val_loss: 1.1212006252278726
epochs 17/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0539639311311133, val_loss: 1.1388018736763605
epochs 18/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.073064839028563, val_loss: 1.1535845906646163
epochs 19/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0589902026491016, val_loss: 1.159987869716826
epochs 20/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0694343563149737, val_loss: 1.1610676605234702
epochs 21/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0857381720817525, val_loss: 1.1558419238953364
epochs 22/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0661607600007381, val_loss: 1.1447695071104342
epochs 23/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0808474156244887, val_loss: 1.1338315438971949
epochs 24/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0783203540672182, val_loss: 1.1250714202406544
epochs 25/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0753867395261196, val_loss: 1.120373322850182
epochs 26/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0781432571211411, val_loss: 1.1194611377816983
epochs 27/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0731950736170663, val_loss: 1.121314460007602
epochs 28/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0682706998280829, val_loss: 1.1241132058794536
epochs 29/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0569201305274565, val_loss: 1.1269962812857652
epochs 30/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.073024189597025, val_loss: 1.1309823150987979
epochs 31/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.059313305697516, val_loss: 1.1331621446306743
epochs 32/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0723952310871703, val_loss: 1.1325499172563906
epochs 33/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0747566372936308, val_loss: 1.1299749064067053
epochs 34/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0709598076905256, val_loss: 1.1276299158732097
epochs 35/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0580394904650943, val_loss: 1.126748108359241
epochs 36/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0787826820193784, val_loss: 1.126563374327604
epochs 37/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0650514239416073, val_loss: 1.1267056824669006
epochs 38/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0552912129781633, val_loss: 1.1262268483954132
epochs 39/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0806423756464614, val_loss: 1.1256128120674658
epochs 40/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0626477265233145, val_loss: 1.1255160443997256
epochs 41/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.074208349457586, val_loss: 1.1255297370688626
epochs 42/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0744191458087942, val_loss: 1.1262307911322862
epochs 43/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.054898240803424, val_loss: 1.126137381508237
epochs 44/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.067334764914987, val_loss: 1.1268286080587477
epochs 45/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0507123357962564, val_loss: 1.126512119378993
epochs 46/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0627441119149093, val_loss: 1.126293249231167
epochs 47/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0682214273832231, val_loss: 1.1270614597532485
epochs 48/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0620592008710532, val_loss: 1.129470261316451
epochs 49/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0644607912183432, val_loss: 1.1310955752771368
epochs 50/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0821140873494572, val_loss: 1.13228513008703
epochs 51/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0814889975243214, val_loss: 1.1312236148844321
epochs 52/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0681299976029321, val_loss: 1.1299227905021143
epochs 53/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0691555376452302, val_loss: 1.1299170489033694
epochs 54/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0561101227530634, val_loss: 1.129582710997768
epochs 55/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0594010961617475, val_loss: 1.1298932808416862
epochs 56/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.07125582245632, val_loss: 1.129684675938238
epochs 57/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0645484231529436, val_loss: 1.1300933840413574
epochs 58/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.061399628666683, val_loss: 1.1317098046106004
epochs 59/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0613176529320123, val_loss: 1.1316274694664767
epochs 60/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0549173252120692, val_loss: 1.1301010374038938
epochs 61/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.081660595239769, val_loss: 1.1271094386539762
epochs 62/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0609248165060712, val_loss: 1.123984625099828
epochs 63/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0605672086096558, val_loss: 1.121810446971308
epochs 64/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0817786461395742, val_loss: 1.120791854051055
epochs 65/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0679143539273925, val_loss: 1.1213458271884413
epochs 66/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.065057389399144, val_loss: 1.121398129791179
epochs 67/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0710365834660556, val_loss: 1.1211674093569397
epochs 68/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0579468358249564, val_loss: 1.1219012478672008
epochs 69/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0639723380198653, val_loss: 1.1233904790626001
epochs 70/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.060984950415127, val_loss: 1.1256307767181801
epochs 71/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0670865880257172, val_loss: 1.127674136843
epochs 72/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0528362552532975, val_loss: 1.129514009864242
epochs 73/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0679403718229363, val_loss: 1.130806118722946
epochs 74/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0653363965568743, val_loss: 1.129802563203075
epochs 75/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0577832151457902, val_loss: 1.129028879145466
epochs 76/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.070236337746625, val_loss: 1.1286496113217066
epochs 77/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0555158039038095, val_loss: 1.1289654061907815
epochs 78/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0798949602386714, val_loss: 1.1281673857774683
epochs 79/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0645910832270278, val_loss: 1.1290373997713523
epochs 80/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0525037072091827, val_loss: 1.1322815884988775
epochs 81/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0645289602079941, val_loss: 1.1351269174505163
epochs 82/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0712757510040443, val_loss: 1.1370930942908797
epochs 83/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0831066326321108, val_loss: 1.1369784288305453
epochs 84/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0658331316803138, val_loss: 1.1351422954488684
epochs 85/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.070207627655948, val_loss: 1.1320377537813135
epochs 86/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.067436751894926, val_loss: 1.1284245164306075
epochs 87/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.062424919992217, val_loss: 1.1249233490575559
epochs 88/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0541629145282725, val_loss: 1.12419192311625
epochs 89/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0588650378881324, val_loss: 1.1242322732531835
epochs 90/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0749600626411238, val_loss: 1.1244160674867176
epochs 91/102
Current Learning Rate: 0.0021991897241803596
train_loss: 1.0629732558864573, val_loss: 1.1253886834654228
epochs 92/102

[I 2024-01-27 01:53:24,668] Trial 15 pruned.

Starting fold 1:
epochs 1/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.6657745713338803, val_loss: 1.4776183234320746
epochs 2/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.289768436192218, val_loss: 1.2859909799363878
epochs 3/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.1168191208265215, val_loss: 1.288603495668482
epochs 4/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.3236969784292252, val_loss: 1.176961792839898
epochs 5/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0954120502421993, val_loss: 1.087834550274743
epochs 6/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.074072241783142, val_loss: 1.4182936482959323
epochs 7/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.1497901859083726, val_loss: 1.1694214917995311
epochs 8/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0866945925807454, val_loss: 1.1198348204294841
epochs 9/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0687732034952853, val_loss: 1.1431989073753357
epochs 10/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0658546667448514, val_loss: 1.17138996830693
epochs 11/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0689182799524037, val_loss: 1.2189853058920965
epochs 12/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0804290964965422, val_loss: 1.202527885083799
epochs 13/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0775162899057278, val_loss: 1.1778826625258834
epochs 14/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0742153746919483, val_loss: 1.1594456213491935
epochs 15/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.071295956666557, val_loss: 1.1609164101106149
epochs 16/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0715250956450457, val_loss: 1.1708518399132624
epochs 17/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.071904821545666, val_loss: 1.1706598643903379
epochs 18/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0722519583727053, val_loss: 1.1724037373507465
epochs 19/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.071955893052186, val_loss: 1.1665297967416268
epochs 20/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0718610218058082, val_loss: 1.1612129520486902
epochs 21/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0697971832065682, val_loss: 1.1652336186832852
epochs 22/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0721669203323843, val_loss: 1.1664926453872964
epochs 23/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0718813872462167, val_loss: 1.1659114250430354
epochs 24/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0712561613602163, val_loss: 1.166980125285961
epochs 25/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0706127969382322, val_loss: 1.1689506261437028
epochs 26/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0716913326872581, val_loss: 1.1668456616225067
epochs 27/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0709766130796903, val_loss: 1.1720969323758725
epochs 28/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0713641125494273, val_loss: 1.1673302915361192
epochs 29/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0706245187689496, val_loss: 1.1630273240583915
epochs 30/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0699953090458016, val_loss: 1.1620188885264926
epochs 31/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0681284965644957, val_loss: 1.1642870240741305
epochs 32/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0684539922244887, val_loss: 1.175604952706231
epochs 33/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0730169374905332, val_loss: 1.164162653463858
epochs 34/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0712518423639668, val_loss: 1.1564388319298073
epochs 35/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0691608440189462, val_loss: 1.1515027593683314
epochs 36/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0681967473154916, val_loss: 1.1612624327341716
epochs 37/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0698438308625946, val_loss: 1.169553233517541
epochs 38/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0700647837204458, val_loss: 1.1678620753464874
epochs 39/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0704999781403866, val_loss: 1.165863730289318
epochs 40/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0698878540418535, val_loss: 1.1656548976898193
epochs 41/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.070349346280722, val_loss: 1.1624306528656572
epochs 42/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.070227065011469, val_loss: 1.1578182975451152
epochs 43/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0690571993433369, val_loss: 1.160516129599677
epochs 44/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0686271933360874, val_loss: 1.1624195487410933
epochs 45/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0686326626083613, val_loss: 1.1678157912360296
epochs 46/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0706047368923406, val_loss: 1.1556587086783514
epochs 47/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0692139551901692, val_loss: 1.1665804231608357
epochs 48/66
Epoch 00048: reducing learning rate of group 0 to 3.7845e-02.
Current Learning Rate: 0.03784489309061442
train_loss: 1.069091275724441, val_loss: 1.1617482547406797
epochs 49/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.065886817677483, val_loss: 1.1613409033528082
epochs 50/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0656912869807937, val_loss: 1.1601082461851615
epochs 51/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0664129307132741, val_loss: 1.1545262138048809
epochs 52/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0653809377660302, val_loss: 1.1501211833070826
epochs 53/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0641695704135594, val_loss: 1.1503477935437803
epochs 54/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0640642124944957, val_loss: 1.1527961536690041
epochs 55/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0638780412873672, val_loss: 1.1541835776081792
epochs 56/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0613366527707164, val_loss: 1.1548774154097945
epochs 57/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0634388967334287, val_loss: 1.1567606616903234
epochs 58/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.066469324820953, val_loss: 1.1471785969204373
epochs 59/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0628877516192292, val_loss: 1.1449951308744926
epochs 60/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0602355546352127, val_loss: 1.1495741274621751
epochs 61/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0581401992218658, val_loss: 1.1572877389413339
epochs 62/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0651608025216308, val_loss: 1.1863022490783974
epochs 63/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.074332328991116, val_loss: 1.146261250531232
epochs 64/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0627715749890392, val_loss: 1.1244487916981731
epochs 65/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0614878419806195, val_loss: 1.1251131671446342
epochs 66/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.053824845408894, val_loss: 1.203047518376951
Starting fold 2:
epochs 1/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.446199957947982, val_loss: 1.060776781152796
epochs 2/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.118728522407381, val_loss: 1.1663784892470748
epochs 3/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0876039592843307, val_loss: 1.0535419782002766
epochs 4/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0714455941790029, val_loss: 1.0559406523351316
epochs 5/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0623411907961493, val_loss: 1.0590422594988789
epochs 6/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0469171718547219, val_loss: 1.0566618884051289
epochs 7/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0482614283498966, val_loss: 1.0559451580047607
epochs 8/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0579716351471449, val_loss: 1.0573084994598672
epochs 9/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0453865059112248, val_loss: 1.056149387801135
epochs 10/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0491025918408443, val_loss: 1.0563977073740076
epochs 11/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0460379473472896, val_loss: 1.0555816579748083
epochs 12/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.053454497142842, val_loss: 1.057167512399179
epochs 13/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.045890861749649, val_loss: 1.0552857628575079
epochs 14/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0465984059007545, val_loss: 1.0555904927077118
epochs 15/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0554881455082643, val_loss: 1.0546241226019684
epochs 16/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0622536367491673, val_loss: 1.0577755967775981
epochs 17/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0428116525474347, val_loss: 1.0555476281378005
epochs 18/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0565046721383144, val_loss: 1.054786624731841
epochs 19/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0463672186198987, val_loss: 1.0545133970401905
epochs 20/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0533116105355715, val_loss: 1.0559121546921906
epochs 21/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0467949992731997, val_loss: 1.0543868828702856
epochs 22/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0540087461471557, val_loss: 1.056824889447954
epochs 23/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0463969335744256, val_loss: 1.0548431608412001
epochs 24/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.047018882318547, val_loss: 1.0554032303668834
epochs 25/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0492361064019957, val_loss: 1.055185975851836
epochs 26/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0490244147024657, val_loss: 1.0558290901007477
epochs 27/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0459125907797562, val_loss: 1.0554489758279588
epochs 28/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0467193060799649, val_loss: 1.0555680946067527
epochs 29/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0487339920119236, val_loss: 1.0557355063932914
epochs 30/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0456606838263964, val_loss: 1.0556869904200237
epochs 31/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0430564450590234, val_loss: 1.0554585103635434
epochs 32/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0435746014118195, val_loss: 1.0552728242344327
epochs 33/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0455723671536696, val_loss: 1.0552854184751157
epochs 34/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0416924203697004, val_loss: 1.055211027463277
epochs 35/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0441364001286657, val_loss: 1.0552216547506827
epochs 36/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0479687446042112, val_loss: 1.0553731520970662
epochs 37/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.042257359623909, val_loss: 1.0553065251421045
epochs 38/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0419435916762603, val_loss: 1.0551602906650968
epochs 39/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0431413386997423, val_loss: 1.0552137825224135
epochs 40/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0422760742275339, val_loss: 1.0552482229691964
epochs 41/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0443715680586665, val_loss: 1.0553055030328256
epochs 42/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0428222143336345, val_loss: 1.0552865156420954
epochs 43/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0415937500564676, val_loss: 1.0552420527846724
epochs 44/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0425259900720496, val_loss: 1.0552953879038494
epochs 45/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0417924920195027, val_loss: 1.055228226714664
epochs 46/66
Epoch 00046: reducing learning rate of group 0 to 3.7845e-02.
Current Learning Rate: 0.03784489309061442
train_loss: 1.043838119977399, val_loss: 1.0552509934813887
epochs 47/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0391350804190886, val_loss: 1.0553058120939467
epochs 48/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0395619748454346, val_loss: 1.0554689875355474
epochs 49/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0396799245947286, val_loss: 1.0555866294436984
epochs 50/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.038945773243904, val_loss: 1.0555423630608454
epochs 51/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0404108147872122, val_loss: 1.0554933260988306
epochs 52/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.040627117690287, val_loss: 1.0554776986440022
epochs 53/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0423332433951529, val_loss: 1.0555423122865182
epochs 54/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0415868034488276, val_loss: 1.055601453339612
epochs 55/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0415769341744874, val_loss: 1.0555978307017573
epochs 56/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0397124274780876, val_loss: 1.0555204660804183
epochs 57/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0398885455570723, val_loss: 1.0554408188219424
epochs 58/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0399723906266063, val_loss: 1.0554436047871907
epochs 59/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0393955279337732, val_loss: 1.0554499052189015
epochs 60/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0392811522672052, val_loss: 1.0554290546311274
epochs 61/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0392073319146509, val_loss: 1.0554414810957733
epochs 62/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0406806282306973, val_loss: 1.0554916284702442
epochs 63/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.03940968811512, val_loss: 1.0555261572202046
epochs 64/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0393946619410264, val_loss: 1.0554961760838826
epochs 65/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.040935710386226, val_loss: 1.0553719644193296
epochs 66/66
Current Learning Rate: 0.03784489309061442
train_loss: 1.0420632799989298, val_loss: 1.0554750186425668
Starting fold 3:
epochs 1/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.3373870478782586, val_loss: 1.0568238253946658
epochs 2/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0666419376597882, val_loss: 1.0457521632865623
epochs 3/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0630413307456434, val_loss: 1.0486356461489643
epochs 4/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0646290299343517, val_loss: 1.051217004104897
epochs 5/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0489658973129017, val_loss: 1.0517418340400413
epochs 6/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0511063359324249, val_loss: 1.0511417499294988
epochs 7/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.052800820037225, val_loss: 1.0522884881054912
epochs 8/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.047348436236591, val_loss: 1.0542146541454174
epochs 9/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.051655773014511, val_loss: 1.0539673566818237
epochs 10/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.05144044573571, val_loss: 1.054083693910528
epochs 11/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0526014603085174, val_loss: 1.0554694886560794
epochs 12/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.05352898526066, val_loss: 1.0588731280079595
epochs 13/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.049590179496993, val_loss: 1.0595948961046007
epochs 14/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0516796891425322, val_loss: 1.0585855863712452
epochs 15/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0527383410658275, val_loss: 1.0594778458277385
epochs 16/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.053237740624768, val_loss: 1.0634653038448758
epochs 17/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0516659005664564, val_loss: 1.0564205182923212
epochs 18/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0508247075474744, val_loss: 1.0538506706555684
epochs 19/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0500081822616563, val_loss: 1.0538052121798198
epochs 20/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0494378939244784, val_loss: 1.0542902990623757
epochs 21/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0490724934634927, val_loss: 1.0520174039734735
epochs 22/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0485101801020817, val_loss: 1.0535687760070518
epochs 23/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0489836678773112, val_loss: 1.0526353496092338
epochs 24/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0492098239268486, val_loss: 1.0520733352060672
epochs 25/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0484851766344951, val_loss: 1.0522233799651817
epochs 26/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.048450840064218, val_loss: 1.0523416929774814
epochs 27/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0485185850902685, val_loss: 1.052020834551917
epochs 28/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0487685983964554, val_loss: 1.0522677699724834
epochs 29/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0475381472408247, val_loss: 1.0516545485567164
epochs 30/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0481698214484014, val_loss: 1.0526345725412722
epochs 31/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0487715821903074, val_loss: 1.0524300535519917
epochs 32/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0482151704220026, val_loss: 1.0519191446127716
epochs 33/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0491595803539029, val_loss: 1.0513790514734056
epochs 34/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0480949138086584, val_loss: 1.0526262698350128
epochs 35/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.048880430013727, val_loss: 1.0522975789176092
epochs 36/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0490304178219478, val_loss: 1.0510860129638955
epochs 37/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.0485078646344752, val_loss: 1.051920959243068
epochs 38/66
Current Learning Rate: 0.09274398223310444
train_loss: 1.048527099231425, val_loss: 1.0524042491559629
epochs 39/66

[I 2024-01-27 01:53:42,977] Trial 16 pruned.

Current Learning Rate: 0.09274398223310444
train_loss: 1.0569149911592477, val_loss: 1.2764381965001423
epochs 8/66
Starting fold 1:
epochs 1/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5347326937770345, val_loss: 1.4606550206583013
epochs 2/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.531065440302744, val_loss: 1.459336623943672
epochs 3/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.528953182135577, val_loss: 1.458076455605724
epochs 4/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5281597194871352, val_loss: 1.4568560609111079
epochs 5/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5244591629317918, val_loss: 1.4556695412075709
epochs 6/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5242645447166803, val_loss: 1.4545039077284474
epochs 7/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5229865893019432, val_loss: 1.4533477378269983
epochs 8/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5205556054389913, val_loss: 1.4521988535684252
epochs 9/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5184012482927731, val_loss: 1.45106715373892
epochs 10/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5139265746970452, val_loss: 1.4499298163822718
epochs 11/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5112484300323805, val_loss: 1.4487682662943684
epochs 12/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.509534823956914, val_loss: 1.4475871797591922
epochs 13/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5090971947964573, val_loss: 1.4463999284007563
epochs 14/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5057084098536306, val_loss: 1.4451878461888228
epochs 15/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.505408090446632, val_loss: 1.4439717468130526
epochs 16/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.5024075963734331, val_loss: 1.4427274787236775
epochs 17/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.501379857512669, val_loss: 1.4414562970872908
epochs 18/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.4971160676466857, val_loss: 1.4401661498206002
epochs 19/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.4954885924673829, val_loss: 1.438836269277744
epochs 20/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.4950527339705622, val_loss: 1.4374728328967221
epochs 21/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.4917447616916677, val_loss: 1.4360716021250164
epochs 22/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.490172652673971, val_loss: 1.4346273948275854
epochs 23/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.4861264840470558, val_loss: 1.4331301557954657
epochs 24/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.486783294153463, val_loss: 1.4315892041675629
epochs 25/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.4836246567870934, val_loss: 1.430000212457445
epochs 26/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.4797937133549395, val_loss: 1.4283615666091758
epochs 27/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.479067811167053, val_loss: 1.426666288779526
epochs 28/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.4747533891837634, val_loss: 1.424916389127257
epochs 29/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.473892318640704, val_loss: 1.423095911898941
epochs 30/89
Current Learning Rate: 0.00014008560932937295
train_loss: 1.4704309764332797, val_loss: 1.4212076115229773
epochs 31/89

[I 2024-01-27 01:53:44,615] Trial 17 pruned.

Current Learning Rate: 0.00014008560932937295
train_loss: 1.4665559336777132, val_loss: 1.4192641431061679
epochs 32/89
Starting fold 1:
epochs 1/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.5960042545308617, val_loss: 1.423883180769663
epochs 2/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.3204398891688642, val_loss: 1.383790101323809
epochs 3/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.1746219365384567, val_loss: 1.1527104390361322
epochs 4/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0783987257493104, val_loss: 1.106759337521104
epochs 5/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0739575930290821, val_loss: 1.162330530307911
epochs 6/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0714111187695208, val_loss: 1.223569531920095
epochs 7/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0825105215866528, val_loss: 1.1984239867124609
epochs 8/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0769283812083499, val_loss: 1.1557961967256334
epochs 9/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0738593015371192, val_loss: 1.1414076777362319
epochs 10/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0812869508853133, val_loss: 1.14466396336833
epochs 11/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0706150288357161, val_loss: 1.1544796461781497
epochs 12/68
Epoch 00012: reducing learning rate of group 0 to 1.3584e-03.
Current Learning Rate: 0.001358403590305767
train_loss: 1.0785516853107833, val_loss: 1.151315622228794
epochs 13/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0578299249029908, val_loss: 1.1496909238674022
epochs 14/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0683839861011006, val_loss: 1.1476194505338315
epochs 15/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0596698288518096, val_loss: 1.1464862369355702
epochs 16/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0709099494974026, val_loss: 1.1455850594888919
epochs 17/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0606254423476014, val_loss: 1.1450058379501262
epochs 18/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0590660696878482, val_loss: 1.145456868504721
epochs 19/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0702448321886713, val_loss: 1.145368594341177
epochs 20/68
Epoch 00020: reducing learning rate of group 0 to 2.9549e-04.
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0647912162760789, val_loss: 1.1455715017974692
epochs 21/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0676014978848203, val_loss: 1.1456501546990934
epochs 22/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0548327949034606, val_loss: 1.1457027436564209
epochs 23/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0676388699970945, val_loss: 1.1458807786305745
epochs 24/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0545307566358157, val_loss: 1.146222503096969
epochs 25/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0578575034416158, val_loss: 1.1465130255966591
epochs 26/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.061372063858971, val_loss: 1.1466829417243836
epochs 27/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0638727321050554, val_loss: 1.1467214602011222
epochs 28/68
Epoch 00028: reducing learning rate of group 0 to 6.4279e-05.
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0591424001449066, val_loss: 1.1467607097020225
epochs 29/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0661556804991517, val_loss: 1.1467343291277607
epochs 30/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0630117130529193, val_loss: 1.1466667336761636
epochs 31/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0628396235211357, val_loss: 1.146585640453157
epochs 32/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.06116116171732, val_loss: 1.1464973845809856
epochs 33/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.06351481682343, val_loss: 1.1463978454549477
epochs 34/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0609043396580282, val_loss: 1.1462864699187103
epochs 35/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.066988803329268, val_loss: 1.1462274859191248
epochs 36/68
Epoch 00036: reducing learning rate of group 0 to 1.3983e-05.
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0667707221046168, val_loss: 1.1461589897751177
epochs 37/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0613220187381924, val_loss: 1.1461469269303417
epochs 38/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0617583887115198, val_loss: 1.1461279934676236
epochs 39/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0639242969882425, val_loss: 1.146100293391596
epochs 40/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0624192871972529, val_loss: 1.1460679290155884
epochs 41/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0636372993753842, val_loss: 1.1460345119395583
epochs 42/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0635576273134242, val_loss: 1.1460052085301233
epochs 43/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0712455670246903, val_loss: 1.1459804981473893
epochs 44/68
Epoch 00044: reducing learning rate of group 0 to 3.0417e-06.
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0671264900586992, val_loss: 1.1459642730692707
epochs 45/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0630687365981297, val_loss: 1.1459623581517941
epochs 46/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0612048878095537, val_loss: 1.1459591092256012
epochs 47/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0630565020426406, val_loss: 1.1459562898312927
epochs 48/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0684482845336354, val_loss: 1.1459507008708973
epochs 49/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0619224921571022, val_loss: 1.1459434486570812
epochs 50/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0634756918352937, val_loss: 1.1459375241446117
epochs 51/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0598986847862524, val_loss: 1.145932742527553
epochs 52/68
Epoch 00052: reducing learning rate of group 0 to 6.6165e-07.
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0678932473297518, val_loss: 1.14592897955072
epochs 53/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0623188496260119, val_loss: 1.1459275439933494
epochs 54/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.066587277107838, val_loss: 1.1459265335527047
epochs 55/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0636223704402983, val_loss: 1.1459257325167378
epochs 56/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0684446439693112, val_loss: 1.145925381196239
epochs 57/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0669084487785219, val_loss: 1.1459243348035864
epochs 58/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0592796403076012, val_loss: 1.1459234978156114
epochs 59/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0577352377756728, val_loss: 1.1459235810728932
epochs 60/68
Epoch 00060: reducing learning rate of group 0 to 1.4393e-07.
Current Learning Rate: 1.4392957863422116e-07
train_loss: 1.0659286127040524, val_loss: 1.1459233786063219
epochs 61/68
Current Learning Rate: 1.4392957863422116e-07
train_loss: 1.0644913659045834, val_loss: 1.1459233786063219
epochs 62/68
Current Learning Rate: 1.4392957863422116e-07
train_loss: 1.0633235511355374, val_loss: 1.145923446095179
epochs 63/68
Current Learning Rate: 1.4392957863422116e-07
train_loss: 1.0566894711624266, val_loss: 1.1459235337676195
epochs 64/68
Current Learning Rate: 1.4392957863422116e-07
train_loss: 1.0632145439142957, val_loss: 1.145923553951203
epochs 65/68
Current Learning Rate: 1.4392957863422116e-07
train_loss: 1.0617691883866076, val_loss: 1.1459232209220764
epochs 66/68
Current Learning Rate: 1.4392957863422116e-07
train_loss: 1.066026247296658, val_loss: 1.1459231534332195
epochs 67/68
Current Learning Rate: 1.4392957863422116e-07
train_loss: 1.0577007067141109, val_loss: 1.1459231017127869
epochs 68/68
Epoch 00068: reducing learning rate of group 0 to 3.1309e-08.
Current Learning Rate: 3.130907662570087e-08
train_loss: 1.0643772436062078, val_loss: 1.1459229509666484
Starting fold 2:
epochs 1/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.1004316367601092, val_loss: 1.0578973700129797
epochs 2/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0511933860025908, val_loss: 1.0549522641474607
epochs 3/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0605387210845947, val_loss: 1.054192826861427
epochs 4/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0542133168170327, val_loss: 1.0546529586353
epochs 5/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.051877854999743, val_loss: 1.0540572278714053
epochs 6/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0431282661463086, val_loss: 1.0539098574370933
epochs 7/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0515578935020848, val_loss: 1.053609397045519
epochs 8/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.048605431381025, val_loss: 1.0535056814945565
epochs 9/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0475166270607397, val_loss: 1.0534299501666315
epochs 10/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0542722228326296, val_loss: 1.0534377053931907
epochs 11/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0468419780856684, val_loss: 1.0533152765067166
epochs 12/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0444158146255895, val_loss: 1.053248081573103
epochs 13/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0464906300369061, val_loss: 1.0531491157869812
epochs 14/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.05006410385433, val_loss: 1.0532195047726707
epochs 15/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.052095283332624, val_loss: 1.053274774046802
epochs 16/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0527358190009468, val_loss: 1.0533436678704762
epochs 17/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0491802416349711, val_loss: 1.0534525702870081
epochs 18/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0514588597573733, val_loss: 1.0534664307321822
epochs 19/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0476310337844648, val_loss: 1.0533960739140789
epochs 20/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.045411310384148, val_loss: 1.0533745582141574
epochs 21/68
Epoch 00021: reducing learning rate of group 0 to 1.3584e-03.
Current Learning Rate: 0.001358403590305767
train_loss: 1.0493156517806805, val_loss: 1.0534016881039534
epochs 22/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0411048133122294, val_loss: 1.0533849354143496
epochs 23/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0366733805129402, val_loss: 1.0533920826104584
epochs 24/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0420049184247067, val_loss: 1.0534481522898194
epochs 25/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0417959294821086, val_loss: 1.0534392033935225
epochs 26/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.043554356851076, val_loss: 1.053392365811363
epochs 27/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0484558337613157, val_loss: 1.0533560823511194
epochs 28/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0428838971414065, val_loss: 1.053343171165103
epochs 29/68
Epoch 00029: reducing learning rate of group 0 to 2.9549e-04.
Current Learning Rate: 0.00029549424448463077
train_loss: 1.041269236489346, val_loss: 1.053329432767535
epochs 30/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.039857860615379, val_loss: 1.053331611963807
epochs 31/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0404457104833502, val_loss: 1.0533393712901564
epochs 32/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0390115966922358, val_loss: 1.0533536480217385
epochs 33/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0419911431638818, val_loss: 1.0533611821749853
epochs 34/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0379035033677753, val_loss: 1.0533703609749123
epochs 35/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0403019324729317, val_loss: 1.0533865390631256
epochs 36/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.040048361765711, val_loss: 1.0533935001918249
epochs 37/68
Epoch 00037: reducing learning rate of group 0 to 6.4279e-05.
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0361356766600358, val_loss: 1.0533998037772203
epochs 38/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0385809201943248, val_loss: 1.053402100290571
epochs 39/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.037882053224664, val_loss: 1.0534047134338864
epochs 40/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.042719856375142, val_loss: 1.0534049755051023
epochs 41/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0375659779498452, val_loss: 1.0534050196566909
epochs 42/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.041038005916696, val_loss: 1.0534055062702723
epochs 43/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0393832526708904, val_loss: 1.0534073786130027
epochs 44/68
Current Learning Rate: 6.42790177725372e-05
train_loss: 1.0421111674685226, val_loss: 1.0534071947531725
epochs 45/68
Epoch 00045: reducing learning rate of group 0 to 1.3983e-05.
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0372652988684805, val_loss: 1.0534079633061848
epochs 46/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.038724503705376, val_loss: 1.0534082736287798
epochs 47/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0391247793247824, val_loss: 1.0534083105268932
epochs 48/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0407049822179895, val_loss: 1.0534083130498413
epochs 49/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0364629877241034, val_loss: 1.0534083808540666
epochs 50/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0376821339130402, val_loss: 1.0534093616500733
epochs 51/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0437244879572014, val_loss: 1.053409299837849
epochs 52/68
Current Learning Rate: 1.3982648403214688e-05
train_loss: 1.0464879293190805, val_loss: 1.053408435728184
epochs 53/68
Epoch 00053: reducing learning rate of group 0 to 3.0417e-06.
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0416782200336456, val_loss: 1.0534076328000064
epochs 54/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0420110661732522, val_loss: 1.0534079465916548
epochs 55/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0399840336096915, val_loss: 1.0534077362408714
epochs 56/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0382247316209894, val_loss: 1.0534081045912687
epochs 57/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0402263051585148, val_loss: 1.053408443927765
epochs 58/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0397019000429857, val_loss: 1.0534076857819128
epochs 59/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.0408663034439087, val_loss: 1.0534077586320343
epochs 60/68
Current Learning Rate: 3.0416528307850803e-06
train_loss: 1.036482938967253, val_loss: 1.053408226954243
epochs 61/68
Epoch 00061: reducing learning rate of group 0 to 6.6165e-07.
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0397376258122293, val_loss: 1.0534076845204388
epochs 62/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0393924713134766, val_loss: 1.0534078081448872
epochs 63/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0378061768255735, val_loss: 1.0534080676931552
epochs 64/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.043883323355725, val_loss: 1.053407852927213
epochs 65/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0358511830631056, val_loss: 1.0534080519247306
epochs 66/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0425326108932496, val_loss: 1.0534081878485504
epochs 67/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0398244870336433, val_loss: 1.053408080938632
epochs 68/68
Current Learning Rate: 6.616523333945726e-07
train_loss: 1.0436976420251947, val_loss: 1.0534082518683539
Starting fold 3:
epochs 1/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.1115901165352136, val_loss: 1.0588852072518968
epochs 2/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.057283101266214, val_loss: 1.041998492662238
epochs 3/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0487116805698415, val_loss: 1.0445598480562683
epochs 4/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0530615061364401, val_loss: 1.0442004235333235
epochs 5/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0494422156278613, val_loss: 1.0424635432384632
epochs 6/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0513234448558626, val_loss: 1.0441352952094305
epochs 7/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0503296233019637, val_loss: 1.0461208605892445
epochs 8/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.0532364121430369, val_loss: 1.0461290885531713
epochs 9/68
Current Learning Rate: 0.006244657378602762
train_loss: 1.051158104504349, val_loss: 1.0450204147232904
epochs 10/68
Epoch 00010: reducing learning rate of group 0 to 1.3584e-03.
Current Learning Rate: 0.001358403590305767
train_loss: 1.0506899817756694, val_loss: 1.0446832549004328
epochs 11/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0464896681229134, val_loss: 1.0443781339933003
epochs 12/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0493825353511816, val_loss: 1.0446800690479379
epochs 13/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.050218562354941, val_loss: 1.0455225220432989
epochs 14/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0430194881134167, val_loss: 1.0454527398265858
epochs 15/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0462693524905373, val_loss: 1.045046247817852
epochs 16/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.0432014945102284, val_loss: 1.0450673648920008
epochs 17/68
Current Learning Rate: 0.001358403590305767
train_loss: 1.045066794842115, val_loss: 1.0453670671377233
epochs 18/68
Epoch 00018: reducing learning rate of group 0 to 2.9549e-04.
Current Learning Rate: 0.00029549424448463077
train_loss: 1.046321186009526, val_loss: 1.0458846726114788
epochs 19/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.045825000177997, val_loss: 1.045882834013177
epochs 20/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0432959364461982, val_loss: 1.0457084494293052
epochs 21/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0443849613880232, val_loss: 1.0455993609453635
epochs 22/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0445692025923772, val_loss: 1.0455623004171584
epochs 23/68
Current Learning Rate: 0.00029549424448463077
train_loss: 1.0432497045067786, val_loss: 1.0455174386185944
epochs 24/68

[I 2024-01-27 01:54:05,656] Trial 18 pruned.

Starting fold 1:
epochs 1/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6429600778050448, val_loss: 1.6269858148362901
epochs 2/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6427616667373017, val_loss: 1.6269423961639404
epochs 3/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.643218931103252, val_loss: 1.6269000238842435
epochs 4/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6422053069968499, val_loss: 1.6268583006329007
epochs 5/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.643718787512854, val_loss: 1.6268167760637071
epochs 6/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6426334431034109, val_loss: 1.6267753309673734
epochs 7/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.643330122787915, val_loss: 1.626733938852946
epochs 8/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6427398077480455, val_loss: 1.6266926394568548
epochs 9/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.642625034791637, val_loss: 1.6266513533062406
epochs 10/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.641471331032159, val_loss: 1.6266101863649156
epochs 11/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6424908950066692, val_loss: 1.6265689002143011
epochs 12/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6435716021123357, val_loss: 1.6265278392367892
epochs 13/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6431104699978654, val_loss: 1.6264868179957073
epochs 14/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6424682677104212, val_loss: 1.6264455450905695
epochs 15/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6426919630060646, val_loss: 1.6264041662216187
epochs 16/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.642375500414384, val_loss: 1.626362959543864
epochs 17/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6429827881109027, val_loss: 1.6263215276930068
epochs 18/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6419266605876504, val_loss: 1.6262803475062053
epochs 19/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6423069968897634, val_loss: 1.626239087846544
epochs 20/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.641976484453491, val_loss: 1.6261978016959295
epochs 21/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6426217712032858, val_loss: 1.626156873173184
epochs 22/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6418270752692097, val_loss: 1.6261151764127943
epochs 23/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6423201367493074, val_loss: 1.6260738902621799
epochs 24/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6423924568435908, val_loss: 1.6260327498118083
epochs 25/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.641682130504029, val_loss: 1.6259915828704834
epochs 26/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6417093682663604, val_loss: 1.6259501112831964
epochs 27/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6420707178365497, val_loss: 1.6259087986416287
epochs 28/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.643092680976029, val_loss: 1.6258673932817247
epochs 29/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6417629019752222, val_loss: 1.625826319058736
epochs 30/104
Current Learning Rate: 1.097143107939142e-06
train_loss: 1.642684249977791, val_loss: 1.6257853110631306
epochs 31/104

[I 2024-01-27 01:54:07,035] Trial 19 pruned.

Current Learning Rate: 1.097143107939142e-06
train_loss: 1.6405240933932559, val_loss: 1.6257439719306097
epochs 32/104
Starting fold 1:
epochs 1/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.6019441338733853, val_loss: 1.6673834437415713
epochs 2/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.6010868549346924, val_loss: 1.666959285105347
epochs 3/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.6033719809267533, val_loss: 1.6665438451464214
epochs 4/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.6009801332863214, val_loss: 1.6661305332940721
epochs 5/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.6011591669152545, val_loss: 1.6657164664495558
epochs 6/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.6008123783540975, val_loss: 1.6653022728269062
epochs 7/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5995522668848488, val_loss: 1.6648855915776006
epochs 8/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5983553850213894, val_loss: 1.6644666440903195
epochs 9/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.599366950114984, val_loss: 1.6640498020030834
epochs 10/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5989279684596036, val_loss: 1.6636333118670832
epochs 11/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5972471642868682, val_loss: 1.6632156895582006
epochs 12/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.596408214244543, val_loss: 1.6627975122007743
epochs 13/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5957651756196747, val_loss: 1.662374700818743
epochs 14/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5960087120845057, val_loss: 1.661950877734593
epochs 15/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5931948398420324, val_loss: 1.6615288547737888
epochs 16/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5961770281117624, val_loss: 1.6611078063016216
epochs 17/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5937184301346385, val_loss: 1.6606896434511458
epochs 18/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5927050263469755, val_loss: 1.660268062006229
epochs 19/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.594125501772496, val_loss: 1.659846241511996
epochs 20/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5932743811482535, val_loss: 1.6594291092857483
epochs 21/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5905957496603123, val_loss: 1.6590067545572917
epochs 22/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5926732860934671, val_loss: 1.6585792492306421
epochs 23/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.591839008930466, val_loss: 1.658153351652559
epochs 24/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5913637957647833, val_loss: 1.6577292933035148
epochs 25/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.591391788727326, val_loss: 1.6573020472097648
epochs 26/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5910146598416472, val_loss: 1.6568764940140739
epochs 27/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5889673963267141, val_loss: 1.6564485112195293
epochs 28/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5869834853716547, val_loss: 1.6560179310500938
epochs 29/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5899822793081793, val_loss: 1.6555871067854462
epochs 30/111

[I 2024-01-27 01:54:08,782] Trial 20 pruned.

Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5887465389611208, val_loss: 1.6551581551788976
epochs 31/111
Current Learning Rate: 1.2093082385082235e-05
train_loss: 1.5895280663255622, val_loss: 1.6547268704762534
epochs 32/111
Starting fold 1:
epochs 1/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.5798496632051717, val_loss: 1.3513684663823042
epochs 2/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.2405008252378533, val_loss: 1.3279721226011003
epochs 3/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.1164709117400085, val_loss: 1.1335754634211304
epochs 4/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0949447473306306, val_loss: 1.172360342015665
epochs 5/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0679194059671533, val_loss: 1.2276836873362305
epochs 6/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0854524333439572, val_loss: 1.1862307231892983
epochs 7/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0724270574709507, val_loss: 1.1369535172427143
epochs 8/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0681145653050608, val_loss: 1.129863839931589
epochs 9/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0664221248077472, val_loss: 1.1471843858244557
epochs 10/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0693074683244315, val_loss: 1.1575415083970972
epochs 11/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0766925059688028, val_loss: 1.1483745795709115
epochs 12/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0725013960094352, val_loss: 1.1454218121432753
epochs 13/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0711301546446317, val_loss: 1.1484631974861104
epochs 14/65
Epoch 00014: reducing learning rate of group 0 to 1.6954e-03.
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0678807649936977, val_loss: 1.1481422633721083
epochs 15/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0578758504378234, val_loss: 1.148264418203364
epochs 16/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0553993211366743, val_loss: 1.1478245762920884
epochs 17/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.071010218552894, val_loss: 1.1448122262954712
epochs 18/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0649171262511408, val_loss: 1.1421462663267024
epochs 19/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0660927255116208, val_loss: 1.1411456513026403
epochs 20/65
Epoch 00020: reducing learning rate of group 0 to 3.3196e-04.
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0585072461847236, val_loss: 1.143324438857023
epochs 21/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.066249722273562, val_loss: 1.1438571883257105
epochs 22/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0601004227917856, val_loss: 1.1444161909597892
epochs 23/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0580685812765391, val_loss: 1.14492158915
epochs 24/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0708898933146012, val_loss: 1.1451473147780806
epochs 25/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0640996469877153, val_loss: 1.1451903619463482
epochs 26/65
Epoch 00026: reducing learning rate of group 0 to 6.4997e-05.
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0624890311850304, val_loss: 1.1451059762762967
epochs 27/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0585267128744675, val_loss: 1.1451046731736925
epochs 28/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0588157576416175, val_loss: 1.1451263389890156
epochs 29/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0623171582271915, val_loss: 1.1451759439296822
epochs 30/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0563820469441838, val_loss: 1.145236333211263
epochs 31/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.065459044503916, val_loss: 1.145262974279898
epochs 32/65
Epoch 00032: reducing learning rate of group 0 to 1.2726e-05.
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.0615925938671171, val_loss: 1.1452765767536466
epochs 33/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.066118431965094, val_loss: 1.1452767432682098
epochs 34/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.0570426467825604, val_loss: 1.1452796276284274
epochs 35/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.0698979696678241, val_loss: 1.1452834612478024
epochs 36/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.0597933955217531, val_loss: 1.1452854606840346
epochs 37/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.0600545315842353, val_loss: 1.1452873163122348
epochs 38/65
Epoch 00038: reducing learning rate of group 0 to 2.4918e-06.
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.068749187504434, val_loss: 1.1452840408950886
epochs 39/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.068472698720962, val_loss: 1.1452804362332378
epochs 40/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.0596670121422613, val_loss: 1.1452754161976002
epochs 41/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.0647995344007202, val_loss: 1.1452714400316673
epochs 42/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.0625305203867208, val_loss: 1.14526768210073
epochs 43/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.069927838460313, val_loss: 1.1452632423431155
epochs 44/65
Epoch 00044: reducing learning rate of group 0 to 4.8789e-07.
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0646552615140745, val_loss: 1.1452581522956726
epochs 45/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0569756446084426, val_loss: 1.1452578482804474
epochs 46/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.060600050768927, val_loss: 1.1452570270608973
epochs 47/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0602876447258196, val_loss: 1.1452562014261882
epochs 48/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0650185490153847, val_loss: 1.145255693052181
epochs 49/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0587572155822633, val_loss: 1.1452554319270705
epochs 50/65
Epoch 00050: reducing learning rate of group 0 to 9.5527e-08.
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.063249980904045, val_loss: 1.1452552811809318
epochs 51/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.0719896511257632, val_loss: 1.1452551979236503
epochs 52/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.059632122204566, val_loss: 1.1452550471775116
epochs 53/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.063454407359917, val_loss: 1.1452548693096827
epochs 54/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.0629914505943578, val_loss: 1.1452548894932661
epochs 55/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.059904194939199, val_loss: 1.1452546870266949
epochs 56/65
Epoch 00056: reducing learning rate of group 0 to 1.8704e-08.
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0635739408862528, val_loss: 1.1452546668431116
epochs 57/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0613445798764054, val_loss: 1.145254309215243
epochs 58/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0672842270416738, val_loss: 1.1452543609356753
epochs 59/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0652948792692254, val_loss: 1.1452543609356753
epochs 60/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0640778747528636, val_loss: 1.145254309215243
epochs 61/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0649035588608986, val_loss: 1.1452543609356753
epochs 62/65
Epoch 00062: reducing learning rate of group 0 to 3.6622e-09.
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0593056004708974, val_loss: 1.1452543609356753
epochs 63/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0614148624904494, val_loss: 1.145254412656108
epochs 64/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0663681382908248, val_loss: 1.145254412656108
epochs 65/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0612786892821027, val_loss: 1.1452543609356753
Starting fold 2:
epochs 1/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.1163953567806044, val_loss: 1.0606687393768754
epochs 2/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.060595066296427, val_loss: 1.0538099565833965
epochs 3/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0592295420797249, val_loss: 1.0543499459665289
epochs 4/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.053476857197912, val_loss: 1.0536407109290835
epochs 5/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0506474745901007, val_loss: 1.0539355880368955
epochs 6/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0509578312698165, val_loss: 1.0536023368911138
epochs 7/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0493603414610813, val_loss: 1.053571602970204
epochs 8/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.052498804268084, val_loss: 1.053546428049683
epochs 9/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0469181537628174, val_loss: 1.0536027916524775
epochs 10/65
Epoch 00010: reducing learning rate of group 0 to 1.6954e-03.
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0507406796279706, val_loss: 1.0536300987793654
epochs 11/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0382972143198315, val_loss: 1.0535868065697807
epochs 12/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.045188957452774, val_loss: 1.0536499748785029
epochs 13/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0434391856193543, val_loss: 1.053760450037699
epochs 14/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0446242856351953, val_loss: 1.0537689662484264
epochs 15/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0426073457065381, val_loss: 1.0537324099944383
epochs 16/65
Epoch 00016: reducing learning rate of group 0 to 3.3196e-04.
Current Learning Rate: 0.0003319569414593337
train_loss: 1.04258387935789, val_loss: 1.0537184502081895
epochs 17/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0398253698098032, val_loss: 1.0537292506328966
epochs 18/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0353614687919617, val_loss: 1.0537579028063981
epochs 19/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0404506476301896, val_loss: 1.0537824113532979
epochs 20/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0431019532053094, val_loss: 1.053783417378784
epochs 21/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0377509556318585, val_loss: 1.053791206034403
epochs 22/65
Epoch 00022: reducing learning rate of group 0 to 6.4997e-05.
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0437425886329852, val_loss: 1.0537891075724648
epochs 23/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0408221596165708, val_loss: 1.053786823673854
epochs 24/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.037972074433377, val_loss: 1.0537871163358132
epochs 25/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0335478585017355, val_loss: 1.0537888555930406
epochs 26/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0411379309077011, val_loss: 1.0537910978630107
epochs 27/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0435921239225487, val_loss: 1.0537921978683067
epochs 28/65
Epoch 00028: reducing learning rate of group 0 to 1.2726e-05.
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.040403120454989, val_loss: 1.0537921827306191
epochs 29/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.041882231047279, val_loss: 1.053791349842435
epochs 30/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.0412245468089456, val_loss: 1.0537912303177768
epochs 31/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.0430263867503717, val_loss: 1.053791051188474
epochs 32/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.0435916492813513, val_loss: 1.0537907597879883
epochs 33/65
Current Learning Rate: 1.2726228497575556e-05
train_loss: 1.0373031362106926, val_loss: 1.0537910272204687
epochs 34/65
Epoch 00034: reducing learning rate of group 0 to 2.4918e-06.
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.0412519398488496, val_loss: 1.0537909345021323
epochs 35/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.0380641567079645, val_loss: 1.0537904699643452
epochs 36/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.042252875001807, val_loss: 1.0537906970296587
epochs 37/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.0417198745827927, val_loss: 1.0537904892018233
epochs 38/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.0395424824011954, val_loss: 1.053790639947962
epochs 39/65
Current Learning Rate: 2.491774274299325e-06
train_loss: 1.0372586049531636, val_loss: 1.0537909073804421
epochs 40/65
Epoch 00040: reducing learning rate of group 0 to 4.8789e-07.
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.042215267921749, val_loss: 1.0537911826971347
epochs 41/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0382750034332275, val_loss: 1.0537905980039526
epochs 42/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0394116875372434, val_loss: 1.0537906462553317
epochs 43/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0407142519950867, val_loss: 1.0537907181593476
epochs 44/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0384294023639278, val_loss: 1.0537907348738775
epochs 45/65
Current Learning Rate: 4.878852391533578e-07
train_loss: 1.0396620235945049, val_loss: 1.0537909540549788
epochs 46/65
Epoch 00046: reducing learning rate of group 0 to 9.5527e-08.
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.0405400238539044, val_loss: 1.0537909102187586
epochs 47/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.0406474769115448, val_loss: 1.0537909102187586
epochs 48/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.0395595170949634, val_loss: 1.0537908190772647
epochs 49/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.0419946610927582, val_loss: 1.0537908190772647
epochs 50/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.0394808568452534, val_loss: 1.053790858498326
epochs 51/65
Current Learning Rate: 9.552711457006377e-08
train_loss: 1.0388098870453082, val_loss: 1.0537908269614769
epochs 52/65
Epoch 00052: reducing learning rate of group 0 to 1.8704e-08.
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0412399238661716, val_loss: 1.0537909023345462
epochs 53/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0406836512841677, val_loss: 1.0537909023345462
epochs 54/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0388664703620107, val_loss: 1.0537908786819095
epochs 55/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0408110483696587, val_loss: 1.0537908269614769
epochs 56/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.039609977759813, val_loss: 1.0537908190772647
epochs 57/65
Current Learning Rate: 1.870404940702393e-08
train_loss: 1.0416484986480914, val_loss: 1.0537908269614769
epochs 58/65
Epoch 00058: reducing learning rate of group 0 to 3.6622e-09.
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0409698291828757, val_loss: 1.0537908190772647
epochs 59/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0379764578844373, val_loss: 1.0537908190772647
epochs 60/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0396785990187996, val_loss: 1.0537908190772647
epochs 61/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0431971782132199, val_loss: 1.0537908190772647
epochs 62/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0406436506070589, val_loss: 1.0537908190772647
epochs 63/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0388598931463142, val_loss: 1.0537908190772647
epochs 64/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0408793333329653, val_loss: 1.0537908190772647
epochs 65/65
Current Learning Rate: 3.662221619431446e-09
train_loss: 1.0391625940799714, val_loss: 1.0537908111930525
Starting fold 3:
epochs 1/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.130263166917858, val_loss: 1.0571633372357283
epochs 2/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0557810617037942, val_loss: 1.043018190002946
epochs 3/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0499444058155134, val_loss: 1.0447934537968309
epochs 4/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.048600205428152, val_loss: 1.04424713843714
epochs 5/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.054119756435468, val_loss: 1.043624842293048
epochs 6/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0543991382805031, val_loss: 1.0445050212441298
epochs 7/65
Current Learning Rate: 0.008658921298170039
train_loss: 1.0494222382250487, val_loss: 1.0439445083103482
epochs 8/65
Epoch 00008: reducing learning rate of group 0 to 1.6954e-03.
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0507342748357038, val_loss: 1.0440944351216472
epochs 9/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0452390937478346, val_loss: 1.043184086443886
epochs 10/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0437595003099558, val_loss: 1.0431517387824083
epochs 11/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0466406410314497, val_loss: 1.043840559702071
epochs 12/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.0412681422250343, val_loss: 1.0444257987870111
epochs 13/65
Current Learning Rate: 0.0016954023211254634
train_loss: 1.045622051600203, val_loss: 1.0447277524483898
epochs 14/65
Epoch 00014: reducing learning rate of group 0 to 3.3196e-04.
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0482736858416526, val_loss: 1.0447285301470883
epochs 15/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0446073755438592, val_loss: 1.0446670323452623
epochs 16/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0455147172528956, val_loss: 1.0445975563513539
epochs 17/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0446345582997234, val_loss: 1.0445602605582545
epochs 18/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0438343293847014, val_loss: 1.0444903376871946
epochs 19/65
Current Learning Rate: 0.0003319569414593337
train_loss: 1.0447658393630244, val_loss: 1.044483761623423
epochs 20/65
Epoch 00020: reducing learning rate of group 0 to 6.4997e-05.
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0445349519198306, val_loss: 1.0445356369018555
epochs 21/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0446454773678302, val_loss: 1.0445390501350322
epochs 22/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.044022194740014, val_loss: 1.044537586509866
epochs 23/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0473630838947263, val_loss: 1.0445612372544708
epochs 24/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.047067116873964, val_loss: 1.044573563116568
epochs 25/65
Current Learning Rate: 6.499661443773662e-05
train_loss: 1.0443359469906517, val_loss: 1.0445660677536455
epochs 26/65

[I 2024-01-27 01:54:31,359] Trial 21 pruned.

Starting fold 1:
epochs 1/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.5451879844615597, val_loss: 1.2830597603762592
epochs 2/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.2194003584497262, val_loss: 1.142717758814494
epochs 3/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0735481721568483, val_loss: 1.1693899675651833
epochs 4/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0691916187396224, val_loss: 1.196016545648928
epochs 5/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0759466718004635, val_loss: 1.1546599555898596
epochs 6/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0665116959217331, val_loss: 1.1217284070120916
epochs 7/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.069168000945246, val_loss: 1.1269713993425723
epochs 8/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.069394436182152, val_loss: 1.145338318966053
epochs 9/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0661571444017102, val_loss: 1.147432106512564
epochs 10/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0666179307468275, val_loss: 1.1407496399349637
epochs 11/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0763547227020662, val_loss: 1.1308298420023035
epochs 12/77
Epoch 00012: reducing learning rate of group 0 to 2.5477e-03.
Current Learning Rate: 0.0025477456505632527
train_loss: 1.070343295941178, val_loss: 1.1323615533334237
epochs 13/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.065903261069852, val_loss: 1.1337699227862887
epochs 14/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.058844328550768, val_loss: 1.1362604609242193
epochs 15/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.060292687091528, val_loss: 1.1356032292048137
epochs 16/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.0563914894433546, val_loss: 1.1339144265210186
epochs 17/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.0590196361092372, val_loss: 1.13134941789839
epochs 18/77
Epoch 00018: reducing learning rate of group 0 to 5.4570e-04.
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0613603273611418, val_loss: 1.1277101790463482
epochs 19/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0664169495018365, val_loss: 1.1268640491697524
epochs 20/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0605641890570756, val_loss: 1.1264975953985144
epochs 21/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0636282965774935, val_loss: 1.126389220908836
epochs 22/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0604075031130726, val_loss: 1.126147985458374
epochs 23/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0525181611795076, val_loss: 1.1261717787495367
epochs 24/77
Epoch 00024: reducing learning rate of group 0 to 1.1688e-04.
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0647811952061679, val_loss: 1.1262264163405806
epochs 25/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0601164589377599, val_loss: 1.1262124644385443
epochs 26/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0564637858206065, val_loss: 1.1262393041893288
epochs 27/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0635014947172234, val_loss: 1.1262446686073586
epochs 28/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0643072228157084, val_loss: 1.126235052391335
epochs 29/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0624255503659472, val_loss: 1.126277106779593
epochs 30/77
Epoch 00030: reducing learning rate of group 0 to 2.5036e-05.
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0589814285957377, val_loss: 1.1263857505939625
epochs 31/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0628082246680535, val_loss: 1.1264027931072094
epochs 32/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.058953813857433, val_loss: 1.126411963392187
epochs 33/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.061611047589966, val_loss: 1.12642890435678
epochs 34/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0682987361678278, val_loss: 1.1264383130603366
epochs 35/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0625952900392224, val_loss: 1.1264407678886696
epochs 36/77
Epoch 00036: reducing learning rate of group 0 to 5.3624e-06.
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.060433604954425, val_loss: 1.1264340921684548
epochs 37/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.07048713848853, val_loss: 1.126432877999765
epochs 38/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.0631914925200776, val_loss: 1.1264298271249842
epochs 39/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.071910375699947, val_loss: 1.126423924057572
epochs 40/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.0631656353386285, val_loss: 1.1264195442199707
epochs 41/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.0638968370347748, val_loss: 1.1264140252713803
epochs 42/77
Epoch 00042: reducing learning rate of group 0 to 1.1486e-06.
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0606266172768557, val_loss: 1.1264104313320584
epochs 43/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0647846154517528, val_loss: 1.1264093407878168
epochs 44/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0662928488866197, val_loss: 1.1264086740988273
epochs 45/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0571449108772877, val_loss: 1.1264073495511655
epochs 46/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0641123880266519, val_loss: 1.1264063384797838
epochs 47/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0646875890761769, val_loss: 1.1264065592377275
epochs 48/77
Epoch 00048: reducing learning rate of group 0 to 2.4602e-07.
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0677928125671068, val_loss: 1.1264057203575417
epochs 49/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0602931508219056, val_loss: 1.1264054598631683
epochs 50/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0667423215836132, val_loss: 1.126405398050944
epochs 51/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0606377230888886, val_loss: 1.1264051772930004
epochs 52/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0662220142274628, val_loss: 1.126405124311094
epochs 53/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0643698794679493, val_loss: 1.1264050669140286
epochs 54/77
Epoch 00054: reducing learning rate of group 0 to 5.2694e-08.
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.055327050348851, val_loss: 1.126405261181019
epochs 55/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.0560696368442155, val_loss: 1.1264053362387199
epochs 56/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.0666833204748742, val_loss: 1.126405504014757
epochs 57/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.0576713497101948, val_loss: 1.126405746848495
epochs 58/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.0552364125925833, val_loss: 1.126405746848495
epochs 59/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.057483020877339, val_loss: 1.1264058219061956
epochs 60/77
Epoch 00060: reducing learning rate of group 0 to 1.1287e-08.
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0654635997342814, val_loss: 1.1264058969638966
epochs 61/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0635366764368188, val_loss: 1.1264058219061956
epochs 62/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.06268293944953, val_loss: 1.1264059278700087
epochs 63/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0648777665892197, val_loss: 1.1264058528123078
epochs 64/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0661547808122884, val_loss: 1.1264058219061956
epochs 65/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.066515226638754, val_loss: 1.1264059278700087
epochs 66/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0745391365121173, val_loss: 1.126405777754607
epochs 67/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0682541912138774, val_loss: 1.1264057336030182
epochs 68/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.056067741978231, val_loss: 1.126405777754607
epochs 69/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0596622615584528, val_loss: 1.126405777754607
epochs 70/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.066198002605538, val_loss: 1.1264057645091303
epochs 71/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0610499413225662, val_loss: 1.1264057336030182
epochs 72/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.057008366934292, val_loss: 1.126405777754607
epochs 73/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0661590093093394, val_loss: 1.1264057247727006
epochs 74/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0622429535651081, val_loss: 1.1264056585453175
epochs 75/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0528889906968122, val_loss: 1.1264058307365135
epochs 76/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.067279062346014, val_loss: 1.126405777754607
epochs 77/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0643274503228553, val_loss: 1.1264057556788127
Starting fold 2:
epochs 1/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.1556643184862638, val_loss: 1.0880676949465717
epochs 2/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0480969014920687, val_loss: 1.0592458292290017
epochs 3/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0912743885266154, val_loss: 1.0542341073354085
epochs 4/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0506471160211062, val_loss: 1.0531166284172624
epochs 5/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0483330299979763, val_loss: 1.053358874939106
epochs 6/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0544025490158482, val_loss: 1.0538183362395674
epochs 7/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0641697770670842, val_loss: 1.0536735653877258
epochs 8/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0535740115140613, val_loss: 1.0531137033745095
epochs 9/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0644893097250085, val_loss: 1.0534934136602614
epochs 10/77
Epoch 00010: reducing learning rate of group 0 to 2.5477e-03.
Current Learning Rate: 0.0025477456505632527
train_loss: 1.0552714984667928, val_loss: 1.053527593612671
epochs 11/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.049629420042038, val_loss: 1.053455889225006
epochs 12/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.0471551967294592, val_loss: 1.0536307471769828
epochs 13/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.0471860076251782, val_loss: 1.0539139619580022
epochs 14/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.0507174369535948, val_loss: 1.0540144001996075
epochs 15/77
Current Learning Rate: 0.0025477456505632527
train_loss: 1.0463994302247699, val_loss: 1.0541642021249842
epochs 16/77
Epoch 00016: reducing learning rate of group 0 to 5.4570e-04.
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0432606919815666, val_loss: 1.0544000753649958
epochs 17/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0468241478267468, val_loss: 1.0544358403594405
epochs 18/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0439350165818866, val_loss: 1.0544755348452814
epochs 19/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0488148849261434, val_loss: 1.0544880893495348
epochs 20/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0448414808825444, val_loss: 1.054491447077857
epochs 21/77
Current Learning Rate: 0.0005457040275880183
train_loss: 1.0500505096034, val_loss: 1.0544688326341134
epochs 22/77
Epoch 00022: reducing learning rate of group 0 to 1.1688e-04.
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0457953747950102, val_loss: 1.054462978133449
epochs 23/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0488432002694983, val_loss: 1.054460185545462
epochs 24/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0457015335559845, val_loss: 1.054455871935244
epochs 25/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.045326397607201, val_loss: 1.0544499556223552
epochs 26/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0517980001474683, val_loss: 1.0544481034632083
epochs 27/77
Current Learning Rate: 0.0001168848568772746
train_loss: 1.0473742155652297, val_loss: 1.054444842868381
epochs 28/77
Epoch 00028: reducing learning rate of group 0 to 2.5036e-05.
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0462083220481873, val_loss: 1.0544475272849754
epochs 29/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0528203280348527, val_loss: 1.0544459488656786
epochs 30/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0466980542007245, val_loss: 1.0544437854378312
epochs 31/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0438964994330155, val_loss: 1.0544426087979917
epochs 32/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0429227854076184, val_loss: 1.0544440348943074
epochs 33/77
Current Learning Rate: 2.5035676990706045e-05
train_loss: 1.0439474112109135, val_loss: 1.0544447700182598
epochs 34/77
Epoch 00034: reducing learning rate of group 0 to 5.3624e-06.
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.0422741049214412, val_loss: 1.0544453417813335
epochs 35/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.0454660120763277, val_loss: 1.0544452181568853
epochs 36/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.0454837444581484, val_loss: 1.0544457501835294
epochs 37/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.047691230711184, val_loss: 1.0544455073497914
epochs 38/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.046891549700185, val_loss: 1.0544454278769317
epochs 39/77
Current Learning Rate: 5.362415107724969e-06
train_loss: 1.047032903683813, val_loss: 1.0544454918967352
epochs 40/77
Epoch 00040: reducing learning rate of group 0 to 1.1486e-06.
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0414262006157322, val_loss: 1.054445297629745
epochs 41/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0494342054191388, val_loss: 1.0544454808588382
epochs 42/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0418892330244969, val_loss: 1.0544451695901376
epochs 43/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0505271240284568, val_loss: 1.0544451453067638
epochs 44/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.0460324146245654, val_loss: 1.0544453086676422
epochs 45/77
Current Learning Rate: 1.1485807153619953e-06
train_loss: 1.043999610762847, val_loss: 1.0544451276461284
epochs 46/77
Epoch 00046: reducing learning rate of group 0 to 2.4602e-07.
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0459575982470262, val_loss: 1.0544452601008945
epochs 47/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0492231108640369, val_loss: 1.0544451872507732
epochs 48/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0487848143828542, val_loss: 1.0544452667236328
epochs 49/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0483050958106392, val_loss: 1.0544452998373244
epochs 50/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.0447547090680975, val_loss: 1.0544452556857355
epochs 51/77
Current Learning Rate: 2.4601557939835915e-07
train_loss: 1.047317192742699, val_loss: 1.0544453616495486
epochs 52/77
Epoch 00052: reducing learning rate of group 0 to 5.2694e-08.
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.0457244797756797, val_loss: 1.0544452843842682
epochs 53/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.051814694153635, val_loss: 1.0544452247796234
epochs 54/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.041670952972613, val_loss: 1.054445343988913
epochs 55/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.0471537709236145, val_loss: 1.0544452843842682
epochs 56/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.0480335746940814, val_loss: 1.054445222572044
epochs 57/77
Current Learning Rate: 5.269430741542205e-08
train_loss: 1.044273095695596, val_loss: 1.0544453130828009
epochs 58/77
Epoch 00058: reducing learning rate of group 0 to 1.1287e-08.
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0429040052388843, val_loss: 1.054445222572044
epochs 59/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0486107970538892, val_loss: 1.054445176212876
epochs 60/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0426650721775859, val_loss: 1.054445176212876
epochs 61/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0454226951850087, val_loss: 1.054445176212876
epochs 62/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0479040443897247, val_loss: 1.0544452203644648
epochs 63/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.041124342303527, val_loss: 1.0544452645160534
epochs 64/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0413048063453876, val_loss: 1.0544451453067638
epochs 65/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.046512184958709, val_loss: 1.0544452203644648
epochs 66/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0476121510329999, val_loss: 1.0544452203644648
epochs 67/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0497615792249377, val_loss: 1.0544452203644648
epochs 68/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0522673255518864, val_loss: 1.0544452203644648
epochs 69/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0425361504680233, val_loss: 1.0544452203644648
epochs 70/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0465345084667206, val_loss: 1.0544452203644648
epochs 71/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0414273801602816, val_loss: 1.0544452203644648
epochs 72/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0492763205578453, val_loss: 1.0544452203644648
epochs 73/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0395205303242332, val_loss: 1.0544452490629974
epochs 74/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.049381417663474, val_loss: 1.0544453108752216
epochs 75/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0478945405859696, val_loss: 1.0544452490629974
epochs 76/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0453047109277624, val_loss: 1.0544452490629974
epochs 77/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0496465265750885, val_loss: 1.0544452490629974
Starting fold 3:
epochs 1/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.148171816328917, val_loss: 1.054993916440893
epochs 2/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0697500361080539, val_loss: 1.0675289498435125
epochs 3/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0672058126838428, val_loss: 1.0660327982019495
epochs 4/77
Current Learning Rate: 0.011894740686913872
train_loss: 1.0623002961566033, val_loss: 1.061128157156485
epochs 5/77
Current Learning Rate: 0.011894740686913872

[I 2024-01-27 01:55:06,641] Trial 22 finished with value: 1.1081558300073815 and parameters: {'batch_size': 70, 'epochs': 77, 'hidden_size': 86, 'learning_rate': 0.011894740686913872, 'dropout_prob': 0.1822609414798579, 'weight_decay': 0.0077881512506651224, 'lr_step_size': 5, 'gamma': 0.21419093678655665, 'conv_channels': 128, 'kernel_size': 4, 'num_layers': 3, 'pool_size': 3, 'stride': 3}. Best is trial 0 with value: 1.1064366340404437.

Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0358491208258753, val_loss: 1.2881981752536915
epochs 77/77
Current Learning Rate: 1.1286643068628048e-08
train_loss: 1.0320899059175817, val_loss: 1.2881981001959906
Mean validation loss: 1.1081558300073815
Starting fold 1:
epochs 1/89
Current Learning Rate: 0.09601613887467929
train_loss: 2.3586005184662904, val_loss: 6.558455618600997
epochs 2/89
Current Learning Rate: 0.09601613887467929
train_loss: 2.5104406060972764, val_loss: 1.3593076845956227
epochs 3/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.2296425965443956, val_loss: 1.280878012142484
epochs 4/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.47422551422219, val_loss: 1.2017664757985917
epochs 5/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.1868331813063298, val_loss: 1.190112342910161
epochs 6/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.1369965881577337, val_loss: 1.3421313403144715
epochs 7/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.1827258801585092, val_loss: 1.0988072412354606
epochs 8/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.1228386282296705, val_loss: 1.1636867693492345
epochs 9/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0767137121155623, val_loss: 1.2470857378036257
epochs 10/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.1357247386303249, val_loss: 1.1334446044195265
epochs 11/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0937681984526948, val_loss: 1.1123219122962347
epochs 12/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.105054408467877, val_loss: 1.1560878999649533
epochs 13/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0869802923102654, val_loss: 1.1679311385230413
epochs 14/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.102920643946263, val_loss: 1.1654014492791795
epochs 15/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.1021763061353673, val_loss: 1.130984742490072
epochs 16/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.081925015799038, val_loss: 1.1490227021868267
epochs 17/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0931182151065446, val_loss: 1.157774949830676
epochs 18/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0817647985138819, val_loss: 1.1779258203884913
epochs 19/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0926247435714562, val_loss: 1.1210376497298953
epochs 20/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0891524884089125, val_loss: 1.1259258720609877
epochs 21/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0777422969878032, val_loss: 1.1532297541224767
epochs 22/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0839948179834176, val_loss: 1.1517717232779852
epochs 23/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0767346564387776, val_loss: 1.1376050824210757
epochs 24/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0763515564783706, val_loss: 1.1483722518360804
epochs 25/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.0655091108451964, val_loss: 1.155515926224845
epochs 26/89
Epoch 00026: reducing learning rate of group 0 to 2.6705e-02.
Current Learning Rate: 0.026705344157019972
train_loss: 1.0820981576180584, val_loss: 1.1391831021460275
epochs 27/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0666669650851743, val_loss: 1.1270354759125483
epochs 28/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.066423584653445, val_loss: 1.12071255559013
epochs 29/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.064379561633964, val_loss: 1.1187038185104492
epochs 30/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0746825590183597, val_loss: 1.1187060011757746
epochs 31/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0671602793388966, val_loss: 1.1204506357510884
epochs 32/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0790097794607671, val_loss: 1.1189431254825895
epochs 33/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.072338093637796, val_loss: 1.1187214444554041
epochs 34/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0690885214281332, val_loss: 1.125963414472247
epochs 35/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0686078527210894, val_loss: 1.1337869138944716
epochs 36/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0826998555847487, val_loss: 1.1380252033945113
epochs 37/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0731057190770255, val_loss: 1.134683522913191
epochs 38/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0714203974339351, val_loss: 1.1342071417778257
epochs 39/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.068539987059788, val_loss: 1.129815930411929
epochs 40/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0672644258169603, val_loss: 1.127668387360043
epochs 41/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.068766992753713, val_loss: 1.131961154559302
epochs 42/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0675500431610028, val_loss: 1.134546352757348
epochs 43/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0739725672137674, val_loss: 1.132209058791872
epochs 44/89
Current Learning Rate: 0.026705344157019972
train_loss: 1.0646785940799413, val_loss: 1.1312290467913189
epochs 45/89
Epoch 00045: reducing learning rate of group 0 to 7.4277e-03.
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0775384921678073, val_loss: 1.1375396753114366
epochs 46/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0633761764196825, val_loss: 1.1427605946858723
epochs 47/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0588864693466906, val_loss: 1.1438056154856606
epochs 48/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.063911260734678, val_loss: 1.1380085926207284
epochs 49/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.062582400456773, val_loss: 1.1295648103668576
epochs 50/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.07324358306006, val_loss: 1.1254976212032257
epochs 51/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0616905189933576, val_loss: 1.1259340170830014
epochs 52/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0683212979301733, val_loss: 1.1254970970607938
epochs 53/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0606662946221717, val_loss: 1.1283972263336182
epochs 54/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0612584845557886, val_loss: 1.132629918673682
epochs 55/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0635780464292197, val_loss: 1.1361537064824785
epochs 56/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0721378569827653, val_loss: 1.1349903051815335
epochs 57/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0686586883055602, val_loss: 1.1331258009350489
epochs 58/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0716713180092616, val_loss: 1.127947037182157
epochs 59/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0686836298847697, val_loss: 1.119269227224683
epochs 60/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.067806899859643, val_loss: 1.1148722342082433
epochs 61/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.064699446967759, val_loss: 1.1146364041737147
epochs 62/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.061716097811754, val_loss: 1.1196155557556757
epochs 63/89
Current Learning Rate: 0.0074276617962707354
train_loss: 1.0586226516993258, val_loss: 1.130281634747036
epochs 64/89
Epoch 00064: reducing learning rate of group 0 to 2.0659e-03.
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0622308915822294, val_loss: 1.1425050402444505
epochs 65/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0645219380942939, val_loss: 1.143476647043985
epochs 66/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.069817152322899, val_loss: 1.1408137234430464
epochs 67/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0717538657612826, val_loss: 1.135809311791072
epochs 68/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0654046342010897, val_loss: 1.1306314165630038
epochs 69/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0684254562667528, val_loss: 1.126553350024753
epochs 70/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0624401918880602, val_loss: 1.1236717190061296
epochs 71/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0655918882779425, val_loss: 1.1207481187487405
epochs 72/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0649860953785362, val_loss: 1.1184338766431052
epochs 73/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0593605284915544, val_loss: 1.117313327297332
epochs 74/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.065836218639194, val_loss: 1.118041685649327
epochs 75/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0615097608865869, val_loss: 1.1204574316266984
epochs 76/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0581729480733422, val_loss: 1.1235257481771803
epochs 77/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0657722232229423, val_loss: 1.1269063514376443
epochs 78/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0584522385871846, val_loss: 1.129482178460984
epochs 79/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0585611983743637, val_loss: 1.132209236659701
epochs 80/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.063246140929417, val_loss: 1.1340713302294414
epochs 81/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0641547996960385, val_loss: 1.134670550861056
epochs 82/89
Current Learning Rate: 0.0020658846197747784
train_loss: 1.0689339356896765, val_loss: 1.1335213572259932
epochs 83/89
Epoch 00083: reducing learning rate of group 0 to 5.7459e-04.
Current Learning Rate: 0.0005745925675243841
train_loss: 1.0627094775594341, val_loss: 1.13206766711341
epochs 84/89
Current Learning Rate: 0.0005745925675243841
train_loss: 1.0721114705370358, val_loss: 1.1314276021624368
epochs 85/89
Current Learning Rate: 0.0005745925675243841
train_loss: 1.057001907788022, val_loss: 1.1307934532089838
epochs 86/89
Current Learning Rate: 0.0005745925675243841
train_loss: 1.0671205951281244, val_loss: 1.1302209799251859
epochs 87/89
Current Learning Rate: 0.0005745925675243841
train_loss: 1.065088255867284, val_loss: 1.1293850862790669
epochs 88/89
Current Learning Rate: 0.0005745925675243841
train_loss: 1.0575957903687243, val_loss: 1.1287836668983338
epochs 89/89
Current Learning Rate: 0.0005745925675243841
train_loss: 1.0586781657803122, val_loss: 1.1283312118242657
Starting fold 2:
epochs 1/89
Current Learning Rate: 0.09601613887467929
train_loss: 2.183926019229387, val_loss: 2.172772458621434
epochs 2/89
Current Learning Rate: 0.09601613887467929
train_loss: 1.845465739463505, val_loss: 1.124073552706885
epochs 3/89

[I 2024-01-27 01:55:11,417] Trial 23 pruned.

Starting fold 1:
epochs 1/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.634462999423761, val_loss: 1.557348955875982
epochs 2/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.5662862249693945, val_loss: 1.4871567853544123
epochs 3/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.4758615368947934, val_loss: 1.3642313316385581
epochs 4/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.3036876336442238, val_loss: 1.2418738035928636
epochs 5/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.1658230108740442, val_loss: 1.2198205517713354
epochs 6/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.1192327176089063, val_loss: 1.1509541897546678
epochs 7/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0733276018921618, val_loss: 1.0974090055183128
epochs 8/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0793044910380978, val_loss: 1.0833981699413724
epochs 9/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0824931304492251, val_loss: 1.0950354287233302
epochs 10/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0744300469053978, val_loss: 1.1154015928349168
epochs 11/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.066521724481233, val_loss: 1.1329740840921958
epochs 12/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.070887325945949, val_loss: 1.14293628205698
epochs 13/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0740294069519842, val_loss: 1.1420292034351005
epochs 14/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0726019031714396, val_loss: 1.1317354510070154
epochs 15/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0703377754900467, val_loss: 1.1175194379513858
epochs 16/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0566619803144046, val_loss: 1.108754245061723
epochs 17/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.083041375220134, val_loss: 1.1082688488026775
epochs 18/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.074881597963303, val_loss: 1.1087977886199951
epochs 19/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0654562686750402, val_loss: 1.109438561888599
epochs 20/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0829381593234877, val_loss: 1.11030652851024
epochs 21/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.072046784830343, val_loss: 1.1103618113452165
epochs 22/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0644328506829226, val_loss: 1.1109595059087036
epochs 23/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0787605246948322, val_loss: 1.1120559103274472
epochs 24/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.079893039783258, val_loss: 1.111228969992784
epochs 25/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0586989968234957, val_loss: 1.107081723591638
epochs 26/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0724119241325019, val_loss: 1.105063791628237
epochs 27/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0660466629797252, val_loss: 1.105705778434794
epochs 28/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0693916981132867, val_loss: 1.107637880971192
epochs 29/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0582187912226972, val_loss: 1.1039232204830836
epochs 30/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0531962317321937, val_loss: 1.0938912743613833
epochs 31/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.055698611973468, val_loss: 1.0831892824677563
epochs 32/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0448382674711536, val_loss: 1.0758990560259138
epochs 33/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0385216524463674, val_loss: 1.063123521981416
epochs 34/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.034612708690903, val_loss: 1.0684251974499415
epochs 35/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0232439821303203, val_loss: 1.068209932594703
epochs 36/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0045503540188854, val_loss: 1.0574082659665869
epochs 37/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.971750797401548, val_loss: 1.0523638927116596
epochs 38/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.9636904606644395, val_loss: 1.0991058374838854
epochs 39/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.9169976851702984, val_loss: 1.0127468402423556
epochs 40/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8946290955493588, val_loss: 0.9807555252912814
epochs 41/82
Current Learning Rate: 0.0007986509099890397
train_loss: 1.0022654246285323, val_loss: 1.3212785336075636
epochs 42/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.9968450237943239, val_loss: 1.2330587263460513
epochs 43/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.9363021320073392, val_loss: 0.9724192871618523
epochs 44/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8923942880480701, val_loss: 1.0779502678800512
epochs 45/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8888354544864275, val_loss: 1.0150719767525083
epochs 46/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8938421529000966, val_loss: 1.0454563779174966
epochs 47/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8733543229352742, val_loss: 1.4524580650228671
epochs 48/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8909371535815493, val_loss: 0.9886497123531564
epochs 49/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8437861538058176, val_loss: 1.093169988778533
epochs 50/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8517193338633832, val_loss: 1.2794804680284368
epochs 51/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.831501114430852, val_loss: 1.0203489412075628
epochs 52/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8188048538737273, val_loss: 1.097177819600181
epochs 53/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8230624994682392, val_loss: 1.2155456233907629
epochs 54/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8063121122839563, val_loss: 1.1303270172189783
epochs 55/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7950889833310512, val_loss: 1.2113056195476068
epochs 56/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7872011346342676, val_loss: 1.2156650868673173
epochs 57/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7717130015657835, val_loss: 1.3759649380174264
epochs 58/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7553193310168401, val_loss: 1.210260104250025
epochs 59/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7295568928668636, val_loss: 1.2006066148243253
epochs 60/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8091554126814398, val_loss: 1.5873840511160553
epochs 61/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8839212593607878, val_loss: 1.58464090155546
epochs 62/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7689026513024775, val_loss: 1.0162198073649533
epochs 63/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7471988316605852, val_loss: 1.3882429505151415
epochs 64/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7241476128238657, val_loss: 1.0846601074965543
epochs 65/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7343991255260887, val_loss: 1.0544037431005449
epochs 66/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.6863249596500895, val_loss: 1.2375546485658675
epochs 67/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7107919635572982, val_loss: 1.1016680241892578
epochs 68/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7680148997231928, val_loss: 1.3545028753381558
epochs 69/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7320189803682696, val_loss: 0.9742859207763874
epochs 70/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.6942586911286359, val_loss: 1.5833423213353233
epochs 71/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.683299163873283, val_loss: 1.3602770043428614
epochs 72/82
Epoch 00072: reducing learning rate of group 0 to 1.1749e-04.
Current Learning Rate: 0.0001174909804951115
train_loss: 0.723391986018076, val_loss: 1.0611823746766993
epochs 73/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6577183975599199, val_loss: 1.2353139743603097
epochs 74/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6491713292935756, val_loss: 1.291489699530223
epochs 75/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6187683069269071, val_loss: 1.2424178716366885
epochs 76/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6232443202228446, val_loss: 1.1873796484457753
epochs 77/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6331629528425127, val_loss: 1.1974857648213704
epochs 78/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6157814712112487, val_loss: 1.2610452774340513
epochs 79/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6071682999895506, val_loss: 1.3058248543865467
epochs 80/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6148022581769533, val_loss: 1.2478350886592158
epochs 81/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6002844355181249, val_loss: 1.1650872236837155
epochs 82/82
Current Learning Rate: 0.0001174909804951115
train_loss: 0.6159803739392945, val_loss: 1.1508017813087141
Starting fold 2:
epochs 1/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8720324045733402, val_loss: 1.8740523012857588
epochs 2/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.9895599064074064, val_loss: 1.8862007030103571
epochs 3/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.8126788631865852, val_loss: 1.8337751999103202
epochs 4/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7818117386416386, val_loss: 1.8080614836758406
epochs 5/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7956352494264903, val_loss: 1.8411728238302565
epochs 6/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7563486356484262, val_loss: 1.8219597869449191
epochs 7/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7661004891521053, val_loss: 1.8641737693201297
epochs 8/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7427961264785967, val_loss: 1.8602603099964283
epochs 9/82
Current Learning Rate: 0.0007986509099890397
train_loss: 0.7297464703258715, val_loss: 1.8623857775693218
epochs 10/82

[I 2024-01-27 01:55:16,271] Trial 24 pruned.

Number of finished trials: 25
Best trial:
Value: 1.1064366340404437
Params:
batch_size: 86
epochs: 84
hidden_size: 51
learning_rate: 0.04471910604647985
dropout_prob: 0.11405534453545046
weight_decay: 8.740781938907536e-05
lr_step_size: 72
gamma: 0.19123176285413301
conv_channels: 84
kernel_size: 5
num_layers: 5
pool_size: 4
stride: 1

In [35]:
trainer = ModelActioner(train_data, test_data, device, model_type)
model = trainer.train(trial.params)

epochs 1/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.2671875208616257
epochs 2/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.1721922186478761
epochs 3/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0769790239946944
epochs 4/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.092586436636851
epochs 5/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0823658549449813
epochs 6/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0773507148866923
epochs 7/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.08044808966593
epochs 8/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0801034945417458
epochs 9/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0775346573389752
epochs 10/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0788547486906321
epochs 11/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.078067997706608
epochs 12/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0796265081620553
epochs 13/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0770025391813736
epochs 14/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.08001581568953
epochs 15/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0805853319839693
epochs 16/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0801044346790918
epochs 17/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0754895379215899
epochs 18/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0782051922779687
epochs 19/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0807297560320774
epochs 20/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0768553718504772
epochs 21/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0751718264860166
epochs 22/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0774794745613152
epochs 23/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0768501129998287
epochs 24/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0738784446262977
epochs 25/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0769664624207456
epochs 26/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.075601297365108
epochs 27/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0750827209000857
epochs 28/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0727804231811577
epochs 29/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0773673008235407
epochs 30/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0752326788406976
epochs 31/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0756905721107
epochs 32/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0741110637154379
epochs 33/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0718828173170627
epochs 34/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0736238024604152
epochs 35/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0735421139799373
epochs 36/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.075390844907559
epochs 37/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.071576198641683
epochs 38/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0735261695275844
epochs 39/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.072578404570969
epochs 40/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0741130396933622
epochs 41/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0732708883957125
epochs 42/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0761959526530454
epochs 43/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0731720083826024
epochs 44/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0719650776033671
epochs 45/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0711224132650334
epochs 46/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0718405720003894
epochs 47/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0742671549530096
epochs 48/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0729080395589412
epochs 49/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0708992971291005
epochs 50/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.071778227850585
epochs 51/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.073298838356851
epochs 52/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0715625696408917
epochs 53/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0710570295931587
epochs 54/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0702984678283545
epochs 55/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0726288327238929
epochs 56/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0710797004506623
epochs 57/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.071192794492547
epochs 58/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0710386430293741
epochs 59/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0721448200269483
epochs 60/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0708695075041812
epochs 61/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.070717920195049
epochs 62/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.07319498146084
epochs 63/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0719082374388063
epochs 64/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0715715296461548
epochs 65/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0701857302600228
epochs 66/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0683280684998337
epochs 67/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0716087063643294
epochs 68/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0696038659399665
epochs 69/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0708017081651888
epochs 70/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0702186770422357
epochs 71/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0691783188934056
epochs 72/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0685455146389948
epochs 73/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.069184611276002
epochs 74/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0700819879560404
epochs 75/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0700344648999227
epochs 76/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0687922822757505
epochs 77/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0709400287186597
epochs 78/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0690069554347388
epochs 79/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0689114422445567
epochs 80/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0686241718874852
epochs 81/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0688657312535903
epochs 82/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0690021229461886
epochs 83/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0688512767074814
epochs 84/84
Current Learning Rate: 0.04471910604647985
train_loss: 1.0684055893773763

In [36]:
preds = trainer.test(trial.params)
y_true = y_test[time_step:]

accuracy = accuracy_score(y_true, preds)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Precision
precision = precision_score(y_true, preds, average='weighted', zero_division=0)
print(f'Precision: {precision:.4f}')

# Recall
recall = recall_score(y_true, preds, average='weighted')
print(f'Recall: {recall:.4f}')

# F1 Score
f1 = f1_score(y_true, preds, average='weighted')
print(f'F1 Score: {f1:.4f}')

test_loss: 1.0864957072345385
Accuracy: 47.41%
Precision: 0.2248
Recall: 0.4741
F1 Score: 0.3050

In [37]:
unique_elements = set(preds)
print(unique_elements)

{0}

In [38]:
signals = pd.DataFrame(preds, columns=['Signal'])
signals

     Signal
0         0
1         0
2         0
3         0
4         0
..      ...
246       0
247       0
248       0
249       0
250       0

[251 rows x 1 columns]

In [39]:
signals["Signal"].value_counts()

Signal
0    251
Name: count, dtype: int64

In [40]:
signals["Date"] = date_test
signals

     Signal       Date
0         0 2023-01-23
1         0 2023-01-24
2         0 2023-01-25
3         0 2023-01-26
4         0 2023-01-27
..      ...        ...
246       0 2024-01-16
247       0 2024-01-17
248       0 2024-01-18
249       0 2024-01-19
250       0 2024-01-22

[251 rows x 2 columns]

In [41]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325653
1    141.737762
2    141.071472
3    143.159821
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [42]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [48]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
strong_sell_signals = signals[signals['Signal'] == 1]
sell_signals = signals[signals['Signal'] == 2]
buy_signals = signals[signals['Signal'] == 3]
strong_buy_signals = signals[signals['Signal'] == 4]


# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]
# buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
# sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]

# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))

# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))

# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [44]:
price_signal = stock_data[stock_data['Date'].isin(signals['Date'])]["Adj Close"]
price_signal = price_signal.reset_index()
price_signal = price_signal.drop(columns=["index"])
result = pd.concat([price_signal,signals], axis=1)
result

      Adj Close  Signal       Date
0    140.325653       0 2023-01-23
1    141.737762       0 2023-01-24
2    141.071472       0 2023-01-25
3    143.159821       0 2023-01-26
4    145.118851       0 2023-01-27
..          ...     ...        ...
246  183.630005       0 2024-01-16
247  182.679993       0 2024-01-17
248  188.630005       0 2024-01-18
249  191.559998       0 2024-01-19
250  193.889999       0 2024-01-22

[251 rows x 3 columns]

In [45]:
price_signal

      Adj Close
0    140.325653
1    141.737762
2    141.071472
3    143.159821
4    145.118851
..          ...
246  183.630005
247  182.679993
248  188.630005
249  191.559998
250  193.889999

[251 rows x 1 columns]

In [46]:
sell_signals

Empty DataFrame
Columns: [Signal, Date]
Index: []

In [47]:
buy_prices

Series([], Name: Adj Close, dtype: float64)