In [217]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm

In [218]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [219]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722874  43.075001  42.314999  102223600
1  2018-01-03  40.715782  43.637501  42.990002  118071600
2  2018-01-04  40.904903  43.367500  43.020000   89738400
3  2018-01-05  41.370617  43.842499  43.262501   94640000
4  2018-01-08  41.216972  43.902500  43.482498   82271200
5  2018-01-09  41.212234  43.764999  43.352501   86336000
6  2018-01-10  41.202774  43.575001  43.250000   95839600
7  2018-01-11  41.436810  43.872501  43.622501   74670800
8  2018-01-12  41.864704  44.340000  43.912498  101672400
9  2018-01-16  41.651939  44.847500  44.035000  118263600
10 2018-01-17  42.339878  44.812500  43.767502  137547200
11 2018-01-18  42.377705  45.025002  44.562500  124773600
12 2018-01-19  42.188572  44.895000  44.352501  129700400
13 2018-01-22  41.843422  44.445000  44.150002  108434400
14 2018-01-23  41.852871  44.860001  44.205002  130756400
15 2018-01-24  41.186222  44.325001  43.299999  204420400
16 2018-01-25  40.451012  43.737499  42.632500  166116000
17 2018-01-26  40.545570  43.000000  42.514999  156572000
18 2018-01-29  39.706329  42.540001  41.767502  202561600
19 2018-01-30  39.472305  41.842499  41.174999  184192800
20 2018-01-31  39.581043  42.110001  41.625000  129915600
21 2018-02-01  39.663780  42.154999  41.689999  188923200
22 2018-02-02  37.942764  41.700001  40.025002  346375200
23 2018-02-05  36.994797  40.970001  39.000000  290954000
24 2018-02-06  38.540874  40.930000  38.500000  272975200
25 2018-02-07  37.715828  40.849998  39.767502  206434400
26 2018-02-08  36.678020  40.250000  38.757500  217562000
27 2018-02-09  37.126640  39.472500  37.560001  282690400
28 2018-02-12  38.622055  40.972500  39.377499  243278000
29 2018-02-13  39.008949  41.187500  40.412498  130196800
30 2018-02-14  39.728172  41.884998  40.720001  162579600
31 2018-02-15  41.062195  43.272499  42.250000  204588800
32 2018-02-16  40.929237  43.705002  42.942501  160704400
33 2018-02-20  40.791584  43.564999  42.855000  135722000
34 2018-02-21  40.606430  43.529999  42.752499  149886400
35 2018-02-22  40.945873  43.487499  42.927502  123967600
36 2018-02-23  41.657978  43.912498  43.384998  135249600
37 2018-02-26  42.481640  44.847500  44.052502  152648800
38 2018-02-27  42.343960  45.119999  44.540001  155712400
39 2018-02-28  42.279888  45.154999  44.512501  151128400
40 2018-03-01  41.539291  44.945000  43.165001  195208000
41 2018-03-02  41.826511  44.075001  43.112499  153816000
42 2018-03-05  41.971302  44.435001  43.630001  113605600
43 2018-03-06  41.935692  44.562500  44.032501   95154000
44 2018-03-07  41.546417  43.962502  43.567501  126814000

In [220]:
time_step = 44

In [221]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [222]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [223]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma = talib.SMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA': sma,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [224]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724166,117105600.0
15,NaN,NaN,55.580714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706163,-87314800.0
16,NaN,NaN,45.152421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695100,-253430800.0
17,NaN,NaN,46.541666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.818108,2.684663,-96858800.0
18,NaN,NaN,37.470200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639374,-81.393431,2.635361,-299420400.0
19,NaN,NaN,35.398265,NaN,NaN,42.761509,41.213175,39.664841,NaN,NaN,-61.987903,-75.553944,2.599704,-483613200.0
20,NaN,NaN,37.137612,NaN,NaN,42.849893,41.156083,39.462273,NaN,NaN,-49.633966,-63.087081,2.602418,-353697600.0
21,NaN,NaN,38.494546,NaN,NaN,42.910289,41.103483,39.296678,NaN,NaN,-41.626546,-51.082805,2.600385,-164774400.0
22,NaN,NaN,25.947657,NaN,NaN,43.228468,40.955376,38.682285,NaN,NaN,-40.766198,-44.008904,2.560087,-511149600.0
23,NaN,NaN,21.743657,NaN,NaN,43.578806,40.736585,37.894364,NaN,NaN,-38.059512,-40.150752,2.593455,-802103600.0
24,NaN,NaN,39.079674,NaN,NaN,43.590201,40.602780,37.615360,NaN,NaN,-24.766563,-34.530758,2.689294,-529128400.0
25,NaN,NaN,34.666315,NaN,NaN,43.652095,40.427960,37.203826,NaN,NaN,-14.972404,-25.932826,2.662139,-735562800.0
26,NaN,NaN,30.066648,NaN,NaN,43.790963,40.201722,36.612481,NaN,NaN,-13.427771,-17.722246,2.652999,-953124800.0
27,NaN,NaN,34.135011,NaN,NaN,43.765501,39.986214,36.206926,NaN,NaN,-15.615398,-14.671858,2.663105,-670434400.0
28,NaN,NaN,45.513663,NaN,NaN,43.544875,39.824081,36.103288,NaN,NaN,-6.294895,-11.779355,2.747587,-427156400.0
29,NaN,NaN,48.015865,NaN,NaN,43.330493,39.691932,36.053371,NaN,NaN,11.072682,-3.612537,2.734577,-296959600.0
30,NaN,NaN,52.392737,NaN,NaN,42.991923,39.561347,36.130770,NaN,NaN,26.336864,10.371550,2.744682,-134380000.0
31,NaN,NaN,59.246678,NaN,NaN,42.753743,39.495571,36.237399,NaN,NaN,41.539639,26.316395,2.801800,70208800.0
32,NaN,NaN,58.345095,NaN,NaN,42.524603,39.432604,36.340606,NaN,NaN,51.997520,39.958008,2.790443,-90495600.0
33,-0.373865,-0.940885,57.371680,NaN,NaN,42.339125,39.380013,36.420900,NaN,NaN,56.241759,49.926306,2.779394,-226217600.0
34,-0.274211,-0.807551,56.017890,NaN,NaN,42.113871,39.317690,36.521510,NaN,NaN,52.331145,53.523475,2.776467,-376104000.0
35,-0.165932,-0.679227,57.975711,NaN,NaN,42.071530,39.305673,36.539816,NaN,NaN,52.421386,53.664763,2.783939,-252136400.0
36,-0.022400,-0.547861,61.815806,NaN,NaN,42.278014,39.366021,36.454028,NaN,NaN,56.395015,53.715849,2.796988,-116886800.0
37,0.156014,-0.407086,65.717908,NaN,NaN,42.641719,39.462825,36.283931,NaN,NaN,62.381560,57.065987,2.825026,35762000.0
38,0.283036,-0.269062,64.530804,NaN,NaN,43.012911,39.594706,36.176501,NaN,NaN,65.108318,61.294964,2.811693,-119950400.0
39,0.374218,-0.140406,63.951858,NaN,NaN,43.346781,39.735085,36.123390,NaN,NaN,64.319978,63.936619,2.811646,-271078800.0
40,0.382313,-0.035862,57.527272,NaN,NaN,43.527897,39.832998,36.138098,NaN,NaN,59.272713,62.900337,2.801179,-466286800.0
41,0.407211,0.052752,59.237562,NaN,NaN,43.735156,39.941134,36.147113,NaN,NaN,52.309014,58.633902,2.782217,-312470800.0
42,0.433627,0.128927,60.109606,NaN,NaN,43.918529,40.142561,36.366594,NaN,NaN,42.550392,51.377373,2.769808,-198865200.0
43,0.446542,0.192450,59.770928,NaN,NaN,43.949829,40.389606,36.829384,40.596318,40.596318,34.222971,43.027459,2.757050,-294019200.0
44,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-420833200.0

In [225]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722874
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715782
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904903
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370617
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216972
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212234
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202774
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436810
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864704
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651939
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339878
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377705
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188572
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843422
14,NaN,NaN,68.998186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724166,117105600.0,41.852871
15,NaN,NaN,55.580714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706163,-87314800.0,41.186222
16,NaN,NaN,45.152421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695100,-253430800.0,40.451012
17,NaN,NaN,46.541666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.818108,2.684663,-96858800.0,40.545570
18,NaN,NaN,37.470200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639374,-81.393431,2.635361,-299420400.0,39.706329
19,NaN,NaN,35.398265,NaN,NaN,42.761509,41.213175,39.664841,NaN,NaN,-61.987903,-75.553944,2.599704,-483613200.0,39.472305
20,NaN,NaN,37.137612,NaN,NaN,42.849893,41.156083,39.462273,NaN,NaN,-49.633966,-63.087081,2.602418,-353697600.0,39.581043
21,NaN,NaN,38.494546,NaN,NaN,42.910289,41.103483,39.296678,NaN,NaN,-41.626546,-51.082805,2.600385,-164774400.0,39.663780
22,NaN,NaN,25.947657,NaN,NaN,43.228468,40.955376,38.682285,NaN,NaN,-40.766198,-44.008904,2.560087,-511149600.0,37.942764
23,NaN,NaN,21.743657,NaN,NaN,43.578806,40.736585,37.894364,NaN,NaN,-38.059512,-40.150752,2.593455,-802103600.0,36.994797
24,NaN,NaN,39.079674,NaN,NaN,43.590201,40.602780,37.615360,NaN,NaN,-24.766563,-34.530758,2.689294,-529128400.0,38.540874
25,NaN,NaN,34.666315,NaN,NaN,43.652095,40.427960,37.203826,NaN,NaN,-14.972404,-25.932826,2.662139,-735562800.0,37.715828
26,NaN,NaN,30.066648,NaN,NaN,43.790963,40.201722,36.612481,NaN,NaN,-13.427771,-17.722246,2.652999,-953124800.0,36.678020
27,NaN,NaN,34.135011,NaN,NaN,43.765501,39.986214,36.206926,NaN,NaN,-15.615398,-14.671858,2.663105,-670434400.0,37.126640
28,NaN,NaN,45.513663,NaN,NaN,43.544875,39.824081,36.103288,NaN,NaN,-6.294895,-11.779355,2.747587,-427156400.0,38.622055
29,NaN,NaN,48.015865,NaN,NaN,43.330493,39.691932,36.053371,NaN,NaN,11.072682,-3.612537,2.734577,-296959600.0,39.008949
30,NaN,NaN,52.392737,NaN,NaN,42.991923,39.561347,36.130770,NaN,NaN,26.336864,10.371550,2.744682,-134380000.0,39.728172
31,NaN,NaN,59.246678,NaN,NaN,42.753743,39.495571,36.237399,NaN,NaN,41.539639,26.316395,2.801800,70208800.0,41.062195
32,NaN,NaN,58.345095,NaN,NaN,42.524603,39.432604,36.340606,NaN,NaN,51.997520,39.958008,2.790443,-90495600.0,40.929237
33,-0.373865,-0.940885,57.371680,NaN,NaN,42.339125,39.380013,36.420900,NaN,NaN,56.241759,49.926306,2.779394,-226217600.0,40.791584
34,-0.274211,-0.807551,56.017890,NaN,NaN,42.113871,39.317690,36.521510,NaN,NaN,52.331145,53.523475,2.776467,-376104000.0,40.606430
35,-0.165932,-0.679227,57.975711,NaN,NaN,42.071530,39.305673,36.539816,NaN,NaN,52.421386,53.664763,2.783939,-252136400.0,40.945873
36,-0.022400,-0.547861,61.815806,NaN,NaN,42.278014,39.366021,36.454028,NaN,NaN,56.395015,53.715849,2.796988,-116886800.0,41.657978
37,0.156014,-0.407086,65.717908,NaN,NaN,42.641719,39.462825,36.283931,NaN,NaN,62.381560,57.065987,2.825026,35762000.0,42.481640
38,0.283036,-0.269062,64.530804,NaN,NaN,43.012911,39.594706,36.176501,NaN,NaN,65.108318,61.294964,2.811693,-119950400.0,42.343960
39,0.374218,-0.140406,63.951858,NaN,NaN,43.346781,39.735085,36.123390,NaN,NaN,64.319978,63.936619,2.811646,-271078800.0,42.279888
40,0.382313,-0.035862,57.527272,NaN,NaN,43.527897,39.832998,36.138098,NaN,NaN,59.272713,62.900337,2.801179,-466286800.0,41.539291
41,0.407211,0.052752,59.237562,NaN,NaN,43.735156,39.941134,36.147113,NaN,NaN,52.309014,58.633902,2.782217,-312470800.0,41.826511
42,0.433627,0.128927,60.109606,NaN,NaN,43.918529,40.142561,36.366594,NaN,NaN,42.550392,51.377373,2.769808,-198865200.0,41.971302
43,0.446542,0.192450,59.770928,NaN,NaN,43.949829,40.389606,36.829384,40.596318,40.596318,34.222971,43.027459,2.757050,-294019200.0,41.935692
44,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-420833200.0,41.546417

In [226]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [227]:
indicators_with_price['Next_Adj_Close'] = indicators_with_price['Adj Close'].shift(-1)
indicators_with_price['Return'] = ((indicators_with_price['Next_Adj_Close'] - indicators_with_price['Adj Close'])/indicators_with_price['Adj Close'])*100
indicators_with_price['Signal'] = np.where(indicators_with_price['Return'] > 1, 1,
                                           np.where(indicators_with_price['Return'] < -1, 2, 0))
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Next_Adj_Close,Return,Signal
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417,41.999790,1.091244,1
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790,42.721375,1.718066,1
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375,43.134396,0.966779,0
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396,42.719009,-0.963005,0
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009,42.355839,-0.850138,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,188.630005,3.257068,1
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,191.559998,1.553301,1
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,193.889999,1.216330,1
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,195.179993,0.665322,0
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,NaN,NaN,0

In [228]:
indicators_with_price["Signal"].value_counts()

Signal
0    740
1    416
2    324
Name: count, dtype: int64

In [229]:
indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close', 'Return'])
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Signal
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417,1
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790,1
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375,0
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396,0
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,1
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,1
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,1
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,0
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,0

In [230]:
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Signal
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417,1
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790,1
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375,0
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396,0
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009,0
5,0.567013,0.443928,58.241621,7.100861,1.143604,43.382885,41.728829,40.074773,40.785715,41.035718,-7.013504,-3.909818,2.715225,-3.124152e+08,42.355839,0
6,0.548495,0.464842,58.592215,7.332888,1.202911,43.261029,41.862705,40.464380,40.813054,41.096606,-20.016654,-8.448451,2.714435,-2.214400e+08,42.405685,0
7,0.515805,0.475034,57.044806,6.516173,0.819328,43.280287,41.922402,40.564517,40.831675,41.148141,-27.991976,-18.340711,2.690141,-3.790588e+08,42.256138,2
8,0.432812,0.466590,50.806350,3.052092,-0.254204,43.245415,41.956465,40.667515,40.825897,41.168690,-36.985499,-28.331377,2.648799,-5.128460e+08,41.610500,0
9,0.361721,0.445616,50.674822,2.976570,-0.055668,43.183913,41.996699,40.809486,40.824632,41.187694,-46.752180,-37.243219,2.644564,-5.914436e+08,41.596272,2
10,0.226728,0.401838,42.776479,-1.895759,-1.685963,43.175295,41.999074,40.822852,40.786315,41.163970,-59.960215,-47.899298,2.611111,-7.396632e+08,40.653915,2
11,0.072555,0.335982,38.805883,-4.708101,-2.298229,43.330932,41.955754,40.580575,40.734082,41.115770,-60.364759,-55.692385,2.604323,-9.056264e+08,40.079475,2
12,-0.123099,0.244166,33.409966,-9.019960,-3.037205,43.669843,41.830423,39.991003,40.665055,41.028464,-57.038039,-59.121004,2.589766,-1.069742e+09,39.151367,1
13,-0.126722,0.169988,48.771960,0.230787,-0.833454,43.603897,41.756840,39.909782,40.646113,41.027642,-35.113454,-50.838751,2.699328,-9.195768e+08,41.009968,2
14,-0.212000,0.093590,42.761440,-4.462381,-1.894436,43.620648,41.637563,39.654479,40.603057,40.980121,-25.755979,-39.302491,2.704914,-1.083267e+09,39.958435,2
15,-0.311617,0.012549,40.504349,-6.346439,-1.669300,43.661172,41.499415,39.337658,40.565119,40.915090,-23.129866,-27.999766,2.693604,-1.249941e+09,39.516922,0
16,-0.361498,-0.062260,42.777711,-4.867444,-0.625511,43.694932,41.413725,39.132519,40.550903,40.866664,-31.638972,-26.841606,2.745530,-1.096347e+09,39.825500,0
17,-0.417287,-0.133266,41.338349,-5.999343,-0.981174,43.709490,41.300620,38.891750,40.528603,40.808785,-33.350038,-29.372959,2.721528,-1.246694e+09,39.564396,1
18,-0.423861,-0.191385,44.466611,-4.030393,0.263973,43.655483,41.200570,38.745656,40.534603,40.771519,-30.537715,-31.842242,2.714498,-1.125582e+09,39.970303,1
19,-0.363211,-0.225750,49.885880,-0.435786,1.262314,43.579269,41.140516,38.701763,40.563292,40.769879,-23.649205,-29.178986,2.737191,-9.871604e+08,40.734619,0
20,-0.289020,-0.238404,51.759458,0.859645,1.436039,43.546088,41.114049,38.682011,40.595929,40.780866,-13.681338,-22.622753,2.743311,-8.794276e+08,41.017082,2
21,-0.311294,-0.252982,45.026021,-3.853599,0.304150,43.457724,41.012456,38.567188,40.602841,40.744736,-15.941607,-17.757384,2.697569,-1.019449e+09,39.967930,0
22,-0.293575,-0.261101,47.789675,-2.010589,2.421566,43.223491,40.894604,38.565718,40.657877,40.727829,-20.848976,-16.823974,2.740926,-9.033780e+08,40.364330,1
23,-0.215755,-0.252031,52.696869,1.419560,4.129101,42.889425,40.794079,38.698733,40.751720,40.745432,-19.855179,-18.881921,2.769122,-7.897436e+08,41.123898,0
24,-0.167663,-0.235158,51.380455,0.543890,2.390759,42.607666,40.704710,38.801755,40.806056,40.753707,-10.385155,-17.029770,2.739621,-8.794700e+08,40.931633,0
25,-0.095884,-0.207303,53.978925,2.354496,3.619328,42.427110,40.653676,38.880242,40.888313,40.779550,0.476718,-9.921205,2.745245,-7.879128e+08,41.335155,0
26,-0.027382,-0.171319,54.880251,2.981765,4.797188,42.237332,40.607152,38.976972,40.997340,40.810468,4.591612,-1.772275,2.736645,-6.874156e+08,41.475208,0
27,0.047239,-0.127607,56.572359,4.145755,4.607296,42.118852,40.581042,39.043233,41.102051,40.851511,13.924978,6.331103,2.724906,-6.011020e+08,41.733936,1
28,0.150988,-0.071888,60.146018,6.689115,3.686314,42.272668,40.615936,38.959203,41.185831,40.916260,22.180899,13.565830,2.744631,-4.946804e+08,42.308369,0
29,0.222977,-0.012915,59.277650,6.212424,3.204464,42.395829,40.646793,38.897756,41.258660,40.973911,28.084392,21.396756,2.719774,-5.776984e+08,42.213413,2
30,0.181405,0.025949,49.567801,0.427657,1.288910,42.421431,40.664951,38.908471,41.287953,40.975830,20.146169,23.470487,2.642225,-7.169336e+08,41.017082,2
31,0.012703,0.023300,39.723960,-6.863875,-1.725685,42.461950,40.627803,38.793655,41.248733,40.902971,-8.291094,13.313156,2.581203,-9.788980e+08,39.336510,0
32,-0.128702,-0.007101,39.156301,-7.330558,-1.706646,42.454273,40.631364,38.808455,41.209946,40.828288,-34.550127,-7.565017,2.567795,-1.124960e+09,39.222591,2
33,-0.281575,-0.061996,36.466798,-9.553036,-2.114937,42.515715,40.514698,38.513681,41.161879,40.732659,-45.877296,-29.572839,2.552946,-1.259728e+09,38.676647,0
34,-0.384693,-0.126535,37.885194,-8.729317,-1.761246,42.577347,40.459035,38.340723,41.121851,40.648772,-39.397567,-39.941663,2.561904,-1.146200e+09,38.845184,0
35,-0.450307,-0.191289,39.061346,-8.061895,-1.965393,42.610304,40.432213,38.254123,41.077183,40.574625,-33.203077,-39.492646,2.563719,-1.034348e+09,38.980480,2
36,-0.532560,-0.259544,36.575172,-9.947394,-3.128498,42.686408,40.367412,38.048417,41.006080,40.483730,-32.805853,-35.135499,2.530740,-1.176971e+09,38.529480,1
37,-0.535264,-0.314688,42.657091,-6.489484,-3.254299,42.697385,40.350560,38.003734,40.932119,40.427890,-28.594961,-31.534630,2.584653,-1.007261e+09,39.227341,1
38,-0.458571,-0.343464,49.472278,-2.193921,-2.205132,42.701496,40.358986,38.016476,40.882002,40.415043,-18.764646,-26.721820,2.619511,-7.929836e+08,40.138828,1
39,-0.251812,-0.325134,59.544954,5.401815,-0.367931,42.852522,40.417853,37.983183,40.873640,40.481573,5.866537,-13.831023,2.739451,-5.268260e+08,41.911957,0
40,-0.080893,-0.276286,59.913619,5.709024,0.448624,42.984210,40.466394,37.948579,40.883836,40.548521,25.969029,4.356973,2.719707,-3.905532e+08,41.987915,1
41,0.185352,-0.183958,66.948284,12.047562,1.808735,43.506950,40.649760,37.792571,40.924944,40.685709,45.736650,25.857405,2.816484,-1.657480e+08,43.635246,0
42,0.417019,-0.063763,68.103514,13.191910,1.979645,44.022548,40.829091,37.635634,40.969936,40.830831,51.666068,41.123916,2.849753,4.057600e+06,43.950947,0
43,0.610626,0.071115,68.887189,13.958459,2.226513,44.489624,40.981006,37.472388,41.020538,40.978892,58.084066,51.828928,2.832203,1.176688e+08,44.162205,0
44,0.780158,0.212924,70.053471,15.087770,2.926739,44.982153,41.158083,37.334013,41.087055,41.134192,59.732775,56.494303,2.821888,2.105136e+08,44.473156,1
45,0.954837,0.361306,72.337954,17.358382,3.109497,45.541691,41.346789,37.151887,41.157726,41.310863,63.227766,60.348202,2.843135,3.224708e+08,45.109287,0
46,1.067127,0.502470,70.769975,16.498689,2.216354,45.997971,41.519915,37.041859,41.208097,41.472057,64.911903,62.624148,2.811891,2.176220e+08,44.937729,0
47,1.134580,0.628892,69.774677,15.967504,1.698498,46.380493,41.674863,36.969233,41.246700,41.621428,64.592740,64.244136,2.785668,1.345068e+08,44.832893,0
48,1.141993,0.731513,65.895629,13.902027,1.706421,46.631591,41.780716,36.929841,41.285482,41.746050,61.526803,63.677148,2.724878,3.972600e+07,44.425430,0
49,1.167862,0.818782,67.853972,15.469610,2.484200,46.941604,41.912047,36.882490,41.341941,41.883561,61.088827,62.402790,2.722356,1.164584e+08,44.840038,0

In [231]:
y = indicators_with_price["Adj Close"]
y_2 = indicators_with_price["SMA"]
y_3 = indicators_with_price["EMA"]
y_4 = indicators_with_price["Upper_BB"]
y_5 = indicators_with_price["Middle_BB"]
y_6 = indicators_with_price["Lower_BB"]
X = np.array(date)

trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



layout = go.Layout(
    title='Stock Price and Volume',
    xaxis=dict(title='Date'),
    yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
    yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
    height=600,
)

fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# Show plot
pyo.iplot(fig)

In [232]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        # Extract a window of data from X
        X_window = self.X[idx : idx + self.window_size]
        
        # Assuming you're predicting the value right after the window
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [233]:
X = indicators_with_price.iloc[:, :-1]
y = indicators_with_price.iloc[:,-1]

signal_true = indicators_with_price.iloc[:,-1]
y

0       1
1       1
2       0
3       0
4       0
       ..
1475    1
1476    1
1477    1
1478    0
1479    0
Name: Signal, Length: 1480, dtype: int64

In [234]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1184    1
1185    0
1186    2
1187    1
1188    0
       ..
1475    1
1476    1
1477    1
1478    0
1479    0
Name: Signal, Length: 296, dtype: int64

In [235]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
# X_train = X_train.to_numpy()
# y_train = y_train.to_numpy()
y_test.head(44)

1184    1
1185    0
1186    2
1187    1
1188    0
1189    2
1190    2
1191    2
1192    1
1193    0
1194    0
1195    0
1196    2
1197    2
1198    1
1199    0
1200    1
1201    0
1202    2
1203    2
1204    2
1205    2
1206    0
1207    1
1208    2
1209    0
1210    2
1211    2
1212    1
1213    0
1214    2
1215    1
1216    2
1217    1
1218    0
1219    0
1220    1
1221    0
1222    1
1223    0
1224    0
1225    0
1226    1
1227    1
Name: Signal, dtype: int64

In [236]:
# # Get the count of each unique value in the series
# category_counts = y_train.value_counts()
# print(category_counts.index)
# print(category_counts.values)

# # Create bar plot
# plt.bar(["1","0"], category_counts.values)

# # Adding labels and title
# plt.xlabel('Category')
# plt.ylabel('Frequency')
# plt.title('Distribution of Categories')

# # Show plot
# plt.show()

In [237]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

for column in X_train.columns:
    # Initialize a scaler
    scaler = MinMaxScaler()
    
    # Fit on the training data and transform it
    X_train_scaled = scaler.fit_transform(X_train[column].to_numpy().reshape(-1, 1))
    X_train_df[column] = X_train_scaled.flatten()
    
    # Transform the test data using the same scaler
    X_test_scaled = scaler.transform(X_test[column].to_numpy().reshape(-1, 1))
    X_test_df[column] = X_test_scaled.flatten()

    scaler_dict[column] = scaler

    

X_train_df.head(24)

features = X_train_df.columns
X_test_df

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.473178,0.391410,0.484405,0.368317,0.443981,0.810260,0.788953,0.749683,0.804887,0.832500,0.850519,0.839325,0.765326,0.761787,0.780636
1,0.499847,0.411144,0.517394,0.387563,0.487569,0.813419,0.791684,0.751875,0.804933,0.833706,0.876575,0.853920,0.764804,0.775662,0.793797
2,0.523637,0.432238,0.527280,0.393264,0.448749,0.816205,0.793223,0.752021,0.804433,0.835055,0.895160,0.867699,0.724522,0.788577,0.797684
3,0.523008,0.448973,0.456306,0.359879,0.379729,0.815520,0.792793,0.751879,0.802963,0.835217,0.907286,0.887937,0.685712,0.778442,0.775317
4,0.534244,0.464868,0.497611,0.382098,0.444492,0.813808,0.792104,0.752318,0.802403,0.836117,0.913913,0.901248,0.661728,0.787383,0.790114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,0.331987,0.360467,0.219193,0.330143,0.438975,1.105702,1.104494,1.078159,1.146372,1.152418,0.696648,0.699736,0.263755,0.912203,1.018693
292,0.358007,0.354748,0.456177,0.434230,0.530971,1.099583,1.101858,1.079371,1.147028,1.152792,0.728273,0.697238,0.316961,0.925666,1.059493
293,0.396417,0.358741,0.541661,0.480564,0.534505,1.093074,1.099905,1.082407,1.147733,1.154161,0.814260,0.731128,0.316624,0.937531,1.079584
294,0.440665,0.371807,0.601114,0.515679,0.555950,1.091863,1.099564,1.083019,1.148741,1.156274,0.926300,0.813002,0.323439,0.947909,1.095561
295,0.483036,0.391711,0.631898,0.534629,0.550954,1.092553,1.099746,1.082644,1.149678,1.158738,0.984412,0.904318,0.300461,0.955220,1.104406

In [238]:
scaler_dict

{'MACD': MinMaxScaler(),
 'MACD_signal': MinMaxScaler(),
 'RSI': MinMaxScaler(),
 'CMO': MinMaxScaler(),
 'MOM': MinMaxScaler(),
 'Upper_BB': MinMaxScaler(),
 'Middle_BB': MinMaxScaler(),
 'Lower_BB': MinMaxScaler(),
 'SMA': MinMaxScaler(),
 'EMA': MinMaxScaler(),
 'SLOWK': MinMaxScaler(),
 'SLOWD': MinMaxScaler(),
 'ATR': MinMaxScaler(),
 'OBV': MinMaxScaler(),
 'Adj Close': MinMaxScaler()}

In [239]:
correlation_matrix = X_train_df.corr()

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values,  # Rounded values for display
                    texttemplate="%{text}",
                    textfont={"size":9}  # Adjust text size if necessary
                    ))

# Update the layout
fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  # or any width you desire
    height=1000,  # or any height you desire
)

# Show the figure
pyo.iplot(fig)

In [240]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train.to_numpy(), dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test.to_numpy(), dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(0)[0])

tensor(1., device='cuda:0')
tensor([[0.4732, 0.3914, 0.4844, 0.3683, 0.4440, 0.8103, 0.7890, 0.7497, 0.8049,
         0.8325, 0.8505, 0.8393, 0.7653, 0.7618, 0.7806],
        [0.4998, 0.4111, 0.5174, 0.3876, 0.4876, 0.8134, 0.7917, 0.7519, 0.8049,
         0.8337, 0.8766, 0.8539, 0.7648, 0.7757, 0.7938],
        [0.5236, 0.4322, 0.5273, 0.3933, 0.4487, 0.8162, 0.7932, 0.7520, 0.8044,
         0.8351, 0.8952, 0.8677, 0.7245, 0.7886, 0.7977],
        [0.5230, 0.4490, 0.4563, 0.3599, 0.3797, 0.8155, 0.7928, 0.7519, 0.8030,
         0.8352, 0.9073, 0.8879, 0.6857, 0.7784, 0.7753],
        [0.5342, 0.4649, 0.4976, 0.3821, 0.4445, 0.8138, 0.7921, 0.7523, 0.8024,
         0.8361, 0.9139, 0.9012, 0.6617, 0.7874, 0.7901],
        [0.5474, 0.4805, 0.5145, 0.3912, 0.4671, 0.8153, 0.7928, 0.7521, 0.8022,
         0.8373, 0.9235, 0.9113, 0.6236, 0.7974, 0.7962],
        [0.5399, 0.4914, 0.4471, 0.3605, 0.4592, 0.8163, 0.7941, 0.7537, 0.8018,
         0.8374, 0.9237, 0.9172, 0.5981, 0.7914, 0.7760],
        [0.5112, 0.4936, 0.3677, 0.3216, 0.4080, 0.8078, 0.7900, 0.7546, 0.8007,
         0.8361, 0.8756, 0.9035, 0.5869, 0.7794, 0.7495],
        [0.4709, 0.4865, 0.3118, 0.2921, 0.3590, 0.8019, 0.7857, 0.7521, 0.7990,
         0.8339, 0.7960, 0.8581, 0.5854, 0.7650, 0.7287],
        [0.4782, 0.4824, 0.4544, 0.3639, 0.4654, 0.8000, 0.7849, 0.7524, 0.7987,
         0.8341, 0.7774, 0.8059, 0.6453, 0.7842, 0.7755],
        [0.4855, 0.4807, 0.4597, 0.3667, 0.5578, 0.8016, 0.7861, 0.7533, 0.7997,
         0.8344, 0.7888, 0.7750, 0.6088, 0.7965, 0.7774],
        [0.4882, 0.4800, 0.4490, 0.3617, 0.6035, 0.8012, 0.7895, 0.7605, 0.8014,
         0.8345, 0.8188, 0.7831, 0.5723, 0.7852, 0.7740],
        [0.4834, 0.4783, 0.4231, 0.3496, 0.5378, 0.7993, 0.7924, 0.7687, 0.8022,
         0.8343, 0.7983, 0.7906, 0.5827, 0.7733, 0.7659],
        [0.4583, 0.4714, 0.3463, 0.3124, 0.4486, 0.7969, 0.7939, 0.7742, 0.8017,
         0.8327, 0.7377, 0.7723, 0.5960, 0.7621, 0.7405],
        [0.4275, 0.4590, 0.3088, 0.2931, 0.4211, 0.7958, 0.7944, 0.7765, 0.8008,
         0.8305, 0.6628, 0.7167, 0.5765, 0.7501, 0.7271],
        [0.4137, 0.4460, 0.3519, 0.3121, 0.4535, 0.7862, 0.7972, 0.7927, 0.8003,
         0.8291, 0.6220, 0.6538, 0.5583, 0.7608, 0.7388],
        [0.4007, 0.4327, 0.3416, 0.3072, 0.5122, 0.7872, 0.7955, 0.7881, 0.8007,
         0.8275, 0.6178, 0.6111, 0.5622, 0.7477, 0.7354],
        [0.4045, 0.4229, 0.4019, 0.3333, 0.5364, 0.7852, 0.7936, 0.7864, 0.8015,
         0.8268, 0.6636, 0.6114, 0.5462, 0.7599, 0.7513],
        [0.4138, 0.4171, 0.4266, 0.3443, 0.5657, 0.7842, 0.7926, 0.7854, 0.8026,
         0.8264, 0.7016, 0.6398, 0.5764, 0.7761, 0.7580],
        [0.4089, 0.4114, 0.3718, 0.3205, 0.5461, 0.7816, 0.7901, 0.7831, 0.8035,
         0.8253, 0.7177, 0.6754, 0.5921, 0.7619, 0.7426],
        [0.3676, 0.3977, 0.2382, 0.2535, 0.4085, 0.7853, 0.7857, 0.7701, 0.8024,
         0.8220, 0.6670, 0.6766, 0.6206, 0.7448, 0.6968],
        [0.3250, 0.3771, 0.2052, 0.2347, 0.4402, 0.7869, 0.7798, 0.7563, 0.8018,
         0.8181, 0.6070, 0.6429, 0.6081, 0.7171, 0.6833],
        [0.2812, 0.3510, 0.1712, 0.2147, 0.3655, 0.7876, 0.7730, 0.7415, 0.8001,
         0.8136, 0.5756, 0.5922, 0.5959, 0.7034, 0.6687],
        [0.2486, 0.3227, 0.1700, 0.2140, 0.3484, 0.7892, 0.7673, 0.7281, 0.7982,
         0.8093, 0.5907, 0.5650, 0.5762, 0.6900, 0.6682],
        [0.2435, 0.2990, 0.2674, 0.2523, 0.3853, 0.7841, 0.7620, 0.7227, 0.7968,
         0.8063, 0.6254, 0.5716, 0.5879, 0.7049, 0.6897],
        [0.2238, 0.2756, 0.2091, 0.2214, 0.3520, 0.7784, 0.7552, 0.7149, 0.7950,
         0.8023, 0.6347, 0.5927, 0.5853, 0.6914, 0.6677],
        [0.2090, 0.2536, 0.2026, 0.2178, 0.3005, 0.7750, 0.7494, 0.7066, 0.7924,
         0.7984, 0.6337, 0.6080, 0.5572, 0.6804, 0.6652],
        [0.1900, 0.2318, 0.1704, 0.2003, 0.2520, 0.7754, 0.7442, 0.6956, 0.7891,
         0.7940, 0.6029, 0.6000, 0.5297, 0.6685, 0.6527],
        [0.1556, 0.2067, 0.1075, 0.1632, 0.1687, 0.7799, 0.7388, 0.6795, 0.7847,
         0.7885, 0.5879, 0.5833, 0.5433, 0.6538, 0.6255],
        [0.1525, 0.1859, 0.2212, 0.2082, 0.2481, 0.7734, 0.7321, 0.6728, 0.7814,
         0.7844, 0.5958, 0.5698, 0.5557, 0.6668, 0.6498],
        [0.1555, 0.1699, 0.2309, 0.2122, 0.3070, 0.7647, 0.7255, 0.6687, 0.7789,
         0.7806, 0.6128, 0.5733, 0.5256, 0.6801, 0.6520],
        [0.1339, 0.1523, 0.1491, 0.1668, 0.1158, 0.7577, 0.7173, 0.6593, 0.7737,
         0.7753, 0.6174, 0.5838, 0.5644, 0.6608, 0.6189],
        [0.1280, 0.1369, 0.1898, 0.1832, 0.1605, 0.7491, 0.7100, 0.6536, 0.7691,
         0.7707, 0.6084, 0.5883, 0.5617, 0.6761, 0.6277],
        [0.1197, 0.1227, 0.1673, 0.1708, 0.1768, 0.7445, 0.7035, 0.6454, 0.7648,
         0.7658, 0.5885, 0.5796, 0.5389, 0.6622, 0.6185],
        [0.1434, 0.1167, 0.3052, 0.2288, 0.3005, 0.7391, 0.6994, 0.6428, 0.7622,
         0.7627, 0.6410, 0.5880, 0.5646, 0.6773, 0.6499],
        [0.1686, 0.1175, 0.3198, 0.2353, 0.3813, 0.7308, 0.6949, 0.6425, 0.7608,
         0.7599, 0.6945, 0.6188, 0.5655, 0.6895, 0.6535],
        [0.1951, 0.1240, 0.3365, 0.2425, 0.3916, 0.7222, 0.6908, 0.6433, 0.7595,
         0.7575, 0.7638, 0.6813, 0.5445, 0.7006, 0.6575],
        [0.2347, 0.1381, 0.4132, 0.2767, 0.4185, 0.7093, 0.6868, 0.6492, 0.7585,
         0.7561, 0.8140, 0.7430, 0.5309, 0.7126, 0.6763],
        [0.2680, 0.1568, 0.4111, 0.2759, 0.4105, 0.6915, 0.6825, 0.6595, 0.7575,
         0.7548, 0.8756, 0.8075, 0.5074, 0.7002, 0.6758],
        [0.3040, 0.1797, 0.4490, 0.2927, 0.4830, 0.6765, 0.6794, 0.6695, 0.7575,
         0.7540, 0.9451, 0.8721, 0.4925, 0.7102, 0.6850],
        [0.3408, 0.2063, 0.4816, 0.3075, 0.3519, 0.6757, 0.6792, 0.6699, 0.7556,
         0.7536, 0.9697, 0.9276, 0.4790, 0.7212, 0.6930],
        [0.3670, 0.2334, 0.4586, 0.2993, 0.3087, 0.6765, 0.6795, 0.6696, 0.7532,
         0.7530, 0.9536, 0.9554, 0.4712, 0.7092, 0.6880],
        [0.3890, 0.2600, 0.4604, 0.3001, 0.3267, 0.6791, 0.6805, 0.6689, 0.7509,
         0.7524, 0.9231, 0.9476, 0.4465, 0.7192, 0.6884],
        [0.4219, 0.2886, 0.5376, 0.3335, 0.3368, 0.6851, 0.6825, 0.6665, 0.7489,
         0.7528, 0.9317, 0.9341, 0.4445, 0.7331, 0.7062]], device='cuda:0')

# Vanilla LSTM

In [241]:
class VanillaLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob):
        super(VanillaLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

# Stacked LSTM

In [242]:
class StackedLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, stateful):
        super(StackedLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size
        self.stateful = stateful
        
        self.hn = None
        self.cn = None

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=self.layer_size,
                            dropout=(dropout_prob if self.layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def reset_hidden_state(self, batch_size=None):
        if batch_size is None or not self.stateful:
            # Reset hidden and cell states to None if batch_size is not provided or if the model is not stateful
            self.hn = None
            self.cn = None
        else:
            # Resize hidden and cell states to match current batch size, preserving the state as much as possible
            self.hn = self._resize_state(self.hn, batch_size)
            self.cn = self._resize_state(self.cn, batch_size)


    def _resize_state(self, state, batch_size):
        if state is None:
            # If state is not initialized, initialize with zeros
            return torch.zeros(self.layer_size, batch_size, self.hidden_size).to(device)
        elif batch_size < state.size(1):
            # If batch size is smaller, truncate the state
            return state[:, :batch_size, :].contiguous()
        elif batch_size > state.size(1):
            # If batch size is larger, pad the state with zeros
            padding_size = batch_size - state.size(1)
            padding = torch.zeros(self.layer_size, padding_size, self.hidden_size).to(device)
            return torch.cat([state, padding], dim=1)
        

    def forward(self, x):
        current_batch_size = x.size(0)

        # Check and adjust the hidden and cell states
        if not self.stateful or self.hn is None or self.hn.size(1) != current_batch_size:
            self.reset_hidden_state(current_batch_size)
        else:
            # Detach the hidden states from the graph to avoid backpropagating through the entire sequence history
            self.hn = self.hn.detach()
            self.cn = self.cn.detach()

        # Ensure that hn and cn are not None and have the correct shape
        h0 = self.hn if self.hn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)
        c0 = self.cn if self.cn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0, c0))

        # Update hidden states if stateful
        if self.stateful:
            self.hn, self.cn = hn.detach(), cn.detach()

        # Process the output of the last time step
        out = self.dropout(out[:, -1, :])  # Add dropout
        out = self.fc(out)  # Fully connected layer

        return out

# Bidirectional LSTM

# 1D CNN-LSTM

In [243]:
class OneDimCNNLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, conv_channels, kernel_size, pool_size, stride):
        super(OneDimCNNLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # Convolutional Layer
        self.conv1 = nn.Conv1d(in_channels=input_dim, out_channels=conv_channels, kernel_size=kernel_size)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool1d(kernel_size=pool_size, stride=pool_size)

        self.conv2 = nn.Conv1d(in_channels=conv_channels, out_channels=conv_channels*2, kernel_size=kernel_size)
        self.relu2 = nn.ReLU()
        self.maxpool2 = nn.MaxPool1d(kernel_size=2, stride=2)


        self.lstm = nn.LSTM(input_size = conv_channels*2, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # CNN in_dim: (batch_size, in_channels, length)
        x = x.transpose(1, 2)

        # Conv layer forward propagate
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.maxpool1(x)

        # x = self.conv2(x)
        # x = self.relu2(x)
        # x = self.maxpool2(x)

        # LSTM in_dim: (batch_size, seq_len, input_size)
        x = x.transpose(1, 2)

        assert x.size(-1) == self.lstm.input_size, f"Mismatch in LSTM input size. Expected: {self.lstm.input_size}, Got: {x.size(-1)}"

        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

In [244]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device, model_type):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model_type = model_type
        self.model = None
        self.optimizer = None
        self.criterion = nn.CrossEntropyLoss()

    
    def train_validate(self, config, trial):

        if self.model_type == "Vanilla LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=3).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=3).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=3, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.long()


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    loss = loss.mean()
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.long()

                        preds = self.model(data)
                        loss = self.criterion(preds, target)
                        loss = loss.mean()

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
        if self.model_type == "Vanilla LSTM":

            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=1).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=1, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1, 1)  # Reshape target to have an extra dimension

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                loss = loss.mean()
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1, 1)
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                all_preds.extend(preds.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [245]:
model_type = "Vanilla LSTM"

def objective(trial):
    if model_type == "Vanilla LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.15),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 10, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9)
        }

    elif model_type == "Stacked LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "num_layers": trial.suggest_int("num_layers", 1, 5)
        }

    elif model_type == "1D CNN-LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "conv_channels": trial.suggest_int("conv_channels", 16, 128),
            "kernel_size": trial.suggest_int("kernel_size", 2, 6),
            "num_layers": trial.suggest_int("num_layers", 1, 5),
            "pool_size": trial.suggest_int("pool_size", 2, 5),
            "stride": trial.suggest_int("stride", 1, 4)
        }

    trainer = ModelActioner(train_data, test_data, device, model_type)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [246]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=25, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    # Optionally, you can include additional information in the progress bar
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=25, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-27 00:35:08,621] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/25 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/107
Current Learning Rate: 0.004699086469573297
train_loss: 1.095158587004009, val_loss: 1.0055946444210253
epochs 2/107
Current Learning Rate: 0.004699086469573297
train_loss: 1.0370233755362661, val_loss: 0.9875043523939032
epochs 3/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9863941932979383, val_loss: 0.9804591605537816
epochs 4/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9905893300708971, val_loss: 0.9795013157944931
epochs 5/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.990764878298107, val_loss: 0.9811847322865537
epochs 6/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9874814096250032, val_loss: 0.9835567693961295
epochs 7/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9806862674261394, val_loss: 0.9822061946517543
epochs 8/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9755498541028876, val_loss: 0.9790952444076538
epochs 9/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9740627332737571, val_loss: 0.9765161683684901
epochs 10/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9715221906963147, val_loss: 0.973691012984828
epochs 11/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9636404056298106, val_loss: 0.9696634217312462
epochs 12/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9576369323228535, val_loss: 0.9642817346673263
epochs 13/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9489261068795857, val_loss: 0.995025971061305
epochs 14/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9697275080178913, val_loss: 0.9704001683937876
epochs 15/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9567116316996123, val_loss: 0.9660061108438592
epochs 16/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9353216296748111, val_loss: 0.9731424902614795
epochs 17/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9438389251106664, val_loss: 0.9723534947947452
epochs 18/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9355117408852828, val_loss: 0.9760654957670915
epochs 19/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9198349538602327, val_loss: 0.9828525618502968
epochs 20/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.925495686029133, val_loss: 0.9798247908291063
epochs 21/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9185353285387943, val_loss: 0.9785378487486588
epochs 22/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9178784282583939, val_loss: 0.9806350940152219
epochs 23/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9175681747888264, val_loss: 0.9852964438890156
epochs 24/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.907858531726034, val_loss: 0.9978105890123468
epochs 25/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9064597932915939, val_loss: 1.0706752808470474
epochs 26/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9464139028599388, val_loss: 1.0219000458717347
epochs 27/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9841562735406976, val_loss: 0.9898299625045375
epochs 28/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9492482988457931, val_loss: 0.9933025987524735
epochs 29/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9392316736673054, val_loss: 0.9862804971243205
epochs 30/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9179557706180371, val_loss: 0.9790678783466942
epochs 31/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9161486657042253, val_loss: 0.9867065856331273
epochs 32/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.921517530867928, val_loss: 0.9850007885380795
epochs 33/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9297350287437439, val_loss: 0.9668738308705782
epochs 34/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9245326468819066, val_loss: 0.9728569231535259
epochs 35/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9111291145023547, val_loss: 0.9892642215678566
epochs 36/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9162375550521048, val_loss: 1.0090315831334968
epochs 37/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9186366137705351, val_loss: 0.9763805721935473
epochs 38/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.913402775714272, val_loss: 0.9795722798297279
epochs 39/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9160056271051106, val_loss: 0.9768006801605225
epochs 40/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.909300484782771, val_loss: 0.9816574799387079
epochs 41/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8965075034844248, val_loss: 0.993246557210621
epochs 42/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8924064874649048, val_loss: 1.0140519211166783
epochs 43/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9009281672929462, val_loss: 0.9948275346505014
epochs 44/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9414910398031536, val_loss: 0.9678890899608009
epochs 45/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9220897630641335, val_loss: 0.9674947682179903
epochs 46/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.90617032615762, val_loss: 1.0432978090487028
epochs 47/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9254522493011073, val_loss: 1.0202814729590164
epochs 48/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9578494071960449, val_loss: 0.9655751880846526
epochs 49/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9280144289920205, val_loss: 0.9761833780690243
epochs 50/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9218710874256335, val_loss: 0.9704322331830075
epochs 51/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9056898888788725, val_loss: 0.9694075427557293
epochs 52/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9080986399399607, val_loss: 0.9765568337942424
epochs 53/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9041629490099455, val_loss: 1.0003440875756113
epochs 54/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8988911672642357, val_loss: 0.9920972654694005
epochs 55/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8959233748285393, val_loss: 0.9911550785365858
epochs 56/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8944518478293167, val_loss: 0.9854130111242595
epochs 57/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8924269193097165, val_loss: 0.9948589212016056
epochs 58/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8832640735726608, val_loss: 1.014234463164681
epochs 59/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8906762819541129, val_loss: 0.9897555953577946
epochs 60/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9085693723277042, val_loss: 0.9752313388021369
epochs 61/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.893405763099068, val_loss: 1.0037959845442521
epochs 62/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8923937778723867, val_loss: 0.9934907348532426
epochs 63/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8827918422849554, val_loss: 0.995322288964924
epochs 64/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8846600934078819, val_loss: 1.0126572288964923
epochs 65/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8778311817269576, val_loss: 1.024884207625138
epochs 66/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8771276812804373, val_loss: 0.9957253556502493
epochs 67/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8800667449047691, val_loss: 0.991952025262933
epochs 68/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8754527769590679, val_loss: 0.9802492593464098
epochs 69/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8837573816901759, val_loss: 0.9930005211579173
epochs 70/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8841669132834986, val_loss: 0.9950080426115738
epochs 71/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.876780915260315, val_loss: 0.9908100034061231
epochs 72/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8824586780447709, val_loss: 0.9979492457289445
epochs 73/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8741522174132498, val_loss: 0.9928230674643266
epochs 74/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8683266959692303, val_loss: 1.0031128299863714
epochs 75/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8552092458072461, val_loss: 1.02783444366957
epochs 76/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.8891766774026971, val_loss: 1.0114987705883227
epochs 77/107
Current Learning Rate: 0.004699086469573297
train_loss: 1.091283661440799, val_loss: 0.9664058371594078
epochs 78/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9204381327880057, val_loss: 0.9663262906827425
epochs 79/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9223263589959395, val_loss: 0.9661754545412565
epochs 80/107
Epoch 00080: reducing learning rate of group 0 to 3.8120e-03.
Current Learning Rate: 0.003812034559865557
train_loss: 0.9182856835817036, val_loss: 0.9702078700065613
epochs 81/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9159023855861864, val_loss: 0.9709496560849642
epochs 82/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.914004301397424, val_loss: 0.9711808374053553
epochs 83/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9146618962287902, val_loss: 0.9749141009230363
epochs 84/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9109286107515034, val_loss: 0.9811342647201137
epochs 85/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9079599330299779, val_loss: 0.9874249765747471
epochs 86/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9046062425563209, val_loss: 0.9931718129860727
epochs 87/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9027809914789702, val_loss: 1.0050649423348277
epochs 88/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8951692261193928, val_loss: 1.027314974132337
epochs 89/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8938917486291182, val_loss: 1.0636811758342541
epochs 90/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9025046568167837, val_loss: 1.0435780656965155
epochs 91/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9617747902870178, val_loss: 0.9661974241859035
epochs 92/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9297876621547498, val_loss: 0.9639039629384091
epochs 93/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9224149208319815, val_loss: 0.9649636965048941
epochs 94/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9153429376451593, val_loss: 0.9623886986782676
epochs 95/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9090054493201406, val_loss: 0.9647816708213405
epochs 96/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.9041071860413802, val_loss: 0.9701686187794334
epochs 97/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8991290688514709, val_loss: 0.9800427913665771
epochs 98/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8927936522584212, val_loss: 0.988597529812863
epochs 99/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8839576777658964, val_loss: 0.9922020447881599
epochs 100/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8779309849990041, val_loss: 1.0094609084882233
epochs 101/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8753762402032551, val_loss: 1.0032240528809397
epochs 102/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.87926863557414, val_loss: 1.0431005220664176
epochs 103/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8886560032242223, val_loss: 0.9904559951079519
epochs 104/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8761390560551694, val_loss: 0.9971484372490331
epochs 105/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8770140108309294, val_loss: 1.027900853282527
epochs 106/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8676852282724883, val_loss: 1.0031518553432666
epochs 107/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.8667683576282702, val_loss: 1.0092810988426208
Starting fold 2:
epochs 1/107
Current Learning Rate: 0.004699086469573297
train_loss: 1.1028966542921568, val_loss: 1.399717512883638
epochs 2/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9440475664640727, val_loss: 1.1136717758680645
epochs 3/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9535982321751745, val_loss: 1.069568347303491
epochs 4/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9658583779084055, val_loss: 1.0554589604076585
epochs 5/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9573554056255441, val_loss: 1.0498588047529522
epochs 6/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9431165877141451, val_loss: 1.0670429085430346
epochs 7/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9662388102004402, val_loss: 1.0647872479338394
epochs 8/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9703268004091162, val_loss: 1.0676772763854578
epochs 9/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9529035442753842, val_loss: 1.061561940218273
epochs 10/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9435598125583247, val_loss: 1.0544454003635206
epochs 11/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9384695939327541, val_loss: 1.0461299877417716
epochs 12/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9460047300708921, val_loss: 1.0466334286488985
epochs 13/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.926212141388341, val_loss: 1.0474588513374328
epochs 14/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.948383408628012, val_loss: 1.0562360550227918
epochs 15/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9319580054596851, val_loss: 1.081818655917519
epochs 16/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9458921056044729, val_loss: 1.0836396907505237
epochs 17/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.970756773572219, val_loss: 1.0925940864964536
epochs 18/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9506061262206027, val_loss: 1.0746489160939268
epochs 19/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9376014151071247, val_loss: 1.0815812562641345
epochs 20/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9325264728383014, val_loss: 1.077266452186986
epochs 21/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9178172695793604, val_loss: 1.0758835353349385
epochs 22/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9180651405924245, val_loss: 1.0804273417121486
epochs 23/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9367154595098998, val_loss: 1.1031459231125682
epochs 24/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9272887474612186, val_loss: 1.0929022688614696
epochs 25/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9544265285918587, val_loss: 1.0983791570914418
epochs 26/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9671830174170042, val_loss: 1.0960504939681606
epochs 27/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.953366022674661, val_loss: 1.07215038098787
epochs 28/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9505175295628999, val_loss: 1.0699907610290929
epochs 29/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9518134719447086, val_loss: 1.076720515050386
epochs 30/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9511541231682427, val_loss: 1.075721696176027
epochs 31/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9464395929324, val_loss: 1.076381976980912
epochs 32/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9459941168364726, val_loss: 1.0921540548926905
epochs 33/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9485061591000934, val_loss: 1.1518227326242547
epochs 34/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9453443756228999, val_loss: 1.098226325135482
epochs 35/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9429435347255908, val_loss: 1.1102488982050043
epochs 36/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9391561778752427, val_loss: 1.132964199467709
epochs 37/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9412206099221581, val_loss: 1.202018205743087
epochs 38/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9335221762719907, val_loss: 1.1665542728022524
epochs 39/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9364618392367112, val_loss: 1.238296137358013
epochs 40/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9331539415215191, val_loss: 1.2207347192262348
epochs 41/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9315617988768377, val_loss: 1.2858381208620573
epochs 42/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9241851918791469, val_loss: 1.1945895935359754
epochs 43/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9233826830983162, val_loss: 1.4444827104869642
epochs 44/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.919489175081253, val_loss: 1.2007246946033678
epochs 45/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9462391580405988, val_loss: 1.0282532773519817
epochs 46/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9642987605772521, val_loss: 1.026284042157625
epochs 47/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9566731120410719, val_loss: 1.0436967987763255
epochs 48/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.965397658473567, val_loss: 1.0592880587828786
epochs 49/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9601496735685751, val_loss: 1.0490829988529808
epochs 50/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9576551406007064, val_loss: 1.0534433584464225
epochs 51/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9581208624337849, val_loss: 1.0443494501866792
epochs 52/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.952268070609946, val_loss: 1.0448239840959248
epochs 53/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9555784645833467, val_loss: 1.0462405261240508
epochs 54/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9522101188960829, val_loss: 1.0451850721710607
epochs 55/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.94965040997455, val_loss: 1.0470981968076605
epochs 56/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9459938873585901, val_loss: 1.0474766003458122
epochs 57/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9434781359998803, val_loss: 1.050982661623704
epochs 58/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9434000118782646, val_loss: 1.0567928653014333
epochs 59/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9433619235691272, val_loss: 1.0631508187243812
epochs 60/107
Current Learning Rate: 0.004699086469573297
train_loss: 0.9401684361853098, val_loss: 1.076169326430873
epochs 61/107
Current Learning Rate: 0.004699086469573297

[I 2024-01-27 00:35:52,755] Trial 0 finished with value: 1.325035759380048 and parameters: {'batch_size': 54, 'epochs': 107, 'hidden_size': 81, 'learning_rate': 0.004699086469573297, 'dropout_prob': 0.011083383552199899, 'weight_decay': 7.793833426169012e-06, 'lr_step_size': 67, 'gamma': 0.8112288600238742}. Best is trial 0 with value: 1.325035759380048.

Current Learning Rate: 0.003812034559865557
train_loss: 0.5591263277750266, val_loss: 1.3443419230611702
epochs 107/107
Current Learning Rate: 0.003812034559865557
train_loss: 0.544927563290847, val_loss: 1.3694184993442735
Mean validation loss: 1.325035759380048
Starting fold 1:
epochs 1/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1339282876566836, val_loss: 1.1531996865021554
epochs 2/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1320385694503785, val_loss: 1.14997523332897
epochs 3/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1292206425415843, val_loss: 1.1467997852124665
epochs 4/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1259573974107442, val_loss: 1.1436659825475592
epochs 5/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1246532929571051, val_loss: 1.1405700533013594
epochs 6/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1205847652334915, val_loss: 1.1375181562022159
epochs 7/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1168312085302252, val_loss: 1.1345079848640844
epochs 8/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1159847272069832, val_loss: 1.1315286724190963
epochs 9/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1127802045721757, val_loss: 1.1285642372934441
epochs 10/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1104846477508545, val_loss: 1.1256147020741514
epochs 11/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1088040464802793, val_loss: 1.122680654023823
epochs 12/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1057785837273848, val_loss: 1.1197720439810501
epochs 13/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1039966144059834, val_loss: 1.1168747073725651
epochs 14/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.1001930249364753, val_loss: 1.1139753329126458
epochs 15/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0971521252080014, val_loss: 1.1110705450961464
epochs 16/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.096350215610705, val_loss: 1.108156492835597
epochs 17/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0943196886464168, val_loss: 1.1052248264613904
epochs 18/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0916056457318757, val_loss: 1.102270888027392
epochs 19/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0876699598211992, val_loss: 1.099296242312381
epochs 20/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0856980938660472, val_loss: 1.0963078084744906
epochs 21/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0822242423107749, val_loss: 1.0932895484723544
epochs 22/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0803328514099122, val_loss: 1.0902322857003464
epochs 23/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0783444718310708, val_loss: 1.0871479360680831
epochs 24/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0751665592193604, val_loss: 1.0840407672681307
epochs 25/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0730291755575883, val_loss: 1.0809010982513427
epochs 26/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0701552855341059, val_loss: 1.0777110953080027
epochs 27/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0676382002077605, val_loss: 1.074482183707388
epochs 28/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.064775796940452, val_loss: 1.071213738541854
epochs 29/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0629055349450363, val_loss: 1.0679177422272532
epochs 30/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0569566400427568, val_loss: 1.064580363976328
epochs 31/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0544304960652402, val_loss: 1.0611955881118775
epochs 32/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0523620191373324, val_loss: 1.0577846451809532
epochs 33/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0492538025504665, val_loss: 1.0543492317199707
epochs 34/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.047388017804999, val_loss: 1.0508956118633872
epochs 35/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0421112349158839, val_loss: 1.0473990189401727
epochs 36/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.038966851485403, val_loss: 1.0438717252329777
epochs 37/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0335030769046984, val_loss: 1.0403181979530736
epochs 38/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.032645979680513, val_loss: 1.036760005198027
epochs 39/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0300513581225748, val_loss: 1.0332277561488905
epochs 40/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0259704539650365, val_loss: 1.0297113380934062
epochs 41/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0229347906614605, val_loss: 1.0262389559494822
epochs 42/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0180376529693604, val_loss: 1.022842042069686
epochs 43/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0162765979766846, val_loss: 1.0195434482474075
epochs 44/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0121193634836296, val_loss: 1.0163761264399478
epochs 45/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0087852628607499, val_loss: 1.0133802301005312
epochs 46/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0066558298311736, val_loss: 1.0105611173730147
epochs 47/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0029768266175922, val_loss: 1.0079207784251163
epochs 48/118
Current Learning Rate: 0.00014853275439127747
train_loss: 1.0026252771678723, val_loss: 1.0055060825849835
epochs 49/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9983210300144396, val_loss: 1.0033426410273503
epochs 50/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.997244037452497, val_loss: 1.0014351932626022
epochs 51/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9937225504925377, val_loss: 0.9997713151730989
epochs 52/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9929161009035612, val_loss: 0.9983599349072105
epochs 53/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9911450637014289, val_loss: 0.9971727622182746
epochs 54/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9905100759707, val_loss: 0.9961929898512991
epochs 55/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9882181311908521, val_loss: 0.9953993772205554
epochs 56/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9859994913402357, val_loss: 0.9947515964508057
epochs 57/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9918356355867888, val_loss: 0.994223774106879
epochs 58/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9869111726158544, val_loss: 0.9937845142264116
epochs 59/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9863635935281453, val_loss: 0.9934032778990897
epochs 60/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9883412699950369, val_loss: 0.9930530472805625
epochs 61/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9867988329184683, val_loss: 0.9927285169300281
epochs 62/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9868651076367027, val_loss: 0.9923987451352572
epochs 63/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9910333457746003, val_loss: 0.9920593713459216
epochs 64/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9905127079863297, val_loss: 0.9917438921175505
epochs 65/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9872716960154082, val_loss: 0.9914244187505622
epochs 66/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9894614809437802, val_loss: 0.9910921924992612
epochs 67/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9847101111161082, val_loss: 0.9907589636350933
epochs 68/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9868070207144085, val_loss: 0.9904460028598183
epochs 69/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9831665867253354, val_loss: 0.9901523753216392
epochs 70/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9878865907066747, val_loss: 0.9898626515739842
epochs 71/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9892342787039907, val_loss: 0.9895508126208656
epochs 72/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9827779625591478, val_loss: 0.9892479068354556
epochs 73/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9879635057951275, val_loss: 0.9889705005444979
epochs 74/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9804939966452749, val_loss: 0.9887030538759733
epochs 75/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9859919102568375, val_loss: 0.9884350638640554
epochs 76/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9839269117305153, val_loss: 0.9881862276478818
epochs 77/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9892685570214924, val_loss: 0.9879434309507671
epochs 78/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9851887646474337, val_loss: 0.9877325108176783
epochs 79/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9822812870929115, val_loss: 0.9875343398043984
epochs 80/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9860396447934603, val_loss: 0.9873542559774299
epochs 81/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9882229528929057, val_loss: 0.9871690072511372
epochs 82/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9855290513289602, val_loss: 0.9869708261991802
epochs 83/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9875565817481593, val_loss: 0.9867609438143279
epochs 84/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9874075419024417, val_loss: 0.9865545235182109
epochs 85/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9858545692343461, val_loss: 0.9863587103391949
epochs 86/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9837449117710716, val_loss: 0.986177608841344
epochs 87/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9824164748191834, val_loss: 0.986041606099982
epochs 88/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9781903637082954, val_loss: 0.9859196148420635
epochs 89/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9820074740209077, val_loss: 0.9858195003710295
epochs 90/118
Current Learning Rate: 0.00014853275439127747
train_loss: 0.9850249321837174, val_loss: 0.9857291886681004
epochs 91/118

[I 2024-01-27 00:35:56,558] Trial 1 pruned.

Current Learning Rate: 0.00014853275439127747
train_loss: 0.9819733789092616, val_loss: 0.9856376120918675
epochs 92/118
Starting fold 1:
epochs 1/110
Current Learning Rate: 0.0005114000297213227
train_loss: 1.0983520984649657, val_loss: 1.08555908203125
epochs 2/110
Current Learning Rate: 0.0005114000297213227
train_loss: 1.0852734088897704, val_loss: 1.07198326587677
epochs 3/110
Current Learning Rate: 0.0005114000297213227
train_loss: 1.0725252866744994, val_loss: 1.0593604564666748
epochs 4/110
Current Learning Rate: 0.0005114000297213227
train_loss: 1.0594946622848511, val_loss: 1.0472309589385986
epochs 5/110
Current Learning Rate: 0.0005114000297213227
train_loss: 1.0485174894332885, val_loss: 1.0354034900665283
epochs 6/110
Current Learning Rate: 0.0005114000297213227
train_loss: 1.0372310519218444, val_loss: 1.0241055369377137
epochs 7/110
Current Learning Rate: 0.0005114000297213227
train_loss: 1.0257922768592835, val_loss: 1.0136959314346314
epochs 8/110
Current Learning Rate: 0.0005114000297213227
train_loss: 1.0155332207679748, val_loss: 1.0050746560096742
epochs 9/110
Current Learning Rate: 0.0005114000297213227
train_loss: 1.0068800449371338, val_loss: 0.9991549015045166
epochs 10/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9989520311355591, val_loss: 0.9962059617042541
epochs 11/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9962387919425965, val_loss: 0.9952678442001343
epochs 12/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9925162196159363, val_loss: 0.9947906494140625
epochs 13/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9936275959014893, val_loss: 0.9935980796813965
epochs 14/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9895968079566956, val_loss: 0.9918813467025757
epochs 15/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9880718231201172, val_loss: 0.9902961134910584
epochs 16/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9859855055809021, val_loss: 0.989059317111969
epochs 17/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9882227301597595, val_loss: 0.9881567478179931
epochs 18/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9866249442100525, val_loss: 0.9876258611679077
epochs 19/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9894235253334045, val_loss: 0.9873834013938904
epochs 20/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9841791391372681, val_loss: 0.9872710227966308
epochs 21/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9866840004920959, val_loss: 0.9871890902519226
epochs 22/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9836779236793518, val_loss: 0.9871957898139954
epochs 23/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9836008310317993, val_loss: 0.9872413158416748
epochs 24/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9841906309127808, val_loss: 0.9871728777885437
epochs 25/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9832525372505188, val_loss: 0.9870920300483703
epochs 26/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9809810280799866, val_loss: 0.986954641342163
epochs 27/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9821510076522827, val_loss: 0.9867772936820984
epochs 28/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9816757202148437, val_loss: 0.986570167541504
epochs 29/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9789777874946595, val_loss: 0.9864235758781433
epochs 30/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9792698740959167, val_loss: 0.9862473130226135
epochs 31/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9766752362251282, val_loss: 0.9860466480255127
epochs 32/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9797239661216736, val_loss: 0.9857751369476319
epochs 33/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9777921676635742, val_loss: 0.9853093504905701
epochs 34/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9768956899642944, val_loss: 0.9848650932312012
epochs 35/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9769280791282654, val_loss: 0.9842883944511414
epochs 36/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9732183933258056, val_loss: 0.9836215138435364
epochs 37/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9724955439567566, val_loss: 0.9828767538070678
epochs 38/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9695358395576477, val_loss: 0.982067859172821
epochs 39/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.968436336517334, val_loss: 0.9813329458236695
epochs 40/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.968139362335205, val_loss: 0.9796343564987182
epochs 41/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9655915975570679, val_loss: 0.977033269405365
epochs 42/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.963296914100647, val_loss: 0.9749005436897278
epochs 43/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9591280460357666, val_loss: 0.9738266825675964
epochs 44/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9554421901702881, val_loss: 0.9724029421806335
epochs 45/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9539026498794556, val_loss: 0.9714640617370606
epochs 46/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9518369436264038, val_loss: 0.9708495974540711
epochs 47/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9507231831550598, val_loss: 0.9702166557312012
epochs 48/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9478668451309205, val_loss: 0.9699120044708252
epochs 49/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9410244226455688, val_loss: 0.9693934440612793
epochs 50/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9390408873558045, val_loss: 0.970218276977539
epochs 51/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9371834754943847, val_loss: 0.9699294328689575
epochs 52/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9322754502296448, val_loss: 0.9714648246765136
epochs 53/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9286049246788025, val_loss: 0.9726955771446228
epochs 54/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9248578429222107, val_loss: 0.9756614804267884
epochs 55/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9166997909545899, val_loss: 0.9787376403808594
epochs 56/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9217815279960633, val_loss: 0.9813619971275329
epochs 57/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9074809908866882, val_loss: 0.9844017624855042
epochs 58/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9278455257415772, val_loss: 0.9967104315757751
epochs 59/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.918742835521698, val_loss: 0.9815908312797547
epochs 60/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9337356209754943, val_loss: 0.9759047865867615
epochs 61/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9140169143676757, val_loss: 0.9882145404815674
epochs 62/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.920883858203888, val_loss: 0.9732876777648926
epochs 63/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8992643594741822, val_loss: 0.9755841851234436
epochs 64/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9079633831977845, val_loss: 0.9805240035057068
epochs 65/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9005621314048767, val_loss: 0.9865896463394165
epochs 66/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8956127405166626, val_loss: 0.9960936903953552
epochs 67/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8954816460609436, val_loss: 1.0011758685112
epochs 68/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8971208810806275, val_loss: 1.0126304507255555
epochs 69/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8944926738739014, val_loss: 1.0150150418281556
epochs 70/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8922163844108582, val_loss: 1.0256453037261963
epochs 71/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8927818655967712, val_loss: 1.0186559796333312
epochs 72/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8914876818656922, val_loss: 1.0334985256195068
epochs 73/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9006860971450805, val_loss: 1.0128046154975892
epochs 74/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9031797170639038, val_loss: 1.0179933071136475
epochs 75/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8996127486228943, val_loss: 1.0181835055351258
epochs 76/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8933376550674439, val_loss: 1.0109144806861878
epochs 77/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8919700026512146, val_loss: 1.0167449474334718
epochs 78/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8939733028411865, val_loss: 1.0094810247421264
epochs 79/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8908544301986694, val_loss: 1.0187923073768617
epochs 80/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8885474085807801, val_loss: 1.021376645565033
epochs 81/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8869354486465454, val_loss: 1.0203073382377625
epochs 82/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8887309432029724, val_loss: 1.0318946957588195
epochs 83/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8856998443603515, val_loss: 1.0295824646949767
epochs 84/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8863003730773926, val_loss: 1.0373661637306213
epochs 85/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8867012023925781, val_loss: 1.0383565425872803
epochs 86/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8830381631851196, val_loss: 1.038364791870117
epochs 87/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8841553688049316, val_loss: 1.043494963645935
epochs 88/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.884081220626831, val_loss: 1.0384048342704773
epochs 89/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8855927586555481, val_loss: 1.0478265285491943
epochs 90/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8944528579711915, val_loss: 1.0519340872764587
epochs 91/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9183080315589904, val_loss: 1.0348604679107667
epochs 92/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8979444742202759, val_loss: 1.0084460139274598
epochs 93/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.891352117061615, val_loss: 1.0013812184333801
epochs 94/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8942779064178467, val_loss: 1.0033197045326232
epochs 95/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8961203694343567, val_loss: 1.007613229751587
epochs 96/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8907611012458801, val_loss: 1.0151578307151794
epochs 97/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.885865306854248, val_loss: 1.024496352672577
epochs 98/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8839344382286072, val_loss: 1.0301019310951234
epochs 99/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8853213071823121, val_loss: 1.0353784680366516
epochs 100/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8817377328872681, val_loss: 1.039749836921692
epochs 101/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8786204695701599, val_loss: 1.0444143414497375
epochs 102/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8834951996803284, val_loss: 1.0480167508125304
epochs 103/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8816047668457031, val_loss: 1.049927568435669
epochs 104/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.883267092704773, val_loss: 1.050312054157257
epochs 105/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8831767916679383, val_loss: 1.0551249384880066
epochs 106/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8926005959510803, val_loss: 1.0592137575149536
epochs 107/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9231631398200989, val_loss: 1.0349973678588866
epochs 108/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9080069422721863, val_loss: 1.0117543458938598
epochs 109/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8891433119773865, val_loss: 1.0016717314720154
epochs 110/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.8892984867095948, val_loss: 0.9981889605522156
Starting fold 2:
epochs 1/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9528082728385925, val_loss: 1.1226125717163087
epochs 2/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9590907514095306, val_loss: 1.1084417581558228
epochs 3/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9448744297027588, val_loss: 1.0894110202789307
epochs 4/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9413150668144226, val_loss: 1.087574303150177
epochs 5/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9358282208442688, val_loss: 1.0896501064300537
epochs 6/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9335995137691497, val_loss: 1.0881484627723694
epochs 7/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9286422014236451, val_loss: 1.0875433564186097
epochs 8/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9248103499412537, val_loss: 1.0903059482574462
epochs 9/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9250189661979675, val_loss: 1.0932754278182983
epochs 10/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9231490790843964, val_loss: 1.0958428859710694
epochs 11/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9200327754020691, val_loss: 1.0972731590270997
epochs 12/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9188163042068481, val_loss: 1.098831009864807
epochs 13/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.922637939453125, val_loss: 1.1021877765655517
epochs 14/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9233753263950348, val_loss: 1.0974871635437011
epochs 15/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9440551817417144, val_loss: 1.114886474609375
epochs 16/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9422837018966674, val_loss: 1.0775817036628723
epochs 17/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9290761232376099, val_loss: 1.0659847855567932
epochs 18/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9199191868305207, val_loss: 1.0723897218704224
epochs 19/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9214428663253784, val_loss: 1.0748941898345947
epochs 20/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9158938944339752, val_loss: 1.0831491827964783
epochs 21/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9181720852851868, val_loss: 1.0831123471260071
epochs 22/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9162663102149964, val_loss: 1.094355845451355
epochs 23/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9198773086071015, val_loss: 1.0880284190177918
epochs 24/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9192161142826081, val_loss: 1.1027237176895142
epochs 25/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9210965156555175, val_loss: 1.0858608603477478
epochs 26/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9200676679611206, val_loss: 1.102589726448059
epochs 27/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9226963996887207, val_loss: 1.0820632696151733
epochs 28/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9214230179786682, val_loss: 1.0967684745788575
epochs 29/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9163399338722229, val_loss: 1.080411398410797
epochs 30/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9164890170097351, val_loss: 1.0933911561965943
epochs 31/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9156839907169342, val_loss: 1.082954216003418
epochs 32/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.913176316022873, val_loss: 1.092984962463379
epochs 33/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9125042796134949, val_loss: 1.0834707260131835
epochs 34/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9170308709144592, val_loss: 1.0924145698547363
epochs 35/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9210869550704956, val_loss: 1.0838615536689757
epochs 36/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9143348932266235, val_loss: 1.0759886384010315
epochs 37/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9129648029804229, val_loss: 1.0812639594078064
epochs 38/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9120190620422364, val_loss: 1.0778502345085144
epochs 39/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9150699496269226, val_loss: 1.090020775794983
epochs 40/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9173267841339111, val_loss: 1.0749157071113586
epochs 41/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9243802726268768, val_loss: 1.1017517566680908
epochs 42/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.926217919588089, val_loss: 1.0742783665657043
epochs 43/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9174325585365295, val_loss: 1.0776872754096984
epochs 44/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9172132015228271, val_loss: 1.0747093558311462
epochs 45/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9131652593612671, val_loss: 1.0747708916664123
epochs 46/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9125693917274476, val_loss: 1.0852017879486084
epochs 47/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9082186222076416, val_loss: 1.0820595026016235
epochs 48/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9108937680721283, val_loss: 1.0855307936668397
epochs 49/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9164136588573456, val_loss: 1.082681369781494
epochs 50/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.91415576338768, val_loss: 1.0724620938301086
epochs 51/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9145264267921448, val_loss: 1.086483931541443
epochs 52/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9156764566898346, val_loss: 1.0661311745643616
epochs 53/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9146959662437439, val_loss: 1.0845325469970704
epochs 54/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9136450529098511, val_loss: 1.0733619570732116
epochs 55/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.9090990781784057, val_loss: 1.077226996421814
epochs 56/110
Current Learning Rate: 0.0005114000297213227

[I 2024-01-27 00:36:49,898] Trial 2 finished with value: 1.1692108569145203 and parameters: {'batch_size': 38, 'epochs': 110, 'hidden_size': 58, 'learning_rate': 0.0005114000297213227, 'dropout_prob': 0.036842811921699456, 'weight_decay': 6.34187218994956e-06, 'lr_step_size': 74, 'gamma': 0.23844020275858402}. Best is trial 2 with value: 1.1692108569145203.

Current Learning Rate: 0.00012193832677749808
train_loss: 0.9181856274604797, val_loss: 1.246264600753784
Mean validation loss: 1.1692108569145203
Starting fold 1:
epochs 1/142
Current Learning Rate: 0.0011982903501126109
train_loss: 1.0884926588911759, val_loss: 1.037476119555925
epochs 2/142
Current Learning Rate: 0.0011982903501126109
train_loss: 1.0340820547781493, val_loss: 0.9877781340950413
epochs 3/142
Current Learning Rate: 0.0011982903501126109
train_loss: 1.0089450804810776, val_loss: 1.00741313601795
epochs 4/142
Current Learning Rate: 0.0011982903501126109
train_loss: 1.0420720985061245, val_loss: 1.025403603440837
epochs 5/142
Current Learning Rate: 0.0011982903501126109
train_loss: 1.0121546139842585, val_loss: 1.0067465248860812
epochs 6/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9971900648192356, val_loss: 0.9996102292286723
epochs 7/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9907727247790287, val_loss: 0.9997978426908192
epochs 8/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9917680592913377, val_loss: 1.0043405457546837
epochs 9/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9917465809144472, val_loss: 1.0100589846309862
epochs 10/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9988176690904718, val_loss: 1.0115735775546024
epochs 11/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9933942979887912, val_loss: 1.0079300877295043
epochs 12/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9890799807874779, val_loss: 1.0037044791798844
epochs 13/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9821294655925349, val_loss: 1.002057653351834
epochs 14/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9864852836257533, val_loss: 1.0009290378344686
epochs 15/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9860072556294893, val_loss: 0.998444255088505
epochs 16/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9816152638510653, val_loss: 0.9942959167455372
epochs 17/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9791260957717896, val_loss: 0.991912075092918
epochs 18/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9795174830838254, val_loss: 1.0142034226342251
epochs 19/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9824689044764168, val_loss: 1.1196248270963367
epochs 20/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9330610770928233, val_loss: 0.9979306217871214
epochs 21/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9933059224956914, val_loss: 0.9729436011690843
epochs 22/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9758926313174399, val_loss: 1.0213385108270143
epochs 23/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9848503349643004, val_loss: 1.029512747024235
epochs 24/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9549934551904076, val_loss: 0.9791610746007217
epochs 25/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9522639608696888, val_loss: 0.9985364951585468
epochs 26/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9553584657217327, val_loss: 1.1399784728100426
epochs 27/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9301751235598013, val_loss: 0.9686421061816969
epochs 28/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9546953226390638, val_loss: 0.9773249619885495
epochs 29/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9675425597319477, val_loss: 1.2068939384661224
epochs 30/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9409519176734121, val_loss: 0.9632547089928075
epochs 31/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9522135207527562, val_loss: 0.9672203452963578
epochs 32/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9588413608701606, val_loss: 0.9642091186423051
epochs 33/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9566371775771442, val_loss: 0.994720385890258
epochs 34/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9505608256710203, val_loss: 0.986674934311917
epochs 35/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9301071220322659, val_loss: 0.968366005859877
epochs 36/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9254419053071423, val_loss: 0.9750459118893272
epochs 37/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9319160617887974, val_loss: 1.0061002740734502
epochs 38/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.925444952829888, val_loss: 1.0062897710423722
epochs 39/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9218279989142167, val_loss: 1.0492887559689974
epochs 40/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.914015865482782, val_loss: 0.9885506902870379
epochs 41/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9344326249862972, val_loss: 1.0377860979030007
epochs 42/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9154930745300494, val_loss: 1.02687505326773
epochs 43/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9122533917427063, val_loss: 1.0320242888049076
epochs 44/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9159163287595699, val_loss: 1.0550902485847473
epochs 45/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9068308933000816, val_loss: 1.0298583833794845
epochs 46/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9110078436371527, val_loss: 1.0964528253203945
epochs 47/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9127133993726028, val_loss: 0.9582156921687879
epochs 48/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9294439176979817, val_loss: 0.9579235961562709
epochs 49/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9333196130630217, val_loss: 1.0220791233213324
epochs 50/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9282742552851376, val_loss: 0.9919599922079789
epochs 51/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9027010302794607, val_loss: 1.000269485147376
epochs 52/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9042594586548053, val_loss: 1.0434339510767083
epochs 53/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9034824473293204, val_loss: 1.0393308266213066
epochs 54/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9045181926143797, val_loss: 1.044960838242581
epochs 55/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9041131773277333, val_loss: 1.033845656482797
epochs 56/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9035509394187676, val_loss: 1.0820336821832155
epochs 57/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9060137062480575, val_loss: 0.967813831881473
epochs 58/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9142373624600862, val_loss: 0.9965185055607244
epochs 59/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9078611682120122, val_loss: 1.0684376581719046
epochs 60/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9044718898440662, val_loss: 0.9597008799251757
epochs 61/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9166145087856995, val_loss: 0.9603479633205816
epochs 62/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9211757237973967, val_loss: 1.019188916683197
epochs 63/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9043066202025665, val_loss: 1.0379102173604464
epochs 64/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9039390504360199, val_loss: 0.9871751559408087
epochs 65/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9074515461921692, val_loss: 1.027150554092307
epochs 66/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8996403782775527, val_loss: 1.0658756375312806
epochs 67/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8995638731278871, val_loss: 0.9900318619452024
epochs 68/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9064781504242043, val_loss: 1.0377341703364724
epochs 69/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9003169079360209, val_loss: 1.041096476818386
epochs 70/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.897821591402355, val_loss: 1.0187465514007368
epochs 71/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8976961376635652, val_loss: 1.0636535697861722
epochs 72/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8955789219391973, val_loss: 0.9967380329182274
epochs 73/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9013645088986346, val_loss: 1.0673182929817
epochs 74/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8990972942427585, val_loss: 0.9891468415134832
epochs 75/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8988576349459196, val_loss: 1.044837545093737
epochs 76/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8943536076890795, val_loss: 1.0043328511087517
epochs 77/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8958475646219756, val_loss: 1.052451268309041
epochs 78/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8953251931228136, val_loss: 0.9870333718626123
epochs 79/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8987062484025955, val_loss: 1.0583891567430999
epochs 80/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9064611306315974, val_loss: 0.9717519810325221
epochs 81/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9277811427649699, val_loss: 0.9833573887222692
epochs 82/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9212642051671681, val_loss: 1.0039098811777014
epochs 83/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.902532087658581, val_loss: 1.0340706160193995
epochs 84/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9068336268004619, val_loss: 0.9698838481777593
epochs 85/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.904485301242063, val_loss: 0.9696731228577463
epochs 86/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9035663850605488, val_loss: 1.0435269318128888
epochs 87/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.9024044544288986, val_loss: 0.9852222132055383
epochs 88/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8954056960971732, val_loss: 0.9904012121652302
epochs 89/142

[I 2024-01-27 00:36:55,065] Trial 3 pruned.

Current Learning Rate: 0.0011982903501126109
train_loss: 0.894240747823527, val_loss: 1.013863127482565
epochs 90/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8905169542682798, val_loss: 0.999949953744286
epochs 91/142
Current Learning Rate: 0.0011982903501126109
train_loss: 0.8887100512259885, val_loss: 1.0012454961475572
epochs 92/142
Starting fold 1:
epochs 1/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1236914283350894, val_loss: 1.1254924284784418
epochs 2/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1233084440231322, val_loss: 1.1250308225029393
epochs 3/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1229336939359966, val_loss: 1.1245784759521484
epochs 4/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1222224775113558, val_loss: 1.1241302515331069
epochs 5/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1223954690130133, val_loss: 1.1236849822496113
epochs 6/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1218007526899638, val_loss: 1.1232417257208573
epochs 7/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.120718708791231, val_loss: 1.122799993816175
epochs 8/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1210120464626112, val_loss: 1.1223603800723427
epochs 9/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1204209252407675, val_loss: 1.121922052534003
epochs 10/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1197298953407688, val_loss: 1.121485219503704
epochs 11/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1195290314523798, val_loss: 1.1210492460351242
epochs 12/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1193308893002962, val_loss: 1.1206142011441682
epochs 13/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1184189219223826, val_loss: 1.1201799355055158
epochs 14/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1184069683677271, val_loss: 1.1197463713194196
epochs 15/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1177946943985788, val_loss: 1.1193136943014044
epochs 16/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1173030188209132, val_loss: 1.1188819044514706
epochs 17/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1172505315981414, val_loss: 1.1184512652848897
epochs 18/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.116659688949585, val_loss: 1.118021089152286
epochs 19/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1163073000154997, val_loss: 1.1175918666939986
epochs 20/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1157564677690204, val_loss: 1.117162907750983
epochs 21/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1152440962038541, val_loss: 1.1167344783481798
epochs 22/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1150429361744931, val_loss: 1.1163063400670101
epochs 23/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1148894171965749, val_loss: 1.1158788342224923
epochs 24/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1138108667574431, val_loss: 1.115452029830531
epochs 25/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1136667979390997, val_loss: 1.115025211635389
epochs 26/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.113373711234645, val_loss: 1.11459818011836
epochs 27/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1131993444342363, val_loss: 1.1141714372132954
epochs 28/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1127017071372585, val_loss: 1.1137451573422081
epochs 29/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1123465086284436, val_loss: 1.1133192325893202
epochs 30/90

[I 2024-01-27 00:36:56,344] Trial 4 pruned.

Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.111531010426973, val_loss: 1.1128928698991474
epochs 31/90
Current Learning Rate: 2.7930112214370945e-05
train_loss: 1.1114249053754304, val_loss: 1.112466451996251
epochs 32/90
Starting fold 1:
epochs 1/101
Current Learning Rate: 0.021384851927701114
train_loss: 1.1861396450745432, val_loss: 1.086409188571729
epochs 2/101
Current Learning Rate: 0.021384851927701114
train_loss: 1.0693907605974298, val_loss: 1.021602527718795
epochs 3/101
Current Learning Rate: 0.021384851927701114
train_loss: 1.028435145240081, val_loss: 1.0462652570322941
epochs 4/101
Current Learning Rate: 0.021384851927701114
train_loss: 1.0778509927423376, val_loss: 1.0447804275311923
epochs 5/101
Current Learning Rate: 0.021384851927701114
train_loss: 1.0115618564580615, val_loss: 1.0273470665279187
epochs 6/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9966452771111538, val_loss: 1.025743296585585
epochs 7/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9987754009271923, val_loss: 1.0283922229942521
epochs 8/101
Current Learning Rate: 0.021384851927701114
train_loss: 1.0024668555510672, val_loss: 1.0363097134389376
epochs 9/101
Current Learning Rate: 0.021384851927701114
train_loss: 1.0098405232554988, val_loss: 1.0415734134222332
epochs 10/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9985691704248127, val_loss: 1.0296281052263159
epochs 11/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9926432687985269, val_loss: 1.0128982892161922
epochs 12/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9845616212016658, val_loss: 1.0212486351791181
epochs 13/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9864072887521041, val_loss: 1.0098532024182771
epochs 14/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9752485322324853, val_loss: 1.0168756826927787
epochs 15/101
Current Learning Rate: 0.021384851927701114
train_loss: 1.067983706687626, val_loss: 1.0969414215338857
epochs 16/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9782071549641459, val_loss: 1.017384541662116
epochs 17/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.970819618200001, val_loss: 1.0073980359654677
epochs 18/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9780997119451824, val_loss: 1.0240262260562496
epochs 19/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9727318619426928, val_loss: 1.0232735618164666
epochs 20/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9593385934829712, val_loss: 1.0137383545699872
epochs 21/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9651529977196142, val_loss: 1.0193126800813173
epochs 22/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9551440031904923, val_loss: 1.0358420930410686
epochs 23/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9597470452910976, val_loss: 0.9954159880939283
epochs 24/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.972078991249988, val_loss: 1.0539964167695297
epochs 25/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.964564386480733, val_loss: 1.0368569198407624
epochs 26/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9527784579678585, val_loss: 1.0308210140780398
epochs 27/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9582791551163322, val_loss: 1.0418344535325703
epochs 28/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9475587273898878, val_loss: 1.0126126493278302
epochs 29/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9444706091755315, val_loss: 1.0166902021357889
epochs 30/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9470436886737221, val_loss: 1.0464260151511744
epochs 31/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9590340288061845, val_loss: 1.0121256122463629
epochs 32/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9428891448598159, val_loss: 1.019278597831726
epochs 33/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9517844356988606, val_loss: 1.0586861202591344
epochs 34/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9475543837798269, val_loss: 1.0141542544490412
epochs 35/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9472747696073431, val_loss: 1.0219660093909815
epochs 36/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9364734492803874, val_loss: 1.0250266313552856
epochs 37/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9457637557857915, val_loss: 1.0462679668476706
epochs 38/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9372349629276677, val_loss: 1.0448916843062952
epochs 39/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9592623036158713, val_loss: 0.968498495691701
epochs 40/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9495267350422708, val_loss: 1.0308942248946742
epochs 41/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9529571357526277, val_loss: 1.0632548388681913
epochs 42/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9543313173871292, val_loss: 1.017799585116537
epochs 43/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9429706689558531, val_loss: 1.019518018396277
epochs 44/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9363214546128323, val_loss: 1.000698520321595
epochs 45/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9381661967227334, val_loss: 1.022333463869597
epochs 46/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9354844714465894, val_loss: 1.0373550898150394
epochs 47/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9343649274424503, val_loss: 1.1415564386468184
epochs 48/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9559713721275329, val_loss: 1.017240992345308
epochs 49/101
Current Learning Rate: 0.021384851927701114
train_loss: 1.1268977064835397, val_loss: 1.019122636004498
epochs 50/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9689585861406829, val_loss: 1.0233435003381026
epochs 51/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9809461860280287, val_loss: 1.044841071806456
epochs 52/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9530323304628071, val_loss: 1.013797486455817
epochs 53/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9499455194724233, val_loss: 1.0357898843915838
epochs 54/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9563438390430651, val_loss: 1.0157269157861408
epochs 55/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9496042722149899, val_loss: 1.0055080288334897
epochs 56/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9402316890264812, val_loss: 1.1195659662547865
epochs 57/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9657751017495205, val_loss: 1.0111984541541652
epochs 58/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9403118980558295, val_loss: 0.9950334090935556
epochs 59/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9427922992329848, val_loss: 1.0507799782251057
epochs 60/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9448032485811334, val_loss: 1.0296070425133956
epochs 61/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9347638161558854, val_loss: 1.0113451402438314
epochs 62/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9365663682159625, val_loss: 1.0320098174245733
epochs 63/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9313680203337419, val_loss: 1.0412366823146217
epochs 64/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9301166716374849, val_loss: 1.1173698262164466
epochs 65/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.98069942248495, val_loss: 1.131647084888659
epochs 66/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9735245033314354, val_loss: 1.002395152418237
epochs 67/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9484278365185387, val_loss: 1.0260585270429912
epochs 68/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9664499141668018, val_loss: 1.0343555682583858
epochs 69/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9486828101308722, val_loss: 1.0143481025570318
epochs 70/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9327847672136207, val_loss: 0.9993157324038053
epochs 71/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9289075500086734, val_loss: 1.0467287672193426
epochs 72/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9467009343599019, val_loss: 1.067815995843787
epochs 73/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9393235410514631, val_loss: 1.0116354481170051
epochs 74/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9328821445766248, val_loss: 1.0432589229784515
epochs 75/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9421053359383031, val_loss: 1.032270354346225
epochs 76/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9217497618574845, val_loss: 1.0364398843363711
epochs 77/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9204599816548197, val_loss: 1.0336539996297736
epochs 78/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9233517976183641, val_loss: 1.0432106557645295
epochs 79/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9076822086384422, val_loss: 1.121397162111182
epochs 80/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9097918874339054, val_loss: 1.051419704838803
epochs 81/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9860313776292299, val_loss: 1.2180472919815466
epochs 82/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9814598089770267, val_loss: 0.9732147037982941
epochs 83/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9315042683952733, val_loss: 1.0231291030582628
epochs 84/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9537558590110979, val_loss: 1.057892774280749
epochs 85/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9478478287395679, val_loss: 1.0276748876822621
epochs 86/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9343107392913417, val_loss: 1.0182693343413503
epochs 87/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9107649357695329, val_loss: 1.0380959115530315
epochs 88/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9235427881542005, val_loss: 1.0295583361073544
epochs 89/101

[I 2024-01-27 00:37:00,489] Trial 5 pruned.

Current Learning Rate: 0.021384851927701114
train_loss: 0.9131156212405155, val_loss: 1.038054358959198
epochs 90/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9242713642747779, val_loss: 1.056103680008336
epochs 91/101
Current Learning Rate: 0.021384851927701114
train_loss: 0.9126947619413075, val_loss: 1.0197625674699482
epochs 92/101
Starting fold 1:
epochs 1/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.1396014376690513, val_loss: 1.115527161798979
epochs 2/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.1242801791743229, val_loss: 1.100533548154329
epochs 3/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.1102867866817274, val_loss: 1.085584138569079
epochs 4/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.0928290580448352, val_loss: 1.07029548444246
epochs 5/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.0802352917821785, val_loss: 1.0544269499025847
epochs 6/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.0648527634771248, val_loss: 1.038049366599635
epochs 7/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.0459609822223062, val_loss: 1.021491597828112
epochs 8/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.0336756505464253, val_loss: 1.006473728230125
epochs 9/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.0192015334179527, val_loss: 0.9955809630845722
epochs 10/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.010290455190759, val_loss: 0.9910563343449643
epochs 11/137
Current Learning Rate: 0.0004390820578094482
train_loss: 1.0073355072423031, val_loss: 0.9916449747587505
epochs 12/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9937260891261853, val_loss: 0.9935290211125424
epochs 13/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9922742837353756, val_loss: 0.9938085518385235
epochs 14/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9998899522580599, val_loss: 0.99243609654276
epochs 15/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9921346218962418, val_loss: 0.9903758463106658
epochs 16/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.989244692576559, val_loss: 0.9887300353301199
epochs 17/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9890678537519355, val_loss: 0.9876027358205695
epochs 18/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9841696387843082, val_loss: 0.9871178488982352
epochs 19/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.992653406921186, val_loss: 0.9868326287520559
epochs 20/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9786376758625633, val_loss: 0.9867017118554366
epochs 21/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9916006960366902, val_loss: 0.9866993577856766
epochs 22/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9912488278589751, val_loss: 0.9866296730543438
epochs 23/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9903805657436974, val_loss: 0.9863491045801263
epochs 24/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9919608059682344, val_loss: 0.9858289831563046
epochs 25/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9847084955165261, val_loss: 0.9852945340307135
epochs 26/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9912635062870226, val_loss: 0.9846901692842183
epochs 27/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9811663276270817, val_loss: 0.9842147563633166
epochs 28/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.983579665108731, val_loss: 0.9839808012309827
epochs 29/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9840568667963931, val_loss: 0.9836357028860795
epochs 30/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9801337047627098, val_loss: 0.9833330530869333
epochs 31/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9820092314168026, val_loss: 0.9831496251256843
epochs 32/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9746622970229701, val_loss: 0.9827627345135338
epochs 33/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9761429604731108, val_loss: 0.9822994119242618
epochs 34/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9767569014900609, val_loss: 0.9813322644484671
epochs 35/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9699710099320663, val_loss: 0.9804162063096699
epochs 36/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9772265045266403, val_loss: 0.9796543547981664
epochs 37/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9686246326095179, val_loss: 0.9790539201937224
epochs 38/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9685589859360143, val_loss: 0.9792134862197073
epochs 39/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9646405401982759, val_loss: 0.9789819115086605
epochs 40/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9591499416451705, val_loss: 0.9793109379316631
epochs 41/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9565713775785346, val_loss: 0.9799862020894101
epochs 42/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9513137466029117, val_loss: 0.9794108328066374
epochs 43/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9499779669862044, val_loss: 0.9771343921360217
epochs 44/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9478586680010745, val_loss: 0.9795648863441065
epochs 45/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.945547596404427, val_loss: 0.9813544361214889
epochs 46/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9354067087173462, val_loss: 0.9825575263876664
epochs 47/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9389156780744854, val_loss: 0.9853496350740132
epochs 48/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9363215446472168, val_loss: 1.0064651213194196
epochs 49/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9321068857845507, val_loss: 0.9863900724210237
epochs 50/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9480501927827534, val_loss: 1.0611949305785329
epochs 51/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9660579016334132, val_loss: 0.9788467582903411
epochs 52/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9327026053478843, val_loss: 0.9799148747795506
epochs 53/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9458235985354373, val_loss: 0.9756865325726961
epochs 54/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9367768544899789, val_loss: 0.9870414972305298
epochs 55/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9364597904054742, val_loss: 0.9848719258057443
epochs 56/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9316862100049069, val_loss: 0.9814994736721642
epochs 57/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9271608898514195, val_loss: 0.9852363348007203
epochs 58/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9273431068972537, val_loss: 0.994029228310836
epochs 59/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9109989291743228, val_loss: 1.0002248864424856
epochs 60/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9109856925512615, val_loss: 0.9998158178831401
epochs 61/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9143073427049737, val_loss: 1.0157253039510628
epochs 62/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9160080357601769, val_loss: 1.0049629186329088
epochs 63/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9166956067085266, val_loss: 1.0073178655222843
epochs 64/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9121190359717921, val_loss: 1.0137507777465018
epochs 65/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9084159863622565, val_loss: 1.018144278777273
epochs 66/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9096468147478606, val_loss: 1.0330429328115363
epochs 67/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9071384662076046, val_loss: 1.0240737275073404
epochs 68/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9223808959910744, val_loss: 1.0378618165066367
epochs 69/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9231372965009589, val_loss: 1.0038814268614116
epochs 70/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9010866409853885, val_loss: 1.0044736899827655
epochs 71/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.899487092620448, val_loss: 1.0093171822397333
epochs 72/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9050094284509358, val_loss: 1.01655989697105
epochs 73/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9117797782546595, val_loss: 1.0177526022258558
epochs 74/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8997845009753579, val_loss: 1.0221621300044812
epochs 75/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8917085327600178, val_loss: 1.0289443066245632
epochs 76/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8982196418862594, val_loss: 1.0339820686139558
epochs 77/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8920708091635453, val_loss: 1.0409889058062904
epochs 78/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8962914837034125, val_loss: 1.0452507445686743
epochs 79/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8911093969094126, val_loss: 1.04190092086792
epochs 80/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8902758592053464, val_loss: 1.0437983450136687
epochs 81/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8842159917480067, val_loss: 1.0461370405397916
epochs 82/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8904756784439087, val_loss: 1.0378050666106375
epochs 83/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9053800683272513, val_loss: 1.036030115579304
epochs 84/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8837480977961891, val_loss: 1.0545924613350317
epochs 85/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8917746255272313, val_loss: 1.018055134070547
epochs 86/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9087793751766807, val_loss: 1.0200754655034918
epochs 87/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.9159606902222884, val_loss: 1.0273409479542783
epochs 88/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8992684521173177, val_loss: 1.0325643162978322
epochs 89/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8944252679222509, val_loss: 1.02745243624637
epochs 90/137

[I 2024-01-27 00:37:04,344] Trial 6 pruned.

Current Learning Rate: 0.0004390820578094482
train_loss: 0.8871408726039686, val_loss: 1.032851010874698
epochs 91/137
Current Learning Rate: 0.0004390820578094482
train_loss: 0.8924480557441712, val_loss: 1.0410422789423088
epochs 92/137
Starting fold 1:
epochs 1/140
Current Learning Rate: 0.03778794422065489
train_loss: 1.2151850599991647, val_loss: 1.179825735092163
epochs 2/140
Current Learning Rate: 0.03778794422065489
train_loss: 1.1578702255299216, val_loss: 1.0344706692193684
epochs 3/140
Current Learning Rate: 0.03778794422065489
train_loss: 1.0469464662827943, val_loss: 0.9990498843945955
epochs 4/140
Current Learning Rate: 0.03778794422065489
train_loss: 1.0207282210651196, val_loss: 0.992376239362516
epochs 5/140
Current Learning Rate: 0.03778794422065489
train_loss: 1.0003467173952805, val_loss: 0.9843075099744295
epochs 6/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9989312146839343, val_loss: 0.9841411581164912
epochs 7/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9987058968920457, val_loss: 0.9844446006574129
epochs 8/140
Current Learning Rate: 0.03778794422065489
train_loss: 1.0016241763767444, val_loss: 0.9838231880413858
epochs 9/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9966993793060905, val_loss: 0.984092313678641
epochs 10/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9978973708654705, val_loss: 0.9848555241760455
epochs 11/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.985376626253128, val_loss: 0.983859576049604
epochs 12/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9844156098993201, val_loss: 0.9808391655746259
epochs 13/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9837408583415183, val_loss: 0.9768653041438052
epochs 14/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9797784610798485, val_loss: 0.9759054441201059
epochs 15/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9721452860455764, val_loss: 0.9862279515517386
epochs 16/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9670881917602138, val_loss: 0.976215051977258
epochs 17/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9650512946279426, val_loss: 0.9788443245385823
epochs 18/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9445409966142554, val_loss: 0.9784224215306734
epochs 19/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9533531684624521, val_loss: 0.9864849965823325
epochs 20/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9277298343809027, val_loss: 0.9961087619003497
epochs 21/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9259345553423229, val_loss: 1.0032705727376436
epochs 22/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9304022669792176, val_loss: 1.0083148153204666
epochs 23/140
Current Learning Rate: 0.03778794422065489
train_loss: 1.0159300148487092, val_loss: 1.0078456433195817
epochs 24/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9628642245342857, val_loss: 0.9760627981863523
epochs 25/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9639894193724582, val_loss: 0.9849239851299085
epochs 26/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9848291538263622, val_loss: 0.9877397349006252
epochs 27/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9871178586232034, val_loss: 0.9807893304448378
epochs 28/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9853994567143289, val_loss: 0.9764982744267112
epochs 29/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9823902967729067, val_loss: 0.9785712019393319
epochs 30/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9683752828522733, val_loss: 0.9776858012927206
epochs 31/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9616790379348554, val_loss: 0.9731368867974532
epochs 32/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9575367243666398, val_loss: 0.9709604288402357
epochs 33/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9538357395874827, val_loss: 0.9681461014245686
epochs 34/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9452888981292122, val_loss: 0.9890453661742963
epochs 35/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.922580130162992, val_loss: 1.0007808751181553
epochs 36/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9745423116182026, val_loss: 1.0114469747794301
epochs 37/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.936920816647379, val_loss: 0.9699690194506394
epochs 38/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9371927888769852, val_loss: 0.978496535828239
epochs 39/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9514538601825112, val_loss: 0.9713083684444428
epochs 40/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9414908117369601, val_loss: 0.9730176668418081
epochs 41/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9345084871116437, val_loss: 0.9756744190266258
epochs 42/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9158233504546316, val_loss: 0.9916956032577314
epochs 43/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9236982784773174, val_loss: 0.9682203242653294
epochs 44/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9272156828328183, val_loss: 0.9768680070575915
epochs 45/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9062326271282999, val_loss: 0.9773995239483683
epochs 46/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9197028884762212, val_loss: 0.9839168366632963
epochs 47/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9176701994318711, val_loss: 0.9885636285731667
epochs 48/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9196026089944338, val_loss: 0.9896218353196194
epochs 49/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9095261664767015, val_loss: 0.9960073442835556
epochs 50/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9112921008938237, val_loss: 1.0009862686458386
epochs 51/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9084214474025526, val_loss: 1.006120408836164
epochs 52/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9008946970889443, val_loss: 1.0091852498681921
epochs 53/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8910433973136701, val_loss: 1.0222544143074437
epochs 54/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8983589162952021, val_loss: 1.058027891422573
epochs 55/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9173407689521187, val_loss: 1.0586864669072
epochs 56/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9860245613675368, val_loss: 0.9911363369540165
epochs 57/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9576349926622291, val_loss: 0.9716855121286292
epochs 58/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.941072258196379, val_loss: 0.9747499481627816
epochs 59/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9404226507011213, val_loss: 0.9724724022965682
epochs 60/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9217442048223395, val_loss: 0.9699310218033038
epochs 61/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9201588843998156, val_loss: 0.9720634494957171
epochs 62/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.917620795651486, val_loss: 0.9738505749326003
epochs 63/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9119991368369053, val_loss: 0.9838877655957875
epochs 64/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8974500511821948, val_loss: 0.9966288811282108
epochs 65/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8905658762705954, val_loss: 1.031974099498046
epochs 66/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9131550569283334, val_loss: 1.10732266338248
epochs 67/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.944814217718024, val_loss: 0.9872221435371198
epochs 68/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9235205333483847, val_loss: 0.9828341173498254
epochs 69/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9319366414296, val_loss: 0.9734240541332646
epochs 70/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9186585100073563, val_loss: 0.9710349220978586
epochs 71/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.914429162364257, val_loss: 0.9690598330999676
epochs 72/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9066854301251863, val_loss: 0.9699236763151069
epochs 73/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9198893948605186, val_loss: 0.9749042432559164
epochs 74/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9134924681563127, val_loss: 0.9809920329796641
epochs 75/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8960557780767742, val_loss: 0.993690245088778
epochs 76/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8946052372455597, val_loss: 1.0047593251654976
epochs 77/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8992222469103964, val_loss: 1.0168215309318742
epochs 78/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8841426877599013, val_loss: 1.0107509368344356
epochs 79/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9016646589103497, val_loss: 1.0137491734404314
epochs 80/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8842246598319004, val_loss: 1.0267517152585481
epochs 81/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.888400315610986, val_loss: 1.024929972698814
epochs 82/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.882572971519671, val_loss: 1.0243311204408345
epochs 83/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8922150135040283, val_loss: 1.031337026545876
epochs 84/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8744954269183309, val_loss: 1.0432876793961776
epochs 85/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8822694891377499, val_loss: 1.0482023540296053
epochs 86/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8668656678576219, val_loss: 1.0579300547900954
epochs 87/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8751171733203688, val_loss: 1.0276548843634756
epochs 88/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8748563289642334, val_loss: 1.0435014809432783
epochs 89/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.882505318365599, val_loss: 1.0139112764283231
epochs 90/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8985681684393632, val_loss: 1.0150022459657568
epochs 91/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9011243424917522, val_loss: 1.021329208424217
epochs 92/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8938842704421596, val_loss: 1.0443695294229607
epochs 93/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9106369818511763, val_loss: 1.0018918859331232
epochs 94/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8963226810881966, val_loss: 0.9867516605477584
epochs 95/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8953527899164903, val_loss: 0.988635183635511
epochs 96/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8990381394561968, val_loss: 1.0170372404550252
epochs 97/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8891459618744098, val_loss: 1.0537579850146646
epochs 98/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8779726276272222, val_loss: 1.0517282931428207
epochs 99/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8754713629421434, val_loss: 1.0215883829091725
epochs 100/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.911782255298213, val_loss: 1.0186412836375989
epochs 101/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9115474540936319, val_loss: 1.022249762635482
epochs 102/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.896061531807247, val_loss: 0.9904820423377187
epochs 103/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8850738029730948, val_loss: 0.9880695572024898
epochs 104/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8863421088770816, val_loss: 1.0004535013123563
epochs 105/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8800176921643709, val_loss: 1.022003009444789
epochs 106/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8766767712015855, val_loss: 1.0283122765390496
epochs 107/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8747597164229343, val_loss: 1.022162548805538
epochs 108/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8679734311605755, val_loss: 1.0397681597032045
epochs 109/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8834722710283179, val_loss: 1.041639479524211
epochs 110/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8591577423246284, val_loss: 1.0289375418110898
epochs 111/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8928879781773216, val_loss: 1.026349066119445
epochs 112/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8683111724100615, val_loss: 1.0456826931551884
epochs 113/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8751372556937368, val_loss: 1.0714583795321615
epochs 114/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8641688233927677, val_loss: 1.0611880760443837
epochs 115/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8534341507836392, val_loss: 1.0446529288040964
epochs 116/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8767634260027032, val_loss: 1.0460565259582117
epochs 117/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8607531236974817, val_loss: 1.0443556631866255
epochs 118/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8502437666842811, val_loss: 1.0365114917880611
epochs 119/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8683536777370855, val_loss: 1.0550418251439144
epochs 120/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8563816475240807, val_loss: 1.1274942774521677
epochs 121/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8893119350859994, val_loss: 1.0246507064292305
epochs 122/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8705751017520302, val_loss: 0.9965934000517193
epochs 123/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8785892169726522, val_loss: 0.9897829912210766
epochs 124/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.894968666214692, val_loss: 1.0122485421205822
epochs 125/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8822885466249366, val_loss: 1.0293159629169264
epochs 126/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8632936907441993, val_loss: 1.030781968330082
epochs 127/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9521069052972292, val_loss: 1.011877593868657
epochs 128/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9384284392783516, val_loss: 1.0090723872184753
epochs 129/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8930736171571831, val_loss: 1.0209944025466318
epochs 130/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8936215795968708, val_loss: 1.0121669132458537
epochs 131/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.8838910915349659, val_loss: 1.0293320207219374
epochs 132/140
Epoch 00132: reducing learning rate of group 0 to 5.3499e-03.
Current Learning Rate: 0.005349938799382975
train_loss: 0.8775361547344609, val_loss: 1.0370729364846882
epochs 133/140
Current Learning Rate: 0.005349938799382975
train_loss: 0.8720047160198814, val_loss: 1.0418846356241327
epochs 134/140
Current Learning Rate: 0.005349938799382975
train_loss: 0.8639056042621011, val_loss: 1.048228939583427
epochs 135/140
Current Learning Rate: 0.005349938799382975
train_loss: 0.8627657698957544, val_loss: 1.054043872105448
epochs 136/140
Current Learning Rate: 0.005349938799382975
train_loss: 0.8541893971593757, val_loss: 1.0602593905047366
epochs 137/140
Current Learning Rate: 0.005349938799382975
train_loss: 0.8361068866754833, val_loss: 1.0658888057658547
epochs 138/140
Current Learning Rate: 0.005349938799382975
train_loss: 0.8438191250750893, val_loss: 1.068437055537575
epochs 139/140
Current Learning Rate: 0.005349938799382975
train_loss: 0.8448174614655344, val_loss: 1.068757786876277
epochs 140/140
Current Learning Rate: 0.005349938799382975
train_loss: 0.8572413943315808, val_loss: 1.0689772574525132
Starting fold 2:
epochs 1/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9906184318818544, val_loss: 1.098479852550908
epochs 2/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9443164936806027, val_loss: 1.075486575929742
epochs 3/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9495913936903603, val_loss: 1.070225034889422
epochs 4/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9398870432063153, val_loss: 1.061793433365069
epochs 5/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9426062499222002, val_loss: 1.047743136631815
epochs 6/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9237358094830262, val_loss: 1.0558556782571893
epochs 7/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9305679876553384, val_loss: 1.0817993854221544
epochs 8/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9159656890128788, val_loss: 1.066751507708901
epochs 9/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9227721123318923, val_loss: 1.0738422770249216
epochs 10/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9153291561101612, val_loss: 1.0933332913800289
epochs 11/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.915029418311621, val_loss: 1.0647001548817283
epochs 12/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9220998726393047, val_loss: 1.061260295541663
epochs 13/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9257706519804503, val_loss: 1.0603091108171563
epochs 14/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9087512733120667, val_loss: 1.0673771425297385
epochs 15/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9157814766231336, val_loss: 1.0677926458810505
epochs 16/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9046266844398096, val_loss: 1.0907133190255416
epochs 17/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9041323875126086, val_loss: 1.080010223388672
epochs 18/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9024305354607732, val_loss: 1.090451224854118
epochs 19/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.895296544464011, val_loss: 1.0756144711845799
epochs 20/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9029221321407117, val_loss: 1.072875594465356
epochs 21/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9321895564857282, val_loss: 1.0668342791105572
epochs 22/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9336278132702175, val_loss: 1.055657912555494
epochs 23/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9213550959762774, val_loss: 1.049372731384478
epochs 24/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9152640276833585, val_loss: 1.0673155188560486
epochs 25/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9150606135004445, val_loss: 1.071886368174302
epochs 26/140
Current Learning Rate: 0.03778794422065489
train_loss: 0.9481033966729515, val_loss: 1.082032130893908
epochs 27/140
Current Learning Rate: 0.03778794422065489

[I 2024-01-27 00:38:00,684] Trial 7 finished with value: 1.2538213749702711 and parameters: {'batch_size': 81, 'epochs': 140, 'hidden_size': 43, 'learning_rate': 0.03778794422065489, 'dropout_prob': 0.13303181533959416, 'weight_decay': 1.1230366220723067e-06, 'lr_step_size': 98, 'gamma': 0.14157792676264985}. Best is trial 2 with value: 1.1692108569145203.

Current Learning Rate: 0.005349938799382975
train_loss: 0.9175221948247206, val_loss: 1.3124473195326956
Mean validation loss: 1.2538213749702711
Starting fold 1:
epochs 1/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0873821440495943, val_loss: 1.0979762434959413
epochs 2/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0889496533494247, val_loss: 1.0979424953460692
epochs 3/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0866796230015001, val_loss: 1.0979090841192949
epochs 4/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0873293224133944, val_loss: 1.0978754727463973
epochs 5/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0885895453001324, val_loss: 1.0978420364229302
epochs 6/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0876229888514468, val_loss: 1.0978085530431647
epochs 7/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0871966073387547, val_loss: 1.0977749416702671
epochs 8/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.086095860757326, val_loss: 1.0977414156261243
epochs 9/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0899227826218856, val_loss: 1.0977078939739027
epochs 10/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0871663833919325, val_loss: 1.097674282601005
epochs 11/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0870980814883584, val_loss: 1.0976406712281077
epochs 12/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.08661045839912, val_loss: 1.0976068421414025
epochs 13/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0867543954598275, val_loss: 1.0975730557190744
epochs 14/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0884358983290823, val_loss: 1.09753928247251
epochs 15/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0884417019392314, val_loss: 1.097505547498402
epochs 16/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0881724740329541, val_loss: 1.0974717742518374
epochs 17/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0862110445373936, val_loss: 1.0974379922214308
epochs 18/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0865020438244468, val_loss: 1.0974043720646909
epochs 19/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0880024514700237, val_loss: 1.0973706797549598
epochs 20/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0872320507702073, val_loss: 1.0973368211796408
epochs 21/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0861640836063184, val_loss: 1.0973033628965678
epochs 22/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0861853957176208, val_loss: 1.0972697515236705
epochs 23/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0867996981269434, val_loss: 1.097236178423229
epochs 24/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0864295212846053, val_loss: 1.097202558266489
epochs 25/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0882058105970684, val_loss: 1.0971688232923809
epochs 26/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0882611845668992, val_loss: 1.0971349985975969
epochs 27/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0851055013506037, val_loss: 1.097101016421067
epochs 28/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0859452122136166, val_loss: 1.0970673404241864
epochs 29/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0861529557328475, val_loss: 1.0970337717156662
epochs 30/130
Current Learning Rate: 1.452968487000971e-06
train_loss: 1.0886716892844752, val_loss: 1.09700040754519
epochs 31/130

[I 2024-01-27 00:38:02,035] Trial 8 pruned.

Current Learning Rate: 1.452968487000971e-06
train_loss: 1.086496158650047, val_loss: 1.0969672391289158
epochs 32/130
Starting fold 1:
epochs 1/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1190367159090544, val_loss: 1.1099882276434647
epochs 2/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.117969947112234, val_loss: 1.1096229465384233
epochs 3/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.117410817899202, val_loss: 1.109263240663629
epochs 4/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1184647133475856, val_loss: 1.1089072679218492
epochs 5/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1186281229320325, val_loss: 1.1085526290692782
epochs 6/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1173576605947395, val_loss: 1.108197131909822
epochs 7/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1180646068171451, val_loss: 1.1078420337877775
epochs 8/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1173655271530152, val_loss: 1.107488065016897
epochs 9/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1173696894394725, val_loss: 1.1071335817638197
epochs 10/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.117174341804103, val_loss: 1.1067785212868138
epochs 11/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1149303398634258, val_loss: 1.1064225962287502
epochs 12/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1162091330478066, val_loss: 1.1060658831345407
epochs 13/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1151282235195763, val_loss: 1.1057082251498573
epochs 14/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1158075771833722, val_loss: 1.105350933576885
epochs 15/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1144782066345216, val_loss: 1.104994763826069
epochs 16/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.113250990917808, val_loss: 1.1046373931985152
epochs 17/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1138843875182303, val_loss: 1.1042799046165064
epochs 18/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1135014935543663, val_loss: 1.1039212904478375
epochs 19/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.113652054887069, val_loss: 1.103561144126089
epochs 20/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1128553578728124, val_loss: 1.1032001068717554
epochs 21/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.111899175141987, val_loss: 1.1028370982722233
epochs 22/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1112714290618897, val_loss: 1.1024731535660592
epochs 23/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1119615241100913, val_loss: 1.1021095112750405
epochs 24/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1107322190937243, val_loss: 1.1017466168654593
epochs 25/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1112745636387875, val_loss: 1.1013824989921168
epochs 26/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1117891223807084, val_loss: 1.101017989610371
epochs 27/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1093992710113525, val_loss: 1.1006539796528063
epochs 28/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1106947158512317, val_loss: 1.1002886496092144
epochs 29/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.108599773206209, val_loss: 1.0999212754400154
epochs 30/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1084676290813245, val_loss: 1.0995545839008531
epochs 31/75
Current Learning Rate: 1.0641020541782451e-05
train_loss: 1.1086197200574373, val_loss: 1.0991868106942428
epochs 32/75

[I 2024-01-27 00:38:03,840] Trial 9 pruned.

Starting fold 1:
epochs 1/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0168787288038355, val_loss: 1.0280682968465906
epochs 2/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.016106968490701, val_loss: 1.0279115353759967
epochs 3/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0175718345140157, val_loss: 1.0277519633895473
epochs 4/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0165084766714196, val_loss: 1.0275940010422155
epochs 5/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0179690693554124, val_loss: 1.027437565514916
epochs 6/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0178153684264735, val_loss: 1.027282753116206
epochs 7/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0183266853031359, val_loss: 1.0271254401457937
epochs 8/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0182751856352155, val_loss: 1.0269710666254948
epochs 9/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0157027561413614, val_loss: 1.0268167169470537
epochs 10/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.01670392218389, val_loss: 1.0266612203497636
epochs 11/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0163685723354943, val_loss: 1.0265073205295363
epochs 12/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0171542842137187, val_loss: 1.0263580093258307
epochs 13/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0169731745594426, val_loss: 1.0262104163044377
epochs 14/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0161625586057965, val_loss: 1.026061159058621
epochs 15/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0176361441612243, val_loss: 1.025905251189282
epochs 16/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0146932021567696, val_loss: 1.0257509661348243
epochs 17/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0165591051704006, val_loss: 1.0255982336245084
epochs 18/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0163502589652413, val_loss: 1.0254468619823456
epochs 19/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.013588363245914, val_loss: 1.0252928824801193
epochs 20/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.015125334262848, val_loss: 1.0251396731326454
epochs 21/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0154051046622428, val_loss: 1.024986401984566
epochs 22/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.015359578948272, val_loss: 1.02483275877802
epochs 23/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0172332236641333, val_loss: 1.0246761218497629
epochs 24/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0146113304715407, val_loss: 1.0245178947323248
epochs 25/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0130979189747258, val_loss: 1.0243618039708389
epochs 26/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0153630946811876, val_loss: 1.0242058866902402
epochs 27/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0135454193541877, val_loss: 1.0240517503336857
epochs 28/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0144959512509797, val_loss: 1.0238976531907131
epochs 29/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0152743038378265, val_loss: 1.0237437279600845
epochs 30/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.015674193595585, val_loss: 1.0235861354752591
epochs 31/52
Current Learning Rate: 3.935590203081777e-05
train_loss: 1.0130105881314528, val_loss: 1.0234327730379607
epochs 32/52

[I 2024-01-27 00:38:05,378] Trial 10 pruned.

Starting fold 1:
epochs 1/149
Current Learning Rate: 0.0908146479576987
train_loss: 1.60284108550925, val_loss: 1.0343414262721413
epochs 2/149
Current Learning Rate: 0.0908146479576987
train_loss: 1.0357853346749355, val_loss: 1.0404959979810213
epochs 3/149
Current Learning Rate: 0.0908146479576987
train_loss: 1.0436339833234485, val_loss: 1.0043407349210036
epochs 4/149
Current Learning Rate: 0.0908146479576987
train_loss: 1.0176150234122026, val_loss: 0.9905902272776553
epochs 5/149
Current Learning Rate: 0.0908146479576987
train_loss: 1.009054151020552, val_loss: 0.9938091259253653
epochs 6/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9979832172393799, val_loss: 0.9909739008075312
epochs 7/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9961859097606257, val_loss: 0.9871434945809213
epochs 8/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9886494184795179, val_loss: 0.9888275140210202
epochs 9/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9939332667149996, val_loss: 0.9926019781514218
epochs 10/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9996120882661719, val_loss: 0.9943096088735681
epochs 11/149
Current Learning Rate: 0.0908146479576987
train_loss: 1.0023512071684788, val_loss: 0.994146936818173
epochs 12/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9994964160417256, val_loss: 0.9932726198121121
epochs 13/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9979786888549202, val_loss: 0.9915438012072915
epochs 14/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9931598101791582, val_loss: 0.9886643117979953
epochs 15/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9924693578167966, val_loss: 0.9854760013128582
epochs 16/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9916371530608127, val_loss: 0.9845888128406123
epochs 17/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9850965283418956, val_loss: 0.9850746377518302
epochs 18/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.982699282859501, val_loss: 0.9850480007497888
epochs 19/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9790996736601779, val_loss: 0.9846982014806647
epochs 20/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9770986139774323, val_loss: 0.9835409631854609
epochs 21/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9739101403637936, val_loss: 0.9798066553316618
epochs 22/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9651738969903243, val_loss: 0.974403169594313
epochs 23/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.971674553657833, val_loss: 0.9709430634975433
epochs 24/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9560550984583402, val_loss: 0.9711633120712481
epochs 25/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.939778618122402, val_loss: 0.9690694338396976
epochs 26/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9356898414461237, val_loss: 0.9696658488951231
epochs 27/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9319125758974176, val_loss: 0.9753901503588024
epochs 28/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9417061021453456, val_loss: 0.9753167833152571
epochs 29/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9277987637017903, val_loss: 0.9701735471424303
epochs 30/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9215214644607744, val_loss: 0.9712063921125311
epochs 31/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9167864103066293, val_loss: 0.9730249659011239
epochs 32/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9219479011861902, val_loss: 0.9740492246652904
epochs 33/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9260945335814827, val_loss: 0.9909147965280634
epochs 34/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9366551229828283, val_loss: 0.9789398939985978
epochs 35/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9147350270497171, val_loss: 0.9880111578263735
epochs 36/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9134843443569384, val_loss: 0.9860888547018954
epochs 37/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9104460211176622, val_loss: 0.9847543396447834
epochs 38/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8992157468670293, val_loss: 1.00530691052738
epochs 39/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9371991706521887, val_loss: 0.9835596602214011
epochs 40/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9170724467227334, val_loss: 0.9889961685004988
epochs 41/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9159545412189082, val_loss: 0.9824013537482211
epochs 42/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9167523697802895, val_loss: 0.9942057179777246
epochs 43/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9074824530827371, val_loss: 1.0134678686919965
epochs 44/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9161388748570493, val_loss: 0.9920205944462827
epochs 45/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9053051267799578, val_loss: 1.049457195558046
epochs 46/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9550149864272067, val_loss: 0.9786313552605478
epochs 47/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9307489991188049, val_loss: 0.9889280952905354
epochs 48/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9245548656112269, val_loss: 1.0040308174334074
epochs 49/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9338868762317457, val_loss: 0.9826894402503967
epochs 50/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9110720737984306, val_loss: 0.991264322870656
epochs 51/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9063223145510021, val_loss: 0.9989433351315951
epochs 52/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9160229532342208, val_loss: 0.9885092079639435
epochs 53/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8988692807523828, val_loss: 0.9980526566505432
epochs 54/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9073917097166965, val_loss: 0.9920366437811601
epochs 55/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9120891156949495, val_loss: 0.9940596018966875
epochs 56/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9029384725972226, val_loss: 1.0037904569977207
epochs 57/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9077085476172598, val_loss: 1.0133084623437179
epochs 58/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8989555678869549, val_loss: 1.018402294108742
epochs 59/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8999380234040713, val_loss: 1.0141012684295052
epochs 60/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9087011327869013, val_loss: 1.0307031587550515
epochs 61/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9427011750246349, val_loss: 0.9915740427217985
epochs 62/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.899024961810363, val_loss: 1.0301756529431594
epochs 63/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9281074467458224, val_loss: 0.9902982962758917
epochs 64/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.901958449890739, val_loss: 1.0158840308063908
epochs 65/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9212738432382283, val_loss: 0.9989958923113974
epochs 66/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9115566626975411, val_loss: 0.9884928119810004
epochs 67/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9025470049757707, val_loss: 1.0199478299994218
epochs 68/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.91144565532082, val_loss: 1.0112338395495164
epochs 69/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8998289970975173, val_loss: 1.0068117176231586
epochs 70/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.882232151533428, val_loss: 1.0286795418513448
epochs 71/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9121754530229067, val_loss: 0.995958116493727
epochs 72/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8925612317888361, val_loss: 1.0416978456472095
epochs 73/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9173044578025216, val_loss: 0.9901674797660426
epochs 74/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9106378759208479, val_loss: 1.0155931962163824
epochs 75/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9032364613131473, val_loss: 1.0247009647519965
epochs 76/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9051863692308727, val_loss: 0.990807404643611
epochs 77/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9119298363986769, val_loss: 1.0090255674562956
epochs 78/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8942502831157885, val_loss: 1.0246291411550421
epochs 79/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9007601706605208, val_loss: 0.9943077846577293
epochs 80/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8937164827396995, val_loss: 1.009110025669399
epochs 81/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8873506768753654, val_loss: 1.039659387186954
epochs 82/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9062793882269609, val_loss: 1.0006776216783022
epochs 83/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8949560350493381, val_loss: 1.023057647441563
epochs 84/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.9044046245123211, val_loss: 1.0244517263613249
epochs 85/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8908463528281764, val_loss: 0.9949885308742523
epochs 86/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8969095161086634, val_loss: 1.0277502819111473
epochs 87/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8811605368789873, val_loss: 1.0351518533731763
epochs 88/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.889226380147432, val_loss: 1.0147828522481417
epochs 89/149

[I 2024-01-27 00:38:08,779] Trial 11 pruned.

Current Learning Rate: 0.0908146479576987
train_loss: 0.8748966031952908, val_loss: 1.0370399010808844
epochs 90/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8765544781559392, val_loss: 1.0489753955288936
epochs 91/149
Current Learning Rate: 0.0908146479576987
train_loss: 0.8809815096227747, val_loss: 1.0413579815312435
epochs 92/149
Starting fold 1:
epochs 1/119
Current Learning Rate: 0.005311286039652717
train_loss: 1.0852869874552677, val_loss: 0.9919799967816002
epochs 2/119
Current Learning Rate: 0.005311286039652717
train_loss: 1.0023807293490359, val_loss: 0.9936822257543865
epochs 3/119
Current Learning Rate: 0.005311286039652717
train_loss: 1.0021952911427146, val_loss: 0.9911946516287954
epochs 4/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9964888898949874, val_loss: 0.9914117066483749
epochs 5/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9917977326794675, val_loss: 0.9878119393398888
epochs 6/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9865626981383876, val_loss: 0.9837616123651204
epochs 7/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9859582041439258, val_loss: 0.9819106942728946
epochs 8/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9837239240345202, val_loss: 0.9810992203260723
epochs 9/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9798672218071787, val_loss: 0.9805234356930381
epochs 10/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9765964031219483, val_loss: 0.9776492815268667
epochs 11/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9679094772589835, val_loss: 0.9753429005020543
epochs 12/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9649707969866301, val_loss: 0.975495770103053
epochs 13/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9564874843547219, val_loss: 0.9742969418826856
epochs 14/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9782101079037315, val_loss: 0.969233280734012
epochs 15/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9462788675960742, val_loss: 0.9693448148275676
epochs 16/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9468262408909045, val_loss: 0.9692267110473232
epochs 17/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9459620268721329, val_loss: 0.9697077355886761
epochs 18/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9398524227895235, val_loss: 0.9723034256382992
epochs 19/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9345581268009386, val_loss: 0.985266143397281
epochs 20/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9474877125338504, val_loss: 0.9717017958038732
epochs 21/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9160428254227889, val_loss: 0.9807758613636619
epochs 22/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.931638819292972, val_loss: 0.9809457415028622
epochs 23/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9206919525798999, val_loss: 1.0088406380854156
epochs 24/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9440651642648797, val_loss: 0.9694763447109022
epochs 25/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.921262264251709, val_loss: 0.9804449727660731
epochs 26/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.910469963676051, val_loss: 1.0303846127108525
epochs 27/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9828950787845411, val_loss: 0.9801013287745024
epochs 28/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.932801185783587, val_loss: 0.9755624896601627
epochs 29/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9304489474547537, val_loss: 0.9706000334338138
epochs 30/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9311761009065729, val_loss: 0.9738034260900397
epochs 31/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9205107983789946, val_loss: 0.9870512228263052
epochs 32/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9214547690592314, val_loss: 1.000308992988185
epochs 33/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9194362257656298, val_loss: 1.003737046844081
epochs 34/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9121924858344229, val_loss: 0.9972856076140153
epochs 35/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9056760160546554, val_loss: 1.0050977405748869
epochs 36/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9052961995727138, val_loss: 1.0137665209017301
epochs 37/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8966765090038902, val_loss: 1.0062545468932704
epochs 38/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9116545470137345, val_loss: 1.0042023457978901
epochs 39/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9086160346081382, val_loss: 0.9989796613392077
epochs 40/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9051888164721037, val_loss: 1.0014522257604097
epochs 41/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8967013001441956, val_loss: 1.0065664843509072
epochs 42/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8964566600950141, val_loss: 1.1013542451356586
epochs 43/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9451337531993264, val_loss: 1.0509451364216051
epochs 44/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9997395440151817, val_loss: 1.009575048873299
epochs 45/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9749036901875546, val_loss: 0.9760876090903031
epochs 46/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9565950814046358, val_loss: 0.9793310987321954
epochs 47/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9353533989504764, val_loss: 0.9773772496926157
epochs 48/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9288968801498413, val_loss: 0.9837558752612063
epochs 49/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9242512175911352, val_loss: 0.9856659180239628
epochs 50/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9189402875147368, val_loss: 0.992967636961686
epochs 51/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9112321640315809, val_loss: 1.0052146428509763
epochs 52/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9123784178181699, val_loss: 0.9896631416521574
epochs 53/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9072203121687237, val_loss: 0.9967417102111014
epochs 54/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9136568527472647, val_loss: 0.9878949566891319
epochs 55/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.903925557512986, val_loss: 1.0066464769212824
epochs 56/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9157839122571443, val_loss: 0.9924764695920443
epochs 57/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.895643969586021, val_loss: 1.0093009710311889
epochs 58/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9146984175631875, val_loss: 0.9830321907997132
epochs 59/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8987605276860688, val_loss: 0.9910954594612121
epochs 60/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9019488635816072, val_loss: 0.9913277563295866
epochs 61/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8955955254404169, val_loss: 1.0026139924400732
epochs 62/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8925173389284234, val_loss: 1.0079382099603351
epochs 63/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8816374057217649, val_loss: 0.9909377813339233
epochs 64/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9041294863349513, val_loss: 1.0462729924603513
epochs 65/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9416903050322282, val_loss: 0.9822709096105475
epochs 66/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9050301589463886, val_loss: 1.0188173394454152
epochs 67/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9307297712878178, val_loss: 0.9824157407409266
epochs 68/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9153326310609516, val_loss: 0.9719866250690661
epochs 69/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9025779768040306, val_loss: 0.9764643123275355
epochs 70/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8975751130204451, val_loss: 0.986990813832534
epochs 71/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8917122000142148, val_loss: 0.9988985513385974
epochs 72/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8820230973394294, val_loss: 0.9951330009259676
epochs 73/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8808415908562509, val_loss: 0.9954763356008027
epochs 74/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8764527041661112, val_loss: 1.0095290560471384
epochs 75/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8839676731511166, val_loss: 0.9891724166117216
epochs 76/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8985844787798429, val_loss: 0.9895657915818064
epochs 77/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8981749409123471, val_loss: 0.9755459735268041
epochs 78/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8871661468556052, val_loss: 0.9837828523234318
epochs 79/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.876097151480223, val_loss: 0.9982347431935762
epochs 80/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8751198919195878, val_loss: 0.9917525090669331
epochs 81/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8751339614391327, val_loss: 0.9915062942002949
epochs 82/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9244983604079798, val_loss: 0.9802322111631695
epochs 83/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.914532616891359, val_loss: 0.9760734049897445
epochs 84/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9233308541147333, val_loss: 0.9708902095493518
epochs 85/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.91947475483543, val_loss: 0.9766785772223222
epochs 86/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9142707467079163, val_loss: 0.990602487639377
epochs 87/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9094488281952707, val_loss: 0.9981621961844594
epochs 88/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.909475206701379, val_loss: 1.0039828099702535
epochs 89/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.9037124044016788, val_loss: 1.0043213442752237
epochs 90/119

[I 2024-01-27 00:38:13,163] Trial 12 pruned.

Current Learning Rate: 0.005311286039652717
train_loss: 0.9040585122610393, val_loss: 1.003162117380845
epochs 91/119
Current Learning Rate: 0.005311286039652717
train_loss: 0.8980875510918467, val_loss: 1.016677673239457
epochs 92/119
Starting fold 1:
epochs 1/82
Current Learning Rate: 0.09272410143556059
train_loss: 1.452366294358906, val_loss: 1.509892628067418
epochs 2/82
Current Learning Rate: 0.09272410143556059
train_loss: 1.4039576750052603, val_loss: 1.041958296926398
epochs 3/82
Current Learning Rate: 0.09272410143556059
train_loss: 1.039912277773807, val_loss: 1.0099679404183437
epochs 4/82
Current Learning Rate: 0.09272410143556059
train_loss: 1.0115076614053626, val_loss: 0.9930338034504338
epochs 5/82
Current Learning Rate: 0.09272410143556059
train_loss: 1.0103987552617726, val_loss: 0.988527964918237
epochs 6/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9942264738835787, val_loss: 0.9889224472798799
epochs 7/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9865423497400786, val_loss: 0.9908571444059673
epochs 8/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9868548170516366, val_loss: 0.992608506428568
epochs 9/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9860500144331079, val_loss: 0.9919027497893885
epochs 10/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9943182233132815, val_loss: 0.9896600227606924
epochs 11/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9812790989875794, val_loss: 0.9868421463589919
epochs 12/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9847267844175037, val_loss: 0.9843877350029192
epochs 13/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9702049763579118, val_loss: 0.9810868291478408
epochs 14/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9536373514878123, val_loss: 0.97688696133463
epochs 15/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9601592227032311, val_loss: 0.9737803694448973
epochs 16/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.940171451003928, val_loss: 0.9784631907939911
epochs 17/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9319365344549481, val_loss: 0.9705963348087512
epochs 18/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9447285570596394, val_loss: 0.9796148748774277
epochs 19/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9156326159050591, val_loss: 0.9879719552240873
epochs 20/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9130115273751711, val_loss: 0.9882519417687466
epochs 21/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9192936815713582, val_loss: 0.9987389799795653
epochs 22/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.932564798154329, val_loss: 0.9991901654946177
epochs 23/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9200700574799587, val_loss: 1.000289920129274
epochs 24/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9202490784619984, val_loss: 1.0007104704254552
epochs 25/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9048692449143059, val_loss: 1.0010841143758673
epochs 26/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9128726711398677, val_loss: 1.0186243461935143
epochs 27/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9255949992882578, val_loss: 1.0203809945206894
epochs 28/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9454459933858169, val_loss: 1.0242205974302794
epochs 29/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.906989871514471, val_loss: 1.0011501560085698
epochs 30/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.906920985485378, val_loss: 0.9811796608724093
epochs 31/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9185921370983123, val_loss: 0.983158781967665
epochs 32/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.908025093141355, val_loss: 1.030390971585324
epochs 33/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9298251948858562, val_loss: 0.9982966736743325
epochs 34/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9142195089867241, val_loss: 0.9896519068040346
epochs 35/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9135915530355353, val_loss: 0.9945058057182714
epochs 36/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8990850285479897, val_loss: 1.020378253334447
epochs 37/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9079421187701978, val_loss: 1.0062477541597266
epochs 38/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.897663499493348, val_loss: 0.9977050109913475
epochs 39/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9074663748866634, val_loss: 1.0103932838690908
epochs 40/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8991008404054139, val_loss: 1.0333659721048254
epochs 41/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9005890767825278, val_loss: 1.0115516123018766
epochs 42/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9033762549099169, val_loss: 1.0237524180035842
epochs 43/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8817120257176851, val_loss: 1.0227165015120254
epochs 44/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9179697384959773, val_loss: 1.0199872330615396
epochs 45/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9092083971751364, val_loss: 1.0272581624357324
epochs 46/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9102597493874399, val_loss: 1.0148268847089066
epochs 47/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8948696183530908, val_loss: 1.0152782901337272
epochs 48/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9029757948298204, val_loss: 1.0255576591742666
epochs 49/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8919825268419166, val_loss: 1.0788234359339663
epochs 50/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9482640573852941, val_loss: 1.095261635905818
epochs 51/82
Current Learning Rate: 0.09272410143556059
train_loss: 1.0174151762535697, val_loss: 1.0000587730031265
epochs 52/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9397976960006513, val_loss: 1.0407100840618735
epochs 53/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.945880180911014, val_loss: 1.025625052577571
epochs 54/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9400862856915123, val_loss: 0.9821013638847753
epochs 55/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9390086431252329, val_loss: 0.9749209444773824
epochs 56/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9335181305282995, val_loss: 0.9746255912278828
epochs 57/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9338207684065166, val_loss: 0.9731055407147658
epochs 58/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9269912456211291, val_loss: 0.9801601030324635
epochs 59/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9193280530603308, val_loss: 1.0002424566369308
epochs 60/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9312155158896195, val_loss: 0.9927669343195463
epochs 61/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9092856140513169, val_loss: 0.9832872349964945
epochs 62/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9184217139294273, val_loss: 0.9825194324317731
epochs 63/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.91048928687447, val_loss: 1.006279919963134
epochs 64/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9254388495495445, val_loss: 1.03752460322882
epochs 65/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9122003756071392, val_loss: 1.0148716537575972
epochs 66/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9052439052807657, val_loss: 1.008977411608947
epochs 67/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9071613355686791, val_loss: 1.0107932671120292
epochs 68/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9076215116601242, val_loss: 1.01442687762411
epochs 69/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9089125322668176, val_loss: 1.0115286996490076
epochs 70/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9062779009342193, val_loss: 1.012545030054293
epochs 71/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8866082492627596, val_loss: 1.0253001253855856
epochs 72/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8915707553687848, val_loss: 1.053600820114738
epochs 73/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9023588186816165, val_loss: 1.0677561722303692
epochs 74/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8845342014965258, val_loss: 1.062463985618792
epochs 75/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9051809649718435, val_loss: 1.066006971032996
epochs 76/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.88567259782239, val_loss: 1.0171261991325178
epochs 77/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8980063943486465, val_loss: 1.0473419973724767
epochs 78/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8985001419719897, val_loss: 1.0518333682888432
epochs 79/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9011854519969539, val_loss: 1.0111283797966806
epochs 80/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.8966796749516537, val_loss: 1.0799046453676726
epochs 81/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.89234535066705, val_loss: 1.0219049943120857
epochs 82/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9158902732949508, val_loss: 1.0015268764997785
Starting fold 2:
epochs 1/82
Current Learning Rate: 0.09272410143556059
train_loss: 1.1256595824894151, val_loss: 1.2118828980546248
epochs 2/82
Current Learning Rate: 0.09272410143556059
train_loss: 1.0174202555104306, val_loss: 1.1004903485900477
epochs 3/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9864575114689376, val_loss: 1.0630043782685932
epochs 4/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9745090606965516, val_loss: 1.029592962641465
epochs 5/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9674048571210159, val_loss: 1.0566353295978748
epochs 6/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9631615204246421, val_loss: 1.0292748507700469
epochs 7/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9466269235861929, val_loss: 1.0562698213677657
epochs 8/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9557880083197041, val_loss: 1.0366177094610114
epochs 9/82
Current Learning Rate: 0.09272410143556059
train_loss: 0.9495412486164193, val_loss: 1.0679562292600933
epochs 10/82

[I 2024-01-27 00:38:16,394] Trial 13 pruned.

Starting fold 1:
epochs 1/126
Current Learning Rate: 0.0025609585642455534
train_loss: 1.0912014214616073, val_loss: 1.0417685847533376
epochs 2/126
Current Learning Rate: 0.0025609585642455534
train_loss: 1.048058299014443, val_loss: 1.0083844561325876
epochs 3/126
Current Learning Rate: 0.0025609585642455534
train_loss: 1.0152916738861486, val_loss: 0.9990336493441933
epochs 4/126
Current Learning Rate: 0.0025609585642455534
train_loss: 1.0056912588445763, val_loss: 1.0058456834993865
epochs 5/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9976099782868435, val_loss: 0.999898436194972
epochs 6/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.99194001743668, val_loss: 0.9920830494479129
epochs 7/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9864000806682989, val_loss: 0.9882412901050166
epochs 8/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.989811983234004, val_loss: 0.9866523441515471
epochs 9/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9869394729011938, val_loss: 0.9858416588682878
epochs 10/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9881563785829042, val_loss: 0.9855130110916338
epochs 11/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9833926781227714, val_loss: 0.9858385613090114
epochs 12/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9827026975782294, val_loss: 0.9867951449594999
epochs 13/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9823930828194869, val_loss: 0.9877288322699698
epochs 14/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9804658070990914, val_loss: 0.987759238167813
epochs 15/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9758919066504428, val_loss: 0.9868404789974815
epochs 16/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9752952610191546, val_loss: 0.9854361370990151
epochs 17/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9726191457949187, val_loss: 0.9840626744847548
epochs 18/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9715243107394168, val_loss: 0.9826907904524552
epochs 19/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9690411269664765, val_loss: 0.9808847957535793
epochs 20/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9619343324711448, val_loss: 0.9788086122588108
epochs 21/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.961626410484314, val_loss: 0.9844361791485234
epochs 22/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9586495556329426, val_loss: 0.9833625448377509
epochs 23/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9562386785682879, val_loss: 0.9776971660162274
epochs 24/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9630024589990315, val_loss: 0.9813687531571639
epochs 25/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9485478526667545, val_loss: 0.9924900867437062
epochs 26/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9621559133655146, val_loss: 0.9828485921809548
epochs 27/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9548953012416237, val_loss: 0.9754859977646878
epochs 28/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9482731822289918, val_loss: 0.9833615039524279
epochs 29/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9448145176234998, val_loss: 0.9775505417271664
epochs 30/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9323275095538089, val_loss: 0.9865686391529284
epochs 31/126
Current Learning Rate: 0.0025609585642455534
train_loss: 0.9315588662498876, val_loss: 0.9922299265861512
epochs 32/126

[I 2024-01-27 00:38:17,888] Trial 14 pruned.

Starting fold 1:
epochs 1/110
Current Learning Rate: 0.020318019129925678
train_loss: 1.1501177150952189, val_loss: 1.0012678557320644
epochs 2/110
Current Learning Rate: 0.020318019129925678
train_loss: 1.01312667821583, val_loss: 1.0056160387239959
epochs 3/110
Current Learning Rate: 0.020318019129925678
train_loss: 1.0149313173796002, val_loss: 0.996326753653978
epochs 4/110
Current Learning Rate: 0.020318019129925678
train_loss: 1.006272693370518, val_loss: 0.9932349418338976
epochs 5/110
Current Learning Rate: 0.020318019129925678
train_loss: 1.00150680353767, val_loss: 0.992419047104685
epochs 6/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9954337578070791, val_loss: 0.9885143876075745
epochs 7/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.989708642896853, val_loss: 0.9850521178621995
epochs 8/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9929924139851019, val_loss: 0.9836966960053695
epochs 9/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9867716754737653, val_loss: 0.9833691995394858
epochs 10/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9882680434929697, val_loss: 0.9839739686564395
epochs 11/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.985350954846332, val_loss: 0.9844433144519203
epochs 12/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9789075688311928, val_loss: 0.9834478977479433
epochs 13/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9739554016213668, val_loss: 0.9801130429694527
epochs 14/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.971024133970863, val_loss: 0.9742980552347082
epochs 15/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9631112970803913, val_loss: 0.9709985334622232
epochs 16/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9555693105647438, val_loss: 0.9750481900415923
epochs 17/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9323046474080336, val_loss: 0.9961203396320343
epochs 18/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9397131097944159, val_loss: 1.0072777572431062
epochs 19/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.912948140031413, val_loss: 0.9949184091467607
epochs 20/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9396876532780497, val_loss: 0.9813289237649817
epochs 21/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9365586418854562, val_loss: 1.0234508059526746
epochs 22/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9319119767138833, val_loss: 0.9895389387482091
epochs 23/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9232856665786944, val_loss: 0.9944282315279308
epochs 24/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9254571964866236, val_loss: 0.9936763321098528
epochs 25/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9137772917747498, val_loss: 1.0382198631763457
epochs 26/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9256524531464828, val_loss: 1.0250800151573984
epochs 27/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.92282193585446, val_loss: 1.0887433447335895
epochs 28/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9922762067694413, val_loss: 0.9716850130181564
epochs 29/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9299588717912373, val_loss: 0.9767444547853972
epochs 30/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9427664606194747, val_loss: 0.9661701403166119
epochs 31/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.929329715590728, val_loss: 0.9655366097625934
epochs 32/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9269696812880667, val_loss: 0.9684021240786502
epochs 33/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9188337150372957, val_loss: 0.9713166415691376
epochs 34/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.917912052807055, val_loss: 0.9859485601124011
epochs 35/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9112430105083867, val_loss: 1.0048638698301817
epochs 36/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9092671221808384, val_loss: 1.0382635957316348
epochs 37/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9513490736484528, val_loss: 0.9760843186002028
epochs 38/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9125078511865515, val_loss: 0.9803748714296441
epochs 39/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9349377867422606, val_loss: 0.9628009887118089
epochs 40/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9238828812774859, val_loss: 0.9691485787692823
epochs 41/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.91974549544485, val_loss: 0.9756286128571159
epochs 42/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9154209331462257, val_loss: 0.9689652254706935
epochs 43/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9127215950112594, val_loss: 0.9710615352580422
epochs 44/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9153027691339192, val_loss: 0.9786003690016897
epochs 45/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9128535380488948, val_loss: 0.9879032705959521
epochs 46/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9101305105184254, val_loss: 0.984096510159342
epochs 47/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9018109396884316, val_loss: 1.0022585504933408
epochs 48/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9217517771218953, val_loss: 0.9892923775472139
epochs 49/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.894823181629181, val_loss: 0.9941744710269728
epochs 50/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9114798370160555, val_loss: 0.9939115565074118
epochs 51/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8927494830206821, val_loss: 1.0275738044788962
epochs 52/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9269961454366383, val_loss: 1.0040892679440347
epochs 53/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8980817051310288, val_loss: 1.0277523903470291
epochs 54/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9381642827862188, val_loss: 0.9666138376060285
epochs 55/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.924599582270572, val_loss: 0.9850367298251704
epochs 56/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9072018444538117, val_loss: 1.0298603415489196
epochs 57/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9020538596730483, val_loss: 1.0083995690471248
epochs 58/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8933730947343926, val_loss: 1.0093468402561387
epochs 59/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9199305352411772, val_loss: 1.00614643755712
epochs 60/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8987423015268226, val_loss: 1.0067237154433601
epochs 61/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9125041920887796, val_loss: 0.9790734937316493
epochs 62/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9111944744461461, val_loss: 0.9772185146808624
epochs 63/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9019137498579527, val_loss: 0.9900741379511984
epochs 64/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8994562534909499, val_loss: 0.9965587816740337
epochs 65/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8880294021807219, val_loss: 0.9983953893184662
epochs 66/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8779222143323798, val_loss: 1.0064733771901382
epochs 67/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8778284386584633, val_loss: 0.9855259845131322
epochs 68/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8735437961001146, val_loss: 1.0154696153967004
epochs 69/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8936442519489087, val_loss: 1.0083447563020806
epochs 70/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8863125531296981, val_loss: 1.019953116303996
epochs 71/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8945849688429581, val_loss: 1.015690127171968
epochs 72/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8761730203503056, val_loss: 1.03509555113943
epochs 73/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8967044014679758, val_loss: 1.0475607297922436
epochs 74/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9150722974225094, val_loss: 1.0538095248372932
epochs 75/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.940843499334235, val_loss: 0.9866450676792546
epochs 76/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9141176731962907, val_loss: 0.9840083410865382
epochs 77/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.895987953324067, val_loss: 0.9881527975985879
epochs 78/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8968173105465739, val_loss: 0.9977965311000222
epochs 79/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.890997734822725, val_loss: 0.9945288240909577
epochs 80/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8816992794212543, val_loss: 1.0060539926353254
epochs 81/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8753605961799622, val_loss: 1.0021134991394847
epochs 82/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8626109455761156, val_loss: 1.027441569064793
epochs 83/110
Epoch 00083: reducing learning rate of group 0 to 1.1214e-02.
Current Learning Rate: 0.011214222746543977
train_loss: 0.8636827575533014, val_loss: 1.0011805145364059
epochs 84/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.9103549800421062, val_loss: 1.0100853063558277
epochs 85/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.9374013615281959, val_loss: 1.0411884941552814
epochs 86/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8988726449640174, val_loss: 0.999334118240758
epochs 87/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8835119181557706, val_loss: 1.0184154661078202
epochs 88/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.9002288793262683, val_loss: 1.0001625371606726
epochs 89/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.9012309259489963, val_loss: 1.005238362676219
epochs 90/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8932718455791473, val_loss: 0.9877783019291727
epochs 91/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8781933204123848, val_loss: 0.990136684869465
epochs 92/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8597107909227673, val_loss: 1.0018961410773428
epochs 93/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.847568595723102, val_loss: 0.9886529596228348
epochs 94/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.9171273880883267, val_loss: 0.9857412523344944
epochs 95/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8966463873260899, val_loss: 0.981763483976063
epochs 96/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8826950211273996, val_loss: 0.9830582411665666
epochs 97/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8798792029681959, val_loss: 0.9889623052195499
epochs 98/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8789839619084409, val_loss: 0.9992331981658935
epochs 99/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8781493055193048, val_loss: 1.006690016232039
epochs 100/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8665359569223303, val_loss: 1.0163725219274822
epochs 101/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.855615315625542, val_loss: 1.025134032337289
epochs 102/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8569049132497687, val_loss: 1.0311028562094036
epochs 103/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8593888734516345, val_loss: 1.0148776593961213
epochs 104/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.9084329893714503, val_loss: 1.0298583313038474
epochs 105/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.885137867300134, val_loss: 1.014846804894899
epochs 106/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8722332192094703, val_loss: 0.9989781006386406
epochs 107/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8656141347006747, val_loss: 0.9920037595849288
epochs 108/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8659131862615285, val_loss: 1.0063128010222786
epochs 109/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8589793079777768, val_loss: 1.0124081884559832
epochs 110/110
Current Learning Rate: 0.011214222746543977
train_loss: 0.8582048535346984, val_loss: 1.0023946429553785
Starting fold 2:
epochs 1/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9539789286098982, val_loss: 1.2731471507172836
epochs 2/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9361644769969739, val_loss: 1.1584520321143301
epochs 3/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9297201241317549, val_loss: 1.1756493693903873
epochs 4/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9286309094805466, val_loss: 1.196454262106042
epochs 5/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.92802831060008, val_loss: 1.2358584761619569
epochs 6/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9270528264735874, val_loss: 1.2300213518895602
epochs 7/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9153243827192407, val_loss: 1.243713074608853
epochs 8/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9207679748535156, val_loss: 1.2496868315495944
epochs 9/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9180445481287806, val_loss: 1.2323234112639176
epochs 10/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.928479320124576, val_loss: 1.3418488671905116
epochs 11/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.920193812251091, val_loss: 1.34155647566444
epochs 12/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9225420951843262, val_loss: 1.2444945053050394
epochs 13/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9163483105207745, val_loss: 1.2045475031200208
epochs 14/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.922015200320043, val_loss: 1.2118270290525337
epochs 15/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9263072594215995, val_loss: 1.2842513015395716
epochs 16/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9081436949340921, val_loss: 1.1813899862138848
epochs 17/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.940696686349417, val_loss: 1.2163957620921888
epochs 18/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.928393427635494, val_loss: 1.0711885675003654
epochs 19/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9250499181057278, val_loss: 1.072618567943573
epochs 20/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9248380773945859, val_loss: 1.105699500284697
epochs 21/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9144514403845134, val_loss: 1.126488234181153
epochs 22/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9132733315229415, val_loss: 1.192752650536989
epochs 23/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9001277465569345, val_loss: 1.1075687982534108
epochs 24/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9087259982761584, val_loss: 1.2044174646076402
epochs 25/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9016228067247491, val_loss: 1.2014123057064257
epochs 26/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9070825506197778, val_loss: 1.096249006296459
epochs 27/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9151352002432472, val_loss: 1.1599803394392918
epochs 28/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9231348194574055, val_loss: 1.1064421895303225
epochs 29/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9054718563431188, val_loss: 1.1730622981723986
epochs 30/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8935597840108369, val_loss: 1.2404442335429944
epochs 31/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8978140303963109, val_loss: 1.1671131275202098
epochs 32/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9138780564069748, val_loss: 1.2385402729636745
epochs 33/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9005251407623291, val_loss: 1.1014602350561242
epochs 34/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.887376963307983, val_loss: 1.1671973435502303
epochs 35/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8865718058849635, val_loss: 1.240026883702529
epochs 36/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8935303799415889, val_loss: 1.1110019087791443
epochs 37/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.924027031189517, val_loss: 1.1449556520110682
epochs 38/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9252428385772203, val_loss: 1.150240367337277
epochs 39/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9112662560061404, val_loss: 1.364368268063194
epochs 40/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9156140743117583, val_loss: 1.2962950788046184
epochs 41/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.906333579515156, val_loss: 1.3187326575580396
epochs 42/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8943265858449434, val_loss: 1.4099743378789802
epochs 43/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8967946068236702, val_loss: 1.3211642566480135
epochs 44/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.914751252375151, val_loss: 1.4463602423667907
epochs 45/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8977333711950403, val_loss: 1.233268220173685
epochs 46/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9021276001867495, val_loss: 1.3014124336995576
epochs 47/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.928373088805299, val_loss: 1.1260183161810824
epochs 48/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9320997660097323, val_loss: 1.094601037000355
epochs 49/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9214945481011741, val_loss: 1.175710487052014
epochs 50/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9108593430958296, val_loss: 1.412725621775577
epochs 51/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9049632728099823, val_loss: 1.3126351745505083
epochs 52/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.9028375235043073, val_loss: 1.4907172968513087
epochs 53/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8934329301118851, val_loss: 1.4597277691489772
epochs 54/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8875067309329384, val_loss: 1.6154858746026692
epochs 55/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.887006446405461, val_loss: 1.3075589882700067
epochs 56/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8985048554445568, val_loss: 1.4013630647408335
epochs 57/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.8837751104643471, val_loss: 1.345820573129152
epochs 58/110
Current Learning Rate: 0.020318019129925678

[I 2024-01-27 00:38:34,495] Trial 15 pruned.

Current Learning Rate: 0.020318019129925678
train_loss: 0.9176018612426624, val_loss: 1.3113600793637727
epochs 51/110
Current Learning Rate: 0.020318019129925678
train_loss: 0.917997040560371, val_loss: 1.312080058298613
epochs 52/110
Starting fold 1:
epochs 1/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.1300947716361598, val_loss: 1.130751639918277
epochs 2/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.127791801251863, val_loss: 1.1275792724207827
epochs 3/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.123009541160182, val_loss: 1.1244690719403718
epochs 4/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.1211881060349314, val_loss: 1.1214039915486387
epochs 5/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.1171598873640363, val_loss: 1.1183914397892198
epochs 6/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.114783847959418, val_loss: 1.1154118123807406
epochs 7/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.1115955679040206, val_loss: 1.1124646575827348
epochs 8/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.1095635966250772, val_loss: 1.1095407498510261
epochs 9/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.1079130637018304, val_loss: 1.1066407241319356
epochs 10/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.1058220336311742, val_loss: 1.1037557564283673
epochs 11/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.101877666774549, val_loss: 1.100878868604961
epochs 12/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.1005624218990928, val_loss: 1.098007365276939
epochs 13/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0956138987290232, val_loss: 1.09515286746778
epochs 14/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0952561378479004, val_loss: 1.0923147025861237
epochs 15/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.093250624757064, val_loss: 1.08948722387615
epochs 16/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0909228387631869, val_loss: 1.0866591616680747
epochs 17/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0865055423033865, val_loss: 1.0838294280202765
epochs 18/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.084393122321681, val_loss: 1.0810006819273297
epochs 19/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0826353562505622, val_loss: 1.078154834948088
epochs 20/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0800109750346134, val_loss: 1.0753083643160368
epochs 21/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0806806125138935, val_loss: 1.0724831869727687
epochs 22/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.07417464632737, val_loss: 1.0696506588082564
epochs 23/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0736899852752686, val_loss: 1.0668055873168143
epochs 24/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0706935769633243, val_loss: 1.0639672856581839
epochs 25/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.068602550657172, val_loss: 1.061132610471625
epochs 26/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.065777305552834, val_loss: 1.0583028517271342
epochs 27/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.062351467734889, val_loss: 1.0554632337469803
epochs 28/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0598151972419336, val_loss: 1.0526155208286485
epochs 29/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.055392773527848, val_loss: 1.0497421239551745
epochs 30/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0546899757887187, val_loss: 1.0468742747055857
epochs 31/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0519459492281864, val_loss: 1.0440188646316528
epochs 32/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0477876274209275, val_loss: 1.0411628472177605
epochs 33/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0470724695607236, val_loss: 1.0383187883778622
epochs 34/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0427206033154537, val_loss: 1.035493598486248
epochs 35/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0406877856505545, val_loss: 1.032705222932916
epochs 36/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0387009507731388, val_loss: 1.0299568126076146
epochs 37/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0396708501012701, val_loss: 1.0272637003346494
epochs 38/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0338807771080418, val_loss: 1.0246115295510543
epochs 39/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.033127898918955, val_loss: 1.0220127055519506
epochs 40/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0295366607214276, val_loss: 1.0194668092225727
epochs 41/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.026904851511905, val_loss: 1.0169837173662688
epochs 42/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0253169166414362, val_loss: 1.014573745978506
epochs 43/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.021970580753527, val_loss: 1.012230302158155
epochs 44/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0165567485909712, val_loss: 1.0099625876075342
epochs 45/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.017098866010967, val_loss: 1.0077989126506606
epochs 46/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0174636508289137, val_loss: 1.0057568054450186
epochs 47/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0133492670561137, val_loss: 1.0038266075284858
epochs 48/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0149120770002666, val_loss: 1.0020257096541556
epochs 49/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0113602387277703, val_loss: 1.0003446258996662
epochs 50/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0077276443180285, val_loss: 0.9987703172784103
epochs 51/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0055121315153022, val_loss: 0.9972940244172749
epochs 52/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0049764557888634, val_loss: 0.9959241804323699
epochs 53/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0052189306208963, val_loss: 0.9946725424967314
epochs 54/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0024416754120276, val_loss: 0.9935287513230976
epochs 55/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0019544344199331, val_loss: 0.9925049926105298
epochs 56/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9965265098371003, val_loss: 0.9915870428085327
epochs 57/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9991567266614814, val_loss: 0.990772347073806
epochs 58/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9982140704205161, val_loss: 0.9900501320236608
epochs 59/66
Current Learning Rate: 0.0002473629221057499
train_loss: 1.0004292205760354, val_loss: 0.9894250568590666
epochs 60/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9931676500721982, val_loss: 0.9888704281104238
epochs 61/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9956904630911978, val_loss: 0.9883799101177014
epochs 62/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9953552390399732, val_loss: 0.9879550275049711
epochs 63/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9949816766538118, val_loss: 0.9875946804096825
epochs 64/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.995728515951257, val_loss: 0.9872889650495429
epochs 65/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9902067196996589, val_loss: 0.9870225912646243
epochs 66/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9979024667488902, val_loss: 0.9868011273835835
Starting fold 2:
epochs 1/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9908026390954068, val_loss: 1.1385319383520829
epochs 2/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9895397343133625, val_loss: 1.1391918420791627
epochs 3/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9895754751406218, val_loss: 1.139448891187969
epochs 4/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9893934754948867, val_loss: 1.1395414051256683
epochs 5/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9894953348134693, val_loss: 1.1395010571730764
epochs 6/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9863279587344119, val_loss: 1.139535012998079
epochs 7/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.990010929107666, val_loss: 1.139449361750954
epochs 8/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9891040811413213, val_loss: 1.13927203730533
epochs 9/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9898824566288998, val_loss: 1.1390565370258532
epochs 10/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9815965169354489, val_loss: 1.138915380678679
epochs 11/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9877879660380514, val_loss: 1.1387853384017945
epochs 12/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9882039430894349, val_loss: 1.1386221672359267
epochs 13/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9847700849959725, val_loss: 1.1383923681158767
epochs 14/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9843788002666675, val_loss: 1.1382466905995419
epochs 15/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.989618938847592, val_loss: 1.138001759428727
epochs 16/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9893446912890986, val_loss: 1.1377443125373439
epochs 17/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9854510279078232, val_loss: 1.1374924985986008
epochs 18/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9863279976342854, val_loss: 1.1372693312795539
epochs 19/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9877758509234378, val_loss: 1.13697501358233
epochs 20/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9870629015721772, val_loss: 1.1366144042266042
epochs 21/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9826664519937415, val_loss: 1.1362894409581235
epochs 22/66

[I 2024-01-27 00:38:38,621] Trial 16 pruned.

Current Learning Rate: 0.0002473629221057499
train_loss: 0.9861906346521879, val_loss: 1.136008445840133
epochs 23/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9891991251393368, val_loss: 1.1355856431157965
epochs 24/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9869314545079282, val_loss: 1.1350915143364355
epochs 25/66
Current Learning Rate: 0.0002473629221057499
train_loss: 0.9871151190055044, val_loss: 1.1346897200534218
epochs 26/66
Starting fold 1:
epochs 1/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0805717236117314, val_loss: 1.0872181221058494
epochs 2/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.078412183334953, val_loss: 1.087191326994645
epochs 3/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0789769015814128, val_loss: 1.0871647376763194
epochs 4/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0806747235749896, val_loss: 1.087137938800611
epochs 5/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0796338438987731, val_loss: 1.0871110865944311
epochs 6/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.080120717224322, val_loss: 1.0870842632494475
epochs 7/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.079275333881378, val_loss: 1.0870574769220853
epochs 8/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0784467803804498, val_loss: 1.0870306454206768
epochs 9/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0796548140676399, val_loss: 1.0870039042673614
epochs 10/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0795224503466958, val_loss: 1.0869770890788029
epochs 11/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.080245892625106, val_loss: 1.0869503479254874
epochs 12/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0807397265183298, val_loss: 1.0869232654571532
epochs 13/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0800557864339728, val_loss: 1.0868962036935907
epochs 14/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0806201765411778, val_loss: 1.0868694914014716
epochs 15/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0792871958331058, val_loss: 1.086842742091731
epochs 16/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.078956937789917, val_loss: 1.086815873572701
epochs 17/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0798098601792987, val_loss: 1.0867891368113065
epochs 18/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0798288132015028, val_loss: 1.0867624778496592
epochs 19/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0798522836283633, val_loss: 1.0867359751149228
epochs 20/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0801176623294229, val_loss: 1.0867093161532753
epochs 21/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.07963497262252, val_loss: 1.0866826490352028
epochs 22/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.078592762821599, val_loss: 1.0866558627078409
epochs 23/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0782402753829956, val_loss: 1.0866290845369038
epochs 24/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.079879293316289, val_loss: 1.0866022982095418
epochs 25/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0795350576701916, val_loss: 1.086575384516465
epochs 26/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0786436689527412, val_loss: 1.0865484545105382
epochs 27/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0784013371718557, val_loss: 1.086521495643415
epochs 28/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.080043613910675, val_loss: 1.0864946641420064
epochs 29/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0806491193018462, val_loss: 1.0864676764136867
epochs 30/90

[I 2024-01-27 00:38:40,211] Trial 17 pruned.

Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0792664872972588, val_loss: 1.086440693077288
epochs 31/90
Current Learning Rate: 1.0545604926314883e-06
train_loss: 1.0798066471752368, val_loss: 1.086413660174922
epochs 32/90
Starting fold 1:
epochs 1/149
Current Learning Rate: 0.014450388645547702
train_loss: 1.1345782154484798, val_loss: 1.0114446376499378
epochs 2/149
Current Learning Rate: 0.014450388645547702
train_loss: 1.0201571364151805, val_loss: 1.001671276594463
epochs 3/149
Current Learning Rate: 0.014450388645547702
train_loss: 1.0098316355755454, val_loss: 0.9996460676193237
epochs 4/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9948147033390246, val_loss: 0.9882693102485255
epochs 5/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9860460068050184, val_loss: 0.980858724368246
epochs 6/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9858093512685675, val_loss: 0.979565607874017
epochs 7/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.984528146292034, val_loss: 0.9812029349176508
epochs 8/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9808657294825504, val_loss: 0.9826254279989945
epochs 9/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9749871680611059, val_loss: 0.9794143877531353
epochs 10/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9690439450113397, val_loss: 0.9752679749539024
epochs 11/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.965101631064164, val_loss: 0.9721126117204365
epochs 12/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9549252484974108, val_loss: 0.972951518861871
epochs 13/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9491812618155229, val_loss: 0.982545018196106
epochs 14/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9369350169834337, val_loss: 0.985316232631081
epochs 15/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9216746405551308, val_loss: 1.0193527121292918
epochs 16/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9303754254391319, val_loss: 0.9941330269763344
epochs 17/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9257313703235827, val_loss: 1.0549470813650834
epochs 18/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9483532654611688, val_loss: 0.9907936610673603
epochs 19/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9678993727031507, val_loss: 0.96378556364461
epochs 20/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9457854597192061, val_loss: 0.9751572546206022
epochs 21/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9586762942765888, val_loss: 0.9774340579384252
epochs 22/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9378296701531661, val_loss: 0.9801095535880641
epochs 23/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9308788588172511, val_loss: 0.979220754221866
epochs 24/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9186846017837524, val_loss: 0.9726830532676295
epochs 25/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9304373138829282, val_loss: 0.9679885945822063
epochs 26/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9204501854745966, val_loss: 0.9798086505187186
epochs 27/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9214760127820467, val_loss: 0.9863235385794389
epochs 28/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9078272581100464, val_loss: 1.0079475766734074
epochs 29/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9277124655874152, val_loss: 0.9878273261220831
epochs 30/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9013596459438926, val_loss: 0.9932747263657419
epochs 31/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9207305406269274, val_loss: 0.9876741610075298
epochs 32/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8983053345429269, val_loss: 1.0170134054987054
epochs 33/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9363781151018644, val_loss: 0.9996718795675981
epochs 34/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8978190547541568, val_loss: 1.0041325155057406
epochs 35/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9168057002519306, val_loss: 0.9685190947432267
epochs 36/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9136794554559808, val_loss: 0.9779002164539538
epochs 37/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9137671997672633, val_loss: 0.9903894349148399
epochs 38/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9007019996643066, val_loss: 0.9976101925498561
epochs 39/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8977722870676141, val_loss: 0.9944169897782175
epochs 40/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8896016007975528, val_loss: 1.02721989782233
epochs 41/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9079470320751792, val_loss: 1.0269377419823094
epochs 42/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9099154848801462, val_loss: 0.9929642112631547
epochs 43/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9243852151067633, val_loss: 0.9827032967617637
epochs 44/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8944579111902338, val_loss: 1.0146361714915226
epochs 45/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.904860728665402, val_loss: 0.9894554615020752
epochs 46/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8879124616321764, val_loss: 1.0386583679600765
epochs 47/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8950354174563759, val_loss: 1.011114660062288
epochs 48/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.917967300666006, val_loss: 1.1291972524241398
epochs 49/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.937565194933038, val_loss: 0.9845944799874958
epochs 50/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9485104021273161, val_loss: 0.9638767932590685
epochs 51/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9185647274318495, val_loss: 0.9808370816080194
epochs 52/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9379340535716006, val_loss: 0.9743042117670963
epochs 53/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9231471262480083, val_loss: 0.9797161441100272
epochs 54/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9095143581691542, val_loss: 0.9954075060392681
epochs 55/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9071196756864849, val_loss: 0.9898977028696161
epochs 56/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8984700566843936, val_loss: 0.9997214078903198
epochs 57/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8952643118406597, val_loss: 0.9900164980637399
epochs 58/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8971227658422369, val_loss: 1.0223315264049329
epochs 59/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9256548128629986, val_loss: 0.9818047034113031
epochs 60/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9105038956591958, val_loss: 0.991906862509878
epochs 61/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8921918304342973, val_loss: 1.0632933315477873
epochs 62/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9119348463259245, val_loss: 1.0642935476805035
epochs 63/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9057627351660478, val_loss: 1.1558911110225476
epochs 64/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9356759472897178, val_loss: 1.0022194573753758
epochs 65/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9227143212368614, val_loss: 1.015757447794864
epochs 66/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9043555824380172, val_loss: 1.0516300640608136
epochs 67/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9149509605608488, val_loss: 1.0366888234489842
epochs 68/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9062729321028057, val_loss: 1.0358930826187134
epochs 69/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8978405500713148, val_loss: 1.054144953426562
epochs 70/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8940483833614149, val_loss: 1.021269208506534
epochs 71/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8905393889075831, val_loss: 0.9945357410531295
epochs 72/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8847370963347586, val_loss: 1.0526615757691233
epochs 73/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8818523915190446, val_loss: 1.0338720208720158
epochs 74/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8812146782875061, val_loss: 1.0729496541776156
epochs 75/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8892545825556705, val_loss: 1.0580997153332359
epochs 76/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8984909747776232, val_loss: 1.1745294081537347
epochs 77/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9562616881571318, val_loss: 0.9785869937194022
epochs 78/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9251943199258101, val_loss: 0.9882521441108302
epochs 79/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.9005816359268991, val_loss: 1.0830523654034263
epochs 80/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.89185337016457, val_loss: 1.096388948591132
epochs 81/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8859544365029586, val_loss: 1.0425465546156232
epochs 82/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8801157443146956, val_loss: 1.08336247268476
epochs 83/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8685187258218464, val_loss: 1.009190415081225
epochs 84/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8671308097086454, val_loss: 1.0132596116316945
epochs 85/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8848675740392584, val_loss: 0.9939712913412797
epochs 86/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8947028423610487, val_loss: 0.9737138371718558
epochs 87/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8830449988967494, val_loss: 0.9812418096943906
epochs 88/149
Current Learning Rate: 0.014450388645547702
train_loss: 0.8844382041379025, val_loss: 1.1080289388957776
epochs 89/149
Epoch 00089: reducing learning rate of group 0 to 8.5892e-03.
Current Learning Rate: 0.008589169618451697
train_loss: 0.881116625509764, val_loss: 1.142480680817052
epochs 90/149

[I 2024-01-27 00:38:44,066] Trial 18 pruned.

Current Learning Rate: 0.008589169618451697
train_loss: 0.8723533279017398, val_loss: 1.148864231611553
epochs 91/149
Current Learning Rate: 0.008589169618451697
train_loss: 0.8670073622151425, val_loss: 1.1500926707920276
epochs 92/149
Starting fold 1:
epochs 1/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.1099153706901952, val_loss: 1.1100966152391936
epochs 2/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.100552173037278, val_loss: 1.0994292554102445
epochs 3/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0925734632893613, val_loss: 1.089130539643137
epochs 4/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0822499181094922, val_loss: 1.0789506109137283
epochs 5/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0741309216147974, val_loss: 1.0688393228932431
epochs 6/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0651850336476376, val_loss: 1.0587553375645689
epochs 7/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0588350095246968, val_loss: 1.0487520908054553
epochs 8/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0465483941529927, val_loss: 1.0388277342444971
epochs 9/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0386757191858793, val_loss: 1.0290635221882871
epochs 10/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0316374323870006, val_loss: 1.0196870013287194
epochs 11/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0236477905198147, val_loss: 1.0109893049064436
epochs 12/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0168586875263013, val_loss: 1.0033326760718697
epochs 13/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.009641823956841, val_loss: 0.997084628594549
epochs 14/132
Current Learning Rate: 0.0006241200170636668
train_loss: 1.0047993716440702, val_loss: 0.9925814804277922
epochs 15/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9978788705248581, val_loss: 0.9899132229779896
epochs 16/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9972892576142361, val_loss: 0.9888635939673374
epochs 17/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9968127664766814, val_loss: 0.9889130570386585
epochs 18/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9947705570020173, val_loss: 0.9893864361863387
epochs 19/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9917304082920677, val_loss: 0.9897631692258935
epochs 20/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9922746034044968, val_loss: 0.9898092894177688
epochs 21/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9889966343578539, val_loss: 0.9895501262263248
epochs 22/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9923079302436427, val_loss: 0.9890628212376644
epochs 23/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9911323980281227, val_loss: 0.9885449174203371
epochs 24/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9887001671289143, val_loss: 0.9880882520424692
epochs 25/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9899850801417702, val_loss: 0.9877357448402204
epochs 26/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9862713782410872, val_loss: 0.9874913588950508
epochs 27/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9871483354192031, val_loss: 0.9873031769928179
epochs 28/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9898780352190921, val_loss: 0.9871449100343804
epochs 29/132

[I 2024-01-27 00:38:45,477] Trial 19 pruned.

Current Learning Rate: 0.0006241200170636668
train_loss: 0.9878434127882907, val_loss: 0.9870119210920836
epochs 30/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9905362753491652, val_loss: 0.9868909503284253
epochs 31/132
Current Learning Rate: 0.0006241200170636668
train_loss: 0.9891110925297988, val_loss: 0.9867669265521201
epochs 32/132
Starting fold 1:
epochs 1/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.10902616663983, val_loss: 1.1014474216260408
epochs 2/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1078292708647879, val_loss: 1.101350304327513
epochs 3/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.109795579784795, val_loss: 1.1012544104927464
epochs 4/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1087457656860351, val_loss: 1.1011588021328576
epochs 5/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1099503015217027, val_loss: 1.1010637007261577
epochs 6/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1096060878352114, val_loss: 1.100968941261894
epochs 7/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.109561380587126, val_loss: 1.100873733821668
epochs 8/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1096570178082115, val_loss: 1.100778497520246
epochs 9/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1089524946714702, val_loss: 1.1006831564401325
epochs 10/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1083803722732946, val_loss: 1.1005876817201312
epochs 11/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1074331791777359, val_loss: 1.100492324954585
epochs 12/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1088206924890216, val_loss: 1.1003971921770197
epochs 13/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1081816271731728, val_loss: 1.1003016271089252
epochs 14/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1089880033543236, val_loss: 1.1002055707730745
epochs 15/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.107961420636428, val_loss: 1.1001098262636284
epochs 16/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1087609485576027, val_loss: 1.1000136927554482
epochs 17/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1077083073164287, val_loss: 1.0999172762820595
epochs 18/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.107549716296949, val_loss: 1.0998209187858983
epochs 19/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1080272166352523, val_loss: 1.0997243818483855
epochs 20/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1075372419859233, val_loss: 1.0996282182241741
epochs 21/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1080057658647235, val_loss: 1.099532367681202
epochs 22/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1086880426657828, val_loss: 1.0994368314743042
epochs 23/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1076927304267883, val_loss: 1.0993413084431698
epochs 24/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1069581226298684, val_loss: 1.0992460696320785
epochs 25/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1072962478587502, val_loss: 1.0991505478557788
epochs 26/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1060298204421997, val_loss: 1.0990553837073476
epochs 27/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1078468479608234, val_loss: 1.098960324337608
epochs 28/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1067057026060003, val_loss: 1.0988653540611266
epochs 29/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1073543818373428, val_loss: 1.0987703837846454
epochs 30/116
Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1076759231717963, val_loss: 1.098675384646968
epochs 31/116

[I 2024-01-27 00:38:46,991] Trial 20 pruned.

Current Learning Rate: 4.622461847599261e-06
train_loss: 1.1073883420542667, val_loss: 1.0985804444865177
epochs 32/116
Starting fold 1:
epochs 1/104
Current Learning Rate: 0.006395454163023793
train_loss: 1.091540224928605, val_loss: 1.0024520692072416
epochs 2/104
Current Learning Rate: 0.006395454163023793
train_loss: 1.0376381215296293, val_loss: 0.9877559059544614
epochs 3/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9872190337432059, val_loss: 0.9840110684695996
epochs 4/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.992000537169607, val_loss: 0.9822765199761642
epochs 5/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9900548941210696, val_loss: 0.9827484149681894
epochs 6/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9867710584088376, val_loss: 0.9836379785286753
epochs 7/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9799088785522863, val_loss: 0.9813887445550216
epochs 8/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.974457207478975, val_loss: 0.9786500711190073
epochs 9/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9723894370229621, val_loss: 0.9760022621405752
epochs 10/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9676172275292246, val_loss: 0.9723865496484857
epochs 11/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9560219287872315, val_loss: 0.9739601612091064
epochs 12/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9567514036831103, val_loss: 0.9761029889709071
epochs 13/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9381703307754115, val_loss: 1.0047099897735998
epochs 14/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9653295523241947, val_loss: 0.981175256402869
epochs 15/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9476184142263312, val_loss: 0.969141709804535
epochs 16/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9325675368309021, val_loss: 0.9658453759394194
epochs 17/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9413933044985721, val_loss: 0.9668101392294232
epochs 18/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9315647018583197, val_loss: 0.9776871336133857
epochs 19/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9196247596489756, val_loss: 0.9696885648526643
epochs 20/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.919920437586935, val_loss: 0.9679262663188734
epochs 21/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9199080216257196, val_loss: 0.9700714569342764
epochs 22/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9156276426817241, val_loss: 0.981076651497891
epochs 23/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9137239343241641, val_loss: 0.9838366646515696
epochs 24/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9055133913692676, val_loss: 1.0436879653679698
epochs 25/104
Current Learning Rate: 0.006395454163023793
train_loss: 1.0029300790084035, val_loss: 1.023241686820984
epochs 26/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9286441213206241, val_loss: 1.0403498266872606
epochs 27/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9703112646153099, val_loss: 0.9774111402662177
epochs 28/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9493319900412308, val_loss: 0.9804126676760222
epochs 29/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9439499171156632, val_loss: 0.9697054900621113
epochs 30/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9254223202404223, val_loss: 0.9717287797676889
epochs 31/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9284227835504633, val_loss: 0.9733151071950009
epochs 32/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9229077571316769, val_loss: 0.9824747838472065
epochs 33/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.916349773030532, val_loss: 0.9834357387141177
epochs 34/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.91347895860672, val_loss: 0.9763915501142802
epochs 35/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9088870713585302, val_loss: 0.9759410036237617
epochs 36/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9062656164169312, val_loss: 0.9796776043741326
epochs 37/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9073182990676478, val_loss: 0.9816318179431714
epochs 38/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8975879073143005, val_loss: 0.9890009572631434
epochs 39/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.897278514661287, val_loss: 0.9999121703599628
epochs 40/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9000993232978017, val_loss: 1.0220184803009034
epochs 41/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.950082234332436, val_loss: 0.9718877993131939
epochs 42/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9146432380927236, val_loss: 1.0043721205309817
epochs 43/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9132557122330917, val_loss: 0.9717121845797488
epochs 44/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9202120724477266, val_loss: 0.9715673189414175
epochs 45/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9217234040561475, val_loss: 0.9753363395992078
epochs 46/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9067835312140615, val_loss: 1.004539154077831
epochs 47/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.934875604353453, val_loss: 0.972202573951922
epochs 48/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9026570803240725, val_loss: 0.9688468268043117
epochs 49/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9113474889805443, val_loss: 0.9722749710083007
epochs 50/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9030470628487436, val_loss: 0.9793885588645935
epochs 51/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8953645135227003, val_loss: 0.9820038644891036
epochs 52/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9017225522744028, val_loss: 0.9839564693601508
epochs 53/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8967965860115854, val_loss: 0.989820903225949
epochs 54/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8857773918854562, val_loss: 1.000838221374311
epochs 55/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.883287963741704, val_loss: 1.0086640759518273
epochs 56/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8801869706103677, val_loss: 1.0151489050764786
epochs 57/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9729943633079529, val_loss: 0.9722839418210482
epochs 58/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9039918140361184, val_loss: 0.9829724863955849
epochs 59/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.897590768964667, val_loss: 0.9886391796563802
epochs 60/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8782523995951602, val_loss: 1.0008169393790396
epochs 61/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.879695283111773, val_loss: 1.000317893530193
epochs 62/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8800405897592244, val_loss: 1.0276696807459782
epochs 63/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8634522870967263, val_loss: 0.9805646256396645
epochs 64/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8798606897655287, val_loss: 0.9718456556922511
epochs 65/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9051777337726794, val_loss: 0.9734628545610529
epochs 66/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8802734582047713, val_loss: 0.9908455026777168
epochs 67/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8723126411437988, val_loss: 1.0137026115467673
epochs 68/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.874347458387676, val_loss: 1.0037547600896735
epochs 69/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9064252257347107, val_loss: 0.9746684714367515
epochs 70/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9211435343089857, val_loss: 0.9663230299949646
epochs 71/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9247301302458111, val_loss: 0.9734438632663928
epochs 72/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9066052499570345, val_loss: 0.9718358159065247
epochs 73/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.898927450807471, val_loss: 0.9774094744732506
epochs 74/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8954116237790961, val_loss: 0.9907386829978542
epochs 75/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8883015500871758, val_loss: 0.9826580317396867
epochs 76/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.893755316734314, val_loss: 0.9750284627864235
epochs 77/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8920196457913048, val_loss: 0.9861186836895189
epochs 78/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8808606630877445, val_loss: 0.9876152471492164
epochs 79/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8658379673957824, val_loss: 1.0049811137349982
epochs 80/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8847528005901136, val_loss: 1.0081714717965378
epochs 81/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9233254068776181, val_loss: 0.9724118627999958
epochs 82/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9103910421070299, val_loss: 0.9878226851162157
epochs 83/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.9005320053351553, val_loss: 0.9833878159523011
epochs 84/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8924801895492955, val_loss: 0.9892527887695715
epochs 85/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.895761942236047, val_loss: 0.9915559580451564
epochs 86/104
Current Learning Rate: 0.006395454163023793
train_loss: 0.8903372068154184, val_loss: 0.9978920754633451
epochs 87/104
Epoch 00087: reducing learning rate of group 0 to 1.5617e-03.
Current Learning Rate: 0.0015616875390252608
train_loss: 0.885625684261322, val_loss: 0.9949277444889671
epochs 88/104
Current Learning Rate: 0.0015616875390252608
train_loss: 0.8839311580908926, val_loss: 0.9977841690966958
epochs 89/104
Current Learning Rate: 0.0015616875390252608
train_loss: 0.8843468490399813, val_loss: 1.0047668751917387
epochs 90/104
Current Learning Rate: 0.0015616875390252608
train_loss: 0.8788839026501304, val_loss: 1.0129950441812214
epochs 91/104

[I 2024-01-27 00:38:51,081] Trial 21 pruned.

Current Learning Rate: 0.0015616875390252608
train_loss: 0.876939949236418, val_loss: 1.015994401981956
epochs 92/104
Starting fold 1:
epochs 1/95
Current Learning Rate: 0.0015324914086730355
train_loss: 1.1012211266316865, val_loss: 1.0655725259529918
epochs 2/95
Current Learning Rate: 0.0015324914086730355
train_loss: 1.0678230034677605, val_loss: 1.0372662280735216
epochs 3/95
Current Learning Rate: 0.0015324914086730355
train_loss: 1.0421459285836472, val_loss: 1.0123477047995517
epochs 4/95
Current Learning Rate: 0.0015324914086730355
train_loss: 1.0185999330721403, val_loss: 0.9975802892132809
epochs 5/95
Current Learning Rate: 0.0015324914086730355
train_loss: 1.0049420670459146, val_loss: 0.9990293490259271
epochs 6/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9981080108567288, val_loss: 1.0014083721135791
epochs 7/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9923569735727812, val_loss: 0.9963567125169854
epochs 8/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9868032078993948, val_loss: 0.9908137424996025
epochs 9/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9848586574981087, val_loss: 0.9874750990616648
epochs 10/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9855801362740366, val_loss: 0.9858089713673842
epochs 11/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9851059728547147, val_loss: 0.9851042132628591
epochs 12/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9841942542477657, val_loss: 0.9850223807912124
epochs 13/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9840615404279609, val_loss: 0.9852180578206715
epochs 14/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9812140994950345, val_loss: 0.9853355671230115
epochs 15/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9817940975490369, val_loss: 0.9850135636957068
epochs 16/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9788185213741504, val_loss: 0.9843509984643836
epochs 17/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9774416214541385, val_loss: 0.983457949287013
epochs 18/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9758510065706153, val_loss: 0.9824516227370814
epochs 19/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.974376611646853, val_loss: 0.9812627566488166
epochs 20/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9724215887094799, val_loss: 0.9796700546616002
epochs 21/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9696449323704368, val_loss: 0.9777564114645908
epochs 22/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9658955050142188, val_loss: 0.9757781907131797
epochs 23/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9635651462956478, val_loss: 0.9738884919568112
epochs 24/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9597508257941196, val_loss: 0.9708658224657962
epochs 25/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9785992060836993, val_loss: 0.9730340744319715
epochs 26/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9574412261184894, val_loss: 0.9778768373163123
epochs 27/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9666270714057119, val_loss: 0.9750359993231924
epochs 28/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9627282500267029, val_loss: 0.9735159290464301
epochs 29/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9579496342884867, val_loss: 0.9779078273396743
epochs 30/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.952786439029794, val_loss: 0.9797970266718613
epochs 31/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9450846618727634, val_loss: 0.9734483232623652
epochs 32/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9379578844497078, val_loss: 0.9692244065435309
epochs 33/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9327725739855516, val_loss: 0.9787395765906886
epochs 34/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9278809857995887, val_loss: 0.9915786642777292
epochs 35/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9174814305807415, val_loss: 0.9757749839832909
epochs 36/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.914741302477686, val_loss: 0.9865358892240023
epochs 37/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9091822003063402, val_loss: 0.9821911567135861
epochs 38/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9048995256423951, val_loss: 0.9861404647952632
epochs 39/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.903126017984591, val_loss: 0.998700541571567
epochs 40/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9006061770414051, val_loss: 1.0033698941531934
epochs 41/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8995384934701418, val_loss: 0.9790518481480448
epochs 42/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9031715631484986, val_loss: 1.0404900990034405
epochs 43/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.906578089375245, val_loss: 0.9566225575773339
epochs 44/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9204952246264407, val_loss: 1.0360018099609174
epochs 45/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9069627674002396, val_loss: 1.0126356203305094
epochs 46/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9427906792414816, val_loss: 0.9672747775128013
epochs 47/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.939565223455429, val_loss: 0.9952626087163624
epochs 48/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9019813559557263, val_loss: 0.9658977486585316
epochs 49/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9109387024452812, val_loss: 0.9924132080454575
epochs 50/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9059292796411013, val_loss: 0.9810442620202114
epochs 51/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8962774935521578, val_loss: 1.0134308309931503
epochs 52/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8923383615518871, val_loss: 0.9780379050656369
epochs 53/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8956187850550601, val_loss: 1.032826815153423
epochs 54/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.893916698506004, val_loss: 0.991773468883414
epochs 55/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8952795204363371, val_loss: 1.0232975407650595
epochs 56/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8886902147217801, val_loss: 1.036807497237858
epochs 57/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8846940846819626, val_loss: 1.0103064395879444
epochs 58/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8869254184396643, val_loss: 1.0474483282942522
epochs 59/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8853577893031271, val_loss: 1.0121821585454438
epochs 60/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8856942534446717, val_loss: 1.0428211623116543
epochs 61/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8867208462012441, val_loss: 0.9899641711460917
epochs 62/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8887840556470972, val_loss: 1.045409224221581
epochs 63/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8937122953565497, val_loss: 0.979163135039179
epochs 64/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.905152492146743, val_loss: 1.0082445342289774
epochs 65/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8908454537391662, val_loss: 1.0425461524411253
epochs 66/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9015837471736105, val_loss: 0.9660182265858901
epochs 67/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.90178048202866, val_loss: 1.0445549180633142
epochs 68/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9263846227997228, val_loss: 0.9765383259246224
epochs 69/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9223919187721453, val_loss: 1.1019814673222994
epochs 70/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9173933377391413, val_loss: 0.9746842396886726
epochs 71/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8977397652048814, val_loss: 0.9694888463145808
epochs 72/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9123693005034798, val_loss: 0.9642191510451468
epochs 73/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9016325668284767, val_loss: 0.9830179876402805
epochs 74/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8921798778207679, val_loss: 1.0105858413796676
epochs 75/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8894960613627183, val_loss: 0.9966321455804925
epochs 76/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8838098817750027, val_loss: 0.9962811987651022
epochs 77/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8828706713099229, val_loss: 1.022247039330633
epochs 78/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8793056362553646, val_loss: 1.013739843431272
epochs 79/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8818941320243635, val_loss: 1.0346206432894656
epochs 80/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8764438484844409, val_loss: 0.9999635429758774
epochs 81/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8822662563700425, val_loss: 1.0423024626154649
epochs 82/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8785073192496049, val_loss: 0.9878632576842057
epochs 83/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8901225033559297, val_loss: 1.0139249114613784
epochs 84/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8805477205075716, val_loss: 1.0538394560939388
epochs 85/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8776288183111893, val_loss: 1.053288073288767
epochs 86/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9072787156230525, val_loss: 0.9904572446095316
epochs 87/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.9162986949870461, val_loss: 1.0628292378626372
epochs 88/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8936664916967091, val_loss: 0.9694403055467103
epochs 89/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8943192770606593, val_loss: 0.9980255450073041
epochs 90/95
Current Learning Rate: 0.0015324914086730355
train_loss: 0.8982198608549018, val_loss: 1.0090550955973174
epochs 91/95

[I 2024-01-27 00:38:55,058] Trial 22 pruned.

Current Learning Rate: 0.0015324914086730355
train_loss: 0.8823712483832711, val_loss: 1.032086202659105
epochs 92/95
Starting fold 1:
epochs 1/110
Current Learning Rate: 0.006571589730312157
train_loss: 1.0944013056002164, val_loss: 0.9952209842832465
epochs 2/110
Current Learning Rate: 0.006571589730312157
train_loss: 1.065866804122925, val_loss: 0.987084812867014
epochs 3/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9769138925953915, val_loss: 0.9933845030634026
epochs 4/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9950297079588237, val_loss: 0.9911528417938634
epochs 5/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9945881078117772, val_loss: 0.9873648963476482
epochs 6/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9887748304166292, val_loss: 0.9897460554775439
epochs 7/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9835259851656462, val_loss: 0.9901296377182007
epochs 8/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9772074975465473, val_loss: 0.9865262790730125
epochs 9/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9727396902285124, val_loss: 0.9841486704976935
epochs 10/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9714527719899227, val_loss: 0.9821796574090657
epochs 11/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9699257072649504, val_loss: 0.9796903528665242
epochs 12/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9635193661639565, val_loss: 0.976855815084357
epochs 13/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9414967812989887, val_loss: 1.010089908148113
epochs 14/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9694674454237285, val_loss: 0.9724448925570438
epochs 15/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9314826074399446, val_loss: 0.9693403269115247
epochs 16/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9329586280019659, val_loss: 0.9762761944218685
epochs 17/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9507624011290701, val_loss: 0.9952320450230648
epochs 18/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9431590205744693, val_loss: 0.9712898047346817
epochs 19/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.933877107971593, val_loss: 0.9714499743361222
epochs 20/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9449106881493017, val_loss: 0.9706801370570534
epochs 21/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9403562006197478, val_loss: 0.9860975171390333
epochs 22/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9264893807862934, val_loss: 0.9751774982402199
epochs 23/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9186340407321327, val_loss: 0.9845520433626677
epochs 24/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9214808564437064, val_loss: 0.996509902100814
epochs 25/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9160559378172222, val_loss: 0.9971691382558723
epochs 26/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9311459541320801, val_loss: 1.0112453749305323
epochs 27/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9087717859368575, val_loss: 0.9985712277261835
epochs 28/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9400968639474166, val_loss: 0.9832049162764298
epochs 29/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9260493755340576, val_loss: 0.9740894468207109
epochs 30/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9102345541903847, val_loss: 0.9694071154845388
epochs 31/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9180178843046489, val_loss: 0.9723425382062009
epochs 32/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9115132934168766, val_loss: 0.9798390030860901
epochs 33/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8982066292511789, val_loss: 1.0038515881488197
epochs 34/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9219254619196842, val_loss: 1.0630341931393272
epochs 35/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9888242596074155, val_loss: 0.9852070469605295
epochs 36/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9261918482027556, val_loss: 0.9731080996362786
epochs 37/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9146554193998638, val_loss: 0.9715200901031494
epochs 38/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9216088282434564, val_loss: 0.9729072777848494
epochs 39/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9125832758451763, val_loss: 0.9797030731251365
epochs 40/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9074949779008564, val_loss: 0.9921852977652299
epochs 41/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9128668571773328, val_loss: 1.0036556206251446
epochs 42/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9039250373840332, val_loss: 1.0098042375163028
epochs 43/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9241374480096918, val_loss: 1.0069991864656147
epochs 44/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9005686621916922, val_loss: 0.9961942810761301
epochs 45/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.922233479901364, val_loss: 0.9769330953296862
epochs 46/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9126748674794247, val_loss: 0.9866678670832986
epochs 47/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8954201284207796, val_loss: 0.9877519544802214
epochs 48/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9031236385044299, val_loss: 0.9963281255019338
epochs 49/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8975210641559802, val_loss: 0.998494281266865
epochs 50/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8905036474529066, val_loss: 1.0164676992516768
epochs 51/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8856783151626587, val_loss: 1.0117608208405344
epochs 52/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9050932859119616, val_loss: 0.9959570859607897
epochs 53/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9057746322531449, val_loss: 0.9950303303567987
epochs 54/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9044355982228329, val_loss: 1.0354408075934962
epochs 55/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9134978884144833, val_loss: 1.0028766644628424
epochs 56/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9312842281241166, val_loss: 0.9725276407442595
epochs 57/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9104464254881206, val_loss: 1.0022567385121395
epochs 58/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.900423402535288, val_loss: 0.9813449771780717
epochs 59/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9064214417808935, val_loss: 0.9804736037003366
epochs 60/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8970307626222309, val_loss: 1.0170447713450381
epochs 61/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8894086222899588, val_loss: 0.9998025091070878
epochs 62/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8981934647811086, val_loss: 0.9861507089514482
epochs 63/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8810132930153295, val_loss: 1.0108102616510892
epochs 64/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8846625064548693, val_loss: 1.0119631340629176
epochs 65/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9048999761280261, val_loss: 0.9839592394075896
epochs 66/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9163807454862093, val_loss: 1.0049728926859405
epochs 67/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8861385270168907, val_loss: 0.9954663464897557
epochs 68/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8855180878388255, val_loss: 0.9936341674704301
epochs 69/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8873594158574154, val_loss: 0.9951235219051964
epochs 70/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8797099439721359, val_loss: 0.9907003402709961
epochs 71/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8732489322361193, val_loss: 1.0031276351527163
epochs 72/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8645346716830605, val_loss: 1.0259862937425313
epochs 73/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8618398741671913, val_loss: 1.0139783859252929
epochs 74/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8608403105484812, val_loss: 1.1011891019971747
epochs 75/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8781890442496851, val_loss: 1.0284407465081467
epochs 76/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9374710333974738, val_loss: 1.0171630332344457
epochs 77/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9247620143388448, val_loss: 0.9813273580450761
epochs 78/110
Epoch 00078: reducing learning rate of group 0 to 4.1293e-03.
Current Learning Rate: 0.0041293361832346115
train_loss: 0.9150828549736425, val_loss: 0.9779094583109805
epochs 79/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.9136421027936433, val_loss: 0.9733478916318793
epochs 80/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.902941295975133, val_loss: 0.985408585949948
epochs 81/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8975082535492747, val_loss: 0.9900287239175094
epochs 82/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8956294624429, val_loss: 0.9859567855533801
epochs 83/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8902875887720209, val_loss: 0.9819015063737568
epochs 84/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8839455842971802, val_loss: 0.9867295635373969
epochs 85/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8797605326301173, val_loss: 0.9965599662379214
epochs 86/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8763216953528555, val_loss: 1.0010566723974128
epochs 87/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8793059072996441, val_loss: 0.9987553320432964
epochs 88/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8714200810382241, val_loss: 0.9996251721131174
epochs 89/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8679621652552956, val_loss: 1.0028649913637262
epochs 90/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.859266535859359, val_loss: 1.0009118368751124
epochs 91/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8710759206822044, val_loss: 0.9943099868924994
epochs 92/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8733036794160541, val_loss: 0.9918006846779271
epochs 93/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8821096357546354, val_loss: 0.9874858981684634
epochs 94/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8754795538751703, val_loss: 0.989098302314156
epochs 95/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8771267715253328, val_loss: 0.988255945004915
epochs 96/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8801638264405099, val_loss: 0.9976695186213443
epochs 97/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8695700720736855, val_loss: 1.0285587913111636
epochs 98/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8660558600174754, val_loss: 1.0080057508067082
epochs 99/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.868954086303711, val_loss: 1.0193815789724652
epochs 100/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8591760635375977, val_loss: 1.0212820611501996
epochs 101/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.856707941858392, val_loss: 1.0212432804860567
epochs 102/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8519275790766666, val_loss: 1.024898194011889
epochs 103/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.850242765326249, val_loss: 1.0328957319259644
epochs 104/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8417818546295166, val_loss: 1.028218644543698
epochs 105/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8468583872443751, val_loss: 1.0298834461914865
epochs 106/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8516513309980693, val_loss: 1.0288890035528886
epochs 107/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8673242280357762, val_loss: 1.0079140870194687
epochs 108/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8556531962595488, val_loss: 1.0037858843803407
epochs 109/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8704107736286364, val_loss: 1.00947568291112
epochs 110/110
Current Learning Rate: 0.0041293361832346115
train_loss: 0.8568339611354627, val_loss: 1.0763249447471217
Starting fold 2:
epochs 1/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9745137177015606, val_loss: 1.3482449130008096
epochs 2/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9321014366651836, val_loss: 1.133074372693112
epochs 3/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9354333055646796, val_loss: 1.1642722543917203
epochs 4/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9369254802402697, val_loss: 1.1810068193234895
epochs 5/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9275787654675935, val_loss: 1.2252781240563644
epochs 6/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9280986553744266, val_loss: 1.204643029915659
epochs 7/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9224847636724773, val_loss: 1.2134417697003013
epochs 8/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9250927969029076, val_loss: 1.2217360973358153
epochs 9/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.916331966927177, val_loss: 1.1758529236442163
epochs 10/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9127097299224451, val_loss: 1.20752760234632
epochs 11/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9039044273527045, val_loss: 1.1868281251505801
epochs 12/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.901332111735093, val_loss: 1.1753136283472965
epochs 13/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9240746309882716, val_loss: 1.1634304234856054
epochs 14/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9331414781118694, val_loss: 1.190606279122202
epochs 15/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9206133924032512, val_loss: 1.1698076323459023
epochs 16/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9144961344568353, val_loss: 1.262209099217465
epochs 17/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9059857130050659, val_loss: 1.1785293303037945
epochs 18/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9083780125567787, val_loss: 1.2481778207578158
epochs 19/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9086050686083342, val_loss: 1.2139453135038678
epochs 20/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8951992505475095, val_loss: 1.2739762193278263
epochs 21/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8995263206331353, val_loss: 1.3190364134939094
epochs 22/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8894353283079047, val_loss: 1.1291182844262375
epochs 23/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8987673646525333, val_loss: 1.1804374130148636
epochs 24/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8850684925129539, val_loss: 1.2125023854406256
epochs 25/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8946974189657914, val_loss: 1.147701076457375
epochs 26/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9064180173371967, val_loss: 1.254494124964664
epochs 27/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9122065650789362, val_loss: 1.0291252512680857
epochs 28/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9223940171693501, val_loss: 1.1665769727606523
epochs 29/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9267939818532843, val_loss: 1.1343625683533518
epochs 30/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.909410349946273, val_loss: 1.0964781635685972
epochs 31/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9074586491835744, val_loss: 1.0900403988988776
epochs 32/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8862543237836737, val_loss: 1.1366178186316238
epochs 33/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8789067952256454, val_loss: 1.0666143705970363
epochs 34/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8863187488756682, val_loss: 1.128626567439029
epochs 35/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8704522258356998, val_loss: 1.1241308149538543
epochs 36/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8819576087750887, val_loss: 1.1433354139328002
epochs 37/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8848458810856468, val_loss: 1.1527264243678044
epochs 38/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8978837590468557, val_loss: 1.149003892195852
epochs 39/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9000680597204911, val_loss: 1.1237633014980115
epochs 40/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.885065211747822, val_loss: 1.1809920838004664
epochs 41/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.86754158798017, val_loss: 1.168094633754931
epochs 42/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8703769012501366, val_loss: 1.243930899469476
epochs 43/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9217270110782824, val_loss: 1.0356998820053904
epochs 44/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8971256990181772, val_loss: 1.1296476213555586
epochs 45/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8712851486707989, val_loss: 1.2052419035058273
epochs 46/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8655987149790714, val_loss: 1.1056454558121531
epochs 47/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.879181128426602, val_loss: 1.1759215392564473
epochs 48/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8516135033808256, val_loss: 1.216286513679906
epochs 49/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8846925264910648, val_loss: 1.301695956681904
epochs 50/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.9035392309490003, val_loss: 1.2267077144823577
epochs 51/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8877190891065095, val_loss: 1.1035629448137785
epochs 52/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8847650496583236, val_loss: 1.0925171877208508
epochs 53/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8940126400244863, val_loss: 1.1533906422163311
epochs 54/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8977592355326602, val_loss: 1.1740457045404535
epochs 55/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8840112347351877, val_loss: 1.2349639026742232
epochs 56/110
Current Learning Rate: 0.006571589730312157
train_loss: 0.8587480789736698, val_loss: 1.2402106209805137
epochs 57/110

[I 2024-01-27 00:39:11,324] Trial 23 pruned.

Starting fold 1:
epochs 1/80
Current Learning Rate: 0.033167394730938826
train_loss: 1.2808587927567332, val_loss: 1.220419886865114
epochs 2/80
Current Learning Rate: 0.033167394730938826
train_loss: 1.1560357275762057, val_loss: 0.9936131427162572
epochs 3/80
Current Learning Rate: 0.033167394730938826
train_loss: 1.0737278822221255, val_loss: 0.9924714204512144
epochs 4/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9853298115102869, val_loss: 0.9921497733969438
epochs 5/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9978722678987604, val_loss: 0.9933446332028038
epochs 6/80
Current Learning Rate: 0.033167394730938826
train_loss: 1.0017261065934833, val_loss: 0.9918155779964045
epochs 7/80
Current Learning Rate: 0.033167394730938826
train_loss: 1.0000053503011401, val_loss: 0.9949562000600916
epochs 8/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9900722503662109, val_loss: 0.9920477710272136
epochs 9/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9830624570972041, val_loss: 0.9865944307101401
epochs 10/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9791733355898606, val_loss: 0.9838552490661019
epochs 11/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9790021322275463, val_loss: 0.9826456527960928
epochs 12/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9724415462268027, val_loss: 0.9835569246819145
epochs 13/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9643896849531877, val_loss: 0.9800458566138619
epochs 14/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9598571830674222, val_loss: 0.9796974878562125
epochs 15/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9595097068109011, val_loss: 0.9832676915745986
epochs 16/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.950694779032155, val_loss: 0.974655165484077
epochs 17/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9406580768133465, val_loss: 0.9728421537499679
epochs 18/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.929146978415941, val_loss: 0.9726533152555165
epochs 19/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9239858498698786, val_loss: 0.9784571779401678
epochs 20/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9237013318036732, val_loss: 0.982630309305693
epochs 21/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9255928334436918, val_loss: 0.986850729114131
epochs 22/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9300714276338878, val_loss: 0.9886413577355837
epochs 23/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9158255755901337, val_loss: 1.002302856821763
epochs 24/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.922040122120004, val_loss: 0.9875285264692808
epochs 25/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9117729444252817, val_loss: 1.0064793495755446
epochs 26/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9240608089848569, val_loss: 0.9845269040057534
epochs 27/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9181765145377109, val_loss: 1.0006649964734127
epochs 28/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9163817230023836, val_loss: 0.990361152510894
epochs 29/80

[I 2024-01-27 00:39:12,834] Trial 24 pruned.

Current Learning Rate: 0.033167394730938826
train_loss: 0.9151001949059335, val_loss: 0.9916887942113375
epochs 30/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9072396708162207, val_loss: 1.0078678350699575
epochs 31/80
Current Learning Rate: 0.033167394730938826
train_loss: 0.9150508155948237, val_loss: 1.0048127378288068
epochs 32/80
Number of finished trials: 25
Best trial:
Value: 1.1692108569145203
Params:
batch_size: 38
epochs: 110
hidden_size: 58
learning_rate: 0.0005114000297213227
dropout_prob: 0.036842811921699456
weight_decay: 6.34187218994956e-06
lr_step_size: 74
gamma: 0.23844020275858402

In [247]:
trainer = ModelActioner(train_data, test_data, device, model_type)
model = trainer.train(trial.params)

epochs 1/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 2/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 3/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 4/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 5/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 6/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 7/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 8/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 9/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 10/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 11/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 12/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 13/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 14/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 15/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 16/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 17/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 18/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 19/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 20/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 21/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 22/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 23/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 24/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 25/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 26/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 27/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 28/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 29/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 30/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 31/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 32/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 33/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 34/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 35/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 36/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 37/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 38/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 39/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 40/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 41/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 42/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 43/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 44/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 45/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 46/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 47/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 48/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 49/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 50/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 51/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 52/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 53/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 54/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 55/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 56/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 57/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 58/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 59/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 60/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 61/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 62/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 63/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 64/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 65/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 66/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 67/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 68/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 69/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 70/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 71/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 72/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 73/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 74/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 75/110
Current Learning Rate: 0.0005114000297213227
train_loss: 0.0
epochs 76/110
Epoch 00076: reducing learning rate of group 0 to 1.2194e-04.
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 77/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 78/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 79/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 80/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 81/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 82/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 83/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 84/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 85/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 86/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 87/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 88/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 89/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 90/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 91/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 92/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 93/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 94/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 95/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 96/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 97/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 98/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 99/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 100/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 101/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 102/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 103/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 104/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 105/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 106/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 107/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 108/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 109/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0
epochs 110/110
Current Learning Rate: 0.00012193832677749808
train_loss: 0.0

In [248]:
y_true = y_test_df[time_step:]
preds = trainer.test(trial.params)

# Mean Absolute Error
mae = mean_absolute_error(y_true, preds)
print(f'Mean Absolute Error: {mae}')

# Mean Squared Error
mse = mean_squared_error(y_true, preds)
print(f'Mean Squared Error: {mse}')

# Root Mean Squared Error
rmse = np.sqrt(mse)
print(f'Root Mean Squared Error: {rmse}')

# R-squared Score
r2 = r2_score(y_true, preds)
print(f'R-squared Score: {r2}')

mape = mean_absolute_percentage_error(y_true, preds)*100
print(f"MAPE: {mape}")

test_loss: 0.0
Mean Absolute Error: 0.9666798129065001
Mean Squared Error: 0.9447733599912217
Root Mean Squared Error: 0.9719945267290457
R-squared Score: -90.69441677440346
MAPE: 100.0

In [249]:
y_true

44     0.728267
45     0.737950
46     0.733381
47     0.747701
48     0.761134
         ...
291    1.018693
292    1.059493
293    1.079584
294    1.095561
295    1.104406
Name: Adj Close, Length: 252, dtype: float64

In [250]:
y_true = y_true.reset_index(drop=True)
#y_true = y_true.drop(columns=["index","level_0"])
X_value = X_test_df.iloc[43:,-1]
X_value = X_value.reset_index()
preds_values = [x[0] for x in preds]
X_value["Preds"] = pd.Series(preds_values)
X_value["Next Day"] = y_true
X_value = X_value.drop(columns=["index"])
X_value["Diff Preds"] = (X_value["Preds"] - X_value["Adj Close"])
X_value["Diff Next Day"] = (X_value["Next Day"] - X_value["Adj Close"])
X_value = X_value.dropna()
X_value

     Adj Close         Preds  Next Day  Diff Preds  Diff Next Day
0     0.706173 -7.781130e-40  0.728267   -0.706173       0.022094
1     0.728267 -7.781130e-40  0.737950   -0.728267       0.009683
2     0.737950 -7.781130e-40  0.733381   -0.737950      -0.004569
3     0.733381 -7.781130e-40  0.747701   -0.733381       0.014320
4     0.747701 -7.781130e-40  0.761134   -0.747701       0.013433
..         ...           ...       ...         ...            ...
247   1.025207 -7.781130e-40  1.018693   -1.025207      -0.006514
248   1.018693 -7.781130e-40  1.059493   -1.018693       0.040800
249   1.059493 -7.781130e-40  1.079584   -1.059493       0.020091
250   1.079584 -7.781130e-40  1.095561   -1.079584       0.015977
251   1.095561 -7.781130e-40  1.104406   -1.095561       0.008846

[252 rows x 5 columns]

In [251]:
def assign_label(diff):
    if diff > 0.0:
        return 1  # Buy
    elif diff < -0.01:
        return 0  # Sell
    else:
        return 2  # Hold/Other

In [252]:
# Apply the function to assign labels
X_value['Signal Preds'] = X_value['Diff Preds'].apply(assign_label)
X_value['Signal True'] = X_value['Diff Next Day'].apply(assign_label)

# Dropping the intermediate difference columns if they are no longer needed
X_value = X_value.drop(columns=['Diff Preds', 'Diff Next Day'])

X_value

     Adj Close         Preds  Next Day  Signal Preds  Signal True
0     0.706173 -7.781130e-40  0.728267             0            1
1     0.728267 -7.781130e-40  0.737950             0            1
2     0.737950 -7.781130e-40  0.733381             0            2
3     0.733381 -7.781130e-40  0.747701             0            1
4     0.747701 -7.781130e-40  0.761134             0            1
..         ...           ...       ...           ...          ...
247   1.025207 -7.781130e-40  1.018693             0            2
248   1.018693 -7.781130e-40  1.059493             0            1
249   1.059493 -7.781130e-40  1.079584             0            1
250   1.079584 -7.781130e-40  1.095561             0            1
251   1.095561 -7.781130e-40  1.104406             0            1

[252 rows x 5 columns]

In [253]:
accuracy = accuracy_score(X_value["Signal True"], X_value["Signal Preds"])
print(f'Accuracy: {accuracy * 100:.2f}%')

# Precision
precision = precision_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'Precision: {precision:.4f}')

# Recall
recall = recall_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'Recall: {recall:.4f}')

# F1 Score
f1 = f1_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'F1 Score: {f1:.4f}')

Accuracy: 19.44%
Precision: 0.0378
Recall: 0.1944
F1 Score: 0.0633

/home/arda/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [254]:
y_true

0      0.728267
1      0.737950
2      0.733381
3      0.747701
4      0.761134
         ...
247    1.018693
248    1.059493
249    1.079584
250    1.095561
251    1.104406
Name: Adj Close, Length: 252, dtype: float64

In [255]:
X_value["Signal Preds"]

0      0
1      0
2      0
3      0
4      0
      ..
247    0
248    0
249    0
250    0
251    0
Name: Signal Preds, Length: 252, dtype: int64

In [256]:
signals = pd.DataFrame(X_value["Signal Preds"].values, columns=['Signal'])
signals

     Signal
0         0
1         0
2         0
3         0
4         0
..      ...
247       0
248       0
249       0
250       0
251       0

[252 rows x 1 columns]

In [257]:
signals["Signal"].value_counts()

Signal
0    252
Name: count, dtype: int64

In [258]:
signals["Date"] = date_test
signals

     Signal       Date
0         0 2023-01-23
1         0 2023-01-24
2         0 2023-01-25
3         0 2023-01-26
4         0 2023-01-27
..      ...        ...
247       0 2024-01-17
248       0 2024-01-18
249       0 2024-01-19
250       0 2024-01-22
251       0 2024-01-23

[252 rows x 2 columns]

In [259]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325668
1    141.737762
2    141.071487
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [260]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [261]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
buy_signals = signals[signals['Signal'] == 1]
sell_signals = signals[signals['Signal'] == 0]

# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]

# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))

# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))

# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [262]:
price_signal = stock_data[stock_data['Date'].isin(signals['Date'])]["Adj Close"]
price_signal = price_signal.reset_index()
price_signal = price_signal.drop(columns=["index"])
result = pd.concat([price_signal,signals], axis=1)
result

      Adj Close  Signal       Date
0    140.325668       0 2023-01-23
1    141.737762       0 2023-01-24
2    141.071487       0 2023-01-25
3    143.159805       0 2023-01-26
4    145.118851       0 2023-01-27
..          ...     ...        ...
247  182.679993       0 2024-01-17
248  188.630005       0 2024-01-18
249  191.559998       0 2024-01-19
250  193.889999       0 2024-01-22
251  195.179993       0 2024-01-23

[252 rows x 3 columns]

In [263]:
price_signal

      Adj Close
0    140.325668
1    141.737762
2    141.071487
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [264]:
sell_signals

     Signal       Date
0         0 2023-01-23
1         0 2023-01-24
2         0 2023-01-25
3         0 2023-01-26
4         0 2023-01-27
..      ...        ...
247       0 2024-01-17
248       0 2024-01-18
249       0 2024-01-19
250       0 2024-01-22
251       0 2024-01-23

[252 rows x 2 columns]

In [265]:
buy_prices

Series([], Name: Adj Close, dtype: float64)