In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm
from sklearn.utils.class_weight import compute_class_weight

In [2]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [3]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722874  43.075001  42.314999  102223600
1  2018-01-03  40.715790  43.637501  42.990002  118071600
2  2018-01-04  40.904911  43.367500  43.020000   89738400
3  2018-01-05  41.370613  43.842499  43.262501   94640000
4  2018-01-08  41.216961  43.902500  43.482498   82271200
5  2018-01-09  41.212223  43.764999  43.352501   86336000
6  2018-01-10  41.202774  43.575001  43.250000   95839600
7  2018-01-11  41.436825  43.872501  43.622501   74670800
8  2018-01-12  41.864700  44.340000  43.912498  101672400
9  2018-01-16  41.651943  44.847500  44.035000  118263600
10 2018-01-17  42.339874  44.812500  43.767502  137547200
11 2018-01-18  42.377697  45.025002  44.562500  124773600
12 2018-01-19  42.188591  44.895000  44.352501  129700400
13 2018-01-22  41.843430  44.445000  44.150002  108434400
14 2018-01-23  41.852879  44.860001  44.205002  130756400
15 2018-01-24  41.186222  44.325001  43.299999  204420400
16 2018-01-25  40.451012  43.737499  42.632500  166116000
17 2018-01-26  40.545570  43.000000  42.514999  156572000
18 2018-01-29  39.706341  42.540001  41.767502  202561600
19 2018-01-30  39.472305  41.842499  41.174999  184192800
20 2018-01-31  39.581047  42.110001  41.625000  129915600
21 2018-02-01  39.663788  42.154999  41.689999  188923200
22 2018-02-02  37.942768  41.700001  40.025002  346375200
23 2018-02-05  36.994804  40.970001  39.000000  290954000
24 2018-02-06  38.540867  40.930000  38.500000  272975200
25 2018-02-07  37.715813  40.849998  39.767502  206434400
26 2018-02-08  36.678009  40.250000  38.757500  217562000
27 2018-02-09  37.126640  39.472500  37.560001  282690400
28 2018-02-12  38.622051  40.972500  39.377499  243278000
29 2018-02-13  39.008949  41.187500  40.412498  130196800
30 2018-02-14  39.728184  41.884998  40.720001  162579600
31 2018-02-15  41.062187  43.272499  42.250000  204588800
32 2018-02-16  40.929256  43.705002  42.942501  160704400
33 2018-02-20  40.791588  43.564999  42.855000  135722000
34 2018-02-21  40.606426  43.529999  42.752499  149886400
35 2018-02-22  40.945877  43.487499  42.927502  123967600
36 2018-02-23  41.657974  43.912498  43.384998  135249600
37 2018-02-26  42.481644  44.847500  44.052502  152648800
38 2018-02-27  42.343971  45.119999  44.540001  155712400
39 2018-02-28  42.279884  45.154999  44.512501  151128400
40 2018-03-01  41.539284  44.945000  43.165001  195208000
41 2018-03-02  41.826515  44.075001  43.112499  153816000
42 2018-03-05  41.971302  44.435001  43.630001  113605600
43 2018-03-06  41.935699  44.562500  44.032501   95154000
44 2018-03-07  41.546417  43.962502  43.567501  126814000

In [4]:
time_step = 44

In [5]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [6]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [7]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma_s = talib.SMA(data["Adj Close"], timeperiod=20)
    sma_l = talib.SMA(data["Adj Close"], timeperiod=50)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA_SHORT': sma_s,
        'SMA_LONG': sma_l,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [8]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724164,117105600.0
15,NaN,NaN,55.580786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0
16,NaN,NaN,45.152358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695098,-253430800.0
17,NaN,NaN,46.541621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.817993,2.684662,-96858800.0
18,NaN,NaN,37.470180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639257,-81.393350,2.635359,-299420400.0
19,NaN,NaN,35.398128,NaN,NaN,42.761510,41.213177,39.664844,41.213177,NaN,NaN,-61.987786,-75.553866,2.599702,-483613200.0
20,NaN,NaN,37.137552,NaN,NaN,42.849894,41.156085,39.462277,41.156085,NaN,NaN,-49.633816,-63.086953,2.602416,-353697600.0
21,NaN,NaN,38.494559,NaN,NaN,42.910289,41.103485,39.296682,41.103485,NaN,NaN,-41.626447,-51.082683,2.600383,-164774400.0
22,NaN,NaN,25.947595,NaN,NaN,43.228468,40.955378,38.682288,40.955378,NaN,NaN,-40.766073,-44.008779,2.560085,-511149600.0
23,NaN,NaN,21.743607,NaN,NaN,43.578806,40.736588,37.894369,40.736588,NaN,NaN,-38.059379,-40.150633,2.593453,-802103600.0
24,NaN,NaN,39.079549,NaN,NaN,43.590203,40.602783,37.615363,40.602783,NaN,NaN,-24.766534,-34.530662,2.689291,-529128400.0
25,NaN,NaN,34.666149,NaN,NaN,43.652100,40.427962,37.203825,40.427962,NaN,NaN,-14.972480,-25.932798,2.662137,-735562800.0
26,NaN,NaN,30.066506,NaN,NaN,43.790971,40.201724,36.612478,40.201724,NaN,NaN,-13.427949,-17.722321,2.652998,-953124800.0
27,NaN,NaN,34.134987,NaN,NaN,43.765507,39.986215,36.206923,39.986215,NaN,NaN,-15.615538,-14.671989,2.663105,-670434400.0
28,NaN,NaN,45.513635,NaN,NaN,43.544882,39.824083,36.103283,39.824083,NaN,NaN,-6.294974,-11.779487,2.747587,-427156400.0
29,NaN,NaN,48.015866,NaN,NaN,43.330500,39.691933,36.053366,39.691933,NaN,NaN,11.072663,-3.612616,2.734577,-296959600.0
30,NaN,NaN,52.392807,NaN,NaN,42.991932,39.561348,36.130765,39.561348,NaN,NaN,26.336915,10.371535,2.744682,-134380000.0
31,NaN,NaN,59.246653,NaN,NaN,42.753753,39.495573,36.237393,39.495573,NaN,NaN,41.539665,26.316414,2.801799,70208800.0
32,NaN,NaN,58.345247,NaN,NaN,42.524612,39.432606,36.340601,39.432606,NaN,NaN,51.997649,39.958076,2.790443,-90495600.0
33,-0.373864,-0.940886,57.371719,NaN,NaN,42.339133,39.380014,36.420895,39.380014,NaN,NaN,56.241838,49.926384,2.779393,-226217600.0
34,-0.274211,-0.807551,56.017869,NaN,NaN,42.113877,39.317691,36.521506,39.317691,NaN,NaN,52.331249,53.523579,2.776466,-376104000.0
35,-0.165931,-0.679227,57.975737,NaN,NaN,42.071536,39.305674,36.539812,39.305674,NaN,NaN,52.421407,53.664831,2.783938,-252136400.0
36,-0.022400,-0.547861,61.815795,NaN,NaN,42.278020,39.366022,36.454025,39.366022,NaN,NaN,56.394995,53.715883,2.796986,-116886800.0
37,0.156014,-0.407086,65.717937,NaN,NaN,42.641725,39.462826,36.283927,39.462826,NaN,NaN,62.381578,57.065993,2.825025,35762000.0
38,0.283037,-0.269062,64.530896,NaN,NaN,43.012919,39.594707,36.176496,39.594707,NaN,NaN,65.108366,61.294980,2.811691,-119950400.0
39,0.374218,-0.140406,63.951812,NaN,NaN,43.346787,39.735086,36.123386,39.735086,NaN,NaN,64.320030,63.936658,2.811644,-271078800.0
40,0.382313,-0.035862,57.527204,NaN,NaN,43.527902,39.832998,36.138095,39.832998,NaN,NaN,59.272713,62.900370,2.801178,-466286800.0
41,0.407211,0.052752,59.237560,NaN,NaN,43.735161,39.941135,36.147108,39.941135,NaN,NaN,52.308986,58.633910,2.782216,-312470800.0
42,0.433627,0.128927,60.109580,NaN,NaN,43.918534,40.142561,36.366589,40.142561,NaN,NaN,42.550380,51.377360,2.769807,-198865200.0
43,0.446542,0.192450,59.770975,NaN,NaN,43.949836,40.389606,36.829376,40.389606,NaN,40.596320,34.223050,43.027472,2.757049,-294019200.0
44,0.420518,0.238064,56.052920,4.051397,0.823544,44.028290,40.539884,37.051477,40.539884,NaN,40.638546,12.020187,29.597872,2.704889,-420833200.0

In [9]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722874
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715790
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904911
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370613
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216961
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212223
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202774
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436825
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864700
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651943
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339874
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377697
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188591
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843430
14,NaN,NaN,68.998704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724164,117105600.0,41.852879
15,NaN,NaN,55.580786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0,41.186222
16,NaN,NaN,45.152358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695098,-253430800.0,40.451012
17,NaN,NaN,46.541621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.817993,2.684662,-96858800.0,40.545570
18,NaN,NaN,37.470180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639257,-81.393350,2.635359,-299420400.0,39.706341
19,NaN,NaN,35.398128,NaN,NaN,42.761510,41.213177,39.664844,41.213177,NaN,NaN,-61.987786,-75.553866,2.599702,-483613200.0,39.472305
20,NaN,NaN,37.137552,NaN,NaN,42.849894,41.156085,39.462277,41.156085,NaN,NaN,-49.633816,-63.086953,2.602416,-353697600.0,39.581047
21,NaN,NaN,38.494559,NaN,NaN,42.910289,41.103485,39.296682,41.103485,NaN,NaN,-41.626447,-51.082683,2.600383,-164774400.0,39.663788
22,NaN,NaN,25.947595,NaN,NaN,43.228468,40.955378,38.682288,40.955378,NaN,NaN,-40.766073,-44.008779,2.560085,-511149600.0,37.942768
23,NaN,NaN,21.743607,NaN,NaN,43.578806,40.736588,37.894369,40.736588,NaN,NaN,-38.059379,-40.150633,2.593453,-802103600.0,36.994804
24,NaN,NaN,39.079549,NaN,NaN,43.590203,40.602783,37.615363,40.602783,NaN,NaN,-24.766534,-34.530662,2.689291,-529128400.0,38.540867
25,NaN,NaN,34.666149,NaN,NaN,43.652100,40.427962,37.203825,40.427962,NaN,NaN,-14.972480,-25.932798,2.662137,-735562800.0,37.715813
26,NaN,NaN,30.066506,NaN,NaN,43.790971,40.201724,36.612478,40.201724,NaN,NaN,-13.427949,-17.722321,2.652998,-953124800.0,36.678009
27,NaN,NaN,34.134987,NaN,NaN,43.765507,39.986215,36.206923,39.986215,NaN,NaN,-15.615538,-14.671989,2.663105,-670434400.0,37.126640
28,NaN,NaN,45.513635,NaN,NaN,43.544882,39.824083,36.103283,39.824083,NaN,NaN,-6.294974,-11.779487,2.747587,-427156400.0,38.622051
29,NaN,NaN,48.015866,NaN,NaN,43.330500,39.691933,36.053366,39.691933,NaN,NaN,11.072663,-3.612616,2.734577,-296959600.0,39.008949
30,NaN,NaN,52.392807,NaN,NaN,42.991932,39.561348,36.130765,39.561348,NaN,NaN,26.336915,10.371535,2.744682,-134380000.0,39.728184
31,NaN,NaN,59.246653,NaN,NaN,42.753753,39.495573,36.237393,39.495573,NaN,NaN,41.539665,26.316414,2.801799,70208800.0,41.062187
32,NaN,NaN,58.345247,NaN,NaN,42.524612,39.432606,36.340601,39.432606,NaN,NaN,51.997649,39.958076,2.790443,-90495600.0,40.929256
33,-0.373864,-0.940886,57.371719,NaN,NaN,42.339133,39.380014,36.420895,39.380014,NaN,NaN,56.241838,49.926384,2.779393,-226217600.0,40.791588
34,-0.274211,-0.807551,56.017869,NaN,NaN,42.113877,39.317691,36.521506,39.317691,NaN,NaN,52.331249,53.523579,2.776466,-376104000.0,40.606426
35,-0.165931,-0.679227,57.975737,NaN,NaN,42.071536,39.305674,36.539812,39.305674,NaN,NaN,52.421407,53.664831,2.783938,-252136400.0,40.945877
36,-0.022400,-0.547861,61.815795,NaN,NaN,42.278020,39.366022,36.454025,39.366022,NaN,NaN,56.394995,53.715883,2.796986,-116886800.0,41.657974
37,0.156014,-0.407086,65.717937,NaN,NaN,42.641725,39.462826,36.283927,39.462826,NaN,NaN,62.381578,57.065993,2.825025,35762000.0,42.481644
38,0.283037,-0.269062,64.530896,NaN,NaN,43.012919,39.594707,36.176496,39.594707,NaN,NaN,65.108366,61.294980,2.811691,-119950400.0,42.343971
39,0.374218,-0.140406,63.951812,NaN,NaN,43.346787,39.735086,36.123386,39.735086,NaN,NaN,64.320030,63.936658,2.811644,-271078800.0,42.279884
40,0.382313,-0.035862,57.527204,NaN,NaN,43.527902,39.832998,36.138095,39.832998,NaN,NaN,59.272713,62.900370,2.801178,-466286800.0,41.539284
41,0.407211,0.052752,59.237560,NaN,NaN,43.735161,39.941135,36.147108,39.941135,NaN,NaN,52.308986,58.633910,2.782216,-312470800.0,41.826515
42,0.433627,0.128927,60.109580,NaN,NaN,43.918534,40.142561,36.366589,40.142561,NaN,NaN,42.550380,51.377360,2.769807,-198865200.0,41.971302
43,0.446542,0.192450,59.770975,NaN,NaN,43.949836,40.389606,36.829376,40.389606,NaN,40.596320,34.223050,43.027472,2.757049,-294019200.0,41.935699
44,0.420518,0.238064,56.052920,4.051397,0.823544,44.028290,40.539884,37.051477,40.539884,NaN,40.638546,12.020187,29.597872,2.704889,-420833200.0,41.546417

In [10]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.567014,0.443929,58.241601,7.100880,1.143620,43.382888,41.728832,40.074776,41.728832,40.814298,41.035721,-7.013324,-3.909598,2.715223,-3.124152e+08,42.355843
1,0.548494,0.464842,58.592114,7.332854,1.202904,43.261033,41.862707,40.464380,41.862707,40.847954,41.096608,-20.016700,-8.448344,2.714432,-2.214400e+08,42.405678
2,0.515806,0.475035,57.044942,6.516263,0.819328,43.280291,41.922405,40.564519,41.922405,40.878762,41.148143,-27.991838,-18.340621,2.690139,-3.790588e+08,42.256153
3,0.432813,0.466591,50.806392,3.052132,-0.254192,43.245421,41.956468,40.667514,41.956468,40.892874,41.168693,-36.985315,-28.331285,2.648797,-5.128460e+08,41.610508
4,0.361721,0.445617,50.674723,2.976529,-0.055679,43.183919,41.996702,40.809484,41.996702,40.897387,41.187696,-46.751996,-37.243050,2.644561,-5.914436e+08,41.596264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [11]:
# Define the conditions
conditions = [
    (indicators_with_price['RSI'] < 30), # al sinyali
    (indicators_with_price['RSI'] > 70) # sat sinyali
]

# Define the choices corresponding to each condition
choices = [2, 1] # 1 sat demek 2 al

# Use np.select to apply the conditions and choices
# The default value is 0 (for when the RSI is between 30 and 70)
indicators_with_price['RSI_SIGNAL'] = np.select(conditions, choices, default=0)

conditions = [
    (indicators_with_price['SMA_SHORT'] > indicators_with_price['SMA_LONG']), # al sinyali
    (indicators_with_price['SMA_LONG'] > indicators_with_price['SMA_SHORT']) # sat sinyali
]
# Define the choices corresponding to each condition
choices = [2, 1] # 1 sat demek 2 al

indicators_with_price['SMA_SIGNAL'] = np.select(conditions, choices, default=0)

# Display the dataframe to verify the results

# Create a column 'MACD_Signal' to hold the trading signal
indicators_with_price['MACD_Signal'] = 0

# Generate buy/sell signals
indicators_with_price['MACD_Signal'][indicators_with_price['MACD'] > indicators_with_price['MACD_signal']] = 2  # Buy signal
indicators_with_price['MACD_Signal'][indicators_with_price['MACD'] < indicators_with_price['MACD_signal']] = 1  # Sell signal

# Create a column 'BB_Signal' to hold the trading signal
indicators_with_price['BB_Signal'] = 0

# Generate buy/sell signals
indicators_with_price['BB_Signal'][indicators_with_price['Adj Close'] < indicators_with_price['Lower_BB']] = 2  # Buy signal
indicators_with_price['BB_Signal'][indicators_with_price['Adj Close'] > indicators_with_price['Upper_BB']] = 1  # Sell signal



indicators_with_price.head(50)

/tmp/ipykernel_18050/840148971.py:29: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_18050/840148971.py:30: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_18050/840148971.py:36: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_18050/840148971.py:37: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,RSI_SIGNAL,SMA_SIGNAL,MACD_Signal,BB_Signal
0,0.567014,0.443929,58.241601,7.100880,1.143620,43.382888,41.728832,40.074776,41.728832,40.814298,41.035721,-7.013324,-3.909598,2.715223,-3.124152e+08,42.355843,0,2,2,0
1,0.548494,0.464842,58.592114,7.332854,1.202904,43.261033,41.862707,40.464380,41.862707,40.847954,41.096608,-20.016700,-8.448344,2.714432,-2.214400e+08,42.405678,0,2,2,0
2,0.515806,0.475035,57.044942,6.516263,0.819328,43.280291,41.922405,40.564519,41.922405,40.878762,41.148143,-27.991838,-18.340621,2.690139,-3.790588e+08,42.256153,0,2,2,0
3,0.432813,0.466591,50.806392,3.052132,-0.254192,43.245421,41.956468,40.667514,41.956468,40.892874,41.168693,-36.985315,-28.331285,2.648797,-5.128460e+08,41.610508,0,2,1,0
4,0.361721,0.445617,50.674723,2.976529,-0.055679,43.183919,41.996702,40.809484,41.996702,40.897387,41.187696,-46.751996,-37.243050,2.644561,-5.914436e+08,41.596264,0,2,1,0
5,0.226727,0.401839,42.776436,-1.895784,-1.685963,43.175302,41.999076,40.822850,41.999076,40.886126,41.163972,-59.960257,-47.899189,2.611109,-7.396632e+08,40.653912,0,2,1,2
6,0.072556,0.335982,38.805945,-4.708055,-2.298210,43.330936,41.955756,40.580576,41.955756,40.863471,41.115773,-60.364790,-55.692348,2.604321,-9.056264e+08,40.079487,0,2,1,2
7,-0.123098,0.244166,33.410012,-9.019923,-3.037212,43.669846,41.830427,39.991008,41.830427,40.822443,41.028466,-57.037896,-59.120981,2.589764,-1.069742e+09,39.151379,0,2,1,2
8,-0.126721,0.169989,48.771961,0.230800,-0.833458,43.603899,41.756843,39.909787,41.756843,40.813906,41.027644,-35.113242,-50.838643,2.699325,-9.195768e+08,41.009972,0,2,1,0
9,-0.211999,0.093591,42.761393,-4.462410,-1.894447,43.620650,41.637566,39.654482,41.637566,40.775781,40.980124,-25.755897,-39.302345,2.704911,-1.083267e+09,39.958431,0,2,1,0
10,-0.311617,0.012549,40.504340,-6.346438,-1.669296,43.661174,41.499418,39.337662,41.499418,40.733080,40.915093,-23.129839,-27.999659,2.693601,-1.249941e+09,39.516926,0,2,1,0
11,-0.361497,-0.062260,42.777733,-4.867422,-0.625504,43.694934,41.413729,39.132524,41.413729,40.682793,40.866667,-31.638917,-26.841551,2.745527,-1.096347e+09,39.825508,0,2,1,0
12,-0.417286,-0.133265,41.338348,-5.999340,-0.981171,43.709493,41.300624,38.891754,41.300624,40.626527,40.808788,-33.349929,-29.372895,2.721525,-1.246694e+09,39.564400,0,2,1,0
13,-0.423862,-0.191385,44.466473,-4.030477,0.263947,43.655488,41.200573,38.745658,41.200573,40.582161,40.771521,-30.537760,-31.842202,2.714495,-1.125582e+09,39.970287,0,2,1,0
14,-0.363212,-0.225750,49.885843,-0.435808,1.262310,43.579273,41.140519,38.701764,41.140519,40.559985,40.769881,-23.649337,-29.179009,2.737189,-9.871604e+08,40.734615,0,2,1,0
15,-0.289022,-0.238404,51.759425,0.859626,1.436031,43.546091,41.114052,38.682012,41.114052,40.543269,40.780868,-13.681532,-22.622877,2.743310,-8.794276e+08,41.017078,0,2,1,0
16,-0.311297,-0.252983,45.025900,-3.853690,0.304123,43.457728,41.012457,38.567186,41.012457,40.518902,40.744736,-15.941870,-17.757580,2.697568,-1.019449e+09,39.967911,0,2,1,0
17,-0.293578,-0.261102,47.789659,-2.010608,2.421558,43.223494,40.894605,38.565715,40.894605,40.517169,40.727829,-20.849247,-16.824216,2.740926,-9.033780e+08,40.364326,0,2,1,0
18,-0.215757,-0.252033,52.696910,1.419593,4.129101,42.889426,40.794080,38.698733,40.794080,40.528735,40.745433,-19.855321,-18.882146,2.769123,-7.897436e+08,41.123905,0,2,2,0
19,-0.167665,-0.235159,51.380474,0.543905,2.390770,42.607667,40.704711,38.801754,40.704711,40.553241,40.753708,-10.385054,-17.029874,2.739621,-8.794700e+08,40.931637,0,2,2,0
20,-0.095885,-0.207304,53.978955,2.354527,3.619350,42.427112,40.653677,38.880242,40.653677,40.590498,40.779551,0.476957,-9.921139,2.745245,-7.879128e+08,41.335163,0,2,2,0
21,-0.027383,-0.171320,54.880229,2.981762,4.797199,42.237336,40.607154,38.976971,40.607154,40.628382,40.810469,4.591755,-1.772114,2.736644,-6.874156e+08,41.475208,0,1,2,0
22,0.047238,-0.127608,56.572332,4.145751,4.607296,42.118852,40.581043,39.043233,40.581043,40.669785,40.851512,13.925073,6.331262,2.724905,-6.011020e+08,41.733936,0,1,2,0
23,0.150988,-0.071889,60.145983,6.689110,3.686317,42.272667,40.615936,38.959205,40.615936,40.757097,40.916261,22.180899,13.565909,2.744631,-4.946804e+08,42.308369,0,1,2,1
24,0.222977,-0.012916,59.277653,6.212438,3.204468,42.395830,40.646793,38.897756,40.646793,40.861469,40.973912,28.084427,21.396800,2.719774,-5.776984e+08,42.213417,0,1,2,0
25,0.181404,0.025948,49.567771,0.427637,1.288895,42.421432,40.664952,38.908471,40.664952,40.910993,40.975831,20.146169,23.470498,2.642224,-7.169336e+08,41.017078,0,1,2,0
26,0.012703,0.023299,39.724013,-6.863845,-1.725670,42.461951,40.627803,38.793656,40.627803,40.943407,40.902973,-8.291022,13.313191,2.581203,-9.788980e+08,39.336517,0,1,1,0
27,-0.128703,-0.007101,39.156279,-7.330591,-1.706673,42.454276,40.631363,38.808451,40.631363,40.994299,40.828289,-34.550159,-7.565004,2.567794,-1.124960e+09,39.222584,0,1,1,0
28,-0.281576,-0.061996,36.466802,-9.553051,-2.114944,42.515717,40.514697,38.513677,40.514697,41.025299,40.732660,-45.877321,-29.572834,2.552946,-1.259728e+09,38.676643,0,1,1,0
29,-0.384694,-0.126536,37.885164,-8.729350,-1.761250,42.577350,40.459034,38.340719,40.459034,41.029761,40.648772,-39.397721,-39.941734,2.561904,-1.146200e+09,38.845177,0,1,1,0
30,-0.450308,-0.191290,39.061379,-8.061891,-1.965397,42.610306,40.432212,38.254118,40.432212,41.029192,40.574625,-33.203163,-39.492735,2.563719,-1.034348e+09,38.980480,0,1,1,0
31,-0.532560,-0.259544,36.575210,-9.947389,-3.128494,42.686410,40.367411,38.048411,40.367411,41.005218,40.483730,-32.805911,-35.135598,2.530741,-1.176971e+09,38.529480,0,1,1,0
32,-0.535265,-0.314688,42.657081,-6.489499,-3.254307,42.697387,40.350558,38.003728,40.350558,40.968521,40.427890,-28.594988,-31.534687,2.584653,-1.007261e+09,39.227337,0,1,1,0
33,-0.458572,-0.343465,49.472283,-2.193920,-2.205143,42.701498,40.358985,38.016471,40.358985,40.952712,40.415043,-18.764674,-26.721858,2.619511,-7.929836e+08,40.138828,0,1,1,0
34,-0.251812,-0.325134,59.544959,5.401827,-0.367924,42.852526,40.417852,37.983178,40.417852,40.975120,40.481573,5.866537,-13.831042,2.739451,-5.268260e+08,41.911961,0,1,2,0
35,-0.080893,-0.276286,59.913604,5.709020,0.448631,42.984213,40.466394,37.948574,40.466394,41.002749,40.548521,25.969057,4.356973,2.719708,-3.905532e+08,41.987915,0,1,2,0
36,0.185352,-0.183959,66.948289,12.047584,1.808739,43.506955,40.649761,37.792566,40.649761,41.056537,40.685710,45.736720,25.857438,2.816484,-1.657480e+08,43.635254,0,1,2,1
37,0.417020,-0.063763,68.103490,13.191902,1.979645,44.022553,40.829092,37.635631,40.829092,41.102396,40.830831,51.666111,41.123963,2.849753,4.057600e+06,43.950947,0,1,2,0
38,0.610626,0.071115,68.887164,13.958451,2.226505,44.489628,40.981007,37.472385,40.981007,41.136008,40.978892,58.084109,51.828980,2.832203,1.176688e+08,44.162205,0,1,2,0
39,0.780158,0.212924,70.053446,15.087762,2.926739,44.982156,41.158083,37.334010,41.158083,41.178591,41.134193,59.732775,56.494332,2.821888,2.105136e+08,44.473156,1,1,2,0
40,0.954838,0.361306,72.337967,17.358413,3.109501,45.541697,41.346790,37.151883,41.346790,41.235180,41.310864,63.227817,60.348234,2.843135,3.224708e+08,45.109299,1,2,2,0
41,1.067129,0.502471,70.769957,16.498702,2.216358,45.997978,41.519916,37.041854,41.519916,41.303149,41.472059,64.911988,62.624194,2.811890,2.176220e+08,44.937737,1,2,2,0
42,1.134580,0.628893,69.774483,15.967421,1.698475,46.380497,41.674863,36.969229,41.674863,41.363276,41.621428,64.592774,64.244193,2.785666,1.345068e+08,44.832882,0,2,2,0
43,1.141994,0.731513,65.895569,13.902006,1.706421,46.631595,41.780716,36.929837,41.780716,41.412359,41.746051,61.526786,63.677183,2.724877,3.972600e+07,44.425430,0,2,2,0
44,1.167861,0.818783,67.853875,15.469559,2.484188,46.941607,41.912047,36.882487,41.912047,41.470445,41.883561,61.088741,62.402767,2.722355,1.164584e+08,44.840031,0,2,2,0
45,1.152200,0.885466,65.100659,14.016836,2.150803,47.228045,42.089017,36.949989,42.089017,41.530647,42.002357,59.272275,60.629267,2.698435,4.728240e+07,44.556480,0,2,2,0
46,1.113873,0.931147,63.514678,13.184193,2.138294,47.411582,42.341914,37.272246,42.341914,41.578540,42.108673,56.482869,58.947962,2.676834,-2.590840e+07,44.394447,0,2,2,0
47,1.096243,0.964166,65.282833,14.425551,3.098484,47.573561,42.616234,37.658907,42.616234,41.618292,42.224242,45.620372,53.791839,2.694421,4.769480e+07,44.708992,0,2,2,0
48,1.061003,0.983534,64.091802,13.832513,3.000729,47.592550,42.912251,38.231953,42.912251,41.647543,42.329698,34.736777,45.613340,2.681320,-1.326800e+07,44.596992,0,2,2,0
49,1.044112,0.995650,65.806954,14.983585,4.229019,47.574087,43.214139,38.854191,43.214139,41.690822,42.443175,22.112332,34.156494,2.670369,6.696560e+07,44.882931,0,2,2,0

In [12]:
# Sum the signals for each row
indicators_with_price['Sum_Buy_Signals'] = (indicators_with_price[['RSI_SIGNAL', 'SMA_SIGNAL', 'MACD_Signal', 'BB_Signal']] == 2).sum(axis=1)
indicators_with_price['Sum_Sell_Signals'] = (indicators_with_price[['RSI_SIGNAL', 'SMA_SIGNAL', 'MACD_Signal', 'BB_Signal']] == 1).sum(axis=1)

# Define the conditions
conditions = [
    (indicators_with_price['Sum_Buy_Signals'] >= 3), # At least three buy signals - Strong Buy
    (indicators_with_price['Sum_Buy_Signals'] >= 2), # At least two buy signals - Buy
    (indicators_with_price['Sum_Sell_Signals'] >= 3), # At least three sell signals - Strong Sell
    (indicators_with_price['Sum_Sell_Signals'] >= 2), # At least two sell signals - Sell
]

# Define the choices corresponding to each condition
choices = [4, 3, 1, 2] # Strong Buy, Buy, Strong Sell, Sell

# Use np.select to apply the conditions and choices
# The default value is 0 (Neutral)
indicators_with_price['Signal'] = np.select(conditions, choices, default=0)

# Remove the sum columns if they are no longer needed
indicators_with_price = indicators_with_price.drop(columns=['Sum_Buy_Signals', 'Sum_Sell_Signals'])

# Display the dataframe to verify the results
indicators_with_price[['RSI_SIGNAL', 'SMA_SIGNAL', 'MACD_Signal', 'BB_Signal', 'Signal']].head(50)

    RSI_SIGNAL  SMA_SIGNAL  MACD_Signal  BB_Signal  Signal
0            0           2            2          0       3
1            0           2            2          0       3
2            0           2            2          0       3
3            0           2            1          0       0
4            0           2            1          0       0
5            0           2            1          2       3
6            0           2            1          2       3
7            0           2            1          2       3
8            0           2            1          0       0
9            0           2            1          0       0
10           0           2            1          0       0
11           0           2            1          0       0
12           0           2            1          0       0
13           0           2            1          0       0
14           0           2            1          0       0
15           0           2            1          0       0
16           0           2            1          0       0
17           0           2            1          0       0
18           0           2            2          0       3
19           0           2            2          0       3
20           0           2            2          0       3
21           0           1            2          0       0
22           0           1            2          0       0
23           0           1            2          1       2
24           0           1            2          0       0
25           0           1            2          0       0
26           0           1            1          0       2
27           0           1            1          0       2
28           0           1            1          0       2
29           0           1            1          0       2
30           0           1            1          0       2
31           0           1            1          0       2
32           0           1            1          0       2
33           0           1            1          0       2
34           0           1            2          0       0
35           0           1            2          0       0
36           0           1            2          1       2
37           0           1            2          0       0
38           0           1            2          0       0
39           1           1            2          0       2
40           1           2            2          0       3
41           1           2            2          0       3
42           0           2            2          0       3
43           0           2            2          0       3
44           0           2            2          0       3
45           0           2            2          0       3
46           0           2            2          0       3
47           0           2            2          0       3
48           0           2            2          0       3
49           0           2            2          0       3

In [13]:
signal_distribution = indicators_with_price['Signal'].value_counts().sort_index()
signal_distribution

Signal
0    697
1      4
2    263
3    504
4      7
Name: count, dtype: int64

In [14]:
# indicators_with_price['Next_Adj_Close'] = indicators_with_price['Adj Close'].shift(-1)
# indicators_with_price['Return'] = ((indicators_with_price['Next_Adj_Close'] - indicators_with_price['Adj Close'])/indicators_with_price['Adj Close'])*100
# indicators_with_price['Signal'] = np.where(indicators_with_price['Return'] > 1, 1,
#                                            np.where(indicators_with_price['Return'] < -1, 2, 0))
# indicators_with_price

In [15]:
indicators_with_price["Signal"].value_counts()

Signal
0    697
3    504
2    263
4      7
1      4
Name: count, dtype: int64

In [16]:
indicators_with_price.columns

Index(['MACD', 'MACD_signal', 'RSI', 'CMO', 'MOM', 'Upper_BB', 'Middle_BB',
       'Lower_BB', 'SMA_SHORT', 'SMA_LONG', 'EMA', 'SLOWK', 'SLOWD', 'ATR',
       'OBV', 'Adj Close', 'RSI_SIGNAL', 'SMA_SIGNAL', 'MACD_Signal',
       'BB_Signal', 'Signal'],
      dtype='object')

In [17]:
# indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close', 'Return'])
# indicators_with_price

In [18]:
indicators_with_price.drop(columns=['RSI_SIGNAL', 'SMA_SIGNAL', 'MACD_Signal', 'BB_Signal'], inplace=True)
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Signal
0,0.567014,0.443929,58.241601,7.100880,1.143620,43.382888,41.728832,40.074776,41.728832,40.814298,41.035721,-7.013324,-3.909598,2.715223,-3.124152e+08,42.355843,3
1,0.548494,0.464842,58.592114,7.332854,1.202904,43.261033,41.862707,40.464380,41.862707,40.847954,41.096608,-20.016700,-8.448344,2.714432,-2.214400e+08,42.405678,3
2,0.515806,0.475035,57.044942,6.516263,0.819328,43.280291,41.922405,40.564519,41.922405,40.878762,41.148143,-27.991838,-18.340621,2.690139,-3.790588e+08,42.256153,3
3,0.432813,0.466591,50.806392,3.052132,-0.254192,43.245421,41.956468,40.667514,41.956468,40.892874,41.168693,-36.985315,-28.331285,2.648797,-5.128460e+08,41.610508,0
4,0.361721,0.445617,50.674723,2.976529,-0.055679,43.183919,41.996702,40.809484,41.996702,40.897387,41.187696,-46.751996,-37.243050,2.644561,-5.914436e+08,41.596264,0
5,0.226727,0.401839,42.776436,-1.895784,-1.685963,43.175302,41.999076,40.822850,41.999076,40.886126,41.163972,-59.960257,-47.899189,2.611109,-7.396632e+08,40.653912,3
6,0.072556,0.335982,38.805945,-4.708055,-2.298210,43.330936,41.955756,40.580576,41.955756,40.863471,41.115773,-60.364790,-55.692348,2.604321,-9.056264e+08,40.079487,3
7,-0.123098,0.244166,33.410012,-9.019923,-3.037212,43.669846,41.830427,39.991008,41.830427,40.822443,41.028466,-57.037896,-59.120981,2.589764,-1.069742e+09,39.151379,3
8,-0.126721,0.169989,48.771961,0.230800,-0.833458,43.603899,41.756843,39.909787,41.756843,40.813906,41.027644,-35.113242,-50.838643,2.699325,-9.195768e+08,41.009972,0
9,-0.211999,0.093591,42.761393,-4.462410,-1.894447,43.620650,41.637566,39.654482,41.637566,40.775781,40.980124,-25.755897,-39.302345,2.704911,-1.083267e+09,39.958431,0
10,-0.311617,0.012549,40.504340,-6.346438,-1.669296,43.661174,41.499418,39.337662,41.499418,40.733080,40.915093,-23.129839,-27.999659,2.693601,-1.249941e+09,39.516926,0
11,-0.361497,-0.062260,42.777733,-4.867422,-0.625504,43.694934,41.413729,39.132524,41.413729,40.682793,40.866667,-31.638917,-26.841551,2.745527,-1.096347e+09,39.825508,0
12,-0.417286,-0.133265,41.338348,-5.999340,-0.981171,43.709493,41.300624,38.891754,41.300624,40.626527,40.808788,-33.349929,-29.372895,2.721525,-1.246694e+09,39.564400,0
13,-0.423862,-0.191385,44.466473,-4.030477,0.263947,43.655488,41.200573,38.745658,41.200573,40.582161,40.771521,-30.537760,-31.842202,2.714495,-1.125582e+09,39.970287,0
14,-0.363212,-0.225750,49.885843,-0.435808,1.262310,43.579273,41.140519,38.701764,41.140519,40.559985,40.769881,-23.649337,-29.179009,2.737189,-9.871604e+08,40.734615,0
15,-0.289022,-0.238404,51.759425,0.859626,1.436031,43.546091,41.114052,38.682012,41.114052,40.543269,40.780868,-13.681532,-22.622877,2.743310,-8.794276e+08,41.017078,0
16,-0.311297,-0.252983,45.025900,-3.853690,0.304123,43.457728,41.012457,38.567186,41.012457,40.518902,40.744736,-15.941870,-17.757580,2.697568,-1.019449e+09,39.967911,0
17,-0.293578,-0.261102,47.789659,-2.010608,2.421558,43.223494,40.894605,38.565715,40.894605,40.517169,40.727829,-20.849247,-16.824216,2.740926,-9.033780e+08,40.364326,0
18,-0.215757,-0.252033,52.696910,1.419593,4.129101,42.889426,40.794080,38.698733,40.794080,40.528735,40.745433,-19.855321,-18.882146,2.769123,-7.897436e+08,41.123905,3
19,-0.167665,-0.235159,51.380474,0.543905,2.390770,42.607667,40.704711,38.801754,40.704711,40.553241,40.753708,-10.385054,-17.029874,2.739621,-8.794700e+08,40.931637,3
20,-0.095885,-0.207304,53.978955,2.354527,3.619350,42.427112,40.653677,38.880242,40.653677,40.590498,40.779551,0.476957,-9.921139,2.745245,-7.879128e+08,41.335163,3
21,-0.027383,-0.171320,54.880229,2.981762,4.797199,42.237336,40.607154,38.976971,40.607154,40.628382,40.810469,4.591755,-1.772114,2.736644,-6.874156e+08,41.475208,0
22,0.047238,-0.127608,56.572332,4.145751,4.607296,42.118852,40.581043,39.043233,40.581043,40.669785,40.851512,13.925073,6.331262,2.724905,-6.011020e+08,41.733936,0
23,0.150988,-0.071889,60.145983,6.689110,3.686317,42.272667,40.615936,38.959205,40.615936,40.757097,40.916261,22.180899,13.565909,2.744631,-4.946804e+08,42.308369,2
24,0.222977,-0.012916,59.277653,6.212438,3.204468,42.395830,40.646793,38.897756,40.646793,40.861469,40.973912,28.084427,21.396800,2.719774,-5.776984e+08,42.213417,0
25,0.181404,0.025948,49.567771,0.427637,1.288895,42.421432,40.664952,38.908471,40.664952,40.910993,40.975831,20.146169,23.470498,2.642224,-7.169336e+08,41.017078,0
26,0.012703,0.023299,39.724013,-6.863845,-1.725670,42.461951,40.627803,38.793656,40.627803,40.943407,40.902973,-8.291022,13.313191,2.581203,-9.788980e+08,39.336517,2
27,-0.128703,-0.007101,39.156279,-7.330591,-1.706673,42.454276,40.631363,38.808451,40.631363,40.994299,40.828289,-34.550159,-7.565004,2.567794,-1.124960e+09,39.222584,2
28,-0.281576,-0.061996,36.466802,-9.553051,-2.114944,42.515717,40.514697,38.513677,40.514697,41.025299,40.732660,-45.877321,-29.572834,2.552946,-1.259728e+09,38.676643,2
29,-0.384694,-0.126536,37.885164,-8.729350,-1.761250,42.577350,40.459034,38.340719,40.459034,41.029761,40.648772,-39.397721,-39.941734,2.561904,-1.146200e+09,38.845177,2
30,-0.450308,-0.191290,39.061379,-8.061891,-1.965397,42.610306,40.432212,38.254118,40.432212,41.029192,40.574625,-33.203163,-39.492735,2.563719,-1.034348e+09,38.980480,2
31,-0.532560,-0.259544,36.575210,-9.947389,-3.128494,42.686410,40.367411,38.048411,40.367411,41.005218,40.483730,-32.805911,-35.135598,2.530741,-1.176971e+09,38.529480,2
32,-0.535265,-0.314688,42.657081,-6.489499,-3.254307,42.697387,40.350558,38.003728,40.350558,40.968521,40.427890,-28.594988,-31.534687,2.584653,-1.007261e+09,39.227337,2
33,-0.458572,-0.343465,49.472283,-2.193920,-2.205143,42.701498,40.358985,38.016471,40.358985,40.952712,40.415043,-18.764674,-26.721858,2.619511,-7.929836e+08,40.138828,2
34,-0.251812,-0.325134,59.544959,5.401827,-0.367924,42.852526,40.417852,37.983178,40.417852,40.975120,40.481573,5.866537,-13.831042,2.739451,-5.268260e+08,41.911961,0
35,-0.080893,-0.276286,59.913604,5.709020,0.448631,42.984213,40.466394,37.948574,40.466394,41.002749,40.548521,25.969057,4.356973,2.719708,-3.905532e+08,41.987915,0
36,0.185352,-0.183959,66.948289,12.047584,1.808739,43.506955,40.649761,37.792566,40.649761,41.056537,40.685710,45.736720,25.857438,2.816484,-1.657480e+08,43.635254,2
37,0.417020,-0.063763,68.103490,13.191902,1.979645,44.022553,40.829092,37.635631,40.829092,41.102396,40.830831,51.666111,41.123963,2.849753,4.057600e+06,43.950947,0
38,0.610626,0.071115,68.887164,13.958451,2.226505,44.489628,40.981007,37.472385,40.981007,41.136008,40.978892,58.084109,51.828980,2.832203,1.176688e+08,44.162205,0
39,0.780158,0.212924,70.053446,15.087762,2.926739,44.982156,41.158083,37.334010,41.158083,41.178591,41.134193,59.732775,56.494332,2.821888,2.105136e+08,44.473156,2
40,0.954838,0.361306,72.337967,17.358413,3.109501,45.541697,41.346790,37.151883,41.346790,41.235180,41.310864,63.227817,60.348234,2.843135,3.224708e+08,45.109299,3
41,1.067129,0.502471,70.769957,16.498702,2.216358,45.997978,41.519916,37.041854,41.519916,41.303149,41.472059,64.911988,62.624194,2.811890,2.176220e+08,44.937737,3
42,1.134580,0.628893,69.774483,15.967421,1.698475,46.380497,41.674863,36.969229,41.674863,41.363276,41.621428,64.592774,64.244193,2.785666,1.345068e+08,44.832882,3
43,1.141994,0.731513,65.895569,13.902006,1.706421,46.631595,41.780716,36.929837,41.780716,41.412359,41.746051,61.526786,63.677183,2.724877,3.972600e+07,44.425430,3
44,1.167861,0.818783,67.853875,15.469559,2.484188,46.941607,41.912047,36.882487,41.912047,41.470445,41.883561,61.088741,62.402767,2.722355,1.164584e+08,44.840031,3
45,1.152200,0.885466,65.100659,14.016836,2.150803,47.228045,42.089017,36.949989,42.089017,41.530647,42.002357,59.272275,60.629267,2.698435,4.728240e+07,44.556480,3
46,1.113873,0.931147,63.514678,13.184193,2.138294,47.411582,42.341914,37.272246,42.341914,41.578540,42.108673,56.482869,58.947962,2.676834,-2.590840e+07,44.394447,3
47,1.096243,0.964166,65.282833,14.425551,3.098484,47.573561,42.616234,37.658907,42.616234,41.618292,42.224242,45.620372,53.791839,2.694421,4.769480e+07,44.708992,3
48,1.061003,0.983534,64.091802,13.832513,3.000729,47.592550,42.912251,38.231953,42.912251,41.647543,42.329698,34.736777,45.613340,2.681320,-1.326800e+07,44.596992,3
49,1.044112,0.995650,65.806954,14.983585,4.229019,47.574087,43.214139,38.854191,43.214139,41.690822,42.443175,22.112332,34.156494,2.670369,6.696560e+07,44.882931,3

In [19]:
# y = indicators_with_price["Adj Close"]
# y_2 = indicators_with_price["SMA"]
# y_3 = indicators_with_price["EMA"]
# y_4 = indicators_with_price["Upper_BB"]
# y_5 = indicators_with_price["Middle_BB"]
# y_6 = indicators_with_price["Lower_BB"]
# X = np.array(date)

# trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
# trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
# trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
# trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
# trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
# trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



# layout = go.Layout(
#     title='Stock Price and Volume',
#     xaxis=dict(title='Date'),
#     yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
#     yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
#     yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
#     yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
#     yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
#     yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
#     height=600,
# )

# fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# # Show plot
# pyo.iplot(fig)

In [20]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        # Extract a window of data from X
        X_window = self.X[idx : idx + self.window_size]
        
        # Assuming you're predicting the value right after the window
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [21]:
X = indicators_with_price.iloc[:, :-1]
y = indicators_with_price.iloc[:,-1]

signal_true = indicators_with_price.iloc[:,-1]
y

0       3
1       3
2       3
3       0
4       0
       ..
1470    2
1471    2
1472    0
1473    0
1474    0
Name: Signal, Length: 1475, dtype: int64

In [22]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1180    0
1181    0
1182    3
1183    3
1184    3
       ..
1470    2
1471    2
1472    0
1473    0
1474    0
Name: Signal, Length: 295, dtype: int64

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
# X_train = X_train.to_numpy()
# y_train = y_train.to_numpy()
y_test.head(44)

1180    0
1181    0
1182    3
1183    3
1184    3
1185    3
1186    3
1187    2
1188    2
1189    0
1190    0
1191    0
1192    0
1193    0
1194    0
1195    0
1196    0
1197    0
1198    0
1199    3
1200    3
1201    2
1202    2
1203    2
1204    2
1205    2
1206    2
1207    2
1208    2
1209    2
1210    2
1211    2
1212    2
1213    2
1214    0
1215    0
1216    0
1217    0
1218    0
1219    0
1220    0
1221    0
1222    0
1223    2
Name: Signal, dtype: int64

In [24]:
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train), y=y_train)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)
class_weights[4]

59.0

In [25]:
# # Get the count of each unique value in the series
# category_counts = y_train.value_counts()
# print(category_counts.index)
# print(category_counts.values)

# # Create bar plot
# plt.bar(["1","0"], category_counts.values)

# # Adding labels and title
# plt.xlabel('Category')
# plt.ylabel('Frequency')
# plt.title('Distribution of Categories')

# # Show plot
# plt.show()

In [26]:
X_test

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
1180,0.423526,-0.563852,55.445392,0.846042,0.268082,156.691698,145.708436,134.725174,145.708436,146.191966,146.545681,65.483628,62.136599,5.360574,2.756478e+09,149.882217
1181,0.755432,-0.299995,56.065708,1.304430,-2.917862,157.096172,145.920445,134.744718,145.920445,146.076225,146.719165,69.529924,64.941426,5.178945,2.831307e+09,150.449066
1182,0.746664,-0.090663,51.612740,-1.380048,-8.582184,156.996709,145.861152,134.725595,145.861152,145.774922,146.739971,72.169962,69.061171,5.003954,2.772583e+09,147.187286
1183,0.903428,0.108155,54.204203,0.406558,-3.267166,156.748142,145.766296,134.784450,145.766296,145.707196,146.855759,73.612770,71.770885,4.895815,2.824387e+09,149.345215
1184,1.086560,0.303836,55.262544,1.137776,-1.409149,156.967746,145.864117,134.760489,145.864117,145.627983,147.005740,75.694642,73.825791,4.723971,2.882688e+09,150.230316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [27]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

X_train_df = X_train
X_test_df = X_test

for column in X_train.columns:

    if column not in ["RSI", "Upper_BB", "Lower_BB", "Middle_BB", "SMA_SHORT", "SMA_LONG", "Return"]:
        scaler = MinMaxScaler()

        # Fit on the training data and transform it
        X_train_scaled = scaler.fit_transform(X_train[[column]].values)
        X_train_df[column] = X_train_scaled
            
        # Transform the test data using the same scaler
        X_test_scaled = scaler.transform(X_test[[column]].values)
        X_test_df[column] = X_test_scaled

        scaler_dict[column] = scaler


X_train_df.head(24)

features = X_train_df.columns
X_train_df

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.510132,0.491711,58.241601,0.465351,0.498238,43.382888,41.728832,40.074776,41.728832,40.814298,0.013598,0.543591,0.529471,0.178111,0.245984,0.056481
1,0.508804,0.493383,58.592114,0.468236,0.498960,43.261033,41.862707,40.464380,41.862707,40.847954,0.014072,0.483866,0.507174,0.177936,0.261686,0.056823
2,0.506461,0.494198,57.044942,0.458080,0.494286,43.280291,41.922405,40.564519,41.922405,40.878762,0.014472,0.447235,0.458579,0.172548,0.234481,0.055798
3,0.500513,0.493523,50.806392,0.414999,0.481205,43.245421,41.956468,40.667514,41.956468,40.892874,0.014632,0.405928,0.409500,0.163379,0.211390,0.051371
4,0.495417,0.491846,50.674723,0.414059,0.483624,43.183919,41.996702,40.809484,41.996702,40.897387,0.014780,0.361069,0.365721,0.162439,0.197825,0.051273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,0.340107,0.343542,52.078571,0.349552,0.360230,154.868504,143.872760,132.877016,143.872760,146.786650,0.829435,0.680158,0.631199,0.850805,0.753803,0.767544
1176,0.388138,0.347930,54.750766,0.377027,0.321213,155.224487,144.447009,133.669532,144.447009,146.627571,0.830427,0.747328,0.665570,0.849088,0.770024,0.786842
1177,0.418622,0.358240,53.149272,0.363377,0.420018,155.507896,144.750603,133.993309,144.750603,146.482940,0.830887,0.835637,0.739664,0.803296,0.757360,0.777158
1178,0.453092,0.374178,54.909711,0.380639,0.423561,155.958144,145.075190,134.192236,145.075190,146.398729,0.831932,0.856512,0.802536,0.812803,0.772871,0.789160
1179,0.473178,0.391409,53.375703,0.368318,0.443981,156.233005,145.332166,134.431326,145.332166,146.261263,0.832500,0.850519,0.839325,0.765326,0.761787,0.780636

In [28]:

# BB bands
scaler_bb = MinMaxScaler()

scaler_bb.fit(X_train[['Middle_BB']].values)  

X_train_df['Upper_BB'] = scaler_bb.transform(X_train[['Upper_BB']].values).flatten()
X_train_df['Middle_BB'] = scaler_bb.transform(X_train[['Middle_BB']].values).flatten()
X_train_df['Lower_BB'] = scaler_bb.transform(X_train[['Lower_BB']].values).flatten()

X_test_df['Upper_BB'] = scaler_bb.transform(X_test[['Upper_BB']].values).flatten()
X_test_df['Middle_BB'] = scaler_bb.transform(X_test[['Middle_BB']].values).flatten()
X_test_df['Lower_BB'] = scaler_bb.transform(X_test[['Lower_BB']].values).flatten()

# MACD
scaler_macd = MinMaxScaler()
scaler_macd.fit(X_train[["MACD"]].values)

X_train_df['MACD'] = scaler_macd.transform(X_train[['MACD']].values).flatten()
X_train_df['MACD_signal'] = scaler_macd.transform(X_train[['MACD_signal']].values).flatten()

X_test_df['MACD'] = scaler_macd.transform(X_test[['MACD']].values).flatten()
X_test_df['MACD_signal'] = scaler_macd.transform(X_test[['MACD_signal']].values).flatten()

scaler_sma = MinMaxScaler()
scaler_sma.fit(X_train[["SMA_SHORT"]].values)

X_train_df['SMA_SHORT'] = scaler_sma.transform(X_train[['SMA_SHORT']].values).flatten()
X_train_df['SMA_LONG'] = scaler_sma.transform(X_train[['SMA_LONG']].values).flatten()

X_test_df['SMA_SHORT'] = scaler_sma.transform(X_test[['SMA_SHORT']].values).flatten()
X_test_df['SMA_LONG'] = scaler_sma.transform(X_test[['SMA_LONG']].values).flatten()

scaler_rsi = MinMaxScaler()
scaler_rsi.fit(X_train[["RSI"]].values)

X_train_df['RSI'] = scaler_rsi.transform(X_train[['RSI']].values).flatten()
X_test_df['RSI'] = scaler_rsi.transform(X_test[['RSI']].values).flatten()


X_test_df

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
1180,0.499847,0.411144,0.517394,0.387564,0.487569,0.871419,0.791684,0.711949,0.791684,0.795195,0.833706,0.876575,0.853920,0.764804,0.775662,0.793797
1181,0.523637,0.432238,0.527281,0.393264,0.448749,0.874356,0.793223,0.712091,0.793223,0.794354,0.835055,0.895160,0.867699,0.724522,0.788577,0.797684
1182,0.523008,0.448973,0.456307,0.359880,0.379729,0.873634,0.792793,0.711952,0.792793,0.792167,0.835217,0.907286,0.887937,0.685712,0.778442,0.775317
1183,0.534244,0.464868,0.497611,0.382098,0.444492,0.871829,0.792104,0.712380,0.792104,0.791675,0.836117,0.913913,0.901248,0.661729,0.787383,0.790114
1184,0.547371,0.480511,0.514480,0.391192,0.467132,0.873423,0.792814,0.712206,0.792814,0.791100,0.837282,0.923475,0.911343,0.623617,0.797445,0.796184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,0.331987,0.360467,0.219194,0.330143,0.438975,1.179515,1.104494,1.029472,1.104494,1.108087,1.152418,0.696649,0.699736,0.263755,0.912203,1.018693
1471,0.358007,0.354748,0.456177,0.434230,0.530971,1.173066,1.101858,1.030651,1.101858,1.109861,1.152792,0.728273,0.697238,0.316961,0.925666,1.059493
1472,0.396416,0.358741,0.541662,0.480565,0.534505,1.166205,1.099905,1.033606,1.099905,1.111685,1.154161,0.814261,0.731129,0.316623,0.937531,1.079584
1473,0.440664,0.371807,0.601114,0.515680,0.555950,1.164928,1.099564,1.034201,1.099564,1.113472,1.156274,0.926300,0.813002,0.323439,0.947909,1.095561
1474,0.483036,0.391711,0.631898,0.534630,0.550954,1.165655,1.099746,1.033836,1.099746,1.115292,1.158738,0.984412,0.904319,0.300461,0.955220,1.104406

In [29]:
correlation_matrix = X_train_df.corr()

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values,  # Rounded values for display
                    texttemplate="%{text}",
                    textfont={"size":9}  # Adjust text size if necessary
                    ))

# Update the layout
fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  # or any width you desire
    height=1000,  # or any height you desire
)

# Show the figure
pyo.iplot(fig)

In [30]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train.to_numpy(), dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test.to_numpy(), dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(0)[0])

tensor(2., device='cuda:0')
tensor([[0.4998, 0.4111, 0.5174, 0.3876, 0.4876, 0.8714, 0.7917, 0.7119, 0.7917,
         0.7952, 0.8337, 0.8766, 0.8539, 0.7648, 0.7757, 0.7938],
        [0.5236, 0.4322, 0.5273, 0.3933, 0.4487, 0.8744, 0.7932, 0.7121, 0.7932,
         0.7944, 0.8351, 0.8952, 0.8677, 0.7245, 0.7886, 0.7977],
        [0.5230, 0.4490, 0.4563, 0.3599, 0.3797, 0.8736, 0.7928, 0.7120, 0.7928,
         0.7922, 0.8352, 0.9073, 0.8879, 0.6857, 0.7784, 0.7753],
        [0.5342, 0.4649, 0.4976, 0.3821, 0.4445, 0.8718, 0.7921, 0.7124, 0.7921,
         0.7917, 0.8361, 0.9139, 0.9012, 0.6617, 0.7874, 0.7901],
        [0.5474, 0.4805, 0.5145, 0.3912, 0.4671, 0.8734, 0.7928, 0.7122, 0.7928,
         0.7911, 0.8373, 0.9235, 0.9113, 0.6236, 0.7974, 0.7962],
        [0.5399, 0.4914, 0.4471, 0.3605, 0.4592, 0.8745, 0.7941, 0.7137, 0.7941,
         0.7905, 0.8374, 0.9237, 0.9172, 0.5981, 0.7914, 0.7760],
        [0.5112, 0.4936, 0.3677, 0.3216, 0.4080, 0.8655, 0.7900, 0.7146, 0.7900,
         0.7896, 0.8361, 0.8756, 0.9035, 0.5869, 0.7794, 0.7495],
        [0.4709, 0.4865, 0.3118, 0.2921, 0.3590, 0.8593, 0.7857, 0.7121, 0.7857,
         0.7877, 0.8339, 0.7960, 0.8581, 0.5854, 0.7650, 0.7287],
        [0.4782, 0.4824, 0.4544, 0.3639, 0.4654, 0.8573, 0.7849, 0.7125, 0.7849,
         0.7865, 0.8341, 0.7774, 0.8059, 0.6453, 0.7842, 0.7755],
        [0.4855, 0.4807, 0.4597, 0.3667, 0.5578, 0.8590, 0.7861, 0.7133, 0.7861,
         0.7857, 0.8344, 0.7888, 0.7750, 0.6088, 0.7965, 0.7774],
        [0.4882, 0.4800, 0.4490, 0.3617, 0.6035, 0.8586, 0.7895, 0.7203, 0.7895,
         0.7851, 0.8345, 0.8188, 0.7831, 0.5723, 0.7852, 0.7740],
        [0.4834, 0.4783, 0.4231, 0.3496, 0.5378, 0.8565, 0.7924, 0.7284, 0.7924,
         0.7846, 0.8343, 0.7983, 0.7906, 0.5827, 0.7733, 0.7659],
        [0.4583, 0.4714, 0.3463, 0.3124, 0.4486, 0.8540, 0.7939, 0.7337, 0.7939,
         0.7835, 0.8327, 0.7377, 0.7723, 0.5960, 0.7621, 0.7405],
        [0.4275, 0.4590, 0.3088, 0.2931, 0.4211, 0.8529, 0.7944, 0.7359, 0.7944,
         0.7819, 0.8305, 0.6628, 0.7167, 0.5765, 0.7501, 0.7271],
        [0.4137, 0.4460, 0.3519, 0.3121, 0.4535, 0.8427, 0.7972, 0.7517, 0.7972,
         0.7809, 0.8291, 0.6220, 0.6538, 0.5583, 0.7608, 0.7388],
        [0.4007, 0.4327, 0.3416, 0.3072, 0.5122, 0.8438, 0.7955, 0.7472, 0.7955,
         0.7809, 0.8275, 0.6178, 0.6111, 0.5622, 0.7477, 0.7354],
        [0.4045, 0.4229, 0.4019, 0.3333, 0.5364, 0.8417, 0.7936, 0.7455, 0.7936,
         0.7819, 0.8268, 0.6636, 0.6114, 0.5462, 0.7599, 0.7513],
        [0.4138, 0.4171, 0.4266, 0.3443, 0.5657, 0.8406, 0.7926, 0.7446, 0.7926,
         0.7823, 0.8264, 0.7016, 0.6398, 0.5764, 0.7761, 0.7580],
        [0.4089, 0.4114, 0.3718, 0.3205, 0.5461, 0.8379, 0.7901, 0.7424, 0.7901,
         0.7820, 0.8253, 0.7177, 0.6754, 0.5921, 0.7619, 0.7426],
        [0.3676, 0.3977, 0.2382, 0.2535, 0.4085, 0.8418, 0.7857, 0.7296, 0.7857,
         0.7806, 0.8220, 0.6670, 0.6766, 0.6206, 0.7448, 0.6968],
        [0.3250, 0.3771, 0.2052, 0.2347, 0.4402, 0.8435, 0.7798, 0.7162, 0.7798,
         0.7790, 0.8181, 0.6070, 0.6429, 0.6081, 0.7171, 0.6833],
        [0.2812, 0.3510, 0.1712, 0.2147, 0.3655, 0.8442, 0.7730, 0.7019, 0.7730,
         0.7779, 0.8136, 0.5756, 0.5922, 0.5959, 0.7034, 0.6687],
        [0.2486, 0.3227, 0.1700, 0.2140, 0.3484, 0.8459, 0.7673, 0.6888, 0.7673,
         0.7768, 0.8093, 0.5907, 0.5650, 0.5762, 0.6900, 0.6682],
        [0.2435, 0.2990, 0.2674, 0.2523, 0.3853, 0.8405, 0.7620, 0.6835, 0.7620,
         0.7763, 0.8063, 0.6254, 0.5716, 0.5879, 0.7049, 0.6897],
        [0.2238, 0.2756, 0.2091, 0.2214, 0.3520, 0.8345, 0.7552, 0.6760, 0.7552,
         0.7755, 0.8023, 0.6347, 0.5927, 0.5853, 0.6914, 0.6677],
        [0.2090, 0.2536, 0.2026, 0.2178, 0.3005, 0.8309, 0.7494, 0.6678, 0.7494,
         0.7739, 0.7984, 0.6337, 0.6080, 0.5572, 0.6804, 0.6652],
        [0.1900, 0.2318, 0.1704, 0.2003, 0.2520, 0.8313, 0.7442, 0.6571, 0.7442,
         0.7727, 0.7940, 0.6029, 0.6000, 0.5297, 0.6685, 0.6527],
        [0.1556, 0.2067, 0.1075, 0.1632, 0.1687, 0.8361, 0.7388, 0.6415, 0.7388,
         0.7704, 0.7885, 0.5879, 0.5833, 0.5433, 0.6538, 0.6255],
        [0.1525, 0.1859, 0.2212, 0.2082, 0.2481, 0.8293, 0.7321, 0.6350, 0.7321,
         0.7684, 0.7844, 0.5958, 0.5698, 0.5557, 0.6668, 0.6498],
        [0.1555, 0.1699, 0.2309, 0.2122, 0.3070, 0.8200, 0.7255, 0.6310, 0.7255,
         0.7664, 0.7806, 0.6128, 0.5733, 0.5256, 0.6801, 0.6520],
        [0.1339, 0.1523, 0.1491, 0.1668, 0.1158, 0.8127, 0.7173, 0.6219, 0.7173,
         0.7638, 0.7753, 0.6174, 0.5839, 0.5644, 0.6608, 0.6189],
        [0.1280, 0.1369, 0.1898, 0.1832, 0.1605, 0.8036, 0.7100, 0.6163, 0.7100,
         0.7608, 0.7707, 0.6084, 0.5883, 0.5617, 0.6761, 0.6277],
        [0.1197, 0.1227, 0.1673, 0.1708, 0.1768, 0.7987, 0.7035, 0.6083, 0.7035,
         0.7573, 0.7658, 0.5885, 0.5796, 0.5389, 0.6622, 0.6185],
        [0.1434, 0.1167, 0.3052, 0.2288, 0.3005, 0.7931, 0.6994, 0.6058, 0.6994,
         0.7541, 0.7627, 0.6410, 0.5880, 0.5646, 0.6773, 0.6499],
        [0.1686, 0.1175, 0.3198, 0.2353, 0.3813, 0.7843, 0.6949, 0.6055, 0.6949,
         0.7513, 0.7599, 0.6945, 0.6188, 0.5655, 0.6895, 0.6535],
        [0.1951, 0.1240, 0.3365, 0.2425, 0.3916, 0.7753, 0.6908, 0.6063, 0.6908,
         0.7493, 0.7575, 0.7638, 0.6813, 0.5445, 0.7006, 0.6575],
        [0.2347, 0.1381, 0.4132, 0.2767, 0.4185, 0.7616, 0.6868, 0.6120, 0.6868,
         0.7462, 0.7561, 0.8140, 0.7430, 0.5309, 0.7126, 0.6763],
        [0.2680, 0.1568, 0.4111, 0.2759, 0.4105, 0.7429, 0.6825, 0.6221, 0.6825,
         0.7433, 0.7548, 0.8756, 0.8075, 0.5074, 0.7002, 0.6758],
        [0.3040, 0.1797, 0.4490, 0.2927, 0.4830, 0.7271, 0.6794, 0.6317, 0.6794,
         0.7411, 0.7540, 0.9451, 0.8721, 0.4925, 0.7102, 0.6850],
        [0.3408, 0.2063, 0.4816, 0.3075, 0.3519, 0.7262, 0.6792, 0.6322, 0.6792,
         0.7398, 0.7536, 0.9697, 0.9276, 0.4790, 0.7212, 0.6930],
        [0.3670, 0.2334, 0.4586, 0.2993, 0.3087, 0.7271, 0.6795, 0.6318, 0.6795,
         0.7393, 0.7530, 0.9536, 0.9554, 0.4712, 0.7092, 0.6880],
        [0.3890, 0.2600, 0.4604, 0.3001, 0.3267, 0.7299, 0.6805, 0.6312, 0.6805,
         0.7388, 0.7524, 0.9231, 0.9476, 0.4465, 0.7192, 0.6884],
        [0.4219, 0.2886, 0.5376, 0.3335, 0.3368, 0.7362, 0.6825, 0.6289, 0.6825,
         0.7387, 0.7528, 0.9317, 0.9341, 0.4445, 0.7331, 0.7062],
        [0.4667, 0.3215, 0.6197, 0.3738, 0.3912, 0.7452, 0.6846, 0.6239, 0.6846,
         0.7389, 0.7542, 0.9518, 0.9335, 0.4810, 0.7472, 0.7283]],
       device='cuda:0')

# Vanilla LSTM

In [31]:
class VanillaLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob):
        super(VanillaLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

# Stacked LSTM

In [32]:
class StackedLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, stateful):
        super(StackedLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size
        self.stateful = stateful
        
        self.hn = None
        self.cn = None

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=self.layer_size,
                            dropout=(dropout_prob if self.layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def reset_hidden_state(self, batch_size=None):
        if batch_size is None or not self.stateful:
            # Reset hidden and cell states to None if batch_size is not provided or if the model is not stateful
            self.hn = None
            self.cn = None
        else:
            # Resize hidden and cell states to match current batch size, preserving the state as much as possible
            self.hn = self._resize_state(self.hn, batch_size)
            self.cn = self._resize_state(self.cn, batch_size)


    def _resize_state(self, state, batch_size):
        if state is None:
            # If state is not initialized, initialize with zeros
            return torch.zeros(self.layer_size, batch_size, self.hidden_size).to(device)
        elif batch_size < state.size(1):
            # If batch size is smaller, truncate the state
            return state[:, :batch_size, :].contiguous()
        elif batch_size > state.size(1):
            # If batch size is larger, pad the state with zeros
            padding_size = batch_size - state.size(1)
            padding = torch.zeros(self.layer_size, padding_size, self.hidden_size).to(device)
            return torch.cat([state, padding], dim=1)
        

    def forward(self, x):
        current_batch_size = x.size(0)

        # Check and adjust the hidden and cell states
        if not self.stateful or self.hn is None or self.hn.size(1) != current_batch_size:
            self.reset_hidden_state(current_batch_size)
        else:
            # Detach the hidden states from the graph to avoid backpropagating through the entire sequence history
            self.hn = self.hn.detach()
            self.cn = self.cn.detach()

        # Ensure that hn and cn are not None and have the correct shape
        h0 = self.hn if self.hn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)
        c0 = self.cn if self.cn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0, c0))

        # Update hidden states if stateful
        if self.stateful:
            self.hn, self.cn = hn.detach(), cn.detach()

        # Process the output of the last time step
        out = self.dropout(out[:, -1, :])  # Add dropout
        out = self.fc(out)  # Fully connected layer

        return out

# Bidirectional LSTM

# 1D CNN-LSTM

In [33]:
class OneDimCNNLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, conv_channels, kernel_size, pool_size, stride):
        super(OneDimCNNLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # Convolutional Layer
        self.conv1 = nn.Conv1d(in_channels=input_dim, out_channels=conv_channels, kernel_size=kernel_size)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool1d(kernel_size=pool_size, stride=pool_size)

        # self.conv2 = nn.Conv1d(in_channels=conv_channels, out_channels=conv_channels*2, kernel_size=kernel_size)
        # self.relu2 = nn.ReLU()
        # self.maxpool2 = nn.MaxPool1d(kernel_size=2, stride=2)


        self.lstm = nn.LSTM(input_size = conv_channels, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # CNN in_dim: (batch_size, in_channels, length)
        x = x.transpose(1, 2)

        # Conv layer forward propagate
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.maxpool1(x)

        # x = self.conv2(x)
        # x = self.relu2(x)
        # x = self.maxpool2(x)

        # LSTM in_dim: (batch_size, seq_len, input_size)
        x = x.transpose(1, 2)

        assert x.size(-1) == self.lstm.input_size, f"Mismatch in LSTM input size. Expected: {self.lstm.input_size}, Got: {x.size(-1)}"

        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

In [34]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device, model_type):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model_type = model_type
        self.model = None
        self.optimizer = None
        self.criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)

    
    def train_validate(self, config, trial):

        if self.model_type == "Vanilla LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=5).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=5).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=5, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.long()


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    #loss = loss.mean()
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.long()

                        preds = self.model(data)
                        loss = self.criterion(preds, target)
                        #loss = loss.mean()

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
        if self.model_type == "Vanilla LSTM":

            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=5).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=5).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=5, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.long()  

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                #loss = loss.mean()
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.long()
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                _, predicted_classes = torch.max(preds, 1)
                all_preds.extend(predicted_classes.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [35]:
model_type = "1D CNN-LSTM"

def objective(trial):
    if model_type == "Vanilla LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.15),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 10, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9)
        }

    elif model_type == "Stacked LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "num_layers": trial.suggest_int("num_layers", 1, 5)
        }

    elif model_type == "1D CNN-LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "conv_channels": trial.suggest_int("conv_channels", 16, 128),
            "kernel_size": trial.suggest_int("kernel_size", 2, 6),
            "num_layers": trial.suggest_int("num_layers", 1, 5),
            "pool_size": trial.suggest_int("pool_size", 2, 5),
            "stride": trial.suggest_int("stride", 1, 4)
        }

    trainer = ModelActioner(train_data, test_data, device, model_type)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [36]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=15, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    # Optionally, you can include additional information in the progress bar
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=15, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-28 14:56:20,546] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/15 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6254671749644254, val_loss: 1.5595686303244696
epochs 2/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6253889218674904, val_loss: 1.5595051712459989
epochs 3/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6257305550949737, val_loss: 1.5594481892055936
epochs 4/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.625314801775348, val_loss: 1.559394015206231
epochs 5/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6272562711026657, val_loss: 1.5593411127726238
epochs 6/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.624392825895579, val_loss: 1.5592881970935397
epochs 7/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6254834024069822, val_loss: 1.5592350429958768
epochs 8/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.622115182626934, val_loss: 1.559181849161784
epochs 9/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.625385398015926, val_loss: 1.5591293838289049
epochs 10/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6240091504850938, val_loss: 1.5590766933229234
epochs 11/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6256455002030776, val_loss: 1.5590252346462674
epochs 12/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6228026632239057, val_loss: 1.5589708619647555
epochs 13/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.625817964214305, val_loss: 1.5589197476704915
epochs 14/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.627403822244774, val_loss: 1.5588694148593478
epochs 15/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6250250108579067, val_loss: 1.558818605211046
epochs 16/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6226458374742438, val_loss: 1.5587652524312336
epochs 17/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6249336004257202, val_loss: 1.5587127208709717
epochs 18/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6249737889354765, val_loss: 1.5586602422926161
epochs 19/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6247905655057018, val_loss: 1.5586081080966525
epochs 20/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6226023485523244, val_loss: 1.558557563357883
epochs 21/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6250718251572853, val_loss: 1.5585065020455255
epochs 22/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6248109084773439, val_loss: 1.5584554274876912
epochs 23/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6247843653743803, val_loss: 1.5584041277567546
epochs 24/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.623451516890401, val_loss: 1.55835141075982
epochs 25/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6246649763346968, val_loss: 1.5582988527086046
epochs 26/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6245547214727751, val_loss: 1.5582469304402669
epochs 27/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.623980710019616, val_loss: 1.558195087644789
epochs 28/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.624548227999223, val_loss: 1.5581431521309748
epochs 29/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6245121543944194, val_loss: 1.5580916669633653
epochs 30/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.624747132755699, val_loss: 1.5580408308241103
epochs 31/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.624748728662261, val_loss: 1.5579897827572293
epochs 32/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6238718862933015, val_loss: 1.5579391320546467
epochs 33/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6243868435864672, val_loss: 1.5578885078430176
epochs 34/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6243173857633981, val_loss: 1.5578378703859117
epochs 35/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6244066610386234, val_loss: 1.5577873256471422
epochs 36/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6244585794928186, val_loss: 1.557736701435513
epochs 37/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6238640627935919, val_loss: 1.5576862229241266
epochs 38/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.624323854271654, val_loss: 1.557635850376553
epochs 39/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.624188581062237, val_loss: 1.5575854116015964
epochs 40/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.62461623783511, val_loss: 1.5575349463356867
epochs 41/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6242056373526288, val_loss: 1.5574844545788236
epochs 42/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.623960390140873, val_loss: 1.5574342409769695
epochs 43/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6238275067344385, val_loss: 1.5573840538660686
epochs 44/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6223355725173552, val_loss: 1.5573348469204373
epochs 45/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.623622034232654, val_loss: 1.5572848982281156
epochs 46/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6236977365004455, val_loss: 1.5572350687450833
epochs 47/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6239690605882575, val_loss: 1.5571848683887057
epochs 48/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6235012071919066, val_loss: 1.5571352773242526
epochs 49/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6239816349838416, val_loss: 1.5570854875776503
epochs 50/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6232373290036985, val_loss: 1.5570365985234578
epochs 51/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6240476132687474, val_loss: 1.556986583603753
epochs 52/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.623588843495434, val_loss: 1.5569360388649836
epochs 53/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6234519269453918, val_loss: 1.5568857325447931
epochs 54/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6231915900844553, val_loss: 1.5568359560436673
epochs 55/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6234973731465365, val_loss: 1.5567861000696819
epochs 56/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.622910012749477, val_loss: 1.5567359659406874
epochs 57/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6234013553689288, val_loss: 1.556685447692871
epochs 58/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.623408821864902, val_loss: 1.5566354327731662
epochs 59/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6233059904338178, val_loss: 1.5565854178534613
epochs 60/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6230172711517175, val_loss: 1.5565359459982977
epochs 61/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6233775347315205, val_loss: 1.5564864873886108
epochs 62/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.623076485713739, val_loss: 1.5564370022879706
epochs 63/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6232827252742508, val_loss: 1.5563877820968628
epochs 64/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6234582656341074, val_loss: 1.5563390519883897
epochs 65/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6231954378607385, val_loss: 1.556290374861823
epochs 66/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6227672555683794, val_loss: 1.5562415785259671
epochs 67/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6230414968510574, val_loss: 1.5561923450893826
epochs 68/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6229528194946767, val_loss: 1.5561432441075642
epochs 69/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.620791991343673, val_loss: 1.5560933351516724
epochs 70/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6227438262619898, val_loss: 1.5560429493586223
Starting fold 2:
epochs 1/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6025516635493229, val_loss: 1.584348652097914
epochs 2/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.602238645051655, val_loss: 1.5842771927515666
epochs 3/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.602456658137472, val_loss: 1.5842044088575575
epochs 4/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6020066907531336, val_loss: 1.5841316646999783
epochs 5/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6006466131461294, val_loss: 1.5840586556328669
epochs 6/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6019206260379992, val_loss: 1.58398613664839
epochs 7/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6016710607629074, val_loss: 1.5839142666922674
epochs 8/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6014543313729135, val_loss: 1.5838426616456773
epochs 9/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6007739625479045, val_loss: 1.583771997027927
epochs 10/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.60050295214904, val_loss: 1.5837011999554105
epochs 11/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.601166462270837, val_loss: 1.5836306015650432
epochs 12/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6008013969973514, val_loss: 1.5835596323013306
epochs 13/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6007343925927815, val_loss: 1.5834890471564398
epochs 14/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6007641453492014, val_loss: 1.583418846130371
epochs 15/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6007216102198552, val_loss: 1.583348857031928
epochs 16/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6003599361369485, val_loss: 1.5832795566982694
epochs 17/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6001605485614978, val_loss: 1.5832104947831895
epochs 18/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6000671851007562, val_loss: 1.5831412341859605
epochs 19/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.599420782766844, val_loss: 1.583071854379442
epochs 20/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5994588682526036, val_loss: 1.5830014016893175
epochs 21/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5993755271560268, val_loss: 1.5829321013556585
epochs 22/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.6004205113963077, val_loss: 1.5828633175955877
epochs 23/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.599118413423237, val_loss: 1.58279554049174
epochs 24/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5996294975280763, val_loss: 1.5827282799614801
epochs 25/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5986568971684105, val_loss: 1.5826608207490709
epochs 26/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.599236367878161, val_loss: 1.5825944476657443
epochs 27/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5974571836622138, val_loss: 1.5825284322102864
epochs 28/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5984874744164317, val_loss: 1.5824623372819688
epochs 29/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5979541640532644, val_loss: 1.5823965469996135
epochs 30/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5978896617889404, val_loss: 1.5823310481177435
epochs 31/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5983682130512438, val_loss: 1.5822651651170518
epochs 32/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5972851182285108, val_loss: 1.5821988979975383
epochs 33/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5973706885388024, val_loss: 1.582133173942566
epochs 34/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5967978634332356, val_loss: 1.5820677147971258
epochs 35/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5971587501074138, val_loss: 1.5820027324888442
epochs 36/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.597169796416634, val_loss: 1.581938213772244
epochs 37/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5959296339436582, val_loss: 1.5818736553192139
epochs 38/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5967382217708388, val_loss: 1.5818094942304823
epochs 39/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.596898671200401, val_loss: 1.5817461411158245
epochs 40/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.596221101284027, val_loss: 1.5816831058926053
epochs 41/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5953212342764203, val_loss: 1.5816194878684149
epochs 42/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5957867321215178, val_loss: 1.5815562804539998
epochs 43/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.59521501189784, val_loss: 1.581493271721734
epochs 44/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5968864673062375, val_loss: 1.5814300907982721
epochs 45/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.595839660418661, val_loss: 1.5813677973217435
epochs 46/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5955942524106879, val_loss: 1.5813059012095134
epochs 47/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5951351015191328, val_loss: 1.5812436607148912
epochs 48/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5936852536703412, val_loss: 1.58118118180169
epochs 49/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5950947309795178, val_loss: 1.581118835343255
epochs 50/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.59453436073504, val_loss: 1.5810566478305392
epochs 51/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5944840820212114, val_loss: 1.5809942483901978
epochs 52/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5944063839159515, val_loss: 1.5809329085879855
epochs 53/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5939650548131843, val_loss: 1.5808710787031386
epochs 54/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5968623048380801, val_loss: 1.5808095269733005
epochs 55/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.593779312309466, val_loss: 1.5807464122772217
epochs 56/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5934885520684092, val_loss: 1.5806839598549738
epochs 57/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.593764102458954, val_loss: 1.580621878306071
epochs 58/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5935692649138602, val_loss: 1.580559942457411
epochs 59/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5933948786635148, val_loss: 1.5804970926708646
epochs 60/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5941691800167685, val_loss: 1.5804353290134006
epochs 61/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5935773416569359, val_loss: 1.5803742673661973
epochs 62/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5941223050418654, val_loss: 1.580314000447591
epochs 63/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5930954054782265, val_loss: 1.580253495110406
epochs 64/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5935367703437806, val_loss: 1.5801924467086792
epochs 65/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5926641740297016, val_loss: 1.5801314512888591
epochs 66/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5921961301251462, val_loss: 1.5800701909595065
epochs 67/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5923818688643605, val_loss: 1.5800089438756306
epochs 68/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5920843538485074, val_loss: 1.579947590827942
epochs 69/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5919613060198332, val_loss: 1.5798866748809814
epochs 70/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.591865437281759, val_loss: 1.5798260238435533
Starting fold 3:
epochs 1/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5893620610865642, val_loss: 1.5912066565619574
epochs 2/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5895227221068264, val_loss: 1.591058373451233
epochs 3/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5892729694269243, val_loss: 1.5909107393688626
epochs 4/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5890521374653848, val_loss: 1.5907636218600802
epochs 5/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5881966090579445, val_loss: 1.5906160275141399
epochs 6/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5891666672141773, val_loss: 1.5904658900366888
epochs 7/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5884462693454091, val_loss: 1.5903209050496419
epochs 8/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5886761302059689, val_loss: 1.590177853902181
epochs 9/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5877084499503271, val_loss: 1.5900351736280653
epochs 10/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5891361169530134, val_loss: 1.5898879369099934
epochs 11/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.587761326917236, val_loss: 1.5897378126780193
epochs 12/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5884882559466236, val_loss: 1.5895923243628607
epochs 13/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5881445215121304, val_loss: 1.589448504977756
epochs 14/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5877896335715778, val_loss: 1.5893008046680026
epochs 15/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5877459700790566, val_loss: 1.5891529189215765
epochs 16/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5896288701226715, val_loss: 1.5890077749888103
epochs 17/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5880185770024733, val_loss: 1.5888617303636339
epochs 18/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.588010916810463, val_loss: 1.5887196063995361
epochs 19/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5873357575052862, val_loss: 1.5885777605904474
epochs 20/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.586911617976291, val_loss: 1.5884366300370958
epochs 21/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5872413150455496, val_loss: 1.5882968372768826
epochs 22/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5873376533310526, val_loss: 1.588157852490743
epochs 23/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5869952599486903, val_loss: 1.5880169206195407
epochs 24/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5863365567631378, val_loss: 1.587877631187439
epochs 25/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5869355828146106, val_loss: 1.587739282184177
epochs 26/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5868971121541644, val_loss: 1.5876004033618503
epochs 27/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5862795822649722, val_loss: 1.5874618424309626
epochs 28/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.586423673193987, val_loss: 1.5873242086834378
epochs 29/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5863135822628, val_loss: 1.5871857272254095
epochs 30/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5867977628389436, val_loss: 1.5870450602637396

[I 2024-01-28 14:56:57,793] Trial 0 finished with value: 1.5985600346232218 and parameters: {'batch_size': 42, 'epochs': 70, 'hidden_size': 30, 'learning_rate': 4.05999705912671e-06, 'dropout_prob': 0.005070853974255618, 'weight_decay': 0.004294981668669153, 'lr_step_size': 58, 'gamma': 0.15438732294376198, 'conv_channels': 97, 'kernel_size': 5, 'num_layers': 2, 'pool_size': 5, 'stride': 4}. Best is trial 0 with value: 1.5985600346232218.

Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5526597868678689, val_loss: 1.64226410124037
epochs 70/70
Current Learning Rate: 4.05999705912671e-06
train_loss: 1.5529529964030104, val_loss: 1.6417806545893352
Mean validation loss: 1.5985600346232218
Starting fold 1:
epochs 1/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5976275486471765, val_loss: 1.5569378295272747
epochs 2/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6002826160161283, val_loss: 1.5567026384293088
epochs 3/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6036860599567753, val_loss: 1.5565177870805933
epochs 4/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5990099725922988, val_loss: 1.5564243541192757
epochs 5/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5924856550406412, val_loss: 1.5563999332448162
epochs 6/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6051772171290133, val_loss: 1.5563785998278825
epochs 7/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6038541668996762, val_loss: 1.5563865004393158
epochs 8/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.600820935209384, val_loss: 1.5563701082158972
epochs 9/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6007528099090016, val_loss: 1.556343641861406
epochs 10/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5961903009115088, val_loss: 1.5563083041912664
epochs 11/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.598807855426329, val_loss: 1.5562907059987385
epochs 12/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5986388054193628, val_loss: 1.5562734912942957
epochs 13/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5923500192102962, val_loss: 1.5562453661015425
epochs 14/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6054520357341666, val_loss: 1.556189534525392
epochs 15/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6035541658002044, val_loss: 1.556108588894839
epochs 16/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.608778648975632, val_loss: 1.5560569435200364
epochs 17/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6095369586145691, val_loss: 1.5560131476669716
epochs 18/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5956022670755836, val_loss: 1.5559644837858815
epochs 19/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6011727817395596, val_loss: 1.5559102031919692
epochs 20/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6051723339170685, val_loss: 1.5558503929269376
epochs 21/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5962427654815594, val_loss: 1.5557753333338984
epochs 22/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6049417269791608, val_loss: 1.5557258469717843
epochs 23/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5888570128935169, val_loss: 1.5557015030472368
epochs 24/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.591266424243987, val_loss: 1.5556722557733929
epochs 25/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5921614931515997, val_loss: 1.5556288200711448
epochs 26/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5919497474950022, val_loss: 1.5555828160079068
epochs 27/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5969710587206936, val_loss: 1.5555399933820049
epochs 28/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5948041758612188, val_loss: 1.5554768490412878
epochs 29/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5959730198246023, val_loss: 1.555403506314313
epochs 30/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5852126613337332, val_loss: 1.5553342835613029
epochs 31/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6055858135223389, val_loss: 1.555290594933525
epochs 32/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5897752215100833, val_loss: 1.5552551519303095
epochs 33/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5901078123072678, val_loss: 1.5552072575483373
epochs 34/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5871255791000047, val_loss: 1.5551522717904793
epochs 35/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.593498324224462, val_loss: 1.555113122576759
epochs 36/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5945333229933734, val_loss: 1.5550829367662864
epochs 37/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6032986934272406, val_loss: 1.5550356535684495
epochs 38/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5791067390541755, val_loss: 1.554983759683276
epochs 39/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5837010856698321, val_loss: 1.5549214510690599
epochs 40/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.592902405099719, val_loss: 1.5548765079054252
epochs 41/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5852093621698349, val_loss: 1.554838944364477
epochs 42/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5910157795351838, val_loss: 1.5548068814807467
epochs 43/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.58486033546987, val_loss: 1.5547796973475703
epochs 44/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5928109771918253, val_loss: 1.5547309722849931
epochs 45/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5823348829259423, val_loss: 1.5546928183742301
epochs 46/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5996194509935628, val_loss: 1.5546754794146018
epochs 47/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5865421469923089, val_loss: 1.5546503956355746
epochs 48/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5814270586243475, val_loss: 1.5546260561261858
epochs 49/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5870433964654413, val_loss: 1.554600199063619
epochs 50/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5987114675382046, val_loss: 1.554588062422616
epochs 51/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5789024561487568, val_loss: 1.5545483045477084
epochs 52/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5941236793058704, val_loss: 1.5545230517311701
epochs 53/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5858494286761857, val_loss: 1.5545154828873893
epochs 54/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5767542804098877, val_loss: 1.5544965595164626
epochs 55/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5790957524514324, val_loss: 1.5544858912311534
epochs 56/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5763479552343878, val_loss: 1.55447933850465
epochs 57/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5807691731378046, val_loss: 1.5544699771063668
epochs 58/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5799267429331834, val_loss: 1.5544872794832503
epochs 59/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5771322412640636, val_loss: 1.5544950867456102
epochs 60/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.6018416432185947, val_loss: 1.5545247704894454
epochs 61/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5927435584093264, val_loss: 1.5545327461585796
epochs 62/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5818291278409709, val_loss: 1.5545175081838376
epochs 63/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5783942007893668, val_loss: 1.5544857013793218
epochs 64/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5816882561638717, val_loss: 1.5544390659483651
epochs 65/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5804108624683, val_loss: 1.5544100848455278
epochs 66/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.579723656489587, val_loss: 1.5544204011796012
epochs 67/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5857830865220874, val_loss: 1.554427081945712
epochs 68/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5826056933527841, val_loss: 1.5544134119831066
epochs 69/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5718913384132984, val_loss: 1.55437247526078
epochs 70/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.583547535367037, val_loss: 1.5543193974822918
epochs 71/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.580219273167755, val_loss: 1.5542798742415413
epochs 72/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5842048897169023, val_loss: 1.5542592352660245
epochs 73/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5819434333222075, val_loss: 1.554259418179749
epochs 74/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5848013980226368, val_loss: 1.5542561137487019
epochs 75/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5832824863064352, val_loss: 1.554249026787975
epochs 76/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5830797674768258, val_loss: 1.5542164725601357
epochs 77/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.576665558115974, val_loss: 1.5541759514934803
epochs 78/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5846139423510166, val_loss: 1.5541692568511558
epochs 79/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5803117858177704, val_loss: 1.5541704520977364
epochs 80/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5814617142003244, val_loss: 1.554180690220424
epochs 81/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5786919225572915, val_loss: 1.5542018615379536
epochs 82/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5886305096261788, val_loss: 1.5542701293551733
Starting fold 2:
epochs 1/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5783596465462133, val_loss: 1.617833927825645
epochs 2/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5747064891614413, val_loss: 1.6184826944240187
epochs 3/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5695685687818026, val_loss: 1.6191346229068817
epochs 4/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5740453669899388, val_loss: 1.6198332221419722
epochs 5/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5660471753070229, val_loss: 1.6205578254013466
epochs 6/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5638555664765208, val_loss: 1.6212967123304094
epochs 7/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5728447148674414, val_loss: 1.6220598542501057
epochs 8/82
Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5674185514450074, val_loss: 1.6228240677919337
epochs 9/82

[I 2024-01-28 14:57:02,011] Trial 1 pruned.

Current Learning Rate: 3.572889522949767e-05
train_loss: 1.5641566866322567, val_loss: 1.6235981227228882
epochs 10/82
Starting fold 1:
epochs 1/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6091242317129804, val_loss: 1.5676925560784718
epochs 2/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.609331577860248, val_loss: 1.567258322680438
epochs 3/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6148601271095075, val_loss: 1.5668131661793543
epochs 4/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.608880408771375, val_loss: 1.5663684682240562
epochs 5/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.609747079654514, val_loss: 1.5659253117899414
epochs 6/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6095286233262867, val_loss: 1.5654849709657135
epochs 7/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.610928036155501, val_loss: 1.5650530031749181
epochs 8/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.609022157978637, val_loss: 1.564623168536595
epochs 9/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6103862018485344, val_loss: 1.5641916208166293
epochs 10/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.609791484178673, val_loss: 1.5637587617944788
epochs 11/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6098229485656579, val_loss: 1.5633270917115387
epochs 12/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6102384335083486, val_loss: 1.5628999313980183
epochs 13/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6101957902858395, val_loss: 1.5624799665319857
epochs 14/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6101597678598933, val_loss: 1.5620592378434681
epochs 15/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.608217888477585, val_loss: 1.5616305473620298
epochs 16/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6099055531137276, val_loss: 1.5611959159689606
epochs 17/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6059123620937008, val_loss: 1.5607557139068684
epochs 18/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6105085255587912, val_loss: 1.5603139148187386
epochs 19/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6103991956610955, val_loss: 1.5598710434777396
epochs 20/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6106234501793746, val_loss: 1.5594270387023845
epochs 21/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6094344448668794, val_loss: 1.5589811984824125
epochs 22/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6091874713048886, val_loss: 1.5585374794309101
epochs 23/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6105535954080952, val_loss: 1.558094861015441
epochs 24/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.611438360513817, val_loss: 1.5576528701832686
epochs 25/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6159672325194194, val_loss: 1.5572075225688793
epochs 26/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6082512077860807, val_loss: 1.5567599749438976
epochs 27/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6110728873008209, val_loss: 1.5563114332774328
epochs 28/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6109535051265935, val_loss: 1.555863727968206
epochs 29/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6102111114881426, val_loss: 1.5554160346429815
epochs 30/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6115089274201717, val_loss: 1.5549649019089957
epochs 31/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6114195217012734, val_loss: 1.5545127114290913
epochs 32/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.611156013623582, val_loss: 1.554059871920833
epochs 33/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6101793668657074, val_loss: 1.5536011564668524
epochs 34/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.610808722011706, val_loss: 1.5531366312945332
epochs 35/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6115621578006845, val_loss: 1.5526693113266476
epochs 36/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6107446179964156, val_loss: 1.5522001111318195
epochs 37/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6114590798372999, val_loss: 1.55172881310579
epochs 38/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6105510246067147, val_loss: 1.5512505757114874
epochs 39/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6091194315106456, val_loss: 1.5507751596037043
epochs 40/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6113925423297581, val_loss: 1.5503019308917736
epochs 41/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.61229602079741, val_loss: 1.5498295971956202
epochs 42/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6114577248458464, val_loss: 1.5493482483757868
epochs 43/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6133420248930368, val_loss: 1.5488583682075379
epochs 44/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6132547917790439, val_loss: 1.5483638180626764
epochs 45/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6115201761585256, val_loss: 1.5478644301651647
epochs 46/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6128401687632057, val_loss: 1.5473581464202315
epochs 47/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6066658783957597, val_loss: 1.5468444048412262
epochs 48/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6130968538254344, val_loss: 1.5463252017106959
epochs 49/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6117758619847722, val_loss: 1.545801489441483
epochs 50/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.613567616927062, val_loss: 1.5452751469990564
epochs 51/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6127987750537733, val_loss: 1.544748375024745
epochs 52/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.612963712028184, val_loss: 1.544214712879645
epochs 53/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6129324105397569, val_loss: 1.5436746714607117
epochs 54/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6131272590597263, val_loss: 1.543129149568144
epochs 55/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6140024262573083, val_loss: 1.5425791109680498
epochs 56/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6135883418677366, val_loss: 1.5420227227387604
epochs 57/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6128246609453132, val_loss: 1.541457798745897
epochs 58/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6104595099444166, val_loss: 1.540884190766269
epochs 59/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.612862315477501, val_loss: 1.5403055930263783
epochs 60/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6084469431981991, val_loss: 1.5397166802138877
epochs 61/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6140067308985127, val_loss: 1.539121737555852
epochs 62/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6132061912127191, val_loss: 1.5385205752004392
epochs 63/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6178471124609104, val_loss: 1.5379227790882979
epochs 64/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6137913409327962, val_loss: 1.5373183148247855
epochs 65/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6143573266673463, val_loss: 1.5367088015117343
epochs 66/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6158573240509833, val_loss: 1.5361026512882696
epochs 67/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.615061428534423, val_loss: 1.5354950995672316
epochs 68/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6148430776845721, val_loss: 1.5348745868319558
epochs 69/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6148350313695938, val_loss: 1.5342413180719607
epochs 70/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6150457590662373, val_loss: 1.5335979745501565
epochs 71/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.6150687027976152, val_loss: 1.5329414568250141
epochs 72/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.61502432261462, val_loss: 1.5322731682863184
Starting fold 2:
epochs 1/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5743436515331268, val_loss: 1.5945392708299022
epochs 2/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5742214024066925, val_loss: 1.5945199702782606
epochs 3/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5733602046966553, val_loss: 1.5945294464706743
epochs 4/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.573045790195465, val_loss: 1.5945544192399927
epochs 5/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5727016627788544, val_loss: 1.5945880854571308
epochs 6/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5707328021526337, val_loss: 1.5946359577633085
epochs 7/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.570539653301239, val_loss: 1.5946875110505119
epochs 8/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5707058906555176, val_loss: 1.5947403497796842
epochs 9/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5699364840984344, val_loss: 1.5947928447572013
epochs 10/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5698588490486145, val_loss: 1.5948488907839256
epochs 11/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5705534517765045, val_loss: 1.5949204289723957
epochs 12/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.569642186164856, val_loss: 1.59499354400332
epochs 13/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5689506232738495, val_loss: 1.5950659835149372
epochs 14/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.568560242652893, val_loss: 1.595141951999967
epochs 15/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5679743885993958, val_loss: 1.5952239143785345
epochs 16/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5667627155780792, val_loss: 1.5953187097317327
epochs 17/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5679940581321716, val_loss: 1.5954139629999797
epochs 18/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5661942958831787, val_loss: 1.5955174492780493
epochs 19/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5656964778900146, val_loss: 1.5956312272914503
epochs 20/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5637980699539185, val_loss: 1.5957530522472645
epochs 21/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5644100606441498, val_loss: 1.5958808546974546
epochs 22/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5641106367111206, val_loss: 1.596011302458546
epochs 23/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5629068315029144, val_loss: 1.5961451530456543
epochs 24/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5635735392570496, val_loss: 1.596282683352314
epochs 25/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5633865296840668, val_loss: 1.5964253932710677
epochs 26/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.562842220067978, val_loss: 1.596574756203505
epochs 27/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5620984733104706, val_loss: 1.5967298134294137
epochs 28/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.561570405960083, val_loss: 1.5968922288329512
epochs 29/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5638433694839478, val_loss: 1.597063940668863
epochs 30/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5603103637695312, val_loss: 1.5972498232725436
epochs 31/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.559875637292862, val_loss: 1.5974477914275316
epochs 32/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5594529509544373, val_loss: 1.5976578653174103
epochs 33/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5588618218898773, val_loss: 1.5978764957851834
epochs 34/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5588807463645935, val_loss: 1.59811543156861
epochs 35/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5588506758213043, val_loss: 1.5983645329399714
epochs 36/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.554801106452942, val_loss: 1.5986351783944186
epochs 37/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5560973584651947, val_loss: 1.5989234510552945
epochs 38/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5566141605377197, val_loss: 1.5992197063234117
epochs 39/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5527001321315765, val_loss: 1.5995294240416673
epochs 40/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5540737211704254, val_loss: 1.599855103189983
epochs 41/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.554636001586914, val_loss: 1.6002001749775396
epochs 42/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5507860481739044, val_loss: 1.6005821619084273
epochs 43/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5515941679477692, val_loss: 1.6009861338075506
epochs 44/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5502080023288727, val_loss: 1.6014158057157324
epochs 45/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5496381223201752, val_loss: 1.6018599826822837
epochs 46/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5470815300941467, val_loss: 1.6023323157477
epochs 47/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5469390749931335, val_loss: 1.6028343691396965
epochs 48/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5467272996902466, val_loss: 1.6033656767436437
epochs 49/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5455314815044403, val_loss: 1.6039278765834828
epochs 50/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5452597439289093, val_loss: 1.6045151753400368
epochs 51/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5471531450748444, val_loss: 1.6051342077356168
epochs 52/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5454286932945251, val_loss: 1.6057858347262024
epochs 53/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.541587233543396, val_loss: 1.6064611616588773
epochs 54/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.541451781988144, val_loss: 1.6071629946824735
epochs 55/72
Epoch 00055: reducing learning rate of group 0 to 6.9098e-06.
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5411782562732697, val_loss: 1.6078980757445884
epochs 56/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5377933382987976, val_loss: 1.608001950556639
epochs 57/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5398630499839783, val_loss: 1.6081061924576128
epochs 58/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5414625406265259, val_loss: 1.6082098130826596
epochs 59/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5395523011684418, val_loss: 1.6083107158620522
epochs 60/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5412193834781647, val_loss: 1.6084105047599349
epochs 61/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.542160302400589, val_loss: 1.6085101441731529
epochs 62/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5391572415828705, val_loss: 1.6086114581930575
epochs 63/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5403172075748444, val_loss: 1.6087125344251199
epochs 64/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5397891104221344, val_loss: 1.6088133331329104
epochs 65/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5387739539146423, val_loss: 1.6089121122208854
epochs 66/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.538991928100586, val_loss: 1.6090100473827786
epochs 67/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5373980700969696, val_loss: 1.609107079329314
epochs 68/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5371308326721191, val_loss: 1.6092063920207755
epochs 69/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5380439460277557, val_loss: 1.6093059437615531
epochs 70/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5388959348201752, val_loss: 1.6094039754262046
epochs 71/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5384548008441925, val_loss: 1.6095030730363553
epochs 72/72
Current Learning Rate: 6.909807233788718e-06
train_loss: 1.5388352572917938, val_loss: 1.6096022873328477
Starting fold 3:
epochs 1/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5618028083459354, val_loss: 1.6672350206072368
epochs 2/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.559934894104205, val_loss: 1.6678740725946175
epochs 3/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5607586985941722, val_loss: 1.66851678537944
epochs 4/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5612975122220487, val_loss: 1.6691573587044206
epochs 5/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5599729080401321, val_loss: 1.6697981155738628
epochs 6/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5606718899286065, val_loss: 1.670445165306172
epochs 7/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5573255062522284, val_loss: 1.671137944731132
epochs 8/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.55744889813274, val_loss: 1.6718567124119512
epochs 9/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5568122444756212, val_loss: 1.6725763328491696
epochs 10/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5572038055094768, val_loss: 1.6733213335117967
epochs 11/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5562663486846093, val_loss: 1.6740485480222753
epochs 12/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.557298538345444, val_loss: 1.6747729853978233
epochs 13/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.554322526408834, val_loss: 1.6755206010959767
epochs 14/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5533366192832772, val_loss: 1.6763209363140126
epochs 15/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5541762090525435, val_loss: 1.6771559677426777
epochs 16/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5586411278360968, val_loss: 1.6779530288050415
epochs 17/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.559146029877956, val_loss: 1.6786306743268613
epochs 18/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.555462427005198, val_loss: 1.6793447114803173
epochs 19/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5542856159444853, val_loss: 1.680086335177144
epochs 20/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.552473978753249, val_loss: 1.6808739761826854
epochs 21/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5544618464521867, val_loss: 1.6816909880865187
epochs 22/72
Current Learning Rate: 5.096215987751791e-05
train_loss: 1.5498079155786175, val_loss: 1.682485789849014
epochs 23/72
Current Learning Rate: 5.096215987751791e-05

[I 2024-01-28 14:57:30,830] Trial 2 finished with value: 1.6204836070169635 and parameters: {'batch_size': 95, 'epochs': 72, 'hidden_size': 39, 'learning_rate': 5.096215987751791e-05, 'dropout_prob': 0.010060641611712585, 'weight_decay': 3.7893644194748283e-06, 'lr_step_size': 53, 'gamma': 0.13558701692384503, 'conv_channels': 33, 'kernel_size': 5, 'num_layers': 3, 'pool_size': 3, 'stride': 1}. Best is trial 0 with value: 1.5985600346232218.

Current Learning Rate: 5.096215987751791e-05
train_loss: 1.4503571608250345, val_loss: 1.4733545370202847
Mean validation loss: 1.6204836070169635
Starting fold 1:
epochs 1/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.618983165755946, val_loss: 1.567522922520915
epochs 2/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.6032137396447945, val_loss: 1.5639291907113695
epochs 3/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.6036369719430414, val_loss: 1.5615041552397309
epochs 4/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.600899772494251, val_loss: 1.5582697240133134
epochs 5/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.5947598986600706, val_loss: 1.5534373452423742
epochs 6/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.5884002216199307, val_loss: 1.5464802658747112
epochs 7/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.5832341578618394, val_loss: 1.53587758162665
epochs 8/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.5797965420478302, val_loss: 1.52016700449444
epochs 9/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.5702350295651022, val_loss: 1.4995716892222248
epochs 10/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.536478294752031, val_loss: 1.476020751806794
epochs 11/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.5172108424271589, val_loss: 1.4597107399077642
epochs 12/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.491894435508089, val_loss: 1.463824612122995
epochs 13/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.4609824238023208, val_loss: 1.4803481537198264
epochs 14/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.4358917094025936, val_loss: 1.5137254876434487
epochs 15/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.417942053984597, val_loss: 1.5501968274040827
epochs 16/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.397147745362127, val_loss: 1.616398228539361
epochs 17/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.3500160565551038, val_loss: 1.6520743862030998
epochs 18/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.3273853007411458, val_loss: 1.713096016929263
epochs 19/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.2908749336971663, val_loss: 1.72441237061112
epochs 20/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.262207254065269, val_loss: 1.7069036683077534
epochs 21/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.2418209351794258, val_loss: 1.781089600431856
epochs 22/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.2692053124542635, val_loss: 1.694490118632241
epochs 23/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.306468092334208, val_loss: 1.678547326219145
epochs 24/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.1903058134448465, val_loss: 1.6403750282116036
epochs 25/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.1725518996802924, val_loss: 1.629725835310719
epochs 26/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.1191436220838138, val_loss: 1.7638438725597645
epochs 27/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.074173495407504, val_loss: 1.8481500110928974
epochs 28/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.01344247887896, val_loss: 1.9061295721266005
epochs 29/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.9754774476845227, val_loss: 1.8669890960057576
epochs 30/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.9172813542850354, val_loss: 1.9980102954087433
epochs 31/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.840947166475326, val_loss: 1.8921604030346744
epochs 32/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.8360520195586519, val_loss: 2.280484367299963
epochs 33/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.8220464593452933, val_loss: 1.8601238588807445
epochs 34/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7672971983230551, val_loss: 2.1399584333732644
epochs 35/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7423265763602331, val_loss: 2.377054886843162
epochs 36/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7642297994403939, val_loss: 1.810122602831119
epochs 37/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.1716641065962028, val_loss: 2.1318395850519654
epochs 38/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.2700107990135072, val_loss: 2.0635305586315336
epochs 39/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7005016554088492, val_loss: 1.8700201334776703
epochs 40/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.8367983982825155, val_loss: 2.348853452495797
epochs 41/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.8927596248881355, val_loss: 2.257427693674804
epochs 42/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7617246817543869, val_loss: 2.3023052467870966
epochs 43/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7117520068328418, val_loss: 1.960750972152387
epochs 44/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7557206659416877, val_loss: 2.2212342774426497
epochs 45/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7254291289139793, val_loss: 2.28735019290258
epochs 46/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.6792644927014855, val_loss: 2.268648898160016
epochs 47/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.6991196368377246, val_loss: 2.2400193189187023
epochs 48/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.6536391954771511, val_loss: 2.372479128459143
epochs 49/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.6399515761130767, val_loss: 2.4280391641394803
epochs 50/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.6155943127826871, val_loss: 2.4105404508176935
epochs 51/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.6054611861393714, val_loss: 2.400710376482161
epochs 52/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.6111215974023829, val_loss: 2.472795505372305
epochs 53/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.5861531923578672, val_loss: 2.462977240325282
epochs 54/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.5830594079656751, val_loss: 2.459226297953772
epochs 55/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.5762895748253268, val_loss: 2.4639567761194137
epochs 56/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.5728205673357579, val_loss: 2.5636657394429365
epochs 57/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.5530150904081255, val_loss: 2.604534175030138
epochs 58/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.5478503894431429, val_loss: 2.6816250615649753
epochs 59/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.5658333950641892, val_loss: 2.698131688688167
epochs 60/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.6357621531836025, val_loss: 2.5835466321814
epochs 61/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.8738222237656877, val_loss: 1.8353275382329548
epochs 62/65
Epoch 00062: reducing learning rate of group 0 to 1.4773e-04.
Current Learning Rate: 0.00014773394453020865
train_loss: 0.7701047914814575, val_loss: 2.9909178415934243
epochs 63/65
Current Learning Rate: 0.00014773394453020865
train_loss: 0.6521421368209479, val_loss: 2.9502835942323875
epochs 64/65
Current Learning Rate: 0.00014773394453020865
train_loss: 0.5851482221593407, val_loss: 2.8154453032861944
epochs 65/65
Current Learning Rate: 0.00014773394453020865
train_loss: 0.5555547478935481, val_loss: 2.7002980791071733
Starting fold 2:
epochs 1/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.5656985922863609, val_loss: 3.28414201358008
epochs 2/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.5612096802184456, val_loss: 2.6407966525466353
epochs 3/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.207115938788966, val_loss: 2.674853937966483
epochs 4/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.211654815234636, val_loss: 2.628947549396091
epochs 5/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.1643115313429582, val_loss: 2.7038266507406084
epochs 6/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.1212952450702065, val_loss: 2.730358808759659
epochs 7/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.0748410507252342, val_loss: 2.8868267965064476
epochs 8/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.046921464957689, val_loss: 2.8328752177102223
epochs 9/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.0001576636966907, val_loss: 2.898712883550654
epochs 10/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.987540204274027, val_loss: 2.8185350983231157
epochs 11/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.9582503171343553, val_loss: 2.8983213699683943
epochs 12/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.8985730346880461, val_loss: 2.9820288943235207
epochs 13/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.8610118533435621, val_loss: 3.1177773791015464
epochs 14/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.9278355052596644, val_loss: 3.112106755927757
epochs 15/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.8296188249399787, val_loss: 3.224614519290823
epochs 16/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.0696330705755634, val_loss: 3.0653798668472856
epochs 17/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.9615501322244343, val_loss: 3.4447161608902865
epochs 18/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.9843504954325525, val_loss: 3.134440302218079
epochs 19/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.1511414756900387, val_loss: 3.169234214005647
epochs 20/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.0075276070519497, val_loss: 3.0993598958171864
epochs 21/65
Current Learning Rate: 0.0006680716275190299
train_loss: 1.059578345010155, val_loss: 3.0266050522920316
epochs 22/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.9162638054082268, val_loss: 3.3094305411848444
epochs 23/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.8477071939330352, val_loss: 3.6182043501939725
epochs 24/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7959195461712385, val_loss: 3.628427714897842
epochs 25/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.757045650168469, val_loss: 3.5592457264188737
epochs 26/65
Current Learning Rate: 0.0006680716275190299
train_loss: 0.7465498031754243, val_loss: 3.6176710986586476
epochs 27/65

[I 2024-01-28 14:57:36,811] Trial 3 pruned.

Starting fold 1:
epochs 1/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6092504849608655, val_loss: 1.5619898687594782
epochs 2/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6079424238953914, val_loss: 1.5621264422381367
epochs 3/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6080724350444933, val_loss: 1.5623091478196403
epochs 4/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6082483654871036, val_loss: 1.5625203759581954
epochs 5/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6145994582101313, val_loss: 1.5627546840243869
epochs 6/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6105979450086025, val_loss: 1.5630019001229098
epochs 7/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6072885241183934, val_loss: 1.5632375573355055
epochs 8/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6048647720776303, val_loss: 1.5634642896198092
epochs 9/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.609341158916813, val_loss: 1.5636689921535512
epochs 10/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6071727787636962, val_loss: 1.5638687175417703
epochs 11/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.5987605911274856, val_loss: 1.5640640567850184
epochs 12/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6149648041001166, val_loss: 1.5642691434375824
epochs 13/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6079330569162418, val_loss: 1.5644821149331551
epochs 14/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6110455896217786, val_loss: 1.5646973116687997
epochs 15/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6112953087422237, val_loss: 1.5649168434597196
epochs 16/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6032514129009547, val_loss: 1.5651271311694352
epochs 17/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.5967991863869873, val_loss: 1.5653412348378903
epochs 18/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.5982453835572248, val_loss: 1.565545955663005
epochs 19/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6061896073256487, val_loss: 1.5657624630700975
epochs 20/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.605344956457927, val_loss: 1.5659787143979753
epochs 21/108
Current Learning Rate: 0.00012682203911633128
train_loss: 1.6104947359774124, val_loss: 1.566215127864212
epochs 22/108
Epoch 00022: reducing learning rate of group 0 to 2.6451e-05.
Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.6125483256984132, val_loss: 1.5664512953430256
epochs 23/108
Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.607314561674108, val_loss: 1.5664990528550728
epochs 24/108
Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.6087396775240674, val_loss: 1.5665453918396481
epochs 25/108
Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.5989491739822308, val_loss: 1.5665881211164767
epochs 26/108
Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.6046621013062163, val_loss: 1.5666337751206898
epochs 27/108
Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.6021779095315185, val_loss: 1.566679978496814
epochs 28/108
Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.6010035744512268, val_loss: 1.5667256003334409
epochs 29/108
Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.6041402311225212, val_loss: 1.5667685364919997
epochs 30/108

[I 2024-01-28 14:57:38,458] Trial 4 pruned.

Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.610162678813435, val_loss: 1.5668139117104667
epochs 31/108
Current Learning Rate: 2.6450674362961037e-05
train_loss: 1.603472762082884, val_loss: 1.5668597221374512
epochs 32/108
Starting fold 1:
epochs 1/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6169041133051767, val_loss: 1.5881325050636574
epochs 2/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6215264073217102, val_loss: 1.587224559809165
epochs 3/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6310047142168613, val_loss: 1.5863652431144917
epochs 4/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.628588296980134, val_loss: 1.5855188868033192
epochs 5/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.626495038651671, val_loss: 1.5847029288609822
epochs 6/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.617870983028911, val_loss: 1.5838394833620264
epochs 7/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.620005791099908, val_loss: 1.582952475421643
epochs 8/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.622151401654588, val_loss: 1.582090107852189
epochs 9/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6153817108164283, val_loss: 1.5812467866473727
epochs 10/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6157904988184024, val_loss: 1.5803877682912917
epochs 11/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6170927922763125, val_loss: 1.5795189356677746
epochs 12/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6180864716075478, val_loss: 1.5786435875312361
epochs 13/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6183335924647866, val_loss: 1.5777679725929543
epochs 14/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6221631883950758, val_loss: 1.576952922281134
epochs 15/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6233668776706875, val_loss: 1.5761373686412024
epochs 16/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6180208503263782, val_loss: 1.5753228519328688
epochs 17/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.622433500140125, val_loss: 1.5744914138127888
epochs 18/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6256091962934165, val_loss: 1.5737096071243286
epochs 19/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6159232218228086, val_loss: 1.5728858072290977
epochs 20/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6183461780947541, val_loss: 1.572006136652023
epochs 21/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6248014697229676, val_loss: 1.5711458801592468
epochs 22/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6197612647610808, val_loss: 1.5702675480060477
epochs 23/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6159455276908674, val_loss: 1.5693566326111081
epochs 24/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6193793681279527, val_loss: 1.5683871097665616
epochs 25/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6160817670572492, val_loss: 1.5674008679768396
epochs 26/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.621931243941422, val_loss: 1.5664458558672951
epochs 27/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6219701604693348, val_loss: 1.5655078774406797
epochs 28/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6153118004973646, val_loss: 1.56458418331449
epochs 29/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6260874864318609, val_loss: 1.5637194895870472
epochs 30/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6011540034678593, val_loss: 1.5628558851423717
epochs 31/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6104303617127902, val_loss: 1.5619052560241133
epochs 32/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6110961256226943, val_loss: 1.560862419466493
epochs 33/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6311265848069916, val_loss: 1.5598215085488778
epochs 34/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6287446340341218, val_loss: 1.5588124113738853
epochs 35/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6096534910002305, val_loss: 1.557706118891479
epochs 36/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.619841305997359, val_loss: 1.556603672643187
epochs 37/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.613825299977008, val_loss: 1.5555702523579673
epochs 38/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.618821461163266, val_loss: 1.5545502289262398
epochs 39/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6229944628570716, val_loss: 1.553523925246385
epochs 40/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6255444775077061, val_loss: 1.552528254569523
epochs 41/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6136974058850273, val_loss: 1.5514376655457511
epochs 42/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6092096854254838, val_loss: 1.5502875545037487
epochs 43/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.593477041933549, val_loss: 1.549084640684582
epochs 44/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.60442833001701, val_loss: 1.5477865827146662
epochs 45/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6059787485612, val_loss: 1.5465972890298834
epochs 46/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.614668580249966, val_loss: 1.54540746048014
epochs 47/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6066031537130865, val_loss: 1.5442496052494756
epochs 48/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6166296005249023, val_loss: 1.5430737904139928
epochs 49/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6152345847084884, val_loss: 1.5418298446312153
epochs 50/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6149650887044937, val_loss: 1.5405347908615434
epochs 51/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6058169628313075, val_loss: 1.5391929893897325
epochs 52/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6170145360587156, val_loss: 1.537885895481816
epochs 53/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6039080569881419, val_loss: 1.5366583614753038
epochs 54/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6132935759908866, val_loss: 1.5354654145619226
epochs 55/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6050307962906922, val_loss: 1.5341383988264377
epochs 56/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6005159610229014, val_loss: 1.5328086601994024
epochs 57/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6039330815769615, val_loss: 1.5315277166467496
epochs 58/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6142944528170282, val_loss: 1.530230302659292
epochs 59/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5977528332415676, val_loss: 1.5288919677179327
epochs 60/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6108678504434555, val_loss: 1.5274766002382552
epochs 61/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.631267948924559, val_loss: 1.5260918443165128
epochs 62/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6241785418924861, val_loss: 1.5247797959696048
epochs 63/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6147159824820714, val_loss: 1.5233322287362718
epochs 64/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6427077897556166, val_loss: 1.5220443987972523
epochs 65/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6144643678715092, val_loss: 1.5207165448123185
epochs 66/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6224924407080206, val_loss: 1.519364353840944
epochs 67/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6201782669696507, val_loss: 1.518008654710477
epochs 68/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6144916043855757, val_loss: 1.5167166656917996
epochs 69/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6149867292474078, val_loss: 1.515315815885231
epochs 70/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6253848163245237, val_loss: 1.5140382442524825
epochs 71/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6358900894045205, val_loss: 1.5128816807711567
epochs 72/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.597268135759843, val_loss: 1.5115730932780675
epochs 73/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.613081721111118, val_loss: 1.5101812655332858
epochs 74/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6263245050819757, val_loss: 1.50886185459359
epochs 75/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6288013907627286, val_loss: 1.5075371259104007
epochs 76/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6143055136915276, val_loss: 1.5062021117992501
epochs 77/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5910913469903756, val_loss: 1.5047377083036635
epochs 78/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5976818974729607, val_loss: 1.5032453372995689
epochs 79/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6103273399213223, val_loss: 1.5017951726913452
epochs 80/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.62238219645635, val_loss: 1.5003416298558472
epochs 81/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6285508658873473, val_loss: 1.498904306421835
epochs 82/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6062486608615096, val_loss: 1.4974389334835072
epochs 83/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6216706805204222, val_loss: 1.4964399362998033
epochs 84/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.623798384092241, val_loss: 1.4952801869659829
epochs 85/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.619121304357239, val_loss: 1.494105648111414
epochs 86/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6315308890417608, val_loss: 1.4929630636538147
epochs 87/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6104756094398298, val_loss: 1.4918233086823156
epochs 88/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6086770580077046, val_loss: 1.490662722991257
epochs 89/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6256232324070956, val_loss: 1.4894267951369917
epochs 90/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.62154004149412, val_loss: 1.4883811587379092
epochs 91/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.626180083339751, val_loss: 1.487146436222016
epochs 92/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6307171901483186, val_loss: 1.4856955330207866
epochs 93/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6349739572764692, val_loss: 1.4844898553121657
epochs 94/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5995507199726804, val_loss: 1.4835958058241183
epochs 95/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6227970310530737, val_loss: 1.4827878683332414
epochs 96/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.616025284946901, val_loss: 1.481506799263929
epochs 97/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5937324724896416, val_loss: 1.4799938214519037
epochs 98/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5994733831021175, val_loss: 1.4785407768986212
epochs 99/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.573466306269481, val_loss: 1.4776322791185328
epochs 100/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.573856912358269, val_loss: 1.4765988329730968
epochs 101/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.616802038946701, val_loss: 1.4754243445774866
epochs 102/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5917644407112561, val_loss: 1.4740082113831132
epochs 103/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6052221309452157, val_loss: 1.4724992264515508
Starting fold 2:
epochs 1/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5238223163705122, val_loss: 1.6088590382268189
epochs 2/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5575981497764588, val_loss: 1.6113370108225988
epochs 3/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5263004516300402, val_loss: 1.613492073205413
epochs 4/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5509763887054042, val_loss: 1.614096099106723
epochs 5/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5385874892535962, val_loss: 1.6141814239441403
epochs 6/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5395116473499098, val_loss: 1.6144827812437028
epochs 7/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5180487990379334, val_loss: 1.6152422137992093
epochs 8/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5379519111231754, val_loss: 1.6159428868974959
epochs 9/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5436216448482714, val_loss: 1.6164963497686637
epochs 10/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5202759071400291, val_loss: 1.6172008829772788
epochs 11/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5291327112599422, val_loss: 1.6177930062410062
epochs 12/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5354193066295825, val_loss: 1.618051705537019
epochs 13/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5308007171279505, val_loss: 1.6181881825129192
epochs 14/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.494468493210642, val_loss: 1.618901529640117
epochs 15/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5269795122899508, val_loss: 1.6195983394743905
epochs 16/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5188675328304893, val_loss: 1.6206132551980397
epochs 17/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.499646422737523, val_loss: 1.6216356552467144
epochs 18/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4939864026872736, val_loss: 1.6222082654004375
epochs 19/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5093944731511568, val_loss: 1.6221018556564573
epochs 20/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5026726942313344, val_loss: 1.622246265411377
epochs 21/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5101424512110257, val_loss: 1.62332319141065
epochs 22/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.497655499608893, val_loss: 1.6246715178565374
epochs 23/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4802246815279911, val_loss: 1.6262158338355008
epochs 24/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.491617997069108, val_loss: 1.6268457514899117
epochs 25/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4881740306553088, val_loss: 1.6275710706357602
epochs 26/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4566699159772774, val_loss: 1.628048371385645
epochs 27/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5154646076654132, val_loss: 1.6305161563176958
epochs 28/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4753587496908087, val_loss: 1.632507808624752
epochs 29/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4773339867591857, val_loss: 1.6332481941848835
epochs 30/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.465403091280084, val_loss: 1.6342827251979284
epochs 31/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4686585545539856, val_loss: 1.636114407468725
epochs 32/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4620521501490944, val_loss: 1.6374079436852187
epochs 33/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4438540314373216, val_loss: 1.638643944704974
epochs 34/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4500670257367585, val_loss: 1.6400666880229162
epochs 35/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4677670830174496, val_loss: 1.6417220320020403
epochs 36/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.450921060537037, val_loss: 1.643247952536931
epochs 37/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4242175811215452, val_loss: 1.644748809476378
epochs 38/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4406651540806419, val_loss: 1.6463126871320937
epochs 39/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4299829859482616, val_loss: 1.6485885753833427
epochs 40/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4403308372748524, val_loss: 1.650752864186726
epochs 41/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4176538517600612, val_loss: 1.652536842558119
epochs 42/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.412823987007141, val_loss: 1.65433402856191
epochs 43/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4243998489881817, val_loss: 1.6550301868448813
epochs 44/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4193217842202437, val_loss: 1.6606496988780914
epochs 45/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3955629511883385, val_loss: 1.6609064555042004
epochs 46/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.367949252379568, val_loss: 1.6632709869001276
epochs 47/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3884848732697337, val_loss: 1.6668978355549
epochs 48/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3887094579244914, val_loss: 1.669507866814023
epochs 49/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3781273164247212, val_loss: 1.6683860670321833
epochs 50/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.379964848568565, val_loss: 1.6753247831233595
epochs 51/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3651190695009734, val_loss: 1.6739983489273718
epochs 52/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3844383064069246, val_loss: 1.6775950761068434
epochs 53/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3759263226860448, val_loss: 1.6788468745650438
epochs 54/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3660518740352832, val_loss: 1.6892102225116952
epochs 55/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3229281005106475, val_loss: 1.6798063995976928
epochs 56/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3448064258224086, val_loss: 1.6925268457049416
epochs 57/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3310855645882456, val_loss: 1.6870234126136416
epochs 58/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3400907089835719, val_loss: 1.6972969852427326
epochs 59/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3280773771436591, val_loss: 1.6920821937934432
epochs 60/103
Epoch 00060: reducing learning rate of group 0 to 9.7092e-05.
Current Learning Rate: 9.709171868865868e-05
train_loss: 1.3018527495233636, val_loss: 1.700986177832992
epochs 61/103

[I 2024-01-28 14:58:22,315] Trial 5 finished with value: 1.4652380997511103 and parameters: {'batch_size': 62, 'epochs': 103, 'hidden_size': 20, 'learning_rate': 0.00013635815806655385, 'dropout_prob': 0.16281589392460533, 'weight_decay': 3.898854912850674e-06, 'lr_step_size': 58, 'gamma': 0.7120345424530452, 'conv_channels': 123, 'kernel_size': 2, 'num_layers': 2, 'pool_size': 2, 'stride': 2}. Best is trial 5 with value: 1.4652380997511103.

Current Learning Rate: 0.00013635815806655385
train_loss: 0.8837784710000913, val_loss: 1.3347575494221278
epochs 103/103
Current Learning Rate: 0.00013635815806655385
train_loss: 0.88068639439036, val_loss: 1.3620764578461015
Mean validation loss: 1.4652380997511103
Starting fold 1:
epochs 1/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6654394652830993, val_loss: 1.5184225007970498
epochs 2/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6050751677358337, val_loss: 1.4639167716263464
epochs 3/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6270341317691104, val_loss: 1.4063110029886638
epochs 4/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6334767098202132, val_loss: 1.3745247087781391
epochs 5/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6583119452935864, val_loss: 1.3530412921829829
epochs 6/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6622859879313963, val_loss: 1.3494242007139499
epochs 7/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6290576704509596, val_loss: 1.351352261487769
epochs 8/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6732264825810936, val_loss: 1.3584498018814772
epochs 9/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6685633877809134, val_loss: 1.3781387042746973
epochs 10/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6462619373311547, val_loss: 1.4048176171287658
epochs 11/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6213204773308718, val_loss: 1.4111850419372478
epochs 12/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.5902326568883127, val_loss: 1.4035960120498818
epochs 13/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.5255145308859062, val_loss: 1.7729420838532624
epochs 14/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.7291003228482151, val_loss: 1.5259200359778429
epochs 15/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6415569701119868, val_loss: 1.4302630342503704
epochs 16/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.631675302358198, val_loss: 1.3799516195973391
epochs 17/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.628917555846469, val_loss: 1.3595562615091838
epochs 18/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6720857258242463, val_loss: 1.3502545019306202
epochs 19/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6862283520673582, val_loss: 1.3523271358202373
epochs 20/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6625041200228388, val_loss: 1.357612653384133
epochs 21/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6582172850039616, val_loss: 1.3634172022027313
epochs 22/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6865556539665343, val_loss: 1.371119067467079
epochs 23/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6588347451225, val_loss: 1.3765220165883423
epochs 24/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6674114871399566, val_loss: 1.3790744807985094
epochs 25/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6580717064323225, val_loss: 1.3795673575981584
epochs 26/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.631758265470335, val_loss: 1.3769307098691426
epochs 27/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6384492288709311, val_loss: 1.3736505363353346
epochs 28/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6624800846838825, val_loss: 1.3726219364574976
epochs 29/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6547130446159404, val_loss: 1.371642980310652
epochs 30/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6641893979766607, val_loss: 1.372420138152188
epochs 31/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6631465338911686, val_loss: 1.3743200623799885
epochs 32/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6158696353747584, val_loss: 1.374121626848897
epochs 33/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6546482035002783, val_loss: 1.3713157057131409
epochs 34/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6476134829496214, val_loss: 1.36888014261054
epochs 35/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6287682047065015, val_loss: 1.3635693094717762
epochs 36/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.65251417060173, val_loss: 1.3583804769490762
epochs 37/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6878344706839916, val_loss: 1.3530609837915533
epochs 38/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6807925008354387, val_loss: 1.3532898413441168
epochs 39/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6780660015126174, val_loss: 1.3583341871619856
epochs 40/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6569043466558007, val_loss: 1.364028812716247
epochs 41/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.615205265464583, val_loss: 1.3649698341334309
epochs 42/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6670950251724084, val_loss: 1.3644675363308538
epochs 43/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6233958074559716, val_loss: 1.3647741025717801
epochs 44/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6424376324833376, val_loss: 1.3648599137074102
epochs 45/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6374518094262527, val_loss: 1.3635566373350758
epochs 46/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6523790562340102, val_loss: 1.3627128790295313
epochs 47/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6572860622905312, val_loss: 1.3628426219420458
epochs 48/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6474174510746102, val_loss: 1.3630455454821309
epochs 49/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6376431749753302, val_loss: 1.365244814958522
epochs 50/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.663969928057406, val_loss: 1.366591180443133
epochs 51/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6525187982314544, val_loss: 1.3677372982893041
epochs 52/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6376373658629613, val_loss: 1.3674782681717443
epochs 53/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.6101377946544069, val_loss: 1.361823511817468
epochs 54/135
Epoch 00054: reducing learning rate of group 0 to 6.6049e-03.
Current Learning Rate: 0.006604919234245127
train_loss: 1.6658098841212807, val_loss: 1.3556369814292464
epochs 55/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6669378708170346, val_loss: 1.3545794058098364
epochs 56/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6594602334561772, val_loss: 1.3527169848876024
epochs 57/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6545068006865018, val_loss: 1.3516349130206637
epochs 58/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6472339664454236, val_loss: 1.3492339899931005
epochs 59/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.63758517996803, val_loss: 1.3469865435645694
epochs 60/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6687719931153102, val_loss: 1.3449788617078589
epochs 61/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6236985850084515, val_loss: 1.3444446413605302
epochs 62/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6783305088262908, val_loss: 1.3427354775408589
epochs 63/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.605250856639203, val_loss: 1.3423698348973794
epochs 64/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6633612507300852, val_loss: 1.343033543339482
epochs 65/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6051345873253509, val_loss: 1.3430861067519617
epochs 66/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.674236077912815, val_loss: 1.3414461322562405
epochs 67/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6607982787786353, val_loss: 1.3404781023661296
epochs 68/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6613840482621918, val_loss: 1.3410245079212089
epochs 69/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6658453750984832, val_loss: 1.343698605027779
epochs 70/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5877017107309472, val_loss: 1.343954709471849
epochs 71/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.657895700469691, val_loss: 1.3440419977934903
epochs 72/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6624845962249797, val_loss: 1.3458375445118658
epochs 73/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6427161690452337, val_loss: 1.3478648643645028
epochs 74/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6701021178854698, val_loss: 1.3501098830863911
epochs 75/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6758729990240167, val_loss: 1.3528033088123987
epochs 76/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6635898292376734, val_loss: 1.3564578029844496
epochs 77/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6559460394045444, val_loss: 1.3601394970581013
epochs 78/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.635112207597463, val_loss: 1.3594213938586925
epochs 79/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6497102326747635, val_loss: 1.358356010661554
epochs 80/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6560616486983775, val_loss: 1.35773312982428
epochs 81/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6354693230534099, val_loss: 1.3563235001589256
epochs 82/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.62945302681149, val_loss: 1.3523010671454132
epochs 83/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6149606536196164, val_loss: 1.347292909546504
epochs 84/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6296033363067668, val_loss: 1.3488878784356293
epochs 85/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5841206711624305, val_loss: 1.3316800890776215
epochs 86/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5828156134220943, val_loss: 1.3163886275240984
epochs 87/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6390100811164416, val_loss: 1.30804382966309
epochs 88/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6265298955103489, val_loss: 1.3233324838063074
epochs 89/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5999017560669264, val_loss: 1.3040865785861142
epochs 90/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6331182961688615, val_loss: 1.2897331966924919
epochs 91/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.599395406183772, val_loss: 1.2827468438754006
epochs 92/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5755029620300414, val_loss: 1.2718798833549338
epochs 93/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5556266744723495, val_loss: 1.2563885992796964
epochs 94/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.521924733179402, val_loss: 1.2326101641806344
epochs 95/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5530119972079213, val_loss: 1.2217226529878282
epochs 96/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5048538493236323, val_loss: 1.2171228859159682
epochs 97/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.451635702742332, val_loss: 1.214809624921708
epochs 98/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.4097522266248135, val_loss: 1.2155698131001185
epochs 99/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.3828022320857223, val_loss: 1.2163422833044062
epochs 100/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.3270833523485672, val_loss: 1.2191923396297233
epochs 101/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.2662303020192691, val_loss: 1.2195881173093484
epochs 102/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.378179667819857, val_loss: 1.1958947370922755
epochs 103/135
Current Learning Rate: 0.006604919234245127
train_loss: 2.090997889715964, val_loss: 1.2372533546553717
epochs 104/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.976725934063577, val_loss: 1.2786135534760814
epochs 105/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.8585454949533753, val_loss: 1.3146733966453996
epochs 106/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.7244950189640385, val_loss: 1.3167087785781375
epochs 107/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.7644488833337555, val_loss: 1.3100613040268105
epochs 108/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6209701499389728, val_loss: 1.3147353955677576
epochs 109/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6688209372665246, val_loss: 1.3281341097342274
epochs 110/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6993167013398016, val_loss: 1.3535329494526778
epochs 111/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6410097264494572, val_loss: 1.374050086137479
epochs 112/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.761073822750471, val_loss: 1.3745231183748396
epochs 113/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6031395805443769, val_loss: 1.3616945816095545
epochs 114/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.596660537245386, val_loss: 1.3414924434883884
epochs 115/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5817538169041978, val_loss: 1.322377928034969
epochs 116/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6964451910937643, val_loss: 1.3233265577169953
epochs 117/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6467189826266304, val_loss: 1.3218981494348516
epochs 118/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5691172596047687, val_loss: 1.3192649619289176
epochs 119/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5402731948498032, val_loss: 1.3061683581619667
epochs 120/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.6238705572033427, val_loss: 1.2904175989842288
epochs 121/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.4578893527934689, val_loss: 1.2495308218809662
epochs 122/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5022124039565081, val_loss: 1.2170249879675568
epochs 123/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.463390811887711, val_loss: 1.212310929147024
epochs 124/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.4351011655093489, val_loss: 1.2426116592669614
epochs 125/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5015864518924533, val_loss: 1.189431555056698
epochs 126/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.5533831650049899, val_loss: 1.1972937959211845
epochs 127/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.3552509408970779, val_loss: 1.252160633051837
epochs 128/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.557461333212428, val_loss: 1.2664238157726468
epochs 129/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.321583056949196, val_loss: 1.2575530564343487
epochs 130/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.3466113116104566, val_loss: 1.231166090914812
epochs 131/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.2504405154607683, val_loss: 1.5095900738680805
epochs 132/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.443730787769038, val_loss: 1.2127891690642745
epochs 133/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.1999312013543713, val_loss: 1.1853780563546237
epochs 134/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.1540171378414044, val_loss: 1.216723225734852
epochs 135/135
Current Learning Rate: 0.006604919234245127
train_loss: 1.1283200599292187, val_loss: 1.2623426220404408
Starting fold 2:
epochs 1/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.164819482125734, val_loss: 2.027273082543933
epochs 2/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.247412079258969, val_loss: 1.9657267073474864
epochs 3/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.1902962162306434, val_loss: 1.930082640950642
epochs 4/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.0945271471613331, val_loss: 1.9565631740938418
epochs 5/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.133736719426356, val_loss: 1.7920402862407543
epochs 6/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.1042345186597422, val_loss: 1.8106044787893851
epochs 7/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.0912878361187484, val_loss: 1.8757435953806316
epochs 8/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.0240152418613433, val_loss: 1.9139095106452861
epochs 9/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.0176222747878025, val_loss: 2.0348882419722423
epochs 10/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.0618172702036406, val_loss: 2.038625834164796
epochs 11/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.011626802620135, val_loss: 2.2802194054164584
epochs 12/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.1282911049692255, val_loss: 1.999770097631626
epochs 13/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.1046747963679464, val_loss: 2.3004094236111516
epochs 14/135
Current Learning Rate: 0.011030893399748741
train_loss: 0.9572590587954772, val_loss: 2.344877179337557
epochs 15/135
Current Learning Rate: 0.011030893399748741
train_loss: 0.9260517570533251, val_loss: 2.3612706459388533
epochs 16/135
Current Learning Rate: 0.011030893399748741
train_loss: 0.9981462913124185, val_loss: 2.3050395770678445
epochs 17/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.254545250378157, val_loss: 2.4333168022216314
epochs 18/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.2361828425997181, val_loss: 2.13754497003303
epochs 19/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.063516997506744, val_loss: 2.3260932864335477
epochs 20/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.0166018664836884, val_loss: 2.0772291857098777
epochs 21/135
Current Learning Rate: 0.011030893399748741
train_loss: 0.9611081634697162, val_loss: 2.235520498462455
epochs 22/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.0132963086429396, val_loss: 2.2385570542522206
epochs 23/135
Current Learning Rate: 0.011030893399748741
train_loss: 0.9425253905748067, val_loss: 2.5168178642868364
epochs 24/135
Current Learning Rate: 0.011030893399748741
train_loss: 0.8417625442147255, val_loss: 2.6029450262665117
epochs 25/135
Current Learning Rate: 0.011030893399748741
train_loss: 0.8588109833629508, val_loss: 2.6459480227616727
epochs 26/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.0798034379356787, val_loss: 2.298521025155587
epochs 27/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.2424726258767278, val_loss: 3.1807804801476696
epochs 28/135
Current Learning Rate: 0.011030893399748741
train_loss: 1.1309106657379553, val_loss: 2.8334402596509016
epochs 29/135
Current Learning Rate: 0.011030893399748741
train_loss: 0.9708834323443865, val_loss: 2.070223961873029
epochs 30/135
Current Learning Rate: 0.011030893399748741
train_loss: 0.976941370336633, val_loss: 2.602838645536433
epochs 31/135
Current Learning Rate: 0.011030893399748741

[I 2024-01-28 14:58:39,146] Trial 6 pruned.

Starting fold 1:
epochs 1/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6196057103691301, val_loss: 1.6223405019316093
epochs 2/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6180343353311428, val_loss: 1.622333283146853
epochs 3/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6195264798808473, val_loss: 1.6223314041813846
epochs 4/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6173251698778561, val_loss: 1.6223301546914237
epochs 5/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6217544085068227, val_loss: 1.6223300253903423
epochs 6/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6207234322712682, val_loss: 1.6223295788285594
epochs 7/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6191125278073455, val_loss: 1.6223301174779419
epochs 8/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6163683468134615, val_loss: 1.6223299566400113
epochs 9/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6180054848106744, val_loss: 1.6223297800336565
epochs 10/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6184543489785719, val_loss: 1.6223293290567147
epochs 11/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6216390663416598, val_loss: 1.6223295460302363
epochs 12/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.621948077416545, val_loss: 1.6223295763056114
epochs 13/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6210437426392321, val_loss: 1.6223296450559423
epochs 14/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6155487735858138, val_loss: 1.622329351763246
epochs 15/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6193929717178743, val_loss: 1.622329488002434
epochs 16/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6170039027149141, val_loss: 1.6223293902382019
epochs 17/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6164837626262485, val_loss: 1.6223294678188505
epochs 18/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6207122603012005, val_loss: 1.6223299995301261
epochs 19/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6149123064510484, val_loss: 1.6223307179395483
epochs 20/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6197410416228608, val_loss: 1.6223311594554357
epochs 21/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6184856098983924, val_loss: 1.6223322083710363
epochs 22/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6179418351637755, val_loss: 1.6223332099813632
epochs 23/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6209771046463732, val_loss: 1.6223342387133806
epochs 24/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6157491849979182, val_loss: 1.6223351482361081
epochs 25/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.618332861605739, val_loss: 1.6223364109715457
epochs 26/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6172108350623964, val_loss: 1.6223375343141102
epochs 27/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.618421510252029, val_loss: 1.6223380187201122
epochs 28/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6205355328415076, val_loss: 1.6223387932651256
epochs 29/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6219804299439435, val_loss: 1.6223395362732902
epochs 30/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.6221546608740123, val_loss: 1.6223411049161638
epochs 31/114
Current Learning Rate: 1.6830262582075883e-06
train_loss: 1.623566756073717, val_loss: 1.6223424509088828
epochs 32/114

[I 2024-01-28 14:58:41,089] Trial 7 pruned.

Starting fold 1:
epochs 1/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.7367405579352253, val_loss: 1.469956601738299
epochs 2/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.5735422247991513, val_loss: 1.480944627176517
epochs 3/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.5312318801879883, val_loss: 1.4615492574752322
epochs 4/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.5545742898711359, val_loss: 1.4318907532111678
epochs 5/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.5226680452286885, val_loss: 1.4210979433917494
epochs 6/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.5085734054056137, val_loss: 1.3896265730025277
epochs 7/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.4807315172325255, val_loss: 1.3487452470436299
epochs 8/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.439502228617044, val_loss: 1.311568990586296
epochs 9/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.3856306394357332, val_loss: 1.2559597526908552
epochs 10/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.3344349711353243, val_loss: 1.297995095530515
epochs 11/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.2955963586637487, val_loss: 1.1981484101562905
epochs 12/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.2392554489105785, val_loss: 1.2243134754675407
epochs 13/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.111649021428293, val_loss: 1.1299684527059082
epochs 14/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.1391279560109084, val_loss: 1.9778404197995625
epochs 15/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.2571873458892262, val_loss: 1.1216180100642814
epochs 16/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.405407537964626, val_loss: 1.1344276177820074
epochs 17/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.2950337282650133, val_loss: 2.209004655716911
epochs 18/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.2972641571654075, val_loss: 1.1579295661714342
epochs 19/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.2928520316228818, val_loss: 1.0898451817729486
epochs 20/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.1916491298775398, val_loss: 1.1734965648600664
epochs 21/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.15236098479226, val_loss: 1.415808079734681
epochs 22/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.0651716075018438, val_loss: 1.233975546700614
epochs 23/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.0455072787419664, val_loss: 1.1904240215896928
epochs 24/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.0060695665669066, val_loss: 1.2996513010963562
epochs 25/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.0084586493007799, val_loss: 1.2978479691914149
epochs 26/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.9377478323681816, val_loss: 1.2017668290113015
epochs 27/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.8875707431613463, val_loss: 1.3179807864799702
epochs 28/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.83256917598984, val_loss: 1.1016011635462444
epochs 29/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.840253506031336, val_loss: 1.8689548868350883
epochs 30/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.0073355941872322, val_loss: 1.0971775796047594
epochs 31/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.4174273656924983, val_loss: 1.3864644601862266
epochs 32/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.0503824212788286, val_loss: 1.1049043567723067
epochs 33/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.9563343322089829, val_loss: 1.3211173708476718
epochs 34/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.8706396212752577, val_loss: 1.465812708965685
epochs 35/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.9127093831282012, val_loss: 1.5428566629924472
epochs 36/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.8684102399811071, val_loss: 1.2186312577711842
epochs 37/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.8216314169124783, val_loss: 1.2831914355515173
epochs 38/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.7757936382168875, val_loss: 1.8453061158064181
epochs 39/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.9037589571238812, val_loss: 0.9911633900233677
epochs 40/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.7798967186693122, val_loss: 1.482628791420548
epochs 41/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.7067147043987094, val_loss: 1.5672706409736916
epochs 42/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.7304109765597039, val_loss: 1.0114392959882343
epochs 43/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6710654543956537, val_loss: 1.4823327651099554
epochs 44/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6712428811957075, val_loss: 1.4478300904470778
epochs 45/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6126771862594245, val_loss: 1.402984207900113
epochs 46/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5524747131382608, val_loss: 1.9576655254162179
epochs 47/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.604758774110784, val_loss: 1.402681709912719
epochs 48/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5784657775419545, val_loss: 1.6067196856100092
epochs 49/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5246093522815805, val_loss: 1.5618586376230552
epochs 50/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.7904569150889731, val_loss: 2.825583543727007
epochs 51/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.8631532828845279, val_loss: 0.8772407964108482
epochs 52/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.8569556424755076, val_loss: 1.6003564037973919
epochs 53/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6846891853821839, val_loss: 1.9445790197483446
epochs 54/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.9400539111092453, val_loss: 1.4383609938243078
epochs 55/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.9654355504749957, val_loss: 1.6721016830868192
epochs 56/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.79531326499909, val_loss: 1.2536977895353205
epochs 57/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6453632028939212, val_loss: 1.706054240938217
epochs 58/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5762504223753645, val_loss: 1.6263127156666346
epochs 59/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6454186345894299, val_loss: 1.4888870492183341
epochs 60/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6283890533197612, val_loss: 1.6780455200760453
epochs 61/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5647061317378937, val_loss: 1.536735002325956
epochs 62/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5338485499951228, val_loss: 2.069430225740665
epochs 63/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5723424753593525, val_loss: 1.5087539556795957
epochs 64/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.546488487595663, val_loss: 1.578127319219882
epochs 65/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5171650922735324, val_loss: 1.7822151133623072
epochs 66/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5201037519889352, val_loss: 1.55517832028172
epochs 67/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.46285642582084496, val_loss: 1.5468295112488761
epochs 68/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.434537515278262, val_loss: 1.7489860196592946
epochs 69/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.48544549068231235, val_loss: 1.8628595121323117
epochs 70/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.4971826703760636, val_loss: 1.759144658134097
epochs 71/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6178639125449495, val_loss: 2.6811580027222
epochs 72/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6876775556833956, val_loss: 1.2175122281861683
epochs 73/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.7536403639778417, val_loss: 1.2952257088883212
epochs 74/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5448795048354184, val_loss: 2.383874943016698
epochs 75/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5475609442950543, val_loss: 1.7370155841585189
epochs 76/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.43858223170510136, val_loss: 1.5057018121714314
epochs 77/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.437122613815737, val_loss: 1.5888147114445923
epochs 78/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.4149210646514493, val_loss: 1.710594601416714
epochs 79/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.41901978787951444, val_loss: 1.7027655196568323
epochs 80/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.3724796709589933, val_loss: 1.675618705295381
epochs 81/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.4039448392016725, val_loss: 2.038924226054439
epochs 82/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.4067223064250347, val_loss: 1.8818657120699605
epochs 83/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.3764676799636861, val_loss: 1.6737379223581343
epochs 84/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.42595138225255835, val_loss: 1.7799676325586107
epochs 85/119
Current Learning Rate: 0.012459987417802734
train_loss: 1.1032178180380017, val_loss: 2.0241035834822076
epochs 86/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.6560430957384759, val_loss: 2.05505062852587
epochs 87/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5467443946768477, val_loss: 1.4991062029644295
epochs 88/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5270409615252031, val_loss: 1.4964213049600994
epochs 89/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.5222490963511442, val_loss: 1.788435747699132
epochs 90/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.4773880052941008, val_loss: 1.8821127111949618
epochs 91/119
Current Learning Rate: 0.012459987417802734
train_loss: 0.41147237516822616, val_loss: 1.7578098982099504
epochs 92/119

[I 2024-01-28 14:58:46,036] Trial 8 pruned.

Starting fold 1:
epochs 1/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.6038609905392711, val_loss: 1.620925611919827
epochs 2/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.601982313925059, val_loss: 1.6203349469200012
epochs 3/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.603647654593303, val_loss: 1.6200749016312694
epochs 4/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.6023533281855558, val_loss: 1.6199806676339852
epochs 5/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.6053509849528367, val_loss: 1.620026460400334
epochs 6/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.6000668503227033, val_loss: 1.620122267455651
epochs 7/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5984209264136109, val_loss: 1.6202530942896687
epochs 8/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.602136724906442, val_loss: 1.620447763059505
epochs 9/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.6007020716891862, val_loss: 1.620677979534896
epochs 10/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5989673924071626, val_loss: 1.6209364441967515
epochs 11/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.599588458450677, val_loss: 1.6212162921037623
epochs 12/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.6007247620228073, val_loss: 1.6214857467267878
epochs 13/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5994526740768193, val_loss: 1.6218185954623752
epochs 14/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5957500266779157, val_loss: 1.622144589348445
epochs 15/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5957446092086314, val_loss: 1.6224789127470955
epochs 16/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.595992395391015, val_loss: 1.6228374463540536
epochs 17/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.601009812654625, val_loss: 1.623202229303027
epochs 18/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5924713624085431, val_loss: 1.6236034732647042
epochs 19/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5971349521457212, val_loss: 1.6239660902628823
epochs 20/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5968478125427406, val_loss: 1.6243145011720204
epochs 21/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5953069076488156, val_loss: 1.6246563372788605
epochs 22/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5928942576752907, val_loss: 1.6249438681930461
epochs 23/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5926867355226846, val_loss: 1.6252366998208263
epochs 24/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.593640117745125, val_loss: 1.6255737808015611
epochs 25/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5961755532868869, val_loss: 1.625875678642717
epochs 26/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.590193941955167, val_loss: 1.6261582898084448
epochs 27/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5901437741923707, val_loss: 1.6264569097095065
epochs 28/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5960803705984385, val_loss: 1.6268117162916396
epochs 29/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5913942546744622, val_loss: 1.6272228287641333
epochs 30/142

[I 2024-01-28 14:58:47,977] Trial 9 pruned.

Current Learning Rate: 0.0002759970876059121
train_loss: 1.595140588845258, val_loss: 1.6276840387828766
epochs 31/142
Current Learning Rate: 0.0002759970876059121
train_loss: 1.5890026672972435, val_loss: 1.6281566746020444
epochs 32/142
Starting fold 1:
epochs 1/91
Current Learning Rate: 0.0019715522383823695
train_loss: 1.6433594170665242, val_loss: 1.7144457234276667
epochs 2/91
Current Learning Rate: 0.0019715522383823695
train_loss: 1.636921114946535, val_loss: 1.7173720200856526
epochs 3/91
Current Learning Rate: 0.0019715522383823695
train_loss: 1.6261569848235364, val_loss: 1.7202918359211512
epochs 4/91
Current Learning Rate: 0.0019715522383823695
train_loss: 1.6221433303743134, val_loss: 1.7227509116369581
epochs 5/91
Current Learning Rate: 0.0019715522383823695
train_loss: 1.621339324881269, val_loss: 1.7249257242868816
epochs 6/91
Current Learning Rate: 0.0019715522383823695
train_loss: 1.6232879960724196, val_loss: 1.7270383134720817
epochs 7/91
Current Learning Rate: 0.0019715522383823695
train_loss: 1.6328305380506665, val_loss: 1.7289999401758587
epochs 8/91
Current Learning Rate: 0.0019715522383823695
train_loss: 1.6200002356973617, val_loss: 1.730702691608005
epochs 9/91
Current Learning Rate: 0.0019715522383823695
train_loss: 1.6144477422324774, val_loss: 1.7324053616750807
epochs 10/91
Epoch 00010: reducing learning rate of group 0 to 1.3859e-03.
Current Learning Rate: 0.001385932337607131
train_loss: 1.6179949494556607, val_loss: 1.734094634888664
epochs 11/91
Current Learning Rate: 0.001385932337607131
train_loss: 1.6205436197250926, val_loss: 1.7353393407095046
epochs 12/91
Current Learning Rate: 0.001385932337607131
train_loss: 1.626035876299074, val_loss: 1.7352363552365984
epochs 13/91
Current Learning Rate: 0.001385932337607131
train_loss: 1.6175823598632013, val_loss: 1.7356817722320557
epochs 14/91
Current Learning Rate: 0.001385932337607131
train_loss: 1.6163120388360548, val_loss: 1.7365422759737288
epochs 15/91
Current Learning Rate: 0.001385932337607131
train_loss: 1.6074909202715488, val_loss: 1.7370024030170743
epochs 16/91
Current Learning Rate: 0.001385932337607131
train_loss: 1.612147666396895, val_loss: 1.738108686038426
epochs 17/91
Current Learning Rate: 0.001385932337607131
train_loss: 1.6166729022071, val_loss: 1.7387776601882208
epochs 18/91
Current Learning Rate: 0.001385932337607131
train_loss: 1.6065189944511933, val_loss: 1.7392020452590216
epochs 19/91
Epoch 00019: reducing learning rate of group 0 to 9.7426e-04.
Current Learning Rate: 0.0009742620089037876
train_loss: 1.6118958395813148, val_loss: 1.7381019724739923
epochs 20/91
Current Learning Rate: 0.0009742620089037876
train_loss: 1.6024845214414347, val_loss: 1.7381425660754006
epochs 21/91
Current Learning Rate: 0.0009742620089037876
train_loss: 1.6152676512433597, val_loss: 1.739074979509626
epochs 22/91
Current Learning Rate: 0.0009742620089037876
train_loss: 1.6166016968132937, val_loss: 1.7375088759831019
epochs 23/91
Current Learning Rate: 0.0009742620089037876
train_loss: 1.6171807862077083, val_loss: 1.7367414690199352
epochs 24/91
Current Learning Rate: 0.0009742620089037876
train_loss: 1.6015242743866607, val_loss: 1.7364500533966791
epochs 25/91
Current Learning Rate: 0.0009742620089037876
train_loss: 1.5928026943306648, val_loss: 1.7343554875207325
epochs 26/91
Current Learning Rate: 0.0009742620089037876
train_loss: 1.5876477750808156, val_loss: 1.7318521775896587
epochs 27/91
Current Learning Rate: 0.0009742620089037876
train_loss: 1.5914584204788607, val_loss: 1.7292414317055353
epochs 28/91
Epoch 00028: reducing learning rate of group 0 to 6.8487e-04.
Current Learning Rate: 0.000684872151574191
train_loss: 1.5754781861579854, val_loss: 1.727234128921751
epochs 29/91
Current Learning Rate: 0.000684872151574191
train_loss: 1.5862099038368744, val_loss: 1.7248755731279888
epochs 30/91

[I 2024-01-28 14:58:49,702] Trial 10 pruned.

Current Learning Rate: 0.000684872151574191
train_loss: 1.5832469613140165, val_loss: 1.72268379491473
epochs 31/91
Current Learning Rate: 0.000684872151574191
train_loss: 1.5992489291735346, val_loss: 1.7251604398091633
epochs 32/91
Starting fold 1:
epochs 1/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.5989764079997677, val_loss: 1.5759032907940091
epochs 2/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.601675225802117, val_loss: 1.5758813619613647
epochs 3/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6001447838638465, val_loss: 1.575861164501735
epochs 4/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.601010074166103, val_loss: 1.5758424316133772
epochs 5/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6013718487704611, val_loss: 1.5758245899563743
epochs 6/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6006261615853035, val_loss: 1.5758062657855807
epochs 7/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6012790733607027, val_loss: 1.5757867381686257
epochs 8/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.600800509228132, val_loss: 1.5757675170898438
epochs 9/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.601971983909607, val_loss: 1.575747665904817
epochs 10/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6000259415641505, val_loss: 1.5757280077253069
epochs 11/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.602034352212676, val_loss: 1.5757080203010922
epochs 12/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.603031560388535, val_loss: 1.5756890660240537
epochs 13/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.600351753035141, val_loss: 1.5756697597957792
epochs 14/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.5996556544179068, val_loss: 1.5756505330403645
epochs 15/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6004902330368602, val_loss: 1.5756315390268962
epochs 16/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6011269953862535, val_loss: 1.5756120965594338
epochs 17/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6004180814583264, val_loss: 1.5755921318417503
epochs 18/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6025057862566403, val_loss: 1.5755725588117326
epochs 19/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.5998115308621792, val_loss: 1.5755530311947776
epochs 20/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.599030029711299, val_loss: 1.5755324477241153
epochs 21/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.601095948543848, val_loss: 1.5755122786476499
epochs 22/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6032792448373365, val_loss: 1.5754914737883068
epochs 23/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6000191460105138, val_loss: 1.5754704929533458
epochs 24/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6033705809977665, val_loss: 1.5754490409578596
epochs 25/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.5986567329985932, val_loss: 1.5754280601228987
epochs 26/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.6024388617870071, val_loss: 1.5754079194295973
epochs 27/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.5997719078163826, val_loss: 1.5753879320053827
epochs 28/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.600179100535927, val_loss: 1.5753675926299322
epochs 29/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.5997734325718505, val_loss: 1.5753474235534668
epochs 30/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.602132317907523, val_loss: 1.5753270047051566
epochs 31/61
Current Learning Rate: 1.3134589739494021e-06
train_loss: 1.5994412574468482, val_loss: 1.5753073181424821
epochs 32/61

[I 2024-01-28 14:58:51,712] Trial 11 pruned.

Starting fold 1:
epochs 1/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6226396498255704, val_loss: 1.5711875315065738
epochs 2/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6227685175641045, val_loss: 1.5711703659996155
epochs 3/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6225955505021579, val_loss: 1.5711680373186787
epochs 4/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6226432367145078, val_loss: 1.5711719106744837
epochs 5/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6224813904437718, val_loss: 1.5711783839281275
epochs 6/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6224658027369314, val_loss: 1.5711870325936212
epochs 7/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6224028908145365, val_loss: 1.5711968954278048
epochs 8/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.622346464876105, val_loss: 1.5712075145156295
epochs 9/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6221015103824477, val_loss: 1.5712186659454668
epochs 10/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6222417504375517, val_loss: 1.5712297990839317
epochs 11/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6221708864441717, val_loss: 1.5712412747125777
epochs 12/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6229487095827833, val_loss: 1.5712528361214533
epochs 13/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.622079415471142, val_loss: 1.571263932046436
epochs 14/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.622254978299765, val_loss: 1.571275031755841
epochs 15/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6221036580220567, val_loss: 1.5712866196556696
epochs 16/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.621868551713634, val_loss: 1.5712981438510631
epochs 17/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6221485431281684, val_loss: 1.5713093104185882
epochs 18/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6219518446797476, val_loss: 1.5713211840422696
epochs 19/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6220106292145415, val_loss: 1.5713332475177826
epochs 20/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6218511234403281, val_loss: 1.5713450019321744
epochs 21/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6218149805568276, val_loss: 1.5713567191330844
epochs 22/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6218879996794056, val_loss: 1.571368242697741
epochs 23/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.622164249420166, val_loss: 1.5713797031886994
epochs 24/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6218521538829305, val_loss: 1.5713915995189123
epochs 25/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6216365267468997, val_loss: 1.5714031420056782
epochs 26/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6214130605078492, val_loss: 1.5714147217059262
epochs 27/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6213758197754466, val_loss: 1.5714266552496208
epochs 28/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6214705761814616, val_loss: 1.5714389016388586
epochs 29/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6214605445012997, val_loss: 1.571451185241578
epochs 30/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6213238463975996, val_loss: 1.5714636517580225
epochs 31/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6213676966921822, val_loss: 1.5714762299149125
epochs 32/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6215191411722394, val_loss: 1.5714885734376454
epochs 33/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.621168213989098, val_loss: 1.5715009169603782
epochs 34/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6217871074277068, val_loss: 1.5715131709184595
epochs 35/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6211362658994983, val_loss: 1.5715254658744449
epochs 36/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6212519357341746, val_loss: 1.5715378428262377
epochs 37/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6212532607672727, val_loss: 1.5715504581966098
epochs 38/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6210166378171031, val_loss: 1.5715632224209095
epochs 39/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.620919886059786, val_loss: 1.5715761020700767
epochs 40/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6207144697299178, val_loss: 1.5715892087845575
epochs 41/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6207332860736947, val_loss: 1.5716023527125202
epochs 42/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6207706709806833, val_loss: 1.5716155073630116
epochs 43/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6207685414409139, val_loss: 1.5716291312818174
epochs 44/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6206947346632394, val_loss: 1.5716428889168634
epochs 45/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6208008789891348, val_loss: 1.5716566465519093
epochs 46/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.620751125650256, val_loss: 1.5716704414004372
epochs 47/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6208577711544736, val_loss: 1.5716847685909776
epochs 48/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.620059054559438, val_loss: 1.5716991739929038
epochs 49/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.620587609825334, val_loss: 1.5717130842662992
epochs 50/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6206397798048888, val_loss: 1.5717272550340682
epochs 51/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.619768383615304, val_loss: 1.5717405244786904
epochs 52/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.620379113402042, val_loss: 1.5717528478178397
epochs 53/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6205553852450785, val_loss: 1.5717667057400657
epochs 54/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.620359855796654, val_loss: 1.5717814429096444
epochs 55/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6203897529871676, val_loss: 1.5717972264718758
epochs 56/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6203175527263063, val_loss: 1.5718133493706032
epochs 57/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6201603880727478, val_loss: 1.5718302505987662
epochs 58/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.620207661109445, val_loss: 1.5718467645544223
epochs 59/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6201759295937903, val_loss: 1.5718633977193681
epochs 60/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6201217199495326, val_loss: 1.5718804667235682
epochs 61/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6201173528950876, val_loss: 1.5718976025858884
epochs 62/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6202475344323364, val_loss: 1.571915312418862
epochs 63/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6199401336190589, val_loss: 1.5719329661162442
epochs 64/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6197826338063983, val_loss: 1.571951565919099
epochs 65/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.615529005440118, val_loss: 1.5719675519479015
epochs 66/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.619857727545094, val_loss: 1.5719804511499154
epochs 67/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6198300691175211, val_loss: 1.5719947430191847
epochs 68/95
Current Learning Rate: 9.275238282342896e-06
train_loss: 1.6198515935718076, val_loss: 1.5720096189508994
epochs 69/95
Epoch 00069: reducing learning rate of group 0 to 7.0107e-06.
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.619710339925676, val_loss: 1.5720252769964713
epochs 70/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6197372119464175, val_loss: 1.5720372603683876
epochs 71/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6193902455075249, val_loss: 1.572049519372365
epochs 72/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6197433733815298, val_loss: 1.5720616705203183
epochs 73/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6195313150345967, val_loss: 1.572074056302429
epochs 74/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6195450553095154, val_loss: 1.5720865871540453
epochs 75/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6194002628326416, val_loss: 1.5720991703568312
epochs 76/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.619606749549586, val_loss: 1.572111794557521
epochs 77/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6195260317537796, val_loss: 1.5721243291935594
epochs 78/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6193700036453327, val_loss: 1.5721370164679471
epochs 79/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6194566288543621, val_loss: 1.5721497560935045
epochs 80/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6195081890565564, val_loss: 1.5721626817864716
epochs 81/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6193501025594341, val_loss: 1.572175175424606
epochs 82/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.619461746115959, val_loss: 1.5721878702678378
epochs 83/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.619354307963586, val_loss: 1.5722004162571417
epochs 84/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.619176213653924, val_loss: 1.572213300952205
epochs 85/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6192874658794303, val_loss: 1.5722263086409796
epochs 86/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6275840111427906, val_loss: 1.5722375111605125
epochs 87/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.619297816491252, val_loss: 1.5722463881527935
epochs 88/95

[I 2024-01-28 14:58:56,127] Trial 12 pruned.

Current Learning Rate: 7.010654015664084e-06
train_loss: 1.619231337028024, val_loss: 1.5722563443360504
epochs 89/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6189627347816347, val_loss: 1.5722673014988975
epochs 90/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6190840012115957, val_loss: 1.572279241349962
epochs 91/95
Current Learning Rate: 7.010654015664084e-06
train_loss: 1.6190967815708739, val_loss: 1.5722916315472315
epochs 92/95
Starting fold 1:
epochs 1/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.622257974135314, val_loss: 1.6073909051834592
epochs 2/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6218803652918152, val_loss: 1.6073763805722434
epochs 3/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6242647907496748, val_loss: 1.6073644255834914
epochs 4/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6236064128226635, val_loss: 1.6073522643437461
epochs 5/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6220858939655165, val_loss: 1.6073398192723591
epochs 6/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6260110083674886, val_loss: 1.6073277885951693
epochs 7/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6220784343349997, val_loss: 1.6073162480006142
epochs 8/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.619909133586584, val_loss: 1.6073064463479179
epochs 9/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.624136644508202, val_loss: 1.607294756268698
epochs 10/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.618770717326259, val_loss: 1.607282663148547
epochs 11/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6224859909237368, val_loss: 1.607272254096137
epochs 12/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6219585484859207, val_loss: 1.6072623691861592
epochs 13/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.620913056178867, val_loss: 1.607252520228189
epochs 14/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.62783257187349, val_loss: 1.6072398840434967
epochs 15/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6221833029342572, val_loss: 1.6072270113324363
epochs 16/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.623975542203294, val_loss: 1.607213222791278
epochs 17/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6196682528051407, val_loss: 1.6072008496239072
epochs 18/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.622274840065322, val_loss: 1.607189833171784
epochs 19/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6195692522987646, val_loss: 1.6071795565741402
epochs 20/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6215222961615519, val_loss: 1.6071695165028648
epochs 21/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6221943794120668, val_loss: 1.6071587119783675
epochs 22/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6270156886565124, val_loss: 1.6071470370368353
epochs 23/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6214231820630778, val_loss: 1.6071357935193986
epochs 24/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.621929577507898, val_loss: 1.607125059006706
epochs 25/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6223501578675514, val_loss: 1.607114309356326
epochs 26/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6213787238635318, val_loss: 1.6071030507012019
epochs 27/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6238670330397122, val_loss: 1.607091706896585
epochs 28/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6191534059834105, val_loss: 1.6070805674507505
epochs 29/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6241030942707162, val_loss: 1.6070693788074313
epochs 30/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.624185309984297, val_loss: 1.6070585648218791
epochs 31/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.622296328319929, val_loss: 1.6070478681534055
epochs 32/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.616787286953152, val_loss: 1.6070366927555628
epochs 33/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.623486991952227, val_loss: 1.6070254378848605
epochs 34/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6215467958550178, val_loss: 1.6070144157561044
epochs 35/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6268320489304229, val_loss: 1.607003234681629
epochs 36/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6247591597871631, val_loss: 1.6069917016559176
epochs 37/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6219668500710531, val_loss: 1.6069809633588035
epochs 38/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6225921845560922, val_loss: 1.6069709062576294
epochs 39/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6217670109883653, val_loss: 1.6069614660172236
epochs 40/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6200098685569164, val_loss: 1.6069512442936973
epochs 41/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6207347303160822, val_loss: 1.6069413934435164
epochs 42/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.62391621030438, val_loss: 1.6069323657050965
epochs 43/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6220655547386689, val_loss: 1.6069234817747087
epochs 44/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.618259610305906, val_loss: 1.606914862753853
epochs 45/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6252025453208006, val_loss: 1.6069035170570252
epochs 46/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6190085835481813, val_loss: 1.6068917210139926
epochs 47/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6219749637923315, val_loss: 1.6068804907420324
epochs 48/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6227836739954524, val_loss: 1.6068692377635412
epochs 49/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6208964573775286, val_loss: 1.6068593963744149
epochs 50/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6217381760712068, val_loss: 1.606849850170196
epochs 51/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6236447077147, val_loss: 1.6068389567117842
epochs 52/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6215852867246299, val_loss: 1.606828186247084
Starting fold 2:
epochs 1/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.614641012643513, val_loss: 1.6264280799835447
epochs 2/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6169376436032747, val_loss: 1.6263866727314298
epochs 3/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.613718204749258, val_loss: 1.6263428056050862
epochs 4/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6149534928171259, val_loss: 1.6262976820506747
epochs 5/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6160826946559705, val_loss: 1.6262544280006772
epochs 6/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6142531432603535, val_loss: 1.6262114558901106
epochs 7/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6136766609392668, val_loss: 1.6261685935277788
epochs 8/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6140838798723722, val_loss: 1.6261270500364757
epochs 9/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6149952072846263, val_loss: 1.6260846891100444
epochs 10/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6140051816639147, val_loss: 1.6260424227941603
epochs 11/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6177194055758024, val_loss: 1.6259976738975161
epochs 12/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6130070372631675, val_loss: 1.625954028159853
epochs 13/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.610431002315722, val_loss: 1.625912622799949
epochs 14/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.61234685747247, val_loss: 1.625872778514075
epochs 15/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6154628138793141, val_loss: 1.6258317780873133
epochs 16/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.611810831019753, val_loss: 1.6257925203868322
epochs 17/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6139477014541626, val_loss: 1.6257510961048187
epochs 18/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6129943621786018, val_loss: 1.625709505308242
epochs 19/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6114349628749647, val_loss: 1.6256688208807082
epochs 20/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.614425728195592, val_loss: 1.6256272963115148
epochs 21/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.615001846614637, val_loss: 1.6255860347596427
epochs 22/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6112592433628283, val_loss: 1.62554499270424
epochs 23/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6133638080797696, val_loss: 1.6255045372342307
epochs 24/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6132081809796786, val_loss: 1.62546329838889
epochs 25/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.615301762129131, val_loss: 1.6254210320730058
epochs 26/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6114464772375006, val_loss: 1.6253807374409266
epochs 27/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.613677784016258, val_loss: 1.6253396140204535
epochs 28/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.614897616286027, val_loss: 1.6252987895693098
epochs 29/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6134876113188894, val_loss: 1.6252580578365023
epochs 30/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6147098403227957, val_loss: 1.6252165673271057
epochs 31/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.614334319767199, val_loss: 1.625174187478565
epochs 32/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.616712286597804, val_loss: 1.6251307536685278
epochs 33/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.612467068120053, val_loss: 1.6250882451496427
epochs 34/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6143004241742587, val_loss: 1.6250457328463357
epochs 35/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6119516259745548, val_loss: 1.6250049329939342
epochs 36/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6123820430354068, val_loss: 1.6249646875593398
epochs 37/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.612406611442566, val_loss: 1.6249238063418676
epochs 38/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6111896514892579, val_loss: 1.62488383527786
epochs 39/52
Current Learning Rate: 6.426489847556882e-06
train_loss: 1.6152864318144948, val_loss: 1.624842846204364
epochs 40/52

[I 2024-01-28 14:59:01,645] Trial 13 pruned.

Starting fold 1:
epochs 1/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.846102340683263, val_loss: 1.998025513830639
epochs 2/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.9975821765929616, val_loss: 1.7974305146585696
epochs 3/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.797826235831096, val_loss: 1.5094096042491771
epochs 4/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.8799233598858898, val_loss: 1.481147016797747
epochs 5/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.668148807206079, val_loss: 1.5377329701469058
epochs 6/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.5900586937110461, val_loss: 1.535312536532286
epochs 7/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6594697499150382, val_loss: 1.5205810032193623
epochs 8/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6609369984471984, val_loss: 1.5072459550130934
epochs 9/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6367609582022222, val_loss: 1.4965916525119196
epochs 10/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6358891007787895, val_loss: 1.4870153495243617
epochs 11/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6131616219176048, val_loss: 1.5099167180439783
epochs 12/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6530124641837873, val_loss: 1.4932866014500774
epochs 13/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6085425409346974, val_loss: 1.4890900352013805
epochs 14/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6591423568925308, val_loss: 1.4674677325304224
epochs 15/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6534205069716688, val_loss: 1.4710649195171537
epochs 16/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6158567354941242, val_loss: 1.491348212988919
epochs 17/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.628518789226472, val_loss: 1.5252147900364386
epochs 18/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6605475067468214, val_loss: 1.5003779508449413
epochs 19/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6142489835229843, val_loss: 1.511234371119706
epochs 20/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6338475199894131, val_loss: 1.5087741392630118
epochs 21/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6053502016666672, val_loss: 1.5116877436007141
epochs 22/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.5983068705853367, val_loss: 1.5170680120508506
epochs 23/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.596252089395573, val_loss: 1.5173014068098927
epochs 24/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.5883649974593317, val_loss: 1.5147865884518497
epochs 25/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.5949960248008448, val_loss: 1.5366555029753024
epochs 26/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6059964664319424, val_loss: 1.8019508173856786
epochs 27/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.7378653855848063, val_loss: 1.7745153746276936
epochs 28/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.810479157882211, val_loss: 1.4967118179987347
epochs 29/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6505135909425026, val_loss: 1.7016626918126667
epochs 30/77

[I 2024-01-28 14:59:03,662] Trial 14 pruned.

Current Learning Rate: 0.06710940387989861
train_loss: 1.6981046293418445, val_loss: 1.544945761009499
epochs 31/77
Current Learning Rate: 0.06710940387989861
train_loss: 1.6212417835964583, val_loss: 1.5726035435994465
epochs 32/77
Number of finished trials: 15
Best trial:
Value: 1.4652380997511103
Params:
batch_size: 62
epochs: 103
hidden_size: 20
learning_rate: 0.00013635815806655385
dropout_prob: 0.16281589392460533
weight_decay: 3.898854912850674e-06
lr_step_size: 58
gamma: 0.7120345424530452
conv_channels: 123
kernel_size: 2
num_layers: 2
pool_size: 2
stride: 2

In [37]:
trainer = ModelActioner(train_data, test_data, device, model_type)
model = trainer.train(trial.params)

epochs 1/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.620214872586895
epochs 2/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6113953111876904
epochs 3/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.613412884129605
epochs 4/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.6046101081539208
epochs 5/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5939168470426344
epochs 6/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5845008790493011
epochs 7/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.576847416204466
epochs 8/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5705800511887376
epochs 9/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5695385040951446
epochs 10/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5594417312195603
epochs 11/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5505509569611349
epochs 12/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5463878997194935
epochs 13/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5418334987381814
epochs 14/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.531110919697184
epochs 15/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.536839867561636
epochs 16/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.529020938445145
epochs 17/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5150057728021917
epochs 18/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5008020077792692
epochs 19/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5003042174896724
epochs 20/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.5029728504973399
epochs 21/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4993227661495478
epochs 22/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4876906426859573
epochs 23/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4835727775180843
epochs 24/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.475912006807999
epochs 25/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4639702114001127
epochs 26/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4751570453526268
epochs 27/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4664452497808027
epochs 28/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4456586445301352
epochs 29/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4523346289782457
epochs 30/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4421595532289693
epochs 31/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.432466340736604
epochs 32/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4162591139615421
epochs 33/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4353415367888733
epochs 34/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3999294686905095
epochs 35/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.4214489514559088
epochs 36/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3834185833242578
epochs 37/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.395593364263924
epochs 38/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3880626294814364
epochs 39/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.376360619991598
epochs 40/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3822004178040463
epochs 41/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.364480811735274
epochs 42/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.357514200076251
epochs 43/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3485992586528752
epochs 44/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3595107332081862
epochs 45/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.356345385313034
epochs 46/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.330124898275859
epochs 47/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3308118495722892
epochs 48/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.334068613782735
epochs 49/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.323420717262886
epochs 50/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.3155586385810878
epochs 51/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.328273645379174
epochs 52/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.279764306902046
epochs 53/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2992322271768475
epochs 54/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2864488130304175
epochs 55/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.282769421981254
epochs 56/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2788941270448793
epochs 57/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2760884728230222
epochs 58/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2877477960477413
epochs 59/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2595682881877457
epochs 60/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2651547444328455
epochs 61/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2554591325387148
epochs 62/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.272043046187347
epochs 63/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2412925816967453
epochs 64/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2475313525384581
epochs 65/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2398427378543666
epochs 66/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2468449561528756
epochs 67/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.223295571518616
epochs 68/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2239801748327805
epochs 69/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.200892000655893
epochs 70/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2196378209431407
epochs 71/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1993290626666915
epochs 72/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2058406073442647
epochs 73/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1766492851393324
epochs 74/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.2052477359981604
epochs 75/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.163779313610473
epochs 76/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.162119811269599
epochs 77/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1743122973072697
epochs 78/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1783120065507755
epochs 79/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1593631232078647
epochs 80/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1592985523838393
epochs 81/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.167159056159812
epochs 82/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1607540672723675
epochs 83/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1540758460760117
epochs 84/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1329888867240556
epochs 85/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1250371327492552
epochs 86/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1363136576304973
epochs 87/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1218987072647457
epochs 88/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1235625227572212
epochs 89/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.104256470963149
epochs 90/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.082743437357352
epochs 91/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1011299702902915
epochs 92/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.119908759186805
epochs 93/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.0848259437881724
epochs 94/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.0927746920308596
epochs 95/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.10983688174419
epochs 96/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1607083026582086
epochs 97/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.186932031747321
epochs 98/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1066336329554167
epochs 99/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.0733967960720332
epochs 100/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1261089652986593
epochs 101/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.1113888398862222
epochs 102/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.0904153200312399
epochs 103/103
Current Learning Rate: 0.00013635815806655385
train_loss: 1.0533709807295195

In [38]:
preds = trainer.test(trial.params)
y_true = y_test[time_step:]

accuracy = accuracy_score(y_true, preds)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Precision
precision = precision_score(y_true, preds, average='weighted', zero_division=0)
print(f'Precision: {precision:.4f}')

# Recall
recall = recall_score(y_true, preds, average='weighted')
print(f'Recall: {recall:.4f}')

# F1 Score
f1 = f1_score(y_true, preds, average='weighted')
print(f'F1 Score: {f1:.4f}')

test_loss: 1.968434199393983
Accuracy: 43.43%
Precision: 0.3367
Recall: 0.4343
F1 Score: 0.3341

In [39]:
unique_elements = set(preds)
print(unique_elements)

{0, 2, 3}

In [40]:
signals = pd.DataFrame(preds, columns=['Signal'])
signals

     Signal
0         2
1         2
2         2
3         2
4         2
..      ...
246       3
247       0
248       0
249       0
250       2

[251 rows x 1 columns]

In [41]:
signals["Signal"].value_counts()

Signal
3    165
2     62
0     24
Name: count, dtype: int64

In [42]:
signals["Date"] = date_test
signals

     Signal       Date
0         2 2023-01-23
1         2 2023-01-24
2         2 2023-01-25
3         2 2023-01-26
4         2 2023-01-27
..      ...        ...
246       3 2024-01-16
247       0 2024-01-17
248       0 2024-01-18
249       0 2024-01-19
250       2 2024-01-22

[251 rows x 2 columns]

In [43]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325638
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [44]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [45]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
strong_sell_signals = signals[signals['Signal'] == 1]
sell_signals = signals[signals['Signal'] == 2]
buy_signals = signals[signals['Signal'] == 3]
strong_buy_signals = signals[signals['Signal'] == 4]


# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]
strong_buy_prices = stock_data[stock_data['Date'].isin(strong_buy_signals['Date'])]["Adj Close"]
strong_sell_prices = stock_data[stock_data['Date'].isin(strong_sell_signals['Date'])]["Adj Close"]

# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='lime', size=10, symbol='triangle-up')
))

fig.add_trace(go.Scatter(
    x=strong_buy_signals['Date'], 
    y=strong_buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))

# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='orange', size=10, symbol='triangle-down')
))

fig.add_trace(go.Scatter(
    x=strong_sell_signals['Date'], 
    y=strong_sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))

# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [46]:
price_signal = stock_data[stock_data['Date'].isin(signals['Date'])]["Adj Close"]
price_signal = price_signal.reset_index()
price_signal = price_signal.drop(columns=["index"])
result = pd.concat([price_signal,signals], axis=1)
result

      Adj Close  Signal       Date
0    140.325638       2 2023-01-23
1    141.737747       2 2023-01-24
2    141.071472       2 2023-01-25
3    143.159805       2 2023-01-26
4    145.118851       2 2023-01-27
..          ...     ...        ...
246  183.630005       3 2024-01-16
247  182.679993       0 2024-01-17
248  188.630005       0 2024-01-18
249  191.559998       0 2024-01-19
250  193.889999       2 2024-01-22

[251 rows x 3 columns]

In [47]:
price_signal

      Adj Close
0    140.325638
1    141.737747
2    141.071472
3    143.159805
4    145.118851
..          ...
246  183.630005
247  182.679993
248  188.630005
249  191.559998
250  193.889999

[251 rows x 1 columns]

In [48]:
sell_signals

     Signal       Date
0         2 2023-01-23
1         2 2023-01-24
2         2 2023-01-25
3         2 2023-01-26
4         2 2023-01-27
..      ...        ...
197       2 2023-11-02
198       2 2023-11-03
199       2 2023-11-06
200       2 2023-11-07
250       2 2024-01-22

[62 rows x 2 columns]

In [49]:
buy_prices

1284    151.075577
1285    150.031387
1286    150.399902
1287    153.228439
1288    152.581055
           ...
1514    185.139999
1515    186.190002
1516    185.589996
1517    185.919998
1518    183.630005
Name: Adj Close, Length: 165, dtype: float64