In [346]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm

In [347]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [348]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722874  43.075001  42.314999  102223600
1  2018-01-03  40.715782  43.637501  42.990002  118071600
2  2018-01-04  40.904903  43.367500  43.020000   89738400
3  2018-01-05  41.370617  43.842499  43.262501   94640000
4  2018-01-08  41.216972  43.902500  43.482498   82271200
5  2018-01-09  41.212234  43.764999  43.352501   86336000
6  2018-01-10  41.202774  43.575001  43.250000   95839600
7  2018-01-11  41.436810  43.872501  43.622501   74670800
8  2018-01-12  41.864704  44.340000  43.912498  101672400
9  2018-01-16  41.651939  44.847500  44.035000  118263600
10 2018-01-17  42.339878  44.812500  43.767502  137547200
11 2018-01-18  42.377705  45.025002  44.562500  124773600
12 2018-01-19  42.188572  44.895000  44.352501  129700400
13 2018-01-22  41.843422  44.445000  44.150002  108434400
14 2018-01-23  41.852871  44.860001  44.205002  130756400
15 2018-01-24  41.186222  44.325001  43.299999  204420400
16 2018-01-25  40.451012  43.737499  42.632500  166116000
17 2018-01-26  40.545570  43.000000  42.514999  156572000
18 2018-01-29  39.706329  42.540001  41.767502  202561600
19 2018-01-30  39.472305  41.842499  41.174999  184192800
20 2018-01-31  39.581043  42.110001  41.625000  129915600
21 2018-02-01  39.663780  42.154999  41.689999  188923200
22 2018-02-02  37.942764  41.700001  40.025002  346375200
23 2018-02-05  36.994797  40.970001  39.000000  290954000
24 2018-02-06  38.540874  40.930000  38.500000  272975200
25 2018-02-07  37.715828  40.849998  39.767502  206434400
26 2018-02-08  36.678020  40.250000  38.757500  217562000
27 2018-02-09  37.126640  39.472500  37.560001  282690400
28 2018-02-12  38.622055  40.972500  39.377499  243278000
29 2018-02-13  39.008949  41.187500  40.412498  130196800
30 2018-02-14  39.728172  41.884998  40.720001  162579600
31 2018-02-15  41.062195  43.272499  42.250000  204588800
32 2018-02-16  40.929237  43.705002  42.942501  160704400
33 2018-02-20  40.791584  43.564999  42.855000  135722000
34 2018-02-21  40.606430  43.529999  42.752499  149886400
35 2018-02-22  40.945873  43.487499  42.927502  123967600
36 2018-02-23  41.657978  43.912498  43.384998  135249600
37 2018-02-26  42.481640  44.847500  44.052502  152648800
38 2018-02-27  42.343960  45.119999  44.540001  155712400
39 2018-02-28  42.279888  45.154999  44.512501  151128400
40 2018-03-01  41.539291  44.945000  43.165001  195208000
41 2018-03-02  41.826511  44.075001  43.112499  153816000
42 2018-03-05  41.971302  44.435001  43.630001  113605600
43 2018-03-06  41.935692  44.562500  44.032501   95154000
44 2018-03-07  41.546417  43.962502  43.567501  126814000

In [349]:
time_step = 44

In [350]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [351]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [352]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma = talib.SMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA': sma,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [353]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724166,117105600.0
15,NaN,NaN,55.580714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706163,-87314800.0
16,NaN,NaN,45.152421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695100,-253430800.0
17,NaN,NaN,46.541666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.818108,2.684663,-96858800.0
18,NaN,NaN,37.470200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639374,-81.393431,2.635361,-299420400.0
19,NaN,NaN,35.398265,NaN,NaN,42.761509,41.213175,39.664841,NaN,NaN,-61.987903,-75.553944,2.599704,-483613200.0
20,NaN,NaN,37.137612,NaN,NaN,42.849893,41.156083,39.462273,NaN,NaN,-49.633966,-63.087081,2.602418,-353697600.0
21,NaN,NaN,38.494546,NaN,NaN,42.910289,41.103483,39.296678,NaN,NaN,-41.626546,-51.082805,2.600385,-164774400.0
22,NaN,NaN,25.947657,NaN,NaN,43.228468,40.955376,38.682285,NaN,NaN,-40.766198,-44.008904,2.560087,-511149600.0
23,NaN,NaN,21.743657,NaN,NaN,43.578806,40.736585,37.894364,NaN,NaN,-38.059512,-40.150752,2.593455,-802103600.0
24,NaN,NaN,39.079674,NaN,NaN,43.590201,40.602780,37.615360,NaN,NaN,-24.766563,-34.530758,2.689294,-529128400.0
25,NaN,NaN,34.666315,NaN,NaN,43.652095,40.427960,37.203826,NaN,NaN,-14.972404,-25.932826,2.662139,-735562800.0
26,NaN,NaN,30.066648,NaN,NaN,43.790963,40.201722,36.612481,NaN,NaN,-13.427771,-17.722246,2.652999,-953124800.0
27,NaN,NaN,34.135011,NaN,NaN,43.765501,39.986214,36.206926,NaN,NaN,-15.615398,-14.671858,2.663105,-670434400.0
28,NaN,NaN,45.513663,NaN,NaN,43.544875,39.824081,36.103288,NaN,NaN,-6.294895,-11.779355,2.747587,-427156400.0
29,NaN,NaN,48.015865,NaN,NaN,43.330493,39.691932,36.053371,NaN,NaN,11.072682,-3.612537,2.734577,-296959600.0
30,NaN,NaN,52.392737,NaN,NaN,42.991923,39.561347,36.130770,NaN,NaN,26.336864,10.371550,2.744682,-134380000.0
31,NaN,NaN,59.246678,NaN,NaN,42.753743,39.495571,36.237399,NaN,NaN,41.539639,26.316395,2.801800,70208800.0
32,NaN,NaN,58.345095,NaN,NaN,42.524603,39.432604,36.340606,NaN,NaN,51.997520,39.958008,2.790443,-90495600.0
33,-0.373865,-0.940885,57.371680,NaN,NaN,42.339125,39.380013,36.420900,NaN,NaN,56.241759,49.926306,2.779394,-226217600.0
34,-0.274211,-0.807551,56.017890,NaN,NaN,42.113871,39.317690,36.521510,NaN,NaN,52.331145,53.523475,2.776467,-376104000.0
35,-0.165932,-0.679227,57.975711,NaN,NaN,42.071530,39.305673,36.539816,NaN,NaN,52.421386,53.664763,2.783939,-252136400.0
36,-0.022400,-0.547861,61.815806,NaN,NaN,42.278014,39.366021,36.454028,NaN,NaN,56.395015,53.715849,2.796988,-116886800.0
37,0.156014,-0.407086,65.717908,NaN,NaN,42.641719,39.462825,36.283931,NaN,NaN,62.381560,57.065987,2.825026,35762000.0
38,0.283036,-0.269062,64.530804,NaN,NaN,43.012911,39.594706,36.176501,NaN,NaN,65.108318,61.294964,2.811693,-119950400.0
39,0.374218,-0.140406,63.951858,NaN,NaN,43.346781,39.735085,36.123390,NaN,NaN,64.319978,63.936619,2.811646,-271078800.0
40,0.382313,-0.035862,57.527272,NaN,NaN,43.527897,39.832998,36.138098,NaN,NaN,59.272713,62.900337,2.801179,-466286800.0
41,0.407211,0.052752,59.237562,NaN,NaN,43.735156,39.941134,36.147113,NaN,NaN,52.309014,58.633902,2.782217,-312470800.0
42,0.433627,0.128927,60.109606,NaN,NaN,43.918529,40.142561,36.366594,NaN,NaN,42.550392,51.377373,2.769808,-198865200.0
43,0.446542,0.192450,59.770928,NaN,NaN,43.949829,40.389606,36.829384,40.596318,40.596318,34.222971,43.027459,2.757050,-294019200.0
44,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-420833200.0

In [354]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722874
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715782
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904903
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370617
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216972
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212234
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202774
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436810
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864704
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651939
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339878
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377705
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188572
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843422
14,NaN,NaN,68.998186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724166,117105600.0,41.852871
15,NaN,NaN,55.580714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706163,-87314800.0,41.186222
16,NaN,NaN,45.152421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695100,-253430800.0,40.451012
17,NaN,NaN,46.541666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.818108,2.684663,-96858800.0,40.545570
18,NaN,NaN,37.470200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639374,-81.393431,2.635361,-299420400.0,39.706329
19,NaN,NaN,35.398265,NaN,NaN,42.761509,41.213175,39.664841,NaN,NaN,-61.987903,-75.553944,2.599704,-483613200.0,39.472305
20,NaN,NaN,37.137612,NaN,NaN,42.849893,41.156083,39.462273,NaN,NaN,-49.633966,-63.087081,2.602418,-353697600.0,39.581043
21,NaN,NaN,38.494546,NaN,NaN,42.910289,41.103483,39.296678,NaN,NaN,-41.626546,-51.082805,2.600385,-164774400.0,39.663780
22,NaN,NaN,25.947657,NaN,NaN,43.228468,40.955376,38.682285,NaN,NaN,-40.766198,-44.008904,2.560087,-511149600.0,37.942764
23,NaN,NaN,21.743657,NaN,NaN,43.578806,40.736585,37.894364,NaN,NaN,-38.059512,-40.150752,2.593455,-802103600.0,36.994797
24,NaN,NaN,39.079674,NaN,NaN,43.590201,40.602780,37.615360,NaN,NaN,-24.766563,-34.530758,2.689294,-529128400.0,38.540874
25,NaN,NaN,34.666315,NaN,NaN,43.652095,40.427960,37.203826,NaN,NaN,-14.972404,-25.932826,2.662139,-735562800.0,37.715828
26,NaN,NaN,30.066648,NaN,NaN,43.790963,40.201722,36.612481,NaN,NaN,-13.427771,-17.722246,2.652999,-953124800.0,36.678020
27,NaN,NaN,34.135011,NaN,NaN,43.765501,39.986214,36.206926,NaN,NaN,-15.615398,-14.671858,2.663105,-670434400.0,37.126640
28,NaN,NaN,45.513663,NaN,NaN,43.544875,39.824081,36.103288,NaN,NaN,-6.294895,-11.779355,2.747587,-427156400.0,38.622055
29,NaN,NaN,48.015865,NaN,NaN,43.330493,39.691932,36.053371,NaN,NaN,11.072682,-3.612537,2.734577,-296959600.0,39.008949
30,NaN,NaN,52.392737,NaN,NaN,42.991923,39.561347,36.130770,NaN,NaN,26.336864,10.371550,2.744682,-134380000.0,39.728172
31,NaN,NaN,59.246678,NaN,NaN,42.753743,39.495571,36.237399,NaN,NaN,41.539639,26.316395,2.801800,70208800.0,41.062195
32,NaN,NaN,58.345095,NaN,NaN,42.524603,39.432604,36.340606,NaN,NaN,51.997520,39.958008,2.790443,-90495600.0,40.929237
33,-0.373865,-0.940885,57.371680,NaN,NaN,42.339125,39.380013,36.420900,NaN,NaN,56.241759,49.926306,2.779394,-226217600.0,40.791584
34,-0.274211,-0.807551,56.017890,NaN,NaN,42.113871,39.317690,36.521510,NaN,NaN,52.331145,53.523475,2.776467,-376104000.0,40.606430
35,-0.165932,-0.679227,57.975711,NaN,NaN,42.071530,39.305673,36.539816,NaN,NaN,52.421386,53.664763,2.783939,-252136400.0,40.945873
36,-0.022400,-0.547861,61.815806,NaN,NaN,42.278014,39.366021,36.454028,NaN,NaN,56.395015,53.715849,2.796988,-116886800.0,41.657978
37,0.156014,-0.407086,65.717908,NaN,NaN,42.641719,39.462825,36.283931,NaN,NaN,62.381560,57.065987,2.825026,35762000.0,42.481640
38,0.283036,-0.269062,64.530804,NaN,NaN,43.012911,39.594706,36.176501,NaN,NaN,65.108318,61.294964,2.811693,-119950400.0,42.343960
39,0.374218,-0.140406,63.951858,NaN,NaN,43.346781,39.735085,36.123390,NaN,NaN,64.319978,63.936619,2.811646,-271078800.0,42.279888
40,0.382313,-0.035862,57.527272,NaN,NaN,43.527897,39.832998,36.138098,NaN,NaN,59.272713,62.900337,2.801179,-466286800.0,41.539291
41,0.407211,0.052752,59.237562,NaN,NaN,43.735156,39.941134,36.147113,NaN,NaN,52.309014,58.633902,2.782217,-312470800.0,41.826511
42,0.433627,0.128927,60.109606,NaN,NaN,43.918529,40.142561,36.366594,NaN,NaN,42.550392,51.377373,2.769808,-198865200.0,41.971302
43,0.446542,0.192450,59.770928,NaN,NaN,43.949829,40.389606,36.829384,40.596318,40.596318,34.222971,43.027459,2.757050,-294019200.0,41.935692
44,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-420833200.0,41.546417

In [355]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [356]:
indicators_with_price['Next_Adj_Close'] = indicators_with_price['Adj Close'].shift(-1)
indicators_with_price['Return'] = ((indicators_with_price['Next_Adj_Close'] - indicators_with_price['Adj Close'])/indicators_with_price['Adj Close'])*100
indicators_with_price['Signal'] = np.where(indicators_with_price['Return'] > 1, 1,
                                           np.where(indicators_with_price['Return'] < -1, 2, 0))
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Next_Adj_Close,Return,Signal
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417,41.999790,1.091244,1
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790,42.721375,1.718066,1
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375,43.134396,0.966779,0
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396,42.719009,-0.963005,0
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009,42.355839,-0.850138,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,188.630005,3.257068,1
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,191.559998,1.553301,1
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,193.889999,1.216330,1
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,195.179993,0.665322,0
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,NaN,NaN,0

In [357]:
indicators_with_price["Signal"].value_counts()

Signal
0    740
1    416
2    324
Name: count, dtype: int64

In [358]:
indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close', 'Return'])
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Signal
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417,1
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790,1
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375,0
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396,0
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,190.372500,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,1
1476,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,190.459545,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,1
1477,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,190.553182,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,1
1478,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,190.686818,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,0
1479,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,190.811136,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,0

In [359]:
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Signal
0,0.420518,0.238064,56.052942,4.051391,0.823544,44.028283,40.539883,37.051484,40.615035,40.638545,12.020130,29.597831,2.704890,-4.208332e+08,41.546417,1
1,0.431503,0.276752,59.233514,6.192289,1.284008,44.042944,40.754081,37.465219,40.644217,40.699045,-9.379546,12.287852,2.706939,-3.257368e+08,41.999790,1
2,0.492755,0.319952,63.732450,9.481636,1.816471,43.867403,41.056249,38.245095,40.685501,40.788926,-18.948476,-5.435964,2.727887,-1.969960e+08,42.721375,0
3,0.568076,0.369577,66.042453,11.303216,1.763779,43.662506,41.356637,39.050768,40.725586,40.893169,-6.400755,-11.576259,2.738476,-6.816760e+07,43.134396,0
4,0.587478,0.413157,61.780485,9.044919,1.502037,43.567676,41.561485,39.555293,40.759724,40.974318,1.684805,-7.888142,2.738628,-1.949416e+08,42.719009,0
5,0.567013,0.443928,58.241621,7.100861,1.143604,43.382885,41.728829,40.074773,40.785715,41.035718,-7.013504,-3.909818,2.715225,-3.124152e+08,42.355839,0
6,0.548495,0.464842,58.592215,7.332888,1.202911,43.261029,41.862705,40.464380,40.813054,41.096606,-20.016654,-8.448451,2.714435,-2.214400e+08,42.405685,0
7,0.515805,0.475034,57.044806,6.516173,0.819328,43.280287,41.922402,40.564517,40.831675,41.148141,-27.991976,-18.340711,2.690141,-3.790588e+08,42.256138,2
8,0.432812,0.466590,50.806350,3.052092,-0.254204,43.245415,41.956465,40.667515,40.825897,41.168690,-36.985499,-28.331377,2.648799,-5.128460e+08,41.610500,0
9,0.361721,0.445616,50.674822,2.976570,-0.055668,43.183913,41.996699,40.809486,40.824632,41.187694,-46.752180,-37.243219,2.644564,-5.914436e+08,41.596272,2
10,0.226728,0.401838,42.776479,-1.895759,-1.685963,43.175295,41.999074,40.822852,40.786315,41.163970,-59.960215,-47.899298,2.611111,-7.396632e+08,40.653915,2
11,0.072555,0.335982,38.805883,-4.708101,-2.298229,43.330932,41.955754,40.580575,40.734082,41.115770,-60.364759,-55.692385,2.604323,-9.056264e+08,40.079475,2
12,-0.123099,0.244166,33.409966,-9.019960,-3.037205,43.669843,41.830423,39.991003,40.665055,41.028464,-57.038039,-59.121004,2.589766,-1.069742e+09,39.151367,1
13,-0.126722,0.169988,48.771960,0.230787,-0.833454,43.603897,41.756840,39.909782,40.646113,41.027642,-35.113454,-50.838751,2.699328,-9.195768e+08,41.009968,2
14,-0.212000,0.093590,42.761440,-4.462381,-1.894436,43.620648,41.637563,39.654479,40.603057,40.980121,-25.755979,-39.302491,2.704914,-1.083267e+09,39.958435,2
15,-0.311617,0.012549,40.504349,-6.346439,-1.669300,43.661172,41.499415,39.337658,40.565119,40.915090,-23.129866,-27.999766,2.693604,-1.249941e+09,39.516922,0
16,-0.361498,-0.062260,42.777711,-4.867444,-0.625511,43.694932,41.413725,39.132519,40.550903,40.866664,-31.638972,-26.841606,2.745530,-1.096347e+09,39.825500,0
17,-0.417287,-0.133266,41.338349,-5.999343,-0.981174,43.709490,41.300620,38.891750,40.528603,40.808785,-33.350038,-29.372959,2.721528,-1.246694e+09,39.564396,1
18,-0.423861,-0.191385,44.466611,-4.030393,0.263973,43.655483,41.200570,38.745656,40.534603,40.771519,-30.537715,-31.842242,2.714498,-1.125582e+09,39.970303,1
19,-0.363211,-0.225750,49.885880,-0.435786,1.262314,43.579269,41.140516,38.701763,40.563292,40.769879,-23.649205,-29.178986,2.737191,-9.871604e+08,40.734619,0
20,-0.289020,-0.238404,51.759458,0.859645,1.436039,43.546088,41.114049,38.682011,40.595929,40.780866,-13.681338,-22.622753,2.743311,-8.794276e+08,41.017082,2
21,-0.311294,-0.252982,45.026021,-3.853599,0.304150,43.457724,41.012456,38.567188,40.602841,40.744736,-15.941607,-17.757384,2.697569,-1.019449e+09,39.967930,0
22,-0.293575,-0.261101,47.789675,-2.010589,2.421566,43.223491,40.894604,38.565718,40.657877,40.727829,-20.848976,-16.823974,2.740926,-9.033780e+08,40.364330,1
23,-0.215755,-0.252031,52.696869,1.419560,4.129101,42.889425,40.794079,38.698733,40.751720,40.745432,-19.855179,-18.881921,2.769122,-7.897436e+08,41.123898,0
24,-0.167663,-0.235158,51.380455,0.543890,2.390759,42.607666,40.704710,38.801755,40.806056,40.753707,-10.385155,-17.029770,2.739621,-8.794700e+08,40.931633,0
25,-0.095884,-0.207303,53.978925,2.354496,3.619328,42.427110,40.653676,38.880242,40.888313,40.779550,0.476718,-9.921205,2.745245,-7.879128e+08,41.335155,0
26,-0.027382,-0.171319,54.880251,2.981765,4.797188,42.237332,40.607152,38.976972,40.997340,40.810468,4.591612,-1.772275,2.736645,-6.874156e+08,41.475208,0
27,0.047239,-0.127607,56.572359,4.145755,4.607296,42.118852,40.581042,39.043233,41.102051,40.851511,13.924978,6.331103,2.724906,-6.011020e+08,41.733936,1
28,0.150988,-0.071888,60.146018,6.689115,3.686314,42.272668,40.615936,38.959203,41.185831,40.916260,22.180899,13.565830,2.744631,-4.946804e+08,42.308369,0
29,0.222977,-0.012915,59.277650,6.212424,3.204464,42.395829,40.646793,38.897756,41.258660,40.973911,28.084392,21.396756,2.719774,-5.776984e+08,42.213413,2
30,0.181405,0.025949,49.567801,0.427657,1.288910,42.421431,40.664951,38.908471,41.287953,40.975830,20.146169,23.470487,2.642225,-7.169336e+08,41.017082,2
31,0.012703,0.023300,39.723960,-6.863875,-1.725685,42.461950,40.627803,38.793655,41.248733,40.902971,-8.291094,13.313156,2.581203,-9.788980e+08,39.336510,0
32,-0.128702,-0.007101,39.156301,-7.330558,-1.706646,42.454273,40.631364,38.808455,41.209946,40.828288,-34.550127,-7.565017,2.567795,-1.124960e+09,39.222591,2
33,-0.281575,-0.061996,36.466798,-9.553036,-2.114937,42.515715,40.514698,38.513681,41.161879,40.732659,-45.877296,-29.572839,2.552946,-1.259728e+09,38.676647,0
34,-0.384693,-0.126535,37.885194,-8.729317,-1.761246,42.577347,40.459035,38.340723,41.121851,40.648772,-39.397567,-39.941663,2.561904,-1.146200e+09,38.845184,0
35,-0.450307,-0.191289,39.061346,-8.061895,-1.965393,42.610304,40.432213,38.254123,41.077183,40.574625,-33.203077,-39.492646,2.563719,-1.034348e+09,38.980480,2
36,-0.532560,-0.259544,36.575172,-9.947394,-3.128498,42.686408,40.367412,38.048417,41.006080,40.483730,-32.805853,-35.135499,2.530740,-1.176971e+09,38.529480,1
37,-0.535264,-0.314688,42.657091,-6.489484,-3.254299,42.697385,40.350560,38.003734,40.932119,40.427890,-28.594961,-31.534630,2.584653,-1.007261e+09,39.227341,1
38,-0.458571,-0.343464,49.472278,-2.193921,-2.205132,42.701496,40.358986,38.016476,40.882002,40.415043,-18.764646,-26.721820,2.619511,-7.929836e+08,40.138828,1
39,-0.251812,-0.325134,59.544954,5.401815,-0.367931,42.852522,40.417853,37.983183,40.873640,40.481573,5.866537,-13.831023,2.739451,-5.268260e+08,41.911957,0
40,-0.080893,-0.276286,59.913619,5.709024,0.448624,42.984210,40.466394,37.948579,40.883836,40.548521,25.969029,4.356973,2.719707,-3.905532e+08,41.987915,1
41,0.185352,-0.183958,66.948284,12.047562,1.808735,43.506950,40.649760,37.792571,40.924944,40.685709,45.736650,25.857405,2.816484,-1.657480e+08,43.635246,0
42,0.417019,-0.063763,68.103514,13.191910,1.979645,44.022548,40.829091,37.635634,40.969936,40.830831,51.666068,41.123916,2.849753,4.057600e+06,43.950947,0
43,0.610626,0.071115,68.887189,13.958459,2.226513,44.489624,40.981006,37.472388,41.020538,40.978892,58.084066,51.828928,2.832203,1.176688e+08,44.162205,0
44,0.780158,0.212924,70.053471,15.087770,2.926739,44.982153,41.158083,37.334013,41.087055,41.134192,59.732775,56.494303,2.821888,2.105136e+08,44.473156,1
45,0.954837,0.361306,72.337954,17.358382,3.109497,45.541691,41.346789,37.151887,41.157726,41.310863,63.227766,60.348202,2.843135,3.224708e+08,45.109287,0
46,1.067127,0.502470,70.769975,16.498689,2.216354,45.997971,41.519915,37.041859,41.208097,41.472057,64.911903,62.624148,2.811891,2.176220e+08,44.937729,0
47,1.134580,0.628892,69.774677,15.967504,1.698498,46.380493,41.674863,36.969233,41.246700,41.621428,64.592740,64.244136,2.785668,1.345068e+08,44.832893,0
48,1.141993,0.731513,65.895629,13.902027,1.706421,46.631591,41.780716,36.929841,41.285482,41.746050,61.526803,63.677148,2.724878,3.972600e+07,44.425430,0
49,1.167862,0.818782,67.853972,15.469610,2.484200,46.941604,41.912047,36.882490,41.341941,41.883561,61.088827,62.402790,2.722356,1.164584e+08,44.840038,0

In [360]:
y = indicators_with_price["Adj Close"]
y_2 = indicators_with_price["SMA"]
y_3 = indicators_with_price["EMA"]
y_4 = indicators_with_price["Upper_BB"]
y_5 = indicators_with_price["Middle_BB"]
y_6 = indicators_with_price["Lower_BB"]
X = np.array(date)

trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



layout = go.Layout(
    title='Stock Price and Volume',
    xaxis=dict(title='Date'),
    yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
    yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
    height=600,
)

fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# Show plot
pyo.iplot(fig)

In [361]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        # Extract a window of data from X
        X_window = self.X[idx : idx + self.window_size]
        
        # Assuming you're predicting the value right after the window
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [362]:
X = indicators_with_price.iloc[:, :-1]
y = indicators_with_price.iloc[:,-1]

signal_true = indicators_with_price.iloc[:,-1]
y

0       1
1       1
2       0
3       0
4       0
       ..
1475    1
1476    1
1477    1
1478    0
1479    0
Name: Signal, Length: 1480, dtype: int64

In [363]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1184    1
1185    0
1186    2
1187    1
1188    0
       ..
1475    1
1476    1
1477    1
1478    0
1479    0
Name: Signal, Length: 296, dtype: int64

In [364]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
# X_train = X_train.to_numpy()
# y_train = y_train.to_numpy()
y_test.head(44)

1184    1
1185    0
1186    2
1187    1
1188    0
1189    2
1190    2
1191    2
1192    1
1193    0
1194    0
1195    0
1196    2
1197    2
1198    1
1199    0
1200    1
1201    0
1202    2
1203    2
1204    2
1205    2
1206    0
1207    1
1208    2
1209    0
1210    2
1211    2
1212    1
1213    0
1214    2
1215    1
1216    2
1217    1
1218    0
1219    0
1220    1
1221    0
1222    1
1223    0
1224    0
1225    0
1226    1
1227    1
Name: Signal, dtype: int64

In [365]:
# # Get the count of each unique value in the series
# category_counts = y_train.value_counts()
# print(category_counts.index)
# print(category_counts.values)

# # Create bar plot
# plt.bar(["1","0"], category_counts.values)

# # Adding labels and title
# plt.xlabel('Category')
# plt.ylabel('Frequency')
# plt.title('Distribution of Categories')

# # Show plot
# plt.show()

In [366]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

for column in X_train.columns:
    # Initialize a scaler
    scaler = MinMaxScaler()
    
    # Fit on the training data and transform it
    X_train_scaled = scaler.fit_transform(X_train[column].to_numpy().reshape(-1, 1))
    X_train_df[column] = X_train_scaled.flatten()
    
    # Transform the test data using the same scaler
    X_test_scaled = scaler.transform(X_test[column].to_numpy().reshape(-1, 1))
    X_test_df[column] = X_test_scaled.flatten()

    scaler_dict[column] = scaler

    

X_train_df.head(24)

features = X_train_df.columns
X_test_df

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.473178,0.391410,0.484405,0.368317,0.443981,0.810260,0.788953,0.749683,0.804887,0.832500,0.850519,0.839325,0.765326,0.761787,0.780636
1,0.499847,0.411144,0.517394,0.387563,0.487569,0.813419,0.791684,0.751875,0.804933,0.833706,0.876575,0.853920,0.764804,0.775662,0.793797
2,0.523637,0.432238,0.527280,0.393264,0.448749,0.816205,0.793223,0.752021,0.804433,0.835055,0.895160,0.867699,0.724522,0.788577,0.797684
3,0.523008,0.448973,0.456306,0.359879,0.379729,0.815520,0.792793,0.751879,0.802963,0.835217,0.907286,0.887937,0.685712,0.778442,0.775317
4,0.534244,0.464868,0.497611,0.382098,0.444492,0.813808,0.792104,0.752318,0.802403,0.836117,0.913913,0.901248,0.661728,0.787383,0.790114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,0.331987,0.360467,0.219193,0.330143,0.438975,1.105702,1.104494,1.078159,1.146372,1.152418,0.696648,0.699736,0.263755,0.912203,1.018693
292,0.358007,0.354748,0.456177,0.434230,0.530971,1.099583,1.101858,1.079371,1.147028,1.152792,0.728273,0.697238,0.316961,0.925666,1.059493
293,0.396417,0.358741,0.541661,0.480564,0.534505,1.093074,1.099905,1.082407,1.147733,1.154161,0.814260,0.731128,0.316624,0.937531,1.079584
294,0.440665,0.371807,0.601114,0.515679,0.555950,1.091863,1.099564,1.083019,1.148741,1.156274,0.926300,0.813002,0.323439,0.947909,1.095561
295,0.483036,0.391711,0.631898,0.534629,0.550954,1.092553,1.099746,1.082644,1.149678,1.158738,0.984412,0.904318,0.300461,0.955220,1.104406

In [367]:
scaler_dict

{'MACD': MinMaxScaler(),
 'MACD_signal': MinMaxScaler(),
 'RSI': MinMaxScaler(),
 'CMO': MinMaxScaler(),
 'MOM': MinMaxScaler(),
 'Upper_BB': MinMaxScaler(),
 'Middle_BB': MinMaxScaler(),
 'Lower_BB': MinMaxScaler(),
 'SMA': MinMaxScaler(),
 'EMA': MinMaxScaler(),
 'SLOWK': MinMaxScaler(),
 'SLOWD': MinMaxScaler(),
 'ATR': MinMaxScaler(),
 'OBV': MinMaxScaler(),
 'Adj Close': MinMaxScaler()}

In [368]:
correlation_matrix = X_train_df.corr()

# Create the heatmap with text
fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values,  # Rounded values for display
                    texttemplate="%{text}",
                    textfont={"size":9}  # Adjust text size if necessary
                    ))

# Update the layout
fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  # or any width you desire
    height=1000,  # or any height you desire
)

# Show the figure
pyo.iplot(fig)

In [369]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train.to_numpy(), dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test.to_numpy(), dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(0)[0])

tensor(1., device='cuda:0')
tensor([[0.4732, 0.3914, 0.4844, 0.3683, 0.4440, 0.8103, 0.7890, 0.7497, 0.8049,
         0.8325, 0.8505, 0.8393, 0.7653, 0.7618, 0.7806],
        [0.4998, 0.4111, 0.5174, 0.3876, 0.4876, 0.8134, 0.7917, 0.7519, 0.8049,
         0.8337, 0.8766, 0.8539, 0.7648, 0.7757, 0.7938],
        [0.5236, 0.4322, 0.5273, 0.3933, 0.4487, 0.8162, 0.7932, 0.7520, 0.8044,
         0.8351, 0.8952, 0.8677, 0.7245, 0.7886, 0.7977],
        [0.5230, 0.4490, 0.4563, 0.3599, 0.3797, 0.8155, 0.7928, 0.7519, 0.8030,
         0.8352, 0.9073, 0.8879, 0.6857, 0.7784, 0.7753],
        [0.5342, 0.4649, 0.4976, 0.3821, 0.4445, 0.8138, 0.7921, 0.7523, 0.8024,
         0.8361, 0.9139, 0.9012, 0.6617, 0.7874, 0.7901],
        [0.5474, 0.4805, 0.5145, 0.3912, 0.4671, 0.8153, 0.7928, 0.7521, 0.8022,
         0.8373, 0.9235, 0.9113, 0.6236, 0.7974, 0.7962],
        [0.5399, 0.4914, 0.4471, 0.3605, 0.4592, 0.8163, 0.7941, 0.7537, 0.8018,
         0.8374, 0.9237, 0.9172, 0.5981, 0.7914, 0.7760],
        [0.5112, 0.4936, 0.3677, 0.3216, 0.4080, 0.8078, 0.7900, 0.7546, 0.8007,
         0.8361, 0.8756, 0.9035, 0.5869, 0.7794, 0.7495],
        [0.4709, 0.4865, 0.3118, 0.2921, 0.3590, 0.8019, 0.7857, 0.7521, 0.7990,
         0.8339, 0.7960, 0.8581, 0.5854, 0.7650, 0.7287],
        [0.4782, 0.4824, 0.4544, 0.3639, 0.4654, 0.8000, 0.7849, 0.7524, 0.7987,
         0.8341, 0.7774, 0.8059, 0.6453, 0.7842, 0.7755],
        [0.4855, 0.4807, 0.4597, 0.3667, 0.5578, 0.8016, 0.7861, 0.7533, 0.7997,
         0.8344, 0.7888, 0.7750, 0.6088, 0.7965, 0.7774],
        [0.4882, 0.4800, 0.4490, 0.3617, 0.6035, 0.8012, 0.7895, 0.7605, 0.8014,
         0.8345, 0.8188, 0.7831, 0.5723, 0.7852, 0.7740],
        [0.4834, 0.4783, 0.4231, 0.3496, 0.5378, 0.7993, 0.7924, 0.7687, 0.8022,
         0.8343, 0.7983, 0.7906, 0.5827, 0.7733, 0.7659],
        [0.4583, 0.4714, 0.3463, 0.3124, 0.4486, 0.7969, 0.7939, 0.7742, 0.8017,
         0.8327, 0.7377, 0.7723, 0.5960, 0.7621, 0.7405],
        [0.4275, 0.4590, 0.3088, 0.2931, 0.4211, 0.7958, 0.7944, 0.7765, 0.8008,
         0.8305, 0.6628, 0.7167, 0.5765, 0.7501, 0.7271],
        [0.4137, 0.4460, 0.3519, 0.3121, 0.4535, 0.7862, 0.7972, 0.7927, 0.8003,
         0.8291, 0.6220, 0.6538, 0.5583, 0.7608, 0.7388],
        [0.4007, 0.4327, 0.3416, 0.3072, 0.5122, 0.7872, 0.7955, 0.7881, 0.8007,
         0.8275, 0.6178, 0.6111, 0.5622, 0.7477, 0.7354],
        [0.4045, 0.4229, 0.4019, 0.3333, 0.5364, 0.7852, 0.7936, 0.7864, 0.8015,
         0.8268, 0.6636, 0.6114, 0.5462, 0.7599, 0.7513],
        [0.4138, 0.4171, 0.4266, 0.3443, 0.5657, 0.7842, 0.7926, 0.7854, 0.8026,
         0.8264, 0.7016, 0.6398, 0.5764, 0.7761, 0.7580],
        [0.4089, 0.4114, 0.3718, 0.3205, 0.5461, 0.7816, 0.7901, 0.7831, 0.8035,
         0.8253, 0.7177, 0.6754, 0.5921, 0.7619, 0.7426],
        [0.3676, 0.3977, 0.2382, 0.2535, 0.4085, 0.7853, 0.7857, 0.7701, 0.8024,
         0.8220, 0.6670, 0.6766, 0.6206, 0.7448, 0.6968],
        [0.3250, 0.3771, 0.2052, 0.2347, 0.4402, 0.7869, 0.7798, 0.7563, 0.8018,
         0.8181, 0.6070, 0.6429, 0.6081, 0.7171, 0.6833],
        [0.2812, 0.3510, 0.1712, 0.2147, 0.3655, 0.7876, 0.7730, 0.7415, 0.8001,
         0.8136, 0.5756, 0.5922, 0.5959, 0.7034, 0.6687],
        [0.2486, 0.3227, 0.1700, 0.2140, 0.3484, 0.7892, 0.7673, 0.7281, 0.7982,
         0.8093, 0.5907, 0.5650, 0.5762, 0.6900, 0.6682],
        [0.2435, 0.2990, 0.2674, 0.2523, 0.3853, 0.7841, 0.7620, 0.7227, 0.7968,
         0.8063, 0.6254, 0.5716, 0.5879, 0.7049, 0.6897],
        [0.2238, 0.2756, 0.2091, 0.2214, 0.3520, 0.7784, 0.7552, 0.7149, 0.7950,
         0.8023, 0.6347, 0.5927, 0.5853, 0.6914, 0.6677],
        [0.2090, 0.2536, 0.2026, 0.2178, 0.3005, 0.7750, 0.7494, 0.7066, 0.7924,
         0.7984, 0.6337, 0.6080, 0.5572, 0.6804, 0.6652],
        [0.1900, 0.2318, 0.1704, 0.2003, 0.2520, 0.7754, 0.7442, 0.6956, 0.7891,
         0.7940, 0.6029, 0.6000, 0.5297, 0.6685, 0.6527],
        [0.1556, 0.2067, 0.1075, 0.1632, 0.1687, 0.7799, 0.7388, 0.6795, 0.7847,
         0.7885, 0.5879, 0.5833, 0.5433, 0.6538, 0.6255],
        [0.1525, 0.1859, 0.2212, 0.2082, 0.2481, 0.7734, 0.7321, 0.6728, 0.7814,
         0.7844, 0.5958, 0.5698, 0.5557, 0.6668, 0.6498],
        [0.1555, 0.1699, 0.2309, 0.2122, 0.3070, 0.7647, 0.7255, 0.6687, 0.7789,
         0.7806, 0.6128, 0.5733, 0.5256, 0.6801, 0.6520],
        [0.1339, 0.1523, 0.1491, 0.1668, 0.1158, 0.7577, 0.7173, 0.6593, 0.7737,
         0.7753, 0.6174, 0.5838, 0.5644, 0.6608, 0.6189],
        [0.1280, 0.1369, 0.1898, 0.1832, 0.1605, 0.7491, 0.7100, 0.6536, 0.7691,
         0.7707, 0.6084, 0.5883, 0.5617, 0.6761, 0.6277],
        [0.1197, 0.1227, 0.1673, 0.1708, 0.1768, 0.7445, 0.7035, 0.6454, 0.7648,
         0.7658, 0.5885, 0.5796, 0.5389, 0.6622, 0.6185],
        [0.1434, 0.1167, 0.3052, 0.2288, 0.3005, 0.7391, 0.6994, 0.6428, 0.7622,
         0.7627, 0.6410, 0.5880, 0.5646, 0.6773, 0.6499],
        [0.1686, 0.1175, 0.3198, 0.2353, 0.3813, 0.7308, 0.6949, 0.6425, 0.7608,
         0.7599, 0.6945, 0.6188, 0.5655, 0.6895, 0.6535],
        [0.1951, 0.1240, 0.3365, 0.2425, 0.3916, 0.7222, 0.6908, 0.6433, 0.7595,
         0.7575, 0.7638, 0.6813, 0.5445, 0.7006, 0.6575],
        [0.2347, 0.1381, 0.4132, 0.2767, 0.4185, 0.7093, 0.6868, 0.6492, 0.7585,
         0.7561, 0.8140, 0.7430, 0.5309, 0.7126, 0.6763],
        [0.2680, 0.1568, 0.4111, 0.2759, 0.4105, 0.6915, 0.6825, 0.6595, 0.7575,
         0.7548, 0.8756, 0.8075, 0.5074, 0.7002, 0.6758],
        [0.3040, 0.1797, 0.4490, 0.2927, 0.4830, 0.6765, 0.6794, 0.6695, 0.7575,
         0.7540, 0.9451, 0.8721, 0.4925, 0.7102, 0.6850],
        [0.3408, 0.2063, 0.4816, 0.3075, 0.3519, 0.6757, 0.6792, 0.6699, 0.7556,
         0.7536, 0.9697, 0.9276, 0.4790, 0.7212, 0.6930],
        [0.3670, 0.2334, 0.4586, 0.2993, 0.3087, 0.6765, 0.6795, 0.6696, 0.7532,
         0.7530, 0.9536, 0.9554, 0.4712, 0.7092, 0.6880],
        [0.3890, 0.2600, 0.4604, 0.3001, 0.3267, 0.6791, 0.6805, 0.6689, 0.7509,
         0.7524, 0.9231, 0.9476, 0.4465, 0.7192, 0.6884],
        [0.4219, 0.2886, 0.5376, 0.3335, 0.3368, 0.6851, 0.6825, 0.6665, 0.7489,
         0.7528, 0.9317, 0.9341, 0.4445, 0.7331, 0.7062]], device='cuda:0')

# Vanilla LSTM

In [370]:
class VanillaLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob):
        super(VanillaLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

# Stacked LSTM

In [371]:
class StackedLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, stateful):
        super(StackedLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size
        self.stateful = stateful
        
        self.hn = None
        self.cn = None

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=self.layer_size,
                            dropout=(dropout_prob if self.layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def reset_hidden_state(self, batch_size=None):
        if batch_size is None or not self.stateful:
            # Reset hidden and cell states to None if batch_size is not provided or if the model is not stateful
            self.hn = None
            self.cn = None
        else:
            # Resize hidden and cell states to match current batch size, preserving the state as much as possible
            self.hn = self._resize_state(self.hn, batch_size)
            self.cn = self._resize_state(self.cn, batch_size)


    def _resize_state(self, state, batch_size):
        if state is None:
            # If state is not initialized, initialize with zeros
            return torch.zeros(self.layer_size, batch_size, self.hidden_size).to(device)
        elif batch_size < state.size(1):
            # If batch size is smaller, truncate the state
            return state[:, :batch_size, :].contiguous()
        elif batch_size > state.size(1):
            # If batch size is larger, pad the state with zeros
            padding_size = batch_size - state.size(1)
            padding = torch.zeros(self.layer_size, padding_size, self.hidden_size).to(device)
            return torch.cat([state, padding], dim=1)
        

    def forward(self, x):
        current_batch_size = x.size(0)

        # Check and adjust the hidden and cell states
        if not self.stateful or self.hn is None or self.hn.size(1) != current_batch_size:
            self.reset_hidden_state(current_batch_size)
        else:
            # Detach the hidden states from the graph to avoid backpropagating through the entire sequence history
            self.hn = self.hn.detach()
            self.cn = self.cn.detach()

        # Ensure that hn and cn are not None and have the correct shape
        h0 = self.hn if self.hn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)
        c0 = self.cn if self.cn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0, c0))

        # Update hidden states if stateful
        if self.stateful:
            self.hn, self.cn = hn.detach(), cn.detach()

        # Process the output of the last time step
        out = self.dropout(out[:, -1, :])  # Add dropout
        out = self.fc(out)  # Fully connected layer

        return out

# Bidirectional LSTM

# 1D CNN-LSTM

In [372]:
class OneDimCNNLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, conv_channels, kernel_size, pool_size, stride):
        super(OneDimCNNLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size

        # Convolutional Layer
        self.conv1 = nn.Conv1d(in_channels=input_dim, out_channels=conv_channels, kernel_size=kernel_size)
        self.relu1 = nn.ReLU()
        self.maxpool1 = nn.MaxPool1d(kernel_size=pool_size, stride=pool_size)

        # self.conv2 = nn.Conv1d(in_channels=conv_channels, out_channels=conv_channels*2, kernel_size=kernel_size)
        # self.relu2 = nn.ReLU()
        # self.maxpool2 = nn.MaxPool1d(kernel_size=2, stride=2)


        self.lstm = nn.LSTM(input_size = conv_channels, hidden_size = hidden_size, num_layers=layer_size,
                            dropout=(dropout_prob if layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def forward(self, x):
        # CNN in_dim: (batch_size, in_channels, length)
        x = x.transpose(1, 2)

        # Conv layer forward propagate
        x = self.conv1(x)
        x = self.relu1(x)
        x = self.maxpool1(x)

        # x = self.conv2(x)
        # x = self.relu2(x)
        # x = self.maxpool2(x)

        # LSTM in_dim: (batch_size, seq_len, input_size)
        x = x.transpose(1, 2)

        assert x.size(-1) == self.lstm.input_size, f"Mismatch in LSTM input size. Expected: {self.lstm.input_size}, Got: {x.size(-1)}"

        # Initializing hidden state
        h0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Initialize cell state
        c0 = torch.zeros(self.layer_size, x.size(0), self.hidden_size).to(device) 

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        out = self.dropout(out[:, -1, :])  # Add dropout

        out = self.fc(out)

        return out

In [373]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device, model_type):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model_type = model_type
        self.model = None
        self.optimizer = None
        self.criterion = nn.CrossEntropyLoss()

    
    def train_validate(self, config, trial):

        if self.model_type == "Vanilla LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=3).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=3).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=3, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []

        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')

            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.long()


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    loss = loss.mean()
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.long()

                        preds = self.model(data)
                        loss = self.criterion(preds, target)
                        loss = loss.mean()

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
        if self.model_type == "Vanilla LSTM":

            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = 1
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]

            self.model = VanillaLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=3).to(self.device)
            
        elif self.model_type == "Stacked LSTM":
            
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            
            self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=3).to(self.device)

        elif self.model_type == "1D CNN-LSTM":
            batch_size = config["batch_size"]
            epochs = config["epochs"]
            hidden_size = config["hidden_size"]
            num_layers = config["num_layers"]
            learning_rate = config["learning_rate"]
            dropout_prob = config["dropout_prob"]
            weight_decay = config["weight_decay"]
            lr_step_size = config["lr_step_size"]
            gamma = config["gamma"]
            kernel_size = config["kernel_size"]
            conv_channels = config["conv_channels"]
            pool_size = config["pool_size"]
            stride = config["stride"]

            self.model = OneDimCNNLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, output_dim=3, conv_channels=conv_channels, kernel_size=kernel_size, pool_size=pool_size, stride=stride).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.long()  

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                loss = loss.mean()
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.long()
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                _, predicted_classes = torch.max(preds, 1)
                all_preds.extend(predicted_classes.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [374]:
model_type = "1D CNN-LSTM"

def objective(trial):
    if model_type == "Vanilla LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.15),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 10, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9)
        }

    elif model_type == "Stacked LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "num_layers": trial.suggest_int("num_layers", 1, 5)
        }

    elif model_type == "1D CNN-LSTM":
        config = {
            "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
            "epochs": trial.suggest_int("epochs", 50, 150),
            "hidden_size": trial.suggest_int("hidden_size", 10, 100),
            "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
            "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
            "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
            "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
            "gamma": trial.suggest_float("gamma", 0.1, 0.9),
            "conv_channels": trial.suggest_int("conv_channels", 16, 128),
            "kernel_size": trial.suggest_int("kernel_size", 2, 6),
            "num_layers": trial.suggest_int("num_layers", 1, 5),
            "pool_size": trial.suggest_int("pool_size", 2, 5),
            "stride": trial.suggest_int("stride", 1, 4)
        }

    trainer = ModelActioner(train_data, test_data, device, model_type)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [375]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=25, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    # Optionally, you can include additional information in the progress bar
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=25, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-27 01:09:27,508] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/25 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.087007609166597, val_loss: 1.0812877554642526
epochs 2/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.087238543911984, val_loss: 1.0810697819057264
epochs 3/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0865755419982106, val_loss: 1.080854374484012
epochs 4/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0862810047049272, val_loss: 1.080641285996688
epochs 5/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.086279156333522, val_loss: 1.0804289228037784
epochs 6/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0860497286445217, val_loss: 1.080216767913417
epochs 7/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.086237879803306, val_loss: 1.0800046130230552
epochs 8/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0857690246481644, val_loss: 1.0797940956918817
epochs 9/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0851413500936409, val_loss: 1.0795836436121087
epochs 10/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0840209408810264, val_loss: 1.0793739632556314
epochs 11/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.085821913418017, val_loss: 1.0791638675488924
epochs 12/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.085526674672177, val_loss: 1.078953322611357
epochs 13/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.084921101519936, val_loss: 1.0787437401319806
epochs 14/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0838367349223086, val_loss: 1.078533781202216
epochs 15/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0850859503997, val_loss: 1.0783237846274125
epochs 16/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0846154576853702, val_loss: 1.078114168267501
epochs 17/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0835666367882177, val_loss: 1.0779043134890105
epochs 18/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0844673043803166, val_loss: 1.07769388650593
epochs 19/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0840029026332654, val_loss: 1.077482018972698
epochs 20/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0832725148451956, val_loss: 1.0772692291360153
epochs 21/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.083652091026306, val_loss: 1.0770588523463198
epochs 22/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.083121270882456, val_loss: 1.076850350279557
epochs 23/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0830261104985288, val_loss: 1.07664332515315
epochs 24/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0821435576991032, val_loss: 1.0764347013674285
epochs 25/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0836568518688805, val_loss: 1.076223769940828
epochs 26/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0823813024320101, val_loss: 1.0760113552996986
epochs 27/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0816730336139078, val_loss: 1.0757984261763722
epochs 28/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0820674582531578, val_loss: 1.075584770503797
epochs 29/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.08162117129878, val_loss: 1.0753705739974975
epochs 30/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0819099074915837, val_loss: 1.0751563699621902
epochs 31/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.081484045480427, val_loss: 1.0749420743239553
epochs 32/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0799356008830823, val_loss: 1.0747289582302695
epochs 33/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0812643327211078, val_loss: 1.0745167569110268
epochs 34/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0795244317305714, val_loss: 1.0743051629317435
epochs 35/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.078720518162376, val_loss: 1.0740922940404791
epochs 36/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0793871841932599, val_loss: 1.073879014818292
epochs 37/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0801140421315243, val_loss: 1.073665055475737
epochs 38/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0792545280958477, val_loss: 1.0734506054928428
epochs 39/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0792765629918952, val_loss: 1.0732341126391762
epochs 40/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0783343202189395, val_loss: 1.0730173976797805
epochs 41/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0786166529906422, val_loss: 1.0727991693898251
epochs 42/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.078555871310987, val_loss: 1.0725812071248104
epochs 43/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0780239971060501, val_loss: 1.0723617428227474
epochs 44/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.079416645200629, val_loss: 1.0721414064106187
epochs 45/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.078815729994523, val_loss: 1.0719200824436388
epochs 46/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0788643385234633, val_loss: 1.0716981950559115
epochs 47/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0786194650750411, val_loss: 1.0714752360394126
epochs 48/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0779530738529406, val_loss: 1.0712500948654977
epochs 49/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.077897636513961, val_loss: 1.0710251042717382
epochs 50/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.076732927874515, val_loss: 1.0708021778809398
epochs 51/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0781152060157375, val_loss: 1.070579743385315
epochs 52/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0759339470612375, val_loss: 1.070354841884814
epochs 53/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0777087876671239, val_loss: 1.0701294610374852
epochs 54/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0766107847816067, val_loss: 1.0699051028803774
epochs 55/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0762957284325048, val_loss: 1.069680787387647
epochs 56/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0761042707844783, val_loss: 1.069455865809792
epochs 57/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0746892703206916, val_loss: 1.0692294309013768
epochs 58/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0744781832945973, val_loss: 1.06900061431684
epochs 59/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0754476396661057, val_loss: 1.0687696582392643
epochs 60/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.074450932051006, val_loss: 1.0685387837259392
epochs 61/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.075759922830682, val_loss: 1.0683092205147995
epochs 62/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.074052609895405, val_loss: 1.0680793398304989
epochs 63/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0737681263371517, val_loss: 1.0678462894339311
epochs 64/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.073671125110827, val_loss: 1.067611511130082
epochs 65/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.075344433282551, val_loss: 1.0673754767367714
epochs 66/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0734623758416426, val_loss: 1.067139704603898
epochs 67/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0739163863031487, val_loss: 1.0669040830511796
epochs 68/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0735395820517288, val_loss: 1.0666679595646105
epochs 69/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0730141200517354, val_loss: 1.0664316516173513
epochs 70/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0726016709679052, val_loss: 1.0661963513022974
epochs 71/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0736996374632184, val_loss: 1.0659603595733642
epochs 72/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.072352449517501, val_loss: 1.0657247016304419
epochs 73/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0730096741726525, val_loss: 1.0654886609629581
epochs 74/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.072381271814045, val_loss: 1.0652523329383448
epochs 75/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0717548282522904, val_loss: 1.0650165846473292
epochs 76/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0717259946622346, val_loss: 1.0647793493772808
epochs 77/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.071161171009666, val_loss: 1.0645402092682688
epochs 78/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.071155423867075, val_loss: 1.0642985080417833
epochs 79/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0703708498101485, val_loss: 1.0640556975414879
epochs 80/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0712982353411222, val_loss: 1.0638126385839362
epochs 81/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0710059053019474, val_loss: 1.0635702384145636
epochs 82/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0713541457527562, val_loss: 1.0633306013910393
epochs 83/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0691922852867528, val_loss: 1.0630892439892417
epochs 84/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0686512771405672, val_loss: 1.0628429927323995
epochs 85/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0697359147824739, val_loss: 1.062595494169938
epochs 86/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0710074575323807, val_loss: 1.0623466930891339
epochs 87/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0687375809016981, val_loss: 1.0620958453730533
epochs 88/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0685150773901688, val_loss: 1.0618437076869764
epochs 89/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.069149751412241, val_loss: 1.0615890239414416
epochs 90/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0679383817471957, val_loss: 1.0613306685497885
epochs 91/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0672224985925776, val_loss: 1.0610703016582288
epochs 92/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0676675031059666, val_loss: 1.060810412858662
epochs 93/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0668416236576281, val_loss: 1.0605483318630018
epochs 94/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.067395419823496, val_loss: 1.0602839708328247
epochs 95/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0669213658884953, val_loss: 1.060017244439376
epochs 96/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0669774645253232, val_loss: 1.0597507213291368
epochs 97/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0658243016192788, val_loss: 1.0594847014075832
epochs 98/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0661682618291755, val_loss: 1.0592181745328402
epochs 99/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0663749180342021, val_loss: 1.058952347855819
epochs 100/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0652184072293733, val_loss: 1.058686795987581
epochs 101/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0660726559789557, val_loss: 1.0584202916998613
epochs 102/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0656464250464188, val_loss: 1.0581517319930227
epochs 103/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0658308493463617, val_loss: 1.0578807993939048
epochs 104/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.064258182676215, val_loss: 1.0576099960427536
epochs 105/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0654038303776792, val_loss: 1.0573403107492547
epochs 106/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0644878650966443, val_loss: 1.0570688410809166
epochs 107/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0652449871364393, val_loss: 1.0567971907163922
epochs 108/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0647135872589915, val_loss: 1.0565245207987333
Starting fold 2:
epochs 1/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0593795010918066, val_loss: 1.082514476776123
epochs 2/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0585128382632607, val_loss: 1.0824060841610557
epochs 3/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0588849004946257, val_loss: 1.0822955834238153
epochs 4/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0580984855953015, val_loss: 1.0821848957162155
epochs 5/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0579110145568849, val_loss: 1.0820751064702083
epochs 6/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.057770552133259, val_loss: 1.081965947151184
epochs 7/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0579930355674343, val_loss: 1.0818582547338385
epochs 8/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0568740493372868, val_loss: 1.0817521283501073
epochs 9/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0572098669252898, val_loss: 1.081646264226813
epochs 10/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0559883682351363, val_loss: 1.0815407878474186
epochs 11/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0555489552648445, val_loss: 1.081437513702794
epochs 12/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0562199140849866, val_loss: 1.081336125574614
epochs 13/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0548410854841535, val_loss: 1.0812364565698724
epochs 14/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0550650345651726, val_loss: 1.081137116331803
epochs 15/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0546341369026586, val_loss: 1.0810393145209864
epochs 16/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0543021390312597, val_loss: 1.0809436333806892
epochs 17/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.053879179452595, val_loss: 1.0808500252271953
epochs 18/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0526174369611239, val_loss: 1.080757797391791
epochs 19/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.051138973236084, val_loss: 1.0806664818211607
epochs 20/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0526122871198151, val_loss: 1.0805759392286602
epochs 21/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0510061339328163, val_loss: 1.080487797134801
epochs 22/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0510907273543508, val_loss: 1.0804005459735269
epochs 23/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0510056332538003, val_loss: 1.0803168736006084
epochs 24/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0508946393665515, val_loss: 1.0802356406262046
epochs 25/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0485491564399319, val_loss: 1.0801560941495394
epochs 26/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0497552495253712, val_loss: 1.0800778602298937
epochs 27/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0489049911499024, val_loss: 1.0800011346214695
epochs 28/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0480739718989323, val_loss: 1.0799283353905929
epochs 29/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0479772617942409, val_loss: 1.079857185012416
epochs 30/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0468394216738248, val_loss: 1.0797886308870817
epochs 31/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.046123638905977, val_loss: 1.0797232452191805
epochs 32/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.046549485859118, val_loss: 1.0796585760618511
epochs 33/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0449726405896638, val_loss: 1.0795966989115664
epochs 34/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0452949147475392, val_loss: 1.0795393655174657
epochs 35/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.043992789168107, val_loss: 1.0794848843624718
epochs 36/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0441192401082893, val_loss: 1.079432151192113
epochs 37/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0431213328712865, val_loss: 1.0793810856969732
epochs 38/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.043723097600435, val_loss: 1.0793350006404676
epochs 39/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.041925151097147, val_loss: 1.079293239744086
epochs 40/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.041157118897689, val_loss: 1.079254718830711
epochs 41/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0423693336938558, val_loss: 1.079220441768044
epochs 42/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.04099358132011, val_loss: 1.0791893883755332
epochs 43/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0410767116044697, val_loss: 1.0791619614550942
epochs 44/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.039197105483005, val_loss: 1.0791391197003817
epochs 45/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.040257119505029, val_loss: 1.0791194300902518
epochs 46/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0397922039031982, val_loss: 1.0791030193630018
epochs 47/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0386409364248577, val_loss: 1.0790887242869327
epochs 48/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0377480092801545, val_loss: 1.079080699619494
epochs 49/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0375333334270276, val_loss: 1.0790797221033197
epochs 50/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0357757041328832, val_loss: 1.0790834991555465
epochs 51/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.036679149928846, val_loss: 1.0790935202648766
epochs 52/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.034784598099558, val_loss: 1.0791089597501253
epochs 53/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0340605039345592, val_loss: 1.0791300158751638
epochs 54/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0356405044856825, val_loss: 1.0791553058122334
epochs 55/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0341181905646073, val_loss: 1.0791846890198558
epochs 56/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.032977793718639, val_loss: 1.079222866108543
epochs 57/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.032994356280879, val_loss: 1.0792694756859227
epochs 58/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.03372853178727, val_loss: 1.0793200831664236
epochs 59/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0332052362592596, val_loss: 1.079375544347261
epochs 60/108
Current Learning Rate: 9.69243553136279e-06
train_loss: 1.0314923393098931, val_loss: 1.079437017440796
epochs 61/108
Current Learning Rate: 9.69243553136279e-06

[I 2024-01-27 01:10:08,848] Trial 0 finished with value: 1.0732808287764153 and parameters: {'batch_size': 92, 'epochs': 108, 'hidden_size': 69, 'learning_rate': 9.69243553136279e-06, 'dropout_prob': 0.11252149882858338, 'weight_decay': 1.5406397074921667e-05, 'lr_step_size': 97, 'gamma': 0.29493266281464603, 'conv_channels': 75, 'kernel_size': 6, 'num_layers': 2, 'pool_size': 5, 'stride': 3}. Best is trial 0 with value: 1.0732808287764153.

Current Learning Rate: 2.8586158204241164e-06
train_loss: 1.0327717738402518, val_loss: 1.1066702089811626
Mean validation loss: 1.0732808287764153
Starting fold 1:
epochs 1/81
Current Learning Rate: 0.02232859040835427
train_loss: 1.1484769582748413, val_loss: 0.9975131452083588
epochs 2/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9878760874271393, val_loss: 0.9965087473392487
epochs 3/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9996513426303864, val_loss: 1.0050821006298065
epochs 4/81
Current Learning Rate: 0.02232859040835427
train_loss: 1.0042048692703247, val_loss: 1.004830926656723
epochs 5/81
Current Learning Rate: 0.02232859040835427
train_loss: 1.0096585750579834, val_loss: 1.0002799332141876
epochs 6/81
Current Learning Rate: 0.02232859040835427
train_loss: 1.006783127784729, val_loss: 0.9964340329170227
epochs 7/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9986208975315094, val_loss: 0.9949827194213867
epochs 8/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9972013831138611, val_loss: 0.9946558773517609
epochs 9/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9956429898738861, val_loss: 0.9933697283267975
epochs 10/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9881445467472076, val_loss: 0.9913752675056458
epochs 11/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9876270294189453, val_loss: 0.9885723888874054
epochs 12/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.980379581451416, val_loss: 0.9859611093997955
epochs 13/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9805900454521179, val_loss: 0.9838002324104309
epochs 14/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9752305746078491, val_loss: 0.9820896089076996
epochs 15/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9642744660377502, val_loss: 0.9819767773151398
epochs 16/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9573662281036377, val_loss: 0.9857240915298462
epochs 17/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9357002079486847, val_loss: 1.0000430941581726
epochs 18/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9256368279457092, val_loss: 1.0443989634513855
epochs 19/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9400006234645844, val_loss: 1.0093815922737122
epochs 20/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9295769333839417, val_loss: 0.9854747354984283
epochs 21/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9194324612617493, val_loss: 0.986338883638382
epochs 22/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9339558482170105, val_loss: 0.9860146343708038
epochs 23/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9219297170639038, val_loss: 0.9932378232479095
epochs 24/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9193896651268005, val_loss: 1.00229611992836
epochs 25/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9170163869857788, val_loss: 1.0172008872032166
epochs 26/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9180171489715576, val_loss: 1.0069269835948944
epochs 27/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9139399230480194, val_loss: 1.0087601840496063
epochs 28/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9003893733024597, val_loss: 1.0291981101036072
epochs 29/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8994889855384827, val_loss: 1.0289975702762604
epochs 30/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8996681571006775, val_loss: 1.038694590330124
epochs 31/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8962112367153168, val_loss: 1.0559672713279724
epochs 32/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8981757164001465, val_loss: 1.0554780960083008
epochs 33/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8911349475383759, val_loss: 1.0482577681541443
epochs 34/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8973455727100372, val_loss: 1.0767669081687927
epochs 35/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8973128199577332, val_loss: 1.0514113306999207
epochs 36/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8936452865600586, val_loss: 1.0689523816108704
epochs 37/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8784897327423096, val_loss: 1.078622817993164
epochs 38/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8978266417980194, val_loss: 1.0716800093650818
epochs 39/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8929717838764191, val_loss: 1.080846905708313
epochs 40/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8998718559741974, val_loss: 1.090646207332611
epochs 41/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8824782967567444, val_loss: 1.0311468243598938
epochs 42/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.891125500202179, val_loss: 1.1138755083084106
epochs 43/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9095248878002167, val_loss: 1.1012025475502014
epochs 44/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8806413114070892, val_loss: 1.093743085861206
epochs 45/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8874681890010834, val_loss: 1.1056448817253113
epochs 46/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8858744502067566, val_loss: 1.0975371599197388
epochs 47/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8624199628829956, val_loss: 1.0880693197250366
epochs 48/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8720420897006989, val_loss: 1.0865404605865479
epochs 49/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8596284985542297, val_loss: 1.09568190574646
epochs 50/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8534072041511536, val_loss: 1.1132375001907349
epochs 51/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8643805980682373, val_loss: 1.1109683513641357
epochs 52/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8653223216533661, val_loss: 1.1054332852363586
epochs 53/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8687379062175751, val_loss: 1.1047574877738953
epochs 54/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8602995276451111, val_loss: 1.1090498566627502
epochs 55/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8450775146484375, val_loss: 1.1220842003822327
epochs 56/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8447230160236359, val_loss: 1.144193708896637
epochs 57/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8754526078701019, val_loss: 1.1534910202026367
epochs 58/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8527571260929108, val_loss: 1.1293936371803284
epochs 59/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8541049063205719, val_loss: 1.118112325668335
epochs 60/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8504904806613922, val_loss: 1.1141135692596436
epochs 61/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8311784863471985, val_loss: 1.136552333831787
epochs 62/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8375677764415741, val_loss: 1.1270637512207031
epochs 63/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8218201398849487, val_loss: 1.1206876039505005
epochs 64/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8270315527915955, val_loss: 1.1230573058128357
epochs 65/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8155225813388824, val_loss: 1.1286028623580933
epochs 66/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8185380697250366, val_loss: 1.1663901805877686
epochs 67/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8041256964206696, val_loss: 1.1721315383911133
epochs 68/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.8088445365428925, val_loss: 1.1913678646087646
epochs 69/81
Epoch 00069: reducing learning rate of group 0 to 7.8137e-03.
Current Learning Rate: 0.007813709386167657
train_loss: 0.8005703687667847, val_loss: 1.1480488181114197
epochs 70/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.807260274887085, val_loss: 1.1785555481910706
epochs 71/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7859007716178894, val_loss: 1.201649785041809
epochs 72/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7961267530918121, val_loss: 1.2008106112480164
epochs 73/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7946748435497284, val_loss: 1.193599820137024
epochs 74/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7927508652210236, val_loss: 1.1902533173561096
epochs 75/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7869791686534882, val_loss: 1.1884140968322754
epochs 76/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.8028179109096527, val_loss: 1.1822180151939392
epochs 77/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7993278503417969, val_loss: 1.1901094317436218
epochs 78/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7856237292289734, val_loss: 1.2014055848121643
epochs 79/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7678056359291077, val_loss: 1.216302216053009
epochs 80/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7844702005386353, val_loss: 1.2081857919692993
epochs 81/81
Current Learning Rate: 0.007813709386167657
train_loss: 0.7808551788330078, val_loss: 1.197087049484253
Starting fold 2:
epochs 1/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9890442192554474, val_loss: 1.1583147048950195
epochs 2/81
Current Learning Rate: 0.02232859040835427
train_loss: 1.0533547699451447, val_loss: 1.171726405620575
epochs 3/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9496635049581528, val_loss: 1.1391047835350037
epochs 4/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9443382769823074, val_loss: 1.1320868730545044
epochs 5/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9522696435451508, val_loss: 1.133297324180603
epochs 6/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9306122064590454, val_loss: 1.1294082403182983
epochs 7/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9150160253047943, val_loss: 1.1256992816925049
epochs 8/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9233711063861847, val_loss: 1.1162617206573486
epochs 9/81

[I 2024-01-27 01:10:12,470] Trial 1 pruned.

Current Learning Rate: 0.02232859040835427
train_loss: 0.9120882153511047, val_loss: 1.1220550537109375
epochs 10/81
Current Learning Rate: 0.02232859040835427
train_loss: 0.9023408591747284, val_loss: 1.1211780309677124
epochs 11/81
Starting fold 1:
epochs 1/87
Current Learning Rate: 0.017106179096075008
train_loss: 1.1272090836575157, val_loss: 1.039106798171997
epochs 2/87
Current Learning Rate: 0.017106179096075008
train_loss: 1.048680870156539, val_loss: 1.018498296486704
epochs 3/87
Current Learning Rate: 0.017106179096075008
train_loss: 1.0224226738277236, val_loss: 1.0014935913838838
epochs 4/87
Current Learning Rate: 0.017106179096075008
train_loss: 1.010784309788754, val_loss: 0.9823576500541286
epochs 5/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9984893974504973, val_loss: 0.9816793253547267
epochs 6/87
Current Learning Rate: 0.017106179096075008
train_loss: 1.0004116083446302, val_loss: 0.9882671469136288
epochs 7/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9950223583924143, val_loss: 0.9945564069245991
epochs 8/87
Current Learning Rate: 0.017106179096075008
train_loss: 1.003567876313862, val_loss: 0.9948082641551369
epochs 9/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9981456555818257, val_loss: 0.98639264922393
epochs 10/87
Current Learning Rate: 0.017106179096075008
train_loss: 1.0054190685874538, val_loss: 0.9838449126795719
epochs 11/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9979416646455463, val_loss: 0.9825809296808745
epochs 12/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9908799058512637, val_loss: 0.982507060076061
epochs 13/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9816789909412986, val_loss: 0.9801309554200424
epochs 14/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9661116236134579, val_loss: 0.9937022535424483
epochs 15/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9626070311194972, val_loss: 0.9873108405815928
epochs 16/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9450068147558915, val_loss: 1.0051909798070005
epochs 17/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9445178546403584, val_loss: 1.006820825526589
epochs 18/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9375856474826211, val_loss: 1.0068116037469161
epochs 19/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9385946418109693, val_loss: 1.0070556176336187
epochs 20/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9340934678127891, val_loss: 0.9965579371703298
epochs 21/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9415155881329587, val_loss: 1.0340339798676341
epochs 22/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.956130842158669, val_loss: 0.9931209225403635
epochs 23/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9269690124612106, val_loss: 0.9837673852318212
epochs 24/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9334443995827123, val_loss: 0.967140793800354
epochs 25/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9403005963877628, val_loss: 0.9919043151955855
epochs 26/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9396983974858334, val_loss: 0.9808077511034514
epochs 27/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9214648516554581, val_loss: 1.0142700559214541
epochs 28/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9529427540929694, val_loss: 1.0404216778905768
epochs 29/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9330575729671278, val_loss: 1.0199038819262856
epochs 30/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9275722804822419, val_loss: 1.0158875678714954
epochs 31/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9332436172585739, val_loss: 1.0058078778417487
epochs 32/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9171853793294806, val_loss: 1.06223448828647
epochs 33/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9553259724064878, val_loss: 0.9850450038909913
epochs 34/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9327771337408769, val_loss: 1.0587791480516133
epochs 35/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9585511082097103, val_loss: 0.9730821446368568
epochs 36/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9343951651924535, val_loss: 0.9858378824434783
epochs 37/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9329639761071457, val_loss: 1.0200918963080958
epochs 38/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.93228675691705, val_loss: 1.0045694940968564
epochs 39/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9053524054979023, val_loss: 1.0199568447313812
epochs 40/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9358839461677952, val_loss: 1.0028270859467356
epochs 41/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9172104998638756, val_loss: 1.0094298651343898
epochs 42/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9143033165680735, val_loss: 1.0711827880457827
epochs 43/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9207894676610043, val_loss: 1.0056780124965468
epochs 44/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9176502001912971, val_loss: 1.1225269116853414
epochs 45/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.970315536699797, val_loss: 1.023285048258932
epochs 46/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9543219365571675, val_loss: 1.0855198333137914
epochs 47/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9353156924247742, val_loss: 0.9766776555462887
epochs 48/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.929113234971699, val_loss: 0.9916108834116082
epochs 49/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9287587755604794, val_loss: 1.0860450957950794
epochs 50/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9271757176047877, val_loss: 0.9826806783676147
epochs 51/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9184489802310342, val_loss: 1.047505901989184
epochs 52/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9129151005493967, val_loss: 0.9992307161030016
epochs 53/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9116805264824315, val_loss: 1.0943351896185625
epochs 54/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9440103781850715, val_loss: 0.9987297120847201
epochs 55/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9352341871512564, val_loss: 1.0483252788844861
epochs 56/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9265384661523919, val_loss: 1.0394787386844033
epochs 57/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9133425587101986, val_loss: 1.0450796290447837
epochs 58/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9131948508714375, val_loss: 1.02884471040023
epochs 59/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8964844208014638, val_loss: 1.0411466661252473
epochs 60/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8979469537734985, val_loss: 1.0491316544382197
epochs 61/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8956644955434298, val_loss: 1.1321065551356266
epochs 62/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9070516837270637, val_loss: 1.0743219024256656
epochs 63/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8976834623437179, val_loss: 1.0946287318279868
epochs 64/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9019717649409645, val_loss: 1.0207486365970813
epochs 65/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9394801604120355, val_loss: 1.09837992818732
epochs 66/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9118584545035111, val_loss: 0.9860147865195024
epochs 67/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9196908586903623, val_loss: 1.022150545371206
epochs 68/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8982447824980083, val_loss: 1.090931130710401
epochs 69/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9189838610197368, val_loss: 0.9797714264769303
epochs 70/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9352094738106979, val_loss: 1.0025420778676084
epochs 71/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8928414018530595, val_loss: 1.1018951955594514
epochs 72/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9240363685708297, val_loss: 0.9943224310874939
epochs 73/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9257358883556567, val_loss: 1.034588364550942
epochs 74/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8968028476363734, val_loss: 1.1108226399672658
epochs 75/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8907152778223941, val_loss: 1.0276001829850046
epochs 76/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9207141700543855, val_loss: 1.1146129771282798
epochs 77/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9140121052139684, val_loss: 1.0190561332200703
epochs 78/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9160426290411698, val_loss: 1.0468262371264005
epochs 79/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8919450621855887, val_loss: 1.024087737735949
epochs 80/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8905155959882234, val_loss: 1.0616525976281417
epochs 81/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9101300139176218, val_loss: 1.008402859537225
epochs 82/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8887679815292359, val_loss: 1.0639695945538972
epochs 83/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9037480831146241, val_loss: 1.0231585075980738
epochs 84/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9181896297555221, val_loss: 1.073552982430709
epochs 85/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8977043377725702, val_loss: 1.019040164194609
epochs 86/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9062354953665482, val_loss: 1.0549291874233044
epochs 87/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9012746472107737, val_loss: 1.0198641199814646
Starting fold 2:
epochs 1/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.992697086459712, val_loss: 1.0895794303793656
epochs 2/87
Current Learning Rate: 0.017106179096075008
train_loss: 1.0276570238565144, val_loss: 1.0960964955781636
epochs 3/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9563116293204458, val_loss: 1.0880150569112677
epochs 4/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9465723828265541, val_loss: 1.088572382926941
epochs 5/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9363743800865977, val_loss: 1.0835239473142122
epochs 6/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9494457301340605, val_loss: 1.0889159227672376
epochs 7/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9360665013915614, val_loss: 1.085696950711702
epochs 8/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.949143309969651, val_loss: 1.0809187939292506
epochs 9/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9484373927116394, val_loss: 1.087573554641322
epochs 10/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9264628736596359, val_loss: 1.076292189798857
epochs 11/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9274251824931095, val_loss: 1.099344980089288
epochs 12/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9395184109085485, val_loss: 1.0935311518217388
epochs 13/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9445936579453318, val_loss: 1.0845275690681055
epochs 14/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9552294693495098, val_loss: 1.0858581292001825
epochs 15/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9436263096959967, val_loss: 1.0684463425686486
epochs 16/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9244414599318254, val_loss: 1.079779412871913
epochs 17/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9184679175678052, val_loss: 1.0829225678192942
epochs 18/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.950094597590597, val_loss: 1.0834714287205747
epochs 19/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9609153866767883, val_loss: 1.1019393243287738
epochs 20/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9357079612581354, val_loss: 1.098844329934371
epochs 21/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.926633558147832, val_loss: 1.0903765741147493
epochs 22/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9363522987616689, val_loss: 1.1236579669149298
epochs 23/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9149337523861936, val_loss: 1.0679963613811292
epochs 24/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9126894398739464, val_loss: 1.108208811910529
epochs 25/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9148555159568786, val_loss: 1.165448478648537
epochs 26/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9153803122671027, val_loss: 1.0599984520360044
epochs 27/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9155711751235159, val_loss: 1.1881552206842523
epochs 28/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9279028654098511, val_loss: 1.0860965992275038
epochs 29/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9510418427617926, val_loss: 1.0846262555373343
epochs 30/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9391900150399459, val_loss: 1.1344263628909463
epochs 31/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9349538702713815, val_loss: 1.040055933751558
epochs 32/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9288689393746226, val_loss: 1.1303423542725413
epochs 33/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9130405482492949, val_loss: 1.131277464565478
epochs 34/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9200836589461878, val_loss: 1.1288240633512798
epochs 35/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9033621330010263, val_loss: 1.0831812808388157
epochs 36/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9132065522043329, val_loss: 1.1243192434310914
epochs 37/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9025590457414326, val_loss: 1.0692261106089542
epochs 38/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.912914776802063, val_loss: 1.0971941119746158
epochs 39/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9337529508691085, val_loss: 1.1149439435256154
epochs 40/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9337640266669424, val_loss: 1.081861969044334
epochs 41/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9054875813032451, val_loss: 1.0981741265246743
epochs 42/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9043434318743254, val_loss: 1.134668210933083
epochs 43/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9014786199519509, val_loss: 1.0944085309379978
epochs 44/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8841833892621492, val_loss: 1.1273829660917583
epochs 45/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9061575506862841, val_loss: 1.1325243021312512
epochs 46/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9071017001804552, val_loss: 1.1293403713326706
epochs 47/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.921223280931774, val_loss: 1.1367583400324772
epochs 48/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9014495837061028, val_loss: 1.05932818964908
epochs 49/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9112829384050871, val_loss: 1.2270840117805883
epochs 50/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8899533478837264, val_loss: 1.0619665672904566
epochs 51/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.95513663793865, val_loss: 1.0748740798548648
epochs 52/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.933956596098448, val_loss: 1.0780296049619975
epochs 53/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9326204017588967, val_loss: 1.070925992413571
epochs 54/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9268897828302886, val_loss: 1.0829239017085026
epochs 55/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9394835447010241, val_loss: 1.0704419136047363
epochs 56/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9492796628098739, val_loss: 1.0718522059290032
epochs 57/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.938168624200319, val_loss: 1.0829256973768535
epochs 58/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9422451483575921, val_loss: 1.0790091865941098
epochs 59/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9307909689451519, val_loss: 1.0819754274267899
epochs 60/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9174512831788314, val_loss: 1.063547931219402
epochs 61/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9305841213778445, val_loss: 1.073818574453655
epochs 62/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9541363076159829, val_loss: 1.0608579886587042
epochs 63/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9267422180426749, val_loss: 1.0697821755158274
epochs 64/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9147939581620066, val_loss: 1.068307584210446
epochs 65/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9116440879671197, val_loss: 1.0796527887645522
epochs 66/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9127390892882096, val_loss: 1.0833141540226183
epochs 67/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9245848235331083, val_loss: 1.0940946629172876
epochs 68/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9135503285809567, val_loss: 1.0777244730999596
epochs 69/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9310229420661926, val_loss: 1.1171692145498175
epochs 70/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9290345944856343, val_loss: 1.13683340549469
epochs 71/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9749724319106654, val_loss: 1.060321509210687
epochs 72/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9732627172219126, val_loss: 1.062272864893863
epochs 73/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9410627001210263, val_loss: 1.0627404664692126
epochs 74/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9366164477247941, val_loss: 1.054407891474272
epochs 75/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9190194845199585, val_loss: 1.0670434073397987
epochs 76/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9121162878839593, val_loss: 1.0639778563850804
epochs 77/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9141208755342584, val_loss: 1.0732058161183406
epochs 78/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8992030055899369, val_loss: 1.077389100978249
epochs 79/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.9049738620456896, val_loss: 1.0818093299865723
epochs 80/87
Current Learning Rate: 0.017106179096075008
train_loss: 0.8998886886395906, val_loss: 1.0860515004710147
epochs 81/87
Current Learning Rate: 0.017106179096075008

[I 2024-01-27 01:10:55,774] Trial 2 finished with value: 1.1129458687035734 and parameters: {'batch_size': 36, 'epochs': 87, 'hidden_size': 26, 'learning_rate': 0.017106179096075008, 'dropout_prob': 0.1706791100178261, 'weight_decay': 0.00036513036178804925, 'lr_step_size': 79, 'gamma': 0.26090384521882026, 'conv_channels': 55, 'kernel_size': 4, 'num_layers': 1, 'pool_size': 2, 'stride': 4}. Best is trial 0 with value: 1.0732808287764153.

Current Learning Rate: 0.017106179096075008
train_loss: 1.0264940367246929, val_loss: 1.1460296141473871
epochs 87/87
Current Learning Rate: 0.017106179096075008
train_loss: 1.0159285201524433, val_loss: 1.1801916047146446
Mean validation loss: 1.1129458687035734
Starting fold 1:
epochs 1/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.1048674840676158, val_loss: 1.013628839505346
epochs 2/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0277750385435005, val_loss: 1.00614408348736
epochs 3/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0217549920082092, val_loss: 0.9957760908101735
epochs 4/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0068230443879178, val_loss: 0.9920539338337747
epochs 5/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.005506112387306, val_loss: 0.9929110586643219
epochs 6/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0104857184384999, val_loss: 0.9949558662740807
epochs 7/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0049978027218267, val_loss: 0.9961588774856768
epochs 8/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0046237230300903, val_loss: 0.9960193376792105
epochs 9/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.006125415626325, val_loss: 0.995640732740101
epochs 10/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.003747281589006, val_loss: 0.995151088112279
epochs 11/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0013712346553802, val_loss: 0.9943195465363954
epochs 12/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0030118801091847, val_loss: 0.9937990066252257
epochs 13/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0027966769118057, val_loss: 0.9939865824423338
epochs 14/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0068718850612641, val_loss: 0.9942856230233845
epochs 15/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.001605541768827, val_loss: 0.9943102996600302
epochs 16/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.002544308022449, val_loss: 0.9940176257961675
epochs 17/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0028496877143258, val_loss: 0.9937451086546245
epochs 18/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0066870748996735, val_loss: 0.9934311684809233
epochs 19/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0003906093145671, val_loss: 0.9931615167542508
epochs 20/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0024561452238183, val_loss: 0.99292105687292
epochs 21/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0011950314044953, val_loss: 0.9930761487860429
epochs 22/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0013311844123036, val_loss: 0.9929888179427699
epochs 23/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0001190216917741, val_loss: 0.9929742273531462
epochs 24/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0021342224196383, val_loss: 0.9931549574199475
epochs 25/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0019579507802663, val_loss: 0.9933728324739557
epochs 26/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9999854796811154, val_loss: 0.9935682616735759
epochs 27/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0033898604543585, val_loss: 0.9938485142431761
epochs 28/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0026329928322841, val_loss: 0.9935771179826636
epochs 29/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0036216707606065, val_loss: 0.9935709463922601
epochs 30/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0017204915222369, val_loss: 0.9938316392271143
epochs 31/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0023683962069059, val_loss: 0.9939943134784699
epochs 32/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.001068410434221, val_loss: 0.993894048113572
epochs 33/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0003205936206014, val_loss: 0.9935483402327487
epochs 34/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.999983380029076, val_loss: 0.9930990981428247
epochs 35/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0005525855641617, val_loss: 0.9926957858236213
epochs 36/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0026599586009979, val_loss: 0.9923970727544081
epochs 37/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0008230554430109, val_loss: 0.9924963546426673
epochs 38/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.002244716568997, val_loss: 0.9927056146295448
epochs 39/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0036702494872243, val_loss: 0.9931138590762489
epochs 40/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0017445165860026, val_loss: 0.9934506789634102
epochs 41/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0007247168766824, val_loss: 0.9933948971723255
epochs 42/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9992687015156997, val_loss: 0.9930082110982192
epochs 43/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.001901615607111, val_loss: 0.9928074134023566
epochs 44/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0024290037782568, val_loss: 0.9929537628826343
epochs 45/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0005581338154643, val_loss: 0.9931176957331206
epochs 46/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0002784371376037, val_loss: 0.9931659886711522
epochs 47/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0000853089909805, val_loss: 0.9930603457124609
epochs 48/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9998563324150286, val_loss: 0.992965769140344
epochs 49/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.998445790378671, val_loss: 0.9929492922205674
epochs 50/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0016367394673198, val_loss: 0.9928430475686726
epochs 51/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9992359964471115, val_loss: 0.9927071709381906
epochs 52/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0002550570588362, val_loss: 0.9924350478147206
epochs 53/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.000566933343285, val_loss: 0.9923424978005259
epochs 54/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0023890049834001, val_loss: 0.9924590549970927
epochs 55/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.000982205491317, val_loss: 0.9926584604539369
epochs 56/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.003453867059005, val_loss: 0.9928930524148439
epochs 57/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0012040953887136, val_loss: 0.9931544984641828
epochs 58/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9995500495559291, val_loss: 0.9933792133080331
epochs 59/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.998842759195127, val_loss: 0.9934016199488389
epochs 60/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9999150985165646, val_loss: 0.9933729887008667
epochs 61/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9988497426635341, val_loss: 0.993262159196954
epochs 62/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9977436884453422, val_loss: 0.9929720420586435
epochs 63/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9991733616904208, val_loss: 0.9929888198250219
epochs 64/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0008259654045104, val_loss: 0.9930823191216117
epochs 65/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.001231305536471, val_loss: 0.9932124385708256
epochs 66/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.998623755417372, val_loss: 0.9931155869835302
epochs 67/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9999666044586584, val_loss: 0.9930073747509405
epochs 68/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0003025657252262, val_loss: 0.9931453409947847
epochs 69/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9991400326553144, val_loss: 0.9931987975773059
epochs 70/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0013168658080853, val_loss: 0.993217009305954
epochs 71/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9994116707852012, val_loss: 0.9932093093269749
epochs 72/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.000017010224493, val_loss: 0.993191630275626
epochs 73/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9993340250692869, val_loss: 0.9932112875737642
epochs 74/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0002119873699389, val_loss: 0.9933383536966224
epochs 75/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9982054766855741, val_loss: 0.9934100543197832
epochs 76/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9984475665970852, val_loss: 0.9934536529214759
epochs 77/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.0009733516918986, val_loss: 0.9934186957384411
epochs 78/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9975077905152974, val_loss: 0.9933017683656592
epochs 79/143
Epoch 00079: reducing learning rate of group 0 to 7.8059e-03.
Current Learning Rate: 0.007805948309524339
train_loss: 1.000698711370167, val_loss: 0.9932269930839539
epochs 80/143
Current Learning Rate: 0.007805948309524339
train_loss: 1.0007978357766805, val_loss: 0.9932516069788682
epochs 81/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9987203074129004, val_loss: 0.993182320030112
epochs 82/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9997645202435945, val_loss: 0.9931245725405844
epochs 83/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.998451806055872, val_loss: 0.9930545700223823
epochs 84/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9998942277933421, val_loss: 0.9929573608072181
epochs 85/143
Current Learning Rate: 0.007805948309524339
train_loss: 1.0001731769034736, val_loss: 0.9928584374879535
epochs 86/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9991444662997597, val_loss: 0.9927180192972485
epochs 87/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9999100167500345, val_loss: 0.9925934866855018
epochs 88/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9977708399295807, val_loss: 0.9924355566501617
epochs 89/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9987685027875398, val_loss: 0.992305265288604
epochs 90/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9982183393679167, val_loss: 0.9922452631749605
epochs 91/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9984583434305693, val_loss: 0.992344342721136
epochs 92/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9981463259772251, val_loss: 0.9924566400678534
epochs 93/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9988695185435446, val_loss: 0.992480628741415
epochs 94/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9989928185939789, val_loss: 0.9924634927197507
epochs 95/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9993071932541696, val_loss: 0.992536891761579
epochs 96/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9997948028539356, val_loss: 0.9926193406707362
epochs 97/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9983821354414287, val_loss: 0.9926882154063175
epochs 98/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9978839541736402, val_loss: 0.9926907671125311
epochs 99/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.99864226611037, val_loss: 0.99259136193677
epochs 100/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.999565610446428, val_loss: 0.9925873954045145
epochs 101/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9991630962020472, val_loss: 0.9926305651664734
epochs 102/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9993925910247, val_loss: 0.9927277994783301
epochs 103/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.999225338822917, val_loss: 0.9927849443335283
epochs 104/143
Current Learning Rate: 0.007805948309524339
train_loss: 1.0003454719719134, val_loss: 0.9927027815266659
epochs 105/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9992955794459895, val_loss: 0.9926899298241264
epochs 106/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9970758729859402, val_loss: 0.992686516046524
epochs 107/143
Current Learning Rate: 0.007805948309524339
train_loss: 1.000999067645324, val_loss: 0.9926231572502537
epochs 108/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9995472465690813, val_loss: 0.992594713913767
epochs 109/143
Current Learning Rate: 0.007805948309524339
train_loss: 1.0005115807056426, val_loss: 0.992677366733551
epochs 110/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9984639654034062, val_loss: 0.9927040843587173
epochs 111/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9984174088427895, val_loss: 0.9926051908417752
epochs 112/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9981209365945113, val_loss: 0.9926331783595838
epochs 113/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9989536941051483, val_loss: 0.992627720770083
epochs 114/143
Current Learning Rate: 0.007805948309524339
train_loss: 1.0001805158037889, val_loss: 0.9926424327649568
epochs 115/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9978446022460336, val_loss: 0.9926421033708672
epochs 116/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.998537436284517, val_loss: 0.9925824723745648
epochs 117/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9991023816560444, val_loss: 0.9925451557887228
epochs 118/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9983140976805436, val_loss: 0.9926081729562659
epochs 119/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9989858341844459, val_loss: 0.99276009547083
epochs 120/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9989754058812794, val_loss: 0.9928672843857815
epochs 121/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9971297706428327, val_loss: 0.9929019469963877
epochs 122/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9992817260717091, val_loss: 0.9928639280168634
epochs 123/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9981891964611255, val_loss: 0.9927039174657118
epochs 124/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9986399572146566, val_loss: 0.9925592855403298
epochs 125/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9985303279600646, val_loss: 0.9925100135175805
epochs 126/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9972922839616475, val_loss: 0.9924942101302899
epochs 127/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9978228863916899, val_loss: 0.9924103015347531
epochs 128/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9992288153422506, val_loss: 0.9923358471770035
epochs 129/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9989363011560942, val_loss: 0.9923071180519305
epochs 130/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9979811925637094, val_loss: 0.992261338861365
epochs 131/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9991964415500039, val_loss: 0.9922826459533289
epochs 132/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9991241235482066, val_loss: 0.9923138405147351
epochs 133/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9979482268032275, val_loss: 0.9922876539983247
epochs 134/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9976579336743606, val_loss: 0.992266636459451
epochs 135/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9997928164507214, val_loss: 0.9923046871235496
epochs 136/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9991056238350116, val_loss: 0.9923913256118172
epochs 137/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9988784881014573, val_loss: 0.9924427540678727
epochs 138/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9978443067324789, val_loss: 0.9923934999265169
epochs 139/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9986105140886808, val_loss: 0.9923572841443513
epochs 140/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9981351871239511, val_loss: 0.9923524338948099
epochs 141/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9983531732308237, val_loss: 0.9923425558366273
epochs 142/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9994882709101627, val_loss: 0.992406734039909
epochs 143/143
Current Learning Rate: 0.007805948309524339
train_loss: 0.9989339903781288, val_loss: 0.9925139295427423
Starting fold 2:
epochs 1/143
Current Learning Rate: 0.009721590243181704
train_loss: 1.004529257667692, val_loss: 1.11420747575007
epochs 2/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9952327436522433, val_loss: 1.1113245923268167
epochs 3/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9944078468962719, val_loss: 1.1110876986854954
epochs 4/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.993949901273376, val_loss: 1.1130790804561816
epochs 5/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9942243477231578, val_loss: 1.1144942816935088
epochs 6/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9929938753968791, val_loss: 1.1142194020120721
epochs 7/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9935489497686687, val_loss: 1.113604400973571
epochs 8/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.992615783685132, val_loss: 1.1137104238334454
epochs 9/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9931263313481682, val_loss: 1.113903952899732
epochs 10/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9929651583495893, val_loss: 1.1144086960114932
epochs 11/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9928652482597451, val_loss: 1.1148961795003791
epochs 12/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9928807768382524, val_loss: 1.1151260275589792
epochs 13/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9922982306856858, val_loss: 1.1148275620058963
epochs 14/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.992744339610401, val_loss: 1.114557692565416
epochs 15/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9925129303806707, val_loss: 1.1146296466651715
epochs 16/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9926482231993424, val_loss: 1.1145024597644806
epochs 17/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9926539764592522, val_loss: 1.1144410977238104
epochs 18/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9924106798673931, val_loss: 1.1143627107143401
epochs 19/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9922653869578713, val_loss: 1.1150980538443516
epochs 20/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9927331682882811, val_loss: 1.1152090339284195
epochs 21/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.992727948960505, val_loss: 1.1151619409259996
epochs 22/143
Current Learning Rate: 0.009721590243181704
train_loss: 0.9924581791225232, val_loss: 1.115581356224261
epochs 23/143

[I 2024-01-27 01:11:23,719] Trial 3 pruned.

Current Learning Rate: 0.007805948309524339
train_loss: 0.9927646296588998, val_loss: 1.1159771712202775
epochs 129/143
Starting fold 1:
epochs 1/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.948025601788571, val_loss: 1.1627218183718229
epochs 2/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.129148913057227, val_loss: 1.0836945652961731
epochs 3/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.1438227280190116, val_loss: 1.3593946281232332
epochs 4/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.3557468282549006, val_loss: 0.9806940643410934
epochs 5/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0754119537378612, val_loss: 1.0196493522117012
epochs 6/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.1522616803646089, val_loss: 1.0909989087205185
epochs 7/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.1012389374406715, val_loss: 0.990169453307202
epochs 8/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0266800927488426, val_loss: 0.9900210804060886
epochs 9/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.015165605984236, val_loss: 0.9932378505405627
epochs 10/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0123283781503376, val_loss: 0.9964848314460956
epochs 11/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0027341193274448, val_loss: 0.9948631973643052
epochs 12/124
Current Learning Rate: 0.025489247406774756
train_loss: 0.9976870150942552, val_loss: 0.9910428699694181
epochs 13/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.011339729710629, val_loss: 0.993598335981369
epochs 14/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0116501321918085, val_loss: 0.9926449593744779
epochs 15/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0082725233153293, val_loss: 0.9954325848504116
epochs 16/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0022805468032234, val_loss: 0.993871567751232
epochs 17/124
Epoch 00017: reducing learning rate of group 0 to 1.8942e-02.
Current Learning Rate: 0.01894158020340023
train_loss: 1.0155170434399654, val_loss: 0.9924792339927272
epochs 18/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0030234851335225, val_loss: 0.992237863415166
epochs 19/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0006282238583817, val_loss: 0.9937708829578601
epochs 20/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0073197891837673, val_loss: 0.9940500042940441
epochs 21/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.008178887241765, val_loss: 0.9932865265168642
epochs 22/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.004517585666556, val_loss: 0.9923959468540392
epochs 23/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0068753976570932, val_loss: 0.9935388521144265
epochs 24/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0085686806001162, val_loss: 0.9934791960214314
epochs 25/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0027117148825997, val_loss: 0.9933054174247541
epochs 26/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0047205441876461, val_loss: 0.9922387236043027
epochs 27/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0051141710657823, val_loss: 0.9906721893109773
epochs 28/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.006769146103608, val_loss: 0.9908177623623295
epochs 29/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0089310501751148, val_loss: 0.991673418408946
epochs 30/124
Epoch 00030: reducing learning rate of group 0 to 1.4076e-02.
Current Learning Rate: 0.01407587501020069
train_loss: 1.0003976329376822, val_loss: 0.9922651683029375
epochs 31/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.0005812218314722, val_loss: 0.9939396481764944
epochs 32/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.006437639813674, val_loss: 0.9934586832397863
epochs 33/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.0045035158333024, val_loss: 0.9928316536702608
epochs 34/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.0034790995873903, val_loss: 0.9920981727148357
epochs 35/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.0074128461511511, val_loss: 0.9942438621270029
epochs 36/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.0065026132684005, val_loss: 0.9931462827481722
epochs 37/124
Current Learning Rate: 0.01407587501020069
train_loss: 0.9966386437416077, val_loss: 0.9919416863667337
epochs 38/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.0050926424955067, val_loss: 0.9923815736645146
epochs 39/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.0004236735795673, val_loss: 0.9917457749969081
epochs 40/124
Current Learning Rate: 0.01407587501020069
train_loss: 0.9994551125325655, val_loss: 0.991824133772599
epochs 41/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.005114508616297, val_loss: 0.9932534205286127
epochs 42/124
Current Learning Rate: 0.01407587501020069
train_loss: 1.0032769488660913, val_loss: 0.991992659004111
epochs 43/124
Epoch 00043: reducing learning rate of group 0 to 1.0460e-02.
Current Learning Rate: 0.010460070130116475
train_loss: 1.0070503250548715, val_loss: 0.9928456002160122
epochs 44/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.0014644381247069, val_loss: 0.9938338703230808
epochs 45/124
Current Learning Rate: 0.010460070130116475
train_loss: 0.9990731559301678, val_loss: 0.9915412611082981
epochs 46/124
Current Learning Rate: 0.010460070130116475
train_loss: 0.9998756945133209, val_loss: 0.9919302918409046
epochs 47/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.0029569525467723, val_loss: 0.9921059837466792
epochs 48/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.0045858718846974, val_loss: 0.992695455174697
epochs 49/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.0072186673942365, val_loss: 0.9928168306225225
epochs 50/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.0043071837801683, val_loss: 0.9936476324733935
epochs 51/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.0028760031649941, val_loss: 0.9933992144308592
epochs 52/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.0017960786819458, val_loss: 0.9930047019531852
epochs 53/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.0031857644256792, val_loss: 0.9920192323232951
epochs 54/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.0050694120557684, val_loss: 0.9925080782488773
epochs 55/124
Current Learning Rate: 0.010460070130116475
train_loss: 1.00227922107044, val_loss: 0.9938820544042085
epochs 56/124
Epoch 00056: reducing learning rate of group 0 to 7.7731e-03.
Current Learning Rate: 0.007773091693956076
train_loss: 1.0070728418074155, val_loss: 0.993084265370118
epochs 57/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.0010977425073322, val_loss: 0.9932432852293316
epochs 58/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.0018944846956352, val_loss: 0.9929416201616589
epochs 59/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.0060269528313688, val_loss: 0.992308962658832
epochs 60/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.00342532051237, val_loss: 0.992119501452697
epochs 61/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.000757707733857, val_loss: 0.9917119942213359
epochs 62/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.0042321961177023, val_loss: 0.992620281169289
epochs 63/124
Current Learning Rate: 0.007773091693956076
train_loss: 0.9981885715534813, val_loss: 0.9923686783564718
epochs 64/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.0016877958649084, val_loss: 0.9924793610447331
epochs 65/124
Current Learning Rate: 0.007773091693956076
train_loss: 0.9996087193489075, val_loss: 0.9932634190509194
epochs 66/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.004500687122345, val_loss: 0.9929793740573682
epochs 67/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.0058398180886319, val_loss: 0.9923878277602949
epochs 68/124
Current Learning Rate: 0.007773091693956076
train_loss: 1.004499454247324, val_loss: 0.9923391125704113
epochs 69/124
Epoch 00069: reducing learning rate of group 0 to 5.7763e-03.
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0020390830541912, val_loss: 0.993549792076412
epochs 70/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0063116459470047, val_loss: 0.9940779281289954
epochs 71/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0002901811348766, val_loss: 0.9934415908236253
epochs 72/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0056380237403668, val_loss: 0.9940408957631964
epochs 73/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0084981272095128, val_loss: 0.9938937751870406
epochs 74/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0028812584124114, val_loss: 0.9931982297646372
epochs 75/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0038264353024333, val_loss: 0.9935778272779364
epochs 76/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0027136579940195, val_loss: 0.9932059636241511
epochs 77/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.007188109975112, val_loss: 0.9932530101976896
epochs 78/124
Current Learning Rate: 0.0057763431536358295
train_loss: 0.9989155973258771, val_loss: 0.993027200824336
epochs 79/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0009530362329986, val_loss: 0.9926908596565849
epochs 80/124
Current Learning Rate: 0.0057763431536358295
train_loss: 0.9995840056946403, val_loss: 0.9919240496660534
epochs 81/124
Current Learning Rate: 0.0057763431536358295
train_loss: 1.0001169882322614, val_loss: 0.9921405876937666
epochs 82/124
Epoch 00082: reducing learning rate of group 0 to 4.2925e-03.
Current Learning Rate: 0.004292518542460933
train_loss: 1.0019838718991532, val_loss: 0.993182098865509
epochs 83/124
Current Learning Rate: 0.004292518542460933
train_loss: 1.001898829246822, val_loss: 0.9937959053014455
epochs 84/124
Current Learning Rate: 0.004292518542460933
train_loss: 1.0000950311359607, val_loss: 0.9944255217125542
epochs 85/124
Current Learning Rate: 0.004292518542460933
train_loss: 1.0015349657912003, val_loss: 0.9941325507665936
epochs 86/124
Current Learning Rate: 0.004292518542460933
train_loss: 0.9949122447716562, val_loss: 0.9926875776366184
epochs 87/124
Current Learning Rate: 0.004292518542460933
train_loss: 1.0050094039816606, val_loss: 0.9923543334007263
epochs 88/124
Current Learning Rate: 0.004292518542460933
train_loss: 1.001197462332876, val_loss: 0.9934298185925735
epochs 89/124
Current Learning Rate: 0.004292518542460933
train_loss: 0.997624849645715, val_loss: 0.993634160255131
epochs 90/124
Current Learning Rate: 0.004292518542460933
train_loss: 0.9963883346632907, val_loss: 0.9931578476178019
epochs 91/124
Current Learning Rate: 0.004292518542460933
train_loss: 1.0016342969317185, val_loss: 0.9920363178378657
epochs 92/124
Current Learning Rate: 0.004292518542460933
train_loss: 1.0027786593688162, val_loss: 0.99221231341362
epochs 93/124
Current Learning Rate: 0.004292518542460933
train_loss: 1.0008262160577273, val_loss: 0.9934517248680718
epochs 94/124
Current Learning Rate: 0.004292518542460933
train_loss: 0.9990369784204584, val_loss: 0.9936248895369078
epochs 95/124
Epoch 00095: reducing learning rate of group 0 to 3.1899e-03.
Current Learning Rate: 0.0031898581762361457
train_loss: 1.0001781532638951, val_loss: 0.9934967147676568
epochs 96/124
Current Learning Rate: 0.0031898581762361457
train_loss: 0.9997901631029029, val_loss: 0.9935366053330271
epochs 97/124
Current Learning Rate: 0.0031898581762361457
train_loss: 0.9968703072322043, val_loss: 0.9935971263207888
epochs 98/124
Current Learning Rate: 0.0031898581762361457
train_loss: 1.001154184027722, val_loss: 0.9940268748684933
epochs 99/124
Current Learning Rate: 0.0031898581762361457
train_loss: 1.0006311134288186, val_loss: 0.9943152766478689
epochs 100/124
Current Learning Rate: 0.0031898581762361457
train_loss: 0.995243964069768, val_loss: 0.993504926405455
epochs 101/124
Current Learning Rate: 0.0031898581762361457
train_loss: 1.0009663672823654, val_loss: 0.9930046420348319
epochs 102/124
Current Learning Rate: 0.0031898581762361457
train_loss: 1.0008167138225155, val_loss: 0.9928103870467135
epochs 103/124
Current Learning Rate: 0.0031898581762361457
train_loss: 1.0036822736263276, val_loss: 0.9927335221516459
epochs 104/124
Current Learning Rate: 0.0031898581762361457
train_loss: 1.0011575974916156, val_loss: 0.9931212833053187
epochs 105/124
Current Learning Rate: 0.0031898581762361457
train_loss: 0.9993429243564605, val_loss: 0.9934176721070942
epochs 106/124
Current Learning Rate: 0.0031898581762361457
train_loss: 0.9985921580540507, val_loss: 0.9935762496371018
epochs 107/124
Current Learning Rate: 0.0031898581762361457
train_loss: 1.0019216913925975, val_loss: 0.9936467995769099
epochs 108/124
Epoch 00108: reducing learning rate of group 0 to 2.3704e-03.
Current Learning Rate: 0.002370448743284187
train_loss: 1.0018230303337698, val_loss: 0.993688995900907
epochs 109/124
Current Learning Rate: 0.002370448743284187
train_loss: 0.9982266118651942, val_loss: 0.993497803022987
epochs 110/124
Current Learning Rate: 0.002370448743284187
train_loss: 1.0001633753902033, val_loss: 0.9934875343975268
epochs 111/124
Current Learning Rate: 0.002370448743284187
train_loss: 0.9966138400529561, val_loss: 0.9933695385330602
epochs 112/124
Current Learning Rate: 0.002370448743284187
train_loss: 1.0021836142790945, val_loss: 0.9931032419204712
epochs 113/124
Current Learning Rate: 0.002370448743284187
train_loss: 0.9988744942765487, val_loss: 0.993048916364971
epochs 114/124
Current Learning Rate: 0.002370448743284187
train_loss: 1.0043233306784378, val_loss: 0.9931875972371352
epochs 115/124
Current Learning Rate: 0.002370448743284187
train_loss: 1.0007412640671982, val_loss: 0.9933127177389045
epochs 116/124
Current Learning Rate: 0.002370448743284187
train_loss: 0.9973013881005739, val_loss: 0.9933187977263802
epochs 117/124
Current Learning Rate: 0.002370448743284187
train_loss: 0.9987581300108056, val_loss: 0.9934764727165825
epochs 118/124
Current Learning Rate: 0.002370448743284187
train_loss: 0.9961908575735594, val_loss: 0.9936175286769867
epochs 119/124
Current Learning Rate: 0.002370448743284187
train_loss: 1.0036967660251417, val_loss: 0.9934711914313467
epochs 120/124
Current Learning Rate: 0.002370448743284187
train_loss: 0.9954078423349481, val_loss: 0.9931619145368275
epochs 121/124
Epoch 00121: reducing learning rate of group 0 to 1.7615e-03.
Current Learning Rate: 0.001761528862442317
train_loss: 1.0000738404299083, val_loss: 0.9932893966373645
epochs 122/124
Current Learning Rate: 0.001761528862442317
train_loss: 0.9990015374986749, val_loss: 0.993372832160247
epochs 123/124
Current Learning Rate: 0.001761528862442317
train_loss: 1.0001019132764717, val_loss: 0.9933139126551779
epochs 124/124
Current Learning Rate: 0.001761528862442317
train_loss: 0.99886726831135, val_loss: 0.9932476413877387
Starting fold 2:
epochs 1/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.1264360227082906, val_loss: 1.1682073618236342
epochs 2/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0146529421994561, val_loss: 1.094838939842425
epochs 3/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0097533883232819, val_loss: 1.1055574658669924
epochs 4/124
Current Learning Rate: 0.025489247406774756
train_loss: 0.9983699770350205, val_loss: 1.0961731590722736
epochs 5/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0049839231528734, val_loss: 1.099956876980631
epochs 6/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0024181609091005, val_loss: 1.1089604465585006
epochs 7/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0062638816080596, val_loss: 1.0993720186384102
epochs 8/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0046076349521937, val_loss: 1.0881681410889876
epochs 9/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0117127598900544, val_loss: 1.1129119982844904
epochs 10/124
Current Learning Rate: 0.025489247406774756
train_loss: 0.9992072572833613, val_loss: 1.097671390520899
epochs 11/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0147971786950765, val_loss: 1.1029933998459265
epochs 12/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0070987826899478, val_loss: 1.1016522253814496
epochs 13/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0220258039863486, val_loss: 1.1042294169727125
epochs 14/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0127375456847643, val_loss: 1.087987849900597
epochs 15/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0149528646155408, val_loss: 1.1061009259600387
epochs 16/124
Current Learning Rate: 0.025489247406774756
train_loss: 0.9996233358194954, val_loss: 1.112150377976267
epochs 17/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0067431664780566, val_loss: 1.1103607974554364
epochs 18/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0028228985635859, val_loss: 1.111217782685631
epochs 19/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0079740740750964, val_loss: 1.1046208315774013
epochs 20/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0064015353980817, val_loss: 1.1086698265452133
epochs 21/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0013070235126897, val_loss: 1.1081010827892706
epochs 22/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0036523240177255, val_loss: 1.1112253628279034
epochs 23/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0132692296254007, val_loss: 1.1075364210103686
epochs 24/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0035654654628352, val_loss: 1.10619774586276
epochs 25/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.0223690530187206, val_loss: 1.1057308325642035
epochs 26/124
Current Learning Rate: 0.025489247406774756
train_loss: 1.006963091931845, val_loss: 1.1079184968220561
epochs 27/124
Epoch 00027: reducing learning rate of group 0 to 1.8942e-02.
Current Learning Rate: 0.01894158020340023
train_loss: 1.011285990790317, val_loss: 1.1196511045882576
epochs 28/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0109122878626773, val_loss: 1.110441048208036
epochs 29/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0000775799939507, val_loss: 1.1059704893513729
epochs 30/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0000139369776375, val_loss: 1.1111403521738554
epochs 31/124
Current Learning Rate: 0.01894158020340023
train_loss: 0.9990054243489316, val_loss: 1.1099524513671273
epochs 32/124
Current Learning Rate: 0.01894158020340023
train_loss: 0.9994860100118738, val_loss: 1.1102336168289184
epochs 33/124
Current Learning Rate: 0.01894158020340023
train_loss: 0.9957895390297237, val_loss: 1.115205871431451
epochs 34/124
Current Learning Rate: 0.01894158020340023
train_loss: 0.9980616625986601, val_loss: 1.1058225019981986
epochs 35/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0029741280957272, val_loss: 1.108354041450902
epochs 36/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.000691314276896, val_loss: 1.112223590047736
epochs 37/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.008726027764772, val_loss: 1.1024694251386742
epochs 38/124
Current Learning Rate: 0.01894158020340023
train_loss: 1.0041457706376127, val_loss: 1.1118407854908392
epochs 39/124

[I 2024-01-27 01:11:53,968] Trial 4 pruned.

Starting fold 1:
epochs 1/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.093770943189922, val_loss: 1.0915018571050543
epochs 2/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.089900951636465, val_loss: 1.0869009494781494
epochs 3/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0834796616905613, val_loss: 1.0823435908869694
epochs 4/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0815422346717434, val_loss: 1.0776911848469783
epochs 5/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0761561330996061, val_loss: 1.0729156858042668
epochs 6/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0727686944760775, val_loss: 1.0680006052318372
epochs 7/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0669167669195878, val_loss: 1.0628696868294163
epochs 8/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0623161353563007, val_loss: 1.0574215901525397
epochs 9/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0577964343522723, val_loss: 1.0516761855075234
epochs 10/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0511862416016429, val_loss: 1.0455576557862132
epochs 11/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.044938520381325, val_loss: 1.0389890231584247
epochs 12/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0419288936414217, val_loss: 1.0323338508605957
epochs 13/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0354095697402954, val_loss: 1.0255549581427323
epochs 14/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.030753681534215, val_loss: 1.0187437157881887
epochs 15/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0237833010522943, val_loss: 1.0122450088199817
epochs 16/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0160037530095953, val_loss: 1.0062913706428127
epochs 17/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0080925979112323, val_loss: 1.0011782081503617
epochs 18/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0128427241977893, val_loss: 0.9973376550172505
epochs 19/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.003723326482271, val_loss: 0.9949380912278828
epochs 20/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0013941620525562, val_loss: 0.9935073099638286
epochs 21/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9976062962883397, val_loss: 0.9927361701664171
epochs 22/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.998316764831543, val_loss: 0.9923922764627557
epochs 23/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0010088180240833, val_loss: 0.9923417317239862
epochs 24/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0024721496983577, val_loss: 0.9923276336569535
epochs 25/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9999295598582217, val_loss: 0.9922396572012651
epochs 26/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0003833896235417, val_loss: 0.9921287674652902
epochs 27/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.001358992175052, val_loss: 0.9920532326949271
epochs 28/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0019113390069259, val_loss: 0.9921016755856966
epochs 29/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0005911023993241, val_loss: 0.9921732764495047
epochs 30/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9982305702410246, val_loss: 0.9921478284032721
epochs 31/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9986712493394551, val_loss: 0.9921395151238692
epochs 32/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9997653521989521, val_loss: 0.9920877594696847
epochs 33/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0049875159012644, val_loss: 0.9920191074672499
epochs 34/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0012211862363314, val_loss: 0.9919831878260562
epochs 35/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9993950881456074, val_loss: 0.9919548222893163
epochs 36/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0001902329294305, val_loss: 0.9919691399524087
epochs 37/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.001778753180253, val_loss: 0.9919704324320743
epochs 38/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0032577891098826, val_loss: 0.9919094537433825
epochs 39/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.000866623301255, val_loss: 0.9918665572216636
epochs 40/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0001287209360223, val_loss: 0.9918020273509779
epochs 41/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9920435265490883, val_loss: 0.991740207923086
epochs 42/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9910161432467008, val_loss: 0.9917118988539043
epochs 43/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9971975903762015, val_loss: 0.991693703751815
epochs 44/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0010137746208592, val_loss: 0.9916905792135942
epochs 45/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0034542711157548, val_loss: 0.9917350693752891
epochs 46/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9961870093094675, val_loss: 0.9917847482781661
epochs 47/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9958998623647188, val_loss: 0.9917825648659154
epochs 48/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9966539019032529, val_loss: 0.9917618977396112
epochs 49/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0010920261081897, val_loss: 0.9917569034977963
epochs 50/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0011556587721173, val_loss: 0.9917824958500109
epochs 51/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.005106104047675, val_loss: 0.9918485628931146
epochs 52/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9928681473982962, val_loss: 0.9918314532229775
epochs 53/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9987144532956576, val_loss: 0.9918205173392045
epochs 54/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0020045920422203, val_loss: 0.9918181268792403
epochs 55/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9983853603664198, val_loss: 0.9918502255489952
epochs 56/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0026565037275617, val_loss: 0.9919393313558478
epochs 57/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0003431658995778, val_loss: 0.9920417321355719
epochs 58/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9991349734758076, val_loss: 0.9920634219520971
epochs 59/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.001346098749261, val_loss: 0.9921123855992368
epochs 60/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9922842101046914, val_loss: 0.9921724921778629
epochs 61/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9999094260366339, val_loss: 0.9922109716816953
epochs 62/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9983298778533936, val_loss: 0.9922601486507215
epochs 63/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9924123883247375, val_loss: 0.992348451363413
epochs 64/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0012742124105756, val_loss: 0.9924086583288092
epochs 65/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9975200891494751, val_loss: 0.9924085391195197
epochs 66/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0002988325922113, val_loss: 0.9923721363669947
epochs 67/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9982342469064813, val_loss: 0.9923087734925119
epochs 68/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.000110990122745, val_loss: 0.9922383898182919
epochs 69/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0078267674697072, val_loss: 0.9921979151274029
epochs 70/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.998546324278179, val_loss: 0.9921483742563348
epochs 71/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.999373755956951, val_loss: 0.9921076109534815
epochs 72/93
Current Learning Rate: 0.0003672863715860752
train_loss: 1.0042531302100735, val_loss: 0.9920704239293149
epochs 73/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9998396446830348, val_loss: 0.992034491739775
epochs 74/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9923257137599745, val_loss: 0.9919803644481459
epochs 75/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9988996386528015, val_loss: 0.9919705202704981
epochs 76/93
Epoch 00076: reducing learning rate of group 0 to 4.4258e-05.
Current Learning Rate: 4.425768453254355e-05
train_loss: 1.006549270529496, val_loss: 0.9919311561082539
epochs 77/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9978969410846108, val_loss: 0.9919248380159077
epochs 78/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 1.0006005952232762, val_loss: 0.9919194861462242
epochs 79/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9901620243725023, val_loss: 0.9919171772505108
epochs 80/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 1.0017344951629639, val_loss: 0.9919158910450182
epochs 81/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9964871406555176, val_loss: 0.9919174909591675
epochs 82/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9969748760524549, val_loss: 0.9919172462664152
epochs 83/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 1.0025418118426674, val_loss: 0.9919171019604331
epochs 84/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9962612829710308, val_loss: 0.9919177544744391
epochs 85/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9963058107777646, val_loss: 0.9919177670227853
epochs 86/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9999846972917256, val_loss: 0.9919205904006958
epochs 87/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9967934771587974, val_loss: 0.9919117500907496
epochs 88/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9988355887563605, val_loss: 0.9919021129608154
epochs 89/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9996709572641473, val_loss: 0.9918946968881708
epochs 90/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9969864456277144, val_loss: 0.9918864212538067
epochs 91/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9968617778075369, val_loss: 0.991874989710356
epochs 92/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9964832224343952, val_loss: 0.9918670089621293
epochs 93/93
Current Learning Rate: 4.425768453254355e-05
train_loss: 0.9983763757504915, val_loss: 0.9918559224982011
Starting fold 2:
epochs 1/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9976969173080042, val_loss: 1.1334540279288041
epochs 2/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9968102166527196, val_loss: 1.1294076756427163
epochs 3/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9918863647862485, val_loss: 1.1258838239469027
epochs 4/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.991975116102319, val_loss: 1.12426033145503
epochs 5/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9953844892351251, val_loss: 1.1232809894963314
epochs 6/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9891039823230944, val_loss: 1.1228782754195363
epochs 7/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9965773758135343, val_loss: 1.1222871918427317
epochs 8/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9867401436755532, val_loss: 1.1221486204548885
epochs 9/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9997155478126124, val_loss: 1.1210757744939703
epochs 10/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.993681926476328, val_loss: 1.1200355730558698
epochs 11/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9939976554167899, val_loss: 1.1196010928404958
epochs 12/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.995019395100443, val_loss: 1.119721061304996
epochs 13/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9942981412536219, val_loss: 1.119191245028847
epochs 14/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9896013548499659, val_loss: 1.1193558103159855
epochs 15/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9963405195035433, val_loss: 1.1188965220200389
epochs 16/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9955028797450819, val_loss: 1.1187889136766132
epochs 17/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9907163005126151, val_loss: 1.11919010940351
epochs 18/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9927597359607094, val_loss: 1.119775414466858
epochs 19/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9911719591994035, val_loss: 1.1201985196063393
epochs 20/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9957717908056158, val_loss: 1.119728169943157
epochs 21/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9891788237973264, val_loss: 1.119487630693536
epochs 22/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9928788134926244, val_loss: 1.1199910264266164
epochs 23/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9936926208044353, val_loss: 1.1198452020946301
epochs 24/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9956549970727218, val_loss: 1.1193388449518304
epochs 25/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9929996132850647, val_loss: 1.119141239868967
epochs 26/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9959122130745336, val_loss: 1.1189999705866764
epochs 27/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9917438281209845, val_loss: 1.1194373557442112
epochs 28/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9957947072229887, val_loss: 1.1193585207587795
epochs 29/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9939753789650766, val_loss: 1.1194310690227307
epochs 30/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9932045528763219, val_loss: 1.1193842699653225
epochs 31/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9934513129686054, val_loss: 1.1199936929501986
epochs 32/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9924554291524386, val_loss: 1.1199032946636802
epochs 33/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9908387880576285, val_loss: 1.1200682614978992
epochs 34/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9919076122735676, val_loss: 1.1202654085661237
epochs 35/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9936459817384419, val_loss: 1.1204761768642224
epochs 36/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9938101015592876, val_loss: 1.1200046225597984
epochs 37/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9912991994305661, val_loss: 1.1199513046365035
epochs 38/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9929031855181644, val_loss: 1.1194589702706588
epochs 39/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9932585986037004, val_loss: 1.1191491892463283
epochs 40/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9947250516791093, val_loss: 1.1192557748995329
epochs 41/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9948422218623915, val_loss: 1.1189158401991193
epochs 42/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9958655802827132, val_loss: 1.1180303284996433
epochs 43/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9910336607380917, val_loss: 1.1179246212306775
epochs 44/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.99334296427275, val_loss: 1.118779376933449
epochs 45/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9909934872075131, val_loss: 1.1195922839014154
epochs 46/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9904556901831376, val_loss: 1.1203524187991494
epochs 47/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9939361967538533, val_loss: 1.120318331216511
epochs 48/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.988280691598591, val_loss: 1.1208216328369944
epochs 49/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9936399773547524, val_loss: 1.120580415976675
epochs 50/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9954775195372733, val_loss: 1.1201698780059814
epochs 51/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.993985326666581, val_loss: 1.1196232281233136
epochs 52/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9900397407381158, val_loss: 1.1196023100300838
epochs 53/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9937238881462499, val_loss: 1.119780509095443
epochs 54/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9915083834999486, val_loss: 1.1196824312210083
epochs 55/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9941605235400953, val_loss: 1.1197857605783563
epochs 56/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9893396496772766, val_loss: 1.1200934334805137
epochs 57/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9966816996273241, val_loss: 1.1197185955549542
epochs 58/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9907052893387643, val_loss: 1.1198735111638118
epochs 59/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9945493246379652, val_loss: 1.119598256914239
epochs 60/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9943119977649889, val_loss: 1.1194215699246055
epochs 61/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9934276122795908, val_loss: 1.1192277920873541
epochs 62/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9961184169116774, val_loss: 1.119092395431117
epochs 63/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9944815478826824, val_loss: 1.1188200586720516
epochs 64/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9934927444708975, val_loss: 1.1188002009140818
epochs 65/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9942637462364999, val_loss: 1.1189293798647428
epochs 66/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9894880526944211, val_loss: 1.1195122254522223
epochs 67/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9972165822982788, val_loss: 1.1195690004449141
epochs 68/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9952235943392703, val_loss: 1.1193142062739323
epochs 69/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9940369035068312, val_loss: 1.119159083617361
epochs 70/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9928355467946905, val_loss: 1.119496828631351
epochs 71/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9928789358390006, val_loss: 1.1195670366287231
epochs 72/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9927684507871929, val_loss: 1.1196291132977134
epochs 73/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9920087927266171, val_loss: 1.1193351055446423
epochs 74/93
Current Learning Rate: 0.0003672863715860752
train_loss: 0.9930388707863657, val_loss: 1.1193420636026483
epochs 75/93
Epoch 00075: reducing learning rate of group 0 to 4.4258e-05.

[I 2024-01-27 01:12:14,686] Trial 5 pruned.

Starting fold 1:
epochs 1/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.1521954975630109, val_loss: 1.0015997071015208
epochs 2/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0508680657336587, val_loss: 0.9892074465751648
epochs 3/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0043305566436367, val_loss: 0.9927622362187034
epochs 4/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0037518237766467, val_loss: 0.9917609691619873
epochs 5/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0027149947066056, val_loss: 0.9915809850943716
epochs 6/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0100256926135014, val_loss: 0.9910037046984622
epochs 7/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.003945463582089, val_loss: 0.9902784761629606
epochs 8/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0009201921914752, val_loss: 0.9886790419879713
epochs 9/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9983573838284141, val_loss: 0.987705713824222
epochs 10/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0055378957798606, val_loss: 0.9871172371663546
epochs 11/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.001361115982658, val_loss: 0.9867675367154574
epochs 12/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0101665164294995, val_loss: 0.9879182043828463
epochs 13/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0034722372105247, val_loss: 0.989945672060314
epochs 14/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0061654950443066, val_loss: 0.9911654779785558
epochs 15/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.00092876898615, val_loss: 0.9916708155682212
epochs 16/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0023847912487232, val_loss: 0.9914302104397824
epochs 17/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9996741131732338, val_loss: 0.990709053842645
epochs 18/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0048406375081915, val_loss: 0.9896119958476016
epochs 19/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9948483956487555, val_loss: 0.9887322563874094
epochs 20/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0004267629824186, val_loss: 0.9881132809739364
epochs 21/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0039120661584955, val_loss: 0.9880839084324083
epochs 22/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0028835064486454, val_loss: 0.9880865310367785
epochs 23/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0034481726194684, val_loss: 0.9878252117257369
epochs 24/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0025428815891868, val_loss: 0.9878830376424288
epochs 25/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.999079682325062, val_loss: 0.9876251848120439
epochs 26/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0022219607704563, val_loss: 0.987980538292935
epochs 27/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9999395389305917, val_loss: 0.9882084037128248
epochs 28/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0017969325969094, val_loss: 0.9885320412485223
epochs 29/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0022235857812982, val_loss: 0.9891366393942582
epochs 30/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0004046998525922, val_loss: 0.9896329892309088
epochs 31/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9997559597617701, val_loss: 0.9899957838811373
epochs 32/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.000261742817728, val_loss: 0.9902132906411824
epochs 33/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9994566283727947, val_loss: 0.990011077178152
epochs 34/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9958244750374242, val_loss: 0.9895183193056207
epochs 35/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0024520064655102, val_loss: 0.9888455742283871
epochs 36/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9995622917225486, val_loss: 0.9882340305729916
epochs 37/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.000112207312333, val_loss: 0.9878660722782737
epochs 38/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0024833930166144, val_loss: 0.9877621343261317
epochs 39/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.0021432763651799, val_loss: 0.9883091857558802
epochs 40/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.00005063571428, val_loss: 0.9890858468256498
epochs 41/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.001192171322672, val_loss: 0.9895954288934407
epochs 42/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9997542092674657, val_loss: 0.9895726975641752
epochs 43/100
Current Learning Rate: 0.04410082408777967
train_loss: 1.001157782579723, val_loss: 0.9893487535024944
epochs 44/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9985075969445077, val_loss: 0.9893964874116998
epochs 45/100
Current Learning Rate: 0.04410082408777967
train_loss: 0.9988144855750235, val_loss: 0.9892653258223283
epochs 46/100
Epoch 00046: reducing learning rate of group 0 to 8.1862e-03.
Current Learning Rate: 0.008186241188426984
train_loss: 1.0013670701729624, val_loss: 0.9894611019837228
epochs 47/100
Current Learning Rate: 0.008186241188426984
train_loss: 1.0003269408878528, val_loss: 0.9895327655892623
epochs 48/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9995822875123275, val_loss: 0.9895670696308738
epochs 49/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9992903376880445, val_loss: 0.9895457719501696
epochs 50/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9991116617855272, val_loss: 0.9894766211509705
epochs 51/100
Current Learning Rate: 0.008186241188426984
train_loss: 1.0012904531077336, val_loss: 0.9893674160304823
epochs 52/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9999401883075112, val_loss: 0.9892772655738028
epochs 53/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9990129878646449, val_loss: 0.9891893549969322
epochs 54/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9996806069424278, val_loss: 0.989090875575417
epochs 55/100
Current Learning Rate: 0.008186241188426984
train_loss: 1.0008528514912254, val_loss: 0.9890241560183073
epochs 56/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9988724652089571, val_loss: 0.9889742136001587
epochs 57/100
Current Learning Rate: 0.008186241188426984
train_loss: 1.000068542204405, val_loss: 0.988946817423168
epochs 58/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9991490150752821, val_loss: 0.9888867265299747
epochs 59/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9987651329291495, val_loss: 0.9888897098993
epochs 60/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9993376700501693, val_loss: 0.9888939731999448
epochs 61/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9978360000409578, val_loss: 0.988855873283587
epochs 62/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9992408187765824, val_loss: 0.9888685063311928
epochs 63/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9993851812262284, val_loss: 0.9890179571352506
epochs 64/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9980449645142806, val_loss: 0.9899297042896873
epochs 65/100
Current Learning Rate: 0.008186241188426984
train_loss: 1.000983332332812, val_loss: 0.988814187677283
epochs 66/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9943662599513405, val_loss: 0.9884547779434606
epochs 67/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9928808024055079, val_loss: 1.009603870542426
epochs 68/100
Current Learning Rate: 0.008186241188426984
train_loss: 1.0021612895162482, val_loss: 0.9874777793884277
epochs 69/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9935965443912306, val_loss: 0.9873524119979457
epochs 70/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9923723528259679, val_loss: 0.9865131252690366
epochs 71/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9736314761011224, val_loss: 0.9988504867804678
epochs 72/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9674945065849706, val_loss: 0.9833929664210269
epochs 73/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9723237533318368, val_loss: 0.9964420262135958
epochs 74/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9777319494046663, val_loss: 0.9824651354237607
epochs 75/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9602058467112089, val_loss: 0.9801960901210183
epochs 76/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9596014524761, val_loss: 0.9799275680592185
epochs 77/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9521855711936951, val_loss: 0.9806033812071148
epochs 78/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9452573092360246, val_loss: 0.9824149232161673
epochs 79/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9524043798446655, val_loss: 0.9997004835229171
epochs 80/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9549748709327296, val_loss: 1.0354106112530357
epochs 81/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9561173225703993, val_loss: 1.0073617759503817
epochs 82/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9444398346700167, val_loss: 0.9928915406528273
epochs 83/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9524439636029696, val_loss: 0.9906805659595289
epochs 84/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9446309397095128, val_loss: 0.9963273845220867
epochs 85/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9466836797563654, val_loss: 1.0071959621027897
epochs 86/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.942047583429437, val_loss: 1.0243592262268066
epochs 87/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9385581643957841, val_loss: 1.0422831961983128
epochs 88/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9371707596276936, val_loss: 1.0344613163094771
epochs 89/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9399503908659282, val_loss: 1.020770135678743
epochs 90/100

[I 2024-01-27 01:12:18,821] Trial 6 pruned.

Current Learning Rate: 0.008186241188426984
train_loss: 0.9216019636706302, val_loss: 1.0382457030446905
epochs 91/100
Current Learning Rate: 0.008186241188426984
train_loss: 0.9346550640306974, val_loss: 1.0275878780766536
epochs 92/100
Starting fold 1:
epochs 1/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0884386828071193, val_loss: 1.0922142191937094
epochs 2/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0886451457676134, val_loss: 1.0912966301566676
epochs 3/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0856601326089157, val_loss: 1.0904036434073197
epochs 4/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0859528328243055, val_loss: 1.0895273032941317
epochs 5/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0840884007905658, val_loss: 1.088662422330756
epochs 6/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.085516841788041, val_loss: 1.0878038318533647
epochs 7/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0824873710933485, val_loss: 1.086952469223424
epochs 8/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0846777125408775, val_loss: 1.0861082177413137
epochs 9/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0816511417690076, val_loss: 1.0852688099208632
epochs 10/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0810004435087506, val_loss: 1.0844336283834357
epochs 11/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.080048854727494, val_loss: 1.0836054877230996
epochs 12/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.077190199651216, val_loss: 1.0827828783737985
epochs 13/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0781879851692602, val_loss: 1.0819628339064749
epochs 14/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0762932551534552, val_loss: 1.0811428923355906
epochs 15/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0792210390693262, val_loss: 1.0803300732060483
epochs 16/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0758443092045031, val_loss: 1.0795190710770457
epochs 17/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0739707256618298, val_loss: 1.0787046168979846
epochs 18/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0748247485411795, val_loss: 1.0778919684259516
epochs 19/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0726744626697742, val_loss: 1.0770782671476666
epochs 20/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0733361482620238, val_loss: 1.0762663088346782
epochs 21/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0722824372743305, val_loss: 1.075455331802368
epochs 22/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.070951875887419, val_loss: 1.0746462294929906
epochs 23/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0705258356897454, val_loss: 1.0738425367756894
epochs 24/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0700940947783621, val_loss: 1.0730418569163271
epochs 25/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0684292893660696, val_loss: 1.0722456267005518
epochs 26/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0680389943875765, val_loss: 1.0714509913795873
epochs 27/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0671207114269858, val_loss: 1.0706562782588758
epochs 28/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0654703403774062, val_loss: 1.0698587116442229
epochs 29/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0660788159621388, val_loss: 1.0690637801822862
epochs 30/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0641262543828864, val_loss: 1.0682686881015175
epochs 31/72
Current Learning Rate: 0.00012915094831291005
train_loss: 1.0650445524014924, val_loss: 1.0674772450798435
epochs 32/72

[I 2024-01-27 01:12:20,148] Trial 7 pruned.

Starting fold 1:
epochs 1/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.082981374389247, val_loss: 1.086578635165566
epochs 2/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0839098892713848, val_loss: 1.086410571399488
epochs 3/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0843666817012587, val_loss: 1.0862473487854003
epochs 4/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0839469018735384, val_loss: 1.086086362286618
epochs 5/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.083686217508818, val_loss: 1.0859257421995465
epochs 6/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0831113300825421, val_loss: 1.085766497411226
epochs 7/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0834810972213744, val_loss: 1.0856077645954332
epochs 8/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0820918785898308, val_loss: 1.0854484909459163
epochs 9/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.082462689751073, val_loss: 1.085289142006322
epochs 10/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0834783001949913, val_loss: 1.0851305836125424
epochs 11/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.082125705166867, val_loss: 1.0849727869033814
epochs 12/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0831911551324944, val_loss: 1.0848156326695493
epochs 13/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0811134012121904, val_loss: 1.0846581471593757
epochs 14/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0823681969391672, val_loss: 1.084500597652636
epochs 15/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0824974248283787, val_loss: 1.0843431121424625
epochs 16/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.08157082984322, val_loss: 1.0841855802034077
epochs 17/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0818188416330439, val_loss: 1.0840280394805104
epochs 18/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.081616156979611, val_loss: 1.0838709843786138
epochs 19/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0799930911315114, val_loss: 1.0837144613265992
epochs 20/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0805261473906667, val_loss: 1.0835579759196232
epochs 21/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.081401941650792, val_loss: 1.0834023161938315
epochs 22/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0802870148106625, val_loss: 1.0832475022265786
epochs 23/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0798625506852801, val_loss: 1.0830928802490234
epochs 24/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0804979512566015, val_loss: 1.0829381942749023
epochs 25/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0793826504757529, val_loss: 1.0827830490313077
epochs 26/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0794967287465145, val_loss: 1.0826273541701468
epochs 27/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.080174180081016, val_loss: 1.082471557667381
epochs 28/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.080180317477176, val_loss: 1.0823162467856156
epochs 29/102

[I 2024-01-27 01:12:21,571] Trial 8 pruned.

Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0795922128777755, val_loss: 1.0821605782759818
epochs 30/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.0795227841327064, val_loss: 1.082005561025519
epochs 31/102
Current Learning Rate: 1.2640793809240468e-05
train_loss: 1.078376357178939, val_loss: 1.081850662984346
epochs 32/102
Starting fold 1:
epochs 1/61
Current Learning Rate: 0.012696090132087954
train_loss: 1.1112530388330157, val_loss: 1.0254974371508547
epochs 2/61
Current Learning Rate: 0.012696090132087954
train_loss: 1.0353839943283483, val_loss: 1.0108644184313322
epochs 3/61
Current Learning Rate: 0.012696090132087954
train_loss: 1.0219354679709987, val_loss: 0.9982618865213896
epochs 4/61
Current Learning Rate: 0.012696090132087954
train_loss: 1.0139882319851925, val_loss: 0.9947900803465592
epochs 5/61
Current Learning Rate: 0.012696090132087954
train_loss: 1.0023636372465836, val_loss: 0.992516783664101
epochs 6/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9997620607677259, val_loss: 0.9919012057153802
epochs 7/61
Current Learning Rate: 0.012696090132087954
train_loss: 1.0009428814837806, val_loss: 0.9918466580541511
epochs 8/61
Current Learning Rate: 0.012696090132087954
train_loss: 1.001697406015898, val_loss: 0.9918119857185765
epochs 9/61
Current Learning Rate: 0.012696090132087954
train_loss: 1.0001599776117425, val_loss: 0.9915558965582597
epochs 10/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9976463951562581, val_loss: 0.9906857339959395
epochs 11/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.995029896811435, val_loss: 0.9876022953736154
epochs 12/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9860876371985987, val_loss: 0.9881397962570191
epochs 13/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9763986675362838, val_loss: 1.0116727923092088
epochs 14/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9808493865163703, val_loss: 0.9882987863139102
epochs 15/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9393684117417587, val_loss: 0.9808910413792259
epochs 16/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9406376844958255, val_loss: 0.9944272355029458
epochs 17/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9396266378854451, val_loss: 1.0123203252491197
epochs 18/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9328749148469222, val_loss: 1.0228541273819773
epochs 19/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9418651116521735, val_loss: 0.9947069826878999
epochs 20/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9243515334631267, val_loss: 1.0123073872766997
epochs 21/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.942625796167474, val_loss: 0.9915335278762014
epochs 22/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.92909351712779, val_loss: 1.0202765176170752
epochs 23/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.931637398192757, val_loss: 1.0145777947024295
epochs 24/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9249150784392106, val_loss: 1.0137734281389337
epochs 25/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9300649184929697, val_loss: 1.0128354499214574
epochs 26/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.919055986404419, val_loss: 1.026583685373005
epochs 27/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9337082900499043, val_loss: 1.028267674697073
epochs 28/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9364710563107541, val_loss: 1.0225460861858569
epochs 29/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.911249588037792, val_loss: 1.0372323036193847
epochs 30/61

[I 2024-01-27 01:12:23,445] Trial 9 pruned.

Current Learning Rate: 0.012696090132087954
train_loss: 0.9405160408270986, val_loss: 1.0064566411470113
epochs 31/61
Current Learning Rate: 0.012696090132087954
train_loss: 0.9119384401722959, val_loss: 1.041986976799212
epochs 32/61
Starting fold 1:
epochs 1/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1100859817705657, val_loss: 1.1189101394854093
epochs 2/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1107676782106097, val_loss: 1.1188041661915027
epochs 3/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1102721703679939, val_loss: 1.1186999396273964
epochs 4/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.111125989964134, val_loss: 1.1185964308286969
epochs 5/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1116080334312037, val_loss: 1.1184932407579924
epochs 6/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.110678159563165, val_loss: 1.1183906404595627
epochs 7/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1105666223325228, val_loss: 1.118287370079442
epochs 8/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.110566352543078, val_loss: 1.1181839378256546
epochs 9/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.110922989092375, val_loss: 1.1180803938915855
epochs 10/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1105456465169004, val_loss: 1.1179769239927593
epochs 11/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1103670358657838, val_loss: 1.1178741279401276
epochs 12/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1093771206705194, val_loss: 1.117771211423372
epochs 13/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1105895506708245, val_loss: 1.1176682560067428
epochs 14/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.108342981338501, val_loss: 1.1175652202806974
epochs 15/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.109086685431631, val_loss: 1.1174621067549053
epochs 16/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1102863826249776, val_loss: 1.1173591124384026
epochs 17/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.109554312103673, val_loss: 1.117255677674946
epochs 18/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1086896017978065, val_loss: 1.117152163856908
epochs 19/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.109458152871383, val_loss: 1.1170485734939575
epochs 20/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1088690870686582, val_loss: 1.1169449417214645
epochs 21/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1105338836971081, val_loss: 1.1168416299318011
epochs 22/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.10882053877178, val_loss: 1.116738160032975
epochs 23/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1080828327881662, val_loss: 1.1166344529704044
epochs 24/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1090374908949199, val_loss: 1.1165308262172497
epochs 25/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1075517679515638, val_loss: 1.1164275947370028
epochs 26/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1091008387113872, val_loss: 1.116325152547736
epochs 27/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.10921807414607, val_loss: 1.1162225924040141
epochs 28/121

[I 2024-01-27 01:12:25,320] Trial 10 pruned.

Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1090660572052002, val_loss: 1.1161199130510029
epochs 29/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1083697582546033, val_loss: 1.1160170341792859
epochs 30/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1080271444822614, val_loss: 1.115913798934535
epochs 31/121
Current Learning Rate: 3.9160205594545086e-06
train_loss: 1.1088289210670872, val_loss: 1.1158110442914462
epochs 32/121
Starting fold 1:
epochs 1/116
Current Learning Rate: 0.0005326985685785343
train_loss: 1.0856591237218756, val_loss: 1.0592054981934398
epochs 2/116
Current Learning Rate: 0.0005326985685785343
train_loss: 1.0639049668061107, val_loss: 1.0426187621919731
epochs 3/116
Current Learning Rate: 0.0005326985685785343
train_loss: 1.0512322243891263, val_loss: 1.0276479551666662
epochs 4/116
Current Learning Rate: 0.0005326985685785343
train_loss: 1.035920940261138, val_loss: 1.0142251422530726
epochs 5/116
Current Learning Rate: 0.0005326985685785343
train_loss: 1.0243084393049542, val_loss: 1.0030610605290062
epochs 6/116
Current Learning Rate: 0.0005326985685785343
train_loss: 1.0090445851024827, val_loss: 0.9950585870366347
epochs 7/116
Current Learning Rate: 0.0005326985685785343
train_loss: 1.004116030429539, val_loss: 0.9910347612280594
epochs 8/116
Current Learning Rate: 0.0005326985685785343
train_loss: 1.0030513681863484, val_loss: 0.9904616283743005
epochs 9/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9974078783863469, val_loss: 0.9914166318742852
epochs 10/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9895534876145815, val_loss: 0.9919337554981834
epochs 11/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9968787717191796, val_loss: 0.9910753962240721
epochs 12/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9984176648290534, val_loss: 0.9894424115356646
epochs 13/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9927367706047862, val_loss: 0.9878070668170327
epochs 14/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9939932980035481, val_loss: 0.9865545037545655
epochs 15/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9886392383198989, val_loss: 0.9856252262466833
epochs 16/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9913103913006029, val_loss: 0.9849438949635154
epochs 17/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9916414910241177, val_loss: 0.9844103970025715
epochs 18/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9906988686636875, val_loss: 0.9841709946331225
epochs 19/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9889533736203846, val_loss: 0.9840217380147231
epochs 20/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.990665594527596, val_loss: 0.9840185604597392
epochs 21/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9868410690834648, val_loss: 0.9840926101333216
epochs 22/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9865879463522058, val_loss: 0.9840784295609123
epochs 23/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9828594524609415, val_loss: 0.984078993609077
epochs 24/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9851865250813333, val_loss: 0.9839558874305926
epochs 25/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9833298937270516, val_loss: 0.9837474895151038
epochs 26/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.986742030005706, val_loss: 0.9834917501399392
epochs 27/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9882021794193669, val_loss: 0.9829771264603263
epochs 28/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9864422396609658, val_loss: 0.9824381188342446
epochs 29/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9824230184680537, val_loss: 0.9819095106501329
epochs 30/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9845299852521796, val_loss: 0.9813690176135615
epochs 31/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9865409095036356, val_loss: 0.9807523435667942
epochs 32/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9748912930488587, val_loss: 0.9802715618359416
epochs 33/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9800028716263018, val_loss: 0.9797492601369556
epochs 34/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9742175346926639, val_loss: 0.9794687468754618
epochs 35/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9712734018501482, val_loss: 0.979337277537898
epochs 36/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9694941718327371, val_loss: 0.9792900577971809
epochs 37/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.974300019364608, val_loss: 0.9790878766461423
epochs 38/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9689246852146952, val_loss: 0.9787841163183514
epochs 39/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9664545172139218, val_loss: 0.9783370093295448
epochs 40/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9637125805804604, val_loss: 0.9777681281692103
epochs 41/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9641288183237376, val_loss: 0.9771802660666014
epochs 42/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9589129542049609, val_loss: 0.9772127320891932
epochs 43/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9582416016804545, val_loss: 0.9773310011938998
epochs 44/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.950901137213958, val_loss: 0.9775872776382848
epochs 45/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.947116904509695, val_loss: 0.9787735352390691
epochs 46/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9428465262839668, val_loss: 0.9806255977404745
epochs 47/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9444765875214025, val_loss: 0.9816009082292255
epochs 48/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9340336526695051, val_loss: 0.9869520858714455
epochs 49/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9365971198207453, val_loss: 0.9915552465539229
epochs 50/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.930598669303091, val_loss: 0.9974810314805884
epochs 51/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9278444026645861, val_loss: 1.001882362052014
epochs 52/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9218968347499245, val_loss: 1.0315790919881118
epochs 53/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.924340671300888, val_loss: 1.0190834851641404
epochs 54/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9522180770572863, val_loss: 1.0234397891320681
epochs 55/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9305566800268072, val_loss: 1.0076885624935752
epochs 56/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9173735455462807, val_loss: 1.0069089318576612
epochs 57/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9203155423465528, val_loss: 1.0090886652469635
epochs 58/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9134631847080431, val_loss: 1.0136079919965644
epochs 59/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9146199329903252, val_loss: 1.0151109717394176
epochs 60/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9165023976250699, val_loss: 1.0257083735967938
epochs 61/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9136258172361474, val_loss: 1.0228171615224135
epochs 62/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9114378132318196, val_loss: 1.0343623173864265
epochs 63/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.911029600155981, val_loss: 1.0207526828113356
epochs 64/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9114616767356271, val_loss: 1.0311288162281638
epochs 65/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9231898555630131, val_loss: 1.0150400898958507
epochs 66/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9047420090750644, val_loss: 1.0195752953228197
epochs 67/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9040829868693101, val_loss: 1.0130572221781078
epochs 68/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8922911151459343, val_loss: 1.0233291942822307
epochs 69/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9114048512358415, val_loss: 1.015501932721389
epochs 70/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9051970795581216, val_loss: 1.0370491768184462
epochs 71/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9125178484540236, val_loss: 1.0214861007113205
epochs 72/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9175551452134785, val_loss: 1.0216615617275238
epochs 73/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9043157561829216, val_loss: 1.0139778353666005
epochs 74/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8954935920865912, val_loss: 1.010879655888206
epochs 75/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9013730155794244, val_loss: 1.021629590109775
epochs 76/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8977816042147184, val_loss: 1.010578499342266
epochs 77/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9049634676230581, val_loss: 1.0160870818715346
epochs 78/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8968043747701143, val_loss: 1.0137703007773349
epochs 79/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8871711997609389, val_loss: 1.0128781039463846
epochs 80/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8899487812268106, val_loss: 1.0212881091393922
epochs 81/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8978958559663672, val_loss: 1.018982751432218
epochs 82/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8914780883412612, val_loss: 1.0271480707745804
epochs 83/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.9047462049283479, val_loss: 1.0221273227741843
epochs 84/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8967201894835422, val_loss: 1.0254376527510192
epochs 85/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8995581344554299, val_loss: 1.0178574524427715
epochs 86/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8958311400915447, val_loss: 1.0182324164792111
epochs 87/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8919668746621985, val_loss: 1.0181543883524442
epochs 88/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8944345994999534, val_loss: 1.016147255897522
epochs 89/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8913206925517634, val_loss: 1.0188513533065193
epochs 90/116
Current Learning Rate: 0.0005326985685785343
train_loss: 0.8977743933075353, val_loss: 1.0158379990803568
epochs 91/116

[I 2024-01-27 01:12:29,797] Trial 11 pruned.

Current Learning Rate: 0.0005326985685785343
train_loss: 0.8875809725962187, val_loss: 1.0167815365289388
epochs 92/116
Starting fold 1:
epochs 1/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1218302331472698, val_loss: 1.11198810338974
epochs 2/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1205525962929976, val_loss: 1.110266457733355
epochs 3/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1196683137040389, val_loss: 1.1085757481424432
epochs 4/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1180253788044578, val_loss: 1.1069071788536875
epochs 5/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1147362357691715, val_loss: 1.1052521931497674
epochs 6/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.11434110152094, val_loss: 1.1036081395651165
epochs 7/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1110065980961448, val_loss: 1.101977326995448
epochs 8/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1120852388833697, val_loss: 1.1003640413284301
epochs 9/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1084695395670439, val_loss: 1.0987591072132712
epochs 10/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1095915562228154, val_loss: 1.0971635881223176
epochs 11/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1073982828541806, val_loss: 1.0955750427748028
epochs 12/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1061325713207848, val_loss: 1.093988783735978
epochs 13/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.103723897432026, val_loss: 1.0924045738420989
epochs 14/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1017298190217268, val_loss: 1.090817834201612
epochs 15/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.1015093571261356, val_loss: 1.0892312589444613
epochs 16/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.097489689525805, val_loss: 1.0876479682169462
epochs 17/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0988826519564578, val_loss: 1.0860650024915997
epochs 18/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0956567977604112, val_loss: 1.0844869908533599
epochs 19/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0935224890708923, val_loss: 1.082902018647445
epochs 20/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0907535013399625, val_loss: 1.081308566896539
epochs 21/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.091311152357804, val_loss: 1.0797165249523364
epochs 22/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0890566091788443, val_loss: 1.078122684202696
epochs 23/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.087811247298592, val_loss: 1.076520286108318
epochs 24/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0885057618743494, val_loss: 1.0749129960411474
epochs 25/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0855876075594049, val_loss: 1.0733111230950607
epochs 26/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0831638643616124, val_loss: 1.0717017907845348
epochs 27/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0826907264558892, val_loss: 1.0700894882804468
epochs 28/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0818074991828517, val_loss: 1.068475966077102
epochs 29/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0796072351305108, val_loss: 1.0668498158454895
epochs 30/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0794165140704104, val_loss: 1.0652254775950782
epochs 31/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0773227635182832, val_loss: 1.0636026181672749
epochs 32/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0737921815169484, val_loss: 1.061979407385776
epochs 33/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0725655524354232, val_loss: 1.0603506966641074
epochs 34/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.072620859899019, val_loss: 1.058707741059755
epochs 35/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.072459064031902, val_loss: 1.057073742464969
epochs 36/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0687863042480068, val_loss: 1.055428647994995
epochs 37/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.069116987680134, val_loss: 1.053786417685057
epochs 38/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0642581494230974, val_loss: 1.052143977190319
epochs 39/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0654889784361188, val_loss: 1.0505101592917192
epochs 40/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.062157014169191, val_loss: 1.0488772423643815
epochs 41/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0633198894952474, val_loss: 1.0472472347711261
epochs 42/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0593976127473932, val_loss: 1.0456154428030315
epochs 43/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0570074871966713, val_loss: 1.0439709362230802
epochs 44/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0573014867933173, val_loss: 1.0423297053889224
epochs 45/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0528124602217424, val_loss: 1.0407000121317411
epochs 46/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0523852040893154, val_loss: 1.0390664012808548
epochs 47/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0550094952708797, val_loss: 1.0374458225149856
epochs 48/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0530736891846908, val_loss: 1.0358451636214006
epochs 49/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0480637064105587, val_loss: 1.0342476029145091
epochs 50/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0470888658573754, val_loss: 1.032650397325817
epochs 51/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0469542791968898, val_loss: 1.0310633100961384
epochs 52/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.042826603588305, val_loss: 1.0294783021274365
epochs 53/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0431715209233134, val_loss: 1.0278970831318905
epochs 54/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0412098166189696, val_loss: 1.02632583254262
epochs 55/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.040581008948778, val_loss: 1.0247644782066345
epochs 56/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.039868364208623, val_loss: 1.0232312233824479
epochs 57/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0376987454138304, val_loss: 1.0217157746616163
epochs 58/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0339092951071889, val_loss: 1.020221729655015
epochs 59/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0326617814992602, val_loss: 1.0187415668838902
epochs 60/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0318955879462393, val_loss: 1.0172752336451882
epochs 61/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0323267431635605, val_loss: 1.0158381669144882
epochs 62/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0297414268317975, val_loss: 1.0144276760126416
epochs 63/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.024615896061847, val_loss: 1.013041040771886
epochs 64/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0280497020796726, val_loss: 1.01169526075062
epochs 65/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.027366756765466, val_loss: 1.0103849050245788
epochs 66/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0209282755851745, val_loss: 1.0091121871220439
epochs 67/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0209672607873614, val_loss: 1.0078700357361843
epochs 68/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0200305543447796, val_loss: 1.0066681504249573
epochs 69/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0204918262205627, val_loss: 1.0055100227657117
epochs 70/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0184611546365838, val_loss: 1.004398051374837
epochs 71/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0156569110719782, val_loss: 1.0033171970593302
epochs 72/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0129873749456908, val_loss: 1.0022706053758923
epochs 73/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0161110329000573, val_loss: 1.0012794748732918
epochs 74/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0110000798576757, val_loss: 1.000330806092212
epochs 75/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0127055616755234, val_loss: 0.9994324222991341
epochs 76/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0134104734972904, val_loss: 0.9986053513853174
epochs 77/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0076906292062058, val_loss: 0.9978301700792814
epochs 78/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.008968943984885, val_loss: 0.9971031047795949
epochs 79/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0098513367928956, val_loss: 0.9964273590790598
epochs 80/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0070374219041123, val_loss: 0.9958003062950938
epochs 81/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0078234923513312, val_loss: 0.9952194254649313
epochs 82/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0092519214278772, val_loss: 0.994683357288963
epochs 83/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0026489420941, val_loss: 0.9941861513413881
epochs 84/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 1.0038380444049835, val_loss: 0.9937291506089663
Starting fold 2:
epochs 1/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 0.9968382981262709, val_loss: 1.1180493398716576
epochs 2/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 0.9954862876942283, val_loss: 1.120422855803841
epochs 3/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 0.9965550278362475, val_loss: 1.1227060804241582
epochs 4/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 0.9978556135767385, val_loss: 1.1247391336842587
epochs 5/84

[I 2024-01-27 01:12:34,197] Trial 12 pruned.

Current Learning Rate: 3.301568823957251e-05
train_loss: 0.9977103804287157, val_loss: 1.12661687700372
epochs 6/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 0.9996264972184834, val_loss: 1.1282101671946676
epochs 7/84
Current Learning Rate: 3.301568823957251e-05
train_loss: 0.9923061096354535, val_loss: 1.1297365154090682
epochs 8/84
Starting fold 1:
epochs 1/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.1627392750037344, val_loss: 1.132738509303645
epochs 2/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.1255174128632797, val_loss: 1.0923404154024625
epochs 3/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0861406037681982, val_loss: 1.0453117289041218
epochs 4/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0422518488607908, val_loss: 1.0042295123401441
epochs 5/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0280720544488806, val_loss: 0.9964380524660411
epochs 6/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0073187956684515, val_loss: 0.9989573230868891
epochs 7/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0037538653925846, val_loss: 0.9951793993774213
epochs 8/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0013765366453873, val_loss: 0.9932934224605561
epochs 9/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9998948586614509, val_loss: 0.9940985892948352
epochs 10/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.006172899509731, val_loss: 0.9951658390070263
epochs 11/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9991284298269372, val_loss: 0.995096188469937
epochs 12/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.008053052111676, val_loss: 0.9945227362607655
epochs 13/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0023367292002627, val_loss: 0.9938122159556338
epochs 14/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0056333554418464, val_loss: 0.9934673952428918
epochs 15/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0054175289053666, val_loss: 0.9933887776575591
epochs 16/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9988561175371471, val_loss: 0.9932503443015249
epochs 17/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.0051795614393133, val_loss: 0.9931392798298284
epochs 18/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9981112586824518, val_loss: 0.9930447939195131
epochs 19/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9940082035566631, val_loss: 0.9926011189034111
epochs 20/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9979743421077728, val_loss: 0.9918643035386738
epochs 21/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9934037660297594, val_loss: 0.9912488981297142
epochs 22/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9971566943745864, val_loss: 0.991321072139238
epochs 23/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9943199775720898, val_loss: 0.9914005166605899
epochs 24/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9886417552044517, val_loss: 0.9912648586850418
epochs 25/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9855687536691364, val_loss: 0.9906738943175266
epochs 26/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9881569049860301, val_loss: 0.9897076685177653
epochs 27/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9818554326107628, val_loss: 0.988344261834496
epochs 28/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9744542899884676, val_loss: 0.9871684319094608
epochs 29/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9732344859524777, val_loss: 0.9880932704398506
epochs 30/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9574703335762024, val_loss: 0.9928441361377114
epochs 31/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.934676636520185, val_loss: 1.0063964599057247
epochs 32/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9605674787571555, val_loss: 1.0309269939598285
epochs 33/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9321645178292927, val_loss: 1.0278187588641519
epochs 34/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9265719580022912, val_loss: 1.0367467221460844
epochs 35/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9459049046039582, val_loss: 1.03754013117991
epochs 36/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9327347156248594, val_loss: 1.0719988070036235
epochs 37/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9616861101828124, val_loss: 1.039391745391645
epochs 38/51
Current Learning Rate: 0.0015932618774985223
train_loss: 1.031604933111291, val_loss: 1.0197256602739033
epochs 39/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.959326300809258, val_loss: 1.00561847122092
epochs 40/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9428573125287106, val_loss: 1.0423455931638417
epochs 41/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9623127469890996, val_loss: 1.0418298144089548
epochs 42/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9550439988311968, val_loss: 1.0312573382728978
epochs 43/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9427924124818099, val_loss: 1.023939703640185
epochs 44/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.935041879666479, val_loss: 1.0277505153103879
epochs 45/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9338743457668706, val_loss: 1.030185357206746
epochs 46/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9332984955687272, val_loss: 1.027432724049217
epochs 47/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9244471703705035, val_loss: 1.0317730894214228
epochs 48/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9232831148724807, val_loss: 1.0304817748697181
epochs 49/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9302118194730659, val_loss: 1.031364748666161
epochs 50/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9154821835066143, val_loss: 1.0318266796438318
epochs 51/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9160155663364812, val_loss: 1.0272965217891492
Starting fold 2:
epochs 1/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9829463820708425, val_loss: 1.093589873062937
epochs 2/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.954513615526651, val_loss: 1.077986845217253
epochs 3/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9454711090577276, val_loss: 1.073007700631493
epochs 4/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9419376010957518, val_loss: 1.0715205819983231
epochs 5/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.955157029785608, val_loss: 1.070670946961955
epochs 6/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.94273617534261, val_loss: 1.0698347348915904
epochs 7/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9444145572812934, val_loss: 1.0692363519417611
epochs 8/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9380409705011468, val_loss: 1.0683546844281648
epochs 9/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9515297635605461, val_loss: 1.0674714320584346
epochs 10/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9448610434406682, val_loss: 1.0677454179839083
epochs 11/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.944060797283524, val_loss: 1.0675010078831724
epochs 12/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9723016691835303, val_loss: 1.0689217934482975
epochs 13/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9794749757176952, val_loss: 1.0871345422769847
epochs 14/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9600727892235705, val_loss: 1.0795588468250474
epochs 15/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9651246026942605, val_loss: 1.0773307248165733
epochs 16/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9521974709473158, val_loss: 1.0939967105263158
epochs 17/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9437744645695937, val_loss: 1.082136198721434
epochs 18/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9495859870785162, val_loss: 1.0720288091584256
epochs 19/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9403887932237825, val_loss: 1.0762494284855693
epochs 20/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9355245941563657, val_loss: 1.0713701310910677
epochs 21/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9411163874362645, val_loss: 1.0739614442775125
epochs 22/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9523453027009964, val_loss: 1.0760395426499216
epochs 23/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9333500070007223, val_loss: 1.0688976297253057
epochs 24/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9292926926361887, val_loss: 1.071366221340079
epochs 25/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9363023803422326, val_loss: 1.086183626400797
epochs 26/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9312966798481188, val_loss: 1.085211966539684
epochs 27/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9515051965650759, val_loss: 1.123612106787531
epochs 28/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9646458625793457, val_loss: 1.157761926400034
epochs 29/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9594377836114482, val_loss: 1.0923810384775463
epochs 30/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9500937113636418, val_loss: 1.1010562783793398
epochs 31/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9352850507748754, val_loss: 1.1211021548823306
epochs 32/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9467980147976625, val_loss: 1.0810483684665277
epochs 33/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9386488374910856, val_loss: 1.0742019537248109
epochs 34/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9341033949663765, val_loss: 1.0692213485115454
epochs 35/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9297562500363902, val_loss: 1.0913351852642863
epochs 36/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9320318684766167, val_loss: 1.0683245379673807
epochs 37/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9225881204793328, val_loss: 1.0741356717912773
epochs 38/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.9145053755295904, val_loss: 1.0792346675145
epochs 39/51

[I 2024-01-27 01:12:39,212] Trial 13 pruned.

Current Learning Rate: 0.0015932618774985223
train_loss: 0.920094568635288, val_loss: 1.0962993734761288
epochs 40/51
Current Learning Rate: 0.0015932618774985223
train_loss: 0.924608199847372, val_loss: 1.082461309746692
epochs 41/51
Starting fold 1:
epochs 1/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1259242459347374, val_loss: 1.124789027163857
epochs 2/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1263032988498085, val_loss: 1.1246534084018909
epochs 3/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.125312052275005, val_loss: 1.1245185939889206
epochs 4/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.125177966920953, val_loss: 1.1243841397134882
epochs 5/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.126151943206787, val_loss: 1.1242503643035888
epochs 6/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1253774103365446, val_loss: 1.1241169276990388
epochs 7/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1275080768685593, val_loss: 1.1239837019067063
epochs 8/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1250415049101177, val_loss: 1.1238506379880404
epochs 9/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1253844123137624, val_loss: 1.1237179505197625
epochs 10/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1252216979076988, val_loss: 1.123585736124139
epochs 11/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1264174122559396, val_loss: 1.1234535129446732
epochs 12/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1254502660349797, val_loss: 1.1233212408266569
epochs 13/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1248427604374132, val_loss: 1.1231889260442633
epochs 14/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1249290855307328, val_loss: 1.123056357785275
epochs 15/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1245059979589362, val_loss: 1.1229237129813747
epochs 16/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1233402427874113, val_loss: 1.1227914960760819
epochs 17/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1232922604209499, val_loss: 1.1226589855394866
epochs 18/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.125039549877769, val_loss: 1.1225266218185426
epochs 19/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.12544474978196, val_loss: 1.1223942518234253
epochs 20/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1241858105910452, val_loss: 1.122262275846381
epochs 21/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1241545815216867, val_loss: 1.1221305018977115
epochs 22/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.124786655526412, val_loss: 1.121998617523595
epochs 23/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1238907425027145, val_loss: 1.1218662500381469
epochs 24/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.123753557707134, val_loss: 1.1217344359347694
epochs 25/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1228461591820968, val_loss: 1.1216024260771902
epochs 26/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1237751785077548, val_loss: 1.1214710699884516
epochs 27/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.124167309309307, val_loss: 1.121339447874772
epochs 28/110

[I 2024-01-27 01:12:40,814] Trial 14 pruned.

Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.122807260563499, val_loss: 1.1212075660103247
epochs 29/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1228341165341829, val_loss: 1.1210756352073268
epochs 30/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1219662992577804, val_loss: 1.1209432463896902
epochs 31/110
Current Learning Rate: 3.1126578660154534e-06
train_loss: 1.1244684784035934, val_loss: 1.1208106831500404
epochs 32/110
Starting fold 1:
epochs 1/88
Current Learning Rate: 0.00260887588751439
train_loss: 1.0563598055588572, val_loss: 1.0133228672178167
epochs 2/88
Current Learning Rate: 0.00260887588751439
train_loss: 1.023360278104481, val_loss: 0.9904917698157462
epochs 3/88
Current Learning Rate: 0.00260887588751439
train_loss: 1.0106895710292616, val_loss: 0.9881133713220295
epochs 4/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9990565820744163, val_loss: 0.9876331762263649
epochs 5/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9973341264222798, val_loss: 0.9880495755296005
epochs 6/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9971313269514787, val_loss: 0.9882293167867159
epochs 7/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9961341719878347, val_loss: 0.9877187114012869
epochs 8/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.996447525526348, val_loss: 0.9871057416263379
epochs 9/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.997075909689853, val_loss: 0.9868510785855745
epochs 10/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9957637353947288, val_loss: 0.9864851217520865
epochs 11/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9947136239001625, val_loss: 0.9861545456083197
epochs 12/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9941681566991304, val_loss: 0.9855661586711281
epochs 13/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9919690176060325, val_loss: 0.9850139649290788
epochs 14/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.990167508627239, val_loss: 0.9845594920610127
epochs 15/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9856832052531995, val_loss: 0.9841076894810326
epochs 16/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9865004489296361, val_loss: 0.9834766544793782
epochs 17/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9799607276916504, val_loss: 0.9827122500068263
epochs 18/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9766858270293788, val_loss: 0.9821107613412957
epochs 19/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9697446459218075, val_loss: 0.9820315059862639
epochs 20/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.964134849372663, val_loss: 0.9840903194327103
epochs 21/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9516505203749004, val_loss: 0.9914830069792898
epochs 22/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9409957383808337, val_loss: 1.014783461470353
epochs 23/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9322815644113641, val_loss: 1.0587981619332967
epochs 24/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9367535484464545, val_loss: 1.0481601188057348
epochs 25/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9332888659678007, val_loss: 1.0271526336669923
epochs 26/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9367146554746126, val_loss: 1.019725215435028
epochs 27/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9263945686189752, val_loss: 1.0230846266997489
epochs 28/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9313773625775388, val_loss: 1.0387897623212714
epochs 29/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9294670355947394, val_loss: 1.041573503142909
epochs 30/88

[I 2024-01-27 01:12:42,884] Trial 15 pruned.

Current Learning Rate: 0.00260887588751439
train_loss: 0.9317593656088177, val_loss: 1.0523518185866507
epochs 31/88
Current Learning Rate: 0.00260887588751439
train_loss: 0.9369106807206806, val_loss: 1.0624730618376481
epochs 32/88
Starting fold 1:
epochs 1/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1471163523824592, val_loss: 1.1556864161240428
epochs 2/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1458777942155536, val_loss: 1.154652610578035
epochs 3/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1450509460348832, val_loss: 1.1536330536792152
epochs 4/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1441759686720998, val_loss: 1.152622887962743
epochs 5/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1428994580319054, val_loss: 1.151620942667911
epochs 6/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1421069333427831, val_loss: 1.1506260307211624
epochs 7/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1414738479413484, val_loss: 1.1496358720879807
epochs 8/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1402905903364482, val_loss: 1.1486492069143999
epochs 9/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1397405185197529, val_loss: 1.1476655947534662
epochs 10/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.137860259256865, val_loss: 1.1466841183210674
epochs 11/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.137199047992104, val_loss: 1.1457049482747128
epochs 12/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1365593445928472, val_loss: 1.144727695615668
epochs 13/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1355165682340924, val_loss: 1.143753298960234
epochs 14/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1343882146634554, val_loss: 1.1427790579042936
epochs 15/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1343697798879524, val_loss: 1.1418046148199783
epochs 16/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1327121722070794, val_loss: 1.1408291967291582
epochs 17/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.132379574524729, val_loss: 1.1398528613542256
epochs 18/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1316680920751472, val_loss: 1.1388736222919664
epochs 19/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1302213656274895, val_loss: 1.137891247397975
epochs 20/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1292481723584626, val_loss: 1.1369041869514867
epochs 21/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.129154506482576, val_loss: 1.135912947905691
epochs 22/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1275677153938695, val_loss: 1.1349152188552054
epochs 23/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1270506118473254, val_loss: 1.1339105493143986
epochs 24/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.126278103025336, val_loss: 1.1328966642680922
epochs 25/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1251318178678813, val_loss: 1.1318742576398348
epochs 26/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1239013144844456, val_loss: 1.130843650667291
epochs 27/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1232347940143785, val_loss: 1.1298025055935508
epochs 28/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1226256608963012, val_loss: 1.1287475836904426
epochs 29/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1208181280838816, val_loss: 1.1276773502952173
epochs 30/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1199665508772199, val_loss: 1.1265921316648784
epochs 31/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1189067087675395, val_loss: 1.1254907043356643
epochs 32/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1184220803411384, val_loss: 1.1243739956303647
epochs 33/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1171800400081433, val_loss: 1.1232393264770508
epochs 34/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1160066692452681, val_loss: 1.1220842298708464
epochs 35/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1153769706424914, val_loss: 1.1209062751970793
epochs 36/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1132623835613853, val_loss: 1.1197021559665077
epochs 37/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.112547244523701, val_loss: 1.1184688241858232
epochs 38/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1116395774640535, val_loss: 1.117208554870204
epochs 39/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1103053996437475, val_loss: 1.1159198547664442
epochs 40/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1094558163693076, val_loss: 1.1146004538787038
epochs 41/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.108176016807556, val_loss: 1.1132476932124087
epochs 42/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.106694383370249, val_loss: 1.111857809518513
epochs 43/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1052761491976286, val_loss: 1.1104266769007634
epochs 44/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.104649369340194, val_loss: 1.1089525950582404
epochs 45/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1031773027620817, val_loss: 1.1074355589716058
epochs 46/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1014669619108501, val_loss: 1.1058717690016093
epochs 47/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.1005169680244045, val_loss: 1.1042589601717496
epochs 48/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0986670707401476, val_loss: 1.1025900213341964
epochs 49/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0971338108966224, val_loss: 1.1008594224327488
epochs 50/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0957598171736065, val_loss: 1.099062368744298
epochs 51/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0939023921364233, val_loss: 1.0971970294651232
epochs 52/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0930442772413556, val_loss: 1.0952596513848556
epochs 53/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0902422252454256, val_loss: 1.0932437093634355
epochs 54/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0889564313386615, val_loss: 1.0911460575304532
epochs 55/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.086051190526862, val_loss: 1.088956194174917
epochs 56/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.084865749509711, val_loss: 1.086670556821321
epochs 57/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0825047869431346, val_loss: 1.0842812525598626
epochs 58/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.081016166586625, val_loss: 1.081785522009197
epochs 59/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0787926360180504, val_loss: 1.0791783282631322
epochs 60/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0762962717758982, val_loss: 1.0764480452788503
epochs 61/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0744088825426603, val_loss: 1.0735942250803898
epochs 62/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.070953369140625, val_loss: 1.0706119625191939
epochs 63/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.069346995102732, val_loss: 1.0674941200959056
epochs 64/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0663179786581742, val_loss: 1.0642363058893305
epochs 65/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0638458615855166, val_loss: 1.0608400733847367
epochs 66/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0601242492073462, val_loss: 1.057300719461943
epochs 67/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0575372884148047, val_loss: 1.0536275211133455
epochs 68/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.053864914492557, val_loss: 1.049832626392967
epochs 69/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0506305293032998, val_loss: 1.0459257464659841
epochs 70/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0473770204343293, val_loss: 1.0419261606116044
epochs 71/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0433694726542422, val_loss: 1.0378586405201962
epochs 72/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0397962519997044, val_loss: 1.0337426398929797
epochs 73/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0370254190344559, val_loss: 1.0296223652990242
epochs 74/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0322140618374473, val_loss: 1.025537563625135
epochs 75/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0307506799697876, val_loss: 1.0215524748751992
epochs 76/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0261827657097264, val_loss: 1.017710242773357
epochs 77/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0217020988464356, val_loss: 1.0140489666085495
epochs 78/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0205238655993814, val_loss: 1.0106430379967941
epochs 79/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0183996677398681, val_loss: 1.0075536627518504
epochs 80/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.014120504730626, val_loss: 1.00479509328541
epochs 81/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0116523805417512, val_loss: 1.002394531902514
epochs 82/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0084350811807732, val_loss: 1.0003580883929604
epochs 83/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0073898629138345, val_loss: 0.9986755760092484
epochs 84/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.006349341492904, val_loss: 0.9973416315881829
epochs 85/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.005956166668942, val_loss: 0.9963211185053775
epochs 86/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0035750338905736, val_loss: 0.9955600600493582
epochs 87/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0027369536851582, val_loss: 0.9950226030851665
epochs 88/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.002107522362157, val_loss: 0.9946661873867637
epochs 89/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0005634859988564, val_loss: 0.9944418304844906
epochs 90/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0008480573955336, val_loss: 0.9943264421663787
epochs 91/139
Current Learning Rate: 4.822635890108728e-05
train_loss: 1.0027311977587248, val_loss: 0.9943071039099443
epochs 92/139

[I 2024-01-27 01:12:47,990] Trial 16 pruned.

Starting fold 1:
epochs 1/132
Current Learning Rate: 0.0020359517728735354
train_loss: 1.1189911465895803, val_loss: 1.0843204962579827
epochs 2/132
Current Learning Rate: 0.0020359517728735354
train_loss: 1.093655979005914, val_loss: 1.0618338145707782
epochs 3/132
Current Learning Rate: 0.0020359517728735354
train_loss: 1.0681181769622, val_loss: 1.0405318523708142
epochs 4/132
Current Learning Rate: 0.0020359517728735354
train_loss: 1.050526209254014, val_loss: 1.020688924036528
epochs 5/132
Current Learning Rate: 0.0020359517728735354
train_loss: 1.026056100192823, val_loss: 1.0061362360653123
epochs 6/132
Current Learning Rate: 0.0020359517728735354
train_loss: 1.0096893297998528, val_loss: 1.0008717367523594
epochs 7/132
Current Learning Rate: 0.0020359517728735354
train_loss: 1.0094295846788506, val_loss: 1.0031554761685824
epochs 8/132
Current Learning Rate: 0.0020359517728735354
train_loss: 1.0011620810157373, val_loss: 1.0051383238089713
epochs 9/132
Current Learning Rate: 0.0020359517728735354
train_loss: 1.0010228194688495, val_loss: 1.0025857881495828
epochs 10/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9957959884091427, val_loss: 0.9976158229928268
epochs 11/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9851576930598209, val_loss: 0.993200357336747
epochs 12/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9955838699089853, val_loss: 0.9902200209467035
epochs 13/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9916541275225188, val_loss: 0.9883826324814244
epochs 14/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9951975326789053, val_loss: 0.9873044798248692
epochs 15/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9910561266698336, val_loss: 0.9867386090128045
epochs 16/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9968894249514529, val_loss: 0.9865457541064212
epochs 17/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9972749910856548, val_loss: 0.9866856813430787
epochs 18/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9928907764585395, val_loss: 0.9871947978672229
epochs 19/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9974115327784889, val_loss: 0.987917255100451
epochs 20/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9876282949196665, val_loss: 0.9887079056940581
epochs 21/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9893070252318131, val_loss: 0.9895753747538516
epochs 22/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9898472465966878, val_loss: 0.9900271102001793
epochs 23/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9882781825567547, val_loss: 0.9899975820591576
epochs 24/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9904390504485683, val_loss: 0.9897629104162518
epochs 25/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9911756866856625, val_loss: 0.98940929927324
epochs 26/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9861026688625938, val_loss: 0.9887992131082635
epochs 27/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9905877621550309, val_loss: 0.9881387164718226
epochs 28/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9848194047024376, val_loss: 0.9878162954982959
epochs 29/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9903117161048086, val_loss: 0.9873920051675094
epochs 30/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9843549753490247, val_loss: 0.9868133802162974
epochs 31/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9812258124351502, val_loss: 0.9865699385341845
epochs 32/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9837230858049895, val_loss: 0.9862484260609276
epochs 33/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9863046752779108, val_loss: 0.9858700984402706
epochs 34/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9792230499418159, val_loss: 0.9856070763186404
epochs 35/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9855326884671262, val_loss: 0.9854586864772595
epochs 36/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.976631247997284, val_loss: 0.9856815607924211
epochs 37/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9800661087036133, val_loss: 0.9856236878194307
epochs 38/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9768789366671914, val_loss: 0.9854328105324193
epochs 39/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9739658744711625, val_loss: 0.9847790856110422
epochs 40/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.968977501517848, val_loss: 0.9838227102631016
epochs 41/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9717220300122311, val_loss: 0.982786132159986
epochs 42/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9699989588637101, val_loss: 0.9819574073741311
epochs 43/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9599877696288259, val_loss: 0.9817921795343098
epochs 44/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9650858063446848, val_loss: 0.9819719452607004
epochs 45/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.960545751923009, val_loss: 0.9821351590909456
epochs 46/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9512459045962284, val_loss: 0.9832420744394001
epochs 47/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9519070148468017, val_loss: 0.9836304746176067
epochs 48/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9489858344981544, val_loss: 0.9846696659138329
epochs 49/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9479746109560916, val_loss: 0.9871228243175306
epochs 50/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9462787000756515, val_loss: 0.9912143889226411
epochs 51/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9437617559182017, val_loss: 0.9965570958037125
epochs 52/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.938213763111516, val_loss: 1.0026886714132208
epochs 53/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9160165862033242, val_loss: 1.0117494721161693
epochs 54/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9316777881823088, val_loss: 1.0176377572511373
epochs 55/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9332654639294273, val_loss: 1.0138030842730874
epochs 56/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9333097263386375, val_loss: 1.0152163053813734
epochs 57/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9296381711959839, val_loss: 1.0160343772486637
epochs 58/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9317423538157814, val_loss: 1.015796579185285
epochs 59/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9273902861695541, val_loss: 1.0137122348735208
epochs 60/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9237628892848366, val_loss: 1.0137309532416494
epochs 61/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9206903852914509, val_loss: 1.0163012837108814
epochs 62/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.914630369136208, val_loss: 1.0166548214460673
epochs 63/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9250150304091604, val_loss: 1.0192708115828664
epochs 64/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9211146611916391, val_loss: 1.0221604152729638
epochs 65/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9169750734379417, val_loss: 1.021940058783481
epochs 66/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9227229369314094, val_loss: 1.022369823330327
epochs 67/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9320215124832957, val_loss: 1.018864357471466
epochs 68/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9172468906954715, val_loss: 1.0169941958628204
epochs 69/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9162524976228413, val_loss: 1.0159821422476518
epochs 70/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9228103085568077, val_loss: 1.0158105988251536
epochs 71/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9222625926921242, val_loss: 1.0158091413347345
epochs 72/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.907156789302826, val_loss: 1.017451738683801
epochs 73/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.919530365341588, val_loss: 1.0208783463427895
epochs 74/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9183246869789926, val_loss: 1.019986419301284
epochs 75/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9030515764888964, val_loss: 1.0203921474908528
epochs 76/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9150685285267077, val_loss: 1.0191969463699742
epochs 77/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9030401367890207, val_loss: 1.020121839799379
epochs 78/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9235464729760823, val_loss: 1.0223876557852092
epochs 79/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9139437549992612, val_loss: 1.0227826563935531
epochs 80/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.908329805574919, val_loss: 1.0264278393042714
epochs 81/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9131665273716575, val_loss: 1.0254970443876166
epochs 82/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.91816824047189, val_loss: 1.0265395986406427
epochs 83/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9094212513220937, val_loss: 1.0247437790820473
epochs 84/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9136606134866413, val_loss: 1.0267619271027415
epochs 85/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9005226656010277, val_loss: 1.032820437456432
epochs 86/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9113466413397538, val_loss: 1.0337039552236857
epochs 87/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9119015304665816, val_loss: 1.0338110158317968
epochs 88/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9084767209856134, val_loss: 1.0328183858018172
epochs 89/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.8993157719310961, val_loss: 1.0327011277801112
epochs 90/132
Current Learning Rate: 0.0020359517728735354
train_loss: 0.9073385232373288, val_loss: 1.0324549380101655
epochs 91/132
Epoch 00091: reducing learning rate of group 0 to 8.5366e-04.
Current Learning Rate: 0.0008536610352803483
train_loss: 0.8979215477642261, val_loss: 1.0327661884458441
epochs 92/132

[I 2024-01-27 01:12:51,843] Trial 17 pruned.

Starting fold 1:
epochs 1/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0731723998722278, val_loss: 1.079179286956787
epochs 2/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0725529193878174, val_loss: 1.0791355120508295
epochs 3/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0724623705211438, val_loss: 1.0790926531741494
epochs 4/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0731123183902942, val_loss: 1.0790499950710095
epochs 5/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0723781271984703, val_loss: 1.0790076945957385
epochs 6/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0731776827260067, val_loss: 1.0789653251045628
epochs 7/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0726163951974166, val_loss: 1.0789227611140202
epochs 8/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0725042882718538, val_loss: 1.078880460638749
epochs 9/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.072749376296997, val_loss: 1.0788380472283614
epochs 10/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0727021505958156, val_loss: 1.0787956714630127
epochs 11/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0731352630414461, val_loss: 1.0787533270685297
epochs 12/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0738080677233244, val_loss: 1.0787112461893182
epochs 13/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0723781522951628, val_loss: 1.0786689394398739
epochs 14/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0737300672029193, val_loss: 1.0786265197553133
epochs 15/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.073104933688515, val_loss: 1.0785843196668123
epochs 16/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.073225548392848, val_loss: 1.0785417494020964
epochs 17/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0729123040249473, val_loss: 1.078499386185094
epochs 18/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.072498879934612, val_loss: 1.0784569163071482
epochs 19/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0725292218358893, val_loss: 1.078414471525895
epochs 20/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0729793812099255, val_loss: 1.0783718761644865
epochs 21/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0727805840341669, val_loss: 1.0783292243355198
epochs 22/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0724884710813825, val_loss: 1.0782866352482845
epochs 23/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0720582447553937, val_loss: 1.0782440085160105
epochs 24/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.072791432079516, val_loss: 1.0782016202023155
epochs 25/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.07196843624115, val_loss: 1.0781591816952354
epochs 26/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0723339319229126, val_loss: 1.0781164106569792
epochs 27/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0718558336559094, val_loss: 1.0780737964730513
epochs 28/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0727400528757196, val_loss: 1.0780309501447176
epochs 29/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0728141194895695, val_loss: 1.0779882418481928
epochs 30/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0714499824925472, val_loss: 1.0779456151159186
epochs 31/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0718786340010793, val_loss: 1.077903057399549
epochs 32/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.072208749620538, val_loss: 1.0778604432156211
epochs 33/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0722206580011469, val_loss: 1.0778178729509051
epochs 34/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0718323870709068, val_loss: 1.0777751709285535
epochs 35/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.072019332333615, val_loss: 1.0777323998902972
epochs 36/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0718884844529002, val_loss: 1.077689572384483
epochs 37/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.072023253691824, val_loss: 1.0776473911185014
epochs 38/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.071968718578941, val_loss: 1.077605178481654
epochs 39/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.071377195810017, val_loss: 1.0775625893944187
epochs 40/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0727202515853078, val_loss: 1.0775200254038761
epochs 41/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0720042115763615, val_loss: 1.0774773861232556
epochs 42/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0722955214349847, val_loss: 1.0774348095843667
epochs 43/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0711466387698525, val_loss: 1.077392484012403
epochs 44/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0713712918130975, val_loss: 1.0773502776497288
epochs 45/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0716195482956736, val_loss: 1.0773078830618608
epochs 46/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0709929842697947, val_loss: 1.077265224958721
epochs 47/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0705941978253817, val_loss: 1.07722260450062
epochs 48/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.070979024234571, val_loss: 1.077180078155116
epochs 49/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0715014809056331, val_loss: 1.0771373949552838
epochs 50/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.071661811125906, val_loss: 1.0770948686097797
epochs 51/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0717188057146574, val_loss: 1.077052066200658
epochs 52/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.07134463285145, val_loss: 1.0770092826140554
epochs 53/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0706356450131065, val_loss: 1.0769664300115485
epochs 54/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0716576764458103, val_loss: 1.076923552312349
epochs 55/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0710730615415072, val_loss: 1.0768806118714183
epochs 56/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0713234010495638, val_loss: 1.07683737654435
epochs 57/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.070721525894968, val_loss: 1.0767943859100342
epochs 58/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.071421560488249, val_loss: 1.0767511819538318
epochs 59/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0705730224910535, val_loss: 1.076708109755265
epochs 60/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0709408082460101, val_loss: 1.0766652320560657
epochs 61/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0705647656792088, val_loss: 1.0766223167118274
epochs 62/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0701616688778526, val_loss: 1.0765794013675891
epochs 63/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0711013517881696, val_loss: 1.076536730716103
epochs 64/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0704848389876516, val_loss: 1.0764937902751721
epochs 65/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0706149904351485, val_loss: 1.076451257655495
epochs 66/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0713329377927279, val_loss: 1.0764084677947194
epochs 67/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.070479625149777, val_loss: 1.076365495982923
epochs 68/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0717871377342625, val_loss: 1.0763223798651445
epochs 69/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0706042490507428, val_loss: 1.0762793264890973
epochs 70/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0708581397407932, val_loss: 1.076236279387223
epochs 71/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0695061620913053, val_loss: 1.0761933013012535
epochs 72/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0698271738855463, val_loss: 1.0761504926179584
Starting fold 2:
epochs 1/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0731998180088245, val_loss: 1.098688194626256
epochs 2/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0733826380026967, val_loss: 1.0986569868890863
epochs 3/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0730478543984263, val_loss: 1.0986250701703524
epochs 4/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0733405633976585, val_loss: 1.098592902484693
epochs 5/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.073388027517419, val_loss: 1.0985607661698993
epochs 6/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0730427158506293, val_loss: 1.098528592210067
epochs 7/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0728367692545842, val_loss: 1.0984965249111778
epochs 8/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0725455346860384, val_loss: 1.098464708579214
epochs 9/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.071921091330679, val_loss: 1.0984328608763845
epochs 10/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0733589153540761, val_loss: 1.0984011637537103
epochs 11/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0723149588233547, val_loss: 1.0983696674045764
epochs 12/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0714707311831022, val_loss: 1.0983380267494602
epochs 13/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0721977572692067, val_loss: 1.098306561771192
epochs 14/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0725897707437213, val_loss: 1.0982753226631565
epochs 15/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0717264884396602, val_loss: 1.0982437510239451
epochs 16/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.07247992879466, val_loss: 1.0982122860456769
epochs 17/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0718327854809009, val_loss: 1.0981808336157548
epochs 18/72
Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0713057423892773, val_loss: 1.098149343540794
epochs 19/72

[I 2024-01-27 01:12:57,546] Trial 18 pruned.

Current Learning Rate: 1.0639661138136991e-06
train_loss: 1.0718636669610675, val_loss: 1.0981178660141795
epochs 20/72
Starting fold 1:
epochs 1/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1481077169117175, val_loss: 1.1652015660938464
epochs 2/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.148463729808205, val_loss: 1.164753418219717
epochs 3/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1493240042736657, val_loss: 1.1643056794216757
epochs 4/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.146612993039583, val_loss: 1.1638628457721911
epochs 5/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1447584578865453, val_loss: 1.1634213836569536
epochs 6/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1454452113101357, val_loss: 1.1629795099559583
epochs 7/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.14796050096813, val_loss: 1.162536859512329
epochs 8/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1450194233342221, val_loss: 1.162093354526319
epochs 9/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1441977074271754, val_loss: 1.1616483550322683
epochs 10/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.140699210919832, val_loss: 1.1612020254135131
epochs 11/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1460962885304502, val_loss: 1.1607578440716393
epochs 12/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1429961279818885, val_loss: 1.1603167822486475
epochs 13/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1419683192905628, val_loss: 1.1598764156040393
epochs 14/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1400117221631503, val_loss: 1.1594362936521831
epochs 15/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1440975716239528, val_loss: 1.1589961804841693
epochs 16/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.141825136385466, val_loss: 1.1585594378019635
epochs 17/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1447630543457834, val_loss: 1.1581206622876619
epochs 18/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.141424674736826, val_loss: 1.1576775902195982
epochs 19/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1397187358454655, val_loss: 1.157228698228535
epochs 20/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1389096975326538, val_loss: 1.1567796380896318
epochs 21/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1386028013731304, val_loss: 1.1563277119084407
epochs 22/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1370729408766094, val_loss: 1.1558760429683486
epochs 23/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1356271630839299, val_loss: 1.1554242485447934
epochs 24/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1381645240281757, val_loss: 1.154972999974301
epochs 25/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1376729538566188, val_loss: 1.1545224076823184
epochs 26/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1379370563908626, val_loss: 1.1540723524595562
epochs 27/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.136231491440221, val_loss: 1.1536254393426995
epochs 28/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.135197273053621, val_loss: 1.1531754468616686
epochs 29/107

[I 2024-01-27 01:12:59,135] Trial 19 pruned.

Current Learning Rate: 6.843159185131243e-05
train_loss: 1.137899331042641, val_loss: 1.152722359958448
epochs 30/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1335864380786294, val_loss: 1.15226410188173
epochs 31/107
Current Learning Rate: 6.843159185131243e-05
train_loss: 1.1361662588621442, val_loss: 1.1518050607882049
epochs 32/107
Starting fold 1:
epochs 1/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0972361859522368, val_loss: 1.0901648709648535
epochs 2/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0954705131681342, val_loss: 1.0899989768078453
epochs 3/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0967182247262253, val_loss: 1.0898384646365518
epochs 4/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0960341848825152, val_loss: 1.0896795881421943
epochs 5/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0962173963847914, val_loss: 1.0895221597269962
epochs 6/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0952214209656967, val_loss: 1.0893650381188644
epochs 7/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0956933548575953, val_loss: 1.0892083092739708
epochs 8/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0953573954732794, val_loss: 1.0890519713100635
epochs 9/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0954753405169437, val_loss: 1.0888958052585
epochs 10/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0949899729929473, val_loss: 1.088739672460054
epochs 11/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.09430652103926, val_loss: 1.0885838972894768
epochs 12/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.094958866269965, val_loss: 1.0884281923896388
epochs 13/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.093557105566326, val_loss: 1.0882729818946437
epochs 14/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0946872780197545, val_loss: 1.0881180255036604
epochs 15/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.093481893915879, val_loss: 1.0879636827268098
epochs 16/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0945309005285564, val_loss: 1.0878096291893407
epochs 17/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0924730928320634, val_loss: 1.0876554056217795
epochs 18/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.093794956332759, val_loss: 1.0875010277095594
epochs 19/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.094161437687121, val_loss: 1.0873470268751446
epochs 20/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0929052716807315, val_loss: 1.0871937569819
epochs 21/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0919073531502173, val_loss: 1.0870409482403804
epochs 22/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0920657070059525, val_loss: 1.0868876802293879
epochs 23/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.093036448955536, val_loss: 1.0867342930091055
epochs 24/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0918436508429679, val_loss: 1.0865811090720328
epochs 25/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0924180068467793, val_loss: 1.0864278918818424
epochs 26/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0918145644037347, val_loss: 1.0862753058734693
epochs 27/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0918862700462342, val_loss: 1.0861226163412396
epochs 28/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0914408696325202, val_loss: 1.0859707104532341
epochs 29/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0919045228707163, val_loss: 1.0858185661466497
epochs 30/94

[I 2024-01-27 01:13:00,642] Trial 20 pruned.

Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0910545512249594, val_loss: 1.0856660642121967
epochs 31/94
Current Learning Rate: 1.1972798446736142e-05
train_loss: 1.0905403538754113, val_loss: 1.0855136306662307
epochs 32/94
Starting fold 1:
epochs 1/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.1570071854089437, val_loss: 1.1647734328320152
epochs 2/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.150823117557325, val_loss: 1.1572109831006903
epochs 3/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.1450253072537875, val_loss: 1.1498112866753025
epochs 4/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.13477842054869, val_loss: 1.1423845284863523
epochs 5/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.1271746942871494, val_loss: 1.1348730884100262
epochs 6/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.121760624333432, val_loss: 1.1272528755037408
epochs 7/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.1142771771079616, val_loss: 1.11941792337518
epochs 8/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.1072289128052561, val_loss: 1.1113303611153051
epochs 9/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.1007960062277944, val_loss: 1.1029386081193622
epochs 10/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.091865336894989, val_loss: 1.0941450225679499
epochs 11/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0823418498039246, val_loss: 1.084954627564079
epochs 12/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0691511712576214, val_loss: 1.0752042789208263
epochs 13/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0655409687443784, val_loss: 1.0649367012475666
epochs 14/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.055954458839015, val_loss: 1.054470437451413
epochs 15/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.048682844011407, val_loss: 1.0439935288931195
epochs 16/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0338777322518198, val_loss: 1.033794049212807
epochs 17/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0321258930783523, val_loss: 1.0244368424541073
epochs 18/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0244516579728378, val_loss: 1.0165654605940768
epochs 19/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0092110589930885, val_loss: 1.0102856642321536
epochs 20/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0071727966007433, val_loss: 1.0057971032042252
epochs 21/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0052446086155742, val_loss: 1.0028414726257324
epochs 22/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0103357754255595, val_loss: 1.0010506576613376
epochs 23/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0016085477251755, val_loss: 0.9999263609710493
epochs 24/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9999501168727875, val_loss: 0.9991484720455973
epochs 25/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.997709941550305, val_loss: 0.9985369672900752
epochs 26/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.003902159552825, val_loss: 0.9980626583099366
epochs 27/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.000828550050133, val_loss: 0.9976547827846125
epochs 28/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9983504772186279, val_loss: 0.9972710772564537
epochs 29/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9956703744436565, val_loss: 0.9968925212558947
epochs 30/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0082306733256892, val_loss: 0.9965847021655032
epochs 31/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0066544990790518, val_loss: 0.9963341314541666
epochs 32/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9982564408528177, val_loss: 0.996071990540153
epochs 33/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9939697761284677, val_loss: 0.9957870342229542
epochs 34/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0030464144129503, val_loss: 0.9954928576946258
epochs 35/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9978896473583422, val_loss: 0.9952903302092301
epochs 36/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0024395211746817, val_loss: 0.9951046215860467
epochs 37/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9932123877500233, val_loss: 0.994941027227201
epochs 38/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9976481720020897, val_loss: 0.9947350385941958
epochs 39/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9896959919678537, val_loss: 0.9945423348953849
epochs 40/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9936259125408373, val_loss: 0.9942898957352889
epochs 41/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0018351787015012, val_loss: 0.9941482136124059
epochs 42/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9969743681581397, val_loss: 0.994071311386008
epochs 43/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0011164044079028, val_loss: 0.9940197649754976
epochs 44/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.004398446020327, val_loss: 0.9940164882885782
epochs 45/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0021056065433904, val_loss: 0.9939996885625939
epochs 46/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0012910425662995, val_loss: 0.9939700691323531
epochs 47/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9890728743452775, val_loss: 0.9939517993676035
epochs 48/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.998682048132545, val_loss: 0.9939503814044751
epochs 49/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9963847088186364, val_loss: 0.9939310952236778
epochs 50/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0093327983429556, val_loss: 0.9939874900014777
epochs 51/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0069203474019703, val_loss: 0.9941045607391157
epochs 52/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9973012224624032, val_loss: 0.9941724325481214
epochs 53/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9966689724671213, val_loss: 0.9941484335221742
epochs 54/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0052939562421097, val_loss: 0.9941332330829219
epochs 55/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9996787469638021, val_loss: 0.9940547384713826
epochs 56/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.993454310768529, val_loss: 0.9939583445850172
epochs 57/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9980078305068769, val_loss: 0.9938740291093525
epochs 58/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0013330942706058, val_loss: 0.9937860523399554
epochs 59/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9999789721087405, val_loss: 0.9937134821163981
epochs 60/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0061412723440872, val_loss: 0.99361704682049
epochs 61/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9940531815353193, val_loss: 0.9935661250039151
epochs 62/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9982161186243358, val_loss: 0.9935345806573567
epochs 63/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0081108253253133, val_loss: 0.9935139960364292
epochs 64/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.998823743117483, val_loss: 0.9935133987351468
epochs 65/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9977647047293814, val_loss: 0.9935116607891886
epochs 66/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.00209296753532, val_loss: 0.9934965839511469
epochs 67/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9946830492270621, val_loss: 0.9934782197600917
epochs 68/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0014505075780968, val_loss: 0.9934885181878742
epochs 69/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0085835961919083, val_loss: 0.9935800982149023
epochs 70/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.003067712407363, val_loss: 0.9937496238633206
epochs 71/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9967022842482517, val_loss: 0.9938723542188344
epochs 72/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0001354572020078, val_loss: 0.993937631657249
epochs 73/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9958610795046153, val_loss: 0.9938849991873691
epochs 74/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9976365252545005, val_loss: 0.9938081917009856
epochs 75/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0067258574460682, val_loss: 0.9937929714980879
epochs 76/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0022498375491091, val_loss: 0.9937869360572413
epochs 77/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0112865444860961, val_loss: 0.9938299546116277
epochs 78/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9989165337462175, val_loss: 0.9938831937940498
epochs 79/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0010022935114409, val_loss: 0.9939164999284242
epochs 80/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0027179689783798, val_loss: 0.9939250177458713
epochs 81/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.003076604165529, val_loss: 0.9939244900879107
epochs 82/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.006562749649349, val_loss: 0.9939408961095308
epochs 83/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9994412233954981, val_loss: 0.9939144645866594
epochs 84/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9961650515857495, val_loss: 0.9938474256741373
epochs 85/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0013628840446471, val_loss: 0.9937979146053917
epochs 86/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.993111746248446, val_loss: 0.9937240487650821
epochs 87/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0040278434753418, val_loss: 0.9936884265196951
epochs 88/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.003458050363942, val_loss: 0.9937269988812898
epochs 89/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9964763882913088, val_loss: 0.9938038302095313
epochs 90/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9950451091716164, val_loss: 0.9937972981678812
epochs 91/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.998283692096409, val_loss: 0.9937513721616644
epochs 92/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9981668920893418, val_loss: 0.9937003349003038
epochs 93/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.998710036277771, val_loss: 0.993630313873291
epochs 94/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9962958505279139, val_loss: 0.9935751748712439
epochs 95/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0044230834433907, val_loss: 0.9935733729287197
Starting fold 2:
epochs 1/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.000875084180581, val_loss: 1.1329724368296172
epochs 2/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9994625563684263, val_loss: 1.1291951518309744
epochs 3/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9934456978973589, val_loss: 1.127070078724309
epochs 4/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9932704106757515, val_loss: 1.1250898925881636
epochs 5/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.989799354892028, val_loss: 1.1239561353859149
epochs 6/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.990731648394936, val_loss: 1.1226833412521764
epochs 7/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.997858411701102, val_loss: 1.1214744784330066
epochs 8/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9951614822212018, val_loss: 1.1201149582862855
epochs 9/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9990558227426127, val_loss: 1.118410005381233
epochs 10/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.995531637574497, val_loss: 1.1174184843113548
epochs 11/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9911671307526136, val_loss: 1.1171628553616373
epochs 12/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9917586525804118, val_loss: 1.1174061069363042
epochs 13/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9921989961674339, val_loss: 1.1177274418504615
epochs 14/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9971338617174249, val_loss: 1.1173737027143178
epochs 15/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9940387186251188, val_loss: 1.1166777811552349
epochs 16/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9995814431654779, val_loss: 1.115310114622116
epochs 17/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.994462190960583, val_loss: 1.1145284712314605
epochs 18/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9949461711080451, val_loss: 1.1144562947122674
epochs 19/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9907737046480178, val_loss: 1.1149849885388425
epochs 20/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9967578696577173, val_loss: 1.1150415561701121
epochs 21/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9950183495094902, val_loss: 1.1149636560364773
epochs 22/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9975981045710413, val_loss: 1.1149233152991846
epochs 23/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9923628999998695, val_loss: 1.1147594229171152
epochs 24/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9926917331783395, val_loss: 1.1144746369437168
epochs 25/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9929405008491717, val_loss: 1.1144920521660855
epochs 26/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9971472889184951, val_loss: 1.1144584894180298
epochs 27/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9937731786778099, val_loss: 1.113450780354048
epochs 28/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9932572907523105, val_loss: 1.1127518070371527
epochs 29/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9957420410294282, val_loss: 1.1118593162611912
epochs 30/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9941926722463809, val_loss: 1.111247605085373
epochs 31/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9960762450569555, val_loss: 1.1103651799653707
epochs 32/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9908305709299289, val_loss: 1.109120920457338
epochs 33/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9896376095320049, val_loss: 1.108877865577999
epochs 34/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9943786522275523, val_loss: 1.1076534807682037
epochs 35/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9851816031493639, val_loss: 1.1057651579380035
epochs 36/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9926929655827974, val_loss: 1.1036953242201555
epochs 37/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9855610373773073, val_loss: 1.1010100358410886
epochs 38/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.989879636388076, val_loss: 1.0966782751836275
epochs 39/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9871701612284309, val_loss: 1.090691971465161
epochs 40/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9785653735461988, val_loss: 1.0857466638088227
epochs 41/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9776731353057059, val_loss: 1.0807136705047207
epochs 42/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9883505236161383, val_loss: 1.0769839101716092
epochs 43/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9785649712148465, val_loss: 1.0748381671152616
epochs 44/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9741603264683172, val_loss: 1.0750829345301578
epochs 45/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9709816644066258, val_loss: 1.0795858828645004
epochs 46/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9627971754262322, val_loss: 1.0830421748914216
epochs 47/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9641715681866596, val_loss: 1.0874709311284516
epochs 48/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9651317185477206, val_loss: 1.0871741978745713
epochs 49/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.961940597546728, val_loss: 1.088652691715642
epochs 50/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9600020896447332, val_loss: 1.087681531906128
epochs 51/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9526692696307835, val_loss: 1.0877624235655132
epochs 52/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9594783053586358, val_loss: 1.0890847112003126
epochs 53/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9580790642060731, val_loss: 1.0898596418531317
epochs 54/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9626656871092947, val_loss: 1.0910826337964912
epochs 55/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9541749731490486, val_loss: 1.0906040561826607
epochs 56/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9563492227541773, val_loss: 1.0907963231990212
epochs 57/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.950585306004474, val_loss: 1.091220296056647
epochs 58/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9628793835639954, val_loss: 1.091813366036666
epochs 59/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9610771899160586, val_loss: 1.090293310190502
epochs 60/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9492160947699296, val_loss: 1.0886363763558238
epochs 61/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9531158464519601, val_loss: 1.0903420649076763
epochs 62/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9562436997890472, val_loss: 1.0907832741737367
epochs 63/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.952791241752474, val_loss: 1.0902923163614775
epochs 64/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9468895846291592, val_loss: 1.0922665439153973
epochs 65/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9512625847992144, val_loss: 1.0925677098725972
epochs 66/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9494716609779157, val_loss: 1.0906748752844961
epochs 67/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9500210336948696, val_loss: 1.0918901725819237
epochs 68/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.951617745976699, val_loss: 1.091930073185971
epochs 69/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9446928836797414, val_loss: 1.0924029883585478
epochs 70/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.954074774290386, val_loss: 1.0943406920684011
epochs 71/95
Current Learning Rate: 0.0003278964463346113
train_loss: 0.9503418437744442, val_loss: 1.0935998709578263
epochs 72/95

[I 2024-01-27 01:13:51,463] Trial 21 finished with value: 1.0725992555994734 and parameters: {'batch_size': 39, 'epochs': 95, 'hidden_size': 28, 'learning_rate': 0.0003278964463346113, 'dropout_prob': 0.14145831654644206, 'weight_decay': 0.0009921223812580742, 'lr_step_size': 37, 'gamma': 0.1093779113711891, 'conv_channels': 61, 'kernel_size': 5, 'num_layers': 5, 'pool_size': 3, 'stride': 4}. Best is trial 21 with value: 1.0725992555994734.

Current Learning Rate: 3.922798151539792e-06
train_loss: 1.0040638631895968, val_loss: 1.112731889674538
Mean validation loss: 1.0725992555994734
Starting fold 1:
epochs 1/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.1184599907774675, val_loss: 1.3146468338213468
epochs 2/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.168384278134296, val_loss: 0.9996677558673056
epochs 3/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0250071475380345, val_loss: 0.9996982966598712
epochs 4/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0088277637958527, val_loss: 0.9979663698296798
epochs 5/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0031071352331262, val_loss: 0.9934302257864098
epochs 6/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0044015009152263, val_loss: 0.9976735557380475
epochs 7/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0100565684469123, val_loss: 0.993579880187386
epochs 8/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0129853248596192, val_loss: 0.9939981808787898
epochs 9/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0114545329620963, val_loss: 0.9928173463595541
epochs 10/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0085667999167192, val_loss: 0.9926956468506863
epochs 11/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0094870859070828, val_loss: 0.9952507605678157
epochs 12/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0085559223827563, val_loss: 0.9917956223613338
epochs 13/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.007861739397049, val_loss: 0.9916178593510075
epochs 14/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0038823422632719, val_loss: 0.9941018559430775
epochs 15/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0058100392943934, val_loss: 0.9917443517007326
epochs 16/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0039476595426862, val_loss: 0.9911846440089377
epochs 17/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0069767082992354, val_loss: 0.9933481737187034
epochs 18/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.00326392242783, val_loss: 0.9911704712792446
epochs 19/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0030634848695053, val_loss: 0.9902278934654437
epochs 20/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0029474857606386, val_loss: 0.9925102001742313
epochs 21/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0025819163573415, val_loss: 0.9922305684340628
epochs 22/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0006011184893155, val_loss: 0.9907707518652866
epochs 23/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0007355059448042, val_loss: 0.9899907284661343
epochs 24/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9998333761566564, val_loss: 0.9903473386639043
epochs 25/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0007619685248326, val_loss: 0.9928336802281832
epochs 26/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.99930749912011, val_loss: 0.9940430205119284
epochs 27/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0011137626673046, val_loss: 0.9924056536272953
epochs 28/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9994228949672297, val_loss: 0.9923123441244427
epochs 29/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0030766082437415, val_loss: 0.9934804517971841
epochs 30/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0022665478681263, val_loss: 0.990553973850451
epochs 31/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.001027582821093, val_loss: 0.9908030001740706
epochs 32/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.001777969849737, val_loss: 0.9937109853091993
epochs 33/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.00017327823137, val_loss: 0.9940175705834439
epochs 34/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9998967597359105, val_loss: 0.9926511090052755
epochs 35/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9997950368805936, val_loss: 0.9917671523596111
epochs 36/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9997887357285148, val_loss: 0.9923030931698649
epochs 37/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.000015058956648, val_loss: 0.9923640856617375
epochs 38/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0010429997193186, val_loss: 0.9945238784739846
epochs 39/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9999818042704933, val_loss: 0.9940884314085308
epochs 40/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.000401117613441, val_loss: 0.9933182603434513
epochs 41/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9996350395052056, val_loss: 0.9927843875006626
epochs 42/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0004537478873605, val_loss: 0.9922891604272943
epochs 43/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.99981241759501, val_loss: 0.9919505417346954
epochs 44/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9997761431493257, val_loss: 0.9921711711507094
epochs 45/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0001332257923328, val_loss: 0.9923601627349854
epochs 46/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.000854198869906, val_loss: 0.9931531661435178
epochs 47/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0000732459520039, val_loss: 0.9936504097361314
epochs 48/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9996783940415633, val_loss: 0.9932310399256254
epochs 49/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9997883859433626, val_loss: 0.992132115050366
epochs 50/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9997024046747308, val_loss: 0.9920847255932658
epochs 51/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9998285387691699, val_loss: 0.9926755465959248
epochs 52/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9998497200639624, val_loss: 0.9928336962273246
epochs 53/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9998224465470565, val_loss: 0.9933798071585204
epochs 54/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9998794213721627, val_loss: 0.9940711539042624
epochs 55/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0001211326373252, val_loss: 0.9938445922575498
epochs 56/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9995410875270241, val_loss: 0.9926508561560982
epochs 57/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9998225089750792, val_loss: 0.9925100712399734
epochs 58/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9997972579378831, val_loss: 0.9926599860191345
epochs 59/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9998859606291118, val_loss: 0.9927623792698509
epochs 60/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9997819982076946, val_loss: 0.9928218421183135
epochs 61/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9997625827789307, val_loss: 0.9928905763124165
epochs 62/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.999681304003063, val_loss: 0.9929567914260061
epochs 63/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9997298482217287, val_loss: 0.992944536083623
epochs 64/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9996775304016314, val_loss: 0.9927534150449853
epochs 65/76
Epoch 00065: reducing learning rate of group 0 to 1.4873e-02.
Current Learning Rate: 0.014873305611801536
train_loss: 0.9997600994612041, val_loss: 0.9927483684138247
epochs 66/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.9979460214313708, val_loss: 0.9927669725920024
epochs 67/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.9979801203075208, val_loss: 0.992795550509503
epochs 68/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.997987102834802, val_loss: 0.9928320432964124
epochs 69/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.9979616711014195, val_loss: 0.9928628720735249
epochs 70/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.997952872201016, val_loss: 0.9929086358923661
epochs 71/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.9979377730896598, val_loss: 0.992941667531666
epochs 72/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.9979176132302535, val_loss: 0.9929453272568552
epochs 73/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.9979137141453592, val_loss: 0.9929400716957293
epochs 74/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.9979093172048268, val_loss: 0.9929389392074786
epochs 75/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.9978837176373131, val_loss: 0.9929402715281437
epochs 76/76
Current Learning Rate: 0.014873305611801536
train_loss: 0.997872501298001, val_loss: 0.9929307699203491
Starting fold 2:
epochs 1/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.1324409964837525, val_loss: 1.0911793012368052
epochs 2/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0137564165027517, val_loss: 1.113346318822158
epochs 3/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0241543791796033, val_loss: 1.1045088372732463
epochs 4/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0125608124231038, val_loss: 1.104392287605687
epochs 5/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0016914326893656, val_loss: 1.1081771976069401
epochs 6/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0022320419549942, val_loss: 1.096365269234306
epochs 7/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.010851099616603, val_loss: 1.106278467805762
epochs 8/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0082528799772263, val_loss: 1.113840308001167
epochs 9/76
Current Learning Rate: 0.07805253881073754
train_loss: 1.0119226269031827, val_loss: 1.104393656630265
epochs 10/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9990081656920282, val_loss: 1.1114207001108871
epochs 11/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9970380301538266, val_loss: 1.1095869334120498
epochs 12/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9966235850986681, val_loss: 1.1125692370690798
epochs 13/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.997899738581557, val_loss: 1.1141869871239913
epochs 14/76
Current Learning Rate: 0.07805253881073754
train_loss: 0.9961377721083792, val_loss: 1.109694118248789
epochs 15/76

[I 2024-01-27 01:13:57,282] Trial 22 pruned.

Current Learning Rate: 0.07805253881073754
train_loss: 0.9960882916262276, val_loss: 1.112464672954459
epochs 16/76
Starting fold 1:
epochs 1/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.096008475203263, val_loss: 1.0285240637628656
epochs 2/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.045541094478808, val_loss: 0.9968785762786865
epochs 3/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0005874997691104, val_loss: 0.9884346974523444
epochs 4/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0003988993795294, val_loss: 0.9881737483175177
epochs 5/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0090683253187882, val_loss: 0.9902554135573538
epochs 6/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0040628031680459, val_loss: 0.9917647938979299
epochs 7/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0032682299613953, val_loss: 0.9931007623672485
epochs 8/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0035134698215284, val_loss: 0.992974645213077
epochs 9/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0025506954444081, val_loss: 0.992246897597062
epochs 10/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0071747422218322, val_loss: 0.9912363968397442
epochs 11/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0062951194612604, val_loss: 0.9908266807857312
epochs 12/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9996072838180944, val_loss: 0.990801927917882
epochs 13/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0054206070147063, val_loss: 0.990995232682479
epochs 14/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0036718638319717, val_loss: 0.9911334953810039
epochs 15/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9991565321621142, val_loss: 0.9909688874294883
epochs 16/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0028197395174128, val_loss: 0.9905602292010659
epochs 17/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9987636898693285, val_loss: 0.9899055142151681
epochs 18/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0036297402883831, val_loss: 0.9901306541342484
epochs 19/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9988986322754307, val_loss: 0.9904535908448069
epochs 20/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0029296818532443, val_loss: 0.9906970626429508
epochs 21/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.998141496432455, val_loss: 0.9905229267321135
epochs 22/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.007460337563565, val_loss: 0.990926678557145
epochs 23/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0038518497818394, val_loss: 0.9913106504239534
epochs 24/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0016403574692576, val_loss: 0.9914617162001761
epochs 25/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9996178721126757, val_loss: 0.9913414290076807
epochs 26/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0045574570956983, val_loss: 0.9913797177766499
epochs 27/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9963736101200706, val_loss: 0.9914477724778025
epochs 28/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0075926159557542, val_loss: 0.9915395059083637
epochs 29/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9978532226462113, val_loss: 0.9912852011228862
epochs 30/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.001351274942097, val_loss: 0.9907190197392514
epochs 31/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.008359430338207, val_loss: 0.9905555536872462
epochs 32/97
Epoch 00032: reducing learning rate of group 0 to 3.3613e-03.
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0013219042828208, val_loss: 0.9905879560269808
epochs 33/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.003139737405275, val_loss: 0.9903326348254555
epochs 34/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9977703025466518, val_loss: 0.9899369980159559
epochs 35/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.002765255225332, val_loss: 0.9896226719806068
epochs 36/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0011540958755896, val_loss: 0.9895622479288202
epochs 37/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9977966534463982, val_loss: 0.9897480036083021
epochs 38/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0015250551073174, val_loss: 0.9899925633480674
epochs 39/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9994840828995956, val_loss: 0.990265961697227
epochs 40/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0045453441770453, val_loss: 0.9903654336929322
epochs 41/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9967809212835211, val_loss: 0.9904487572218242
epochs 42/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.002892930256693, val_loss: 0.9904468925375688
epochs 43/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9996090845057839, val_loss: 0.99038724899292
epochs 44/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9961130801000093, val_loss: 0.9901686467622456
epochs 45/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0067066079691838, val_loss: 0.9900674456044247
epochs 46/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.005456524773648, val_loss: 0.990086599400169
epochs 47/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9985235327168515, val_loss: 0.9901475341696488
epochs 48/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9980953599277296, val_loss: 0.9900838977412174
epochs 49/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0025479699435986, val_loss: 0.9899871587753296
epochs 50/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0010919658761275, val_loss: 0.9900215839084826
epochs 51/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0008481508807132, val_loss: 0.9900188144884612
epochs 52/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0069762436967147, val_loss: 0.9900509859386243
epochs 53/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0034655050227517, val_loss: 0.990011339438589
epochs 54/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0000135390382063, val_loss: 0.9900262280514366
epochs 55/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9994947377004122, val_loss: 0.9901548849908929
epochs 56/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0030561629094576, val_loss: 0.9901845191654406
epochs 57/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9995956728332921, val_loss: 0.9901545022663317
epochs 58/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.0004324737348054, val_loss: 0.9902191199754414
epochs 59/97
Current Learning Rate: 0.0033612598157425743
train_loss: 1.001392932942039, val_loss: 0.9902765236402813
epochs 60/97
Epoch 00060: reducing learning rate of group 0 to 1.9925e-03.
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0016725000582243, val_loss: 0.9903353214263916
epochs 61/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9976873266069513, val_loss: 0.9903143292979191
epochs 62/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9980176655869735, val_loss: 0.9902184636969316
epochs 63/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9969255591693678, val_loss: 0.9900973181975515
epochs 64/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0018630812042637, val_loss: 0.9898664148230302
epochs 65/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.001351251100239, val_loss: 0.9896556666022853
epochs 66/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0008687213847511, val_loss: 0.9895274852451525
epochs 67/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0027663914780869, val_loss: 0.9895992053182502
epochs 68/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.995613862338819, val_loss: 0.9897198212774176
epochs 69/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0001854802432812, val_loss: 0.9897338641317267
epochs 70/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0025476098060608, val_loss: 0.9897527230413337
epochs 71/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.005663531704953, val_loss: 0.9898875236511231
epochs 72/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0019617419493825, val_loss: 0.9900276234275416
epochs 73/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0013793349266051, val_loss: 0.9901256912632992
epochs 74/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.997654556600671, val_loss: 0.9901297368501362
epochs 75/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9967053858857405, val_loss: 0.9900331660320885
epochs 76/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0029459677244488, val_loss: 0.9899888703697606
epochs 77/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0012578292896872, val_loss: 0.9900049033917879
epochs 78/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.997706001055868, val_loss: 0.990033759568867
epochs 79/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9976391660539727, val_loss: 0.9899962952262477
epochs 80/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9984462832149706, val_loss: 0.9899278163909913
epochs 81/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0014061199991326, val_loss: 0.9898778024472689
epochs 82/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0016506464857804, val_loss: 0.989865339429755
epochs 83/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9986808952532317, val_loss: 0.9898342057278282
epochs 84/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0048857180695785, val_loss: 0.9898055453049509
epochs 85/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9972989678382873, val_loss: 0.9898399553800884
epochs 86/97
Current Learning Rate: 0.0019925005457065905
train_loss: 1.0013455290543405, val_loss: 0.9898527283417551
epochs 87/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9984174144895454, val_loss: 0.9898444075333445
epochs 88/97
Epoch 00088: reducing learning rate of group 0 to 1.1811e-03.
Current Learning Rate: 0.0011811221512979025
train_loss: 0.9982079336517735, val_loss: 0.9898457853417647
epochs 89/97
Current Learning Rate: 0.0011811221512979025
train_loss: 1.00079805537274, val_loss: 0.9898486400905409
epochs 90/97
Current Learning Rate: 0.0011811221512979025
train_loss: 1.004621754821978, val_loss: 0.9898498095964131
epochs 91/97
Current Learning Rate: 0.0011811221512979025
train_loss: 0.9993028948181554, val_loss: 0.9898697087639257
epochs 92/97
Current Learning Rate: 0.0011811221512979025
train_loss: 0.9995567321777343, val_loss: 0.9898377079712717
epochs 93/97
Current Learning Rate: 0.0011811221512979025
train_loss: 1.0000179755060297, val_loss: 0.9897854265413786
epochs 94/97
Current Learning Rate: 0.0011811221512979025
train_loss: 1.001401776389072, val_loss: 0.9897259473800659
epochs 95/97
Current Learning Rate: 0.0011811221512979025
train_loss: 0.9992040521220157, val_loss: 0.9896670416781777
epochs 96/97
Current Learning Rate: 0.0011811221512979025
train_loss: 0.9982452216901277, val_loss: 0.9896511215912668
epochs 97/97
Current Learning Rate: 0.0011811221512979025
train_loss: 0.9967198729515075, val_loss: 0.9896416902542114
Starting fold 2:
epochs 1/97
Current Learning Rate: 0.0056702958366915916
train_loss: 1.0240062782638952, val_loss: 1.1044923832542017
epochs 2/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.997298821022636, val_loss: 1.0980868540312114
epochs 3/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9998166994044655, val_loss: 1.1093879084838063
epochs 4/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9955602739986621, val_loss: 1.115197763944927
epochs 5/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9932530421959727, val_loss: 1.1140546321868896
epochs 6/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9963621271284003, val_loss: 1.1118969038913125
epochs 7/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9912130311915749, val_loss: 1.1135834618618614
epochs 8/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9942757775909022, val_loss: 1.115484272806268
epochs 9/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9935206802267778, val_loss: 1.1154643774032593
epochs 10/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9975989812298824, val_loss: 1.1124076052715903
epochs 11/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9942836203073201, val_loss: 1.111759204613535
epochs 12/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9947490679590325, val_loss: 1.113522343886526
epochs 13/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9942879689367194, val_loss: 1.1136251361746536
epochs 14/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9968109055569297, val_loss: 1.1126592912172015
epochs 15/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9926310137698525, val_loss: 1.1132398592798334
epochs 16/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9945688768437034, val_loss: 1.113882871678001
epochs 17/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.995231923304106, val_loss: 1.1132576704025268
epochs 18/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9936137582126416, val_loss: 1.114560573979428
epochs 19/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9909515368311028, val_loss: 1.1140072621797261
epochs 20/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9930655391592729, val_loss: 1.115035323092812
epochs 21/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9917138551410876, val_loss: 1.1165334011379042
epochs 22/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9938214233047084, val_loss: 1.1148929595947266
epochs 23/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9949959723572982, val_loss: 1.1132543363069234
epochs 24/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9938450650164955, val_loss: 1.11308879601328
epochs 25/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9928084718553644, val_loss: 1.1138173969168412
epochs 26/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9915407933686909, val_loss: 1.1158820654216566
epochs 27/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9949807807018882, val_loss: 1.1131457981310393
epochs 28/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9934097679037797, val_loss: 1.1121129688463713
epochs 29/97
Current Learning Rate: 0.0056702958366915916
train_loss: 0.9958416129413404, val_loss: 1.112248178532249
epochs 30/97
Epoch 00030: reducing learning rate of group 0 to 3.3613e-03.
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9928459669414319, val_loss: 1.1144632050865575
epochs 31/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9910642410579481, val_loss: 1.1164135067086471
epochs 32/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9943797525606657, val_loss: 1.1165431662609702
epochs 33/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9943295761158591, val_loss: 1.114733816448011
epochs 34/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9928751976866471, val_loss: 1.1142388368907727
epochs 35/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.995020770399194, val_loss: 1.1147091037348698
epochs 36/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9931659152633265, val_loss: 1.1152639765488475
epochs 37/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9911285965066207, val_loss: 1.1165774332849603
epochs 38/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.992336820928674, val_loss: 1.116800130041022
epochs 39/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9928484703365125, val_loss: 1.116021428610149
epochs 40/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9949857931388052, val_loss: 1.115095722047906
epochs 41/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9930976497499566, val_loss: 1.114630803308989
epochs 42/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9907476651041132, val_loss: 1.115386276496084
epochs 43/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.994470759441978, val_loss: 1.1158209524656597
epochs 44/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9912767680067766, val_loss: 1.1162329385155125
epochs 45/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9930137295471995, val_loss: 1.11642644405365
epochs 46/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9942732509813811, val_loss: 1.1156188500554938
epochs 47/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9929507173989949, val_loss: 1.1149124547054894
epochs 48/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9925862080172488, val_loss: 1.115016884552805
epochs 49/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9936476682361803, val_loss: 1.1150590093512285
epochs 50/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9923120021820069, val_loss: 1.1157071615520278
epochs 51/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9921150013020165, val_loss: 1.116291332244873
epochs 52/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9921306942638598, val_loss: 1.1163985001413446
epochs 53/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9938726387525859, val_loss: 1.1153396656638697
epochs 54/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9952478440184342, val_loss: 1.1142097460596185
epochs 55/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9916578424604315, val_loss: 1.1150893462331672
epochs 56/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.991219837414591, val_loss: 1.1165013614453767
epochs 57/97
Current Learning Rate: 0.0033612598157425743
train_loss: 0.9931639138020967, val_loss: 1.1169915625923559
epochs 58/97
Epoch 00058: reducing learning rate of group 0 to 1.9925e-03.
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9937798612996152, val_loss: 1.115894335194638
epochs 59/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9925116476259733, val_loss: 1.115812991794787
epochs 60/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9928249930080615, val_loss: 1.115513573194805
epochs 61/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9904329011314794, val_loss: 1.1162181628377814
epochs 62/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.990327775478363, val_loss: 1.1177047867523997
epochs 63/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9920971588084572, val_loss: 1.1181916437650983
epochs 64/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.992079404153322, val_loss: 1.1180136931569953
epochs 65/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9942695561208224, val_loss: 1.1164406525461297
epochs 66/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9920357239873786, val_loss: 1.1154283975300037
epochs 67/97
Current Learning Rate: 0.0019925005457065905
train_loss: 0.9934987557561774, val_loss: 1.11502366065979
epochs 68/97
Current Learning Rate: 0.0019925005457065905

[I 2024-01-27 01:14:17,517] Trial 23 pruned.

Starting fold 1:
epochs 1/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1522886753082275, val_loss: 1.1521728873252868
epochs 2/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.152109146118164, val_loss: 1.1503965258598328
epochs 3/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1473880290985108, val_loss: 1.148645031452179
epochs 4/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1484215021133424, val_loss: 1.146907424926758
epochs 5/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1429500222206115, val_loss: 1.1451788425445557
epochs 6/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1450612664222717, val_loss: 1.143454670906067
epochs 7/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1409581899642944, val_loss: 1.1417362093925476
epochs 8/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1381697177886962, val_loss: 1.1400108933448792
epochs 9/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1362823367118835, val_loss: 1.1382665395736695
epochs 10/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1371373891830445, val_loss: 1.136505389213562
epochs 11/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1334335327148437, val_loss: 1.1347201824188233
epochs 12/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1340688467025757, val_loss: 1.1329384684562682
epochs 13/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1346250295639038, val_loss: 1.1311732411384583
epochs 14/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1330369353294372, val_loss: 1.1294056534767152
epochs 15/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1299991250038146, val_loss: 1.1276057481765747
epochs 16/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1254622101783753, val_loss: 1.1257752895355224
epochs 17/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1248538136482238, val_loss: 1.1238911390304565
epochs 18/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1267197966575622, val_loss: 1.1219955563545227
epochs 19/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1225473046302796, val_loss: 1.1201154589653015
epochs 20/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.120161783695221, val_loss: 1.1181881427764893
epochs 21/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1160544514656068, val_loss: 1.1162024855613708
epochs 22/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1179411649703979, val_loss: 1.1141571402549744
epochs 23/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1143444895744323, val_loss: 1.112073540687561
epochs 24/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1123867273330688, val_loss: 1.109942126274109
epochs 25/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1121065497398377, val_loss: 1.1078247666358947
epochs 26/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1080579042434693, val_loss: 1.1056836247444153
epochs 27/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1055456280708313, val_loss: 1.1034433960914611
epochs 28/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1066156864166259, val_loss: 1.1011633396148681
epochs 29/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.103540050983429, val_loss: 1.098823857307434
epochs 30/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.1000514388084413, val_loss: 1.0963845610618592
epochs 31/111
Current Learning Rate: 0.00013181339015927505
train_loss: 1.093903911113739, val_loss: 1.0938772439956665
epochs 32/111

[I 2024-01-27 01:14:19,675] Trial 24 pruned.

Number of finished trials: 25
Best trial:
Value: 1.0725992555994734
Params:
batch_size: 39
epochs: 95
hidden_size: 28
learning_rate: 0.0003278964463346113
dropout_prob: 0.14145831654644206
weight_decay: 0.0009921223812580742
lr_step_size: 37
gamma: 0.1093779113711891
conv_channels: 61
kernel_size: 5
num_layers: 5
pool_size: 3
stride: 4

In [376]:
trainer = ModelActioner(train_data, test_data, device, model_type)
model = trainer.train(trial.params)

epochs 1/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.089576555239527
epochs 2/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0769140507045545
epochs 3/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0646134042426159
epochs 4/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.057625372786271
epochs 5/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0531212317316156
epochs 6/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0531311609243093
epochs 7/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052690472885182
epochs 8/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0531987240439966
epochs 9/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0541629221878555
epochs 10/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0534992650935524
epochs 11/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0529172360897063
epochs 12/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0533094065754036
epochs 13/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0533976027840062
epochs 14/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.055806795546883
epochs 15/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0530416098080184
epochs 16/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0529599221129167
epochs 17/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0524285661546808
epochs 18/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0507175811027225
epochs 19/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0542023321515634
epochs 20/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0516630342132167
epochs 21/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0522225337593178
epochs 22/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052762357969033
epochs 23/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0537788456992099
epochs 24/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0536801584457096
epochs 25/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0527343182187332
epochs 26/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0533668935298919
epochs 27/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0536608757157075
epochs 28/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052400233243641
epochs 29/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052998077712561
epochs 30/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052207747258638
epochs 31/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0524818994496998
epochs 32/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0535486735795674
epochs 33/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0534154021426252
epochs 34/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0529437146688763
epochs 35/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0524253735416813
epochs 36/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0530244792762555
epochs 37/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052345596802862
epochs 38/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0526513455729736
epochs 39/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0516413125552628
epochs 40/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.051716174577412
epochs 41/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0519967963821009
epochs 42/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.053100157411475
epochs 43/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0513546195469405
epochs 44/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.051891384783544
epochs 45/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.053273834209693
epochs 46/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0501875593474037
epochs 47/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0524375499863374
epochs 48/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052920941459505
epochs 49/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052815136156584
epochs 50/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0518856337195948
epochs 51/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052999783973945
epochs 52/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0529029731687747
epochs 53/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0518626586387032
epochs 54/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0531468835316207
epochs 55/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0515670525400262
epochs 56/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0526601833732505
epochs 57/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0526027778261586
epochs 58/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0519150729242124
epochs 59/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0521586664413152
epochs 60/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0528507489907115
epochs 61/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0530001014471053
epochs 62/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.053420542572674
epochs 63/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0528461487669694
epochs 64/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0521810112815155
epochs 65/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0532999934334504
epochs 66/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052625828197128
epochs 67/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0510312750151283
epochs 68/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0510575405861202
epochs 69/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0520971106855492
epochs 70/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0528273552656173
epochs 71/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0524223150391327
epochs 72/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0522205471992492
epochs 73/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0527498543262481
epochs 74/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0529209792613983
epochs 75/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0544606492707604
epochs 76/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0512649843567297
epochs 77/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0528158885867973
epochs 78/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0537026728454388
epochs 79/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.054050714248105
epochs 80/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0528906063029642
epochs 81/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0514176920840614
epochs 82/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.052330352130689
epochs 83/95
Current Learning Rate: 0.0003278964463346113
train_loss: 1.0530875504016877
epochs 84/95
Epoch 00084: reducing learning rate of group 0 to 3.5865e-05.
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.0521349982211465
epochs 85/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.0506922775193264
epochs 86/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.0517884072504546
epochs 87/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.0529205560684205
epochs 88/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.0529690670339684
epochs 89/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.053337326175288
epochs 90/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.0527596042344445
epochs 91/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.0511428489496832
epochs 92/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.0516347847486798
epochs 93/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.050234784421168
epochs 94/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.053649703609316
epochs 95/95
Current Learning Rate: 3.586462844611498e-05
train_loss: 1.0509076479234194

In [377]:
preds = trainer.test(trial.params)
y_true = y_test[time_step:]

accuracy = accuracy_score(y_true, preds)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Precision
precision = precision_score(y_true, preds, average='weighted', zero_division=0)
print(f'Precision: {precision:.4f}')

# Recall
recall = recall_score(y_true, preds, average='weighted')
print(f'Recall: {recall:.4f}')

# F1 Score
f1 = f1_score(y_true, preds, average='weighted')
print(f'F1 Score: {f1:.4f}')

test_loss: 0.9543475097134
Accuracy: 63.89%
Precision: 0.4082
Recall: 0.6389
F1 Score: 0.4981

In [378]:
unique_elements = set(preds)
print(unique_elements)

{0}

In [379]:
y_true = y_true.reset_index(drop=True)
#y_true = y_true.drop(columns=["index","level_0"])
X_value = X_test_df.iloc[43:,-1]
X_value = X_value.reset_index()
preds_values = [x[0] for x in preds]
X_value["Preds"] = pd.Series(preds_values)
X_value["Next Day"] = y_true
X_value = X_value.drop(columns=["index"])
X_value["Diff Preds"] = (X_value["Preds"] - X_value["Adj Close"])
X_value["Diff Next Day"] = (X_value["Next Day"] - X_value["Adj Close"])
X_value = X_value.dropna()
X_value

IndexError: invalid index to scalar variable.

In [ ]:
def assign_label(diff):
    if diff > 0.0:
        return 1  # Buy
    elif diff < -0.01:
        return 0  # Sell
    else:
        return 2  # Hold/Other

In [ ]:
# Apply the function to assign labels
X_value['Signal Preds'] = X_value['Diff Preds'].apply(assign_label)
X_value['Signal True'] = X_value['Diff Next Day'].apply(assign_label)

# Dropping the intermediate difference columns if they are no longer needed
X_value = X_value.drop(columns=['Diff Preds', 'Diff Next Day'])

X_value

     Adj Close         Preds  Next Day  Signal Preds  Signal True
0     0.706173 -7.781130e-40  0.728267             0            1
1     0.728267 -7.781130e-40  0.737950             0            1
2     0.737950 -7.781130e-40  0.733381             0            2
3     0.733381 -7.781130e-40  0.747701             0            1
4     0.747701 -7.781130e-40  0.761134             0            1
..         ...           ...       ...           ...          ...
247   1.025207 -7.781130e-40  1.018693             0            2
248   1.018693 -7.781130e-40  1.059493             0            1
249   1.059493 -7.781130e-40  1.079584             0            1
250   1.079584 -7.781130e-40  1.095561             0            1
251   1.095561 -7.781130e-40  1.104406             0            1

[252 rows x 5 columns]

In [ ]:
accuracy = accuracy_score(X_value["Signal True"], X_value["Signal Preds"])
print(f'Accuracy: {accuracy * 100:.2f}%')

# Precision
precision = precision_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'Precision: {precision:.4f}')

# Recall
recall = recall_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'Recall: {recall:.4f}')

# F1 Score
f1 = f1_score(X_value["Signal True"], X_value["Signal Preds"], average='weighted')
print(f'F1 Score: {f1:.4f}')

Accuracy: 19.44%
Precision: 0.0378
Recall: 0.1944
F1 Score: 0.0633

/home/arda/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [ ]:
y_true

0      0.728267
1      0.737950
2      0.733381
3      0.747701
4      0.761134
         ...
247    1.018693
248    1.059493
249    1.079584
250    1.095561
251    1.104406
Name: Adj Close, Length: 252, dtype: float64

In [ ]:
X_value["Signal Preds"]

0      0
1      0
2      0
3      0
4      0
      ..
247    0
248    0
249    0
250    0
251    0
Name: Signal Preds, Length: 252, dtype: int64

In [ ]:
signals = pd.DataFrame(X_value["Signal Preds"].values, columns=['Signal'])
signals

     Signal
0         0
1         0
2         0
3         0
4         0
..      ...
247       0
248       0
249       0
250       0
251       0

[252 rows x 1 columns]

In [ ]:
signals["Signal"].value_counts()

Signal
0    252
Name: count, dtype: int64

In [ ]:
signals["Date"] = date_test
signals

     Signal       Date
0         0 2023-01-23
1         0 2023-01-24
2         0 2023-01-25
3         0 2023-01-26
4         0 2023-01-27
..      ...        ...
247       0 2024-01-17
248       0 2024-01-18
249       0 2024-01-19
250       0 2024-01-22
251       0 2024-01-23

[252 rows x 2 columns]

In [ ]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325668
1    141.737762
2    141.071487
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [ ]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
buy_signals = signals[signals['Signal'] == 1]
sell_signals = signals[signals['Signal'] == 0]

# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]

# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))

# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))

# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [ ]:
price_signal = stock_data[stock_data['Date'].isin(signals['Date'])]["Adj Close"]
price_signal = price_signal.reset_index()
price_signal = price_signal.drop(columns=["index"])
result = pd.concat([price_signal,signals], axis=1)
result

      Adj Close  Signal       Date
0    140.325668       0 2023-01-23
1    141.737762       0 2023-01-24
2    141.071487       0 2023-01-25
3    143.159805       0 2023-01-26
4    145.118851       0 2023-01-27
..          ...     ...        ...
247  182.679993       0 2024-01-17
248  188.630005       0 2024-01-18
249  191.559998       0 2024-01-19
250  193.889999       0 2024-01-22
251  195.179993       0 2024-01-23

[252 rows x 3 columns]

In [ ]:
price_signal

      Adj Close
0    140.325668
1    141.737762
2    141.071487
3    143.159805
4    145.118851
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [ ]:
sell_signals

     Signal       Date
0         0 2023-01-23
1         0 2023-01-24
2         0 2023-01-25
3         0 2023-01-26
4         0 2023-01-27
..      ...        ...
247       0 2024-01-17
248       0 2024-01-18
249       0 2024-01-19
250       0 2024-01-22
251       0 2024-01-23

[252 rows x 2 columns]

In [ ]:
buy_prices

Series([], Name: Adj Close, dtype: float64)