In [165]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import yfinance as yf
import talib
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.utils.data import Dataset, DataLoader, Subset
from sklearn.model_selection import train_test_split
import torch.optim as optim
import os
from sklearn.model_selection import TimeSeriesSplit

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, log_loss, mean_absolute_error, mean_squared_error, r2_score, mean_absolute_percentage_error
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as sch
import seaborn as sns

import optuna
from optuna.samplers import TPESampler
from optuna.trial import TrialState
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau 
import shap
import plotly.graph_objs as go
import plotly.offline as pyo
from tqdm.auto import tqdm
from sklearn.utils.class_weight import compute_class_weight

In [166]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print("gpu")
else:
    device = torch.device('cpu')
print(torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('CUDA version:', torch.version.cuda)
print('cuDNN version:', torch.backends.cudnn.version())

gpu
2.1.2+cu121
CUDA available: True
CUDA version: 12.1
cuDNN version: 8902

In [167]:
start_date = '2018-01-01'
end_date = '2024-01-24'

stock_data = yf.download("AAPL", start=start_date, end=end_date)[["Adj Close", "High", "Low", "Volume"]]

stock_data = stock_data.reset_index()

stock_data = stock_data[['Date', 'Adj Close', "High", "Low", "Volume"]]

stock_data = stock_data.sort_values(by="Date")
stock_data.head(45)

[*********************100%%**********************]  1 of 1 completed

         Date  Adj Close       High        Low     Volume
0  2018-01-02  40.722874  43.075001  42.314999  102223600
1  2018-01-03  40.715790  43.637501  42.990002  118071600
2  2018-01-04  40.904900  43.367500  43.020000   89738400
3  2018-01-05  41.370625  43.842499  43.262501   94640000
4  2018-01-08  41.216969  43.902500  43.482498   82271200
5  2018-01-09  41.212227  43.764999  43.352501   86336000
6  2018-01-10  41.202774  43.575001  43.250000   95839600
7  2018-01-11  41.436806  43.872501  43.622501   74670800
8  2018-01-12  41.864697  44.340000  43.912498  101672400
9  2018-01-16  41.651939  44.847500  44.035000  118263600
10 2018-01-17  42.339882  44.812500  43.767502  137547200
11 2018-01-18  42.377712  45.025002  44.562500  124773600
12 2018-01-19  42.188572  44.895000  44.352501  129700400
13 2018-01-22  41.843430  44.445000  44.150002  108434400
14 2018-01-23  41.852890  44.860001  44.205002  130756400
15 2018-01-24  41.186222  44.325001  43.299999  204420400
16 2018-01-25  40.451012  43.737499  42.632500  166116000
17 2018-01-26  40.545570  43.000000  42.514999  156572000
18 2018-01-29  39.706341  42.540001  41.767502  202561600
19 2018-01-30  39.472305  41.842499  41.174999  184192800
20 2018-01-31  39.581043  42.110001  41.625000  129915600
21 2018-02-01  39.663788  42.154999  41.689999  188923200
22 2018-02-02  37.942776  41.700001  40.025002  346375200
23 2018-02-05  36.994793  40.970001  39.000000  290954000
24 2018-02-06  38.540871  40.930000  38.500000  272975200
25 2018-02-07  37.715816  40.849998  39.767502  206434400
26 2018-02-08  36.678013  40.250000  38.757500  217562000
27 2018-02-09  37.126640  39.472500  37.560001  282690400
28 2018-02-12  38.622044  40.972500  39.377499  243278000
29 2018-02-13  39.008972  41.187500  40.412498  130196800
30 2018-02-14  39.728165  41.884998  40.720001  162579600
31 2018-02-15  41.062187  43.272499  42.250000  204588800
32 2018-02-16  40.929264  43.705002  42.942501  160704400
33 2018-02-20  40.791584  43.564999  42.855000  135722000
34 2018-02-21  40.606449  43.529999  42.752499  149886400
35 2018-02-22  40.945873  43.487499  42.927502  123967600
36 2018-02-23  41.657978  43.912498  43.384998  135249600
37 2018-02-26  42.481640  44.847500  44.052502  152648800
38 2018-02-27  42.343975  45.119999  44.540001  155712400
39 2018-02-28  42.279877  45.154999  44.512501  151128400
40 2018-03-01  41.539295  44.945000  43.165001  195208000
41 2018-03-02  41.826515  44.075001  43.112499  153816000
42 2018-03-05  41.971306  44.435001  43.630001  113605600
43 2018-03-06  41.935699  44.562500  44.032501   95154000
44 2018-03-07  41.546413  43.962502  43.567501  126814000

In [168]:
time_step = 44

In [169]:
test_index = int((len(stock_data)-44)*0.8+44+44)

In [170]:
date = stock_data["Date"].iloc[time_step:].dt.strftime('%Y-%m-%d')
date_test = stock_data["Date"].iloc[test_index:].reset_index()
date_test.drop(columns=["index"], inplace=True)
date_test

          Date
0   2023-01-23
1   2023-01-24
2   2023-01-25
3   2023-01-26
4   2023-01-27
..         ...
247 2024-01-17
248 2024-01-18
249 2024-01-19
250 2024-01-22
251 2024-01-23

[252 rows x 1 columns]

In [171]:
def add_technical_indicators(data, timeperiod=time_step):

    # MACD
    macd, macdsignal, macdhist = talib.MACD(data["Adj Close"], fastperiod=12, slowperiod=26, signalperiod=9)

    rsi = talib.RSI(data["Adj Close"], timeperiod=14)

    # CMO
    cmo = talib.CMO(data["Adj Close"], timeperiod=timeperiod)

    # MOM
    mom = talib.MOM(data["Adj Close"], timeperiod=timeperiod)

    # Bollinger Bands
    upperband, middleband, lowerband = talib.BBANDS(data["Adj Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # SMA
    sma_s = talib.SMA(data["Adj Close"], timeperiod=20)
    sma_l = talib.SMA(data["Adj Close"], timeperiod=50)

    # Calculate Exponential Moving Average (EMA)
    ema = talib.EMA(data["Adj Close"], timeperiod=timeperiod)

    # Calculate Stochastic Oscillator
    slowk, slowd = talib.STOCH(data['High'], data['Low'], data['Adj Close'], fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0)

    # Calculate Average True Range (ATR)
    atr = talib.ATR(data['High'], data['Low'], data['Adj Close'], timeperiod=14)

    # Calculate On-Balance Volume (OBV)
    obv = talib.OBV(data['Adj Close'], data['Volume'])

    # Combine all indicators into a DataFrame
    indicators = pd.DataFrame({
        'MACD': macd,
        'MACD_signal': macdsignal,
        'RSI': rsi,
        'CMO': cmo,
        'MOM': mom,
        'Upper_BB': upperband,
        'Middle_BB': middleband,
        'Lower_BB': lowerband,
        'SMA_SHORT': sma_s,
        'SMA_LONG': sma_l,
        'EMA': ema,
        'SLOWK': slowk,
        'SLOWD': slowd,
        'ATR': atr,
        'OBV': obv,

    })
    return indicators

In [172]:
indicators = add_technical_indicators(stock_data)
indicators.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0
14,NaN,NaN,68.998483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724165,117105600.0
15,NaN,NaN,55.580658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0
16,NaN,NaN,45.152430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695098,-253430800.0
17,NaN,NaN,46.541669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.817868,2.684662,-96858800.0
18,NaN,NaN,37.470339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639257,-81.393287,2.635359,-299420400.0
19,NaN,NaN,35.398304,NaN,NaN,42.761512,41.213177,39.664842,41.213177,NaN,NaN,-61.987786,-75.553866,2.599702,-483613200.0
20,NaN,NaN,37.137643,NaN,NaN,42.849896,41.156085,39.462274,41.156085,NaN,NaN,-49.633849,-63.086964,2.602416,-353697600.0
21,NaN,NaN,38.494694,NaN,NaN,42.910291,41.103485,39.296679,41.103485,NaN,NaN,-41.626480,-51.082705,2.600383,-164774400.0
22,NaN,NaN,25.947826,NaN,NaN,43.228468,40.955379,38.682290,40.955379,NaN,NaN,-40.766055,-44.008795,2.560085,-511149600.0
23,NaN,NaN,21.743753,NaN,NaN,43.578808,40.736587,37.894367,40.736587,NaN,NaN,-38.059391,-40.150642,2.593452,-802103600.0
24,NaN,NaN,39.079676,NaN,NaN,43.590203,40.602782,37.615362,40.602782,NaN,NaN,-24.766527,-34.530658,2.689292,-529128400.0
25,NaN,NaN,34.666297,NaN,NaN,43.652100,40.427962,37.203824,40.427962,NaN,NaN,-14.972504,-25.932808,2.662137,-735562800.0
26,NaN,NaN,30.066666,NaN,NaN,43.790970,40.201724,36.612478,40.201724,NaN,NaN,-13.427890,-17.722307,2.652998,-953124800.0
27,NaN,NaN,34.135080,NaN,NaN,43.765508,39.986216,36.206923,39.986216,NaN,NaN,-15.615498,-14.671964,2.663104,-670434400.0
28,NaN,NaN,45.513606,NaN,NaN,43.544884,39.824083,36.103282,39.824083,NaN,NaN,-6.294991,-11.779460,2.747587,-427156400.0
29,NaN,NaN,48.016017,NaN,NaN,43.330503,39.691935,36.053367,39.691935,NaN,NaN,11.072749,-3.612580,2.734577,-296959600.0
30,NaN,NaN,52.392681,NaN,NaN,42.991932,39.561349,36.130765,39.561349,NaN,NaN,26.336884,10.371547,2.744681,-134380000.0
31,NaN,NaN,59.246617,NaN,NaN,42.753750,39.495572,36.237395,39.495572,NaN,NaN,41.539671,26.316435,2.801799,70208800.0
32,NaN,NaN,58.345266,NaN,NaN,42.524614,39.432607,36.340600,39.432607,NaN,NaN,51.997573,39.958043,2.790443,-90495600.0
33,-0.373864,-0.940885,57.371660,NaN,NaN,42.339135,39.380015,36.420894,39.380015,NaN,NaN,56.241859,49.926368,2.779392,-226217600.0
34,-0.274209,-0.807550,56.018009,NaN,NaN,42.113880,39.317693,36.521505,39.317693,NaN,NaN,52.331393,53.523609,2.776465,-376104000.0
35,-0.165930,-0.679226,57.975721,NaN,NaN,42.071539,39.305675,36.539812,39.305675,NaN,NaN,52.421489,53.664914,2.783936,-252136400.0
36,-0.022399,-0.547860,61.815829,NaN,NaN,42.278023,39.366024,36.454024,39.366024,NaN,NaN,56.395118,53.716000,2.796985,-116886800.0
37,0.156014,-0.407085,65.717940,NaN,NaN,42.641727,39.462827,36.283928,39.462827,NaN,NaN,62.381560,57.066056,2.825023,35762000.0
38,0.283037,-0.269061,64.530961,NaN,NaN,43.012921,39.594709,36.176497,39.594709,NaN,NaN,65.108385,61.295021,2.811690,-119950400.0
39,0.374218,-0.140405,63.951772,NaN,NaN,43.346788,39.735087,36.123387,39.735087,NaN,NaN,64.319996,63.936647,2.811643,-271078800.0
40,0.382313,-0.035861,57.527307,NaN,NaN,43.527904,39.833000,36.138096,39.833000,NaN,NaN,59.272747,62.900376,2.801177,-466286800.0
41,0.407211,0.052753,59.237600,NaN,NaN,43.735163,39.941136,36.147110,39.941136,NaN,NaN,52.309002,58.633915,2.782215,-312470800.0
42,0.433628,0.128928,60.109646,NaN,NaN,43.918536,40.142563,36.366589,40.142563,NaN,NaN,42.550457,51.377402,2.769805,-198865200.0
43,0.446543,0.192451,59.771003,NaN,NaN,43.949837,40.389608,36.829380,40.389608,NaN,40.596320,34.223077,43.027512,2.757048,-294019200.0
44,0.420518,0.238064,56.052898,4.051371,0.82354,44.028290,40.539885,37.051481,40.539885,NaN,40.638547,12.020170,29.597901,2.704887,-420833200.0

In [173]:
indicators_with_price = pd.concat([indicators, stock_data["Adj Close"]], axis=1, join='inner')
indicators_with_price.head(45)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102223600.0,40.722874
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15848000.0,40.715790
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73890400.0,40.904900
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168530400.0,41.370625
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86259200.0,41.216969
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-76800.0,41.212227
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-95916400.0,41.202774
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-21245600.0,41.436806
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80426800.0,41.864697
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-37836800.0,41.651939
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99710400.0,42.339882
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,224484000.0,42.377712
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94783600.0,42.188572
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13650800.0,41.843430
14,NaN,NaN,68.998483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.724165,117105600.0,41.852890
15,NaN,NaN,55.580658,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.706161,-87314800.0,41.186222
16,NaN,NaN,45.152430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.695098,-253430800.0,40.451012
17,NaN,NaN,46.541669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-87.034555,-73.817868,2.684662,-96858800.0,40.545570
18,NaN,NaN,37.470339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-77.639257,-81.393287,2.635359,-299420400.0,39.706341
19,NaN,NaN,35.398304,NaN,NaN,42.761512,41.213177,39.664842,41.213177,NaN,NaN,-61.987786,-75.553866,2.599702,-483613200.0,39.472305
20,NaN,NaN,37.137643,NaN,NaN,42.849896,41.156085,39.462274,41.156085,NaN,NaN,-49.633849,-63.086964,2.602416,-353697600.0,39.581043
21,NaN,NaN,38.494694,NaN,NaN,42.910291,41.103485,39.296679,41.103485,NaN,NaN,-41.626480,-51.082705,2.600383,-164774400.0,39.663788
22,NaN,NaN,25.947826,NaN,NaN,43.228468,40.955379,38.682290,40.955379,NaN,NaN,-40.766055,-44.008795,2.560085,-511149600.0,37.942776
23,NaN,NaN,21.743753,NaN,NaN,43.578808,40.736587,37.894367,40.736587,NaN,NaN,-38.059391,-40.150642,2.593452,-802103600.0,36.994793
24,NaN,NaN,39.079676,NaN,NaN,43.590203,40.602782,37.615362,40.602782,NaN,NaN,-24.766527,-34.530658,2.689292,-529128400.0,38.540871
25,NaN,NaN,34.666297,NaN,NaN,43.652100,40.427962,37.203824,40.427962,NaN,NaN,-14.972504,-25.932808,2.662137,-735562800.0,37.715816
26,NaN,NaN,30.066666,NaN,NaN,43.790970,40.201724,36.612478,40.201724,NaN,NaN,-13.427890,-17.722307,2.652998,-953124800.0,36.678013
27,NaN,NaN,34.135080,NaN,NaN,43.765508,39.986216,36.206923,39.986216,NaN,NaN,-15.615498,-14.671964,2.663104,-670434400.0,37.126640
28,NaN,NaN,45.513606,NaN,NaN,43.544884,39.824083,36.103282,39.824083,NaN,NaN,-6.294991,-11.779460,2.747587,-427156400.0,38.622044
29,NaN,NaN,48.016017,NaN,NaN,43.330503,39.691935,36.053367,39.691935,NaN,NaN,11.072749,-3.612580,2.734577,-296959600.0,39.008972
30,NaN,NaN,52.392681,NaN,NaN,42.991932,39.561349,36.130765,39.561349,NaN,NaN,26.336884,10.371547,2.744681,-134380000.0,39.728165
31,NaN,NaN,59.246617,NaN,NaN,42.753750,39.495572,36.237395,39.495572,NaN,NaN,41.539671,26.316435,2.801799,70208800.0,41.062187
32,NaN,NaN,58.345266,NaN,NaN,42.524614,39.432607,36.340600,39.432607,NaN,NaN,51.997573,39.958043,2.790443,-90495600.0,40.929264
33,-0.373864,-0.940885,57.371660,NaN,NaN,42.339135,39.380015,36.420894,39.380015,NaN,NaN,56.241859,49.926368,2.779392,-226217600.0,40.791584
34,-0.274209,-0.807550,56.018009,NaN,NaN,42.113880,39.317693,36.521505,39.317693,NaN,NaN,52.331393,53.523609,2.776465,-376104000.0,40.606449
35,-0.165930,-0.679226,57.975721,NaN,NaN,42.071539,39.305675,36.539812,39.305675,NaN,NaN,52.421489,53.664914,2.783936,-252136400.0,40.945873
36,-0.022399,-0.547860,61.815829,NaN,NaN,42.278023,39.366024,36.454024,39.366024,NaN,NaN,56.395118,53.716000,2.796985,-116886800.0,41.657978
37,0.156014,-0.407085,65.717940,NaN,NaN,42.641727,39.462827,36.283928,39.462827,NaN,NaN,62.381560,57.066056,2.825023,35762000.0,42.481640
38,0.283037,-0.269061,64.530961,NaN,NaN,43.012921,39.594709,36.176497,39.594709,NaN,NaN,65.108385,61.295021,2.811690,-119950400.0,42.343975
39,0.374218,-0.140405,63.951772,NaN,NaN,43.346788,39.735087,36.123387,39.735087,NaN,NaN,64.319996,63.936647,2.811643,-271078800.0,42.279877
40,0.382313,-0.035861,57.527307,NaN,NaN,43.527904,39.833000,36.138096,39.833000,NaN,NaN,59.272747,62.900376,2.801177,-466286800.0,41.539295
41,0.407211,0.052753,59.237600,NaN,NaN,43.735163,39.941136,36.147110,39.941136,NaN,NaN,52.309002,58.633915,2.782215,-312470800.0,41.826515
42,0.433628,0.128928,60.109646,NaN,NaN,43.918536,40.142563,36.366589,40.142563,NaN,NaN,42.550457,51.377402,2.769805,-198865200.0,41.971306
43,0.446543,0.192451,59.771003,NaN,NaN,43.949837,40.389608,36.829380,40.389608,NaN,40.596320,34.223077,43.027512,2.757048,-294019200.0,41.935699
44,0.420518,0.238064,56.052898,4.051371,0.82354,44.028290,40.539885,37.051481,40.539885,NaN,40.638547,12.020170,29.597901,2.704887,-420833200.0,41.546413

In [174]:
indicators_with_price = indicators_with_price.dropna()
indicators_with_price = indicators_with_price.reset_index(drop=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close
0,0.567012,0.443928,58.241571,7.100837,1.143608,43.382885,41.728831,40.074777,41.728831,40.814298,41.035720,-7.013548,-3.909835,2.715224,-3.124152e+08,42.355835
1,0.548493,0.464841,58.592165,7.332864,1.202908,43.261026,41.862707,40.464388,41.862707,40.847954,41.096607,-20.016790,-8.448493,2.714434,-2.214400e+08,42.405682
2,0.515805,0.475034,57.044875,6.516212,0.819340,43.280283,41.922405,40.564526,41.922405,40.878761,41.148142,-27.991976,-18.340771,2.690140,-3.790588e+08,42.256145
3,0.432812,0.466589,50.806405,3.052131,-0.254189,43.245413,41.956467,40.667521,41.956467,40.892874,41.168691,-36.985361,-28.331376,2.648798,-5.128460e+08,41.610508
4,0.361720,0.445616,50.674736,2.976527,-0.055676,43.183910,41.996701,40.809491,41.996701,40.897386,41.187695,-46.752088,-37.243142,2.644562,-5.914436e+08,41.596264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993

In [175]:
indicators_with_price['Prev_Adj_Close'] = indicators_with_price['Adj Close'].shift(1)
indicators_with_price['Return'] = ((indicators_with_price['Adj Close'] - indicators_with_price['Prev_Adj_Close'])/indicators_with_price['Prev_Adj_Close'])*100
indicators_with_price['Signal'] = np.where(indicators_with_price['Return'] > 1, 1,
                                           np.where(indicators_with_price['Return'] < -1, 2, 0))
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
0,0.567012,0.443928,58.241571,7.100837,1.143608,43.382885,41.728831,40.074777,41.728831,40.814298,41.035720,-7.013548,-3.909835,2.715224,-3.124152e+08,42.355835,NaN,NaN,0
1,0.548493,0.464841,58.592165,7.332864,1.202908,43.261026,41.862707,40.464388,41.862707,40.847954,41.096607,-20.016790,-8.448493,2.714434,-2.214400e+08,42.405682,42.355835,0.117685,0
2,0.515805,0.475034,57.044875,6.516212,0.819340,43.280283,41.922405,40.564526,41.922405,40.878761,41.148142,-27.991976,-18.340771,2.690140,-3.790588e+08,42.256145,42.405682,-0.352632,0
3,0.432812,0.466589,50.806405,3.052131,-0.254189,43.245413,41.956467,40.667521,41.956467,40.892874,41.168691,-36.985361,-28.331376,2.648798,-5.128460e+08,41.610508,42.256145,-1.527914,2
4,0.361720,0.445616,50.674736,2.976527,-0.055676,43.183910,41.996701,40.809491,41.996701,40.897386,41.187695,-46.752088,-37.243142,2.644562,-5.914436e+08,41.596264,41.610508,-0.034232,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [176]:
indicators_with_price["Signal"].value_counts()

Signal
0    737
1    414
2    324
Name: count, dtype: int64

In [177]:
indicators_with_price.dropna(inplace=True)
indicators_with_price

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Prev_Adj_Close,Return,Signal
1,0.548493,0.464841,58.592165,7.332864,1.202908,43.261026,41.862707,40.464388,41.862707,40.847954,41.096607,-20.016790,-8.448493,2.714434,-2.214400e+08,42.405682,42.355835,0.117685,0
2,0.515805,0.475034,57.044875,6.516212,0.819340,43.280283,41.922405,40.564526,41.922405,40.878761,41.148142,-27.991976,-18.340771,2.690140,-3.790588e+08,42.256145,42.405682,-0.352632,0
3,0.432812,0.466589,50.806405,3.052131,-0.254189,43.245413,41.956467,40.667521,41.956467,40.892874,41.168691,-36.985361,-28.331376,2.648798,-5.128460e+08,41.610508,42.256145,-1.527914,2
4,0.361720,0.445616,50.674736,2.976527,-0.055676,43.183910,41.996701,40.809491,41.996701,40.897386,41.187695,-46.752088,-37.243142,2.644562,-5.914436e+08,41.596264,41.610508,-0.034232,0
5,0.226727,0.401838,42.776447,-1.895776,-1.685970,43.175297,41.999074,40.822851,41.999074,40.886125,41.163971,-59.960257,-47.899235,2.611110,-7.396632e+08,40.653912,41.596264,-2.265473,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,-1.918426,-1.197745,36.736038,-3.771153,-3.720001,199.131030,188.796999,178.462968,188.796999,189.292038,187.549134,26.310155,30.750307,3.101382,3.547580e+09,182.679993,183.630005,-0.517351,0
1471,-1.555397,-1.269276,51.604604,4.598480,3.830002,198.242596,188.434000,178.625403,188.434000,189.536287,187.597173,33.195313,30.241850,3.341284,3.625586e+09,188.630005,182.679993,3.257068,1
1472,-1.019515,-1.219324,56.967975,8.324259,4.119995,197.297528,188.164999,179.032471,188.164999,189.787603,187.773298,51.916516,37.140661,3.339763,3.694327e+09,191.559998,188.630005,1.553301,1
1473,-0.402178,-1.055894,60.698088,11.147862,5.880005,197.121605,188.117999,179.114394,188.117999,190.033787,188.045152,76.309536,53.807122,3.370495,3.754460e+09,193.889999,191.559998,1.216330,1
1474,0.188980,-0.806919,62.629499,12.671634,5.469986,197.221811,188.142999,179.064188,188.142999,190.284400,188.362256,88.961635,72.395896,3.266888,3.796816e+09,195.179993,193.889999,0.665322,0

In [178]:
indicators_with_price.columns

Index(['MACD', 'MACD_signal', 'RSI', 'CMO', 'MOM', 'Upper_BB', 'Middle_BB',
       'Lower_BB', 'SMA_SHORT', 'SMA_LONG', 'EMA', 'SLOWK', 'SLOWD', 'ATR',
       'OBV', 'Adj Close', 'Prev_Adj_Close', 'Return', 'Signal'],
      dtype='object')

In [179]:
# indicators_with_price = indicators_with_price.drop(columns=['Next_Adj_Close', 'Return'])
# indicators_with_price

In [180]:
indicators_with_price.drop(columns=['Prev_Adj_Close', "Signal"], inplace=True)
indicators_with_price.head(50)

,MACD,MACD_signal,RSI,CMO,MOM,Upper_BB,Middle_BB,Lower_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,ATR,OBV,Adj Close,Return
1,0.548493,0.464841,58.592165,7.332864,1.202908,43.261026,41.862707,40.464388,41.862707,40.847954,41.096607,-20.016790,-8.448493,2.714434,-2.214400e+08,42.405682,0.117685
2,0.515805,0.475034,57.044875,6.516212,0.819340,43.280283,41.922405,40.564526,41.922405,40.878761,41.148142,-27.991976,-18.340771,2.690140,-3.790588e+08,42.256145,-0.352632
3,0.432812,0.466589,50.806405,3.052131,-0.254189,43.245413,41.956467,40.667521,41.956467,40.892874,41.168691,-36.985361,-28.331376,2.648798,-5.128460e+08,41.610508,-1.527914
4,0.361720,0.445616,50.674736,2.976527,-0.055676,43.183910,41.996701,40.809491,41.996701,40.897386,41.187695,-46.752088,-37.243142,2.644562,-5.914436e+08,41.596264,-0.034232
5,0.226727,0.401838,42.776447,-1.895776,-1.685970,43.175297,41.999074,40.822851,41.999074,40.886125,41.163971,-59.960257,-47.899235,2.611110,-7.396632e+08,40.653912,-2.265473
6,0.072555,0.335981,38.805954,-4.708042,-2.298225,43.330931,41.955755,40.580578,41.955755,40.863470,41.115772,-60.364790,-55.692378,2.604323,-9.056264e+08,40.079487,-1.412963
7,-0.123098,0.244165,33.410058,-9.019869,-3.037186,43.669839,41.830425,39.991011,41.830425,40.822443,41.028466,-57.037842,-59.120963,2.589765,-1.069742e+09,39.151386,-2.315650
8,-0.126721,0.169988,48.771962,0.230803,-0.833458,43.603893,41.756842,39.909791,41.756842,40.813906,41.027644,-35.113187,-50.838606,2.699326,-9.195768e+08,41.009972,4.747176
9,-0.212000,0.093591,42.761345,-4.462436,-1.894466,43.620644,41.637564,39.654484,41.637564,40.775781,40.980123,-25.755897,-39.302308,2.704911,-1.083267e+09,39.958424,-2.564128
10,-0.311617,0.012549,40.504312,-6.346445,-1.669300,43.661170,41.499416,39.337663,41.499416,40.733080,40.915092,-23.129921,-27.999668,2.693602,-1.249941e+09,39.516922,-1.104902
11,-0.361497,-0.062260,42.777709,-4.867430,-0.625507,43.694929,41.413727,39.132524,41.413727,40.682793,40.866666,-31.639027,-26.841615,2.745529,-1.096347e+09,39.825504,0.780886
12,-0.417287,-0.133266,41.338344,-5.999331,-0.981171,43.709487,41.300621,38.891755,41.300621,40.626526,40.808787,-33.349984,-29.372977,2.721526,-1.246694e+09,39.564400,-0.655622
13,-0.423862,-0.191385,44.466501,-4.030452,0.263950,43.655481,41.200570,38.745659,41.200570,40.582161,40.771521,-30.537756,-31.842256,2.714496,-1.125582e+09,39.970291,1.025901
14,-0.363212,-0.225750,49.885849,-0.435804,1.262310,43.579266,41.140516,38.701766,41.140516,40.559985,40.769880,-23.649306,-29.179015,2.737190,-9.871604e+08,40.734615,1.912231
15,-0.289021,-0.238404,51.759482,0.859663,1.436043,43.546085,41.114050,38.682014,41.114050,40.543268,40.780867,-13.681431,-22.622831,2.743311,-8.794276e+08,41.017086,0.693441
16,-0.311295,-0.252982,45.025990,-3.853617,0.304138,43.457724,41.012457,38.567190,41.012457,40.518903,40.744737,-15.941644,-17.757460,2.697568,-1.019449e+09,39.967926,-2.557861
17,-0.293577,-0.261101,47.789596,-2.010642,2.421543,43.223489,40.894604,38.565719,40.894604,40.517169,40.727829,-20.849104,-16.824060,2.740925,-9.033780e+08,40.364319,0.991777
18,-0.215756,-0.252032,52.696915,1.419595,4.129112,42.889423,40.794079,38.698736,40.794079,40.528735,40.745432,-19.855247,-18.881998,2.769122,-7.897436e+08,41.123905,1.881826
19,-0.167664,-0.235159,51.380476,0.543907,2.390766,42.607665,40.704711,38.801757,40.704711,40.553241,40.753708,-10.385136,-17.029829,2.739620,-8.794700e+08,40.931637,-0.467534
20,-0.095884,-0.207304,53.978964,2.354529,3.619347,42.427111,40.653677,38.880244,40.653677,40.590498,40.779551,0.476957,-9.921142,2.745245,-7.879128e+08,41.335163,0.985854
21,-0.027383,-0.171319,54.880192,2.981730,4.797188,42.237333,40.607153,38.976974,40.607153,40.628382,40.810468,4.591666,-1.772171,2.736644,-6.874156e+08,41.475201,0.338785
22,0.047238,-0.127608,56.572350,4.145754,4.607296,42.118850,40.581043,39.043235,40.581043,40.669785,40.851511,13.924984,6.331202,2.724905,-6.011020e+08,41.733936,0.623832
23,0.150987,-0.071889,60.145941,6.689063,3.686314,42.272663,40.615935,38.959208,40.615935,40.757096,40.916260,22.180704,13.565784,2.744631,-4.946804e+08,42.308357,1.376388
24,0.222977,-0.012916,59.277712,6.212449,3.204445,42.395826,40.646793,38.897760,40.646793,40.861469,40.973912,28.084321,21.396670,2.719775,-5.776984e+08,42.213417,-0.224401
25,0.181404,0.025948,49.567828,0.427676,1.288921,42.421429,40.664952,38.908475,40.664952,40.910993,40.975830,20.146134,23.470387,2.642225,-7.169336e+08,41.017086,-2.834007
26,0.012704,0.023299,39.724033,-6.863802,-1.725658,42.461946,40.627804,38.793661,40.627804,40.943407,40.902973,-8.290844,13.313204,2.581203,-9.788980e+08,39.336529,-4.097213
27,-0.128701,-0.007101,39.156333,-7.330518,-1.706661,42.454270,40.631365,38.808459,40.631365,40.994299,40.828289,-34.549809,-7.564840,2.567794,-1.124960e+09,39.222603,-0.289619
28,-0.281573,-0.061995,36.466803,-9.553014,-2.114929,42.515711,40.514699,38.513686,40.514699,41.025299,40.732661,-45.876956,-29.572537,2.552944,-1.259728e+09,38.676655,-1.391922
29,-0.384692,-0.126534,37.885076,-8.729368,-1.761272,42.577345,40.459036,38.340728,40.459036,41.029762,40.648773,-39.397464,-39.941410,2.561901,-1.146200e+09,38.845177,0.435720
30,-0.450307,-0.191289,39.061268,-8.061926,-1.965397,42.610301,40.432214,38.254127,40.432214,41.029192,40.574627,-33.203105,-39.492509,2.563717,-1.034348e+09,38.980476,0.348305
31,-0.532560,-0.259543,36.575071,-9.947443,-3.128506,42.686407,40.367413,38.048419,40.367413,41.005218,40.483731,-32.805995,-35.135522,2.530739,-1.176971e+09,38.529472,-1.157000
32,-0.535265,-0.314687,42.657015,-6.489527,-3.254307,42.697384,40.350559,38.003734,40.350559,40.968521,40.427891,-28.595100,-31.534734,2.584652,-1.007261e+09,39.227333,1.811239
33,-0.458572,-0.343464,49.472276,-2.193923,-2.205147,42.701495,40.358986,38.016477,40.358986,40.952712,40.415044,-18.764757,-26.721951,2.619510,-7.929836e+08,40.138828,2.323623
34,-0.251813,-0.325134,59.544980,5.401833,-0.367916,42.852522,40.417853,37.983184,40.417853,40.975120,40.481573,5.866509,-13.831116,2.739450,-5.268260e+08,41.911961,4.417499
35,-0.080893,-0.276286,59.913626,5.709027,0.448620,42.984210,40.466395,37.948580,40.466395,41.002749,40.548522,25.969057,4.356936,2.719707,-3.905532e+08,41.987915,0.181224
36,0.185351,-0.183958,66.948282,12.047556,1.808727,43.506949,40.649761,37.792572,40.649761,41.056537,40.685709,45.736656,25.857407,2.816484,-1.657480e+08,43.635242,3.923337
37,0.417018,-0.063763,68.103514,13.191904,1.979637,44.022546,40.829092,37.635637,40.829092,41.102396,40.830831,51.666028,41.123914,2.849753,4.057600e+06,43.950943,0.723499
38,0.610624,0.071114,68.887176,13.958441,2.226498,44.489621,40.981006,37.472392,40.981006,41.136007,40.978892,58.083988,51.828890,2.832204,1.176688e+08,44.162197,0.480659
39,0.780157,0.212923,70.053502,15.087794,2.926746,44.982150,41.158083,37.334015,41.158083,41.178591,41.134192,59.732738,56.494251,2.821889,2.105136e+08,44.473160,0.704138
40,0.954838,0.361306,72.338021,17.358446,3.109524,45.541692,41.346790,37.151887,41.346790,41.235179,41.310864,63.227816,60.348180,2.843136,3.224708e+08,45.109303,1.430397
41,1.067128,0.502470,70.769974,16.498715,2.216358,45.997973,41.519916,37.041859,41.519916,41.303148,41.472058,64.912024,62.624193,2.811890,2.176220e+08,44.937737,-0.380334
42,1.134580,0.628892,69.774571,15.967472,1.698490,46.380494,41.674864,36.969234,41.674864,41.363276,41.621429,64.592825,64.244222,2.785667,1.345068e+08,44.832890,-0.233316
43,1.141993,0.731513,65.895542,13.901997,1.706421,46.631593,41.780717,36.929842,41.780717,41.412358,41.746051,61.526803,63.677217,2.724877,3.972600e+07,44.425426,-0.908849
44,1.167863,0.818783,67.853951,15.469636,2.484215,46.941608,41.912049,36.882491,41.912049,41.470445,41.883562,61.088844,62.402824,2.722355,1.164584e+08,44.840050,0.933302
45,1.152201,0.885466,65.100564,14.016816,2.150799,47.228046,42.089019,36.949992,42.089019,41.530646,42.002358,59.272343,60.629330,2.698434,4.728240e+07,44.556480,-0.632402
46,1.113874,0.931148,63.514667,13.184213,2.138309,47.411584,42.341915,37.272247,42.341915,41.578540,42.108674,56.482995,58.948061,2.676833,-2.590840e+07,44.394455,-0.363641
47,1.096243,0.964167,65.282733,14.425510,3.098476,47.573564,42.616234,37.658905,42.616234,41.618292,42.224243,45.620351,53.791897,2.694419,4.769480e+07,44.708984,0.708488
48,1.061004,0.983534,64.091825,13.832533,3.000732,47.592554,42.912251,38.231948,42.912251,41.647544,42.329699,34.736788,45.613378,2.681319,-1.326800e+07,44.596996,-0.250482
49,1.044113,0.995650,65.806998,14.983621,4.229027,47.574093,43.214139,38.854186,43.214139,41.690823,42.443176,22.112386,34.156508,2.670368,6.696560e+07,44.882938,0.641169
50,1.014989,0.999518,65.219787,14.709171,4.753403,47.457200,43.506760,39.556320,43.506760,41.740364,42.549385,-9.602534,15.748880,2.645846,-2.597040e+07,44.832890,-0.111510

In [181]:
y = indicators_with_price["Return"]
y_2 = indicators_with_price["SMA_SHORT"]
y_3 = indicators_with_price["EMA"]
y_4 = indicators_with_price["Upper_BB"]
y_5 = indicators_with_price["Middle_BB"]
y_6 = indicators_with_price["Lower_BB"]
X = np.array(date)

trace = go.Scatter(x=X, y=y, mode="lines", name="Adj Close")
trace_2 = go.Scatter(x=X, y=y_2, mode="lines", name="SMA")
trace_3 = go.Scatter(x=X, y=y_3, mode="lines", name="EMA")
trace_4 = go.Scatter(x=X, y=y_4, mode="lines", name="Upper_BB")
trace_5 = go.Scatter(x=X, y=y_5, mode="lines", name="Middle_BB")
trace_6 = go.Scatter(x=X, y=y_6, mode="lines", name="Lower_BB")



layout = go.Layout(
    title='Stock Price and Volume',
    xaxis=dict(title='Date'),
    yaxis=dict(title='Adj Close', side='left', rangemode='tozero'),
    yaxis2=dict(title='SMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis3=dict(title='EMA', side='right', overlaying='y', rangemode='tozero'),
    yaxis4=dict(title='Upper_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis5=dict(title='Middle_BB', side='right', overlaying='y', rangemode='tozero'),
    yaxis6=dict(title='Lower_BB', side='right', overlaying='y', rangemode='tozero'),
    height=600,
)

fig = go.Figure(data=[trace, trace_2, trace_3, trace_4, trace_5, trace_6], layout=layout)

# Show plot
pyo.iplot(fig)

In [182]:
class RollingWindowDataset(Dataset):
    def __init__(self, X, y, window_size, device="gpu"):
        self.X = X.clone().detach().to(torch.float).to(device)
        self.y = y.clone().detach().to(torch.float).to(device)
        self.window_size = window_size

    def __len__(self):
        # Adjust the length to account for window size
        return len(self.X) - self.window_size 

    def __getitem__(self, idx):
        # Ensure idx is within the valid range
        if idx + self.window_size > len(self.X):
            raise IndexError("Index out of bounds")

        # Extract a window of data from X
        X_window = self.X[idx : idx + self.window_size]
        
        # Assuming you're predicting the value right after the window
        y_target = self.y[idx + self.window_size]  

        return X_window.clone().detach().to(torch.float), y_target.clone().detach().to(torch.float)

In [183]:
X = indicators_with_price.iloc[:,:-1]
y = indicators_with_price.iloc[:,-2]

signal_true = indicators_with_price.iloc[:,-1]
y

1        42.405682
2        42.256145
3        41.610508
4        41.596264
5        40.653912
           ...
1470    182.679993
1471    188.630005
1472    191.559998
1473    193.889999
1474    195.179993
Name: Adj Close, Length: 1474, dtype: float64

In [184]:
train_signal_true = signal_true.iloc[:int(len(X)*0.8)]
test_signal_true = signal_true.iloc[int(len(X)*0.8):]
test_signal_true

1180    1.297136
1181    0.378186
1182   -2.168029
1183    1.466111
1184    0.592644
          ...
1470   -0.517351
1471    3.257068
1472    1.553301
1473    1.216330
1474    0.665322
Name: Return, Length: 295, dtype: float64

In [185]:
correlation_matrix = X.corr()

linked = sch.linkage(sch.distance.pdist(correlation_matrix), method='ward')
cluster_order = sch.dendrogram(linked, no_plot=True)['leaves']

correlation_matrix_ordered = correlation_matrix.iloc[cluster_order, cluster_order]

fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix_ordered,
                    x=correlation_matrix_ordered.columns,
                    y=correlation_matrix_ordered.columns,
                    colorscale='Viridis',
                    text=correlation_matrix_ordered.round(2).values, 
                    texttemplate="%{text}",
                    textfont={"size":9}  
                    ))

fig.update_layout(
    title='Ordered Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000,  
    height=1000,  
)

# Show the figure
pyo.iplot(fig)

In [186]:
X= X.iloc[:, cluster_order]

In [187]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

y_test.head(44)

1180    149.882233
1181    150.449066
1182    147.187286
1183    149.345215
1184    150.230301
1185    147.286743
1186    143.418381
1187    140.385315
1188    147.207184
1189    147.485611
1190    146.988403
1191    145.814987
1192    142.115631
1193    140.156601
1194    141.857086
1195    141.369812
1196    143.686859
1197    144.661423
1198    142.413986
1199    135.741272
1200    133.762329
1201    131.634232
1202    131.564636
1203    134.697128
1204    131.494995
1205    131.127060
1206    129.307236
1207    125.339417
1208    128.889572
1209    129.207779
1210    124.374802
1211    125.657639
1212    124.325089
1213    128.899521
1214    129.426559
1215    130.003342
1216    132.748016
1217    132.668442
1218    134.010925
1219    135.184387
1220    134.458450
1221    134.518112
1222    137.103668
1223    140.325638
Name: Adj Close, dtype: float64

In [188]:
X_train_df = pd.DataFrame()
X_test_df = pd.DataFrame()
scaler_dict = {}

X_train_df = X_train
X_test_df = X_test

for column in X_train.columns:

    if column not in ["Adj Close", "Return"]:
        scaler = MinMaxScaler()

        X_train_scaled = scaler.fit_transform(X_train[[column]].values)
        X_train_df[column] = X_train_scaled
            
        X_test_scaled = scaler.transform(X_test[[column]].values)
        X_test_df[column] = X_test_scaled

        scaler_dict[column] = scaler


X_train_df.head(24)

features = X_train_df.columns
X_train_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1,0.177936,0.261686,42.405682,0.048691,0.032213,0.037797,0.037797,0.016755,0.014072,0.483865,0.507173,0.508804,0.493383,0.498960,0.567549,0.468235
2,0.172548,0.234481,42.256145,0.049438,0.032346,0.038231,0.038231,0.016988,0.014472,0.447235,0.458578,0.506461,0.494198,0.494287,0.542887,0.458079
3,0.163379,0.211390,41.610508,0.050206,0.032106,0.038478,0.038478,0.017095,0.014632,0.405927,0.409499,0.500513,0.493523,0.481206,0.443455,0.414999
4,0.162440,0.197825,41.596264,0.051265,0.031682,0.038770,0.038770,0.017129,0.014780,0.361068,0.365721,0.495417,0.491846,0.483624,0.441356,0.414058
5,0.155021,0.172243,40.653912,0.051365,0.031623,0.038787,0.038787,0.017044,0.014595,0.300402,0.313373,0.485741,0.488346,0.463759,0.315469,0.353465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,0.850804,0.753803,146.053635,0.738088,0.800862,0.778358,0.778358,0.818604,0.829435,0.680158,0.631198,0.340107,0.343542,0.360230,0.463732,0.349552
1176,0.849088,0.770024,148.867905,0.744000,0.803314,0.782527,0.782527,0.817400,0.830427,0.747328,0.665569,0.388138,0.347930,0.321213,0.506322,0.377027
1177,0.803296,0.757360,147.455780,0.746416,0.805266,0.784731,0.784731,0.816305,0.830887,0.835637,0.739664,0.418622,0.358240,0.420018,0.480797,0.363377
1178,0.812803,0.772871,149.206009,0.747900,0.808367,0.787087,0.787087,0.815668,0.831932,0.856512,0.802536,0.453092,0.374178,0.423562,0.508856,0.380638
1179,0.765325,0.761787,147.962952,0.749683,0.810260,0.788953,0.788953,0.814627,0.832500,0.850519,0.839325,0.473178,0.391410,0.443981,0.484406,0.368317

In [189]:
scaler_adj = MinMaxScaler()
scaler_adj.fit(X_train[["Adj Close"]].values)

X_train_df['Adj Close'] = scaler_adj.transform(X_train[['Adj Close']].values).flatten()
X_test_df['Adj Close'] = scaler_adj.transform(X_test[['Adj Close']].values).flatten()

y_train = scaler_adj.transform(y_train.values.reshape(-1,1)).flatten()
y_test = scaler_adj.transform(y_test.values.reshape(-1,1)).flatten()



X_test_df

,ATR,OBV,Adj Close,Lower_BB,Upper_BB,Middle_BB,SMA_SHORT,SMA_LONG,EMA,SLOWK,SLOWD,MACD,MACD_signal,MOM,RSI,CMO
1180,0.764804,0.775662,0.793797,0.751875,0.813419,0.791684,0.791684,0.814103,0.833706,0.876576,0.853920,0.499847,0.411144,0.487569,0.517394,0.387563
1181,0.724522,0.788577,0.797684,0.752021,0.816204,0.793223,0.793223,0.813227,0.835055,0.895160,0.867699,0.523637,0.432238,0.448749,0.527280,0.393264
1182,0.685712,0.778442,0.775317,0.751879,0.815519,0.792793,0.792793,0.810946,0.835217,0.907286,0.887937,0.523008,0.448973,0.379729,0.456307,0.359879
1183,0.661728,0.787383,0.790114,0.752318,0.813808,0.792104,0.792104,0.810434,0.836117,0.913913,0.901248,0.534244,0.464868,0.444492,0.497611,0.382098
1184,0.623616,0.797445,0.796183,0.752139,0.815320,0.792815,0.792815,0.809834,0.837282,0.923475,0.911342,0.547370,0.480512,0.467132,0.514479,0.391191
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1470,0.263755,0.912203,1.018693,1.078159,1.105702,1.104494,1.104494,1.140327,1.152418,0.696649,0.699736,0.331987,0.360467,0.438975,0.219193,0.330142
1471,0.316961,0.925666,1.059493,1.079371,1.099583,1.101858,1.101858,1.142176,1.152792,0.728273,0.697238,0.358007,0.354748,0.530971,0.456177,0.434229
1472,0.316623,0.937531,1.079584,1.082407,1.093074,1.099905,1.099905,1.144078,1.154161,0.814261,0.731128,0.396416,0.358741,0.534505,0.541661,0.480564
1473,0.323439,0.947909,1.095561,1.083019,1.091863,1.099564,1.099564,1.145941,1.156274,0.926300,0.813002,0.440664,0.371807,0.555951,0.601114,0.515679
1474,0.300461,0.955220,1.104406,1.082644,1.092553,1.099746,1.099746,1.147838,1.158738,0.984412,0.904318,0.483036,0.391711,0.550955,0.631898,0.534629

In [190]:
correlation_matrix = X_train_df.corr()

fig = go.Figure(data=go.Heatmap(
                    z=correlation_matrix,
                    x=correlation_matrix.columns,
                    y=correlation_matrix.columns,
                    colorscale='Viridis',
                    text=correlation_matrix.round(2).values, 
                    texttemplate="%{text}",
                    textfont={"size":9}  
                    ))

fig.update_layout(
    title='Correlation Matrix',
    xaxis_title="Variables",
    yaxis_title="Variables",
    xaxis=dict(side='bottom'),
    yaxis=dict(autorange='reversed'),
    width=1000, 
    height=1000,  
)

pyo.iplot(fig)

In [191]:
X_train_tensor = torch.tensor(X_train_df.to_numpy(), dtype=torch.float, device=device)
y_train_tensor = torch.tensor(y_train, dtype=torch.float, device=device)

X_test_tensor = torch.tensor(X_test_df.to_numpy(), dtype=torch.float, device=device)
y_test_tensor = torch.tensor(y_test, dtype=torch.float, device=device)

train_data = RollingWindowDataset(X_train_tensor, y_train_tensor, window_size=time_step, device=device)
test_data = RollingWindowDataset(X_test_tensor, y_test_tensor, window_size=time_step, device=device)

print(test_data.__getitem__(0)[1])
print(test_data.__getitem__(1)[0])

tensor(0.7379, device='cuda:0')
tensor([[0.7245, 0.7886, 0.7977, 0.7520, 0.8162, 0.7932, 0.7932, 0.8132, 0.8351,
         0.8952, 0.8677, 0.5236, 0.4322, 0.4487, 0.5273, 0.3933],
        [0.6857, 0.7784, 0.7753, 0.7519, 0.8155, 0.7928, 0.7928, 0.8109, 0.8352,
         0.9073, 0.8879, 0.5230, 0.4490, 0.3797, 0.4563, 0.3599],
        [0.6617, 0.7874, 0.7901, 0.7523, 0.8138, 0.7921, 0.7921, 0.8104, 0.8361,
         0.9139, 0.9012, 0.5342, 0.4649, 0.4445, 0.4976, 0.3821],
        [0.6236, 0.7974, 0.7962, 0.7521, 0.8153, 0.7928, 0.7928, 0.8098, 0.8373,
         0.9235, 0.9113, 0.5474, 0.4805, 0.4671, 0.5145, 0.3912],
        [0.5981, 0.7914, 0.7760, 0.7537, 0.8163, 0.7941, 0.7941, 0.8092, 0.8374,
         0.9237, 0.9172, 0.5399, 0.4914, 0.4592, 0.4471, 0.3605],
        [0.5869, 0.7794, 0.7495, 0.7546, 0.8078, 0.7900, 0.7900, 0.8083, 0.8361,
         0.8756, 0.9035, 0.5112, 0.4936, 0.4080, 0.3677, 0.3216],
        [0.5854, 0.7650, 0.7287, 0.7521, 0.8019, 0.7857, 0.7857, 0.8063, 0.8339,
         0.7960, 0.8581, 0.4709, 0.4865, 0.3590, 0.3118, 0.2921],
        [0.6453, 0.7842, 0.7755, 0.7524, 0.8000, 0.7849, 0.7849, 0.8050, 0.8341,
         0.7774, 0.8059, 0.4782, 0.4824, 0.4654, 0.4544, 0.3639],
        [0.6088, 0.7965, 0.7774, 0.7533, 0.8016, 0.7861, 0.7861, 0.8043, 0.8344,
         0.7888, 0.7750, 0.4855, 0.4807, 0.5578, 0.4597, 0.3667],
        [0.5723, 0.7852, 0.7740, 0.7605, 0.8012, 0.7895, 0.7895, 0.8036, 0.8345,
         0.8188, 0.7831, 0.4882, 0.4800, 0.6035, 0.4490, 0.3617],
        [0.5827, 0.7733, 0.7659, 0.7687, 0.7993, 0.7924, 0.7924, 0.8030, 0.8343,
         0.7983, 0.7906, 0.4834, 0.4783, 0.5378, 0.4231, 0.3496],
        [0.5960, 0.7621, 0.7405, 0.7742, 0.7969, 0.7939, 0.7939, 0.8019, 0.8327,
         0.7377, 0.7723, 0.4583, 0.4714, 0.4486, 0.3463, 0.3124],
        [0.5765, 0.7501, 0.7271, 0.7765, 0.7958, 0.7944, 0.7944, 0.8003, 0.8305,
         0.6628, 0.7167, 0.4275, 0.4590, 0.4211, 0.3088, 0.2931],
        [0.5583, 0.7608, 0.7388, 0.7927, 0.7862, 0.7972, 0.7972, 0.7992, 0.8291,
         0.6220, 0.6538, 0.4137, 0.4460, 0.4535, 0.3519, 0.3121],
        [0.5622, 0.7477, 0.7354, 0.7881, 0.7872, 0.7955, 0.7955, 0.7992, 0.8275,
         0.6178, 0.6111, 0.4007, 0.4327, 0.5122, 0.3416, 0.3072],
        [0.5462, 0.7599, 0.7513, 0.7864, 0.7852, 0.7936, 0.7936, 0.8002, 0.8268,
         0.6636, 0.6114, 0.4045, 0.4229, 0.5364, 0.4019, 0.3333],
        [0.5764, 0.7761, 0.7580, 0.7854, 0.7842, 0.7926, 0.7926, 0.8007, 0.8264,
         0.7016, 0.6398, 0.4138, 0.4171, 0.5657, 0.4266, 0.3443],
        [0.5921, 0.7619, 0.7426, 0.7831, 0.7816, 0.7901, 0.7901, 0.8003, 0.8253,
         0.7177, 0.6754, 0.4089, 0.4114, 0.5461, 0.3718, 0.3205],
        [0.6206, 0.7448, 0.6968, 0.7701, 0.7853, 0.7857, 0.7857, 0.7988, 0.8220,
         0.6670, 0.6766, 0.3676, 0.3977, 0.4085, 0.2382, 0.2535],
        [0.6081, 0.7171, 0.6833, 0.7563, 0.7869, 0.7798, 0.7798, 0.7972, 0.8181,
         0.6070, 0.6429, 0.3250, 0.3771, 0.4402, 0.2052, 0.2347],
        [0.5959, 0.7034, 0.6687, 0.7415, 0.7876, 0.7730, 0.7730, 0.7961, 0.8136,
         0.5756, 0.5922, 0.2812, 0.3510, 0.3655, 0.1712, 0.2147],
        [0.5762, 0.6900, 0.6682, 0.7281, 0.7892, 0.7673, 0.7673, 0.7949, 0.8093,
         0.5907, 0.5650, 0.2486, 0.3227, 0.3484, 0.1700, 0.2140],
        [0.5879, 0.7049, 0.6897, 0.7227, 0.7841, 0.7620, 0.7620, 0.7944, 0.8063,
         0.6254, 0.5716, 0.2435, 0.2990, 0.3853, 0.2674, 0.2523],
        [0.5853, 0.6914, 0.6677, 0.7149, 0.7784, 0.7552, 0.7552, 0.7935, 0.8023,
         0.6347, 0.5927, 0.2238, 0.2756, 0.3520, 0.2091, 0.2214],
        [0.5572, 0.6804, 0.6652, 0.7066, 0.7750, 0.7494, 0.7494, 0.7919, 0.7984,
         0.6337, 0.6080, 0.2090, 0.2536, 0.3005, 0.2026, 0.2178],
        [0.5297, 0.6685, 0.6527, 0.6956, 0.7754, 0.7442, 0.7442, 0.7907, 0.7940,
         0.6029, 0.6000, 0.1900, 0.2318, 0.2520, 0.1704, 0.2003],
        [0.5433, 0.6538, 0.6255, 0.6795, 0.7799, 0.7388, 0.7388, 0.7882, 0.7885,
         0.5879, 0.5833, 0.1556, 0.2067, 0.1687, 0.1075, 0.1632],
        [0.5557, 0.6668, 0.6498, 0.6728, 0.7734, 0.7321, 0.7321, 0.7862, 0.7844,
         0.5958, 0.5698, 0.1525, 0.1859, 0.2481, 0.2212, 0.2082],
        [0.5256, 0.6801, 0.6520, 0.6687, 0.7647, 0.7255, 0.7255, 0.7841, 0.7806,
         0.6128, 0.5733, 0.1555, 0.1699, 0.3070, 0.2309, 0.2122],
        [0.5644, 0.6608, 0.6189, 0.6593, 0.7577, 0.7173, 0.7173, 0.7814, 0.7753,
         0.6174, 0.5839, 0.1339, 0.1523, 0.1158, 0.1491, 0.1668],
        [0.5617, 0.6761, 0.6277, 0.6536, 0.7491, 0.7100, 0.7100, 0.7783, 0.7707,
         0.6084, 0.5883, 0.1280, 0.1369, 0.1605, 0.1898, 0.1832],
        [0.5389, 0.6622, 0.6185, 0.6454, 0.7445, 0.7035, 0.7035, 0.7746, 0.7658,
         0.5885, 0.5796, 0.1197, 0.1227, 0.1768, 0.1673, 0.1708],
        [0.5646, 0.6773, 0.6499, 0.6428, 0.7391, 0.6994, 0.6994, 0.7712, 0.7627,
         0.6410, 0.5880, 0.1434, 0.1167, 0.3005, 0.3052, 0.2288],
        [0.5655, 0.6895, 0.6535, 0.6425, 0.7308, 0.6949, 0.6949, 0.7684, 0.7599,
         0.6945, 0.6188, 0.1686, 0.1175, 0.3813, 0.3198, 0.2353],
        [0.5445, 0.7006, 0.6575, 0.6433, 0.7222, 0.6908, 0.6908, 0.7663, 0.7575,
         0.7638, 0.6813, 0.1951, 0.1240, 0.3916, 0.3365, 0.2425],
        [0.5309, 0.7126, 0.6763, 0.6492, 0.7093, 0.6868, 0.6868, 0.7630, 0.7561,
         0.8140, 0.7430, 0.2347, 0.1381, 0.4185, 0.4132, 0.2767],
        [0.5074, 0.7002, 0.6758, 0.6595, 0.6915, 0.6825, 0.6825, 0.7600, 0.7548,
         0.8756, 0.8075, 0.2680, 0.1568, 0.4105, 0.4111, 0.2759],
        [0.4925, 0.7102, 0.6850, 0.6695, 0.6765, 0.6794, 0.6794, 0.7577, 0.7540,
         0.9451, 0.8721, 0.3040, 0.1797, 0.4830, 0.4490, 0.2927],
        [0.4790, 0.7212, 0.6930, 0.6699, 0.6757, 0.6792, 0.6792, 0.7563, 0.7536,
         0.9697, 0.9276, 0.3408, 0.2063, 0.3519, 0.4816, 0.3075],
        [0.4712, 0.7092, 0.6880, 0.6696, 0.6765, 0.6795, 0.6795, 0.7558, 0.7530,
         0.9536, 0.9554, 0.3670, 0.2334, 0.3087, 0.4586, 0.2993],
        [0.4465, 0.7192, 0.6884, 0.6689, 0.6791, 0.6805, 0.6805, 0.7554, 0.7524,
         0.9231, 0.9476, 0.3890, 0.2600, 0.3267, 0.4604, 0.3001],
        [0.4445, 0.7331, 0.7062, 0.6665, 0.6851, 0.6825, 0.6825, 0.7552, 0.7528,
         0.9317, 0.9341, 0.4219, 0.2886, 0.3368, 0.5376, 0.3335],
        [0.4810, 0.7472, 0.7283, 0.6614, 0.6937, 0.6846, 0.6846, 0.7554, 0.7542,
         0.9518, 0.9335, 0.4667, 0.3215, 0.3912, 0.6197, 0.3738],
        [0.4616, 0.7587, 0.7379, 0.6561, 0.7057, 0.6883, 0.6883, 0.7566, 0.7561,
         0.9821, 0.9545, 0.5099, 0.3575, 0.3851, 0.6520, 0.3910]],
       device='cuda:0')

# Stacked LSTM

<img src="/home/arda/Turkcell/RNN/LSTM/images/Screenshot from 2024-01-30 10-30-23.png" alt="Alt text">

In [192]:
class StackedLSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_size, layer_size, output_dim, dropout_prob, stateful):
        super(StackedLSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.layer_size = layer_size
        self.stateful = stateful
        
        self.hn = None
        self.cn = None

        self.lstm = nn.LSTM(input_size = input_dim, hidden_size = hidden_size, num_layers=self.layer_size,
                            dropout=(dropout_prob if self.layer_size > 1 else 0), batch_first=True)
                            
        self.dropout = nn.Dropout(dropout_prob)
        
        self.fc = nn.Linear(hidden_size, output_dim)

    def reset_hidden_state(self, batch_size=None):
        if batch_size is None or not self.stateful:
            self.hn = None
            self.cn = None
        else:
            self.hn = self._resize_state(self.hn, batch_size)
            self.cn = self._resize_state(self.cn, batch_size)


    def _resize_state(self, state, batch_size):
        if state is None:
            # If state is not initialized, initialize with zeros
            return torch.zeros(self.layer_size, batch_size, self.hidden_size).to(device)
        elif batch_size < state.size(1):
            return state[:, :batch_size, :].contiguous()
        elif batch_size > state.size(1):
            # If batch size is larger, pad the state with zeros
            padding_size = batch_size - state.size(1)
            padding = torch.zeros(self.layer_size, padding_size, self.hidden_size).to(device)
            return torch.cat([state, padding], dim=1)
        

    def forward(self, x):
        current_batch_size = x.size(0)

        if not self.stateful or self.hn is None or self.hn.size(1) != current_batch_size:
            self.reset_hidden_state(current_batch_size)
        else:
            self.hn = self.hn.detach()
            self.cn = self.cn.detach()

        # Ensure that hn and cn are not None and have the correct shape
        h0 = self.hn if self.hn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)
        c0 = self.cn if self.cn is not None else torch.zeros(self.layer_size, current_batch_size, self.hidden_size).to(device)

        # Forward propagate LSTM
        out, (hn, cn) = self.lstm(x, (h0, c0))

        # Update hidden states if stateful
        if self.stateful:
            self.hn, self.cn = hn.detach(), cn.detach()

        # Process the output of the last time step
        out = self.dropout(out[:, -1, :])  # Add dropout
        out = self.fc(out)  # Fully connected layer

        return out

In [193]:
class ModelActioner:
    
    def __init__(self, train_data, test_data, device):
        self.train_data = train_data
        self.test_data = test_data
        self.device = device
        self.model = None
        self.optimizer = None
        self.criterion = nn.MSELoss()

    
    def train_validate(self, config, trial):

        batch_size = config["batch_size"]
        epochs = config["epochs"]
        hidden_size = config["hidden_size"]
        num_layers = config["num_layers"]
        learning_rate = config["learning_rate"]
        dropout_prob = config["dropout_prob"]
        weight_decay = config["weight_decay"]
        lr_step_size = config["lr_step_size"]
        gamma = config["gamma"]
        
        self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=1).to(self.device)

        n_splits = 5
        tscv = TimeSeriesSplit(n_splits=n_splits)

        val_losses = []


        for fold, (train_ids, val_ids) in enumerate(tscv.split(self.train_data)):
            print(f'Starting fold {fold+1}:')
            self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)
            scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True) 

            train_subset = Subset(self.train_data, train_ids)
            val_subset = Subset(self.train_data, val_ids)
            
            # Creating data loader
            train_loader = DataLoader(dataset=train_subset, batch_size=batch_size, shuffle=False)
            val_loader = DataLoader(dataset=val_subset, batch_size=batch_size, shuffle=False)

            # Training Loop
            for epoch in range(epochs):
                print('epochs {}/{}'.format(epoch+1,epochs))

                running_loss = 0.0
                total_sample_train = 0

                self.model.train()

                for batch_idx, (data, target) in enumerate(train_loader):
                    data, target = data.to(self.device), target.to(self.device)
                    target = target.view(-1,1)


                    self.optimizer.zero_grad()
                    preds = self.model(data)

                    loss = self.criterion(preds, target)
                    loss.backward()
                    self.optimizer.step() # Update model params

                    running_loss += loss.item() * data.size(0)
                    total_sample_train += data.size(0)

                train_loss = running_loss/total_sample_train
                #print(f"train loss: {train_loss}")

                self.model.eval()
                val_running_loss = 0.0
                total_sample_val = 0

                with torch.no_grad():

                    for batch_idx, (data, target) in enumerate(val_loader):
                        data, target = data.to(self.device), target.to(self.device)
                        target = target.view(-1,1)

                        preds = self.model(data)
                        loss = self.criterion(preds, target)

                        val_running_loss += loss.item() * data.size(0)
                        total_sample_val += data.size(0)
                
                if trial.should_prune():
                    raise optuna.TrialPruned()
                
                val_loss = val_running_loss/total_sample_val
                val_losses.append(val_loss)
                scheduler.step(val_loss)
                
                unique_step = fold * epochs + epoch
                trial.report(val_loss, unique_step)

                current_lr = self.optimizer.param_groups[0]['lr']

                print(f'Current Learning Rate: {current_lr}')
                print(f"train_loss: {train_loss}, val_loss: {val_loss}")
                
        mean_val_loss = np.mean(val_losses)
        print(f"Mean validation loss: {mean_val_loss}")
        return mean_val_loss
    
                    
    def train(self, config):
            
        batch_size = config["batch_size"]
        epochs = config["epochs"]
        hidden_size = config["hidden_size"]
        num_layers = config["num_layers"]
        learning_rate = config["learning_rate"]
        dropout_prob = config["dropout_prob"]
        weight_decay = config["weight_decay"]
        lr_step_size = config["lr_step_size"]
        gamma = config["gamma"]
        
        self.model = StackedLSTMModel(input_dim=self.train_data.__getitem__(0)[0].shape[1], hidden_size=hidden_size, layer_size=num_layers, dropout_prob=dropout_prob, stateful=False, output_dim=1).to(self.device)

        # Update optimizer with updated lr
        self.optimizer = optim.Adam(self.model.parameters(), lr = learning_rate, weight_decay=weight_decay)

        # Creating data loader
        train_loader = DataLoader(dataset=self.train_data, batch_size=batch_size, shuffle=False)

        scheduler = ReduceLROnPlateau(self.optimizer, patience=lr_step_size, factor=gamma, mode="min", verbose=True)  

        # Training Loop
        for epoch in range(epochs):
            print('epochs {}/{}'.format(epoch+1,epochs))

            running_loss = 0.0
            total_sample_train = 0

            self.model.train()

            for batch_idx, (data, target) in enumerate(train_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)  

                self.optimizer.zero_grad()
                preds = self.model(data)

                loss = self.criterion(preds, target)
                loss.backward()
                self.optimizer.step() # Update model params

                running_loss += loss.item() * data.size(0)
                total_sample_train += data.size(0)

            train_loss = running_loss/total_sample_train
            #print(f"train loss: {train_loss}")
            scheduler.step(train_loss)
            current_lr = self.optimizer.param_groups[0]['lr']

            print(f'Current Learning Rate: {current_lr}')
            print(f"train_loss: {train_loss}")
        
        return self.model
            
    
    def test(self, config):
        batch_size = config["batch_size"]
        all_preds = []

        test_loader = DataLoader(dataset=self.test_data, batch_size=batch_size, shuffle=False)

        running_loss = .0
        total_sample = 0

        self.model.eval()

        with torch.no_grad():

            for batch_idx, (data, target) in enumerate(test_loader):

                data, target = data.to(self.device), target.to(self.device)
                target = target.view(-1,1)
                
                preds = self.model(data)
                loss = self.criterion(preds, target)

                running_loss += loss.item() * data.size(0)
                total_sample += data.size(0)

                all_preds.extend(preds.cpu().numpy())

            test_loss = running_loss/total_sample
            print(f"test_loss: {test_loss}")

        return all_preds

In [194]:

def objective(trial):

    config = {
        "batch_size": trial.suggest_int("batch_size", 32, 128, log=True),
        "epochs": trial.suggest_int("epochs", 50, 150),
        "hidden_size": trial.suggest_int("hidden_size", 10, 100),
        "learning_rate": trial.suggest_float("learning_rate", 1e-6, 1e-1, log=True),
        "dropout_prob": trial.suggest_float("dropout_prob", 0.0, 0.2),
        "weight_decay": trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True),
        "lr_step_size": trial.suggest_int("lr_step_size", 5, 100), 
        "gamma": trial.suggest_float("gamma", 0.1, 0.9),
        "num_layers": trial.suggest_int("num_layers", 1, 5)
    }

    trainer = ModelActioner(train_data, test_data, device)

    val_loss = trainer.train_validate(config, trial)

    return val_loss

In [195]:
study_name = "Vanilla-LSTM-Tunner"
storage_url = "sqlite:///db.sqlite3"

optuna.delete_study(study_name=study_name, storage= storage_url)

study = optuna.create_study(direction='minimize', 
                            storage=storage_url, 
                            sampler=TPESampler(),
                            pruner=optuna.pruners.HyperbandPruner(
                            min_resource=30,  
                            max_resource=150,  
                            reduction_factor=3,  
                            ),
                            study_name=study_name,
                            load_if_exists=False)

pbar = tqdm(total=10, desc='Optimizing', unit='trial')

def callback(study, trial):
    # Update the progress bar
    pbar.update(1)
    pbar.set_postfix_str(f"Best Value: {study.best_value:.4f}")


study.optimize(objective, n_trials=10, callbacks=[callback])
pbar.close()

# Best hyperparameters
print('Number of finished trials:', len(study.trials))
print('Best trial:')
trial = study.best_trial

print('Value:', trial.value)
print('Params:')
for key, value in trial.params.items():
    print(f'{key}: {value}')

[I 2024-01-30 19:34:37,780] A new study created in RDB with name: Vanilla-LSTM-Tunner

Optimizing:   0%|          | 0/10 [00:00<?, ?trial/s]

Starting fold 1:
epochs 1/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.004485888575436548, val_loss: 0.0020046627355946433
epochs 2/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.004308951908024028, val_loss: 0.0018713965358473756
epochs 3/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.003968987119151279, val_loss: 0.0017575479682938999
epochs 4/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0036144798970781265, val_loss: 0.001662491838615289
epochs 5/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0037448584917001426, val_loss: 0.001585145740401463
epochs 6/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0034108688472770155, val_loss: 0.0015240947438142798
epochs 7/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0032666847866494207, val_loss: 0.0014785699478274202
epochs 8/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0028615847229957582, val_loss: 0.0014472276375200304
epochs 9/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.002608271094504744, val_loss: 0.0014281665035351008
epochs 10/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.002487991051748395, val_loss: 0.0014195134556820252
epochs 11/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.002631694998126477, val_loss: 0.0014199203255379365
epochs 12/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0024816856719553472, val_loss: 0.0014281378711405008
epochs 13/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0022704453789629043, val_loss: 0.0014427278268461425
epochs 14/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0021505338954739273, val_loss: 0.001462418867968683
epochs 15/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0022029079147614537, val_loss: 0.0014859736558584565
epochs 16/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.00208506683120504, val_loss: 0.0015129261257782302
epochs 17/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.002107033191714436, val_loss: 0.0015421451824574322
epochs 18/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0019252439495176076, val_loss: 0.001572638381427775
epochs 19/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0018765745800919831, val_loss: 0.0016036407195743686
epochs 20/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001807537628337741, val_loss: 0.001635999961604645
epochs 21/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0019747545477002857, val_loss: 0.0016685161143960186
epochs 22/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0018671109108254313, val_loss: 0.0017002747702429555
epochs 23/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0018821744190063328, val_loss: 0.0017304895562735736
epochs 24/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0019666501320898533, val_loss: 0.0017598713059828336
epochs 25/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0019040799816139042, val_loss: 0.0017889894542922437
epochs 26/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017293535289354621, val_loss: 0.0018169219308734807
epochs 27/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017920634883921594, val_loss: 0.0018431688181528693
epochs 28/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016933688544668256, val_loss: 0.0018689629314442673
epochs 29/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017561329645104707, val_loss: 0.001893224992922374
epochs 30/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001804519788129255, val_loss: 0.001914841737031503
epochs 31/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016881095943972468, val_loss: 0.001935199916944223
epochs 32/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017890060960780829, val_loss: 0.0019533929658964986
epochs 33/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0018236403178889305, val_loss: 0.0019700558272205174
epochs 34/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001774332480272278, val_loss: 0.0019852390442605295
epochs 35/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017442131182178855, val_loss: 0.001998505684443646
epochs 36/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017173826228827239, val_loss: 0.0020120002876932697
epochs 37/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.00172840794257354, val_loss: 0.002021842729793024
epochs 38/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017430531152058393, val_loss: 0.00202999931911657
epochs 39/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016908602905459703, val_loss: 0.002038654080707895
epochs 40/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016933960985625162, val_loss: 0.002045241755214101
epochs 41/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017252194607863202, val_loss: 0.0020514473115172847
epochs 42/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001639221765799448, val_loss: 0.0020563808986153354
epochs 43/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016102140478324145, val_loss: 0.002061508875278628
epochs 44/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016717064601834864, val_loss: 0.0020642647379270147
epochs 45/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001619703762116842, val_loss: 0.002066612362223505
epochs 46/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016337873326847329, val_loss: 0.0020680011822300022
epochs 47/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001659858788480051, val_loss: 0.0020679855049666627
epochs 48/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017187811667099596, val_loss: 0.002068668686742919
epochs 49/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017486163007561118, val_loss: 0.0020704231226186037
epochs 50/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015561318956315517, val_loss: 0.0020731505398914494
epochs 51/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015121347940294072, val_loss: 0.002078303563711603
epochs 52/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016553451016079635, val_loss: 0.002080971100084267
epochs 53/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001645703479880467, val_loss: 0.0020814855849720223
epochs 54/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016443370201159268, val_loss: 0.0020794533716672393
epochs 55/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015909766836557538, val_loss: 0.0020776898800346152
epochs 56/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016759175749029964, val_loss: 0.0020727337022045894
epochs 57/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001532853304524906, val_loss: 0.0020669760307538564
epochs 58/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016501537174917758, val_loss: 0.0020607848277207088
epochs 59/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016782946127932518, val_loss: 0.002056761526517452
epochs 60/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015377113304566592, val_loss: 0.0020560125857911923
epochs 61/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001582308387150988, val_loss: 0.0020565198606284207
epochs 62/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016453017306048423, val_loss: 0.0020569918560795486
epochs 63/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016517853509867564, val_loss: 0.002059554433876343
epochs 64/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016372782381949946, val_loss: 0.0020631817030897807
epochs 65/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015315993892727419, val_loss: 0.002066711220390129
epochs 66/118
Epoch 00066: reducing learning rate of group 0 to 1.8965e-05.
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0017911403730977327, val_loss: 0.002068365852609671
epochs 67/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0016811240755487233, val_loss: 0.002071833076933645
epochs 68/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001656932954210788, val_loss: 0.0020749205270678634
epochs 69/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015186800097580998, val_loss: 0.0020769332950102
epochs 70/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015443833894096316, val_loss: 0.0020782356233602123
epochs 71/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015480117202969269, val_loss: 0.002078804974665954
epochs 72/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014977579412516207, val_loss: 0.0020798463121835123
epochs 73/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015980278432834894, val_loss: 0.002078656939033261
epochs 74/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0016096630279207602, val_loss: 0.0020781834227915005
epochs 75/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0016258591960649938, val_loss: 0.0020763880037949003
epochs 76/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001572166569530964, val_loss: 0.0020748373162908056
epochs 77/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001443401796859689, val_loss: 0.0020742381980800363
epochs 78/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014800684701185673, val_loss: 0.0020747058119417894
epochs 79/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0016163991997018457, val_loss: 0.002074825079131024
epochs 80/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015920999139780179, val_loss: 0.002074339793854585
epochs 81/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015779597888467833, val_loss: 0.0020720478903043958
epochs 82/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014686623471789062, val_loss: 0.0020710205897644515
epochs 83/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014595979853766039, val_loss: 0.0020686591862671315
epochs 84/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001591182075208053, val_loss: 0.0020646650661965684
epochs 85/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015513213904341683, val_loss: 0.002060497286803429
epochs 86/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0016068305791122838, val_loss: 0.0020573148279076333
epochs 87/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001533484776155092, val_loss: 0.002054005083640318
epochs 88/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015419963077874855, val_loss: 0.002051132459811886
epochs 89/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015817714243894442, val_loss: 0.0020475560108140583
epochs 90/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015083719394169749, val_loss: 0.002044904844653078
epochs 91/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015255156729836016, val_loss: 0.0020451784976536318
epochs 92/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015277055150363593, val_loss: 0.0020466646208506687
epochs 93/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015874651056947187, val_loss: 0.0020452029239287767
epochs 94/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0016201646067202091, val_loss: 0.0020450557204500512
epochs 95/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015756352164316922, val_loss: 0.002047137132163342
epochs 96/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001633057146682404, val_loss: 0.0020478536164210666
epochs 97/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001518429012503475, val_loss: 0.0020486857559132788
epochs 98/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015583794214762748, val_loss: 0.002050996963156476
epochs 99/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001434524095384404, val_loss: 0.0020523902137206977
epochs 100/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015672249632189051, val_loss: 0.00205273741995423
epochs 101/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014585566823370755, val_loss: 0.0020559534157020233
epochs 102/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014926582050975412, val_loss: 0.0020578416614428596
epochs 103/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001510028971824795, val_loss: 0.0020598638353120317
epochs 104/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014643800881458447, val_loss: 0.0020611462076736624
epochs 105/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001584900837042369, val_loss: 0.0020615026929474895
epochs 106/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015281650034012274, val_loss: 0.0020596291035260986
epochs 107/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014516588824335485, val_loss: 0.0020554912795199367
epochs 108/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014431722374865785, val_loss: 0.002051373949538049
epochs 109/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001440070359967649, val_loss: 0.0020469968606318745
epochs 110/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.001423348783282563, val_loss: 0.002044400829752838
epochs 111/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0013959473872091621, val_loss: 0.002040870840015708
epochs 112/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015373787085991354, val_loss: 0.0020362410571785872
epochs 113/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014690156531287357, val_loss: 0.0020317534199132334
epochs 114/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0013705893681617454, val_loss: 0.0020295187197108236
epochs 115/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014297253801487386, val_loss: 0.0020268447312191324
epochs 116/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0013584119791630656, val_loss: 0.0020262780845677728
epochs 117/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0014538854942657054, val_loss: 0.0020254811871964385
epochs 118/118
Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0015102654870133847, val_loss: 0.0020245344870201453
Starting fold 2:
epochs 1/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0018443630794480954, val_loss: 0.05107262586711576
epochs 2/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0017072358725397137, val_loss: 0.0500251264878051
epochs 3/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016744309495077875, val_loss: 0.049087342801232815
epochs 4/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015799166070417769, val_loss: 0.0482819317273362
epochs 5/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.00163424258626565, val_loss: 0.04762142792186409
epochs 6/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015858605631202027, val_loss: 0.04704499589624228
epochs 7/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015518118504196465, val_loss: 0.04655868825182397
epochs 8/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001545251681626649, val_loss: 0.0462113982805657
epochs 9/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001564296626235238, val_loss: 0.04592709346777863
epochs 10/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015892713999690238, val_loss: 0.04569011008140271
epochs 11/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015351608331686274, val_loss: 0.04549110320115846
epochs 12/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015700820667268634, val_loss: 0.04534665633130957
epochs 13/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0016070299552714252, val_loss: 0.04520199944575628
epochs 14/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014574465886775729, val_loss: 0.04506109586902081
epochs 15/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001536222876480837, val_loss: 0.0449244605879935
epochs 16/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015979517908738606, val_loss: 0.044795614031572194
epochs 17/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001509943705925713, val_loss: 0.04465532149114306
epochs 18/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001576622624452764, val_loss: 0.044569122284729645
epochs 19/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015179323527647432, val_loss: 0.04441059200418374
epochs 20/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015628194509536067, val_loss: 0.044293237455859384
epochs 21/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014486816555223524, val_loss: 0.04421027614759705
epochs 22/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014504892110368754, val_loss: 0.04412877160523619
epochs 23/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014725264158292788, val_loss: 0.044079801501341595
epochs 24/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0015154621746000345, val_loss: 0.044024257334294145
epochs 25/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014861298571119581, val_loss: 0.04389600387759625
epochs 26/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014146974946570026, val_loss: 0.04380515662253534
epochs 27/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014541783394036436, val_loss: 0.043737686835426504
epochs 28/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014579783065218753, val_loss: 0.043616650330405383
epochs 29/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001508444635271854, val_loss: 0.04351483373138955
epochs 30/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014694001807310276, val_loss: 0.04343316693194013
epochs 31/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001526535028148821, val_loss: 0.043355825677435234
epochs 32/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014504444801388676, val_loss: 0.043272164201846826
epochs 33/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.001361204214187678, val_loss: 0.04311875890565928
epochs 34/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014267428096206884, val_loss: 0.042997449922262045
epochs 35/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0014028990715570099, val_loss: 0.042856256728844036
epochs 36/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0013891454072058505, val_loss: 0.04271890450682905
epochs 37/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.00141184163107205, val_loss: 0.04259348871610152
epochs 38/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0013718189080958415, val_loss: 0.04240774763403116
epochs 39/118
Current Learning Rate: 2.4673051657737193e-05
train_loss: 0.0013302228271305108, val_loss: 0.04222436165486378
epochs 40/118
Current Learning Rate: 2.4673051657737193e-05

[I 2024-01-30 19:35:42,333] Trial 0 finished with value: 0.018739915842472716 and parameters: {'batch_size': 38, 'epochs': 118, 'hidden_size': 53, 'learning_rate': 2.4673051657737193e-05, 'dropout_prob': 0.09317487290501586, 'weight_decay': 1.3345533398684195e-05, 'lr_step_size': 55, 'gamma': 0.7686596064059844, 'num_layers': 3}. Best is trial 0 with value: 0.018739915842472716.

Current Learning Rate: 1.8965178176070793e-05
train_loss: 0.0013336083129327448, val_loss: 0.0027867277453421917
Mean validation loss: 0.018739915842472716
Starting fold 1:
epochs 1/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.01949898888675594, val_loss: 0.019394347207650306
epochs 2/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.008472136636019537, val_loss: 0.0016858066662698836
epochs 3/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.002080231519128, val_loss: 0.001291462383325404
epochs 4/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0015486749405298676, val_loss: 0.004296411076442353
epochs 5/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.002134553751123971, val_loss: 0.0014568676775698329
epochs 6/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0012836882805506895, val_loss: 0.0008217259386410227
epochs 7/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0009230047378591017, val_loss: 0.0018533318197735333
epochs 8/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0010308775886905526, val_loss: 0.0018692339058144995
epochs 9/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0006192334968976579, val_loss: 0.0007544132880404562
epochs 10/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.000657843295821773, val_loss: 0.002915228625559913
epochs 11/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.001275942433245578, val_loss: 0.0010952547215440842
epochs 12/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0002877270570024848, val_loss: 0.0007418626896290493
epochs 13/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0006549906200043073, val_loss: 0.0018914262519314116
epochs 14/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0007732416817146403, val_loss: 0.0015729032996219642
epochs 15/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0003454249695335564, val_loss: 0.0005739168624304945
epochs 16/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0004906890716244417, val_loss: 0.0008027478493565309
epochs 17/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0003115591619126989, val_loss: 0.001490756067574867
epochs 18/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0002827908375796764, val_loss: 0.00044850357424741286
epochs 19/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00036124830152594337, val_loss: 0.0007362007631205156
epochs 20/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0002157183669623919, val_loss: 0.0011169791936163887
epochs 21/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00016449934291334724, val_loss: 0.0005233110213238332
epochs 22/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0002126905524882635, val_loss: 0.0008782538404505301
epochs 23/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00020238865568229046, val_loss: 0.0009539840290912367
epochs 24/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00017122634798349618, val_loss: 0.0005876647755651483
epochs 25/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00015810248296475038, val_loss: 0.0010260539164601286
epochs 26/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001935866741022389, val_loss: 0.0006365413588817261
epochs 27/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00015879070361782063, val_loss: 0.0007683202400960634
epochs 28/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.000138482158294401, val_loss: 0.0009133408586623975
epochs 29/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00014157093146901676, val_loss: 0.0005899895456553038
epochs 30/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00017043569532688708, val_loss: 0.000929902204555378
epochs 31/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00016717885637741633, val_loss: 0.0005981360424941938
epochs 32/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00017372005922401226, val_loss: 0.0010287763748021376
epochs 33/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00017860877476203696, val_loss: 0.0005691924115313985
epochs 34/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00013785725765812554, val_loss: 0.0008032563929436802
epochs 35/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00013520116504208235, val_loss: 0.0007217604220458602
epochs 36/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00012195698517117356, val_loss: 0.0007953285584956156
epochs 37/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001433669361224594, val_loss: 0.0006123580209936739
epochs 38/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001541668095772988, val_loss: 0.0007767082662746635
epochs 39/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001423652609350699, val_loss: 0.0006395242690193718
epochs 40/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00012995018639087088, val_loss: 0.0009197261889413414
epochs 41/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00014024524831543922, val_loss: 0.0006473190214675259
epochs 42/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001406944361454072, val_loss: 0.0006429001805372536
epochs 43/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00011994115453777149, val_loss: 0.0009963194375842929
epochs 44/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00014972740586687762, val_loss: 0.0003940593207574686
epochs 45/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0002170088520200041, val_loss: 0.0014580479011841354
epochs 46/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00024875358894381575, val_loss: 0.0004175290205961256
epochs 47/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0002673096578004525, val_loss: 0.001813723356463015
epochs 48/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.000346291704121732, val_loss: 0.0006239301943597162
epochs 49/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0004992013333034456, val_loss: 0.003125634057343834
epochs 50/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0009784429937625598, val_loss: 0.000535538402179973
epochs 51/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0005511005223716462, val_loss: 0.0010140418981170534
epochs 52/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0004527894050146355, val_loss: 0.0014524564602262607
epochs 53/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00026541137700214197, val_loss: 0.00045631169170577316
epochs 54/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00042707069124413755, val_loss: 0.0017479070783814504
epochs 55/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0004357866118784602, val_loss: 0.0006490552080481032
epochs 56/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00021419539016757257, val_loss: 0.0005020352113032935
epochs 57/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00020489615769627944, val_loss: 0.0012030111268806708
epochs 58/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0002909127353249412, val_loss: 0.000606872007853189
epochs 59/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001684618301959218, val_loss: 0.0006309606142744925
epochs 60/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001631349462274413, val_loss: 0.000925211205506616
epochs 61/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001445888298851634, val_loss: 0.0005261382738974625
epochs 62/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00016745486998268844, val_loss: 0.0008055971488901709
epochs 63/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00013703050533781368, val_loss: 0.000691944897606311
epochs 64/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00012314276552244434, val_loss: 0.0006965070780198504
epochs 65/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00014227671965368483, val_loss: 0.0007191647256683883
epochs 66/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001248443706763761, val_loss: 0.0006416564068612864
epochs 67/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00011402705514276596, val_loss: 0.0006885337047389753
epochs 68/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00012670754842570445, val_loss: 0.0008352451717771131
epochs 69/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00011966366230473412, val_loss: 0.0005781826113225035
epochs 70/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00012408153040604177, val_loss: 0.0009348254682822338
epochs 71/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00015675539118666692, val_loss: 0.0004651030384203685
epochs 72/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00015765182661676877, val_loss: 0.001202593043137948
epochs 73/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00021053070652813307, val_loss: 0.0004754682004060005
epochs 74/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00017076534461107497, val_loss: 0.0010805104739986184
epochs 75/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.000245515330951955, val_loss: 0.0005331882418850289
epochs 76/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001648738910597259, val_loss: 0.0006975769032982902
epochs 77/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00015177649800438974, val_loss: 0.0005897870155638971
epochs 78/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001224457531766108, val_loss: 0.000747909928332009
epochs 79/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00013750911197061406, val_loss: 0.0006924456891803337
epochs 80/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001247796091391999, val_loss: 0.0007027061358149652
epochs 81/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00013820712276930479, val_loss: 0.0006789074611752146
epochs 82/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00011802721809975705, val_loss: 0.0006892444938467446
epochs 83/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00010684930350276103, val_loss: 0.0006947118210576712
epochs 84/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00012813374701899622, val_loss: 0.0006183529340122487
epochs 85/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00011574825330171735, val_loss: 0.0008759664742106069
epochs 86/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00011919249621936807, val_loss: 0.0005348610355877244
epochs 87/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00011417264820346118, val_loss: 0.0010911416497875175
epochs 88/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0001547990623389763, val_loss: 0.0004285747949440505
epochs 89/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00018358199480357336, val_loss: 0.0015424546180015785
epochs 90/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00027395161680607614, val_loss: 0.00042831082250885963
epochs 91/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00027188710235733247, val_loss: 0.002000402525207767
epochs 92/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0005108092124206259, val_loss: 0.00044481891901731227
epochs 93/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00033780708909034727, val_loss: 0.001635177656204351
epochs 94/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0004934605992227597, val_loss: 0.0007254676311276853
epochs 95/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00018034417214374498, val_loss: 0.000530647433137462
epochs 96/141
Epoch 00096: reducing learning rate of group 0 to 6.5735e-03.
Current Learning Rate: 0.006573469802295223
train_loss: 0.000212852344894169, val_loss: 0.0010803369648148499
epochs 97/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00016879433012371393, val_loss: 0.00048426785048962174
epochs 98/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00019038801102923524, val_loss: 0.0008054552074301884
epochs 99/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00016872997159800052, val_loss: 0.0009174186327852242
epochs 100/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00013499567660466328, val_loss: 0.0005072356238203596
epochs 101/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.0001748979038797858, val_loss: 0.0009561001568236241
epochs 102/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00016983831240060298, val_loss: 0.0007034078050295763
epochs 103/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00013172861554745682, val_loss: 0.0005118796712301287
epochs 104/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00014161939555043846, val_loss: 0.0009413773133553424
epochs 105/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00014520931516400244, val_loss: 0.0006384201052631917
epochs 106/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00012555585681662992, val_loss: 0.0006727832068073829
epochs 107/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00011532206986693813, val_loss: 0.0007651463082376202
epochs 108/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.0001228784544142208, val_loss: 0.0006478015703679477
epochs 109/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00010398161772938788, val_loss: 0.0008715751552252129
epochs 110/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00012381132251711708, val_loss: 0.0006366748378255464
epochs 111/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00010926495999324527, val_loss: 0.0007682686055121604
epochs 112/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.0001177065803188414, val_loss: 0.0007276042440300068
epochs 113/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00010299998075903492, val_loss: 0.0006297389733686393
epochs 114/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00011492773800886139, val_loss: 0.0007827162559214417
epochs 115/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00010137778322371703, val_loss: 0.0006413542291811031
epochs 116/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00010955930545031534, val_loss: 0.0007783248492780822
epochs 117/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00011292200108169039, val_loss: 0.0006153708677701947
epochs 118/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00011073621958769906, val_loss: 0.0007468568955017771
epochs 119/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00013289254830421045, val_loss: 0.0006788652429508696
epochs 120/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00010962173956182884, val_loss: 0.0007657380949009196
epochs 121/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00012386344973684143, val_loss: 0.0007299168043703373
epochs 122/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00010790926137001646, val_loss: 0.0007818441681881687
epochs 123/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00012698905951478274, val_loss: 0.0006503302309226008
epochs 124/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00011147150228345325, val_loss: 0.0008738471861718045
epochs 125/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.0001248963803702377, val_loss: 0.000556996557399601
epochs 126/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00013954775319067076, val_loss: 0.0009826189798043323
epochs 127/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00016356346650833362, val_loss: 0.0005102469763692676
epochs 128/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00012899279988088988, val_loss: 0.001037778207636808
epochs 129/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00015460445735554555, val_loss: 0.0005365907737065018
epochs 130/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00013874048753151377, val_loss: 0.0009841119822268079
epochs 131/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00013767158322336497, val_loss: 0.0005094108099232442
epochs 132/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.0001585393031985548, val_loss: 0.001051798425333035
epochs 133/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.0001626385411854196, val_loss: 0.0005161796529252555
epochs 134/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00014859661360357054, val_loss: 0.0010055046242043665
epochs 135/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.0001583247774090667, val_loss: 0.0005094633998519312
epochs 136/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00014674040790659521, val_loss: 0.0010578705464251385
epochs 137/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.0001625303168303186, val_loss: 0.0005490486020414484
epochs 138/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00013714680382307913, val_loss: 0.0009272980531686843
epochs 139/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00014418334252887257, val_loss: 0.0005508111401771506
epochs 140/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.000143776931738677, val_loss: 0.000951403328982119
epochs 141/141
Current Learning Rate: 0.006573469802295223
train_loss: 0.00013751494353575827, val_loss: 0.0006284178546463538
Starting fold 2:
epochs 1/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.003005035956774772, val_loss: 0.041597913684589524
epochs 2/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.002278626848830495, val_loss: 0.044699976398121746
epochs 3/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0024519502822651297, val_loss: 0.04653351718471164
epochs 4/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0014481998528206432, val_loss: 0.04010235036294612
epochs 5/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0014709000450977934, val_loss: 0.030053470594187576
epochs 6/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.001172190830728904, val_loss: 0.015220984720462372
epochs 7/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0013390625280837681, val_loss: 0.03330307223257564
epochs 8/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0006677554971381831, val_loss: 0.020321025143540096
epochs 9/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0008380456255794328, val_loss: 0.02134520032753547
epochs 10/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0004574368142806691, val_loss: 0.011998344094507278
epochs 11/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00039979903282208175, val_loss: 0.009929099397379019
epochs 12/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.0005044114419952094, val_loss: 0.011040377467575054
epochs 13/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00024823677525434785, val_loss: 0.007477888512232947
epochs 14/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00037403157587368336, val_loss: 0.01085962432007941
epochs 15/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00038297338867197573, val_loss: 0.008197214714961038
epochs 16/141
Current Learning Rate: 0.008051037886044223
train_loss: 0.00025785267045125515, val_loss: 0.007651737477216456
epochs 17/141
Current Learning Rate: 0.008051037886044223

[I 2024-01-30 19:38:16,802] Trial 1 finished with value: 0.07245369398238109 and parameters: {'batch_size': 69, 'epochs': 141, 'hidden_size': 98, 'learning_rate': 0.008051037886044223, 'dropout_prob': 0.14526038223225965, 'weight_decay': 2.4094297972175474e-05, 'lr_step_size': 51, 'gamma': 0.8164748316101907, 'num_layers': 3}. Best is trial 0 with value: 0.018739915842472716.

Current Learning Rate: 0.008051037886044223
train_loss: 0.10100150399547991, val_loss: 0.05502023376406185
Mean validation loss: 0.07245369398238109
Starting fold 1:
epochs 1/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.010032082020648215, val_loss: 0.009307515051058203
epochs 2/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.005940123434227548, val_loss: 0.0057237491703951955
epochs 3/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.004167365616089419, val_loss: 0.003298637508008156
epochs 4/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.002680141245333576, val_loss: 0.0018610302458958276
epochs 5/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0020047462851691404, val_loss: 0.0011794634590543826
epochs 6/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.001817776331077575, val_loss: 0.0009407914399474899
epochs 7/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0018251529229976432, val_loss: 0.0008812581533757063
epochs 8/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.001483078595361133, val_loss: 0.0008675631866531654
epochs 9/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0015669263540889675, val_loss: 0.0008655821164779208
epochs 10/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0016528202937670837, val_loss: 0.0008857457372070433
epochs 11/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.001540391697658618, val_loss: 0.0009412967338763848
epochs 12/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0014122258507229975, val_loss: 0.0010220499345989622
epochs 13/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0015211325999667966, val_loss: 0.0011041252618217002
epochs 14/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.001402402570544693, val_loss: 0.0011764288888092365
epochs 15/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.001607552121123789, val_loss: 0.0012081392081984116
epochs 16/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0011993578947639388, val_loss: 0.001216726959990978
epochs 17/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0013861098630035197, val_loss: 0.0011824009467745397
epochs 18/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0015158532542715731, val_loss: 0.0011256807479113045
epochs 19/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0012853404963511581, val_loss: 0.0010600853159317806
epochs 20/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0010269556408993115, val_loss: 0.0010144131185139515
epochs 21/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0012633794676635021, val_loss: 0.0009694626967843977
epochs 22/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0013699199927750191, val_loss: 0.0009269623953427765
epochs 23/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0010978934106931678, val_loss: 0.0008938487104223992
epochs 24/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0012204265840792734, val_loss: 0.0008758467857857733
epochs 25/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0011632292237328855, val_loss: 0.0008623319073295635
epochs 26/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0011101751572967164, val_loss: 0.0008653800722972919
epochs 27/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0012606483957681217, val_loss: 0.000879177230729958
epochs 28/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.001085556560581991, val_loss: 0.0008950005837490723
epochs 29/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009751394617763397, val_loss: 0.0009157476083913857
epochs 30/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009271305700837586, val_loss: 0.0009341942568810991
epochs 31/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.001157271351947106, val_loss: 0.0009323402700444349
epochs 32/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0011278469784883783, val_loss: 0.0009176274303441729
epochs 33/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0010945637563341542, val_loss: 0.0009149872474914426
epochs 34/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0010073979189129253, val_loss: 0.0009237967616177494
epochs 35/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.000886663103990845, val_loss: 0.0009217433038256353
epochs 36/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008616906612204682, val_loss: 0.0009009529803830282
epochs 37/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009572850610742248, val_loss: 0.0008686349582310185
epochs 38/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009208924884564783, val_loss: 0.0008414648566425842
epochs 39/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009281324948747887, val_loss: 0.0008132821013633576
epochs 40/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009696151488338058, val_loss: 0.0007998311792675248
epochs 41/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008135620379011686, val_loss: 0.0008033670465155165
epochs 42/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009033723951832048, val_loss: 0.0008189084327708259
epochs 43/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008637372088790136, val_loss: 0.0008366639127156564
epochs 44/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008112533845154471, val_loss: 0.0008533414446030591
epochs 45/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008659595743091287, val_loss: 0.0008677041386599066
epochs 46/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009593506619383238, val_loss: 0.0008684980348719619
epochs 47/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0010391839390841166, val_loss: 0.0008636647133956166
epochs 48/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008558038203964794, val_loss: 0.0008543312356181482
epochs 49/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.000883814437915326, val_loss: 0.0008428847629277568
epochs 50/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007695734712270726, val_loss: 0.0008404070951713486
epochs 51/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009032481984161821, val_loss: 0.000828498733835418
epochs 52/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008440475861885045, val_loss: 0.0007980921490964228
epochs 53/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007370149131594716, val_loss: 0.0007686305872907507
epochs 54/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008433496470771436, val_loss: 0.0007423164412901594
epochs 55/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005755697557776186, val_loss: 0.0007296664680806408
epochs 56/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007972429846535976, val_loss: 0.0007239802489974955
epochs 57/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007076145183466571, val_loss: 0.0007323024049308891
epochs 58/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007015719173451592, val_loss: 0.0007421083030138145
epochs 59/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.000802242951957803, val_loss: 0.000749338998936028
epochs 60/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007413284525299739, val_loss: 0.0007416114745268638
epochs 61/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007755661269919457, val_loss: 0.0007373621092435396
epochs 62/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.000826382932504394, val_loss: 0.0007269272441999178
epochs 63/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007186005647159426, val_loss: 0.0007123323745665845
epochs 64/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007423591628474625, val_loss: 0.0007008657629494481
epochs 65/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005171786681258757, val_loss: 0.0006982745336634773
epochs 66/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007284881853449501, val_loss: 0.0007087909002115743
epochs 67/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006868955827820556, val_loss: 0.0007241555439861413
epochs 68/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006618472873110717, val_loss: 0.0007376322779458302
epochs 69/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006867884033310571, val_loss: 0.0007613598013810429
epochs 70/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006482971948571503, val_loss: 0.000789037618752835
epochs 71/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006257395779309599, val_loss: 0.0007968389279167193
epochs 72/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007131674519960621, val_loss: 0.0007864240156277206
epochs 73/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006368889418234559, val_loss: 0.0007626335418391381
epochs 74/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006725785533873071, val_loss: 0.0007301669176846556
epochs 75/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007308659278542587, val_loss: 0.000701528117239288
epochs 76/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006676079956569562, val_loss: 0.00068267680431726
epochs 77/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006535046761487856, val_loss: 0.0006684886747275149
epochs 78/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007258052144224118, val_loss: 0.000662137501027371
epochs 79/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005995234587891518, val_loss: 0.0006726817909299233
epochs 80/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005491166412340183, val_loss: 0.0006740154297658976
epochs 81/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006596376828383654, val_loss: 0.0006698784020343775
epochs 82/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.000584953928697168, val_loss: 0.0006671263753940356
epochs 83/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006677403277104818, val_loss: 0.0006666363501199398
epochs 84/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006184569446639599, val_loss: 0.0006780268352019241
epochs 85/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006972794761072452, val_loss: 0.0006894937370104282
epochs 86/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005473509983858094, val_loss: 0.0006996025402153098
epochs 87/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005787444657854441, val_loss: 0.0007050685496309713
Starting fold 2:
epochs 1/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0009466428705921156, val_loss: 0.026203140976134118
epochs 2/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007009651573494047, val_loss: 0.02146225912181079
epochs 3/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008881186038510023, val_loss: 0.02085052360164583
epochs 4/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0008982846428613157, val_loss: 0.021751030944484884
epochs 5/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007505393230742074, val_loss: 0.022150325214381886
epochs 6/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007579512212248544, val_loss: 0.021996062465761072
epochs 7/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007850504317505182, val_loss: 0.021743331552931556
epochs 8/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006320304698052775, val_loss: 0.021726141745352714
epochs 9/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007049108207770095, val_loss: 0.02159644737248383
epochs 10/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006757881504662906, val_loss: 0.02110870959355481
epochs 11/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007176782051531357, val_loss: 0.020692818936098506
epochs 12/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006782982330541999, val_loss: 0.01998153860587134
epochs 13/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007112987739885456, val_loss: 0.019523155050125543
epochs 14/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006918011847232274, val_loss: 0.019298557822824157
epochs 15/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0007212707768397106, val_loss: 0.01923836240170415
epochs 16/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005986303143881477, val_loss: 0.01940454387662824
epochs 17/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005841234542698523, val_loss: 0.01977886548315091
epochs 18/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006068016465084927, val_loss: 0.01981460439563586
epochs 19/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006150940639251907, val_loss: 0.01955226568810681
epochs 20/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006188353896663232, val_loss: 0.018940506404433302
epochs 21/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005431793708296488, val_loss: 0.01846749049231962
epochs 22/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006571416464347963, val_loss: 0.018387278381774508
epochs 23/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006340845431339998, val_loss: 0.018387728602324845
epochs 24/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0006075875518326267, val_loss: 0.018811317658416492
epochs 25/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005910676648461881, val_loss: 0.018880718281719264
epochs 26/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005792776494511799, val_loss: 0.01850010051081578
epochs 27/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005881030390181611, val_loss: 0.018319821625790267
epochs 28/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.000582516544018098, val_loss: 0.01811437961206865
epochs 29/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005805343136100448, val_loss: 0.017447894101558382
epochs 30/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005618482507153421, val_loss: 0.01724626600407261
epochs 31/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005354163618414297, val_loss: 0.017172172037322842
epochs 32/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005443311172923304, val_loss: 0.017101312137489753
epochs 33/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005592916226555104, val_loss: 0.017113874861034294
epochs 34/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005019615999592522, val_loss: 0.016989410625741122
epochs 35/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005183882752094309, val_loss: 0.017161037536367538
epochs 36/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005161762732851483, val_loss: 0.016935058450572704
epochs 37/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005162728312707907, val_loss: 0.016646848794407944
epochs 38/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005171512666565064, val_loss: 0.016675643211417887
epochs 39/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004976017853382748, val_loss: 0.016609708275941628
epochs 40/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005090241734335312, val_loss: 0.016306742138805844
epochs 41/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00048428182288977296, val_loss: 0.01614957357751866
epochs 42/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004815926030001758, val_loss: 0.016801919869428115
epochs 43/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004948988524763194, val_loss: 0.016924786630268925
epochs 44/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00046724435146271414, val_loss: 0.016717093230456746
epochs 45/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005717346545168761, val_loss: 0.016090884469646627
epochs 46/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00042663123225178916, val_loss: 0.015356692310580343
epochs 47/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005076373022695939, val_loss: 0.015511991882391234
epochs 48/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004920511302079927, val_loss: 0.015938952478959604
epochs 49/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005024696206047364, val_loss: 0.01605545155575903
epochs 50/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005372256983721525, val_loss: 0.015903495946928622
epochs 51/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004993966700893761, val_loss: 0.015697237106641292
epochs 52/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004660510945675703, val_loss: 0.015468836838389358
epochs 53/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00042280314492042074, val_loss: 0.015564485443213944
epochs 54/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00047957202211381143, val_loss: 0.015573471084867835
epochs 55/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005027129412210967, val_loss: 0.015363313028559325
epochs 56/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00047387877364930424, val_loss: 0.015089407846548412
epochs 57/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00047229993492512324, val_loss: 0.01496418036776718
epochs 58/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00044557909746310306, val_loss: 0.015264061491483103
epochs 59/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004747457118701229, val_loss: 0.015491705387830734
epochs 60/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00045385166591384735, val_loss: 0.015234952405706126
epochs 61/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004278291289425531, val_loss: 0.014934052272192227
epochs 62/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004346675437163699, val_loss: 0.014910936966617272
epochs 63/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0005506377957151873, val_loss: 0.014827562993756992
epochs 64/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004262481294701362, val_loss: 0.01451042043932137
epochs 65/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00043670125112139024, val_loss: 0.014945230606903948
epochs 66/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004582518203636155, val_loss: 0.01505104219294572
epochs 67/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00043214949873511955, val_loss: 0.014777191089239543
epochs 68/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004754691487018481, val_loss: 0.014750032882802385
epochs 69/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004132129446238446, val_loss: 0.014646072430959927
epochs 70/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00041769989168745684, val_loss: 0.014328121237220272
epochs 71/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.0004981517782379532, val_loss: 0.014212119375803956
epochs 72/87
Current Learning Rate: 0.0002530278977234123
train_loss: 0.00045471846683216245, val_loss: 0.014179562430375468
epochs 73/87
Current Learning Rate: 0.0002530278977234123

[I 2024-01-30 19:38:54,132] Trial 2 finished with value: 0.006284757489032097 and parameters: {'batch_size': 71, 'epochs': 87, 'hidden_size': 73, 'learning_rate': 0.0002530278977234123, 'dropout_prob': 0.19078610695820522, 'weight_decay': 0.001629521629180977, 'lr_step_size': 90, 'gamma': 0.24778531965365228, 'num_layers': 1}. Best is trial 2 with value: 0.006284757489032097.

Current Learning Rate: 0.0002530278977234123
train_loss: 0.0011838860542607694, val_loss: 0.0012901131255877397
Mean validation loss: 0.006284757489032097
Starting fold 1:
epochs 1/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.005518734362895453, val_loss: 0.002612494853714471
epochs 2/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.004248486407787392, val_loss: 0.0071760587524819786
epochs 3/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.005918447881642925, val_loss: 0.0029766806256563143
epochs 4/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.002496612462288651, val_loss: 0.0009336317515970213
epochs 5/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0014551196500083039, val_loss: 0.0009096272182884926
epochs 6/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.001139850750577783, val_loss: 0.0007112708857262053
epochs 7/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0006020469969371334, val_loss: 0.0012346437852583313
epochs 8/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008359219445418076, val_loss: 0.0013827332168436862
epochs 9/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007402712748827119, val_loss: 0.0006091351876935857
epochs 10/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0002633343245466485, val_loss: 0.0003454026073327032
epochs 11/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00020752370129278126, val_loss: 0.00030137949848991683
epochs 12/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00019979505795115408, val_loss: 0.0003453277132446784
epochs 13/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0001755602351055897, val_loss: 0.0003994236721487213
epochs 14/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00011493506348128186, val_loss: 0.00021667761237560107
epochs 15/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00014291148890103949, val_loss: 0.00022843021314844327
epochs 16/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00018017251690923187, val_loss: 0.00029031070611111956
epochs 17/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0001222219064641793, val_loss: 0.0003724479132745213
epochs 18/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00012228475794759825, val_loss: 0.0003062165811936317
epochs 19/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00011515971051075643, val_loss: 0.0002835780076027192
epochs 20/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00011422029730104106, val_loss: 0.00030717146670674933
epochs 21/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0001312649156285548, val_loss: 0.00034975046994904964
epochs 22/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00010639577881910986, val_loss: 0.00035401674371093227
epochs 23/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.551253466928182e-05, val_loss: 0.00030211276170260534
epochs 24/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.422370746146618e-05, val_loss: 0.0002655493023604519
epochs 25/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00016121263049028226, val_loss: 0.0002942904837678369
epochs 26/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.473656258202697e-05, val_loss: 0.0003160687722681489
epochs 27/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00012368386317240565, val_loss: 0.00028194337063863203
epochs 28/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00011999145798127805, val_loss: 0.0002615793382381853
epochs 29/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00013291709248350295, val_loss: 0.0002703469188649222
epochs 30/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.506220642869409e-05, val_loss: 0.000264522198386855
epochs 31/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.273670046994659e-05, val_loss: 0.0002568903903165221
epochs 32/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.873494178056717e-05, val_loss: 0.0002608770004439133
epochs 33/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0001017995767669115, val_loss: 0.00027149592619574083
epochs 34/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.480268661514856e-05, val_loss: 0.00025236322866351143
epochs 35/146
Current Learning Rate: 0.005264885042493901
train_loss: 9.892839907000675e-05, val_loss: 0.00023489100475137728
epochs 36/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00010056249995709789, val_loss: 0.00026809271201263456
epochs 37/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.218608663331619e-05, val_loss: 0.00030025652093596005
epochs 38/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00011359475902281702, val_loss: 0.0002501484643924789
epochs 39/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.305901792853164e-05, val_loss: 0.00022691852525837482
epochs 40/146
Current Learning Rate: 0.005264885042493901
train_loss: 9.436239668407085e-05, val_loss: 0.0002541024213310001
epochs 41/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.626355246585598e-05, val_loss: 0.00027429968936038674
epochs 42/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00011785670538206193, val_loss: 0.00023347968063144772
epochs 43/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.818149733207017e-05, val_loss: 0.00025025357014287717
epochs 44/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.630456051341944e-05, val_loss: 0.0003006381121902633
epochs 45/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0001011091000691522, val_loss: 0.00026609530996884805
epochs 46/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00011500165798535914, val_loss: 0.0002220321542746018
epochs 47/146
Current Learning Rate: 0.005264885042493901
train_loss: 9.38054265708687e-05, val_loss: 0.0002445801905071161
epochs 48/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.422256573339262e-05, val_loss: 0.00026868415890026235
epochs 49/146
Current Learning Rate: 0.005264885042493901
train_loss: 9.947831433811715e-05, val_loss: 0.00022089172853156924
epochs 50/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00010812596290059828, val_loss: 0.0002442110599654298
epochs 51/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.334174471153682e-05, val_loss: 0.0002625615229132886
epochs 52/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.74441605303314e-05, val_loss: 0.0002445597720142114
epochs 53/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.001324732922704e-05, val_loss: 0.00024599135571089204
epochs 54/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.094041284660833e-05, val_loss: 0.0002496167557346684
epochs 55/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.7872871280108626e-05, val_loss: 0.0002365526036810864
epochs 56/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.04764642931619e-05, val_loss: 0.0002538313179568846
epochs 57/146
Current Learning Rate: 0.005264885042493901
train_loss: 9.046585197977134e-05, val_loss: 0.00027104242072377855
epochs 58/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.449364922266748e-05, val_loss: 0.0002269607456770563
epochs 59/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.98459235260165e-05, val_loss: 0.0002418160836212953
epochs 60/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.304115832097044e-05, val_loss: 0.00024043084169207043
epochs 61/146
Current Learning Rate: 0.005264885042493901
train_loss: 9.68698802018097e-05, val_loss: 0.00022381033891443627
epochs 62/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.108714516538097e-05, val_loss: 0.00024525534097356573
epochs 63/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.625266150614295e-05, val_loss: 0.0002514997911969047
epochs 64/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00010740106494937975, val_loss: 0.0002564811071910077
epochs 65/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.032459662265242e-05, val_loss: 0.00022104220757711797
epochs 66/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.379789393254261e-05, val_loss: 0.00023741486394394771
epochs 67/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.066396000326341e-05, val_loss: 0.000258951212917627
epochs 68/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.016654448761409e-05, val_loss: 0.00022044802885613448
epochs 69/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.665079283099131e-05, val_loss: 0.00023187962633239786
epochs 70/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.38986394685497e-05, val_loss: 0.0002560034926217567
epochs 71/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.275031350314079e-05, val_loss: 0.00021970514361296963
epochs 72/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.849771845353595e-05, val_loss: 0.0002268667990513018
epochs 73/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.547348597163555e-05, val_loss: 0.0002470055715767322
epochs 74/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.92191465005683e-05, val_loss: 0.00020955540575505919
epochs 75/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.30683026131316e-05, val_loss: 0.00023017493356111652
epochs 76/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.96898589608578e-05, val_loss: 0.00026764306641693806
epochs 77/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.921943045809473e-05, val_loss: 0.00021805869010874568
epochs 78/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.6524771284066924e-05, val_loss: 0.0002452888665844011
epochs 79/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.2552885034329895e-05, val_loss: 0.00023149916238955927
epochs 80/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.263345004347348e-05, val_loss: 0.00022783860359119163
epochs 81/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.691013534464506e-05, val_loss: 0.00023470614568968476
epochs 82/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00010167081919988911, val_loss: 0.00021565195670254065
epochs 83/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.545050745983117e-05, val_loss: 0.00021737737948550453
epochs 84/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.31455982473103e-05, val_loss: 0.00022323243858948075
epochs 85/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.654498258859875e-05, val_loss: 0.0002339780284846374
epochs 86/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.692223603175463e-05, val_loss: 0.00024293489149333072
epochs 87/146
Current Learning Rate: 0.005264885042493901
train_loss: 9.869087696547228e-05, val_loss: 0.00026822114450239244
epochs 88/146
Current Learning Rate: 0.005264885042493901
train_loss: 9.285480444209259e-05, val_loss: 0.00021125876321488124
epochs 89/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.332730493005855e-05, val_loss: 0.00023267945314285705
epochs 90/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.286910867581978e-05, val_loss: 0.0002412221275677131
epochs 91/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.9454693722440614e-05, val_loss: 0.0002004829302051957
epochs 92/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.183002160206486e-05, val_loss: 0.0002755725649612027
epochs 93/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.91695090943923e-05, val_loss: 0.00023096761784501492
epochs 94/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.680605283212284e-05, val_loss: 0.0002180544452996747
epochs 95/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.141847718709247e-05, val_loss: 0.0002431060880774918
epochs 96/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.6236306658033034e-05, val_loss: 0.000181472504062753
epochs 97/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.122329045996977e-05, val_loss: 0.0002466667689395041
epochs 98/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.467588289536683e-05, val_loss: 0.00023357653459897461
epochs 99/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.838300833267184e-05, val_loss: 0.00021635248451573754
epochs 100/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.324798837579836e-05, val_loss: 0.000258629603291247
epochs 101/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.301589704973403e-05, val_loss: 0.0002027152056273605
epochs 102/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.744122660728049e-05, val_loss: 0.0002360001325200154
epochs 103/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.536226702014622e-05, val_loss: 0.00026998408025570423
epochs 104/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.170820830843265e-05, val_loss: 0.00018230034361800386
epochs 105/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.312330436482291e-05, val_loss: 0.00026240437949478514
epochs 106/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.9915686215513e-05, val_loss: 0.00020370668705143823
epochs 107/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.702138018322569e-05, val_loss: 0.00021975836073690236
epochs 108/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.260858495615569e-05, val_loss: 0.00023827987338312183
epochs 109/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.246239187787165e-05, val_loss: 0.00019080438956041776
epochs 110/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.5755966356005766e-05, val_loss: 0.0002405773005015574
epochs 111/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.494828181231002e-05, val_loss: 0.0002150238472269232
epochs 112/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.5653503104143677e-05, val_loss: 0.00020515233132447407
epochs 113/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.4917227699709324e-05, val_loss: 0.00022665892068833167
epochs 114/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.536414384167935e-05, val_loss: 0.00020467952893499935
epochs 115/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.4679521379416416e-05, val_loss: 0.00021541764172503637
epochs 116/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.4322389137508396e-05, val_loss: 0.00021211452820343236
epochs 117/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.38506594872237e-05, val_loss: 0.0002268327160597663
epochs 118/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.5032584101641794e-05, val_loss: 0.00019088787786328732
epochs 119/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.704509934180685e-05, val_loss: 0.00023406420213557783
epochs 120/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.500641872410932e-05, val_loss: 0.00018319731824458502
epochs 121/146
Current Learning Rate: 0.005264885042493901
train_loss: 4.670992099195964e-05, val_loss: 0.0002064759943990909
epochs 122/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.23548118471119e-05, val_loss: 0.00023580061569523496
epochs 123/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.5199958603081636e-05, val_loss: 0.0001718617915887282
epochs 124/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.271088703814281e-05, val_loss: 0.0003029254504812699
epochs 125/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.133243550350399e-05, val_loss: 0.0001608276344812968
epochs 126/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.582260212242162e-05, val_loss: 0.00020952046897416938
epochs 127/146
Current Learning Rate: 0.005264885042493901
train_loss: 4.9237898948424695e-05, val_loss: 0.00020173498353595653
epochs 128/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.929200255973755e-05, val_loss: 0.0001977023693764331
epochs 129/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.804975457366948e-05, val_loss: 0.00023571372297564742
epochs 130/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.759414069823259e-05, val_loss: 0.00019526439462511224
epochs 131/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.425441883816873e-05, val_loss: 0.0002452462352666001
epochs 132/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.461004978566626e-05, val_loss: 0.00017747416582313322
epochs 133/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.354171073912815e-05, val_loss: 0.00020992545864948874
epochs 134/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.368616230522381e-05, val_loss: 0.00017615640747684877
epochs 135/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.27764055791072e-05, val_loss: 0.0002087633657976295
epochs 136/146
Current Learning Rate: 0.005264885042493901
train_loss: 4.960829807571013e-05, val_loss: 0.00019390597549438348
epochs 137/146
Current Learning Rate: 0.005264885042493901
train_loss: 4.859042461535673e-05, val_loss: 0.00022527523234929452
epochs 138/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.293078594197715e-05, val_loss: 0.00019586824867584885
epochs 139/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.508056984629212e-05, val_loss: 0.00022295230043936206
epochs 140/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.668479731723078e-05, val_loss: 0.00016087314182345474
epochs 141/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.352217822770686e-05, val_loss: 0.0002215793021951824
epochs 142/146
Current Learning Rate: 0.005264885042493901
train_loss: 5.870873348229859e-05, val_loss: 0.00015997755205413947
epochs 143/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.618762973199697e-05, val_loss: 0.0003002156958842611
epochs 144/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.885066776285194e-05, val_loss: 0.00017272732622500154
epochs 145/146
Current Learning Rate: 0.005264885042493901
train_loss: 7.196662349758155e-05, val_loss: 0.00027523742384377687
epochs 146/146
Current Learning Rate: 0.005264885042493901
train_loss: 6.531060201890987e-05, val_loss: 0.00016529518051784997
Starting fold 2:
epochs 1/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0009485123779964578, val_loss: 0.0034503708569679123
epochs 2/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0010646100285862962, val_loss: 0.020810888740160162
epochs 3/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0003342845444796339, val_loss: 0.01153450134634065
epochs 4/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005804431197905574, val_loss: 0.01182471189608492
epochs 5/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0003463592009038645, val_loss: 0.012475728562407236
epochs 6/146
Current Learning Rate: 0.005264885042493901
train_loss: 9.717548203545237e-05, val_loss: 0.005498743136524267
epochs 7/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0001965126273880214, val_loss: 0.005363809262037711
epochs 8/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00013024996275809903, val_loss: 0.004050039254324806
epochs 9/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00013012296618773335, val_loss: 0.0039027204211042436
epochs 10/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00012336762173231544, val_loss: 0.004821460268450359
epochs 11/146
Current Learning Rate: 0.005264885042493901
train_loss: 8.673829820617115e-05, val_loss: 0.004216888789198406
epochs 12/146
Current Learning Rate: 0.005264885042493901

[I 2024-01-30 19:39:56,835] Trial 3 finished with value: 0.0018078895155108786 and parameters: {'batch_size': 79, 'epochs': 146, 'hidden_size': 19, 'learning_rate': 0.005264885042493901, 'dropout_prob': 0.006817452931502488, 'weight_decay': 4.962885626360071e-06, 'lr_step_size': 82, 'gamma': 0.669249506127128, 'num_layers': 1}. Best is trial 3 with value: 0.0018078895155108786.

Current Learning Rate: 0.0035235217145051464
train_loss: 0.0005648119225083426, val_loss: 0.0011413713335675538
Mean validation loss: 0.0018078895155108786
Starting fold 1:
epochs 1/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.043676643102968996, val_loss: 0.05121490254840523
epochs 2/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.038064873483228054, val_loss: 0.044884924850766623
epochs 3/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.03255039916226738, val_loss: 0.03886568971057102
epochs 4/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.027331594073850857, val_loss: 0.03312479603109221
epochs 5/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.023130509771994854, val_loss: 0.027668965517213106
epochs 6/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.018769729774641364, val_loss: 0.02248480632684376
epochs 7/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.014942951733246446, val_loss: 0.017599347111566986
epochs 8/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.010983928550328863, val_loss: 0.013067772072399892
epochs 9/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.007780658063405242, val_loss: 0.009022285834092784
epochs 10/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.004978704984042499, val_loss: 0.005697987189580484
epochs 11/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.0030538502951936893, val_loss: 0.003368741327899178
epochs 12/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.0021602471083353616, val_loss: 0.002129562466285837
epochs 13/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.0018627532019500474, val_loss: 0.0016805411212666148
epochs 14/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.001978172196418439, val_loss: 0.0016303836861095594
epochs 15/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.002046921611824808, val_loss: 0.001780535585047411
epochs 16/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.0019847015219152365, val_loss: 0.0020791557748375765
epochs 17/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.001943427716737221, val_loss: 0.0024768042784041318
epochs 18/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.0020239414947450553, val_loss: 0.00276768249280938
epochs 19/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.0019043905645192258, val_loss: 0.0029226307431975056
epochs 20/101
Current Learning Rate: 0.00018690713625368872
train_loss: 0.002373530030385346, val_loss: 0.0029349266255777034
epochs 21/101
Epoch 00021: reducing learning rate of group 0 to 6.7793e-05.
Current Learning Rate: 6.779305879384596e-05
train_loss: 0.002174544807731811, val_loss: 0.0028206228698042057
epochs 22/101
Current Learning Rate: 6.779305879384596e-05
train_loss: 0.0017483929570421184, val_loss: 0.002754090664595385
epochs 23/101
Current Learning Rate: 6.779305879384596e-05
train_loss: 0.00201286837783348, val_loss: 0.0026868305032920073
epochs 24/101
Current Learning Rate: 6.779305879384596e-05
train_loss: 0.0020271620045318023, val_loss: 0.0026337605816060825
epochs 25/101
Current Learning Rate: 6.779305879384596e-05
train_loss: 0.0019160003287987293, val_loss: 0.002580820058322162
epochs 26/101
Current Learning Rate: 6.779305879384596e-05
train_loss: 0.0019413335086459196, val_loss: 0.0025357360985171955
epochs 27/101
Current Learning Rate: 6.779305879384596e-05
train_loss: 0.0021033273939361895, val_loss: 0.00250389248289158
epochs 28/101
Epoch 00028: reducing learning rate of group 0 to 2.4589e-05.
Current Learning Rate: 2.4589209982800497e-05
train_loss: 0.00205023684446994, val_loss: 0.002467569097120157
epochs 29/101
Current Learning Rate: 2.4589209982800497e-05
train_loss: 0.0018081211095896403, val_loss: 0.002460903592503792
epochs 30/101
Current Learning Rate: 2.4589209982800497e-05
train_loss: 0.0019367390212688693, val_loss: 0.0024563732731621712
epochs 31/101

[I 2024-01-30 19:39:59,016] Trial 4 pruned.

Current Learning Rate: 2.4589209982800497e-05
train_loss: 0.001810376611722045, val_loss: 0.002454340021358803
epochs 32/101
Starting fold 1:
epochs 1/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0013245764356964317, val_loss: 0.0032423678930311724
epochs 2/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0012336529946064968, val_loss: 0.0029772433383629298
epochs 3/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0010243387120059005, val_loss: 0.0027495962727775492
epochs 4/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0010536031962960566, val_loss: 0.002548256722370054
epochs 5/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0009266013140165198, val_loss: 0.002369428812199711
epochs 6/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0008767500546558662, val_loss: 0.002213288801223306
epochs 7/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0008877593787282853, val_loss: 0.002074085115319581
epochs 8/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.000750305183005127, val_loss: 0.001953300018040291
epochs 9/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0007819222884503879, val_loss: 0.001853849536264389
epochs 10/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0007538451504507592, val_loss: 0.0017726310673102036
epochs 11/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0007296476347715055, val_loss: 0.001703236480819421
epochs 12/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0006598042962171971, val_loss: 0.0016470997785704663
epochs 13/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0007094955782553083, val_loss: 0.0015989564696114963
epochs 14/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0006336690128113045, val_loss: 0.001560267399769848
epochs 15/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.000640675116569343, val_loss: 0.0015283215385381251
epochs 16/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005738435398119404, val_loss: 0.0015035580169063347
epochs 17/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0006279588886843014, val_loss: 0.001485358221101003
epochs 18/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005900327070297575, val_loss: 0.0014710156182344588
epochs 19/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005801552267879934, val_loss: 0.0014600179549435982
epochs 20/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005601910616142528, val_loss: 0.0014505409812690228
epochs 21/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005689562044081916, val_loss: 0.0014436737946530301
epochs 22/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005662783114913557, val_loss: 0.001436829293702936
epochs 23/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005305740714232486, val_loss: 0.0014299671119448567
epochs 24/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005189535456194886, val_loss: 0.0014225960107521454
epochs 25/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005916347748624455, val_loss: 0.0014178560652970903
epochs 26/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005033860804120961, val_loss: 0.0014158024699162327
epochs 27/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005374376784617964, val_loss: 0.0014114046354455352
epochs 28/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005429610291397886, val_loss: 0.001404709482726286
epochs 29/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005010391037151414, val_loss: 0.0013993601882941135
epochs 30/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005261975945598494, val_loss: 0.0013911212015608769
epochs 31/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005581452564863292, val_loss: 0.001385851341337286
epochs 32/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005312997947361222, val_loss: 0.0013776993907639442
epochs 33/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005289006828158898, val_loss: 0.0013700151603814293
epochs 34/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005283066077697042, val_loss: 0.001363128764852364
epochs 35/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004905947105726227, val_loss: 0.0013579459864462642
epochs 36/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00048167142009142, val_loss: 0.0013550847176543718
epochs 37/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0005009680284848927, val_loss: 0.0013513101034467578
epochs 38/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00046377287347384386, val_loss: 0.0013434134035527697
epochs 39/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00046408480863503526, val_loss: 0.001336977229189995
epochs 40/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004985262413117054, val_loss: 0.0013281960066816912
epochs 41/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004689504378659062, val_loss: 0.0013167843701984369
epochs 42/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004588536803279758, val_loss: 0.0013062367802448866
epochs 43/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.000425000198792029, val_loss: 0.0012972085041741757
epochs 44/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004811504710232839, val_loss: 0.0012886975901897396
epochs 45/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004579666816617215, val_loss: 0.0012799863583899827
epochs 46/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00043617654423302923, val_loss: 0.001268975282236983
epochs 47/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00047154438798315825, val_loss: 0.001258593263974901
epochs 48/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00046920276394015863, val_loss: 0.0012447910169145664
epochs 49/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004320154718650309, val_loss: 0.0012341785375071966
epochs 50/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00043951421945453864, val_loss: 0.001226838852898538
epochs 51/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00043229955067784575, val_loss: 0.0012229388802547608
epochs 52/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004463933601264695, val_loss: 0.0012199553695233865
epochs 53/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004022381934766216, val_loss: 0.0012182622672755902
epochs 54/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004062064813057843, val_loss: 0.0012166285049663018
epochs 55/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003955389002313543, val_loss: 0.0012170176385783605
epochs 56/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004057375401699621, val_loss: 0.0012199504159436506
epochs 57/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00041463137236668875, val_loss: 0.0012209144745529605
epochs 58/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00037880184367838264, val_loss: 0.001221494469160298
epochs 59/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003925958260783534, val_loss: 0.001218466347569437
epochs 60/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00041062663030492043, val_loss: 0.0012136232619889564
epochs 61/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004236280297750215, val_loss: 0.001208255098650365
epochs 62/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00036813003519598983, val_loss: 0.00119972207945976
epochs 63/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00039748306735418735, val_loss: 0.0011911187083035381
epochs 64/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003566412033059781, val_loss: 0.0011809431061101832
epochs 65/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003740706697020582, val_loss: 0.0011729290491005742
epochs 66/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0004094403448490132, val_loss: 0.0011653189623430274
epochs 67/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00034225849391843536, val_loss: 0.0011569380768046286
epochs 68/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00037653522066600424, val_loss: 0.001149445331840845
epochs 69/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003440912132837663, val_loss: 0.0011433624474900877
epochs 70/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00041068549969503165, val_loss: 0.00113444872455802
epochs 71/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00035460349141718135, val_loss: 0.001126416367167612
epochs 72/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003379498726357461, val_loss: 0.0011187961890033284
epochs 73/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003735985824421636, val_loss: 0.0011106593882826419
epochs 74/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003229432871816435, val_loss: 0.0011044444615469762
epochs 75/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00036385182205489594, val_loss: 0.001098020522496121
epochs 76/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00037610513184182837, val_loss: 0.001092909853372639
epochs 77/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0002970191182133644, val_loss: 0.0010910636212439005
epochs 78/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00033239105602995934, val_loss: 0.0010886760350013714
epochs 79/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003371822175961968, val_loss: 0.0010840502323055511
epochs 80/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003051528605283238, val_loss: 0.0010785465184155675
epochs 81/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.000317246126590027, val_loss: 0.0010771608189094526
epochs 82/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003446360678552944, val_loss: 0.0010737428073149184
epochs 83/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003376637213238466, val_loss: 0.0010641138176353667
epochs 84/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00030553196656431903, val_loss: 0.0010591804233309444
epochs 85/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00028984224841942225, val_loss: 0.0010537985654852091
epochs 86/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003068461543941674, val_loss: 0.0010486511493880283
epochs 87/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00028608799421865687, val_loss: 0.0010419442803751696
epochs 88/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00037189605125030015, val_loss: 0.0010339595580248103
epochs 89/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.0003203739452338165, val_loss: 0.0010273085413414432
epochs 90/122

[I 2024-01-30 19:40:03,562] Trial 5 pruned.

Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00032507766116300206, val_loss: 0.0010159241374201394
epochs 91/122
Current Learning Rate: 2.9617769438385444e-05
train_loss: 0.00030153953825662794, val_loss: 0.0010099391615118033
epochs 92/122
Starting fold 1:
epochs 1/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.03694701476120635, val_loss: 0.002114361825290693
epochs 2/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.002260395895542675, val_loss: 0.005241546815596324
epochs 3/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0032308350831858424, val_loss: 0.006372499442289746
epochs 4/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0034038781335479335, val_loss: 0.003000698787487905
epochs 5/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0020223718406142373, val_loss: 0.0016440836532243463
epochs 6/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001980378252061966, val_loss: 0.002031589365470662
epochs 7/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016249038573158414, val_loss: 0.0035858902317673835
epochs 8/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019583071680053282, val_loss: 0.004343158926410728
epochs 9/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0024502293880734787, val_loss: 0.003454175315151809
epochs 10/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.002023436462408618, val_loss: 0.0024153993165652666
epochs 11/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017671436708616582, val_loss: 0.0022209714897957547
epochs 12/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016853765419096148, val_loss: 0.002743511513385567
epochs 13/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016927184782137997, val_loss: 0.0034487490350055315
epochs 14/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0020242262987027826, val_loss: 0.0035252140252234995
epochs 15/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001981484845868851, val_loss: 0.0030144942535097322
epochs 16/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019498683028168191, val_loss: 0.002576918891266422
epochs 17/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016098211789013523, val_loss: 0.002512478689717316
epochs 18/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001643085435008336, val_loss: 0.002792835515546834
epochs 19/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019022974528764424, val_loss: 0.003084035492354324
epochs 20/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0018060837780419542, val_loss: 0.003094066411784047
epochs 21/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001882640471510393, val_loss: 0.002826510291982679
epochs 22/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001747140050620625, val_loss: 0.00273429684244865
epochs 23/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016475060856656024, val_loss: 0.0028643902922763672
epochs 24/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017404983353212868, val_loss: 0.0029767668117995734
epochs 25/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017355710531486883, val_loss: 0.002979581980662982
epochs 26/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001735241491175992, val_loss: 0.0028529613203043857
epochs 27/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017185539497356667, val_loss: 0.002780300850558671
epochs 28/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001741788840215457, val_loss: 0.002811716500208984
epochs 29/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016465775858561852, val_loss: 0.0028717536784131966
epochs 30/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017841322384284516, val_loss: 0.0029014160267752474
epochs 31/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017454343425159, val_loss: 0.002895383499673612
epochs 32/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016935323836821082, val_loss: 0.0028056263995711647
epochs 33/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016456927712026395, val_loss: 0.0027460744019311965
epochs 34/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016297001036276158, val_loss: 0.0028100396237316387
epochs 35/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017645183840374412, val_loss: 0.002888666425225517
epochs 36/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017602468393497954, val_loss: 0.0028968687783976
epochs 37/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017145359600698085, val_loss: 0.0028727284399176598
epochs 38/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017264292918537792, val_loss: 0.002808505110257852
epochs 39/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001665565038810631, val_loss: 0.0028007976549416385
epochs 40/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017279918752855768, val_loss: 0.002799798825031353
epochs 41/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016721594086112944, val_loss: 0.002830408838153792
epochs 42/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017313141767915927, val_loss: 0.0028102812138583178
epochs 43/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016166743025869915, val_loss: 0.0028189193588563258
epochs 44/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016913289902731777, val_loss: 0.002843120941342835
epochs 45/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016347796588793006, val_loss: 0.002836488336065991
epochs 46/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016770531380500056, val_loss: 0.0027711582277709294
epochs 47/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016411516392652533, val_loss: 0.0027479151403654624
epochs 48/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016033950580382034, val_loss: 0.0027717399123252896
epochs 49/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016656818144072435, val_loss: 0.0028323539241374763
epochs 50/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016509201965833964, val_loss: 0.0028553518772164665
epochs 51/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016763614386467165, val_loss: 0.002839620125654927
epochs 52/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0017089939927437195, val_loss: 0.002776965076687731
epochs 53/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016530469825834428, val_loss: 0.002712761729810308
epochs 54/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001585185544957456, val_loss: 0.002690560405546671
epochs 55/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016115999700942714, val_loss: 0.002732301370496985
epochs 56/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001611308235748622, val_loss: 0.00280076145501216
epochs 57/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001604093271797817, val_loss: 0.0028513979666284902
epochs 58/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0016944904499197084, val_loss: 0.0028403073551734447
epochs 59/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001660083409545845, val_loss: 0.002795590817369028
Starting fold 2:
epochs 1/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0036617578378949794, val_loss: 0.05418830215142517
epochs 2/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0025795078572220017, val_loss: 0.04155189256188731
epochs 3/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.00234582648356998, val_loss: 0.04426613789071482
epochs 4/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001933888723584762, val_loss: 0.04346634112495594
epochs 5/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0020202287859197384, val_loss: 0.04294011706397647
epochs 6/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0020437535969909074, val_loss: 0.04361067548709572
epochs 7/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001977840810768444, val_loss: 0.043739323893552104
epochs 8/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019428651284740988, val_loss: 0.043525182676536066
epochs 9/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019133067136940037, val_loss: 0.04308155232242176
epochs 10/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019552775435665707, val_loss: 0.04302119798761196
epochs 11/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001966165559916784, val_loss: 0.043310314338043256
epochs 12/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001909467720028534, val_loss: 0.043296989841909
epochs 13/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001936032221772976, val_loss: 0.04311389921518861
epochs 14/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001959682068428747, val_loss: 0.042992458772407004
epochs 15/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019340122033814878, val_loss: 0.04294969277485969
epochs 16/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019342608099906535, val_loss: 0.04294998573247718
epochs 17/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019048500758789893, val_loss: 0.04292332093236308
epochs 18/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001917188217688971, val_loss: 0.04279365118533846
epochs 19/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019373914892207782, val_loss: 0.04280114221194434
epochs 20/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019198867607871587, val_loss: 0.04289626927366332
epochs 21/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019117836600248174, val_loss: 0.042871635899972664
epochs 22/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019099808529653344, val_loss: 0.042765911569986395
epochs 23/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019142815104801218, val_loss: 0.042712210721912836
epochs 24/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019226156179436868, val_loss: 0.04269381821470917
epochs 25/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019100997394250613, val_loss: 0.04269809920399908
epochs 26/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019059301434468114, val_loss: 0.04268480997000422
epochs 27/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001915769868390266, val_loss: 0.04265410861089116
epochs 28/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001914221767304185, val_loss: 0.04266582054908944
epochs 29/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001911308464046204, val_loss: 0.042659909735438685
epochs 30/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001919965024750021, val_loss: 0.04265571342258857
epochs 31/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.0019021323442183888, val_loss: 0.04262162297569885
epochs 32/59
Current Learning Rate: 0.011578520726110155
train_loss: 0.001918252567959689, val_loss: 0.042566805565483354
epochs 33/59

[I 2024-01-30 19:40:10,053] Trial 6 pruned.

Starting fold 1:
epochs 1/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.004278762247658482, val_loss: 0.007743320151887558
epochs 2/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0042064275776379206, val_loss: 0.0076883140675447605
epochs 3/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.00417326354960862, val_loss: 0.007634174665091214
epochs 4/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.004180474162689949, val_loss: 0.007580663836388676
epochs 5/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.004127680663460571, val_loss: 0.00752760197415396
epochs 6/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.004068045338958894, val_loss: 0.007475042612188392
epochs 7/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003961900708657738, val_loss: 0.007423080469447153
epochs 8/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0039361342983810525, val_loss: 0.007371595129370689
epochs 9/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.00402932135682357, val_loss: 0.007320392255981763
epochs 10/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0038650237918390253, val_loss: 0.007269645868628113
epochs 11/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003975441859495875, val_loss: 0.007219296328171536
epochs 12/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003881338323270412, val_loss: 0.007169308865235912
epochs 13/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0039450522585722965, val_loss: 0.007119610940140707
epochs 14/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0038468564921793967, val_loss: 0.007070274333711024
epochs 15/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.00379942379720313, val_loss: 0.007021378277352563
epochs 16/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003706152841301733, val_loss: 0.0069728996604681015
epochs 17/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0036598741885666784, val_loss: 0.006924936064967403
epochs 18/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0037798117650182624, val_loss: 0.006877260144661974
epochs 19/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0036735125609036337, val_loss: 0.006829894665214751
epochs 20/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003715800452291181, val_loss: 0.006782851940779774
epochs 21/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003688673443455053, val_loss: 0.006736094373519774
epochs 22/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0036629228656621356, val_loss: 0.006689698159418724
epochs 23/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003480022465565095, val_loss: 0.0066438839529399515
epochs 24/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0036673453771264145, val_loss: 0.006598479183459723
epochs 25/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003464921866543591, val_loss: 0.006553576707288071
epochs 26/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003476991978670029, val_loss: 0.006509225194652875
epochs 27/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0034323296436157666, val_loss: 0.006465354244466181
epochs 28/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003381281058107944, val_loss: 0.006421908460281513
epochs 29/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0032639724521064443, val_loss: 0.0063790809363126755
epochs 30/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.003369109027430807, val_loss: 0.006336753325605834
epochs 31/54
Current Learning Rate: 1.0655902922558257e-05
train_loss: 0.0033051914559971344, val_loss: 0.006294877233880537
epochs 32/54

[I 2024-01-30 19:40:11,978] Trial 7 pruned.

Starting fold 1:
epochs 1/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.04851254138507341, val_loss: 0.1203857958316803
epochs 2/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.03550908109602077, val_loss: 0.002756176732613572
epochs 3/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0038626513250882883, val_loss: 0.006626950443855354
epochs 4/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0057358511478493085, val_loss: 0.001991601727370705
epochs 5/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.002475216443417594, val_loss: 0.0017772150957690819
epochs 6/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.00199610337057445, val_loss: 0.004724912711286119
epochs 7/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.003393723442537808, val_loss: 0.001699055071055357
epochs 8/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0019936470075902577, val_loss: 0.003930687422065863
epochs 9/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0029515284766124463, val_loss: 0.001820076780859381
epochs 10/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0020096558369818683, val_loss: 0.0035875711889405337
epochs 11/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0029228489980787824, val_loss: 0.0021936659052568886
epochs 12/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.002135950374481342, val_loss: 0.003042236319743097
epochs 13/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.002516858013481588, val_loss: 0.0023648404333341333
epochs 14/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0021156889272357436, val_loss: 0.0029085931102080004
epochs 15/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.002224234074176485, val_loss: 0.0024741662034232703
epochs 16/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0020743043617633366, val_loss: 0.0025771606347656678
epochs 17/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.002019722304861429, val_loss: 0.00270013083770339
epochs 18/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.002055647002003082, val_loss: 0.0025651254774337368
epochs 19/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.001953240941695281, val_loss: 0.002617474104876497
epochs 20/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0018898440179519209, val_loss: 0.002762223577259907
epochs 21/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0018731312640164488, val_loss: 0.0026204619373727056
epochs 22/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0018614143879140581, val_loss: 0.002602422476879188
epochs 23/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.001793581072170606, val_loss: 0.0027108891268393825
epochs 24/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0018513380613416972, val_loss: 0.0026069364310907467
epochs 25/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0017687870065473314, val_loss: 0.00257805542787537
epochs 26/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0017346394117339515, val_loss: 0.0026937593439860003
epochs 27/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0017687247272988316, val_loss: 0.0026514846000022124
epochs 28/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0017445897177247771, val_loss: 0.0025776476499491502
epochs 29/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0017036055685725603, val_loss: 0.0026234662675830933
epochs 30/82

[I 2024-01-30 19:40:14,971] Trial 8 pruned.

Current Learning Rate: 0.021796449278101208
train_loss: 0.0017301000390465273, val_loss: 0.002703821037097701
epochs 31/82
Current Learning Rate: 0.021796449278101208
train_loss: 0.0017547476847539656, val_loss: 0.0026252417592331767
epochs 32/82
Starting fold 1:
epochs 1/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0022969644118443523, val_loss: 0.0016333178708529367
epochs 2/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.002348963999017877, val_loss: 0.0016564469006548207
epochs 3/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0023165047490405605, val_loss: 0.0016819773281606593
epochs 4/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0022623565305318486, val_loss: 0.0017097124810023824
epochs 5/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0023502713565616623, val_loss: 0.0017379019878313153
epochs 6/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.002099663826122292, val_loss: 0.0017676032691111138
epochs 7/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0021981997234673287, val_loss: 0.0017971405433768052
epochs 8/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.002178254567307273, val_loss: 0.0018277038537826951
epochs 9/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.002154589175111859, val_loss: 0.0018581420816998514
epochs 10/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0020878888789172237, val_loss: 0.0018894144270147773
epochs 11/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.002126743285426576, val_loss: 0.0019213166304989644
epochs 12/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.002136243986866535, val_loss: 0.0019511888806139016
epochs 13/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0020959028762789736, val_loss: 0.0019813954030045325
epochs 14/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0019554553783229112, val_loss: 0.002011729052312495
epochs 15/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0019929724053087596, val_loss: 0.002040107732191534
epochs 16/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0019575494160802153, val_loss: 0.002066652491478072
epochs 17/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0020932833840274006, val_loss: 0.0020907582874069848
epochs 18/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0018273238140146101, val_loss: 0.002112580091869902
epochs 19/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0020528763650585653, val_loss: 0.0021309803465440398
epochs 20/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0019890056579912963, val_loss: 0.0021509441144261805
epochs 21/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.001855573004975572, val_loss: 0.002169969107767212
epochs 22/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0019556850164295417, val_loss: 0.0021864948281463945
epochs 23/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0019250769169670285, val_loss: 0.002202913457978635
epochs 24/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0019791156508481914, val_loss: 0.0022182765029673834
epochs 25/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0020173325330496913, val_loss: 0.0022336394033609106
epochs 26/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0016752168738381251, val_loss: 0.0022480442430750126
epochs 27/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0018971945954131355, val_loss: 0.0022630630387178077
epochs 28/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0019080160164249766, val_loss: 0.002276383246579725
epochs 29/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0018023516526323204, val_loss: 0.0022879366731522457
epochs 30/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.001986521412005746, val_loss: 0.002297145391662886
epochs 31/77
Current Learning Rate: 1.3239840121443326e-05
train_loss: 0.0018746551204362491, val_loss: 0.002306185323663706
epochs 32/77

[I 2024-01-30 19:40:17,020] Trial 9 pruned.

Number of finished trials: 10
Best trial:
Value: 0.0018078895155108786
Params:
batch_size: 79
epochs: 146
hidden_size: 19
learning_rate: 0.005264885042493901
dropout_prob: 0.006817452931502488
weight_decay: 4.962885626360071e-06
lr_step_size: 82
gamma: 0.669249506127128
num_layers: 1

In [196]:
trainer = ModelActioner(train_data, test_data, device)
model = trainer.train(trial.params)

epochs 1/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.042051912890285634
epochs 2/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.11772229324427273
epochs 3/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.013476292284755323
epochs 4/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.009513833764468686
epochs 5/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.012804523314911428
epochs 6/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.012513080775934694
epochs 7/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.005885409727286945
epochs 8/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00552271578290668
epochs 9/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0056307782199529165
epochs 10/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.006228975722841131
epochs 11/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.004758685928490423
epochs 12/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.004954490025778043
epochs 13/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.002982111587978916
epochs 14/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.002646189801356989
epochs 15/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0016338318752510564
epochs 16/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.001500172277431451
epochs 17/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0012756364685324296
epochs 18/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0010304702358873712
epochs 19/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.001027480222601218
epochs 20/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0011192638510356078
epochs 21/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0015211347535551045
epochs 22/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0012372537990373
epochs 23/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0009906353086573153
epochs 24/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.001305637898673365
epochs 25/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0011033538910626979
epochs 26/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0012121090569686235
epochs 27/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0011217114841129572
epochs 28/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0006839219803395189
epochs 29/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008638472654518265
epochs 30/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0011235289401805544
epochs 31/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008730341041345756
epochs 32/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0016696006189908684
epochs 33/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0018605633787138979
epochs 34/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0012950981972984753
epochs 35/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0018977131739685452
epochs 36/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.003618338880321987
epochs 37/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.002481078629541962
epochs 38/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.005158553404106845
epochs 39/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.001617469013315248
epochs 40/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0019462299310101714
epochs 41/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008703543783815799
epochs 42/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000999041314986596
epochs 43/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008171981421739297
epochs 44/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008028026648165273
epochs 45/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007224863360798507
epochs 46/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007320013628502803
epochs 47/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005396523429114179
epochs 48/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000663025957972759
epochs 49/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0006840000484863887
epochs 50/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005582348963077537
epochs 51/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0006176769970682868
epochs 52/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000589276886276392
epochs 53/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005141881622062762
epochs 54/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005642644529839124
epochs 55/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007134911383575009
epochs 56/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0009309835681852799
epochs 57/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007248897557654561
epochs 58/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007544347507961706
epochs 59/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0015538409295505209
epochs 60/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0022704895777963226
epochs 61/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0014540443997632707
epochs 62/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.001238963850617454
epochs 63/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.003974794995451001
epochs 64/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.002921710258589787
epochs 65/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0018667910429202882
epochs 66/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0028531705738314003
epochs 67/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0006602936655671196
epochs 68/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0012145897207075488
epochs 69/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0013756555521764304
epochs 70/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008717559218777975
epochs 71/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0018248102054336326
epochs 72/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0006040536551218324
epochs 73/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0011069647011876368
epochs 74/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0009369569011073609
epochs 75/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0006095401781376776
epochs 76/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008189339142834813
epochs 77/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0006647127004810055
epochs 78/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005208509524610808
epochs 79/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005853119670705242
epochs 80/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005388819400309831
epochs 81/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005285554858258442
epochs 82/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005379581034936356
epochs 83/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007695357022985984
epochs 84/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000766935750029495
epochs 85/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000545391576189116
epochs 86/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0010949156806206266
epochs 87/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0015781213097337897
epochs 88/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008207912084114192
epochs 89/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0010303141506920088
epochs 90/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0021832326413896387
epochs 91/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0027166172435367686
epochs 92/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0011259787935788727
epochs 93/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0015614417916030975
epochs 94/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00390935834945438
epochs 95/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.001738666682498989
epochs 96/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0019075863258600325
epochs 97/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0010976048672339974
epochs 98/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005621581387066073
epochs 99/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0011904237036798907
epochs 100/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0009861060865002885
epochs 101/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000832956923697029
epochs 102/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0011729037052221464
epochs 103/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005291668180989652
epochs 104/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007926785136639173
epochs 105/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0009708925354702702
epochs 106/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005409354414526242
epochs 107/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007844965955337903
epochs 108/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0006881448082930495
epochs 109/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005051783343601668
epochs 110/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007785468784277328
epochs 111/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007595486009810407
epochs 112/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0004456281576470763
epochs 113/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005334693443792716
epochs 114/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007906045309793089
epochs 115/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000814166666090074
epochs 116/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005449481157203654
epochs 117/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0008954306101038773
epochs 118/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0014155938097038347
epochs 119/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0010571688194123264
epochs 120/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0009217772271347208
epochs 121/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.002220019017459542
epochs 122/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.002116113465170618
epochs 123/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0009113146525772805
epochs 124/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0016422557006377239
epochs 125/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.003966321492857927
epochs 126/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.001628990548340776
epochs 127/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0023561068750135314
epochs 128/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0016534954981736343
epochs 129/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0007104719229353313
epochs 130/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0016062037902884185
epochs 131/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0014386367618971984
epochs 132/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000691782252814073
epochs 133/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000992810577351604
epochs 134/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0004404977750120836
epochs 135/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005544273740530428
epochs 136/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005126038930734768
epochs 137/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000342957933884912
epochs 138/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0003929755843097307
epochs 139/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00044406013532376557
epochs 140/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00047445388511848936
epochs 141/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00043318517836778
epochs 142/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0004585846271153051
epochs 143/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.0005138231611161622
epochs 144/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00047517886104155537
epochs 145/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.00036603388468717485
epochs 146/146
Current Learning Rate: 0.005264885042493901
train_loss: 0.000530462474135286

In [197]:
preds = trainer.test(trial.params)
preds = np.array(preds)

y_true = y_test[time_step:]
y_true = scaler_adj.inverse_transform(y_true.reshape(-1, 1)).flatten()
preds = scaler_adj.inverse_transform(preds.reshape(-1, 1)).flatten()


mse = mean_squared_error(y_true, preds)
print(f'Mean Squared Error: {mse:.4f}')

rmse = mean_squared_error(y_true, preds, squared=False)
print(f'Root Mean Squared Error: {rmse:.4f}')

r2 = r2_score(y_true, preds)
print(f'R² Score: {r2:.4f}')

mape = mean_absolute_percentage_error(y_true, preds)*100
print(f'mape Score: % {mape:.4f}')

test_loss: 0.0003615064952064276
Mean Squared Error: 7.6885
Root Mean Squared Error: 2.7728
R² Score: 0.9643
mape Score: % 1.2525

In [198]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325638
1    141.737747
2    141.071472
3    143.159821
4    145.118835
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [199]:
signals = pd.DataFrame(preds, columns=['pred'])
signals["next_day"] = pd.DataFrame(y_true)
signals["today"] = stock_price
signals["Signal_Pred"] = (signals["today"] < signals["pred"]).astype(int)
signals["Signal_True"] = (signals["today"] < signals["next_day"]).astype(int)

signals.head(50)

          pred    next_day       today  Signal_Pred  Signal_True
0   139.679611  141.737747  140.325638            0            1
1   140.726303  141.071472  141.737747            0            0
2   140.330124  143.159821  141.071472            0            1
3   142.777252  145.118835  143.159821            0            1
4   144.669281  142.205139  145.118835            0            0
5   141.670776  143.487976  142.205139            0            1
6   143.577530  144.621613  143.487976            1            1
7   145.194702  149.981674  144.621613            1            1
8   149.650391  153.641205  149.981674            0            1
9   152.306702  150.886612  153.641205            0            0
10  149.629639  153.790390  150.886612            0            1
11  152.677673  151.075577  153.790390            0            0
12  150.563263  150.031387  151.075577            0            0
13  150.551544  150.399902  150.031387            1            1
14  151.294312  153.228439  150.399902            1            1
15  153.668716  152.581055  153.228439            1            0
16  153.221146  154.702454  152.581055            1            1
17  155.486282  153.089005  154.702454            1            0
18  154.304230  151.933685  153.089005            1            0
19  153.853271  147.880127  151.933685            1            0
20  150.202347  148.308395  147.880127            1            1
21  150.550522  148.796417  148.308395            1            1
22  150.282837  146.117279  148.796417            1            0
23  146.937347  147.322388  146.117279            1            1
24  148.104492  146.814453  147.322388            1            0
25  147.485901  144.722931  146.814453            1            0
26  145.452087  145.320511  144.722931            1            1
27  146.197983  150.419815  145.320511            1            1
28  151.056671  153.208511  150.419815            1            1
29  153.186234  150.987534  153.208511            0            0
30  151.362442  152.252396  150.987534            1            1
31  153.261246  149.981598  152.252396            1            0
32  150.978424  147.900040  149.981598            1            0
33  149.155380  149.862076  147.900040            1            1
34  150.937134  151.973526  149.862076            1            1
35  152.388397  152.371902  151.973526            1            1
36  152.711487  155.220352  152.371902            1            1
37  155.562180  154.373779  155.220352            1            0
38  154.830475  156.764099  154.373779            1            1
39  157.387024  158.636490  156.764099            1            1
40  158.998993  157.192368  158.636490            1            0
41  157.599457  158.287903  157.192368            1            1
42  158.851227  159.602570  158.287903            1            1
43  159.884232  157.640533  159.602570            1            0
44  157.878143  157.013077  157.640533            1            0
45  157.931702  160.120499  157.013077            1            1
46  161.253632  161.704056  160.120499            1            1
47  162.661407  164.233795  161.704056            1            1
48  164.941742  165.498672  164.233795            1            1
49  166.154922  164.960846  165.498672            1            0

In [200]:
signals["Signal_Pred"].value_counts()

Signal_Pred
0    158
1     93
Name: count, dtype: int64

In [201]:
signals["Date"] = date_test
signals

           pred    next_day       today  Signal_Pred  Signal_True       Date
0    139.679611  141.737747  140.325638            0            1 2023-01-23
1    140.726303  141.071472  141.737747            0            0 2023-01-24
2    140.330124  143.159821  141.071472            0            1 2023-01-25
3    142.777252  145.118835  143.159821            0            1 2023-01-26
4    144.669281  142.205139  145.118835            0            0 2023-01-27
..          ...         ...         ...          ...          ...        ...
246  179.860428  182.679993  183.630005            0            0 2024-01-16
247  178.770111  188.630005  182.679993            0            1 2024-01-17
248  185.437347  191.559998  188.630005            0            1 2024-01-18
249  187.416367  193.889999  191.559998            0            1 2024-01-19
250  189.927139  195.179993  193.889999            0            1 2024-01-22

[251 rows x 6 columns]

In [202]:
stock_price = stock_data["Adj Close"].iloc[test_index:]
stock_price=stock_price.reset_index()
stock_price=stock_price.drop(columns=["index"])
stock_price

      Adj Close
0    140.325638
1    141.737747
2    141.071472
3    143.159821
4    145.118835
..          ...
247  182.679993
248  188.630005
249  191.559998
250  193.889999
251  195.179993

[252 rows x 1 columns]

In [203]:
date_test["Date"] = date_test["Date"].dt.strftime('%Y-%m-%d')
date_test

           Date
0    2023-01-23
1    2023-01-24
2    2023-01-25
3    2023-01-26
4    2023-01-27
..          ...
247  2024-01-17
248  2024-01-18
249  2024-01-19
250  2024-01-22
251  2024-01-23

[252 rows x 1 columns]

In [204]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=np.array(date_test).flatten(), y=stock_data["Adj Close"].iloc[test_index:], mode='lines', name='TSLA Stock Price'))

# Buy and sell signals
buy_signals = signals[signals['Signal_Pred'] == 1]
sell_signals = signals[signals['Signal_Pred'] == 0]

# Ensure that buy and sell prices are aligned with the signals by matching on the 'Date' column
buy_prices = stock_data[stock_data['Date'].isin(buy_signals['Date'])]["Adj Close"]
sell_prices = stock_data[stock_data['Date'].isin(sell_signals['Date'])]["Adj Close"]


# Plot buy signals
fig.add_trace(go.Scatter(
    x=buy_signals['Date'], 
    y=buy_prices, 
    mode='markers', 
    name='Buy', 
    marker=dict(color='green', size=10, symbol='triangle-up')
))


# Plot sell signals
fig.add_trace(go.Scatter(
    x=sell_signals['Date'], 
    y=sell_prices, 
    mode='markers', 
    name='Sell', 
    marker=dict(color='red', size=10, symbol='triangle-down')
))


# Update layout
fig.update_layout(
    title='Stock Price with Buy and Sell Signals',
    xaxis_title='Date',
    yaxis_title='Price',
    xaxis_rangeslider_visible=False,
    height = 700,
    width=1280
)

# Show the plot
pyo.iplot(fig)

/home/arda/anaconda3/lib/python3.11/site-packages/_plotly_utils/basevalidators.py:106: FutureWarning:

The behavior of DatetimeProperties.to_pydatetime is deprecated, in a future version this will return a Series containing python datetime objects instead of an ndarray. To retain the old behavior, call `np.array` on the result

In [205]:
trace_pred = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['pred'],
    mode='lines+markers',
    name='Predicted'
)

trace_true = go.Scatter(
    x=np.array(date_test).flatten(),
    y=signals['next_day'],
    mode='lines+markers',
    name='Actual Next Day'
)

# Define the layout
layout = go.Layout(
    title='Predicted vs Actual Next Day Values',
    xaxis=dict(title='Index'),
    yaxis=dict(title='Value'),
    height=700
)

# Create the figure and add traces
fig = go.Figure(data=[trace_pred, trace_true], layout=layout)

# Show the figure
fig.show()